### ISSUE TITLE
[firebase_dynamic_links] getDynamicLink(url) does not resolve short links with custom domain on iOS

### ISSUE THREAD

**Issue by davidmigloz** [FirebaseExtended/flutterfire#10059]
The current firebase_dynamic_links SDK exposes the following method to get a dynamic link from a given URL:
- [`getDynamicLink(url)`](https://pub.dev/documentation/firebase_dynamic_links/latest/firebase_dynamic_links/FirebaseDynamicLinks/getDynamicLink.html)

Which in iOS calls [handleUniversalLink(_:completion:)](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Classes/DynamicLinks#/c:objc(cs)FIRDynamicLinks(im)handleUniversalLink:completion:) under the hood.

However, that method from the iOS SDK is not able to resolve a **short** dynamic link. If you try, you get the following exception:
```
The operation couldn’t be completed. Universal link URL could not be parsed by Dynamic Links.
```

For that the iOS SDK provides a specific method:
- [resolveShortLink(_:completion:)](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Classes/DynamicLinks#/c:objc(cs)FIRDynamicLinks(im)resolveShortLink:completion:)

Would it be possible to expose this method?

**Comment by Lyokone** [comment]
@davidmigloz according to documentation:
```
Convenience method to handle a Universal Link whether it is long or short.
``` 

Are you sure your URL is properly formed?

**Comment by davidmigloz** [comment]
Actually, the long version doesn't work either in iOS:
```
final dynamicLink = await FirebaseDynamicLinks.instance.getDynamicLink(
  Uri.parse('https://app.dev.brxs.com/referral/?link=https://app.dev.brxs.com/referrals-invitation?referralCode%3D7F1E4C6%26referralName%3DDavid%26shareId%3D743f811c-eacc-4172-a280-1f0175b49b0c&apn=com.brxs.test&isi=6443703266&ibi=com.brxs.test&st=Invest+in+BRXS+with+me!&sd=Easily+invest+in+real+estate.&si=https://assets-global.website-files.com/6182ab7c3f9983c2bc2a8485/61a6bb0b2bd3b47420db2bce_Brxs_WebThumbnail.png&utm_campaign=referrals&utm_medium=referrals&utm_source=app&ct=referrals'),
);
```

Android:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/6546265/206234323-2791b01a-51d1-4f32-9aa9-61471b1e3206.png">

iOS:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/6546265/206234566-5074c37c-c85f-49d9-a680-e4f7127571c0.png">

(Firebase is properly configured in the iOS app. As the app is also generating the short dynamic links and the generation is workibg fine in both Android and iOS).

**Comment by Lyokone** [comment]
It might be, I'll check this

**Comment by Lyokone** [comment]
I cannot reproduce this bug on iOS. Can you try without specifying a custom domain?

**Comment by davidmigloz** [comment]
Indeed, it seems to be related to custom domains.

I tried with:
```dart
final dynamicLink = await FirebaseDynamicLinks.instance.getDynamicLink(
  Uri.parse('https://brxsstage.page.link/zNHN43nUAyfqJbfYA'),
);
```

And it worked fine on both platforms.

Android:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/6546265/206424979-db17c25d-f28e-443a-aa48-b2fcb1828047.png">

iOS:
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/6546265/206425470-67420022-4196-4f5b-86b7-1d7dceda7f41.png">

**Comment by davidmigloz** [comment]
Sorry, the exception was caused because I was missing `https://` in the custom domain specified in `FirebaseDynamicLinksCustomDomains`.

Before:
```
<key>FirebaseDynamicLinksCustomDomains</key>
<array>
    <string>app.dev.brxs.com/referral</string>
</array>
```

After:
```
<key>FirebaseDynamicLinksCustomDomains</key>
<array>
    <string>https://app.dev.brxs.com/referral</string>
</array>
```

Now an exception is not thrown anymore, but I still get `null` when calling `getDynamicLink()`.

```dart
final dynamicLink = await FirebaseDynamicLinks.instance.getDynamicLink(
  Uri.parse('https://app.dev.brxs.com/referral/NJFFkPY6f3Ft16Xc8'),
);
```
<img width="247" alt="image" src="https://user-images.githubusercontent.com/6546265/206442299-3420cfc9-92c8-4b33-b1c6-7be6caf59cd5.png">
