### ISSUE TITLE
[firebase_analytics] handle nested json in event params

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1036]
Calling [`logEvent`](https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/lib/firebase_analytics.dart#L43) with parameters throws unless the map values are [primitives](https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java#L154
) and non-null.

It should accept arbitrary JSON and flatten the map for me.

The guardrails around reserved event names are nice.  It would be nice to have more, say, [Error 5 = too many keys](https://firebase.google.com/docs/analytics/errors).

**Comment by kroikie** [comment]
@mockturtl

The issue at https://github.com/flutter/flutter/issues/34645 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Landing in #4394
