### ISSUE TITLE
SSV

### ISSUE THREAD

**Issue by BibyChacko** [FirebaseExtended/flutterfire#104]
Please add the features for server-side verification and the callbacks

**Comment by Ehesp** [comment]
Hello @BibyChacko please can you provide some more information? Is this possible with the Firebase SDKs?

Due to the age of the issue I'm going to close it. Please let me know with some more information about this FR and I can get it re-opened.

**Comment by Ehesp** [comment]
Closed via https://github.com/FirebaseExtended/flutterfire/pull/173
