### ISSUE TITLE
[firebase_messaging] D8: Program type already present

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1043]
## Steps to Reproduce

For new project add   in pubspcec.yml
  camera: ^0.5.4+1
  firebase_messaging: ^5.1.4

## Logs
```
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
...
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
```
```

<!-- If possible, paste the output of running `flutter doctor -v` here. -->
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.678], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\Projects\Flutter\Flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Greg\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\Greg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Redmi 3 • ea9c5b827cf3 • android-arm64 • Android 5.1.1 (API 22)

• No issues found!

```

**Comment by kroikie** [comment]
@jaworskig

The issue at https://github.com/flutter/flutter/issues/39969 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@jaworskig did you manage to fix by migrating to AndroidX as in https://github.com/flutter/flutter/issues/39969#issuecomment-532518030?

**Comment by jaworskig** [comment]
Not exactly after migrate to AndroidX I still have versioning issues, after
many experiments with versions in results I get working verson with
firebase_messaging: 5.1.2
and
camera: 0.5.4+1

pon., 21 paź 2019 o 15:44 Stanislav Bondarenko <notifications@github.com>
napisał(a):

**Comment by BondarenkoStas** [comment]
do you still use v1.7.8+hotfix.4 or it's with v1.9.1+hotfix.5?

**Comment by jaworskig** [comment]
v1.9.1+hotfix.5

pon., 21 paź 2019 o 15:55 Stanislav Bondarenko <notifications@github.com>
napisał(a):

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
