### ISSUE TITLE
[firebase_messaging] and sqflite

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1044]
I try to send a message from my website to users with Firebase and store the message in the user device with sqflite plugin.

When the application in the foreground, everything works good and message insert in the database. But when the application in the background or completely close it just displays notification and data not inserted in the database.

edit:

After setting click_action for notification, Clicking on the notification data will be saved but if the user dismisses notification data lost.

code

```
final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

@override
void initState() {
    prepareFirebaseCloudMessaging();
    super.initState();
 }
void prepareFirebaseCloudMessaging() {
    if (Platform.isIOS) IOSPermission();
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        notificationDataHandler(message);
      },
      onResume: (Map<String, dynamic> message) async {
        notificationDataHandler(message);
      },
      onLaunch: (Map<String, dynamic> message) async {
        notificationDataHandler(message);
      },
    );
  }

void notificationDataHandler(Map<String, dynamic> message) async {
    try {
    var databasesPath = await getDatabasesPath();
    String path = join(databasesPath, 'MY_DATABASE_FILE.db');
    Database database = await openDatabase(path, version: 1,
        onCreate: (Database db, int version) async {
      await db.execute(
          'CREATE TABLE Messages (id INTEGER PRIMARY KEY, message TEXT, date TEXT, seen INTEGER)');
    });
    Message messageStore = Message(
        null, message["data"]["message"], message["data"]["date"], false);
      await database.insert("Messages", messageStore.toMap());
    database.close();
    }catch(e){
      debugPrint(e.toString());
    }
  }
```

How Can call dart code after receive notification without user click on it?

**Comment by kroikie** [comment]
@mhd-barikhan

The issue at https://github.com/flutter/flutter/issues/39889 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/1041

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. It now supports background notification handling for iOS & Android.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
