### ISSUE TITLE
[firebase_messaging] not show when app close in some device

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1046]
#37081 

I have a problem with my app, I use Firebase Messaging plugin and found there is no notification that I get only when my app closed (terminated). for some reason, I can't get a notification in a few devices.

Tested Devices:
1. Asus Zenfone 5 (Model: ASUS_X00QD) **Not work**
2. Asus Zenfone 5 (Model: ASUS_Z01FD) **Not Work**
3. Redmi Note 7 **Work**
4. Redmi 6 **Work**
5. Huawei Nova 3i **Work**
6. Samsung Galaxy S7 **Work**
7. Emulator Pixel 2 Api 27 **Work**
8. ASUS Zenfone 3 (Model: ASUS_Z017DB) **Not Work**

 Steps to Reproduce

1. Install App
2. Close App
3. Send a notification from firebase console
4. Get notification only in few devices

## Logs
no logs

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.37.0)
[√] Connected device (1 available)
```

**Comment by kroikie** [comment]
@mukhtarfauzi

The issue at https://github.com/flutter/flutter/issues/38505 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by georgesitoniv** [comment]
are there any updates on this?

**Comment by mukhtarfauzi** [comment]
@georgesitoniv check your android device is it any program that has block notification like notification manager.
the reason why my ASUS didn't get a notification is that there a "Mobile Manager" apps somehow blocking some app notification.

**Comment by Ehesp** [comment]
Hello - going to close this one as there's not much information to go by. If notifications are not displaying on a particular platform, please check the device settings.
