### ISSUE TITLE
[firebase_messaging] iOS notifications only working while in foreground.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1048]
After implementation of firebase_messaging with the official documentation and adding the configuration functions with this guide : https://medium.com/flutterpub/enabling-firebase-cloud-messaging-push-notifications-with-flutter-39b08f2ed723 .
onMessage, onResume and onLaunch output also only shows, while app is in foreground. If not in foreground, the notification will be returned as soon as the app is again in foreground. Also linked all onMessage, onResume and onLaunch with the local_notifications plugin. As with the Log Output, notifications only appear while app is in foreground.

Has anyone experienced a similar issue or/and can please help me?

**Comment by kroikie** [comment]
@Klingens13

The issue at https://github.com/flutter/flutter/issues/38336 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Klingens13** [comment]
Hey,
for me it worked to just swap out the licenses in “Project Settings > Cloud Messaging” in the Firebase Console from the AuthKey file to the APNS certificate (dev. and prod.) files. (Generate them here : http://bit.ly/2OM83l4) At least for me, it wasn’t the fault of the code not functioning, but it just won’t work with the AuthKey file. Hope that helps! 

(https://imgur.com/a/i9OoblF)

**Comment by BondarenkoStas** [comment]
Good, I think it's safe to close the issue, thank you!

**Comment by anhdt-eas** [comment]
Sorry, it's still not working although I already changed to APNs certificate in Firebase Console.
Any help?

**Comment by mubashirbashir** [comment]
i tried many things but was not not able to make push notification work on ios 13.5.1. I followed the official documentation and uploaded the build on test flight. Strangely i start receiving push notification on resume, on launch as well as on message. Also working fine with local notification plugin.

**Comment by RafaelR7** [comment]
Any news about this issue?
I got the same problem, I have the the APNs certificate in Firebase, but still only can get the notification when the app in the foreground. I only tested on the IOS simulador, does anyone know if the problem happen also on a physical iphone?

**Comment by Klingens13** [comment]
> Any news about this issue?
> I got the same problem, I have the the APNs certificate in Firebase, but still only can get the notification when the app in the foreground. I only tested on the IOS simulador, does anyone know if the problem happens also on a physical iphone?

iOS Notifications aren't supported on simulators, but they should work on a physical device.

**Comment by RafaelR7** [comment]
@Klingens13, I tested on a physical device and the notification isn't woking when the app is in the foreground (the opposite of the iOS simulator).

**Comment by Klingens13** [comment]
@RafaelR7 I also have this issue. I’m just using flutter_local_notifications to display any received in the foreground...
