### ISSUE TITLE
[firebase_messaging] iOS onMessage inconsistency

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1049]
The message in ios comes in this form
{gcm.message_id: 1565547628558818, thread_id: -LlwL2xHCWRXSCuFIJ3U, google.c.a.e: 1, aps: {alert: {title: abcd, body: abcd}, category: /*Package */_TARGET_NOTIFICATION}}

please look at aps and alert which different from notification on the android side

**Comment by kroikie** [comment]
@dvird

The issue at https://github.com/flutter/flutter/issues/38206 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
