### ISSUE TITLE
Gradle Build failing after adding firebase_messaging plugin

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1050]
when adding the firebase_messaging: ^5.1.2 my app doesn't build, after removing it, the app builds with no problems, I tried to migrate to androidX but this didn't help, also tries to use multi dex, didn't help

I only get one red error line that says: Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by ssghazaryan** [comment]
hi guys can someone help me. i get the same error after adding firebase_messaging, cant make release apk, if i delate firebase_messaging all works fine.
this is my app/build.gradle
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
//if (flutterRoot == null) {
//    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
//}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }


    defaultConfig {
        applicationId "auto.procontext.ru"
        minSdkVersion 18
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionCode 2032
        versionName "4.2"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
//        debug {
//            keyAlias keystoreProperties['keyAlias']
//            keyPassword props['keystore.password']
//            storeFile file(props['keystore'])
//            storePassword props['keystoqre.password']
//        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
              minifyEnabled true
              useProguard true

              proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

apply plugin: 'com.android.application'

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.android.support:multidex:2.0.0' //1.0.3
    implementation 'com.google.firebase:firebase-core:17.2.1'
    implementation "com.google.firebase:firebase-analytics:17.2.1"
    implementation "com.google.firebase:firebase-messaging:20.1.0"
//
//    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
//    implementation 'com.facebook.android:facebook-core:[4,5)'
//    implementation 'com.facebook.android:facebook-marketing:[4,5)'
}

apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
`
this is build.gradle 
`buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.26.1'

    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.0.2"
            }
        }
    }
}`

this is  pubspec.yaml.gradle
`name: auto
description: A new Flutter application.

version: 1.0.0+1

#environment:
#  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # add this
    sdk: flutter # add this

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  url_launcher: ^5.4.1
  #  http_logger: ^1.0.0
  #  http_middleware: ^1.0.0
  date_range_picker: ^1.0.6
  date_format: ^1.0.8
  ##  flutter_svg: ^0.13.0+2
  expandable: ^4.1.2
  animated_text_kit: ^2.0.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_masked_text: ^0.8.0
  flutter_secure_storage: ^3.3.1+1
  charts_flutter: ^0.8.1
  flutter_icons: ^1.0.0+1
  #  flutter_advanced_networkimage: any
  toast: ^0.1.5
  intl: ^0.16.0
  cached_network_image: ^2.0.0-rc
  dio: ^3.0.8
  flutter_spinkit: ^4.1.1+1
#  firebase_dynamic_links: ^0.5.0+9
  flushbar: ^1.9.1
  flutter_speed_dial: ^1.2.5
  dart_random_choice: ^0.0.2
  flutter_pagewise: ^1.2.3
  flutter_cache_manager: ^1.1.3
  firebase_analytics: ^5.0.11
  shared_preferences: ^0.5.6+1
  fl_chart: ^0.8.1
  appmetrica_sdk: ^0.0.5
  percent_indicator: ^2.1.1+1
  month_picker_dialog: ^0.3.1
  bezier_chart: ^1.0.16
  zoom_widget: ^0.1.3
  network_to_file_image: ^2.2.4
  passcode_screen: ^1.0.2
  shimmer: ^1.0.1
  flutter_calendar_carousel: ^1.4.10
  oktoast: ^2.3.1
  flutter_swiper: ^1.1.6
  local_auth: ^0.6.1
  flutter_svg: ^0.17.1
  dynamic_theme: ^1.0.1
  syncfusion_flutter_charts: ^17.4.46
  package_info: ^0.4.0+13
  firebase_crashlytics: ^0.1.2+5
  flare_flutter: ^2.0.1
  path_provider: ^1.6.0
#  connectivity: ^0.4.6+2
#  connectivity_macos: ^0.0.2+1
#  connectivity: ^0.4.6+2
#  connectivity_macos: ^0.0.2+1
  meet_network_image: ^0.1.2
  foundation_fluttify: ^0.4.6
#  flutter_local_notifications: ^1.1.6
  overlay_support: ^1.0.2
  auto_animated: ^2.0.1
  permission_handler: ^4.2.0+hotfix.3
  downloads_path_provider: ^0.1.0
  open_file: ^3.0.1
  flutter_downloader: ^1.4.1
  device_info: ^0.4.1+4
  firebase_messaging: ^6.0.9


#  open_file: ^3.0.1
#dependency_overrides:
#  flutter_icons: ^0.3.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.9.4
#dependency_overrides:
#  intl: ^0.16.0


flutter:

  uses-material-design: true

  assets:
    - image/
    - assets/
 `

**Comment by R4yGM** [comment]
i have the same problem, is there any solution?
