### ISSUE TITLE
[firebase_messaging] Proposal: Way to avoid pushing same route twice

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1052]
## Use case

We are building an app that has several chat conversations. When the user presses a notification we want the app to open with the conversation open corresponding to the notification tapped.

The closes we have come to getting this working is something like the following:

```dart
_firebaseMessaging.configure(
  onMessage: (message) async {},
  onLaunch: (message) async {
    if (message.containsKey('threadId') && message.containsKey('messageId')) {
      navigatorKey.currentState.pushNamedAndRemoveUntil('/thread', (Route<dynamic> route) => route.isFirst, arguments: message);
    }
  },
  onResume: (message) async {
    if (message.containsKey('threadId') && message.containsKey('messageId')) {
      navigatorKey.currentState.pushNamedAndRemoveUntil('/thread', (Route<dynamic> route) => route.isFirst, arguments: message);
    }
  },
);
```

This makes sure that the navigation stack is being reset to the start page, and then pushes in the page showing the conversation.

The only small problem is if the app is already open with the same conversation that the notification is trying to open. The current page will reload which makes images briefly flash, the scroll position will be lost, and other small glitches.

## Proposal

It would be great if we could either 1) inspect the current state of the navigator, so that we can determine wether the target page is already open or not, or if we could 2) expose an option that tells the navigator to not replace the current page if the new pages name and arguments matches.

I would be happy to discuss any ideas on how this could look, and help with an implementation!

**Comment by kroikie** [comment]
@LinusU

The issue at https://github.com/flutter/flutter/issues/37304 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. We now have one API `onMessageOpenedApp` to listen to open events, and a `getInitialMessage` API that can be used during app startup to check for an initial message to trigger routing with.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
