### ISSUE TITLE
iOS: Firebase Messaging is not calling onMessage when sending a data only message.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1053]
Hi,
When the app is in the background, and I'm sending a data only message firebase_messaging is calling onResume callback, and when I resume/lunch the app it is not calling onMessage callback.

onResume is being called even without tapping on the notification.

But when the app is in foreground, the onMessage is being called.

Is this the expected behavior? Because in the documentation it is saying that onMessage will be called when the app is brought back to foreground.

On Android, it is working as expected, this issue is only on iOS.

I'm using version 5.1.2
firebase_messaging: ^5.1.2

FYI, I'm not using any other push messaging plugin.

**Comment by kroikie** [comment]
@arsen

The issue at https://github.com/flutter/flutter/issues/36745 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@arsen Is the issue still relevant? Can you please check it using current stable flutter version v1.9.1+hotfix.2 and firebase_messaging 5.1.6?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
