### ISSUE TITLE
Multiple FirebaseMessaging crash issues reported by Google PlayStore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1061]
APK built using latest stable version `1.5.4+hotfix2-stable`

After uploading build to android playstore beta channel, here is what I see.

![screencapture-play-google-apps-publish-2019-05-12-13_15_19](https://user-images.githubusercontent.com/14252381/57579539-0a2df080-74bb-11e9-9423-5ccf372272b9.png)

**Comment by kroikie** [comment]
@tiholic

The issue at https://github.com/flutter/flutter/issues/32577 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@tiholic did you manage to solve it?
