### ISSUE TITLE
firebase_messaging with local notification

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1062]
i know firebase_messaging can't work fine with local notification pub.
let me know solution about using firebase_messaging with local notifi feature or you must create similar feature inside firebase_messaging package. please !

**Comment by kroikie** [comment]
@minh98

The issue at https://github.com/flutter/flutter/issues/31492 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@minh98 do you still encounter the issue?

**Comment by tbm98** [comment]
@BondarenkoStas  yes. it's a bug from [#111](https://github.com/MaikuB/flutter_local_notifications/issues/111)

**Comment by Ehesp** [comment]
Duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/111
