### ISSUE TITLE
[firebase_messaging] Please add all fields to FCM message (Android)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1064]
Now [firebase_messaging](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging) provide to onMessage only two parameters inside notification map: 'title' and 'body'.  [FirebaseMessagingPlugin.java](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java#L82)

Please add also other parameters from docs:
icon
color
sound
tag
click_action
body_loc_key
body_loc_args[]
title_loc_key
title_loc_args[]
channel_id

[Firebase docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)
[Android docs](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification)

**Comment by kroikie** [comment]
@Alezhka

The issue at https://github.com/flutter/flutter/issues/29066 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by kirstywilliams** [comment]
Hey @Alezhka, I'm closing this issue. If it's not been fixed in more recent versions please feel free to open a new issue.

**Comment by ristiisa** [comment]
> Hey @Alezhka, I'm closing this issue. If it's not been fixed in more recent versions please feel free to open a new issue.

@kirstywilliams what is the reason behind closing the issue?

**Comment by bscottsmith** [comment]
@kirstywilliams Why is this closed?? There is still no support for localization of FCM notifications via the ``body_loc_key``, ``body_loc_args[]``, ``title_loc_key``, and ``title_loc_args[]`` fields. See #2436.
