### ISSUE TITLE
[firebase_messaging] Different notification format for Android and iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1065]
firebase_messaging: 4.0.0+1

There is a different notification format for iOS and Android - parameter for onMessage callback.

iOS:
{google.c.a.c_l: 20190226 - en, google.c.a.c_id: 2741820249588377404, gcm.n.e: 1, google.c.a.e: 1, count: 2, gcm.message_id: 0:1552019268226658%929750ef929750ef, path: lists_custom/2019-02-26/list, action: list, google.c.a.udt: 0, google.c.a.ts: 1552019268, aps: {alert: 2 new flowers were added to the herbary}, click_action: FLUTTER_NOTIFICATION_CLICK}

Android:
{notification: {title: null, body: 2 new flowers were added to the herbary}, data: {action: list, path: lists_custom/2019-02-26/list, count: 2, click_action: FLUTTER_NOTIFICATION_CLICK}}

**Comment by kroikie** [comment]
@benadrasni

The issue at https://github.com/flutter/flutter/issues/29027 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by JinG312** [comment]
I'm having a similar issue but what weird is notification I got in iOS simulator and iOS devices is different.

iOS simulator:
{FROM_NOTIFICATION: true, from: /topics/5ddcbeaf15deea0007923d88, _id: 5de0a474067c110007d860fd, notification: {body: testing, title: Testing title for patch, e: 1, click_action: ISSUE_MESSAGE}, sentBy: 5d6e229fe7d43e0008157087, imageCheck: false, collapse_key: com.connyonair.onair, type: ISSUE_MESSAGE, ISSUE_ID: 5ddcbeaf15deea0007923d88, issueId: 5ddcbeaf15deea0007923d88, createdAt: 2019-11-29T04:54:12.457Z}

iOS device:
{issueId: 5ddcbeaf15deea0007923d88, gcm.message_id: 1575003253415106, google.c.a.e: 1, type: ISSUE_MESSAGE, aps: {alert: {title: Testing title for patch, body: Zi Jing Lim: testing}, sound: default, content-available: 1.0}, _id: 5de0a474067c110007d860fd, sentBy: 5d6e229fe7d43e0008157087, FROM_NOTIFICATION: true, createdAt: 2019-11-29T04:54:12.457Z, imageCheck: false, ISSUE_ID: 5ddcbeaf15deea0007923d88}

I've tried this two code but I received null when I try to get the body using data["body"]. 
Code 1: 
    var data = message["data"];
    if (Platform.isIOS) {
      data = message;
    }

Code 2:
    var data = message["data"] ?? message;

Flutter Doctor:
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-MY)
    • Flutter version 1.9.1+hotfix.6 at /Users/jing/Development/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jing/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (4 available)
    • A0001             • f9ff5e1a                                 • android-arm • Android 5.1.1 (API 22)
    • JinG iPhone       • b9405437c35d652421a58b319f816fdcb6e4a933 • ios         • iOS 13.2.3
    • iPhone 11 Pro     • BDA95402-8188-4226-AA50-61A3E8C57D54     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • iPhone 11 Pro Max • 2CF9B59A-20BA-4A43-B2E8-545C243DECE2     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

**Comment by kirstywilliams** [comment]
Hey @benadrasni and @JinG312 I'm reviewing old issues. Is this still an issue with the most recent version?

**Comment by benadrasni** [comment]
Hey,

I still have this code in my sources, so yes.

onResume: (Map<String, dynamic> message) async {
  setState(() {
    _notificationData = Map.from(
        Platform.isIOS ? message : message[notificationAttributeData]);
  });

},

**Comment by kirstywilliams** [comment]
@benadrasni thanks!

**Comment by nemoryoliver** [comment]
I have this issue as well. It's weird having different payloads for android and ios

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. Both Android & iOS should now be consistent, we also now have a typed api `RemoteMessage` for messages rather than the raw map that was returned previously.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
