### ISSUE TITLE
[firebase_database] Get children count without downloading all the children

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1069]
## Use case
Will be able to get children count on Firebase database without downloading all the children

## Proposal
I don't know , probably need to add a children count variable in Firebase Database and increment it as in when a new child is added

**Comment by kroikie** [comment]
@sarat12us

The issue at https://github.com/flutter/flutter/issues/38732 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
> @sarat12us I don't know , probably need to add a children count variable in Firebase Database and increment it as in when a new child is added

Correct, this is the best way of doing it, I'd recommend setting up a Cloud Function trigger that listens to on child added & removed and transactionally update a counter
