### ISSUE TITLE
[firebase_database] Android Firebase RTDB Transactions integration test failure

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1071]
Times out after 30 seconds.

This is likely the same issue as what was fixed in https://github.com/flutter/plugins/pull/1701

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/34422 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release.
