### ISSUE TITLE
firebaseStorage and imagepicker do not work together

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1076]
If I make a new FlutterProject and import 

image_picker: ^0.6.1
firebase_storage: ^3.0.4

I always get the following:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:preDebugBuild'.
> > Android dependency 'androidx.core:core' has different version for the compile (1.0.0-rc01) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> *******************************************************************************************
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> *******************************************************************************************
> Finished with error: Gradle task assembleDebug failed with exit code 1

Interesting ist that I have an old Project where I use both packages together and it works just fine??

I tried both: new project with androidx and without. Still the same thing. 
if you remove one of them the Project compiles

Does anybody know why that is?
___________________________________________________________________________________________________
> [√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)
>     • Flutter version 1.7.8+hotfix.4 at C:\Flutter\flutter\flutter
>     • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\peter\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio1
>     • Flutter plugin version 38.2.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code, 64-bit edition (version 1.31.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.25.1
> 
> [√] Connected device (1 available)
>     • SM G850F • 4100f4474548918d • android-arm • Android 5.0.2 (API 21)
> 
> • No issues found!

**Comment by pekretsc** [comment]
So Iknow you just closed the issue but I still run into the same problem :( and this time downgrading is not an option. 

1. Fresh new project(Counter)
2. import latest Image_Picker into yaml--> Still running
3. import latest cloud firestore and I get this:

Launching lib\main.dart on SM G850F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Note: C:\Flutter\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9+5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9+5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\108.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\85.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\104.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\142.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\95.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\79.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\179.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\153.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\160.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\121.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\169.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\100.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\91.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\175.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\115.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\107.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\182.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\94.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\178.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\135.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\82.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\166.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\103.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\112.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\86.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\163.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\127.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\124.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\130.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\134.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\118.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\145.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\139.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\151.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\87.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\133.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\105.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\148.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\172.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\96.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\152.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\73.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\157.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\180.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\0.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\8.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

C:\Users\peter\AndroidStudioProjects\imagepickertest>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.31.1)
[√] Connected device (1 available)

• No issues found!

C:\Users\peter\AndroidStudioProjects\imagepickertest>

**Comment by pekretsc** [comment]
I have tryed all the gradle changes I found on simular Image picker issues but nothing worked so far.

Latest versions:
  cloud_firestore: ^0.12.9+5
  image_picker: ^0.6.1+8

**Comment by pekretsc** [comment]
Same thing with Storage

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: 3.0.6
  image_picker: ^0.6.1+8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

Launching lib\main.dart on SM G850F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\85.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\79.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\100.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\91.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\94.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\82.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\97.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\103.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\73.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\88.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\0.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\peter\AndroidStudioProjects\imagepickertest\build\app\intermediates\transforms\dexBuilder\debug\10.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by pekretsc** [comment]
The Day After.......
I Finally figured it out!!! I had a cascade of issues with my project configuration. But lets start at the beginning:

1. Missunderstanding on project setup.
When you start creating a project you can check a box to use androidx Artifacts. My consumption was that this means the project will automatically be migrated to androidx(okt 2019). 
So building a fresh project without this and then migrating manually to androidx did it....Errormessage changed! [Follow this guid to migrate](https://flutter.dev/docs/development/androidx-migration)

![grafik](https://user-images.githubusercontent.com/5869144/67101559-22204380-f1c2-11e9-8899-a521cc396073.png)

2. and 3. I unfortunatly cant remember right now which of the issues came after that but there are still two things that need to be done. You will encounter these two issues:

[Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution #27254](https://github.com/flutter/flutter/issues/27254)

and

[Program type already present: android.support.v4.app.INotificationSideChannel #240](https://github.com/material-components/material-components-android/issues/240)

On Issue #27254 I sticked with the solution of Hixie. I did not try the one of Lebogang95 maybe this would work as well.

On Issue #240 you just need to add 

android.enableJetifier=true
android.useAndroidX=true

in android/gradle/gradle.properties

![grafik](https://user-images.githubusercontent.com/5869144/67102358-9a3b3900-f1c3-11e9-95cf-2a93137daa9c.png)

So if anybody has the same Issue I hope this will help ;)
