### ISSUE TITLE
Expose Firebase Storage's new ability to list files in Flutter

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1077]
The Firebase SDKs for Cloud Storage recently added the ability to list files in the storage bucket ([Android](https://firebase.google.com/docs/storage/android/list-files), [iOS](https://firebase.google.com/docs/storage/ios/list-files)). It would be great if this functionality were also available in the `firebase_storage` Flutter plugin.

**Comment by kroikie** [comment]
@puf

The issue at https://github.com/flutter/flutter/issues/39054 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Duplicate of #83
