### ISSUE TITLE
[firebase_auth] The message of Firebase Phone Auth not change according its template (Localization)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1084]
I am using firebase_auth for verify user's phone number, although I already tried to chaneg the language code to Vietnamese, and the template on the Firebase also is Vietnamese but I still got the SMS like this: "Your Firebase App verification code is: 099211" 

Here is my code:

` _auth.setLanguageCode("vi");`

Here is my Firebase Console setting: 
[https://i.ibb.co/2d4pthC/Screen-Shot-2019-08-09-at-2-02-13-PM.png](https://i.ibb.co/2d4pthC/Screen-Shot-2019-08-09-at-2-02-13-PM.png)

I also wonder how to change the "Firebase App" name for the SMS?

Thank you very much!

**Comment by kroikie** [comment]
@khachuong

The issue at https://github.com/flutter/flutter/issues/37918 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
