### ISSUE TITLE
firebase_auth build warnings in xcode

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1087]
Personally, I'm a fan of a clean build. Broken window theory and all.

firebase_auth v0.14.0

![image](https://user-images.githubusercontent.com/85355/62123222-aa90f580-b2f1-11e9-9826-0b7448d23328.png)

**Comment by kroikie** [comment]
@lookfirst

The issue at https://github.com/flutter/flutter/issues/37230 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@lookfirst how's it now? As I see 1st warning was fixed here https://pub.dev/packages/firebase_auth#01402.
What about the second one?

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/67588790-2e3b7080-f781-11e9-8004-7d0fd6cfae63.png)

**Comment by lookfirst** [comment]
firebase_auth=/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+5/

**Comment by lookfirst** [comment]
@BondarenkoStas remove the invalid tag please.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
