### ISSUE TITLE
firebase_auth _auth.onAuthStateChanged.listen() should pass in an AuthResult

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1088]
With the new api, shouldn't this method pass in an AuthResult instead of a FirebaseUser?

**Comment by kroikie** [comment]
@lookfirst

The issue at https://github.com/flutter/flutter/issues/37215 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by lookfirst** [comment]
Probably close this since @collinjackson didn't answer my thoughts in the previous issue.

**Comment by collinjackson** [comment]
> Here is my train of thought, correct me if I'm wrong:
> 
> Sign in and Creation now return an `AuthResult` instead of a `FirebaseUser`. I figure that this was changed in order to pass back `AdditionalUserInfo` since that is the only extra field in `AuthResult` right now.
> 
> ```
>     final AuthResult authResult = await _auth.signInWithEmailAndPassword(email: username, password: password);
> 
>     final AuthResult authResult = await _auth.createUserWithEmailAndPassword(email: username, password: password);
> ```
> 
> I would think that updates to this same data as a result of a state change via `onAuthStateChanged` would also result in an `AuthResult` in order to retrieve any updated `AdditionalUserInfo` (which is the extra information contained in the AuthResult). In the same way that `signInWithEmailAndPassword` returns an `AuthResult` now.
> 
> Currently, `onAuthStateChanged` is only signin/signout events, but I could see it also containing updated `AdditionalUserInfo` when that information changes as well. Otherwise, how would my app know that any `AdditionalUserInfo` has changed?
> 
> Hope this explains things a bit further.

It seems like you're running into a limitation of the Firebase Auth API generally, rather than an issue with Flutterfire's wrapper. If there isn't a way to get the profile info that is in AdditionalUserInfo in the iOS/Android/JavaScript equivalent, I don't think we should expose it in Flutter. You can build your own class that does sign-in/sign-out for your app and expose the additional information as a `Stream`.

**Comment by collinjackson** [comment]
I'm closing this issue since I don't think an action is needed but feel free to comment further if it seems like I've missed something.
