### ISSUE TITLE
FirebaseAuth failing on iOS after upgrade to flutter v1.7.8+hotfix.3 and firebase_auth: ^0.11.1+3 (the same with v1.9.1+hotfix.2)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1093]
Errors:
**Use of undeclared identifier 'FIRAuthErrorUserInfoNameKey' 
Property 'providerID' not found on object of type '__strong id'**
(and then many more errors).

Was working before the upgrade, and still works on Android.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)

Note: Just adding firebase_auth to the pubspec.yaml of the default created app
```dart
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.11.1+3
```
causes the same issue.

**Comment by kroikie** [comment]
@agreensh

The issue at https://github.com/flutter/flutter/issues/36676 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@agreensh Basing on https://github.com/flutter/flutter/issues/36676#issuecomment-540890533 I think it's safe to close the issue. Please comment if you don't agree, I will re-open it right away.
