### ISSUE TITLE
cannot find symbol

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1096]
C:\Users\User\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+10\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\Users\User\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+10\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^

**Comment by kroikie** [comment]
@flash-gh

The issue at https://github.com/flutter/flutter/issues/36400 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing based on https://github.com/flutter/flutter/issues/36400#issuecomment-515923676
