### ISSUE TITLE
[firebase_auth] does not return the refresh_token and access token

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1099]
Hello,
  The firebase_auth plugin does not provide an option to get the refresh token and access token when you create a new user. This is need if you are linking to your custom backend service.. 

Can you please let me know how we get these values

Thanks

**Comment by kroikie** [comment]
@premtemp1

The issue at https://github.com/flutter/flutter/issues/35974 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by kirstywilliams** [comment]
Hi @premtemp1 you need to call `getIdToken` on the [FirebaseUser ](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseUser-class.html) object that is returned. Closing this.

Feel free to reopen if this does not solve your solution.

**Comment by kevto** [comment]
@kirstywilliams refresh token is not provided by FirebaseUser.
