### ISSUE TITLE
[firebase_auth] Microsoft Azure Active Directory authentication flow for mobile app Update flutter

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1107]
Recently firebase released microsoft azure authentication to login in to the mobile app.
Currently there is native ios and android plugin.

**There is no  flutter plugin** 

Reference:
https://firebase.google.com/docs/auth/ios/microsoft-oauth

**Comment by kroikie** [comment]
@yugandh

The issue at https://github.com/flutter/flutter/issues/32829 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ramesh-X** [comment]
We have implemented Microsoft authentication to firebase using a fork of `firebase_auth` [here](https://github.com/fcodelabs/firebase_auth).

Someone can refer to that code and create a pull request here..

**Comment by kimamil** [comment]
Is there any status update? I would be needing this. Is there a workaround currently?

**Comment by behlsoft** [comment]
any update?

**Comment by MrZyr0** [comment]
> We have implemented Microsoft authentication to firebase using a fork of `firebase_auth` in [here](https://github.com/fcodelabs/firebase_auth).
> 
> Someone can refer to that code and create a pull request here..

@Ramesh-X I tried to create a pull request based on your implementation, but I'm a newbie 😅 Many changes occurred on firebase_auth plugin and your work need some changes.Could you please help me?

I really need to implement this function for a project.

Thanks

**Comment by mertcanbs** [comment]
This is a much-needed feature on our end. Are there any recent plans to implement it?

**Comment by buimanhhungit** [comment]
any update?

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

Please could you update to the new version as this feature is should now be supported through the custom OAuth provider flow. If you have any problems with this feature or the updated plugins please raise a new GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
