### ISSUE TITLE
[firebase_auth] verificationCompleted never triggered for test (whitelisted) phone numbers

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1108]
Steps to reproduce:
1- Added my own phone number to the whitelist, events fired: codeSent, codeAutoRetrievalTimeout.
2- Removed my phone number from the whitelist, events fired were: codeSent, verificationCompleted, (I did receive the sms).
3- Added the number suggested by the docs., +16505551234, events fired were: same as in step 1.

```
    await _auth.verifyPhoneNumber(
        phoneNumber: phone,
        timeout: const Duration(seconds: 5),
        verificationCompleted: (r) {
          print("Verification completed ");
        },
        verificationFailed: (r) {
          print("Verification failed " + r.message);
        },
        codeSent: (r, [v]) {
          print("Code sent." + r + v.toString());
          return null;
        },
        codeAutoRetrievalTimeout: (r) {
          print("Timeout " + r.toString());
        });
```

**Comment by kroikie** [comment]
@votagus

The issue at https://github.com/flutter/flutter/issues/32732 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@votagus did you manage to solve the issue?

**Comment by votagus** [comment]
> @votagus did you manage to solve the issue?

No, I just moved on with another way to do the auth.

**Comment by Ehesp** [comment]
I believe this is valid, whitelisted phone numbers are never auto-verified. When you whitelist a number, you have to provide a manual code. Therefore Firebase will never actually send a code to the device (since you know the code already).
