### ISSUE TITLE
firebase_auth updatePhoneNumber

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1116]
Hi, I'm using the firebase_auth plugin but I cannot find the method .updatePhoneNumber.

Is this method implemented in the plugin or is it missing?

**Comment by kroikie** [comment]
@GianlucaCesari

The issue at https://github.com/flutter/flutter/issues/29000 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This functionality is supported in the latest version of the plugin
