### ISSUE TITLE
[firebase_auth] Firebase Facebook login internal error on iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1119]
I'm trying to implement Firebase Facebook login but it throws an error says like so.

> PlatformException(sign_in_failed, FIRAuthErrorDomain, An internal error has occurred, print and inspect the error details for more information.)

I enabled Facebook method and paste code in plist.  
What am I doing wrong?   
Anyone have an idea?

**Code**

```dart
    try {
      final FacebookLogin facebookLogin = FacebookLogin();
      final result = await facebookLogin.logInWithReadPermissions(['email']);
      switch (result.status) {
        case FacebookLoginStatus.loggedIn: 
          final FirebaseUser user = await FirebaseAuth.instance.signInWithFacebook(accessToken: result.accessToken.token);
          print(user.uid);
        break;
        case FacebookLoginStatus.error:
          print('ERROR');
          break;
        default:
          break;
      }
     } catch (e) {
        print(e);
    }
```

**Comment by kroikie** [comment]
@ghost

The issue at https://github.com/flutter/flutter/issues/24488 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Seems to be outdated already, closing it. @ghost can you confirm that it's solved?

**Comment by phunlle** [comment]
I am still having this problem. Also doesn't look like `signInWithFacebook` is available on `FirebaseAuth.instance`

**Comment by Salakar** [comment]
Going to consolidate this under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format - this will help with diagnosing what the actual issue is in scenarios like this.
