### ISSUE TITLE
[firebase_dynamic_link] v0.5.0 is not correctly working in ios  in running/background state

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1124]
In android application firebase dynamic link 0.5.0 is working fine. But in ios device dynamic link is not working when app is in running/background state. But in killed state it works fine means when link is clicked in killed state it open correct location in the application.
I have no idea why it is happening.
should I use one of the old versions?

**Comment by kroikie** [comment]
@dhanrajvermaRepo

The issue at https://github.com/flutter/flutter/issues/38744 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by logemann** [comment]
Here are my findings on that issue.

FirebaseDynamicLinks.instance.getInitialLink() returns null in the following situations:

* background state / app open
* app closed before

It only works when app is in foreground mode.

All tests with the same DynamicLink and URL clicked from Notes app on iOS Xr real device. So from what i can gather, its totally unusable at this point.

Redirecting to AppStore works without problem if the app is not installed at all.

**Comment by wilburt** [comment]
To buttress @logemann's findings, it always works on iOS when the app is in the foreground mode. However, it works for me in background mode, but it appears to be random and inconsistent.

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/1041

**Comment by MderM** [comment]
I got the same behaviour with 0.4.0+6, also.

**Comment by MderM** [comment]
Nevermind. Got it working just like it should. All having this same issue, please follow  the setup guide on the flutter pub site.

> Receiving dynamic links on iOS requires a couple more steps than Android. If you only want to receive dynamic links on Android, skip to step 4. You can also follow a video on the next two steps here.

In the Info tab of your iOS app's Xcode project:
Create a new URL Type to be used for Dynamic Links.
Set the Identifier field to a unique value and the URL Schemes field to be your bundle identifier, which is the default URL scheme used by Dynamic Links.
In the Capabilities tab of your app's Xcode project, enable Associated Domains and add the following to the Associated Domains list:
applinks:YOUR_SUBDOMAIN.page.link

**Comment by kroikie** [comment]
Seems like in general this issue is resolved. For more specific cases where there are issues with the plugin please file an issue.
