### ISSUE TITLE
[firebase_dynamic_links v0.5] - Dynamic link always null when link is pressed in Gmail App on IOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1125]
## Steps to Reproduce

1. Use the example project provided here https://github.com/flutter/plugins/tree/master/packages/firebase_dynamic_links/example
2. Send the dynamic link to a gmail account
3. Open the link in the Gmail App on an IOS device
4. The link will be null.
5. Send another link to the same gmail
6. Open safari/chrome, log into gmail.
7. Click the link, the link will be valid

## Logs

```
No real logs, just a log statement printing out the value of the dynamic link which is indeed null when click from gmail.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale
    en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by kroikie** [comment]
@Baileypollard

The issue at https://github.com/flutter/flutter/issues/38455 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by nevercamp** [comment]
Same issue

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release. If this is still a problem then the best way forward is to raise a new issue with updated and detailed information on the issue.
