### ISSUE TITLE
[firebase_core] Package on pub.dev is v0.4.0+1 but repo is v0.4.0+8

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1129]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/firebase_core/pubspec.yaml

**Comment by kroikie** [comment]
@workerbee22

The issue at https://github.com/flutter/flutter/issues/37538 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by eldraco19** [comment]
I created an issue in shields GitHub repository, 
https://github.com/badges/shields/issues/4172

Look like they fixed it in
https://github.com/badges/shields/pull/4173

After this gets merged, then we might see correct version in badge.

**Comment by BondarenkoStas** [comment]
It's merged, but still pub v0.4.0+1

**Comment by Ehesp** [comment]
No longer an issue
