### ISSUE TITLE
[firebase_remote_config] iOS Readme Documentation missing

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1134]
The readme for the Flutter Firebase Remote Config Plugin has instructions for Android but not for iOS.

https://github.com/flutter/plugins/tree/master/packages/firebase_remote_config

**Comment by kroikie** [comment]
@MisterJimson

The issue at https://github.com/flutter/flutter/issues/29605 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Pannkaaka** [comment]
Any updates on this?

**Comment by jsimon-development** [comment]
Looking for an update on this as well.

**Comment by Salakar** [comment]
Given the age of this issue and that Remote Config has had a major rework since including new documentation; I'm going to close this issue in favour of trying the latest release.
