### ISSUE TITLE
[firebase_performance] HttpMetric PayloadSize field can throw a NullPointerException

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1135]
When following the example for "Adding monitoring for network requests" on the plugin Readme page (https://pub.dev/packages/firebase_performance), an uncaught `java.lang.NullPointerException` can be thrown when `responsePayloadSize` or `requestPayloadSize` are given a null value. 

This should be handled, as sometimes these values aren't available (especially in the case of streamed responses).

**Comment by kroikie** [comment]
@axel-op

The issue at https://github.com/flutter/flutter/issues/38133 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by daadu** [comment]
Any work around for this?

**Comment by daadu** [comment]
@kroikie I submitted a PR to fix this.

**Comment by axel-op** [comment]
Thanks @Salakar :)
