### ISSUE TITLE
Crashlytics plugin request: report actual exception mesage instead of harcoded "Dart error"

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1146]
Currently FirebaseCrashlyticsPluginJava has this code
```java
      Exception exception = new Exception("Dart Error");
     Crashlytics.setString("exception", (String) call.argument("exception"));
      Crashlytics.logException(exception);

```
I propose instead something like this (not exact code, I didn't run it)
```java
 String dartExceptionMessage = (String) call.argument("exception");
 Exception exception = new Exception("Dart Error:" + dartExceptionMessage );
      Crashlytics.logException(exception);
```
This seems like this would be a really big improvement in terms of not getting exceptions grouped improperly... of course, you can put some defensive code around nullchecks, but this would be great.

**Comment by kroikie** [comment]
@neiljaywarner

The issue at https://github.com/flutter/flutter/issues/31370 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by neiljaywarner** [comment]
Unfortunately I've been away from flutter lately mostly but I'm still very excited about it on general and thanks for working on it
