### ISSUE TITLE
Flutter firebase_admob:   anchortype.top broken

### ISSUE THREAD

**Issue by ArtfulDodgerB92** [FirebaseExtended/flutterfire#115]
**Describe the bug**
Hi guys,

In IOS, when the screen layout is landscape (haven't tested for portrait), setting anchortype.top for banner ads results in a failedtoload error.    Setting achortype.bottom works perfectly.

Can this please be resolved?   The issue was present in 0.5.5, and I updated to 0.9.0+7, and this still is not fixed.

Please resolve this issue, I am unable to release my application to the Apple Appstore because this is not working.

**To Reproduce**
Set up firebase_admob ads in your app.   Use anchortype.bottom and observe ad showing correctly.

Change to anchortype.top and see in logs that you will now receive a FailedToLoad message, changing no other values at all in the app.

**Expected behavior**
Banner ad should appear on the top of the application in all screen orientations.

**Additional context**

**Comment by iapicca** [comment]
Hi @ArtfulDodgerB92 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/97)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
