### ISSUE TITLE
[firebase_crashlytics] Support for deobfuscation of Dart reports

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1150]
I can't even find any info on how to find dart obfuscation maps to deobfuscate reports manually

**Comment by kroikie** [comment]
@rostopira

The issue at https://github.com/flutter/flutter/issues/30303 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by sperochon** [comment]
Hello,

I have created a web flutter app to do dart deobfuscation easily:
https://www.mobiquite.fr/dart-flutter-stacktrace-deobfuscator/

It is inspired from the script of @rostopira
https://github.com/flutter/flutter/issues/30303#issuecomment-522544995

**Comment by kikuchy** [comment]
Any update?

**Comment by rostopira** [comment]
@kikuchy yep, update: https://flutter.dev/docs/deployment/obfuscate
@kroikie Please, close this issue, it's resolved

**Comment by rostopira** [comment]
Oops, missed that issue is about crashlytics, not only obfuscation, should not be closed

**Comment by lsuhov** [comment]
Hello,
Please prioritize the deobfuscation of dart stack traces in Crashlytics. How are the production Flutter apps managing this part? I doubt that `flutter symbolize` can be considered a reasonable solution if you have multiple exceptions to check.

**Comment by 2math** [comment]
Best solution is to be able to upload the symbols per version in firebase and crashlitics to be able to translate the exception.
Something like mappings on Play Store

**Comment by singun-lxd** [comment]
Any solutions?

**Comment by talent-apps** [comment]
Any update?
At the moment, the `firebase_crashlytics` plugin is useless for apps that use Dart obfuscation.
Does this plugin have any owners? Why such a crucial issue is left unaddressed?

**Comment by nt4f04uNd** [comment]
@talent-apps it's not. You still can manually deobfuscate crash reports

**Comment by dluksza** [comment]
@nt4f04uNd the first step would be to include this information in the README and document how to do this manually. I've tried deobfuscating my crash reports manually but it never worked for me.

**Comment by dayron9110** [comment]
Any updates?
