### ISSUE TITLE
[firebase_crashlytics] incomplete documentation

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1153]
Along with the instructions mentioned, I had to add the following line to [project]/android/app/build.gradle in the dependencies section to get crash reports on the dashboard.

implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'

**Comment by kroikie** [comment]
@abhaumik

The issue at https://github.com/flutter/flutter/issues/30030 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Please consider the indication provided in this [comment](https://github.com/FirebaseExtended/flutterfire/issues/1376#issuecomment-550466807)

```
So it seems that there are two things missing in the documentation:

 - Add implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9' to android/app/build.gradle.
 - Do a complete restart (using the Stop and Run buttons in IntelliJ for example) to actually send the crash report to Crashlytics.
```

**Comment by Salakar** [comment]
A new Crashlytics plugin has now landed on master which should solve this issue. Lots of new documentation too.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin: https://firebase.flutter.dev/docs/migration/
