### ISSUE TITLE
[firebase_ml_vision] ImageLabeler doesn't return entityId on iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1158]
ImageLabeler returns null in entityId on iOS. On Android it returns entity id.

I think the problem is with this (Android is using "entityId" but iOS is using "entityID"):
```
Android: 
Map<String, Object> labelData = new HashMap<>();
labelData.put("confidence", (double) label.getConfidence());
labelData.put("entityId", label.getEntityId());
labelData.put("text", label.getText());
labels.add(labelData);


iOS:
NSDictionary *data = @{
              @"confidence" : label.confidence,
              @"entityID" : label.entityID,
              @"text" : label.text,
};
```

**Comment by kroikie** [comment]
@benadrasni

The issue at https://github.com/flutter/flutter/issues/34852 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @benadrasni
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/flutter/issues/34852#issuecomment-545435476
