### ISSUE TITLE
[firebase_ml_vision] How to use RecognizedLanguage in TextRecognize 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1160]
```
class RecognizedLanguage {
  RecognizedLanguage._(dynamic data) : languageCode = data['languageCode'];
  final String languageCode;
}

```
how to call this class.

**Comment by kroikie** [comment]
@MistryHiral

The issue at https://github.com/flutter/flutter/issues/34380 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release.
