### ISSUE TITLE
flutter fire firebase_ml_vision object detections 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1161]
Hello folks, 
This issue is regarding mlkit object detection annouced recently. Creating an issue to track its implementation in flutter.

Thank you

**Comment by kroikie** [comment]
@startupgurukul

The issue at https://github.com/flutter/flutter/issues/32291 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@startupgurukul I'm going to close the issue in favour of #1159 to avoid duplication. Please follow it there.
