### ISSUE TITLE
Support "direct booking" in the current firebase Admob plug-in

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1166]
Customer mentioned that it is a requirement for them to add custom ads beside those from Google, namely, direct bookings. 

However, the current firebase Admob plug-in does not support direct bookings. Direct bookings is a feature available in Double Click. Hence, customer is requesting Flutter to support either DoubleClick, or at least add this feature to existing Admob plug-in.

**Comment by zoeyfan** [comment]
@kroikie , may I ask why is this issue closed now?
