### ISSUE TITLE
[web]: <Firebase Admob Support on the web>

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1167]
Throwing away cached asset graph because the build phases have     changed. This most commonly would happen as a result of adding a
new dependency or updating your dependencies.
Skipping compiling flutter_app|lib/main_web_entrypoint.dart withddc because some of its
transitive libraries have sdk dependencies that not supported on
this platform:

firebase_admob|lib/firebase_admob.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-
i-resolve-skipped-compiling-warnings

**Comment by tmthecoder** [comment]
Will this plug-in end up having web support in the future? I would like to port my app to web, but the only thing stopping me is the lack of admob for web

**Comment by tomrozb** [comment]
Same question here. Are there plans for AdMob on web?
