### ISSUE TITLE
Please add The Native Add Feature in firebase admob package

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1170]
## Proposal

It's been a long time so can you guys please add the support for native ads in firebase admob 
package?

**Comment by kroikie** [comment]
@Loopex2019

The issue at https://github.com/flutter/flutter/issues/38738 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Closing in favour of https://github.com/FirebaseExtended/flutterfire/issues/1174
