### ISSUE TITLE
firebase_admob crashes in iOS simulator on startup after basic install

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1172]
Steps to reproduce:

1. create default app in Android Studio
2. build and run app successfully in iOS simulator through Android Studio
3. add dependency `firebase_admob: ^0.9.0+2` in pubspec.yaml
4. app builds successfully but crashes on startup
5. follow instructions to add `GADApplicationIdentifier` with test ID code into ios/Runner/info.plist file

App still crashes on startup. Instructions followed for setting up on iOS as detailed here: https://pub.dev/packages/firebase_admob. As far as I can see, I've done everything as instructed so no idea why it doesn't work with a basic app.

The error I get after all steps above is:

`Xcode build done.                                            8.5s`
`Configuring the default Firebase app...`
`6.4.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.`
`6.4.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.`
`6.4.0 - [Firebase/Core][I-COR000005] No app has been configured yet.`
`6.4.0 - [Firebase/Core][I-COR000005] No app has been configured yet.`
`*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113b521bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001130f0735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113b52015 +[NSException raise:format:] + 197
	3   Runner                              0x000000010bd33af0 +[FIRApp configure] + 576
	4   Runner                              0x000000010bd7f1c5 -[FLTFirebaseAdMobPlugin init] + 261
	5   Runner                              0x000000010bd7ef2e +[FLTFirebaseAdMobPlugin registerWithRegistrar:] + 78
	6   Runner                              0x000000010bd333fb +[GeneratedPluginRegistrant registerWithRegistry:] + 123
	7   Runner                           <…>`

**Comment by kroikie** [comment]
@hasen6

The issue at https://github.com/flutter/flutter/issues/36241 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by hasen6** [comment]
@kroikie Is this some kind of error? Why are all these firebase_admob issues being closed, move somewhere else where they are ALSO closed???

**Comment by BondarenkoStas** [comment]
@hasen6 All the firebase plugins related issues were moved here (to FirebaseExtended/flutterfire). This issue is open here, as the rest of moved open issues.

**Comment by hasen6** [comment]
@BondarenkoStas Ok can you add the links for each issue in this thread and the other closed threads? Otherwise these issues just go nowhere.

**Comment by thuraucsy** [comment]
It seems the **firebase_admob 0.9.0+7** not supporting the swift enable flutter project yet. 
In my case, I recreated the ios folder in my project without swift enabling and then the error has gone. 
Of course, if your project using swift enable plugin, you have to remove that plugin for the solution.

**Comment by Ehesp** [comment]
> App with name __FIRAPP_DEFAULT does not exist.

You have not added the GoogleServices-Info.plist file to your project. Please follow these instructions https://firebase.google.com/docs/flutter/setup?platform=ios and rebuild your app.
