### ISSUE TITLE
[firebase_admob] Pure Flutter support for Native Ads Advanced

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1173]
Split off #12114

Users would like to use Flutter widget for rendering AdMob [Native Ads Advanced](https://developers.google.com/admob/android/native/start) ads.

Note: Native Ads Advanced is only available to a limited set of approved app developers(publishers)

**Comment by kroikie** [comment]
@amirh

The issue at https://github.com/flutter/flutter/issues/35083 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by orestesgaolin** [comment]
Are there any plans to support pure Flutter ads in the foreseeable future? We would love to get some update on this.

**Comment by Kuoyhout** [comment]
Please implement this feature. It'd help me & a lot of other developers.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
