### ISSUE TITLE
[firebase_admob] Support AdMob Native Ads Advanced in overlays

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1174]
Split off https://github.com/flutter/flutter/issues/12114

This issue tracks adding support to overlay [AdMob Native Ads Advanced](https://developers.google.com/admob/android/native/start) ads on top of the Flutter UI (similarly to how banner ads are currently overlaid: e.g it shows in a pre-set position and on top all of the Flutter UI).

While obviously being able to embed native ads is a better option(https://github.com/flutter/flutter/issues/12114), overlaying the native ad similarly to the current banner support is something reasonable to expect within a shorter timer frame.

**Comment by kroikie** [comment]
@amirh

The issue at https://github.com/flutter/flutter/issues/35082 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
