### ISSUE TITLE
[firebase_admob] Allow embedding AdMob banner ads in a Flutter widget tree

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1175]
Split off https://github.com/flutter/flutter/issues/12114

Users are would like to embed a [AdMob banner ad](https://developers.google.com/admob/android/banner) as part of the Flutter widget tree(vs. the current approach taken by the firebase_admob plugin which is to overlay the banner ad on top of the Flutter UI in a pre-set position).

**Comment by kroikie** [comment]
@amirh

The issue at https://github.com/flutter/flutter/issues/35081 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Waheed388** [comment]
It is frustrating. Hope it will get fixed soon.

**Comment by tolgatanriverdi** [comment]
Are there any progress on allowing us to use admob banners in anywhere we want in the screen?
Because this is very annoying approach to force developers to use admob banners only on top

**Comment by ugurcany** [comment]
It's quite frustrating not being able to add ads as widgets. That's against the entire approach of Flutter.

**Comment by namchuai** [comment]
Currently, I'm using admob_flutter for this. But, IMO, the library is not stable yet..

**Comment by erperejildo** [comment]
> Currently, I'm using admob_flutter for this. But, IMO, the library is not stable yet..

I'm trying the same one. What's the difference from `firebase_admob`?

**Comment by comlaterra** [comment]
I just would like to point out the fact that currently the firebase_admob plugin is implementing a discouraged banner implementation by the Admob Policies. See it [here](https://support.google.com/admob/answer/6275345?hl=en): Ad sandwiched between app items.
So I guess this plugin is also discouraged to be used.

**Comment by jpainam** [comment]
The approach is really discouraging. Hope the flutter team is working on fixing this

**Comment by devibrahimkarahan** [comment]
Any update ?

**Comment by mileusna** [comment]
> I just would like to point out the fact that currently the firebase_admob plugin is implementing a discouraged banner implementation by the Admob Policies. See it [here](https://support.google.com/admob/answer/6275345?hl=en): Ad sandwiched between app items.
> So I guess this plugin is also discouraged to be used.

It is discouraged banner implementations if you put it without any padding close to buttons and other elements causing accidental banner clicks.

For the users it is much more pleasing to see banner in the widget tree than overlaying at the top or the bottom.

**Comment by voipworld** [comment]
no update on this?

**Comment by MaximeDelhorme** [comment]
Any update on this feature?

**Comment by ramos41** [comment]
Any update?

**Comment by jagomf** [comment]
> Also, banner ads should not move as a user scrolls, as users may try to click on the menu but end up clicking on the ad accidentally instead

Like I just mentioned in @kmcgill88's [admob_flutter](https://github.com/kmcgill88/admob_flutter), IMHO the interpretation of «banner ads should not move as a user scrolls» does **not** include banners which are actually **fixed to a position in a list**, and thus not actually moving other than all the rest of the content. I understand that ads should not move **on their own or in a different pace than the scroll itself**, so that users do not click _accidentally_. It is not possible to click _accidentally_ if the ads are each one fixed to a position; otherwise users might _accidentally_ click in virtually any part of the screen while scrolling.

Google themselves actually do sell that kind of banners in platforms of theirs such as Blogspot blogs.

Again IMHO, the sentence «banner ads should not move as a user scrolls» is too vague and does not actually clarify anything, and does not match the 21st century world where ads do literally integrate in the content.

**Comment by jesusmartinoza** [comment]
Any update? 🙃

**Comment by dayron9110** [comment]
Any update?

**Comment by dblokhin** [comment]
https://github.com/flutter/flutter/issues/12114#issuecomment-725731427

**Comment by erperejildo** [comment]
Watching the Flutter engage video:

<img width="1131" alt="Screenshot 2021-03-03 at 22 28 27" src="https://user-images.githubusercontent.com/5629919/109874785-ddd6fb80-7c6f-11eb-8c7d-be7255570e80.png">

**Comment by mileusna** [comment]
Tne new package is public now https://pub.dev/packages/google_mobile_ads

**Comment by erperejildo** [comment]
> https://pub.dev/packages/google_mobile_ads

This is confusing. Why do we have now a new package for ads? Do we need to stop using admob_flutter?

**Comment by gcshri** [comment]
@erperejildo - the simplest explanation is that it now covers Google Ad Manager which many of us had requested. No longer "Admob" only.

**Comment by erperejildo** [comment]
> @erperejildo - the simplest explanation is that it now covers Google Ad Manager which many of us had requested. No longer "Admob" only.

but they didn't mention what to do with firebase_admob. Is it deprecated? Can we do the same thing PLUS whatever we need from Google Ad Manager using the new package?

**Comment by henriq-88** [comment]
> > @erperejildo - the simplest explanation is that it now covers Google Ad Manager which many of us had requested. No longer "Admob" only.
> 
> but they didn't mention what to do with firebase_admob. Is it deprecated? Can we do the same thing PLUS whatever we need from Google Ad Manager using the new package?

https://pub.dev/packages/firebase_admob seems now to have been tagged as `discontinued`

**Comment by erperejildo** [comment]
> > > @erperejildo - the simplest explanation is that it now covers Google Ad Manager which many of us had requested. No longer "Admob" only.
> > 
> > 
> > but they didn't mention what to do with firebase_admob. Is it deprecated? Can we do the same thing PLUS whatever we need from Google Ad Manager using the new package?
> 
> https://pub.dev/packages/firebase_admob seems now to have been tagged as `discontinued`

I don't understand why they don't say everything, the more info the better.
Do they have a new package? Fine. Are they going to leave this version deprecated? Fine also, but say it to make it clear.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
