### ISSUE TITLE
Admob wrong size smartBanner when ad have long text

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1176]
Hello! When specifying the size: AdSize.smartBanner for an advertising banner, the size on the iphone xr is not correctly determined

<img width="597" alt="Снимок экрана 2019-06-24 в 13 24 43" src="https://user-images.githubusercontent.com/44409006/60011914-763b7100-9683-11e9-8f8c-c84bc9dbc7c2.png">

**Comment by kroikie** [comment]
@1AlexFix1

The issue at https://github.com/flutter/flutter/issues/34985 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
