### ISSUE TITLE
[Firebase Auth] <Not Receive OTP Code>

### ISSUE THREAD

**Issue by chandrabezzo** [FirebaseExtended/flutterfire#118]
I was followed step by step tutorial from Readme. In debug or release installed apps I can get OTP Number to my phone number, but when I publish my apps to Play Store that I upload using appbundle with the same code with debug or release apk. When I install that application from play store, I still can't get OTP Number. What should I do for resolve this bugs? I was add SHA1 to the firebase project. Thank You.

**Comment by GianlucaCesari** [comment]
Did you link the firebase project to the playstore? Once the app goes live it's signed with a different SHA1 than the development app, could be that one. You can find it in /settings/integrations in your firebase app, just need to link google play store and submit a new build.

**Comment by chandrabezzo** [comment]
Solved, add SHA 1 from play store to Firebase
