### ISSUE TITLE
[firebase_admob] Crash on launch for iOS (Needs better setup documentation)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1181]
## Steps to Reproduce

Could not reproduce in another application. 

It just started happening in my iOS application after cocoapods upgrade. When running the app with flutter run it works 100% of the times. But when building the app and installing via the .ipa file or through xcode it will crash on start ~40% of the times.

1. Go to xcode and run the app on a real device
3. See files added
[error.txt](https://github.com/flutter/flutter/files/3072987/error.txt)

## Logs

```
Analyzing Levconomy...                                                  
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-SE)
    • Flutter version 1.2.1 at /Users/admin/Documents/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Roberts iPad • b54711fbe84c3679a1a4c726638f0f78394e4ee8 • ios • iOS 9.3.5

! Doctor found issues in 1 category.
```

**Comment by kroikie** [comment]
@RobertBrunhage

The issue at https://github.com/flutter/flutter/issues/30962 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@RobertBrunhage is it still the same with current flutter stable and firebase_admob 0.9.0+7?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
