### ISSUE TITLE
cloud_function crashes when region is specified

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1189]
## Steps to Reproduce

- deploy a cloud function without specifying a region. 
```
export const myFunction = functions.https.onCall
```

Call the function from a flutter app using:
```
final HttpsCallable call = CloudFunctions.instance.getHttpsCallable(
                functionName: 'myFunction',

              );

              dynamic response = await call.call(<String, dynamic>{
                params
              });
```

The above should work without a problem. 

However, if you specifiy a region in:
```
export const myFunction = functions.https.region('europe-west1').onCall
```
Then flutter can't find the function.

## Logs
`cloud function response is not a valid json object`

## pubspec.yaml

firebase_core: ^0.4.0+8
 firebase_auth: ^0.11.1+12
 cloud_firestore: ^0.12.8
 cloud_functions: ^0.4.0+3

## doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-CA)
    • Flutter version 1.7.8+hotfix.3 at /Users/Aljulanda/Desktop/Projects/flutter
    • Framework revision b712a172f9 (3 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Aljulanda/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/Aljulanda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/Aljulanda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • GM1917 • 34fea642 • android-arm64 • Android 9 (API 28)

• No issues found!
```

Finally, does Flutter support multi-region functions? Like
```
export const myFunction = functions.https.region('europe-west1', 'europe-west1').onCall
```

**Comment by kroikie** [comment]
@Aljulanda9

The issue at https://github.com/flutter/flutter/issues/37284 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by bogdannedelcu** [comment]
any idea how to overcome this... sometimes works sometimes crashes... really annoying.

**Comment by bogdannedelcu** [comment]
Not sure if this is the same bug we encountered but for us renameing the function and deploy again worked.

**Comment by cmregazzo** [comment]
Hi,

I have a problem, even not specifying the region:

[ERROR: flutter / lib / ui / ui_dart_state.cc (148)] Unhandled Exception: Instance of 'CloudFunctionsException'
E / flutter (11096): # 0 HttpsCallable.call (package: cloud_functions / src / https_callable.dart: 48: 9)

I am using 'com.google.firebase: firebase-functions: 18.1.0' within the Android APP build.gradle and my cloud_functions plugin version is ^0.4.1+4.

Is there any definitive solution?

Thank you,

Cristian Regazzo

**Comment by shadysamir** [comment]
It is stated in [docs](https://firebase.google.com/docs/functions/locations#client-side_location_selection_for_callable_functions) that a function's region other than `us-central1` (the default) should be indicated in the client call. No mention of how to do that in Flutter.
var functions = firebase.app().functions('us-central1');
The example code given for Web (JS) is:
```js
var functions = firebase.app().functions('us-central1');
```

**Comment by shadysamir** [comment]
I got it fixed. The region gets set in CloudFunction constructor. So instead of calling the static method `instance` build an object with the constructor.

Replace this
```dart
final HttpsCallable call = CloudFunctions.instance.getHttpsCallable(functionName: 'myFunction',);
```
with this:
```dart
final HttpsCallable call = CloudFunctions(region: 'europe-west1').getHttpsCallable(functionName: 'myFunction',);
```

**Comment by greghesp** [comment]
@Aljulanda9 - this can be achieved as per the comments above from @shadysamir 

For the latest [roadmap version](https://github.com/FirebaseExtended/flutterfire/issues/2582), this will utilise `instanceFor` like below:

```dart
HttpsCallableResult callable = 
  CloudFunctions.instanceFor(region: 'europe-west1')
   .httpsCallable('getName');
```

Keep an eye out on the roadmap for the release.
