### ISSUE TITLE
[cloud_functions] Comparison of distinct pointer types warning 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1190]
## Steps to Reproduce

1. Include cloud_functions
```Dart
import 'package:cloud_functions/cloud_functions.dart';
```
2. `open ios/Runner.xcworkspace`
2. Build in Xcode => Warning:
```
/Users/deg/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.4.0+2/ios/Classes/CloudFunctionsPlugin.m:56:59: Comparison of distinct pointer types ('NSNumber *' and 'NSNull * _Nonnull')
```
```obj-c
timeoutMicroseconds != [NSNull null]
```

Found this while doing the recommended Xcode build per:
```Could not install build/ios/iphoneos/Runner.app on f3e62265833e1fa286a468bd734f20814f52f4f8.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace
```

Thanks for considering!

**Comment by kroikie** [comment]
@repentsinner

The issue at https://github.com/flutter/flutter/issues/36642 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by awhitford** [comment]
I am using **Fluttter 1.17.1** with **cloud_functions 0.5.0** and still see **2 warnings generated**:
```
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.5.0/ios/Classes/CloudFunctionsPlugin.m:59:59: warning:
    comparison of distinct pointer types ('NSNumber *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
        if (timeoutMicroseconds != nil && timeoutMicroseconds != [NSNull null]) {
                                          ~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.5.0/ios/Classes/CloudFunctionsPlugin.m:83:78: warning:
    values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
                                errorWithCode:[NSString stringWithFormat:@"%ld", error.code]
                                                                           ~~~   ^~~~~~~~~~
                                                                           %ld   (long)
    2 warnings generated.
```

**Comment by manafire** [comment]
I was getting the same with Flutter 1.20.3 and cloud_functions 0.6.0.  In my case, I was upgrading and was eventually able to get around it by following the steps in the [migration guide](https://firebase.flutter.dev/docs/migration) and [setting an iOS deployment target](https://stackoverflow.com/a/57868395/805003).  The `pod repo update` in the [CocoaPods section](https://firebase.flutter.dev/docs/migration#cocoapods-could-not-find-compatible-versions-for-pod) might have also done the trick.

**Comment by Salakar** [comment]
Given the age of this issue and that Functions has had a major rework since; I'm going to close this issue in favour of trying the latest release.
