### ISSUE TITLE
“Invalid Envelope” errors in Firebase Cloud Functions

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1193]
Sometimes the response of callable CloudFunctions cloud_functions 0.1.2+1 throws CloudFunctionGenericException with "Invalid Envelope" message.

This seems to happen for no specific reason, and nothing is logged to the Firebase Cloud Function Logs.

This occours rarely (once each 25 times approx)  and more frequently when a map is returned, but breaks the app logic.

I know this problem since 0.0.5 version.

Why this is happening and how to fix it?

**Comment by kroikie** [comment]
@yamauchieduardo

The issue at https://github.com/flutter/flutter/issues/30994 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/flutter/issues/30994#issuecomment-543719569

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by iapicca** [comment]
Hi @yamauchieduardo
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` or `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by yamauchieduardo** [comment]
The problems don't appear more. I'm updating the project cloud_functions versions to ^0.4.1. 

Thanks.
