### ISSUE TITLE
cloud_functions uses KVC methods unnecessarily

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1195]
@cyanglaz wrote:

>>> Did you intend to use NSMutableDictionary and setObject:forKey instead of using the KVC method setValue:forKey? Same for below. If the intention is to actually use the KVC, please ignore this comment.

https://github.com/flutter/flutter/issues/28271#issue-413066060

Could potentially lead to bugs, see https://stackoverflow.com/questions/1249634/wheres-the-difference-between-setobjectforkey-and-setvalueforkey-in-nsmutab

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/28271 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age of this issue and that Functions has had a major rework since; I'm going to close this issue in favour of trying the latest release.
