### ISSUE TITLE
[cloud_firestore] when you wrap get,set,delete in a transaction it no longer changes firestore data

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1196]

**Comment by kroikie** [comment]
@rizjohn

The issue at https://github.com/flutter/flutter/issues/42097 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
