### ISSUE TITLE
[cloud_firestore] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1197]

**Comment by kroikie** [comment]
@amirh

The issue at https://github.com/flutter/flutter/issues/41852 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by helenaford** [comment]
Fix merged, closing issue

**Comment by helenaford** [comment]
Supported in the latest plugin versions
