### ISSUE TITLE
[firebase_remote_config] RemoteConfig.instance Future already completed

### ISSUE THREAD

**Issue by IchordeDionysos** [FirebaseExtended/flutterfire#120]
**Describe the bug**
When calling RemoteConfig.instance twice both of these calls go into the if-statement and try to retrieve the instance.

Then in here both calls to get RemoteConfig.instance try to complete with the instance, but the second one fails as the first one already completed the Completer.

**To Reproduce**
1. Install and configure Remote Config
2. Get RemoteConfig.instance twice in parallel
3. See that the second call will fail with Bad state: Future already completed

**Expected behavior**
Both calles to `RemoteConfig.instance` complete without an error

**Additional context**

I'll put together an MVCE

**Comment by IchordeDionysos** [comment]
Here is the MCVE: https://gist.github.com/IchordeDionysos/849d1ec5ec409487f1f2640c9c806e9f
If you run it in Debug mode you'll stop at the `Future already complete` error.

Of course, this example seems a bit useless, but consider the second `RemoteConfig.instance` being called somewhere else in the source code independent from the first call.

**Comment by mayurdhurpate** [comment]
Facing the same issue `Unhandled Exception: Bad state: Future already completed` if running:
`final RemoteConfig remoteConfig = await RemoteConfig.instance;` multiple times in parent-child widgets at the same time.

**Comment by stepankuzmin** [comment]
> Facing the same issue `Unhandled Exception: Bad state: Future already completed` if running:
> `final RemoteConfig remoteConfig = await RemoteConfig.instance;` multiple times in parent-child widgets at the same time. Any workarounds?

Same issue here ☹️

**Comment by Praveen-Aanand** [comment]
this problem occurs only when i am using MVC architecture.

**Comment by michaldev** [comment]
I have the same problem.

**Comment by albertputrapurnama** [comment]
I'm experiencing the same problem?

**Comment by Salakar** [comment]
Given the age of this issue and that Remote Config has had a major rework since; I'm going to close this issue in favour of trying the latest release.

**Comment by IchordeDionysos** [comment]
Ah yes, forgot to close this issue.

This is definitely fixed with the new version!
