### ISSUE TITLE
[cloud_firestore] orderBy doesn't return null values

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1204]
The [docs](https://firebase.google.com/docs/firestore/manage-data/data-types#value_type_ordering) say that null values should come first in any ordering.
However, the following stream excludes any documents where the `createdAt` field is null:
`Firestore.instance.collection('someCollection').orderBy('createdAt', descending: true).snapshots()`

How do I get all the documents, orders, including null values (first)?

Thanks!

**Comment by kroikie** [comment]
@Vluf

The issue at https://github.com/flutter/flutter/issues/38771 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by logbaseaofn** [comment]
I think this is an issue with the Firestore api not flutter. I am having the same issue on a React project.

**Comment by Salakar** [comment]
Given the age of this issue and that Firestore has had a major rework since; I'm going to close this issue in favour of trying the latest release.
