### ISSUE TITLE
[cloud_firestore] Unhandled Exception: type 'int' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1205]
This issue seems straight-forward but its not. My application works on most iphones and ALL android devices. But some iphones and ipads crash everytime they encounter this :
`Firestore.instance.collection('collection').document('documentname').get()`

It works if i use `snapshots()`. What is happening here? my app is already live and NOW i see this bug...

**Comment by kroikie** [comment]
@crushman1

The issue at https://github.com/flutter/flutter/issues/38696 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Hello - going to close this one due to lack of interaction. Please try on the latest version of the plugin as there has been many updates since this issue was created.

Please create a new issue if this still persists on the latest versions.
