### ISSUE TITLE
Cloud_Firestore Plugin Readme Documentation Error

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1206]
Readme documentation is incorrect for transactions which causes user errors.

The Readme is missing collection when setting the DocumentReference

_Running a transaction:
final DocumentReference postRef = Firestore.instance.document('posts/123');
..._

Should be:
final DocumentReference postRef = Firestore.instance.collection('myCollection').document('posts/123');

Thank you,

**Comment by kroikie** [comment]
@AriCohen8

The issue at https://github.com/flutter/flutter/issues/37591 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) (a new documentation hub has been created with update docs) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
