### ISSUE TITLE
cloud_firestore 'where' method has no 'isNotEqualTo' operator

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1211]
I think you should add , "isNotEqualTo" argument to "where" method in "cloud_firestore" package , it's very important argument , for example if I want to get all users having 'desc' != '', i can not , because we have not "isNotEqualTo" operator

I checked it out , its not exists. I hope you add it soon.
# Available argument

- isEqualTo
- isLessThan
- isLessThanOrEqualTo
- isGreaterThan
- isGreaterThanOrEqualTo
- arrayContains
- isNull

# **But there is NO "isNotEqualTo"**

_I tried to add it manually by editing some lines in package file , but it fail._

I hope u add it soon , its very important, and ty !

**Comment by 2n-1** [comment]
Cloud Firestore Database (not the Flutter plugin) does not support inequality checks.

https://github.com/flutter/flutter/issues/36980#issuecomment-515639561
