### ISSUE TITLE
[cloud_firestore] Facing issues while fetching data from Firestore.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1225]
I have two application. From one application all the clients can upload the data to Firestore.
The data which the client uploads will be stored in the form of `user/user_uid/form/formId/data`
```
user = collection
user_uid = document
form = collection
formId = document
data = name,address,email...
```
The other application is on the administrator side. The Administrator should be able to see all the data from all the clients by fetching details like `user/user_uid`. But I'm having issues in fetching the data that way, it always returns null. If  I add data in the form of `user/user_uid/data` it's fetching data, but not fetching in the earlier way.

**Comment by kroikie** [comment]
@LuciferAJ

The issue at https://github.com/flutter/flutter/issues/34333 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Closing this one - please create an issue on the SDK your admin interface is using if this is still a problem.
