### ISSUE TITLE
[cloud_firestore] metadata is missing for QuerySnapshot class

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1228]
## Use case
I have disabled the persistent mode in my app and I am looking for solution to identify unsuccessful firestore read. 
Seems like firestore always returns successful result (via Future / Stream) in query case.
The metadata should contain isFromCache property which can indicate if the read was failed or not.
The metadata is already implemented in other sdks such as js,dart (html) and more (see references)

https://pub.dev/documentation/firebase/latest/firebase_firestore/QuerySnapshot-class.html
https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot

## Proposal
Please implement it, Thanks a lot

**Comment by kroikie** [comment]
@shasaf1986

The issue at https://github.com/flutter/flutter/issues/32789 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey all, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) (metadata is now available on the QuerySnapshot class) - which has been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
