### ISSUE TITLE
[Firebase Analytics] Show more data in debugView console

### ISSUE THREAD

**Issue by logemann** [FirebaseExtended/flutterfire#1246]
**Is your feature request related to a problem? Please describe.**
Feature request result from issue: #1245 

**Describe the solution you'd like**
I would like to see the "parameter" screenName of the even "screen_view" in the DebugConsole. Just showing screen_view in a debug doesnt reveal where a user a clicked in terms of screen transitions. Dont know if its even worth extending this feature request to SteamView->Events.

**Additional context**
Possible DebugView with the extended information (assuming Dashboard was clicked via NamedRoute)

![screen](https://user-images.githubusercontent.com/346353/66722853-baa97300-ee12-11e9-8a5e-5bf73ef0ced4.png)

**Comment by Ehesp** [comment]
Hey, unfortunately this is out of the control of this plugin. You're best creating your own log event to handle this as you'd need to pass in custom information about what was clicked.

Closing but happy to help in here.
