### ISSUE TITLE
[firebase_admob] Bad Androidmanifex.xml, also crashes android app

### ISSUE THREAD

**Issue by relativityboy** [FirebaseExtended/flutterfire#1247]
**Describe the bug**
In`AndroidManifest.xml` file within lib `com.google.android.gms.ads.APPLICATION_ID` meta-data causes AndroidStudio to error when building.

**To Reproduce**
Add admob to project
1. setup admob basics as per readme (incl adding app id to project's Androidmanifex.xml)
2. add banner add to main as per example codes
4. Attempt to build app. See app fail to build with error message citing two instances of *com.google.android.gms.ads.APPLICATION_ID*, one in the app AndroidManifest.xml file, the other in the lib's AndroidManifest.xml file.

**Expected behavior**
App builds and launches successfully

**Additional context**
Using 0.9.0+7

**Comment by blasten** [comment]
Can you provide the exact error message that you got? Also, would you mind pasting the content of AndroidManifest.xml?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
