### ISSUE TITLE
[firebase_auth] use existing Google Login information on iOS

### ISSUE THREAD

**Issue by kwiesmueller** [FirebaseExtended/flutterfire#1248]
**Is your feature request related to a problem? Please describe.**
We expected the firebase_auth Google Login to behave comparable to Android on iOS devices. So when a user is already logged in either on the iOS or the browser level, it should not require the user to manually go through the Google Login flow.
Some testers reported this as unexpected and also mentioned that their password manager (1Password) was not capable of filling the information in the opened WebView.

**Describe the solution you'd like**
We would like the firebase_auth login flow to use the local browser or system login information where available.

**Comment by Salakar** [comment]
Not sure this is something we can support directly on FlutterFire, we just wrap the underlying native Firebase SDKs. If this is something you still need then please raise a feature request with Firebase: https://firebase.google.com/support/troubleshooter/report/features
