### ISSUE TITLE
[firebase_admob] Only test ads are showing on iOS release.

### ISSUE THREAD

**Issue by DSancTech** [FirebaseExtended/flutterfire#1251]
It appears that although the correct adUnitID is provided, the iOS version of my app is only displaying the test ads. Has been tested on several different devices and none of them are properly showing ads, however when running the Android version the ads are showing up perfectly.
Please fix this or give an idea of some workaround.  App is currently published on the App Store so I'm in need of fixing it.
Thank you.

**Comment by Ehesp** [comment]
Hi @DSancTech please can you try upgrading to the latest version of Flutter & the plugin. A lot has changed since this issue was created.

If you still experience the problem, please create a new issue following the issue template
