### ISSUE TITLE
This version of firebase_auth will break your Android build

### ISSUE THREAD

**Issue by ArtfulDodgerB92** [FirebaseExtended/flutterfire#1252]
```
[   +1 ms]          *********************************************************
[   +1 ms] WARNING: This version of firebase_auth will break your Android build if it or its dependencies aren't compatible with AndroidX.
[   +1 ms]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
```

Getting this warning across all my applications, no matter what version of firebase_auth I try to use.  One app will run fine, but will not build a release apk because of this error.   Another app will not run at all, crashing at "Waiting for observatory port to be available..." and will not compile a release apk either because of the androidx error above.

This is a very serious problem, and I have been waiting to upload a new version of my app to the store for over a week now and I simply cannot because of this error.

**Comment by elmariocarlos** [comment]
@ArtfulDodgerB92 I'm having the same issue but you should add your pubspec just in case. I'm using latest version.

**Comment by iapicca** [comment]
Hi @elmariocarlos 
If you are still experiencing this issue 
with newest version (came out yesterday, literally) `firebase_auth 0.15.0+1`
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by elmariocarlos** [comment]
It seems to have gone, so I believe we are OK to close =)
