### ISSUE TITLE
[firebase_auth] Can't handle firebase auth exception when using phone auth

### ISSUE THREAD

**Issue by redbayoub** [FirebaseExtended/flutterfire#1253]
Hi, 
Can't Handel firebase auth exception when using phone auth
```
 final PhoneVerificationFailed verifiedFailed =
          (AuthException authException) {
        // Todo show error message
        print(authException.message);
      };
```

the message contains error code TOO_SHORT 
but authException.code return invalidCredentials

dependencies: 
 firebase_auth: ^0.11.1+3

# Temporally fix
```
String extract_error_code_from_message(AuthException authException) {
  int startIndexPernthesis=authException.message.lastIndexOf("[");
  int endIndexPernthesis=authException.message.length;

  return authException.message.substring(startIndexPernthesis+2,endIndexPernthesis-2);
}
```

**Comment by BondarenkoStas** [comment]
@redayoub47 can you please try it with firebase_auth 0.14.0+5 to check was it solved there or not?

**Comment by Salakar** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
