### ISSUE TITLE
[cloud_firestore] Look Up function

### ISSUE THREAD

**Issue by HannHank** [FirebaseExtended/flutterfire#1261]
Hello, I am very new to flutter and Firestore. I am trying to build a lookUp function to see, if a certain Ticket exists. 
`       This is my function:

        var check = databaseReference
        .collection('Tickets')
        .document(qrText);
        print(check.path);
        print(check.get().then((snapshot){
        print(snapshot.data);
        if(snapshot.data != null){
        print("Ticket was found");
        }else{
        print("Ticket not found");
        print(check.path);
       }
    }));

But the Problem with this function is, that I am setting the Path to the document with a variable.
`.document(qrText);`
For some reason the "snapshot.data" is null. So I log the path of the document like this:
`print(check.path);`
And this shows: "Ticket/asdkw23jl3j" which is the correct path to the document. I could not really figure out whats going on, so I tried to set the path of the document like this:
`.document("asdkw23jl3j");` 
And now the Ticket can be found and the Terminal displays the same path as before. This make no sens to me, because the path of the Ticket is both times equal. 

Thanks in advanced.

**Comment by HannHank** [comment]
I think the problem is with the databaseReference: 
var check = databaseReference
.collection('Tickets')
.document(qrText);

**Comment by Ehesp** [comment]
Hi @HannHank you're referencing 2 different databases here, Firestore & Database. Please could you try upgrading the plugin version to latest as there's been a lot of changes since this issue was created.

Thanks!
