### ISSUE TITLE
[Firebase Storage] List all files of a folder, bucket, ect

### ISSUE THREAD

**Issue by MilesAdamson** [FirebaseExtended/flutterfire#1270]
**Is your feature request related to a problem? Please describe.**
I need a way to get the filename of all files within my storage, and/or all the files within a folder. I would like to store my files with a certain format, such as `noun-id-datetime.jpg`, and download all 
relevant files which start with `noun-id` based on the "noun" my client is looking at.  

**Describe the solution you'd like**
I would like simply a `listAll()` method for a given bucket or folder within the bucket, which returns a list of strings which are the file names. Without this, I cannot download a group of files without knowing beforehand exactly what their file names are.

**Comment by BondarenkoStas** [comment]
Hi @MilesAdamson, I'm going to close the issue to avoid duplication, please follow it in https://github.com/FirebaseExtended/flutterfire/issues/83 and upvote, PR is in progress.
