### ISSUE TITLE
Notification not working on Chinese Custom ROM like oppo, vivo, huawei, one plus...

### ISSUE THREAD

**Issue by lyseiha** [FirebaseExtended/flutterfire#1272]
Please Help. i stuck 4 days already.

**Comment by BondarenkoStas** [comment]
@lyseiha Can you explain in more details, do you mean firebase_messaging? Which version do you use, is there any error or they simply don't come?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by ashishalagiya** [comment]
When application kill ( oppo and vivo device ) notification not receive. If app in background then receive. Can you help me on that ?

**Comment by Farrukh381** [comment]
Make sure you app is in protected apps category on these phones it will work.
