### ISSUE TITLE
[firebase_core] app name can only contain alphanumeric

### ISSUE THREAD

**Issue by bardram** [FirebaseExtended/flutterfire#1273]
**Describe the bug**
When adding support for Firebase to my Flutter app, on iOS I get the following exception:

```
Terminating app due to uncaught exception 'com.firebase.core', reason: 'App name can only contain alphanumeric, hyphen (-), and underscore (_) characters'
```

Looking at issue #928 I was wondering if this had to do with the iOS bundle ID. So I changed this to comply to the above (using hypens instead of dots). But this did not solve the issue.

I also tried to adjust the iOS "Bundle display name". But this didn't help either.

So - my question is; what is the "App name"? And how can I change it?

**To Reproduce**

Well - since I'm not sure what the "App name" is, then it's hard to specify. But - I mainly added support for Firebase in my app following the instructions at 

https://firebase.google.com/docs/flutter/setup#add_flutterfire_plugins

**Comment by iapicca** [comment]
Hi @bardram 
you might want to take a look to this possible [solution](https://github.com/flutter/flutter/issues/13518#issuecomment-351910058)
I'm closing the current one as duplicate,
please follow up in the issue you have linked in the initial post.
If you disagree please write in the comments
and I will reopen it.
Thank you
