### ISSUE TITLE
[firebase_messaging] Android only: allow launching app immediately when notification arrives

### ISSUE THREAD

**Issue by atsu85** [FirebaseExtended/flutterfire#1274]
**Is your feature request related to a problem? Please describe.**
I'd like Android app to be opened when push notification is received (I know this can't be implemented on iOS, but i need it for Android only).
This feature request is related to [this SO question that isn't using Flutter](https://stackoverflow.com/questions/37554274/open-app-on-firebase-notification-received-fcm) (I'm not Android developer).
> I know I can set `click_action` but that's only for customizing which activity will start on notification click, I need something that will start automatically when notification is received.

**Describe the solution you'd like**
I'd like my app to be opened immediately on Android devices instead of creating just notification that could be clicked to open my app

**Additional context**

From answer [linked SO question](https://stackoverflow.com/questions/37554274/open-app-on-firebase-notification-received-fcm) it is said, that 
> To automatically open an application via FCM you need to use a data-message

And my message received via configure callbacks have the data-message format, as suggested in that answer:
`{"data" : { "key1" : "value1"}}`

P.S. i'm not sending them via FCM console, but from my java backend application using firebase-admin sdk provided by FCM

**Comment by Salakar** [comment]
> I know I can set click_action but that's only for customizing which activity will start on notification click, I need something that will start automatically when notification is received.

This is not possible, starting an app into the foreground can only happen on user interaction.
