### ISSUE TITLE
[firebase_messaging] handle deeplink with custom uri scheme 

### ISSUE THREAD

**Issue by Sp4Rx** [FirebaseExtended/flutterfire#1275]
I want to handle deeplinks(click actions) with my custom uri scheme so I can navigate to a page in the app without redirecting it to the browser.

Thus I need to implement a custom event listener so that I can get the url which was set from the firebase console and process it manually. 

This is already documented [here](https://firebase.google.com/docs/in-app-messaging/modify-message-behavior?platform=android#implement_an_event_listener_for_card_interactions) for native IOS and Android. But there is no similar api for the flutter version.

If possible please update the library ASAP or provide a workaround.

**Comment by Salakar** [comment]
Not sure if this is something we can support yet, but we'll keep it in mind when we look into reworking In App Messaging.
