### ISSUE TITLE
[firebase_ml_vision] (textRecognizer) <ios problem>

### ISSUE THREAD

**Issue by AtillaPehlivan** [FirebaseExtended/flutterfire#1276]
**Describe the bug**

when i using the  textRecognizer.processImage(visionImage)  ,
android results is fine  but ios result is null, i don't receive any recognized string 

Sample Code : 

     File image = await ImagePicker.pickImage(source: ImageSource.gallery);
      visionImage = FirebaseVisionImage.fromFile(image);
      visionText = await textRecognizer.processImage(visionImage);
      print(visionText.text); // this line works on android platform bu ios platform dont return any string

    

** pubspec.yaml
`firebase_ml_vision: ^0.9.2+2`

**Podfile

```
target 'Runner' do
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/MLVisionTextModel'
pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
end
```

**Comment by iapicca** [comment]
Hi @AtillaPehlivan 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by AtillaPehlivan** [comment]
hi @iapicca  thanks for your interest 
i couldn't `FirebaseVision.instance.textRecognizer().processImage(visionImage);` code on ios 
but i am using the 
`FirebaseVision.instance.cloudTextRecognizer().processImage(visionImage);`  code temporarily on my ios app , cloudTextRecognition run on two platform as expected 

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-TR)
    • Flutter version 1.9.1+hotfix.6 at /Users/atilapehlivan/Desktop/flutter1.5/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/atilapehlivan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Users/atilapehlivan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/atilapehlivan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

flutter run --verbose 
this command don't give any error , my app launched  as expected

```
[        ] Updating files
[ +227 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Android SDK built for x86... (completed in 2,477ms, longer than expected)
[        ] Synced 1.5MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +2 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xa178c510, isolate: {type: @Isolate, fixedId: true,
id: isolates/1273464644891715, name: main.dart$main-1273464644891715, number: 1273464644891715}}]}
[        ] <- accept
[        ] Connected to _flutterView/0xa178c510.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:51009/hUnKNFCzECo=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

**Comment by iapicca** [comment]
HI @AtillaPehlivan 
I'm glad to see that you solved the issue,
thank you for letting me know

**Comment by Alecsplus** [comment]
Also in my case I have this problem only on iOS devices.
Text is recognized only with cloudTextRecognizer and not with textRecognizer method (with the same image). 

This is a really great problem, because cloud recognition needs billing.

What we can do to to solve it?

Thanks in advance

**Comment by Waaheeda** [comment]
I am also facing same issue is it iOS 13 issue?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by junnyea** [comment]
Hi,

I am also facing the same issue as @AtillaPehlivan .

[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-SG)
    • Flutter version 1.17.0 at /Users/hoongjun/Developer/flutter
    • Framework revision e6b34c2b5c (2 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hoongjun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2017.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.44.2)
    • VS Code at /Users/hoongjun/Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone                    • 00008020-001D44A611EA002E            • ios         • iOS 13.4.1

It is quite easy to replicate. As mentioned by @AtillaPehlivan , this code return empty.

> FirebaseVision.instance.textRecognizer().processImage(visionImage);
