### ISSUE TITLE
[firebase_auth] Add support for atomic transactions

### ISSUE THREAD

**Issue by guilhermeagostinelli** [FirebaseExtended/flutterfire#1277]
**Is your feature request related to a problem? Please describe.**
When creating a new user account with [firebase_auth](https://pub.dev/packages/firebase_auth) (let's say operation A), usually there is a need for storing other profile information (e.g. age, profile photo) with [cloud_firestore](https://pub.dev/packages/cloud_firestore) (operation B) using the UID of the created user in A as the document id of B. Ideally this process should happen in an atomic way such that if B fails, A isn't performed (or is rolled back).

**Describe the solution you'd like**
It would be nice if `firebase_auth` had a transaction function for performing atomic operations, with a commit trigger to consolidate it - in the above example, the transaction should be comitted only if B is successful. Also, the user creation functions should be able to return the UID beforehand i.e. before the transaction is committed.

**Comment by Abed1230** [comment]
How do you guys tackle this problem right now? Would be great if someone could give me some ideas

**Comment by jrgilbert74** [comment]
I agree this would be helpful in lots of scenarios.

**Comment by Salakar** [comment]
Hey all, appreciate you raising this feature request but we'd need the underlying Firebase SDKs for Web, Android & iOS to support this before FlutterFire could. I'd suggest raising a feature request [here](https://firebase.google.com/support/troubleshooter/report/features) with the Firebase team if this is something you'd like to see.
