### ISSUE TITLE
Error: PlatformException(error, FirebaseApp with name [DEFAULT] doesn't exist. , null)

### ISSUE THREAD

**Issue by Zizu098** [FirebaseExtended/flutterfire#1278]
flutter/flutter I try to connect the app with firebase but there is an error message : I/flutter (30904): Error: PlatformException(error, FirebaseApp with name [DEFAULT] doesn't exist. , null) and i added apply plugin: 'com.google.gms.google-services'

**Describe the bug**

**To Reproduce**
2. '...'
4. See error or incorrect behavior

**Expected behavior**

**Additional context**

**Comment by BondarenkoStas** [comment]
I wonder if `flutter clean` will help as in https://github.com/flutter/flutter/issues/28003.
About firebase, did you mean firebase_database?
Will leave a link to similar issue https://github.com/FirebaseExtended/flutterfire/issues/1299.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by elliott-io** [comment]
I'm having the same problem. Here is my `flutter doctor -v`

[✓] Flutter (Channel master, v1.14.2-pre.51, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.14.2-pre.51 at /Users/elliottio/Documents/dev/flutter
    • Framework revision ec1044a877 (7 hours ago), 2020-01-17 19:19:33 -0800
    • Engine revision ecc74c966d
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f96c48307d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro             • 77541578-0043-46D2-B8C6-62A29B04577D • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by AlexEAA** [comment]
I'm having the same problem. Here is my flutter doctor -v

[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.13.6 17G10021, locale ru-RU)
    • Flutter version 1.13.6 at /Users/seoinetru/Downloads/flutter
    • Framework revision 659dc8129d (3 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/seoinetru/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Users/seoinetru/Downloads/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (4 available)
    • SM G975F                     • R58M351M10R   • android-arm64  • Android 10
      (API 29)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 10
      (API 29) (emulator)
    • Chrome                       • chrome        • web-javascript • Google
      Chrome 79.0.3945.117
    • Web Server                   • web-server    • web-javascript • Flutter
      Tools

**Comment by mziyandajoko** [comment]
apply plugin: 'com.google.gms.google-services'

Somehow when you create your App on Firebase they no longer have this above line so you can communicate with the Firebase,    at the bottom of app's Gradle file and then clean and rebuild the project add the above line

**Comment by ChiragKushwaha** [comment]
> apply plugin: 'com.google.gms.google-services'

yeah it worked for me thanks 👍
