### ISSUE TITLE
[Firebase Storage] getDownloadURL return type

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#1280]
Why is the return type for [getDownloadURL](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_storage/lib/src/storage_reference.dart#L141) a _dynamic_ instead of a _String_?
```dart
  /// Asynchronously retrieves a long lived download URL with a revokable token.
  /// This can be used to share the file with others, but can be revoked by a
  /// developer in the Firebase Console if desired.
  Future<dynamic> getDownloadURL() async {
    return await FirebaseStorage.channel.invokeMethod<dynamic>(
        "StorageReference#getDownloadUrl", <String, String>{
      'app': _firebaseStorage.app?.name,
      'bucket': _firebaseStorage.storageBucket,
      'path': _pathComponents.join("/"),
    });
  }
```

In practice, the _runtimeType_ seems to be _String_.  Could it be something else?

**Comment by iapicca** [comment]
Hi @awhitford 
You might want to check the documentation regarding [invokeMethod](https://api.flutter.dev/flutter/services/MethodChannel/invokeMethod.html)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by awhitford** [comment]
Please reopen.  I don't understand why the return type is not well documented.

The implementation would have two tiny changes:
```dart
  /// Asynchronously retrieves a long lived download URL with a revokable token.
  /// This can be used to share the file with others, but can be revoked by a
  /// developer in the Firebase Console if desired.
  Future<String> getDownloadURL() async {
    return await FirebaseStorage.channel.invokeMethod<String>(
        "StorageReference#getDownloadUrl", <String, String>{
      'app': _firebaseStorage.app?.name,
      'bucket': _firebaseStorage.storageBucket,
      'path': _pathComponents.join("/"),
    });
  }
```

Note that the [Java API](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageReference.html#getDownloadUrl()) has a return type is a [`Uri`](https://developer.android.com/reference/android/net/Uri.html), but the Flutter/Dart API seems to be returning a `String`.  Should it also be returning a [`Uri`](https://api.dart.dev/stable/2.6.0/dart-core/Uri-class.html)?

The [Swift API](https://firebase.google.com/docs/reference/swift/firebasestorage/api/reference/Classes/StorageReference#downloadurlcompletion:) seems to indicate that maybe the return value is either a URL (success) or an Error -- so then wouldn't a `Future<String>` or `Future<Uri>` be a fine equivalent?

If _dynamic_ is appropriate because the return type may be _String_ or something else, the developer needs to know to handle it appropriately.  Right now, I am assuming that I am getting a String, but I don't like to assume.

**Comment by awhitford** [comment]
I appreciate the _thumbs up_ support.  This looks like a trivial fix; I'm surprised that this is still outstanding.  Is there a way that I can help with a pull request?

**Comment by Salakar** [comment]
On the latest release getDownloadURL does return `Future<String>`: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_storage/firebase_storage/lib/src/reference.dart#L57
