### ISSUE TITLE
[firebase_messaging ] ios also does not sound when notification comes

### ISSUE THREAD

**Issue by hsnbsst** [FirebaseExtended/flutterfire#1281]
**Describe the bug**
ios also does not sound when notification comes

**Expected behavior**
beep when notification comes

**Comment by iapicca** [comment]
Hi 
provide your `flutter doctor -v`
also to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
