### ISSUE TITLE
[firebase_messaging] Example for handling onBackgroundMessage

### ISSUE THREAD

**Issue by sm-tester** [FirebaseExtended/flutterfire#1283]
Need example for background message handling, why you don't add callback to "onBackgroundMessage" in your example? There are bug

**Comment by QuentinSc** [comment]
Up! Really need that :)

**Comment by shinriyo** [comment]
Me too.
I created Kotlin file. why>

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. We've added tons of documentation with examples :)

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
