### ISSUE TITLE
[firestore] API not contain docSnap.readTime()

### ISSUE THREAD

**Issue by logemann** [FirebaseExtended/flutterfire#1285]
**Describe the bug**
the DART API of DocumentSnapshot doesnt define readTime() as described in https://googleapis.dev/nodejs/firestore/latest/DocumentSnapshot.html

**To Reproduce**
nothing to reproduce

**Expected behavior**
same APIs for each platform

**Additional context**

**Comment by Ehesp** [comment]
Hello. The `readTime` value of a document snapshot is available to the admin SDKs only at this time, so it's not possible to pull this value into the plugin.
