### ISSUE TITLE
[firebase_admob] mediation

### ISSUE THREAD

**Issue by glennmichaelmejias** [FirebaseExtended/flutterfire#1301]
I'd like to request mediation in admob, or is already possible and simple to implement in flutter?

**Comment by dasebasto** [comment]
Is it confirmed that AdMob mediation does not work with firebase_admob, even if the required native SDKs  (e.g. Facebook Audience Network) are integrated and initialized with basic flutter plugins?

After all, the parent ad view is always created by AdMob so no specific code should be needed to support showing as views coming from other SDKs, right?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
