### ISSUE TITLE
[firebase_dynamic_links] rename class PendingDynamicLinkData without Pending...

### ISSUE THREAD

**Issue by logemann** [FirebaseExtended/flutterfire#1305]
**Is your feature request related to a problem? Please describe.**
Not a problem but perhaps confusion for people new to Futures

**Describe the solution you'd like**
rename the class to DynamicLinkData. The fact that it CAN be wrapped in a Future and might be pending should not be the reason to name it Pending.... In theory every object could be pending. At the end its a normal class which has data at some point.

**Additional context**

**Comment by Ehesp** [comment]
Hi @logemann - I'm going to close this due to inactivity. There are no plans to change this right now util the API is reviewed. Thanks.
