### ISSUE TITLE
[firebase_auth] listener for user changes

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#1308]
I have widgets that show user information, like the `displayName`.  I have a _User Profile_ screen that allows one to change their name.  When that happens, `updateProfile` and `reload` are called like:
```
          await widget.user
              .updateProfile(UserUpdateInfo()..displayName = newDisplayName);
          await widget.user.reload();
```

Consider the case where the user is on _Screen A_ which has widgets that show user information, like the displayName.  Then the user chooses to go to the _User Profile_ screen, edits the user's display name, and then closes the _User Profile_ screen to return to _Screen A_.  _Screen A_ is not being refreshed to reflect the new display name.

Widgets referencing the `FirebaseUser` are wrapped in a `StreamBuilder` (and I've also experimented with using a [`StreamProvider`](https://pub.dev/documentation/provider/latest/provider/StreamProvider-class.html)) that is linked to the Stream from [`onAuthStateChanged`](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/onAuthStateChanged.html).

`onAuthStateChanged` seems to be limited to _Sign In_ and _Sign Out_ events.  There does not seem to be a way to hook into getting updates made by `updateProfile` or `reload`.

This results in stale information being displayed for the user that can cause confusion (and possibly bugs).

I would like to see `onAuthStateChanged` triggered also for `updateProfile` and `reload` events (and maybe even other operations such as `reauthenticateWithCredential`).  Alternatively, if `onAuthStateChanged` should remain limited to _Sign In_ and _Sign Out_ events, provide an alternate Stream to listen to.

**Comment by erf** [comment]
I also would like to see `FirebaseAuth.instance.onAuthStateChanged` triggered on `FirebaseUser.updateProfile`.

**Comment by maguro** [comment]
My preference would be to add a new method, `onProfileChanged`.

However, I would like `onAuthStateChanged` to be triggered when the user's email has been verified.

**Comment by Ehesp** [comment]
On React Native Firebase we added a method called `onUserChanged` which handles this, so it's possible.

**Comment by awhitford** [comment]
I ended up solving this by using [firebase_user_stream](https://pub.dev/packages/firebase_user_stream), written by @feinstein.  See #717 for more details.

**Comment by Ehesp** [comment]
As part of https://github.com/FirebaseExtended/flutterfire/issues/2582 we've introduced a `userChanges` stream, which triggers whenever auth state, id token or profile changes occur. Essentially, this acts as a way to obtain realtime changes on currently stateless functionality (such as `updateProfile`).
