### ISSUE TITLE
[firebase_auth] The method 'signInWithPhoneNumber' isn't defined for the class 'FirebaseAuth'.

### ISSUE THREAD

**Issue by Sreejith93** [FirebaseExtended/flutterfire#1310]
The method 'signInWithPhoneNumber' isn't defined for the class 'FirebaseAuth'.
Try correcting the name to the name of an existing method, or defining a method named 'signInWithPhoneNumber'.dart(undefined_method)

signInWithPhoneNumber function is not working in latest firebase_auth.fore mobile number authentication

**Comment by BondarenkoStas** [comment]
@Sreejith93 which version of firebase_auth do you use? Can you provide a code example which reproduces the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by ToxaDev** [comment]
`firebase_auth: ^0.15.3+1`

Function `signInWithPhoneNumber` is gone;

![image](https://user-images.githubusercontent.com/11254917/72926615-6bea6e00-3d5d-11ea-8825-63d983aa174a.png)
