### ISSUE TITLE
Add support for FieldPath for where-clause querying to Firestore Plugin.

### ISSUE THREAD

**Issue by t-cun** [FirebaseExtended/flutterfire#1311]
Querying Firestore doesn't yield results when the Field name consists special characters.
For example abc@gmail.com which consists '.'
Can you include a work around like including ` around the Field name so that it treats special characters as Normal one.

This issue was previously closed without any comments/updates. Re-opening as the issue still exists.

Reference:
https://github.com/flutter/flutter/issues/22712
https://github.com/FirebaseExtended/flutterfire/issues/626

**Comment by jyardin** [comment]
This is really annoying. Is there any way to circumvent this problem ?

**Comment by zephyo** [comment]
encountering this, does this have a fix yet?

**Comment by Ehesp** [comment]
You can use the `FieldPath` class to provide a path/key with special characters: https://github.com/FirebaseExtended/flutterfire/blob/29eb495bddafe3965e3b7f5f097d5122bf5e2d1a/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/field_path.dart#L7

Will close, but this should be documented.

**Comment by Ehesp** [comment]
Re-opening to track with testing

**Comment by Salakar** [comment]
Hey all, as part of our on-going work for #2582, this has been implemented in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
