### ISSUE TITLE
[firebase_admob] AdRequestBuilderFactory.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by kw2019ltd** [FirebaseExtended/flutterfire#1313]
flutter build apk
```
Running "flutter pub get" in plants_price_flutter_app... 20.0s
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
To generate an app bundle, run:
flutter build appbundle --target-platform android-arm,android-arm64
Learn more on: https://developer.android.com/guide/app-bundle
To split the APKs per ABI, run:
flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
Learn more on: https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle... 11.7s
Resolving dependencies... 128.4s (!)
Running Gradle task 'assembleRelease'...
```
**Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.**

flutter doctor -v
```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
• Flutter version 1.9.1+hotfix.5 at /home/cirrus/sdks/flutter
• Framework revision 1aedbb1 (4 days ago), 2019-10-17 08:37:27 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /opt/android-sdk-linux
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
• All Android licenses accepted.

[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] Connected device
! No devices available
```

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/1215

**Comment by HumbleCarl** [comment]
Did you solve it? @kw2019ltd

**Comment by kw2019ltd** [comment]
no flutter team should solve it

**Comment by HumbleCarl** [comment]
Oooh it is still a bug.

**Comment by iapicca** [comment]
Hi @kw2019ltd
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_admob?
thank you

**Comment by zpaya** [comment]
Hi
I had this issue and logged with Flutter but was closed with comment to solve by Firebaseflutter.
Here are the complete log and issue details - https://github.com/flutter/flutter/issues/56234

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
