### ISSUE TITLE
Any Idea when the fireflutter plugins are going to be available for web also?

### ISSUE THREAD

**Issue by copypasteearth** [FirebaseExtended/flutterfire#1315]
Im wondering about firestore and auth mostly but probably messaging too when they will be available for web and mobile because I am using all of these 3rd party packages and they don't even have all of the functionality.  Thank you for your time

**Comment by iapicca** [comment]
Hi @copypasteearth
you might want to look at this [comment](https://github.com/flutter/flutter/issues/32637#issuecomment-495771423).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
