### ISSUE TITLE
[firebase_auth] Link accounts with different providers

### ISSUE THREAD

**Issue by dacxjo** [FirebaseExtended/flutterfire#1318]
I'm developing a flutter app that requires Google Facebook and email/password auth. I'm using the latest firebase_auth,google_sign_in and facebook_login plugins to develop this. The trouble come when I try to sign in with an account with the same email , it throws the PlatformException **ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL** when I'm calling the method :

`auth.signInWithCredential(credential)`

To be clear, this is when user sign in with Google and then sign in with Facebook using the same email or vice versa, the logic is that the same account has to be linked to both providers.

So reading the source code of Flutter auth, the comments shows:

>  Resolve this case by calling [fetchSignInMethodsForEmail] and then asking the user to sign in using one of them

So for this I need the email of Facebook or Google account but the Stacktrace or the Error object doesn't return any account detail or email.

I have found a link where someone explains how to do this but it seems to be the JS api, where the error object has **error.email** and with that you can use the **fetchSignInMethodsForEmail**

[This is the link](https://stackoverflow.com/questions/39459524/handling-linking-accounts-in-firebase/39524516#39524516) 

After several days and Google searches,  I don't found the way to do this using the flutter dart firebase_auth, the error object in the PlatFormException does not return an error.email and I don't found examples of account linking using linkwidthcredentials and firebase_auth.

I'm pretty new on Flutter/Dart , I don't know if there is already some way to handle this or a Workaround , but it is necessary to include it in the firebase_auth package , this way of **linkwithcredentials** after return this PlatformError.

**Comment by HaoCherHong** [comment]
After some hours I figured it out. For now you have to implement some of the flow yourself.
I simplified some of the generic part and error handling to make it straightforward:

```dart
final facebookLogin = FacebookLogin();
// Remember you MUST login with email permission
final loginResult = await facebookLogin.logIn(['email']);
final credential = FacebookAuthProvider.getCredential(accessToken: loginResult.accessToken.token);
try {
  // Assume we'll login with an error that causes `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL`
  await _firebaseAuth.signInWithCredential(credential);
} on PlatformException catch (e) {
  if (e.code != 'ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL')
    throw e;
  // Now we caught the error we're talking about, we get the email by calling graph API manually
  final httpClient = new HttpClient();
  final graphRequest = await httpClient.getUrl(Uri.parse("https://graph.facebook.com/v2.12/me?fields=email&access_token=${loginResult.accessToken.token}"));
  final graphResponse = await graphRequest.close();
  final graphResponseJSON = json.decode((await graphResponse.transform(utf8.decoder).single));
  final email = graphResponseJSON["email"];
  // Now we have both credential and email that is required for linking
  final signInMethods = await FirebaseAuth.instance.fetchSignInMethodsForEmail(email: e.email);
  // Assume that signInMethods[0] is 'google.com'
  final authResult = ....;  // ... do the Google sign-in logic here and get the Firebase AuthResult
  if (authResult.user.email == e.email) {
    // Now we can link the accounts together
    await authResult.user.linkWithCredential(e.credential);
  }
}
```

The result would looks like this after you successfully linked it
![image](https://user-images.githubusercontent.com/2157335/69971900-925d0b80-155b-11ea-931f-9a2b45605123.png)

**Comment by jeanadam** [comment]
> 
> 
> After some hours I finally figured it out. For now you have to implement some of the flow yourself.
> I simplified some of the generic part and error handling to make it straightforward:
> 
> ```dart
> final facebookLogin = FacebookLogin();
> // Remember you MUST login with email permission
> final loginResult = await facebookLogin.logIn(['email']);
> final credential = FacebookAuthProvider.getCredential(accessToken: loginResult.accessToken.token);
> try {
>   // Assume we'll login with an error that causes `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL`
>   await _firebaseAuth.signInWithCredential(credential);
> } on PlatformException catch (e) {
>   if (e.code != 'ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL')
>     throw e;
>   // Now we caught the error we're talking about, we get the email by calling graph API manually
>   final httpClient = new HttpClient();
>   final graphRequest = await httpClient.getUrl(Uri.parse("https://graph.facebook.com/v2.12/me?fields=email&access_token=${loginResult.accessToken.token}"));
>   final graphResponse = await graphRequest.close();
>   final graphResponseJSON = json.decode((await graphResponse.transform(utf8.decoder).single));
>   final email = graphResponseJSON["email"];
>   // Now we have both credential and email that is required for linking
>   final signInMethods = await FirebaseAuth.instance.fetchSignInMethodsForEmail(email: e.email);
>   // Assume that signInMethods[0] is 'google.com'
>   final authResult = ....;  // ... do the Google sign-in logic here and get the Firebase AuthResult
>   if (authResult.user.email == e.email) {
>     // Now we can link the accounts together
>     await authResult.user.linkWithCredential(e.credential);
>   }
> }
> ```
> 
> The result should looks like this after you successfully linked it
> ![image](https://user-images.githubusercontent.com/2157335/69971900-925d0b80-155b-11ea-931f-9a2b45605123.png)

Gizz!, thank you a lot.

**Comment by HaoCherHong** [comment]
> Gizz!, thank you a lot. I had to fix a bit of the "e.email" and "e.credential", but all good.

thanks for reminding, just edited  the `e.` in the comment.

**Comment by DanielZanchi** [comment]
but this way you are then asked to login with Google (or the other method), that the user is not using.

**Comment by Ehesp** [comment]
Just to confirm, the issue here is that the error returned from the rejection should have a `.email` property on it?

**Comment by HaoCherHong** [comment]
> but this way you are then asked to login with Google (or the other method), that the user is not using.

No, the fetchSignInMethodsForEmail only returns sign in methods that user already used before.

**Comment by HaoCherHong** [comment]
> Just to confirm, the issue here is that the error returned from the rejection should have a `.email` property on it?

I think so

**Comment by DanielZanchi** [comment]
> > but this way you are then asked to login with Google (or the other method), that the user is not using.
> 
> 
> 
> No, the fetchSignInMethodsForEmail only returns sign in methods that user already used before.

Yes I know. 
But if I signup with Google, then I logout and want to login with Facebook (same email) I try to link the two accounts. But I need to login again with Google (since it needs the credentials of both), which is not very user friendly (login with Facebook and then with Google).

**Comment by HaoCherHong** [comment]
Seems to be the only way now. Our workaround is just ask user to login with available sign-in methods and have a page for linking all accounts, which reduces the chance that user get blocked when signing in. In other words, encourage users to link all credentials by their own.

**Comment by jazzbpn** [comment]
> After some hours I finally figured it out. For now you have to implement some of the flow yourself.
> I simplified some of the generic part and error handling to make it straightforward:
> 
> ```dart
> final facebookLogin = FacebookLogin();
> // Remember you MUST login with email permission
> final loginResult = await facebookLogin.logIn(['email']);
> final credential = FacebookAuthProvider.getCredential(accessToken: loginResult.accessToken.token);
> try {
>   // Assume we'll login with an error that causes `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL`
>   await _firebaseAuth.signInWithCredential(credential);
> } on PlatformException catch (e) {
>   if (e.code != 'ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL')
>     throw e;
>   // Now we caught the error we're talking about, we get the email by calling graph API manually
>   final httpClient = new HttpClient();
>   final graphRequest = await httpClient.getUrl(Uri.parse("https://graph.facebook.com/v2.12/me?fields=email&access_token=${loginResult.accessToken.token}"));
>   final graphResponse = await graphRequest.close();
>   final graphResponseJSON = json.decode((await graphResponse.transform(utf8.decoder).single));
>   final email = graphResponseJSON["email"];
>   // Now we have both credential and email that is required for linking
>   final signInMethods = await FirebaseAuth.instance.fetchSignInMethodsForEmail(email: email);
>   // Assume that signInMethods[0] is 'google.com'
>   final authResult = ....;  // ... do the Google sign-in logic here and get the Firebase AuthResult
>   if (authResult.user.email == email) {
>     // Now we can link the accounts together
>     await authResult.user.linkWithCredential(credential);
>   }
> }
> ```
> 
> The result should looks like this after you successfully linked it
> ![image](https://user-images.githubusercontent.com/2157335/69971900-925d0b80-155b-11ea-931f-9a2b45605123.png)

**How to resolve the issue in this case?**

      loginWithFacebook() async {
      String clientId = "6032xxxxx6393x4";
      String oauthRedirectUrl =
          "https://www.facebook.com/connect/login_success.html";
      String authToken = await Navigator.push(
        context,
        MaterialPageRoute(
            builder: (context) => CustomWebView(
                  selectedUrl:
                      'https://www.facebook.com/dialog/oauth?client_id=$clientId&redirect_uri=$oauthRedirectUrl&response_type=token&scope=email,public_profile,',
                ),
            maintainState: true),
      );

      if (authToken != null) {
        try {
          AuthCredential authCredential =
              FacebookAuthProvider.getCredential(accessToken: authToken);

          AuthResult user = await _auth.signInWithCredential(authCredential);
          if (user.additionalUserInfo != null) {
            AdditionalUserInfo af = user.additionalUserInfo;
            Map<String, dynamic> valMap = Map();
            af.profile.forEach((key, value) {
              valMap[key] = value;
            });

            final FirebaseUser currentUser = await _auth.currentUser();
            if (currentUser.uid != null && currentUser.uid.isNotEmpty) {
              saveWithNavigateCallback(currentUser.uid);
            }

            print(af);
          } else {
            print(user);
          }
        } catch (e) {
          print(e);
        }
      }
    }

**CustomWebview.dart**

      class CustomWebView extends StatefulWidget {
      final String selectedUrl;

      CustomWebView({this.selectedUrl});

      @override
      _CustomWebViewState createState() => _CustomWebViewState();
    }

    class _CustomWebViewState extends State<CustomWebView> {
      final flutterWebviewPlugin = new FlutterWebviewPlugin();

      @override
      void initState() {
        super.initState();

        flutterWebviewPlugin.onUrlChanged.listen((String url) {
          if (url.contains("#access_token")) {
            succeed(url);
          }

          if (url.contains(
              "https://www.facebook.com/connect/login_success.html?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied")) {
            denied();
          }
        });
      }

      denied() {
        Navigator.pop(context);
      }

      succeed(String url) {
        var params = url.split("access_token=");

        var endparam = params[1].split("&");

        Navigator.pop(context, endparam[0]);
      }

      @override
      Widget build(BuildContext context) {
        return WebviewScaffold(
          url: widget.selectedUrl,
          appBar: new AppBar(
            backgroundColor: Color.fromRGBO(66, 103, 178, 1),
            title: new Text(""),
          ),
        );
      }
    }

**Comment by N0TN4** [comment]
As the answers are old and not only the flutter but the libraries no longer support here is my code linking facebook and google by an credential


`Future<dynamic> handleFacebookSignIn() async {
    final FacebookLogin _facebookLogin = FacebookLogin();
    FirebaseUser user;
    FacebookLoginResult result;
    Usuario usuario = new Usuario();
    AuthCredential credential;
    try {
      _facebookLogin.loginBehavior = FacebookLoginBehavior.nativeWithFallback;
      result = await _facebookLogin
          .logInWithReadPermissions(['email', 'public_profile']);
      usuario.uid = result.accessToken.userId.toString();

      credential = FacebookAuthProvider.getCredential(
          accessToken: result.accessToken.token);
      token = result.accessToken.token;
      FirebaseUser firebaseUser = await _auth.signInWithCredential(credential);

      user = firebaseUser;
    } catch (e) {
      print(result.errorMessage);
      print("handle facebook sign in: $e");
      if (e.code == 'ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL') {
        // if exists get email of your simple get (i will write the code by this later)
        final graphResponse = await Session.get(
            'https://graph.facebook.com/v2.12/me?fields=name,first_name,last_name,email&access_token=${token.toString()}');

        final email = graphResponse["email"];
        // unused
        final signInMethods = await FirebaseAuth.instance
            .fetchSignInMethodsForEmail(email: email);
        FirebaseUser guser; // create a google user
        //get credential google here
        try {
          final GoogleSignIn _googleSignIn = GoogleSignIn();
          GoogleSignInAccount googleUser = await _googleSignIn.signIn();
          GoogleSignInAuthentication googleAuth =
              await googleUser.authentication;

          final AuthCredential credential = GoogleAuthProvider.getCredential(
            accessToken: googleAuth.accessToken,
            idToken: googleAuth.idToken,
          );
          final FirebaseUser firebaseUser =
              await _auth.signInWithCredential(credential);
          guser = firebaseUser;
          // get google user
        } catch (e) {
          print("handle google sign in: $e");
        }
        final authResult = guser;
        if (authResult.email == email) {
          // link facebook + google.
          await authResult.linkWithCredential(credential);
        }

        //return usuario;
      }
    }
    return user;
  }`





session get:

**Comment by sanekyy** [comment]
same issue

**Comment by alexandreangeli** [comment]
> > After some hours I finally figured it out. For now you have to implement some of the flow yourself.
> > I simplified some of the generic part and error handling to make it straightforward:
> > ```dart
> > final facebookLogin = FacebookLogin();
> > // Remember you MUST login with email permission
> > final loginResult = await facebookLogin.logIn(['email']);
> > final credential = FacebookAuthProvider.getCredential(accessToken: loginResult.accessToken.token);
> > try {
> >   // Assume we'll login with an error that causes `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL`
> >   await _firebaseAuth.signInWithCredential(credential);
> > } on PlatformException catch (e) {
> >   if (e.code != 'ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL')
> >     throw e;
> >   // Now we caught the error we're talking about, we get the email by calling graph API manually
> >   final httpClient = new HttpClient();
> >   final graphRequest = await httpClient.getUrl(Uri.parse("https://graph.facebook.com/v2.12/me?fields=email&access_token=${loginResult.accessToken.token}"));
> >   final graphResponse = await graphRequest.close();
> >   final graphResponseJSON = json.decode((await graphResponse.transform(utf8.decoder).single));
> >   final email = graphResponseJSON["email"];
> >   // Now we have both credential and email that is required for linking
> >   final signInMethods = await FirebaseAuth.instance.fetchSignInMethodsForEmail(email: email);
> >   // Assume that signInMethods[0] is 'google.com'
> >   final authResult = ....;  // ... do the Google sign-in logic here and get the Firebase AuthResult
> >   if (authResult.user.email == email) {
> >     // Now we can link the accounts together
> >     await authResult.user.linkWithCredential(credential);
> >   }
> > }
> > ```
> > 
> > 
> > The result should looks like this after you successfully linked it
> > ![image](https://user-images.githubusercontent.com/2157335/69971900-925d0b80-155b-11ea-931f-9a2b45605123.png)
> 
> **How to resolve the issue in this case?**
> 
> ```
>   loginWithFacebook() async {
>   String clientId = "6032xxxxx6393x4";
>   String oauthRedirectUrl =
>       "https://www.facebook.com/connect/login_success.html";
>   String authToken = await Navigator.push(
>     context,
>     MaterialPageRoute(
>         builder: (context) => CustomWebView(
>               selectedUrl:
>                   'https://www.facebook.com/dialog/oauth?client_id=$clientId&redirect_uri=$oauthRedirectUrl&response_type=token&scope=email,public_profile,',
>             ),
>         maintainState: true),
>   );
> 
>   if (authToken != null) {
>     try {
>       AuthCredential authCredential =
>           FacebookAuthProvider.getCredential(accessToken: authToken);
> 
>       AuthResult user = await _auth.signInWithCredential(authCredential);
>       if (user.additionalUserInfo != null) {
>         AdditionalUserInfo af = user.additionalUserInfo;
>         Map<String, dynamic> valMap = Map();
>         af.profile.forEach((key, value) {
>           valMap[key] = value;
>         });
> 
>         final FirebaseUser currentUser = await _auth.currentUser();
>         if (currentUser.uid != null && currentUser.uid.isNotEmpty) {
>           saveWithNavigateCallback(currentUser.uid);
>         }
> 
>         print(af);
>       } else {
>         print(user);
>       }
>     } catch (e) {
>       print(e);
>     }
>   }
> }
> ```
> 
> **CustomWebview.dart**
> 
> ```
>   class CustomWebView extends StatefulWidget {
>   final String selectedUrl;
> 
>   CustomWebView({this.selectedUrl});
> 
>   @override
>   _CustomWebViewState createState() => _CustomWebViewState();
> }
> 
> class _CustomWebViewState extends State<CustomWebView> {
>   final flutterWebviewPlugin = new FlutterWebviewPlugin();
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     flutterWebviewPlugin.onUrlChanged.listen((String url) {
>       if (url.contains("#access_token")) {
>         succeed(url);
>       }
> 
>       if (url.contains(
>           "https://www.facebook.com/connect/login_success.html?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied")) {
>         denied();
>       }
>     });
>   }
> 
>   denied() {
>     Navigator.pop(context);
>   }
> 
>   succeed(String url) {
>     var params = url.split("access_token=");
> 
>     var endparam = params[1].split("&");
> 
>     Navigator.pop(context, endparam[0]);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return WebviewScaffold(
>       url: widget.selectedUrl,
>       appBar: new AppBar(
>         backgroundColor: Color.fromRGBO(66, 103, 178, 1),
>         title: new Text(""),
>       ),
>     );
>   }
> }
> ```

Using this code, when the user log-in with Facebook, and then log-out and try to log-in with Facebook again, the e-mail/password screen doesn't show up, and he is logged-in again automatically. Have you gone through this issue?

**Comment by Xgamefactory** [comment]
if user is currently loggedout for example signed before as google account, user have to reloging with google credentials in order to link with facebook

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue (there's a new section on social providers and also linking) & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration

**Comment by bwerere** [comment]
Unlinking a gmail.com account (providerID google.com) from a phone is executed successfully. Printing the users data shows the unlinked account still exists in the users account together with the phone off course. Calling reload() does not do anything. This prevents the re-linking if one was to do a test or change the linked account to something else. Note: when gmail is linked, the icon for google is next to the phone icon under the providers column. How do we completely remove the linked email.  See attached image: 
![image](https://user-images.githubusercontent.com/63925295/93238438-1bab9a80-f78a-11ea-9b20-223c28b111d1.png)

**Comment by harshptl14** [comment]
@bwerere can you create one repository for this project's code?

> Unlinking a gmail.com account (providerID google.com) from a phone is executed successfully. Printing the users data shows the unlinked account still exists in the users account together with the phone off course. Calling reload() does not do anything. This prevents the re-linking if one was to do a test or change the linked account to something else. Note: when gmail is linked, the icon for google is next to the phone icon under the providers column. How do we completely remove the linked email. See attached image:
> ![image](https://user-images.githubusercontent.com/63925295/93238438-1bab9a80-f78a-11ea-9b20-223c28b111d1.png)

**Comment by bwerere** [comment]
@harshptl14 please check out this: https://medium.com/@anusha.btech.2018/flutter-linking-accounts-in-firebase-with-different-authentication-providers-abe993ba4efe and set up phone authentication and https://firebase.flutter.dev/docs/auth/social for linking the accounts. Once you have linked the accounts phone and google.com (gmail), try to unlink with FirebaseUser user = FirebaseAuth.instance.currentUser();
user.unlinkFromProvider(“google.com”); and go back to firebase console or on the app, it will log on the console the user if you print(User//user properties.).

**Comment by harshptl14** [comment]
Got it

> @harshptl14 please check out this: https://medium.com/@anusha.btech.2018/flutter-linking-accounts-in-firebase-with-different-authentication-providers-abe993ba4efe and set up phone authentication and https://firebase.flutter.dev/docs/auth/social for linking the accounts. Once you have linked the accounts phone and google.com (gmail), try to unlink with FirebaseUser user = FirebaseAuth.instance.currentUser();
> user.unlinkFromProvider(“google.com”); and go back to firebase console or on the app, it will log on the console the user if you print(User//user properties.).

Got it, thank you @bwerere🙌
