### ISSUE TITLE
[cloud_firestore] PlatformException is totally different for iOS and Android

### ISSUE THREAD

**Issue by kika** [FirebaseExtended/flutterfire#1320]
**Describe the bug**

Exactly the same code running on exactly the same document in the Cloud Firestore on two platforms throws two completely different exceptions:

iOS: `PlatformException(Error 7, FIRFirestoreErrorDomain, Missing or insufficient permissions.)`
Android: `PlatformException(Error performing get, PERMISSION_DENIED: Missing or insufficient permissions., null)`

This document is protected by the security rule and I do expect the `get()` call to error out, but I didn't expect to deal with completely different errors.

**To Reproduce**
Call `document.get()` on the document protected by the security rule.

**Expected behavior**
I'd expect at least `PlatformException.code` to be the same on both platforms.

cloud_firestore 0.12.9+5 Flutter 1.9.1 (stable)

**Comment by yamauchieduardo** [comment]
`PlatformException.code` have any documentation for the FlutterFire have any documentation about? I lost a lot of time to discover every `PlatformException.code` and `PlatformException.message` variation

**Comment by Salakar** [comment]
Let's consolidate this under #1223 - will close this one - thanks
