### ISSUE TITLE
[cloud_firestore]: Query returning stale data

### ISSUE THREAD

**Issue by HathTech** [FirebaseExtended/flutterfire#1321]
**Describe the bug**
One of my queries is returning stale data. 

```
ordersCollection
          .where("userId", isEqualTo: userId)
          .orderBy("createdAt", descending: true)
          .snapshots()
          .map((list) => list.documents
              .map((doc) => OrderModel.fromFirestore(doc))
              .toList());
```
I cannot understand the issue. 
I am using the latest version of the cloud_firestore.
` cloud_firestore: ^0.12.9+5`
Only for the above collection, I am getting this error. Changing the collection query is removing the stale data and fetching the latest one. 
Like I removed createdAt and got the data refreshed.

**Comment by cmkweber** [comment]
Have you tried passing Source.server to getDocuments? You can force the query to bypass the cache.

https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/getDocuments.html

**Comment by iapicca** [comment]
Hi @HathTech 
does the proposed [solution](https://github.com/FirebaseExtended/flutterfire/issues/1321#issuecomment-548008237) fix the issue?
Thank you

**Comment by HathTech** [comment]
Hi @iapicca. Yes, it is working. 
Thank you for the response.

**Comment by iapicca** [comment]
Hi @HathTech 
I'm glad that you fixed the issue,
thank you for letting me know
