### ISSUE TITLE
[cloud_firestore] CollectionRef.snapshots.listen leaks

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#1332]
I have a screen that subscribes to a collection using code like:
```dart
  @override
  void initState() {
    super.initState();
    Firestore.instance
        .collection('MainThing')
        .document(documentId)
        .collection('subcollection')
        .snapshots()
        .listen(_processUpdates);
  }

  void _processUpdates(QuerySnapshot snapshot) {
    // process the snapshot...
    setState(() {
      // update state
    });
  }
```

I noticed that when I close this screen, and then go back to it, I get an exception like:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: setState() called after dispose(): _DashboardScreenState#a81a3(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/<…>
```
And this is on the `setState` inside `_processUpdates`.  I believe what is going on is that I now have two snapshot listeners.  My original screen that triggered the first snapshot listener still has an active `Stream` linked to the `_processUpdates` method of the now unmounted screen.

This suggests that I've got a **leak**! 🚨 And to address it, I believe I need a way to _cancel the listener_.  Alas, the [`snapshots`](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/snapshots.html) method returns a `Stream`, not the `StreamController`, so I do not have access to a [`close`](https://api.dart.dev/stable/2.6.0/dart-async/StreamController/close.html) method.

I am using Flutter 1.9.1+hotfix.6, Dart 2.5.0, and Cloud Firestore 0.12.9+6.

**Comment by awhitford** [comment]
Whoops!  My bad!

I need to retain the `StreamSubscription` from the `listen` and then `cancel` that upon `dispose`.

**Comment by SwapnilDaware7** [comment]
Hello @awhitford 
Can you please tell me how to StreamSubscription from the listen? I also facing same issue, can you please help me about this?

**Comment by awhitford** [comment]
Hi @SwapnilDaware7 , I'm just doing something like this in a `StatefulWidget`:
```dart
  StreamSubscription<QuerySnapshot> _subscription;

  @override
  void initState() {
    super.initState();

    assert(null == _subscription);
    _subscription = Firestore.instance
        .collection('MainThing')
        .document(documentId)
        .collection('subcollection')
        .snapshots()
        .listen(_processUpdates);
  }

  @override
  void dispose() {
    assert(null != _subscription);
    _subscription.cancel();
    _subscription = null;

    super.dispose();
  }
```

Essentially, the `listen` method is returning a `StreamSubscription` which needs to eventually be canceled, which I do in `dispose`.

_Does that help?_

**Comment by firatcetiner** [comment]
This is very strange. In my case I'm not calling `setState((){})` in anywhere but the same error appears. I tried adding a check for `mounted` property of the widget but that doesn't solve the problem either.
