### ISSUE TITLE
[cloud_firestore] implement array-contains-any

### ISSUE THREAD

**Issue by qaleghnes** [FirebaseExtended/flutterfire#1333]
Do you plan to implement the "array-contains-any" feature?

https://dev.to/nabettu/array-contains-any-was-created-in-firebase-firestore-so-i-will-explain-it-with-a-sample-site-4g9

**Comment by rosariopfernandes** [comment]
@qaleghnes as mentioned on the post you referenced:

> there is no shadow or shape in the official document yet

That's because that feature hasn't been released on the Mobile SDKs yet.
I'm currently working on a PR to implement it on flutterfire. I'll send it over as soon as the feature is released.

**Comment by thecoffeehog** [comment]
Really looking forward to this PR being pushed. array-contains-any will solve a lot of problems in our app.

**Comment by collinjackson** [comment]
fixed in #1477
