### ISSUE TITLE
Firebase google_app_id missing 

### ISSUE THREAD

**Issue by dimityrivanov** [FirebaseExtended/flutterfire#1335]
**Describe the bug**
Device console log output  Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

**To Reproduce**
Follow the steps of implementing the google analytics plugin

**Expected behavior**
Plugin is connected to firebase

**Comment by iapicca** [comment]
Hi @dimityrivanov 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
