### ISSUE TITLE
[firebase_messaging]  onLaunch is never called

### ISSUE THREAD

**Issue by nivla360** [FirebaseExtended/flutterfire#1336]
When notification is received when app is in background and the app is launched by clicking on the notification **onLaunch()** is called but when app is launched without clicking on the notification **onLaunch()** is never called hence changing app state based on notification becomes impossible.

**Comment by KyllianDM** [comment]
It's not because you must use **onRemuse()** ?

**Comment by nivla360** [comment]
it is still the same even if I use onResume
