### ISSUE TITLE
Removing the requirement to send click_action: FLUTTER_NOTIFICATION_CLICK for Android

### ISSUE THREAD

**Issue by WinkMeter** [FirebaseExtended/flutterfire#1338]
**Is your feature request related to a problem? Please describe.**
Currently we would have to send click_action: FLUTTER_NOTIFICATION_CLICK as part of the message sent to apps using the Flutter firebase_messaging plugin for Android apps to wake up from the background and deliver the notification data to the app. This requirement creates a problem in an environments with apps created using different platforms. (Flutter, Xamrin, Native, etc...) 

The problem with this is that it adds a dependency to the backend which has to know when (i.e. Flutter vs. non-flutter apps) it needs to include the click_action to the push message. Sending "click_action" to all apps doesn't make sense. In other words, there's a tight coupling between the app and the backend.

**Describe the solution you'd like**
It would be nice if Android clients don't have to depend on this and just work like how iOS does it by default without this "click_action" information being included in the push message. In other words, remove the "client_action" requirement and only needs it to pass "specific" actions.

**Additional context**
Is there another way to get around not having to include "click_action"?

**Comment by Salakar** [comment]
Hey 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues, specifically `FLUTTER_NOTIFICATION_CLICK` no longer exists and is not required anymore - all notification 'clicks' for FCM notifications will go through the message handlers now.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Thanks
