### ISSUE TITLE
Publish cloud_functions 0.4.1+2

### ISSUE THREAD

**Issue by cbenhagen** [FirebaseExtended/flutterfire#1346]
To fix https://github.com/flutter/flutter/issues/42923

**Comment by iapicca** [comment]
Hi @cbenhagen 
according to this [answer ](https://github.com/flutter/flutter/issues/42923#issuecomment-547568162)the issue has been fixed with this [pull request](https://github.com/FirebaseExtended/flutterfire/pull/1250/) 
on it's way for being published.
leaving this open until the published

**Comment by collinjackson** [comment]
It's published now.
