### ISSUE TITLE
[firebase_messaging] ability to retrieve native APN token ID

### ISSUE THREAD

**Issue by jam33** [FirebaseExtended/flutterfire#1348]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A method to call to retrieve the native/ios APN token ID in addition to the FCM token ID that is done after it registers the APN token with FCM in the background.  Right now you can only get the FCM token ID.  That's fine for Android because only one token exists, but with ios there are technically 2 tokens.

**Additional context**
While I don't plan on moving away from FCM in the near future, it makes sense to be able to store each devices iOS APN and FCM token ID in my own backend in-case there are ever needs to call the APN servers directly (bypassing FCM).

**Comment by Ehesp** [comment]
Hello - we'll get `getAPNSToken` implemented

**Comment by Salakar** [comment]
Hey 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues, specifically; we've added a `getAPNSToken` API that you can now use..

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Thanks
