### ISSUE TITLE
[firebase_ml_vision] Doesn't Recognize Image taken with ImagePicker in iOS 11

### ISSUE THREAD

**Issue by kalismeras61** [FirebaseExtended/flutterfire#1356]
**Describe the bug**
I am using firebase_ml_vision package for Text Recognition. It is working on Android side but when i test it real IOS device taken photo with image_picker plugin doesn't recognize texts. I tried convert to image Unit8 and same problem not reading image.

Do i need convert image something?

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[!] Connected device
    ! No devices available
```

**The image picker function**
```
Future<Null> getImage(ImageSource source) async {
    try {
      var image = await ImagePicker.pickImage(source: source);

      var uuid = new Uuid();

      // Step 3: Get directory where we can duplicate selected file.
      Directory directory = await getApplicationDocumentsDirectory();
      String path = directory.path;
      String pathVar = path + '/' + uuid.v1() + '.png';
      await image.copy(pathVar);
      if (image != null) {
        _getImageSize(image);
        _imageFromGallery = image;
        _isLoaded = true;

        notifyListeners();
      } else {
        Flushbar(
          message: "Lütfen Resim Seçiniz",
        );
      }
    } catch (e) {
      _isLoaded = false;
      print(e.toString());
      notifyListeners();
    }
  }
```

**Comment by kuailink** [comment]
I hit the same problem on iPhone X. By binary searching, I located this issue in 0.6.0+4. 0.6.0+3 works OK for me, but 0.6.0+4 not.

**Comment by kalismeras61** [comment]
I test it with IPAD 3 and i saw it is working as normal.  I think the problem coming with new devices later ios 11 and which is the supports HEIC format. 

Do i need to convert it someting else ? What do you think of that?

**Comment by kalismeras61** [comment]
any update for this?

**Comment by eddiesTime** [comment]
The problem lies in the HEIF/HEIC format iOS is using since iOS 11 as @kalismeras61 mentioned.
A couple of month prior to your issue someone mentioned the same problem. Follow [this issue](https://github.com/FirebaseExtended/flutterfire/issues/150) for more information.
If you manage to convert your image to a .jpg it should work as expected.

**Comment by Ehesp** [comment]
Closing - tracking on https://github.com/FirebaseExtended/flutterfire/issues/150
