### ISSUE TITLE
[firebase_messaging] data message arrives on the native side, but is not delivered to the Dart side

### ISSUE THREAD

**Issue by sd-timaru** [FirebaseExtended/flutterfire#1357]
Using firebase_messaging: ^5.1.6 plugin in my application, I noticed that when the app is in the background, sometimes the messages do not reach "the destination", so i decided to do some "tracking".

In the file **FlutterFirebaseMessagingService.java**, at the method **executeDartCallbackInBackgroundIsolate** i added
 "Log.i(TAG, "before handleBackgroundMessage")":

```java
    ...
    Log.i(TAG, "before handleBackgroundMessage");
    args.put("message", messageData);
    backgroundChannel.invokeMethod("handleBackgroundMessage", args, result);
    ...
```

In the file **firebase_messaging.dart** , at the method **setMethodCallHandler** i added
 "print('Received in Dart!');":

```dart
  backgroundChannel.setMethodCallHandler((MethodCall call) async {
    print('Received in Dart!');
    if (call.method == 'handleBackgroundMessage') {
    ...
```

To do some testing,  i send 4 data messages, while the app was in background.  2 of them arrived successfully in the app, but the last 2 didn't, even they arrived to the java side:

![mess](https://user-images.githubusercontent.com/44212228/68083071-250b6d00-fe2d-11e9-9959-02de42e536e0.jpg)

If i "bring" the app in the foreground and send to it others data messages, the arrive successfully.

What could be the problem? Why the messages are not delivered always to the Dart side, when the app is in the background?

**Comment by iapicca** [comment]
Hi @sd-timaru 
Could you please provide your `flutter doctor -v`
and your your `flutter run --verbose`?
Thank you

**Comment by sd-timaru** [comment]
Yes, but i just updated the flutter and dart plugin....

[doc.txt](https://github.com/FirebaseExtended/flutterfire/files/3804702/doc.txt)

[output.txt](https://github.com/FirebaseExtended/flutterfire/files/3804705/output.txt)

**Comment by iapicca** [comment]
Thank you @sd-timaru

**Comment by goody-h** [comment]
I also experience this on my app.

A simple `flutter logs` on the connected device would show the creation of an observatory listener when a data message is received
`I/flutter (24260): Observatory listening on http://127.0.0.1:46040/aO_xk0_pDeQ=/`

But then the Dart background Message handler does not always execute

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
