### ISSUE TITLE
[cloud_firestore] unable to retrieve data on Flutter Web

### ISSUE THREAD

**Issue by Parmendrakumar** [FirebaseExtended/flutterfire#1361]
I am unable to get data from firebase if using code line:
Firestore.instance.collection('testcrud').getDocuments();

But its working fine with
import 'package:firebase/firebase.dart' as fb;
fb.firebase.firestore().collection('testcrud').get();

pubspec.yaml:
cloud_firestore: ^0.12.9+6
firebase: any

On Mobile its revert situation.

I am working on master build

I am not sure about why this happening...

**Comment by iapicca** [comment]
Hi @Parmendrakumar 
Could you please provide your `flutter doctor -v`
and your your `flutter run --verbose`?
Thank you

**Comment by Parmendrakumar** [comment]
PS C:\Users\e01699\web\flutterapp> flutter doctor -v
[√] Flutter (Channel master, v1.10.15-pre.350, on Microsoft Windows [Version 10.0.17763.379], locale en-IN)
    • Flutter version 1.10.15-pre.350 at C:\flutter
    • Framework revision 79323f7c13 (5 days ago), 2019-10-30 19:40:19 -0700
    • Engine revision b16eab6aff
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 d50c158d42)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\e01699\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
       - If there are multiple versions, install the latest one
        Windows 10 SDK (10.0.17763.0)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\e01699\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.379]
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
PS C:\Users\e01699\web\flutterapp>

**Comment by Parmendrakumar** [comment]
PS C:\Users\e01699\web\flutterapp> flutter run --verbose
[  +20 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +108 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 79323f7c137a28f36ac27e589f4c80dc7c96c072
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +150 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-350-g79323f7c1
[   +6 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +88 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[   +1 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[  +84 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +110 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +86 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +107 ms] executing: C:\Users\e01699\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +57 ms] Exit code 0 from: C:\Users\e01699\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +10 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +51 ms] Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.379]
[   +1 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
[        ] Web Server • web-server • web-javascript • Flutter Tools
[   +7 ms] "flutter run" took 328ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:287:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:532:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)



PS C:\Users\e01699\web\flutterapp>

**Comment by iapicca** [comment]
thank you @Parmendrakumar

**Comment by yannbarrault** [comment]
Any news about this issue ? We would love to use this on flutter for web as well as on mobile version

**Comment by yannbarrault** [comment]
> Any news about this issue ? We would love to use this on flutter for web as well as on mobile version

**Comment by NoamDev** [comment]
flutter for web does not support plugins (like cloud_firestore package) yet,
there other solutions though
please look at this issue #1470 .

**Comment by Tonne-TM** [comment]
As plugins for flutter web were announced will cloud_firestore be updated too?

[https://medium.com/flutter/web-support-for-flutter-goes-beta-35b64a1217c0](https://medium.com/flutter/web-support-for-flutter-goes-beta-35b64a1217c0)

**Comment by Soumyadeep21** [comment]
Flutter for web is in beta now. So can we expect firebase packages like auth firestore for web as well?

**Comment by cbenhagen** [comment]
You can subscribe to the issues mentioned in this project: https://github.com/flutter/flutter/projects/69

**Comment by ditman** [comment]
cloud_firestore web is being actively worked on right now.

I'm going to close this as we're tracking progress here: https://github.com/flutter/flutter/issues/45293

Thanks for reporting!
