### ISSUE TITLE
[cloud_firestore] AndroidX Incompatibility

### ISSUE THREAD

**Issue by milano23** [FirebaseExtended/flutterfire#1368]
I have requested this [issue](https://github.com/FirebaseExtended/flutterfire/issues/1362) re-open and over 24 hours have passed and it is still closed with no response from anyone. I responded that i have tried all of the suggestions but still not able to get a release build completed. I am currently road blocked from deploying my app to the Play Store.  My iOS version has already been through review and accepted and now on the App Store.  I am receivng the error in the title and i am unable to build a release version for android.

I have followed all of the instruction on the [Firebase](https://firebase.google.com/docs/android/setup) setup.  I am using all of the currect version of dependencies listed on that site.

I have since created a brand new project.  It has one page and i am pulling one item from the cloudstore.  I am able to run this on an android emulator but i am unable to build a release version of this new project.

I get the exact same error as I did in my original project from the post from the link above.
```
[   +1 ms]          *********************************************************
[        ] WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't
compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be
unrelated.
[        ]          *********************************************************
```

Also the link the error is pointing to is the [Android X](https://flutter.dev/docs/development/androidx-migration) migration link.  This page says nothing about how to fix any cloud firestore incompatibilities with android x migration.  I wouldn't even know where to start looking if i had an issue with Android X migration as it isn't specific. 

I don't even know with certainty if this is a cloud firestore issue and not more of an Android X or other issue.  Everyone else seems to be fixing there issues with changing version numbers of either kotlin, com.google.gms:google-services, com.android.tools.build:gradle, or multiDex.  None of these have helped me.  

If you require me to post anything else form my logs i can, but between this post and the previous one i should have enough logs up, even still let me know and i will post it.,

Thank you,

**Comment by milano23** [comment]
Okay, posting so anyone that comes across this same ridiculousness they wont have to go through three days of it.  This [site](https://github.com/flutter/flutter/wiki/Resolving-common-build-failures) helped out.  
I was originally trying to build my release version on the stable branch.  And it was not giving me errors but it did give me a warning about firestore.  The above mentioned site said to switch to flutters dev branch to get more informative messages.  Sure enough there is way more information showing up in those logs. 
I switched to the dev channel: 
```
flutter channel dev
```
then i ran
```
flutter upgrade
```
in the flutter sdk directory and then my project directory.  I am not 100% certain that both are needed but i did it anyway.

Then i ran ```flutter build appbundle --verbose```, this is the error messages i received:
```
[   +2 ms] WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't
compatible with AndroidX.
[   +1 ms]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be
unrelated.
[        ]          *********************************************************
[        ] FAILURE: Build failed with an exception.
[   +4 ms] * What went wrong:
[        ] Execution failed for task ':app:validateSigningRelease'.
[        ] > Keystore file 'C:\Users\serbs\Documents\Flutter Projects\hwe_app\android\app\C:UsersserbsDocumentsFlutter
Projectshwe_appandroidhwebundlekeystore.jks' not found for signing config 'release'.
[   +4 ms] * Try:
[   +3 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +5 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 1m 53s
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[   +3 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 153 actionable tasks: 136 executed, 17 up-to-date
```
As you can see the warning is still there but now there is also an error.  It looks like I was adding the wrong route to where my keystore file was.  Apparently somehow it should have been in the app folder and doesn't need a proper route mentioned just the file name.  I had it saved to the android root directory.  After moving it to the app directory and then only specifying the name of the file in my key.properties file, the build succeeded.
```
[   +1 ms] > Task :app:bundleRelease
[        ] BUILD SUCCESSFUL in 2m 14s
[        ] 162 actionable tasks: 148 executed, 14 up-to-date
[ +349 ms] Running Gradle task 'bundleRelease'... (completed in 135.0s, longer than expected)
[   +8 ms] Built build\app\outputs\bundle\release\app-release.aab (14.3MB).
[   +3 ms] "flutter appbundle" took 144,947ms.
```

Mind you though i am still in the flutter dev channel and not on stable. I switch over using the same commands and methods mentioned above, obviously this time though i am using ```flutter channel stable```.
After i finish my flutter upgrade on my project directory i run ```flutter clean```, then i run ```flutter build appbundle --verbose```, just as i did in the dev channel. Below is my output:
```
[   +1 ms] > Task :app:bundleRelease
[  +53 ms] 161 actionable tasks: 147 executed, 14 up-to-date
[ +352 ms] Running Gradle task 'bundleRelease'... (completed in 109.8s)
[   +4 ms] "flutter appbundle" took 120,862ms.
Gradle build failed to produce an Android bundle package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:780:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
As you can see i still get an error. But this error says "Gradle build failed to produce an Android bundle package".  This is not true.  There is an app-release.aab file in the build\app\outputs folder.  This is the only error in the log.  I don't know why we shouldn't have the same informative messages as we do in the dev channel.  I will be uploading this appbundle to the play console to test and make sure everything works but i think this is it.  Far better than i have gotten in the past three days.   For now i am going to bed but i will update this tomorrow either way, hoping it passes the test in the google play console.

**Comment by iapicca** [comment]
Hi again @milano23 
I've closed you previuos issue [[1](https://github.com/FirebaseExtended/flutterfire/issues/1362)],
like another issue mentioned above [[2](https://github.com/FirebaseExtended/flutterfire/issues/77#issuecomment-533875036)],
redirecting both to the earliest issue [[3](https://github.com/FirebaseExtended/flutterfire/issues/17)] on the topic.

I apologize for the confusion 
and I assure you that closing your previous issue 
does not mean in any way that has been ignore or rejected.

If I have missed something and your issue is different from the one
I've redirected you to I, again, apologize for that and
I ask you to please point out those differences.

I recommend to follow up in the issue [3] as it's more effective
keep track of all feedback in one place.
Thank you

**Comment by milano23** [comment]
hi @iapicca, thank you for getting back to this.

I don't believe this issue should be combined with the [original](https://github.com/FirebaseExtended/flutterfire/issues/17) issue you redirected me to.  This issue had nothing to do with cluod firestore.  I did have a warning about the cloud firestore dependecies, but like i said yesterday once i switched to the flutter dev channel and ran the command to build a release that is when i found out the true issue and resolved it.  My app is currently pending approval on the google play store and all tests have passed.  I believe if this should be posted it should be on the main flutter github issue section as the main problem was that the stable channel does not give enough information when there are errors.  

In the end it is up to you where you want to redirect this post to,  I have laid out everything i did to resolve my problem in the posts above. I just want people to find this conversation to allow them to resolve their issue.

Thanks again for your help.  We can close this issue as my problem is resolved.

**Comment by iapicca** [comment]
Hi @milano23 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
