### ISSUE TITLE
[firebase_admob] Exposed Ad Banner width and height to flutter

### ISSUE THREAD

**Issue by ensecoz** [FirebaseExtended/flutterfire#137]
**Is your feature request related to a problem? Please describe.**
There is no way to know the width and height of the smart ads in flutter and banner is always at the bottom of the screen. I need a way to add bottom margin of the content to avoid overlapping with the banner.

**Describe the solution you'd like**
Expose the width and height from the native code.

e.g. 
```
int widthPixels = AdSize.SMART_BANNER.getWidthInPixels(this);
int heightPixels = AdSize.SMART_BANNER.getHeightInPixels(this);
```

**Comment by orischwartz** [comment]
Previous discussion: https://github.com/flutter/flutter/issues/19832#issuecomment-530817975

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
