### ISSUE TITLE
[firebase_crashlytics] No errors are reported in the Firebase console

### ISSUE THREAD

**Issue by magnuswikhog** [FirebaseExtended/flutterfire#1376]
I have followed the steps in the README to install and configure the plugin, but get nothing in the Firebase console. I do get 

    Flutter error caught by Crashlytics plugin:
    Error caught by Crashlytics plugin <recordError>:
    ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═
    ...
    Error reported to Crashlytics.

But nothing appears in the Firebase console, no matter how much I fiddle around with the filters etc. I have tested this on a physical device as well as an emulator with Play Store.

`FlutterError.onError()` is definitely getting called, and as mentioned above, the Crashlytics plugin says that it has caught and reported the error.

We also tested this plugin at my workplace a few months ago, same issue in a different app. I think we managed to get one or two errors to show up in Firebase, but that's out of several hundred tries over a few weeks. Was hoping it was fixed by now, unfortunately it seems not.

**To Reproduce**
1. Add firebase_crashlytics plugin as described in the README
2. Make sure you have `Crashlytics.instance.enableInDevMode = true;`
3. Call `Crashlytics.instance.crash()` and/or `throw StateError('test-error');`
4. Go to the Crashlytics page in Firebase console
5. Wait 24+ hours

**Expected behavior**
Something should appear in the Firebase console.

**Comment by magnuswikhog** [comment]
I was just about to give up on using this plugin, when I found https://github.com/FirebaseExtended/flutterfire/issues/1153 

It seems to have solved the problem - I'm finally getting something in the Crashlytics page in the Firebase Console! 

And in the app output I got a line that says 

    Crashlytics report upload complete: <GUID>

so it seems that the crucial part that's missing in the documentation - and in other threads regarding this problem - is adding 

    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'

to the `dependencies` section in `android/app/build.gradle`.

**Comment by iapicca** [comment]
Hi @magnuswikhog 
I'm glad to hear that you solved the issue,
I'll report your comments in the issue dedicated to 
improve the documentation.

Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 

Thank you for your contribution
