### ISSUE TITLE
[firebase_auth] Twitter login doesn't work

### ISSUE THREAD

**Issue by filipppp** [FirebaseExtended/flutterfire#138]
**Describe the bug**
After adding everything to the twitter web dev plattform: (oauth callback url and twittersdk://) signInWithCredential returns "PlatformException(ERROR_INVALID_CREDENTIAL, The supplied auth credential is malformed or has expired. [ Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 401, http response: {"errors":[{"code":32,"message":"Could not authenticate you."}]} ], null)"

**To Reproduce**
1. Create twitter login with flutter_twitter_login for example and get both auth and auth token secret keys
2. Sign in with the signInWithCredential method
4. See error or incorrect behavior

**Expected behavior**
Get information from twitter account.
**Additional context**
None.

**Comment by filipppp** [comment]
Full Code:

```
       TwitterLoginResult result = await _twitterSignIn.authorize();

        /// TODO: Could handle exit data for errors result.status to show in UI
        /// 
        credential = TwitterAuthProvider.getCredential(authToken: result.session.token, authTokenSecret: result.session.secret);
    FirebaseUser user = await _auth.signInWithCredential(credential);

```

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue (see social providers docs section) & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration
