### ISSUE TITLE
error with google-services.json file

### ISSUE THREAD

**Issue by srikanth1612** [FirebaseExtended/flutterfire#1382]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_messaging:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/macbookair/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/nullnull/google-services.json
  /Users/macbookair/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/debug/google-services.json
  /Users/macbookair/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/nullnullDebug/google-services.json
  /Users/macbookair/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/nullnull/debug/google-services.json
  /Users/macbookair/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/debug/nullnull/google-services.json
  /Users/macbookair/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3sGradle task assembleDebug failed with exit code 1

**Comment by srikanth1612** [comment]
added google-services.json file in android/app folder still getting error

**Comment by iapicca** [comment]
Hi @srikanth1612 
can you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Thank you

**Comment by srikanth1612** [comment]
hi @iapicca 
this is updated details of what u asked

MacBooks-MacBook-Air:~ macbookair$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale
    en-IN)
    • Flutter version 1.9.1+hotfix.4 at /Users/macbookair/flutter
    • Framework revision cc949a8e8b (6 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/macbookair/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • MotoG3 • ZY2225DL8N • android-arm • Android 6.0.1 (API 23)

• No issues found!
MacBooks-MacBook-Air:~ macbookair$ flutter build --verbose
[  +18 ms] executing: [/Users/macbookair/flutter/] git log -n 1
--pretty=format:%H
[  +90 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] cc949a8e8b9cf394b9290a8e80f87af3e207dce5
[        ] executing: [/Users/macbookair/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[ +135 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +4 ms] v1.9.1+hotfix.4-0-gcc949a8e8
[  +10 ms] executing: [/Users/macbookair/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +17 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
Missing subcommand for "flutter build".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.

**Comment by srikanth1612** [comment]
issue resolved

**Comment by rnagar3434** [comment]
i am also getting same error can you help me

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
