### ISSUE TITLE
[cloud_firestore] Support `in` queries

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#1387]
[`in` queries were recently added to Cloud Firestore](https://firebase.googleblog.com/2019/11/cloud-firestore-now-supports-in-queries.html), i.e. the native client libraries support this feature and the Flutter plugin should support it as well.

**Comment by rosariopfernandes** [comment]
Thanks for sending this Feature Request @creativecreatorormaybenot 

Even though this has been [released on the iOS SDK](https://firebase.google.com/support/release-notes/ios#cloud-firestore), the Android SDK does not support it yet.

I'm currently working on a PR that will support `in` and `array_contains_any` queries on FlutterFire. I'll send it as soon as it's released on the Android SDK.

**Comment by ramamurthyk** [comment]
Thanks folks. Looking forward for this feature to be available in Flutter Firestore plugin.

**Comment by agordeev** [comment]
Docs say it is available in both iOS and Android SDKs. Would be great to see this feature on Flutter too.

**Comment by collinjackson** [comment]
fixed in #1477
