### ISSUE TITLE
[firebase_analytics] FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by nihalreddy33** [FirebaseExtended/flutterfire#1389]
**Describe the bug**
After upgrading to firebase_analytics: ^5.0.6, we are facing this issue.
**To Reproduce**
upgrade to firebase_analytics: ^5.0.6, and try to run a flutter build apk.

**Error Message**
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/Nihalreddygurrala/Documents/FlutterDevelopment/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.6/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.

**Additional context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.443, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2016.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ This install is older than the minimum recommended version of 2017.1.0.
[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.40.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by russellwheatley** [comment]
Hey @nihalreddy33, can you confirm if this is still an issue? `firebase_analytics` is now a few major versions from `5.0.6`. Thanks.

**Comment by russellwheatley** [comment]
Given the age, version and lack of response, I'm going to close this out and ask that users upgrade to the latest analytics version.
