### ISSUE TITLE
[firebase_messaging] iOS recognizes all notifications ad Data only

### ISSUE THREAD

**Issue by AlexBacich** [FirebaseExtended/flutterfire#1390]
I have integrated FCM into my project and sending Notification Messages to my devices. 

iOS is processing them as they are data only messages. How did I get that:
1. Push notification isn't shown when app is in background
2. When I launch the app after getting push - I receive onMessage callback. Which is what should happen according to docs when app receives DATA messages while being in background. 
Here is log: 
```
On message {
from: 672729660118, 
notification: {title: test_title, e: 1, body: test_body}, 
collapse_key: com.bundle.id.of.my.ios.app, 
notificationId: 13,  // custom param in data object
id: 16, // custom param in data object
type: price, // custom param in data object
click_action: FLUTTER_NOTIFICATION_CLICK // custom param in data object
}
```

Docs with Notification and Data messages: https://pub.dev/packages/firebase_messaging#receiving-messages

Several observations:
1. My push notification also contained some data and instead of putting it into data object it has sent it right in the push body. Fields like type, click_action, type, notificationId
2. Android receives messages just right. As notification + data. 

What I tried so far, none of that helped:
- Flutter clean and rebuild
- Remove Background Modes feature 
- Tried sending pushes using different ways: legacy API, API v1, Firebase Console

This shouldn't be certificate thing as in general pushes are received by my developer device. But no idea what else. There isn't much code added to the app itself. 

There also isn't much code in the app related to pushes. Just obtaining push token, requesting iOS permission and calling _FirebaseMessaging().configure with callbacks.

My flutter doctor: 
```
[✓] Flutter (Channel master, v1.10.15-pre.387, on Mac OS X 10.15 19A602, locale ru-UA)
    • Flutter version 1.10.15-pre.387 at /Users/reiven/flutter
    • Framework revision 3422540bc4 (4 days ago), 2019-11-04 09:09:20 -0800
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/reiven/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 41.0.3
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (5 available)
    • F5321        • BH901SWC5P                               • android-arm64  • Android 8.0.0 (API 26)
    • iPad () •   • ios            • iOS 13.1.2
    • iPhone 6s    • 698418C7-2F45-45CB-8057-3358AAADCDA1     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Chrome       • chrome                                   • web-javascript • Google Chrome 78.0.3904.87
    • Web Server   • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

**Comment by AlexBacich** [comment]
So I'm observing the issue more. Couple of days passed. Nothing changed (in Flutter code, in firebase messaging  plugin,  flutter engine and in code sending FCM requests). 

But notifications suddenly started coming. Also push notification looks like this now: 

```
on Message {google.c.a.e: 1, notificationId: 13, aps: {alert: {title: test_title, body: test_body}}, id: 16, type: price, gcm.message_id: 1573723511044328, click_action: FLUTTER_NOTIFICATION_CLICK}
```

**Comment by Ehesp** [comment]
Hi @AlexBacich please could you try with the latest Flutter & messaging plugin please. If you still have this issue, please let me know and I can reopen the issue.

**Comment by peter-meemo** [comment]
@Ehesp  I am seeing this issue on the latest flutter/FCM plugin.
