### ISSUE TITLE
[firebase_admob] when using this plugin strictly for ads, pod unnecessarily installs firebase core and other plugins only on iOS side

### ISSUE THREAD

**Issue by hariom08** [FirebaseExtended/flutterfire#1400]
I use firebase_admob plugin in my flutter project and don't intend to include any other firebase related plugins like firebase_analytics, firebase_core, etc. So, my android side of the development seems very neat and all the Ads implementation is totally fine.
But from the iOS side, there seem to some config steps which I'm not able to narrow down. There is no proper documentation also regarding this.
Now, Correct me if my understanding is wrong.
podfile is a generated one based on the pubspec.yaml file with regard to flutter ios side. And the terminal command 'pod install' installs all the dependent plugins for iOS automatically. But here is the actual problem, instead of installing only the AdMob part as a standalone plugin, the pod installs all other firebase_core, analytics, etc too, which I don't expect. I want it exactly to be similar to the android side.  Because of this, I get this Google-services-info.plist is not set up and all that which I haven't done either in android with 'google-services.json'.
Why should I have to forcibly include the google analytics part when I look only for Ads? Why there is no straightforward way to install only the AdMob part with the firebase_admob as in android.

And since the podfile is an auto-generated one pulling all the needed plugins from the pubspec.yaml. i'm not sure if i can add the standalone 'pod firebase_admob -version'. and run pod update.
But still not sure how this will remove the other firebase related plugins.
In fact, even after manually removing the dependencies from the pods.xcodeproj's target, pod update restores all the removed plugins again. How to sort this out.?

**Comment by blasten** [comment]
This is by design. Those are transitive dependencies.
