### ISSUE TITLE
[firebase_messaging] 5.1.8: Crash on start

### ISSUE THREAD

**Issue by iampopal** [FirebaseExtended/flutterfire#1402]
**App crush on start 5.1.8**
When app start app crushes in firebase_messaging 5.1.8 version, i work tree days to solve it but finally solve it with downgrading to firebase_messaging 5.1.6

**Fix the problem**
firebase_messaging 5.1.6 works perfectly so fix the latest or include in docs that current version is not stable.

**Comment by iapicca** [comment]
Hi @iampopal 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` or `flutter build --verbose` ?
Thank you

**Comment by iampopal** [comment]
Hello @iapicca 
I have my problem by migrating my app to AndroidX. 
It will be great if you add the AndroidX migrating step to firebase_messaging documentation. 

The Application.java file location at the android/app is also not very clear for many of us
if you add a clear path of Application.java to documentation it will be awesome.

**Comment by iampopal** [comment]
@iapicca 
When the Android app is closed, local_notification shows the app icon and not show an icon that I initialized while getting the instance of local_notification, is there any way to solve it.

**Comment by iapicca** [comment]
Hi @iampopal 
if you are using [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications)
please remember that is a 3rd party plugin and you may want to open an issue in the dedicated [github](https://github.com/MaikuB/flutter_local_notifications/issues)
thank you for the update

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
