### ISSUE TITLE
[firebase_dynamic_links] Working Only on 2nd Open

### ISSUE THREAD

**Issue by CedYF** [FirebaseExtended/flutterfire#1409]
**Describe the bug**
If install an app with a firebase deeplink, the deeplink won't work on the original install. But it will work on subsequent opens of the app.

**To Reproduce**
1. Set Up DeepLinking
2. Install The App And Notice That It Doesn't Work
3. See That One 2nd time clicking the link, deeplinking successfully works.

**Expected behavior**
I would expect the deeplink to work on the initial install.

**Additional context**
There could be something on the install where it's not passing through.

**Comment by iapicca** [comment]
Hi @CedYF 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by HofmannZ** [comment]
#255 fixed it for me. Currently running that fork, it will hopefully be merged soon.

**Comment by ch-muhammad-adil** [comment]
If this issue is happening in iOS then you may find some good information in this article 

https://medium.com/flutter-community/handling-firebase-dynamic-links-in-flutter-7c1de6a4e2e

**Comment by iapicca** [comment]
Hi again @CedYF
did the proposed solutions worked for you?
Thank you both @HofmannZ  and @ch-muhammad-adil

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
