### ISSUE TITLE
[firebase_messaging] Unable to receive any Data Messages

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#1419]
Detailed description of the bug at https://stackoverflow.com/q/58841677/6509751. I kind of need data messages in order to perform l10n.

I followed the setup at https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages and data messages do not trigger anything, neither in foreground nor in background.

Notifications work fine otherwise.

**Comment by creativecreatorormaybenot** [comment]
I have noticed that `registrar.activity()` is null when the background isolate is started. Potentially this causes the issue.

**Comment by Salakar** [comment]
Hey 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thank you
