### ISSUE TITLE
[firebase_admob] Unable to open the app.

### ISSUE THREAD

**Issue by HumbleCarl** [FirebaseExtended/flutterfire#1423]
**Describe the bug**
I'm using ads wrapper for firebase_admob but when I try to run the app there's a note and I can't open the app. Here's the note "firebase_admob-0.9.0+9/android/src/main/java/io/flutter/plugins/firebase admob/AdRequest Builder Factory.java uses or overrides a deprecated API."

**To Reproduce**
1. Add ads to pubspec.yaml
2. flutter run
4. See error or incorrect behavior

**Expected behavior**
App can be run.

**Comment by iapicca** [comment]
Hi @HumbleCarl 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1313) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by HumbleCarl** [comment]
@iapicca didn't found solutions there.

**Comment by akshaykhatale** [comment]
After adding package you have to add Admob app id to manifest file and create a banner ad if you only add package app will not launch.
