### ISSUE TITLE
[firebase_remote_config] MissingPluginException

### ISSUE THREAD

**Issue by muhsinzyne** [FirebaseExtended/flutterfire#1425]
When i am trying to integrate flutter firebase_remote_config to my project i am getting an error like 

```
MissingPluginException(No implementation found for method RemoteConfig#instance on channel plugins.flutter.io/firebase_remote_config)
flutter: AsyncSnapshot<RemoteConfig>(ConnectionState.done, null, null)
```

my code is as bellow for collecting the remote config values 

```
Future<RemoteConfig> setupRemoteConfig() async {
    final RemoteConfig remoteConfig = await RemoteConfig.instance;
    // Enable developer mode to relax fetch throttling
    remoteConfig.setConfigSettings(RemoteConfigSettings(debugMode: true));
    remoteConfig.setDefaults(<String, dynamic>{
      'welcome': 'default welcome',
      'hello': 'default hello',
    });
    return remoteConfig;
  }
```

and inside my  MaterialApp home look like 

```
home: FutureBuilder<RemoteConfig>(
          future: setupRemoteConfig(),
          builder:
              (BuildContext context, AsyncSnapshot<RemoteConfig> snapshot) {
            print(snapshot);
            return snapshot.hasData
                ? LoginScreen(remoteConfig: snapshot.data)
                : Container(
                    color: Colors.red,
                  );
          },
        ),
```

please help me what was wrong in my code to get on stuck...

I am testing with ios application and i have placed the GoogleService-Info.plist as per the documentation for working wiith ios application with firebase. 

please navigate me what was coming wrong to denying my config fetch

**Comment by iapicca** [comment]
Hi @muhsinzyne 
could you please provide your updated  `flutter doctor -v` and your `pubspec.yaml` ?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by yourshinsuke** [comment]
just add it is okey? I also met the bug.
```
dependencies:
  firebase_remote_config: ^0.3.1+1
```

**Comment by yourshinsuke** [comment]
```
classpath "com.google.firebase:firebase-config:19.2.0"
```

**Comment by yourshinsuke** [comment]
android/app/src/main/kotlin/jp/yourmystar/partner/MainActivity.kt

```
import io.flutter.plugins.deviceinfo.DeviceInfoPlugin
import io.flutter.plugins.firebase.core.FirebaseCorePlugin
import io.flutter.plugins.firebase.crashlytics.firebasecrashlytics.FirebaseCrashlyticsPlugin
import io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin // <= Add
```

```
        flutterEngine.plugins.add(FirebaseCrashlyticsPlugin())
        flutterEngine.plugins.add(FirebaseRemoteConfigPlugin()) // <= Add
        flutterEngine.plugins.add(FirebaseMessagingPlugin())
```
