### ISSUE TITLE
[Firebase Auth] Cannot Run Project After Adding Dependencies

### ISSUE THREAD

**Issue by jonhunterking66** [FirebaseExtended/flutterfire#1430]
When I add the dependency for firebase_auth to my pubspec.yaml file I cannot run my project. I get the error "Finished with error: Gradle task assembleDebug failed with exit code 1"

1. Add firebase_auth: ^0.14.0+5 to your pubspec.yaml file under dependencies
2. Run flutter pub get 
2. Run project 

I am not even using the dependency in my dart files but it stall causes gradle to fail. 

C:\Users\jonathan.king\App Dev\oto_app_0>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.1130], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jonathan.king\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\jonathan.king\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

Any idea how to fix this?

**Comment by businessApp62** [comment]
the same problem happens to me, I try many things but nothing works

**Comment by jvrjohnson** [comment]
having the same issues as well

**Comment by iapicca** [comment]
Hi @jonhunterking66 
could you please provide your  `flutter build --verbose` ?
Thank you

**Comment by jonhunterking66** [comment]
> Hi @jonhunterking66
> could you please provide your `flutter build --verbose` ?
> Thank you

[  +24 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[ +344 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +190 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a091
[  +15 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +186 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[ +190 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
Missing subcommand for "flutter build".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

Not sure why it is failing but this is what i get when I run the command from my project location. 

Thanks for responding, not really sure how to fix this.

**Comment by jonhunterking66** [comment]
I solved this by restarting my flutter project in Android Studio. I made sure not to use Kotlin and then I followed the firebase tutorial again (https://firebase.google.com/docs/flutter/setup). I had to add the following code to my gradle.properties however:

android.useAndroidX=true android.enableJetifier=true

Seems to work fine now
