### ISSUE TITLE
[firebase_auth] Sign in with Apple

### ISSUE THREAD

**Issue by MichaelM97** [FirebaseExtended/flutterfire#1434]
http://firebase.googleblog.com/2019/11/sign-in-with-apple-auth.html

Would love to know when this will become available for Flutter devs! 😄

**Comment by kroikie** [comment]
[Apple sign in](https://pub.dev/packages/apple_sign_in) plugin already exists, happy to review any PR that adds this functionality to firebase_auth.

**Comment by zariweyo** [comment]
I launch the PR https://github.com/FirebaseExtended/flutterfire/pull/1526 , that solve this issue for iOS devices, because apple_sign_in only work in iOS.

**Comment by collinjackson** [comment]
I believe that this was fixed in #1549 but let me know if I'm mistaken.
