### ISSUE TITLE
[firebase_auth] invalid credential error

### ISSUE THREAD

**Issue by renanzdm** [FirebaseExtended/flutterfire#1435]
```
class AuthRepository extends Disposable {
  FirebaseAuth _auth = FirebaseAuth.instance;
  final GoogleSignIn _googleSignIn = GoogleSignIn();
 

  Future<bool> signGoogle() async {
    try {
      final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;
      final AuthCredential credential =GoogleAuthProvider.getCredential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken
      );
      
        FirebaseUser user =
          (await _auth.signInWithCredential(credential)).user;
      return true;
    } catch (e) { 
      print(e);
      return false;
    }
  }
```

**Comment by iapicca** [comment]
Hi @renanzdm 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose` ?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by eltonmorais** [comment]
I'm with the same error.

![flutter_doctor](https://user-images.githubusercontent.com/29517974/75568153-8507ce00-5a31-11ea-9709-bcf1944bc4c8.jpg)

**Comment by eltonmorais** [comment]
`try {
      final GoogleSignIn _googleSignIn = GoogleSignIn(
        scopes: [
          'email',
          'https://www.googleapis.com/auth/contacts.readonly',
        ],
      );
      final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();      

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await _auth.signInWithCredential(credential)).user;
      setFirebaseUser(_user);
    } catch (e) {
      handleError(e);
    }`

**Comment by eltonmorais** [comment]
`try {
      final GoogleSignIn _googleSignIn = GoogleSignIn(
        scopes: [
          'email',
          'https://www.googleapis.com/auth/contacts.readonly',
        ],
      );
      final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();      

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await _auth.signInWithCredential(credential)).user;
      setFirebaseUser(_user);
    } catch (e) {
      handleError(e);
    }`

**Comment by eltonmorais** [comment]
`try {
      final GoogleSignIn _googleSignIn = GoogleSignIn(
        scopes: [
          'email',
          'https://www.googleapis.com/auth/contacts.readonly',
        ],
      );
      final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();      

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await _auth.signInWithCredential(credential)).user;
      setFirebaseUser(_user);
    } catch (e) {
      handleError(e);
    }`

**Comment by eltonmorais** [comment]
`try {
      final GoogleSignIn _googleSignIn = GoogleSignIn(
        scopes: [
          "email",
          "https://www.googleapis.com/auth/contacts.readonly",
        ],
      );
      final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();      

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await _auth.signInWithCredential(credential)).user;
      setFirebaseUser(_user);
    } catch (e) {
      handleError(e);
    }`

**Comment by eltonmorais** [comment]
`final GoogleSignIn _googleSignIn = GoogleSignIn(
        scopes: [
          "email",
          "https://www.googleapis.com/auth/contacts.readonly",
        ],
      );
      final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();      

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await _auth.signInWithCredential(credential)).user;`

**Comment by eltonmorais** [comment]
final GoogleSignIn _googleSignIn = GoogleSignIn(
        scopes: [
          "email",
          "https://www.googleapis.com/auth/contacts.readonly",
        ],
      );
      final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();      

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await _auth.signInWithCredential(credential)).user;

**Comment by eltonmorais** [comment]
final GoogleSignInAccount _googleUser = await _googleSignIn.signIn();

      final GoogleSignInAuthentication _googleAuth =
          await _googleUser.authentication;

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.accessToken, accessToken: _googleAuth.idToken);

      FirebaseUser _user = (await `_auth.signInWithCredential(credential)).user;

**Comment by efraespada** [comment]
Same here. It starts working fine but after a few (success) logins it doesn't work up to after a while.
Re-installing doesn't fix that, so it could be some a wrong token generation 🤔
