### ISSUE TITLE
[firebase_dynamic_links] allow custom paths for short URLs

### ISSUE THREAD

**Issue by gisinator** [FirebaseExtended/flutterfire#1442]
**Is your feature request related to a problem? Please describe.**
I can create short dynamic links with my own custom domain no problem. They look like "https://app.myapp.com/2dBY" for example and link a user within my app. Problem: "2dBY" doesnt look cool. Within firebase console, custom paths are possible, so my link could look like "https://app.myapp.com/Chris123" for example. In flutter, I did not find a way to do this.

**Describe the solution you'd like**
It would be cool if "DynamicLinkParameters class" could be extended with a new parameter called "urlSuffix" for example. This suffix would be used for short dynamic links, so that even within flutter I could generate userfriendly short links like "https://app.myapp.com/Chris123"

**Additional context**
Guess (and hope) that no more info is required :)

**Comment by edisonpagtakhan** [comment]
I think it's a really great feature to add. However, I realized that there are a lot of things to consider. When building a new dynamic link using the api, it's trying creating a new one. What if the custom path already exists? And how do we make sure that the new and existing paths have the same link?

**Comment by simbakowo** [comment]
If the program is using usernames, which are unique(the app has to deal with this), and the same user generates a new dynamic link again, why not just overwrite the old link . The custon path feature would  be very useful it'll allow user to generate better looking links to get other users to signup eg. instagram/someusername
