### ISSUE TITLE
[cloud_firestore] support for IN and array-contains-any support

### ISSUE THREAD

**Issue by casvanluijtelaar** [FirebaseExtended/flutterfire#1445]
I really need support for the new IN and array-contains-any queries in the cloud_firestore plugin.

**Comment by kizmiaz7** [comment]
Yes please! 

I was super excited to see the firebase team implement this recently as it is something I could very much use in my Flutter app. Please do implement this in the Flutter Firestore Package :).

**Comment by jcsena** [comment]
Yes, I think it is a great feature for the community that uses flutter_firestore.

**Comment by iapicca** [comment]
Hi @casvanluijtelaar 
there's already an [issue ](https://github.com/FirebaseExtended/flutterfire/issues/1333)open addressing the enhancement you proposed
and, as @jcsena already mentioned a PR is on the way.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
