### ISSUE TITLE
[firebase_messaging] Change notification sound

### ISSUE THREAD

**Issue by kitoide** [FirebaseExtended/flutterfire#1446]
How can I change the notification sound using firebase_messaging?

**Comment by iapicca** [comment]
Hi @kitoide 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/523)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
