### ISSUE TITLE
Clearing and reading the unread notifications

### ISSUE THREAD

**Issue by ashish-agarwal** [FirebaseExtended/flutterfire#1450]
How can i read the unread notifications? If a notification is sent and user opens the app from app list instead of notification then how should i read(and/or clear) the notiifcation?

**Comment by iapicca** [comment]
Hi @ashish-agarwal 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you
