### ISSUE TITLE
[firebase_messaging] firebase_messaging should work with flutter_local_notifications

### ISSUE THREAD

**Issue by bparrishMines** [FirebaseExtended/flutterfire#1455]
We currently have a solution for [multiple plugins to receive callbacks](https://github.com/flutter/flutter/issues/22099) as a `UNUserNotificationCenterDelegate`. However, the `firebase_messaging` uses swizzling when you set the `UNUserNotificationCenterDelegate` and [FIRMesssagingDelegate](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessaging#/c:objc(cs)FIRMessaging(py)delegate); as explained [here](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle-swizzle).

It should be possible to have `firebase_messaging` work with other notification plugins and would require disabling of swizzling and handling the callbacks manually. Explained here: https://firebase.google.com/docs/cloud-messaging/ios/receive#handle-swizzle

**Comment by agyimr** [comment]
Are there any news on this?

**Comment by jaumard** [comment]
by having this new issue instead of https://github.com/flutter/flutter/issues/22099 it has been put deep into backlog :( 
Still not possible to have `firebase_messaging` working with other plugin for local notification...

**Comment by bparrishMines** [comment]
Debugging, solving, and testing will probably take about 1-2 weeks. I put this in the January 2020 milestone since this is highly upvoted.

**Comment by omarsherifs** [comment]
is there any news ?

**Comment by pro100svitlo** [comment]
https://media.giphy.com/media/1Cdu8r25fJi3m/giphy.gif

**Comment by pro100svitlo** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/12133914/71977532-4fa4e800-3219-11ea-81b7-408ee2d4fef4.gif)

**Comment by bparrishMines** [comment]
@MaikuB

You said that you tested firebase_messaging and flutter_local_notifications together and didn't receive messages in firebase_messaging.

When I run the example in https://github.com/FirebaseExtended/flutterfire/pull/1785, I get a callback in `onMessage` for firebase_messaging and `onSelectNotification` for flutter_local_notifications.

What did you do to test if you received the remote notification?

**Comment by MaikuB** [comment]
@bparrishMines I was this the app at https://github.com/MaikuB/flutter_firebase_local_notifications_examples/tree/firebase_with_local/java_objc to test. It was pointing to your fork of the phone. For sending notifications, I had a firebase project set up and used the console to send a targeted test notification using the token returned from the plugin

**Comment by MaikuB** [comment]
@bparrishMines i've updated the repo to omit the versions in the pubspec so it should pull the latest versions. The things I've observed using the app in the repo were

- if app is in background and test notification is sent, it will be displayed. That was expected though so all good
- if app is in foreground and I tried to send a test notification, `onMessage` isn't fired. This occurs even if I removed all references to the `flutter_local_notifications` plugin. For`onMessage` to fire when the app is in the foreground, I needed to remove the code in `AppDelegate` for registering the `UNUserNotificationCenterDelegate`. This behaviour is why I suspected the method swizzling is causing issues given I was previously able to create two simple notification related plugins, execute code to fire a notification and `willPresentNotification` would trigger on the iOS side for both plugins (note: this was done a while back and I mentioned it [here](https://github.com/flutter/flutter/issues/22099#issuecomment-533189179))

Note that I do need to make changes following our previous discussion where I'll likely need to have the `flutter_local_notifications` plugin add some additional information to the notification. This is to ensure that the plugin will only triggers callbacks for notifications created by the plugin.

**Comment by audkar** [comment]
> if app is in foreground and I tried to send a test notification, onMessage isn't fired.

I believe current version of `firebase_messaging` doesn't work in background at all https://github.com/FirebaseExtended/flutterfire/issues/1763#issuecomment-572214640 That problem is not related to this issue (_firebase_messaging should work with flutter_local_notifications_)

**Comment by pro100svitlo** [comment]
any updates on this topic?

**Comment by JoseGeorges8** [comment]
> Debugging, solving, and testing will probably take about 1-2 weeks. I put this in the January 2020 milestone since this is highly upvoted.

been 28 days since this update, any news?

**Comment by bparrishMines** [comment]
@MaikuB Could you run `flutter doctor` in a terminal for me. I would like to see what version of Flutter you are using. I was able to receive messages from Firebase Console and I'm using:
`Flutter (Channel master, v1.13.8-pre.69)`

**Comment by MaikuB** [comment]
Ah not at my usual laptop where I do my work but I'm definitely on 1.12.13+hotfix.5 (stable)

**Comment by MaikuB** [comment]
@bparrishMines Went to master and same problem

```
[✓] Flutter (Channel master, v1.14.2-pre.34, on Mac OS X 10.15.2 19C57, locale
    en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (4 available)
```

Can you clarify what you meant by how you were able to receive messages? The issue I see is what I described [here](https://github.com/FirebaseExtended/flutterfire/issues/1455#issuecomment-572509599) but to recap, from my own testing when the [app](https://github.com/MaikuB/flutter_firebase_local_notifications_examples/tree/firebase_with_local/java_objc) is in the foreground, `onMessage` isn't fired.

**Comment by bparrishMines** [comment]
@MaikuB It seems that `onMessage` is fired while the app is in the foreground whether or not these lines are added to `AppDelegate.m`.
 
```
  if (@available(iOS 10.0, *)) {
    [UNUserNotificationCenter currentNotificationCenter].delegate =
        (id<UNUserNotificationCenterDelegate>)self;
  }
```

However, `flutter_local_notifications` stops working when I remove it. I wonder if your issue is related to https://github.com/FirebaseExtended/flutterfire/issues/1041. I also ran `pod update` and `flutter clean` and I was still able to receive messages from both plugins.

**Comment by MaikuB** [comment]
@bparrishMines I believe you're right. I created a PR that from my own testing addresses the issue (see https://github.com/FirebaseExtended/flutterfire/pull/1829)

I created a new branch of the test app I've been using at https://github.com/MaikuB/flutter_firebase_local_notifications_examples/tree/fcm/java_objc that points to my fork of the `firebase_messaging` plugin and all seems to work as expected. May need help from the team to check to take a look and test the PR

**Comment by pro100svitlo** [comment]
hey guys, lets give [this pr](https://github.com/FirebaseExtended/flutterfire/pull/1829) some value with 👍

**Comment by willianfeltri92** [comment]
Guys, any updates on this topic?

**Comment by pro100svitlo** [comment]
@MaikuB thanks!

But I still not able to receive message and show local push notification when ios app is off, even with changes from your repo.

I update my pubspec with repo ref:
```
 firebase_messaging: 
    git:
      url: git@github.com:MaikuB/flutterfire.git
      path: packages/firebase_messaging/
```

also I add line to infoPlist:
```
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
```

To send msg I am using next cmd:
```
curl --location --request POST 'https://fcm.googleapis.com/fcm/send' \
--header 'Authorization: key=myApiKey' \
--header 'Content-Type: application/json' \
--data-raw '{
  "to": "/topics/myTopic",
  "data": {
  	"id":63
  }
}
'
```

So,
- android works as expected 👌 
- when ios app is running - I am able to receive msg and show local notification. 
- when ios app is off - nothing happen. But as soon as app started - it behaves like app just received a push notification.

**Comment by MaikuB** [comment]
@pro100svitlo Deleted my reply and posting it here. Your issue looks to be more to do with using the wrong type of notification. You sent a data notification, which means it's up to the app to display. This won't work when the app is terminated. Refer to the matrix on receiving messages in the readme [here](https://pub.dev/packages/firebase_messaging) and FCM docs on [message types](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages).

**Comment by chaodroger001** [comment]
It work, If I use postman to send only data message.
If I send a Notification, it'll never call `onMessage`.

swift:
`if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
} `

**Comment by rlee1990** [comment]
@chaodroger001 thats an issue with firebase messaging on iOS right now their are a number if open issues for it on flutter

**Comment by erolasan** [comment]
@bparrishMines @kroikie can the solution by @MaikuB be merged soon?

**Comment by t-yasukawa** [comment]
I hope it will be updated soon. :kissing_heart:

**Comment by gitrid** [comment]
I'm also waiting peacefully with crossed fingers :-)

**Comment by balajiks-dev** [comment]
@bparrishMines 
Still not fixed dude!

**Comment by MaikuB** [comment]
@balajiks-dev see my post above. You could use my fork of the plugin whilst the PR hasn't been reviewed/merged

**Comment by bparrishMines** [comment]
This issue should be solved by https://github.com/FirebaseExtended/flutterfire/pull/1829. I'm going to close this unless someone is still having issues with using both of these plugins together. Feel free to ping me if this should remain open.

**Comment by MaikuB** [comment]
Thanks @bparrishMines. FYI there is another incompatibility issue of sorts where notification is removed when it goes to the foreground and is being done by the `firebase_messaging` plugin. This has an effect where local notifications end up being removed as well. #762 tracks it as a bug but #114 states that it's working as intended. I posted my own suggestion on how to solve this [here](https://github.com/FirebaseExtended/flutterfire/issues/114#issuecomment-583697109). Happy to collaborate and discuss further in one of those issues though perhaps one of them should be closed as they look like duplicates
