### ISSUE TITLE
[firebase_messaging] FirebaseMessagingAutoInitEnabled seems to be ignored on iOS

### ISSUE THREAD

**Issue by LucasR93** [FirebaseExtended/flutterfire#1457]
**Describe the bug**
Anyone else experiencing, that the FirebaseMessagingAutoInitEnabled flag in the info.plist file is ignored? Instead of showing the iOS notification permission dialog only after the permission request is called from code, the popup appears directly after first app start.

**To Reproduce**
Setup a new project and add FirebaseMessaging according to default integration tutorial on Firebase homepage.

**Expected behavior**
iOS notification permission dialog should only be shown after the permission requests is called from code, not directly after first app start

**Comment by iapicca** [comment]
Hi @LucasR93 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by LucasR93** [comment]
Flutter Doctor:

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-DE)
    • Flutter version 1.9.1+hotfix.6 at /Users/lucasreiners/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lucasreiners/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/lucasreiners/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Users/lucasreiners/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/lucasreiners/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/lucasreiners/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 6s Plus • F753F1CE-0207-4017-9CA6-820DECF4B3CF • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 4 categories.

**Comment by LucasR93** [comment]
outout of run --verbose is too long to be posted unfortunately

**Comment by LucasR93** [comment]
My bad, another library caused the trouble. Not a bug in firebase messaging :)

**Comment by kareldebedts** [comment]
Same issue, what package was causing the issue?
