### ISSUE TITLE
[firebase_messaging] Firebase Token is valid only for first launch (iOS)

### ISSUE THREAD

**Issue by pkvuled** [FirebaseExtended/flutterfire#1459]
**Describe the bug**
On iOS it seems that generated Firebase Token is valid only for the first launch, after relaunching the app (killing it in app switcher and starting it again) the token received from firebase library is marked as"NotRegistered" while trying to send direct message via FCM api

**To Reproduce**
1. Make a fresh install of the app
2. Perform Firebase messaging init
3. Use received token to send direct message using FCM - at this point it works properly
4. Kill the app and start it again
5. Use the token to send direct message using FCM (token is the same as in point 3) - FCM api returns "NotRegistered"

**Expected behavior**
Token should not depend on app kill/start or should be renewed if is not valid anymore.

**Additional context**
Dependencies:
```
  firebase_core: ^0.4.1+5
  firebase_messaging: ^5.1.6
```

Firebase init:
```
 void initialize() {
    if (Platform.isIOS) {
      _messaging.requestNotificationPermissions(
          IosNotificationSettings(sound: true, badge: true, alert: true)
      );
      _messaging.onIosSettingsRegistered
          .listen((IosNotificationSettings settings) {
        print("Settings registered: ${settings.badge}");
      });
    }

    _messaging.configure(
        onMessage: (Map<String, dynamic> message) async {
          print('on message $message');
        },
        onResume: (Map<String, dynamic> message) async {
          print('on resume $message');
        },
        onLaunch: (Map<String, dynamic> message) async {
          print('on launch $message');
        });
  }
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.11.0, on Mac OS X 10.13.6 17G66, locale pl-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
[✓] VS Code (version 1.38.1)
[✓] Connected device (4 available)
```

**Comment by iapicca** [comment]
Hi @pkvuled 
could you please provide the output of `flutter channel`?
thank you

**Comment by insider1g** [comment]
Here is the output:
```Flutter channels:
  beta
* dev
  master
  stable
```

I have also tested this case on other flutter versions such like:
```
v1.9.1+hotfix.6
v1.12.4
```

But the result is the same.

What is more, I have updated iPhone from iOS 12 to 13, but token behavior hasn't changed.

**Comment by pkvuled** [comment]
Here is the output:

  beta
* dev
  master
  stable
I have also tested this case on other flutter versions such like:

v1.9.1+hotfix.6
v1.12.4
But the result is the same.

What is more, I have updated iPhone from iOS 12 to 13, but token behavior hasn't changed.

**Comment by iapicca** [comment]
Thank you for checking @pkvuled

**Comment by diegoveloper** [comment]
same issue here

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
