### ISSUE TITLE
FAILURE: Build failed with an exception. when registering app to firebase

### ISSUE THREAD

**Issue by AnuragVadd** [FirebaseExtended/flutterfire#1463]
**Describe the bug**
I tried to register my application to firebase and followed the instructions to add the following lines to gradle files : 
```
classpath 'com.google.gms:google-services:4.3.2'
```
```
implementation 'com.google.firebase:firebase-analytics:17.2.0'
apply plugin: 'com.google.gms.google-services'
```
I have also tried to edit it on android studio and also used the "sync now" option and it fails to sync due to an ASCII error.

full error:

```
* Error running Gradle:
ProcessException: Process "E:\flutter apps\todolist_unmodified_dup\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\flutter apps\todolist_unmodified_dup\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: E:\flutter apps\todolist_unmodified_dup\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

```

I have also tried to follow the steps from https://github.com/flutter/flutter/issues/41492 and https://github.com/gradle/gradle/issues/1747, tried to delete .gradle file and flutter clean but the error was still there.

project repository:
https://bitbucket.org/Anurag_vadd/todolist/src/master/

**Comment by daniyalshah** [comment]
Hey, did you figure this out? Having the exact same problem.

**Comment by AnuragVadd** [comment]
> Hey, did you figure this out? Having the exact same problem.

yep, in my case i had to change the code `classpath 'com.google.gms:google-services:4.3.3` to `classpath 'com.google.gms:google-services:4.2.0`.

if that doesnt work, check your `com.android.tools.build:gradle:x.x.x` under android/build.gradle file. at the moment, i am using `com.android.tools.build:gradle:3.2.1`

i would suggest change both lines of code.
