### ISSUE TITLE
[firebase_messaging] Configuring onBackgroundMessage on iOS causes error

### ISSUE THREAD

**Issue by Eddydpyl** [FirebaseExtended/flutterfire#1469]
When _onBackgroundMessage_ is set in the _configure_ method in _FirebaseMessaging_, an error is thrown in iOS and so firebase messaging can't be configured.

`Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#start on channel plugins.flutter.io/firebase_messaging)
`

It may be worth noting that I'm using _flutter_local_notifications_, but this seems unrelated to the other issues reported when working with both libraries at the same time.

**Comment by iapicca** [comment]
Hi @Eddydpyl 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/125) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
