### ISSUE TITLE
Flutter web support for `firebase_storage` plugin

### ISSUE THREAD

**Issue by ptyagicodecamp** [FirebaseExtended/flutterfire#1470]
Hi,

`firebase_storage` plugin doesn't seem to work on Flutter Web. Am I missing something or this plugin is not yet supported for web ? If so, could you point me to workaround to make it work on web ?

Thanks,
Priyanka

**Comment by NoamDev** [comment]
as far as I know flutter for web does not have a plugins management system yet, so generally you cannot use plugins with flutter for web yet.

in general,  flutter for web is still at tech view so you shouldn't use it for production.

but if you really will, it's possible to use js libraries temporarily until they'll add plugins. so you can use the firebase js sdk storage package.

Good luck and happy coding!

**Comment by NoamDev** [comment]
Plugins are not supported yet in flutter web, you should use a wrapper for the js library instead.
in general, flutter web haven't reached alpha yet, and is currently for tech view, it is not recommended to use it for production.

**Comment by iapicca** [comment]
Hi @ptyagicodecamp 
@NoamDev  is right, 

There's a [dart web version](https://pub.dev/packages/firebase) you might want to consider,
you can also take a look to this [solution](https://github.com/flutter/flutter/issues/32637#issuecomment-491968219).

A better [solution](https://github.com/flutter/flutter/issues/45294) is currently work  in progress.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ialhashim** [comment]
@iapicca suggestion helped me enable storage on the web for the time being.

Here is a gist of what I did to enable uploading from the web https://gist.github.com/ialhashim/d0c867daa2dc02cf4e178374abd0ca49

Its a hack for now, I am sure the flutter community will develop an official package soon.
