### ISSUE TITLE
[firebase_messaging] PHONE_REGISTRATION_ERROR on Android API 18 with Google APIs

### ISSUE THREAD

**Issue by mleonhard** [FirebaseExtended/flutterfire#1471]
**Describe the bug**
I'm using `Flutter (Channel master, v1.12.5-pre.16, on Mac OS X 10.15.1 19B88, locale en-US)` and the [firebase_messaging](https://pub.dev/packages/firebase_messaging) 5.1.8 Flutter package.  On startup, my app checks permissions and then calls [`FirebaseMessaging.getToken()`](https://pub.dev/documentation/firebase_messaging/latest/firebase_messaging/FirebaseMessaging/getToken.html).  Running the app inside Android Emulator:
- `Android 5.0 (Google APIs) API 21 x86` works.
- `Android 4.4 (Google APIs) API 19 x86` works.
- `Android 4.3 (Google APIs) API 18 x86` fails with PHONE_REGISTRATION_ERROR.

The Android OS image is SDK package "Android 4.3 (Jelly Bean) - Google APIs Intel x86 Atom System Image - API Level 18 - Revision 6".

**To Reproduce**
1. Create a new Flutter app with `flutter create bug2`.
1. Open Android Studio.
1. Click menu File / Open.  Select the `bug2` directory.
1. Open `pubspec.yaml`, find the `dependencies:` section and add `  firebase_messaging: ^5.1.8`.  Click the "Packages Get" button that appears at the top of the edit window.
1. Log in to the [Firebase Console](https://console.firebase.google.com/) and click "+ Add Project".
1. Enter "bug-demo" as the project name.  Click Continue.
1. Turn off the switch labeled "Enable Google Analytics for this project".  Click Create project.
1. Wait a while.  Click Continue.
1. In the left panel, next to "Project Overview", click the unnamed gear icon.  Click "Project settings" from the popup.
1. Scroll down to the "Your apps" section.  Click the unlabeled blue circle with an Android mascot icon in the middle.  "Add Firebase to your Android app" page appears.
1. Enter `com.example.bug2` in the box labeled "Android package name".
1. Click "Register App".
1. Click "Download google-services.json".  Save it under `bug2/android/app`.
1. Switch back to Android Studio.
1. Open `bug2/android/build.gradle` and add the line
   ```
   classpath 'com.android.tools.build:gradle:3.5.0'
   ```
   at the end of the `buildscript { dependencies {} }` section.
1. Open `bug2/android/app/build.gradle` and add this line at the bottom:
   ```
   apply plugin: 'com.google.gms.google-services'
   ```
1. Open `bug2/lib/main.dart` and change it to be:
   ```dart
   import 'package:firebase_messaging/firebase_messaging.dart'
       show FirebaseMessaging;
   import 'package:flutter/widgets.dart' show WidgetsFlutterBinding;
   
   void main() async {
     WidgetsFlutterBinding.ensureInitialized();
     FirebaseMessaging().configure(
       onMessage: (_) {},
       onResume: (_) {},
       onLaunch: (_) {},
     );
     final String tokenString = await FirebaseMessaging().getToken();
     print('Got "$tokenString"');
   }
   ```
1. Click menu Tools / SDK Manager.
1. Tick the "Show Package Details" box.
1. Under `Android 4.3 (Jelly Bean)` tick the box next to `Google APIs Intel x86 Atom System Image - API Level 18 - Revision 6` and click Apply.  Wait for download and install.
1. Click menu Tools / AVD Manager.  The "Your Virtual Devices" window appears.
1. Click "+ Create Virtual Device..." button.  Click Next.
1. Click "x86 Images" tab.
1. Select "Jelly Bean - 18 - x86 - Android 4.3 (Google APIs)"
1. Click Next and Finish.
1. Select the newly created virtual device and click the triangle button to start it.  The Android emulator window appears.
1. Close the "Your Virtual Devices" window.
1. Click the menu Run / Run main.dart.  The `Run` pane opens on the bottom part of the Android Studio window.  A `main.dart` tab appears on it.  Observe the text appearing there.

You will see something like this:
```
Syncing files to device Android SDK built for x86...
W/FirebaseMessagingPlugin( 3841): getToken, error fetching instanceID: 
W/FirebaseMessagingPlugin( 3841): java.io.IOException: PHONE_REGISTRATION_ERROR
W/FirebaseMessagingPlugin( 3841): 	at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.0:67)
W/FirebaseMessagingPlugin( 3841): 	at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.0:80)
W/FirebaseMessagingPlugin( 3841): 	at com.google.firebase.iid.zzp.then(com.google.firebase:firebase-iid@@20.0.0:4)
W/FirebaseMessagingPlugin( 3841): 	at com.google.android.gms.tasks.zzd.run(Unknown Source)
W/FirebaseMessagingPlugin( 3841): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/FirebaseMessagingPlugin( 3841): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/FirebaseMessagingPlugin( 3841): 	at java.lang.Thread.run(Thread.java:841)
W/FirebaseMessagingPlugin( 3841): getToken, error fetching instanceID: 
W/FirebaseMessagingPlugin( 3841): java.io.IOException: PHONE_REGISTRATION_ERROR
W/FirebaseMessagingPlugin( 3841): 	at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.0:67)
W/FirebaseMessagingPlugin( 3841): 	at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.0:80)
W/FirebaseMessagingPlugin( 3841): 	at com.google.firebase.iid.zzp.then(com.google.firebase:firebase-iid@@20.0.0:4)
W/FirebaseMessagingPlugin( 3841): 	at com.google.android.gms.tasks.zzd.run(Unknown Source)
W/FirebaseMessagingPlugin( 3841): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/FirebaseMessagingPlugin( 3841): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/FirebaseMessagingPlugin( 3841): 	at java.lang.Thread.run(Thread.java:841)
I/flutter ( 3841): Got "null"
```

**Expected behavior**
```
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 2515): eglMakeCurrent: 0xb96914a0: ver 3 0
I/flutter ( 2515): Got "d8xNq2s:APA91bHRJOAMD8RoICUhlKW0nZqwAJdH6Rj9V3aMDVEm3Dh"
```

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
