### ISSUE TITLE
[firebase_messaging 6.0.1] W/FirebaseMessaging(11255): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

### ISSUE THREAD

**Issue by jayvasantjv** [FirebaseExtended/flutterfire#1478]
**Describe the bug**
During onLaunch & onMessage background messages the following error has been thrown: `W/FirebaseMessaging(11255): Missing Default Notification Channel metadata in AndroidManifest. Default value will be
used.` 

**To Reproduce**
1. Add firebase_messaging to pubspec.yaml.
2. Add class path to `[project]/android/build.gradle file.` and apply plugin to `[project]/android/app/build.gradle`.
3. Add .Application class as mentioned [here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging#optionally-handle-background-messages) to `android\app\src\main\java\com\example\appdev\MainActivity.java`
4. Configure `androidmanifest.xml` as follows:
```
     <application
        android:name=".Application"
        android:label="appdev"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:screenOrientation="portrait"> 
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <meta-data
                android:name="com.google.firebase.ml.vision.DEPENDENCIES"
                android:value="ocr" />
        </activity>
    </application>
```
5. Configure firebase in main as follows:
```
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        // Notification while the app is open

        print('onMessage: $message');
        _handlePushNotification(message);
      },
      onLaunch: (Map<String, dynamic> message) async {
        // Clicked on notification

        print('onlaunch: $message');
        _handlePushNotification(message);
      },
      onResume: (Map<String, dynamic> message) async {
        // App running in background

        print('onResume: $message');
        _handlePushNotification(message);
      },
      onBackgroundMessage: myBackgroundMessageHandler,
    );
```
6. Send message using curl as mentioned [here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging#sending-messages) 

**Expected behavior**
The messages for `onMessage` is recieved but, the `onResume` and `onLaunch` should be called upon receiving notification. Although the error has been thrown.

**Additional Context**
I've referenced for the same from #1478 #88 #343 #1357 , but none seemed to work.

**Comment by iapicca** [comment]
Hi @jayvasantjv 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by jayvasantjv** [comment]
logs from [flutter doctor](https://pastebin.com/89ctDTZC)
logs from [flutter run --verbose](https://pastebin.com/8R9Xgdpk)

**Comment by jayvasantjv** [comment]
> Hi @jayvasantjv
> could you please provide your updated `flutter doctor -v`
> and your `flutter run --verbose`?
> Thank you

logs from flutter doctor
logs from flutter run --verbose

Sorry for limited data in --verbose output since my shell can list only that much data. I hope all the requried details are captured.

**Comment by digarahayu17** [comment]
I got same issue even i add meta data in manifest and create strings.xml that contain default channel id still get same error. I use flutter sdk stable version....
Anybody how to make it work in android Oreo 8.0 up to... 
In android lower 8.0 all is work fine

**Comment by digarahayu** [comment]
Any update for this issue..? 
or it will be fix when stable version updated???

**Comment by jayvasantjv** [comment]
> Hi @jayvasantjv
> could you please provide your updated `flutter doctor -v`
> and your `flutter run --verbose`?
> Thank you

@iapicca Why is this thread still tagged with `waiting for customer response`?

**Comment by ankii9600** [comment]
this is a bug in firebase messging plugin .. as they dont provide default notification channel id ..
for fix :

```
class MyApplication : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        this.registerChannel();
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(registry)
    }


    @TargetApi(Build.VERSION_CODES.O)
    private fun registerChannel(){
        val channel: NotificationChannel = NotificationChannel(
                getString(R.string.default_notification_channel_id),
                "CiggyGhar Delivery",
                NotificationManager.IMPORTANCE_HIGH
        ).also {

            it.setSound(Uri.parse("android.resource://${packageName}/${R.raw.deduction}"), it.audioAttributes)
        }
        val manager:NotificationManager = getSystemService(NotificationManager::class.java) as NotificationManager
        manager.createNotificationChannel(channel)
    }
}
```

Next Add this to AndroidManifest file
```
<meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="@string/default_notification_channel_id"/>

```
also define value in string.xml

but this did'nt work...
A little Hack
________________________________________

Add Same Above in firebase_messaging plugins .. AndroidManifest.xml 
also define value in string.xml

That worked for me ..
You need to do a little work around

**Comment by digarahayu** [comment]
> this.registerChannel();

i already edit my code like your Application.kt but when build i got error like this
`: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (19, 4): Unresolved reference: TargetApi
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (19, 14): Unresolved reference: Build
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (21, 18): Unresolved reference: NotificationChannel
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (21, 40): Unresolved reference: NotificationChannel
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (24, 17): Unresolved reference: NotificationManager
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (27, 13): Unresolved reference: it
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (27, 25): Unresolved reference: Uri
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (27, 74): Unresolved reference: raw
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (27, 92): Unresolved reference: it
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (29, 21): Unresolved reference: NotificationManager
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (29, 60): Unresolved reference: NotificationManager
e: /Users/developer1/Documents/JEFRI FERNANDO/FlutterProject/think_clean/android/app/src/main/kotlin/com/example/think_clean/Application.kt: (29, 96): Unresolved reference: NotificationManagerGradle task assembleDebug failed with exit code 1`

maybe is there any package should i import..?
for now  i have import 
`package com.jef.contoh
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService`

**Comment by digarahayu** [comment]
> this is a bug in firebase messging plugin .. as they dont provide default notification channel id ..
> for fix :
> 
> ```
> class MyApplication : FlutterApplication(), PluginRegistrantCallback {
>     override fun onCreate() {
>         super.onCreate()
>         this.registerChannel();
>         FlutterFirebaseMessagingService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry) {
>         GeneratedPluginRegistrant.registerWith(registry)
>     }
> 
> 
>     @TargetApi(Build.VERSION_CODES.O)
>     private fun registerChannel(){
>         val channel: NotificationChannel = NotificationChannel(
>                 getString(R.string.default_notification_channel_id),
>                 "CiggyGhar Delivery",
>                 NotificationManager.IMPORTANCE_HIGH
>         ).also {
> 
>             it.setSound(Uri.parse("android.resource://${packageName}/${R.raw.deduction}"), it.audioAttributes)
>         }
>         val manager:NotificationManager = getSystemService(NotificationManager::class.java) as NotificationManager
>         manager.createNotificationChannel(channel)
>     }
> }
> ```
> 
> Next Add this to AndroidManifest file
> 
> ```
> <meta-data
>         android:name="com.google.firebase.messaging.default_notification_channel_id"
>         android:value="@string/default_notification_channel_id"/>
> ```
> 
> also define value in string.xml
> 
> but this did'nt work...
> A little Hack
> 
> Add Same Above in firebase_messaging plugins .. AndroidManifest.xml
> also define value in string.xml
> 
> That worked for me ..
> You need to do a little work around

i already try Missing Default Notification Channell was not appears... but notification not working onResume and onLaunch

**Comment by marinat** [comment]
@ankii9600 onResume and onLoad works on your android device?

**Comment by Brayan-C** [comment]
> este es un error en el complemento de mensajería firebase ... ya que no proporcionan la identificación del canal de notificación predeterminada ...
> para solucionarlo:
> 
> ```
> class MyApplication : FlutterApplication(), PluginRegistrantCallback {
>     override fun onCreate() {
>         super.onCreate()
>         this.registerChannel();
>         FlutterFirebaseMessagingService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry) {
>         GeneratedPluginRegistrant.registerWith(registry)
>     }
> 
> 
>     @TargetApi(Build.VERSION_CODES.O)
>     private fun registerChannel(){
>         val channel: NotificationChannel = NotificationChannel(
>                 getString(R.string.default_notification_channel_id),
>                 "CiggyGhar Delivery",
>                 NotificationManager.IMPORTANCE_HIGH
>         ).also {
> 
>             it.setSound(Uri.parse("android.resource://${packageName}/${R.raw.deduction}"), it.audioAttributes)
>         }
>         val manager:NotificationManager = getSystemService(NotificationManager::class.java) as NotificationManager
>         manager.createNotificationChannel(channel)
>     }
> }
> ```
> 
> Siguiente Agregar esto al archivo AndroidManifest
> 
> ```
> <meta-data
>         android:name="com.google.firebase.messaging.default_notification_channel_id"
>         android:value="@string/default_notification_channel_id"/>
> ```
> 
> También defina el valor en string.xml
> 
> pero esto no funcionó ...
> Un pequeño truco
> 
> Agregue lo mismo arriba en plugins firebase_messaging. AndroidManifest.xml
> también define el valor en string.xml
> 
> Eso funcionó para mí.
> Necesitas hacer un poco de trabajo

Que debo agregar en el String?
