### ISSUE TITLE
[firebase_admob] Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. 

### ISSUE THREAD

**Issue by and-david** [FirebaseExtended/flutterfire#1483]
**Describe the bug**
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/david/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+9/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'firebase_admob'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Users/david/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+9/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

**To Reproduce**
`flutter build apk`

**Additional context**
firebase_admob: 0.9.0+9

`flutter --version`
```
Flutter 1.11.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 856a90e67c (2 weeks ago) • 2019-11-08 18:00:01 -0800
Engine • revision af04338413
Tools • Dart 2.7.0
```

**Comment by duduf15** [comment]
Same for me.

**Comment by duduf15** [comment]
Nothing new ? It's a severe bug, when the next version of flutter will be release admob will not working anymore. And we will be obliged to update flutter to the new version because au that issue on the current stable version : https://github.com/flutter/flutter/issues/37155

**Comment by redabelca** [comment]
me too , i have that problem.
this is a huge problem that can affect negatively flutter and admob.
what developers will do , when they can't earn money ( through admob ) with their apps.

**Comment by alonhh** [comment]
Same here,
Any updates on this??

Thank you!!


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

**Comment by mo-ah-dawood** [comment]
any update here

**Comment by duduf15** [comment]
I think someone should create a new issue, no one is assigned and it seems no one of the team is looking on old issues

**Comment by caseta** [comment]
Hey All, 

I solved this by following [this answer here](https://github.com/flutter/flutter/issues/29879#issuecomment-504657507)

It involves downgrading your version of `admob` plugin, which worked fine for me. Good luck 👍

**Comment by daneed** [comment]
Hi.
My fix was: goto <yourproject>\android\gradle\wrapper, open gradle-wrapper.properties, where, do change distributionUrl,
FROM: https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
TO: https\://services.gradle.org/distributions/gradle-5.6.2-all.zip (or 5.1.1 or whatewer you want)
For me, this solution worked.
DaneeD
