### ISSUE TITLE
[firebase_messaging] Action Buttons and receiver are needed.

### ISSUE THREAD

**Issue by max202021** [FirebaseExtended/flutterfire#1484]
I am trying to create an app which allow user to quickly take action on push notification without need to go to app. Currently many apps ( including youtube ) allow this feature to take action right from notification drawer.

Solution should be to have a provision to show custom button using firebase push notification and there should be a listener function for user action.

sample image of button is as follows.

![flutter Push Notification](https://user-images.githubusercontent.com/57527948/69480924-144d8600-0e32-11ea-8a53-ff540163c3ee.png)

**Comment by SebAubin** [comment]
This feature would be great!

**Comment by Ehesp** [comment]
Hello - FCM doesn't support this functionality. The solution would be to send a data message via FCM and create your own notification using https://pub.dev/packages/flutter_local_notifications

**Comment by bagintz** [comment]
@Ehesp this would work for all cases except for Android when the app is terminated, correct?  Do you know if the firebase_messaging package will support data messages when the app is terminated any time soon?

**Comment by dkansh** [comment]
I would support to reopen this issue. I am also having similar requirement. I feel it's good to have this feature in firebase messaging.
