### ISSUE TITLE
[cloud_firestore] snapshot not emits when query is with .where() condition

### ISSUE THREAD

**Issue by HaoCherHong** [FirebaseExtended/flutterfire#1491]
**Describe the bug**

`Query.snapshots()` only emits updates when there is no `.where(...)` added

```dart
Firestore.instance.document('games/aov').collection('IngameIds')
  //.where('user', isEqualTo: userDocRef)
  .orderBy('createdAt')
  .snapshots(includeMetadataChanges: true)
  .listen(...);
```

**To Reproduce**
1. remove the commented line

**Expected behavior**
Should emit updates even if there is `where` in the query

**Additional context**
This is in a sub-collection, not top-level collection

Is this a bug or expected behavior?

**Comment by iapicca** [comment]
Hi @HaoCherHong 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` with the line "uncommented",
Thank you

**Comment by HaoCherHong** [comment]
Just ran `flutter run --verbose` and found that the query requires a composite index.
After creating the required index, the snapshots emits correctly.
Big thanks to you. ❤️

**Comment by iapicca** [comment]
Hi @HaoCherHong 
I'm glad to hear that
thank you for letting me know
