### ISSUE TITLE
[firebase_messaging] Group backgroud push notification

### ISSUE THREAD

**Issue by ElderTugBoat786** [FirebaseExtended/flutterfire#1492]
**Is your feature request related to a problem? Please describe.**
I used a backgroudNotidicationHandler to get a push notification when the app is closed.

I can't find a way to customize this notification (in the case of a notification message) or to launch a custom notification in the case of a data message.

Is there a way to group notifications that are automatically launched by the plugin?

**Comment by Ehesp** [comment]
Hello - you can use https://pub.dev/packages/flutter_local_notifications to display a custom local notification.

With FCM, when a message is delivered to the device with a `notification` payload, the SDKs will automatically show the message.

**Comment by Dreamersoul** [comment]
> Hello - you can use https://pub.dev/packages/flutter_local_notifications to display a custom local notification.
> 
> With FCM, when a message is delivered to the device with a `notification` payload, the SDKs will automatically show the message.

the issue with using the following workaround is that in the documentation if you don't supply the notification attribute the notification on iOS devices will not trigger if the application is terminated and only triggered when the application is in foreground.
that requires the backend to save the device type and to be honest feels a bit hacky, i think the library can provide a call back before showing a notification on android that allows the developer to specify the group_id. in my own opinion this will be a really nice addition to the toolset
