### ISSUE TITLE
[cloud_firestore] Support for "IN" operator

### ISSUE THREAD

**Issue by frankps** [FirebaseExtended/flutterfire#1493]
Firestore does not support the OR clause
But, there is the new 'in' operator. 

Official docs: 
https://firebase.google.com/docs/firestore/query-data/queries#in_and_array-contains-any

**Describe the solution you'd like**
Just support for this 'in' operator

(I think) we just need 2 extra lines in de query.dart file:
 Query where(String field, {
   ...
    **dynamic inArray,**
    ...
  }) {

**if (inArray != null) addCondition(field, 'in', inArray);**

}

**Comment by georgeherby** [comment]
There is a PR for this #1405
