### ISSUE TITLE
[all] Test web plugins on Cirrus

### ISSUE THREAD

**Issue by collinjackson** [FirebaseExtended/flutterfire#1495]
Now that we have web versions of Flutterfire plugins we should launch Chrome on Cirrus and use it to run the web tests.

Here's an example of an issue that would hopefully be caught by running tests on a real browser: https://github.com/FirebaseExtended/flutterfire/pull/1487

**Comment by hterkelsen** [comment]
This PR which adds `firebase_core_web` confirms we are now running web tests on Cirrus:
https://github.com/FirebaseExtended/flutterfire/pull/1488

Here is the output from running the web tests with `--platform=chrome`: https://cirrus-ci.com/task/5362653274308608
