### ISSUE TITLE
[firebase_dynamic_links] getInitialLink() not working on Android on version 0.5.0+8

### ISSUE THREAD

**Issue by dpedrinha** [FirebaseExtended/flutterfire#1506]
**Describe the bug**
I'm using dynamic links for **passwordless login** with firebase and **getInitialLink()** is always returning **null** on version **0.5.0+8**.
If I use version **0.4.0+4** and **retrieveDynamicLink()** instead of **getInitialLink()** it works fine.

**To Reproduce**
Since it's working in version **0.4.0+4** I assume the problem is not on Firebase settings.
This is how I'm sending the email:
```
final FirebaseAuth user = FirebaseAuth.instance;
    try {
      user.sendSignInWithEmailLink(
          email: _email,
          androidInstallIfNotAvailable: true,
          iOSBundleID: "com.mydomain.myappname",
          androidMinimumVersion: "16",
          androidPackageName: "com.mydomain.myappname",
          url: "https://myAppName.page.link/fJc4",
          handleCodeInApp: true);
    } catch (e) {
      _showDialog(e.toString());
      return false;
    }
```

And then to retrieve it:
```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _retrieveDynamicLink();
    }
  }

  Future<void> _retrieveDynamicLink() async {
    final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
    print('data == ' + data.toString());

    final Uri deepLink = data?.link;
    print(deepLink.toString());

    if (deepLink != null) {
      _link = deepLink.toString();
      _signInWithEmailAndLink();
    }
    return deepLink.toString();
  }
```

data is always **null** on the new version with **getInitialLink()**. It works on the previous version with **retrieveDynamicLink()**.

**Expected behavior**
Get a non null link

**Additional context**
I'm testing it on Android. I haven't tested for iOS yet.

Here's the flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.864], locale pt-BR)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.5)
> [!] VS Code (version 1.40.0)
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.

**Comment by gisinator** [comment]
On my iOS devices with iOS version 10 and 12 I had to implement a short delay after appstart before calling getInitialLink(), otherwise it returned null. Havent tested how long this delay has to be, but with a 2 second delay it works. Tested both with v1.7.8.hotfix+4 and 1.9.1.hotfix+6

Tested with 0.5.0+6 and 0.5.0+8, didnt work without the delay

**Comment by dpedrinha** [comment]
@gisinator I saw this workaround somewhere else but it doesn't work for Android. Tried with 3 seconds delay and the problem persists.

**Comment by sanekyy** [comment]
Same issue on iOS. On Android all OK.

**Comment by rajesh-anecure** [comment]
The two second delay fix is working. Otherwise, getInitialLink got null

**Comment by allco** [comment]
Firebase 0.6.0, same on iOS. 
`getInitialLink()` returns null time to time but pretty often.

**Comment by madmag77** [comment]
Hey @allco, @sanekyy you could try https://github.com/FirebaseExtended/flutterfire/pull/3567 - I experienced with same problem in ios and found a reason when the initial link is being overwritten by null later so there is a race condition...

**Comment by sanekyy** [comment]
Hello @madmag77. Your PR works great. Thanks.

**Comment by otopba** [comment]
@Salakar Hi!
Could you close this issue because of merge https://github.com/FirebaseExtended/flutterfire/pull/3567 ?
