### ISSUE TITLE
[firebase_messaging] iOS don't received scheduled notifications with option 'Recipient time zone'

### ISSUE THREAD

**Issue by OstapShymansky** [FirebaseExtended/flutterfire#1509]
**Describe the bug**
All **iOS** devices don't receive schedule notifications that are sending to topic, using options 'Recipient time zone'. This problem affect both daily scheduled notifications, and notifications that are scheduled to send only once. 

**To Reproduce**
Create new schedule notification, use topic to set to who send notifications, set time when to send using options 'Recipient time zone' 

**Expected behavior**
Notifications should received in proper timezones and at all platforms(Android and iOS).

**Additional context**
I had made a bunch of tests, all others types of notifications are received OK. No problem when you send notifications to specific Time Zone. No problem with Android platform.
Also i checked it in different conditions - when app are running, in foreground and terminated. In all cases except one that are described, notifications works as should. Problem was tested on different devices and on three last version of lib.

**Comment by iapicca** [comment]
Hi @OstapShymansky 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by OstapShymansky** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale uk-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/ostap/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ostap/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /Users/ostap/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G930P            • f3cc98ac                                 • android-arm64 • Android 8.0.0 (API 26)
    • Test's iPhone • 552759596d34c80143cb4e2bb94b5d22ae750828 • ios           • iOS 12.3.1

**Comment by iapicca** [comment]
Hi @OstapShymansky 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_messaging?
thank you

**Comment by OstapShymansky** [comment]
Yes, i'm still have this issue. I made a bunch of different tests, and looks like this problem are not connected to the flutter firebase_messaging. This feature doesn't work on native iOS platform. I had written native bridge for this feature but have the same problem. Then i just made new project on native iOS, and still no result. So i don't know, but maybe there is some problem on Firebase or iOS side. Android still works as should.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
