### ISSUE TITLE
[firebase_ml_vision] detects wrong text on IOS

### ISSUE THREAD

**Issue by nellybaz** [FirebaseExtended/flutterfire#1511]
**Description**
I used the firebase_ml_vision to recognize text on images, it works perfectly fine on android but on IOS, it reads the wrong text.

**To Reproduce**
1. Follow the instructions on https://pub.dev/packages/firebase_ml_vision and add the plugin to your project.
2. Run you the project on iPhone not simulator.

**Expected behavior**
Just as in Android, it should read the right text on the images 

**Additional context**
I created a native IOS app, integrated Firebase and followed the Firebase ML documentation and it works perfectly fine, recognizing the right text.

**Comment by iapicca** [comment]
Hi @nellybaz 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by nellybaz** [comment]
(base) Nelsons-MBP:~ nelson$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-RW)
    • Flutter version 1.9.1+hotfix.4 at /Users/nelson/Documents/Development/Tools/flutter
    • Framework revision cc949a8e8b (9 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/nelson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • TECNO Camon CX    • 0228010762004464                         • android-arm64 • Android 7.0 (API 24)
    • NellyBaz’s iPhone • fd6e0327ccf60d37f9bc30295e4b4aae0c9bf544 • ios           • iOS 12.4.1

! Doctor found issues in 2 categories.

**Comment by nellybaz** [comment]
Hi @iapicca above is the updated flutter doctor -v

**Comment by iapicca** [comment]
Hi @nellybaz 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_ml_vision?
thank you
