### ISSUE TITLE
[firebase_dynamic_links] When sharing a link on iOS, in the facebook application, the image is not being generated in the dynamic link

### ISSUE THREAD

**Issue by ecvargase** [FirebaseExtended/flutterfire#1513]
When a link is shared directly to Facebook, the image associated with that publication does not appear.

In Android it is working correctly, and using any other application in which it can be shared, it is also working properly

The tests were performed with iOS 12 and 13.

**Comment by iapicca** [comment]
Hi @ecvargase 
if I understand correctly the issue is occurring 
only on iOS 
and when sharing the link specifically to `facebook`'s app,  
am I correct?

could you please provide your `flutter doctor -v` ?
Thank you

**Comment by ecvargase** [comment]
Hi @iapicca 
Yes, only with facebook's app in iOS.

Look
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale es-CO)
    • Flutter version 1.9.1+hotfix.6 
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK 
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc1
    • ANDROID_HOME 
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone de Camilo • ios • iOS 13.1.3

• No issues found!

**Comment by ecvargase** [comment]
@iapicca 
Facebook crawler is taking a long time to analyze the link generated by firebase.
In the constructors of the dynamicLink it is not possible to indicate either the width or the height of the image, Facebook cannot generate the preview of the image with sufficient speed and when making the post, it does not generate the previous image in the facebook application.
That is what I could find.

**Comment by iapicca** [comment]
Hi @ecvargase 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_dynamic_links?
thank you
