### ISSUE TITLE
Sample App Link Doesn't Seem to be Correct

### ISSUE THREAD

**Issue by SubutaDan** [FirebaseExtended/flutterfire#1515]
Hi,

This URL:

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/example

from this page:

https://pub.dev/packages/firebase_auth

gets a 404.

Apparently the link should be:

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example

Thanks.

-Dan

**Comment by iapicca** [comment]
Hi @SubutaDan 
thanks for the correction

**Comment by kirstywilliams** [comment]
Closing as resolved.
