### ISSUE TITLE
[cloud_functions] Error executing Cloud Function

### ISSUE THREAD

**Issue by cmregazzo** [FirebaseExtended/flutterfire#1516]
**Describe the bug**
When using lib cloud_functions, to execute a Firebase Cloud Function, the following error is generated: `[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Instance of 'CloudFunctionsException'  HttpsCallable.call (package:cloud_functions/src/https_callable.dart:48:9).`

Even with the above error, the Cloud function runs in Firebase.

**To Reproduce**
To reproduce the error, simply create a Cloud Function in Firebase, include lib cloud_functions in pubspec.yaml, download the package, and use cloud_functions' own example to call Firebase Cloud Function.

**Expected behavior**
The expected behavior is to get or return the Cloud function.

**Additional context**
Following is the example used: 

` final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable( functionName: 'helloWorld');
`
`final HttpsCallableResult resp = await callable.call();
`
**Doctor**
```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [versÃ£o 10.0.18362.476], locale pt-BR)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\cristian_regazzo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\cristian_regazzo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
Process finished with exit code 0

**Comment by Isti01** [comment]
I figured it out. :)
When you are declaring the CloudFunctions object you need to specify the region if you changed it.
(My function is deployed to europe-west1)
Like this:
`
final CloudFunctions functions = CloudFunctions(region: 'europe-west1');
.
.
.
final response = await functions.getHttpsCallable(functionName: 'myFunction').call();
`

Specifying the region solved the problem for me

**Comment by helenaford** [comment]
Hi  @cmregazzo, did the solution that @Isti01 suggested work for you? Or, are you still experiencing the issue?
