### ISSUE TITLE
[firebase_crashlytics] Example doesn't match the docs

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1517]
The docs [here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics#use-the-plugin) say we just set `FlutterError.onError` and then call `runApp()`, later the docs say: 

>If you want to catch errors that occur in runZoned, you can supply Crashlytics.instance.recordError to the onError parameter

But the example [here ](https://github.com/FirebaseExtended/flutterfire/blob/b49837250c619e7363463db732261737e093557d/packages/firebase_crashlytics/example/lib/main.dart#L20) does:

```
runZoned<Future<void>>(() async {
    runApp(MyApp());
  }, onError: Crashlytics.instance.recordError);
}
```

Which is confusing, as there's no explanation on the benefits of wrapping `RunApp` in a `runZoned`.

Also the examples doesn't show `recordError`, just `log` which doesn't fully match the Android (`logException`) or the iOS (`recordError` with other parameters) docs, so this should be better explained as well.

**Comment by friebetill** [comment]
I was also wondering what the benefits are of `runZoned` until I came across [this StackOverflow post](https://stackoverflow.com/a/27815206/6169345). 
The summary is that you use `Zones` to catch unexpected asynchronous errors.

I would also appreciate it if an explanation with an example or the link to the StackOverflow answer for this is included in the documentation.

**Comment by Salakar** [comment]
Closing in favour of #3623
