### ISSUE TITLE
[cloud_firestore] I do not receive data by minimizing the application

### ISSUE THREAD

**Issue by Nicolr3** [FirebaseExtended/flutterfire#1528]
**Describe the bug**
When entering the app and being in the different sections and suddenly you minimize and these 5-10 minutes without touching the application and when re-entering firestore stops working, you do not receive data when changing pages. I have to close the application completely to make it work.

**To Reproduce**
1. Go to minimize the app
2. 5 minutes after entering I do not receive data from the firestore

**Expected behavior**
Well, keep firestore running after minimizing the application.

**Comment by iapicca** [comment]
Hi @Nicolr3 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` when minimizing and resuming the app?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @Nicolr3 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution
