### ISSUE TITLE
[firebase_messaging v6.0.1] iOS doesn't trigger onMessage() when app in foreground

### ISSUE THREAD

**Issue by building-software-2018** [FirebaseExtended/flutterfire#1530]
**Describe the bug**
iOS doesn't trigger onMessage() when app in foreground. But app is in background, it will trigger onResume() perfectly.
I test on Android, all is oke.

**Additional context**
Test on iPad mini 2 and Ios 12.4.3

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/1041

**Comment by rlee1990** [comment]
I have the same issue are there any updates this will affect an app release for a client

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
