### ISSUE TITLE
Firebase Analytics Flutter 

### ISSUE THREAD

**Issue by SteviePlaysMc4** [FirebaseExtended/flutterfire#1532]
Been looking around haven't find any fix for this problem with flutter

`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)`

Using firebase_analytics: ^5.0.6 in my flutter dependences

**Comment by SteviePlaysMc4** [comment]
Fixed the problem.

Make sure to add classpath 'com.google.gms:google-services:4.0.2' in dependencies. I had         classpath 'com.google.gms:google-services:4.0.1'

**Comment by iapicca** [comment]
Hi @SteviePlaysMc4 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
