### ISSUE TITLE
[firebase_analytics] Option to write UTM arguments

### ISSUE THREAD

**Issue by premtemp1** [FirebaseExtended/flutterfire#1534]
Hello,
  Need an option to write  Source / Medium, Campaign, Source, Medium UTM parameters to Google Analytics from the Flutter app.

Thanks

**Comment by Ehesp** [comment]
Hello - closing this one due to lack of information / details. Please can you show exactly what functionality you're expecting? Maybe a pointer to an example somewhere.

Thanks.
