### ISSUE TITLE
client_context.h file not found - Cannot Run IOS Project

### ISSUE THREAD

**Issue by leonardodavila** [FirebaseExtended/flutterfire#1538]
**Describe the bug**

**To Reproduce**
2. '...'
4. See error or incorrect behavior

**Expected behavior**

**Additional context**
I added firebase to my app, but i can't run it on IOS. Can anybody help me?

![image](https://user-images.githubusercontent.com/1143821/70056605-83597600-15ba-11ea-81ea-05849254c3a1.png)

**Comment by iapicca** [comment]
Hi @leonardodavila 
could you please provide your  `flutter doctor -v`
and your  `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @leonardodavila 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution
