### ISSUE TITLE
[firebase_crashlytics] 65 key/value pairs will be allowed

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1539]
I didn't test this, but reading the code I think I found a bug in this method:

```
void _setValue(String key, dynamic value) {
    // Check that only 64 keys are set.
    if (_keys.containsKey(key) || _keys.length <= 64) {
      _keys[key] = value;
    }
  }
```

So in the line `if (_keys.containsKey(key) || _keys.length <= 64)` when we want to add a new `key`/`value` pair, and there are already 64 `key`/`value` pairs, a 65th will be added. It should be `_keys.length < 64` or `_keys.length <= 63`, thus blocking at `64` and not at `65`, since `if (_keys.length <= 64)` is `true`  for `_keys.length == 64`, which allows one more addition.

**Comment by Salakar** [comment]
Thanks for this report, as you are aware Crashlytics has since had a major rework and we now defer custom key counting/limits to the validators that already exist in the native SDKs (no need to duplicate logic there). 

Going through a bit of issue cleanup today so will close this now.

**Comment by feinstein** [comment]
No problem, happy cleaning :)
