### ISSUE TITLE
[firebase_ml_vision] <CLOUD TEXT RECOGNIZER>

### ISSUE THREAD

**Issue by rubayetevan** [FirebaseExtended/flutterfire#154]
**Is your feature request related to a problem? Please describe.**
can not recognize any other language rather than English

**Describe the solution you'd like**
Please add support to add options in the text recognizer method

**Comment by filipppp** [comment]
Really need this.

**Comment by Ehesp** [comment]
Hello - this issue is more a Firebase ML issue rather than this plugin. Please make a support ticket with Firebase: https://firebase.google.com/support/troubleshooter/contact

To help, provide them with an example of the document which isn't picking up the expected language. Thanks.
