### ISSUE TITLE
[firebase_crashlytics] recordError() "context" should be called "reason"

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1542]
`context` parameter of `recordError()` should be renamed to `reason` as it's very easy to be confused with Flutter's `BuildContext` `context` parameter that's very common on Flutter Widgets.

Also, `reason` matches the iOS API.

**Comment by chen-yumin** [comment]
+1 Good point. I got confused with this one as well.

**Comment by feinstein** [comment]
Yes, but this package is version 0.x.x which means it's still beta and breaking changes can happen, so people should be aware of it. Besides it's a simple fix to just rename it on all files.
