### ISSUE TITLE
[cloud_firestore] - Server connection instability

### ISSUE THREAD

**Issue by yamauchieduardo** [FirebaseExtended/flutterfire#1543]
Usually, when the App has wifi and internet connection Firestore doesn't connect correctly and return the message "Failed to get document because the client is offline." (I pinged to google servers to check the connection/internet in view of the fact that this bug occurs frequently).

If I change the connection to other wifi connections and return to the same wifi connection, the plugins sometimes start to work normally.

Since a few months ago this bug sometimes appears in my Flutter Project, but recently (weeks ago) this bug has appeared more times.

```
 [√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [versÃ£o 10.0.17763.864], locale pt-BR)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (3 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Eduardo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

 [√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7761
```
FlutterFire Plugins in my project:

  ```
cloud_firestore: 0.12.9
  cloud_functions: ^0.4.1+4
  firebase_analytics: ^5.0.0
  firebase_auth: 0.14.0+2
  firebase_core: ^0.4.0+8
  firebase_messaging: ^5.1.8
  firebase_storage: 3.0.5
```

**Comment by knissophiliac** [comment]
I'm also facing this issue. I can say that it was occuring very often with older versions of cloud_firestore package, but now it occurs rarely. My iPhone is always online but it cannot connect to firebase servers when it happens. As a temporary solution I have to say to user to try again :/

Additionally, I do not completely sure but sometimes "geolocator" package is returning similar error message. They may be connected with google servers' connection. To people who are investigating this, I recommend check the similarity with that issue: [https://github.com/Baseflow/flutter-geolocator/issues/223](url)

**Comment by Salakar** [comment]
Hey 👋 

Please could you try the new reworked versions of the plugins and see if this is still an issue? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
