### ISSUE TITLE
[cloud_firestore] Query specifying a Document Reference in the Where clause

### ISSUE THREAD

**Issue by AlessioLuciani** [FirebaseExtended/flutterfire#155]
**Describe the bug**
The current API does not allow you to perform a query, specifying that an attribute has to match with a document reference (in the where clause).

For instance: 
`DocumentReference docRef = Firestore.instance.collection('otherCollectionID').document('myDocumentID');
Firestore.instance.collection('collectionID').where("attributeReference", isEqualTo: docRef);`

**To Reproduce**
1) Create two collections 'collectionID' and 'otherCollectionID' in the database.
2) Create a document in 'otherCollectionID', called 'myDocumentID'.
3) Create a document in 'collectionID' with one attribute of type reference: `attributeReference = otherCollectionID/myDocumentID`
4) Create a reference in flutter `DocumentReference docRef = Firestore.instance.collection('otherCollectionID').document('myDocumentID');` 
5) Perform the query in flutter: `Firestore.instance.collection('collectionID').where("attributeReference", isEqualTo: docRef).getDocuments();`

**Expected behavior**
It should retrieve that one newly created document, but it retrieves none.

**Additional context**
Browsing the where clause source code (https://github.com/FirebaseExtended/flutterfire/blob/28411c1818cd04d81e9d0c531e03ecdd2076c2ba/packages/cloud_firestore/lib/src/query.dart#L119), I've seen that there are no mentions to document references. Instead, in the NodeJS firestore API you can clearly see that this case is managed (https://github.com/googleapis/nodejs-firestore/blob/2737b080170aa144e6d7b6ab40916a82ee7330b0/dev/src/reference.ts#L1129).
Hopefully you can get to fix this :)

**Comment by scullabyte** [comment]
Why was this closed? It still doesn't work for me:
`where('field',isEqualTo:'val').reference()` will return a reference to the entire collection
