### ISSUE TITLE
[firebase_dynamic_links] not working on my iPhone but yes on others

### ISSUE THREAD

**Issue by quetool** [FirebaseExtended/flutterfire#1554]
Hi! I don't even know how to start explaining this or how or where to start debuggin it but dynamic links are not working on my iPhone XR but they are working great on other iPhones like SE, 7 and 11 Pro... 

```
AlfredoMBPro:apperto alfredo$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale es-AR)
    • Flutter version 1.9.1+hotfix.6 at /Users/alfredo/Desktop/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • SM G900H             • 4d0070a74a4821bd                         • android-arm • Android 6.0.1 (API 23)
    • iPhone Alfredo       • 00008020-001A03CE1161002E                • ios         • iOS 13.2.3
    • iPhone SE de Alfredo • 1ef594b0026a2a873a22f86bfa4e3e768b66f9ca • ios         • iOS 13.1.3

• No issues found!
```

**Comment by iapicca** [comment]
Hi @quetool 
can you please provide your  `flutter run --verbose`
debugging on the device that shows the issue?
Thank you

**Comment by quetool** [comment]
> Hi @quetool
> can you please provide your `flutter run --verbose`
> debugging on the device that shows the issue?
> Thank you

Wich logs do I need to capture? Only flutter run? Debugger (Observatory)? All of them?
![Captura de Pantalla 2019-12-06 a la(s) 09 58 56](https://user-images.githubusercontent.com/14978705/70324846-5520a400-180f-11ea-931a-3e99d097966a.png)

**Comment by quetool** [comment]
@iapicca there you go https://gist.github.com/quetool/75947a9a68f25ab2a9a6a49bef677181 I hope it helps!

**Comment by quetool** [comment]
Hi @iapicca, is there something new on this?

**Comment by quetool** [comment]
I am still facing this issue

**Comment by iapicca** [comment]
Hi @quetool 
I cannot access your link above
could you provide your `flutter run --verbose` 
and your `pubspec.yaml` 
if the output doesn't fit could you please attach it as txt file
Thank you

**Comment by quetool** [comment]
> Hi @quetool
> I cannot access your link above
> could you provide your `flutter run --verbose`
> and your `pubspec.yaml`
> if the output doesn't fit could you please attach it as txt file
> Thank you

It was there for a while until I deleted, I thought you downloaded it. I am not confortable sharing those kind of logs. As soon as I go back to work I'll upload again.

**Comment by quetool** [comment]
Sorry! I stopped working with flutter a month ago! I switched back to native. As soon as I return to Flutter I'll update this issue if isn't solved.

**Comment by iapicca** [comment]
Hi @quetool 
given your last message I'm closing the issue for now
Thank you
