### ISSUE TITLE
[firebase_messaging] Unresolved reference: firebasemessaging

### ISSUE THREAD

**Issue by VictorUvarov** [FirebaseExtended/flutterfire#1558]
**Describe the bug**
In the README for background messages. The example for `Application.java` imports `import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;` If you create a new project there is no `FlutterFirebaseMessagingService` class in the Java code `android.main.java.io.flutter.plugins` folder. Are we supposed to create this class ourselves?

**To Reproduce**
1. Create new flutter project
2. read [README](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging)

**Expected behavior**
An implementation example of how to handle `import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;`

**Additional context**
Maybe I am wrong and somehow the Flutter `firebase_messaging` injects the code?

**Comment by mohitjadav** [comment]
in my case there is same issue i solve this by 
creating an new MainActivity.java  
code in class

//
public class MainActivity extends FlutterActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}


//
Hope this one can help you

**Comment by DjivaCanessane** [comment]
It is what I have in this class already, unfortunately it doesn't work.

**Comment by iapicca** [comment]
Hi @VictorUvarov 
does the solution proposed by @mohitjadav works for you?

Hi @DjivaCanessane 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VictorUvarov** [comment]
@mohitjadav solutions is what flutter automatically creates in the `MainActivity.java` or `MainActivity.kt`. My question is related to FCM and having to create my own `FlutterApplication` and my own `FlutterFirebaseMessagingService` as shown in the [README](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging). Do I have to create my own FlutterFirebaseMessagingService to handle background messages correctly?

**Comment by gerryhigh** [comment]
@VictorUvarov that class already exists in the plugin. 

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java

**Comment by VictorUvarov** [comment]
Does the service work in Kotlin or only Java?

**Comment by kaparray** [comment]
@VictorUvarov  In my project on Kotlin not works

**Comment by msarkrish** [comment]
@kaparray Are you solved this problem and written code in Kotlin. I need that in Kotlin. i have one doubt why we need to create new kotlin file Application.kt because i already have some native code in mainActivity file with kotlin.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by JFernandoGomez** [comment]
Please add the correct implementation guide for the latest version of Flutter which enables **MainActivity.kt**  and **kotlin** file
