### ISSUE TITLE
[firebase_auth] [all] Networking Exceptions should be detailed

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1573]
If there's no network connection when I call `user.sendEmailVerification()` I get a generic 

>PlatformException(FirebaseException, An internal error has occurred. [ 7: ], null)

Networking errors should have their own code, this way not only we can present to users a more informative message about the network status, but also we avoid logging network problems as errors in Crashlytics, using `recordError`, avoiding unnecessary alarms and waste of productivity trying to fix something there's no fix.

**Comment by feinstein** [comment]
@iapicca I understand this sounds like an enhancement, but at the same time I feel this should need some sort of higher priority than a simple feature, as it impacts code quality severely. Could you classify it with another higher-priority label as well? Thanks.

**Comment by Ehesp** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
