### ISSUE TITLE
[firebase_auth] Flutter + Firebase Apple Sign In Integration?

### ISSUE THREAD

**Issue by garrettmortara** [FirebaseExtended/flutterfire#1574]
My app just got denied for allowing Google sign in but not Apple sign in. Are there any updates on Firebase support for Apple sign in with Flutter?

**Comment by softnodelabs** [comment]
Any updates on this? Does a workaround exists? I also got an app rejected and my client is pressing me to solve the issue asap.

**Comment by EliasDeuss** [comment]
Firebase also now supports sign in with apple, so this needs to be added to the Flutter firebase_auth package. Here are the links for each platform.
[iOS](https://firebase.google.com/docs/auth/ios/apple?authuser=0)
[Android](https://firebase.google.com/docs/auth/android/apple?authuser=0)
[Web](https://firebase.google.com/docs/auth/web/apple?authuser=0)

**Comment by EliasDeuss** [comment]
Looks like there is a open PR that someone is working on. #1526
