### ISSUE TITLE
[Firestore] Possible misleading information in a doc?

### ISSUE THREAD

**Issue by cielo** [FirebaseExtended/flutterfire#1579]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to check if doc is up to date.

**Additional context**
Hi,

I use Firestore library, and found out possible outdated information.

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/lib/src/transaction.dart#L88

The above doc says that developer can provide `SetOptions` param to enable merge operation, but it appears that the method signature of `set` does not accept any arguments related to `SetOptions`.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days along with the new documentation website. Thank you

**Comment by thecoffeehog** [comment]
@Salakar just wanted to know whether we will be having set options in future releases or just the documentation will be updated?

**Comment by Salakar** [comment]
Both, changes are on master but not yet published and we also have a new docs website.

**Comment by thecoffeehog** [comment]
Awesome @Salakar !
