### ISSUE TITLE
[firebase_analytics] iOS Runtime Arguments Not Working

### ISSUE THREAD

**Issue by willhaslett** [FirebaseExtended/flutterfire#1586]
**Describe the bug**
Reference #844. Can not connect to Firebase Analytics from the iOS emulator, but it works if you run from XCode. History suggests XCcode runtime argument not getting respected.

**To Reproduce**
1. Create a vanilla Flutter app
2. Replace replace /lib/main.dart with [these two files](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics/example/lib).
2. Add Firebase via the instructions [here](https://firebase.google.com/docs/flutter/setup)
4. Enable Firebase Analytics via ADB and test debug logging from the Android emulator (works)
5. Enable Firebase Analytics for iOS via the instructions [here](https://firebase.google.com/docs/flutter/setup) and [here](https://firebase.google.com/docs/analytics/get-started?platform=ios)
6. Discover (documented?) that you need to add the `-FIRDebugEnabled` runtime argument in XCode, and do so.
7. Debug analytics now work when the app is launched via XCode, but not when it is launched via Android Studio or the CLI.

**Expected behavior**
When launching from AS or the CLI, should be able to connect to Firebase Analytics.

**Additional context**
Flutter doctor:
```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/will/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/will/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.6.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • AF5B6408-768A-4C8C-A392-25125F77272C • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
```

**Comment by blasko** [comment]
Posting again here for visibility. 

Still seeing this issue with no obvious fix or resolution almost 1 year on. Any progress or information that could potentially lead to a resolution?

This seems like it will have a much larger impact on overall workflow and productivity. Hopefully something turns up in the way of a fix or workaround soon.

**Comment by russellwheatley** [comment]
We have documented how to debug Analytics from both platforms [here](https://firebase.flutter.dev/docs/analytics/usage#debug-analytics-events). You are also able to run from flutter CLI once the `-FIRDebugEnabled` flag has been set in Xcode. Other than that, there isn't much else we can do from a Flutterfire perspective.
