### ISSUE TITLE
[firebase_analytics, firebase_crashlytics] deprecating the install_referrer intent ( Migrate to the Play Install Referrer API)

### ISSUE THREAD

**Issue by Xgamefactory** [FirebaseExtended/flutterfire#1594]
Google is changing install referer api and current install_referrer intent  will be deprecating.
Is there any plans to migrate this plugin ?
Thanks.
> Hello Google Play Developer,
> 
> We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.
> 
> Action required
> 
> Migrate to the Play Install Referrer API to track your app installs for the following apps and/or games.

**Comment by Sarthaktydy** [comment]
Any update?

**Comment by us3soap** [comment]
Hello, we are in the same case. Do you have visibility on the upgrade of firebase core?

**Comment by Sarthaktydy** [comment]
> Hello, we are in the same case. Do you have visibility on the upgrade of firebase core?

What framework you're using to build your app?

**Comment by us3soap** [comment]
We work with :
- Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale fr-FR)
- firebase_core: 0.4.1+5
- firebase_analytics: 5.0.6
- firebase_crashlytics: 0.1.1+2

**Comment by Salakar** [comment]
Closing due to age and the latest versions of Core and Analytics Android SDKs are now in use.
