### ISSUE TITLE
[firebase_admob] Add BannerAd support as widget using PlatformView instead of native view over activity.

### ISSUE THREAD

**Issue by awazgyawali** [FirebaseExtended/flutterfire#161]
As its clear by the title. Can't we add this feature, I didn't find any ongoing work on this matter. I want to work on this but wanted to know if anyone is working it already?

**Comment by awazgyawali** [comment]
I have migrated BannerAd to Platform View. Details: #163

**Comment by kirstywilliams** [comment]
Closing. PR merged, see https://github.com/FirebaseExtended/flutterfire/pull/163

**Comment by kirstywilliams** [comment]
As per the comments on https://github.com/FirebaseExtended/flutterfire/pull/163, specifically https://github.com/FirebaseExtended/flutterfire/pull/163#issuecomment-532431192 it is not possible to merge this at this time. Happy to revisit in future if things change. Closing this issue.
