### ISSUE TITLE
enable public_member_api_docs for all plugns

### ISSUE THREAD

**Issue by collinjackson** [FirebaseExtended/flutterfire#1610]
Running documentation lint checks on CI will help us get Flutterfire ready for Flutter Favorite. Right now they're being ignored in analysis_options.yaml. We need to go through incrementally and enable the lint rule and add missing documentation.

This issue tracks progress on the Flutterfire plugins. There's an issue for flutter/plugins: https://github.com/flutter/flutter/issues/45440.

## Related issues

https://github.com/flutter/flutter/issues/46808
https://github.com/flutter/flutter/issues/45440

**Comment by mklim** [comment]
My [comment on the related issue](https://github.com/flutter/flutter/issues/46808#issuecomment-565127913) also applies here.

> could you link to an instance where it appears that CI is ignoring this file? In my testing I remember being blocked in multiple PRs based on analysis failures from the `analysis_options.yaml`, so I'd be really surprised if we weren't using it _at all_. I think it's probably more likely that there's a specific issue with it being applied to a particular package somehow.
> 
> ETA: packages that were already failing lints in the root `analysis_options.yaml` have their own sub `analysis_options.yaml` excluding them from the global linter rules that they're already failing. Most plugins were failing `public_member_api_docs`, and there's been a long tail of work cleaning them up: flutter/flutter#45440. It could be that the failure to alert that you're seeing is from this?

**Comment by collinjackson** [comment]
I think that's right, thanks for looking into it.
