### ISSUE TITLE
[fireabase_crashlytics] Java compilation error after upgrade to Flutter 1.12

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1612]
I upgraded Flutter to 1.12 and Crashlytics (0.1.2+3) and Auth (0.15.2) to the latest versions, now I get this warning message when I build my app:

>Note: C:\Programming\Flutter\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.1+5\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Programming\Flutter\sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.2+3\android\src\main\java\io\flutter\plugins\firebase\crashlytics\firebasecrashlytics\FirebaseCrashlyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by nihalreddy33** [comment]
Same here

**Comment by Ehesp** [comment]
Hello - please try upgrading to the latest version of the plugin. If this issue persists, please let me know and I'll re-open the issue.

**Comment by Ehesp** [comment]
sh
