### ISSUE TITLE
[firebase_messaging] Type mismatch: inferred type is PluginRegistry? but FlutterEngine was expected

### ISSUE THREAD

**Issue by Jacobsjj2** [FirebaseExtended/flutterfire#1613]
Following the [instructions on pub.dev](https://pub.dev/packages/firebase_messaging) for handling background messages doesn't compile for Android since the `GeneratedPluginRegistrant.registerWith` method takes a `FlutterEngine` object as a parameter. Using the `PluginRegistry` provided by the method throws the error

```
Type mismatch: inferred type is PluginRegistry? but FlutterEngine was expected
```
Please see the below code for reference
```
package ...

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application: FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(registry) //Error thrown here
    }
}
```
**To reproduce**
1. Follow the steps in the given link up to step 1 of [**Optionally handle background messages**](https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages)
2. Build the project

**Expected behavior**
Somehow a FlutterEngine object should be passed to the method in order to successfully build for Android

**Comment by hsangtini** [comment]
Fixed by replace with: 

```
class MainApplication : FlutterApplication(), PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    override fun registerWith(registry: PluginRegistry?) {
        registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin");
    }

}
```

**Comment by iapicca** [comment]
Hi @Jacobsjj2 
does the solution proposed by @hsangtini  work for you?
thank you

**Comment by Jacobsjj2** [comment]
This does allow me to compile, but I'm not sure if the background service is being registered correctly since I get the error

```
E/flutter (12123): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#initialized on channel plugins.flutter.io/firebase_messaging_background)
E/flutter (12123): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (12123): <asynchronous suspension>
E/flutter (12123): #1      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:51:21)
E/flutter (12123): #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (12123): #3      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:24:32)
E/flutter (12123): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (12123): #5      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (12123): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (12123): #7      _runZoned (dart:async/zone.dart:1518:10)
E/flutter (12123): #8      runZoned (dart:async/zone.dart:1502:12)
E/flutter (12123): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (12123): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (12123): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
Doesn't the replacement simply return a `Registrar` object without registering anything?

**Comment by hsangtini** [comment]
> This does allow me to compile, but I'm not sure if the background service is being registered correctly since I get the error
> 
> ```
> E/flutter (12123): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#initialized on channel plugins.flutter.io/firebase_messaging_background)
> E/flutter (12123): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> E/flutter (12123): <asynchronous suspension>
> E/flutter (12123): #1      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:51:21)
> E/flutter (12123): #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
> E/flutter (12123): #3      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:24:32)
> E/flutter (12123): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
> E/flutter (12123): #5      _rootRun (dart:async/zone.dart:1126:13)
> E/flutter (12123): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter (12123): #7      _runZoned (dart:async/zone.dart:1518:10)
> E/flutter (12123): #8      runZoned (dart:async/zone.dart:1502:12)
> E/flutter (12123): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
> E/flutter (12123): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> E/flutter (12123): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> ```
> 
> Doesn't the replacement simply return a `Registrar` object without registering anything?

Try this replace @Jacobsjj2 
```
    override fun registerWith(registry: PluginRegistry?) {
  io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    }
```

**Comment by Jacobsjj2** [comment]
Sorry for the delay! @hsangtini's latest suggestion works. I guess it would also be necessary to update the documentation to that then?

**Comment by jayvhaile** [comment]
I tried your solution and i am getting 

>  Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
>     class io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService, unresolved supertypes: com.google.firebase.messaging.FirebaseMessagingService

**Comment by isyantoID** [comment]
> Fixed by replace with:
> 
> ```
> class MainApplication : FlutterApplication(), PluginRegistrantCallback {
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this);
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin");
>     }
> 
> }
> ```

tq work for me

**Comment by insinfo** [comment]
I also had this problem, I changed the "Application.kit" to the suggested one. and now it's compiling, I just haven't tested the notifications yet.

### Application.kt
```kotlin
package br.gov.rj.riodasostras.riodasostrasapp

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
//import com.google.firebase.messaging.FirebaseMessagingService

 class Application : FlutterApplication() , PluginRegistrantCallback {
   
   override fun onCreate() {
     super.onCreate();
     FlutterFirebaseMessagingService.setPluginRegistrant(this);
   }

   override fun registerWith(registry: PluginRegistry?) {
     //GeneratedPluginRegistrant.registerWith(registry);
     //registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin");
      io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
   }
 }
```

### MainActivity.kt
```kotlin
package br.gov.rj.riodasostras.riodasostrasapp

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

```

Ideally, the Readme and documentation should be updated

**Comment by yourshinsuke** [comment]
`android/app/src/main/kotlin/com/example/my_app/MainActivity.kt`

```
package com.example.my_app

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
//import com.google.firebase.messaging.FirebaseMessagingService

class Application : FlutterApplication() , PluginRegistrantCallback {
  override fun onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  override fun registerWith( registry: PluginRegistry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

**Comment by yourshinsuke** [comment]
@insinfo 
Hello
You mean.
rename `Application.kt` to `MainActivity.kt`?
How is your `android/app/src/main/AndroidManifest.xml`?

Do you import? both of them?
```
        <activity
            android:name=".MainActivity"
// something

        <activity
            android:name=".Application"
        />
```

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. Additionally, messaging now supports v2 embedding.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
