### ISSUE TITLE
[firebase_auth_web] Failed to build app with firebase after update firebase_auth(0.15.2)

### ISSUE THREAD

**Issue by Elvian-DissoLver** [FirebaseExtended/flutterfire#1614]
I upgraded Flutter to 1.13.0 and firebase_auth (0.15.2) to the latest versions, now I get this error message when I build my app:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :firebase_auth_web.
     Required by:
         project :app > project :firebase_auth
      > Unable to find a matching configuration of project :firebase_auth_web: None of the consumable configurations have attributes.
   > Could not resolve project :firebase_core_web.
     Required by:
         project :app > project :firebase_core
      > Unable to find a matching configuration of project :firebase_core_web: None of the consumable configurations have attributes.

**Comment by rignaneseleo** [comment]
Take a look here: https://github.com/flutter/flutter/issues/46807

**Comment by Elvian-DissoLver** [comment]
> Take a look here: [flutter/flutter#46807](https://github.com/flutter/flutter/issues/46807)

I still get error for the latest version of  firebase_auth_web and firebase_core_web

**Comment by draganjovanovic1** [comment]
`flutter pub cache repair` did the magic for me. Build works now

**Comment by iapicca** [comment]
Hi @Elvian-DissoLver 
does the solution proposed by @draganjovanovic1  solve the issue?
thank you

**Comment by Jacobsjj2** [comment]
I was facing the same issue and was only able to compile after switching to the `beta` branch of flutter. I'm assuming there may be a problem in the `dev` channel?

**Comment by draganjovanovic1** [comment]
I am on master channel and it worked for me:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.1-pre.99, on Mac OS X 10.15.1 19B88, locale en-RS)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[!] Connected device
```

**Comment by Elvian-DissoLver** [comment]
> Hi @Elvian-DissoLver
> does the solution proposed by @draganjovanovic1 solve the issue?
> thank you

OK it work, after upgrade flutter to (1.13.1)
Thankz for solve it
