### ISSUE TITLE
realtime database, onChildAdded listener

### ISSUE THREAD

**Issue by katerjiabedalaziz** [FirebaseExtended/flutterfire#1616]
the onChildAdded event is triggered whenever i use the databasereference.once.then(), even though nothing is being added to the database so the onChildAdded should not be called

**Comment by iapicca** [comment]
Hi @abedkaterji 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` while using `databasereference.once.then()`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you
