### ISSUE TITLE
[firebase_auth] 0.15.2 signInAnonymously

### ISSUE THREAD

**Issue by nikitadol** [FirebaseExtended/flutterfire#1618]
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("isNewUser")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53)
#1      _decodeAdditionalUserInfo (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:450)
#2      _decodeAuthResult (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:443)
#3      MethodChannelFirebaseAuth.signInAnonymously (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:54)
<asynchronous suspension>
#4      FirebaseAuth.signInAnonymously (package:firebase_auth/src/firebase_auth.dart:42)
#5      _LoginScreenState._signIn (package:remindful/screen/login_screen.dart:28)
```

**Comment by iapicca** [comment]
Hi @nikitadol 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by nikitadol** [comment]
Hi @iapicca 
This is already fixed here.
https://github.com/FirebaseExtended/flutterfire/blob/b41ca632e8fb428f170dd4e42c45390b3a6b7505/packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel_firebase_auth.dart#L449-L451

But firebase_auth refers to an old version of code
https://github.com/FirebaseExtended/flutterfire/blob/b41ca632e8fb428f170dd4e42c45390b3a6b7505/packages/firebase_auth/firebase_auth/pubspec.yaml#L22

**Comment by iapicca** [comment]
Hi @nikitadol 
I'm glad you fixed the issue
thank you for letting me know
