### ISSUE TITLE
[firebase_dynamic_links] onLink and getInitialLink not working on iOS

### ISSUE THREAD

**Issue by calebisstupid** [FirebaseExtended/flutterfire#1624]
Dynamic links on iOS are properly redirecting to app or app store when needed, but the actual link data and callback are not working.

1. set up custom dynamic link for our product in firebase: https://share.myapp.com/share
2. add "applinks:share.myapp.com" as an associated domain
3. add appropriate url type "com.myapp.mobile" with identifier "share_url"
4. create dynamic link via:
```
final DynamicLinkParameters parameters = DynamicLinkParameters(
    uriPrefix: 'https://share.myapp.com/share',
    link: Uri.parse(urlString), //this is our backend/webapp share url
    androidParameters: AndroidParameters(
      packageName: 'com.myapp.mobile',
      minimumVersion: 1,
    ),
    iosParameters: IosParameters(
      bundleId: 'com.myapp.mobile',
      minimumVersion: '1.0.0',
      appStoreId: '<numbers>',
    ),
  );
```
5. share that link: android works no problem, callbacks and links hit properly and parsed on Android. web redirection works great. iOS will open app store if not installed, and open app if it is installed, but the onLink function is never hit and getInitialLink is null (even if opened from link).

I'm by no means intimately familiar with web type stuff; could this be something with the "/share" piece on the end of the url?

Flutter Doctor:
```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)
```
Using:  ```  firebase_dynamic_links: ^0.5.0+8```

**Comment by iapicca** [comment]
possible duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1571

**Comment by blaneyneil** [comment]
This looks to be separate from #1571, and is still a major open bug on iOS 13.  Of the three possible ways to handle the payload:

1) app is installed and hot, using `onLink()`
2) app is installed and cold, using `getInitialLink()`
3) app is not installed, using `getInitialLink()` after AppStore redirect

it's 3 that is failing.  1 and 2 are working reliably (for me at least), and 3 is failing maybe 60-70% of the time.

**Comment by blaneyneil** [comment]
And worth noting that I've tested both `buildUrl()` and `buildShortLink()` to generate the urls in case the latter was causing a lookup delay, but they both failed routinely.

**Comment by LucasTejero** [comment]
Did you set your team id and the app id in the App configuration for firebase?

**Comment by blaneyneil** [comment]
@LucasTejero not sure who you're asking that of, but yes, everything is configured properly.  It's only on iOS13 cold installs where the payload is not preserved.  Hot opens are fine, cold opens after install are fine, everything on Android is fine.

**Comment by jbryanh** [comment]
I would like to point out that issue #6260 experienced the issue when app was hot in background.  Above, @blaneyneil says it's an uninstalled app that fails.  Different issues.
