### ISSUE TITLE
[firebase_messaging] Deprecation warning after updating flutter.

### ISSUE THREAD

**Issue by jcvw75** [FirebaseExtended/flutterfire#1625]
```bash
Note: d:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.8\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

-----------------------Using this flutter--------------------

Flutter 1.12.13+hotfix.5 ΓÇó channel stable ΓÇó
https://github.com/flutter/flutter.git
Framework ΓÇó revision 27321ebbad (2 days ago) ΓÇó 2019-12-10 18:15:01 -0800
Engine ΓÇó revision 2994f7e1e6
Tools ΓÇó Dart 2.7.0
```

**Comment by iapicca** [comment]
Hi @jcvw75 
could you please run 
`flutter clean`
`flutter pub cache repair`
if the issue persists please your `flutter doctor -v`
and your `flutter run --verbose`?
thank you

**Comment by hungbu** [comment]
`Launching lib\main.dart on MI MAX 2 in debug mode...
Running Gradle task 'assembleDebug'...
Note: D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device MI MAX 2...`

-------------------------------flutter doctor -v---------------------------
`D:\project\workspace>flutter doctor -v
[√] Flutter (Channel unknown, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hungb\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\hungb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • MI MAX 2 • b0e5de04 • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
`

----flutter run --verbose---
[flutter_run_verbose.txt](https://github.com/FirebaseExtended/flutterfire/files/4001980/flutter_run_verbose.txt)

--------------------------------------------------------------------------

**Comment by azizainunnajib** [comment]
hai, do you solve this?  i just got the error here.

**Comment by williamdes** [comment]
@iapicca I am using
```
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (il y a 5 semaines) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```
`firebase_messaging 6.0.9`

I applied your comment https://github.com/FirebaseExtended/flutterfire/issues/1625#issuecomment-565448974

```
Note: /mnt/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+13/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /mnt/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.9/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
/mnt/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^                                               
1 warning                                                               
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService, unresolved supertypes: com.google.firebase.messaging.FirebaseMessagingService
```

And still have the issue, please fix the deprecated code :)

**Comment by williamdes** [comment]
downgrading `shared_preferences: ^0.5.6` to `shared_preferences: ^0.5.3` solved the deprecation errors

https://stackoverflow.com/questions/58706496/getting-error-while-adding-shared-preferences-to-flutter-app

`class io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService, unresolved supertypes: com.google.firebase.messaging.FirebaseMessagingService` got solved by
https://github.com/FirebaseExtended/flutterfire/issues/1606#issuecomment-565134789

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
