### ISSUE TITLE
isn't working for flutter sdk >1.10.0 

### ISSUE THREAD

**Issue by jawale204** [FirebaseExtended/flutterfire#1627]
Because flash_chat depends on cloud_firestore >=0.13.0+1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
pub get failed (1)
exit code 1

this is what i get after i add the cloud_firestore in my .yaml file dependencies

**Comment by iapicca** [comment]
Hi ... 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
thank you

**Comment by TahaTesser** [comment]
Hi @jawale204 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
