### ISSUE TITLE
[firebase_messaging] Notification not shown on android 6 

### ISSUE THREAD

**Issue by boucoding** [FirebaseExtended/flutterfire#1632]
I am working on an app and I've used firebase_messaging plugin to push notification but I can't receive any notification on android 6 but it works on android 9 and Q perfectly.

I didn't receive any error in firebase cloud functions logs and when I use local notification plugin it works perfectly and can receive the upcoming notification but it doesn't work in the background.

Should I create a background message handler like that described in readme.md of the plugin or to create a notification channel?

Please help me because I'm stuck at this point and all my work stopped because of.

**Comment by iapicca** [comment]
Hi @abdu987 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by abdu987** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\boood\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by iapicca** [comment]
Hi @abdu987
can you please provide your `flutter run --verbose`?
Thank you

**Comment by boucoding** [comment]
I am sorry for the issue this is produced from this phone only and not on any android marshmallow.

thanks
