### ISSUE TITLE
[firebase_auth] _auth.verifyPhoneNumber method is not working with Flutter web 1.12.13+hotfix.6

### ISSUE THREAD

**Issue by yashharkhani** [FirebaseExtended/flutterfire#1634]
```dart
void _verifyPhoneNumber() async {
    ...
    ...
    await _auth.verifyPhoneNumber(
        phoneNumber: _phoneNumberController.text,
        timeout: const Duration(seconds: 5),
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
  }
```
On calling _auth.verifyPhoneNumber() method it shows error as below.

![Screenshot from 2019-12-13 11-43-51](https://user-images.githubusercontent.com/22542889/70773631-fecadc80-1d9d-11ea-91dc-8216b605f2b5.png)

**Comment by shubhabanerjeewin8** [comment]
signIn() async {
    try {
      final AuthCredential credential = PhoneAuthProvider.getCredential(
        verificationId: verificationId,
        smsCode: smsOTP,
      );
      final FirebaseUser user = await _auth.signInWithCredential(credential);
      final FirebaseUser currentUser = await _auth.currentUser();
      assert(user.uid == currentUser.uid);
      Navigator.of(context).pop();
      Navigator.of(context).pushReplacementNamed('/homepage');
    } catch (e) {
      handleError(e);
    }
  }

try this method

**Comment by iapicca** [comment]
Hi @yashharkhani 
did the solution proposed by @shubhabanerjeewin8 (thank you) worked for you?

If it didn't 
could you please provide your `flutter run --verbose`?
Thank you

**Comment by ronytesler** [comment]
inside the function 'verifyPhoneNumber' (version 0.15.4):
    throw UnimplementedError('verifyPhoneNumber() is not implemented');
So there's no way to use phone verification? The example code also uses this method.
What am I missing?

**Comment by ronytesler** [comment]
inside the function 'verifyPhoneNumber' (version 0.15.4):
throw UnimplementedError('verifyPhoneNumber() is not implemented');
So there's no way to use phone verification on web?

**Comment by MarcelEdward** [comment]
I get the same error, flutter web cannot access _auth.verifyPhoneNumber 

In that function is gets the verificationId needed (and on android the code)
I think something goes wrong in here: https://www.gstatic.com/firebasejs/7.7.0/firebase-auth.js

**Comment by AnandSaran** [comment]
I'm also facing the same issue.

**Comment by iapicca** [comment]
Hi @MarcelEdward  and @AnandSaran 
does this [solution](https://github.com/FirebaseExtended/flutterfire/issues/1634#issuecomment-565467265) work for you?
If doesn't 
could you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you
