### ISSUE TITLE
Firebase auth with Transaction in flutter 

### ISSUE THREAD

**Issue by tarektaamali** [FirebaseExtended/flutterfire#1636]
I want to make a transaction in update profile in firebase if any error in request i make rollback .does flutter and firebase authentification support Transactions.
![image](https://user-images.githubusercontent.com/17914433/70801365-00e96700-1daf-11ea-9cb8-589e017a6bd7.png)

**Comment by Ehesp** [comment]
Hello, this is now supported: https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Firestore/runTransaction.html
