### ISSUE TITLE
The plugin cloud_firestore could not be built due to the issue above.

### ISSUE THREAD

**Issue by muriloks** [FirebaseExtended/flutterfire#1638]
Hi, 
I was build a flutter app with firebase using a AVD. The app is almost done, running without any error, but when i try to build a release version i got this error:
The plugin cloud_firestore could not be built due to the issue above.

Here is the build apk --verbose: https://pastebin.com/rSEHS8iz

That is my build gradle(/android/l):
https://pastebin.com/jtaNF1cC

That is my build gradle(/android/app/):
https://pastebin.com/tV1crnzQ

And that is my pubspec.yaml:
https://pastebin.com/bpNrxTbj

**Comment by subhamX** [comment]
I am facing the same problem. Can someone help?

**Comment by muriloks** [comment]
Hello everyone,
I've solved my problem. 
One of my dependences in .flutter\.pub-cache\hosted\pub.dartlang.org\ was using CompileSdkVersion 27 in build.gradle.
I just changed it to 28 and everything works just fine.

**Comment by adbr-dev** [comment]
Same problem but it is already set to 28...

**build.gradle**
android { 
  compileSdkVersion 28 
  ...
}

**Comment by imeDevelopers** [comment]
[fixed](https://github.com/flutter/flutter/issues/56208#issue-611250180)
