### ISSUE TITLE
[firebase_admob] RewardedVideoAd Server-Side-Verification parameters missing

### ISSUE THREAD

**Issue by dr4xor** [FirebaseExtended/flutterfire#164]
I'm using rewarded video ads and want to verify that users actually watched them by using 
Server-side verification callbacks.
(https://developers.google.com/admob/android/rewarded-video-ssv)

However I need to specify the **_user_id_** and **_custom_data_** parameters in order to work with those callbacks. E.g. to determine which user watched the ad.

In the native android admob implementation setter methods for those parameters already exist

[setUserId(String userId)](https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAd#setUserId(java.lang.String))
[setCustomData(String customData)](https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAd#setCustomData(java.lang.String))

But I did to find anything similar in the firebase_admob package yet

**Comment by Ehesp** [comment]
Closed via https://github.com/FirebaseExtended/flutterfire/pull/173
