### ISSUE TITLE
[fireabase_auth] ERROR_REQUIRES_RECENT_LOGIN has more precedence than ERROR_EMAIL_ALREADY_IN_USE.

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1640]
`ERROR_REQUIRES_RECENT_LOGIN` has more precedence than `ERROR_EMAIL_ALREADY_IN_USE`. 

I tried to change the email of the user with another user's email, as a test, and I got `ERROR_REQUIRES_RECENT_LOGIN` which would take the user to new login process, just later to find out that other email he probably has is already in use. I believe It would be more correct if `ERROR_EMAIL_ALREADY_IN_USE` had more precedence.

**Comment by helenaford** [comment]
Consolidating under #1223 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
