### ISSUE TITLE
[cloud_firestore] Deleted documents remain in collection snapshots

### ISSUE THREAD

**Issue by ChristofferSkog21st** [FirebaseExtended/flutterfire#1647]
**Describe the bug**
When querying the database I get snapshots of documents that no longer exists.

**To Reproduce**
I can't give exact reproduction steps as this happens very randomly, but it makes the code breaks when doing if statements for snapshot lengths for example.

You can however try something along these lines, starting with an empty collection:

1. Login with provider of your choice
2. Create a new document in any collection in the firestore with the user uid as the document key/id
3. Fetch a **collection snapshot** (`QuerySnapshot`)
4. Hot restart flutter
5. Login again
6. Manually remove a document by removing it via the firebase console
7. Repeat step 3 and you should see a `QuerySnapshot.documents.length` of 1 rather than 0

**Expected behavior**
I don't expect deleted documents to appear in the snapshot, I can't tell if this is a cache issue or not because even when I kill flutter, remove the installed app and then run it again, the deleted documents still appear in the snapshots.

**Additional context**

Here's an example of a deleted document that I've printed after running the query:

`{game: othello, hasEnded: false, playerTwo: null, hasStarted: false, hostScore: 1000, playerOne: 2CjvZsLHktXz1j0iryzFKhRUlxI2, isActive: false}`

by doing:

`print(ongoingGamesSnapshot.documents.first.data);`

Here `2CjvZsLHktXz1j0iryzFKhRUlxI2` is the uid of a user that no longer exists, and the document has that same string as `documentID`.

And here's what my database looks like (after logging out, refreshing the browser etc):

<img width="625" alt="db" src="https://user-images.githubusercontent.com/47322485/70863840-a0902c00-1f4c-11ea-8c70-1ce5c2f8547b.png">

As you can see the collection "ongoingGames" doesn't even exist anymore. I'm not sure what to make of this issue, perhaps it's already known but I haven't managed to find any information on this.

**Comment by emmett-deen** [comment]
Having this same issue. Need fixed ASAP

**Comment by Ehesp** [comment]
Not sure how this one is possible to be honest as the data comes straight from Firebase native SDKs. I'll leave open to add tests.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this should have been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
