### ISSUE TITLE
[cloud_functions] How to set the region for firebase functions using flutter

### ISSUE THREAD

**Issue by febg11** [FirebaseExtended/flutterfire#1649]
I can see that there is a region string in the CloudFunctions class but there doesn't seem to be a way to set it. How can I achieve this?

**Comment by o-gi** [comment]
Try like this.

```
final CloudFunctions _cloudFunctions =
    CloudFunctions(region: 'YOUR_FUNCTION_REGION');

final HttpsCallable testFunction = _cloudFunctions.getHttpsCallable(
  functionName: 'YOUR_FUNCTION_NAME',
);
```

**Comment by ronpetit** [comment]
Can confirm @o-gi solution works

**Comment by helenaford** [comment]
Closing this. @febg11 if the above solution didn't work and you are stll having issues,  please could you post your question on StackOverflow using the Flutter tag; https://stackoverflow.com/questions/tagged/flutter
