### ISSUE TITLE
firebase 5.0.9 uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Xgamefactory** [FirebaseExtended/flutterfire#1650]
`pub.dartlang.org/firebase_analytics-5.0.9/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.`

same for firebase_core 

```
pub.dartlang.org/firebase_core-0.4.3+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by NathofGod** [comment]
I'm getting the same issue stopping me run projects

**Comment by kiranbhagannavar** [comment]
You can find the solution here [#1401](https://github.com/FirebaseExtended/flutterfire/issues/1401)

**Comment by tnup** [comment]
No, there is no solution there, just suggestions.

**Comment by PauloHenrique81** [comment]
Some one could solve this ?

**Comment by SandroMaglione** [comment]
Same error, for all the Firebase plugin that I am using in my project and also the share plugin

```
\pub.dartlang.org\firebase_analytics-5.0.9\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
\pub.dartlang.org\firebase_core-0.4.3+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
\pub.dartlang.org\firebase_crashlytics-0.1.2+4\android\src\main\java\io\flutter\plugins\firebase\crashlytics\firebasecrashlytics\FirebaseCrashlyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
\pub.dartlang.org\cloud_firestore-0.13.0+1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
\pub.dartlang.org\firebase_messaging-6.0.9\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
\pub.dartlang.org\firebase_performance-0.3.1+5\android\src\main\java\io\flutter\plugins\firebaseperformance\FirebasePerformancePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
\pub.dartlang.org\share-0.6.3+5\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by egarson** [comment]
> No, there is no solution there, just suggestions.

There are several suggestions there, many of which may help ^_^.

**Comment by Dattaya** [comment]
@rodruiz fixed this issue, run `flutter packages upgrade` and it should all be fine even after `flutter clean`

**Comment by jokonugr** [comment]
> @rodruiz fixed this issue, run `flutter packages upgrade` and it should all be fine even after `flutter clean`

Thx bro, this fixed for whole my "uses or overrides a deprecated API" problem

**Comment by Abdulfetahjemal** [comment]
past this on the app build gradle:

multiDexEnabled true

Example ...

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.uber"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

**Comment by Ehesp** [comment]
Closing - please upgrade your flutter packages & enable multi-dex if required. Se https://github.com/FirebaseExtended/flutterfire/issues/1401
