### ISSUE TITLE
[firebase_auth] iOS verifyPhoneNumber Token mismatch

### ISSUE THREAD

**Issue by Antonimo** [FirebaseExtended/flutterfire#1655]
I get a token mismatch error on iOS, on any of the latest versions. it does work with this old that someone made: https://stackoverflow.com/questions/57395948/flutter-firebase-phone-auth-always-returns-token-mismatch-on-ios
But why it doesn't work on the original repository and after so many updates?

I tried using APNs Authentication Key.
I tried using the APNs Certificates instead.
I re-downloaded the google-services-json many times.
I think the fact that it works with the fix someone made means that there is something missing in package code or in the setup instructions.

**Comment by nrooban** [comment]
Yes, I too getting this issue.

**Comment by nrooban** [comment]
simply upgraded the firebase_auth version to latest and worked like charm.
firebase_auth: ^0.15.3+1

**Comment by Antonimo** [comment]
upgraded the firebase_auth version to latest, ^0.15.3+1, still same issue, tested on multiple different iphones

**Comment by AmruthPillai** [comment]
Yep, same here. Updating doesn't seem to do the trick. Really frustrated with this.

**Comment by mathu97** [comment]
Is there any update on this? I've tried using both the APNs authentication key and APNs certificate as well and cannot seem to figure out why I see token mismatch.

**Comment by nrooban** [comment]
This is wired, I also getting the Token mismatch issue while a ago. Some time works some time did not.

But this time i get worked with 
===========================
firebase_auth:
    git:
      url: https://github.com/collinjackson/plugins.git
      ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
      path: packages/firebase_auth 
===========================
Steps I did
1. Deleted build folder 
2. added above firebase_auth package to pubspec.yaml and click Package Get
3. Deleted perviously installed app in iOS device
4. Installed fresh copy

**Comment by Antonimo** [comment]
a verbose mode would be nice to see what kind of steps and requests are happening behind the scenes

**Comment by mathu97** [comment]
For me, it started working as soon as I deployed it to test flight, but it still does not work when I try to run it locally on my phone (As I still get token mismatch).

**Comment by yukitaka13-1110** [comment]
Hi everyone!
I'm getting the same error. I found out odd behavior.

At first, I installed my newest app version, but it didn't work.
Next, I installed my older app version, and it worked.
Finally, I installed newest one again, and it worked.


Is there anything we can tell from this?

**Comment by AlexBacich** [comment]
With some magic problem just disappeared today. What is more interesting - it is working now with both @nroobah solution and with simply latest version: firebase_auth: 0.15.4
p.s. struggled 3 days before that

**Comment by Shlaayl** [comment]
I have same problem with firebase_auth: 0.15.4 in real device iPhone.
Simulator is working with 0.15.4

**Comment by rignaneseleo** [comment]
Same problem with `firebase_auth: 0.15.5+3`: on the simulator, I get the CAPTCHA code and it works, on a physical iPhone I get the errors `Token mismatch` and then `ERROR_MISSING_VERIFICATION_ID, The phone auth credential was created with an empty verification ID`.

Everything seems to have set up well on firebase (certificates, APNs, etc.): the normal notifications work well.

**Comment by acoutts** [comment]
@rignaneseleo 's fix worked for me as well.

One thing: I was seeing this warning:
```
2020-04-16 15:27:01.981926-0400 Runner[23543:7794346] Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
```

Commenting out `print(userInfo)` fixed that for me.

**Comment by MichaelM97** [comment]
This is still present on version `0.16.1`, and @rignaneseleo's fix is still working, but it would be good to get a fix on the plugin side!

**Comment by amitkabra59** [comment]
Hi! I have used Phone Authentication to authenticate users with firebase_auth, and I successfully get back my Firebase User. I want to keep the user authenticated when they come back to the app. It works perfectly on Android but when I close my IOS app, I am redirected to page where I enter OTP and OTP is sent again to my mobile number which I logged in previously. I am having a hard time figuring out stuff with IOS. I do not understand why I am sent to the verification SMS page every time I opened the app after login. The verification is completed automatically when I open the app without sending SMS. I cannot understand why it behaves differently with IOS
I have performed the steps in https://firebase.google.com/docs/auth/ios/phone-auth including setting up APN's and reverse client in info.plist! I am stuck on these things from days. Please help
I am saving the login type option and triggering the following code when the user restarts app after login: I do not get any error but this is really bad for the production

` Future  (BuildContext context, String phoneNumber) async {
    final FirebaseAuth _auth = FirebaseAuth.instance;
    await _auth.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        timeout: Duration(seconds: 0),
        verificationCompleted: (authCredential) =>
            _verificationComplete(authCredential, context),
        verificationFailed: (authException) =>
            _verificationFailed(authException, context),
        codeAutoRetrievalTimeout: null,
        codeSent: (verificationId, [code]) => _smsCodeSent(
            verificationId: verificationId,
            code: [code],
            context: context,
            phoneNumber: phoneNumber));
  }
  _verificationComplete(AuthCredential authCredential, BuildContext context) {
    FirebaseAuth.instance.signInWithCredential(authCredential);
    if (!smsCodeSent) handleLogin(context, authCredential);
  }
  _verificationFailed(AuthException authException, BuildContext context) {
    Navigator.of(context).pushNamedAndRemoveUntil(
        AuthPage.routeName, (Route<dynamic> route) => false);
  }
  _smsCodeSent(
      {String verificationId,
      List<int> code,
      BuildContext context,
      String phoneNumber}) {
    smsCodeSent = true;
    _smsVerificationCode = verificationId;
    smsOTPDialog(context, phoneNumber);
  }
  smsOTPDialog(BuildContext context, String userPhoneNumber) {
    Navigator.of(context)
        .push(_createRoute(userPhoneNumber, _smsVerificationCode));
  }`

**Comment by amitkabra59** [comment]
`
 Future  (BuildContext context, String phoneNumber) async {
    final FirebaseAuth _auth = FirebaseAuth.instance;
    await _auth.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        timeout: Duration(seconds: 0),
        verificationCompleted: (authCredential) =>
            _verificationComplete(authCredential, context),
        verificationFailed: (authException) =>
            _verificationFailed(authException, context),
        codeAutoRetrievalTimeout: null,
        codeSent: (verificationId, [code]) => _smsCodeSent(
            verificationId: verificationId,
            code: [code],
            context: context,
            phoneNumber: phoneNumber));
  }
  _verificationComplete(AuthCredential authCredential, BuildContext context) {
    FirebaseAuth.instance.signInWithCredential(authCredential);
    if (!smsCodeSent) handleLogin(context, authCredential);
  }
  _verificationFailed(AuthException authException, BuildContext context) {
    Navigator.of(context).pushNamedAndRemoveUntil(
        AuthPage.routeName, (Route<dynamic> route) => false);
  }
  _smsCodeSent(
      {String verificationId,
      List<int> code,
      BuildContext context,
      String phoneNumber}) {
    smsCodeSent = true;
    _smsVerificationCode = verificationId;
    smsOTPDialog(context, phoneNumber);
  }
  smsOTPDialog(BuildContext context, String userPhoneNumber) {
    Navigator.of(context)
        .push(_createRoute(userPhoneNumber, _smsVerificationCode));
  }
`

**Comment by adalberht** [comment]
Hey, any news on this issue?
@rignaneseleo 's fix is still working, but as @MichaelM97 's said, it would be good to get a fix too on the plugin side!

**Comment by superakabo** [comment]
I have realized that deleting your app without signing out first causes this problem.
You'll also notice that you are automatically logged in after reinstalling your app.
So if you are experiencing this, sign out of your app and restart the authentication process.

**Comment by jfrsbg** [comment]
I've been following this issue since 0.16.1 and now with the release of 0.18.0 I'm getting the same problem, are no one looking for this problem? Man, I'm really stuck here, I already tried the @rignaneseleo fix in both versions and still doesn't woking. I already follow all the steps in https://firebase.flutter.dev/docs/auth/phone and the problem still persists, why apple makes things incredible complicated???? It's really frustanting, I've been trying to fix this for 2 weeks without any success. The thing is it's working on emulator but not working on real device, how can I understand this apple way to make things?? Can anyone give some update, please?

**Comment by Salakar** [comment]
Closing pending merge & release of https://github.com/FirebaseExtended/flutterfire/pull/3345. Thanks @Ehesp

**Comment by long1eu** [comment]
Any news on the release?
