### ISSUE TITLE
[firebase_admob] Can't run flutter app when firebase_admob is added as a dependency. Error:  "Waiting for observatory port to be available..."

### ISSUE THREAD

**Issue by 99darshan** [FirebaseExtended/flutterfire#1656]
I created a new flutter project **( Flutter 1.12.13+hotfix.5 )** then added **firebase_admob** as a dependency in package.yaml. When I try to run the app it crashes.

`flutter run --verbose` gives a message "Waiting for observatory port to be available..." and it gets stuck there

I tried removing firebase_admob as a dependency and added other packages like url_launcher, flutter_pdfview, etc. and the app works just fine.

Not sure if there is a problem with my dev environment setup or problem with the package itself. I created a new project and added firebase_admob to the dependency, that's all I did.

**Comment by diegoismael81** [comment]
I have the same problem... any news????

**Comment by diegoismael81** [comment]
I resolved it! I had an error because I placed the AdMob IDs inside 'activity' instead of 'application'.

**Comment by 99darshan** [comment]
Not sure which part exactly did the trick but I solved this by setting:

android/build.gradle:

```
dependencies {
    classpath 'com.android.tools.build:gradle:3.5.0'
    classpath 'com.google.gms:google-services:4.3.3'
}
```

android/app/build.gradle:

```
dependencies {
    ...
    implementation 'com.google.android.gms:play-services-ads:16.5.0'
}
```

android/app/source/main/AndroidManifest.xml
Making sure

```
 <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-XXXXXXXXXXXX~XXXXXX"/>
```

was set as a direct child to <application> and not under <activity>
