### ISSUE TITLE
[firebase_messaging] Documentation and example out of sync 6.0.9

### ISSUE THREAD

**Issue by ninnepinne** [FirebaseExtended/flutterfire#1657]
**Describe the bug**
The documentation and the example project are out of sync.

To make matters worse there are a lot of issues with the latest release: https://github.com/FirebaseExtended/flutterfire/issues/1606 (and some other related and linked to this)

**To Reproduce**
1. Read and follow the documentation.
2. You might enjoy failing builds and inconsistent behaviour.
3. Look into the example project to verify your code and setup (by comparison).
4. Discover that the example project handles plugin registration completely different from what is described in the documentation. Different code and different versions.
5. Feel utterly confused ;-)

Which method should be used?

**Expected behavior**
The example and the documentation should be using the same code.

**Comment by Dr-Legend** [comment]
same for me

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
