### ISSUE TITLE
[firebase_messaging] when onBackgroundMessage is called ?

### ISSUE THREAD

**Issue by woprandi** [FirebaseExtended/flutterfire#1660]
**Describe the bug**
According to the documentation of the `firebase_messaging` plugin, we can define a `onBackgroundMessage` callback. But when it is called ?
According to the table [here](https://pub.dev/packages/firebase_messaging#receiving-messages),`onMessage` would be called even when the app is in the background. Either it is an error in the documentation or something is missing

**Comment by dmiedev** [comment]
The `onBackgroundMessage` is called only on data message with no notification body when the app is terminated or in background.

**Comment by iapicca** [comment]
Hi @woprandi 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1590) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
