### ISSUE TITLE
[firebase_crashlytics] Printing lots of old errors during compilation after 1.12 upgrade

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1662]
After I upgraded to the latest version of Flutter:

>Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.476], locale pt-BR)

>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.40.0)
[√] Connected device (1 available)

>• No issues found!

And I click the Debug button to launch my app in and Android AVD I get hundreds of lines of errors in my console while the app is compiling, then later it installs just fine.

They look like old messages printed on the past days, exceptions I got while designing my UI, I uninstalled my app and reinstalled in the AVD but its the same, I also tried `flutter clean`.

These are the messages, they are huge, so I am just showing a printscreen:

![image](https://user-images.githubusercontent.com/8120472/70816674-c384d980-1dae-11ea-8bc9-0d211e57a093.png)

Take a look at the scroll handle so you can have an idea on all of the messages being printed just after I clicked the Debug button.

As you can see, they start once the compilation starts, and later when the APK is built they end, so they are being dumped during the compilation phase, as this can be shown here:

![image](https://user-images.githubusercontent.com/8120472/70817253-f4b1d980-1daf-11ea-97dc-523c29b3272d.png)

I don't know if this is related to #46898.

Using a separate device I don't get this messages.

**Comment by rkpradeep20** [comment]
Facing the same problem.

**Comment by xEyad** [comment]
me too have the same problem

**Comment by feinstein** [comment]
So give it a thumbs up 👍🏻, they give more priority to more thumbs up.

**Comment by helenaford** [comment]
closing this (see https://github.com/flutter/flutter/issues/46898 for more information).

**Comment by feinstein** [comment]
Thanks @helenaford I am already there too.

Guess today is cleanup day? Lots of issues being closed, thanks for your help.

**Comment by helenaford** [comment]
no problem. yes, a lot of work planned for this repo.
