### ISSUE TITLE
[FlutterFire Plugins] - Lack of pattern when instanciating/getting the instance of the FlutterFire plugins

### ISSUE THREAD

**Issue by yamauchieduardo** [FirebaseExtended/flutterfire#1667]
In my project, I use some FlutterFire plugins, like:

```
Firestore
FirebaseAuth
FirebaseStorage
CloudFunctions
FirebaseAnalytics
FirebaseMessaging
Crashlytics
FirebasePerformance
```

I miss a pattern when instantiating/getting the instance of the plugins:

**using default google.json:**

```
Firestore firestore =  Firestore();
FirebaseAuth FirebaseAuth =  FirebaseAuth.instance;
FirebaseStorage firebaseStorage = FirebaseStorage();
CloudFunctions cloudFunctions = CloudFunctions();
FirebaseAnalytics firebaseAnalytics = FirebaseAnalytics();
FirebaseMessaging firebaseMessaging = FirebaseMessaging();
Crashlytics crashlytics = Crashlytics();
FirebasePerformance firebasePerformance = FirebasePerformance.instance;
```

**from app:**

```
Firestore firestore =  Firestore(app:app);
FirebaseAuth FirebaseAuth =  FirebaseAuth.fromApp(app);
FirebaseStorage firebaseStorage = FirebaseStorage(app:app);
CloudFunctions cloudFunctions = CloudFunctions(app:app);
```

Why when using google.json (default) the plugins FirebaseAuth, FirebasePerformance instantiate in a different way?

Wouldn't it be better if every plugin were instantiated in the same way?

**Comment by Salakar** [comment]
Hey, our firebase_core rework has now landed on master via #2890 - we hope to start publishing preview releases to test out next week which should solve this issue (and others). All plugins will eventually use this new core and therefore provide identical APIs to get their instances (we've done Firestore & Auth already in upcoming PRs).

Thank you for raising this issue 👍
