### ISSUE TITLE
[firebase_messaging] can't find com.google.firebase.messaging.FirebaseMessagingService (6.0.9)

### ISSUE THREAD

**Issue by cuijinfeng68** [FirebaseExtended/flutterfire#1668]
in android ,com.google.firebase.messaging.FirebaseMessagingService

**Comment by cuijinfeng68** [comment]
Running Gradle task 'assembleDebug'...
  无法访问FirebaseMessagingService
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
                                       ^
  找不到com.google.firebase.messaging.FirebaseMessagingService的类文件
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by cuijinfeng68** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012, locale zh-Hans-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/jackcui/Desktop/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by behlsoft** [comment]
any update?

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
