### ISSUE TITLE
[firebase_messaging] iOS 13 and Xcode 11 Changes That Affect Push Notifications

### ISSUE THREAD

**Issue by rodruiz** [FirebaseExtended/flutterfire#167]
**Is your feature request related to a problem? Please describe.**
A new attribute is required on all APNS (Apple Push Notification Service) API headers.
Apple recently added a new attribute to the headers for APNS Payloads: apns-push-type.

Per [Apple’s documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc), the value of this header must be set to "alert" or "background", based on whether the notification has user-visible content or not.
According to Apple, this header is:

“Required when delivering notifications to devices running iOS 13 and later, or watchOS 6 and later.”

**Describe the solution you'd like**
You can see OneSignal suggestion [here](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/)

**Additional context**
Ignore this if your code already supports iOS 13. iOS 13 comes out on September 19th.

**Comment by Ehesp** [comment]
This is out of scope for this library - it's more of something you should be setting when sending push notifications from your own server implementation.

I'll close this however it'll be one to mention in the docs.
