### ISSUE TITLE
[firebase_ml_vision] Tensorflow lite custom models

### ISSUE THREAD

**Issue by bhack** [FirebaseExtended/flutterfire#1675]
**Is your feature request related to a problem? Please describe.**
As developer I need an easy and reliable path to use custom Tensorflow lite models in flutter apps.

**Describe the solution you'd like**
Add an example to cover Firebase with custom Tflite models

**Additional context**
https://firebase.google.com/docs/ml-kit/use-custom-models

**Comment by bhack** [comment]
See also https://codelabs.developers.google.com/codelabs/mlkit-android-custom-model/index.html

**Comment by Ehesp** [comment]
Closing in favour of https://github.com/FirebaseExtended/flutterfire/issues/788
