### ISSUE TITLE
[Firebase Storage] <Uploading an image succeeds but in the Firebase console the path is different and URL gives 404>

### ISSUE THREAD

**Issue by chirmac** [FirebaseExtended/flutterfire#1676]
Whenever I attempt to upload a sample image (JPEG) to Firebase, it never presents an error client-side, however, once I go to the console to try and open it, it gives a 404 error. Also, the path in the console is altered and the image doesn't preload.

To reproduce, just make a button and execute the following:
```dart
var result = await FilePicker.getMultiFile(type: FileType.IMAGE);
if (result != null) {
    print(basename(result.first.path));
    FirebaseStorage.instance.ref().child("images").child("test.jpeg").putFile(result.first, StorageMetadata(contentType: "image/jpeg")).onComplete.then((
}
```

I use:

```xaml
firebase_storage: ^3.1.0
file_picker: ^1.4.3+1
```

This is what happens (in the client app, no error occurs):

![image](https://user-images.githubusercontent.com/19695011/71056705-a7779400-2130-11ea-88ad-2760c726610b.png)

As you can see, the path is different from what I coded and the image does not load.

The image is no problem, as if I upload it through the Firebase console it uploads normally, just the Flutter upload gives this behavior.

If I need to add any more information, please ask. I've been trying for days now.

**Comment by prabathh** [comment]
Any updates?

**Comment by Ehesp** [comment]
In order to generate a "public URL" you need to call the `getDownloadURL` method: https://pub.dev/documentation/firebase_storage/latest/firebase_storage/StorageReference/getDownloadURL.html

When you upload the image via the console yourself, this is automatically handled for you, but with SDKs you need to do it yourself.
