### ISSUE TITLE
[dynamic_links] Short Dynamic links are blocked ios.

### ISSUE THREAD

**Issue by naumanmir** [FirebaseExtended/flutterfire#1678]
I am getting this error on ios.
```bash
Dart Error: Unhandled exception:
PlatformException(Error 0, com.firebase.durabledeeplink, The operation couldn’t be completed. Requests to this API firebasedynamiclinks.googleapis.com method google.firebase.dynamiclinks.v1.DynamicLinksService.CreateShortDynamicLink are blocked.)
```

**Comment by iapicca** [comment]
Hi @naumanmir 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by letiagoalves** [comment]
Me too. Any update on this?

**Comment by iapicca** [comment]
HI @naumanmir 
can you please provide your `flutter doctor -v`,
your `flutter run --verbose`
and your `pubspec.yaml`
Thank you
