### ISSUE TITLE
[cloud_firestore] Array Union overwrites data.

### ISSUE THREAD

**Issue by dzliergaard** [FirebaseExtended/flutterfire#168]
**Describe the bug**
`FieldValue.arrayUnion` overwrites contents of an array instead of appending.

**To Reproduce**
1. Create collection `data_collection`
2. Create document `data` in `data_collection`
3. Add field `field` of type Array to `data`
4. Add item `Hello` to `field`.
5. Run this code in a flutter app:

```
import 'package:cloud_firestore/cloud_firestore.dart';

...

var ref = Firestore.instance.document("data_collection/data");
ref.setData({
  "field": FieldValue.arrayUnion(["World"]),
});
```

6. Review `data` document in Firestore, observe that contents are just ["World"].

**Expected behavior**
`FieldValue.arrayUnion` should just add the item to the array.

**Additional context**
Output of `flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.3-pre.66, on Microsoft Windows [Version 10.0.18362.356], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.38.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by kenwen** [comment]
Not tried arrayunion before but have you tried setting merge to true?

so

var ref = Firestore.instance.document("data_collection/data");
ref.setData({
  "field": FieldValue.arrayUnion(["World"]),
}, merge: true);`
`

**Comment by iapicca** [comment]
Hi @dzliergaard  
is the proposed resolution working for you?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
