### ISSUE TITLE
🐛 [Firestore] Vector fields compatible with real-time snapshot listeners.

### ISSUE THREAD

**Issue by Lerobindesbois** [FirebaseExtended/flutterfire#16823]
I know that vector fields are not compatible on Flutter when there is a listener on the collection or there is the presence of a vector.

But it is impossible to make a reactive application with the database without using snapshot stream.

Unfortunately and luckily I have realtime listeners from snapshot and it is incompatible with vector field feature, it is useful for smart searches and blocks the progress of an AI application. Almost all developers use STREAM on Firestore like me. 

Is it possible to prioritize and complete the work on this feature?

**Comment by SelaseKay** [comment]
Hi @Lerobindesbois, thanks for bringing this up. This issue is already being worked on, and you can track its progress [here](https://github.com/firebase/flutterfire/issues/13299).
