### ISSUE TITLE
[firebase_auth_web] time to implement fetchSignInMethodsForEmail

### ISSUE THREAD

**Issue by azol** [FirebaseExtended/flutterfire#1682]
`firebase_auth_web.dart` contains unimplemented `fetchSignInMethodsForEmail` waiting for resolving https://github.com/FirebaseExtended/firebase-dart/issues/272.

https://github.com/FirebaseExtended/firebase-dart/issues/272 is resoled so it's time to implement :)

**Comment by Ehesp** [comment]
Support has landed for this in the latest release.
