### ISSUE TITLE
[CloudMessaging] didReceiveRemoteNotification is not fired in Flutter plugin

### ISSUE THREAD

**Issue by sglim** [FirebaseExtended/flutterfire#1683]
**Describe the bug**
didReceiveRemoteNotification is not fired while its implementation is in FlutterPlugin.

**To Reproduce**
1. Create a plugin project to test APNs remote notification (It requires some setting to get APNs)
2. Register DeviceToken correctly
3. Send Apns message
4. didReceiveRemoteNotification in AppDelegate fires but it doesn't propagate into plugin function.

**Expected behavior**
FlutterPluginAppLifeCycleDelegate has `didReceiveRemoteNotification` function to implement but overriding the function cause this error.

```
Objective-C method 'application:didReceiveRemoteNotification:fetchCompletionHandler:' provided by method 'application(_:didReceiveRemoteNotification:fetchCompletionHandler:)' conflicts with optional requirement method 'application(_:didReceiveRemoteNotification:fetchCompletionHandler:)' in protocol 'FlutterApplicationLifeCycleDelegate'

Add '@nonobjc' to silence this error
```

Here is the final function structure: 
```
@nonobjc public override func application(
    _ application: UIApplication,
    didReceiveRemoteNotification userInfo: [AnyHashable : Any],
    fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void
  ) {
    // Not fired!!!
  }
```

Adding @nonobjc, I think it suppress to override the function, so it will not be exposed.

It works perfectly when overriding the same function in AppDelegate extending FlutterAppDelegate

```
  override func application(
    _ application: UIApplication,
    didReceiveRemoteNotification userInfo: [AnyHashable : Any],
    fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void
  ) {
    // I can see the function is fired correctly
    // Do something
    // call super function to fire didReceiveRemoteNotification in plugin -> But failed!!
    super.application(application, didReceiveRemoteNotification: userInfo, fetchCompletionHandler: completionHandler)
  }
```

**Additional context**
I think declaration or didReceiveRemoteNotification is not the same as the one Apple provided. I didn't investigate the exact problem but the situation only.

**Comment by sglim** [comment]
Here is the result of `fluttter docter`.

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale ko-KR)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
