### ISSUE TITLE
[firebase_crashlytics] web support

### ISSUE THREAD

**Issue by chen-yumin** [FirebaseExtended/flutterfire#1693]
Web support for Firebase Crashlytics is currently missing. As Flutter for web is more mature, we should add web support for `firebase_crashlytics`. This would be useful especially for logging Exceptions and Errors within the web app.

----

Currently, on web, `Crashlytics#onError` method has no implementation.

```
Error: MissingPluginException(No implementation found for method Crashlytics#onError on channel plugins.flutter.io/firebase_crashlytics)
```

**Comment by bean5** [comment]
I think I read on another issue that Dart supports Crashlytics from within, so there isn't a big need to use Crashlytics outside of the main flutter app.

So I think this can be closed.

**Comment by Ehesp** [comment]
Hello. Crashlytics only currently supports Android, iOS and Unity therefore we can't bridge web support as no underlying SDK exists.

I'd advise adding an upvote [here](https://github.com/firebase/firebase-js-sdk/issues/710) and submitting a [feature request](https://firebase.google.com/support/troubleshooter/report/features).

Closing this as it isn't actionable.
