### ISSUE TITLE
[firebase_storage] whereIn clause is not working in Android Studio on Windows but visible and properly working on IntelliJ on MAC. Please resolve this Issue

### ISSUE THREAD

**Issue by imhassanjaved** [FirebaseExtended/flutterfire#1696]
![IssuewhereIn](https://user-images.githubusercontent.com/48206945/71323329-b1641300-24f3-11ea-905a-d389e3858a34.PNG)
Firebase_Storage whereIn clause is not working in AndroidStudio on Windows but visible and properly working on IntelliJ on MAC. Please resolve this Issue

**Comment by iapicca** [comment]
Hi @imhassanjaved 
can you please provide your `flutter doctor -v` 
Thank you

**Comment by imhassanjaved** [comment]
Hi Dear,

Thanks for contacting me back. Below you will find my flutter doctor -v.

flutter doctor -v
[√] Flutter (Channel master, v1.13.3-pre.85, on Microsoft Windows [Version
10.0.17763.107], locale en-PK)
    • Flutter version 1.13.3-pre.85 at C:\Flutter\flutter
    • Framework revision bd25f70c66 (5 days ago), 2019-12-19 09:45:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[√] Android toolchain - develop for Android devices (Android SDK version
29.0.2)
    • Android SDK at C:\Users\XYZ\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b03)
    • All Android licenses accepted.
[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b03)
[!] Connected device
    ! No devices available
! Doctor found issues in 1 category.

**Comment by japborst** [comment]
Likely you need to upgrade your version of `cloud_firestore` in `pubspec.yaml`, `wherein` is only supported from `0.12.11`

**Comment by iapicca** [comment]
Hi @imhassanjaved 
did @japborst solution work for you?
thank you both

**Comment by imhassanjaved** [comment]
Hi FirebaseExtended/flutterfire.

Thanks for asking. Yes, It resolves my problem.

**Comment by iapicca** [comment]
Hi @imhassanjaved 
I'm glad to hear that 
thank you for your response
