### ISSUE TITLE
There are conflicts between plug-ins

### ISSUE THREAD

**Issue by yousaywhat** [FirebaseExtended/flutterfire#1699]
I used FCM plug-in and barcode_scan plug-in in the project. When the two plug-ins were used together, the application initialization would report an error, but the Token would be received normally. When I tried to send notifications to the application, the application crashed

**Comment by yousaywhat** [comment]
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): java.lang.IllegalStateException: registrar.activity() must not be null
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at com.apptreesoftware.barcodescan.BarcodeScanPlugin.registerWith(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at com.startiasoft.flutter_kotlin_demo.Application.registerWith(Application.kt:17)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:177)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at android.app.ActivityThread.main(ActivityThread.java:7470)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#plugins.flutter.io/firebase_messaging(12492): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/flutter (12492): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#initialized on channel plugins.flutter.io/firebase_messaging_background)
E/flutter (12492): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (12492): <asynchronous suspension>
E/flutter (12492): #1      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:50:21)
E/flutter (12492): #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter (12492): #3      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:23:32)
E/flutter (12492): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (12492): #5      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (12492): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12492): #7      _runZoned (dart:async/zone.dart:1516:10)
E/flutter (12492): #8      runZoned (dart:async/zone.dart:1500:12)
E/flutter (12492): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (12492): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (12492): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (12492): 
E/flutter (12492): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, registrar.activity() must not be null, null)
E/flutter (12492): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (12492): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (12492): <asynchronous suspension>
E/flutter (12492): #2      FirebaseMessaging.configure (package:firebase_messaging/firebase_messaging.dart:130:16)
E/flutter (12492): #3      _MyHomePageState.initState (package:flutter_kotlin_demo/main.dart:79:24)
E/flutter (12492): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4085:58)
E/flutter (12492): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
E/flutter (12492): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (12492): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
E/flutter (12492): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (12492): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
E/flutter (12492): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
E/flutter (12492): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (12492): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (12492): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
E/flutter (12492): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (12492): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
E/flutter (12492): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
E/flutter (12492): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
E/flutter (12492): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (12492): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
E/flutter (12492): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
E/flutter (12492): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (12492): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
E/flutter (12492): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
E/flutter (12492): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
E/flutter (12492): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
E/flutter (12492): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
E/flutter (12492): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
E/flutter (12492): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
E/flutter (12492): #45     Componen

**Comment by yousaywhat** [comment]
This problem is solved when I don't use the barcode_scan plugin, but I want my project to be able to use this plugin. What should I do

**Comment by iapicca** [comment]
Hi @yousaywhat 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by yousaywhat** [comment]
![image](https://user-images.githubusercontent.com/16442633/71385781-8200f380-2624-11ea-9562-ab83cef49641.png)

**Comment by yousaywhat** [comment]
![image](https://user-images.githubusercontent.com/16442633/71385836-c096ae00-2624-11ea-8c56-8ad82330415c.png)

**Comment by yousaywhat** [comment]
![image](https://user-images.githubusercontent.com/16442633/71385842-cdb39d00-2624-11ea-9666-bba9135594fc.png)

**Comment by yousaywhat** [comment]
I haven't used the flutter run --verbose command, so I don't quite understand where the error message is. You can try using these two plugins in the Demo and see the error message, right

**Comment by yousaywhat** [comment]
barcode_scan 1.0.0   and    firebase_messaging 6.0.9

**Comment by tharit-haup** [comment]
You might want to see this issue #1591

**Comment by helenaford** [comment]
Closing this, similar to https://github.com/FirebaseExtended/flutterfire/issues/1591.
