### ISSUE TITLE
[cloud_firestore] iOS build does not work due to a error in the Podfile.

### ISSUE THREAD

**Issue by iTiPo** [FirebaseExtended/flutterfire#1700]
**Describe the bug**
I added Cloud Firestore to my project and tried to build it for iOS. But this can not be done due to an error during build.

**To Reproduce**
1. Run `flutter run` or press Run in Android Studio.
2. I get the following error:

>     [!] Invalid `Podfile` file: no implicit conversion of nil into String.
> 
>      #  from my_project_path/ios/Podfile:38
>      #  -------------------------------------------
>      #  
>      >    copied_flutter_dir = File.join(__dir__, 'Flutter')
>      #    copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
>      #  -------------------------------------------

**Expected behavior**
The build completes successfully and the application starts.

**Additional context**
OS:
`macOS Mojave 10.14.6.`

Flutter and Dart:
```
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (12 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

pod --version:
`1.9.0.beta.2`

Dependencies:
```
firebase_core: ^0.4.0
cloud_firestore: 0.13.0+1
```

This error is reproduced in the same way for example project in the repository.

**Comment by iTiPo** [comment]
I replaced `__dir__` with `'.'` and now it works.

**Comment by iapicca** [comment]
Hi @iTiPo 
I'm glad that you solved the issue
thank you for letting me know
