### ISSUE TITLE
[firebase_ml_vision] Cloud text recognition does not return coordinates blocks, lines and elements 

### ISSUE THREAD

**Issue by ArtRog** [FirebaseExtended/flutterfire#1701]
When using the cloud text recognizer, the coordinates of the recognized text do not come. However, text detection works fine.

The problem does not appear when using text recognition on both platforms on the device.
See attached screenshots.

### **Steps to reproduce the behavior:**

1. Use FirebaseVision.instance.cloudTextRecognizer()
2. Progress image File
3. Look at coordinates

Supporting Code:
 ```
 final FirebaseVisionImage visionImage =
        FirebaseVisionImage.fromFile(imageFile);
    final TextRecognizer textRecognizer =
        FirebaseVision.instance.cloudTextRecognizer();
    VisionText visionText;
    textRecognizer.processImage(visionImage).then((vText) {
      if (visionText != null && visionText.blocks.isNotEmpty)
        visionText.blocks.forEach((block) {
          block.lines.forEach((line) {
            line.elements.forEach((element) {
              print(element);
            });
          });
        });
    });
```

**Additional context**
Original Image:
![z-OwjuNohYQ](https://user-images.githubusercontent.com/53770569/71350006-5d077480-2581-11ea-8db5-b54f76a387c0.jpg)

The result in the debugger if you use FirebaseVision.instance.textRecognizer():
![QIP Shot - Screen 003](https://user-images.githubusercontent.com/53770569/71350145-b40d4980-2581-11ea-82cb-eedd41d61718.png)

The result in the debugger if you use FirebaseVision.instance.cloudTextRecognizer():
![QIP Shot - Screen 002](https://user-images.githubusercontent.com/53770569/71350229-eae35f80-2581-11ea-952e-cf37e770cee0.png)

As you can see in the photo, if you use cloudTextRecognizer (), then the text is recognized, but the empty result of the cornerPoints field for both platforms is returned

### **Logs**
```
λ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\Android\flutter_sdk\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Arro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Redmi Note 4 • 192.168.100.15:5555 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

pubspec.yaml
`firebase_ml_vision: ^0.9.3+5`

**Comment by Salakar** [comment]
Given the age of this issue and it's inactivity I'm going to go ahead and close it in favour of trying the latest versions of ML Vision which ships with newer on device models. Thanks

**Comment by Smux1demo** [comment]
Hi Salakar, 

I've stumbled across the exact same issue (I'm using the newest plugin version: firebase_ml_vision 0.12.0+1).
I was wondering, did you manage to find a solution to this issue?
