### ISSUE TITLE
[FCM]Followed Instruction flutter_messaging but error

### ISSUE THREAD

**Issue by suhardiyan** [FirebaseExtended/flutterfire#171]
I just followed the instructions but always error

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Failed to capture fingerprint of input files for task ':app:checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[18.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
                                                                        
  Dependency failing: com.google.firebase:firebase-messaging:18.0.0 -> com.google.firebase:firebase-iid@[18.0.0], but fire
  base-iid version was 19.0.0.                                          
                                                                        
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.                                                 
  -- Project 'app' depends on project 'firebase_messaging' which depends onto com.google.firebase:firebase-messaging@18.0.
  0                                                                     
  -- Project 'app' depends on project 'firebase_core' which depends onto com.google.firebase:firebase-core@16.0.9
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.0
                                                                        
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.                                                     
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org  

`flutter version v1.9.1+hotfix.2`

**Comment by mackattack3k** [comment]
I had the same error but resolved it by adding in newer version of `firebase-messaging`.
Add the following to your `android/app/build.gradle`:
```
dependencies {
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
}

**Comment by suhardiyan** [comment]
just upgraded to 5.1.6 and everything is fine
