### ISSUE TITLE
[cloud_firestore] Distinguish "no data" from "not connected" states

### ISSUE THREAD

**Issue by HaoCherHong** [FirebaseExtended/flutterfire#1710]
When creating views using StreamBuilder connected to a Firestore stream of QuerySnapshot, it seems there is no way to distinguish is it really has no data or it just connecting or waiting for data.

For example, if there is actually no data for a query, the stream would be in 'waiting' state. And if there are some data but it's just not arrived yet, the stream would also be in 'waiting' state.
Therefore you cannot determine wether to show a connecting indicator or an empty placeholder in the UI.

Am I using it wrong?

**Comment by ibobo** [comment]
This happens to me also, and, IMHO, this is more a bug than an enhancement.

I need to be able to tell users that the query he performed contained zero rows

**Comment by Ehesp** [comment]
Hey @HaoCherHong @ibobo could you show some code usage of what exactly you're doing?

**Comment by Ehesp** [comment]
It looks as though the API is missing an `empty` property on the QuerySnapshot class.

**Comment by Ehesp** [comment]
You can achieve this by watching for the `ConnectionState` of the returned snapshot. If the state is active and `documents.isEmpty`, there is no documents returned from the result.
