### ISSUE TITLE
[firebase_crashlytics] version solving failed.

### ISSUE THREAD

**Issue by klaszlo8207** [FirebaseExtended/flutterfire#1712]
firebase_crashlytics >=0.1.2 which requires Flutter SDK version >=1.9.1+hotfix.5 <2.0.0, version solving failed.

after Packages get

**Comment by iapicca** [comment]
Hi @klaszlo8207 
please consider upgrading `firebase_crashlytics` to  `0.1.2+4`
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by TahaTesser** [comment]
Hi @klaszlo8207 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
