### ISSUE TITLE
only on few devices - flutter: Unauthenticated#0 HttpsCallable.call

### ISSUE THREAD

**Issue by rahulkumar26** [FirebaseExtended/flutterfire#1713]
Android is all working fine. however, not sure what's causing this issue on few IOS devices (FYI - some IOS devices working fine). Any help would be appreciated.

## Quick note
Firebase functions using Node 8 engine

## onCall script from app
ces2020/stores/login/loginStore.dart
await callable.call(<String, dynamic>{'email': '${email}'}); : line 40
```
Future<bool> validateUserEmail(String email, BuildContext context, Function completion) async{
    Dialogs.showLoadingDialog(context, _keyLoader);
    loading = true;
    try {
      final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
        functionName: 'getUserByEmailOnCall',
      );
      final HttpsCallableResult resp =
      await callable.call(<String, dynamic>{'email': '${email}'});
      Map<String, dynamic> data = jsonDecode(resp.data);

      loginResponse = LoginResult.fromMap(data);
      loading = false;
      Navigator.of(_keyLoader.currentContext, rootNavigator: true).pop();
      if (loginResponse.result.data.isEmpty) {
        success = false;
        errorStore.errorMessage = loginResponse.result.message;
        errorStore.showError = true;
        Dialogs.showPopUp(context, "User Not Found, please Register to login.");
        return false;
      } else {
        print("user validated successfully");
        final _appStateStore = Provider.of<AppStateStore>(
            context, listen: false);
        _appStateStore.userEmaiID = email;
        completion();
        return true;
      }
    }
    on CloudFunctionsException catch (e, s) {
      loading = false;
      success = false;
      Navigator.of(_keyLoader.currentContext, rootNavigator: true).pop();
      print(e.message + s.toString());
      errorStore.errorMessage = "Registration failed with error";
      Dialogs.showPopUp(context,"Server unreachable.");
    }
  }
```

**Target Platform:** Iphone
**Target OS version/browser:** 10 >
**Devices:** 11

## error

```
flutter: Unauthenticated#0      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:48:9)
<asynchronous suspension>
#1      _LoginStore.validateUserEmail (package:ces2020/stores/login/loginStore.dart:40:22)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      _LoginStore.validateUserEmail (package:ces2020/stores/login/loginStore.dart:32:33)
#4      _LoginPage._signInButtonTapped (package:ces2020/ui/login/userLogin.dart:194:19)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#22     _rootRunUnary (dart:async/zone.dart:1138:13)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#25     _invoke1 (dart:ui/hooks.dart:273:10)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

**Comment by iapicca** [comment]
Hi @rahulkumar26 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by rahulkumar26** [comment]
## flutter doctor -v

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at /Users/rahkumar3/work/mobile/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rahkumar3/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Toronto - iPhone X (1190235) • 513b77e9652ae5cc3f529cfda4fe490222c97c22 • ios • iOS 13.3

• No issues found!

##flutter run --verbose
too many characters, sharing through link - https://1drv.ms/t/s!ArGtfdGSfkbLhKMdf51lWlF14A7Dig?e=6SxBg9

**Comment by rahulkumar26** [comment]
@iapicca hope you are able to see the logs :)

**Comment by iapicca** [comment]
Hi @rahulkumar26 
your logs are visible 
thanks

**Comment by Ehesp** [comment]
Hello - please update your Firebase CLI version, as per the docs:

>  New HTTP and HTTP callable functions deployed with any Firebase CLI lower than version 7.7.0 are private by default and throw HTTP 403 errors when invoked. Either explicitly make these functions public, or update your Firebase CLI before you deploy any new functions.

**Comment by Salakar** [comment]
Closing in favour of trying the latest release, this has since been reworked.
