### ISSUE TITLE
[firebase_auth] Authentication State Persistence

### ISSUE THREAD

**Issue by saisantosh2095** [FirebaseExtended/flutterfire#1714]
How to implement Auth state persistence on flutter web using firebase_auth package. Like (LOCAL,SESSION AND NONE)

Previously using [firebase](https://pub.dev/packages/firebase) package was able to implement this feature ---

```dart
_firebaseAuth.setPersistence(Persistence.LOCAL).then((_) {
     //Perform user authentication here
    }).catchError((error) {
      print(error);
    });
```

But now i am unable to find this option in firebase_auth package after the support for web has been enabled.

**Comment by JSANL** [comment]
We are currently running our first beta of our flutter web app.  
Our app is used mostly in schools and with the addition of the web not only on smartphones but also on shared computers.
   
This leaves wishing for a better way to handle auth state persistence like described in the [web auth documentation](https://firebase.google.com/docs/auth/web/auth-state-persistence).

**Comment by rjreid** [comment]
I'm also developing a flutter web app, and also need to be able to set the persistance.

In my case it appears that the default (which is "local" according to this https://firebase.google.com/docs/auth/web/auth-state-persistence) IS indeed what is occurring.

But while that may make sense for android/ios apps, where it will normally be a device owner exiting/restarting an app, it makes less sense for web apps which are more likely to be used on devices which other people may use. It is arguably a dangerous default setting as it exposes users data unless they explicitly log out.

So I would like to see the .setPersistence method added to the firebase_auth package and/or a way to change the setting at the console level (perhaps via a security rule?) as my app will be primarily web-accessed.

**Comment by fearlessambassador** [comment]
Has this been recognized as a gap at this point? Is there a work-around? :)

**Comment by AndroidNils** [comment]
Any updates?

**Comment by Chriszat** [comment]
Any updates?

**Comment by dumbasPL** [comment]
Any updates?

**Comment by cad0p** [comment]
Same here, after a reload auth.currentUser() becomes null..

**Comment by Kuhno92** [comment]
there is a workaround here: https://github.com/FirebaseExtended/flutterfire/issues/1918

**Comment by cad0p** [comment]
Yeah, actually my implementation now has a timeout as well so it doesn't wait forever if something fails

`
          user = await _auth.onAuthStateChanged.timeout(
		    Duration(seconds: 1),
		    onTimeout: (eventSink) => eventSink.close()
	    )
		  .firstWhere(
			  (u) => u != null, orElse: () => null
	  );
`

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this feature is still missing for you? If it is then please submit a new up to date GitHub issue explaining what's missing on the updated plugins.

See https://firebase.flutter.dev/docs/auth/usage#persisting-authentication-state

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
