### ISSUE TITLE
[cloud_firestore] add limitToLast

### ISSUE THREAD

**Issue by tibbiyelininja** [FirebaseExtended/flutterfire#1717]
Javascript SDK has limitToLast function. Please add it.

**Comment by awhitford** [comment]
Apparently, this would be helpful to solve [pagination to the _previous page_](https://stackoverflow.com/questions/54074135/how-to-paginate-to-previous-page-using-angularfire-firestore-and-firebase).

**Comment by Ehesp** [comment]
Hello, `limitToLast` is a Realtime Database feature which is supported: https://pub.dev/documentation/firebase_database/latest/firebase_database/Query/limitToLast.html

You may be looking for the `endAt` Query methods which are available in Firestore already. Thanks.
