### ISSUE TITLE
[cloud_firestore]  Plugin adds about 150M to iOS flutter app

### ISSUE THREAD

**Issue by tapizquent** [FirebaseExtended/flutterfire#1718]
**Describe the bug**
When building my app, I noticed there was a huge difference in size between IPA (100M+) and APK (17M) files for the flutter build on release mode.

To try and identify if it was a plugins' issue, I created a new project and started adding plugins one by one and measuring the size after adding each plugin.

I noticed that when I added `cloud_firestore`, the size of the IPA jumped from:

`-rw-r--r--  1 tapizquent  staff   9.7M Dec 25 16:20 build/app.ipa`

to:

`-rw-r--r--  1 tapizquent  staff   159M Dec 25 16:33 build/app.ipa`

As can be seen, that is an 150M increase in size by just adding `cloud_firestore` to my `pubspec.yaml`

**To Reproduce**
1. Generate a new flutter project
2. Measure its IPA size using steps recommended here: https://flutter.dev/docs/perf/app-size or simply run
`flutter build ios && tar -zcf build/app.ipa build/ios/iphoneos/Runner.app && ls -lh build/app.ipa`
and observe the output.
3. Add `could_firestore` to `pubspec.yaml`
4. Re-run `flutter build ios && tar -zcf build/app.ipa build/ios/iphoneos/Runner.app && ls -lh build/app.ipa`

**Expected behavior**
App size should NOT increase by 150M when adding a plugin... This behavior could cause rejections on Apple Store and drastically impacts user experience as no one wants a simple app with huge size on their phone

**Additional context**
I began with a clean, new project and noticed the huge change only when `cloud_firestore` was added.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/47101

**Comment by larssn** [comment]
By the looks from the thread you linked, this is not a regression, but a consequence of bitcode in the build, which is later stripped by xcode: https://github.com/flutter/flutter/issues/47101#issuecomment-567522077

**Comment by collinjackson** [comment]
It sounds like this covered by flutter/flutter#47101
