### ISSUE TITLE
[firebase_messaging] use _firebaseMessaging.configure in two different places in one application?

### ISSUE THREAD

**Issue by DenisMrGnusa** [FirebaseExtended/flutterfire#1719]
I installed _firebaseMessaging.configure in two different places in one application. the first in the root home class, and the second in the chat class. here's my code:

**home.dart**
```
....
HomeBodyState({Key key});

@override
  void initState() {
    super.initState();
    _firebaseMessaging.configure(...);
}
....
```

**and chat.dart**

```
....
class ChatBuilderState extends State<ChatBuilder> with AfterLayoutMixin<ChatBuilder> { 

@override
  void initState() {
    super.initState();
    _firebaseMessaging.configure(...);
  }
....
```

the condition is when I receive a message from the cloud, what works is only the configuration in home.dart, while in chat.dart nothing happens. why did it happen?, is there anyone who can help to answer?

**thank you,
Best Regards,**

**Comment by mariogorki94** [comment]
abstract your code to configure the firebase messaging only once and attach listeners to your pages where you need them. Make an Inherited Widget above the Widget Tree and initialize firebase there and create stream for the notifications. In the pages where you need to listen for notifications get the inherited widget and listen for the stream there.

**Comment by iapicca** [comment]
Hi @DenisMrGnusa 
does @mariogorki94 proposed solution solves your issue?
thank you

**Comment by Ehesp** [comment]
As @mariogorki94 pointed out, this is by design. Your code should be setup to use handle the events from a single point of truth.

Will close, but this generally will be documented.
