### ISSUE TITLE
[firebase_messaging] Notification Sound is not working on IOS

### ISSUE THREAD

**Issue by majdkz97** [FirebaseExtended/flutterfire#1721]
**Describe the bug**
When I send Notification on android the sound is working but on iOS Sound not Working

 
**Expected behavior**
Sound When there is a notification

**Additional context**
my flutter doctor log is:
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.6-pre.22, on Mac OS X 10.15.2 19C57, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!
```

My Code is:
```dart
 _firebaseMessaging.configure();
    _firebaseMessaging.requestNotificationPermissions(
      const IosNotificationSettings(sound: true, badge: true, alert: true),
    );

My Firebase code:
[
			'notification'	=> [
				'title'	=> $title,
				'body' 	=> $body,
				'icon' => $icon,
				'click_action'=>'https://MyWebSite.com/v8/',
				'sound'=>'default',

			],
			'data' => ['title'=> $title, 'body'=>$body, 'otherData'=>$otherData]
];



```

**Comment by DaYuClo** [comment]
You are missing the APNS (Apple Push Notification Service) object in your cloud code.

`    let message = {
        notification: {
            title: 'My title',
            body: myMessage,
        },
		apns: {
			payload: {
				aps: {
					sound: 'default',
				}
			}
		},
    };`

**Comment by iapicca** [comment]
Hi @majdkz97 
did @DaYuClo  solution fixed the issue?
thank you

**Comment by TahaTesser** [comment]
Hi @majdkz97 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by greenblue467** [comment]
Does anyone solve this issue?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by mzl1988** [comment]
![image](https://user-images.githubusercontent.com/11645762/84230922-a04da380-ab1f-11ea-9bf6-cb79766fcc10.png)
not work
