### ISSUE TITLE
[firebase_messaging] FCM dashboard doesn't show received notifications count

### ISSUE THREAD

**Issue by lesnitsky** [FirebaseExtended/flutterfire#1724]
Notifications are working properly, but FCM dashboard doesn't show received notifications count

![image](https://user-images.githubusercontent.com/6261302/71544592-7ef26400-2992-11ea-8d27-8f702c2b1fce.png)

**Comment by iapicca** [comment]
Hi @lesnitsky 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by lesnitsky** [comment]
this issue is valid for the whole time app has been released, so `flutter doctor -v` will be useless (issue is valid on all version of flutter released in 2019)
Minimal code sample could be found in firebase_messaging readme. I'm not doing anything extravagant, just sending notifications to FCM from server

example payload:

```
{
  "priority": "high",
  "data": {
    "click_action": "FLUTTER_NOTIFICATION_CLICK",
    "feedId": "<feed-id>
  },
  "to": "<device token>",
  "notification": {
      "body": "Message",
      "title": "Chat title",
      "sound": "default",
      "badge": 3
  },
}
```

**Comment by Salakar** [comment]
Hey 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. Specifically we've updated to the latest Firebase SDKs which should resolve any underlying issues. Firebase Analytics is also a requirement for these to work.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks.
