### ISSUE TITLE
[firebase_auth][google_sign_in] PlatformException with microG

### ISSUE THREAD

**Issue by tapeo** [FirebaseExtended/flutterfire#1726]
After a 'Login with Google' on a device with microG 0.2.10.19420` _auth.signInWithCredential()`throws this exception:

```
12-27 18:25:41.161 14233 14233 W AuthSignInClient: Could not launch sign in Intent. Google Play Service is probably being updated...
12-27 18:25:41.169 14233 14262 I flutter : PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 17: , null)
```

On other devices with standard Play Services the user can login correctly.
I am not sure if is an issue with `firebase_auth` or `google_sign_in`.

**Comment by iapicca** [comment]
Hi @tapeo 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by emailsubjekt** [comment]
> After a 'Login with Google' on a device with microG 0.2.10.19420` _auth.signInWithCredential()`throws this exception:
> 
> ```
> 12-27 18:25:41.161 14233 14233 W AuthSignInClient: Could not launch sign in Intent. Google Play Service is probably being updated...
> 12-27 18:25:41.169 14233 14262 I flutter : PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 17: , null)
> ```
> 
> On other devices with standard Play Services the user can login correctly.
> I am not sure if is an issue with `firebase_auth` or `google_sign_in`.

Dude, are you stupid, he asked you for flutter doctor -v and flutter run --verbose. Please provide that so that the problem can be fixed. What is wrong with you!!!!! It's been 4 days!!!!!

**Comment by tapeo** [comment]
Are you crazy? in this period of holidays I have not had the opportunity to do that besides being a secondary project. I'm going to ignore that.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
