### ISSUE TITLE
[firebase_messaging] Android not receives notification (only title and body) when app Force stopped 

### ISSUE THREAD

**Issue by MrVanosh** [FirebaseExtended/flutterfire#1732]
**Describe the bug**
Android phones not receives notification sent by token or topic (curl or fcm site) when app is Force stopped which some phones do when app is closed so not all receive the notification.
Payload I use to send notification: 
`{"notification": {"body": "this is a body","title": "this is a title"}, "to": "<TOKEN>"}`
or
`{"notification": {"body": "this is a body","title": "this is a title"}, "priority": "high", "to": "<TOKEN>"}
`or
`{ notification: {title: 'sth', body: sth'}, android: {notification: {sound: "default" }},apns: {payload: {aps: {sound: "default"  }  } }, topic: 'sometopic' }`
or generated on firebase site and send.

**To Reproduce**
1. Use newest firebase_messaging (in older versions not works also)
2. Set up fcm
3. Run app force stop it from Settings and try to send notification

**Expected behavior**
Receive notification when app is Force stopped (Terminated) as flutter fcm documentation says: 
```bash
App Terminated:
Notification is delivered to system tray. When the user clicks on it to open app onLaunch fires if click_action: FLUTTER_NOTIFICATION_CLICK is set (see below)
```
 but there is no notification on system tray when app terminated :(

**Additional context**
My code for FCM:

```dart
import 'dart:io';
import 'package:firebase_messaging/firebase_messaging.dart';

class FirebaseNotifications {
  FirebaseMessaging _firebaseMessaging;

  void setUpFirebase() {
    _firebaseMessaging = FirebaseMessaging();
    firebaseCloudMessaging_Listeners();
  }

  void firebaseCloudMessaging_Listeners() {
    if (Platform.isIOS) iOS_Permission();

    _firebaseMessaging.getToken().then((token) {
      print(token);
    });

    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print('on message $message');
      },
      onResume: (Map<String, dynamic> message) async {
        print('on resume $message');
      },
      onLaunch: (Map<String, dynamic> message) async {
        print('on launch $message');
      },
    );
  }

  void iOS_Permission() {
    _firebaseMessaging.requestNotificationPermissions(
        IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });
  }
}

```

**Comment by iapicca** [comment]
Hi @MrVanosh 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by MrVanosh** [comment]
Of course, there it is
flutter doctor -v
`[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15 19A536g, locale pl-PL)
    • Flutter version 1.12.13+hotfix.6 at /Users/mrvanosh/Downloads/flutter
    • Framework revision 18cd7a3601 (3 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mrvanosh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Users/mrvanosh/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
`
I test it on emulator but also on real androids when app force stopped it won't receive any notifications.
flutter run --verbose in file
[runverbose.log](https://github.com/FirebaseExtended/flutterfire/files/4012548/runverbose.log)

**Comment by a-chris** [comment]
I have the same problem: I won't receive notifications while the app has been closed/terminated/killed.

**Comment by Dreamersoul** [comment]
i'm having the same issue when sending to a specific topic! in iOS i only receive the notification in onMessage even though im sending notification payload without data

**Comment by MrVanosh** [comment]
> i'm having the same issue when sending to a specific topic! in iOS i only receive the notification in onMessage even though im sending notification payload without data

Yes, now my app uses topics and I have same issue.

**Comment by isaiahtaylor** [comment]
What is the status on this? I don't see notifications in the system tray when my android app is force stopped.

**Comment by harshselani** [comment]
Facing the same issue. How are we supposed to use this plugin and Flutter, if basic notification functionality doesn't work? It just stopped working recently

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
