### ISSUE TITLE
[firebase_admob] How to hide the ad when the current scaffold contains a bottomNavigationBar

### ISSUE THREAD

**Issue by Legolaszstudio** [FirebaseExtended/flutterfire#1742]
**Describe the bug**
The ad is showing on top of my bottomNavigationBar so the application is unusable.
![](https://kepkuldes.com/images/9dae73a480ce937799e23fbbc2cc6210.jpg)

**To Reproduce**
1. Use firebase AdMob create a banner ad 
2. 'Show ad like this:
```
BannerAd smartSizeBanner = BannerAd(
  adUnitId: config.bannerUnitId,
  size: AdSize.smartBanner,
  listener: (MobileAdEvent event) {
    print("BannerAd event is $event");
    FirebaseAnalytics().logEvent(name: event.toString());
  },
);
smartSizeBanner.load();
smartSizeBanner.show(
   anchorType: AnchorType.bottom
);
```
4. Use a scaffold to show a bottomNavigationBar:
```
Widget build(BuildContext context) {
  return Scaffold(
    ...
    bottomNavigationBar: BottomNavigationBar(...),
    ...
  );
}
```
**Expected behavior**
Maybe hide the ad when the current scaffold contains a bottomNavigationBar, or move the ad above the bottomNavigationBar

**Comment by orestesgaolin** [comment]
The show method has `anchorOffset` parameter that you can use in this case

```
    banner.show(
              anchorOffset: 60.0,
              anchorType: AnchorType.bottom,
              horizontalCenterOffset: 0.0,
            );
```

**Comment by Legolaszstudio** [comment]
Thanks, it works perfectly
