### ISSUE TITLE
[Dynamic Links] Deeplink always null because FirebaseApp.configure() is are never call?

### ISSUE THREAD

**Issue by achubutkin** [FirebaseExtended/flutterfire#1752]
**Describe the bug**
I follow the installation and configuration instructions for the Flutterfire plugin from [https://firebaseopensource.com/projects/firebaseextended/flutterfire/packages/firebase_dynamic_links/readme.md/](https://firebaseopensource.com/projects/firebaseextended/flutterfire/packages/firebase_dynamic_links/readme.md/). But, deeplink is null.

    final Uri deepLink = data?.link; /* here link is always null */

If you add a call, then a deeplink will be received.

    FirebaseApp.configure() /* for Swift. For ObjectiveC call [FIRApp configure]; */

That instruction does not describe any additional steps, such as these, for example [https://firebase.google.com/docs/dynamic-links/ios/receive](https://firebase.google.com/docs/dynamic-links/ios/receive) (steps 4, 5). But at the same time, the plugin automatically performs steps 6, 7.

It may be to add Firebase initialization to the Flutterfire plugin, or add the need to call initialization to get a deeplink in the Flutterfire documentation?

**Comment by anthonyym** [comment]
Appears from the [readme](https://pub.dev/packages/firebase_dynamic_links) that there's two parts two parts to handling the link. `onLink` for when app is in background, so I would think `getInitialLink()` would be for when the app was not running in background. So if your app was opened when running in background then dynamiclink.link would have the link and data.link would be null.

> To receive a dynamic link, call the getInitialLink() method from FirebaseDynamicLinks which gets the link that opened the app (or null if it was not opened via a dynamic link) and configure listeners for link callbacks when the application is active or in background calling onLink.

**Comment by achubutkin** [comment]
No, the application is installed and launched for the first time.

**Comment by iapicca** [comment]
Hi @achubutkin 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by achubutkin** [comment]
Hi @iapicca yes, of course (FirebaseApp.configure() added in AppDelegate.swift)
[output.log](https://github.com/FirebaseExtended/flutterfire/files/4018654/output.log)

`flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-KZ)
    • Flutter version 1.12.13+hotfix.5 at /Users/default/downloads/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone X • 96C1CBFD-70F2-4697-921E-19FDE0F62B9D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 3 categories.
```


`flutter run --verbose`
Please, see attachment file

**Comment by geek2driod** [comment]
Hi, I am facing the same issue, adding this **FirebaseApp.configure()**  in AppDelegate is not working  for me. @achubutkin can you help me to resolve this issue? I will be very thankful to you

**Comment by Salakar** [comment]
This should no longer be an issue in the latest FF, Firebase Core is automatically initialized on native sdks before you call initialize in Dart.

Updated documentation: https://firebase.flutter.dev/docs/installation/ios
