### ISSUE TITLE
[Cloud Firestore] Rules request.auth.token.firebase.identities["phone"] not update on Ios

### ISSUE THREAD

**Issue by ClassSadStranger** [FirebaseExtended/flutterfire#1762]
**Describe the bug**
I using `request.auth.token.firebase.identities["phone"] != null` to make sure number is verified.Android are works fine (immediately update) but on IOS after user verified their phone number I need to wait like half hour for update.

**To Reproduce**
1. Put `request.auth.token.firebase.identities["phone"] != null` in rules
2. Do verify phone number on IOS

**Expected behavior (Android is work as I expected)**
I expected that once the phone verified i can immediate using `request.auth.token.firebase.identities["phone"] != null` to make sure phone is verified.

**Additional context**
I don't know which part when wrong it's bug or it's api difference between two platform.
Other like ` request.auth.token.firebase.identities["facebook.com"]` or ` request.auth.token.firebase.identities["google.com"]` all work fine.
only `request.auth.token.firebase.identities["phone"]` didn't work on IOS.

**Comment by ClassSadStranger** [comment]
Currently fix by call FirebaseUser firebaseUser = await _firebaseAuth.currentUser(); await firebaseUser.getIdToken(refresh: true);to make token update after phone verified and app started.But i still don't know why this only happen on ios.

**Comment by iapicca** [comment]
Hi @ClassSadStranger 
I'm glad that you found a workaround
I'm closing the issue for now;
if the problem will occur again,
please write in the comments and I'll reopen the issue
thank you
