### ISSUE TITLE
[firebase_messaging] Upgrading from 5.1.4 -> 6.0.9 causes build failure in old iPhone device (32bit, ARMv7 architecture).

### ISSUE THREAD

**Issue by cielo** [FirebaseExtended/flutterfire#1764]
**Describe the bug**
Hi,

When I upgrade 'firebase_messaging' from 5.1.4 to 6.0.9, the flutter project does not build successfully anymore for iPhone 5c, running in 10.3.3. iPhone 5c has (32bit, ARMv7 underlying architecture). The project builds fine in iPhone X running in iOS 13 with 64bit, ARMv8-A. 

Below is the 2 lines of build failure messages that are relevant.

```
Non-fat binary /Users/user/Library/Developer/Xcode/DerivedData/Runner-heeizlbsvjnmhfdbicwzezzvgbqu/Build/Products/Debug-iphoneos/Runner.app/Frameworks/grpcpp.framework/grpcpp is not armv7. Running lipo -info:
Non-fat file: /Users/user/Library/Developer/Xcode/DerivedData/Runner-heeizlbsvjnmhfdbicwzezzvgbqu/Build/Products/Debug-iphoneos/Runner.app/Frameworks/grpcpp.framework/grpcpp is architecture: arm64

```

The thing is that `firebase_messaging` **works totally fine** in this old iPhone 5c model if I use version `firebase_messaging` 5.1.4.

**To Reproduce**
- Add `firebase_messaging: ^6.0.9` to pubspec.yaml dependency file in any flutter project. 
- Attempt to run the project in iPhone 5c device.

**Expected behavior**
Build should be successful, and I should be able to build for iPhone 5c, which would have been possible if I used version 5.1.4.

**Additional context**

flutter doctor -v

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A546d, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/user/Dev/flutter-active/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone • 7fdb35be441429c092fad958bd96da882fc63322 • ios • iOS 10.3.3
```

**Comment by iapicca** [comment]
Hi @cielo 
could you please run
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated 
flutter doctor -v`, your `pubspec.yaml` 
and your `flutter build ios  --verbose`?
Thank you

related to https://github.com/FirebaseExtended/flutterfire/issues/1763

**Comment by cielo** [comment]
Hi,

Thanks for getting back to me. I followed through above steps but it would not solve the problem. I would still get the same error.

However, I decided to run the app this time through `flutter run` command, instead of using xcode's `Run` button. Surprisingly, the app built fine in my device.

The reason that I have been running debug release apps with xcode is because it always seems to start the app faster. For instance, with xcode, the first run takes 8~10 min, but all subsequent runs take less than 2 minutes.

On the other hand, `flutter run` always takes 8~10 minutes to run the app, regardless of whether or not the build has been completed previously. This can be very time consuming as I will have to run this when I disconnect the phone and re-connect.So I often avoid using `flutter run` to run the app in my device.

Anyhow, I can successfully run firebase_messaging 6.0.9 in iPhone 5c, if I use `flutter run`. I am not sure why I have been able to run 5.1.4 version with xcode without any issues.

By any chance, do you know if I have to update any ios config in order to make xcode run behave like `flutter run`?
