### ISSUE TITLE
Authentication works in development, but not in release.

### ISSUE THREAD

**Issue by sharath12345678** [FirebaseExtended/flutterfire#1765]
When i run the app in Emulator(debug / release mode), firebase_auth with google sign-in app works as intended and the user will be registered in firebase authentication.

However, after the release of app to playstore,  & running of app in actual android device, user registration (firebase_auth) do not works, (of course, google sign-in window pop-ups and after selecting the user account, pop-up closes & the app simply keeps on loading) and the app was stalled.

firebase_auth & google plug-ins are up-to date, 
no warning / errors found during run in debug /release mode in emulator,

Find [flutter run --verbose.txt](https://github.com/FirebaseExtended/flutterfire/files/4022962/flutter.run.--verbose.txt)

Find [flutter doctor -v.txt](https://github.com/FirebaseExtended/flutterfire/files/4022959/flutter.doctor.-v.txt)

**Comment by Isakdl** [comment]
Did you register the SHA certificate fingerprints hashes in the firebase console for your release keys?

https://console.firebase.google.com

project settings > general > android app > SHA certificate fingerprints

This list should contain at least 2 hashes one for the debug keys and one for the release keys.

**Comment by sharath12345678** [comment]
Hi, @Isakdl,
Thanks for the suggestion, it really helped.
