### ISSUE TITLE
 I can't authenticate

### ISSUE THREAD

**Issue by cristianpaulo4** [FirebaseExtended/flutterfire#1769]
> Durante o desenvolvimento funciona perfeitamente, mas após gerara o apk e instalar no dispositivo, não consegui autenticar o usuário.

During development works perfectly, but after generating the apk and installing on the device, I could not authenticate the user.

**Comment by iapicca** [comment]
Hi @cristianpaulo4 
can you please provide your  `flutter doctor -v`,
your `pubspec.yaml` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @cristianpaulo4 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
