### ISSUE TITLE
[firebase_messaging] hard to detect initial route when the app is opened from push

### ISSUE THREAD

**Issue by rostyslavroshak** [FirebaseExtended/flutterfire#177]
# Problem
Clicking on push usually opens some specific route, however current api makes it hard and not effective. Currently, I have to create app with initial route, when `onLaunch` is use navigator to perform navigation to a correct page.

# Solution
Ideal solution is to get the data before run off the app. So solution could be by extending api:
```dart
  final options = await _firebaseMessaging.launchOptions;
  if (options != null) {
    runApp(MyAwesomeApp.withInitialOptions(options));
  } else {
    runApp(MyAwesomeApp());
  }
```

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin. I'd recommend checking out the new APIs `getInitialMessage` and `onMessageOpenedApp` to help with this issue.

Thanks everyone 🤓
