### ISSUE TITLE
[firebase_messaging] How to bundle notifications?

### ISSUE THREAD

**Issue by esDotDev** [FirebaseExtended/flutterfire#1770]
I'd like to group notifications like Hangouts does, where multiple messages are grouped together in one notification but I can't figure out how. From what I've read, this is a client-side implementation detail.

Here's my example payload: 
```
var response = await http.post(
      'https://fcm.googleapis.com/fcm/send',
      headers: <String, String>{
        'Content-Type': 'application/json',
        'Authorization': 'key=$serverToken',
      },
      body: jsonEncode(
        <String, dynamic>{
          'collapse_key': 'chats',
          'notification': <String, dynamic>{
            'body': 'this is a body',
            'title': 'this is a title',
            'tag': 'tag'
          },
          'priority': 'high',
          'data': <String, dynamic>{
            'click_action': 'FLUTTER_NOTIFICATION_CLICK',
            'id': '1',
            'status': 'done'
          },
          'to': "/topics/all",
        },
      ),
    );
```

**Comment by esDotDev** [comment]
For reference, this is what I'm after: 
https://javapapers.com/android/android-bundled-notifications/

**Comment by p30arena** [comment]
@iapicca 
This is really needed in a messaging app, as WhatsApp does.

**Comment by TedRibeiro** [comment]
Reading the docs, my best guess is to link the plugin to Android project and then handle background messages:
![image](https://user-images.githubusercontent.com/17773037/83308142-8b4a4980-a1dc-11ea-81bd-5eda44199abf.png)

**Comment by Salakar** [comment]
A basic version of this would be to specify `threadId` for APNs and `collapseKey` for Android when sending your FCM messages from your backend service, for example with the Firebase Admin SDK for Node.js you'd do something like:

```js
await admin.messaging().send({
  token: 'YOUR_TOKEN_HERE',
  apns: {
    payload: {
      aps: {
        threadId: 'foo',
        alert: 'Hello world',
      },
    },
  },
  android: {
    collapseKey: 'foo',
    notification: {
      title: 'Hello world',
    },
  },
});
```

For the full style though on Android you need to create notifications using the Inbox Style notification style. For this I'd recommend sending data only messages through FCM and then using a local notifications plugin to build an Inbox Style notification from your FCM message data.
