### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs 

### ISSUE THREAD

**Issue by sunjianan9900** [FirebaseExtended/flutterfire#178]
Firebase_admob:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

**Comment by hansanker** [comment]
Hi, For for 2 projects I also have this issue (ITMS-90809: Deprecated API Usage). I think it is because of dependency within this project to a firebase version still using UIWebView.
I hope this will be updated soon

**Comment by iapicca** [comment]
Hi @sunjianan9900 
are you still experiencing this [issue ](https://github.com/flutter/flutter/issues/39470)with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you
