### ISSUE TITLE
Bug in onMessage, onLaunch and onResume

### ISSUE THREAD

**Issue by AndresC17** [FirebaseExtended/flutterfire#1781]
When i send the notification, these method run 2 times

**Comment by candyman15** [comment]
i have same issue. but configure method() call one time. onMessage, onResume call back 2 times, onLaunch is 1 times.

**Comment by rodrigolmacedo** [comment]
yes its a bug, im facing the same issue. 

#1669

**Comment by scognito** [comment]
I confirm (firebase messaging 6.0.9, and flutter 1.12.13+hotfix.5)
but it happens only on Android, not iOS.

**Comment by iapicca** [comment]
Hi @AndresC17 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1669) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
