### ISSUE TITLE
[<FIREBASE_Messaging>] <onLaunch, onMessage, onResume don't fire on real iOS Device with AppStore version>

### ISSUE THREAD

**Issue by mabdelatief** [FirebaseExtended/flutterfire#1787]
Hello, 
i've implemented Firebase_Messaging, it works perfectly on Android with everything firing as expected, 
also works perfectly on iOS Simulators, made me so confident to push the app on the store, however, after installing the app from the App Store on multiple ios devices, the onLaunch, onResume and onMessage, NONE of them work, while all of them work perfectly on Android version.

I do NOT have any other conflicting library the uses notifications .
i followed the readme carefully more than 3 times, all steps are done.
i Made sure that iOS receives notifications differently than Android, as i mentioned earlier, it works perfectly on the iOS Simulator.

**Comment by igoriuz** [comment]
Can you try the following? https://github.com/FirebaseExtended/flutterfire/issues/1757#issuecomment-570754059

**Comment by mabdelatief** [comment]
> Can you try the following? [#1757 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1757#issuecomment-570754059)

Working Perfectly,  
Thanks so Much !
