### ISSUE TITLE
[Cloud functions>] Unable to call function FUNCTION_NAME

### ISSUE THREAD

**Issue by blaster92** [FirebaseExtended/flutterfire#1788]
**Describe the bug**
Getting "Unable to call function FUNCTION_NAME" when running Flutter code on iOS device.

**Expected behavior**
The function returns the output of a cloud function routine.

**Comment by helenaford** [comment]
Closing this due to lack of clarification. If still experiencing the issue, please create a new one with steps on how to reproduce.
