### ISSUE TITLE
[<FIREBASE_MESSAGING>] <Do not show push notification on IOS when app is background or terminated>

### ISSUE THREAD

**Issue by bryanus1** [FirebaseExtended/flutterfire#1790]
**Describe the bug**
I have implemented FCM to flutter and everything works to android version but IOS version only works to foreground, in background or terminated don't show push notification for open app.

I followed all documentation steps but don't works

**Comment by iapicca** [comment]
Hi @bryanus1 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/1590)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
