### ISSUE TITLE
onLaunch spams new screens when navigator is used there

### ISSUE THREAD

**Issue by Feralnex** [FirebaseExtended/flutterfire#1792]
When pushing new screen through Navigator in onLaunch function it gets looped and never ends (on and on new screens).

**Comment by iapicca** [comment]
Hi @Feralnex 
can you please provide your `flutter doctor -v`,
your `flutter run --verbose` 
and  a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by Feralnex** [comment]
Hi @iapicca 
Sorry for waiting, the problem was that i configured FirebaseMessaging instance too late in app. That led to some unexpected behaviour ; )
