### ISSUE TITLE
[firebase_auth_web] Sign in with google doesn't work on Safari 13.0.4

### ISSUE THREAD

**Issue by thachnb85** [FirebaseExtended/flutterfire#1793]
**Describe the bug**
When signing in with google, got this error in javascript console:
```
The source list for Content Security Policy directive 'script-src' contains an invalid source:
'strict-dynamic'. It will be ignored.
T0 — js_primitives.dart:49
```
**To Reproduce**
Following example using google_sign_in
https://pub.dev/documentation/firebase_auth/latest/

After logged in using google account in the popup window, when returning to the website, the error above is thrown.

**Expected behavior**
    final FirebaseUser currentUser = await FirebaseAuth.instance.currentUser();
should return correct current user info using google sign in method.

**Additional context**
Chrome Version 79.0.3945.88 (Official Build) (64-bit) : working fine!
Firefox 71.0 (64-bit), working fine!
Safari Version 13.0.4 (14608.4.9.1.4), does not work.

**Comment by thachnb85** [comment]
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G1012,
    locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.32.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by thachnb85** [comment]
pubspec.yaml

```
  firebase_auth_web: 0.1.1+1
  firebase_core: ^0.4.0+8
  firebase_dynamic_links: ^0.3.0
  google_sign_in: 4.1.1
```

**Comment by shashwatadi** [comment]
Any luck with this? I have been getting this weird error on some of iOS devices.

![WhatsApp Image 2020-08-24 at 8 16 08 PM](https://user-images.githubusercontent.com/6792267/91062502-684bfc00-e64a-11ea-9244-4bbfd4a62cb1.jpeg)

User Screenshot ^

**Comment by Ehesp** [comment]
Hmm, this could be an issue with the Google Sign-In plugin rather than this library.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue. Though as @Ehesp pointed out this is could likely be an issue with the Google Sign-in plugin so I'd suggest raising an issue there if this still persists.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration

**Comment by shashwatadi** [comment]
Thanks, will check and update here!
