### ISSUE TITLE
Firebase Analytics different method names?

### ISSUE THREAD

**Issue by BugsBunnyBR** [FirebaseExtended/flutterfire#18]
https://github.com/flutter/flutter/issues/37600

**Comment by iapicca** [comment]
contents from https://github.com/flutter/flutter/issues/37600
> So,
> it looks like Android has `setSessionTimeoutDuration`
> https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setSessionTimeoutDuration(long)
> 
> and iOS has `setsessiontimeoutinterval`
> https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#+setsessiontimeoutinterval:
> 
> They seems to me to be the same action, but with different names in each platform?
> Firebase Analytics plugin current implementation only tracks the `setSessionTimeoutDuration`.
> 
> If so, how to proceed ?
> 1) Create an `FirebaseAnalyticsIos` namespace and add the method `setsessiontimeoutinterval`?
> 2) Create the iOS version of `setSessionTimeoutDuration` and call `setsessiontimeoutinterval` ? Leaving it documented in the dart side?
> 
> cc: @collinjackson

**Comment by Salakar** [comment]
Closing this due to the tag spam from other issues. If this is still an issue then it'll most likely be covered under #2582
