### ISSUE TITLE
[firebase_messaging] Error "Fatal: failed to find callback" is logged even if no background message handling is needed

### ISSUE THREAD

**Issue by cremor** [FirebaseExtended/flutterfire#180]
**Describe the bug**
According to the readme handling background messages is optional. But if you don't implement it (and don't pass a `onBackgroundMessage` handler to `configure`), the error message "Fatal: failed to find callback" is always logged.

**To Reproduce**
1. Configure the plugin in a Flutter app without implementing any background message handling (e.g. like you would have done in version 5.1.4 and before)
2. Start the app.
4. See the error in the log.

**Expected behavior**
No error should be logged because background message handling is not wanted if no message handler is passed as `onBackgroundMessage` to `configure`.

**Additional context**
firebase_messaging version 5.1.5
Flutter version 1.9.1+hotfix.2
I assume this was added by @collinjackson or @kroikie in #38

**Comment by boyfox** [comment]
I have same issue

**Comment by kevin4dhd** [comment]
same error

**Comment by supertiger1234** [comment]
aaand its still not fixed oof

**Comment by jameskaguo777** [comment]
Somebody save this train i have same issue.

```
class PushNotificationsManager {

  PushNotificationsManager._();

  factory PushNotificationsManager() => _instance;

  static final PushNotificationsManager _instance = PushNotificationsManager._();

  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  bool _initialized = false;

  Future<void> init() async {
    if (!_initialized) {
      // For iOS request permission first.
      _firebaseMessaging.requestNotificationPermissions();
      _firebaseMessaging.subscribeToTopic('all');
      _firebaseMessaging.configure();

      // For testing purposes print the Firebase Messaging token
      String token = await _firebaseMessaging.getToken();
      print("FirebaseMessaging token: $token");
      
      _initialized = true;
    }
  }
}
```

**Comment by supertiger1234** [comment]
I managed to fix it. I'll share the code when I get on my pc

**Comment by supertiger1234** [comment]
Follow this updated getting started from here: https://github.com/FirebaseExtended/flutterfire/blob/181e3e6d4d9793495018cb159b8072ebef5d94c8/packages/firebase_messaging/README.md#optionally-handle-background-messages
I have also sent in a pr

**Comment by shinriyo** [comment]
me too.
```
firebase_messaging: ^6.0.16
```

**Comment by jdeltoft** [comment]
I still see this, just updated to these for firebase:

  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.0+1
  firebase_ml_vision: ^0.9.7

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓
