### ISSUE TITLE
[firebase_core] Confusion on needing GoogleServices-Info and creating new FirebaseApp

### ISSUE THREAD

**Issue by alevinetx** [FirebaseExtended/flutterfire#1803]
I looked for a forum link, but I didn't find one -- please send me in that direction if it's a better location.

I'm confused as to why we're required to have a GoogleServices-Info file in our build, yet we still need to manually configure a FirebaseApp using a FirebaseConfig populated with the same values. 

 It doesn't appear that the included GoogleServices file is even used.   I have my dev account information in the FirebaseOptions initialization code, but a production account GoogleServices-Info file in the build, and have no problem accessing the dev resources.

If I use the ```FirebaseApp(name:)``` constructor, it complains about not having a FirebaseOptions configuration.

And then when I look at this project:  https://github.com/lohanidamodar/flutter_flavors, he is making direct calls to ```Firestore.instance.collection``` and I don't see any configuration in the code, relying only on the GoogleServices-Info file.

Am I missing something?

Thank you!

**Comment by Ehesp** [comment]
Hey @alevinetx

The `GoogleServices-Info.plist` file is needed to connect your Android/iOS app to Firebase. The "default" app is then used by the plugins by default. 

Some plugins allow you to pass in an additional secondary app, which can be created by the `core` plugin. However, some plugins (such as messaging) require a default app to be available which cannot be created via core.
