### ISSUE TITLE
[firebase_dynamic_links] Sharing through iMessage not working

### ISSUE THREAD

**Issue by dennis-tra** [FirebaseExtended/flutterfire#1806]
**Describe the bug**

Short links shared via the iOS share sheet through iMessage are _sometimes_ not working. See below.

**To Reproduce**
I'm creating a dynamic link like so:

```dart
  final parameters = DynamicLinkParameters(
    uriPrefix: 'https://myapp.page.link',
    link: Uri.parse('https://my.bundle.id/$deepLinkPath'),
    iosParameters: IosParameters(
      bundleId: 'my.bundle.id',
      minimumVersion: '0.0.1',
      appStoreId: '123456789',
    ),
    socialMetaTagParameters: SocialMetaTagParameters(
      title: 'title',
      description: 'description',
      imageUrl: someImageUri,
    ),
  );
  final shortDynamicLink = await parameters.buildShortLink()
```
Now I'm opening a share sheet via the [share package](https://pub.dev/packages/share) with `shortDynamicLink.shortUrl` via
```
Share.share(shortDynamicLink.shortUrl);
```

If I tap on an iMessage contact immediately I'll share the proper short link like: `https://myapp.page.link/EorziMd2SC4Qgswa9`.

If I wait a couple of seconds and then tap on an iMessage contact the link that gets shared looks more like this:
```
https://myapp.page.link/s?socialDescription=description&socialImageUrl=https://firebasestorage.googleapis.com/v0/b/foobar?alt%3Dmedia%26token%3Dc59a3823-129e-4830-96ff-efe2429cef6b&socialTitle=title
```

When the recipient taps on the first link the `onLink` callback gets reliably called. However the second link redirects to the app but won't trigger the `onLink` callback.

**Expected behavior**
Actually I expect only the first link to be shared but this seems like an iOS thing. Therefore my expected behavior is that also the second link will trigger the `onLink` callback.

**Additional context**
`flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.7-pre.24, on Mac OS X 10.14.6 18G2022, locale en-DE)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Edit:** I believe if I didn't share just the link but add some additional context iOS wouldn't resolve the 302 redirect.
```
Share.share("Foo bar, foo foo bar ${shortDynamicLink.shortUrl}.");
```
This has the disadvantage of not being able to share just the link via airdrop and being redirected directly into the app. I'll check this.

**Comment by RobertBrunhage** [comment]
Seeing the same behavior and as of now I have no real workaround. Do you know any current workaround that could be used in the meantime @dennis-tra?

**Comment by dennis-tra** [comment]
Hi @RobertBrunhage,

sorry I don't know of any workaround yet.

For me it was more important for the `onLink` callback to be called at all, so I went with embedding the dynamic link into a short sentence and accepted that Airdrop would be inconvenient.

**Comment by RobertBrunhage** [comment]
So you mean that all your share links would look like the following and then the dynamic link would work with iMessage?

```
Share.share("Foo bar, foo foo bar ${shortDynamicLink.shortUrl}.");
```

**Comment by dennis-tra** [comment]
That's exactly what I meant :)

**Comment by Andranjo97** [comment]
I'm having the same issue. Have you found a solution yet @dennis-tra?

**Comment by dennis-tra** [comment]
@Andranjo97 I went ahead with the solution that @RobertBrunhage outlined above 👍

**Comment by AresVampire** [comment]
I am having the same issue.
