### ISSUE TITLE
Database does not return a filtered record 

### ISSUE THREAD

**Issue by jamiethain** [FirebaseExtended/flutterfire#1807]
A bit of a problem. 

We have a chip bar record that we put in a variable call _catFilterRecord and depending on the type of property we have it stored in five records, so you can pick five different elements on the chip bar and the subset of properties shows up. 

When we first open the app and go to the "properties screen" the data "Never returns" even if the _catFilterRecord has all "" in it, which should select All elements. 

If the _catFilterRecord is null and the item is "skipped" then it returns the records properly. Or if we go to another section of the application where the filtering record is not used and retrieve the data, then return to this screen where it is used, the application works as normal.  Once it has returned the data, we have to wipe the phone for the issue to come back. 

I don't know if there is some form of logging I can turn on Firestore to see why the records returns no data, it actually sits in the linear progress indicator for ever which just has a standard stream in it. 

The _catFilterRecord the first time it appears is a class that has "" empty strings in it with the exception of category1 which has "TEST" in it for example. 

If we bypass the filter, by removing the record, or we putting a test-fail condition in the "if statement" it works properly. 

  ```
Stream<QuerySnapshot> _streamSelector() {
    CollectionReference cr = Firestore.instance.collection('Properties');
    
    Query query = cr.limit(1000);

    Stream<QuerySnapshot> qs;

    // NOTE:: Here we need to fix why property does not appear first time 
    
    if (_catFilterRecord != null ) {
      if (_catFilterRecord.category1 != null && _catFilterRecord.category1.isNotEmpty)
        query = query.where('category1', isEqualTo: _catFilterRecord.category1);

      if (_catFilterRecord.category2 != null && _catFilterRecord.category2.isNotEmpty)
        query = query.where('category2', isEqualTo: _catFilterRecord.category2);

      if (_catFilterRecord.category3 != null && _catFilterRecord.category3.isNotEmpty)
        query = query.where('category3', isEqualTo: _catFilterRecord.category3);

      if (_catFilterRecord.category4 != null && _catFilterRecord.category4.isNotEmpty)
        query = query.where('category4', isEqualTo: _catFilterRecord.category4);

      if (_catFilterRecord.category5 != null && _catFilterRecord.category5.isNotEmpty)
        query = query.where('category5', isEqualTo: _catFilterRecord.category5);
    }

    qs = query
      .orderBy('category3')
      .snapshots();

    return qs;
  }
```

How do I find the issue?

**Comment by iapicca** [comment]
Hi @jamiethain  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you for providing the code sample

**Comment by TahaTesser** [comment]
Hi @jamiethain 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
