### ISSUE TITLE
[cloud_functions] App crashes on iOS when UInt8List is used as parameter

### ISSUE THREAD

**Issue by lschmierer** [FirebaseExtended/flutterfire#1808]
**Describe the bug**
iOS app crashes when `Uint8List` is used as parameter.
On Android  `FormatException: Invalid envelope` is thrown.

**To Reproduce**
Call a Firebase Cloud Function with an Uint8List as parameter.

**Expected behavior**
As an `Uint8List` basically is (implements) `List<int>`, I would expect `Uint8List` to work as parameter

**Additional context**
Currently possible workaround is to use `List.from(myUint8List)`.

**Comment by nicogranuja** [comment]
Beware when I implemented the workaround mentioned above worked on the flutter side, but on Node cloud function side I had to convert the Array (List) back to a buffer:

`Buffer.from(list);`

**Comment by russellwheatley** [comment]
I don't think it's possible to pass a `Uint8List` parameter to a native platform without wrapping it. [See here](https://stackoverflow.com/questions/58866332/flutter-pass-uint8list-to-ios-objective-c)

**Comment by lschmierer** [comment]
Your statement is false. `Uint8List` is specifically listed here: https://flutter.dev/docs/development/platform-integration/platform-channels#codec

Further, the link you provided is not helpful at all. In fact, the Stackoverflow specifically shows that passing `Uint8List` ist possible. https://stackoverflow.com/a/58869349

**Comment by russellwheatley** [comment]
Apologies, will reopen. I guess that may have been true in that moment in time. Just to clarify, I didn't say it wasn't possible, just that it had to be wrapped i.e. placed within a List.

**Comment by lschmierer** [comment]
Alright, sorry for being a little rude.

I think in `httpsFunctionCall`, parameters containing `FlutterStandardTypedData ` types require special treatment. https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/ios/Classes/FLTFirebaseFunctionsPlugin.m#L74

**Comment by russellwheatley** [comment]
Hey @lschmierer,  I tried  to pass through an obj-c representation of a buffer as a parameter of the cloud function call [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/ios/Classes/FLTFirebaseFunctionsPlugin.m#L93):

```obj-c

// sent an object "parameter" from dart code like so: { "list": Uint8List(100) } 
  NSData * buffer = [[parameters objectForKey:@"list"] data];

  NSDictionary * params = @{
    @"list": buffer
  };
  
  [function callWithObject:params
                completion:^(FIRHTTPSCallableResult *callableResult, NSError *error) {
                  if (error) {
                    result.error(nil, nil, nil, error);
                  } else {
                    result.success(callableResult.data);
                  }
                }];
```

But it still loses connection to device. Looking at the `iOS` for cloud functions documentation, I don't think a buffer is an [accepted parameter](https://firebase.google.com/docs/reference/ios/firebasefunctions/api/reference/Classes/FIRHTTPSCallable#-callwithobject:completion:). The same appears true for the android cloud function [call](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/HttpsCallableReference#call(java.lang.Object)). Not sure if you have any thoughts on a viable solution? If not, I will update the documentation with accepted parameter types to warn users.

**Comment by lschmierer** [comment]
So maybe check if the parameter is FlutterStandardTypedData and if so copy from the buffer to an array?
```objc
NSData *data = ...

UInt8 buf[data.length];
[data getBytes:buf length:data.length];
```

The copy needs to happen anyway. Using  `List.from(myUint8List)` it happens on the Dart side.

`Int32List`, `Int64List` and `Float64List` Dart types will probably require the same handling as they are all represented as FlutterStandardTypedData (wrapped NSData).

On Android bye[], int[], long[] and double[] need to be converted to List<> types.
Like
```Java
  Byte[] array = ....
  List<Byte> list = Arrays.asList(array);
```
which is zero copy, I think.
