### ISSUE TITLE
[firebase_messaging] documentation not according to documentation in firebase causing build failure

### ISSUE THREAD

**Issue by d-silveira** [FirebaseExtended/flutterfire#181]
**Describe the bug**
 [firebase_messaging's  Documentation](https://pub.dev/packages/firebase_messaging) not according to [documentation in firebase](https://firebase.google.com/docs/flutter/setup) causing build failure

**To Reproduce**
1. Following the documentation in https://pub.dev/packages/firebase_messaging, you will enter this line:  'com.google.gms:google-services:4.3.0' in [project]/android/build.gradle file 
2. Run the project
3. Have the build fail with: 
Execution failed for task :app:transformNativeLibsWithStripDebugSymbolForDevDebug
tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils which is totally unreadable

**Expected behavior**
following the documentation the build should run smoothly

**Additional context**
in [firebase's flutter documentation](https://firebase.google.com/docs/flutter/setup), it clearly states that **Flutter is currently compatible with version 3.2.1 of the Google Services plugin.**, so the [documentation in firebase_messaging](https://pub.dev/packages/firebase_messaging) ought to be changed to reflect this limitation instead of showing version 4.3.0 as if it were working

Thank you,
Regards,
Duarte

**Comment by BondarenkoStas** [comment]
@d-silveira Thank you, it's a known bug, I'm going to close the issue to avoid duplication. Please follow https://github.com/FirebaseExtended/flutterfire/issues/57 and https://github.com/FirebaseExtended/flutterfire/issues/243.
