### ISSUE TITLE
[cloud_functions] Cloud functions in local mode doesn't work on Android emulator but works on iOS emulator.

### ISSUE THREAD

**Issue by nerdrun** [FirebaseExtended/flutterfire#1814]
**Describe the bug**

If I run Firebase cloud functions emulator locally it works on iOS emulator but not on Android.

**To Reproduce**
1. Run firebase emulators:start --only functions on terminal.
2. Run my app on android emulator Nexus 6 with API 29 sdk via Visual Studio Code
3. snapshot that I expect to get from server has no any data.

This is codes for cloud functions.
```dart
exports.getUserInfo = https.onCall(async (data, context) => {
  if(!context.auth) return onAuthError()
  try {
    const uid = context.auth.uid
    const usersDocRef = admin.firestore().collection('users').doc(uid)
    const userDoc = await usersDocRef.get()
    return userDoc.data()
  }
  catch(e) {
    return e.message
  }
})
```

And codes for my app

```dart
// user_service.dart
  Stream<HttpsCallableResult> getUserInfo() {
    final HttpsCallable callable = cloudFunctions.getHttpsCallable(functionName: 'getUserInfo');
    return Stream.fromFuture(callable.call());
  }

// team_builder.dart
 return StreamBuilder<HttpsCallableResult>(
      stream: userService.getUserInfo(),
      builder: (context, AsyncSnapshot<HttpsCallableResult> snapshot) {
        switch(snapshot.connectionState) {
          case ConnectionState.waiting: 
            return MaterialApp(
              home: Material(child: CircularProgressIndicator(),)
            );
          default: 
            print('has data : ${snapshot.hasData}');
            if(snapshot.data != null) {
              List teams = snapshot.data.data['teams'];
              return MaterialApp(
                home: (teams.length == 0) ? NoTeam() : Home()
              );
            }
        }
      },
    );

```

The most interesting part is that it works if I run it on iOS emulator clearly.
But it happens only on Android emulator.

Also if I deploy all my codes to the production server and run firebase cloud functions as a production mode, it works as well.

**Expected behavior**
If I use cloud functions in local mode it should works well on Android emulator.

**Additional context**
If I run my app with cloud functions as a production mode, it works both Android and iOS emulator

Thank you.

**Comment by iapicca** [comment]
Hi @nerdrun  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` (on android) 
and your `pubspec.yaml`
Thank you

**Comment by TahaTesser** [comment]
Hi @nerdrun 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
