### ISSUE TITLE
[cloud_functions] Function gets called twice sometimes

### ISSUE THREAD

**Issue by kinex** [FirebaseExtended/flutterfire#1817]
My Flutter app calls cloud functions using the API `CloudFunctions.getHttpsCallable(..).call(..)`

Occasionally I have seen from the Firebase Console logs that a single function call gets called twice. They start almost at the same time and run in parallel. I am 99% sure I didn't call the function twice from my client app code. I just saw this happening when I launched my app in iPhone. App is a release mode app downloaded from TestFlight, so at least the issue cannot have anything to do with debugging or hot reload.

Is this normal or a possible bug in the plugin or somewhere else?

I also found [this from Stackoveflow](https://stackoverflow.com/questions/55379651/firebase-cloud-function-executing-twice-when-triggered-over-http), could it be related?

**Comment by iapicca** [comment]
Hi @kinex 
can you please provide your `flutter doctor -v` ,
your `flutter run -release --verbose` 
Thank you

**Comment by kinex** [comment]
Actually it may be better to close this. I reviewed the plugin code and issue cannot be there (it's so simple). It must be something else, either an issue in Firebase SDK or...... in my code. I will continue tracking this and reopen if needed.

**Comment by elvisun** [comment]
This is an a known behavior of cloud functions, check out this video here 

https://youtu.be/rERRuBjxJ80?t=1018

**Comment by kinex** [comment]
If I understood correctly that video talks about function triggers. The issue I saw is not related to function triggers. I am calling the function directly from my app so it is a different case.
