### ISSUE TITLE
Flutter - Execution failed for task ':unique_identifier:verifyReleaseResources'

### ISSUE THREAD

**Issue by eliaweiss** [FirebaseExtended/flutterfire#1818]
I get this when I do 'flutter run --release'

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':unique_identifier:verifyReleaseResources'.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > Android resource linking failed
         C:\Users\USER\.gradle\caches\transforms-2\files-2.1\df6cf23cc51da578d8b158de17d0c9cb\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
    
         C:\Users\USER\.gradle\caches\transforms-2\files-2.1\df6cf23cc51da578d8b158de17d0c9cb\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
    
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 19s
    Running Gradle task 'assembleRelease'...
    Running Gradle task 'assembleRelease'... Done                      19.7s
    The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
    Building plugin camera...
    Running Gradle task 'assembleAarRelease'...
    Running Gradle task 'assembleAarRelease'... Done                    1.7s
    √ Built build\app\outputs\repo.
    Building plugin cloud_firestore...
    The plugin cloud_firestore could not be built due to the issue above.

When I do `flutter run --debug` I don't get this issue,

Any idea how to solve it?

**Comment by iapicca** [comment]
Hi @eliaweiss  
can you please provide your `flutter doctor -v` ,
your `flutter run --release --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by vinhbui1** [comment]
same issue here

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
