### ISSUE TITLE
[firebase_ml_vision] Issue using firebase_ml_vision 

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [FirebaseExtended/flutterfire#182]
Considering local module **com.google.android.gms.vision.dynamite:0** and remote module **com.google.android.gms.vision.dynamite:2702**
I/DynamiteModule(31079): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2702
V/DynamiteModule(31079): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Vision (31079): Loading library libocr.so
I/Vision (31079): libocr.so library load status: true

I used **firebase_ml_vision****-0.9.2+1.**

**Comment by iapicca** [comment]
Hi @Kyaw-Zin-Thant 
could you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
