### ISSUE TITLE
Execution failed for task ':app:signingConfigWriterDebug'.

### ISSUE THREAD

**Issue by ArtfulDodgerB92** [FirebaseExtended/flutterfire#1822]
**Describe the bug**
I am just trying to start a brand new empty app, and add firebase to it.   Getting this error:

```bash
[   +3 ms] FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[   +3 ms] Execution failed for task ':app:signingConfigWriterDebug'.
[   +2 ms] > java.nio.file.AccessDeniedException: C:\Projects\Apps\appname\build\app\intermediates\signing_config\debug\out\signing-config.json
```

**To Reproduce**
1.  Start a brand new flutter app
2.  Trying to add some very basic functionality, such as following this guide:  https://blog.codemagic.io/firebase-authentication-google-sign-in-using-flutter/
3.  Attempt to run the app.

**Expected behavior**
I expect the app to run.

**Additional context**
Flutter is getting to a point where it is so unstable now that not only do none of my old applications run, but new applications fail if you modify anything outside of the starting code.

As an additional note, I checked the contents of the file referenced in the error message and it is completely empty.

Edit:   Have also tried forcing permissions on all subfolders and files, "everyone" now has full access to this file, no change.

**Comment by iapicca** [comment]
Hi @ArtfulDodgerB92  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by baddri** [comment]
I have the same issue. I try to change signing-config.json and it works.

- open <project_dir>\build\app\intermediates\signing_config\debug\out\
then right click on signing-config.json and open properties.
go to security tab and click advanve button
![image](https://user-images.githubusercontent.com/49059318/76954306-b5f96580-6942-11ea-904e-524f40048130.png)

- click change owner
![image](https://user-images.githubusercontent.com/49059318/76954477-fc4ec480-6942-11ea-9c01-9722719aebdc.png)

- add your active windows user. then apply
![image](https://user-images.githubusercontent.com/49059318/76954708-636c7900-6943-11ea-866a-fd4200937702.png)


open file properties one more time, go to the Security tab. now 
![image](https://user-images.githubusercontent.com/49059318/76955028-058c6100-6944-11ea-96d8-18e1bf0b47cc.png)

edit and simply add an active user. allow full control permission and apply. it works for me. now you have permission to access this file.


> the error happens because you have no access to this file. in my case, it happens right after I reinstall my os.

**Comment by Ehesp** [comment]
Thanks for posting the solution.

**Comment by ArtfulDodgerB92** [comment]
Why is this closed?   You can't just close tickets that are a bit difficult for you.   I specifically said that editing some basic windows permissions did not resolve the fundamental flaws in yet another flutter code release.

Please do not just shrug this off.   Literally every single time the flutter team posts an update, everything breaks.   The whole platform would have been better off if none of them did a single thing in the last 10 months, and instead watched reruns of Seinfeld or something.

**Comment by lakhghazali** [comment]
Have you tried deleting the Build folders from project by running :flutter clean
there are two build folder one is .dart_tool and second is build .
the solution is :delete the both of them from your project and reopen and run flutter run -v it will be word

**Comment by lakwsh01** [comment]
the same problem comes after my computer crash and restore, 
run flutter clean and manually delete the file app\intermediates\signing_config\debug\out\signing-config.json , then flutter run
work for me and flutter automatically build a new one in my case

**Comment by Wassim-TOUATI** [comment]
DELETE FILE 
"C:\Projects\Apps\appname\build\app\intermediates\signing_config\debug\out\signing-config.json"
AND run application
