### ISSUE TITLE
Is it possible to make notifications audible in silent/do not disturb mode?

### ISSUE THREAD

**Issue by DaYuClo** [FirebaseExtended/flutterfire#1825]
Is it possible to make notifications audible even if the phone is in silent or do not disturb mode?
My team managed to make it work for the foreground app but we are unable to find a way to make it work when the app is running in the background or terminated.  Our app is for a special field, therefore, this is one of the feature that our users requested.  For both iOS and Android.

Packages:
firebase_messaging
flutter_local_notifications

**Comment by iapicca** [comment]
Hi @DaYuClo 
this issue doesn't seem to be specific to `flutterfire`,
it's easily translatable in `how can <any app> override "do not disturb"`;
regardless my personal doubt,
if you believe that your case is somehow related to the 3rd party plugin you mentioned
[flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications/issues) you may consider open an issue in the dedicated github I liked.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
