### ISSUE TITLE
[cloud_functions] 'connection error'

### ISSUE THREAD

**Issue by ltduc** [FirebaseExtended/flutterfire#1827]
**Describe the bug**
I call a functions.https.onCall then get error: Function execution took 1788 ms, finished with status: 'connection error' but sometimes at fault, sometimes not

**Expected behavior**
No error occurred

![Untitled](https://user-images.githubusercontent.com/11805724/72610264-808fc600-3959-11ea-8efd-4b82061ccd31.png)

**Comment by iapicca** [comment]
Hi @ltduc  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by TahaTesser** [comment]
Hi @ltduc 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution

**Comment by spideyduulr** [comment]
It appears  really frequently if you don't have a very good connection.
