### ISSUE TITLE
[documentation] document possible exceptions.

### ISSUE THREAD

**Issue by GregorySech** [FirebaseExtended/flutterfire#183]
It would be nice to have a list of known exceptions (or even better an exception/error hierarchy) that can be thrown by the various Flutterfire packages and their APIs.

As those exceptions are not documented error handling is, at best, a shot in the dark.
At worse gets people to publish apps that will not gracefully fail.

For example giving feedback to the user when retrieving data from Firestore or RTDB goes wrong is particularly gnarly. 
Right now those packages users are thorn between printing out the exception or giving way too generic errors to theirs users.

**Comment by panthe** [comment]
I think that the description of errors are a feature very important. In this moment in Flutterfire they are imbarazzing. Please improve it...

**Comment by collinjackson** [comment]
I agree that it would be better to provide dedicated exception classes for all the errors that we're pushing up to the developer. If anyone would like to take a crack at writing a PR for one plugin I'd be happy to review the approach and then we can extend it to the other plugins.

**Comment by GregorySech** [comment]
After looking at the Android reference for most packages it seems that using a hierarchy needs some planning as almost no official SDK uses them between the various platforms. I'm not sure if using it here is a good idea, maybe I'd keep the already used pattern of PackageException + code. It has already been adopted in a few packages including **Auth** with https://github.com/flutter/plugins/pull/775.

 I think this is pretty much the **best** possible way to handle exceptions in the other plugins.

Some seem to already use a similar approach i.e. [Storage](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/StorageError-class.html).

If I'm free in the weekend I'll try to take one of the SDKs with gRPC based errors like firestore.

**Comment by yamauchieduardo** [comment]
Also clarification about exceptions and errors related in https://github.com/FirebaseExtended/flutterfire/issues/1320
