### ISSUE TITLE
[cloud_functions] Legacy endpoints (pre-GA v0.1 and v1beta1) are getting deprecated

### ISSUE THREAD

**Issue by W2YAdmin** [FirebaseExtended/flutterfire#1830]
Hi Team,

I am using the cloud_function plugin in flutter to call my firebase cloud functions and it all works great. At the same time, yesterday I received one email from google stating that am using the Legacy endpoints (pre-GA v0.1 and v1beta1).

The email mentioned few cloud functions which are still being called by these legacy endpoints and all of them are being called using this plugin.

According to the email, I am supposed to migrate the call from pre-GA v0.1 and v1beta1 to v1 endpoints as the Legacy one will expire on April 30 2020.

How can I upgrade to endpoint v1? Will that require changes on my end or in the plugin it self?

Thank a lot in advance!

Regards,
Rajdeep Barad

**Comment by iapicca** [comment]
Hi @W2YAdmin 
this "issue" is hardly related to the FlutterFire plugin for Cloud Function,
more than an issue appear to be a decision from Google Cloud itself
I'd recommend to follow the docs and  [migrate to v1](https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by W2YAdmin** [comment]
Hi @iapicca ,
I agree to your point that it's not related to flutter, at the same time, it is related to the [cloud_functions] plugin.
I current implementation of the cloud_functions plugin is using the legacy endpoints and needed to be updated to V1.
I hope that makes sense?

Regards,
Rajdeep Barad

**Comment by Ehesp** [comment]
Closing this one off - functions should be deployed via the CLI using the latest version which deals with the deprecations. 

Since this issue talks about v1, which is now deprecated itself, its worth closing this to reduce noise.
