### ISSUE TITLE
[firebase_auth] Example is outdated returning the wrong type

### ISSUE THREAD

**Issue by lancecarlson** [FirebaseExtended/flutterfire#1837]
**Describe the bug**

The example returns a FirebaseUser directly:
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/register_page.dart

The library returns an AuthResult type which has a user property on it:
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart

Should be easy to update? Also, I'm not sure if the extends to other examples like login. I can submit a PR if it helps, but I just wanted to confirm first that this was indeed outdated.

**Comment by Ehesp** [comment]
Fixed in latest release
