### ISSUE TITLE
[cloud_firebase] Massive compile time cost - could it be reduced?

### ISSUE THREAD

**Issue by daniel-v** [FirebaseExtended/flutterfire#1841]
**Is your feature request related to a problem? Please describe.**
The compile time overhead of using Firestore is huge, CI systems do cringe when my project is being compiled.

**Describe the solution you'd like**
Somehow make compile time overhead of Firestore sensible.

**Additional context**
1. To measure what's going on with Firestore, I started off with an empty project: `flutter create -t app cpt_slow` with default settings of Flutter's 1.12 SDK.
2. Add `cloud_firestore` to pubspec.yaml
3. `flutter packages get`
4. `cd ios && pod install`
5. `time xcodebuild -sdk iphoneos -configuration Release -workspace ./Runner.xcworkspace -scheme Runner | xcpretty`

The project compiled with `firebase_core` in about 45sec on my system. (Just to add some package that has stuff to compile). Once firestore was added, it jumped up to about 8.5 minutes and pod install also took significantly longer (about 3 minutes).

In an environment, where you make a point of building you app from a clean checkout+environment, this overhead is pretty large just to compile 1 dependency. In my case, the a build on the CI system gets about half the CPU time as my dev machine and much slower IO, resulting in a **whopping 20 min overhead** for this single package.

**Stuff I tried to help poor CI**:

1. use `cocoapods-binary` to cache some build artifacts but I couldn't figure out how to get it to work with Flutter
2. cache pod cache directory, to reduce `pod install` time - does work, pod install is about 15 sec now

**Questions**
Given the following dependencies of cloud_firestore (copied from Podspec.lock):

```
SPEC CHECKSUMS:
  abseil: 18063d773f5366ff8736a050fe035a28f635fd27
  BoringSSL-GRPC: db8764df3204ccea016e1c8dd15d9a9ad63ff318
  cloud_firestore: c5d1e4d114eecb1dfb535f008435685bcf6063f1
  Firebase: 5d77105d9740a07ca6b16927ca971db7e860faaf
  firebase_core: 9bd2e66a276153e219a87ff39dfecb6b671f524a
  firebase_core_web: d501d8b946b60c8af265428ce483b0fff5ad52d1
  FirebaseAnalytics: e83e64b1231dedcd9ddd4bdecd9bcfd6ba341679
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 4aeb81ff53dcd9a3634ca725dc1fb8c2a4622046
  FirebaseCoreDiagnostics: 5e78803ab276bc5b50340e3c539c06c3de35c649
  FirebaseCoreDiagnosticsInterop: 296e2c5f5314500a850ad0b83e9e7c10b011a850
  FirebaseFirestore: b7e6adda31974dbd259fc25b541e8850420c92ed
  FirebaseInstallations: 575cd32f2aec0feeb0e44f5d0110a09e5e60b47b
  FirebaseInstanceID: 6668efc1655a4052c083f287a7141f1ead12f9c2
  Flutter: 0e3d915762c693b495b44d77113d4970485de6ec
  GoogleAppMeasurement: a08a43b8677b95ed51fcef880e36737334d804fd
  GoogleDataTransport: 574a983e829327d7c18f2627f65d9e80164ea8a4
  GoogleDataTransportCCTSupport: cad3cd6cdbdbad6b5c2c9206ec413402755faaaa
  GoogleUtilities: f8de7ddf8c706f58e9b405d53e38bbdaa2731e5a
  "gRPC-C++": 9dfe7b44821e7b3e44aacad2af29d2c21f7cde83
  gRPC-Core: c9aef9a261a1247e881b18059b84d597293c9947
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  nanopb: 18003b5e52dab79db540fe93fe9579f399bd1ccd
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6
```

1. what's the point of having nanopb and gRPC-Core and gRPC-C++. Isn't it redundant?
2. why is there a dependency on FirebaseAnalytics? 
3. what general tips can you give to "make things faster"?

Thanks

**Comment by Ehesp** [comment]
Closing this issue in favour of https://github.com/FirebaseExtended/flutterfire/issues/349
