### ISSUE TITLE
Firebase Admob never shows test deviceid on logcat

### ISSUE THREAD

**Issue by rajeshjeshar** [FirebaseExtended/flutterfire#1842]
Installed firebase admob plugin 
Created admob account and used both test ads and real ads but the current test device id is not showing in both vs code and android studio logcat

Im Not using emulator, Physical device

**Comment by iapicca** [comment]
Hi @rajeshjeshar 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by korchix** [comment]
for android you have to add this as well:

<manifest>
    <application>
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
    </application>
</manifest>

https://developers.google.com/ad-manager/mobile-ads-sdk/android/quick-start#update_your_androidmanifestxml

**Comment by TahaTesser** [comment]
Hi @rajeshjeshar 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution
