### ISSUE TITLE
Firebase Messaging not working correctly in iOS

### ISSUE THREAD

**Issue by rlee1990** [FirebaseExtended/flutterfire#1844]
When the iOS app is in the foreground I do not receive any notifications.
Using Firebase messaging 6.0.9 with Flutter Channel stable, v1.12.13+hotfix.5

**Comment by iapicca** [comment]
Hi @rlee1990 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1530) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
