### ISSUE TITLE
[firebase_auth] Cannot test verifyWithPhoneNumber with Simulator/Emulator

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [FirebaseExtended/flutterfire#1850]
According to [the docs](https://firebase.google.com/docs/auth/android/phone-auth#test-with-whitelisted-phone-numbers), we can whitelist phone numbers for use when authenticating phone numbers with simulators/ emulators.
## Test with whitelisted phone numbers
You can whitelist phone numbers for development via the Firebase console. Whitelisting phone numbers provides these benefits:

- Test phone number authentication without consuming your usage quota.
- Test phone number authentication without sending an actual SMS message.
- Run consecutive tests with the same phone number without getting throttled. This minimizes the risk of rejection during App store review process if the reviewer happens to use the same phone number for testing.
- ### **_Test readily in development environments without any additional effort, such as the ability to develop in an iOS simulator or an Android emulator without Google Play Services._**
- Write integration tests without being blocked by security checks normally applied on real phone numbers in a production environment.

The problem is, as soon as I attempt to run this function, the simulator/emulator crashes asking if I'm using a physical device. Am I wrong in my expectations?

**Comment by Ehesp** [comment]
This is now fixed - tests are running on emulators and also the API now provided a way to specify a `autoRetrievedSmsCodeForTesting` argument.
