### ISSUE TITLE
[cloud_firestore] Indexes missing messages should be shown at the console

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#1852]
I wasted a lot of time on a query that just didn't work, and sometimes (don't as me how) worked but super slow. I didn't think it was a missing Composite Index, since if there's a missing one the Cloud Firestore docs say there would be a message on the console.

After a while I got the idea that maybe it was a missing index and the error message was being printed in Logcat but not on the Flutter Debug Console. Lo and Behold, the message was there.

The perfect solution would be to print the error messages on the Flutter Console, but for now, at least the docs, specially the Getting Started, should point out that any messages related to indexes missing will be printed to Logcat (I don't know the equivalent for iOS).

**Comment by ibobo** [comment]
I'm having this same issue, and it took me a lot of time to figure out it was the problem. Please fix this!!

**Comment by Salakar** [comment]
Consolidating under #1223 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
