### ISSUE TITLE
[firebase_messaging] Fetch whether notifications are enabled or disabled by user

### ISSUE THREAD

**Issue by mehmetf** [FirebaseExtended/flutterfire#186]
Firebase messaging is the primary plugin for delivering notifications for Flutter apps. It is a fairly common use case for notification handling apps to determine whether user has disabled notifications for the app. 

E.g.: https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()

This is a fairly easy fix. I am opening this to see whether @collinjackson agrees this belongs to firebase_messaging.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin. I'd recommend checking out the new `getNotificationSettings` API specifically for this issue.

Thanks everyone 🤓
