### ISSUE TITLE
[firebase_auth] onAuthStateChanged is triggered even if the state has no changes

### ISSUE THREAD

**Issue by herkulano** [FirebaseExtended/flutterfire#1860]
**Describe the bug**
When doing an `auth.signOut()` and the user is already signed out the `onAuthStateChanged` is triggered even though the state has no changes because the state was `user == null` and after it should be `user == null`.

Because of this listening for changes in `onAuthStateChanged` and signing out if `user == null` causes an endless loop.

**To Reproduce**
```dart
    auth.onAuthStateChanged.listen((user) {
      if (user != null) {
        // do something;
      } else {
        auth.signOut();
      }
    });
```

**Expected behavior**
`onAuthStateChanged` should only trigger if the next state is different from the previous state.

**Additional context**
A simple fix is to check if the user is indeed signed in before signing them out:
```dart
    auth.onAuthStateChanged.listen((user) async {
      if (user != null) {
        // do something;
      } else if (await auth.currentUser() != null) {
        auth.signOut();
      }
    });
```

**Comment by iapicca** [comment]
Hi @herkulano 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by Ehesp** [comment]
Your usage is incorrect, when `onAuthStateChanged` is triggered and the user is `null`, the user is already signed out (so you don't need to call it yourself).

That being said, a sign out call shouldn't retrigger the method if they are already signed out so this seems like a valid bug.

**Comment by diegoveloper** [comment]
I found a different behavior  on Android vs iOS with the `FirebaseAuth` plugin.

`auth.onAuthStateChanged` on iOS it won't notify if the user is not sign-in and you call ` auth.signOut()` but on Android yes.
