### ISSUE TITLE
[firebase_messaging] Adding cloud_storage stops notifications being delivered

### ISSUE THREAD

**Issue by Bharavi26** [FirebaseExtended/flutterfire#1865]
I added these two dependencies cloud_firestore and firebase_messaging, because of some conflits in cloud_firestore i am not receiving notification in device if i remove cloud_firestore then notification work, i tried lots of things for this but not perfact solution found.

[https://github.com/flutter/flutter/issues/49288](url)

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
• Flutter version 1.12.13+hotfix.5 at /Users/harishvekariya/flutter
• Framework revision 27321eb (6 weeks ago), 2019-12-10 18:15:01 -0800
• Engine revision 2994f7e1e6
• Dart version 2.7.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/harishvekariya/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /Users/harishvekariya/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.3.1, Build version 11C504
• CocoaPods version 1.9.0.beta.2
[✓] Android Studio (version 3.5)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 42.1.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
[✓] Connected device (1 available)
• iPhone • ---------- • ios • iOS 13.3
• No issues found!
Process finished with exit code 0

```

**Comment by iapicca** [comment]
Hi @Bharavi26 
can you please provide your `flutter run --verbose` 
and your `pubspec.yaml`?
Thank you

**Comment by Bharavi26** [comment]
Hello @iapicca , thank you for your reply.
**pubspec.yaml**
`dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+2
  shared_preferences: 0.5.4+8
  flutter_html: 0.11.0
  jaguar_jwt: 2.1.6
  share: 0.6.3+5
  url_launcher: 5.4.1
  image_picker: 0.6.2+3
  mime: 0.9.6+3
  firebase_messaging: 6.0.9
  webview_flutter: 0.3.16

  #chat settings
  cloud_firestore: 0.13.0+1
  flutter_local_notifications: 0.9.1
  intl: 0.16.0

  provider: 2.0.1+1
`

**flutter run --verbose**
`[  +28 ms] executing: [F:\flutter_sdk\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [F:\flutter_sdk\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +35 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +11 ms] executing: [F:\flutter_sdk\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [F:\flutter_sdk\flutter\] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +81 ms] executing: [F:\flutter_sdk\flutter\] git rev-parse --abbrev-ref HEAD
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +123 ms] executing: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +96 ms] Exit code 0 from: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           4200169d96a47449       device product:j7maxlteins model:SM_G615F device:j7maxlte transport_id:26
[  +14 ms] C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4200169d96a47449 shell getprop
[ +150 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +88 ms] Found plugin cloud_firestore at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\
[  +64 ms] Found plugin firebase_core at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+1\
[  +20 ms] Found plugin firebase_core_web at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+1\
[  +13 ms] Found plugin firebase_messaging at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\
[  +28 ms] Found plugin flutter_local_notifications at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-0.9.1\
[  +71 ms] Found plugin image_picker at F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+3\
[ +106 ms] Found plugin share at F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\
[  +10 ms] Found plugin shared_preferences at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+8\
[  +83 ms] Found plugin url_launcher at F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +7 ms] Found plugin url_launcher_macos at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[  +14 ms] Found plugin url_launcher_web at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[  +13 ms] Found plugin webview_flutter at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.16\
[ +129 ms] Found plugin cloud_firestore at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\
[   +7 ms] Found plugin firebase_core at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+1\
[   +2 ms] Found plugin firebase_core_web at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+1\
[   +2 ms] Found plugin firebase_messaging at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\
[   +4 ms] Found plugin flutter_local_notifications at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-0.9.1\
[   +8 ms] Found plugin image_picker at F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+3\
[   +8 ms] Found plugin share at F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\
[   +1 ms] Found plugin shared_preferences at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.4+8\
[   +9 ms] Found plugin url_launcher at F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +1 ms] Found plugin url_launcher_macos at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +3 ms] Found plugin url_launcher_web at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[   +2 ms] Found plugin webview_flutter at
F:\flutter_sdk\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.16\
[ +152 ms] Generating
D:\AndroidProject\Flutter\telefoniim\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +69 ms] ro.hardware = mt6757
[   +1 ms] ro.build.characteristics = default
[  +60 ms] Launching lib\main.dart on SM G615F in debug mode...
[   +7 ms] executing: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
D:\AndroidProject\Flutter\telefoniim\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +85 ms] Exit code 0 from: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
D:\AndroidProject\Flutter\telefoniim\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.telefoniim" (Raw: "com.telefoniim")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x13
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=11)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=12)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw:
                 "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=13)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw:
                 "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw:
                 "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw:
                 "com.google.android.c2dm.permission.RECEIVE")
               E: application (line=18)
                 A: android:label(0x01010001)="telefoniim" (Raw: "telefoniim")
                 A: android:icon(0x01010002)=@0x7f040015
                 A: android:name(0x01010003)="com.telefoniim.Application" (Raw: "com.telefoniim.Application")
                 A: android:usesCleartextTraffic(0x010104ec)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=24)
                   A: android:theme(0x01010000)=@0x7f090000
                   A: android:name(0x01010003)="com.telefoniim.MainActivity" (Raw: "com.telefoniim.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw:
                     "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                   E: intent-filter (line=47)
                     E: action (line=48)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=50)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw:
                       "android.intent.category.DEFAULT")
                   E: intent-filter (line=52)
                     E: action (line=53)
                       A: android:name(0x01010003)="android.intent.action.VIEW" (Raw: "android.intent.action.VIEW")
                     E: category (line=55)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw:
                       "android.intent.category.DEFAULT")
                     E: category (line=56)
                       A: android:name(0x01010003)="android.intent.category.BROWSABLE" (Raw:
                       "android.intent.category.BROWSABLE")
                     E: data (line=58)
                       A: android:scheme(0x01010027)="https" (Raw: "https")
                       A: android:host(0x01010028)="telefoniim.wrteam.in" (Raw: "telefoniim.wrteam.in")
                 E: service (line=64)
                   A: android:name(0x01010003)="io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService"
                   (Raw: "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService")
                   E: intent-filter (line=65)
                     E: action (line=66)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw:
                       "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=69)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw:
                   "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=73)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebasemessaging.Flutt
                     erFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=76)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.messaging.FirebaseMess
                     agingRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=79)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.cloudfirestore
                     .FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.cloudfirestore.FlutterFirebaseAppRegist
                     rar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=82)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFi
                     rebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=85)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.datatransport.Transpor
                     tRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=88)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.iid.Registrar"
                     (Raw: "com.google.firebase.components:com.google.firebase.iid.Registrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=91)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.firestore.FirestoreReg
                     istrar" (Raw: "com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                 E: service (line=99)
                   A: android:name(0x01010003)="com.google.firebase.messaging.FirebaseMessagingService" (Raw:
                   "com.google.firebase.messaging.FirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: intent-filter (line=102)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=103)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw:
                       "com.google.firebase.MESSAGING_EVENT")
                 E: activity (line=107)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw:
                   "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: provider (line=112)
                   A: android:name(0x01010003)="io.flutter.plugins.imagepicker.ImagePickerFileProvider" (Raw:
                   "io.flutter.plugins.imagepicker.ImagePickerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.telefoniim.flutter.image_provider" (Raw:
                   "com.telefoniim.flutter.image_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=117)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw:
                     "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f0b0000
                 E: receiver (line=122)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdReceiver" (Raw:
                   "com.google.firebase.iid.FirebaseInstanceIdReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw:
                   "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=126)
                     E: action (line=127)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw:
                       "com.google.android.c2dm.intent.RECEIVE")
                 E: provider (line=131)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw:
                   "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.telefoniim.firebaseinitprovider" (Raw:
                   "com.telefoniim.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                 E: activity (line=137)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw:
                   "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: meta-data (line=142)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw: "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f060001
                 E: service (line=146)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.backends.TransportBackendDiscovery
                   " (Raw: "com.google.android.datatransport.runtime.backends.TransportBackendDiscovery")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: meta-data (line=149)
                     A: android:name(0x01010003)="backend:com.google.android.datatransport.cct.CctBackendFactory" (Raw:
                     "backend:com.google.android.datatransport.cct.CctBackendFactory")
                     A: android:value(0x01010024)="cct" (Raw: "cct")
                 E: service (line=153)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSc
                   hedulerService" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=159)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmMana
                   gerSchedulerBroadcastReceiver" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastRece
                   iver")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[  +18 ms] executing: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4200169d96a47449 shell
-x logcat -v time -s flutter
[   +9 ms] executing: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +28 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\ShreeSoftech\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +21 ms] Building APK
[  +22 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +8 ms] Using gradle from D:\AndroidProject\Flutter\telefoniim\android\gradlew.bat.
[   +7 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +114 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +3 ms] executing: [D:\AndroidProject\Flutter\telefoniim\android\]
D:\AndroidProject\Flutter\telefoniim\android\gradlew.bat -Pverbose=true
-Ptarget=D:\AndroidProject\Flutter\telefoniim\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm assembleDebug
[ +724 ms] Welcome to Gradle 5.4.1!
[  +30 ms] Here are the highlights of this release:
[   +1 ms]  - Run builds with JDK12
[        ]  - New API for Incremental Tasks
[   +1 ms]  - Updates to native projects, including Swift 5 support
[   +1 ms] For more details see https://docs.gradle.org/5.4.1/release-notes.html
[ +255 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+11599 ms] File C:\Users\ShreeSoftech\.android\repositories.cfg could not be loaded.
[ +709 ms] Checking the license for package Android SDK Build-Tools 28.0.3 in
C:\Users\ShreeSoftech\AppData\Local\Android\sdk\licenses
[  +12 ms] Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
[   +2 ms] FAILURE: Build failed with an exception.
[   +9 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[   +5 ms] > Failed to install the following Android SDK packages as some licences have not been accepted.
[   +1 ms]      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
[   +2 ms]   To build this project, accept the SDK license agreements and install the missing components using the
Android Studio SDK Manager.
[   +3 ms]   Alternatively, to transfer the license agreements from one workstation to another, see
http://d.android.com/r/studio-ui/export-licenses.html
[   +5 ms]   Using Android SDK: C:\Users\ShreeSoftech\AppData\Local\Android\sdk
[   +6 ms] * Try:
[   +8 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 13s
[ +479 ms] Running Gradle task 'assembleDebug'... (completed in 14.0s)
[   +6 ms] "flutter run" took 15,682ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
`

**Comment by Ehesp** [comment]
Hi @Bharavi26 please could you show some code usage of how you're listening for notifications? These two libraries should have no impact on each other so I think this may be a localised issue.

**Comment by Bharavi26** [comment]
Thank you for reply, i solved that issue.

**Comment by Ehesp** [comment]
Thanks. Posting the solution would be helpful for others who come across this issue.
