### ISSUE TITLE
[cloud_firestore] Poor handling of network when strong Wifi and weak cellular connection is present

### ISSUE THREAD

**Issue by andrewjallenuoft** [FirebaseExtended/flutterfire#1869]
**Describe the bug**
Often when a user is using an app with cloud Firestore in an area with a strong wifi internet connection but very weak cellular data connection, Firestore behaves as if the client is completely offline, with all server queries immediately failing. This can cause a very frustrating user experience for users in a location where this occurs, e.g. inside a building with wifi but inconsistent network data. Eventually Firestore will come back online (>30 seconds) if left running, or will immediately come back online if the app is exited and reopened.

**To Reproduce**
1. Start an app using cloud Firestore in an area with good wifi connectivity and poor data network connectivity. 
2. Minimize (not exit) the app and leave it in the background for some time. 
3. At this point after reopening the app (still in the location with poor network connection but strong wifi connection), often cloud Firestore server queries will immediately fail, as if the device was entirely offline. Eventually Firestore will come back online if the app is left running in the same place, or will immediately come back online if the app is exited and reopened.

This issue occurs often enough to make a considerable impact on the user experience for users using an app in a location where cellular data is unreliable. It seems more likely (or potentially only) to occur if the app is minimized for some time before being reopened again. In general, a user using the app in an area with consistent wifi connectivity but inconsistent network connectivity will experience this issue regularly.

**Expected behavior**
Cloud Firestore remains online using the consistent wifi connection, and server queries return successfully.

**Additional context**
Tested on a physical Android device (Samsung S10+, Android 10). Not tested on iOS

**Comment by iapicca** [comment]
Hi @andrewjallenuoft 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` when reopening the app?
Thank you

**Comment by andrewjallenuoft** [comment]
Here's a copy of the verbose flutter doctor: https://pastebin.com/RSfWbKHa

And a copy from flutter run --verbose: https://pastebin.com/SAUtSefN

Note that the above log was run with a debug build of the app, but the issue will occur in both release and debug builds alike. The device used in the test was kept stationary for the entire duration, for all of which the WiFi connection was good, but cellular data connection very poor.

Somewhat confusingly, I was not able to replicate the problem every time I did this test (2 out of 4 tests - the above log was from one of the tests where the problem was replicated). It seems that the phone may have to be locked or idle (or the app in the background) for a minimum amount of time?

Thanks!

**Comment by frankyvij** [comment]
I have the exact same problem! And this problem is not new, I had this problem a few months ago, and I left it there because I could not find the right solution. In my experience, this issue is only happening on Android - I have not received any complaints from my iOS users yet about my app losing the connection.
