### ISSUE TITLE
[cloud_functions] iOS integration test isn't turning build red on failure

### ISSUE THREAD

**Issue by collinjackson** [FirebaseExtended/flutterfire#1870]
https://github.com/FirebaseExtended/flutterfire/pull/1854 led to a regression (https://github.com/FirebaseExtended/flutterfire/issues/1866) on iOS that was caught by our automated CI in https://cirrus-ci.com/task/5446446803582976

This should have turned Cirrus red but did not because the integration test wasn't migrated to using the E2E plugin and our CI no longer looks at the test log output to determine failures.

Regression fix: https://github.com/FirebaseExtended/flutterfire/pull/1868.

**Comment by Salakar** [comment]
CI rework from a year back has resolved this issue, thanks
