### ISSUE TITLE
[firebase_messaging] Table in "Receiving Messages" section should be updated

### ISSUE THREAD

**Issue by Sylvain17** [FirebaseExtended/flutterfire#1873]
**Describe the bug**
Table in "Receiving Messages" section is outdated

Outdated table 
![image](https://user-images.githubusercontent.com/26551637/73089727-2356c000-3ed7-11ea-8da3-f84499340e23.png)

Updated table should be like
![image](https://user-images.githubusercontent.com/26551637/73089768-3a95ad80-3ed7-11ea-867e-8eee6fd6f4ec.png)

**Comment by krishnakumarcn** [comment]
Is there any way we can get the data messages on the background for iOS? (without bringing the app to foreground?) @Sylvain17

**Comment by Sylvain17** [comment]
@krishnakumarcn Be aware of what you really speak about :
- If you want a push notification on iOS if App is in background, method onMessage is called, then you can create a push with a local notifcation with this plugin : https://pub.dev/packages/flutter_local_notifications
- If you speak about App killed, I think the only way is to call the "Notification Service Extension" which is a more complicated process.

**Comment by Salakar** [comment]
> Is there any way we can get the data messages on the background for iOS? (without bringing the app to foreground?) @Sylvain17

There is but support is not currently implemented as far as I know - we'll be looking to implement the same support in FlutterFire as we did for React Native Firebase; https://rnfirebase.io/messaging/usage#receiving-messages

Which should cover all scenarios;

![image](https://user-images.githubusercontent.com/5347038/79855289-af875f00-83c2-11ea-85fd-3d2c57cafa98.png)

**Comment by britannio** [comment]
When is this being updated? The current README is quite misleading.

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with **detailed and up to date documentation**: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
