### ISSUE TITLE
[firebase_core] Add delete to FirebaseApp

### ISSUE THREAD

**Issue by rich-j** [FirebaseExtended/flutterfire#1876]
Provide `Future<void> FirebaseApp.delete()`. App delete is available in all of the platform APIs. It is needed to release resources used by dynamically configured Firebase apps.

The `delete` method is not available in `firebase_core-v0.4.3+2` or `firebase_core_web-v0.1.1+2`

**Comment by Salakar** [comment]
Hey, this has now landed on master via #2890 - we hope to start shipping preview releases to test out next week.

Thank you for raising this issue 👍
