### ISSUE TITLE
cloud_firestone any which doesn't exist

### ISSUE THREAD

**Issue by Denis-Tadeu-Andre** [FirebaseExtended/flutterfire#1879]

**Comment by iapicca** [comment]
Hi @Denis-Tadeu-Andre 
opening an issue 
please describe it in details and provide 
your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

Closing this issue as no info has been provided
