### ISSUE TITLE
[firebase_dynamic_links] onLink called immediately after calling getInitialLink

### ISSUE THREAD

**Issue by granmoe** [FirebaseExtended/flutterfire#1880]
**Describe the bug**
I'm following the example from the docs pretty closely by calling `getInitialLink` right away and then calling `onLink` and passing in my callbacks. However, when I click a dynamic link in the Android emulator, it is first received from `getInitialLink`, but then the `onSuccess` callback of `onLink` is also called immediately after.

**To Reproduce**
1. Create a minimal app that sets up a ChangeNotifier which listens for dynamic links
2. Debug the app and set breakpoints in the dynamic link handling code
3. Open a dynamic link from another app in Android emulator
4. Note that the link is received from `getInitialLink` and then `onLink({ onSuccess })` is also called with the same link.

**Expected behavior**
If I receive a link when my app is initially opened / resumed, then `onLink({ onSuccess })` shouldn't also be called with that same link.

**Additional context**
I'm new to Flutter and to using the emulators, so this could very well just be a quirk of the Android emulator or an expected behavior of Android itself. Thanks for bearing with me if that's the case.

Here is the code from my ChangeNotifier:

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
import 'package:flutter/material.dart';

class UserModel extends ChangeNotifier {
  GlobalKey<NavigatorState> _navigatorKey;

  UserModel(navigatorKey) {
    _navigatorKey = navigatorKey;
    this.initDynamicLinks();
  }

  String _email;
  String get email => _email;
  set email(String email) {
    _email = email;
    notifyListeners();
  }

  FirebaseUser _firebaseUser;
  FirebaseUser get firebaseUser => _firebaseUser;
  set firebaseUser(FirebaseUser firebaseUser) {
    _firebaseUser = firebaseUser;
    notifyListeners();
  }

  void initDynamicLinks() async {
    final PendingDynamicLinkData dynamicLink =
        await FirebaseDynamicLinks.instance.getInitialLink();

    processDynamicLink(dynamicLink);

    FirebaseDynamicLinks.instance.onLink(
        onSuccess: this.processDynamicLink,
        onError: (OnLinkErrorException e) async {
          print('onLinkError');
          print(e.message);
        });
  }

  Future<dynamic> processDynamicLink(PendingDynamicLinkData dynamicLink) async {
    final Uri deepLink = dynamicLink?.link;

    if (deepLink == null) {
      return;
    }

    final String link = deepLink.toString();
    final bool isEmailSignIn =
        await FirebaseAuth.instance.isSignInWithEmailLink(link);

    if (_email != null && _email.length > 0 && isEmailSignIn) {
      try {
        AuthResult authResult = await FirebaseAuth.instance
            .signInWithEmailAndLink(email: _email, link: link);

        this.firebaseUser = authResult.user;
        _navigatorKey.currentState.pushReplacementNamed('/');
      } catch (e) {
        print(e);
      }
    }
  }
}
```

This is set up via a ChangeNotifierProvider in a very basic app. I can setup a repro with the minimal code to reproduce if needed.

**Comment by iapicca** [comment]
Hi @granmoe 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose` 
Thank you

**Comment by granmoe** [comment]
Hi, @iapicca. Thanks for the response 🙂

Here is the output of `flutter doctor -v`:

```sh
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.7 at /Users/mattgranmoe/flutter
    • Framework revision 9f5ff2306b (3 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mattgranmoe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

I've attached the output of `flutter run --verbose`.

/Users/mattgranmoe/code/zen/client/output.txt

**Comment by granmoe** [comment]
Those two errors in the output seem to be stale. That type was wrong, but I fixed it. And I was in the middle of refactoring my auth page when that error about missing a Material ancestor occurred. That's gone now, too. I did run `flutter clean` before `flutter run --verbose`.

**Comment by granmoe** [comment]
@iapicca I just ran `flutter upgrade` last night, and now I can't seem to repro the issue 🙂

Closing
