### ISSUE TITLE
[firebase_analytics] - constructor with FirebaseApp parameter.

### ISSUE THREAD

**Issue by lucaspizzo** [FirebaseExtended/flutterfire#1892]
**Is your feature request related to a problem? Please describe.**
Constructor just like FireStore and Firebase Auth passing FirebaseApp as param.

**Describe the solution you'd like**
Constructor just like FireStore and Firebase Auth passing FirebaseApp as param.

**Additional context**
None.

**Comment by iapicca** [comment]
Hi @lucaspizzo 
could you describe more in detail your proposal
and how it would improve the plugin?
thank you
