### ISSUE TITLE
[cloud_firestore] PERMISSION_DENIED on auth related rules

### ISSUE THREAD

**Issue by XiNiHa** [FirebaseExtended/flutterfire#1893]
**Describe the bug**
I wrote some simple Firestore rules that restricts the writing actions:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
  	match /user/{uid} {
    	allow write: if uid == request.auth.uid
    }
    match /notification/{uid} {
  		allow write: if uid == request.auth.uid
    }
    match /ride/{rideID} {
        allow create: if request.auth.uid != null
    	allow update, delete: if get(resource.data.host).id == request.auth.uid
    }
    match /{document=**} {
      allow read: if true;
    }
  }
}
```
And everytime the rule requires `request.auth.uid` check(even the null checks!), it fails even after finishing the `FirebaseAuth.instance.signInWithCredential(credential)`.  I think its just not sending any auth data at all as `request.auth != null` check also fails.

**To Reproduce**
1. Write some rules that use `request.auth`
2. Complete the auth.
3. Attempt to do the action that requires authentication.
4. Get the exception.

**Expected behavior**
It should work without any exception thrown.

**Additional context**
I don't see any integration between `cloud_firestore` and `firebase_auth`. Does the integration even work?

**Comment by iapicca** [comment]
Hi @XiNiHa 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by XiNiHa** [comment]
`flutter doctor -v`
```
[✓] Flutter (Channel master, v1.14.6-pre.55, on Linux, locale ko_KR.UTF-8)
    • Flutter version 1.14.6-pre.55 at /home/xiniha/flutter
    • Framework revision 3bd4c69fd8 (2일 전), 2020-01-28 10:14:08 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/xiniha/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

[`flutter run --verbose` (Pastebin link)](https://pastebin.com/M7mDZ8g2)

**Comment by XiNiHa** [comment]
While writing the sample, I realized that it was because I didn't use the singleton instance of the `Firestore` object. Which I didn't even know that it exists. ;(
