### ISSUE TITLE
[all] Flutter plugins assume that there will be an Activity available at registration

### ISSUE THREAD

**Issue by BugsBunnyBR** [FirebaseExtended/flutterfire#19]
https://github.com/flutter/flutter/issues/38692

**Comment by collinjackson** [comment]
The only thing we're using the activity for in Flutterfire is transactions (which use AsyncTask and runOnUiThread). There's probably a better way of getting the result of the transaction back to the thread where result can be invoked.

**Comment by iapicca** [comment]
Hello, @BugsBunnyBR 
is this issue still meant to be open?

**Comment by Salakar** [comment]
This is being refactored in an upcoming change. Closing this as its full of issue tag spam.
