### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method DocumentReference#setData on channel plugins.flutter.io/cloud_firestore))

### ISSUE THREAD

**Issue by VanessaERamirez** [FirebaseExtended/flutterfire#1903]
I already made a  
-flutter clean 
-flutter packages get
 but the problem persists in all my projects
Help me please

**Comment by iapicca** [comment]
Hi @VanessaERamirez 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by IchordeDionysos** [comment]
@VanessaERamirez Are you trying to use the plugin in Flutter for web?
This is currently not supported.

https://github.com/FirebaseExtended/flutterfire#available-flutterfire-plugins

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by haipv2** [comment]
@iapicca I've met the same problem
this is output from: flutter doctor -v

`$ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at E:\flutter-sdk
    • Framework revision 0b8abb4724 (9 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\03.android\sdk20180918
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 28.0.3
    • ANDROID_HOME = D:\03.android\sdk20180918
    • Java binary at: D:\03.android\androidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.1)
    • Android Studio at D:\03.android\androidStudio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\02.java\JetBrainsIntelliJIDEAUltimate.2019.3.4.taiwebs.com\IntelliJ IDEA 2019.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
`
plz help me fix! thanks

**Comment by IchordeDionysos** [comment]
@haipv2 What version of Firestore are you using? 🤔
Have you tried to update Firestore to the newest version as I suggested here:
https://github.com/FirebaseExtended/flutterfire/issues/1903#issuecomment-586986578

**Comment by haipv2** [comment]
@IchordeDionysos :
the error was resolved by steps:
-flutter clean
-flutter packages get
- uninstall app
- run again 
Thanks for your time!!!!

**Comment by tibe97** [comment]
@haipv2 I'm having the same issues. Can you tell which version of firebase and cloud_firestore you are using please? Thank you in advance!

**Comment by haipv2** [comment]
@tibe97 latest version, I dont remember which version I used in last month. u can check lib's change log
