### ISSUE TITLE
Error occured during 'Integrate Firebase into Flutter App ' in android studio

### ISSUE THREAD

**Issue by hussain1713** [FirebaseExtended/flutterfire#1907]
```bash
FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Flutter_Apps_Folder\Firebase_project_in_Flutter\firebase_project\android\app\build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'flutterRoot' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by iapicca** [comment]
Hi @hussain1713 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by hussain1713** [comment]
Thank your for your response...
Francecsco Iapicca

**Comment by TahaTesser** [comment]
Hi @hussain1713 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
