### ISSUE TITLE
【firebase_messaging】onResume and onMessage cannot work on iOS

### ISSUE THREAD

**Issue by weiwei00200** [FirebaseExtended/flutterfire#191]
I had two problems.

1. I integrated firebase_messaging v5.1.5 and everything on Android is OK. 
But on ios, onMessage () does not receive messages when APP is in the foreground.

2. App hides to the background and receives the status bar message, click the message, and after evoking APP, onResume will not be called.
What is the reason for this?

In the firebase_messaging doc, only these two cases do not work.

xx | App in Foreground | App in Background
-- | -- | -- 
Notification on iOS | onMessage | Notification is delivered to system tray. When the user clicks on it to open app onResume fires. 
Data Message on iOS | onMessage | Message is stored by FCM and delivered to app via onMessage when the app is brought back to foreground.

**Comment by kleinpetr** [comment]
post contect of your FCM message please.
Do you using some another plugin for example local_notification?

**Comment by weiwei00200** [comment]
1.Yes, I used the flutter_local_notifications plugin.
2.When APP is started, the init() method is called. Here's my code.
`
class PushManager{
  static FirebaseMessaging _fireBaseMessaging;

  /// 初始化消息订阅
  static void init(context, topic) {
    _fireBaseMessaging = FirebaseMessaging();
    _fireBaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        if (message.isNotEmpty) {
          // do Something....
        }
      },
      onLaunch: (Map<String, dynamic> message) async {
        if (message.isNotEmpty) {
          NotificationRes res = NotificationRes.fromJson(message);
          if (res != null) {
            // do Something....
          }
        }
      },
      onResume: (Map<String, dynamic> message) async {
        if (message.isNotEmpty) {
          // do Something....
        }
      },
    );
    _fireBaseMessaging.requestNotificationPermissions(const IosNotificationSettings(sound: true, badge: true, alert: true));
    _fireBaseMessaging.onIosSettingsRegistered.listen((IosNotificationSettings settings) {
      debugPrint("xxx_setting = $settings");
    });
    _fireBaseMessaging.getToken().then((String token) {
      _subscribeTopic(topic);
    });
  }

  /// 订阅主题
  static void _subscribeTopic(topic){
    if(_fireBaseMessaging != null) {
      _fireBaseMessaging.subscribeToTopic(topic);
    }
  }

  /// 取消订阅主题
  static void unsubscribeTopic(topic){
    if(_fireBaseMessaging != null) {
      _fireBaseMessaging.unsubscribeFromTopic(topic);
    }
  }
}`

**Comment by iapicca** [comment]
Hi @weiwei00200 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Thank you"

**Comment by BondarenkoStas** [comment]
Thank you @weiwei00200 , it's a known defect https://github.com/flutter/flutter/issues/21443

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
