### ISSUE TITLE
[cloud_firestore] Sending data to firestore is slow

### ISSUE THREAD

**Issue by Ajaystefin** [FirebaseExtended/flutterfire#1913]
We are planning to do a realtime application, We are able to integrate firestore in the app, but, sending data to firestore takes an average of 1.2 seconds. We have also checked this with the example app provided with the plugin in a good internet connection.
We have recorded some samples in the sheet attached (https://docs.google.com/spreadsheets/d/1oJBTTbF8654EiFy5whMztWLBSQ8mViRIuE2TLK_ThzA/edit#gid=0)

**Steps to Reproduce**
Build the example app provided with firestore.
Modify the sample data to this. So that we can calculate the delay.
```
 {
      'sentTime': DateTime.now(),
      'serverReceivedTime': FieldValue.serverTimestamp(),
 }
```

**Expected behavior**
We need the speed to be less than at least 100 milliseconds for the data to be received at the firestore end because the data deals with currency. The data will be very small.

Thanks

**Comment by iapicca** [comment]
Hi @Ajaystefin  
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
