### ISSUE TITLE
[firebase_ml_vision] PlatformException(Error 13, com.firebase.ml, Barcode engine is nil.)

### ISSUE THREAD

**Issue by jmayobres** [FirebaseExtended/flutterfire#1916]
```bash
flutter: PlatformException(Error 13, com.firebase.ml, Barcode engine is nil.), #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
flutter: #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
flutter: <asynchronous suspension>
flutter: #2      MethodChannel.invokeListMethod 
package:flutter/…/services/platform_channel.dart:335
flutter: #3      BarcodeDetector.detectInImage 
package:firebase_ml_vision/src/barcode_detector.dart:200
flutter: #4      _detect 
package:flutter_camera_ml_vision/utils.dart:43
flutter: #5      CameraMlVisionState._processImage 
package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart:285
flutter: #6      CameraController.startImageStream.<anonymous closure> 
package:camera/camera.dart:412
flutter: #7      _rootRunUnary  (dart:async/zone.dart:1134:38)
flutter: #8      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
flutter: #9      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
flutter: #10     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:338:11)
flutter: #11     _DelayedData.perform  (dart:async/stream_impl.dart:593:14)
flutter: #12     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:709:11)
flutter: #13     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:669:7)
flutter: #14     _rootRun  (dart:async/zone.dart:1122:38)
flutter: #15     _CustomZone.run  (dart:async/zone.dart:1023:19)
flutter: #16     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
flutter: #17     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
flutter: #18     _rootRun  (dart:async/zone.dart:1126:13)
flutter: #19     _CustomZone.run  (dart:async/zone.dart:1023:19)
flutter: #20     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
flutter: #21     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
flutter: #22     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
flutter: #23     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
```

**Comment by iapicca** [comment]
Hi @jmayobres 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by jmayobres** [comment]
name: lcp_mobile
description: LCP Mobile

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  skeleton_text: ^1.0.0
  location: ^2.3.5
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  equatable: ^1.0.3
  flutter_bloc: ^3.1.0
  font_awesome_flutter: ^8.5.0
  meta: ^1.1.8
  fluro: ^1.5.1
  intl: ^0.16.0
  http: ^0.12.0+2
  flutter_secure_storage: ^3.3.1+1
  google_maps_flutter: ^0.5.21+16
  groovin_widgets: ^1.4.2
  dio: ^3.0.8
  shared_preferences: ^0.5.3+4
  fast_qr_reader_view: ^0.1.5
  barcode_flutter: ^1.0.2
  intl_phone_number_input: ^0.1.3
  url_launcher: ^5.2.5
  flutter_crashlytics: ^1.0.0
  flutter_speed_dial: ^1.2.5
  flutter_signature_pad: ^2.0.0+1
  liquid_pull_to_refresh: ^1.1.1
  firebase_ml_vision: ^0.9.3+5
  scanbot_sdk: ^1.1.0
  camera: ^0.5.7+2
  path: ^1.6.2
  path_provider:  ^1.4.0
  enum_to_string: ^1.0.8
  super_enum: ^0.3.0
  torch: ^0.1.1
  image_picker: ^0.6.3+1

  flutter:
    sdk: flutter
 
cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  super_enum_generator: ^0.3.0
  build_runner: ^1.7.3 
  
flutter:
  uses-material-design: true
  assets:
    - assets/

**Comment by jmayobres** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G95,
    locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by jmayobres** [comment]
If you're using one of the on-device APIs, include the corresponding ML Kit library model in your Podfile. Then run pod update in a terminal within the same directory as your Podfile.

pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLVisionTextModel'
