### ISSUE TITLE
[firebase_auth_web] authentication status not persistent

### ISSUE THREAD

**Issue by tianhaoz95** [FirebaseExtended/flutterfire#1918]
**Describe the bug**

According to [firebase auth doc](https://firebase.google.com/docs/auth/web/auth-state-persistence), the default behavior of firebase auth persistency is `LOCAL` meaning it should persistent across refresh. However, that's not the case with `firebase_auth_web`.

Setting the persistency manually did help either:

https://github.com/tianhaoz95/iwfp/blob/faaabf9788fc393888a66a7b864e582fca4b8952/iwfpapp/web/index.html#L12-L26

**To Reproduce**

1. setup `firebase_auth` for web app
2. sign in
3. refresh the browser
4. user is signed out

**Expected behavior**

Users should still be signed in after refreshing the tab.

**Additional context**

Fun fact: it persists during development, but not when the app is compiled.

**Comment by lymtechx** [comment]
I have found the solution:
Instead of this:
``await _firebaseAuth.currentUser();``
use this:
`await _firebaseAuth.onAuthStateChanged.first;`

**Comment by iapicca** [comment]
Hi @tianhaoz95 
does the proposed [solution](https://github.com/FirebaseExtended/flutterfire/issues/1918#issuecomment-583522415) works for you?
If doesn't can you please provide 
your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by tianhaoz95** [comment]
@iapicca yes it worked for me. You can probably mark as fixed if that is the suggested approach.

**Comment by slightfoot** [comment]
This is a bug if the implementations of the platform interfaces have different results.

Just checked and the JavaScript SDK treats it as a property: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/auth.js#L928

I think we should update the [getCurrentUser](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart#L155) function to track the initialization and use the fix above to wait for the first authChanged response whilst the library is still initializing.

**Comment by tianhaoz95** [comment]
lgtm

**Comment by tianhaoz95** [comment]
@iapicca what is left in this issue? Do we want to use it as a tracking bug for the JS SDK fix?

**Comment by iapicca** [comment]
Hi @tianhaoz95 
I think you are right, thanks for letting me know

@slightfoot is it ok for you if I close this?

**Comment by slightfoot** [comment]
This fix cannot be put in the JS SDK. Assign this ticket to me.

**Comment by Yacine-Benali** [comment]
any updates on this issue ?

**Comment by Salakar** [comment]
Hey 👋 

The rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

We also added support on web for configuring persistence, see: https://firebase.flutter.dev/docs/auth/usage#persisting-authentication-state

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
