### ISSUE TITLE
[firebase_ml_vision] TextBlocks and all of it's children have NULL confidency

### ISSUE THREAD

**Issue by topnax** [FirebaseExtended/flutterfire#1919]
**Describe the bug**
When scanning text using the `TextRecognizer` class all scanned elements have  `confidency` field of value `null`.

**To Reproduce**
Try using the following code:
```
    final FirebaseVisionImage visionImage =
        FirebaseVisionImage.fromBytes(availableImage.planes[0].bytes, metadata);
    final TextRecognizer textRecognizer =
        FirebaseVision.instance.textRecognizer();
    final VisionText visionText =
        await textRecognizer.processImage(visionImage);

    for (TextBlock tb in visionText.blocks) {
      debugPrint(tb.confidence.toString());
    }
```
and see that each block (and all it's children such as lines or elements) has a `null` value,

**Expected behavior**
`confidence` field should represent the confidence of the recognizer's choice to mark this block as a text block.

**Additional context**
It's been like this since forever, currently using version `0.9.3+5`.

**Comment by iapicca** [comment]
Hi @topnax 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
Thank you

**Comment by topnax** [comment]
I am closing this issue as now I have read that the `confidence` field is filled only when using it in the cloud which I am not doing. Thank you very much and sorry for my misunderstanding.
