### ISSUE TITLE
Error: The method 'confirmPasswordReset' isn't defined for the class 'FirebaseAuthPlatform'.

### ISSUE THREAD

**Issue by Mahesh73** [FirebaseExtended/flutterfire#1923]
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/lib/src/firebase_auth.dart:340:10: Error: The method 'confirmPasswordReset' isn't defined for the class 'FirebaseAuthPlatform'.
 - 'FirebaseAuthPlatform' is from 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_interface-1.1.2/lib/firebase_auth_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'confirmPasswordReset'.      
        .confirmPasswordReset(app.name, oobCode, newPassword);
         ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

**Comment by nemoryoliver** [comment]
I'm getting the same issue on version 0.15.4

**Comment by phungtienthanh** [comment]
I also got this issue and then I upgraded to the latest version of flutter stable channel to fix it.

**Comment by xiiihyou13** [comment]
I'm having the same issue. On stable channel Dart 2.7, Flutter: 1.12.13, upgraded to beta channel also yield this same issue.

**Comment by xiiihyou13** [comment]
I'm able to compile on Android if commented // confirmPasswordReset method on FirebaseAuth. But on IOS it wont compile due to pod problem, not sure my fault or related, I'll dive it again.

  Future<void> confirmPasswordReset(String oobCode, String newPassword) {
    return FirebaseAuthPlatform.instance.confirmPasswordReset(app.name, oobCode, newPassword);
  }

Seems like this method did not get called in the FirebaseAuthPlatform?

**Comment by MrAndrixx** [comment]
I have the same problem :(
I use Flutter 1.12.13 + hotfix.7 • stable channel and Dart 2.7.0.
At the moment, the only solution I found was to downgrade to `firebase_auth: 0.15.3+1`

**Comment by tenebre1592** [comment]
Same here

**Comment by akarabach** [comment]
Same `firebase_auth: ^0.15.4`

**Comment by razikallayi** [comment]
Same problem

```
Compiler message:
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.
15.4/lib/src/firebase_auth.dart:340:10: Error: The method 'confirmPasswordReset'
isn't defined for the class 'FirebaseAuthPlatform'.
 - 'FirebaseAuthPlatform' is from
 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart
 '
 ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth
 _platform_interface-1.1.2/lib/firebase_auth_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method
named 'confirmPasswordReset'.
        .confirmPasswordReset(app.name, oobCode, newPassword);
         ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.
```

**Comment by razikallayi** [comment]
Solved mine
[#1885 ](https://github.com/FirebaseExtended/flutterfire/issues/1885)

**Comment by Mahesh73** [comment]
it work's finally run this commands in terminal 
1) flutter pub upgrade
2) flutter run
