### ISSUE TITLE
[Firebase Dynamic Links] Documentation of uriPrefix needs to be updated

### ISSUE THREAD

**Issue by loushou** [FirebaseExtended/flutterfire#1930]
**Describe the bug**
The bug is in the documentation. It is more a problem with missing a key piece of information, rather than an actual functional bug. Essentially the problem is this:

No where in the documentation for this plugin does it say that specifically the `uriPrefix` parameter of the `DynamicLinkParameters` class should NOT have a trailing slash. After digging through the code, and doing a long series of testing, I have finally concluded that if you include a trailing slash in this parameter, you will get an error in return that says "The operation couldn’t be completed. Long link is not parsable" because an additional trailing '/' is added to the end of that urlPrefix before the '?' and ensuing query params.

Two things about this are true:
1) this issue DOES NOT manifest on Android builds
2) this issue DOES manifest on iOS builds

**To Reproduce**
```
...
Future<Uri> buildShortLink(String id) async {
  final DynamicLinkParameters parameters = DynamicLinkParameters(
    uriPrefix: 'https://short.example.com',
    link: Uri.parse('https://example.com/?some_id=$id'),
    androidParameters: AndroidParameters(
      packageName: 'com.example.awesome_app',
      minimumVersion: 1,
    ),
    iosParameters: IosParameters(
      bundleId: 'com.example.awesomeApp',
      minimumVersion: '0.1.0',
      appStoreId: '1234567890',
    ),
    googleAnalyticsParameters: GoogleAnalyticsParameters(
      campaign: 'aCampaign',
      medium: 'aMedium',
      source: '$id',
    ),
    itunesConnectAnalyticsParameters: ItunesConnectAnalyticsParameters(
      providerToken: '$id',
      campaignToken: 'aCampaign',
    ),
    socialMetaTagParameters: SocialMetaTagParameters(
      title: 'A social title',
      imageUrl: Uri.parse('https://example.com/path/to/image/image.png?imageversion=1'),
      description: 'Some catch phrase that grabs the eye of the reader',
    ),
  );
  
  Uri long;
  Uri linkUri;
  try {
    long = await parameters.buildUrl();
    print('Full Long Link // $long');
    final ShortDynamicLink shortDynamicLink = await parameters.buildShortLink();
    linkUri = shortDynamicLink.shortUrl;
    return linkUri;
  } catch (e, stack) {
    print('Issue Generating Short Link // $e => $stack');
    return long;
  }
}
...
final Uri finalUrl = await buildShortLink('some-id');
...
```

**Expected behavior**
Either one of two things need to happen:
1) the documentation should be updated to specifically notate, in a clear concise manner, that adding a trailing slash will break the short link generation on iOS, or...
2) the underlying library needs to be repaired in such a way that either a second trailing slash is not added to the end of the `uriPrefix` or the input `uriPrefix` is sanitized before it is sent to the underlying library to not include it

**Additional context**
Thanks for making a great library! It took some time to setup, but now that I have corrected the steps required for getting started on my end, it works like a charm!

**Comment by russellwheatley** [comment]
Hey @loushou, can you confirm if this is still a problem given the major version updates to firebase iOS sdk and `firebase_dynamic_links` package?
