### ISSUE TITLE
[firebase_auth] throws PlatformException instead of FirebaseAuthInvalidUserException when user is disabled

### ISSUE THREAD

**Issue by riyoua** [FirebaseExtended/flutterfire#1934]
FlutterSDK:1.12.13+hotfix.7

 this my simple code : 
```
`final PhoneVerificationCompleted phoneVerificationCompleted =
        (AuthCredential credential) async{
          print("verified $phoneNumber");
         
         
         try{
                await FirebaseAuth.instance.signInWithCredential(credential);

                } on PlatformException catch (exception){
                  print(exception);
                  
                } catch (error){

                }`
```
it works fine until i try to disable the account from Firebase Console . 
according to firebase docs FirebaseAuth should throw FirebaseAuthInvalidUserException
no matter what i still can't handle this thrown PlatFormException .
and this is what i get when  a disabled user try to login . 

[ +876 ms] E/flutter ( 2479): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:
PlatformException(ERROR_USER_DISABLED, The user account has been disabled by an administrator., null)
[   +4 ms] E/flutter ( 2479): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[  +29 ms] E/flutter ( 2479): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[   +2 ms] E/flutter ( 2479): <asynchronous suspension>
[  +17 ms] E/flutter ( 2479): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
[   +4 ms] E/flutter ( 2479): #3      MethodChannelFirebaseAuth.signInWithCredential
(package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:161:23)
[  +19 ms] E/flutter ( 2479): #4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
[   +2 ms] E/flutter ( 2479): #5      _RegisterUiState.verifyNumber.<anonymous closure>
(package:highest_price/ui/register_ui.dart:47:45)
[   +1 ms] E/flutter ( 2479): #6      MethodChannelFirebaseAuth._callHandler
(package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:377:30)
[   +1 ms] E/flutter ( 2479): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55) 
[        ] E/flutter ( 2479): #8      MethodChannel.setMethodCallHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:370:54)
[   +1 ms] E/flutter ( 2479): #9      _DefaultBinaryMessenger.handlePlatformMessage
(package:flutter/src/services/binding.dart:200:33)
[   +3 ms] E/flutter ( 2479): #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
[   +1 ms] E/flutter ( 2479): #11     _rootRun (dart:async/zone.dart:1126:13)
[  +19 ms] E/flutter ( 2479): #12     _CustomZone.run (dart:async/zone.dart:1023:19)
[   +1 ms] E/flutter ( 2479): #13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter ( 2479): #14     _invoke3 (dart:ui/hooks.dart:302:10)
[        ] E/flutter ( 2479): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
[        ] E/flutter ( 2479):

**Comment by iapicca** [comment]
Hi @riyoua 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by greghesp** [comment]
Hi @riyoua 

I have tested this on the [latest roadmap version](https://github.com/FirebaseExtended/flutterfire/issues/2582), and can confirm this is fixed.

```
[firebase_auth/user-disabled] The user account has been disabled by an administrator.
```

Please keep an eye out on the [roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) for release notifications

**Comment by iapicca** [comment]
Hi @riyoua 
given @greghesp  last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
