### ISSUE TITLE
Execution failed for task ':firebase_auth:javaPreCompileDebug'. > Could not resolve all files for configuration ':firebase_auth:debugCompileClasspath'.

### ISSUE THREAD

**Issue by younesmps** [FirebaseExtended/flutterfire#1937]
Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:javaPreCompileDebug'.
> Could not resolve all files for configuration ':firebase_auth:debugCompileClasspath'.
   > Could not find firebase-auth.jar (com.google.firebase:firebase-auth:19.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-auth/19.2.0/firebase-auth-19.2.0.jar
   > Could not find firebase-common.jar (com.google.firebase:firebase-common:19.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-common/19.3.0/firebase-common-19.3.0.jar

**Comment by iapicca** [comment]
Hi @younesmps 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by helenaford** [comment]
@younesmps closing this. please let me know if you are still experiencing the issue and I'll reopen it.
