### ISSUE TITLE
[firebase_messaging] onLaunch not firing on iOS

### ISSUE THREAD

**Issue by SebAubin** [FirebaseExtended/flutterfire#1938]
The problem is: On iOS i'm receiving the notification but when I click on it, the callback onLaunch is not triggered. 

> [✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale fr-CA)

    • Flutter version 1.12.13+hotfix.7 at /Users/SPicheAubin/Documents/git/flutter
    • Framework revision 9f5ff2306b (il y a 9 jours), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

    • Android SDK at /Users/SPicheAubin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/SPicheAubin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

> [✓] Android Studio (version 3.5)

    • Android Studio at /Users/SPicheAubin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

> [✓] VS Code (version 1.41.1)

    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

> [✓] Connected device (2 available)

    • SM G955W • 988bdb415845483034                       • android-arm64 • Android 9 (API 28)
    • iPhone   • 87e37ed046a1dd67838006cf237bc5fd0f40dece • ios           • iOS 13.1.3

> • No issues found!

I've followed the iOS integration steps and some issues but nothing is working. 

Thank you

**Comment by fxsalazar** [comment]
Posible duplicate: #1838

**Comment by SebAubin** [comment]
I resolved my problem using this "hack": 

When the app is launching from my notification and the app terminated, the launch options data is  present but the call to the onLaunch callback is not made. Knowing that, I'm able to store the data in the UserDefaults in the _didFinishLaunchingWithOptions_ function. After that, in the Dart side, i'm able to access the UserDefaults to get the data and do my work.
