### ISSUE TITLE
"firebase_firestore" Doesn't exist on docs

### ISSUE THREAD

**Issue by Reprevise** [FirebaseExtended/flutterfire#194]
There's an issue with the docs. "firebase_firestore" doesn't exist. I assume you mean "cloud_firestore". The issue is also in the "Analytics enabled" tab too.
![image](https://user-images.githubusercontent.com/25782944/65374262-e5f6d300-dc55-11e9-8b4c-6ad1ee7d27b4.png)
![image](https://user-images.githubusercontent.com/25782944/65374268-06bf2880-dc56-11e9-9cc1-84cd3a9330c8.png)

**Comment by iapicca** [comment]
Hi @Reprevise, 
you are correct as [firebase_firestore](https://pub.dev/packages/firebase_firestore) is dart 2 incompatible,
you may use [cloud_firestore](https://pub.dev/packages/cloud_firestore).

I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
