### ISSUE TITLE
 cloud_firestore package, missing file(s)

### ISSUE THREAD

**Issue by Gavinkaa** [FirebaseExtended/flutterfire#1941]
I'm working on an app and i wanna use cloud_firestore, but if i add the package in the dependencies, I get this error:
Xcode's output:
↳
    In file included from
     ...app/ios/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/nanopb/writer.cc:17:
    In file included from
     ...app/ios/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/nanopb/writer.h:28:
    ...app/ios/Pods/Headers/Public/gRPC-C++/grpcpp/support/byte_buffer.h:22:10: fatal error:
    'grpc/byte_buffer.h' file not found
    #include <grpc/byte_buffer.h>

If i just use these packages: 
  firebase_core: ^0.4.3+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
everything works fine, the problem appears when i add cloud_firestore.

I don't know if it can help but all my dependencies are:
flutter:
    sdk: flutter
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+5
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.1
  email_validator: ^1.0.4
  firebase_core: ^0.4.3+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1

I already flutter upgrade, reinstall pods, cocoapods... and flutter doctor have no issues
I also try to change the channel to dev but nothing changes

I hope someone can help !

**Comment by bakatsuyuki** [comment]
I have same error.
I hope someone can help too!!!!

**Comment by Anmol92verma** [comment]
Same issue here!

[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.12.13+hotfix.7 at /Users/anmolverma/flutter
    • Framework revision 9f5ff2306b (13 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/anmolverma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/anmolverma/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/anmolverma/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • SM N960F       • 4a44434350413598                         • android-arm64 • Android 10 (API 29)
    • Anmol’s iPhone • b79dd3e8a73f8a6b4777dc90cc2e6d42ddb9b5ac • ios           • iOS 13.3.1

• No issues found!

**Comment by bakatsuyuki** [comment]
I found a solution.
```
sudo gem install cocoapods --pre
```

I'm glad if you can help!

**Comment by Anmol92verma** [comment]
@bakatsuyuki Thanks a lot! I ran `pod install` after that command and whoosh! its working!

**Comment by Gavinkaa** [comment]
Works fine for me thanks a lot !
I just change the package to the new one
`cloud_firestore: ^0.13.0+1` to `cloud_firestore: ^0.13.1+1`
and after I ran exactly as you said
`sudo gem install cocoapods --pre
pod install
`
Thank you so much !
