### ISSUE TITLE
[firebase_auth] Support disabling reCaptcha on iOS and Web

### ISSUE THREAD

**Issue by amitkot** [FirebaseExtended/flutterfire#1942]
**Is your feature request related to a problem? Please describe.**
When running integration tests using Flutter Driver, my tests fail due to reCaptcha being shown even though I am using whitelisted numbers. 

**Describe the solution you'd like**
There is a setting in the iOS library for disabling the reCaptcha:
https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/AuthSettings#isappverificationdisabledfortesting

Same setting for Web:
https://firebase.google.com/docs/reference/js/firebase.auth.AuthSettings.html#appverificationdisabledfortesting

Please add support for this flag to the Flutter package.

**Additional context**
On Android the reCaptcha does not show for whitelisted numbers, so the change required will help with iOS and Web.

**Comment by Ehesp** [comment]
Implemented in latest release
