### ISSUE TITLE
[firebase_auth ^0.15.4] <Multiple accounts per email address>

### ISSUE THREAD

**Issue by kingdg25** [FirebaseExtended/flutterfire#1949]
![Screenshot from 2020-02-07 13-16-56](https://user-images.githubusercontent.com/53597092/74003193-b9491b00-49ac-11ea-9773-a5e5922e8a28.png)

In firebase authentication **Allow creation of multiple accounts with the same email address**

      GoogleSignInAccount googleUser = await googleSignIn.signIn();
      print(googleUser.authentication);
      GoogleSignInAuthentication googleAuth = await googleUser.authentication;
      print(googleAuth.idToken);
      final AuthCredential credential = GoogleAuthProvider.getCredential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      print(credential);
      FirebaseUser firebaseUser =
      (await firebaseAuth.signInWithCredential(credential)).user;
      print("=====firebaseUser");
      print(firebaseUser);
      print(firebaseUser.email);

After logging in, getting the email(even others functions like displayName, photoUrl) using the FireBaseUser instance(firebase.email) returns null.

here is the output/print:
![Screenshot from 2020-02-07 13-32-29](https://user-images.githubusercontent.com/53597092/74003648-53f62980-49ae-11ea-86c1-bd9d74c3c670.png)

But choosing back the **Prevent creation of multiple accounts with the same email address** in authentication advance settings:
![Screenshot from 2020-02-07 13-25-53](https://user-images.githubusercontent.com/53597092/74003462-a256f880-49ad-11ea-97d7-6eb04dcaef62.png)

No errors but returning the expected email address.

PS. that email address was used in different provider(like facebook login)

**Comment by iapicca** [comment]
Hi @kingdg25 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by hsangtini** [comment]
May be a bug, try to get email by

`final email = firebaseUser.email ?? firebaseUser.providerData.firstOrNullWhere((e) => e.email != null)?.email;`

firstOrNullWhere from `dartx`: https://pub.dev/packages/dartx or write by your self.

**Comment by arpitjacob** [comment]
> @kingdg25 May be a bug, try to get email by
> 
> `final email = firebaseUser.email ?? firebaseUser.providerData.firstOrNullWhere((e) => e.email != null)?.email;`
> 
> firstOrNullWhere from `dartx`: https://pub.dev/packages/dartx or write by your self.

Thanks for this solution.

**Comment by greghesp** [comment]
Hi @kingdg25 

I have tested this using the [WIP roadmap version](https://github.com/FirebaseExtended/flutterfire/issues/2582) as per below, and can confirm that the information required can be found in `providerData`.  It looks like the implementation is the same for the version you are using as per your comment above.

```
final GoogleSignInAccount googleUser = await GoogleSignIn().signIn();
GoogleSignInAuthentication googleAuth = await googleUser.authentication;

final AuthCredential credential = GoogleAuthProvider.credential(
  accessToken: googleAuth.accessToken,
   idToken: googleAuth.idToken,
);

final UserCredential firebaseUser = await FirebaseAuth.instance.signInWithCredential(credential);

print(firebaseUser.user);
```

`User(displayName: Greg, email: null, emailVerified: false, isAnonymous: false, metadata: UserMetadata(creationTime: 2020-07-14 12:06:24.661, lastSignInTime: 2020-07-14 12:54:50.509), phoneNumber: null, photoURL: https://lh3.googleusercontent.com/a-/*****, providerData, [UserInfo(displayName: Greg, email: g****@****.com, phoneNumber: null, providerId: google.com, uid: ******)], refreshToken: , tenantId: null, uid: *******)`
