### ISSUE TITLE
[cloud_firestore] Map isEqualTo boolean not working

### ISSUE THREAD

**Issue by kepuza** [FirebaseExtended/flutterfire#1953]
I was trying to query but I realized that it wasn't working

```
// Sample document in the 'users' collection

{
    user: "John Doe",
    wantX: {
        "man": true,
        "woman": false
    }
}
```

```
CollectionReference col = Firestore.instance.collection("users");
Query x = col.where('wantX.man',  isEqualTo: true);
```

this query does not work

**Comment by ditman** [comment]
We're currently doing some big updates to `cloud_firestore`. Has this code ever worked before for you and started failing, or is it something that you wanted to do and can't? Could you please let us know what version of the plugin are you using? (cc @amrfarid140)

**Comment by kepuza** [comment]
`cloud_firestore: ^0.13.1`

This code working if it is string but boolean not working

`Query x = col.where('bla.man',  isEqualTo: 'string');`

**Comment by amrfarid140** [comment]
@kepuza Thanks for the issue. Is it crashing or just not returning any results?

If it's crashing. Do you mind posting the stacktrace?

**Comment by kepuza** [comment]
no crash just not returning any results

**Comment by Ehesp** [comment]
Fixed via https://github.com/FirebaseExtended/flutterfire/pull/2913
