### ISSUE TITLE
[cloud_firestore] where 'arrayContains' doesn't work with document references

### ISSUE THREAD

**Issue by leetworx** [FirebaseExtended/flutterfire#1954]
I have a collection in which each document contains an array field which is used to hold a list of other document references - i.e.

```
collection_foo 
     > doc_a 
          > field_1 (array) 
               - /collection_bar/doc_x (doc ref)
               - /collection_bar/doc_y (doc ref)
collection_bar 
     > doc_x 
     > doc_y 
``` 

I just recently updated my firestore plugin:

```
-  cloud_firestore: ^0.12.10
+  cloud_firestore: ^0.13.1
```

I was hoping to use the new 'arrayContains' feature but when create my StreamBuilder with the following:

```
      return new StreamBuilder(
          stream: Firestore.instance.collection('collection_foo').where('field_1', arrayContains: <some DocumentReference>).snapshots(),
```
I get the following exception:

22:58:18.579 4 info flutter.tools E/flutter (12895): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
22:58:18.579 5 info flutter.tools E/flutter (12895): Invalid argument: Instance of 'DocumentReference'
22:58:18.579 6 info flutter.tools E/flutter (12895): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:392:7)
22:58:18.579 7 info flutter.tools E/flutter (12895): #1      FirestoreMessageCodec.writeValue (package:cloud_firestore_platform_interface/src/method_channel/utils/firestore_message_codec.dart:83:13)

Note that as a test I found that if I change the array to hold strings (e.g. document_ref.path) then the filtering works fine, but it would be great if we could handle the actual references.

**Comment by amrfarid140** [comment]
@leetworx We are doing some major changes in `cloud_firestore` and this looks like a bug in those recent changes.

**Comment by leetworx** [comment]
Thanks @amrfarid140 confirmed it was the issue with the message codec encoding for document reference. Looks like your PR will take care of it - appreciate the quick turn!

**Comment by collinjackson** [comment]
Fix landed in https://github.com/FirebaseExtended/flutterfire/pull/1955
