### ISSUE TITLE
[< firebase_in_app_messaging >] <Add 'Firebase/InAppMessaging' dependency>

### ISSUE THREAD

**Issue by Sp4Rx** [FirebaseExtended/flutterfire#1956]
**Describe the bug**
Add 'Firebase/InAppMessaging' dependency to firebase_in_app_messaging IOS.

**Reason:**
`FIRInAppMessaging` is used in this library but it is not to the dependency thus it gives compile time error.

https://github.com/FirebaseExtended/flutterfire/blob/1b45082655034b6807228e24ca3fa7ed6b0e9bf5/packages/firebase_in_app_messaging/ios/Classes/FirebaseInAppMessagingPlugin.m#L30-L49

Please add `s.dependency 'Firebase/InAppMessaging'` to the pod file
```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'firebase_in_app_messaging'
  s.version          = '0.0.1'
  s.summary          = 'InAppMessaging Plugin for Firebase'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Flutter Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'Firebase'
  s.dependency 'Firebase/InAppMessagingDisplay'
  s.dependency 'Firebase/InAppMessaging' .  <--- add here
  s.static_framework = true

  s.ios.deployment_target = '8.0'
end
```

**Comment by Ehesp** [comment]
Related https://github.com/invertase/react-native-firebase/pull/3264/files

**Comment by Ehesp** [comment]
Going to close this one in favour of https://github.com/FirebaseExtended/flutterfire/issues/2151#issuecomment-600634285
