### ISSUE TITLE
Invalid Form Key. Please refresh the page.

### ISSUE THREAD

**Issue by Xia000** [FirebaseExtended/flutterfire#1958]
**Describe the bug**
When i create a new costumer user in magento 2.3 i got an error Invalid Form Key. Please refresh the page. 

how can i fix this issue?

**Comment by iapicca** [comment]
Hi @Xia000 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by Ehesp** [comment]
Sorry, I'm not sure what your issue is? Please create a new ticket with reproduction so we can investigate.
