### ISSUE TITLE
[Firebase messaging] SubscribeToTopic not working iOS

### ISSUE THREAD

**Issue by rlee1990** [FirebaseExtended/flutterfire#1961]
When using an iPhone 11 or iPhone xr I get the FCM token but then when I try to subscribe to a topic it gives an error:
`6.13.0 - [Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "(null)"
`
On an iPhone 8 it works just fine. Each phone is on the same carrier and are on iOS 13.3.1

Flutter Doctor: 
`[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!`

I have tried all different versions of the plugin even tried

**Comment by rlee1990** [comment]
Can someone take a look at this @sethladd

**Comment by rlee1990** [comment]
@iapicca Anyone looking at this?

**Comment by iapicca** [comment]
Hi @rlee1990 
can you please provide your your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by rlee1990** [comment]
@iapicca sorry I forgot to close this yesterday I made a new project on the latest version of flutter stable channel. It worked on all the devices even with topic subscription.

**Comment by rlee1990** [comment]
I again am having the same issue after creating a new flutter project

**Comment by rlee1990** [comment]
The pubspec:
`cupertino_icons: ^0.1.2
  responsive_builder:
  provider:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  connectivity:
  flrx_validator:
  chewie:
  video_player:
  image_picker:
  permission_handler: ^4.2.0+hotfix.1
  uuid:
  intl:
  flutter_image_compress: 0.6.3
  font_awesome_flutter:
  shared_preferences:
  geolocator:
  path_provider:
  settings_ui:
  flutter_facebook_login:
  google_sign_in:
  timeago:
  agora_rtc_engine:
  overlay_support:
  agora_rtm:
  cached_network_image:
  community_material_icon:
  rflutter_alert:
  url_launcher:
  firebase_crashlytics:
  profanity_filter:
  flutter_slidable:
  geoflutterfire:
  lottie:
  device_info:
  package_info:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git`

**Comment by rlee1990** [comment]
[FCM_error.txt](https://github.com/FirebaseExtended/flutterfire/files/4393742/FCM_error.txt)

**Comment by rlee1990** [comment]
@iapicca  here is more
`[+71075 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/956144081293355, name: main, number: 956144081293355}, timestamp: 1585315662518, bytes:
Zmx1dHRlcjogRXJyb3IgY2F1Z2h0IGJ5IENyYXNobHl0aWNzIHBsdWdpbiA8cmVjb3JkRXJyb3I+Og==}}
[   +7 ms] flutter: Error caught by Crashlytics plugin <recordError>:
[   +2 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/956144081293355, name: main, number: 956144081293355}, timestamp: 1585315662518, bytes:
Cg==}}
[  +46 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/956144081293355, name: main, number: 956144081293355}, timestamp: 1585315662580, bytes:
Zmx1dHRlcjogZmlyZWJhc2VfY3Jhc2hseXRpY3M6IEVycm9yIHJlcG9ydGVkIHRvIENyYXNobHl0aWNzLg==}}
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/956144081293355, name: main, number: 956144081293355}, timestamp: 1585315662580, bytes:
Cg==}}
[        ] flutter: firebase_crashlytics: Error reported to Crashlytics.
`

**Comment by iapicca** [comment]
Hi @rlee1990 
could you please provide you `flutter run --verbose`
thank you

**Comment by rlee1990** [comment]
@iapicca I did it was in the txt file Ill add it again
[FCM_error.txt](https://github.com/FirebaseExtended/flutterfire/files/4393800/FCM_error.txt)

**Comment by rlee1990** [comment]
Here is the flutter doctor: 
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/rickeylee/Desktop/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rickeylee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1`

**Comment by iapicca** [comment]
Thank you @rlee1990

**Comment by rlee1990** [comment]
@iapicca its odd that It worked on an empty project but then when I made a new project and created the full app it stopped working for ios

**Comment by rlee1990** [comment]
@iapicca I got it to work its odd the new bundle ID was the issue for some reason it would not send anything to it. Made a new one and it works. But the docs are not up for ios messages for notifications they are returned as:
`['aps']['alert']`
