### ISSUE TITLE
[firebase_messaging] 6.0.9. Data: onMessage, onLaunch, onResume not working on device. Works on simulator.

### ISSUE THREAD

**Issue by ollydixon** [FirebaseExtended/flutterfire#1962]
Using firebase_messaging 6.0.9 the data notifications work on the simulator but not on the device. Tried release and debug versions.

The device is receiving push notifications just not the data for cloud messages which we use to navigate to the correct screen when they tap the notification.

We use Cloud messaging for our instant message threads, as of now the chat in the app doesn't work. Not sure what to do..

The code looks like such, minimal example.

```
fcmListener(GlobalKey<NavigatorState> navigatorKey) {
  print('Listening for cloud messages');
    final FirebaseMessaging firebaseMessaging = FirebaseMessaging();
    firebaseMessaging.configure(
      onMessage: (map) {
        print('Got new onMessage FCM: ' + map.toString());
        return;
      },
      onLaunch: (map) {
        print('Got new onLaunch FCM: ' + map.toString());
        return;
      },
      onResume: (map) {
        print('Got new onResume FCM: ' + map.toString());
        return;
      },
    );
```

We send the notification data as such using node.js
```
{
    notification: {
        title: 'New message',
        body: 'You received a new instant message from ' + user.firstName,
        badge: '0',
        sound: 'default',
},
    data: {
        json: JSON.stringify({ action: 'new-im', instantMessage, thread }),
    },
}
```

**Comment by ollydixon** [comment]
I found the solution, in order for FCM data notifications to work on the device you need to add options when you send the notification. Example:

```
await admin.messaging().sendToDevice(user.fcmToken, messagePayload, {
        priority: 'high',
        contentAvailable: true,
        restrictedPackageName: 'com.polydelic.zest',
    })
```

**Comment by irufano** [comment]
> I found the solution, in order for FCM data notifications to work on the device you need to add options when you send the notification. Example:
> 
> ```
> await admin.messaging().sendToDevice(user.fcmToken, messagePayload, {
>         priority: 'high',
>         contentAvailable: true,
>         restrictedPackageName: 'com.polydelic.myapp',
>     })
> ```

Did you change this in backend ?

**Comment by ollydixon** [comment]
@irufano yes. Hence admin :-)
