### ISSUE TITLE
[firebase_messaging] Conflict with custom plugin - unable to receive Data messages on iOS

### ISSUE THREAD

**Issue by oligazar** [FirebaseExtended/flutterfire#1963]
I run into a problem and I unable to overcome it without flutter team's help.

I developed a custom plugin which is based on [this](https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124) tutorial and has the same initialization:

```
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    
//    if #available(iOS 10.0, *) {
//        UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
//    }
    
    UIApplication.shared.setStatusBarHidden(false, with: UIStatusBarAnimation.none)

    registerPlugins(self)
      
    SwiftGpsServicePlugin.setPluginRegistrantCallback(registerPlugins)
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

func registerPlugins(_ registry: FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
}
```

When my plugin is initialized in the project I'm unable to receive Data messages on iOS (while Notification messages worked). I debugged firebase_messaging in XCode and I can confirm that 

> (void)messaging:(FIRMessaging *)messaging didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage
 
do called whenever I send Data message, it then calls `[_channel invokeMethod:@"onMessage" arguments:remoteMessage.appData]`, but dart side callback is never invoked.

In the same time when sending Notification message `didReceiveRemoteNotification` gets called as well, it invokes the same `[_channel invokeMethod:@"onMessage" arguments:userInfo]` as `didReceiveMessage` does but in this case dart part works as expected.

I'm struggling to understand the reason why `@"onMessage"` call gets lost. Also I don't know how to debug this case properly. Any suggestion would be appreciated.

I'll attach any additional info if requested. I'm just not sure what is relevant.

**Comment by iapicca** [comment]
Hi @oligazar 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you
