### ISSUE TITLE
[firebase_messaging] Modification/Translation of title and body

### ISSUE THREAD

**Issue by renatomotorline** [FirebaseExtended/flutterfire#1967]
Hi,

It is possible to modify/translate the title and body before the notification appears on the screen?
Something like this: [https://medium.com/coletiv-stories/android-notifications-with-firebase-translations-and-troubleshooting-9f3b136a9ae1](url)

Best regards

**Comment by Ehesp** [comment]
Hello - to achieve this you have 2 options:

1. Send a translated message payload from your server, which will be presented on the device.
2. Send a data-only payload to the device, and manually create your own notification (see [local notifications](https://pub.dev/packages/flutter_local_notifications)) using the data to perform the translation on device before it's shown to the user.

Thanks!
