### ISSUE TITLE
[FIREBASE_ADMOB] Unity Ad Mediation

### ISSUE THREAD

**Issue by JohnBaker123** [FirebaseExtended/flutterfire#1970]
I have impletemented Admob ads without issues using FIREBASE_ADMOB however I now would like to add some other ad sources to my mediation group. I'm not sure if firebase_admob can handle this.

I've followed the instructions from this page (https://developers.google.com/admob/android/mediation/unity)
and everything appears to be setup. Although on Admob side it still shows "Optimizing" after over 3 days for both my Unity Interstitial and Banner ad.

I could not remove "Admob Network" from the mediation group so I just set the CPM to $1000.00 for testing while the Unity ads are set to optimized.

Also in order for Admob to accept the api key I need to use the "Applifier Stats API (deprecated)"  key from unity and not the "Monetization Stats API Access" key as this was giving me an error when I used this on Admob side.

I've added the Unity SDK and Unity AAR files into my Flutter project manually. Added this to my build.gradle file

dependencies {
    compile files('libs/unity-3.4.0.0.aar')
    compile files('libs/unity-ads-3.4.2.aar')
}

and adding the aar files into my app/libs folder in my project. 

I am using the firebase_admob to request ads.

I am not getting any Unity Ads. It continues to default to Admob Ads. 

I have tried on the Unity side to default to all TEST ads and tried all REAL ads. Still receiving only Admob ads.

I have not tried the Mediation Test Suite. I am not sure how to use that within my Flutter project.

**Comment by oncul** [comment]
I have same problem. I test to ads on Mediation test suit its work. 
In test suite
SDK - Found
Adapter - Found
Adapter Initialzation Status - Not Ready

**Comment by oncul** [comment]
Did you solve this problem ?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
