### ISSUE TITLE
[firebase_dynamic_links] dynamic links are not working on Google Chrome browser on Android

### ISSUE THREAD

**Issue by piyushrathodIn** [FirebaseExtended/flutterfire#1984]
Whenever we click on the dynamic link via the Google Chrome browser (which is default browser in Android One devices and Motorola devices), it navigate to Google play store even the app is installed on the phone and from there it does not remember the deep link.

Steps to reproduce :
Its easy to reproduce, just click on any dynamic link on Android device with Google Chrome web browser.

It works fine with other web browsers like Firefox/Opera or default browsers on other devices like in Mi(not Android One devices) and Samsung.

**Comment by nvtuan96** [comment]
Yes, I facing with this problem too . Bump

**Comment by theochampion** [comment]
Have you got any updates on this ?

**Comment by Salakar** [comment]
Could you provide output from `flutter doctor` please? Thanks

**Comment by piyushrathodIn** [comment]
> Have you got any updates on this ?

Unfortunately not.

**Comment by piyushrathodIn** [comment]
> Could you provide output from `flutter doctor` please? Thanks

Of course, here it is:

 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G95, locale en-IN)
⣷^CPiyushs-Mac-mini:generic-template-flutter piyushrathod$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G95, locale en-IN)
    • Flutter version 1.17.1 at /Users/piyushrathod/newer-flutter/flutter
    • Framework revision f7a6a7906b (10 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/piyushrathod/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by piyushrathodIn** [comment]
> Yes, I facing with this problem too . Bump

@nvtuan96 indeed this is a blocker issue since most of the android devices use Google chrome as a default browser and we can not use flutter dynamic links efficiently. Can you please inform me if you got any solution for this?

**Comment by nvtuan96** [comment]
> > Yes, I facing with this problem too . Bump
> 
> @nvtuan96 indeed this is a blocker issue since most of the android devices use Google chrome as a default browser and we can not use flutter dynamic links efficiently. Can you please inform me if you got any solution for this?

I have changed to paid service Appsflyer

**Comment by piyushrathodIn** [comment]
I haven't got solution yet.
