### ISSUE TITLE
firebase_admob Adaptive Banners feature request

### ISSUE THREAD

**Issue by nemoryoliver** [FirebaseExtended/flutterfire#2003]
Hi Team,

I know **Smart Banners** are here already and great! But according to the Admob Team, developers will have up to **20% increase in revenue** if they implement **Adaptive Banners**. So I wish you could add this feature soon to the firebase_admob plugin. 

Thank you very much!

**Comment by talent-apps** [comment]
Any update on this?
It seems like this plugin is not updated at all.

**Comment by contextract** [comment]
Any update?

**Comment by marciorr** [comment]
It would be very nice to have adaptive banners. Any idea when it will be available?

**Comment by ycv005** [comment]
@Ehesp any update ? Issue going to be 1 year old. Work done will be highly appreciated.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
