### ISSUE TITLE
FirebaseMessaging: iOS integration issue

### ISSUE THREAD

**Issue by Vikas-Jilla** [FirebaseExtended/flutterfire#2009]
**issue**
onMessage and onResume are not getting fired on iOS

**To Reproduce**
1. Create a new project
2. add firebase_messaging to pubspec.yaml
3. Do integration steps specified in the iOS part
4. Keep the app open or in background
4. send a notification message with both **data** and **notification** tags using curl

**Expected behavior**
onMessage should be fired if the app is kept open
onResume should be fired if the app is in background and launched by clicking notification

**Additional context**
If we remove the below lines from `AppDelegate.m`, then everything is working fine
```
if (@available(iOS 10.0, *)) {
  [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
}
```

**Comment by iapicca** [comment]
Hi @Vikas-Jilla 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you
