### ISSUE TITLE
[firebase_ml_vision] possible incorrect face contour eye position

### ISSUE THREAD

**Issue by xxhenglyxx** [FirebaseExtended/flutterfire#2010]
**Describe the bug**
Face contour eye position seems scaled in, see the [video](https://drive.google.com/file/d/1k4hcK3yhR3Ggvxjqi11MwfRxYOhk4LK0/view?usp=sharing)

**Expected behavior**
Eye coordinate should be very near to actual eye position

**Additional context**
Equation I used to scale coordinate from `CameraImage` by `camera` package to correspond to screen size is:

    scaleX = screenSize.width / imageSize.width
    scaleY = screenSize.height / imageSize.height
    
    newTop = scaleY * mlVisionFace.boundingBox.top
    newLeft = scaleX * mlVisionFace.boundingBox.left
    newRight = scaleX * mlVisionFace.boundingBox.right
    newBottom = scaleY * mlVisionFace.boundingBox.bottom

I notice how `mlVisionFace.boundingBox` different when `enableContour` to `true` and `false`, see the [video](https://drive.google.com/file/d/1rpP30JQFxBXoH2UKtAgIWCL7RzOF7eK5/view?usp=sharing). The bounding box surrounding are much fully cover the face when `enableContour: false`, so I think the eye position should also stretch little to side to be in correct position comparing with the one that has `enableContour: true` which are narrower on the width which might cause the eye position to get stretch in little.

**Comment by iapicca** [comment]
Hi @xxhenglyxx 
can you please provide your `flutter doctor -v` , 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you
