### ISSUE TITLE
[firebase_messaging] iOS notification onResume, onLaunch callback not working

### ISSUE THREAD

**Issue by SandyAra** [FirebaseExtended/flutterfire#2011]
We Tried creating notification in our flutter application and found it to be working perfectly fine in Android devices. When it comes to iOS device we are getting the notifications when the app is in the background or when it is not open, but on clicking them we aren't taken to the respective screens which are because the callbacks aren't called. Kindly help to fix this issue.

Versions Used:
Flutter: 1.12.13+hotfix.8
firebase_messaging: 6.0.9
Minimum iOS version supported: 10.0

**To Reproduce**
1. Created APNs Auth Key and Configured in Firebase

2. Enabled Capabilities 
    - Push Notifications
    - Background Mode (Background Fetch and Remote Notifications)

3. Added below code in AppDelegate.m
if (@available(iOS 10.0, *)) {
  [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
}

4. Added below code in main.dart for listening onResume and onLaunch callbacks

    ``` a
   _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print('on message $message');
      },
      onResume: (Map<String, dynamic> message) async {
        print('on resume $message');
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("OnLaunch Message");
      },
    );
    _firebaseMessaging.getToken().then((token) {
      print("NOTIFY TOKEN ${token}");
    }); 


Note: I could not find the solution in #935  #1757  #1677  #23293

**Comment by DevarshRanpara** [comment]
Facing same issue, getting notification if app is not open on screen.
I want to redirect user to specific screen on notification click, but i am getting 3 different cases for notification

#### 1. If app is in foreground 
I don't get notification.

#### 2. If app is in background (Not terminated) 
I get notification, but on notification click unable to redirect to specific screen.

#### 3. If app is terminated
I get notification, and on notification click i am able to redirect to specific screen. (I want this to be happen in all above cases)

[Here](https://stackoverflow.com/q/60283343) is more detail of my issue.

**Comment by AlexandreRoba** [comment]
Was facing the same issue. Removing the swift check as mentionned by @DevarshRanpara resolved the issue.

**Comment by iapicca** [comment]
Hi @SandyAra 
did the proposed [solution](https://github.com/FirebaseExtended/flutterfire/issues/2011#issuecomment-588105004) fix the issue for you
thank you

**Comment by LOG-TAG** [comment]
@AlexandreRoba @SandyAra same issue exists or your comment solution working fine on  `firebase_messaging: ^6.0.12 `?

**Comment by Jackcui68** [comment]
the same issue to me. 
but as the doc,with the code ,it still works. where is the problem?
 
 if (@available(iOS 10.0, *)) {
  [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
}

**Comment by yazinsai** [comment]
Had a similar issue -- including a minimal repo that can be used to demonstrate the erroneous behavior.

**Describe the bug**
Background notifications on iOS do not trigger the `onLaunch` / `onResume` methods in my Flutter app. I also do not see a badget / notification in the iOS notification center. Instead, I receive an `onMessage` trigger when the app is reopened

**To Reproduce**
I created a minimal repo that exhibits this behavior

1. Clone the repository [here](https://github.com/yazinsai/flutter-ios-notifs/)
2. Run the app on the iOS simulator
3. Note the `Token: xxx` value in the Debug Console
4. Move the app to the background
4. Trigger a notification using the following `curl` command:

```sh
DATA='{"notification": {"body": "this is a body","title": "this is a title"}, "priority": "high", "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, "to": "<TOKEN>"}'
curl https://fcm.googleapis.com/fcm/send -H "Content-Type:application/json" -X POST -d "$DATA" -H "Authorization: key=AAAALOSN_jE:APA91bEl5CscNyXpHRrz9F4lJJnFTlt9_FPwEOvI54Q6dr2eSuS00rryGiEXkABdhfMSHimkHrybSh7r3kfhVlciBpO3HYPa_kyT34eg-JE3bWsUg479OQK5ANzCTpJ-bvktN1AWw9j4"
```

**Expected behavior**
I expect a notification to appear in the iOS Notification Center, that when clicked will trigger the `onResume` method. Instead, no notification is presented.

**Additional context**
Output of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-BH)
    • Flutter version 1.12.13+hotfix.9 at /Users/rock/Downloads/flutter
    • Framework revision f139b11009 (2 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rock/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 • 11E9FF08-2E40-4812-A0A4-DC3B1E3398CC • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

Note: I could not find the solution in #935 #1757 #1677 or #2011

**Comment by aizazzaheer** [comment]
Facing the same issue, I've not added the iOS 10 code in AppDelegate.swift yet not able to receive anything on onlaunch and onresume handlers. Anyone facing somethign similar?

**Comment by kristina-efros** [comment]
Faced the same problem - instead of `onResume` and `onLaunch` callbacks an `onMessage` callback is received.

**Comment by nominator** [comment]
any update on this?

**Comment by KarimMohamed2005** [comment]
Are there new updates?

**Comment by KarimMohamed2005** [comment]
New Updates?

**Comment by aloisdeniel** [comment]
Any news? This is a really blocking issue I'm facing too. 😟

**Comment by alustrement** [comment]
+1 This bug is blocking the release of our product, thank you for your reactivity.

**Comment by yazinsai** [comment]
@iapicca the fix doesn't work. Please share an update with everyone on this thread.

**Comment by acoutts** [comment]
In my case I've got onMessage and onResume working as expected, but onLaunch does not fire in iOS. All 3 handlers working as expected in Android.

I have had a lot of issues with firebase messaging in iOS, and there are a ton of open issues about this. Is there another library that works as expected that we can use?

**Comment by ziasultan2** [comment]
in my version v1.12.13+hotfix.9 fcm not working at all. before update it works without any problem. and now it's not giving any message but local notification working only. It's terrible lots of error in every version that really sucks that's why I stopped upgrading

**Comment by MATTYGILO** [comment]
has anyone worked out a fix?

**Comment by spideyduulr** [comment]
has anyone worked out a fix????????

**Comment by emran92** [comment]
I'm on firebase_messaging: ^6.0.16

onResume and onLaunch on iOS is working. It works only when I click on the notification banner, but not when I click on the app icon. Is that an expected behaviour ? 

Also the banner on the notification centre or lock screen wasn't showing up until I uploaded the app on Testflight.

Here's my code:

```
_firebaseMessaging.configure(
        onMessage: (Map<String, dynamic> message) async {
      print('on Message:  $message');
      if (Platform.isIOS) {
        _title = message['title'];
        _message = message['body'];
      } else {
        _title = message['notification']['title'];
        _message = message['notification']['body'];
      }
    }, onResume: (Map<String, dynamic> message) async {
      print('on Resume $message');
      if (Platform.isIOS) {
        _title = message['title'];
        _message = message['body'];
      } else {
        _title = message['data']['title'];
        _message = message['data']['body'];
      }
    }, onLaunch: (Map<String, dynamic> message) async {
      print('onLaunch $message');
      if (Platform.isIOS) {
        _title = message['title'];
        _message = message['body'];
      } else {
        _title = message['data']['title'];
        _message = message['data']['body'];
      }
    });
```

**Comment by RauschDev** [comment]
Same problem for me, this bug is blocking the release of our product.

**Comment by ziasultan2** [comment]
Check your configuration and rebuild again

**Comment by ThomasTeoSY** [comment]
The project I am working on is having the same issue and at last, we found that the root cause was due to format of the push notification is incorrect. I noticed that a lot of comments that I found from the internet asking people to put **click_action**  inside the data content. But for my case, I put the **click_action** in the notification content and its works in my case. 

Not working example: 
DATA='{"notification": {"body": "this is a body","title": "this is a title"}, "priority": "high", "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, "to": "<TOKEN>"}'

**Comment by MobileMon** [comment]
Its working fine for me, I'm guessing some of your apps our crashing or not working because you aren't parsing the title and body correctly on apple devices

to parse the title and body for iOS and Android, use this:

`  final dynamic data = message['data'] ?? message;
    var title = data['title'] ?? message['aps']['alert']['title'];
    var body = data['body'] ?? message['aps']['alert']['body'];`

**Comment by MobileMon** [comment]
Its working fine for me. I suspect some of you may not be parsing the title and body correctly on iOS and that's where the error is occurring. Try using this code:

 ```
try{
      if (Platform.isAndroid) {
        if (message['notification'] != null){
          title = message['notification']['title'] ?? '';
          body = message['notification']['body'] ?? '';
        }
      }
      else if (Platform.isIOS) {
        if (message['aps'] != null){
          if (message['aps']['alert'] != null){
            title = message['aps']['alert']['title'] ?? '';
            body = message['aps']['alert']['body'] ?? '';
          }
        }
      }
      title = title == null ? '' : title;
      body = body == null ? '' : body;
    }
    catch(e){
      title = title == null ? '' : title;
      body = body == null ? '' : body;
    }
```

**Comment by Ranjithsp6** [comment]
> Its working fine for me. I suspect some of you may not be parsing the title and body correctly on iOS and that's where the error is occurring. Try using this code:
> 
> ```
> try{
>      if (Platform.isAndroid) {
>        if (message['notification'] != null){
>          title = message['notification']['title'] ?? '';
>          body = message['notification']['body'] ?? '';
>        }
>      }
>      else if (Platform.isIOS) {
>        if (message['aps'] != null){
>          if (message['aps']['alert'] != null){
>            title = message['aps']['alert']['title'] ?? '';
>            body = message['aps']['alert']['body'] ?? '';
>          }
>        }
>      }
>      title = title == null ? '' : title;
>      body = body == null ? '' : body;
>    }
>    catch(e){
>      title = title == null ? '' : title;
>      body = body == null ? '' : body;
>    }
> ```

Hai @MobileMon ,
I am parsing only data message, Is there any difference for Android and IOS on parsing data message?
In my case on launch is not working only on IOS

**Comment by vercorro** [comment]
>            title = message['aps']['alert']['title'] ?? '';
>            body = message['aps']['alert']['body'] ?? '';

It's now working well thanks to you buddy.

**Comment by Imgkl** [comment]
> > Its working fine for me. I suspect some of you may not be parsing the title and body correctly on iOS and that's where the error is occurring. Try using this code:
> > ```
> > try{
> >      if (Platform.isAndroid) {
> >        if (message['notification'] != null){
> >          title = message['notification']['title'] ?? '';
> >          body = message['notification']['body'] ?? '';
> >        }
> >      }
> >      else if (Platform.isIOS) {
> >        if (message['aps'] != null){
> >          if (message['aps']['alert'] != null){
> >            title = message['aps']['alert']['title'] ?? '';
> >            body = message['aps']['alert']['body'] ?? '';
> >          }
> >        }
> >      }
> >      title = title == null ? '' : title;
> >      body = body == null ? '' : body;
> >    }
> >    catch(e){
> >      title = title == null ? '' : title;
> >      body = body == null ? '' : body;
> >    }
> > ```
> 
> Hai @MobileMon ,
> I am parsing only data message, Is there any difference for Android and IOS on parsing data message?
> In my case on launch is not working only on IOS

Did you find how to parse only the data message? I'm also facing the same issue.

**Comment by Imgkl** [comment]
```
 if (Platform.isAndroid) {
    if (message['data'] != null) {
      screen = message['data']['screen'];
      docID = message['data']['docId'];
      title = message['data']['title'];
    }
  } else if (Platform.isIOS) {
    if (message != null) {
      screen = message['screen'];
      docID = message['docId'];
      title = message['title'];
    }
  } else {
    debugPrint("No message was received");
  }

```

This is how we should parse the data message.

**Comment by Pauljohnson78** [comment]
Strange one indeed this.

- **Android** 

All working as expected.

- **iOS device** (14.3)

Receiving notification (in tray) in both instances when app is not in foreground.
onResume() - onLaunch() - onResume() all fail to fire with no errors.

- **iOS simulator**

Notifications are not visible in tray (expected behaviour).
onResume() - onLaunch() - onResume() all fire correctly and contain correct data (unexpected behaviour(at least for me)).

Anyone had any luck with this one yet?

I'll keep plugging away.

**Comment by russellwheatley** [comment]
Hey @SandyAra, we're a few major versions removed since you raised this issue; `9.1.2`. Could you please let me know if you see the same issue after upgrading, and following the latest documentation? The two platforms are very different on how notification are handled and it is worth your time to carefully understand the expectations [documented here](https://firebase.flutter.dev/docs/messaging/usage).
