### ISSUE TITLE
[firebase_auth] On the web I get null from 'currentUser' after refreshing the browser.

### ISSUE THREAD

**Issue by ronytesler** [FirebaseExtended/flutterfire#2015]
Login, then refresh the browser. Then `await FirebaseAuth.instance.currentUser() `returns null;

**Comment by kjmj** [comment]
Can confirm that I am having the same issue.

**Comment by Ehesp** [comment]
> As a workaround for my use case 

This isn't a workaround, it's expected behaviour. You should be treating the `onAuthStateChanged` listener as the source of truth, as the `currentUser` may not have been initialised by the time you call it.
