### ISSUE TITLE
[firebase_messaging] Support Flutter 1.12 Android embedding

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#2017]
The plugin needs to integrate the [Android embedding changes in Flutter 1.12](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).

`FlutterApplication` does not exist anymore - [see the `README`  section](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/README.md#optionally-handle-background-messages).

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser I think that this is not only documentation because the functionality of the plugin depends on this.

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Please explain it detail what's the issue/change you looking for? 
To better the address the issue
Thank you

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser See https://github.com/FirebaseExtended/flutterfire/issues/1646 and #1764.

I opened this to show that there are problems with `FlutterApplication` **in addition** to what the other issues state. I do not know how to fix it right now.

**Comment by mnesarco** [comment]
Hi, I just upgraded my App to the new Flutter 1.12 API (embedding) and now I don't know how to keep firebase_messaging working :(

**Comment by vkammerer** [comment]
@mnesarco you may find some help at https://stackoverflow.com/a/59490722

**Comment by vkammerer** [comment]
@amirh @kroikie Should the migration of the firebase_messaging plugin to Android embedding v2 take inspiration from the work done by @bkonyi in https://github.com/flutter/plugins/pull/2193 ?
It looks like his abstraction of a BackgroundExecutor could be quite useful when executing firebase messaging in the background: https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/FlutterBackgroundExecutor.java .

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser Do you have any idea how to handle the following situation:

 * This issue is titled "Support Flutter 1.12 Android embedding".

 * #248 is actually something that now occurs for a different reason with this new Android embedding. 

I can add this here as a comment, however, that would not show the importance of this issue and make it less searchable. The `firebase_messaging` plugin is completely broken with the new Android embedding.

**Comment by KamilSvoboda** [comment]
> @mnesarco you may find some help at https://stackoverflow.com/a/59490722

But this approach is not compatible with writing custom platform-specific code. As is described on [flutter.dev](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=ios-channel-swift-tab#step-3-add-an-android-platform-specific-implementation) - I need the FlutterEngine to set setMethodCallHandler on MethodChannel.

**Comment by henry2man** [comment]
> @mnesarco you may find some help at https://stackoverflow.com/a/59490722

I followed the tutorial for Android ( https://pub.dev/packages/firebase_messaging ) just without the optional section [Optionally handle background messages](https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages). At that point I had the same issue as per https://github.com/FirebaseExtended/flutterfire/issues/248.

At that point I used the answer pointed by @mnesarco (https://stackoverflow.com/a/59490722) and then notifications worked great :) 

Kudos!

**Comment by rafaeljustinox** [comment]
> > @mnesarco you may find some help at https://stackoverflow.com/a/59490722
> 
> I followed the tutorial for Android ( https://pub.dev/packages/firebase_messaging ) just without the optional section [Optionally handle background messages](https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages). At that point I had the same issue as per #248.
> 
> At that point I used the answer pointed by @vkammerer (https://stackoverflow.com/a/59490722) and then notifications worked great :)
> 
> Kudos!

Me too! I was facing the same problem but I solved following this steps! Thanks bro!

**Comment by KamilSvoboda** [comment]
> > > @mnesarco you may find some help at https://stackoverflow.com/a/59490722
> > 
> > 
> > I followed the tutorial for Android ( https://pub.dev/packages/firebase_messaging ) just without the optional section [Optionally handle background messages](https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages). At that point I had the same issue as per #248.
> > At that point I used the answer pointed by @vkammerer (https://stackoverflow.com/a/59490722) and then notifications worked great :)
> > Kudos!
> 
> Me too! I was facing the same problem but I solved following this steps! Thanks bro!

Unfortunately not for me. This procedure cannot be combined with the use of [PlatformChannel](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=ios-channel-swift-tab), which must be registered in method **configureFlutterEngine** in **FlutterActivity**. 

For the above procedure to work, it is necessary to remove method configureFlutterEngine from the FlutterActivity. Unfortunately AFAIK  **it is not possible to register PlatformChannel in FlutterApplication**!

**Comment by Salakar** [comment]
I don't believe this issue is relevant anymore with v2 embedding so am closing in favour of checking out the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

Thanks
