### ISSUE TITLE
[cloud_firestore_web] Blob are treated as GeoPoint when compiled in Profile mode

### ISSUE THREAD

**Issue by D-Jeremie** [FirebaseExtended/flutterfire#2020]
**Describe the bug**
The bug appear when compiled with Profile or Release mode (not in debug mode) for flutter web.
I parse documents received by a QuerySnapshot from Firestore but when I retrieve data stored as Blob in my document, value are returned as GeoPoint (for Profile mode) and minified:ia (for Release mode) instead of Blob.

In Debug mode (in web) or in all modes when compiled for mobile (android) data is treated as Blob as expected.

**To Reproduce**
I have documents in Firestore that have this structure:
docId: String
version: String
camData: Blob
time: Timestamp

and retrieving list of this type of document with : 
`Future<List<Map<String, dynamic>>> getData(String id) async {
    QuerySnapshot query;
    query = await _firestore
        .collection("servers/$id/data")
        .where('id', isEqualTo: id)
        .orderBy('time')
        .getDocuments();

    List<Map<String, dynamic>> _list = List();
    for (DocumentSnapshot doc in query.documents) {
      Map<String, dynamic> data = Map.from(doc.data);
      _list.add(data);
    }
    return _list;
  }`

then displaying data with 
`
Column(
          children: <Widget>[
            ...list.map((e) => Text('$e')).toList(),
          ],
        )
`
it return : "{camData: Instance of 'GeoPoint', docId: docN11111, time: Timestamp......}" when compiled with Profile mode 
and 
 "{camData: Instance of 'minified:ia', docId: docN11111, time: Timestamp......}" when compiled with Release mode

**Expected behavior**
camData is stored in Firestore as Blob so when retrieving data it should be a Blob not a GeoPoint or minified:ia with no data on it.

**Additional context**
version of package : 
`cloud_firestore: ^0.13.2+1`

flutter --version :
`Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (3 weeks ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
`

flutter doctor -v : 
`
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale fr-FR)
    • Flutter version 1.14.6 at /Users/jeremie/Documents/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/jeremie/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • ONEPLUS A6013 • 3dc4c7fd   • android-arm64  • Android 10 (API 29)
    • Chrome        • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server    • web-server • web-javascript • Flutter Tools

• No issues found!
`

**Comment by ssilverstein** [comment]
I have the same [issue](https://github.com/FirebaseExtended/flutterfire/issues/2747)

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this should have been resolved in our Firebase Firestore rework (#2913) (we have e2e tests testing Blob & GeoPoint values on Web which are parsing) - this has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
