### ISSUE TITLE
[Fire store ] Upgrade from cloud_firestore: ^0.12.0 to cloud_firestore: ^0.13.0 results in write failure

### ISSUE THREAD

**Issue by madhuks75** [FirebaseExtended/flutterfire#2024]
**Describe the bug**
In cloud firestore 0.12 I set the various parameters into documentsnap.data and then call docsnap.ref.setData to commit it into database. On upgrade to 0.13 there is a silent failure and it does not write into database. 

I have currently downgraded my build to 0.12 and functionality is working. 

Following is the illustrative code snippet, that works in 0.12 and that does not work in 0.13. Please suggest how to proceed.

Code:
dsData.currentStudentDocSnapShot.data[L_SUBSCRIBED] = L_YES;
    if (dsData.currentStudentDocSnapShot.exists) {
      dsData.currentStudentDocSnapShot.reference
          .setData(dsData.currentStudentDocSnapShot.data);
    } else {
     debugPrint('ERROR:dsData.currentStudentDocSnapShot does not exist');
    }

working in 0.12, silent failure in 0.13

**Comment by stuied148** [comment]
I think this is mentioned in #2007. From what I can tell the documentSnapshot.data will remain immutable in the future but will throw an error instead of falling silently.

I'd keep this issue open until an official response is issued.

**Comment by madhuks75** [comment]
thanks!  I shall wait for the official response. Looks very strange, a working s/w starts failing silently because of changes introduced.  

I was working on snapshot as my working area. Now I need to make a copy.

**Comment by Salakar** [comment]
Let consolidate and track this under #2007 - thanks
