### ISSUE TITLE
[all] Add Linux and Windows support

### ISSUE THREAD

**Issue by cbenhagen** [FirebaseExtended/flutterfire#2028]
Options are:
- [C++ SDK](https://github.com/firebase/firebase-cpp-sdk)
- Writing / Adopting existing dart-native implementations like [firedart](https://github.com/cachapa/firedart).

The second option might be harder but in the long run it might be easier to maintain.

(Related to https://github.com/FirebaseExtended/flutterfire/issues/2029)

**Comment by stuartmorgan** [comment]
> * [C++ SDK](https://github.com/firebase/firebase-cpp-sdk)

Note the following, from [the documentation for that SDK](https://firebase.google.com/docs/cpp/setup#desktop-workflow):
> Caution: Firebase C++ SDK desktop support is a beta feature. This feature is intended only for workflows during the development of your game, not for publicly shipping code.

**Comment by cbenhagen** [comment]
I guess pure Dart implementations would be the way to go then.

**Comment by salihgueler** [comment]
If we decide(e.g. I am planning to work on this) to tackle this, should we create separate issues per product and work on them accordingly?

**Comment by cbenhagen** [comment]
@salihgueler I think one meta issue and discussion in the PR would work as well but It's not up to decide. How do you plan to implement it?

**Comment by nilsreichardt** [comment]
An advantage of creating multiple tickets is that we can track which firebase package is how often requested.

**Comment by lzzy12** [comment]
Is there any work started on desktop support?
