### ISSUE TITLE
[all] Add Windows support

### ISSUE THREAD

**Issue by cbenhagen** [FirebaseExtended/flutterfire#2029]
Options are:
- [C++ SDK](https://github.com/firebase/firebase-cpp-sdk)
- Writing / Adopting existing dart-native implementations like [firedart](https://github.com/cachapa/firedart).

The second option might be harder but in the long run it might be easier to maintain.

(related to https://github.com/FirebaseExtended/flutterfire/issues/2028)

**Comment by stuartmorgan** [comment]
> * [C++ SDK](https://github.com/firebase/firebase-cpp-sdk)

Note the following, from [the documentation for that SDK](https://firebase.google.com/docs/cpp/setup#desktop-workflow):
> Caution: Firebase C++ SDK desktop support is a beta feature. This feature is intended only for workflows during the development of your game, not for publicly shipping code.

**Comment by cbenhagen** [comment]
Closing this in favor of https://github.com/FirebaseExtended/flutterfire/issues/2028. I think we can most likely discuss Windows and Linux support in the same issue for now.
