### ISSUE TITLE
[firebase_messaging] Detect User Reject Permissions Via requestNotificationPermissions()

### ISSUE THREAD

**Issue by jasonkaruza** [FirebaseExtended/flutterfire#203]
Per the documentation here https://pub.dev/packages/firebase_messaging, the call requestNotificationPermissions() is a void() and doesn't seem to have a way to detect if the user selects "No" instead of "Yes" to accepting permissions.

> Next, you should probably request permissions for receiving Push Notifications. For this, call _firebaseMessaging.requestNotificationPermissions(). This will bring up a permissions dialog for the user to confirm on iOS. It's a no-op on Android. Last, but not least, register onMessage, onResume, and onLaunch callbacks via _firebaseMessaging.configure() to listen for incoming messages (see table below for more information).

How should one detect that the user declined accepting notification permissions so that the code can handle that scenario appropriately (such as logging the user out, or re-requesting permissions, etc)?

**Comment by ali-thowfeek** [comment]
Yeah, notifications are a crucial part of an app. So it is a must that we know if the user has declined permission. Or at-least we should have a way to ask for permission again, because running `requestNotificationPermissions` again after the first time doesn't bring up the request dialog.

**Comment by Zazo032** [comment]
Maybe the `requestNotificationPermissions()` method should have a return type of `bool` or `Future<bool>`. On Android, as far as I know, you can't block notifications (although you can mute them), so it would probably always return `true`. On iOS, it would be really useful for our app yo know if the user (Android or iOS) has accepted receiving notifications or not. Is there any ETA to improve this?

**Comment by Jan-pp** [comment]
For this I use a separate package that works well: https://pub.dev/packages/notification_permissions

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin. There's also new apis now to read & request detailed permissions, please see the permissions section of the documentation.

Thanks everyone 🤓
