### ISSUE TITLE
[firebase_messaging] Init firebase at runtime / without google-services.json

### ISSUE THREAD

**Issue by timosturm** [FirebaseExtended/flutterfire#2031]
**Description**

Currently the plugin needs the `google-services.json` file to be initialized, or at least no other approach is documented. This is a problem if the file cannot be present when the app is build, i.e. all the information is (optionally) added when the app is already running. Additionally this means that the app can only receive messages from one firebase project. A possible workaround right now might be to create the file at runtime, but that approach  is tedious.

**Describe the solution you'd like**

In android it is possible to initialize firebase at runtime by using [`FirebaseOptions.Builder`](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseOptions.Builder) with something like this:
```java
FirebaseOptions.Builder builder = new FirebaseOptions.Builder()
                    .setApplicationId(...)
                    .setApiKey(...)
                    .setDatabaseUrl(...)
                    .setStorageBucket(...)
                    .setProjectId(...)
                    .setGcmSenderId(...);
            FirebaseApp.initializeApp(this, builder.build());
```

**Additional context**
This might be related to [this](https://github.com/FirebaseExtended/flutterfire/issues/1990).

**Comment by jpeiffer** [comment]
An alternative might be to support the passing a `FirebaseApp` to initialize FirebaseMessaging.  I tried a while back to remove the need for the `google-services.json` and it looked to be pretty deeply embedded into the tools chain and code.

What we're doing is including our Production defaults with the apps, but overriding them at runtime for the `FirebaseDatabase` for test environments.  Unfortunately... that doesn't work for FCM.
