### ISSUE TITLE
[firebase_messaging] critical alerts on iOS? 

### ISSUE THREAD

**Issue by Finn0811** [FirebaseExtended/flutterfire#2033]
Is it possible to send critical push notifications to iOS devices? 

[Apple documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112) says it needs an 'critical' key in the sound dictionary but how do I have to do it with firebase messaging?

**Comment by Ehesp** [comment]
This should be possible, however it requires the critical permission to be set which is currently no implemented. 

Will leave open to track.
