### ISSUE TITLE
[firebase_auth] Google Play Games Auth

### ISSUE THREAD

**Issue by Line-** [FirebaseExtended/flutterfire#2036]
Could support for a GPGS provider please be added?

I am not sure if google_sign_in's SignInOption.games would be enough for auth using the web API client/secret (as set up in Firebase), but maybe that also requires changes to work with firebase_auth.

**Comment by Ehesp** [comment]
Closing as as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2092
