### ISSUE TITLE
[firebase_crashlytics] Migrate away from Fabric

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#2038]
Firebase is going to shut down the Fabric Crashlytics API that is currently still used in the iOS and Android plugin implementations.

The [Firebase Crashlytics Beta has been announced](https://firebase.googleblog.com/2020/02/announcing-firebase-crashlytics-sdk-beta.html).

There is a [migration guide](https://firebase.google.com/docs/crashlytics/upgrade-sdk) detailing how to upgrade from existing Fabric-based code to the new Firebase Crashlytics on both iOS and Android

**Comment by kw2019ltd** [comment]
hi when flutter planning on update Firebase Crashlytics SDKs

mail from google:
we are writing to let you know that the Fabric Crashlytics SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. After this date, the Fabric Crashlytics SDK and beta versions of the Firebase Crashlytics SDK will stop sending crash reports for your app.
What happened?

We are replacing Fabric Crashlytics SDKs and beta versions of the Firebase Crashlytics SDKs with the generally available Firebase Crashlytics SDKs.
What’s Next?

To continue getting crash reports in the Firebase console, make sure to upgrade your apps to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity before November 15, 2020.

Android - upgrade instructions
iOS - upgrade instructions
Unity - upgrade instructions

The following project(s) linked with your account include apps that have enabled Crashlytics:

**Comment by userCodingGabriel** [comment]
Is there any word on this. We are looking into using Crashlytics, but it looks like the support is sketchy with no one updating the documentation. How are we supposed to use Firebase Crashlytics, not Fabric Crashlytics? I've searched this Github rep, but no one seems to have the answer.

**Comment by yringler** [comment]
It looks like it's being worked on (see the linked PR). From the rather superficial look I had at the PR, this seems to be a Big Deal :tm: , affecting a bunch of the firebase plugins, including the core plugin, so - things take time.
IDK, hoping it's released soon :pray:

**Comment by sanekyy** [comment]
Waiting for update.

**Comment by greghesp** [comment]
Hi All,

We're currently working on Crashlytics in the [roadmap version](https://github.com/FirebaseExtended/flutterfire/issues/2582) of FlutterFire.  It is using the Firebase Crashlytics SDKs, and is nearing completion. 

Please keep an eye on on the [roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582)) for upcoming releases

**Comment by Salakar** [comment]
Hey everyone :) the new Crashlytics plugin has now landed on master which now uses the updated non-Fabric SDK.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin and see whats changed: https://firebase.flutter.dev/docs/migration/

**Comment by kw2019ltd** [comment]
there is no new release for it in pub

**Comment by greghesp** [comment]
It's currently on Prerelease: 
https://pub.dev/packages/firebase_crashlytics/versions/0.2.0-dev.5

**Comment by kw2019ltd** [comment]
when it will be merged to Latest?

**Comment by yourshinsuke** [comment]
hey! it is Google product. fix it.0.2
