### ISSUE TITLE
[FIREBASE MESSAGING] <error Plugin Registrant not being recognized in Application.java for background message handling>

### ISSUE THREAD

**Issue by Chimba123** [FirebaseExtended/flutterfire#2041]
when you follow the instructions for the firebase_messaging (https://pub.dev/packages/firebase_messaging) plugin to handle background messages it throws  errors :  "Plugin Registrant not being recognized in Application.java, and Flutter Activity not found"

Follow the instructions on the page exactly and run the application and you will see those errors.

Solution

After some research found here (https://stackoverflow.com/questions/58180714/package-not-found-in-application-java-in-flutter-flutterfirebasemessaging-plugin/58357095#58357095)
 
The problem is that the instructions on the page are simply outdated and the correct instructions are here (https://github.com/FirebaseExtended/flutterfire/blob/111c5b02945b3668016bb55b14e88a637769a1b3/packages/firebase_messaging/README.md#optionally-handle-background-messages)

it will be good if you could update the page

**Comment by haroonkhan9426** [comment]
is onResume and onLaunch callbacks are called properly on your side?
I'm facing issues with onResume and onLaunch callbacks as they are not called.  I just filed the issue here: https://github.com/FirebaseExtended/flutterfire/issues/2042

**Comment by vkammerer** [comment]
I have  just tried to implement it as well and managed to get it done by following the instructions at https://stackoverflow.com/a/59490722

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
