### ISSUE TITLE
[cloud_firestore]: Android release build not possible (Not AndroidX compatible)

### ISSUE THREAD

**Issue by Ahmadre** [FirebaseExtended/flutterfire#2047]
**Description**
I can't build my android app for release, because mindSDK in plugin is just 16 and not androidX compatible.

**To Reproduce**
1. flutter run --release

**Expected behavior**
I can build a release android app

**Additional context**
```bash
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
```

**Comment by Ahmadre** [comment]
Someone here to help?...

**Comment by Ahmadre** [comment]
Nevermind. I solved it on my own yet. I will use my own fork

**Comment by mikron123** [comment]
What was the solution?

**Comment by Ahmadre** [comment]
@mikron123 set minimum api level to 21 and target api to 28 like always. it's just a little thing
