### ISSUE TITLE
firebase_messaging onIosSettingsRegistered does not work

### ISSUE THREAD

**Issue by jcsena** [FirebaseExtended/flutterfire#205]
**Describe the bug**
firebase_messaging ```onIosSettingsRegistered```does not work

**To Reproduce**
I have activated the notifications and in ios correctly. I manage to request permissions and correctly and I can register the topics and get the token after having accepted the PN, however, the ```onIosSettingsRegistered``` event is also not fired.

**Expected behavior**
related Pull request [https://github.com/FirebaseExtended/flutterfire/pull/20](https://github.com/FirebaseExtended/flutterfire/pull/20)

**Comment by Ehesp** [comment]
Hi @jcsena please could you try on the latest versions of the plugin. Going to close this due to it's age & inactivity. 

Please create a new issue with reproduction code if the problem still persists after upgrading.
