### ISSUE TITLE
[firebase_messaging] web support

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [FirebaseExtended/flutterfire#2059]
Firebase Messaging is awesome as it supports iOS, Android AND Web. Flutter for Web is growing rapidly so having push notification support in Flutter Web from a single plugin that also supports iOS and Android would be a game change. Any plans, roadmaps?

**Comment by AndroidNils** [comment]
There is already a ticket in the Flutter git repo: https://github.com/flutter/flutter/issues/45300

You can see the process of all the other firebase plugins for web here: https://github.com/flutter/flutter/projects/69

Don't ask me, why they created it in the Flutter git repo and not here in `FirebaseExtended` 🤷‍♂️

**Comment by iapicca** [comment]
Hi @TobiasHeidingsfeld 
as @AndroidNils pointed out (thanks)
there's an open issue addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
