### ISSUE TITLE
[firebase_remote_config] When FetchThrottledException is thrown, `throttleEnd` time is negative

### ISSUE THREAD

**Issue by readytopark** [FirebaseExtended/flutterfire#206]
**Describe the bug**
When calling fetch() many times with very low duration such as 1 minute in a production build, I get FetchThrottledException with negative `throttleEnd` value. So I get the exception message such as "Fetching throttled, try again in -14393922032 milliseconds"

**To Reproduce**
1. Pass a low value(such as 1 minute) to `fetch()`
2. Call fetch many times within the specified expiration duration.
4. See logging message from the `FetchThrottledException`

**Expected behavior**
`throttleEnd` from `FetchThrottledException` should be positive.

**Comment by Salakar** [comment]
Given the age of this issue and that Remote Config has had a major rework since; I'm going to close this issue in favour of trying the latest release
