### ISSUE TITLE
[all] Federating FlutterFire platform interface technical debt

### ISSUE THREAD

**Issue by collinjackson** [FirebaseExtended/flutterfire#2064]
This issue is a centralized place to note things that aren't ideal about the way things are done, but that we're leaving in place for now, either because we don't have time or to avoid breaking changes in platform interfaces. If we do  platform interface breaking changes in the future we should consider addressing these.

- [x] [cloud_firestore] `FieldValuePlatform.verifyExtends` is deprecated
- [x] [cloud_firestore] `FieldValueFactoryPlatform` is using dynamic instead of generics
- [x] [firebase_auth] `FirebaseAuthPlatform` is using `isMock` https://github.com/FirebaseExtended/flutterfire/issues/1939
- [x] [firebase_core] `firebase_core_platform_interface` package should use `PlatformInterface` https://github.com/FirebaseExtended/flutterfire/issues/1940

When encountering additional platform interface technical debt, consider linking to this issue.

**Comment by ditman** [comment]
This is great, thanks @collinjackson!!

**Comment by Salakar** [comment]
This has since been resolved, thanks everyone.
