### ISSUE TITLE
[cloud_firestore] retainWhere broken for List<DocumentSnapshot>

### ISSUE THREAD

**Issue by leetworx** [FirebaseExtended/flutterfire#2066]
**Describe the bug**
Upon receiving the QuerySnapshots from a collection query, I want to drop those results that don't match certain filter criteria. Previously I did this with retainWhere (pre version 0.13.1) however upon updating to 0.13.4 I've found that this no longer works.

**To Reproduce**
Consider the following code snippet:

```
return StreamBuilder(
        stream: Firestore.instance
            .collection('...')
            .snapshots(),
        builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
          if (snapshot.hasData || snapshot.data != null) {

            print('pre-processing doc count: ${snapshot.data.documents.length}');

            // filter documents
            snapshot.data.documents.retainWhere((DocumentSnapshot snap) {
                // some condition under which we want to keep docs
                if (...) {
                   print('keeping this one...');
                   return true;
                }
                // some condition under which we want to discard
                if (...) {
                   print('dropping this one...');
                   return false;
                }
            });

            print('post-processing doc count: ${snapshot.data.documents.length}');
          }

```

**Expected behaviour**
Debug & print statements validate that we are hitting both cases (keep and drop) and returning the respective boolean values, however the pre and post processing doc count in the returned collection is always  the same (all are retained).

**Comment by iapicca** [comment]
Hi @leetworx 
could you please provide a sample of your implementation of [retainWhere](https://api.flutter.dev/flutter/dart-core/List/retainWhere.html)
together with your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by leetworx** [comment]
Hi @iapicca - the implementation is in comment #1. Note specifically the use case where 'retainWhere' is being used on a list of documents having been turned from a query on a collection - i.e.

// filter documents
snapshot.data.documents.retainWhere((DocumentSnapshot snap) {
   ...
[run.log](https://github.com/FirebaseExtended/flutterfire/files/4309698/run.log)
});

flutter doctor -v
============
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.5 18F132, locale en-CA)
    • Flutter version 1.12.13+hotfix.7 at /Users/leet/development/flutter
    • Framework revision 9f5ff2306b (6 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/leet/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/leet/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Todd’s iPhone • ecd4a0dcdaacabca34d6d580f6e8a10de6ebeaca • ios • iOS 10.3.3

! Doctor found issues in 1 category.

Flutter/firebase related info from pubspec.yaml
==================================
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.13.4

  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+3
  firebase_dynamic_links: ^0.5.0+9
  firebase_performance: ^0.3.1+5
  firebase_remote_config: ^0.3.0+1
  firebase_messaging: ^6.0.9

**Comment by awhitford** [comment]
My understanding is that you can't define the stream inside `StreamBuilder`.
I tend to use a [`StreamController`](https://api.flutter.dev/flutter/dart-async/StreamController-class.html).
Often `initState` will trigger a query subscription, then a processor will send updates to the StreamController using `add`.
The `StreamBuilder` uses the stream from the `StreamController`, like:

For example:
```dart
  final _statusController = StreamController<Payload>();
...
  Widget build(BuildContext context) {
    return StreamBuilder(
          stream: _statusController.stream,
          builder: (BuildContext context, AsyncSnapshot<Payload> snapshot) {
```

**Comment by leetworx** [comment]
@awhitford - not sure what you're referring to w.r.t the restriction on where/how the stream is defined. Is the behaviour you're describing documented somewhere? If so, any pointers would be most helpful as I know that the implementation that I outlined in the initial comment worked perfectly pre version 0.13.1 (so presumably this would be a new limitation?)

**Comment by awhitford** [comment]
It is well documented for [FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html):

> The future must have been obtained earlier, e.g. during State.initState, State.didUpdateConfig, or State.didChangeDependencies. It must not be created during the State.build or StatelessWidget.build method call when constructing the FutureBuilder. If the future is created at the same time as the FutureBuilder, then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.

I tried finding the same advice/guidance for `StreamBuilder`, but it admittedly does not seem to be well documented.  However, if you look at `StreamBuilder` examples all over, you can see that the `Stream` lifecycle is independent of the `StreamBuilder`.  I recommend applying the `FutureBuilder` advice to `StreamBuilder`.

Hope this helps!

**Comment by kirstywilliams** [comment]
Hey @leetworx I'm reviewing issues, does @awhitford's solution work for you for now?

**Comment by Ehesp** [comment]
Closing - `retainWhere` modifies the existing List, which you shouldn't be doing. Try iterating over the data and adding your own items to a list if they match your use-case.
