### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by tesissoftware** [FirebaseExtended/flutterfire#2071]
grpc_impl::internal::AlarmImpl::AlarmImpl() in alarm.o
      "_grpc_alts_credentials_server_options_create", referenced from:
          grpc_impl::experimental::AltsServerCredentials(grpc_impl::experimental::AltsServerCredentialsOptions const&) in secure_server_credentials.o
      "_grpc_resource_quota_unref", referenced from:
          grpc_impl::ResourceQuota::~ResourceQuota() in resource_quota_cc.o
          grpc_impl::ServerBuilder::~ServerBuilder() in server_builder.o
          grpc_impl::ServerBuilder::SetResourceQuota(grpc_impl::ResourceQuota const&) in server_builder.o
          grpc_impl::Server::Server(int, grpc_impl::ChannelArguments*, std::__1::shared_ptr<std::__1::vector<std::__1::unique_ptr<grpc_impl::ServerCompletionQueue, std::__1::default_delete<grpc_impl::ServerCompletionQueue> >, std::__1::allocator<std::__1::unique_ptr<grpc_impl::ServerCompletionQueue, std::__1::default_delete<grpc_impl::ServerCompletionQueue> > > > >, int, int, int, grpc_resource_quota*, std::__1::vector<std::__1::unique_ptr<grpc::experimental::ServerInterceptorFactoryInterface, std::__1::default_delete<grpc::experimental::ServerInterceptorFactoryInterface> >, std::__1::allocator<std::__1::unique_ptr<grpc::experimental::ServerInterceptorFactoryInterface, std::__1::default_delete<grpc::experimental::ServerInterceptorFactoryInterface> > > >) in server_cc.o
      "grpc_timer_init_unset(grpc_timer*)", referenced from:
          grpc_impl::internal::AlarmImpl::AlarmImpl() in alarm.o
      "_grpc_slice_split_head", referenced from:
          grpc::CoreCodegen::grpc_slice_split_head(grpc_slice*, unsigned long) in core_codegen.o
      "_gpr_log", referenced from:
          grpc_impl::internal::AlarmImpl::Set(grpc_impl::CompletionQueue*, gpr_timespec, void*) in alarm.o
          grpc_core::ApplicationCallbackExecCtx::~ApplicationCallbackExecCtx() in alarm.o
          grpc_impl::ChannelArguments::ChannelArguments(grpc_impl::ChannelArguments const&) in channel_arguments.o
          grpc_impl::ChannelArguments::SetSocketMutator(grpc_socket_mutator*) in channel_arguments.o
          grpc_impl::ChannelArguments::SetUserAgentPrefix(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in channel_arguments.o
          grpc_impl::Channel::WaitForStateChangeImpl(grpc_connectivity_state, gpr_timespec) in channel_cc.o
          grpc::ClientContext::set_call(grpc_call*, std::__1::shared_ptr<grpc_impl::Channel> const&) in client_context.o
          ...
      "_grpc_resource_quota_arg_vtable", referenced from:
          grpc_impl::ChannelArguments::SetResourceQuota(grpc_impl::ResourceQuota const&) in channel_arguments.o
          grpc_impl::ServerBuilder::BuildAndStart() in server_builder.o
      "_grpc_alts_credentials_create", referenced from:
          grpc_impl::experimental::AltsCredentials(grpc_impl::experimental::AltsCredentialsOptions const&) in secure_credentials.o
      "_grpc_slice_ref", referenced from:
          grpc::CoreCodegen::grpc_slice_ref(grpc_slice) in core_codegen.o
      "_gpr_cpu_num_cores", referenced from:
          grpc::(anonymous namespace)::CreateDefaultThreadPoolImpl() in create_default_thread_pool.o
      "grpc_timespec_to_millis_round_up(gpr_timespec)", referenced from:
          grpc_impl::internal::AlarmImpl::Set(grpc_impl::CompletionQueue*, gpr_timespec, void*) in alarm.o
          grpc_impl::internal::AlarmImpl::Set(gpr_timespec, std::__1::function<void (bool)>) in alarm.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Comment by iapicca** [comment]
Hi @tesissoftware 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by juan-c-s** [comment]
I have the same error message, What can I do?

**Comment by juan-c-s** [comment]
It works for android but not for iOS

**Comment by juan-c-s** [comment]
![Screen Shot 2020-04-15 at 3 32 08 PM](https://user-images.githubusercontent.com/63207344/79385488-47ea9300-7f2e-11ea-8c18-c6831c7daa8d.png)

**Comment by juan-c-s** [comment]
![Screen Shot 2020-04-15 at 4 08 33 PM](https://user-images.githubusercontent.com/63207344/79388684-5dae8700-7f33-11ea-8e34-9d240d7fd157.png)

**Comment by iapicca** [comment]
Hi @juan-c-s 
your` flutter doctor -v ` and 
your `flutter build ios --verbose`
are both incomplete please provide them in full length
you may attach it as txt file
Please refrain from posting pictures if not necessary.
thank you

**Comment by juan-c-s** [comment]
> Hi @juan-c-s
> your`flutter doctor -v` and
> your `flutter build ios --verbose`
> are both incomplete please provide them in full length
> you may attach it as txt file
> Please refrain from posting pictures if not necessary.
> thank you

Just solved the problem. It was a problem in Xcode that I needed to add a line of code to use google-sign-in but thanks!
