### ISSUE TITLE
SignIn Anonymously plugin exception

### ISSUE THREAD

**Issue by Traitor00** [FirebaseExtended/flutterfire#2075]
Isn't there support for Annoymously login in this version. I am getting folllowing error

 MissingPluginException(No implementation found for method signInAnonymously on channel plugins.flutter.io/firebase_auth)

**Comment by iapicca** [comment]
Hi @Traitor00 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by Ehesp** [comment]
Closing this off, support for anonymous auth is supported: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart#L40
