### ISSUE TITLE
no otp receive 

### ISSUE THREAD

**Issue by motorahul** [FirebaseExtended/flutterfire#2085]
In chrome web browser i update all  configurations in index.html file 
complete setup in firebase console according to flutter authentication library
but still didnot receive any otp 
didnot get any error or bug

**Comment by iapicca** [comment]
Hi @motorahul 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @motorahul 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
