### ISSUE TITLE
[firebase_messaging] How to use FirebaseMessaging with secondary FirebaseApp

### ISSUE THREAD

**Issue by timosturm** [FirebaseExtended/flutterfire#2086]
**Is your feature request related to a problem? Please describe.**
I want to use fcm notifications in my application, therefor I need to configure Firebase at runtime. But as it seems `FirebaseMessaging` will always attempt to use a default firebase app. Configuring firebase with `FirebaseApp` from firebase_core does not seem to work, leading to an error: 

```
E/MethodChannel#plugins.flutter.io/firebase_messaging( 6934): java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.my_app. Make sure to call FirebaseApp.initializeApp(Context) first.
```

Also it is not possible to configure the "default firebase app" with firebase_core:

```
  /// Configures an app with the given [name] and [options].
  ///
  /// Configuring the default app is not currently supported. Plugins that
  /// can interact with the default app should configure it automatically at
  /// plugin registration time.
  ///
  /// Changing the options of a configured app is not supported.
  static Future<FirebaseApp> configure({
...
```

**Describe the solution you'd like**
Some way to tell firebase messaging to use a firebase app that was initialized with firebase core.

**Comment by Ehesp** [comment]
Hello - unfortunately this is not possible. Messaging can only work with the default app (native SDK limitation), so this is why there is no way to change it on the messaging plugin.
