### ISSUE TITLE
[firebase_auth] List compatible/recommended plugins for various providers

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#2089]
I am trying to setup various **Sign-in providers** with `Firebase_Auth` and am finding the documentation to be insufficient.

I first setup **Google** successfully because the documentation is very good.  Good job! :clap:  Note that in addition to `firebase_auth`, one needs to also use [google_sign_in](https://pub.dev/packages/google_sign_in).

Next, I moved on to **Facebook**, and I think I can see how to transform the Google example to match Facebook.  However, I still haven't gotten this working due to a [Facebook issue](https://developers.facebook.com/support/bugs/2639940609572252/) -- but that is on them.  Note that it appears I need to use [flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login).

Next, I moved on to **Twitter**, and am running into a [wall](https://stackoverflow.com/questions/60461547/how-to-sign-in-with-twitter-using-firebase-auth-with-flutter) because both [flutter_twitter_login](https://pub.dev/packages/flutter_twitter_login) and [flutter_twitter](https://pub.dev/packages/flutter_twitter) use the [deprecated Twitter Kit SDK](https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html).  What is the current recommendation here that will not lead to [Apple Store Rejection](https://github.com/roughike/flutter_twitter_login/issues/19)?

I naively thought that `firebase_auth` contained all the magic to connect to the various social _Sign In_ providers.  However, it appears that it still requires third party plugins -- but the curated list of these plugins are not part of the documentation, except for Google.

Finally, I plan to attempt adding **Sign In with Apple ID** because [new apps submitted to the App Store must also offer Sign in with Apple as an equivalent option](https://developer.apple.com/news/?id=09122019b).

I would like to see a curated list of the plugins required to actually connect to the various _Sign In providers_, and/or better documentation and sample code.

Specifically, improving documentation for Apple ID is important so that Flutter apps can abide by Apple App Store policies.

**Comment by helenaford** [comment]
closing this and consolidating under  #442.
