### ISSUE TITLE
[Auth] Encrypt user profile/token data while at rest

### ISSUE THREAD

**Issue by acoutts** [FirebaseExtended/flutterfire#2090]
User data including access token is persisted on the device at rest. We can access the existing user data by calling the following:

```dart
FirebaseAuth.instance.currentUser()
```

But I cannot find any information in the documentation about where this data is persisted. When you clear the app storage, this data is reset and there is no user to access anymore. How is this data persisted now, and can it be customized?

- Is it stored in shared preferences in plaintext?
- Is it stored in the secure enclave (and if no secure enclave is available, then where)?
- Can we encrypt the data with a password/pin/key before it's persisted so it's safe while at rest?

In rooted / jailbroken devices, other applications can access the data stored in plain text. The risk is a user's token could be stolen unless there is a way to store it encrypted or in a secure enclave.

**Comment by Ehesp** [comment]
This question would be better placed on the android/ios repositories for Firebase, since FlutterFire uses them behind the scenes. I'll leave open to discuss though.
