### ISSUE TITLE
[firebase_auth] Provide support for all of firebase's providers

### ISSUE THREAD

**Issue by franck-noahk** [FirebaseExtended/flutterfire#2092]
I am trying to take advantage of all of the resources of Firebase auth in my **flutter** app, but it is frustrating because there is no way to use Apple, Microsoft, or Yahoo sign in.

I would love it if a developer would implement the different providers in the native dart code.

This is a repeat of [firebase_auth - Other provider logins #728](https://github.com/FirebaseExtended/flutterfire/issues/728 ) and [firebase_auth - Other provider logins #20092](https://github.com/flutter/flutter/issues/20092), but these were both closed on the same day saying that future work would be done on the opposite issue. I am not sure if I missed an issue or a blog post but I didn't see where the current state of adding additional providers was for flutter fire.

**Comment by awhitford** [comment]
This might help you for Apple:  https://github.com/tomgilder/flutter_apple_sign_in

**Comment by franck-noahk** [comment]
@awhitford I think that this would help someone using a database in the AWS or Azure, but if they are using firebase Firestore or RealtimeDB I am not sure if the user's UUID for their data either database would be accessible. 

This is an interesting thought that I will look into over the next 36 hours.

**Comment by awhitford** [comment]
I was able to successfully roll my own **Apple Sign In** using [apple_sign_in](https://pub.dev/packages/apple_sign_in) and FirebaseAuth's `OAuthProvider`.  It is possible and a little googling that point you in the right direction.

* https://medium.com/@karlwhiteprivate/flutter-firebase-sign-in-with-apple-c99967df142f
* https://firebase.google.com/docs/auth/ios/apple

I don't understand your comment about database.  Authentication doesn't really have any database requirements.  You likely need to manage your own `User` records -- but you can use whatever you want.  Personally, I'm using `Cloud Firestore`.  Firebase Auth will give you a `uid` to be the key for the user.

**Comment by franck-noahk** [comment]
Sorry for the miscommunication. What I was trying to get at was Firebase gives you a `uid` but I didn't think signing in with a third party would give you one. And I usually use `users/uid` as a document for users' data to be stored. I haven't had time to try out the plugin you sent but if third-party plugins that have support for signing-in work with Firebase Auth that is very good to know. 

The concern that I had was that Flutter users should be able to use all of the Firebase Auth providers without having to add additional plugins.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this feature is still missing for you? If it is then please submit a new up to date GitHub issue explaining what's missing on the updated plugins.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
