### ISSUE TITLE
i am unable to receive push notification in ios

### ISSUE THREAD

**Issue by urvashikharecha** [FirebaseExtended/flutterfire#2094]
i am unable to receive push notification in ios using this plugin please review my question in below link ::
help wanted 

https://stackoverflow.com/questions/60473357/push-notification-not-coming-in-ios-device-using-flutter

**Comment by iapicca** [comment]
Hi @urvashikharecha 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @urvashikharecha 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
