### ISSUE TITLE
[firebase_auth] Token Expired: PlatformException, and refresh it

### ISSUE THREAD

**Issue by dekadevelop** [FirebaseExtended/flutterfire#2096]
Hi,

If I leave the app in the background the open it again after about 1h, it seems that the firebase token is expired.
The problem is that there is no actual way to define this case, as a PlatformException is fired, but this is more kind of a generic firebase exception, so I can't use it to recognise if the token is expired.
Ho can we handle this case? 

And also if i try to refresh the token with _fireBaseUser.getIdToken(refresh: true), I get an Exception.

Ho can we refresh the token properly?

possible solutions:
get a TokenExipredException,

and redirect to the login page;
or
refresh the token without even bother the user

**Comment by Ehesp** [comment]
Tracking; `onTokenRefresh` is missing

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

Please could you update to the new version as subscribing to id token changes is now supported. If you have any problems with this feature or the updated plugins please raise a new GitHub issue.

See: https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/idTokenChanges.html

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
