### ISSUE TITLE
[firebase_dynamic_links] Error - Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by AJearyzhe** [FirebaseExtended/flutterfire#210]
**Error when trying to compile on ios**

The error I get is:
> Property with 'retain (or strong)' attribute must be of object type

<img width="1021" alt="Screenshot 2019-09-24 at 19 48 08" src="https://user-images.githubusercontent.com/55593746/65536981-ae618280-df04-11e9-838d-227bce8541df.png">

**Comment by sgalway00** [comment]
Any resolution to this?  I have the exact same issue.

**Comment by helenaford** [comment]
Hi @AJearyzhe and @sgalway00, 
Please can you give more information if you are still experiencing this issue
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated `flutter doctor -v`
and your `flutter run --verbose/flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you
