### ISSUE TITLE
[firebase_messaging] Firebase push notification is not popup on the screen

### ISSUE THREAD

**Issue by Hetal2011** [FirebaseExtended/flutterfire#2100]
**Flutter heads up notification**

I am trying to implement firebase push notifications for a flutter app.
But it appears just as an icon in the status bar. How can I make it pop up?
I want popup on the screen when notification is received.

**Comment by iapicca** [comment]
Hi @Hetal2011 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and reproducible minimal code sample.
Thank you

**Comment by naveen-krishna** [comment]
any updates?

**Comment by iapicca** [comment]
Hi @naveen-krishna 
could you please provide the information listed [above](https://github.com/FirebaseExtended/flutterfire/issues/2100#issuecomment-596546960)
Thank you
