### ISSUE TITLE
[firebase_analytics] DebugView for iOS not catching events

### ISSUE THREAD

**Issue by HartP97** [FirebaseExtended/flutterfire#2108]
### **Bug Description**
I currently only have **firebase_core: 0.4.3+3** and **firebase_analytics: ^5.0.11** included in my Flutter-project. Firebase is recognizing my App as soon as I start it for both Android and iOS. I set up some test-events to track. Under the menu item "DebugView" on the Firebase page it tracks all of those just fine for Android. Still, for iOS it is not showing anything in "DebugView", just in the "Project Overview", that a device got connected.

### **What I've tried:**
Enabling DebugMode for iOS by adding both: **-FIRDebugEnabled** and **-FIRAnalyticsDebugEnabled** to **Product > Scheme > Edit Scheme...** I also tried them separately from another.

### **Expected behavior**
Debug-Events should show up in the DebugView, just as they do for Android.

### **Additional context**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.15.2 19C57, locale en-DE)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.6)
> [✓] Connected device (1 available)
> 
> • No issues found!

**Comment by snaeji** [comment]
Same issue here...

**Comment by snaeji** [comment]
I did a pod update on the firebase analytics module in the ios/ folder and it worked right away. Could have been a coincidence but worth the try.

**Comment by blasko** [comment]
Same issue with the latest Firebase packages:
(works from Xcode, not from the CLI or IntelliJ)
```
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
  firebase_core: ^0.5.0+1
```

**Comment by TheVinhLuong** [comment]
Try to build the project by Xcode directly. It works for me.

**Comment by blasko** [comment]
@TheVinhLuong That works, yes. But that's not solving the issue.

**Comment by brenoasm** [comment]
Does the device shows up for selection for you? I already have done everything multiple times and, even the logs Tell me that everything started well, my simulator does not show for selection.
