### ISSUE TITLE
[cloud_firestore] disable network for client (enableNetwork / disableNetwork)

### ISSUE THREAD

**Issue by EmilHW** [FirebaseExtended/flutterfire#211]
**Is your feature request related to a problem? Please describe.**
I would like to be able to disable a clients network for the cloud_firestore (Like it is possible for the java android  version, and other languages. https://firebase.google.com/docs/firestore/manage-data/enable-offline). I would like this possibility, because i would like to have a client that can use the cloud_firestore functionality, but without uploading their data to the cloud, before they purchase the full version of my application. So that when they purchase the full version, then i would simply reenable the network and all data would be synced.

**Describe the solution you'd like**
The solution should be the one similar to the java android implementation, with the following methods for the instance of Firestore:
disableNetwork() which should disable the network.
enableNetwork() which should enable the network.

**Additional context**
The documentation that i am refering to when i say the java implementation:
![java](https://user-images.githubusercontent.com/22076878/65543056-a7407180-df10-11e9-8ba8-790ed338ceda.PNG)

**Comment by gkumarau** [comment]
I believe this feature is very important for firestore. Any idea when the feature will be released?

**Comment by Ehesp** [comment]
Will be supported as part of #2582

**Comment by Salakar** [comment]
Hey all, as part of our on-going work for #2582, this has been implemented in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
