### ISSUE TITLE
[firebase_crashlytics] Flutter errors not being reported in a release version

### ISSUE THREAD

**Issue by dpioempx** [FirebaseExtended/flutterfire#2114]
Firebase Crashlytics reports it's  test crash but doesn't report Flutter error in a release version.

Both debug and release version properly report this one:
```
Crashlytics crashy = Crashlytics();
crashy.crash();
```
But the one below is being reported only in a debug mode, not in a release version of the Flutter app. This is couple of lines of the Flutter error that debug versions report properly:

`Non-fatal Exception: java.lang.Exception
Duplicate GlobalKey detected in widget tree. The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was: - [LabeledGlobalKey<FormState>#a31f3 [...]
`

Initialization is pretty standard: 
```
void main() {
  Crashlytics.instance.enableInDevMode = true;
  FlutterError.onError = Crashlytics.instance.recordFlutterError;
  runZoned<Future<void>>(() async {
    runApp(MyApp());
  }, onError: Crashlytics.instance.recordError);
}
```
Any ideas are welcomed, I'm having hard time figuring this one out. As far as I can tell it works that way on both iOS and Android but I'm focusing on Android here.

**Comment by britannio** [comment]
@dpioempx Did you fix it? What was the cause?

**Comment by dpioempx** [comment]
I didn't fix it. Crashlytics reports Non-Fatals from a production environment now but not this particular  bug.
