### ISSUE TITLE
[remote_config] Support for Flutter Web

### ISSUE THREAD

**Issue by red010b37** [FirebaseExtended/flutterfire#2115]
Currently there is no support for Flutter Web

Remote Config is a Key firebase feature that should be cross platform supported.

**Comment by Viacheslav-Romanov** [comment]
Can you assign someone on this, guys? Thanks.

**Comment by Ehesp** [comment]
This is planned, but is not currently being worked on. We'll update the roadmap #2582 with more information when applicable.

**Comment by tungtrinh** [comment]
> This is planned, but is not currently being worked on. We'll update the roadmap #2582 with more information when applicable.

Could you please give us update on this. As I can see flutter fire implementation for web is making huge progress but this has no mention at all.
