### ISSUE TITLE
[firebase_admob] Repeated log message output for banner advertisement (D / eglCodecCommon (30389): setVertexArrayObject: set vao to...)

### ISSUE THREAD

**Issue by exptk3** [FirebaseExtended/flutterfire#2123]
**Describe the bug**
Same as the title.
When showing banner ads, the following unnecessary log messages are repeatedly printed, making it difficult to see other logs, which puts a lot of load on the computer.

...
D/eglCodecCommon(30389): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon(30389): setVertexArrayObject: set vao to 1 (1) 1 6
…
…
D/eglCodecCommon(30389): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon(30389): setVertexArrayObject: set vao to 1 (1) 1 6
D/eglCodecCommon(30389): setVertexArrayObject: set vao to 0 (0) 1 2
...

**To Reproduce**
This problem occurs after upgrading the flutter sdk version (fv1.12.13 + hotfix.7 —> v1.12.13 + hotfix.8). It did not occur in hotfix.7. In fact, when I changed to hotfix.7, the logs were not printed.

*** Minor changes to the above post
The above bug report had some problems during the testing process. The version of the bug above was the v1.15.x version of the master channel.
So I came back to the stable channel and tested it.
Logs that were not shown in 'v.1.12.13 - Hotfix 7'  were printed  in Hotfix 8, but are not unusually severe as in the master channel, and they appear to be logged whenever the banner ad changes.
This bug also makes other logs difficult to be seen.
It would be nice to have these logs, which are repeated every time the ad loads, disappear as before (Hotfix 7).
Thank you.

**Comment by LiveRock** [comment]
I am having the exact same problem. Any solutions?

**Comment by galloperx** [comment]
Same issue, all the latest updates. Log is impossible to read with this constant spam.
To replicate the issue do this: create new flutter project, configure it to show a test banned ad with firebase_admob package (currently my pubspec.yaml has it as "firebase_admob: ^0.9.3+4"), see the banner in emulator - see the spam in console.
Flutter version 1.17+

Seeing this for the last few months is becoming really annoying.

**Comment by refoxdev** [comment]
Same issue!

**Comment by virskor** [comment]
Same

**Comment by fschlosser** [comment]
same ...
