### ISSUE TITLE
[firebase_admob] Call AdView lifecycle methods in Android activity lifecycle callbacks

### ISSUE THREAD

**Issue by bparrishMines** [FirebaseExtended/flutterfire#2124]
It's not clear in the [AdView](https://developers.google.com/android/reference/com/google/android/gms/ads/AdView)  documentation about when to call `destroy()`, `resume()`, or `pause()`. Their documentation only states that they should be called in their respective Activity method. (e.g. adview.pause() called in activity.onPause()), but we have only been calling `destroy()` in the `dispose()` method.

I should also note that neither Banner, Interstitial, or Native ads examples talk about using these.
https://developers.google.com/admob/android/banner.

We should investigate if calling these methods is recommended and if so, support activity lifecycles in the Android Admob implementation.

**Comment by bparrishMines** [comment]
First discussion: https://github.com/FirebaseExtended/flutterfire/pull/169#discussion_r386658814

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
