### ISSUE TITLE
Improper text detection in ios.

### ISSUE THREAD

**Issue by KishorP18** [FirebaseExtended/flutterfire#2126]
I am using firebase_ml_vision package for text scanning on both android and ios.It works properly
on android but incase of ios the text detection is incorrect.

![Screenshot 2020-03-05 at 3 56 01 PM](https://user-images.githubusercontent.com/31824635/75974342-9d2d9080-5efc-11ea-9a1f-0590a116dfc3.png)

**Comment by iapicca** [comment]
Hi @KishorP18 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by KishorP18** [comment]
I was able solve this problem with  workaround.
