### ISSUE TITLE
[firebase_storage] StorageMetadata updatedTimeMillis overflow

### ISSUE THREAD

**Issue by cmkweber** [FirebaseExtended/flutterfire#2127]
On 32bit systems (such as lower end android tablets and earlier generation iPads) updatedTimeMillis is utilizing 32bit integers and returning 2147483647. These values would need to be stored in at least a 64bit integer (long long) since they are in milliseconds. My guess is this is also happening for creationTimeMillis but I haven't tested this.

A potential workaround in our case to determine if the file has changed would be to use:
[https://pub.dev/documentation/firebase_storage/latest/firebase_storage/StorageMetadata/generation.html](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/StorageMetadata/generation.html)

But is that referring to:
[getGeneration](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageMetadata#getGeneration())
or:
[getMetadataGeneration](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageMetadata#getMetadataGeneration())

**Comment by Salakar** [comment]
This should be ok now on the latest version. Please raise a new issue with up to date information and flutter doctor output if you still face this problem. Thanks
