### ISSUE TITLE
[firebase_crashlytics]  Should not use platform channels, dart port?

### ISSUE THREAD

**Issue by charafau** [FirebaseExtended/flutterfire#2133]
Since all firebase plugins are open source now, it seems good to have dart port and dont backport to platform channels? 

That way plugin would have more control over logic and it would resolve problems like implementing android-ndk in plugin, one could add crashlytics to native platform if needed.

Code for native android https://github.com/firebase/firebase-android-sdk/tree/master/firebase-crashlytics

**Comment by Ehesp** [comment]
Hi @charafau - the plugins use the underlying Firebase SDKs which are built from the open sourced SDKs. It's also worth noting not all features have been open sourced yet either.

I'll close this one off to reduce noise - however if you feel like I have the wrong end of the stick, please let me know!
