### ISSUE TITLE
[firebase_messaging] App not receiving push data when launched from background

### ISSUE THREAD

**Issue by Omaryasirm** [FirebaseExtended/flutterfire#2136]
On Android and ios push works as expected but only issue I'm facing is when a notification is sent with notification and data field while the app is running in the background I receive the notification in the notification drawer as expected, but when I reopen the app I don't receive any data. This scenario I just described happens with combined notification and data field push but if I only send data field push then I get the desired behaviour. Not sure if this is a bug or how it's supposed to work?

While I wait for a response I'm going to change the way I send push by sending 2 separate push, one with notification field and one with data field instead of combined push.

I'm using firebase_messaging: 6.0.12

**Comment by AndroidNils** [comment]
Same issue!

Data from `firebase_messaging`:

- App is open: `on message {notification: {title: test, body: asdfsdaf}, data: {message_id: notification-dialog, click_action: FLUTTER_NOTIFICATION_CLICK}}`

- Notification was launched from background: `on resume {notification: {}, data: {collapse_key: de.domain.app, google.original_priority: high, google.sent_time: 1583699908538, google.delivered_priority: high, google.ttl: 2419200, message_id: notification-dialog, from: 366164701221, click_action: FLUTTER_NOTIFICATION_CLICK, google.message_id: 0:1583699908553343%e07e47e3e07e47e3}}`

It was the same push notification (sent with Firebase Console). You can see that the `notification` map is empty, when the notification launched from background.

**Comment by iapicca** [comment]
Hi @Omaryasirm 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1763) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
