### ISSUE TITLE
[Firebase RealTime Database] Write to the database of another firebase project?

### ISSUE THREAD

**Issue by shikharvaish28** [FirebaseExtended/flutterfire#2137]
I have two apps, Rider and Driver with firebase projects named as `rider` and `captain` respectively. I am trying to access the `captain firebase database`(which contains the driver's location) from the Rider's flutter app and use [flutter geo-query](https://pub.dev/packages/flutter_geofire) in it. Flutter geo-query plugin uses the android's [GeoFire Api](https://github.com/googlearchive/geofire)

When I am writing to the driver's database from the rider app using ```.set()```, the database is updated but, when I try to update using the ```Geofire.setLocation```, the original database i.e. rider's database gets updated instead of the driver's database.

The code is as follows:

```
Future<FirebaseDatabase> _CaptainsFirebase() async {

    FirebaseApp captain = await FirebaseApp.configure(
        name: 'bob-captain',
        options: const FirebaseOptions(
          apiKey: '',
          googleAppID: '',
          databaseURL: '',
          clientID:
              '',
          projectID: '',
        ));

    FirebaseDatabase captainsFirebase = new FirebaseDatabase(app: captain);
    String pathToReference = '';

    await Geofire.initialize(pathToReference);

// The below like on contrary writes to the Rider Database in spite of initialising it to the captain's database

    bool response =
        await Geofire.setLocation(widget.user.uid, 19.29139421, 73.2919019);

// The code below successfully writes to the captain's database in Firebase(as expected)

//    captainsFirebase
//        .reference()
//        .child("captainAvailable/$vehicalName/${widget.user.uid}")
//        .set({
//      'vehical_number': 'UP',
//      'vehical_model': 'Ace',
//    });

    print("Response = $response");

    return FirebaseDatabase(app: captain);
  }
}
```
Code for `Geofire.setLocation` is as follows:
```
  static Future<bool> initialize(String path) async {
    final dynamic r = await _channel
        .invokeMethod('GeoFire.start', <String, dynamic>{"path": path});
    return r ?? false;
  }
```

**Comment by Ehesp** [comment]
Hi @shikharvaish28 - Database supports multiple apps by passing the instance created into the constructor. 

The issue you're having is related to the Geofire not using the secondary instance. I'd suggest creating an issue on that repository asking how multiple app instances can be supported.
