### ISSUE TITLE
[firebase_auth] FirebaseUser email is empty after force quit on android for signInWithCredential

### ISSUE THREAD

**Issue by dcoleyoung** [FirebaseExtended/flutterfire#214]
When an android user who has signed in with signInWithCredential force quits then reloads the app, the FirebaseUser associated email is null

Steps to reproduce the behavior on (physical device only):
1. Sign in with signInWithCredential (Google or Facebook) on Android device (tested on S9, Pixel)
```
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;
```
2. Force quit 
3. Reload the app
4. User is logged in but FirebaseUser email is null

**Expected behavior**
User should be remained logged in and FirebaseAuth.instance.currentUser() email preserved with access to FirebaseUser email

**Additional context**
This is Android-specific, and specific to signInWithCredential, not happening for signInWithEmailAndPassword

  firebase_auth: ^0.14.0+5

**Comment by dcoleyoung** [comment]
Flutter doctor:

[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/dcoleyoung/development/flutter
    • Framework revision b712a172f9 (3 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dcoleyoung/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

**Comment by dcoleyoung** [comment]
I discovered the source of the issue.  After a force quit, the FirebaseUser object has an empty string '' for email rather than null (preforce quit / timeout).

**Comment by Ehesp** [comment]
This is by design, you need to be listening to https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/onAuthStateChanged.html - when your app boots, the auth service may not have initialised yet.
