### ISSUE TITLE
[firebase_auth] Cannot build for MacOS

### ISSUE THREAD

**Issue by PieterAelse** [FirebaseExtended/flutterfire#2140]
When building my app for MacOS using firebase_auth 15.5.+2 (latest) I get a CompileC error:

> [laptop_name]:[folder] pieter$ flutter run
> 
> Launching lib/main.dart on macOS in debug mode...
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         CompileC /Users/pieter/[app_path]/build/macos/Build/Intermediates.noindex/Pods.build/Debug/firebase_auth.build/Objects-normal/x86_64/FLTFirebaseAuthPlugin.o /Users/pieter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+2/darwin/Classes/FLTFirebaseAuthPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)

Using a pre-MacOS support version, eg 0.15.4, the build succeeds (but later the app crashed on a MissingPluginException of course)

Might be related to issue #2097

**Comment by AndroidNils** [comment]
I have the same issue. There is a problem with the UserAgent.h. PR for this fix: https://github.com/FirebaseExtended/flutterfire/pull/2099

**Comment by dluksza** [comment]
For me the workaround was to pin version of `firebase_auth` and `firebase_core` to `0.15.3` and `0.4.4` respectively.

It seems that `firebase_core` 0.4.4+2 is breaking auth by bumping `firebase_core_platform_interface` to the latest version which brings in breaking API changes in iOS.

**Comment by PieterAelse** [comment]
@dluksza For me that won't work as `firebase_auth` needs to be at least 0.15.5 for supporting MacOS.

**Comment by iapicca** [comment]
Hi @PieterAelse 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2104) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
