### ISSUE TITLE
[Auth] Flutter Firebase app not compilable anymore :(

### ISSUE THREAD

**Issue by Ahmadre** [FirebaseExtended/flutterfire#2144]
**Describe the bug**
Can't run and build a native flutter ios or android app

**To Reproduce**
1. Be on firebase_auth-0.15.5+2
2. try 'flutter run'

**Expected behavior**
Flutter runs and builds

**Additional context**

## Crash-Report

<details>

```bash
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Xcode build done.                                           84,3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/rebar/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+2/darwin/Classes/FLTFirebaseAuthPlugin.m:6:9: fatal error: 'UserAgent.h' file not found
    #import "UserAgent.h"
            ^~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)
```
</details>

maybe related to this PR: #2099

**Comment by iapicca** [comment]
Hi @Ahmadre 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2084) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
