### ISSUE TITLE
firebase_auth onAuthStateChanged doesn't change when user is deleted/disabled from firebase console

### ISSUE THREAD

**Issue by RamiAil** [FirebaseExtended/flutterfire#2150]
Hello, 

I'm trying to delete/disable a logged in user (using the firebase console website), but the onAuthStateChanged doesn't get triggered.
The only way I could find was to manually run 'user.reload()' and handle the 'ERROR_USER_DISABLED' or 'ERROR_USER_NOT_FOUND' out of it.

Thank you

**Comment by iapicca** [comment]
Hi @RamiAil 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by RamiAil** [comment]
hi @iapicca, this is my sample code, I'm using the provide package
Thank you !

import 'package:firebase_app/wrapper.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of myapplication.

  @override
  Widget build(BuildContext context) {
    return StreamProvider<FirebaseUser>.value(
      value: FirebaseAuth.instance.onAuthStateChanged,
      child: MaterialApp(
        home: Wrapper(),
      ),
    );
  }
}

----------------------------------------------------------------

class Wrapper extends StatelessWidget {
 @override
  Widget build(BuildContext context) {
    final user = Provider.of<FirebaseUser>(context);
    if (user == null) {
      home = null;
      return SignIn();
    }
    return Home();
  }
}

**Comment by iapicca** [comment]
Hi @RamiAil 
thank you for the code sample,
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
as well
Thank you

**Comment by red42** [comment]
I believe the behaviour you are experiencing is by design. [This stackoverflow comment](https://stackoverflow.com/questions/35960546/firebase-still-retrieving-authdata-after-deletion/35961217#35961217) has more details.

If I understand that correctly, the authentication state is thus unchanged, which would explain why onAuthStateChanged is not triggered.

**Comment by RamiAil** [comment]
@red42 Thank you so much for clearing it out! it's all about token and revoking it!
