### ISSUE TITLE
[cloud_functions] The getter 'uri' was called on null.

### ISSUE THREAD

**Issue by jasonkolodziej** [FirebaseExtended/flutterfire#2155]
**Describe the bug**
I was able to make various `onCall()` functions within firebase. I have done some simple tests locally and produce logs in the cloud (expected). However, there seems to be only one function that will work with this package and I am not too sure why.

**To Reproduce**
1. Go to https://code.luasoftware.com/tutorials/google-cloud-functions/create-compatitle-cloud-function-for-firebase-with-python/ to create a OnCall() python based function.
2. deploy to your firebase project.
4. Follow the steps, for `cloud_functions` example to get started.
5. You will see that a statement printout on debug for

```
caught generic exception
FirebaseError: internal (internal)
```

on Flutter web app. (I am running macOS, using chrome to debug)

**Expected behavior**
To get some reponse coming from my function.

**Additional context**
I have yet to try a different build of the Flutter app (iOS or Android)

**Comment by jasonkolodziej** [comment]
CORS on browser issue

**Comment by alisonthemonster** [comment]
What was your fix to this issue?

**Comment by jasonkolodziej** [comment]
@alisonthemonster Hi! I would love to give you a break down of how to go about this. Are you using python functions as well? Or some other language in with a GCP function (not Firebase and Node.js)??

**Comment by riordanpawley** [comment]
> @alisonthemonster Hi! I would love to give you a break down of how to go about this. Are you using python functions as well? Or some other language in with a GCP function (not Firebase and Node.js)??

I'm experiencing this issue and am using firebase and nodejs, would appreciate a break down when you get a chance :)
