### ISSUE TITLE
[Firebase_Auth] Unable to logout of two logged-in databases

### ISSUE THREAD

**Issue by EricPreventa** [FirebaseExtended/flutterfire#2159]
I have a production and development database I'm looking to use in my app. 
Production is default which I login using Google-Sign In.
Option to sign-in to the Development account using Google-Sign In (same credentials). All works well so far.

1. When I go to logout, there appears to be a bug where it does not log out of the development account.

2. When I try logging out of default (production) account, I logout, but the StreamBuilder doesn't acknowledge the stream FirebaseAuth.instance.onAuthStateChanged as being changed.

To Login:
```
FirebaseApp developmentDB = await FirebaseApp.configure(
				name: '__FIRAPP_DEV',
				options: const FirebaseOptions(
						apiKey: '',
						bundleID: '',
						clientID: '',
						gcmSenderID: '',
						projectID: '',
						databaseURL: '',
						storageBucket: '',
						googleAppID: ''));

		final GoogleSignInAccount googleSignInAccount = await GoogleSignIn().signIn();
		final GoogleSignInAuthentication googleSignInAuth = await googleSignInAccount.authentication;

		AuthCredential credential = GoogleAuthProvider.getCredential(
				accessToken: googleSignInAuth.accessToken,
				idToken: googleSignInAuth.idToken);
```

To Log out:
```
FirebaseApp dev  = await FirebaseApp.appNamed('__FIRAPP_DEV');
FirebaseAuth.fromApp(dev).signOut().then((value) => print('signed out'));
```

Flutter Doctor output:
```
Already up to date.
Flutter is already up to date on channel beta
Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (6 weeks ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
(base) Erics-Mac-Pro:ios hasseye$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G3020, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
(base) Erics-Mac-Pro:ios hasseye$ 

```

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
