### ISSUE TITLE
[cloud_firestore-0.13.4] deprecated apis

### ISSUE THREAD

**Issue by lvlrSajjad** [FirebaseExtended/flutterfire#2163]
I'm using Firestore 0.13.4 and facing this kind of warning:

```
cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
```

It's better to get rid of old packages and deprecated APIs.

Thanks in advance

**Comment by iapicca** [comment]
Hi @lvlrSajjad 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1921) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
