### ISSUE TITLE
[firebase_storage] Unknown error updating metadata on the encrypted file

### ISSUE THREAD

**Issue by kika** [FirebaseExtended/flutterfire#2168]
**Describe the bug**

 * Upload the file to Firebase Storage with `putFile`
 * `updateMetadata()` succeeds
 * cloud function trigger sees update on metadata and encrypts the file with customer-supplied key, encryption happens with `rewrite` (`copy` over itself) using Google Storage SDK for Node.js. 
 * cloud function updates metadata with Google Storage SDK for Node.js, stores encrypted key, algorithm and other relevant information in the metadata of the encrypted file. 
 * Flutter app tries to update the metadata on this file again (to mark it for deletion) - failure.

`Error -13000: FIRStorageErrorDomain, An unknown error occurred, please check the server response.`

No way to find out where this `server response` is.

**Expected behavior**
If Google Storage SDK can update metadata on the encrypted file without decrypting it (without having access to the key), then I expect Firebase Storage to be able to do it too.
I verified with `gsutil` - I can update custom metadata on the encrypted file too, without supplying the key.

**Comment by iapicca** [comment]
Hi @kika 
I'm not sure if the issue you are describing is 
with `Firebase` or with `FlutterFire`'s plugins;

Could you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by kika** [comment]
I missed the initial notification (on Mar 20) somehow. Minimal code sample is not very minimal (it requires a Flutter app and a Cloud Function) but I'm willing to work on one.

**Comment by Ehesp** [comment]
@kika Do you see any iOS logs? "please check the server response" - you should see the output of some HTTP requests by the underlying SDK.

**Comment by kika** [comment]
@Ehesp that was the only information that I collected from the log.
