### ISSUE TITLE
[cloud_firestore_web] FieldValues Equality broken in Web

### ISSUE THREAD

**Issue by ditman** [FirebaseExtended/flutterfire#2171]
#### Describe the bug

FieldValues in web delegate their equality comparison to the underlying package:firestore objects.

The base library **doesn't override the == operator**, so equality for types with parameters (arrayRemove, arrayUnion, increment) is broken in web.

The current integration test is catching this:

```
00:13 +18 -1: Firestore Equality comparison on FieldValues [E]
Expected: FieldValue:<FieldValue(FieldValue.arrayRemove([1]))>
    Actual: FieldValue:<FieldValue(FieldValue.arrayRemove([1]))>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49      throw_
  package:test_api/src/frontend/expect.dart 153:30                                          fail
  package:test_api/src/frontend/expect.dart 147:3                                           _expect
  package:test_api/src/frontend/expect.dart 59:3                                            expect$
  package:flutter_test/src/widget_tester.dart 348:3                                         expect$
  package:firestore_example/main.dart 541:7                                                 <fn>
  package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54                runBody
  package:dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12               _async
  package:firestore_example/main.dart 539:48                                                <fn>
```

#### `1.0` vs `1`

There's also a **secondary issue** where [the browser is not able to tell apart `1` from `1.0`](https://stackoverflow.com/a/7422110). That [part of the test](https://github.com/FirebaseExtended/flutterfire/blob/4d7b2bdd7fbdee65551754968b140653ea16128f/packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore.dart#L546-L548) will always fail (unless we try to compare 1 and 1 + Number.EPSILON, which is the closest, different, value to 1 in the browser) 

**To Reproduce**

1. Go to `flutterfire/packages/cloud_firestore/cloud_firestore/example`
2. Run `./run-tests-web` 
3. See error or incorrect behavior

**Expected behavior**

All tests pass, and you can successfully compare FieldValues in web.

**Additional context**

These are the [affected, underlying FieldValue implementations](https://github.com/FirebaseExtended/firebase-dart/blob/ec106a9e65656c8c8c88d12fad6d88e3ba7f7c8b/lib/src/firestore.dart#L924-L963) for web.

Relevant issue: #2018

**Comment by ditman** [comment]
The question is... Do we patch this in the plugin, or do we implement `==` in `package:firestore`?

**Comment by Ehesp** [comment]
@ditman the web sdk doesn't handle equality on FieldValue, do you think this one is actually needed in Dart?

**Comment by ditman** [comment]
@Ehesp AFAIK it only had to do with the test I linked above when running on web (I haven't seen any real-world issue about this that I can remember).

**Comment by Ehesp** [comment]
Closing this one - a lot has been reworked since this issue (no longer using firebase-dart).
