### ISSUE TITLE
[<Admob>] <Not waiting for ads to be loaded>

### ISSUE THREAD

**Issue by aldwnesx** [FirebaseExtended/flutterfire#2175]
I am getting error when I try to call a function which loads and then displays the ads when user is clicked.

As the ads not fully loaded, it gives error

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)`

```dart
Future loadAds() async {

    await RewardedVideoAd.instance.load(
        adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);

    return "completed";
  }

  void showAds() async {
    var test = await loadAds();

    RewardedVideoAd.instance.show();
  }
```

**Comment by iapicca** [comment]
Hi @aldwnesx 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`
and your `pubspec.yaml` 
Thank you

**Comment by blasten** [comment]
This sounds like a race condition. Is this being fixed @bparrishMines ?

**Comment by blasten** [comment]
Another race condition: https://github.com/FirebaseExtended/flutterfire/issues/669

**Comment by willmeet** [comment]
[That issue is clearly shown here how to solve admob failed to load ads](http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html)

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
