### ISSUE TITLE
[cloud_firestore] java.lang.RuntimeException: Internal error

### ISSUE THREAD

**Issue by davidlutta** [FirebaseExtended/flutterfire#218]
The following error has been coming up and crashing my app whenever I try to read or write data to firestore using a real android device running Android 5 yet yesterday it was working. When I run the app on my emulator which is running Android 10 the app works just fine. I don't know where the problem is.

Error: 
`E/AndroidRuntime( 3058): java.lang.RuntimeException: Internal error in Firestore (19.0.0).
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@19.0.0:379)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(com.google.firebase:firebase-firestore@@19.0.0)
E/AndroidRuntime( 3058): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime( 3058): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime( 3058): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 3058): 	at android.app.ActivityThread.main(ActivityThread.java:5651)
E/AndroidRuntime( 3058): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3058): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3058): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/AndroidRuntime( 3058): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
E/AndroidRuntime( 3058): Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid field path (``). Paths must not be empty, begin with '.', end with '.', or contain '..'
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@19.0.0:290)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@19.0.0)
E/AndroidRuntime( 3058): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/AndroidRuntime( 3058): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 3058): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
E/AndroidRuntime( 3058): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
E/AndroidRuntime( 3058): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 3058): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@19.0.0:205)
E/AndroidRuntime( 3058): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 3058): Caused by: java.lang.IllegalArgumentException: Invalid field path (``). Paths must not be empty, begin with '.', end with '.', or contain '..'
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.model.FieldPath.fromServerFormat(com.google.firebase:firebase-firestore@@19.0.0:90)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.remote.RemoteSerializer.decodeDocumentMask(com.google.firebase:firebase-firestore@@19.0.0:537)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.remote.RemoteSerializer.decodeMutation(com.google.firebase:firebase-firestore@@19.0.0:470)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.LocalSerializer.decodeMutationBatch(com.google.firebase:firebase-firestore@@19.0.0:190)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.SQLiteMutationQueue.decodeInlineMutationBatch(com.google.firebase:firebase-firestore@@19.0.0:437)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.SQLiteMutationQueue.lambda$getNextMutationBatchAfterBatchId$4(com.google.firebase:firebase-firestore@@19.0.0:236)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.SQLiteMutationQueue$$Lambda$5.apply(com.google.firebase:firebase-firestore@@19.0.0)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.SQLitePersistence$Query.firstValue(com.google.firebase:firebase-firestore@@19.0.0:476)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.SQLiteMutationQueue.getNextMutationBatchAfterBatchId(com.google.firebase:firebase-firestore@@19.0.0:236)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.local.LocalStore.getNextMutationBatch(com.google.firebase:firebase-firestore@@19.0.0:497)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.remote.RemoteStore.fillWritePipeline(com.google.firebase:firebase-firestore@@19.0.0:574)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.remote.RemoteStore.enableNetwork(com.google.firebase:firebase-firestore@@19.0.0:240)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.remote.RemoteStore.start(com.google.firebase:firebase-firestore@@19.0.0:289)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@19.0.0:255)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@19.0.0:116)
E/AndroidRuntime( 3058): 	at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.`

**Comment by furkansarihan** [comment]
Did you figure it out ?

**Comment by davidlutta** [comment]
Not really, the error doesn't seem to occur when I run my app on devices with android Pie and android 10

**Comment by iapicca** [comment]
Hi @davidlutta 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by yvzoncu** [comment]
i am facing with the same problem from yesterday any solution so far?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by davidlutta** [comment]
I was able to resolve this error by changing this in my `project level build.gradle` file
from
`ext.kotlin_version = '1.2.71'`
to this
`ext.kotlin_version = '1.3.0'`

**Comment by mep72** [comment]
I'm having this same issue, I've been trying different proposed solutions without any luck, I'm attaching two files: 
The result from running **flutter doctor -v**
[FlutterDoctorV.txt](https://github.com/FirebaseExtended/flutterfire/files/3898021/FlutterDoctorV.txt)

And the result from **flutter run --verbose**
[FlutterRunVerbose.txt](https://github.com/FirebaseExtended/flutterfire/files/3898026/FlutterRunVerbose.txt)

Hope this helps to resolve the issue or to get what I'm doing wrong.

Thanks in advance!
