### ISSUE TITLE
[Service took too long to process intent] FirebaseMessaging

### ISSUE THREAD

**Issue by mudi256** [FirebaseExtended/flutterfire#2181]
Flutter firebaseMessaging issue data Notification not received when app is in background not terminated, further "onMessage" is not triggered.
```bash
D/FlutterNativeView(17720): FlutterView.send called on a detached view, channel=plugins.flutter.io/firebase_database
W/FirebaseInstanceId(17720): Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.
```

flutter Channel stable, v1.12.13+hotfix.8
<img width="574" alt="Screenshot 2020-03-17 at 1 29 10 AM" src="https://user-images.githubusercontent.com/36504724/76797281-f8aa2900-67ee-11ea-9e6f-29b4ee9a9199.png">
<img width="1498" alt="Screenshot 2020-03-17 at 1 29 48 AM" src="https://user-images.githubusercontent.com/36504724/76797292-fea00a00-67ee-11ea-8c3c-7880d01378b4.png">

**Comment by iapicca** [comment]
Hi @mudi256 
can you please provide your `flutter run --verbose`,
your `pubspec.yaml` 
and if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

possibly related to https://github.com/FirebaseExtended/flutterfire/issues/1590

**Comment by mudi256** [comment]
Muhammads-MBP:north_messaging muhammadmudassar$ flutter run --verbose
[  +32 ms] executing: [/Users/muhammadmudassar/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/muhammadmudassar/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +8 ms] executing: [/Users/muhammadmudassar/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/muhammadmudassar/Documents/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] executing: [/Users/muhammadmudassar/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +45 ms] executing: /usr/bin/xcode-select --print-path
[  +16 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[ +661 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3.1
           Build version 11C504
[  +77 ms] executing: /Users/muhammadmudassar/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/muhammadmudassar/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +29 ms] executing: /Users/muhammadmudassar/Documents/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +75 ms] /usr/bin/xcrun simctl list --json devices
[ +133 ms] No supported devices connected.
[  +12 ms] "flutter run" took 1,142ms.

**Comment by mudi256** [comment]
Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) async {
  print("fuck!!:$message");
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      new FlutterLocalNotificationsPlugin();
  var android = new AndroidInitializationSettings('mipmap/noti');
  var ios = new IOSInitializationSettings();
  var platform = new InitializationSettings(android, ios);
  flutterLocalNotificationsPlugin.initialize(platform);

  var android2 =
      AndroidNotificationDetails("senderName", "North Messaging", "");
  var iOS2 = new IOSNotificationDetails();
  var platform2 = new NotificationDetails(android2, iOS2);
  ContactsService.getContactsForPhone("senderName").then((value) async {
    if (value.isEmpty) {
      await flutterLocalNotificationsPlugin.show(
          1, "senderName", "text", platform2);
    } else {
      await flutterLocalNotificationsPlugin.show(
          1, value.elementAt(0).displayName, "text", platform2);
    }
  });

//main.dart
main() async {
runApp(App());
}
//add.dart init state

@override
  void initState() {
    super.initState();
    final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
    _firebaseMessaging.requestNotificationPermissions(
        IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {});
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        
      },
      onBackgroundMessage: myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume22: $message");
      },
    );

    });

**Comment by mudi256** [comment]
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3
  outline_material_icons: ^0.1.0
  provider:
  flutter_launcher_icons: ^0.7.3
  firebase_messaging: ^6.0.9
  http: ^0.12.0+2
  url_launcher: ^5.1.1
  toast: ^0.1.5
  flutter_screenutil: ^0.6.0
  fluttertoast: ^3.1.0
  intl: ^0.15.7
  cached_network_image: ^2.0.0
  image_picker: 0.6.0+17
  firebase_auth: 0.15.3
  contact_picker: ^0.0.2
  firebase_core: 0.4.4
  firebase_storage: 3.0.5
  contacts_service: ^0.3.10
  libphonenumber: ^1.0.0
  firebase_database: ^3.1.3
  flutter_local_notifications: ^1.2.0+4
  connectivity_widget: ^0.1.1
  flutter_linkify: ^2.1.0
  flutter_selectable_text: ^0.3.1
  permission_handler: ^4.4.0
  flutter_image_compress: ^0.6.3
  path_provider: ^1.3.1
  scroll_to_index: ^1.0.2
  indexed_list_view: ^1.0.8
  isolate: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_icons:
  image_path: "assets/icon/northIcon.png"
  android: true
  ios: true
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/github_ic.png
    - assets/linkedin_ic.png
    - images/img_not_available.jpeg

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500

**Comment by mudi256** [comment]
@iapicca I provide all detail which you want, why the tag is "waiting for customer response"?

**Comment by iapicca** [comment]
> @iapicca I provide all detail which you want, why the tag is "waiting for customer response"?
Hi @mudi256 
I removed the tag, I didn't add it

**Comment by mudi256** [comment]
update dart plugin to 192.7761, 
firebase service plugin to 3.6.0 
and flutter plugin to 44.0.2 resolve the issue
