### ISSUE TITLE
[firebase_auth] Test firebase_auth_platform_interface_test is order-dependent

### ISSUE THREAD

**Issue by enetor** [FirebaseExtended/flutterfire#2182]
Internal bug: b/151523518

When running test cases in a particular order, test case "FirebaseAuthPlatform.MethodChannelFirebaseAuth" fails consistently.

**Comment by Ehesp** [comment]
Hey @enetor - could you send over some additional details? Seems like that's an internal bug report. We can take a look if we know what tests are failing.

Thanks
