### ISSUE TITLE
[firebase_messaging] onBackgroundMessage does not register plugins

### ISSUE THREAD

**Issue by alokraop** [FirebaseExtended/flutterfire#2183]
The README instructions say that to work with background messages on android, we need to extend `FlutterApplication`:

```
public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

But since the v2 embedding update, `GeneratedPluginRegistrant.registerWith` expects a `flutterEngine` instead of a `pluginRegistry`. So the code doesn't compile. I can't even simply omit the registration for the background thread because i need to use some plugins in the backgroundView

https://github.com/FirebaseExtended/flutterfire/blob/fd8f63d4ac6f2fb073e91726cb4879e02119d242/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java#L164

So i'm currently manually writing all the plugin registration code to get things working:

```
override fun registerWith(registry: PluginRegistry) {
        PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.pathprovider.PathProviderPlugin"))
        FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
        FlutterLocalNotificationsPlugin.registerWith(registry.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"))
        FlutterSecureStoragePlugin.registerWith(registry.registrarFor("com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin"))
        SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"))
}
```

Also, the [v2 embedding upgrade guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) says:

> Remove the reference to `FlutterApplication` from the application tag.

So is overriding `FlutterApplication` even recommended anymore? What's the best way to configure `FlutterFirebaseMessagingService`?

The example app does not show usage of `onBackgroundMessage` either. so it's not clear what the right way is.

**Comment by hw-dwalter** [comment]
Here is sample project https://github.com/hw-dwalter/flutter-firebase-messaging-background-example and video https://youtu.be/frhnHX8Z-UQ demonstrating the bug.

**Comment by ahawlitschek** [comment]
So ist there currently no way to use background messages when using v2 embedding?

**Comment by joaovvrodrigues** [comment]
They need to update the tutorial on pub.dev, as they are upgrading to Android V2 but I did SEVERAL tests and it seemed like a very bad transition. It is not working, so it is necessary to improvise and be content with the use of only 1 package in the background. I hope they soon update the README - Getting Started from pub.dev to Android v2 embedding.

**Comment by Yirmerah** [comment]
Has anyone successfully handle on backgroud notification with OnBackgroundMessage?

**Comment by MaikuB** [comment]
@Ehesp should this be closed as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1775?

**Comment by Stone2517** [comment]
I solved this issue

https://github.com/FirebaseExtended/flutterfire/issues/2777#issuecomment-685805903

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has been been heavily reworked, along with documentation, since this issue was raised: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
