### ISSUE TITLE
Auth and Firestore persist even after app uninstall

### ISSUE THREAD

**Issue by andcea** [FirebaseExtended/flutterfire#2185]
**Describe the bug**
I have a weird situation where I can't clear the cache for Firebase Auth and Firestore on a real device.

When using the app, the persisted data updates correctly (including auth logout/login) however, after I re-install the app or use `flutter install -d deviceId`, on first start of the app it loads with a user already logged in and an older version of my Firestore data (even though it has been updated later and user changed).

I've tried manually uninstalling the app and clear the cache, storage.
Restarted the phone and cleared the phone cache.
Killed google services and other that I thought might be relevant.

Other things that might be relevant: I've updated the phone (OnePlus 5T) and migrated the flutter app to AndroidX recently.

This has to be a persistence issue but I haven't been able to clear it.

**Comment by iapicca** [comment]
Hi @andcea 
can you please provide your `flutter doctor -v` , 
your `pubspec.yaml` 
and if possible a reproducible minimal code sample
for your implementation of `firebase_auth `and `cloud_firestore`
Thank you

**Comment by andcea** [comment]
Hi @iapicca 

This behaviour has stopped happening and I'm aware that it's going to be difficult to debug as I don't know exactly what caused it. It could be a potential security and privacy issue if after app uninstall the user is still authenticated.  

This request was more for help in _manually_  clearing the Firebase cache from a phone.  

Having said that, I'll add the information you required in case it happens to someone else in the future but feel free to resolve.  

**flutter doctor**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/andcea/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andcea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one
        being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • ONEPLUS A5010             • e7b832ee      • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**pubspec extract**
```
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
```


**Relevant code snippets**
```
class Auth extends ValueNotifier<AuthState> {
  StreamSubscription<FirebaseUser> _firebaseUserStreamSubscription;

  Auth() : super(AuthLoading()) {
    _initAsync();
  }

  Future _initAsync() async {
    _firebaseUserStreamSubscription =
       FirebaseAuth.instance.onAuthStateChanged.listen((firebaseUser) => value = _getStateForUser(firebaseUser));
    value = _getStateForUser(await FirebaseAuth.instance.currentUser());
  }

  @override
  void dispose() async {
    super.dispose();
    _firebaseUserStreamSubscription.cancel();
  }
```
```
Firestore.instance.collection('a').document('b').listen((data) => ...);
```

Let me know if you need anything else.
Thanks

**Comment by andcea** [comment]
I'm still seeing this issue pretty consistently on Android while developing (sign out -> app reinstall using flutter install -> user is already logged in and old cache data) 
I hope it doesn't affect release as well.

Other people might have this issue as well: https://stackoverflow.com/questions/58902649/how-to-clear-firebase-cache

Is there a way to clear cached data from Flutter (i.e. on sign out)?

**Comment by dpedrinha** [comment]
I'm having this issue on released version. And also, having problems with dynamic links on a few devices that I believe are related to the link cache.

**Comment by Salakar** [comment]
Hey all, as part of our on-going work for #2582, we've added support for the `clearPersistence()` API with our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
