### ISSUE TITLE
[firebase_messaging] deprecated API

### ISSUE THREAD

**Issue by lvlrSajjad** [FirebaseExtended/flutterfire#2186]
Receiving this in build time (Android)
```
Note: /Users/lvlrx/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.9/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java uses or overrides a deprecated API.
```
It's better to get rid of this kind of warnings in firebase_messaging

Thanks in advance

**Comment by iapicca** [comment]
Hi @lvlrSajjad 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1625) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
