### ISSUE TITLE
flutter firebase auth email link login "isSignInWithEmailLink" does not work as expected.

### ISSUE THREAD

**Issue by kkibria** [FirebaseExtended/flutterfire#2190]
**Describe the bug**
isSignInWithEmailLink is returning false instead of true in flutter web app .

**To Reproduce**
1. The example app provided in the firebase_auth package was used.
2. A deep link landing page added to MyApp build.
```dart
return MaterialApp(
      title: 'Firebase Auth Demo',
      initialRoute: '/',
      routes: {
        '/': (context) => MyHomePage(title: 'Firebase Auth Demo'),
        '/register': (context) => RegisterPage(),
        '/signin': (context) => SignInPage(),
        '/email-link': (context) => EmailLinkPage(),
      }
    );
```
 3: EmailLinkPage widget contains a button calls following handler when pressed
```dart
 Future<void> _signinConfirm(String url) async {
    try {
      if (await _auth.isSignInWithEmailLink(url)) {
        print("valid link");
      }
      else {
        print("invalid link");
      } 
    } catch (e) {
      print(e.toString());    
    }
  }
```
4: app was built for web with "flutter build web" and deployed to firebase.
5: email was sent from the app and then link from email is clicked.
6: landing page opened and Console prints "invalid link" which is incorrect behavior.

**Expected behavior**
isSignInWithEmailLink should be returning true in such case.

**Additional context**

**Comment by iapicca** [comment]
Hi @kkibria 
can you please provide your `flutter doctor -v`
and your `pubspec.yaml` 
Thank you
