### ISSUE TITLE
[cloud_firestore] Please provide native dart library for firestore

### ISSUE THREAD

**Issue by HerrNiklasRaab** [FirebaseExtended/flutterfire#2191]
Please rewrite the cloud_firestore library in native dart, so we can remove all the big (in terms of download size) Android and iOS libraries. Which slow down build time dramatically. 

Having to create a manual abstraction to support https://pub.dev/packages/firebase and https://pub.dev/packages/cloud_firestore is a mess.

All future platforms would be supported out of the box.

Something like this: https://github.com/cachapa/firedart

**Comment by NullByte08** [comment]
Hi, I am new here, so I am not sure but the cloud_firestore plugin is already made now. So shouldn't the issue be closed now?

**Comment by Salakar** [comment]
Lets discuss over at #3359
