### ISSUE TITLE
[firebase_admob] AdMob suspended my banner on iOS: "Modified ad code: Resizing Ad Frames"

### ISSUE THREAD

**Issue by danieeelfc** [FirebaseExtended/flutterfire#2198]
I've implemented the standard code of `firebase_admob` for showing a simple banner ad at the bottom and one week and a half after publishing my app to app store AdMob sent me and email with the following succinct information:

> MODIFIED ADS: Publishers are not permitted to alter the behavior of Google ads in any way. This includes resizing ad frames to cut off parts of ads or hiding the Ads by Google moniker.

I need to say that the implementation is very simple and I cannot figure out what is pushing admob away.

some config info:

```dart
size: AdSize.smartBanner;

  void displayBanner() {
    myBanner
      ..load()
      ..show(
        anchorOffset: 0.0,
        anchorType: AnchorType.bottom,
      );
  }

```
Version:
`firebase_admob: ^0.9.1+1`

**Comment by iapicca** [comment]
Hi @danieeelfc 
I'm not sure if this matter is about 
your implementation of `firebase_admob`
or `google ads policy`

If you believe it's the first case
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and a minimal code sample
of your implementation of `firebase_admob`
Thank you

**Comment by danieeelfc** [comment]
Hi @iapicca , thanks for your reply.

Here is an example of what I think google got angry: https://imgur.com/XbLgYQb

My implementation:

` void startBanner() {

  myBanner = BannerAd(

  adUnitId: BannerAd.testAdUnitId,
  size: AdSize.smartBanner,
  targetingInfo: targetingInfo,
  listener: (...)
}
void displayBanner() {
  myBanner
    ..load()
    ..show(
      anchorOffset: 0.0,
      anchorType: AnchorType.bottom,
    );
 }

 @override
 void dispose() {
   myBanner?.dispose();
   myInterstitial?.dispose();
   super.dispose();
  }
 @override
 void initState() {
   super.initState();

   FirebaseAdMob.instance
     .initialize(appId: Platform.isIOS ? "ca-app-XXX" : "ca-app-YYY");

   startBanner();
   displayBanner();
}`

> flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-BR)
    • Flutter version 1.12.13+hotfix.8 at /Users/daniel/Dev/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 6311F8A3-A228-408C-8E8C-CCA4C84DC2A8 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!


flutter run --verbose was too bit to put on pastebin, so I uploaded it here: https://1drv.ms/t/s!Aq-m5HeHbcgJkKJCEhobM4mGutLZeQ?e=4hfm3p

**Comment by lohanidamodar** [comment]
@danieeelfc were you able to fix the problem? my ads was recently suspended too.

**Comment by fleoparra** [comment]
I was suspended too and I try to explain that this is the library that Firebase provide us to use admob. On my research I found that the problem was reported only for iOS devices and the ad is a SmartBanner

**Comment by lohanidamodar** [comment]
For me it was reported for Android and ad is fullBanner?

**Comment by ming-chu** [comment]
Reported for android too.
```Android , Modified ad code: Resizing Ad Frames```

**Comment by cristovamsegundo** [comment]
Same problem on Android.

**Comment by armandojimenez** [comment]
is this still an issue?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
