### ISSUE TITLE
[firebase_database] transaction do nothing

### ISSUE THREAD

**Issue by ektelat** [FirebaseExtended/flutterfire#22]
i run transaction to add 1 to the last value, put it return the last value
this my code:
 Future<void> saveNewMission(Message message) async {
    TransactionResult res = await _firebase
        .reference()
        .child('offices')
        .child(this.officeKey)
        .child('counters/missions')
        .runTransaction((count) async {
        count.value = (count.value ?? 0) + 1;
       return count;
    });
  
 this.count =  res.dataSnapshot.value;
------------------------------------------------------------------------

always i get la last value that saved on the database

**Comment by Ehesp** [comment]
Hi @ektelat due to the age and inactivity of this issue I'm going to close it. Please try upgrading versions of Flutter & the plugin as there has been many changes since this issue was created.

If it continues to be a problem after upgrading, please create a new issue following the issue template.
