### ISSUE TITLE
I follow the steps of the document, the following phenomenon occurs, how should I solve? Thank you very much！

### ISSUE THREAD

**Issue by PacteraJiJiaWei** [FirebaseExtended/flutterfire#2205]
Launching lib/main.dart on iPhone XS in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: DLZ6PYT9WF
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A Firebase
      A FirebaseAnalytics
      A FirebaseAnalyticsInterop
      A FirebaseCore
      A FirebaseCoreDiagnostics
      A FirebaseCoreDiagnosticsInterop
      A FirebaseInstallations
      A FirebaseInstanceID
      A FirebaseMessaging
      A Flutter
      A GoogleAppMeasurement
      A GoogleDataTransport
      A GoogleDataTransportCCTSupport
      A GoogleUtilities
      A PromisesObjC
      A Protobuf
      A firebase_messaging
      A nanopb

    Downloading dependencies

    -> Installing Firebase (6.20.0)
      > Copying Firebase from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/Firebase/6.20.0-fe7f7` to `Pods/Firebase`

    -> Installing FirebaseAnalytics (6.3.1)
      > Copying FirebaseAnalytics from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalytics/6.3.1-572e4` to `Pods/FirebaseAnalytics`

    -> Installing FirebaseAnalyticsInterop (1.5.0)
      > Copying FirebaseAnalyticsInterop from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalyticsInterop/1.5.0-3f862` to `Pods/FirebaseAnalyticsInterop`

    -> Installing FirebaseCore (6.6.4)
      > Copying FirebaseCore from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/6.6.4-ed0a2` to `Pods/FirebaseCore`

    -> Installing FirebaseCoreDiagnostics (1.2.2)
      > Copying FirebaseCoreDiagnostics from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseCoreDiagnostics/1.2.2-e9b4c` to `Pods/FirebaseCoreDiagnostics`

    -> Installing FirebaseCoreDiagnosticsInterop (1.2.0)
      > Copying FirebaseCoreDiagnosticsInterop from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseCoreDiagnosticsInterop/1.2.0-296e2` to `Pods/FirebaseCoreDiagnosticsInterop`

    -> Installing FirebaseInstallations (1.1.0)
      > Copying FirebaseInstallations from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseInstallations/1.1.0-575cd` to `Pods/FirebaseInstallations`

    -> Installing FirebaseInstanceID (4.3.2)
      > Copying FirebaseInstanceID from `/Users/wufan/Library/Caches/CocoaPods/Pods/Release/FirebaseInstanceID/4.3.2-7ee0d` to `Pods/FirebaseInstanceID`

    -> Installing FirebaseMessaging (4.3.0)
     > Git download
     > Git download
         $ /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/ll/fbd2ml8j45j270nr573b0dy80000gn/T/d20200319-42041-1l440x5 --template= --single-branch --depth 1 --branch Messaging-4.3.0

    [!] Error installing FirebaseMessaging
    [!] /usr/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/ll/fbd2ml8j45j270nr573b0dy80000gn/T/d20200319-42041-1l440x5 --template= --single-branch --depth 1 --branch Messaging-4.3.0

    Cloning into '/var/folders/ll/fbd2ml8j45j270nr573b0dy80000gn/T/d20200319-42041-1l440x5'...
    fatal: unable to access 'https://github.com/firebase/firebase-ios-sdk.git/': Failed to connect to github.com port 443: Operation timed out

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:139:in `execute_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/base.rb:154:in `block in executable'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/git.rb:79:in `block in clone'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/git.rb:77:in `clone'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/git.rb:45:in `download!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/base.rb:82:in `block in download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:157:in `block in ui_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:156:in `ui_action'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-downloader-1.2.2/lib/cocoapods-downloader/base.rb:80:in `download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:108:in `download_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:75:in `download_request'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:171:in `download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:42:in `download'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:478:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:478:in `install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:234:in `download_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:157:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
         Cloning into '/var/folders/ll/fbd2ml8j45j270nr573b0dy80000gn/T/d20200319-42041-1l440x5'...
         fatal: unable to access 'https://github.com/firebase/firebase-ios-sdk.git/': Failed to connect to github.com port 443: Operation timed out

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Finished with error: Error running pod install

**Comment by ikaro1970** [comment]
HI!

Did you solve this problem?
How?
