### ISSUE TITLE
[cloud_functions] Call function error

### ISSUE THREAD

**Issue by thangvdpnl** [FirebaseExtended/flutterfire#2206]
I'm following this code to call cloud functions. But getting error
My code
`
final _cloudFunctions = CloudFunctions.instance;
final HttpsCallable callable = _cloudFunctions.getHttpsCallable(functionName: 'JOIN_ROOM');
final HttpsCallableResult result = await callable.call(<String, dynamic>{
      'roomCode': roomCode,
      'password': password
});
`
Getting errors:
**PlatformException (PlatformException(3840, The data couldn’t be read because it isn’t in the correct format., null))**

Anybody has solution. Thank you!

**Comment by cornetthomas** [comment]
Where you able to fix it? Or why did you close this?
