### ISSUE TITLE
[firebase_crashlytics] Example Project is not working

### ISSUE THREAD

**Issue by leochiu-work** [FirebaseExtended/flutterfire#2207]
**Describe the bug**
Crashlytics cannot catch the Exception at all.

**To Reproduce**
1. Download and run the Firebase Crashlytics Example Project in iOS
2. Press 'Crash' button
4. Crashed, but Crashlytics cannot catch the exception

**Expected behavior**
"Flutter error caught by Crashlytics plugin" is shown in Debug Console

**Comment by iapicca** [comment]
Hi @leochiu-work 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`
and your `pubspec.yaml` 
Thank you

**Comment by ajackson2907** [comment]
It seems the command line argument -FIRAnalyticsDebugEnabled is not included when using flutter run

Can flutter include command-line arguments?

**Comment by workerbee22** [comment]
It hasn't worked as documented for about 6 months or longer.

**Comment by Ehesp** [comment]
Closing as duplicate of the older https://github.com/FirebaseExtended/flutterfire/issues/1951
