### ISSUE TITLE
[FirebaseAuth] isEmailVerified doesn't update unless user signs in again

### ISSUE THREAD

**Issue by IoanaAlexandru** [FirebaseExtended/flutterfire#2208]
**Describe the bug**
The value of a user's `isEmailVerified` doesn't seem to update correctly unless the user signs in again after verifying.

**To Reproduce**
1. Create a new user (`FirebaseAuth.instance.createUserWithEmailAndPassword`)
2. Send email verification (`FirebaseAuth.instance.sendEmailVerification`)
3. The call at 1. also signs the user in
4. User clicks on link in e-mail, account is verified
5. Check e-mail verification status on the signed in user (`((await FirebaseAuth.instance.currentUser()).isEmailVerified`) -> it returns `false` unless the user signs out and signs in again

**Expected behavior**
`isEmailVerified` returns `true` without the user needing to sign in again

**Comment by laurentiustamate94** [comment]
You must use
```dart
currentUser().reload
```
because the `FirebaseAuth.instance.currentUser()` call will return cached data otherwise.
