### ISSUE TITLE
[firebase_auth] sendEmailVerification missing actionCodeSettings parameter

### ISSUE THREAD

**Issue by shadysamir** [FirebaseExtended/flutterfire#221]
Firebase allows sending an actionCodeSettings parameter to sendEmailVerification method according to web docs https://firebase.google.com/docs/auth/web/passing-state-in-email-actions which is the same for iOS and Android

Flutter should support that. Currently it doesn't:
```dart
/// Initiates email verification for the user.
  Future<void> sendEmailVerification() async {
    // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
    // https://github.com/flutter/flutter/issues/26431
    // ignore: strong_mode_implicit_dynamic_method
    await FirebaseAuth.channel.invokeMethod(
        'sendEmailVerification', <String, String>{'app': _app.name});
  }
```
This is a port of flutter/flutter#30349

**Comment by willvlad** [comment]
Any update? It's quite a useful function that's still missing from the flutter firebase sdk...

**Comment by willvlad** [comment]
Any update on this from flutter/firebase folks? @zoechi @Hixie @FlutterIssues

**Comment by j05u3** [comment]
Hi guys, I also need to redirect back to the app when sending a verification email. Any updates?

**Comment by abinmittu** [comment]
Any updates on this?

**Comment by Salakar** [comment]
Added in latest release
