### ISSUE TITLE
Firebase_Auth, needing refresh token.

### ISSUE THREAD

**Issue by KFMong** [FirebaseExtended/flutterfire#2212]
I need to get refresh token from firebase auth, which I will use that "**refresh token**" for custom backend API. But in firebase_auth plugin "**getIdToken**" class, I use parameter "refresh" and set as "true" it is just returning a refreshed **JWT idToken**, 

**Expected Solution**
What I want is a "**refresh token**".

**Additional context**
 Is there an alternative solution for this issue?.

**Comment by Ehesp** [comment]
Hi @KFMONGF2P - could you show some code of what you're doing & expecting please? the `getIdToken` returns a new JWT with an updated expiry time as expected.

Thanks
