### ISSUE TITLE
[cloud_firestore] <Fieldvalue.increment>

### ISSUE THREAD

**Issue by aldwnesx** [FirebaseExtended/flutterfire#2215]
FieldValue.increment is bugged.

If i put positive integer, it works properly as expected e.g value of 1 means increase by 1.

If I  put negative integer, it works fine BUT one second later it decrements once more e.g if I put -1, it will decrease by 1, but one second later it -1 again.

I have verified function calls and logs that the function to do that only gets called on my code, but the library does it twice.

**Comment by iapicca** [comment]
Hi @aldwnesx 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by Ehesp** [comment]
Please can you post some code to reproduce.

**Comment by Ehesp** [comment]
I can confirm this is as expected. When using `setData` with a negative increment (e.g. -1), it sets it to -1. You need to use `updateData` to make it decrement.

**Comment by dulajdanu** [comment]
i also get this error . i used updateData to decrease the value of a field but sometimes it runs twice
