### ISSUE TITLE
[<firebase messaging>] <IOS InvalidRegistration NotRegistered >

### ISSUE THREAD

**Issue by Jackcui68** [FirebaseExtended/flutterfire#2216]
**Describe the bug**
firebase_messaging: 6.0.12.     IOS:    
The app first run ,the first message is ok ,but after show invalid registration.

 {multicast_id: 7069242072246239101, success: 1, failure: 0, canonical_ids: 0, results: [{message_id: 0:1584772819024939%de619279f9fd7ecd}]}
{multicast_id: 2059086090861151724, success: 0, failure: 1, canonical_ids: 0, results: [{error: InvalidRegistration}]}
{multicast_id: 8731985824744209514, success: 0, failure: 1, canonical_ids: 0, results: [{error: NotRegistered}]}
{multicast_id: 373187184390019037, success: 0, failure: 1, canonical_ids: 0, results: [{error: NotRegistered}]}
{multicast_id: 3686360921666845957, success: 0, failure: 1, canonical_ids: 0, results: [{error: NotRegistered}]}
{multicast_id: 3834293159411406592, success: 0, failure: 1, canonical_ids: 0, results: [{error: NotRegistered}]}

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020, locale zh-Hans-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

**Comment by iapicca** [comment]
Hi @Jackcui68 
can you please provide your `flutter run --verbose`
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by diegoveloper** [comment]
I have the same issue and it looks like similar to #1459
