### ISSUE TITLE
Resending SMS using "forceResendingToken" on verifyPhoneNumber

### ISSUE THREAD

**Issue by anraiki** [FirebaseExtended/flutterfire#2226]
I can't seem to figure out how to resend a SMS if the first one was lost or not received.

I dug into **verifyPhoneNumber** and found **forceResendingToken** but I couldn't find any documentation on how to use or apply it. 

Some guidance would be much apprecited.

```
  /// [forceResendingToken] The [forceResendingToken] obtained from [codeSent]
  ///   callback to force re-sending another verification SMS before the
  ///   auto-retrieval timeout.
```

**Comment by JemZubiri-Projects** [comment]
Same issue here. Been trying to figure it out for almost 5 hours now.

**Comment by TahaTesser** [comment]
Hi @anraiki  @JemZubiri-Projects 
Please check this [Stackoverflow answer](https://stackoverflow.com/a/54063190) and you can find  `PhoneCodeSent` [api](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/verifyPhoneNumber.html)

Hope it helps
Thanks

**Comment by anraiki** [comment]
@TahaTesser Hi Taha, that answer and solution leads back to this: https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/verifyPhoneNumber.html

Which still does not explain properly how to use `forceResendingToken`.

The  `PhoneCodeSent` executes after an SMS is sent but I am trying to do a manual resend in case the user finds that they have not received their code.

**Comment by JemZubiri-Projects** [comment]
Need this ASAP. Please provide an explanation on how to use it because that was our problem.

**Comment by anraiki** [comment]
It's time for discovery!

I believe our next step is to hold onto the `forceResendingToken` and drop it into `verifyPhoneNumber` and call it again.

This should essentially rerun the function again and send the sms once more and loop back to the verification screen.

**Comment by JemZubiri-Projects** [comment]
Tried that and there are times that the OTP is not resending. Maybe because the timeout is not yet called?

If yours is working stably, can you please show me how you did yours? Thank you

**Comment by anraiki** [comment]
Seems to be working for me. It sent the same SMS code 3x from the same text services.

`await _auth.verifyPhoneNumber(
                          phoneNumber: "+1$truePhoneNumber",
                          timeout: const Duration(seconds: 5),
                          forceResendingToken: _forceResendingToken,
                          verificationCompleted: (AuthCredential phoneAuthCredential) async {
                            await _auth.signInWithCredential(phoneAuthCredential);
                            final FirebaseUser currentUser = await _auth.currentUser();
                            if( currentUser.uid.isNotEmpty ) {
                              await _pushSignIn(currentUser);
                            } else {
                              print("Could not get Current User");
                            }
                          },
                          verificationFailed: (AuthException authException) {
                            print('Phone number verification failed. Code: ${authException.code}. Message: ${authException.message}');
                            _alertError('There was an error in sending the code. Please contact us to help you sort this issue.');
                            return;
                          },
                          codeSent: (String verificationId, [int forceResendingToken]) async {
                            setState(() {
                              _loading = false;
                            });
                            _verificationId = verificationId;
                            _forceResendingToken = forceResendingToken;
                          },
                          codeAutoRetrievalTimeout: (String verificationId) {
                            // print("Time Out. Duration Exceeded");
                            _verificationId = verificationId;
                          }
                        );`

**Comment by dave-k** [comment]
@anraiki If the auto-retrieval times out, do you call  ````verifyPhoneNumber```` again?
I want to re-send the SMS code if the user does not receive the code.
Could you explain how I would do this with my code?

````
  Widget _verifyPhoneNumberButton() {
    return _codeSent ? SizedBox() : AppButton(
      text: 'VERIFY',
      onPressed: _disableVerifyButton ? null : () async {
        setState(() => _disableVerifyButton = true);
        /// TODO: add country_code_picker()
        final countryCode = '+1';
        String _phoneNumber = '$countryCode${_phoneEditingController.text}';
        _verifyPhoneNumber(_phoneNumber);
      }
    );
  }

  Future<void> _verifyPhoneNumber(String phoneNumber) async {
      
    // Triggered when an SMS is auto-retrieved or the phone number has been instantly verified.
    final PhoneVerificationCompleted verificationCompleted = (AuthCredential credential) async {
      print('verificationCompleted');
    };

    // Triggered when an error occurred during phone number verification.
    final PhoneVerificationFailed verificationFailed =
        (AuthException authException) {
      print('PhoneVerificationFailed ${authException.message}');
      setState(() {
        this._error = authException.message;
      });
    };

    // Triggered when an SMS has been sent to the users phone,
    final PhoneCodeSent codeSent = (String verificationId, [int forceResendingToken]) {
      print('codeSent forceResendingToken: $forceResendingToken');
      setState(() {
        this._verificationId = verificationId;
        this._forceResendingToken = forceResendingToken;
        this._codeSent = true;
      });
    };

    // Triggered when SMS auto-retrieval times out and provide a [verificationId].
    final PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout = (String verificationId) {
      print('codeAutoRetrievalTimeout verificationId: $verificationId');
      setState(() {
        this._verificationId = verificationId;
      });
    };

    await _authService.verifyPhoneNumber( 
      phoneNumber: phoneNumber,
      timeout: const Duration(seconds: 5),
      forceResendingToken: _forceResendingToken,
      verificationCompleted: verificationCompleted,
      verificationFailed: verificationFailed,
      codeSent: codeSent,
      codeAutoRetrievalTimeout: codeAutoRetrievalTimeout
    );
  }
````
