### ISSUE TITLE
Issue in getting subcollection from document in firebase

### ISSUE THREAD

**Issue by ShabanGomaa** [FirebaseExtended/flutterfire#2227]
I have an issue, I can't get subcollection from the document:
I have firestore db with
collection: collectionName
Inside collection documents and inside one document subcollection "items"

collectionName
Document1
Items <- subcollection
Item1
Item2
I use the following code but the items subcollection can't be retrieved from my db....

QuerySnapshot snapshot = await Firestore.instance
.collection('collectionName')
.orderBy("order")
.getDocuments();

then
snapshot.documents.forEach((document) {})

The document doesn't have the items subcollection

**Comment by TahaTesser** [comment]
Hi @ShabanGomaa 
Please take a look at  this [comment](https://github.com/flutter/flutter/issues/26561#issuecomment-454269410)

You have to get subcollection for documents

Thank you

**Comment by ShabanGomaa** [comment]
@TahaTesser thank you for ur reply
The comment is not my issue,
I need to bring all the documents with its own subcollections.
I have many documents (for ex doc1, doc2, etc), inside doc1 or doc2, etc... a subcollection "items"
and I need to load all documents with its subcollection at loading

**Comment by TahaTesser** [comment]
Hi @ShabanGomaa 
Please posts question on Stackoverflow 
Thank you
