### ISSUE TITLE
[CLOUD_FIRESTORE] endBefore works as endAt in iOS (includes passed document)

### ISSUE THREAD

**Issue by dzhamshed** [FirebaseExtended/flutterfire#2228]
**Describe the bug**
**endBefore** clause in firestore query includes the document which values were passed to the function in **iOS** (works similar to **endAt**). But it works correct in Android and doesn't include the document.

**To Reproduce**
1. create a document with timestamp field called **time** and id **testDocument**. 
2. get the created document **var doc = await Firestore.instance.collection('testCollection').document('testDocument').get()**
3. query data as **var snapshot = await Firestore.instance.collection('testCollection').orderBy('time', descending: true).endBefore([doc.data['time'].toDate()]).getDocuments()**
4. look at the length of the **snapshot.documents** it's 1 and it has the **doc**.

**Expected behavior**
The **doc** should not be included. It works in Android.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
