### ISSUE TITLE
[firebase_auth] provide more tooling for Twitter login

### ISSUE THREAD

**Issue by lukepighetti** [FirebaseExtended/flutterfire#223]
Right now there are no functional community packages to handle Twitter login on `firebase_auth`. Ideally it would work as well as the web sdks without much hassle on our end.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue (documented Twitter integration) & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

We do also have plans for a future release to remove the need for an additional package for the social providers.

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration

**Comment by lukepighetti** [comment]
The documentation tells us to bake our client secret into the app. AFAIK this is not required for the web sdk and it's bad practice for security. If I am mistaken can you please clarify? Thanks.
