### ISSUE TITLE
[FIREBASE_ADMOB] Update podspec to remove UIWebView references

### ISSUE THREAD

**Issue by zmeggyesi** [FirebaseExtended/flutterfire#2232]
**Describe the bug**
For a while now, Apple has been issuing a warning to users of this plugin for _ITMS-90809_, which specifies that as of April 2020, no more submissions that use the deprecated `UIWebView` API will be accepted.

The iOS component of this plugin still retains references to this API, as evidenced by the _Mobile Ads SDK Team_ member [here](https://groups.google.com/d/msg/google-admob-ads-sdk/QuZMbjIyxn8/nl8jYBpZCAAJ).

This means that a new version needs to be released in at most one week to avoid disruptions to _all users_ of this plugin.

**Comment by gysipos** [comment]
This issue is really concerning, especially because of the tight deadline!

**Comment by zmeggyesi** [comment]
The AdMob SDK team has confirmed release of the new version that removes all forbidden references - can we force a podspec update in the plugin to target at least AdMob SDK version 7.57.0?
cc @iapicca in caase he's the one coordinating work on this issue.

**Comment by iapicca** [comment]
@zmeggyesi 
I am not, but I do what I can to underline the issue.
thank you for reporting this

**Comment by alectogeek** [comment]
Guys? Any updates here? 
Google Admob sent me a letter asking to upgrade my GMA SDK version to 7.55 or higher

**Comment by blasten** [comment]
Internal bug: b/140559063

**Comment by blasten** [comment]
Run `pod update` in the location of your Podfile under the ios folder.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
