### ISSUE TITLE
Failed to establish connection with the application instance in Chrome. After Adding cloud_firestore 0.13.4+2 dependency 

### ISSUE THREAD

**Issue by abdullah432** [FirebaseExtended/flutterfire#2233]
**Describe the bug**
Before adding cloud-firestore dependency, everything work fine. After adding dependency following error occure.

**Error**
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a
firewall.

I create 3 different project and same error happened when cloud_firestore 0.13.4+2 dependency added.
**Channel checked: **beta, dev, master

**Comment by TahaTesser** [comment]
Hi @abdullah432 

First, make sure you've done setup for [web](https://pub.dev/packages/cloud_firestore#web) in your `index.html`

can you please provide your `flutter doctor -v` and `flutter run -d Chrome --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by abdullah432** [comment]
Thanks for reply. By some reason when i create new project again, it's start working. By my knowledge i set same setting. May be some minor mistake.
