### ISSUE TITLE
Support for Firebase.InstanceId

### ISSUE THREAD

**Issue by rgb1380** [FirebaseExtended/flutterfire#2234]
Hi,

Are there any plans to add support for Firebase.InstanceId in flutterfire?

Thanks,

**Comment by TahaTesser** [comment]
Hi @rgb1380 
Please checkout this [answer](https://stackoverflow.com/a/57388170)
Hope it helps
Thank you

**Comment by rgb1380** [comment]
Thanks for the link. Still would be good to include Firebase.InstanceId in the library if possible.
