### ISSUE TITLE
[cloud_functions] Strange function behaviour [HELP NEEDED]

### ISSUE THREAD

**Issue by erolasan** [FirebaseExtended/flutterfire#2235]
I have a very strange behaving cloud function, which totally stopped working recently. I think it might be due to my use async/await and promises and the function not having enough time I guess to fire the notification.
 
So I have a scheduled function that runs every hour and sends reminder notifications through FCM to the applicable users, at that time, using their device registration tokens. It worked perfectly when I had few users but as I got more users I started missing some notifications and eventually I stopped receiving any. I tried changing the structure and giving the function more time by returning a Promise but it still doesn't work. Now the strange thing is that when I test it and target only my account's devices it works, which leads me to the conclusion that either when I target the other users the function doesn't have enough time to trigger the FCM notification send or I am getting an error with some user and the function is getting terminated. I tested the latter with a lot of console.log's and didn't get any errors. 

So can someone please review my code and tell me what am i doing wrong please - https://gist.github.com/erolasan/89f198ca9bfc464d12256e98757dfa7a

I am using latest versions of both fcm and cloud functions. Thanks in advance! :)

**Comment by TahaTesser** [comment]
Hi @erolasan 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by erolasan** [comment]
I already have provided a code sample of the cloud function, as for the code of my app i have just implemented FCM and configured it, I don't think the issue is from the code of the app but rather the cloud function itself. Here are the logs from flutter doctor: 
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-BG)
    • Flutter version 1.12.13+hotfix.8 at /Users/erolasan/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/erolasan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
