### ISSUE TITLE
Erro de -Xlint:deprecation for details firebase_admob 0.9.3

### ISSUE THREAD

**Issue by JonatasCosta1983** [FirebaseExtended/flutterfire#2236]
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by TahaTesser** [comment]
Duplicate of [#438](https://github.com/FirebaseExtended/flutterfire/issues/438)
