### ISSUE TITLE
[firebase_auth] support linking multiple login providers to one account

### ISSUE THREAD

**Issue by lukepighetti** [FirebaseExtended/flutterfire#224]
Support linking an account to an existing account.

Currently if you sign up with Google and try to login with Facebook it throws an "email in use" error.

If you sign up with Facebook and sign in with Google it will replace the auth provider and login.

But there is no way to connect multiple accounts like there is in the web sdk.

**Comment by i6x86** [comment]
I think you can resolve it enabling multiple account signups with one email. You have this option in the console Auth section just below the different providers.

**Comment by lukepighetti** [comment]
@i6x86 That just creates multiple accounts. Supposedly there's a way to link multiple login providers to a single account.

**Comment by i6x86** [comment]
> @i6x86 That just creates multiple accounts. Supposedly there's a way to link multiple login providers to a single account.

ah I see, that was the same problem I was facing when google brought me here :) look at this link it might be helpful https://stackoverflow.com/questions/58357910/handle-different-firebase-auth-providers/58358054#58358054 in my case I've searched a way to link phone number to existing account, but it should work the same way for facebook sign up.

**Comment by lukepighetti** [comment]
I haven't tested it but that seems reasonable so I will close this issue!
