### ISSUE TITLE
[<Firebase Messaging>] <Multiline/Expandable push notification>

### ISSUE THREAD

**Issue by edumolins** [FirebaseExtended/flutterfire#2246]
I wanted to know if it is possible to modify the notification style when the text is very long and can be seen on multiple lines. In Android it was solved like this
```
NotificationCompat.Builder mBuilder = new NotificationCompat.Builder()
mBuilider.setStyle(new NotificationCompat.BigTextStyle().bigText(message))
```
But I haven't found anything about how to do it on Flutter. Thanks in advance

**Comment by rajeshzmoke** [comment]
Same question
Not sure why this was closed [Issue](https://github.com/flutter/flutter/issues/46953)

**Comment by Ehesp** [comment]
Hello, this type of functionality would come from a local notifications library such as https://pub.dev/packages/flutter_local_notifications

The FlutterFire plugins support FCM messages with basic notification support.
