### ISSUE TITLE
[Firebase_Analytics] Logging nested event 

### ISSUE THREAD

**Issue by mktdevcwi** [FirebaseExtended/flutterfire#2248]
Hello, I'm trying to log an event on firebase analytics with the setup mentioned below.
Thought it was supported, but couldn't find any place confirming or denying.
After trying to log it, all I receive is a parameter named `ga_extra_params_ct` with value `1`
(flutter project)

```
params = {
    post: [{
      'title': 'my_post_title',
      'current_likes': '3',
      'extra_info': 'my_extra_info',
    }]
  }

  await analytics.logEvent('post_like', params);
```
The reason is: I need to know the post name with more likes and the total count of current likes...

Is it possible to register this event without BigQuery?

**Comment by kirstywilliams** [comment]
Hey @mktdevcwi, this is covered with [#1036 ](https://github.com/FirebaseExtended/flutterfire/issues/1036) I'm closing this and you can follow the updates over there :).
