### ISSUE TITLE
[firebase_auth] How I get new credential in SignIn with Apple flow?

### ISSUE THREAD

**Issue by yuichirokato** [FirebaseExtended/flutterfire#2253]
**Is your feature request related to a problem? Please describe.**
Hi flutterfire team.
I tried to link multiple auth provider to an account.
And I tried to link Sign in with Apple credential to existing account refer to [firebase-ios-sdk document.](https://firebase.google.com/docs/auth/ios/apple#sign_in_with_apple_and_authenticate_with_firebase)
But I got error `PlatformException(ERROR_MISSING_OR_INVALID_NONCE, Duplicate credential received. Please try again with a new credential., null)` and I want to solve it.

This document describes how to resolve this kind of error as follows:
>If you want to link a Sign in with Apple credential to another account, you must first attempt to link the accounts using the old Sign in with Apple credential and then examine the error returned to find a new credential. The new credential will be located in the error's userInfo dictionary and can be accessed via the FIRAuthErrorUserInfoUpdatedCredentialKey key.

I want to get new credential from `error.userInfo[FIRAuthErrorUserInfoUpdatedCredentialKey]` for solve that error.
However, can not refer to `error.userInfo` from flutter side.

**Describe the solution you'd like**
I want get new credential when `ERROR_MISSING_OR_INVALID_NONCE` error occurred in Sign in with Apple flow.

**Additional context**
none.

Thank you.

**Comment by pixnbit** [comment]
Is Sign in with Apple feature being worked on? Apps are now getting rejected for not providing "Sign in with Apple" We would have to remove other social logins and email only. Please upvote and make this high priority.

**Comment by iapicca** [comment]
Hi @yuichirokato 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2048
) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Salakar** [comment]
Lets consolidate under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
