### ISSUE TITLE
[firebase_admob] Native Ads support documentation for Swift 

### ISSUE THREAD

**Issue by ahsanalidev** [FirebaseExtended/flutterfire#2257]
Documentation for implementing Native adds with AppDelegate.swift rather then AppDelegate.m file.

1. Converted this code 
```
@interface NativeAdFactoryExample : NSObject<FLTNativeAdFactory>
@end

@implementation NativeAdFactoryExample
- (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
                             customOptions:(NSDictionary *)customOptions {
  // Create GADUnifiedNativeAdView
}
@end
```
from the firebase_admob pub.dev to Swift because I have AppDelegate.swift file in Ios folder using online converter since I have no knowledge of swift
```
import FLTFirebaseAdMobPlugin
class NativeAdFactoryExample: NSObject, FLTNativeAdFactory {
    func createNativeAd(
        _ nativeAd: GADUnifiedNativeAd?,
        customOptions: [AnyHashable : Any]?) -> GADUnifiedNativeAdView? {
        // Create GADUnifiedNativeAdView
    }
}
```
 but when I write in Xcode it gives an error No such module 'FLTFirebaseAdMobPlugin'  

**Expected behavior**
Better documentation for adding native ads with swift or AppDelegate.swift

**Additional context**
I will be really grateful if some body help me out. Thanks in advance.

**Comment by caseta** [comment]
I am having similar troubles. 

I am trying to use `firebase_admob: ^0.9.3+2`. The documentation is not specific enough / is in Objective-C. I'm having compile time errors for iOS, but I'm not even trying to use Native Ads, only banner ads. Here is what I get when trying to build:

```
    In file included from /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:6:
    /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:4: error: expected a type
    - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
       ^
    /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:45: error: expected a type
    - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
                                                ^
    2 errors generated.

```

**Comment by ahsanalidev** [comment]
> I am having similar troubles.
> 
> I am trying to use `firebase_admob: ^0.9.3+2`. The documentation is not specific enough / is in Objective-C. I'm having compile time errors for iOS, but I'm not even trying to use Native Ads, only banner ads. Here is what I get when trying to build:
> 
> ```
>     In file included from /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:6:
>     /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:4: error: expected a type
>     - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
>        ^
>     /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:45: error: expected a type
>     - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
>                                                 ^
>     2 errors generated.
> ```

For Banner Ads you don't need to specify anything in the AppDelegate file just use it directly inside your flutter app it will work.

**Comment by jpvanmuijen** [comment]
Did anyone find any solution, documentation or tutorial yet?

**Comment by ahsanalidev** [comment]
I tried to implement the native ads but later found out they act just like banner ads and I wanted to implement them in list view. I found a plugin in pub.dev. https://pub.dev/packages/native_ads and implemented ads with that.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
