### ISSUE TITLE
[Firestore.instance.settings(timestampsInSnapshotsEnabled: true)]=> Here "timestampsInSnapshotsEnabled" is working or not available

### ISSUE THREAD

**Issue by SaiVaraPrasad-3** [FirebaseExtended/flutterfire#2259]
**Describe the bug**
I am using the version cloud_firestore-0.13.4+2 , for the project and i want add the Firestore settings for that i was adding it to Main.dart in **void main() async{Firestore.instance.settings(timestampsInSnapshotsEnabled: true)} ** but it not accepted here, any solution...?

**To Reproduce**
1. install Library cloud_firestore - 0.13.4+2
2. Add the lines in main.dart as in screenshot
4. u won't see that "timestampsInSnapshotsEnabled" is available

**Expected behavior**
It must accept the "timestampsInSnapshotsEnabled", if not how to do :{

**Additional context**
![bug](https://user-images.githubusercontent.com/59758830/77852180-d656d900-71fa-11ea-9948-2dee31278420.JPG)

**Comment by iapicca** [comment]
Hi @SaiVaraPrasad-3 
it is possible that is just a [warning](https://stackoverflow.com/questions/54695367/firebase-database-error-for-timestampsinsnapshotsenabled)
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
Thank you

**Comment by Akshay0701** [comment]
hey can anyone give solution on this?

**Comment by Salakar** [comment]
Hey all, unfortunately this Setting has long been deprecated and removed from some of the underlying SDKs so we can no longer support it. The recommendation is to update your code to expect Timestamp objects and stop using this setting.

If you were previously setting this value as `true` then you don't need to change anything in your code (other than removing the setting) as this now the default behaviour.
