### ISSUE TITLE
[Firestore.instance.settings(timestampsInSnapshotsEnabled: true)]=> Here "timestampsInSnapshotsEnabled" is not working or not available 

### ISSUE THREAD

**Issue by SaiVaraPrasad-3** [FirebaseExtended/flutterfire#2260]
**Describe the bug**
I am using the version cloud_firestore-0.13.4+2 , for the project and i want add the Firestore settings for that i was adding it to Main.dart in **void main() async{Firestore.instance.settings(timestampsInSnapshotsEnabled: true)} ** but it not accepted here, any solution...?

**To Reproduce**
   1. install Library cloud_firestore - 0.13.4+2
    2.Add the lines in main.dart as in screenshot
    3.u won't see that "timestampsInSnapshotsEnabled" is available

**Expected behavior**
It must accept the "timestampsInSnapshotsEnabled", if not how to do :{
![bug](https://user-images.githubusercontent.com/59758830/77852531-d2c45180-71fc-11ea-9f54-020c138479c4.JPG)

**Additional context**
![bug](https://user-images.githubusercontent.com/59758830/77852546-dbb52300-71fc-11ea-9ad5-bb6c437983f9.JPG)

**Comment by TahaTesser** [comment]
Hi @SaiVaraPrasad-3 
If i am not mistaken this feature is deprecated [changelog](https://pub.dev/packages/cloud_firestore#0130)
There is no parameter in [settings](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Firestore/settings.html)

Closing, as this isn't an issue with cloud_firestore itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by SaiVaraPrasad-3** [comment]
Yeah...it worked no problem..

**Comment by Akshay0701** [comment]
@TahaTesser  thank you man
