### ISSUE TITLE
[Codelab] Firebase for Flutter Codelab missing firebase_core

### ISSUE THREAD

**Issue by rubensdemelo** [FirebaseExtended/flutterfire#2261]
Once firebase_core is required to all Flutter-Firebase apps, would be nice if codelab cover this topic.

https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#3

<img width="846" alt="Screen Shot 2020-03-29 at 21 03 14" src="https://user-images.githubusercontent.com/1351177/77864735-b6c2af00-7200-11ea-9c13-8f303570b087.png">

**Comment by Salakar** [comment]
Closing as these code labs no longer exist.
