### ISSUE TITLE
[firebase_dynamic_links] creating a link for a different app redirects to the same app on iOS

### ISSUE THREAD

**Issue by omarhuss** [FirebaseExtended/flutterfire#2264]
**Describe the bug**
I have two apps, one for the customer, another for the business. When generating a dynamic link from the business app for the customer app, after tapping on the link, it goes to the same business app, this is only on iOS, Android works as expected.

**To Reproduce**
1. Generate a dynamic link that has the customer app parameters.
2. Tap on the generated link from an iOS device.
3. The app redirects the user to the business app.

**Expected behavior**
The app should redirect the user to the customer app (the customer app's iOS parameters are given and matched).

**Additional context**
You may try this as well to check the behavior, make two different apps, each has a unique bundle ID, create a dynamic link from an app to the other, you'll see it always goes to the same app that the link is generated from. I use ` firebase_dynamic_links: ^0.5.0+11`.

Flutter Doctor Summary:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @omarhuss 
can you please provide your  and `flutter run --verbose`?
Thank you
