### ISSUE TITLE
Requesting Consent from European Users

### ISSUE THREAD

**Issue by rachidev84** [FirebaseExtended/flutterfire#2274]
I want to know how to set request for European Users, I search on youtube and pu.dev, I found plugin, but I can't trust of something very sensitive not developed by google, hope I'll find solution from you

**Comment by TahaTesser** [comment]
Hi @rachidev84 
Please check this  [Privacy and Security in Firebase
](https://firebase.google.com/support/privacy)

We don't provide support for. 3rd party plugins anyway
Closing since this isn't an issue 
if you disagree please write in the comments and I will reopen it 
Thank you
