### ISSUE TITLE
Image Picker camera is opening twice time  for the first time after permission allow

### ISSUE THREAD

**Issue by shruti-techindustan** [FirebaseExtended/flutterfire#2279]
I am using 29 compile SDK Version. When I capture image from camera after permission allow, it open camera and  capture image it again open camera and then capture image. means twice time. 
I am only getting issue when permission is requested and tap on allow. It open the camera twice and same for gallery. But its working fine in 28 compile sdk.

**Comment by TahaTesser** [comment]
Hi @shruti-techindustan 
Do you mean [image_picker](https://pub.dev/packages/image_picker)
If yes, please create your issue on [Flutter GitHub](https://github.com/flutter/flutter/issues)

This issue isn't related to flutterfire 
if you disagree please write in the comments and I will reopen it 
Thank you
