### ISSUE TITLE
[<Firebase Messaging>] android push data

### ISSUE THREAD

**Issue by armygui** [FirebaseExtended/flutterfire#2280]
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("push data $message")
      },
    );
Android device foreground push gets 2 same results,Print in above code

**Comment by TahaTesser** [comment]
Hi @armygui 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by iapicca** [comment]
Hi @armygui 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2278
) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by armygui** [comment]
I think this problem is because the corresponding result of the front desk push in android is transmitted through the form of broadcasting. I found only one result in the service printing in the source code, but there are two values corresponding to the printing in the broadcast.

**Comment by TaiHK** [comment]
> Hi @armygui
> I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2278) addressing the case you described.
> Please follow up on that issue,
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

Hi @iapicca 
Please confirm [issue](https://github.com/FirebaseExtended/flutterfire/issues/2278) .
Thank you
