### ISSUE TITLE
Documentation contradiction

### ISSUE THREAD

**Issue by stephenhuey** [FirebaseExtended/flutterfire#2295]
The following page on the Firebase site says "Note: All Flutter-Firebase apps, both iOS and Android versions, require the firebase_core plugin for Flutter."

https://firebase.google.com/docs/flutter/setup

But firebase_core is missing from this page of the Firebase for Flutter codelab:

https://codelabs.developers.google.com/codelabs/flutter-firebase/#3

This is all it mentions adding to your project:

dependencies: flutter: sdk: flutter cloud_firestore: ^0.13.0+1 # new

I just tried creating a new project in Android Studio and was successfully able to read from Cloud Firestore without having firebase_core in there.  What's the verdict?  Is firebase_core no longer needed by the cloud_firestore plugin?  Whose docs should be updated?  This page implies cloud_firestore depends on firebase_core:

https://pub.dev/packages?q=dependency%3Afirebase_core

**Comment by Salakar** [comment]
Hey, our firebase_core rework has now landed on master via #2890 - we hope to start publishing preview releases to test out next week which should solve this issue (and others) with the new documentation website.

Thank you for raising this issue 👍
