### ISSUE TITLE
[cloud_functions] Cloud Functions Web CORS issue and empty request body

### ISSUE THREAD

**Issue by alisonthemonster** [FirebaseExtended/flutterfire#2298]
**Describe the bug**
Using the cloud_functions library(`cloud_functions: ^0.4.2+3`) in my Flutter Web project I tried the following code:
```
final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
      functionName: 'myFunctionName',
    );
dynamic response = await callable.call(<String, dynamic>{
      'key': value,
      'key1': value,
      'key2': value
    });
```

When it runs I see this error in the console: 
```
Access to fetch at 'https://us-central1-<mycloudfunction>.cloudfunctions.net/myFunctionName' from origin 'http://localhost:56152' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I also see that in my Cloud Functions logs the function is being invoked but **my request body is empty despite setting values there**. I have tested my functions using Postman and they work as expected there.  This [StackOverflow question](https://stackoverflow.com/questions/57293249/i-have-firebase-cloud-function-that-working-final-when-request-from-postman-but) had the same issue but no mention of CORS.

**Additional context**
In my searching people suggest to add CORS to your function, but I have tried several approaches and not had success yet. Hoping for some guidance there. Here is my function code:
```
const cors = require('cors')({
    origin: true,
  });

exports.myFunction = functions.https.onRequest(async (req, res) => {
    //res.set('Access-Control-Allow-Origin', '*'); //Tried this with no success
    //cors(req, res, () => {}); //Also tried this with no success

    // logic here

    res.status(200).json({key: value});
}
```

Thank you in advance!

**Comment by alisonthemonster** [comment]
I saw this [answer on stackoverflow](https://stackoverflow.com/a/57033110/2752082) where it mentions using regular HTTPS triggered function vs using callable functions. Flutter is expecting a callable function and my function code is using https triggered functions. 

So switched my cloud function to a callable function but sadly had even less luck. I still saw the same CORS error and this time I wasn't able to see any logs at all for my function. 

I also tried adding this to my function and didn't have success there either:
```
res.set('Access-Control-Allow-Origin', '*');
res.set('Access-Control-Allow-Methods', 'GET, PUT, POST, OPTIONS');
res.set('Access-Control-Allow-Headers', '*');
```

**Comment by jans-y** [comment]
We had the same issue. We've resolved it by specifying the region.

```
CloudFunctions.instance
        .getHttpsCallable(functionName: 'myFunctionName')
        .call({})
```
⬇️⬇️⬇️
```
CloudFunctions(region: 'europe-west1')
        .getHttpsCallable(functionName: 'myFunctionName')
        .call({})
```

**Comment by alisonthemonster** [comment]
I'll have to go back and try the region trick! In the end I stopped using the flutter firebase library and just called the endpoint using http package and didn't run into any issues that way.

**Comment by russellwheatley** [comment]
I'm going to close this issue as I believe it has been resolved by setting the region. Will reopen if that is not the case.
