### ISSUE TITLE
[FIREBASE_ADMOB] RewardedVideoAd.instance.load(adUnitId: ) targeting info should be required

### ISSUE THREAD

**Issue by emmett-deen** [FirebaseExtended/flutterfire#2303]
**Describe the bug**
On ios getting NSException when trying to load a RewardedVideoAd

**To Reproduce**
Call RewardedVideoAd.instance.load(adUnitId: <your id>) without targeting info

**Expected behavior**
Load an ad

**Additional context**
Targeting info is not a required parameter and should be to help developers avoid this crash

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
