### ISSUE TITLE
[cloud_firestore] snapshots() should have a changed filter

### ISSUE THREAD

**Issue by illion20** [FirebaseExtended/flutterfire#2308]
**Is your feature request related to a problem? Please describe.**
Right now listening to a query always return all documents:
`query.where(...).snapshots().listen(...)`
when the collection grows huge this will be a problem

**Describe the solution you'd like**
Is it possible to add a flag in the snapshots() function to filter only the documentChanges to be sent across the wire?
`.snapshots(changed: true)`

**Additional comments**
Moved here
https://github.com/flutter/flutter/issues/54042

**Comment by Ehesp** [comment]
It's only possible to request document changes via `includeMetadataChanges`, however this still returns all documents WITH the changes. 

I'll close this off as it's a native SDK limitation rather than this library.

**Comment by Ehesp** [comment]
That being said, it is technically does make sense to ignore the actual documents being sent from native which would help speed things up - the actual reads would still happen though.

I'll bring this one up as it would require non-standard API changes.
