### ISSUE TITLE
unable to build project after adding firebase_auth

### ISSUE THREAD

**Issue by Xgamefactory** [FirebaseExtended/flutterfire#231]
running with stacktrace getting such error 
**./gradlew assembleDebug --stacktrace**

> Task :app:processDebugGoogleServices FAILED

build.gradle (project)
```
 classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.3.0'
```
build.gradle (app)
also has this at the bottom
apply plugin: 'com.google.gms.google-services'

no error in flutter doctor

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E2035, locale en-TR)
    • Flutter version 1.9.1+hotfix.2 at /Users/fersmart/SDK_all/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fersmart/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by Mirarsoft** [comment]
I got the same issue, if you change 'classpath 'com.google.gms:google-services:4.3.0' to 'classpath 'com.google.gms:google-services:3.2.0', you will be able to build and run, but if you try to sign in (google sign in), it will crash. Google mentioned flutter supports this version at the moment. Wondering how they could run this app with the latest version!!

**Comment by Ehesp** [comment]
Going to close this due to inactivity / age.

Based on the error, I think this is because either the emulator doesn't have Play Services enabled, or you are missing the native config files from the Firebase console.

If you are still having the problem, please create a new issue following the issue template.
