### ISSUE TITLE
[firebase_analytics] Fix deprecated api

### ISSUE THREAD

**Issue by alectogeek** [FirebaseExtended/flutterfire#2315]
Standart `eccomerce_purchase` event (and many others, I guess) has been deprecated. Need a support for new events API

https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#public-static-final-string-ecommerce_purchase

**Comment by tonzingj** [comment]
I am also facing this issue, any progress or ETA?

Would also need the functionality for multiple items being purchased in the one transaction.

**Comment by TahaTesser** [comment]
Closing this in favor of https://github.com/FirebaseExtended/flutterfire/issues/3876
