### ISSUE TITLE
[cloudFirestore] runTransation ObjC implementation sends two replies on error

### ISSUE THREAD

**Issue by stuartmorgan** [FirebaseExtended/flutterfire#2317]
[This code](https://github.com/FirebaseExtended/flutterfire/blob/4d7b2bdd7fbdee65551754968b140653ea16128f/packages/cloud_firestore/cloud_firestore/darwin/Classes/FLTCloudFirestorePlugin.m#L537) is missing either an early return or an `else`; currently the error case calls `result` with an error, then falls through and calls `result` again. This violates the message channel API contract, and will cause error logging in the macOS embedding.

**Comment by Ehesp** [comment]
Could you post some code to which causes this error? Appreciate it may be simple but it'll help us replicate the problem.

**Comment by stuartmorgan** [comment]
It was found via source inspection while looking into a different issue. I don't have source code offhand that will reproduce it.

However, it's obviously incorrect, without needing to run it. I wrote the Flutter engine code that runs when `result` is called though, and I guarantee you that calling it twice is incorrect. [Here](https://github.com/flutter/engine/blob/master/shell/platform/darwin/common/framework/Headers/FlutterChannels.h#L140) is the API contract, which you can see indicates that you are indicating both that the code failed and succeeded which is clearly wrong, and [here](https://github.com/flutter/engine/blob/master/shell/platform/darwin/macos/framework/Source/FlutterEngine.mm#L355) is the log statement that will print if that error path is taken.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved (listed in changelog) in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
