### ISSUE TITLE
[firebase_auth] [IOS ONLY] MissingPluginException on calling method verifyPhoneNumber 

### ISSUE THREAD

**Issue by rohandalvi** [FirebaseExtended/flutterfire#2321]
**Describe the bug**
I am encountering the following error when calling the verifyPhoneNumber method using Firebase_Auth plugin. I am only experiencing this on IOS , works fine on android platform.

Version of firebase_auth:  0.15.5+3 

Stacktrace:

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method verifyPhoneNumber on channel plugins.flutter.io/firebase_auth)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      MethodChannelFirebaseAuth.verifyPhoneNumber (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:352:20)
#2      FirebaseAuth.verifyPhoneNumber (package:firebase_auth/src/firebase_auth.dart:266:42)

Flutter doctor -v :

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G3020, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/rohandalvi/flutter/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rohandalvi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 11 Pro • A07BF3E2-372C-416D-A619-2F64D61FD90F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

**To Reproduce**
Calling the following method:
`await FirebaseAuth.instance.verifyPhoneNumber(
        phoneNumber: phoneNo,
        timeout: const Duration(seconds: 5),
        verificationCompleted: verified,
        verificationFailed: verificationfailed,
        codeSent: smsSent,
        codeAutoRetrievalTimeout: autoTimeout);
  }`

**Expected behavior**
I expect the method to work uniformly as on Android (proceed with sending SMS code) and subsequently signing in if the code entered matches with the auth credential token.

**Additional context**
As mentioned above, the same method seems to work flawlessly on android. Upon reading on similar issues elsewhere, I also tried changing the `ios deployment target` to `9.3` but that didn't help.

**Comment by TahaTesser** [comment]
Hi @rohandalvi 
can you please provide your `flutter run --verbose` running on iOS? 
Thank you

**Comment by rohandalvi** [comment]
@TahaTesser  Please see attached log file. 

[flutter_run_ios.log](https://github.com/FirebaseExtended/flutterfire/files/4500859/flutter_run_ios.log)

**Comment by helenaford** [comment]
Thanks @rohandalvi. I'm going to close this and consolidating issues relating to missing plugin exception for firebase_auth on iOS under #1489.
