### ISSUE TITLE
platform exception with firebase google_sign_in(Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by sumitrvi** [FirebaseExtended/flutterfire#2324]
I having this issue with ios.
Dependencies
 google_sign_in: ^4.1.1
  firebase_auth: ^0.15.3+1

1 .flutter create bug.
[✓] Flutter: is fully installed. (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15 19A583, locale en-IN)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.1)
[✓] Android Studio: is fully installed. (version 3.3)
[✓] VS Code: is fully installed. (version 1.43.2)
[✓] Connected device: is fully installed. (1 available)
2. flutter run --verbose.
[DEVICE LOG] 2020-04-08 13:32:25.956959+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
boringssl_context_handle_warning_alert(1894) [C8.1:2][0x7fedf176c800] write alert, level: warning, description: close notify
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957149+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
boringssl_session_disconnect(539) [C8.1:2][0x7fedf176c800] SSL_shutdown 0
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957329+0530  localhost Runner[36946]: (libnetwork.dylib) [com.apple.network:] nw_flow_disconnected [C8.1
2404:6800:4002:80c::200a.443 cancelled socket-flow ((null))] Output protocol disconnected
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957840+0530  localhost Runner[36946]: (libnetwork.dylib) [com.apple.network:]
nw_connection_report_state_with_handler_on_nw_queue [C8] reporting state cancelled
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957997+0530  localhost Runner[36946]: (CFNetwork) [com.apple.CFNetwork:Coalescing] removing all entries
config 0x600000f57600
[        ] [DEVICE LOG] 2020-04-08 13:32:25.958179+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
nw_protocol_boringssl_remove_input_handler(1010) [C8.1:2][0x7fedf176c800] nw_protocol_boringssl_remove_input_handler forced true
[        ] [DEVICE LOG] 2020-04-08 13:32:25.959368+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
nw_protocol_boringssl_remove_input_handler(1028) [C8.1:2][0x7fedf176c800] Transferring nw_protocol_boringssl_t handle back into ARC for autorelease
[        ] [DEVICE LOG] 2020-04-08 13:32:25.960141+0530  localhost Runner[36946]: (Flutter) [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception:
PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)
[        ] [DEVICE LOG] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] [DEVICE LOG] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
[        ] [DEVICE LOG] #3      MethodChannelFirebaseAuth.signInWithCredential
(package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:161:23)
[        ] [DEVICE LOG] #4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
[        ] [DEVICE LOG] #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
[        ] [DEVICE LOG] #6      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:205:42)
[        ] [DEVICE LOG] #7      _SigninScreenState.socialLogin (package:down_beatflutterproject/screens/signinscreen.<…>
[        ] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and
inspect the error details for more information., null)
[        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] <asynchronous suspension>
[        ] #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
[        ] #3      MethodChannelFirebaseAuth.signInWithCredential
(package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:161:23)
[        ] #4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
[        ] #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
[        ] #6      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:205:42)
[        ] #7      _SigninScreenState.socialLogin (package:down_beatflutterproject/screens/signinscreen.<…>
3. flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15 19A583, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/theninehertz/Desktop/hybrid/sumit/fluttersdk/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/theninehertz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode 11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (1 available)
    • iPhone 7 • 9EED1588-2FE1-4F78-8148-F002D7B43838 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Please enable google sign in option in your firebase console then try signing in
Thank you

**Comment by sumitrvi** [comment]
@TahaTesser That's already enabled

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Can you please provide your `flutter run -v` from root of your app while trying to sign in?
Thank you

**Comment by andrzejchm** [comment]
While I faced the same problem, I've tried the same code on Android, there, I got this stacktrace, which is way more descriptive than iOS version:
```
E/flutter ( 6934): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ERROR_DYNAMIC_LINK_NOT_ACTIVATED, Please activate Dynamic Links in the Firebase Console and agree to the terms and conditions. [ FDL domain is not configured ], null)
E/flutter ( 6934): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6934): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 6934): <asynchronous suspension>
E/flutter ( 6934): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 6934): #3      MethodChannelFirebaseAuth.sendLinkToEmail (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:98:20)
E/flutter ( 6934): #4      FirebaseAuth.sendSignInWithEmailLink (package:firebase_auth/src/firebase_auth.dart:121:42)
E/flutter ( 6934): #5      FirebaseSendMagicLinkAction.execute (package:data/src/firebase/actions/firebase_send_magic_link_action.dart:15:21)
E/flutter ( 6934): #6      FirebaseRepository.sendMagicLink (package:data/src/firebase/firebase_repository.dart:11:96)
E/flutter ( 6934): #7      SendMagicLinkUseCase.execute (package:domain/src/usecases/send_magic_link_use_case.dart:13:19)
E/flutter ( 6934): #8      LoginPresenter.onSendMagicLinkClicked (package:presentation/src/login/login_presenter.dart:17:10)
E/flutter ( 6934): #9      LoginPage.sendMeMagicLinkButton.<anonymous closure> (package:groceryshopper/src/login/login_page.dart:65:34)
E/flutter ( 6934): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:14)
E/flutter ( 6934): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 6934): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6934): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 6934): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 6934): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 6934): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter ( 6934): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 6934): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 6934): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 6934): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 6934): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 6934): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 6934): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6934): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6934): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6934): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6934): #27     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 6934): #28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6934): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6934): #30     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 6934): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter ( 6934): 
```

For reference, here is the stacktrace from iOS:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannelFirebaseAuth.sendLinkToEmail (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:98:20)
#4      FirebaseAuth.sendSignInWithEmailLink (package:firebase_auth/src/firebase_auth.dart:121:42)
#5      FirebaseSendMagicLinkAction.execute (package:data/src/firebase/actions/firebase_send_magic_link_action.dart:15:21)
#6      FirebaseRepository.sendMagicLink (package:data/src/firebase/firebase_repository.dart:11:96)
#7      SendMagicLinkUseCase.execute (package:d<…>

```

I believe this is also relevant for #124 and #1514

**Comment by Salakar** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.

**Comment by sumitrvi** [comment]
@Salakar is this issue resolve or not.?

**Comment by TahaTesser** [comment]
Hi @sumitrvi 
Mention duplicate [#1456](https://github.com/FirebaseExtended/flutterfire/issues/1456) is still open. Please follow up there
