### ISSUE TITLE
[firebase_messaging] Support getting the instance ID in addition to the token.

### ISSUE THREAD

**Issue by jjones-figure** [FirebaseExtended/flutterfire#2327]
**Is your feature request related to a problem? Please describe.**
Currently `firebase_messaging` only supports getting the instance ID token. Our use case requires the stable ID. This is not currently exposed in the flutter plugin.

**Describe the solution you'd like**
A method for retrieving the stable instance ID.

**Comment by talent-apps** [comment]
See also: #1924

**Comment by jjones-figure** [comment]
@talent-apps FYI #2328

**Comment by Ehesp** [comment]
Dup of https://github.com/FirebaseExtended/flutterfire/issues/2327

**Comment by jjones-figure** [comment]
@Ehesp this is a dupe of itself?
