### ISSUE TITLE
[firebase_crashlytics] Native crash report is missing recorded logs

### ISSUE THREAD

**Issue by audkar** [FirebaseExtended/flutterfire#233]
**Describe the bug**
Customs logs are kept in memory instead of imeadeatly register in Crashlytics service. When app crashes, logs are lost. [Problematic code](https://github.com/FirebaseExtended/flutterfire/blob/f6dc29c4455afca1fe45d5cde58800874b080fb2/packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L72)

**To Reproduce**
1. Log some messages with `Crashlytics.log(...)`
2. Make native crash
3. Observe registered report. It is missing logs.

**Expected behavior**
Crash report contains emitted custom logs in Craslytics console `Logs` tab.

**Additional context**
Snippet to make native crash on android:
```java
new Thread(){
  public void run(){
    System.out.println("Runnable running");
    Crashlytics.getInstance().crash();
  }
}.start();
```

**Comment by Salakar** [comment]
A new Crashlytics plugin has now landed on master which should solve this issue.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin: https://firebase.flutter.dev/docs/migration/
