### ISSUE TITLE
[firebase_messaging] Unicode char

### ISSUE THREAD

**Issue by sante85** [FirebaseExtended/flutterfire#2333]
**Describe the bug**
Unicode char are not encoded

**To Reproduce**
if an push notification i insert a unicode char, for example 🔥 (U+1F525), this is not encoded

**Expected behavior**
encode automatic

firebase messaging last version

Best Regards

**Comment by TahaTesser** [comment]
Hi @sante85 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
