### ISSUE TITLE
[firebase_crashlytics] All native crashed on Main Thread reported under single crash report

### ISSUE THREAD

**Issue by audkar** [FirebaseExtended/flutterfire#234]
**Describe the bug**
Reported error has only Dart side stacktrace when crash happens in plugin on main Android thread after calling `ChannelMethod`. So tip of stacktrace always has something like this:
```
StandardMethodCodec.decodeEnvelope (message_codecs.dart:569)
MethodChannel.invokeMethod (platform_channel.dart:316)
<...>
```
So different crashes gets collected under single report in Crashlytics.

**To Reproduce**
1. Call plugin method over `ChannelMethod` and throw Exception on Android side.
2. Call plugin method over `ChannelMethod` and throw **different** Exception on Android side.
3. Observe in Crashlytics console. Crashes are grouped under single item AND missing important information about crashes on native side (native side stacktraces).

**Expected behavior**
Android side stactrace is reported and visible. That should make different crashes reported as different groups in Crashlytics.

**Additional context**
Any different Exceptions can be thrown on native side e.g.
```java
@Override
public void onMethodCall(MethodCall call, Result result) {
  throw new IllegalStateException("omg an error");
}
```

**Comment by danielgomezrico** [comment]
This is still happening on version `firebase_crashlytics: 0.2.3`

**Comment by Salakar** [comment]
I think this one is still valid, maybe we should slice the first 2 stack trace elements off in this scenario - though would need confirmation that this is consistent.

**Comment by rrousselGit** [comment]
@Salakar Why test only the first two stacktrace elements? Why not test all of them?

**Comment by Salakar** [comment]
> @Salakar Why test only the first two stacktrace elements? Why not test all of them?

Let's do that

**Comment by kmandrika** [comment]
Hi @audkar,

We've recently fixed grouping of issues on the backend, could you let me know if this is still happening? On a different note, Crashlytics is currently EAPing a new SDK that supports features such as on-demand fatals, any interest in trying it out? If so, please reach out to me on the Firebase community channel (firebase-community.slack.com) on Slack or Twitter (kmandrika@) to let me know where I can send instructions.

Thanks,
Konstantin

**Comment by audkar** [comment]
>  could you let me know if this is still happening?

That's good news that Flutter support is moving forward! However I will not be able to verify if the original issue was solved. We are not using Flutter anymore.
