### ISSUE TITLE
[cloud_functions] Error being swallowed by Future

### ISSUE THREAD

**Issue by cacianokroth** [FirebaseExtended/flutterfire#2348]
This is returning a promise that is not resolved, so it will never fall into that catch and it never returns a Cloud Functions Exception.

https://github.com/FirebaseExtended/flutterfire/blob/bdb95fcacf7cf077d162d2f267eee54a8b0be3bc/packages/cloud_functions/cloud_functions/lib/src/https_callable.dart#L42-L53|

**Comment by Ehesp** [comment]
I think this is a valid question - the code needs to be using `await` for the catch to throw. Right now it's being swallowed as an unhandled exception in the Future.

**Comment by cacianokroth** [comment]
Exactly, catch is being ignored.

**Comment by Salakar** [comment]
This was fixed in the reworked version last year. Thanks
