### ISSUE TITLE
[firebase_messaging 5.1.6] Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'

### ISSUE THREAD

**Issue by earyzhe** [FirebaseExtended/flutterfire#235]
**Describe the bug**
After doing these two steps in the process of using ffirebase_messaging 5.1.6 or Android

![Screenshot 2019-09-29 at 11 19 56](https://user-images.githubusercontent.com/26453863/65829951-1c160180-e2ab-11e9-8dfb-4e0ff9cc7e99.png)

This error message is thrown.
> Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'

**Expected behavior**
It should not throw errors when following instructions, or give clear solutions to the problem.

**Additional context**
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/earyzhe/SDKs/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/earyzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • Andrew's iPhone           • 6aa0c9719a85c174869a09656237b42f23701a91 • ios         • iOS 13.1.1
    • iPhone 7 Plus             • 7E90D404-B505-4D5D-BFF5-0CCFB46D417C     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-11-1 (simulator)

**Comment by BondarenkoStas** [comment]
@earyzhe Closing the issue in favour to https://github.com/FirebaseExtended/flutterfire/issues/57 to avoid duplication, please follow it there.
