### ISSUE TITLE
[cloud_firestore 21.4.2]: FirestoreCallCredentials exception thrown

### ISSUE THREAD

**Issue by abhinavc** [FirebaseExtended/flutterfire#2351]
Hi, 

I see the following in the log 
```
(21.4.2) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.FirebaseException: 
An internal error has occurred. [ yRequests to this API securetoken.googleapis.com method 
google.identity.securetoken.v1.SecureToken.GrantToken are blocked.
```

when I trigger the code below
```dart
Firestore.instance
              .collection("buttons")
              .document()
              .setData({'message': 'pressed'})
              .catchError((e) => print(e.toString()));
```
even though I have enabled `Cloud Firestore API` for my Android and iOS API keys in Google Cloud Console. 
 
As only registered users will ever get to the point where they can trigger the code above, I do not need them to sign-in again. Hence, I **enabled Anonymous Sign-in* in Firebase Console. 

My setup is as follows: 
```
   cloud_firestore: ^0.13.4+2 (pubspec.yaml)
   implementation 'com.google.firebase:firebase-firestore:21.4.2' (build.gradle)
```

I am sure I am making one or more faulty assumptions about how Firestore APIs work. 
Hence, any help would be most appreciated. 

Thanks
Abhinav.

**Comment by abhinavc** [comment]
I enabled `Token Services API` in Google Cloud Console - along with `Anonymous Sign-in`. 
And things seems to be working now.  Still need to test on iOS. 

But have I enabled too much? If yes, then what is the minimal setup required on Google Cloud Console? If not, then should these changes be captured in the plugin's doc also?

**Comment by TahaTesser** [comment]
Hi @abhinavc 
Enabling is required for new projects
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
Thank you
