### ISSUE TITLE
[Firebase Analytics] Analytics for flutter web is not implemented

### ISSUE THREAD

**Issue by bb-ac** [FirebaseExtended/flutterfire#2352]
Uncaught (in promise) Error: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)
    at Object.throw_ [as throw] (errors.dart:195)
    at MethodChannel._invokeMethod (platform_channel.dart:154)
    at _invokeMethod.next (<anonymous>)
    at onValue (async_patch.dart:47)
    at _RootZone.runUnary (zone.dart:1439)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:141)
    at handleValueCallback (future_impl.dart:682)
    at Function._propagateToListeners (future_impl.dart:711)
    at _Future.new.[_completeWithValue] (future_impl.dart:526)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:556)
    at Object._microtaskLoop (schedule_microtask.dart:43)
    at _startMicrotaskLoop (schedule_microtask.dart:52)
    at async_patch.dart:168

1. Run a Flutter web app that includes firebase analytics: flutter run -d chrome 
2. Open Developer Tools/Console in Chrome
3. Observe the error above (and other similar errors)

**Comment by TahaTesser** [comment]
Hi @bb-ac 
Please follow this [solution](https://stackoverflow.com/a/59739455) and make sure you done all of them
Thanks

**Comment by nstrelow** [comment]
Will there be a way of using the flutter_analytics package or is using firebase package the official recommendation?

**Comment by bb-ac** [comment]
> Hi @bb-ac
> Please follow this [solution](https://stackoverflow.com/a/59739455) and make sure you done all of them
> Thanks

@TahaTesser I have the config recommended in the solution in my index.html page. It doesn't work. Most likely because it requires different elements in flutter code for web as compared with mobile. That's not good. The same config should work across all platforms

**Comment by senordonfelipe** [comment]
I am currently experimenting with a flutter web app and the example mentioned by @TahaTesser will work for a flutter web app only. I am totally on the side of @bb-ac that the implementation for the different platforms should not be different.

I was wondering though - are there any ways to supply an updated title to google analytics? right now, i have the title tag in my index.html, but also updating it with `SystemChrome.setApplicationSwitcherDescription()` won't send a different title to GA.

**Comment by adamduren** [comment]
@bb-ac it looks like this is now supported. This can be closed right?

**Comment by nstrelow** [comment]
IIRC I am already using it and it works nicely.

Thanks FlutterFire!

**Comment by EightRice** [comment]
> @bb-ac it looks like this is now supported. This can be closed right?

I'm getting the same issue. Not sure how it looks like it' supported..

**Comment by id18522096554** [comment]
> Uncaught (in promise) Error: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)
> 
>     at Object.throw_ [as throw] (errors.dart:195)
> 
>     at MethodChannel._invokeMethod (platform_channel.dart:154)
> 
>     at _invokeMethod.next (<anonymous>)
> 
>     at onValue (async_patch.dart:47)
> 
>     at _RootZone.runUnary (zone.dart:1439)
> 
>     at _FutureListener.thenAwait.handleValue (future_impl.dart:141)
> 
>     at handleValueCallback (future_impl.dart:682)
> 
>     at Function._propagateToListeners (future_impl.dart:711)
> 
>     at _Future.new.[_completeWithValue] (future_impl.dart:526)
> 
>     at async._AsyncCallbackEntry.new.callback (future_impl.dart:556)
> 
>     at Object._microtaskLoop (schedule_microtask.dart:43)
> 
>     at _startMicrotaskLoop (schedule_microtask.dart:52)
> 
>     at async_patch.dart:168
> 
> 
> 
> Steps to reproduce the behavior:
> 
> 1. Run a Flutter web app that includes firebase analytics: flutter run -d chrome 
> 
> 2. Open Developer Tools/Console in Chrome
> 
> 3. Observe the error above (and other similar errors)
> 
> 
> 
>

**Comment by russellwheatley** [comment]
Analytics for flutter web is now available.
