### ISSUE TITLE
[firebase_crashlytics] CrashlyticsCore: Received null settings, skipping report submission!

### ISSUE THREAD

**Issue by vivchar** [FirebaseExtended/flutterfire#2354]
**Describe the bug**
I followed to these steps https://pub.dev/packages/firebase_crashlytics
But I don't see that Firebase was successfully integrated on Firebase Console

**To Reproduce**
1. Follow to these instructions https://pub.dev/packages/firebase_crashlytics
2. Try to run app
4. See logcat output
Result: 
```
I/CrashlyticsCore: Initializing Crashlytics 2.6.8.32
I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
W/CrashlyticsCore: Received null settings, skipping report submission!
```
5. See Firebase console
Firebase console still show:
```
Step 3: Build and run your app
```

**Expected behavior**
You should not see console error, and Firebase craslytics should work correctly

**Additional context**
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.5 18F132, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```

pubspeck.yaml
```
firebase_core: ^0.4.0+9
firebase_crashlytics: ^0.1.3+3
firebase_analytics: ^5.0.2
```

build.gradle
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.10"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.31.2'
    }
```

**Comment by TahaTesser** [comment]
Hi @vivchar 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by vivchar** [comment]
Hi, currently I can't reproduce this anymore.
