### ISSUE TITLE
[firebase_auth] Could you support sign in with Apple on iOS under 13 or Android devices?

### ISSUE THREAD

**Issue by leejh10003** [FirebaseExtended/flutterfire#2356]
https://github.com/SpiralMoon/apple_sign_in_firebase

This repository contains an implementation of sign in with apple functionality on Android devices. Of course, I know maintainers of this repository are busy and this functionality is hard to implement. But if this function implemented, more developers can use flutter with sure. 

Could this scenario be implemented?
1. If device support sign in with apple natively, just use Apple's API
2. If the device doesn’t support API(iOS below 13 or Android devices), use webview or browser to authenticate the user(of course I know the latter one is more secure but hard to implement).

**Comment by Salakar** [comment]
Thanks for the feature request.

This is out of the scope of this repository unfortunately. But, we are planning to support raw OAuth flows in Firebase Auth in a later release (uses webview/browser) which should hopefully cover this use case anyway.
