### ISSUE TITLE
[cloud_functions] Error when setting origin to localhost

### ISSUE THREAD

**Issue by lexyfeito** [FirebaseExtended/flutterfire#2357]
**Describe the bug**
When using `useFunctionsEmulator` and set the origin to localhost it throws error with code="INTERNAL" and detail=null

**To Reproduce**
user `functions.useFunctionsEmulator(origin: 'http://127.0.0.1:5001');` to set origin to localhost. call a cloud function like
`final createProfileCallable = _functions.getHttpsCallable(functionName: 'funcName');
  final res = await createProfileCallable.call();
`

**Expected behavior**
should call cloud function with no error

**Additional context**
it works fine when not using `useFunctionsEmulator` and call the deployed callable functions

**Comment by jans-y** [comment]
Did you specify region? If you are not using the default us-central1 and don't specify it in your Flutter app it may cause similar problem.

**Comment by kroikie** [comment]
@lexyfeito Try setting the origin when you are making the call.

```
_functions.useFunctionsEmulator(origin: 'http://10.0.2.2:5001')
        .getHttpsCallable(functionName: 'funcName')
        .call()
```

I believe you only need to make the `useFunctionsEmulator` call once but currently it has to be attached to a `call`.

**Comment by gsusI** [comment]
I've tried making the call from the instance with the origin specified, but nothing...

```
CloudFunctions.instance.useFunctionsEmulator(origin: 'http://localhost:5001',)
                                  .getHttpsCallable(functionName: 'funcName').call();
```

I wonder if the appName is the issue?

**Comment by greghesp** [comment]
Hi @lexyfeito ,

I've tested this on the latest [roadmap version](https://github.com/FirebaseExtended/flutterfire/issues/2582), and can confirm this has been fixed.

```
HttpsCallable callable = CloudFunctions.instance
  .useFunctionsEmulator(origin: 'http://localhost:5001')
  .httpsCallable('listFruit');
```

It's also worth mentioning for future reference, that if you're targeting apps using Android 8.0 or higher, the platform will block the http endpoint.  To get around this in your debug builds, you can add the below to your AndroidManifest.xml, or set a [per-host network security file](https://developer.android.com/training/articles/security-config)

```
<application
  android:usesCleartextTraffic="true"
/>
```

Please keep an eye for the version release, and let us know if you're still having issues

**Comment by russellwheatley** [comment]
As described above, this issue has been resolved.
