### ISSUE TITLE
[firebase_crashlytics] runZoned with onError is deprecated in version v1.17.0

### ISSUE THREAD

**Issue by nerder** [FirebaseExtended/flutterfire#2361]
**Describe the bug**
Updating `flutter` to `v1.17.0` (`beta` channel at the moment of writing) cause `flutter analyze` to trigger an error:
```
   info • 'onError' is deprecated and shouldn't be used. Use runZonedGuarded instead • lib/main.dart:73:6 • deprecated_member_use
```
**To Reproduce**
1. run `flutter channel`
2. select the channel `beta`
3. run `flutter analyze`
4. see the error in the console

**Expected behavior**
The example code in the documentation should not cause any deprecation warning.

**Comment by nerder** [comment]
related to https://github.com/flutter/flutter/issues/53185

**Comment by nerder** [comment]
A possible fix would be to change the documentation into something like this:

```dart
  runZonedGuarded(() {
    runApp(
      MyApp(),
    );
  }, (Object error, StackTrace stack) {
    Crashlytics.instance.recordError(error, stack);
  });
```

**Comment by Salakar** [comment]
The documentation now recommends `runZoneGuarded` so I'm going to go ahead and close this.

https://firebase.flutter.dev/docs/crashlytics/usage#zoned-errors
