### ISSUE TITLE
[Dynamic Link] Cannot force dynamic link to open web browser when app is installed

### ISSUE THREAD

**Issue by coolcool1994** [FirebaseExtended/flutterfire#2363]
**Describe the bug**
I tried them all: REST API and manual construction. You cannot create dynamic link that would open the web broswer if the app is installed - it will always open the app. I get a previewLink after successfully creating dynamic link, and that flow chart shows that just created dynamic link should open browser: [
<img width="873" alt="Screen Shot 2020-04-13 at 9 18 45 AM" src="https://user-images.githubusercontent.com/23645054/79137792-39527f00-7d68-11ea-911b-5f69b312c0cc.png">
](url)

But it doesn't. It never does. It always open the installed app, never the website.

To reproduce, try to force create short link from dynamic link to open web browser in a mobile device that has the app installed. You can't. Dynamic link opens the app instead 100% of the time, and there is no way to force it to open web browser - this is contrary to what the flow chart says. There is no field whatsoever (tried them all in REST API and manual construction) that you can use to make programmatically created dynamic link to open browser. It is so funny because when you create short link from the dynamic link in the console, you can specify how it will behave, but it is impossible to do this when creating short link using REST API and manual construction. Please fix.

When not specifying bundle id for the apps when creating dynamic link, the created short link should open website, and not the app. Right now iOSInfo field or apn (in manual construction) are just obsolete/useless fields. Tested in mobile iOS environment (Haven't tested in Android).

**Comment by TahaTesser** [comment]
Hi @coolcool1994 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by coolcool1994** [comment]
Hi im sorry, I shouldn't have posted this in flutter fire chat. I will post this again elsewhere.

There is no need for sample project. Just create a dynamic link that opens iOS app, and try to program it to open browser instead. It is not possible contrary to the flow chart.
