### ISSUE TITLE
[firebase_auth] Email Link sign in just shows default page

### ISSUE THREAD

**Issue by DRSchlaubi** [FirebaseExtended/flutterfire#2364]
**Describe the bug**
I tried to set up the email sign-in feature of firebase using this package.
First of all, it used domain.com instead of our URL-Prefix we set up in dynamic links, then I read that URL prefixes aren't supported by firebase_auth yet so I deleted the URL prefixes and used a page.link domain this worked but when you open the email in chrome you get redirected to the play store instead of the app even if the app is installed

**Comment by TahaTesser** [comment]
Hi @DRSchlaubi 
This seems more like Stackoverflow type of question or do you think this is a bug?
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by DRSchlaubi** [comment]
It's probbably a FR since the Android client seems to have an option to specify the dynamic links domain for the sign in link. The app doesn't actually do anything since chrome does directly redirect in the playstore so there is no output in flutter run but here's flutter doctor

```C:\Users\micha>flutter doctor -v                                                                                        [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.752], locale de-DE)                • Flutter version 1.12.13+hotfix.9 at C:\Users\micha\flutter                                                            • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700                                                • Engine revision af51afceb8                                                                                            • Dart version 2.7.2                                                                                                                                                                                                                                                                                                                                                [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)                                            • Android SDK at C:\Users\micha\AppData\Local\Android\Sdk                                                               • Android NDK location not configured (optional; useful for native profiling support)                                   • Platform android-29, build-tools 29.0.3                                                                               • ANDROID_HOME = C:\Users\micha\AppData\Local\Android\Sdk                                                               • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java                                                  • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                                           X Android license status unknown.                                                                                         Try re-installing or updating your Android SDK Manager.                                                                 See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed      instructions.                                                                                                                                                                                                                             [√] Android Studio (version 3.6)                                                                                            • Android Studio at C:\Program Files\Android\Android Studio                                                             • Flutter plugin version 45.0.1                                                                                         • Dart plugin version 192.7761                                                                                          • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)                                                                                                                                                               [√] VS Code, 64-bit edition (version 1.44.0)                                                                                • VS Code at C:\Program Files\Microsoft VS Code                                                                         • Flutter extension version 3.9.1                                                                                                                                                                                                           [!] Connected device                                                                                                        ! No devices available                                                                                                                                                                                                                      ! Doctor found issues in 2 categories.      ```

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

Please could you update to the new version which now supports specifying the dynamic links domain as part of action code settings. If you have any problems with this feature or the updated plugins please raise a new GitHub issue.

See:
  - https://pub.dev/documentation/firebase_auth_platform_interface/latest/firebase_auth_platform_interface/ActionCodeSettings-class.html
  - https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/sendSignInLinkToEmail.html

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
