### ISSUE TITLE
[firebase_auth] version solving failed.

### ISSUE THREAD

**Issue by kishoraditya7** [FirebaseExtended/flutterfire#2367]
I am facing an issue installing firebase_auth, I tried the solutions available online, but they doesn't seem to work,
Error:
`Running "flutter pub get" in login...                           
The current Flutter SDK version is 1.9.1+hotfix.6.

Because login depends on firebase_auth >=0.15.1+1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
pub get failed (1)
Process finished with exit code 1` 

pubspec.yaml file
`version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter`

flutter doctor -v
`
[√] Flutter (Channel dev, v1.18.0-dev.5.0, on Microsoft Windows [Version 10.0.18363.720], locale en-IN)
    • Flutter version 1.18.0-dev.5.0 at C:\src\flutter
    • Framework revision 7f56b53de4 (3 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\kisho\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\kisho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
`
As per change log of the package it says, " Migrate to Android v2 embedding"
I do not understand how will that change things for dart sdk,

I think I am missing out on something very basic, so it would of great help if anyone can pinpoint the solution and mistake. 
Or even any better stable package for supporting different types of login and verification using firebase would work.

I tried using different versions of firebase_auth, it seems like all versions including and below "firebase_auth: 0.15.1" work properly whereas version including and above  "firebase_auth: 0.15.1+1" do not work properly while installation, but as the later versions are upgrade shouldn't they work more precisely?

**Comment by TahaTesser** [comment]
Hi @kishoraditya7 
Try the following
```
dependencies:
  flutter:
    sdk: flutter
  login: ^1.1.2
  cupertino_icons: ^0.1.3

dependency_overrides:
  firebase_auth: ^0.16.0
```

Thank you

**Comment by kishoraditya7** [comment]
yeah this works too, 
and also all versions below "firebase_auth: 0.15.1" work properly in normal manner.
Thank you.
Also is it a minor bug after that in the repo?

**Comment by TahaTesser** [comment]
Hi @kishoraditya7 
it's `login` package, they need to upgrade their dependencies 
i am glad it works for you 
Closing, as this isn't an issue with` firebase_auth` itself,
if you disagree please write in the comments and I will reopen it 
Thank you
