### ISSUE TITLE
[firebase_admob] AnchorType.bottom property is not working

### ISSUE THREAD

**Issue by AlanSGC** [FirebaseExtended/flutterfire#2371]
On previous iOS 11 the AnchorType.bottom property is not working. The ads always appear at the top of the screen. Android and iOS from version 11 works perfectly.

**To Reproduce**
FirebaseAdMob.instance.initialize(appId: LociUtils.getAppId());
    _bannerAd = createBannerAd()
      ..load()
      ..show(
        anchorOffset: 0.0,
        anchorType: AnchorType.bottom,
      );

**Additional context**
iOS device: 10.3.3

**Comment by TahaTesser** [comment]
Hi @AlanSGC 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by AlanSGC** [comment]
Hi, sorry for my delay.

[✓] Flutter (Channel master, v1.15.19, on Mac OS X 10.15.4 19E287, locale
pt-BR)
    • Flutter version 1.15.19 at /Users/alan_costa/downloads/flutter
    • Framework revision 60d0fef17a (5 weeks ago), 2020-03-09 22:07:34 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[✓] Android toolchain - develop for Android devices (Android SDK version
28.0.3)
    • Android SDK at /Users/alan_costa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
1.8.0_212-release-1586-b4-5784211)



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
18/04/20
14:52:10

Em qui., 16 de abr. de 2020 às 10:16, Taha Tesser <notifications@github.com>
escreveu:

**Comment by blasten** [comment]
Is there a workaround for this? @bparrishMines

**Comment by blasten** [comment]
Related to https://github.com/FirebaseExtended/flutterfire/issues/97

**Comment by erickcchoi** [comment]
exactly same problem, tested with ios 10.3 in simulator and actual device ios 9.

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H105 darwin-x64, locale en-CA)
    • Flutter version 1.22.4 at /Users/eric/Development/flutter
    • Framework revision 1aafb3a8b9 (13 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/eric/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 6 (mobile) • DF0CFB12-A1DA-4561-94B6-82B23B915BA0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-10-3
      (simulator)

**Comment by erickcchoi** [comment]
AnchorType default is Bottom, but the Banner stick on Top.  in ios 9 and ios 10

**Comment by dayron9110** [comment]
Any solution?

**Comment by dayron9110** [comment]
flutter doctor:

[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Mac OS X 10.15.6 19G2021 darwin-x64, locale es-CO)
    • Flutter version 1.24.0-7.0.pre at /Users/venko/Developer/flutter
    • Framework revision a0860f6e87 (6 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/venko/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone de Carmen (mobile) • 00008030-001028D40204802E            • ios • iOS 13.1.3
    • iPhone 6(10.3) (mobile)   • 48D91901-730E-43B3-8E9E-9083E046E09E • ios • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)

• No issues found!

**Comment by bparrishMines** [comment]
@dayron9110 We're currently working on integrating Ads into the widget tree which would remove this problem. Here's more info on applying for the closed beta: https://github.com/flutter/flutter/issues/12114#issuecomment-725731427

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
