### ISSUE TITLE
[firebase_messaging] Collapsible notifications

### ISSUE THREAD

**Issue by MATTYGILO** [FirebaseExtended/flutterfire#2372]
**Is your feature request related to a problem? Please describe.**
I've been scouring the web for the past day to see if it is possible to deliver collapsable notifications using flutter firebase messaging if some knows how to do so please say. If this is not yet possible I'd be incredibly grateful if you could implement it ASAP.

Thank you for any suggestions or help.

**Comment by Ehesp** [comment]
Hi @MATTYGILO please can you show an example of what you mean?

**Comment by TedRibeiro** [comment]
@Ehesp I think @MATTYGILO meant to create bundles of notifications matching a criteria (for example, grouping messages sent by user in a chat application)

Something like [this](url)
