### ISSUE TITLE
[firebase_auth_web] Exceptions returned are incompatible with mobile

### ISSUE THREAD

**Issue by buntagonalprism** [FirebaseExtended/flutterfire#2376]
**Issue Summary.**
Any exception thrown by `firebase_auth_web` is a `FirebaseError` from `package:firebase`. On mobile a `PlatformError` is thrown instead. This makes it difficult to have cross-platform error handling logic. 

For example, the following logic works great on mobile for handling users attempting to sign in with an unrecognised email address. But to handle errors from web with similar type-safety requires importing the web-only `package:firebase` to get the `FirebaseError` class, making it no longer mobile-compatible:

```dart
try {
  final user = await auth.signInWithEmailAndPassword(email: email, password: password);
  goToUserHome(user);
} on PlatformException catch (error, trace) {
  if (error.code == "ERROR_USER_NOT_FOUND") {
    showNotFoundWarning();
  } else {
    rethrow;
  }
} 
```

(The error codes are also different between mobile and web for the same causes, but that's from the underlying Firebase library not FlutterFire).

**Desired Solution**
`firebase_auth_web` should map any `FirebaseError` into a `PlatformError` to provide API compatability and cross-platform support with the mobile implementation. Or perhaps `FirebaseError` could be exposed as part of `package:firebase_core` or similar to avoid the need for a  dependency on the web-only `package:firebase`.

**Comment by Ehesp** [comment]
Related: https://github.com/FirebaseExtended/flutterfire/issues/1456 

Different platform so leaving open.

**Comment by Ehesp** [comment]
This has been fixed in the latest release.
