### ISSUE TITLE
[firebase_crashlytics] <README not updated>

### ISSUE THREAD

**Issue by josechagas** [FirebaseExtended/flutterfire#2379]
**Describe the bug**
The README file is not correctly, it says to add: classpath 'io.fabric.tools:gradle:1.26.1'.

It must point to this link https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android&authuser=0, this link is updated, or be updated.

**Comment by TahaTesser** [comment]
Hi @josechagas 
it should be updated `firebase_crashlytics` Migrate away from Fabric

**Comment by josechagas** [comment]
I understand, but take a look at this link https://pub.dev/packages/firebase_crashlytics the Readme file says on step 2 to use classpath 'io.fabric.tools:gradle:1.26.1', even not using fabric anymore.

**Comment by Nico04** [comment]
I just spend few hour trying to make CrashLytics work on iOS.
Between the officiel CrashLytics docs and this plugin Readme, both are partially wrong or not enough (at least in my case, which should be any Flutter dev's).

When you add a new iOS App on Firebase, you're asked to :
1. Download a .plist file and copy inside your project. 
=> In Flutter's case, it should be in the Runner folder
2. Add some lines to the Podfile. 
=> In my case this would cause error. Ignoring this totally resolve the issue.
3. Add some lines to the AppDelegate.swift
=> This was needed.

After, you need to install firebase_crashlytics.
1. Add line to pubspec.yaml
2. Follow this plugin's README iOS instructions
=> This cause error too. Ignoring this totally resolve the issue.

**Comment by Saifallak** [comment]
@Nico04 current `firebase_crashlytics` plugin isn't migrated to the new `Crashlytics SDKs` and still depends on `fabric`, until #2288 is merged.

**Comment by Nico04** [comment]
I've read that, but still, the README is incorrect and leads to errors.

**Comment by axel-op** [comment]
Hey @Nico04,

If this doesn't bother you and if you have the time to do so, could you please update your Crashlytics dependency in your `pubspec.yaml` file like this:

```yml
dependencies:
  firebase_crashlytics:
    git:
      url: https://github.com/axel-op/flutterfire.git
      path: packages/firebase_crashlytics
      ref: crashlytics-new-sdk
```

and tell me if following the steps described on [this README](https://github.com/axel-op/flutterfire/tree/crashlytics-new-sdk/packages/firebase_crashlytics) is sufficient, or if you also have to do the extra steps that you described above?

It would be greatly appreciated 😊

**Comment by Nico04** [comment]
I've spent few hour trying to setup a environnement suitable to test your suggestion.
Unfortunately I had to gave up as I had to configure all the iOS certificate stuff for the test project which takes so much time.
I'll test your suggestion next time I'd have to install CrashLytics, not before. Sorry.
In any case, I can tell you this : in the README you start by saying to follow official Firebase installations instructions, but one of theses step is to add some lines to the Podfile, and I guess that may not be necessary with your script. But maybe I'm wrong

**Comment by axel-op** [comment]
@Nico04 Thank you 😊

**Comment by dannyalbuquerque** [comment]
> Hey @Nico04,
> 
> If this doesn't bother you and if you have the time to do so, could you please update your Crashlytics dependency in your `pubspec.yaml` file like this:
> 
> ```yaml
> dependencies:
>   firebase_crashlytics:
>     git:
>       url: https://github.com/axel-op/flutterfire.git
>       path: packages/firebase_crashlytics
>       ref: crashlytics-new-sdk
> ```
> 
> and tell me if following the steps described on [this README](https://github.com/axel-op/flutterfire/tree/crashlytics-new-sdk/packages/firebase_crashlytics) is sufficient, or if you also have to do the extra steps that you described above?
> 
> It would be greatly appreciated 😊

I did but build failed:

```
FAILURE: Build failed with an exception.

* Where:
Script 'flutter/packages/flutter_tools/gradle/flutter.gradle' line: 793

* What went wrong:
Execution failed for task ':app:assembleDevDebug'.
> FlutterPlugin$_addFlutterTasks_closure18$_closure45$_closure46$_closure47

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
Exception: Gradle task assembleDevDebug failed with exit code 1
```

**Comment by axel-op** [comment]
@dannyalbuquerque Thank you. Are you on iOS?

**Comment by dannyalbuquerque** [comment]
> @dannyalbuquerque Thank you. Are you on iOS?

for android, if i remove firebase_messaging: ^6.0.16 it builds. I dont see my crashes on firebase console for the moment.

for iOS, it builds too.

but for both platforms, i face this isssue:
https://github.com/FirebaseExtended/flutterfire/issues/1147

"Unhandled Exception: Bad state: Error thrown by Crashlytics plugin" 

nothing is reported to crashlytics console

**Comment by axel-op** [comment]
@dannyalbuquerque Awesome! Thanks for your help ☺️

**Comment by josechagas** [comment]
> I've read that, but still, the README is incorrect and leads to errors.

I had to install again, I followed all steps from README and it worked, no crashes, but I am not receiving crash reports of iOS, it's only working for Android version.

**Comment by Salakar** [comment]
A new Crashlytics plugin has now landed on master which should solve this issue.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin: https://firebase.flutter.dev/docs/migration/
