### ISSUE TITLE
Firebase Messaging does not call onResume and onLaunch when sending data including "notification" when app is background or terminated

### ISSUE THREAD

**Issue by thieplehuu** [FirebaseExtended/flutterfire#238]
I use nodejs firebase-admin to send notifications to Android devices
I have configured flutter_local_notification as instructed in
https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages

When I send the notification from node js with payload:
```
var payload = {
                  "data": {
                    "Nick": "Mario",
                    "body": "great match!",
                    "Room": "PortugalVSDenmark",
                    "screen": "ChannelScreen",
                  },
                };
```
then flutter_local_notification trigger onBackgroundMessage and displays the success message, but when I click on firebase_messaging does not trigger the onResume and onLaunch functions.
When I send the notification from node js with payload:
```
var payload = {
                  "data": {
                    "Nick": "Mario",
                    "body": "great match!",
                    "Room": "PortugalVSDenmark",
                    "screen": "ChannelScreen",
                  },
                  "notification": {
       "click_action": "FLUTTER_NOTIFICATION_CLICK" //or "clickAction":
                  }
                };
```
then the notification appears in the device's navigation bar and firebase_messaging's onResume was trigger when I click on the notificaition but flutter_local_notification does not trigger onBackgroundMessage when the app is in the background

Please help me, Thank so much.

sorry because my English not good

**Comment by Mahmoud2B** [comment]
Did you get a fix?

**Comment by thieplehuu** [comment]
@Mahmoud2B No, I am getting error, and I need help to fix it.
Thanh you for reply!

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓
