### ISSUE TITLE
[firebase_mesaging] iOS PN's not showing Images

### ISSUE THREAD

**Issue by droidluv** [FirebaseExtended/flutterfire#2381]
I'm sending test PN's from the Firebase Console, and was adding images(max of 145KB size) and they are appearing correctly on Android, but not on iOS, I'm receiving the PN but always without the image, not sure what more to do, when checking the data payload recieved I can see the url I set in Firebase Console for images is coming in the fcm_options: {"image": "my_image_url"} object of the PN payload

So PN's are always received with just only the text appearing.

Tested on iOS 13.3.1 iPhone 6S+, with flutter v1.12.13+hotfix.8 and firebase_messaging 6.0.13

**Comment by TahaTesser** [comment]
Hi @droidluv 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
