### ISSUE TITLE
[firebase_auth] Incorrect description for OAuthCredential.providerId

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#2383]
Minor copy/paste error for the description of `providerId` for `OAuthCredential `:
* https://github.com/FirebaseExtended/flutterfire/blob/a76667272788be38ffd6f8a579b2df61b18853a7/packages/firebase_auth/firebase_auth_platform_interface/lib/src/types.dart#L191

```dart
/// Abstract class to implement [OAuthCredential] authentications
abstract class OAuthCredential extends AuthCredential {
  /// The ID Token associated with this credential.
  final String idToken;

  /// The OAuth access token.
  final String accessToken;

  /// The OAuth raw nonce.
  final String rawNonce;

  /// The OAuth raw nonce.
  final String providerId;
```

I noticed the mistake from the [documentation](https://pub.dev/documentation/firebase_auth_platform_interface/latest/firebase_auth_platform_interface/OAuthCredential/providerId.html).

**Comment by Salakar** [comment]
Thanks for the report, would you be able to send a PR to update it and tag me in it? I can get it reviewed and merged if ok
