### ISSUE TITLE
[FIREBASE DYNAMIC LINK] <Notification click not getting the deeplink url in iOS>

### ISSUE THREAD

**Issue by SureShDood** [FirebaseExtended/flutterfire#2385]
**Describe the bug**
Notification triggered via clevertap with attached the deeplink url. IOS received the notification without any problem. The deeplink link receiver onlink also triggered. But the link returned null.  The same think the deeplink url click from message, whatsapp, got the link. Let me know why its not getting the link.

**Comment by ejdrian313** [comment]
the same issue in my iOS app

**Comment by russellwheatley** [comment]
@SureShDood Could you please provide a reproducible code sample, confirm you're using the latest version and using a physical device?
