### ISSUE TITLE
[firebase_auth] Is there a plan to support multifactor authentication (so called MFA/2FA)?

### ISSUE THREAD

**Issue by fysoul17** [FirebaseExtended/flutterfire#2386]
I found that Google has released multi-factor authentication recently.

https://cloud.google.com/identity-platform/docs/web/mfa

and thus, I am just wondering if there is a plan to implement this feature soon. 

I know that there is some sort of workaround solution using 'userClaim', but it would be greater if we can use official way of MFA.

**Comment by TahaTesser** [comment]
Hi @fysoul17 
Please checkout this [answer](https://stackoverflow.com/a/52906804)
Since it's not supported in Firebase, i am closing this issue 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by fysoul17** [comment]
Hi @TahaTesser 

Please check the link I provided. In fact, it does support by Firebase now. It is an example of Firebase.

Also, the link you provided was an old answer, if you scroll down to recent reply, it also said Firebase is now supporting MFA only when you enable Identity Provider.

Thanks in advance for further support. ;)

**Comment by fysoul17** [comment]
@TahaTesser Would you please re-open the issue?

**Comment by AndroidNils** [comment]
It was released with v7.11.0: https://firebase.google.com/support/release-notes/js#version_7110_-_march_12_2020 😍

**Comment by kaarens93** [comment]
I see mfa is supported but how do we implement with flutter? I tried to use cloud functions but I don't think it's possible. See below code. I have no way of getting "user" because I can't pass user as a parameter in the cloud function. The way I have called auth.currentUser returns null because I used firebase_auth package. There's no method to get user by UID either so I don't think there's much I can do, right?

```
var firebase = require("firebase")

firebase.initializeApp({
  // config
});

const auth = firebase.auth();

exports.add2fa = functions.https.onCall((data, context) => {
  const user = auth.currentUser; // trouble here
  const cred = firebase.auth.PhoneAuthProvider.credential(data.verificationId, data.code);
  const multiFactorAssertion = firebase.auth.PhoneMultiFactorGenerator.assertion(cred);
  user.multiFactor.enroll(multiFactorAssertion, 'phone number');
})
```

**Comment by Ehesp** [comment]
I've taken a look into this as part of #2582 , we've decided that we'll first get the API stable and then look at introducing MFA. Another potential issue is that iOS support is in beta and the underlying web library wrapper doesn't support it.
