### ISSUE TITLE
[firebase_database] startAt return items in random order

### ISSUE THREAD

**Issue by igorka48** [FirebaseExtended/flutterfire#2392]
Query startAt returns items in random order. 

firebaseDatabase
        .reference()
        .child('users')
        .orderByChild('fullname')
        .startAt('A')
        .limitToFirst(5)

Expected result: 
  Users with **fullname** begins from **A** on top of list. 
Actual result: list of users in random order

**Comment by Ehesp** [comment]
Please follow the issue template.

How are you iterating over the items to check order?

**Comment by Ehesp** [comment]
Hi @igorka48 - are you fetching the results once, or streaming them? Also how are you iterating over the results?

**Comment by igorka48** [comment]
@Ehesp 
Here is a full query: 

` @override
  Stream<List<User>> search(String text) {
    return firebaseDatabase
        .reference()
        .child('users')
        .orderByChild("fullname")
        .startAt(text)
        .limitToFirst(5)
        .once()
        .asStream()
        .map((snapshot) => (snapshot.value != null)
            ? (snapshot.value as Map<dynamic, dynamic>)
                .values
                .map((document) => User.fromMap(document))
                .toList()
            : List());
  }`

And real result:

**H** - Helen is expected first. 
But results looks random. If I do limmitToFirst(1) Helen will be the one right result. 
It means database query work fine, but order loss later. 


<img width="353" alt="Снимок экрана 2020-04-18 в 13 04 38" src="https://user-images.githubusercontent.com/10116759/79634796-81f9a600-8175-11ea-84ab-4a6538ee281f.png">

The same result for **Test**.  
You can see that Test User isn't at top
<img width="361" alt="Снимок экрана 2020-04-18 в 13 05 19" src="https://user-images.githubusercontent.com/10116759/79634855-d00ea980-8175-11ea-96fa-4cf3371bafda.png">

Another sample:
**Igor**. There are two users that starts from **Igor**, but only one at top. 

<img width="354" alt="Снимок экрана 2020-04-18 в 13 05 02" src="https://user-images.githubusercontent.com/10116759/79634919-33004080-8176-11ea-9593-bae53a111e4d.png">

**Comment by Ehesp** [comment]
Hmm it looks as though the DataSnapshot class doesn't return an iterator method. When the data comes back from the database, it is returned unordered. The other SDKs provide some `for each` method which then returns the data in order. 

The native side needs to iterate the children keys, return these in an array and then on Dart, iterate over those keys and fetch the correct map key/value.

**Comment by igorka48** [comment]
@Ehesp 
Look at screen. It's request for **"Ig"**

I can't request data as Array/List. Data returns as _InternalLinkedHashMap
and order is already wrong. 

<img width="811" alt="Снимок экрана 2020-04-18 в 19 30 40" src="https://user-images.githubusercontent.com/10116759/79643355-3f52c080-81ab-11ea-8fd1-cf3446750611.png">

**Comment by Salakar** [comment]
Fixed in https://github.com/FirebaseExtended/flutterfire/pull/5765 - thanks
