### ISSUE TITLE
[firebase_auth] Make auth errors uniform and platform independent

### ISSUE THREAD

**Issue by NoamDev** [FirebaseExtended/flutterfire#24]
It's annoying that for every PlatformException being thrown from firebase auth I have to compare the code twice, once for android and once for ios.

Is it possible to use the same error code in all platforms?

**Comment by collinjackson** [comment]
I agree that this would be a welcome improvement. I don't have the bandwidth to implement this in the short term but would be happy to review PRs.

**Comment by NoamDev** [comment]
I've found a list of all error codes (https://docs.google.com/spreadsheets/d/1FDn0rRRYjgXMwc_FIAxO7_cQh69q5VXgQt7Hmvyb1Sg)
in this PR https://github.com/flutter/plugins/pull/775.

**Comment by NoamDev** [comment]
I'm not sure if I can do that, but anyway, we should have a specification for it.
which error code and message do we want, the android or the ios version.

**Comment by Salakar** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
