### ISSUE TITLE
[Firestore] Array Contains with a null value returns ALL documents

### ISSUE THREAD

**Issue by MilesAdamson** [FirebaseExtended/flutterfire#2404]
**Describe the bug**

If you do a query with `arrayContains`, and the value you pass in is null, you receive ALL documents, opposed to any documents where the array contains a null value. In my case, no arrays had any null values, and I expected this to return ZERO documents.

**To Reproduce**

```
      Query query = groups
          .where('my_array', arrayContains: null)
          .orderBy('recent.timestamp', descending: true);

      QuerySnapshot querySnapshot = await query.getDocuments();

      print(querySnapshot.documents.length);
```

```
I/flutter ( 3564): 207
```

**Expected behavior**
`.where('my_array', arrayContains: null)` return documents where the array had a null value. If no documents have `my_array` with a null value, return no documents at all.

**Comment by Salakar** [comment]
@MilesAdamson array contains doesn't support null value queries on any of the underlying SDKs. Null supports only equality comparisons, e.g. `equalTo`
