### ISSUE TITLE
[FirebaseAuth] OAuth2 client id in access token audience is not found.

### ISSUE THREAD

**Issue by niallshaw** [FirebaseExtended/flutterfire#2407]
**Describe the bug**
```
void handleGoogleSignIn() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;
      
      final AuthCredential credential = GoogleAuthProvider.getCredential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      

      final FirebaseUser user =
          (await _auth.signInWithCredential(credential)).user;
      print("signed in " + user.displayName);
      setUserId(user);
      _user = new User(name: user.displayName, email: user.email);
      var debug = true;
  }
```
Attempting to login/signup with Google always fails with the exception:
`Unhandled Exception: PlatformException(ERROR_INVALID_CREDENTIAL, OAuth2 client id in access token audience is not found., null)`

**To Reproduce**
1. Create a Firebase Project
2. Create Flutter Project
3. Register the iOS application under Firebase project
4. Add URL Type and GoogleService-Info.plist to Flutter Runner
5. Attempt to sign up with google with above code

**Expected behavior**
Signup works - FirebaseUser object is populated.

**Additional context**
This is using the iOS simulator (iPhone 11 Pro Max iOS 13.3)
Signing in with Facebook works as expected.
The application also uses maps via a different GCP project - could this be interfering? If so, how can I remove it from this project?

The JWT id token payload azp and aud match.

The JWT Access Token payload takes the form ya29.XXXXXX... - which looks _significantly_ different to the id token payload

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale
    en-AE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Closing this issue based on [comment](https://github.com/flutter/flutter/issues/55274#issuecomment-617019239) by same reporter 
Closing as solved
if you disagree please write in the comments and I will reopen it 
Thank you
