### ISSUE TITLE
RemoteConfig getInt() fails when passing the key through method's input parameter Flutter

### ISSUE THREAD

**Issue by vinnytwice** [FirebaseExtended/flutterfire#2408]
I have a RemoteConfig parameter that I fetch with the `'localization_version'` key passed in when calling the method `Future<int> versionCheck(String key)` from a bloc. 
The problem is that if I fetch the value with the passed in string as `int locValKey = remoteConfig.getInt(key);`it fails and returns '0', while if I fetch it passing in an actual string as `int v = remoteConfig.getInt('localization_version');` it then succeeds returning the correct value. Why 'getInt()' is not accepting the same string when passed from the method's input? Can you see something wrong? 

These are the methods:

```
Stream<DefaultsState> _mapSyncLanguagesToState(DefEvent event) {
    int value = await _defaultsRepository.versionCheck('localizazion_version');
    print('fetched value is $value');
  }
```

and 

```
Future<int> versionCheck(String key) async {
    // ket is correct
    print('key to fetch is: $key'); 
    final RemoteConfig remoteConfig = await RemoteConfig.instance;
    // Enable developer mode to relax fetch throttling
    remoteConfig.setConfigSettings(RemoteConfigSettings(debugMode: true));
    remoteConfig.setDefaults(<String, dynamic>{'localization_version': ''});
    try {
      // Using default duration to force fetching from remote server.
      await remoteConfig.fetch(expiration: const Duration(seconds: 0));
      await remoteConfig.activateFetched();

      // int using key directly WORKS
      int v = remoteConfig.getInt('localization_version');
      print('v is : $v');

      // using passed in key FAILS
      int locValKey = remoteConfig.getInt(key);
      print('locValKey is $locValKey');

      //
      return v;
    } on FetchThrottledException catch (exception) {
      // Fetch throttled.
      print(exception);
    } catch (exception) {
      print('Unable to fetch remote config. Cached or default values will be '
          'used');
    }
  }
```

**Comment by TahaTesser** [comment]
Hi @vinnytwice 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?

**Comment by vinnytwice** [comment]
Hi. Sorry for late reply.
here is flutter doctor:
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.13.6 17G65, locale en-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!

and this is run

[  +50 ms] executing: [/Users/vinnytwice/Developer/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/vinnytwice/Developer/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +43 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +13 ms] executing: [/Users/vinnytwice/Developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +21 ms] executing: [/Users/vinnytwice/Developer/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +47 ms] executing: /usr/bin/xcode-select --print-path
[  +14 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +315 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +5 ms] Xcode 10.2.1
           Build version 10E1001
[ +106 ms] executing: /Users/vinnytwice/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/vinnytwice/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           3300f55e4cf61347       device usb:4246732800X product:a5xeltexx model:SM_A510F device:a5xelte transport_id:13
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +40 ms] executing: /Users/vinnytwice/Developer/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +144 ms] /usr/bin/xcrun simctl list --json devices
[ +337 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] /Users/vinnytwice/Library/Android/sdk/platform-tools/adb -s 3300f55e4cf61347 shell getprop
[ +234 ms] ro.hardware = samsungexynos7580
[   +3 ms] /Users/vinnytwice/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +21 ms] ro.hardware = ranchu
[ +195 ms] SM A510F                  • 3300f55e4cf61347                     • android-arm    • Android 7.0 (API 24)
[   +1 ms] Android SDK built for x86 • emulator-5554                        • android-x86    • Android 7.0 (API 24) (emulator)
[        ] iPhone Xs                 • 78F23F50-FF9E-42E4-BA42-4BB01CABD46F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
[        ] Chrome                    • chrome                               • web-javascript • Google Chrome 81.0.4044.122
[        ] Web Server                • web-server                           • web-javascript • Flutter Tools
[  +22 ms] "flutter run" took 1,517ms.

Hope this helps.
Thank you.

**Comment by Salakar** [comment]
Closing in favour of trying the latest Remote Config version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/remote-config/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
