### ISSUE TITLE
[Cloud Firestore] Array of Maps turns into Map<dynamic, dynamic>

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#241]
I have a document that has a field that is an **array of maps**.  Theoretically, it should be a `List<Map<String,dynamic>>` -- however, I totally understand that since each element of the array could be anything, the type is truly `List<dynamic>`.

Now, if I take the first element of the array, it should be a `Map<String, dynamic>`, however its actual type is `_InternalLinkedHashMap<dynamic, dynamic>`.  _(Why is the key not `String`?)_

My problem is that I need to pass this to a function accepting a `Map<String, dynamic>`, but Dart is throwing an error saying that:

> Type `_InternalLinkedHashMap<dynamic, dynamic>` is not a subtype of type `Map<String, dynamic>`

My expectation is that this `_InternalLinkedHashMap` is `<String, dynamic>` instead of `<dynamic, dynamic>`.

**Comment by awhitford** [comment]
This may be related to https://github.com/flutter/flutter/issues/17417.

**Comment by AlexMoon90** [comment]
You have to convert your arraymaps to map<String, dynamic> to fix 
  : Type _InternalLinkedHashMap<dynamic, dynamic> is not a subtype of type Map<String, dynamic>

`
List<Map<String, dynaymic>array = list[];
arraymaps.map((a) {
 for(var c in a) 
array.add [ Map<String, dynamic>.from(c)] });
`

**Comment by awhitford** [comment]
Thank you @AlexMoon90 for responding.

I was able to use a _cast_ to workaround this:
```
      services: data.containsKey('services')
          ? List<MyService>.from(data['services']
              .map((d) => MyService.fromMap(d.cast<String, dynamic>())))
          : null,
```

**Comment by iapicca** [comment]
Hi @awhitford 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by hassanfaour** [comment]
> MyService.fromMap(d.ca

I used this method and it's now working is there method of uploading instead of dowloading?
