### ISSUE TITLE
[Dynamic Links] Update requirements for ios

### ISSUE THREAD

**Issue by LucasTejero** [FirebaseExtended/flutterfire#2413]
You have to add the FirebaseDynamicLinksCustomDomains in the info.plist

https://firebase.google.com/docs/dynamic-links/custom-domains

and there is no reference in the readme to implement the package.
i lost a lot of time until i discover this.

**Comment by TahaTesser** [comment]
Duplicate of [#1738](https://github.com/FirebaseExtended/flutterfire/issues/1738)
