### ISSUE TITLE
Firebase Messaging notifications received but not displayed (Android)

### ISSUE THREAD

**Issue by CaptainWeb1** [FirebaseExtended/flutterfire#2416]
I am using firebase cloud messaging with Flutter. When I send notification to a device in foreground, it's well received (json printed in onMessage of firebaseMessaging.configure method) but no notification is displayed on the screen. 
However when app is behind other apps, the notification is displaying on the screen

Here is the notification in json :

 ```
var client = http.Client();

 var jsonData = json.encode({
        "to": "/topics/$userId",
        "data": {
          "click_action": "FLUTTER_NOTIFICATION_CLICK",
          "body": "$notificationText",
          "title": "Title",
          "sound": "default",
          "status": "done",
          "screen": "ListPostsScreen",
        },
        "content_available": true,
        "priority": "high",
      });

      var headers = {
        'Authorization': "key=$key",
        'Content-Type': 'application/json',
      };

      var response = await client.post(url, headers: headers, body: jsonData);

      print(response.body);

```
intent-filter in AndroidManifest.xml

```
        <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```

**Flutter doctor**
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [version 10.0.18363.778], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.0)
[√] Connected device (3 available)

• No issues found!

**Comment by GiviMAD** [comment]
Same for me. I think the problem is that the package is not fully compatible with latest versions on flutter.
It doesn't seem to implement the changes described in this document: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by CaptainWeb1** [comment]
Thank you for this information, did you try what is explained in this doc ?

**Comment by TahaTesser** [comment]
Hi @CaptainWeb1 
Are you experiencing on latest upgrade to new `beta`?
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by CaptainWeb1** [comment]
Hi @TahaTesser 
Thank you for your answer.

`flutter doctor -v`
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [version 10.0.18363.778], locale fr-FR)
    • Flutter version 1.14.6 at C:\Program Files\flutter
    • Framework revision fabeb2a16f (3 months ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Firecobra\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\Firecobra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

For the run verbose it's on a client project so confidential :x

**Comment by alanstyong71** [comment]
We faced the same problem. On debug console, you can see the message printed. But it doesn't show, and the Snackbar didn't fire. Two possible scenarios of this occurred. One, FCM wasn't working (but it clearly was, since the App received the message), Two, that Snackbar wasn't firing because when searching for the Context to anchor SnackBar, it couldn't find one and so nothing showed. Using Google, we found the answer to how to display Snackbar using a Global Scaffold key.

**Comment by reltid** [comment]
I have the same problem applications that had notifications working a month ago, now they receive them but the icon is not seen, only the blank space or a gray box ...
Has anyone found solutions? I have updated the plugins and flutter to the latest version without being able to fix it.

**Comment by greghesp** [comment]
Possibly same behaviour being experienced on iOS: https://github.com/FirebaseExtended/flutterfire/issues/762

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has been been heavily reworked, along with documentation, since this issue was raised: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
