### ISSUE TITLE
[<FCM>] <Work with local notification>

### ISSUE THREAD

**Issue by niypoo** [FirebaseExtended/flutterfire#2417]
I looking for any way to make flutter_local_notifications work with fcm on ios, when app is open it received only data message and when app is closed or in background doesn't received any thing ,

working with flutter ->master -> 1.8V

I have updated to last version `firebase_messaging: ^6.0.13`

and put 
`<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>`

and in AppDelegate.swift 

`
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
`

so is there any way for working together !

**Comment by TahaTesser** [comment]
hI @niypoo 
For issue related to the 3rd party plugin [flutter_local_notifications](https://pub.dev/packages/flutter_local_notificationse) you may want to open an issue in the dedicated [github](https://github.com/MaikuB/flutter_local_notifications/issues).

if you disagree please write in the comments and I will reopen it
Thank you

**Comment by SergeShkurko** [comment]
@niypoo did you to solve the problem?

**Comment by niypoo** [comment]
> @niypoo did you to solve the problem?

yes I did , update your local_notification and firebase_message to last version this solve my issue and be sure you have checked background_fetch and push_notification in xcode abilities
