### ISSUE TITLE
Firebase analytics does not display demographics data

### ISSUE THREAD

**Issue by Nomorewine** [FirebaseExtended/flutterfire#2418]
I have integrated firebase plugins in our flutter app (Android and iOS). Everything is working fine except for demographics data. Demographics data appears to be missing. 
I have no errors/warning in logs so don't really know where to start.
Here is some relevant info for my project :
```
firebase_messaging: ^6.0.12
firebase_analytics: ^5.0.11
firebase_core: ^0.4.4+3
firebase_auth: ^0.15.5+3
```
flutter doctor:
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.6, on Mac OS X 10.15.3 19D76, locale en-KR)
    • Flutter version 1.12.13+hotfix.6 at /Users/username/flutter
    • Framework revision 18cd7a3601 (4 months ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

I have also contacted firebase support, but unfortunately we couldn't resolve the issue and they have suggested to try submitting ticket here.
Is there a way to ensure that my app sends ADID/IDFA to Firebase ? Do I need to enable this functionality or is it ON by default?

**Comment by vincent0225** [comment]
Same problem here. No demographics in flrebase console, even I added AdSupport.framework in ios workspace

**Comment by Nomorewine** [comment]
We solved the problem by creating new project in firebase console. 
In Flutter code we only changed firebase keys, so I assume the problem was with firebase server side.

**Comment by laurent-pereira** [comment]
Same problem here. I can't create a new project in firebase (It's in production).
Any other tips ?

**Comment by Alezhka** [comment]
@laurent-pereira we activated Google Signals for out project and problem resolved.

**Comment by 7ammer** [comment]
Hi @Alezhka, how long did it take for you to see the data coming in? We have done this  and had many hits since but still nothing.

**Comment by Alezhka** [comment]
@7ammer Around 2-3 days. How many DAU in your app?

**Comment by Alezhka** [comment]
@7ammer I think this is not enough. We read that you need at least 100 people for each of the categories. We started thinking about the audience when we already had 1k users.

**Comment by 7ammer** [comment]
Hi @Alezhka, Thanks for the reply! It did indeed take a few days. We have about 24K DAU at the moment. All is working well now.

**Comment by russellwheatley** [comment]
> We solved the problem by creating new project in firebase console.
> In Flutter code we only changed firebase keys, so I assume the problem was with firebase server side.

Hey @Nomorewine, thanks for confirming your issue was resolved.
