### ISSUE TITLE
[Analytics] Undefined symbol: _OBJC_CLASS_$_FIRAnalytics

### ISSUE THREAD

**Issue by csongorkeller** [FirebaseExtended/flutterfire#2419]
**Describe the bug**
Hi there,
When adding your plugin to my iOS app, and trying to build, it fails with this:
Undefined symbol: _OBJC_CLASS_$_FIRAnalytics
However in my podfile I do see pod 'Firebase/Analytics'
Do you have any idea how it can be solved?

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Mac OS X 10.15.4 19E266, locale en-NL)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @csongorkeller 
Can you try running `pod install` from of your ios folder and try again? 
Can you please provide you `flutter run --verbose` and `pubspec.yaml`?  
Thank you

**Comment by TahaTesser** [comment]
Hi @csongorkeller 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
