### ISSUE TITLE
[cloud_firestore] Firebase Security Rule doesn't restrict a stream type of query

### ISSUE THREAD

**Issue by tranceyos2419** [FirebaseExtended/flutterfire#242]
**Describe the bug**
 When I set firebase security rules to restrict read requests, my app still can read the documents by stream.

**To Reproduce**
1. Go to firease console and write rules like below
<img width="1123" alt="Screen Shot 2019-10-01 at 22 18 31" src="https://user-images.githubusercontent.com/31304661/65965777-1e8a7e00-e49a-11e9-9d0a-27a8d1d6c5c3.png">

2. And this code still gives me data
```
  Stream<QuerySnapshot> stramDataCollection(User user) {
    return Firestore.instance.collection('characters')
        .orderBy('rating', descending: true)
        .where('uid', isEqualTo: user.uid)
        .snapshots();
  }
```

**Expected behavior**
I'm new to flutter and firebase So I might be wrong. However, I  think that this function shouldn't give me any data under the condition.

**Comment by Ehesp** [comment]
Hm this doesn't make much sense as to why this would happen.

Only thing I can think of is that you've accessed the data before and it's retuning a locally cached instance. Will track and get reproduced.

**Comment by tyirvine** [comment]
@tranceyos2419 I think @Ehesp is correct. I'm doing something similar in my project.

When I first build my application the value in question is reading `null` and upon authentication it grabs the data through Firestore - **passing the security rules** - and then returns it.

Upon logging out it does read the data within the value in question, however after deleting the app, the cache is cleared and the value is again `null`.

I think all that is needed is to conditionally stream these snapshots and have them be updated on an authorization change. This is very easy to do when it comes to `FirebaseUser` as it has the `OnAuthStateChanged` method but the `Firestore` object does not have this option.

-----

~~So it's more so up to the developer as of right now to somehow overwrite or nullify that snapshot. **Perhaps the cache could just be cleared on logging out?**~~

I looked into this some more and found that persistence can be disabled for Firebase and that it is enabled by default. [This means it will store the data in the cache so the user can see it when offline.](https://firebase.google.com/docs/firestore/manage-data/enable-offline)

I am unsure however how to disable persistence for just one item. 😔

I will look into this more but I feel like in the Firebase plugin there should be a way to set a snapshot stream to disable persistence or something along those lines.

**Comment by Ehesp** [comment]
> I am unsure however how to disable persistence for just one item.

Not possible sorry, this is something the underlying SDKs handle.

**Comment by Salakar** [comment]
As part of our on-going work for #2582, we've added the `Settings` api for persistence and also the api to clear persistence (`clearPersistence()` in our Firebase Firestore rework (#2913), but there is no apis to target persistence on specific items unfortunately, however; you can now use `GetOptions` with source set to `Source.server` to always force getting data from the server and bypass cache (but this won't work offline of course).
