### ISSUE TITLE
issue in firebase_crashlytics: ^0.1.3+3 for Flutter

### ISSUE THREAD

**Issue by kalpesh** [FirebaseExtended/flutterfire#2427]
Followed all instructions mentioned for the plugin installation from below url.

https://pub.dev/packages/firebase_crashlytics

Getting below error for android only. on iOS, it's working fine.

Build file 'android/build.gradle' line: 43
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'io.fabric']
   > Crashlytics was applied to a project without an Android plugin. Please make sure the Crashlytics plugin is applied after the appropriate Android plugin for your project.

**Comment by Jimexist** [comment]
@kalpesh FYI you should review https://github.com/FirebaseExtended/flutterfire/pull/2288 which updates everything

**Comment by russellwheatley** [comment]
Hey @kalpesh, I'm going to close this as it is 2 major versions removed from the latest version, and fabric has been completely removed from the underlying implementation.
