### ISSUE TITLE
[firebase_auth] "signInWithCredential" doesn't throw error with Google credentials

### ISSUE THREAD

**Issue by DanielZanchi** [FirebaseExtended/flutterfire#2428]
I'm trying to link a Facebook account to a Google account in firebase. 
The issue is that when I call 

> signInWithCredential
it doesn't throw the error how it should. When I try to link an existing Google account to a Facebook account, that method throws an error that I catch and then link the two accounts.

If I try to link an existing Facebook account to a Google account (with same mail obviously) the method doesn't throw any error and I find that Google replaces Facebook authentication method in Firebase Auth. 

This is the code I use to sign in with Google:

```
 Future<FirebaseUser> signInWithGoogle() async {
    final GoogleSignInAccount googleUser = await GoogleSignIn().signIn();
    final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    if (googleUser == null) {
      return null;
    }
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    try {
      final user = (await FirebaseAuth.instance.signInWithCredential(credential)).user;

      final FirebaseUser currentUser = await FirebaseAuth.instance.currentUser();
      assert(user.uid == currentUser.uid);
      return user;
    } on PlatformException catch (e) {
      print("error while google signin");
      SocialLoginError error =
          SocialLoginError(pendingCredential: credential, emailToLink: "no email, google", error: e);
      throw (error);
    }
  }
```

it never enters the catch block even if:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/6886116/80206990-a3eba080-862d-11ea-91db-b7946c8b94d7.png">

What's wrong? 

daniel@Daniels-MacBook-Pro mobile_reps % flutter doctor -v    
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/danielzanchi/Developer/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/danielzanchi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

Not complete, it's too long.
[runverbose.txt](https://github.com/FirebaseExtended/flutterfire/files/4540282/runverbose.txt)

**Comment by TahaTesser** [comment]
HI @DanielZanchi 
can you please provide your `flutter doctor -v` and `flutter run --verbose` while signing? 
Also, to better address the issue, would be helpful if you could post a minimal **runnable** code sample to reproduce the problem
Thank you

**Comment by DanielZanchi** [comment]
> HI @DanielZanchi
> can you please provide your `flutter doctor -v` and `flutter run --verbose` while signing?
> Also, to better address the issue, would be helpful if you could post a minimal **runnable** code sample to reproduce the problem
> Thank you

I updated my first post. I just call that method from a button tap. The issue is in that method and how it's handled.

**Comment by greghesp** [comment]
Hi @DanielZanchi 

There was a similar issue raised for the JS SDK a while back which you can [find here](https://github.com/firebase/firebase-js-sdk/issues/301#issuecomment-342569132)

The reason this happens is because Firebase Auth has a concept of "trusted providers."  Google are the trusted provider of gmail.com accounts, therefore if you when you sign in with Google, the account is already verified so overrides the account.

In your scenario, if the user is already signed in, then you can link their account with `linkWithCredential`.  If the user is not logged in, then you can call `fetchSignInMethodsForEmail` before using `signInWithCredential`.  That way you can check if their email address already has a provider, and if so, log them in and link their account.

You can read more about the trusted provider concept here: https://groups.google.com/g/firebase-talk/c/ms_NVQem_Cw/m/8g7BFk1IAAAJ
