### ISSUE TITLE
[firebase_messaging] Which is proper dependency?

### ISSUE THREAD

**Issue by nhwilly** [FirebaseExtended/flutterfire#243]
There are three different suggestions on which dependency to include in `firebase_messaging` found in four locations.

**In the `firebase_messaging` readme:**
![image](https://user-images.githubusercontent.com/7560842/65976734-975bec80-e43e-11e9-8482-2d90ecceac44.png)

**In the `firebase_messaging` example code:**
![image](https://user-images.githubusercontent.com/7560842/65976925-f7529300-e43e-11e9-8aa0-b34f976f66a3.png)

**In the Firebase project `Add Firebase to your Android app` instructions:**
![image](https://user-images.githubusercontent.com/7560842/65977169-721bae00-e43f-11e9-9f2b-4556816783ea.png)

**And in the "Get started with Firebase" in the docs**
![image](https://user-images.githubusercontent.com/7560842/65977605-3c2af980-e440-11e9-8909-99b48fa26e26.png)

Does anyone have any guidance on which to use and when?  I'm having lots of problems with iOS and messages going to the system tray and testing all possible combinations isn't really feasible.

I'm not really sure how these packages all related to each other (and which `flutter_messaging` version) and what I should use to get a working setup.  Clearly, it must have worked at one time or another.

TIA

**Comment by nhwilly** [comment]
My experience:
3.2.1/3.2.1 - deprecated messages but works.
3.2.1/4.3.0 - fails
3.3.0/4.3.0 - fails
3.3.0/4.3.2 - fails
3.2.1/4.3.2 - fails

**Comment by BondarenkoStas** [comment]
@nhwilly thank you for report! Please check https://github.com/FirebaseExtended/flutterfire/issues/57, the solution would be to set 3.2.1/4.2.0.

**Comment by Salakar** [comment]
Let's consolidate this on #57 (applies to all Firebase plugins) - we'll be looking at improving the overall integration docs in one location.
