### ISSUE TITLE
Database-When a missing index is required FlutterFire should create it

### ISSUE THREAD

**Issue by jamiethain** [FirebaseExtended/flutterfire#2430]
When building data driven mobile applications indicies need to be built "on the fly" instead of creating an error.  

The program I am working on, adds, 
   .orderby (orderParameter) and 
   .where (whereParmeter, isEqualTo: whereItem) 

Dynamically throughout the code. 

When the code produces the error " Listen for Query(commCategories where collection == commonData order by ordinal) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index. You can create it here: <xxxxxxxxxxxxxxxxxx> some long query string, 

It should actually create the index or be a feature to create the index.

**Comment by Ehesp** [comment]
The SDKs return a url in the error message which isn't being sent back to dart land. This is being tracked on another issue which I'll try to find.

**Comment by jamiethain** [comment]
Elliot,

We do get a URL back to Dart Land but what good is that to dynamically
created content. The "end user doesn't have access to "create a database"
index, we need a feature that says as part of the settings "dynamically
create database index" instead of sending back URLs.

I was seeing the data act irrationally throughout my entire data driven
application, and because the user can choose a different combination of
fields to filter on at Run time, It took me a long time to figure it out,
its a compound index problem.

Also often it wants to create a compound index where there are only 18 or
100 records, which you can just sort through, have you ever heard of "Jet
database"

The basic idea is when a query happens it reads through it by hand and
determines if there are enough records to be meaningful, it creates the
index it needs as its reading the database, if it doesn't need them (its
small, or they were following the primary key) then it doesn't create
them.  Jet was a microsoft product that solved this 20 years ago.

**Comment by Ehesp** [comment]
Apologies I thought the error returned didn't include it.

I appreciate this would be handy however this is something outside of FluttedFires possibility. These plugins wrap the native SDKs which doesn't expose this sort of functionality.

I'd suggest creating a feature request over on the Firebase console explaining.

**Comment by Ehesp** [comment]
> I was seeing the data act irrationally throughout my entire data driven
application, and because the user can choose a different combination of
fields to filter on at Run time, It took me a long time to figure it out,
its a compound index problem.

You'll need to create an index then for every possibility. I'd advise setting up a test runner which does this, and if the query fails it'll flag you to create the index via the console.

> Also often it wants to create a compound index where there are only 18 or
100 records, which you can just sort through, have you ever heard of "Jet
database"

Record size is irrelevant for indexing, you only need to do it once and it'll scale as the database grows.

Closing this off as it's not something which is possible (unfortunately).

**Comment by jamiethain** [comment]
Elliot,

If the flutter wrapper gets back the URL as an error, why couldn't the
wrapper do a request on the URL.

Jamie

**Comment by jamiethain** [comment]
Where should I post the issue?

Jamie
