### ISSUE TITLE
[firebase_dynamic_links] Link is being caught by onLink after opening app from dynamic link

### ISSUE THREAD

**Issue by li0nza** [FirebaseExtended/flutterfire#2431]
**Describe the bug**
When opening a dynamic link from a cold start, if you minimise and reopen the app by clicking on it's icon, `onLink`'s success call is called each time with the link used for `getInitialLink`

**To Reproduce**
1. Open link with app closed.
2. Minimise app, and re-open
3. Link will be fired again with `getInitialLink`'s link but in `onLink` this time.

**Expected behavior**
Link should not be used for `onLink` if it was used in `getInitialLink`

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by furkankurt** [comment]
Same issue here! Please fix ASAP 😩

**Comment by russellwheatley** [comment]
Hey @li0nza, I'm afraid that is not a bug. You're making an attempt to retrieve the initial link, and also listening for links.

**Comment by li0nza** [comment]
> Hey @li0nza, I'm afraid that is not a bug. You're making an attempt to retrieve the initial link, and also listening for links. 

Unfortunately this was not the case, but doesn't really matter anymore now
