### ISSUE TITLE
[firebase_messaging] Plugin with id 'com.google.gms.google-services' not found.

### ISSUE THREAD

**Issue by redjanym** [FirebaseExtended/flutterfire#2439]
**Describe the bug**
I'm trying to implement Firebase Messaging on a new Flutter app and i get this error message when i execute ```flutter run```:
```bash
A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.
```

**To Reproduce**
1. Create a new Flutter app, via Flutter cli tool or Android Studio
2. Directly start to install firebase_messaging plugin of Flutter by following the instructions.
4. Follow instructions 1,2,3,4 for Android Integration

**Expected behavior**
I expect to build the app
**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-AL)
    • Flutter version 1.12.13+hotfix.9 at /Users/redjanymeraj/Sites/flutter_development/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/redjanymeraj/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

I have also checked in SDK Manager if i had downloaded the Google Services package and yes, i already had it since i have been developing apps before i had this issue.

**Comment by iapicca** [comment]
Hi @redjanym 
can you please provide your full `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by redjanym** [comment]
Hi @iapicca 
thank you for your reply. I published a demo project on url: https://github.com/redjanym/flutter-issue-demo-project
The output of ```flutter run --verbose``` is found on file ```output-verbose.txt``` file in the root of the project
I again did the same steps:
1.  Flutter clean install via ```flutter create [name of project]``` 
2. Followed the steps 1-4 of installation of the Firebase Messaging plugin
3. Ran ```flutter run``` and i get the issue

I also tried gradle sync by oppenning the Android Module in Android Studio but still get the same issue.

**Comment by redjanym** [comment]
Hi @iapicca,

have you had any chance to test the issue?

Thanks a lot

**Comment by redjanym** [comment]
Hi guys. Do you have any idea why this might happen? I'm still not able to create and run a new flutter app on android.

**Comment by prakharb10** [comment]
Hi @redjanym 
I looked at the [repo](https://github.com/redjanym/flutter-issue-demo-project) you mentioned. Can you try adding the line `apply plugin: 'com.google.gms.google-services'` to your **app/build.gradle** file and then building the app?
Also, try upgrading flutter to the latest stable version.

**Comment by redjanym** [comment]
Hi @prakharb10 
i already have added the plugin line in app/build.gradle and the issue continues. But i managed to solve the problem differently. 
I had taken from the installation instructions also this line [classpath 'com.android.tools.build:gradle:3.5.3'](https://github.com/redjanym/flutter-issue-demo-project/blob/4e5cfbbdf5dd884ddff95d0089e17e0bd1c1da94/android/build.gradle#L35) which is given as an example of the existing configurations and that's my bad but i still think that is a bit confusing. 
I think maybe would be best to substitute the example line with dots `...` like in many other projects when they symbolise the fact that other code may be present. 
Thanks for the response anyway.
