### ISSUE TITLE
[cloud_firestore] Regression in equality from 0.12.11 to 0.13.5

### ISSUE THREAD

**Issue by jackdreilly** [FirebaseExtended/flutterfire#2440]
**Describe the bug**
Equality between DocumentReference objects with identical paths created in the same fashion returns true in 0.12.11 and false in 0.13.5

**To Reproduce**
 Run this test:
```dart
void main() {
  test("query", () {
    TestWidgetsFlutterBinding.ensureInitialized();
    expect(
        Firestore.instance.document('a/b'), Firestore.instance.document('a/b'));
  });
}
```

**Expected behavior**
The above test should pass (it does in 0.12.11, it does *not* in 0.13.3)

**Additional context**
The equality fails because the equality method on `Firestore` class was removed between the two versions.

The test above passes by adding the following lines back into `Firestore` class:

```dart
@override
bool operator ==(dynamic o) => o is Firestore && o.app == app;

@override
int get hashCode => app.hashCode;
```

These lines were removed between the two versions

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.14.6 18G3020, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (3 available)

• No issues found!
```

Related issue: #2019

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
