### ISSUE TITLE
[cloud_firestore] Error: Too many positional arguments

### ISSUE THREAD

**Issue by 0PIXIU0** [FirebaseExtended/flutterfire#2443]
Compiler message:
```bash
lib/home/setprofile.dart:170:35: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    userQuery = dbRef.orderByValue('name').onChildAdded;
```

 Listed below is the source code for orderByValue.  

```dart
/// Generate a view of the data sorted by value.
  ///
  /// Intended to be used in combination with [startAt], [endAt], or
  /// [equalTo].
  Query orderByValue() {
    assert(!_parameters.containsKey('orderBy'));
    return _copyWithParameters(<String, dynamic>{'orderBy': 'value'});
  }
```

As a newbie for Dart and Flutter, I hope my fundamental knowledge of dart programing language is correct

BTW, I think we really should give more examples of how the query works. As far as I see , Firebase have the worst documentation and example. It's good to have more tutorials to draw public interest. However, In the world of programming, there is no absolute right way to all situations and programming is not exactly copy and paste from another tutor's code or their programming logic.    
Of course, If firebase team's intension is phasing out the realtime database, then I think the team did a real good job.

**Comment by iapicca** [comment]
Hi @0PIXIU0 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by 0PIXIU0** [comment]
Firstly, Thanks for getting back to me!
Second, I do not understand why you have to change the title to [cloud_firestore]. Come on, The function I invoke in my code is the realtime database-specific function (orderByValue, last time I checked, firestore has no such function).
Third, I think we can close this by now as I stop the usage of firebase realtime database library. It lacks support and interest from the public!  I agree that the error 'Too many positional arguments' likely depends on the code. However, such code is invokable functions from the firebase realtime database flutter library as list below 
`/// Generate a view of the data sorted by value.
  ///
  /// Intended to be used in combination with [startAt], [endAt], or
  /// [equalTo].
  Query orderByValue() {
    assert(!_parameters.containsKey('orderBy'));
    return _copyWithParameters(<String, dynamic>{'orderBy': 'value'});
  }
`
as you clearly able to notice , such function takes no arguments !  


If you are truly interested in fixing this problem, 
FLUTTER DOCTOR -V  :
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76,
    locale en-CA)
    • Flutter version 1.12.13+hotfix.9 at /Users/ken/Desktop/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ken/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 5F00555B-FE04-4057-B071-7A8E34BD0FF7 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!

PUBSPEC library and version number:
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  image_picker: ^0.6.5+2
  image_cropper: ^1.2.1
  firebase_core: ^0.4.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_database: ^3.1.3
