### ISSUE TITLE
[<FIREBASE_Messaging>] <push notification is not received>

### ISSUE THREAD

**Issue by ederluca** [FirebaseExtended/flutterfire#2460]
** Describe the bug **
I am facing a problem where I trigger a notification for two devices one of the devices receives the notification without major problems the other does not, analyzing it I cannot find the problem simply some devices do not receive the notification. Has anyone ever experienced this?

**Reproduce**

**Expected behavior**
I need all devices with the same application to receive the push and not just some.

** Additional context **

** Flutter Doctor **
As I reported above, the error happens only on the clients' devices, both my test device and the simulators I am normally receiving the push.

Below is the function I created to implement the push:

Future <void> registerNotification (context) async {
  Duration timeout;
  SharedPreferences prefs = await SharedPreferences.getInstance ();
  timeout = Duration (seconds: 30);

  _firebaseMessaging.requestNotificationPermissions ();
  if (Platform.isAndroid) {
    _firebaseMessaging.configure (
      onBackgroundMessage: myBackgroundMessageHandler,
      onMessage: (Map <String, dynamic> message) async {
        await pushTreatment (message);
        await pushInf (message, false, context);
        if (Platform.isAndroid) {
          message.clear ();
        }
      },
      onLaunch: (Map <String, dynamic> message) async {
        await pushTreatment (message);
        await Future.delayed (Duration (seconds: 1));
        if (Platform.isAndroid) {
          message.clear ();
        }
      },
      onResume: (Map <String, dynamic> message) async {
        await pushTreatment (message);
        await Future.delayed (Duration (seconds: 1));
        pushDestino (message, context);

        if (Platform.isAndroid) {
          message.clear ();
        }
      },
    );
  } else {
    _firebaseMessaging.configure (
      onMessage: (Map <String, dynamic> message) async {
        await pushTreatment (message);
        await pushInf (message, false, context);
        if (Platform.isAndroid) {
          message.clear ();
        }
      },
      onLaunch: (Map <String, dynamic> message) async {
        await pushTreatment (message);
        await Future.delayed (Duration (seconds: 1));

        if (Platform.isAndroid) {
          message.clear ();
        }
      },
      onResume: (Map <String, dynamic> message) async {
        await pushTreatment (message);
        await Future.delayed (Duration (seconds: 1));
        pushDestino (message, context);
        if (Platform.isAndroid) {
          message.clear ();
        }
      },
    );
  }

  _firebaseMessaging.requestNotificationPermissions (
    const IosNotificationSettings (sound: true, badge: true, alert: false),
  );
  _firebaseMessaging.onIosSettingsRegistered.listen ((IosNotificationSettings settings) {
    // print ("Settings registered: $ settings");
  });
}

**Comment by TahaTesser** [comment]
Hi @ederluca 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Thank you

**Comment by Okiring** [comment]
Firebase messaging has been working fine  on my phone but when my phone updated its support libraries, the push notifications stopped working... The onmessge is nolonger triggered..it doesnt even print any message yet the rest api says the message was successfully sent......have been paying attention to these phones,its the second time have encounted this...once any device updates its support libraries, the push notifcations suddenly stop working...seems there is nothing we can do...its google to fix its issue...even if a device has the most updated google play services, u still wont see e notifications on most of the devices.. E.g tecno ...etc...very few devices show the notifications..

**Comment by TahaTesser** [comment]
Hi @ederluca 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
