### ISSUE TITLE
[firebase_storage] Extract platform interface

### ISSUE THREAD

**Issue by sbeitzel** [FirebaseExtended/flutterfire#2463]
**Is your feature request related to a problem? Please describe.**
We'd sure love to be able to use firebase_storage with Flutter Web (see #1972, flutter/flutter#45294). The first step in supporting the web platform is to migrate the plugin to use the platform interface pattern.

**Describe the solution you'd like**
Modeling the plugin architecture on cloud_firestore or cloud_functions or firebase_auth, define the platform interface and rewrite the current plugin so that it is using the platform interface. This will open the door to additional platform implementations.

**Comment by Maxim-Filimonov** [comment]
Took an initial spin at [the platform interface](https://github.com/Maxim-Filimonov/firebase_storage_platform_interface). 
Largely based on cloud_firestore. 

Needs:
- Tests
- Move appropriate types to platform_interfaces
- Recover method handler - right now commented out.

Any feedback or help would be great.

**Comment by Ehesp** [comment]
We'll be doing this as part of #2582 when we get to it.

**Comment by Maxim-Filimonov** [comment]
> We'll be doing this as part of #2582 when we get to it.

Okay. Should I stop the work on it for now then ?

**Comment by Salakar** [comment]
> > We'll be doing this as part of #2582 when we get to it.
> 
> Okay. Should I stop the work on it for now then ?
> I just need upload functionality of firebase_storage

Yes please, we're nearing completion so don't want to duplicate effort.

**Comment by Salakar** [comment]
Official support for Web (along with a platform interface) has now been shipped. Thanks everyone.
