### ISSUE TITLE
[cloud_firestore] The plugin initialise the default app 

### ISSUE THREAD

**Issue by long1eu** [FirebaseExtended/flutterfire#2466]
I don't want to use the default app, I am initialising my FirebaseApp manually, but `cloud_firestore` initialises the default app anyways. Why?

```
    if (![FIRApp appNamed:@"__FIRAPP_DEFAULT"]) {
      NSLog(@"Configuring the default Firebase app...");
      [FIRApp configure];
      NSLog(@"Configured the default Firebase app %@.", [FIRApp defaultApp].name);
    }
```  

Same is true for `cloud_functions`, `firebase_auth`, `firebase_messaging`, `firebase_storage`.

**Comment by Salakar** [comment]
Hey all, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
