### ISSUE TITLE
[firebase_messaging] onLaunch called multiple times [Android]

### ISSUE THREAD

**Issue by Akora-IngDKB** [FirebaseExtended/flutterfire#2476]
`onLaunch` is being called multiple times for a single notification even after unsubscribing from topic. This happens even when the app is in the foreground.  
It happens after navigating to and from another screen.

**To Reproduce**
1. Create a `StatefulWidget`.
2. Configure `firebase_messaging` in the `initState` of the widget create in step 1.
3. Send notification from Firebase Console.
4. Navigate to another screen and back.

**Expected behavior**
Notification is sent once. It appears in the system tray and it also responds to `click_action`. Once clicked, notification disappears, app opens and fires the `onLaunch` callback and that notification is not expected to appear again on the device.

**`flutter doctor -v`**
```
[√] Flutter (Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.18362.175], locale en-GH)
    • Flutter version 1.17.0-3.2.pre at D:\flutter
    • Framework revision 2a7bc389f2 (10 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\debra\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\debra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\debra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • SM A305F   • R58M62W011R • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome      • web-javascript • Google Chrome 81.0.4044.129
    • Web Server • web-server  • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi @Akora-IngDKB 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1669) addressing the case you described even if not specific for `onLaunch`.

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
