### ISSUE TITLE
[firebase_messaging] While .configurate "PlatformException(error, PluginRegistrantCallback is not set., null)"

### ISSUE THREAD

**Issue by earyzhe** [FirebaseExtended/flutterfire#248]
**Describe the bug**
When trying to configure the  Firebase Cloud Messaging an Exception is thrown.
PlatformException (PlatformException(error, PluginRegistrantCallback is not set., null))

**To Reproduce**
Call the configure function.
<img width="836" alt="Screenshot 2019-10-02 at 12 06 10" src="https://user-images.githubusercontent.com/26453863/66036272-1ddeff80-e50d-11e9-8a63-766d2361ea4a.png">

**Stack Trance**
```
E/flutter (17015): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, PluginRegistrantCallback is not set., null)
E/flutter (17015): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (17015): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
E/flutter (17015): <asynchronous suspension>
E/flutter (17015): #2      FirebaseMessaging.configure 
package:firebase_messaging/firebase_messaging.dart:118
E/flutter (17015): #3      _configureMessaging 
package:firebase_cloud_messaging_play/main.dart:28
E/flutter (17015): #4      main 
package:firebase_cloud_messaging_play/main.dart:9
E/flutter (17015): #5      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:231:25)
E/flutter (17015): #6      _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (17015): #7      _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (17015): #8      _runZoned  (dart:async/zone.dart:1516:10)
E/flutter (17015): #9      runZoned  (dart:async/zone.dart:1500:12)
E/flutter (17015): #10     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:223:5)
E/flutter (17015): #11     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (17015): #12     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (17015):
```

**Additional context**
The repo is here
https://github.com/earyzhe/firebase_cloud_messaging_play

**Comment by GProDev2019** [comment]
Hello, 
I have the same issue.
Any ideas how to solve it?

**Comment by charleshan** [comment]
This issue should be rename to `[firebase_messaging] PlatformException thrown on configuration`

**Comment by nmnclk** [comment]
Please help I have same problem .

**Comment by Eddydpyl** [comment]
Several people have managed to get around the issue (me included):
https://github.com/FirebaseExtended/flutterfire/issues/199
https://github.com/FirebaseExtended/flutterfire/issues/116

**Comment by mhadaily** [comment]
I still have this issue and it only works when I delete 
```// onBackgroundMessage: Platform.isIOS ? null : backgroundMessageHandler,```

**Comment by insinfo** [comment]
someone got any solution

**Comment by MustafaGamalAbbas** [comment]
Same Issue. :(

**Comment by sgehrman** [comment]
same issue.

**Comment by oe19fyfa** [comment]
Any news? I am getting the same issue... Did anyone try lower versions of the plugin?

**Comment by marceloiavenissi** [comment]
Hello I followed the tutorial and had this problem.
1 - Replaces <application android: name = ". Application" with <application android: name = "com.myorg.myapp.Application".
2 - I had to add a cast to line 19 of Application.java:
GeneratedPluginRegistrant.registerWith ((FlutterEngine) registry);
3 - I put all functions (onMessage, onBackgroundMessage, onLaunch, onResume) as top-level.
4 - versions:
classpath 'com.android.tools.build:gradle:3.5.3'
classpath 'com.google.gms: google-services: 4.3.2'
5 - I added: implementation 'com.google.firebase: firebase-messaging: 20.1.0'

And the problem has now changed to:
[ERROR: flutter /lib/ui/ui_dart_state.cc (157)] Unhandled Exception: PlatformException (error, io.flutter.app.FlutterPluginRegistry cannot be cast to io.flutter.embedding.engine.FlutterEngine, null)

**Comment by marceloiavenissi** [comment]
> Hello I followed the tutorial and had this problem.
> 1 - Replaces <application android: name = ". Application" with <application android: name = "com.myorg.myapp.Application".
> 2 - I had to add a cast to line 19 of Application.java:
> GeneratedPluginRegistrant.registerWith ((FlutterEngine) registry);
> 3 - I put all functions (onMessage, onBackgroundMessage, onLaunch, onResume) as top-level.
> 4 - versions:
> classpath 'com.android.tools.build:gradle:3.5.3'
> classpath 'com.google.gms: google-services: 4.3.2'
> 5 - I added: implementation 'com.google.firebase: firebase-messaging: 20.1.0'
> 
> And the problem has now changed to:
> [ERROR: flutter /lib/ui/ui_dart_state.cc (157)] Unhandled Exception: PlatformException (error, io.flutter.app.FlutterPluginRegistry cannot be cast to io.flutter.embedding.engine.FlutterEngine, null)

To solve the problem, I removed the cast I had placed on line 19 and used the FirebaseCloudMessagingPluginRegistrant.java class that I found at this link:
https://stackoverflow.com/questions/59446933/pluginregistry-cannot-be-converted-to-flutterengine

And it worked perfectly in the background.

**Comment by oe19fyfa** [comment]
@marceloiavenissi did you use the sendNotificationOnBackground dart function from the stackoverflow as your (onMessage, onBackgroundMessage, onLaunch, onResume) at top-lavel?

**Comment by marceloiavenissi** [comment]
> @marceloiavenissi did you use the sendNotificationOnBackground dart function from the stackoverflow as your (onMessage, onBackgroundMessage, onLaunch, onResume) at top-lavel?

No, just the same FirebaseCloudMessagingPluginRegistrant class

**Comment by oe19fyfa** [comment]
`
    class NotificationServiceImpl {
  
    // make it singleton pls
    static final NotificationServiceImpl _singleton = NotificationServiceImpl._internal();
  
    static Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) {
      print("triggerd");
  
      if (message.containsKey('data')) {
        // Handle data message
        final dynamic data = message['data'];
      }
  
      if (message.containsKey('notification')) {
        // Handle notification message
        final dynamic notification = message['notification'];
      }
  
      return null;
      // Or do other work.
    }
  

    bool _initialized = false;
    String _fcmToken;
  
    Future<void> init() async {
      if (!_initialized) {
        // For iOS request permission first.
        _firebaseMessaging.requestNotificationPermissions();
  
        // _firebaseMessaging.configure();
  
        _firebaseMessaging.configure(
          onMessage: (Map<String, dynamic> message) async {
            print("onMessage: $message");
          },
          onBackgroundMessage: myBackgroundMessageHandler,
          onLaunch: (Map<String, dynamic> message) async {
            print("onLaunch: $message");
          },
          onResume: (Map<String, dynamic> message) async {
            print("onResume: $message");
          },
        );
  
        _fcmToken = await _firebaseMessaging.getToken();
        print("Token : "+_fcmToken);
  
        _initialized = true;
      }
    }
  
    Future<String> getToken() async {
      if (!_initialized) {
        await init();
      }
      return _fcmToken;
    }
  
  
  
    }
`

So at this point the callback triggers on background. However at build Process i am still getting an error: 
`
  Unhandled Exception: Invalid argument(s): Failed to setup background message handler! `onBackgroundMessage`
E/flutter (24529):           should be a TOP-LEVEL OR STATIC FUNCTION and should NOT be tied to a
E/flutter (24529):           class or an anonymous function.
`

Am I doing something wrong here? Isn't it already top level?

**Comment by marceloiavenissi** [comment]
@oe19fyfa This is not wrong anyway. But how is your application.java and the manifest?

**Comment by oe19fyfa** [comment]
So I have 3 files in my package: Application.java ,FirebaseCloudMessagingPluginRegistrant.java as mentioned in SO. I also have a MainActivity.java that i had prior to SO stuff.
`
      package mapackag;
    
    public class MainActivity extends FlutterActivity {
      @Override
      protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
      }
    }

`

**Comment by marceloiavenissi** [comment]
No errors were corrected when replacing GeneratedPluginRegistrant with FirebaseCloudMessagingPluginRegistrant on line 19 of the Application.

**Comment by AvatarDevs** [comment]
hey guys, while following the guide on the package i also got the error.

I referenced some code from over a year ago using the package and the following works:
`
    _messaging.requestNotificationPermissions();

    _messaging.configure(onLaunch: (data) {
      print("onLaunch $data");
    }, onMessage: (data) {
      print("onMessage $data");
    }, onResume: (data) {
      print("OnResume $data");
    });
`

this will at least get rid of the error, and should still allow your devices to receive notifications - at least on android. I havent tested on iOS.

**Comment by ACHEZ9** [comment]
Piggybacking on this issue to point out that firebase_messaging does not properly support Flutter Android Embedding V2. This same error is thrown when the `pluginRegistrantCallback` is not set, but this is not required for V2. It should not be required to extend `FlutterApplication` and call `FlutterFirebaseMessagingService.setPluginRegistrant` when using newer Flutter versions.

**Comment by KanybekMomukeyev** [comment]
Same here, any solutions? Pls help

**Comment by Ehesp** [comment]
Hello - please can you check whether this is an issue on the latest messaging plugin (6.0.13 at this time). Thanks,

**Comment by ejprok** [comment]
> Several people have managed to get around the issue, me included (#199 | #116). In my case, there was an incompatibility caused by the barcode_scan package.

Any luck getting barcode_scan to work with firebase_messaging or did you have to find an alternative?

**Comment by Eddydpyl** [comment]
@ejprok In the end I switched to qrcode_reader, which worked for me.

**Comment by carlosesquivel-katoo** [comment]
I have followed the code in the example app with a blank app from Flutter create (Flutter version: 1.12.13+hotfix.9 and with version 6.0.13) and I get the following error: 

> java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.

And the application just dies when receiving a notification (this is without setting the backgroundMessages handler). If I set it, then I get the following error on app initialization:

> PlatformException (PlatformException(error, PluginRegistrantCallback is not set., null))

Any pointers?

**Comment by carlosesquivel-katoo** [comment]
> I have followed the code in the example app with a blank app from Flutter create (Flutter version: 1.12.13+hotfix.9 and with version 6.0.13) and I get the following error:
> 
> > java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.
> 
> And the application just dies when receiving a notification (this is without setting the backgroundMessages handler). If I set it, then I get the following error on app initialization:
> 
> > PlatformException (PlatformException(error, PluginRegistrantCallback is not set., null))
> 
> Any pointers?

So, got it working by patching info from several sources. For some reason my MainActivity was in Kotlin, so the Application class needs to be in Kotlin as well. My Application.kt file looks like this:

`class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    }
}`

Using solution from (https://github.com/FirebaseExtended/flutterfire/issues/1613#issuecomment-565293988). I also needed to add the following (per https://github.com/FirebaseExtended/flutterfire/issues/1607#issuecomment-577028200):

in android/app/build.gradle
implementation "com.google.firebase:firebase-messaging:20.1.0"

**Comment by bretie** [comment]
This is still a very big issue clearly from researching the errors involved in registering the plugin on Android.

Most users are hacking together from 10-20 sources and there is no definite answer to the problem.

Can we get some updated documentation on this issue related to Kotlin?

**Comment by Maus3rSR** [comment]
I have the same issue with latest version of the plugin 
`firebase_messaging: ^6.0.16`

**Comment by Maus3rSR** [comment]
> 
> 
> > I have followed the code in the example app with a blank app from Flutter create (Flutter version: 1.12.13+hotfix.9 and with version 6.0.13) and I get the following error:
> > > java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.
> > 
> > 
> > And the application just dies when receiving a notification (this is without setting the backgroundMessages handler). If I set it, then I get the following error on app initialization:
> > > PlatformException (PlatformException(error, PluginRegistrantCallback is not set., null))
> > 
> > 
> > Any pointers?
> 
> So, got it working by patching info from several sources. For some reason my MainActivity was in Kotlin, so the Application class needs to be in Kotlin as well. My Application.kt file looks like this:
> 
> ```
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>     }
> }
> ```
> 
> Using solution from ([#1613 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1613#issuecomment-565293988)). I also needed to add the following (per [#1607 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1607#issuecomment-577028200)):
> 
> in android/app/build.gradle
> `implementation "com.google.firebase:firebase-messaging:20.1.0"`

From my side it's just crashing when installing the APK on my device. I do not know how to debug this...

```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [version 10.0.18362.836], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.0)
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (1 available)
```

Device : `SM G950F (android-arm64)`

I followed up @carlosesquivel-katoo solution, however the Application.kt is crashing the app.

**Comment by Maus3rSR** [comment]
With `flutter run --verbose`

Logs when build succeed: 

```
[  +30 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[  +39 ms] executing: C:\Users\KEVINUS\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree E:\Developpement\Web\Projects\FlutterApps\enchere_equestre\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +35 ms] Exit code 0 from: C:\Users\KEVINUS\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree E:\Developpement\Web\Projects\FlutterApps\enchere_equestre\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +54 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.bonnemaison.app" (Raw: "com.bonnemaison.app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x12
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw: "com.google.android.c2dm.permission.RECEIVE")
               E: application (line=20)
                 A: android:label(0x01010001)="Bonne Maison" (Raw: "Bonne Maison")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="com.bonnemaison.app.Application" (Raw: "com.bonnemaison.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=26)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.bonnemaison.app.MainActivity" (Raw: "com.bonnemaison.app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=33)
                     E: action (line=34)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=36)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                   E: intent-filter (line=38)
                     E: action (line=39)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=41)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
                 E: meta-data (line=48)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: service (line=52)
                   A: android:name(0x01010003)="io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService" (Raw: "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService")
                   E: intent-filter (line=53)
                     E: action (line=54)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=57)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw: "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=61)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar" (Raw: "com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=64)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar" (Raw: "com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=67)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar" (Raw: "com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=70)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.iid.Registrar" (Raw: "com.google.firebase.components:com.google.firebase.iid.Registrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                 E: activity (line=75)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw: "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: provider (line=80)
                   A: android:name(0x01010003)="io.flutter.plugins.imagepicker.ImagePickerFileProvider" (Raw: "io.flutter.plugins.imagepicker.ImagePickerFileProvider")
                 E: meta-data (line=121)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw: "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f060000
                 E: service (line=125)
                   A: android:name(0x01010003)="com.google.android.datatransport.runtime.backends.TransportBackendDiscovery" (Raw: "com.google.android.datatransport.runtime.backends.TransportBackendDiscovery")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: meta-data (line=128)
                     A: android:name(0x01010003)="backend:com.google.android.datatransport.cct.CctBackendFactory" (Raw: "backend:com.google.android.datatransport.cct.CctBackendFactory")
                     A: android:value(0x01010024)="cct" (Raw: "cct")
                 E: service (line=132)
                   A: android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" (Raw: "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw: "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=138)
                   A: android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver" (Raw: "com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[ +101 ms] Stopping app 'app.apk' on SM G950F.
[   +1 ms] executing: C:\Users\KEVINUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.11:5555 shell am force-stop com.bonnemaison.app
[ +213 ms] executing: C:\Users\KEVINUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.11:5555 shell pm list packages com.bonnemaison.app
[ +152 ms] package:com.bonnemaison.app
[   +2 ms] executing: C:\Users\KEVINUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.11:5555 shell cat /data/local/tmp/sky.com.bonnemaison.app.sha1
[  +65 ms] 516cc7a77c6fb3a905420cd601788f65b6965f06
[   +1 ms] Latest build already installed.
[        ] SM G950F startApp
[   +1 ms] executing: C:\Users\KEVINUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.11:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.bonnemaison.app/com.bonnemaison.app.MainActivity
[ +176 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.bonnemaison.app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```

And as it crash it does nothing else..

**Comment by Maus3rSR** [comment]
> 
> 
> > I have followed the code in the example app with a blank app from Flutter create (Flutter version: 1.12.13+hotfix.9 and with version 6.0.13) and I get the following error:
> > > java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.
> > 
> > 
> > And the application just dies when receiving a notification (this is without setting the backgroundMessages handler). If I set it, then I get the following error on app initialization:
> > > PlatformException (PlatformException(error, PluginRegistrantCallback is not set., null))
> > 
> > 
> > Any pointers?
> 
> So, got it working by patching info from several sources. For some reason my MainActivity was in Kotlin, so the Application class needs to be in Kotlin as well. My Application.kt file looks like this:
> 
> ```
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> 
> class Application : FlutterApplication(), PluginRegistrantCallback {
>     override fun onCreate() {
>         super.onCreate()
>         FlutterFirebaseMessagingService.setPluginRegistrant(this)
>     }
> 
>     override fun registerWith(registry: PluginRegistry?) {
>         io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>     }
> }
> ```
> 
> Using solution from ([#1613 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1613#issuecomment-565293988)). I also needed to add the following (per [#1607 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1607#issuecomment-577028200)):
> 
> in android/app/build.gradle
> `implementation "com.google.firebase:firebase-messaging:20.1.0"`

Implementing this solved my problem.

**Be aware if you are a noob like me:**
- replace `android:name="io.flutter.app.FlutterApplication"` by `android:name=".Application"` in AndroidManifest.xml
- add a file in the same location as your `MainActivity.kt`
- In your `Application.kt` **do not forget to add `package com.yourpackage.example`**

**Comment by andzejsw** [comment]
Same issue for me in firebase_messaging: ^6.0.16
