### ISSUE TITLE
 Build failed with an exception.  * Where: Build file line: 35  * What went wrong: A problem occurred evaluating root project 'android'. > Could not find method implementation() for arguments [com.android.support:support-annotations:28.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by skroys** [FirebaseExtended/flutterfire#2494]
```

**ERROR EXCEPTION:**
Launching lib\main.dart on  in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'G:\programs\flutterproject\post\android\build.gradle' line: 35

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [com.android.support:support-annotations:28.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.

```

```
**Project level build.gradle :**
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
            jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

dependencies {
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.android.support:support-v13:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'

}

**app level build.gradle file:**
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:customtabs:28.0.0'
    implementation 'com.android.support:support-media-compat:28.0.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.4.0'
}
apply plugin: 'com.google.gms.google-services'
```

**gradle.properties file:**

org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

**EXPECTED Behavior** 
Project should build and run successfully

I tried all previous solution but nothing worked for me.
Please help to solve this issue is not same I searched 
Thanks in advance.

**Comment by TahaTesser** [comment]
Hi @skroys 
Your `build.gradle` in your app folder might probably wrong keyword for dependencies 
Please check this [solution](https://stackoverflow.com/a/45616286)

if the problem persists after trying the solution, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by skroys** [comment]
Thanks for response @TahaTesser . But I already tried solution on stackoverflow .but not working.

**Comment by skroys** [comment]
@TahaTesser 
flutter run --verbose output:
[  +36 ms] executing: [G:\programs\android\flutter\] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +114 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +3 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [G:\programs\android\flutter\] git describe --match
v*.*.* --first-parent --long --tags
[  +57 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.12.13+hotfix.9-0-gf139b1100
[  +14 ms] executing: [G:\programs\android\flutter\] git rev-parse
--abbrev-ref --symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [G:\programs\android\flutter\] git ls-remote --get-url
origin
[  +50 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +101 ms] executing: [G:\programs\android\flutter\] git rev-parse
--abbrev-ref HEAD
[  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +449 ms] executing:
C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +253 ms] Exit code 0 from:
C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +3 ms] List of devices attached
[  +37 ms] No supported devices connected.
[  +38 ms] "flutter run" took 855ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main
(file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tool
s.dart:8:3)
#40     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:174:12)


flutter doctor -v output:
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version
    10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at G:\programs\android\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: G:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at G:\Program Files\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[!] VS Code
    • VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @skroys 
Please attach a device while running the project and provide `flutter run --verbose`
```
[ +3 ms] List of devices attached
[ +37 ms] No supported devices connected.
[ +38 ms] "flutter run" took 855ms.
```

To better address the issue, would be helpful if you could post a  **minimal code sample** to reproduce the problem
Thank you

**Comment by skroys** [comment]
Hi @TahaTesser 
I am new to flutter.I already above given ERROR of grade same is in flutter run bellow

**flutter run --verbose log**

[  +34 ms] executing: [G:\programs\android\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +324 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +1 ms] executing: [G:\programs\android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +80 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +29 ms] executing: [G:\programs\android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [G:\programs\android\flutter\] git ls-remote --get-url origin
[  +78 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +101 ms] executing: [G:\programs\android\flutter\] git rev-parse --abbrev-ref HEAD
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +225 ms] executing: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +36 ms] Exit code 0 from: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           71ead32a               device product:1610 model:vivo_1610 device:1610 transport_id:2
[  +25 ms] C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe -s 71ead32a shell getprop
[ +147 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +118 ms] Found plugin cloud_firestore at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\
[  +10 ms] Found plugin cloud_firestore_web at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +17 ms] Found plugin firebase_auth at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.0\
[   +5 ms] Found plugin firebase_auth_web at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +3 ms] Found plugin firebase_core at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +4 ms] Found plugin firebase_core_web at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[ +491 ms] Found plugin cloud_firestore at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\
[   +5 ms] Found plugin cloud_firestore_web at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +17 ms] Found plugin firebase_auth at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.0\
[   +7 ms] Found plugin firebase_auth_web at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +4 ms] Found plugin firebase_core at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +9 ms] Found plugin firebase_core_web at G:\programs\android\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[ +119 ms] Generating G:\programs\flutterproject\post\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +85 ms] ro.hardware = qcom
[  +73 ms] Launching lib\main.dart on vivo 1610 in debug mode...
[  +22 ms] executing: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe -s 71ead32a shell -x logcat -v time -t 1
[ +192 ms] Exit code 0 from: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe -s 71ead32a shell -x logcat -v time -t 1
[  +27 ms] --------- beginning of main
           05-09 13:51:57.106 W/qti_sensors_hal( 1377): timestampCalc: Adjusting timestamp for rollover: 1874662209542008, 2623
[  +13 ms] executing: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +2 ms] executing: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe -s 71ead32a logcat -v time -T 05-09 13:51:57.106
[  +57 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +5 ms] executing: C:\Users\LENOVO\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +90 ms] Building APK
[  +42 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +8 ms] Using gradle from G:\programs\flutterproject\post\android\gradlew.bat.
[  +18 ms] executing: G:\Program Files\Android Studio\jre\bin\java -version
[ +557 ms] Exit code 0 from: G:\Program Files\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +4 ms] executing: G:\Program Files\Android Studio\jre\bin\java -version
[ +131 ms] Exit code 0 from: G:\Program Files\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +6 ms] executing: [G:\programs\flutterproject\post\android\] G:\programs\flutterproject\post\android\gradlew.bat -Pverbose=true
-Ptarget=G:\programs\flutterproject\post\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm
assembleDebug
[+3893 ms] Welcome to Gradle 5.6.4!
[   +1 ms] Here are the highlights of this release:
[        ]  - Incremental Groovy compilation
[   +1 ms]  - Groovy compile avoidance
[   +1 ms]  - Test fixtures for Java projects
[   +1 ms]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.4/release-notes.html
[+2988 ms] > Configure project :app
[  +10 ms] WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
[   +1 ms] It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
[  +88 ms] FAILURE: Build failed with an exception.
[   +6 ms] * Where:
[   +1 ms] Build file 'G:\programs\flutterproject\post\android\build.gradle' line: 35
[   +1 ms] * What went wrong:
[   +1 ms] A problem occurred evaluating root project 'android'.
[   +1 ms] > Could not find method implementation() for arguments [com.android.support:support-annotations:28.0.0] on object of type
org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
[   +3 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +8 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 6s
[ +430 ms] Running Gradle task 'assembleDebug'... (completed in 8.1s)
[   +4 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[  +10 ms] Building plugin cloud_firestore...
[   +6 ms] Running Gradle task 'assembleAarRelease'...
[  +14 ms] "flutter run" took 10,155ms.
The plugin cloud_firestore could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
task.dart:43:21)

**Comment by TahaTesser** [comment]
Hi @skroys 
Please migrate your project to Androidx using [AndroidX Migration](https://flutter.dev/docs/development/androidx-migration) and enable [Multidex](https://developer.android.com/studio/build/multidex)
and try again

**Comment by skroys** [comment]
Yes I migrated to androidx and it worked for me.
