### ISSUE TITLE
CI is red

### ISSUE THREAD

**Issue by amirh** [FirebaseExtended/flutterfire#2499]
Seems like the same issue as https://github.com/flutter/flutter/issues/55743 is a contributing factor. However PRs were landed on red so I can't be sure it's the only issue.

@kroikie @cyanglaz

**Comment by amirh** [comment]
#2509 fixed the iOS tasks that were failing. There's an additional CI failure on master for some Android targets (haven't looked into the details).

**Comment by Salakar** [comment]
Remaining issue fixed in #2519 - thanks!
