### ISSUE TITLE
[firebase_admob] ads showing in old release build of an app but not in recent one

### ISSUE THREAD

**Issue by EngDjango** [FirebaseExtended/flutterfire#2500]
recently I've build a release of an app and found no ads are showing neither banner or native ads, but I have another old version of the same app and the ads are working in it!
the same ad units and the same app id;
i've spent over a day on this but no luck;
any body has an explanation for this please?

**Comment by TahaTesser** [comment]
Hi @EngDjango 
can you please provide your `flutter doctor -v` and `flutter run --verbose` while trying to load the app in new version app? 
Thank you

**Comment by EngDjango** [comment]
thank you for replying
here is `flutter doctor -v` output :
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.815], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at D:\Programming\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Programming\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:Programming\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • A5010  • android-x86 • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

and the output of `flutter run --verbose` is attached;
thank you again;

[output.txt](https://github.com/FirebaseExtended/flutterfire/files/4586576/output.txt)

**Comment by EngDjango** [comment]
test ads already showing in debug and release builds but no real ads in the latest release;

**Comment by EngDjango** [comment]
all i get is :
`W/flutter ( 2825): onAdFailedToLoad: 3`
`I/Ads     ( 2825): Ad failed to load : 3`

**Comment by EngDjango** [comment]
bug fixed by fixing some android app singing configurations by following correct singing procedure

**Comment by emran92** [comment]
> bug fixed by fixing some android app singing configurations by following correct singing procedure

Hi. Can you please share the singing configurations ? I'm unable to show real ads on release build, debug build works and test ads works too. But not showing real ads on release build.

**Comment by EngDjango** [comment]
@emran92 i found the problem cause was the keystore in the app; 
real ads didn't show when using a recently created keystore (for me, this was the stuck);
also didn't show if i don't provide Sha1 of the keystore to firebase;
also didn't show if i use adblocker app in the client phone;
