### ISSUE TITLE
[firebase_admob] Glimpse of white screen when app resume from memory

### ISSUE THREAD

**Issue by designerSJ** [FirebaseExtended/flutterfire#2504]
I have implemented Firebase AdMob on my flutter app (Android only). Everything works fine. But when I resume the app from the memory, there is a glimpse of the white screen (splash screen) for some milliseconds (just like a glitch) before the app resumes.

Also, I am not talking about the case when the app is not there in memory and just restarts. I am talking about the case when the app is in memory and I resume it from memory. Because when I completely remove the ads from my app, everything works fine.

In the console, whenever I resume the app from memory, it says:
`W/Ads     (21823): #004 The webview is destroyed. Ignoring action.`

I don't know whether this has something to do with the issue stated above.

**Expected behavior**
When I resume the app back from the memory, it should not give a glimpse of white screen and rather straight away goes to the app.

**Flutter doctor**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.1 18B75, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 9.2)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)
```

**Comment by TahaTesser** [comment]
Hi @designerSJ 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
