### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method RemoteConfig#instance on channel plugins.flutter.io/firebase_remote_config)

### ISSUE THREAD

**Issue by VisheshAtWork** [FirebaseExtended/flutterfire#2505]
I initialised the Remote-Config in the following way and got the MissingPluginException. I have added and imported the dependencies as well. I am on flutter stable and flutter doctor has no issues as well.

`RemoteConfig remoteConfig;

  Future setupRemoteConfig() async {
    remoteConfig.setConfigSettings(RemoteConfigSettings(debugMode: true));
    remoteConfig.setDefaults(<String, dynamic>{
      'Welcome': 'default welcome',
    });
  }

  Future fetchRemoteConfig() async {
    remoteConfig = await RemoteConfig.instance;
      await setupRemoteConfig();`

**Comment by TahaTesser** [comment]
Hi @VisheshAtWork 
You might be missing `google-services.json` file from your app folder 
Please make you've done the steps from [this](https://pub.dev/packages/firebase_remote_config#android-integration)
If problem persist after this,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VisheshAtWork** [comment]
Hi @TahaTesser, I have the json in place and have also configured as in the steps given. Here is my flutter doctor -v : 
 flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at F:\Development\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\vishe_3yijymz\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\vishe_3yijymz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • Redmi Note 5 Pro • 4e72c237 • android-arm64 • Android 9 (API 28)

• No issues found!

This is the part of code I inserted before getting this error.Even the error in the console doesn't have much info other than Invalid Arguements().
This could be used to reproduce the error.

`Future setupRemoteConfig() async {
    remoteConfig.setConfigSettings(RemoteConfigSettings(debugMode: true));
    remoteConfig.setDefaults(<String, dynamic>{
'welcome': 'Default Welcome'
}
Future fetchRemoteConfig() async {
    remoteConfig = await RemoteConfig.instance;
    await setupRemoteConfig();
    try {
      await remoteConfig.fetch(expiration: Duration(seconds: 0));
      await remoteConfig.activateFetched();
    } on FetchThrottledException catch (exception) {
      print(exception);
    } catch (exception) {
      print(
          'Unable to fetch remote config. Cached or default values will be used');
    }
  }
@override
  void initState() {
  super.initState();
  fetchRemoteConfig();
  }
Widget build(Buildcontext context){
return Text('Hey, ${remoteConfig.getString('welcome')}');
}
`

**Comment by TahaTesser** [comment]
Hi @VisheshAtWork 
Can you please post your `MainActviity` class and `manifest.xml`?
Thank you

**Comment by VisheshAtWork** [comment]
Dont know how but that was solved. So posting wont help i guess. This can be closed now.

**Comment by yourshinsuke** [comment]
@VisheshAtWork  can you remember?
