### ISSUE TITLE
firebase_ml_vision 0.9.3+8 not able to detect barcode

### ISSUE THREAD

**Issue by kw2019ltd** [FirebaseExtended/flutterfire#2506]
barcodeDetector.detectInImage(visionImage)  is not able to parse below image and get the qrcode details

using: firebase_ml_vision 0.9.3+8 

![qr-code__2_](https://user-images.githubusercontent.com/47334522/81186419-6e46a000-8fbb-11ea-922a-812ee4d56042.png)

you can repreduce it with attached image

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
Please use the [example](https://pub.dev/packages/firebase_ml_vision#-example-tab-)  and make sue you've proper done the [setup](https://pub.dev/packages/firebase_ml_vision#-readme-tab-)
can you please provide your `flutter doctor -v` and `flutter run --verbose` while scanning?
Thank you

**Comment by kw2019ltd** [comment]
yes i tried it, the issue with this QR it has no border so barcodeDetector.detectInImage(visionImage)
not able to detect the barcode.

**you can save the image and try it you will face same issue.**

[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-IL)
    • Flutter version 1.17.0 at C:\Tools\flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\kotai\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
I tried to to reproduce this issue using official. [example](https://pub.dev/packages/firebase_ml_vision) and it has no issue 

![flutter_01](https://user-images.githubusercontent.com/48603081/81417708-35e4c480-9169-11ea-8aef-99fa355f73ea.png)

Please clone this [repo](https://github.com/FirebaseExtended/flutterfire) and add your firebase configuration 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-13.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-13.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 8fbfe1cfbf (35 hours ago), 2020-05-06 17:36:01 -0700
    • Engine revision d6aa099de7
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
I tried to to reproduce this issue using official. [example](https://pub.dev/packages/firebase_ml_vision) and it has no issue 

![flutter_03](https://user-images.githubusercontent.com/48603081/81418470-5b260280-916a-11ea-8423-28b025fb9629.png)


Please clone this [repo](https://github.com/FirebaseExtended/flutterfire) and add your firebase configuration 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-13.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-13.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 8fbfe1cfbf (35 hours ago), 2020-05-06 17:36:01 -0700
    • Engine revision d6aa099de7
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by kw2019ltd** [comment]
Hi in order to reproduce the issue you need to load the image using image
picker and you will face the issue.

Attached image pls load it using image picker and call barcode detector you
will get no result.

**Comment by kw2019ltd** [comment]
salam any any update of this issue?

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem, official example works fine 
Thank you

**Comment by kw2019ltd** [comment]
hi as i said you need to download the image i sent as is, dont take screen shot and try to scan it.

the issue that image has no border.

in order to repreduce the issue do the following:
1 - downalod the image as is
2- try to scan it using image picker and then call 
     barcodeDetector.detectInImage(visionImage)

expected: barCode return
actual: empty result

minimal code:
final _barcodeDetector = FirebaseVision.instance.barcodeDetector();

  Future<void> _getImage() async {
    try {
      var image = await ImagePicker.pickImage(
        source: ImageSource.gallery,
      );

      if (image != null) {
        var barCodes =
            await getBarcodeFromFile(image, _barcodeDetector);
        var barcodeDto = await _parseBarCode(barCodes, 'scan_image');
        await _showCodeWidget(barcodeDto);
      }
    } catch (e, s) {
     
    }
  }

  Future<List<Barcode>> getBarcodeFromFile(
      File imageFile, BarcodeDetector barcodeDetector) async {
    final visionImage = FirebaseVisionImage.fromFile(imageFile);
    if (visionImage != null) {
      return await barcodeDetector.detectInImage(visionImage);
    }
    return null;
  }

**Comment by TahaTesser** [comment]
Hi @viplavrawal 
Using official [example](https://pub.dev/packages/firebase_ml_vision#-example-tab-)

Pick your qr code and then please select barcode scanner from the menu 

![flutter_01](https://user-images.githubusercontent.com/48603081/82559910-092fa480-9b8e-11ea-98cc-97db0474ac63.png)

Here using you qr code, can see green highlight that detected qr code 
![flutter_02](https://user-images.githubusercontent.com/48603081/82559921-0b91fe80-9b8e-11ea-80bc-28527530ec72.png)



<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (10 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (7 available)
    • SM M305F                  • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E            • ios
      • iOS 13.5
    • iPhone 11                 • F067D2F5-5386-4EBE-8600-326B40C64462 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS                     • macOS                                •
      darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server                           •
      web-javascript • Flutter Tools
    • Chrome                    • chrome                               •
      web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details> 

Thank you

**Comment by kw2019ltd** [comment]
hi i tried the same for me its not working on my device one plus 8T

attached screen shot where it was not able to detect QR code
![Screenshot_20200524-152234](https://user-images.githubusercontent.com/47334522/82757070-c583a780-9de6-11ea-8c0f-9135aa84bae5.jpg)

record where it was not able to detect qrcode
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47334522/82757118-04196200-9de7-11ea-9c10-e2e41ecdda82.gif)

also i added print to check if barcode detect it was not 

![image](https://user-images.githubusercontent.com/47334522/82757184-6c684380-9de7-11ea-9b68-9b7a18a6b4bb.png)

I/native  ( 9172): barcode_detector_client.cc:238 Not using NNAPI
**I/flutter ( 9172): 0**


pls check the issue.
