### ISSUE TITLE
FirebaseCoreDiagnostics - use of undeclared identifier 'PB_LTYPE_BOOL'

### ISSUE THREAD

**Issue by JoshRice1** [FirebaseExtended/flutterfire#2507]
When building in CodeMagic I am getting an error of "use of undeclared identifier 'PB_LTYPE_BOOL'"

```
/<projectPath>/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.c:42:5: error: use of undeclared identifier 'PB_LTYPE_BOOL'
    PB_FIELD( 25, BOOL    , OPTIONAL, STATIC  , OTHER, logs_proto_mobilesdk_ios_ICoreConfiguration, use_default_app, min_supported_ios_version, 0),
    ^
In module 'nanopb' imported from /<projectPath>/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.h:22:
/Users/builder/clone/reconxy_flutter/ios/Pods/nanopb/pb.h:534:9: note: expanded from macro 'PB_FIELD'
        PB_LTYPE_MAP_ ## type, ptr)
        ^
<scratch space>:71:1: note: expanded from here
PB_LTYPE_MAP_BOOL
^
In module 'nanopb' imported from /<projectPath>/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.h:22:
/<projectPath>/ios/Pods/nanopb/pb.h:495:41: note: expanded from macro 'PB_LTYPE_MAP_BOOL'
#define PB_LTYPE_MAP_BOOL               PB_LTYPE_BOOL
                                            ^
```

**Comment by JoshRice1** [comment]
Sorry don't have much to go on as I can't reproduce it locally.  But I did find a note in the nanopb migration about needing to recompile.  Thanks for any and all help and sorry I can't provide a more process description and repro steps.
https://github.com/nanopb/nanopb/blob/master/docs/migration.rst

**Comment by EHBradford** [comment]
I am having exactly this same issue.

**Comment by JoshRice1** [comment]
So deleting everything in the following three directories cleaned up the issue for me:
$FLUTTER_ROOT/.pub-cache	
$HOME/.gradle/caches	$HOME/.gradle
$HOME/Library/Caches/CocoaPods

gradle probably wasn't needed in relation to this but I cleaned it all up anyway.

**Comment by oguzhangedik** [comment]
In my case, that error was gone just with clean and build.

**Comment by jhbiggs** [comment]
Yes, a "Clean Build Folder" did the trick.  I was puzzled at the strange error.  Glad it just needed a clean.

**Comment by kesha-antonov** [comment]
Clean + ```rm -rf ~/Library/Developer/Xcode/DerivedData``` helped

**Comment by 9to5iOS** [comment]
Just do
pod deintegrate
pod update

**Comment by usman-whizpool** [comment]
In my case, cleaning both derived data and build folder worked

**Comment by everuribe** [comment]
Just a Project Clean and rebuild did the trick
