### ISSUE TITLE
[Firebase Storage] getReferenceFromUrl returns wrong storage reference path

### ISSUE THREAD

**Issue by ugurcany** [FirebaseExtended/flutterfire#2518]
I have a file which resides in the following path in Firebase storage: **/users/{userid}/avatar.jpg**

I'm putting this file in storage, then retrieve its download URL via `getDownloadURL` method. Afterwards, I'm saving this download URL in Firestore.

Whenever I want to delete this file from storage, I'm using this download URL already saved in Firestore to retrieve the storage reference of this file. So, I'm using this method:

```
StorageReference avatarRef =
        await _firebaseStorage.getReferenceFromUrl(user.avatarUrl);
```

When I debug this `avatarRef` object, I see that its `path` field has the value: **/users/{userid}/{userid}/avatar.jpg**

As you can see the path involves duplicate `{userid}`s. Therefore `avatarRef.delete()` operation fails due to this wrong reference path.

I tested this on an Android device. And here is my `flutter doctor` output:
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @ugurcany 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ugurcany** [comment]
Hi @TahaTesser 

The following is the code snippet:

```
//DEFINE AVATAR PATH ON STORAGE
1.    StorageReference avatarRef =
        await FirebaseStorage.instance.getReferenceFromUrl(aValidDownloadUrl);

//DELETE AVATAR IMAGE FILE
2.    await avatarRef.delete();
```

If you put debug point on the line 2 and run the code, you will see the `path` parameter inside `avatarRef` object has a wrong value.

**Comment by ugurcany** [comment]
It turned out that it's not related to storage sdk itself, thus closing.
