### ISSUE TITLE
[firebase_admob] Admob Won't Compile For iOS Simulator

### ISSUE THREAD

**Issue by caseta** [FirebaseExtended/flutterfire#2520]
**Describe the bug**
iOS won't compile when using newest version of admob plugin

**To Reproduce**
1. Use `firebase_admob: ^0.9.3+2`
2. run `flutter run` on iOS simulator
3. Observe error:

```
    In file included from /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:6:
    /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:4: error: expected a type
    - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
       ^
    /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:45: error: expected a type
    - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
                                                ^
    2 errors generated.
```

**Additional context**
I'm only attempting to use Banner Ads. Do I need to do the special additional setup required for Native ads? (Implementing this protocol `FLTNativeAdFactory` as it says to do [here](https://pub.dev/packages/firebase_admob#ios) ?)

If so, can we get a very specific example in Swift on how to do this? I have tried and failed.

**Flutter doctor**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/administrator/Library/Flutter/flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/administrator/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone 8 • 5C94EF7F-01E8-4102-84BC-94F1BBD2EF64 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @caseta 
Please setup firebase for your project in [iOS](https://pub.dev/packages/firebase_admob#ios)  which includes adding `GoogleService-info.plist` and and Firebaseconfig in AppDelegate
and also [ AdMob app ID in your Info.plist](https://pub.dev/packages/firebase_admob#ios)
```
dict>
	<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-################~##########</string>
</dict>
```
Run official [example](https://pub.dev/packages/firebase_admob#-example-tab-)  

Thank you

**Comment by caseta** [comment]
I am currently using plugin version `0.5.7` successfully in my production app.

- `GADApplicationIdentifier` was added to my `Info.plist`
- `GoogleService-info.plist` is present in my app (currently using this plugin in production)
- `Firebaseconfig in AppDelegate` <-- not sure what you mean by this honestly

Ran the official example and got the same result: 

```
Launching lib/main.dart on iPhone 8 in debug mode...
Running pod install...                                              1.9s
Running Xcode build...                                                  
Xcode build done.                                            2.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:6:
    /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:4: error: expected a type
    - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
       ^
    /Users/administrator/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTFirebaseAdMobPlugin.h:28:45: error: expected a type
    - (GADUnifiedNativeAdView *)createNativeAd:(GADUnifiedNativeAd *)nativeAd
                                                ^
    2 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone 8.


```

**Comment by caseta** [comment]
I think I solved my own problem -- but this might mean there is a bug related to what is happening. 

I noticed that my errors were referencing version `0.9.3+2` of the plugin when I was attempting to build a random, older version of the plugin (`0.9.1`). I then realized from [this answer here](https://stackoverflow.com/a/55399559), that I needed to

1. Comment out the plugin
2. Get packages
3. Comment it back in with the new version

I guess there is a bug with cleaning out the plugin `pub cache`? I did `flutter clean` _many_, _many_ times, so that was not cleaning it out.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
