### ISSUE TITLE
iOS Can't receive background remote notifications

### ISSUE THREAD

**Issue by avkojwer1** [FirebaseExtended/flutterfire#2522]
I following the guide 
- i have downloaded and added GoogleService-Info.plist
- i have turned on Push Notifications and Background Modes, and enable Background fetch and Remote notifications under Background Modes

then i am using the example code and complied  successfuly, run the app well.

i can receive the message from **onMessage** method when i open the app.
 **but if i switch the app to background, i can't  receive the message**.

help me......

using the version:
  
  firebase_messaging: ^6.0.13

**Comment by ialhashim** [comment]
Same here, it used to be working two days ago. Maybe its a server issue.

**Comment by ialhashim** [comment]
Okay I read elsewhere something about iOS version. I then tried updating to iOS 13.4.1 (iPhone 11) and just like that it is working. I am happy it is fixed but that is unfortunate not to be able to support more devices out of the box.

**Comment by knissophiliac** [comment]
@ialhashim did you followed only the guide on https://pub.dev/packages/firebase_messaging? and getting background notifications on iOS?

**Comment by ialhashim** [comment]
I believe so, I didn't do step 5 (the swizzling stuff). In case this might helps others experiment. This is my current setup. At my home page I define:
```
  @override
  void initState() {
    super.initState();

    /// Register Firebase Cloud Messaging (FCM)
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      firebaseMessaging.configure(
        // App is in the foreground
        onMessage: (Map<String, dynamic> message) async {
          pushNotificationRouter(context, message, (){ moveToPage(1); });
        },
        // App is in the background
        onResume: (Map<String, dynamic> message) async {
          pushNotificationRouter(context, message, (){ moveToPage(1); });
        },
        // App is completely terminated
        onLaunch: (Map<String, dynamic> message) async {
          pushNotificationRouter(context, message, (){ moveToPage(1); });
        },
        // Background messages
        onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler
      );
      
      await firebaseMessaging.requestNotificationPermissions(const IosNotificationSettings(sound: true, badge: true, alert: true, provisional: false));
      firebaseMessaging.onIosSettingsRegistered.listen((IosNotificationSettings settings) {});
      fcmToken = await firebaseMessaging.getToken();
    });
  }

// Then elsewhere...
void pushNotificationRouter(context, message, callback) async {  
  Map data = message['data'] ?? message; // iOS
  //..... do stuff with message data
}
```
My backend (a Firebase function in TypeScript) I do it like so:
```
        const payloadData = {
            title: 'Appointment Status',
            body: `Appointment status changed to ${statusData.name}`,
            click_action: 'FLUTTER_NOTIFICATION_CLICK',
            sound: 'default',
            badge: '1',
            screen: 'appointment',                
            appointmentID: newAppointment.appointmentID,
        };

        const payload: admin.messaging.MessagingPayload = {
            data: payloadData,
            notification: payloadData
        };

        //...
        fcm.sendToDevice(`${patient.fcmToken}`, payload).then(() => { return; }).catch(()=>console.log('error'));
```
I am not very sure about my approach but not it seem to be working when app is in foreground and background on both iOS and Android. I am using Flutter 1.17 stable.

**Comment by knissophiliac** [comment]
@ialhashim you are setting
`onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler`

if iOS it is null, so how do you get information of a notification when app is background?

**Comment by ialhashim** [comment]
I actually don't use onBackgroundMessage on either platforms. In the end the behavior seem to be that the notifications are queued until the app opens again. So a notification appears on the OS side, if you click on it the app will open up and the other functions will be called, i.e., `onResume` or `onLaunch`. That is good enough for my use case.

**Comment by knissophiliac** [comment]
@ialhashim hmm, if user clicks on one of the notifications, the app loses other notification datas. To solve that we can use onBackgroundMessage. But it is only for android...

**Comment by xfumihiro** [comment]
also hit with this issue and have noticed somehow the onMessage payload format changed:
from (around 10:00 this morning 5/12, and the background notification was working atm)
```json
{
  "aps": {
    "alert": {
      "title": [title],
      "body": [body],
    }
  }
}
```

to (around 1:00 afternoon 5/12)
```json
{
  "notification": {
      "title": [title],
      "body": [body],
  }
}
```

**Comment by Salakar** [comment]
Lets track this on #1041 so as to avoid duplication on the discussions - thanks!
