### ISSUE TITLE
[firebase_admob] Cannot close some rewarded ads on notch devices 

### ISSUE THREAD

**Issue by shunMB** [FirebaseExtended/flutterfire#2531]
**Describe the bug**
When viewing and closing rewarded ads, the time display and close button may overlap and prevent pressing the close button. This has been confirmed on devices such as iPhoneX.

below is the part of the screenshot:
<img width="365" alt="screenshot 2020-05-11 14 35 23" src="https://user-images.githubusercontent.com/41967502/81527221-ad4a6c00-9394-11ea-86c4-05ea34f6d758.png">

**To Reproduce**
On test ads couldn't confirm that.
As you know, not all ads apply in this case.

**firebase_admob version in pubspec.yaml**
```
firebase_admob: ^0.9.2+1
```

**Flutter doctor -v**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.1 19B88, locale ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.0)
[✓] Connected device (2 available)

• No issues found!
shunmanabe$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.1 19B88, locale ja-JP)
    • Flutter version 1.17.0 at /usr/local/bin/flutter
    • Framework revision e6b34c2b5c (8 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shunmanabe/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (2 available)            
    • iPhoneSE  • D0C26FC5-CBF1-4E38-BE18-F9FA11F8F573 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)
    • iPhone 11 • 4B5E0CE0-8D25-49CC-BEBA-0BDE35991977 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)
```

**Comment by nhjeon** [comment]
I have this problem too.
Anyone solve this?

**Comment by wonpyohong** [comment]
I have same problem
This needs quick fix.

**Comment by xz013** [comment]
Same problem... any update?

**Comment by Kenoshen** [comment]
Yikes, this is still an issue.  Any update?

**Comment by jangruenwaldt** [comment]
Can only say that using this:
`listener: (MobileAdEvent event) {
      if (event == MobileAdEvent.closed) {
        SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
      }
      if (event == MobileAdEvent.clicked) {
        SystemChrome.setEnabledSystemUIOverlays([]);
      }
},`
from https://github.com/FirebaseExtended/flutterfire/issues/3090
solved it for me

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
