### ISSUE TITLE
Don't crash when config is not found

### ISSUE THREAD

**Issue by matthew-carroll** [FirebaseExtended/flutterfire#2534]
I was setting up a Flutter project with Firebase. I inadvertently mis-configured the `GoogleService-Info.plist` file inclusion.

The result is that my app crashed immediately upon launch. Unfortunately, no logs made it back to Android Studio, where I was running the project. To debug this crash, which could have been anything, required opening the project in XCode, running the app through XCode, and then looking at the logs that did make it to the console in XCode. Eventually it became clear that I was missing the config file.

I think that crashing immediately when no config file is found is counterproductive. Instead, I would recommend logging an error to the console and then allowing execution to continue. Perhaps if a future command is executed, then a crash makes sense. However, to crash the app before a UI is even rendered - to crash the app so early that logs don't even make it back to Android Studio, this makes it more difficult, not less difficult, to find and solve the problem.

PS - I wasn't even invoking a Firebase API to cause this crash. I merely imported the relevant Firebase package.

**Comment by TahaTesser** [comment]
Just noticed this issue and i totally agree

**Comment by Salakar** [comment]
As far as I'm aware this was solved in the reworked plugins last year, thanks.
