### ISSUE TITLE
[firebase crashlytics] after the new flutter version has came up crashlytics is not working

### ISSUE THREAD

**Issue by jk-hub** [FirebaseExtended/flutterfire#2535]
Hope you all are Doing well 
**To Reproduce**
1. if we has put the crashlytics line on a api call when the response comes 200 or 201 or 400 or 500 
2. it should give us a report of success or   error on console of crashlytics 
3. but it goes to that line and executes it and then the app either crashed or goes in loading 
 
**Expected behavior**
expected that after the response has error or success that should be reported to crashlytics console 
but its not working as expected 
 
**Additional context**
after the flutter upgrade to 1.17.0 new stable version the crashlytics is not working when it comes to that line of crashlytics after the app crash of after that line app goes into loop

**Flutter doctor**
Run `flutter doctor` and paste the output below:
[image](https://user-images.githubusercontent.com/58223882/81643094-7d59a200-9442-11ea-867f-d2961b046180.png)

thank you 
expecting help as soon as possible

**Comment by TahaTesser** [comment]
Hi @jk-hub 
can you please provide your  `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
