### ISSUE TITLE
[firebase_storage] Object does not exist at location (but it does!)

### ISSUE THREAD

**Issue by atreeon** [FirebaseExtended/flutterfire#2537]
I'm getting an error when attempting to download a file from firebase storage.  The file locations seem to be identical.  I can access firebase database data in the same firebase project from the same flutter project too and I've got my permissions set to allow reads from anyone.  Any ideas please?

The error is
```
E/StorageException(27807): StorageException has occurred.
E/StorageException(27807): Object does not exist at location.
E/StorageException(27807):  Code: -13010 HttpResult: 404

```

Comparing the file I'm requesting to the one that is in storage (storage location field), they are identical
```
gs://XXXX.appspot.com/triggeraudio/trig_aud_100.zip
gs://XXXX.appspot.com/triggeraudio/trig_aud_100.zip
```

My permissions
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read;
    }
  }
}
```

The code that I run to try to download the file 
```
    var storageReference = FirebaseStorage().ref().child(gsPath);
    var file = File(savePath);
    await storageReference.writeToFile(file);

```
Flutter doctor
`Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)`

**Comment by TahaTesser** [comment]
Hi @atreeon 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by atreeon** [comment]
due to security issues I'd rather not post the flutter doctor response.  I have included a code sample above.

**Comment by Lexpeartha** [comment]
I had the same error, and after playing around with it, I realized that it happens only with "big" files. For example fetching image with around **200KB** works just fine, but when I try to do the same with mp3 that is almost **7MBs** (in my case I am just fetching metadata from reference) it shows this error, even tho file exists. I can provide more info about this, if needed.

**Comment by dipakp2726** [comment]
HI @atreeon 
Please use whole path in refrence at time of downloading url,
i am sure this will solve this issue,

i had gone through the same problem and i found i wa just giving file name without directory 

use this way 

`storage.ref('Directory/$filename').getDownloadURL();`

**Comment by russellwheatley** [comment]
> HI @atreeon
>Please use whole path in refrence at time of downloading url,
>i am sure this will solve this issue,
>
>i had gone through the same problem and i found i was just giving file name without directory
>
>use this way
>
>storage.ref('Directory/$filename').getDownloadURL(); 

Hey @atreeon, are you able to confirm the above solved your problem?

**Comment by atreeon** [comment]
@russellwheatley thanks, its been a while since I looked at this but I think it is solved and was a problem with the path

I think I used a relative path without the gs:// part

**Comment by russellwheatley** [comment]
Thanks for letting us know, @atreeon!
