### ISSUE TITLE
[firebase_messaging] Ways workaround data message on app terminated?

### ISSUE THREAD

**Issue by nerder** [FirebaseExtended/flutterfire#254]
What is the current workaround in order to receive custom data when the user click on a notification when the app is terminated?

Seems like on `Android` is not possible to receive a data message in the `onLaunch` (which is the ideal way)
On `IOS` i hadn't tried yet since i'm facing this issue first.

Any clue?

**Comment by urbanjagodic** [comment]
It works for me, I tested it on both platforms.

**Comment by kirstywilliams** [comment]
Hey @nerder, I'm closing this as stale and seems a question better suited to StackOverflow using tag [`Flutter`](https://stackoverflow.com/questions/tagged/flutter). If this remains an issue then please feel free to create a new issue with as much information as possible.
