### ISSUE TITLE
[firebase_auth] Crash while integrating Firebase Auth with Phone sign-in method

### ISSUE THREAD

**Issue by GyuriMajercsik** [FirebaseExtended/flutterfire#2542]
**Describe the bug**
The application crashed with below stacktrace. It's not reproducible all the time.

```
E/AndroidRuntime( 8371): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 8371): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$1.onCodeAutoRetrievalTimeOut(FirebaseAuthPlugin.java:280)
E/AndroidRuntime( 8371): 	at com.google.firebase.auth.api.internal.zzey.zza(com.google.firebase:firebase-auth@@19.2.0:2)
E/AndroidRuntime( 8371): 	at com.google.firebase.auth.api.internal.zzfa.run(com.google.firebase:firebase-auth@@19.2.0:4)
E/AndroidRuntime( 8371): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8371): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8371): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8371): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime( 8371): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8371): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime( 8371): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Expected behavior**
The application should not crash. 

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-RO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

**Comment by TahaTesser** [comment]
Hi @GyuriMajercsik 
Are you trying phone sign in method on iOS?
It needs extra steps, please follow [After authentication](https://pub.dev/packages/firebase_auth#after-authentication) and checkout  [Enable app verification](https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification) from same page of `firebase_auth` 

if the problem persist after setup,  can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by GyuriMajercsik** [comment]
It happened a couple of times and on Android as well. (as might be visible in the crash logs) 

Apparently, it happens randomly. 

In case the problem persists and I find some steps I will let you know. 

Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution
