### ISSUE TITLE
[firebase-messaging] android do not remove alert badge when user open app by click app not alert badge

### ISSUE THREAD

**Issue by whatamelon** [FirebaseExtended/flutterfire#2547]
same as title.

1. users device get alert badge.
2. user open app by click app not click alert badge.

In ios when user doing 2, alert badge is removed.
I just think this is ios handle.

but in android, user open app to click app, alert badge still remain.
how can I handle it?

Is there any option in library? or I handle it by native bridge code?

**Comment by gouthamkumar253** [comment]
Hi @whatamelon , I'm not able to get badge notifications in Android. However, it perfectly works in iOS. Can u tell me how you managed to show the alert badge in Android?

**Comment by TahaTesser** [comment]
Hi @whatamelon 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by whatamelon** [comment]
Hi @gouthamkumar253, I'm didn't do anything else for manage show alert badge. I just download plugin and doing like example. I think if my issue can't solve than make local notification to manage alert badge. I hope it won't happen.

Hi @TahaTesser, 
here is my flutter doctor -v 
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale ko-KR)
    • Flutter version 1.12.13+hotfix.9 at /Users/denny/flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/denny/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Denny의 iPhone • 00008030-001C71DC01F1802E • ios • iOS 13.4.1

• No issues found!

And, flutter run --verbose is too long to copy them. So, I can't provide it for here. sorry for that.
While doing flutter run --verbose, there are no error just running that I expecting.

Additionally, for more clearly question, I attach example video link. Please watch it.

https://drive.google.com/open?id=1n-4zFRA8Y52VvjyWg28l-YOM6IXGIQAo


As the video, I get alert. But, I just open app not by alert. I just open app by click app icon.
In that case, ios remove alert badge itself, but android has remain alert badge.
I want to know can I handle alert in this library version.
Also, Do you guys have any plans to change it to handle it in library, from now on?

**Comment by TahaTesser** [comment]
Hi @whatamelon 
Can you please try another device or emulator? if see this behaviour repeats? 
Thank you

**Comment by whatamelon** [comment]
Hi @TahaTesser 
Upgrade library version 6.0.13 -> 6.0.15.
And changing test device LGV300 -> Galaxy7
But it still happen.

**Comment by whatamelon** [comment]
Close this issue for solve problem with flutter_app_badger plugin.
