### ISSUE TITLE
MissingPluginException for 'FcmDartService#start' on iOS

### ISSUE THREAD

**Issue by tkeithblack** [FirebaseExtended/flutterfire#2549]
Defining 'onBackgroundMessage' in firebaseMessaging.configure(...) causes a **MissingPluginException** under iOS because there is no MethodChannel definition for "FcmDartService#start" in the iOS implementation.

```
firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
      },
      onBackgroundMessage: backgroundMessageHandler,  // <- causes exception on iOS.
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
      },
    );

```
Version: firebase_messaging 6.0.15

**Comment by philipgiuliani** [comment]
iOS is currently not supported. You have to write it like this:
```
import 'dart:io';
....
onBackgroundMessage: Platform.isAndroid ? backgroundMessageHandler : null,
```

**Comment by iapicca** [comment]
Hi @tkeithblack 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/116) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by tkeithblack** [comment]
> Hi @tkeithblack
> I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/116) addressing the case you described.
> Please follow up on that issue,
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

Thank you @iapicca. Probably should update the plugin docs showing this is not supported for iOS.

Keith
