### ISSUE TITLE
[firebase_admob] Upgrade SDK version from 18.1.1 to 19.1.0

### ISSUE THREAD

**Issue by edscodeblenders** [FirebaseExtended/flutterfire#2550]
The firebase_admob package version 0.9.3+2 uses SDK 18.1.1 on Android, which was released almost a year ago. I can see the following line in the build.gradle file:
    dependencies {
        api 'com.google.firebase:firebase-ads:18.1.1'
    }

But the Google Mobile Ads SDK is already in version 19.1.0:
https://developers.google.com/admob/android/rel-notes

Can you estimate when this version will become available? Is it safe to manually edit the line from "flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\build.gradle" to use the latest version of the SDK?

We're using Open Bidding Beta, and we need to use the latest version to avoid adding extra parameters to the AndroidManifest.xml.

Thanks.

**Comment by edscodeblenders** [comment]
Adding on top of this, when we try to add the adapters of third party networks like AppLovin or AdColony via gradle, which is required to add them to the bidding process, we get an error due to incompatible dependencies:
`Could not determine the dependencies of task ':app:preReleaseBuild'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.0.0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-measurement-api:17.0.0 -> com.google.android.gms:play-services-measurement-sdk-api@[17.0.0], but play-services-measurement-sdk-api version was 17.1.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the artifact with the issue.
  -- Project 'app' depends on project 'firebase_admob' which depends onto com.google.firebase:firebase-ads@18.1.1
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-sdk@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-ads@19.1.0
  -- Project 'app' depends onto com.google.android.gms:play-services-gass@19.1.0
  -- Project 'app' depends onto com.google.firebase:firebase-ads@18.1.1
  -- Project 'app' depends onto com.google.ads.mediation:adcolony@4.1.4.1
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.0.0
  -- Project 'app' depends on project 'firebase_analytics' which depends onto com.google.firebase:firebase-analytics@16.5.0
  -- Project 'app' depends onto com.google.ads.mediation:applovin@9.12.5.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-sdk-api@17.1.0
  -- Project 'app' depends onto com.google.android.gms:play-services-ads-lite@19.1.0`

Their adapters require the lastest version of the Google Mobile Ads SDK. Do you have any recommendation for this case?

**Comment by ThrowJojo** [comment]
I can attest to what is written above, trying to add the latest mediation adapters(FAN etc.) to an Android project is not pretty. If a newer version of the AdMob SDK was used it would make everything go a lot smoother.

**Comment by spremathilaka** [comment]
I'm  [https://stackoverflow.com/questions/62325206/flutter-app-integrating-adcolony-with-mediation](facing ) this issue now, can someone help me which version I should add to work adcolony?

**Comment by ThrowJojo** [comment]
@spremathilaka There's probably a way you could hack this by using resolutionStrategy.force [in your build.gradle](https://stackoverflow.com/questions/53028495/gradle-gives-compatibility-error-when-adding-firebase) but I would suggest against it. I did it in a React Native project a couple of years ago and it became really annoying to maintain - not to mention this kind of solution won't help with the iOS side.

I recently added mediation to a Flutter project this week and this is what I did:
- Removed the firebase_admob library from my pubspec.yaml
- Added the native iOS dependency to my Podfile
- Added native(Swift) calls to load/show ads and the relevant MethodChannel calls in Dart
- Added the mediation adapters to my Podfile

You could do the same on Android above you'd just add the dependencies to your build.gradle file instead. This obviously won't help with banners either only interstitials.

I would rather just use `firebase_admob` than do the above but the version of AdMob it uses is too outdated and it causes all sorts of conflict issues with the latest mediation adapters.

**Comment by alectogeek** [comment]
any updates here?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
