### ISSUE TITLE
[firebase_messaging] Fatal: failed to find callback

### ISSUE THREAD

**Issue by YeomDongUk** [FirebaseExtended/flutterfire#2552]
onLaunch, onResume are not working after update flutter 1.17.1 stable.
when tap notification, show error.
Fatal: failed to find callback.

**Comment by brasizza** [comment]
Same error here!

**Comment by iapicca** [comment]
Hi @YeomDongUk 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by Shiba-Kar** [comment]
same here

**Comment by YeomDongUk** [comment]
![스크린샷 2020-05-25 오후 2 58 28](https://user-images.githubusercontent.com/40842475/82782810-36cf6300-9e98-11ea-9432-641aae7b0a18.png)
it is result of flutter doctor -v.
![스크린샷 2020-05-25 오후 2 59 50](https://user-images.githubusercontent.com/40842475/82782930-65e5d480-9e98-11ea-9e5a-4dd2f7ef2dff.png)

**Comment by codeeuser** [comment]
I have same issue on Android platform, but no issue on iOS platform. The push notification does not trigger the onMessage for Android platform although same code for both platform.

**Comment by iapicca** [comment]
Hi @YeomDongUk 
thank you for your doctor 
could you please provide the remaining info listed [above](https://github.com/FirebaseExtended/flutterfire/issues/2552#issuecomment-629193317)
Please refrain from posting pictures if not necessary.
Thank you

**Comment by YeomDongUk** [comment]
![스크린샷 2020-05-29 오후 5 16 12](https://user-images.githubusercontent.com/40842475/83237587-1a9d3000-a1d0-11ea-9ee1-937f81f2dff0.png)
it is my pubspec.yaml

**Comment by iapicca** [comment]
Hi @YeomDongUk 
could you please provide 
a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by YeomDongUk** [comment]
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  AppConfig.init();
  FirebaseMessage.init();
  await LocalNotification.init();
  Analytics.init();
  SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle.dark.copyWith(
      statusBarColor: Colors.black,
      statusBarIconBrightness: Brightness.light,
      statusBarBrightness: Brightness.light,
    ),
  );
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runZoned(() => runApp(MyApp()), onError: (error, stackTrace) async {
    Logger().e(error.toString());
    await FlutterCrashlytics()
        .reportCrash(error, stackTrace, forceCrash: false);
  });
}
class FirebaseMessage {
 static void init() {
    if (instance == null) {
      _instance = FirebaseMessage();
      if (instance._firebaseMessaging == null) {
        instance._firebaseMessaging = FirebaseMessaging();
        instance._firebaseCloudMessagingListen();
      }
    }
  }

  void configure(String userId) {
    try {
      instance.firebaseMessaging.configure(
          onMessage: (Map<String, dynamic> fcm) async {
        Logger().i("onMessage: $fcm");
        Map<String, dynamic> data = Map<String, dynamic>.from(fcm);
        if (fcm['data'] != null) data = Map<String, dynamic>.from(fcm['data']);
        switcher(
          clickAction: data["click_action"],
          callback: () =>
              LocalNotification.instance.onFeedback(fcm: data, userId: userId),
        );
      }, onLaunch: (Map<String, dynamic> fcm) async {
        Logger().i("onLaunch: $fcm");
        Map<String, dynamic> data = Map<String, dynamic>.from(fcm);
        if (fcm['data'] != null) data = Map<String, dynamic>.from(fcm['data']);
        switcher(
          clickAction: data["click_action"],
          callback: () => goFeedbackPage(
            lectureId: data['lectureId'],
            userId: userId,
          ),
        );
      }, onResume: (Map<String, dynamic> fcm) async {
        Logger().i("onResume: $fcm");
        Map<String, dynamic> data = Map<String, dynamic>.from(fcm);
        if (fcm['data'] != null) data = Map<String, dynamic>.from(fcm['data']);
        switcher(
          clickAction: data["click_action"],
          callback: () => goFeedbackPage(
            lectureId: data['lectureId'],
            userId: userId,
          ),
        );
      });
    } catch (error) {
      Logger().e(error);
      // throw Exception(error);
    }
  }
}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    FirebaseMessage.instance.configure(user.authId);
    return ....;
}
}
I can receive onMessage but can't not receive onLaunch and onResume. This happens only on Android.

**Comment by avinashyalgonde** [comment]
Hi there,

Is this issue resolved. I am also facing same issue on Android. onLaunch and onResume are not getting called. Can anyone help me here?
