### ISSUE TITLE
Unable to receive background messages (onLaunch/onResume) on iOS

### ISSUE THREAD

**Issue by angelocapone** [FirebaseExtended/flutterfire#2553]
**Describe the bug**
On iOS I can only get foreground messages. I’m unable to receive background messages (onLaunch/onResume)
On Android all works fine; I can received both foreground and background messages.
I have followed exactly all the steps as described in Readme
I've created a fresh 1.71.1 project with firebase_messaging 6.0.15

My environment:
iPhone 11 iOS 13.4.1
Pixel 3a Android 10
Fresh flutter project version 1.71.1
firebase_messaging 6.0.15

**Comment by iapicca** [comment]
Hi @angelocapone 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2552) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
