### ISSUE TITLE
Module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by Mike333333** [FirebaseExtended/flutterfire#2562]
Getting this error. when running Product archive in Xcode. Please help!!! Strugging with this for 3 weeks now.

**Comment by TahaTesser** [comment]
Hi @Mike333333 
You might need to execute `pod install` from root of your `ios` folder from your project
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by bensir4u** [comment]
@Mike333333 @TahaTesser 
Same trouble here... 
tried flutter clean, remove pod, install again 
& no luck...
