### ISSUE TITLE
Unhandled Exception: PlatformException(barcodeDetectorError, Waiting for the barcode detection model to be downloaded. Please wait., null)

### ISSUE THREAD

**Issue by EvnLi** [FirebaseExtended/flutterfire#2568]

**Comment by TahaTesser** [comment]
Hi @EvnLi 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
