### ISSUE TITLE
[firebase_auth] FirebaseUser.verifyBeforeUpdateEmail missing

### ISSUE THREAD

**Issue by dumbasPL** [FirebaseExtended/flutterfire#2577]
Problem:
FirebaseUser.[verifyBeforeUpdateEmail](https://firebase.google.com/docs/reference/js/firebase.User#verifybeforeupdateemail) is missing

Solution:
Implement verifyBeforeUpdateEmail

**Comment by Stinox22** [comment]
Maybe try this.
https://github.com/flutter/flutter/issues/56548#issuecomment-625239992

**Comment by prakharb10** [comment]
Hi
I believe that the latest version of firebase_auth resolves this issue. [Changelog](https://pub.dev/packages/firebase_auth/changelog#user)
