### ISSUE TITLE
[firebase_messaging] Visually broken app after background notification process

### ISSUE THREAD

**Issue by furkansarihan** [FirebaseExtended/flutterfire#2581]
**Describe the bug**
App launches visually broken(watch behavior in action [video1](https://streamable.com/bpjcwl) [video2](https://streamable.com/z02jks)) after background notification process while app is terminated.
-In background flutter_local_notification creates notification but this issue is not related to it because even if onBackgroundMessage callback do nothing issue stays same. 
-Debug mode is fine, issue only occurs in release and profile mode.

I disabled all nullable operations but it can still be related to isolated background dart execution I could not trace the issue perfectly.

But even app is visually broken, it works logically firestore connections and operations works fine, in [video2](https://streamable.com/z02jks).

**To Reproduce**
1. Configure Firebase with onBackgroundMessage callback
2. App recieved an notification
3. Visually broken app can be launched with notification or app icon.

AndroidManifest.xml
```
<application
        android:name=".Application"
        android:label="Monotony"
        android:icon="@mipmap/launcher_icon">
...
```
Application.java
```
package com.appmonotony.monotony;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```
App level build.gradle, firebase_messaging:20.1.7
```
dependencies {
    implementation 'androidx.fragment:fragment:1.0.0'
    implementation 'android.arch.lifecycle:common-java8:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.firebase:firebase-messaging:20.1.7'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
Top-Level _myBackgroundMessageHandler
```
Future<dynamic> _myBackgroundMessageHandler(Map<String, dynamic> message) {
  ... 
}
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/me/flutter
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/me/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • SM G950F • ce0517150d08e8f30d • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

1. Verbose: Flutter app launch and revieved message
[flutter run --verbose](https://pastebin.pl/view/a9009e28)

**Comment by bretie** [comment]
I’m very curious what your Application.java or kotlin file looks like. 

Also sharing your AndroidManifest.xml application name attribute.

**Comment by furkansarihan** [comment]
@bretie done. Are you facing with exact same issue? I also tried name attribute with package name.

**Comment by TahaTesser** [comment]
Hi @furkansarihan 
Can you please this issue using official example with `_myBackgroundMessageHandler` added?
Can you also please another video or emulator?
Thank you

**Comment by furkansarihan** [comment]
@TahaTesser I added [flutter run --verbose](https://pastebin.pl/view/a9009e28).  But app is working fine after this verbose even it recieved data messages and processed them before and while flutter run operation. 

And I am sorry but I can not figure out how to add ```_myBackgroundMessageHandler``` to official example because lack of Native Android experience. Official example contains different Flutter implementations in MainActivity.java.

**Comment by bretie** [comment]
Never mind you're using Java not Kotlin. Seems to be major issues with both.

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
