### ISSUE TITLE
[firebase_storage] ref.writeToFile returns a future and doesn't report progress

### ISSUE THREAD

**Issue by iscriptology** [FirebaseExtended/flutterfire#2584]
**Is your feature request related to a problem? Please describe.**
On native, we have a way to track progress of a download, but flutterfire doesn't expost the progress stream.

**Describe the solution you'd like**
As described in the flutter fire source code: `/// TODO: Move into own file and build out progress functionality`

**Additional context**

**Comment by TahaTesser** [comment]
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/420

**Comment by awazgyawali** [comment]
https://github.com/FirebaseExtended/flutterfire/pull/2884
