### ISSUE TITLE
[Google Dynamic Links for Firebase] Always redirects to the app store on iOS, on Android works fine

### ISSUE THREAD

**Issue by bulenthacioglu** [FirebaseExtended/flutterfire#2585]
**Describe the bug**
After clicking of the short link, app is not opened but rather the app store (in both cases that the app is installed or not)

**To Reproduce**
1. Generate a short link as following:

```
body = {
"dynamicLinkInfo": {
"domainUriPrefix": "https://petleoapp.page.link",
"link": link,
"androidInfo": {
"androidPackageName": app_bundle_id,
"androidMinPackageVersionCode": "100"
},
"iosInfo": {
"iosBundleId": app_bundle_id,
"iosAppStoreId": app_store_id
},

},
"suffix": {
"option": "UNGUESSABLE"
},
}
session = requests.session()
response = session.post(
url="https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=firebase_key",
json=body)
data = response.json()
```

2. Set up the required things on iOS according to the following video. (Adding associated domains with: applinks:link.petleo.app.page.link and adding a URL type in Info tab with identifier: bundleId and URL scheme net.petleo.app(bundle id of my app))

https://www.youtube.com/watch?v=KLBjAg6HvG0

3. Check the apple-app-site-association of the firebase link and make sure they include your team id and bundle id

https://petleoapp.page.link/apple-app-site-association
https://petleoapp.page.link/well-known/apple-app-site-association

4. Press on the link and get navigated to the store rather than your app.

**Expected behavior**
Getting redirected to the app

**Additional context**
When the link is created WITHOUT `iosAppStoreId` parameter, pressing on the link opens the app. But when the app is not installed, it doesn't redirect to app store. Debug view of the firebase link is:

<img width="393" alt="Screen Shot 2020-05-19 at 16 31 14 (1)" src="https://user-images.githubusercontent.com/11859322/82339819-c2f00f00-99ee-11ea-8061-59dcfbfa01e8.png">

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale en-DE)
    • Flutter version 1.17.1 at /Users/buelenthacioglu/sdk/flutter
    • Framework revision f7a6a7906b (7 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/buelenthacioglu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] Connected device (1 available)
    • Bülent’s iPhone • 8418dbf9850aaef7c09c6c9760fbc1f02b5a74f8 • ios • iOS 13.3.1

! Doctor found issues in 2 categories.

```

**Comment by dheerajsarwaiya** [comment]
same issue

**Comment by bulenthacioglu** [comment]
Any news on this issue?

**Comment by LucasTejero** [comment]
i already made it work for another app but im currently adding dynamic links to another app and even i follow the exact steps it didnt work

**Comment by softronaut** [comment]
Having same issue. It was working on Simulator, also Android side is working perfectly but my app just released and dynamic links does not work. I followed the steps exactly. Today I checked again all setup, no mistake, everything is correct.

**Comment by softronaut** [comment]
Any progress? This is a breaking problem, I use custom domain and I controlled every step. Android is working, apple-app-site-association link is working but dynamic links forwards to App Store all the time. Please do something because this is pretty production critical.
Or tell us should we migrate to `unilinks` or not.

**Comment by fish-like-mammal** [comment]
Try to delete your ios files of the flutter project and rebuild them with `flutter create .`

**Comment by softronaut** [comment]
> Try to delete your ios files of the flutter project and rebuild them with `flutter create .`

Projects are big and there are many native side customizations, extensions etc... So it is very cumbersome for me to delete ios folder and recreated it. Instead I have compared the my ios folder with a plain new Flutter projects ios folder, there are very minor differences. I applied that changes and will see is it work or not with next publish.

**Comment by whatamelon** [comment]
Is this issue have any progress?

**Comment by JoeAndrei** [comment]
I am facing same issue. Is there solution?

**Comment by softronaut** [comment]
> Try to delete your ios files of the flutter project and rebuild them with `flutter create .`

Forgot to comeback, I didn't recreate the ios folder but I checked the all differences and applied them onebyone, didn't work...

**Comment by Bear27kuma** [comment]
You guys still have same problem??
I was facing same issue, but I solve it.
I found this article!!
https://stackoverflow.com/questions/63500747/universallink-stop-working-on-ios-14-devices/63939770#63939770

**Comment by softronaut** [comment]
> You guys still have same problem??
> I was facing same issue, but I solve it.
> I found this article!!
> https://stackoverflow.com/questions/63500747/universallink-stop-working-on-ios-14-devices/63939770#63939770

It looks related to development environment, are you sure it affects app in production?

**Comment by russellwheatley** [comment]
I'm pretty sure this is a problem with configuration. There are many moving pieces to dynamic links iOS setup. Here is [documentation](https://rnfb-docs.netlify.app/dynamic-links/usage#ios-setup) for RNFB dynamic links setup that is exactly the same as flutter iOS setup and is based off this [YouTube firecast video](youtube.com/watch?v=KLBjAg6HvG0) on dynamic links for iOS.

**Comment by arjunkeshav** [comment]
@russellwheatley  I have the same issue. I just followed all the steps that provided but it ended up with only redirect to appstore. could you please help me where maybe the configuration issue occurs?

**Comment by arjunkeshav** [comment]
> I'm pretty sure this is a problem with configuration. There are many moving pieces to dynamic links iOS setup. Here is [documentation](https://rnfb-docs.netlify.app/dynamic-links/usage#ios-setup) for RNFB dynamic links setup that is exactly the same as flutter iOS setup and is based off this [YouTube firecast video](youtube.com/watch?v=KLBjAg6HvG0) on dynamic links for iOS.

@russellwheatley I have the same issue. I just followed all the steps that provided but it ended up with only redirect to appstore. could you please help me where maybe the configuration issue occurs?
