### ISSUE TITLE
[firebase_database] Cannot restore connection to Firebase Realtime Database after app was in background.

### ISSUE THREAD

**Issue by robmr88** [FirebaseExtended/flutterfire#2590]
**Describe the bug**
After my app is in the background for some time (a few hours) and I bring it back to the foreground it does not connect to Firebase anymore. The only way to make it connect again is to completely remove it from the background (kill it) and start it again.  The console just keeps printing this every time I try to write something on a node:

D/ViewRootImpl@fc2062a[MainActivity]: ViewPostIme pointer 0D/ViewRootImpl@fc2062a[MainActivity]: ViewPostIme pointer 1
D/INA: [__createAndUpdateConnection] Port to be used for connection : (443) with domainName (s-usc1c-nss-296.firebaseio.com)

sometimes but not always I also see this in the console:
 E/INA: Error in resolving domain (s-usc1c-nss-296.firebaseio.com) for renewing pre-cache : Success

**To Reproduce**
In my realtime database I have 3 nodes from which I am getting my data like this:
```
    DatabaseReference databaseReference = FirebaseDatabase.instance.reference();
    DatabaseReference maindataTable = databaseReference.child('maindata');
    mainDataSubscription = maindataTable.onValue.listen((value) {
```
the data I get I store it in a BehaviorSubject that I then listen to in different points in my app .
I cancel the subscritions in dispose , in onResume and onPaused . I am cancelling the subscription in 3 places just to make sure the subscription is being actually cancelled because this bug has been driving me crazy for a month now.

**Additional context**
The bug is identical even if I don't cancel the StreamSubscription

**Flutter doctor**
Run `flutter doctor` and paste the output below:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale it-IT)
    • Flutter version 1.12.13+hotfix.9 at /Users/ulixe/developer/flutter
    • Framework revision f139b11009 (7 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ulixe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Lenovo TB X505L • HA127MFG                                 • android-arm64 • Android 9 (API 28)
    • SM A705FN       • R58MB3Z05KA                              • android-arm64 • Android 10 (API 29)
    • iPhone di Denys • f4900e1d2f463e8966b243609f0bb857dd6f8674 • ios           • iOS 12.4.6

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @robmr88 
can you please provide your and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal runnable code sample to reproduce the problem
Thank you

**Comment by robmr88** [comment]
Sure, here is my FirebaseApi class, at app startup I call getMainData that gets the maindata node and keeps a connection opened and keeps the data fresh and in sync in real time. The problem is that after the app is in the background for a while and resumed these calls they just hang. they don't provide data and they don't provide any error. it just hangs there with no callback. 

abstract class UserInfoResponseListener {
  void onUserInfoReady(UserInfoResponse userInfoResponse);
}

abstract class FirstOrderIdsListener{
  void onFirsOrdersReady(FirstOrderIds firstOrderIds);
}

abstract class MainDataReadyListener{
  void onMainDataready(MainData mainData);
}

class UserInfoResponse{
  UserInfo userInfo;
  bool userHasData;
}


class FirebaseApi {

  static bool gettinMainData = false;
  static MainData _mainData = null;
  static BehaviorSubject<MainData> _mainDataSubject = BehaviorSubject();


  static bool gettinUser = false;
  static UserInfoResponse _userInfo;
  static BehaviorSubject<UserInfoResponse> _userInfoSubject = BehaviorSubject();

  static bool gettinFirst = false;
  static FirstOrderIds _firstOrderIds;
  static BehaviorSubject<FirstOrderIds> _firstOrderIdsSubject = BehaviorSubject();

  static StreamSubscription mainDataSubscription;
  static StreamSubscription userSubscription;
  static StreamSubscription firstSubscription;


  static void clearUser(){
    _userInfo = null;
    _userInfoSubject.add(_userInfo);
  }

  static void resetListeners(){

    if(mainDataSubscription!=null)
      mainDataSubscription.cancel();

    if(userSubscription!=null)
      userSubscription.cancel();

    if(firstSubscription!=null)
      firstSubscription.cancel();

  }



  static void fetchData() {

    gettinMainData = true;


    DatabaseReference databaseReference = FirebaseDatabase.instance.reference();
    DatabaseReference maindataTable = databaseReference.child('maindata');
    mainDataSubscription = maindataTable.onValue.listen((value) {

      print("FirebaseApi__ maindata getting value");

      if (value != null && value.snapshot != null &&
          value.snapshot.value != null) {
        Map<dynamic, dynamic> maindataAsJson = value.snapshot.value;
        print('mainData as json: ${maindataAsJson}');

        Map<String, dynamic> mainDataAsJsonString = Map();

        for (var entry in maindataAsJson.entries) {
          String key = entry.key.toString();
          mainDataAsJsonString[key] = entry.value;
        }

        _mainData = MainData.fromJson(mainDataAsJsonString);
        _mainDataSubject.add(_mainData);
        gettinMainData = false;


      } else {
        print("FirebaseApi__ menu data is null");
      }
    });

    mainDataSubscription.onError((error) {
      gettinMainData = false;
      print("FirebaseApi__ mainData get error ${error}");
    });



  }

  static void fetchFirstOrders(){

    DatabaseReference databaseReference = FirebaseDatabase.instance.reference();
    DatabaseReference firstOrderIdsTable = databaseReference.child("firsts");

    gettinFirst = true;
    firstSubscription = firstOrderIdsTable.onValue.listen((data){
      gettinFirst = false;

      print("FirebaseApi__ firsts getting value");


      Map<dynamic, dynamic> firstsAsJson = data.snapshot.value;
      print('firstsAsJson as json: ${firstsAsJson}');

      Map<String, dynamic> firstsAsJsonString = Map();

      for (var entry in firstsAsJson.entries) {
        String key = entry.key.toString();
        firstsAsJsonString[key] = entry.value;
      }

      FirstOrderIds firstOrderIds = FirstOrderIds.fromJson(firstsAsJsonString);
      _firstOrderIds = firstOrderIds;
      _firstOrderIdsSubject.add(firstOrderIds);

    });

    firstSubscription.onError((error){
      gettinFirst = false;
    });


  }

  static void fetchUserData(String userId){

    FbAuth.FirebaseAuth.instance.onAuthStateChanged.listen((user){
      if(user==null){
        clearUser();
      }
    });

    DatabaseReference databaseReference = FirebaseDatabase.instance.reference();
    databaseReference.child("userInfo").child("${userId}").keepSynced(true);

    gettinUser = true;
    userSubscription = databaseReference.child("userInfo").child("${userId}").onValue.listen((data){
      gettinUser = false;

      print("FirebaseApi__ user getting value");

      if (data == null || data.snapshot == null ||
          data.snapshot.value == null) {
        UserInfoResponse userInfoResponse = UserInfoResponse();
        userInfoResponse.userHasData = false;
        _userInfo = userInfoResponse;
        _userInfoSubject.add(_userInfo);
      }
      else {
        Map<dynamic, dynamic> userInfoAsJson = data.snapshot.value;
        print('userinfo as json: ${userInfoAsJson}');

        Map<String, dynamic> userInfoAsJsonString = Map();

        for (var entry in userInfoAsJson.entries) {
          String key = entry.key.toString();
          userInfoAsJsonString[key] = entry.value;
        }

        UserInfoResponse userInfoResponse = UserInfoResponse();
        userInfoResponse.userInfo = UserInfo.fromJson(userInfoAsJsonString);
        userInfoResponse.userHasData = true;

        _userInfo = userInfoResponse;
        _userInfoSubject.add(_userInfo);
      }
    });

    userSubscription.onError((error){
      gettinUser = false;
    });
  }
  
  static Stream<MainData> getMainData() {

    if(_mainData == null){
      if(!gettinMainData)
      fetchData();
    }
    return _mainDataSubject;

  }

  static Stream<UserInfoResponse> getUserInfo(String userId) {

    if(_userInfo==null ){
      if(!gettinUser)
        fetchUserData(userId);
    }
    return _userInfoSubject;


  }

  static Stream<FirstOrderIds> getFirstOrders() {

    if(_firstOrderIds==null ){
      if(!gettinFirst)
        fetchFirstOrders();
    }
    return _firstOrderIdsSubject;


  }


}

**Comment by robmr88** [comment]
Hi, I think I just found my bug. I actually am resetting the Streams but not the data. The new Streams are never used... So sorry if I made you waste time..

**Comment by TahaTesser** [comment]
Hi @robmr88 
It's okay 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by robmr88** [comment]
Hi, unfortunately I have to come back to this issue.
I have done some more testing, unfortunately given the nature of the problem the tests are not fast. Basically I have to wait a few hours for the bug to happen. Once again I take the app from the background after a few hours of inactivity and it doesn't connect to Firebase Realtime Database. When I try to write a value to a node it does nothing and in the logs it loops this with a 30 second frequency: D/INA: [__createAndUpdateConnection] Port to be used for connection : (443) with domainName (s-usc1c-nss-296.firebaseio.com)
