### ISSUE TITLE
[FIREBASE_AUTH] DEMO/Linking multiple auth providers starter

### ISSUE THREAD

**Issue by darasat** [FirebaseExtended/flutterfire#2593]
**so many problems with multiple auth providers using firebase auth with flutter for unique account.**

Good day
**I want an example showing firebase auth multiple providers flow**
I am confused , using flutter auth with different providers (Google, Facebook and email) can you make a demo  showing features like linking multiple auth providers and his flow (create users , login , signout) 

Thank you very much! 

**Additional context**
1. Firebase account linking 
https://firebase.google.com/docs/auth/web/account-linking

2. https://stackoverflow.com/questions/55716180/link-multiple-auth-providers-to-an-account

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration
