### ISSUE TITLE
[Database] Issue when reading single field on a OrderbyChild Filter

### ISSUE THREAD

**Issue by waseemahmed-za** [FirebaseExtended/flutterfire#2596]
**Describe the bug**
When doing a datasnapshot using a OrderbyChild filter, the snapshot is not returning an Array every time even though the tree structure is consistent between my various childs.

e.g. when querying based on the first item in the list, i gent a snapshot length of 1. on item 2 the length is 2 and the all other items are length 1 as well.

However when querying on any item after the first, the snapshot is never returned as a Array which means i cannot extract a specific field on the Array.

**To Reproduce**
1. run a query on tree than has identical structure for all children. 
2. retrieve a particular field for each child but similar field.
4. Check if the field is obtainable regardless of which child is triggered.

**Expected behavior**
based on the filter in EqualTo, the query should return an Array for my data and i should be able to read that value regardless of which item in the tree it is.

**Additional context**
there is a serious issue with the snapshot not returning any of the children other than the first item as an Array.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.778], locale en-ZA)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.0)
[√] Connected device (1 available)

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @waseemahmed-za 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem and sample database for RealTime Database 
Thank you

**Comment by waseemahmed-za** [comment]
Hi TahaDo you have any feedback on this issue?Regards?Waseem Ahmed
-------- Original message --------From: Taha Tesser <notifications@github.com> Date: 2020/05/21  2:20 PM  (GMT+02:00) To: FirebaseExtended/flutterfire <flutterfire@noreply.github.com> Cc: waseemahmed-za <waseem@openbid.co.za>, Mention <mention@noreply.github.com> Subject: Re: [FirebaseExtended/flutterfire] [<Firebase Realtime Database>] <Issue when reading single field on a OrderbyChild Filter> (#2596) 
Hi @waseemahmed-za
can you please provide your flutter run --verbose?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem and sample database for RealTime Database
Thank you

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FirebaseExtended/flutterfire/issues/2596#issuecomment-632055312",
"url": "https://github.com/FirebaseExtended/flutterfire/issues/2596#issuecomment-632055312",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TahaTesser** [comment]
Hi @waseemahmed-za 
Also provide a minimal code sample
Thank you

**Comment by waseemahmed-za** [comment]
Hi Taha. I did attach sample code. The query I am running is in attached.Waseem AhmedDirector072 455 6892
-------- Original message --------From: Taha Tesser <notifications@github.com> Date: 2020/05/25  4:34 PM  (GMT+02:00) To: FirebaseExtended/flutterfire <flutterfire@noreply.github.com> Cc: waseemahmed-za <waseem@openbid.co.za>, Mention <mention@noreply.github.com> Subject: Re: [FirebaseExtended/flutterfire] [<Firebase Realtime Database>] <Issue when reading single field on a OrderbyChild Filter> (#2596) 
Hi @waseemahmed-za
Also provide a minimal code sample
Thank you

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FirebaseExtended/flutterfire/issues/2596#issuecomment-633600906",
"url": "https://github.com/FirebaseExtended/flutterfire/issues/2596#issuecomment-633600906",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by waseemahmed-za** [comment]
More sample code attached Waseem AhmedDirector072 455 6892
-------- Original message --------From: Taha Tesser <notifications@github.com> Date: 2020/05/25  4:34 PM  (GMT+02:00) To: FirebaseExtended/flutterfire <flutterfire@noreply.github.com> Cc: waseemahmed-za <waseem@openbid.co.za>, Mention <mention@noreply.github.com> Subject: Re: [FirebaseExtended/flutterfire] [<Firebase Realtime Database>] <Issue when reading single field on a OrderbyChild Filter> (#2596) 
Hi @waseemahmed-za
Also provide a minimal code sample
Thank you

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/FirebaseExtended/flutterfire/issues/2596#issuecomment-633600906",
"url": "https://github.com/FirebaseExtended/flutterfire/issues/2596#issuecomment-633600906",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by russellwheatley** [comment]
I'm going to close this unless a reproducible code sample is provided.
