### ISSUE TITLE
Error when reading 'firebase_core_platform_interface.dart'

### ISSUE THREAD

**Issue by fodbad** [FirebaseExtended/flutterfire#2604]
this issue started suddenly. note that I've run `flutter clean` and still nothing 
```
Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/firebase_core.dart:5:1: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_platform_interface-1.0.4/lib/firebase_core_platform_interface.dart': No such file or directory
export 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart'
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:8:8: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_platform_interface-1.0.4/lib/firebase_core_platform_interface.dart': No such file or directory
import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart';
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:26:10: Error: Type 'FirebaseOptions' not found.
  Future<FirebaseOptions> get options async {
         ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:53:15: Error: Type 'FirebaseOptions' not found.
    @required FirebaseOptions options,
              ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:27:11: Error: 'PlatformFirebaseApp' isn't a type.
    final PlatformFirebaseApp app =
          ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:28:15: Error: The getter 'FirebaseCorePlatform' isn't defined for the class 'FirebaseApp'.
 - 'FirebaseApp' is from 'package:firebase_core/src/firebase_app.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FirebaseCorePlatform'.
        await FirebaseCorePlatform.instance.appNamed(name);
              ^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:36:11: Error: 'PlatformFirebaseApp' isn't a type.
    final PlatformFirebaseApp app =
          ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:37:15: Error: Getter not found: 'FirebaseCorePlatform'.
        await FirebaseCorePlatform.instance.appNamed(name);
              ^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:53:15: Error: 'FirebaseOptions' isn't a type.
    @required FirebaseOptions options,
              ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:63:11: Error: Getter not found: 'FirebaseCorePlatform'.
    await FirebaseCorePlatform.instance.configure(name, options);
          ^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:70:16: Error: 'PlatformFirebaseApp' isn't a type.
    final List<PlatformFirebaseApp> result =
               ^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:71:15: Error: Getter not found: 'FirebaseCorePlatform'.
        await FirebaseCorePlatform.instance.allApps();
              ^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+3/lib/src/firebase_app.dart:74:12: Error: 'PlatformFirebaseApp' isn't a type.
          (PlatformFirebaseApp app) => FirebaseApp(name: app.name),
           ^^^^^^^^^^^^^^^^^^^
Exception: Gradle task assembleDebug failed with exit code 1

```

**Flutter doctor**

`/Users/mac/flutter/bin/flutter doctor --verbose
Unable to find any JVMs matching version "1.8".
Unable to find any JVMs matching version "1.8".
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-DZ)
    • Flutter version 1.17.0 at /Users/mac/flutter
    • Framework revision e6b34c2b5c (3 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

Unable to find any JVMs matching version "1.8".
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.1+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at path-to-android-studio/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at path-to-android-studio/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[!] Connected device
    ! No devices available
`

I'm using IntelliJ

**Comment by luiscruzurvenue** [comment]
Hi, i'm using the same version:
firebase_core: 0.4.4+3

And i have no problems.

Did you run pub get?

**Comment by fodbad** [comment]
> firebase_core: 0.4.4+3

yes, still nothing :/ looks like firebase_core_platform_interface.dart isn't included in the package for some reason . I tried different versions but still nothing
is there a way I can add the file manually?

**Comment by TahaTesser** [comment]
Hi @fodbad 
Please try latest version of `firebase_core` and `pod update` from ios fodler and try again 
can you please provide you `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by fodbad** [comment]
SOLVED!
`firebase_core_platform_interface: ^1.0.4` is included with `firebase_core` so i forced downgraded by adding `firebase_core_platform_interface: ^1.0.2` to pubspec.yaml 

the problem seemed that firebase_core_platform_interface.dart wasn't found anywhere and when I went through the dart packages the file was indeed not included in the package for some reason.

TO DO:
-Check if your current **firebase_core_platform_interface** package includes `firebase_core_platform_interface.dart`
- Add `firebase_core_platform_interface: ^1.0.2` to your pubspec.yaml
- Delete **firebase_core_platform_interface1.0.4** from the dart packages directory

**Comment by celesteking** [comment]
Entire setup instruction at https://firebase.google.com/docs/flutter/setup  are useless because of this error.  You should really fix either this error or that page. Try to exactly follow that page and see what you get. Maybe you should fix the versions on that page, dunno.

**Comment by markusaksli-nc** [comment]
This popped up again for some people with `firebase_core_platform_interface-2.0.0` on `firebase_core v0.5.0+1` see https://github.com/FirebaseExtended/flutterfire/issues/3986#issuecomment-719398054 for the solution (very weird that missing braces would be in the sdk like that).

**Comment by russellwheatley** [comment]
Nothing to action here now as the solution is to use the latest `firebase_core` package.
