### ISSUE TITLE
Firebase auth crashing app after restarting app

### ISSUE THREAD

**Issue by james9181** [FirebaseExtended/flutterfire#2608]
My app seems to work fine initially, where i can constantly log in and out of different accounts. But if I exit the app by using the back button and reopen the app, trying to sign in and out crashes the app (all other features of the app are fine e.g. firestore access). This gives the following info:

> java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(20520): at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged(FirebaseAuthPlugin.java:710)
E/AndroidRuntime(20520): at com.google.firebase.auth.zzp.run(com.google.firebase:firebase-auth@@19.2.0:3)
E/AndroidRuntime(20520): at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20520): at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20520): at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(com.google.firebase:firebase-auth@@19.2.0:6)
E/AndroidRuntime(20520): at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(20520): at android.app.ActivityThread.main(ActivityThread.java:7857)
E/AndroidRuntime(20520): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20520): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(20520): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

If i choose to instead exit the app by viewing all apps running in the background and swiping it away, or simply tapping the home button, the app works perfectly fine and I can log in and out without crashing. Any help would be appreciated as I'm still pretty new with flutter/firebase

**Comment by TahaTesser** [comment]
Hi @james9181 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by james9181** [comment]
@TahaTesser
flutter doctor -v (I am using android studio, not vscode)

> [√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.17763.1217], locale en-GB)
>     • Flutter version 1.17.0 at C:\sdk flutter\flutter
>     • Framework revision e6b34c2b5c (3 weeks ago), 2020-05-02 11:39:18 -0700
>     • Engine revision 540786dd51
>     • Dart version 2.8.1
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\james\AppData\Local\Android\sdk
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.8052
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [!] VS Code (version 1.45.1)
>     • VS Code at C:\Users\james\AppData\Local\Programs\Microsoft VS Code
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (1 available)
>     • SM G965F • 239b61e50f057ece • android-arm64 • Android 10 (API 29)
> 
> ! Doctor found issues in 1 category.

flutter run --verbose (I assume you mean just where it crashes the app?)

> [+3742 ms] D/ViewRootImpl@66b3716[MainActivity](12588): ViewPostIme pointer 0
> [ +143 ms] D/ViewRootImpl@66b3716[MainActivity](12588): ViewPostIme pointer 1
> [  +32 ms] I/BiChannelGoogleApi(12588): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@dea12ee
> [+1231 ms] D/FirebaseAuth(12588): Notifying id token listeners about user ( lbNJm4UhpFZFdirkAv5cXeb9mda2 ).
> [   +2 ms] D/FirebaseAuth(12588): Notifying auth state listeners about user ( lbNJm4UhpFZFdirkAv5cXeb9mda2 ).
> [   +2 ms] D/AndroidRuntime(12588): Shutting down VM
> [   +2 ms] E/AndroidRuntime(12588): FATAL EXCEPTION: main
> [   +2 ms] E/AndroidRuntime(12588): Process: com.example.netflixlist, PID: 12588
> [   +2 ms] E/AndroidRuntime(12588): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
> [   +3 ms] E/AndroidRuntime(12588):     at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged(FirebaseAuthPlugin.java:710)
> [   +4 ms] E/AndroidRuntime(12588):     at com.google.firebase.auth.zzp.run(com.google.firebase:firebase-auth@@19.2.0:3)
> [   +2 ms] E/AndroidRuntime(12588):     at android.os.Handler.handleCallback(Handler.java:883)
> [   +2 ms] E/AndroidRuntime(12588):     at android.os.Handler.dispatchMessage(Handler.java:100)
> [   +2 ms] E/AndroidRuntime(12588):     at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(com.google.firebase:firebase-auth@@19.2.0:6)
> [   +2 ms] E/AndroidRuntime(12588):     at android.os.Looper.loop(Looper.java:237)
> [   +1 ms] E/AndroidRuntime(12588):     at android.app.ActivityThread.main(ActivityThread.java:7857)
> [   +1 ms] E/AndroidRuntime(12588):     at java.lang.reflect.Method.invoke(Native Method)
> [   +1 ms] E/AndroidRuntime(12588):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> [   +1 ms] E/AndroidRuntime(12588):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
> [  +20 ms] I/Process (12588): Sending signal. PID: 12588 SIG: 9
> [ +113 ms] Service protocol connection closed.
> [   +3 ms] Lost connection to device.
> [  +10 ms] executing: C:\Users\james\AppData\Local\Android\sdk\platform-tools\adb.exe -s 239b61e50f057ece forward --list
> [  +71 ms] Exit code 0 from: C:\Users\james\AppData\Local\Android\sdk\platform-tools\adb.exe -s 239b61e50f057ece forward --list
> [        ] 239b61e50f057ece tcp:64351 tcp:34029
> [   +1 ms] executing: C:\Users\james\AppData\Local\Android\sdk\platform-tools\adb.exe -s 239b61e50f057ece forward --remove tcp:64351
> [  +46 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.netflixlist/code_cache/netflix_listFYFQCG/netflix_list/)
> [        ] Sending to VM service: _deleteDevFS({fsName: netflix_list})
> [ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
> [   +2 ms] executing: C:\Users\james\AppData\Local\Android\sdk\platform-tools\adb.exe -s 239b61e50f057ece forward --list
> [  +40 ms] Exit code 0 from: C:\Users\james\AppData\Local\Android\sdk\platform-tools\adb.exe -s 239b61e50f057ece forward --list
> [   +1 ms] "flutter run" took 153,069ms.

I haven't written a reproduction of the problem yet, but I can outline it. 

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<User>.value(
      value: AuthService().user,
      child: MaterialApp(
        home: Wrapper(),
      )
    );
  }
}
```

This is to detect a change in user auth. The AuthService().user returns FirebaseUser converted into a User class i decided to keep user details in. I found that it crashes after code snippets like:

`
AuthResult result = await _auth.signInAnonymously();
`
`
return await _auth.signOut();
`
and all other authorisation functions.

**Comment by james9181** [comment]
@TahaTesser 
Wrote some quick code to reproduce the problem. Works as intended until backing out of the app and reentering. 

[debugApp.zip](https://github.com/FirebaseExtended/flutterfire/files/4668495/debugApp.zip)

**Comment by TahaTesser** [comment]
Hi @james9181 
Your code isn't minimal, please remove provider and create a minimal sample code that reproduces the issue with Firebase Auth
Thank you

**Comment by james9181** [comment]
It turns out that this is a problem on the current version of FirebaseAuth. After downgrading to version 0.15.5+3, it seemed to fix the problem

Related link at [https://github.com/FirebaseExtended/flutterfire/issues/2517](url)

**Comment by kinex** [comment]
@james9181 The link you referenced is a different issue (different plugin), but it is possible that the root cause is same (same invalid logic in both plugins). 

I think I have the same issue (actually this is top 1 issue in the update I released yesterday). I cannot reproduce this myself but I see a lot of crashes in Crashlytics. 

Crash log:
```
java.lang.NullPointerException: 
  at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged (FirebaseAuthPlugin.java:45)
  at com.google.firebase.auth.zzp.run (zzp.java:24)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage (zzj.java)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7770)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1047)
```

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)
```
firebase_auth: ^0.16.1

**Comment by kinex** [comment]
@TahaTesser  I also reviewed the plugin code quickly. I think this line https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java#L710
should verify if `channel` is null. `channel` is set to null in `onDetachedFromEngine`. Maybe better to check all references to `channel`.
