### ISSUE TITLE
[firebase_core] Allow one configuration file for all plattforms

### ISSUE THREAD

**Issue by IchordeDionysos** [FirebaseExtended/flutterfire#2612]
**Is your feature request related to a problem? Please describe.**
In the Roadmap #2582 is the effort described to "Reduce the installation steps".

Adding the config file for every platform is cumbersome, adding just one file for all platforms would be great.

**Describe the solution you'd like**
I would settle on some kind of format (maybe JSON) and folder name for a Flutter config file.

This config file should be added to the application by the developer and `firebase_core` would try to read that file first to configure any Firebase app using these methods [Android](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/FirebaseApp#initializeapp_1), [iOS](https://firebase.google.com/docs/reference/swift/firebasecore/api/reference/Classes/FirebaseApp#configureoptions:), [web](https://firebase.google.com/docs/reference/js/firebase#initializeapp).

**Additional context**
For the priority, I would first look at the Firebase config file and then try to use the platform-specific config files.

JSON as a format could be helpful as a format as one could for now just copy the web config.

@FirebaseExtended/invertase @Salakar Could be relevant for the core rework invertase/flutterfire#7

**Comment by Salakar** [comment]
@IchordeDionysos appreciate you taking the time to write this out, unfortunately this isn't something we're going to be looking at, at least not as part of #2582 - there's some complications as each platform has their own specific keys and ways of initializing these credentials.

Having said that though; we are taking steps to make it easier for you to figure out how to integrate the credentials, e.g. we've got a new docs site in the works with specific platform integration sections: https://firebase.flutter.dev/docs/overview#platform-setup - and we're also taking steps to reduce manual native code changes that are normally required to integrate.
