### ISSUE TITLE
[firebase_dynamic_links] onLink gets called every time on hot restart

### ISSUE THREAD

**Issue by spareblock** [FirebaseExtended/flutterfire#2614]
**Describe the bug**
When I open the app from link and then hot restart the app from terminal, the onLink gets called again with the same link thus navigating to the route. Is this a desired behavior? Because when developing, I have to quit and start app every time.

**To Reproduce**
1. Open the app by dynamic link
2. Hot restart the app from terminal

**Expected behavior**
I expect the link to be cleared on hot restart.

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @spareblock 
can you please provide your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you
