### ISSUE TITLE
Firebase sign-in on Web

### ISSUE THREAD

**Issue by mark-zs** [FirebaseExtended/flutterfire#2616]
Hi I am trying the test code for auth: and firebase_auth: for a Flutter Web app (not mobile).  In both cases I get 
`TypeError: Cannot read property 'app' of undefined`
Are these packages not valid for a Web app?  Or is there some setup I need to do?
For example I get that error when running for Web the code given here
https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4

Maybe someone can tell me the best package for normal login and social login for Web please or tell me how to fix this please.  Thanks?

**Comment by sergiocasero** [comment]
You need to configure the firebase object in web/index.html, something like this:

```
<script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-firestore.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-storage.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
         https://firebase.google.com/docs/web/setup#available-libraries -->

    <script>
        // Your web app's Firebase configuration
        var firebaseConfig = {
            apiKey: "YOUR_API_KEY",
            authDomain: "YOUR_DOMAIN",
            databaseURL: "YOUR_DATABASE",
            projectId: "YOUR_PROJECT_ID",
            storageBucket: "STORAGE",
            messagingSenderId: "PUSH_ID",
            appId: "APP_ID"
        };
        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
    </script>
```

hope this help you :)

**Comment by zvischreiber** [comment]
Great that helped thanks :-)

Would be good to mention that in the docs.

Thanks for your help

**Comment by sergiocasero** [comment]
Yep, I've discovered it by myself :(

**Comment by ShardulNalegave** [comment]
Hi! Did your project work?
I have done the same setup and everything is working but when I reload the page, the user signs out automatically.
Please help!

**Comment by zvischreiber** [comment]
Yes once I fixed index.html and the other issues it's working fine thank you

**Comment by iapicca** [comment]
Hi @zvischreiber 
if you don't mind I'd like to keep the issue open
to improve the docs following @sergiocasero 's solution
Thank you

**Comment by Ehesp** [comment]
Docs now in place: https://firebase.flutter.dev/docs/auth/overview
