### ISSUE TITLE
[firebase_dynamic_link] listener not being called on iOS

### ISSUE THREAD

**Issue by quetool** [FirebaseExtended/flutterfire#262]
I have tried both on iOS 12 and 13 and `FirebaseDynamicLinks.instance.onLink` listener is not being called at all... App is opened just fine, but like I said, the listener is not being called...

**Comment by quetool** [comment]
I debugged my Dynamic Link and it looks fine...
![Captura de Pantalla 2019-10-03 a la(s) 17 00 09](https://user-images.githubusercontent.com/14978705/66159941-6bd43000-e5ff-11e9-93a1-3bf8d65ad743.png)
![Captura de Pantalla 2019-10-03 a la(s) 17 00 27](https://user-images.githubusercontent.com/14978705/66159942-6bd43000-e5ff-11e9-9639-de811d5a668f.png)

**Comment by quetool** [comment]
So, finally I came up with the solution... In Dynamic Link firebase docs you will find this:

![Captura de Pantalla 2019-10-03 a la(s) 17 49 18](https://user-images.githubusercontent.com/14978705/66163241-3bdc5b00-e606-11e9-8e88-1edb1f89cfd0.png)

I must say this is not mentioned in the flutter plugin README doc 
https://pub.dev/packages/firebase_dynamic_links#-readme-tab-

So adding that key I solved the issue... 

Here it is the doc https://firebase.google.com/docs/dynamic-links/custom-domains?authuser=0

**Comment by HofmannZ** [comment]
Hi @quetool,

Just wondering what you exactly managed to solve by adding the `FirebaseDynamicLinksCustomDomains` key. Did you manage to read the dynamic link, and its path, in flutter?

**Comment by quetool** [comment]
@HofmannZ yes, before I realize I needed to add that key on the info.plist dynamic links were not being readed at all, not from `FirebaseDynamicLinks.instance.getInitialLink()` nor even from `FirebaseDynamicLinks.instance.onLink`

**Comment by HofmannZ** [comment]
@quetool managed to get that working, though the `onLink` seems to subscribe multiple times and has no dispose method :s Did you get that to work?

**Comment by quetool** [comment]
@HofmannZ you need to add the onLink listener once in an initState() method or in a singleton class. I think you are instantiating the FirebaseDynamicLinks more than one time.

**Comment by HofmannZ** [comment]
@quetool Yeah came to that conclusion as well. The only problem I had was that I was calling `onLink` from inside each page, without the putting` FirebaseDynamicLinks` inside a singleton. Puting it inside a singleton should solve the issue.

Also using `initState` outside `MaterialApp` is not ideal because you don't have to `context` of the `Navigator`

**Comment by quetool** [comment]
I have a main container class (a stateful widget) that contains the entire app. On its initState method I instantiate the FirebaseDynamicLinks.instance with it onLink method. Then I use streams to communicate the link parsing result wherever I want to. But that's my approach.

**Comment by HofmannZ** [comment]
@quetool how did you solve getting the `Navigator` context? Using `navigatorKey` I'm guessing?

**Comment by quetool** [comment]
Maybe is better if you provide some code and an explanation on what you need to do... I do not have problem getting current context becauase like I said I manage everything inside a stateful widget... Anyway, this is just for issues, maybe you can open a question on SO

**Comment by HofmannZ** [comment]
PR #255 managed to fix my issue, thanks!

**Comment by quetool** [comment]
I do not have that sort of problems described on that PR but ok

**Comment by emmett-deen** [comment]
> So, finally I found the solution... In Dynamic Link firebase docs you will find this:
> 
> ![Captura de Pantalla 2019-10-03 a la(s) 17 49 18](https://user-images.githubusercontent.com/14978705/66163241-3bdc5b00-e606-11e9-8e88-1edb1f89cfd0.png)
> 
> I must say this is not mentioned in the flutter plugin README doc
> https://pub.dev/packages/firebase_dynamic_links#-readme-tab-
> 
> So adding that key I solved the issue...
> 
> Here it is the doc https://firebase.google.com/docs/dynamic-links/custom-domains?authuser=0

This MUST be included on pub.dev I feel a large amount of developers will want to use custom domains and will have to dig through hundreds of issues to find this.

**Comment by kwent** [comment]
Please guys update the doc. So hard to find this!

**Comment by surpriso1997** [comment]
Thanks @emmett-deen  for your comment. This problem still exists and your comment helped to solve the problem. I can't believe  the plugin's readme is still not updated.

**Comment by quetool** [comment]
@surpriso1997 uhm... I think you are talking about MY comment :P

**Comment by surpriso1997** [comment]
@quetool  oops sorry, didn't realise that was quoted comment from @emmett-deen  
Thanks a lot man for mentioning that.
