### ISSUE TITLE
firebase issue: createUserWithEmailAndPassword

### ISSUE THREAD

**Issue by anchit987** [FirebaseExtended/flutterfire#2627]
`
//user.dart file
class User {
  String userId;
  User({this.userId});
}

//auth.dart file
import 'package:firebase_auth/firebase_auth.dart';

import '../models/user.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  User _userFromFirebaseUser(FirebaseUser user) {
    return user != null ? User(userId: user.uid) : null;
  }

  Future signUpWithEmailAndPassword(String email, String password) async {
    try {
      AuthResult authResult = await _auth.createUserWithEmailAndPassword(
          email: email, password: password);
      FirebaseUser firebaseUser = authResult.user;
      return _userFromFirebaseUser(firebaseUser);
    } catch (error) {
      print('PrintByMe: $error');
    }
  }

}

//signupscreen.dart file 
//calling function
signUp() async {
    if (_formKey.currentState.validate()) {
      setState(() {
        _isLoading = true;
      });
      print('email:$email , password: $password');
       authService.signUpWithEmailAndPassword(email, password).then((value) {
        if( value != null) {
          setState(() {
            _isLoading = false;
          });
          Navigator.of(context).pushReplacementNamed(HomeScreen.routeName);
          
        }
      });
    }
   
  }

`

`
I/flutter ( 5831): email:anc	 , password: anc
E/flutter ( 5831): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'signUpWithEmailAndPassword' was called on null.
E/flutter ( 5831): Receiver: null
E/flutter ( 5831): Tried calling: signUpWithEmailAndPassword("anc\t", "anc")
E/flutter ( 5831): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 5831): #1      _SignUpScreenState.signUp 
package:quizapp/screens/sign_up_screen.dart:29
E/flutter ( 5831): #2      _SignUpScreenState.build.<anonymous closure> 
package:quizapp/screens/sign_up_screen.dart:98
E/flutter ( 5831): #3      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter ( 5831): #4      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
E/flutter ( 5831): #5      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:282
E/flutter ( 5831): #6      BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:254
E/flutter ( 5831): #7      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 5831): #8      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter ( 5831): #9      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter ( 5831): #10     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 5831): #11     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 5831): #12     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 5831): #13     _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter ( 5831): #14     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter ( 5831): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter ( 5831): #16     _invoke1  (dart:ui/hooks.dart:275:10)
E/flutter ( 5831): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)
`

**Comment by ShardulNalegave** [comment]
Hi! This error has nothing to do with FlutterFire. This error is in your code of AuthService as the method is registered on that. Please check if you are initializing your service properly.
__Also please put your code in code block__
