### ISSUE TITLE
Firebase Messaging Big Picture Style

### ISSUE THREAD

**Issue by TejaDroid** [FirebaseExtended/flutterfire#263]
Hi,

Is there any possibility to show different style of notification like 
**-BigTextStyle
-BigPictureStyle
-InboxStyle
-MessageStyle**  ?

I want to implement in my current app to show **BigPictureStyle Notification** in app, I have to force fully use **flutter_local_notification** plugin, but the problem is that there is no possibility to use both plugin in IOS development.

**Comment by Ehesp** [comment]
I'm going to close this one for now. This functionality exists within the 
https://pub.dev/packages/flutter_local_notifications package - we'll work towards getting them compatible with each other.

Thanks
