### ISSUE TITLE
[firebase_crashlytics] add documentation on how to verify installation

### ISSUE THREAD

**Issue by Undeadlol1** [FirebaseExtended/flutterfire#2635]
I think documentation must specify how one should verify that plugin was installed properly.
How does one crash application intentionally? How does one verify that crashlytics submitted a report?

Currently when I go to "crashlytics" tab in the console there are only two ways described to forcefully crash an application: iOS and Android.

**Comment by Salakar** [comment]
A new Crashlytics plugin has now landed on master (with documentation) which should solve this issue.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin: https://firebase.flutter.dev/docs/migration/
