### ISSUE TITLE
[Firebase-messagem] onMessage is called only when I open the application, only in IOS

### ISSUE THREAD

**Issue by griks-lab** [FirebaseExtended/flutterfire#264]
I send a message through FCM, but my application is not called to handle the message. However when I open the application I get all the messages at once in the onMessage method.

In android this does not happen. The problem is located specifically on the IOS platform.

I followed all the documentation, so that when I open the application I get the messages, would be some limitation of the plugin? Can I get around this?

**Comment by tuanitpro** [comment]
Me too. It's work well on Simulator but on my iPhone (iOS 13.x) work for background only.

**Comment by Salakar** [comment]
Given the age of this issue and that Messaging has had a major rework since; I'm going to close this issue in favour of trying the latest release.
