### ISSUE TITLE
Can't build android app in release mode and there is no specific error just The plugin firebase_dynamic_links could not be built due to the issue above.

### ISSUE THREAD

**Issue by DyaryRaoof** [FirebaseExtended/flutterfire#2640]
**Describe the bug**

I am trying to build my android app fo release mode. I can't do so because of firebase dynamic links plugin. I get no specific error. just   "The plugin firebase_dynamic_links could not be built due to the issue above." it used to work fine just a few days ago. and it still works fine in debug mode.

**Additional context**
the app is a complex one and I have nearly 20 other plugin's installed.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!


```

**Comment by TahaTesser** [comment]
Hi @DyaryRaoof 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by DyaryRaoof** [comment]
Here is the verbose output :

**Comment by DyaryRaoof** [comment]
After going through the verbose output It seems the problem was in another plugin which I managed to fix. Thank you so much and sorry for the inconvenience. I will close this issue now. Thank you again.
