### ISSUE TITLE
[firebase_crashlytics] No stack traces for issues on Crashlytics dashboard

### ISSUE THREAD

**Issue by talent-apps** [FirebaseExtended/flutterfire#2644]
After upgrading to Flutter SDK 1.17, where dart obfuscation is supported by default, **no stack traces appear for crashes that originate from dart code on the Crashlytics dashboard on the Firebase console**.
On earlier versions of the Flutter SDK they were reported with their obfuscated names.

**Comment by TahaTesser** [comment]
Hi @talent-apps 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by talent-apps** [comment]
Output of `flutter doctor -v`:

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version
    10.0.18363.836], locale en-US)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by talent-apps** [comment]
The relevant piece of code is the main function fo the app:
```
void main() async {

  Crashlytics.instance.enableInDevMode = false;
  // Pass all uncaught errors to Crashlytics.
  FlutterError.onError = (FlutterErrorDetails details) {
    Crashlytics.instance.recordFlutterError(details);
  };

  runApp(App());
}
```

**Comment by talent-apps** [comment]
Any update on this?
The official crashlytics plugin is practically useless with Flutter 1.17.X versions.
Uncaught exceptions are not reported properly.

**Comment by talent-apps** [comment]
Any update on this?
The fact that this ticket is still open for months is nothing short of amazing.
Crashes that occur in Flutter apps **in production** do not include stack traces, leaving developers practically blind and incapable to improve the stability of their Flutter apps.

**Comment by talent-apps** [comment]
Any update?
At the moment, the `firebase_crashlytics` plugin is useless for apps that use Dart obfuscation.
Does this plugin have any owners? Why such a crucial issue is left unaddressed?

**Comment by untp** [comment]
I sent a PR that fixes the issue. After merge, we can get obfuscated stack traces like this:
![1](https://user-images.githubusercontent.com/54450843/102347865-12f97900-3fb2-11eb-967b-6b72066bd4ea.png)

We need to remove (.java) and add **4 spaces** every line like this:
```
    #00 abs 000075f179930367 virt 00000000001b0367 _kDartIsolateSnapshotInstructions+0x1a2367
    #01 abs 000075f1797fe8ee virt 000000000007e8ee _kDartIsolateSnapshotInstructions+0x708ee
    #02 abs 000075f17991f448 virt 000000000019f448 _kDartIsolateSnapshotInstructions+0x191448
    #03 abs 000075f1797c247a virt 000000000004247a _kDartIsolateSnapshotInstructions+0x3447a
    #04 abs 000075f17990e5f9 virt 000000000018e5f9 _kDartIsolateSnapshotInstructions+0x1805f9
    #05 abs 000075f179874385 virt 00000000000f4385 _kDartIsolateSnapshotInstructions+0xe6385
    #06 abs 000075f1798b64c6 virt 00000000001364c6 _kDartIsolateSnapshotInstructions+0x1284c6
    #07 abs 000075f1797c04c6 virt 00000000000404c6 _kDartIsolateSnapshotInstructions+0x324c6
    #08 abs 000075f1799493fa virt 00000000001c93fa _kDartIsolateSnapshotInstructions+0x1bb3fa
    #09 abs 000075f17994937d virt 00000000001c937d _kDartIsolateSnapshotInstructions+0x1bb37d
    #10 abs 000075f1798d749d virt 000000000015749d _kDartIsolateSnapshotInstructions+0x14949d
    #11 abs 000075f1797c07cc virt 00000000000407cc _kDartIsolateSnapshotInstructions+0x327cc
    #12 abs 000075f1797ce432 virt 000000000004e432 _kDartIsolateSnapshotInstructions+0x40432
    #13 abs 000075f179837196 virt 00000000000b7196 _kDartIsolateSnapshotInstructions+0xa9196
    #14 abs 000075f1797ce30e virt 000000000004e30e _kDartIsolateSnapshotInstructions+0x4030e
    #15 abs 000075f1797cdf10 virt 000000000004df10 _kDartIsolateSnapshotInstructions+0x3ff10
    #16 abs 000075f1797cde23 virt 000000000004de23 _kDartIsolateSnapshotInstructions+0x3fe23
    #17 abs 000075f1797cdc7d virt 000000000004dc7d _kDartIsolateSnapshotInstructions+0x3fc7d
    #18 abs 000075f1797d400d virt 000000000005400d _kDartIsolateSnapshotInstructions+0x4600d
    #19 abs 000075f1797b2914 virt 0000000000032914 _kDartIsolateSnapshotInstructions+0x24914
    #20 abs 000075f1798ebc8d virt 000000000016bc8d _kDartIsolateSnapshotInstructions+0x15dc8d
    #21 abs 000075f1798c37a1 virt 00000000001437a1 _kDartIsolateSnapshotInstructions+0x1357a1
    #22 abs 000075f1797b3852 virt 0000000000033852 _kDartIsolateSnapshotInstructions+0x25852
    #23 abs 000075f1797b3756 virt 0000000000033756 _kDartIsolateSnapshotInstructions+0x25756
```

After saving this to a file (error.txt), we can run `flutter symbolize -d symbols/app.android-x64.symbols -i error.txt`
```
#0      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:firebase_crashlytics_example/main.dart:153)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:304)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77)
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267)
#16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213)
#19     _rootRunUnary (dart:async/zone.dart:1206)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
#22     _invoke1 (dart:ui/hooks.dart:265)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174)
```

**Comment by talent-apps** [comment]
@untp Great news!
When will it be merged?

**Comment by untp** [comment]
I don't know. I am not a maintainer. We need to wait the review process.

**Comment by krokyze** [comment]
Hopefully someday Firebase will support this automatically ❤️

**Comment by talent-apps** [comment]
@untp 
We tested the PR and we successfully managed to deobfuscate crashes from the Crashlytics reports.
One question remains: each report on the dashboard contains a reason field which is also obfuscated.
Example: `Error thrown Instance of 'Ax'.` 
 Is there a way to deobfuscate it? It could be very helpful for the analysis.

**Comment by untp** [comment]
Hi @talent-apps 

Thanks for testing my PR.

If you want to deobfuscate it too, you need `CodeSourceMap`.
You can generate that file with adding build options:

`android/gradle.properties`
```
...
extra-gen-snapshot-options=--save-obfuscation-map=symbols/android.mapping.json
```

`ios/Flutter/Release.xcconfig`
```
...
EXTRA_GEN_SNAPSHOT_OPTIONS=--save-obfuscation-map=symbols/ios.mapping.json
```

Then you can run `flutter build <target> --obfuscate --split-debug-info=symbols`.

You will get a json file containing an array `["original[0]", "obfuscated[0]", "original[1]", "obfuscated[1]", ...]`.
With this file, you can find out what `Ax` symbol is.

**Comment by talent-apps** [comment]
@untp Thanks for the quick response.
We will test it and update.

**Comment by deepak786** [comment]
recorded the exception in Firebase like below from the obfuscated dart code.
<img width="1139" alt="Screen Shot 2021-01-18 at 7 33 42 PM" src="https://user-images.githubusercontent.com/14223997/104925042-49b51b80-59c4-11eb-9eb3-85c21284b89f.png">

But it is fine if the dart code is not obfuscated.

**Comment by deepak786** [comment]
**Update with the pull request:**
Tested the pull request https://github.com/FirebaseExtended/flutterfire/pull/4407 and it generated the below stack trace.
Now not getting the error ```Unable to generate stack trace element from Dart error.``` So I think it worked.
Also tested the below stack trace with symbols to read it and it also worked fine. 

But the crashlytics shows that ```This VM has been configured to produce stack traces that violate the Dart standard.``` @untp can you please check this?


```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: exception from obfuscated apk. Error thrown Instance of 'HA'.
       at This VM has been configured to produce stack traces that violate the Dart standard.(This VM has been configured to produce stack traces that violate the Dart standard.java)
       at .*** *** *** *** *** *** *** *** *** *** *** *** *** *** ***(.java)
       at .    #00 abs 0 virt 00556c27 _kDartIsolateSnapshotInstructions+0x54ac27(.java)
       at .    #01 abs 0 virt 00137df3 _kDartIsolateSnapshotInstructions+0x12bdf3(.java)
       at .    #02 abs 0 virt 0007a15f _kDartIsolateSnapshotInstructions+0x6e15f(.java)
       at .    #03 abs 0 virt 004168ab _kDartIsolateSnapshotInstructions+0x40a8ab(.java)
       at .    #04 abs 0 virt 001cf227 _kDartIsolateSnapshotInstructions+0x1c3227(.java)
       at .    #05 abs 0 virt 001cf11f _kDartIsolateSnapshotInstructions+0x1c311f(.java)
       at .    #06 abs 0 virt 0018d913 _kDartIsolateSnapshotInstructions+0x181913(.java)
       at .    #07 abs 0 virt 0018d663 _kDartIsolateSnapshotInstructions+0x181663(.java)
       at .    #08 abs 0 virt 00061477 _kDartIsolateSnapshotInstructions+0x55477(.java)
       at .    #09 abs 0 virt 00061063 _kDartIsolateSnapshotInstructions+0x55063(.java)
       at .    #10 abs 0 virt 0007117f _kDartIsolateSnapshotInstructions+0x6517f(.java)
       at .    #11 abs 0 virt 00071317 _kDartIsolateSnapshotInstructions+0x65317(.java)
       at .    #12 abs 0 virt 000717ef _kDartIsolateSnapshotInstructions+0x657ef(.java)
       at .    #13 abs 0 virt 0001c987 _kDartIsolateSnapshotInstructions+0x10987(.java)
       at .    #14 abs 0 virt 00466bfb _kDartIsolateSnapshotInstructions+0x45abfb(.java)
       at .    #15 abs 0 virt 0046bef7 _kDartIsolateSnapshotInstructions+0x45fef7(.java)
       at .    #16 abs 0 virt 0003a04f _kDartIsolateSnapshotInstructions+0x2e04f(.java)
       at .    #17 abs 0 virt 0003ed4f _kDartIsolateSnapshotInstructions+0x32d4f(.java)
       at .    #18 abs 0 virt 0003ecdf _kDartIsolateSnapshotInstructions+0x32cdf(.java)
```

**Comment by untp** [comment]
@deepak786 Thanks for testing my PR. You can ignore this warning. Also, this warning will be removed in future versions of Dart (See dart-lang/sdk#43388).

**Comment by marcosmko** [comment]
Hello!

Any update on this?

**Comment by deepak786** [comment]
@untp I'm already using your pull request code for the crashlytics like below under dependency_overrides:
```
firebase_crashlytics:
    git:
      url: https://github.com/untp/flutterfire.git
      ref: obfuscated-stack-traces
      path: packages/firebase_crashlytics/firebase_crashlytics
```

But right now getting the error:
```
Because every version of firebase_crashlytics from git depends on firebase_core ^0.8.0-nullsafety.0 and your_app depends on firebase_core 1.0.3, firebase_crashlytics from git is forbidden.
So, because your_app depends on firebase_crashlytics from git, version solving failed.
```

**Comment by untp** [comment]
@deepak786 I created updated branch. You can try `obfuscated-stack-traces-updated`.
