### ISSUE TITLE
Push notification with large icon (user avatar)

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [FirebaseExtended/flutterfire#2645]
Hello guys, 

i cannot find a way how to set user avatar on push notifications (like in whatsup). I searched on stackoverflow and your docs and I am not sure if there is way.
It looks like for Java and react native you can do it like described here: https://stackoverflow.com/questions/54896754/fcm-push-notification-with-users-avatar

but not sure how to do it in flutter.
Can you provide any documentation on that or help?

**Comment by vytautas-pranskunas-** [comment]
Hello, any word on this one? I really would like to have it. And if I send image along with notification (no matter how small) it spears below message but not as avatar

**Comment by wlodzix** [comment]
Hi, do you manage to find any solution to this and somehow set avatar?

**Comment by vytautas-pranskunas-** [comment]
@wlodzix n, i did not. If you find it please tell me how :(

**Comment by russellwheatley** [comment]
I'm afraid this out of scope for the library, I'd research into other notification packages that might allow this advanced customisation.
