### ISSUE TITLE
[FIREBASE_AUTH] Consider strongly typing exceptions and/or returning results with errors

### ISSUE THREAD

**Issue by matthew-carroll** [FirebaseExtended/flutterfire#2653]
I'm working with email/password authentication. I see that this process can fail for a number of reasons, and those failures are expressed as `PlatformException`s with `code` `String`s.

This is cumbersome for multiple reasons:

 * Authentication is expected to have many possible failure cases. Treating these cases as "errors" or "exceptions" that need to be try/catch'ed is, in my opinion, an unnecessary hassle. An `AuthResult` is already being returned. Why not use that object to represent failures, too?
 * Representing the failure reason as a `String` makes it easy to introduce typos when handling failures. It also requires that each app project create an enum for this purpose, or re-type the `String` representation in multiple places.

At a minimum, I would recommend strongly typing all error cases instead of using `String`s. But I would also recommend considering a request/response paradigm that doesn't treat common cases, like a bad password, as a language-level error.

**Comment by Ehesp** [comment]
This is planned as part of https://github.com/FirebaseExtended/flutterfire/issues/2582

**Comment by Ehesp** [comment]
This is now handled in the rework, please see https://firebase.flutter.dev/docs/auth/error-handling for more information
