### ISSUE TITLE
[FIREBASE_AUTH]When the default FirebaseApp is not used, verifyPhoneNumber does not work

### ISSUE THREAD

**Issue by wds609** [FirebaseExtended/flutterfire#2656]
I use the api "firebaseAuth.verifyPhoneNumber" but it doesn't work.
The reason is that I configured FirebaseApp with custom FirebaseOptions and found that PhoneAuthProvider only uses the default FirebaseApp, not my custom FirebaseApp.
The bug code:
io.flutter.plugins.firebaseauth.FirebaseAuthPlugin#handleVerifyPhoneNumber
C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+5/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:244

```
  PhoneAuthProvider.getInstance()
          .verifyPhoneNumber(
              phoneNumber,
              timeout,
              TimeUnit.MILLISECONDS,
              registrar.activity(),
              verificationCallbacks);

PhoneAuthProvider.getInstance() only use the default FirebaseApp
```

**Comment by Ehesp** [comment]
@wds609 This should now be fixed in the latest version of auth. Closing - please let me know if you continue to have issues. Thanks!
