### ISSUE TITLE
[firebase_auth] sign in methods throw Error instead of Exception [WEB & iOS]

### ISSUE THREAD

**Issue by fourman-alex** [FirebaseExtended/flutterfire#2657]
**Describe the bug**
FirebaseAuth sign in methods throw Error instead of Exception.
for example `FirebaseAuth.signInWithEmailAndPassword`.
An Error is not expected to be caught in release code. 

[From Dart documentation](https://api.dart.dev/stable/2.8.3/dart-core/Error-class.html)
> An Error object represents a program failure that the programmer should have avoided.
> 
> Examples include calling a function with invalid arguments, or even with the wrong number of arguments, or calling it at a time when it is not allowed.
> 
> These are not errors that a caller should expect or catch - if they occur, the program is erroneous, and terminating the program may be the safest response.
> 

**To Reproduce**
**Reproducable on WEB** 
on Android works as expected
needs verification on iOS

1. Try signing in with `FirebaseAuth.signInWithEmailAndPassword(email, password)`. Use incorrect password.
2. An Error will be thrown `FirebaseError: The password is invalid or the user does not have a password. (auth/wrong-password)` 

**Expected behavior**
An `Exception` is the correct type to represent a failure that was meant to be caught.

**Additional context**
N/A

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by RobertBrunhage** [comment]
Noticed that it's throwing a PlatformException on Android but on Web and iOS it seems to just return the FirebaseError for me

**Comment by tomalabaster** [comment]
> **To Reproduce**
> **Reproducable on WEB**
> on Android works as expected
> needs verification on iOS

Can confirm it's working on iOS but not web:

Flutter version: 1.20.0-3.0.pre.80

firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.8"
  firebase_auth_web:
    dependency: transitive
    description:
      name: firebase_auth_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3+1"

**Comment by fourman-alex** [comment]
@TahaTesser  Can you take a second look? I think this is more of a bug then a feature because trying to catch an exception (even the most general one) will not catch the `Error` and catching an `Error` is discouraged.

**Comment by Ehesp** [comment]
Hey, this should now be fixed on the latest versions. Please see https://firebase.flutter.dev/docs/auth/error-handling

Closing - please let me know if you continue to have issues & I can reopen.
