### ISSUE TITLE
Hiding firebase config in index.html

### ISSUE THREAD

**Issue by bharathkv90** [FirebaseExtended/flutterfire#2658]
Is there any security risk by exposing the firebase config in the index.html file? Are there any alternative measures? The firebase config is being exposed in the browser by inspecting source code.

`<script src="https://www.gstatic.com/firebasejs/3.0.2/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: '<your-api-key>',
    authDomain: '<your-auth-domain>',
    databaseURL: '<your-database-url>',
    storageBucket: '<your-storage-bucket>'
  };
  firebase.initializeApp(config);
</script>
`

**Comment by Ehesp** [comment]
Nope, it's as intended: https://stackoverflow.com/a/37484053/11760094
