### ISSUE TITLE
app crease after use flutter 1.17.1 in android in reales mode

### ISSUE THREAD

**Issue by Ahmedtaha123** [FirebaseExtended/flutterfire#2659]
**i'm useing
firebase_auth: ^0.16.1
cloud_firestore: ^0.13.6
firebase_messaging: ^6.0.16
and i use flutter 1.17.1 and app working fine in debug mode but after using reales mode app crashing when use cloud_firestore code in flutter any help
this is my android/build.gradle**
```
buildscript {
    ext.kotlin_version = '1.3.10'
    repositories {
        google()
        jcenter()
        mavenLocal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenLocal()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
**and this is my android/app/build.gradle**
`
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.myapp"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
    }

    buildTypes {
        release {
            //shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.release
            //minifyEnabled false            
        }
        /*debug{
            minifyEnabled false
        }*/
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    //implementation 'com.android.support:multidex:1.0.3'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by Ehesp** [comment]
Whats the error?

**Comment by Ahmedtaha123** [comment]
> Whats the error?

how i can get the error when i run app in reales mode in android
and nothing print in console

**Comment by TahaTesser** [comment]
Hi @Ahmedtaha123 
Can you please provide your `flutter doctor -v`, your `flutter run  --release --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by Ahmedtaha123** [comment]
i run flutter doctor -v and this is result

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.1 19B88, locale en-EG)
    • Flutter version 1.17.1 at /users/dell/desktop/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dell/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPad • 4a5c1dc1e2024c618604a3b9f8f9d55e73592c5c • ios • iOS 12.4.5

• No issues found!

**Comment by TahaTesser** [comment]
Hi @Ahmedtaha123 
Please provide more information asked in earlier [comment](https://github.com/FirebaseExtended/flutterfire/issues/2659#issuecomment-635430912)

**Comment by Ahmedtaha123** [comment]
after i update macos to macos catalina 10.15.5 and xcode to xcode 11.5 it's work good no crash
in android but in ios when i left the screen contains cloudstore code the app crash in ios reales mode

**Comment by Ahmedtaha123** [comment]
app not crash after update macos to macos catalina 10.15.5 and xcode to xcode 11.5
