### ISSUE TITLE
Dynamic Links  The plugin does not work if the flutter application is compiled for web

### ISSUE THREAD

**Issue by dirugec** [FirebaseExtended/flutterfire#2660]
I compiled my flutter project for web and I have it hosted on a server, the application runs fine but the flutter dynamiclinks plugin doesn't work.

any suggestion ?? or a next improvement of the complement?

**Comment by TahaTesser** [comment]
Hi @dirugec 
Dynamic links is for iOS and Android only
Closing, as this isn't an issue. If you disagree, please write in the comments and I will reopen it.
Thank you"
