### ISSUE TITLE
Unable to log event: analytics library is missing

### ISSUE THREAD

**Issue by NSO-Elturki** [FirebaseExtended/flutterfire#2663]
Hello everyone, in FCM I can not get notification onMessage in Android device but in IOS everything works good. Every time I send notification on foreground I get this message "Unable to log event: analytics library is missing" but if I send the notification and the app is in background it works. Do anyone knows have to fix this issue ?

**Comment by TahaTesser** [comment]
Hi @NSO-Elturki 
Running the official [example](https://pub.dev/packages/firebase_messaging#-example-tab-) on Android 
```
I/flutter (31533): onMessage: {notification: {title: test, body: thanos}, data: {}}

```
Make sure you've the following dependencies and `firebase_messaging: ^6.0.16`
```
dependencies {
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-messaging:20.1.7'
}
apply plugin: 'com.google.gms.google-services'

```

Thank you

**Comment by ghenry** [comment]
Shouldn't this be mentioned in the firebase_messaging README?

https://pub.dev/packages/firebase_analytics#-readme-tab-

**Comment by ralmarri12** [comment]
> Hi @NSO-Elturki
> Running the official [example](https://pub.dev/packages/firebase_messaging#-example-tab-) on Android
> 
> ```
> I/flutter (31533): onMessage: {notification: {title: test, body: thanos}, data: {}}
> ```
> 
> Make sure you've the following dependencies and `firebase_messaging: ^6.0.16`
> 
> ```
> dependencies {
>     def multidex_version = "2.0.1"
>     implementation "androidx.multidex:multidex:$multidex_version"
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     implementation 'com.google.firebase:firebase-analytics:17.2.2'
>     implementation 'com.google.firebase:firebase-messaging:20.1.7'
> }
> apply plugin: 'com.google.gms.google-services'
> ```
> 
> Thank you

for me I'm facing the same problem now and your solution is not meant to solve the problem, I don't want to include firebase analytics. And it is working in another app I have perfectly without need of firebase analytics to be included. Anyway I will update this post when I recognise my mistake.
