### ISSUE TITLE
[Firestore] App slow performance issue

### ISSUE THREAD

**Issue by expertdevs** [FirebaseExtended/flutterfire#2669]
We are developing an flutter app (Pixz:- [android](https://play.google.com/store/apps/details?id=pixz.io.pixz) & [iOS](https://apps.apple.com/us/app/pixz-group-event-photos/id1491306184?ls=1)) and everything works fine except the firestore queries. When we launch the app for the first time everything is smooth and run fine but after a while firestore queries jams the app. Simple save query takes 5 minutes to execute. See query below

---SAVE QUERY---
```
Firestore.instance.collection('Groups').document(groupID).setData({
  'id': groupID,
  'created_by': currentUser.uid,
  'title': titleText.text,
  'description': descriptionText.text,
  'isPrivate': true,
  'status': 1,
  'created_at': DateTime.now().millisecondsSinceEpoch,
  'updated_at': DateTime.now().millisecondsSinceEpoch,
  }).then((response) {
     print('success);
  }).catchError((error) {
     print('error);
  });
```
I upgraded to latest packages see below versions of Packages and also upgraded Flutter to latest stable version but no luck.

---VERSIONS---

firebase_auth: ^0.16.0
firebase_storage: ^3.1.5
cloud_firestore: ^0.13.5
firebase_messaging: ^6.0.13
firebase_remote_config: ^0.3.0+3
firebase_crashlytics: ^0.1.3+3
firebase_analytics: ^5.0.11
I read online about disabling the offline persistence but firestore package has deprecated the use.

Kindly suggest if someone has gone through similar problem.

[Video URL (Save Query Issue)](https://firebasestorage.googleapis.com/v0/b/pixz-92afa.appspot.com/o/Issues%2FScreen%20Recording%202020-05-29%20at%201.58.59%20PM.mov?alt=media&token=84e7be7f-aa08-44f9-98f7-c7e49f058aa5)

**Comment by Ehesp** [comment]
There's a number of reasons this may happen. Would you be able to debug it on the Native side? Does the slow-query actually happen when executing? Also are there any logs?

**Comment by expertdevs** [comment]
Not, I only debugged flutter code , Yes when query execute the response time is very slow even It also take more time to getting the Document Snapshot and Query Snapshot. Logs are available in video.

**Comment by Ehesp** [comment]
Yes but could you debug it on native please?

**Comment by expertdevs** [comment]
Hi @Ehesp  I debugged the native code and found that the following method is where it's taking time. Kindly suggest if I need to dig more.

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/55388809/83599799-ba6d0c00-a58a-11ea-84b9-84211fba8895.png">


 ```
private void addDefaultListeners(final String description, Task<Void> task, final Result result) {
    task.addOnSuccessListener(
        new OnSuccessListener<Void>() {
          @Override
          public void onSuccess(Void ignored) {
            result.success(null);
          }
        });
    task.addOnFailureListener(
        new OnFailureListener() {
          @Override
          public void onFailure(@NonNull Exception e) {
            result.error("Error performing " + description, e.getMessage(), null);
          }
        });
  }
```

**Comment by expertdevs** [comment]
Was problem in code. Firestore doesn't have any problem.

**Comment by Jethro87** [comment]
@expertdevs I'm facing a similar problem, of very long firestore queries. Would you mind letting me know what the problem in your code was, so I can better track down this issue? Cheers.

**Comment by Ehesp** [comment]
Please create a new issue, with the exact query, sample document you're querying against and also let us know about the amount of documents in the DB and expected to be returned.
