### ISSUE TITLE
firebase_storage upload in background

### ISSUE THREAD

**Issue by syonip** [FirebaseExtended/flutterfire#2670]
**Is your feature request related to a problem? Please describe.**
Uploading large files (such as video files) could take a long time. Right now if the app is put in the background while an upload is running, it can close and stop the upload.

**Describe the solution you'd like**
I would like the upload process to continue running when the app is in the background / closed.

**Comment by Techno-Disaster** [comment]
@syonip were you able to find a workaround? I'm planning to use [flutter_uploader](https://pub.dev/packages/flutter_uploader) with this. 

cc : @TahaTesser

**Comment by syonip** [comment]
@Techno-Disaster Yeah I'm just writing a blog post about a workaround using cloud functions to generate an upload url.
Full guide should be done soon, here is the gist of it in the meanwhile:
![flutter_fbstorage_background_upload](https://user-images.githubusercontent.com/5416329/97833558-5045c800-1cde-11eb-909d-803d2466bfe6.jpg)

**Comment by Techno-Disaster** [comment]
> @Techno-Disaster Yeah I'm just writing a blog post about a workaround using cloud functions to generate an upload url.
> Full guide should be done soon, here is the gist of it in the meanwhile:
> ![flutter_fbstorage_background_upload](https://user-images.githubusercontent.com/5416329/97833558-5045c800-1cde-11eb-909d-803d2466bfe6.jpg)
> 
> Edit: you can read the full guide here: https://medium.com/@syonip/background-video-upload-to-firebase-storage-with-flutter-ee398b796656
> 
> Source: https://github.com/syonip/flutter_fbstorage_background_upload

ah thanks a lot man, I'm implementing something similar for images this is really helpful 💙

**Comment by rlee1990** [comment]
@TahaTesser any updates on this?
