### ISSUE TITLE
[firebase_admob] Add support to mute video ads

### ISSUE THREAD

**Issue by dymx101** [FirebaseExtended/flutterfire#2673]
**Is your feature request related to a problem? Please describe.**
My app is a video app, when the video ads shows while video is playing, it's annoying.

**Describe the solution you'd like**
If it's possible please provide `setMute` function to the MobleAd class

**Comment by M1123581E** [comment]
we also need it!

**Comment by DanielSjtea** [comment]
Would be a great improvement to the package!!

**Comment by fleoparra** [comment]
Yes, I need it too!!

**Comment by uzumaki258** [comment]
I hope we will have this feature soon!

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
