### ISSUE TITLE
FCM not working in flutter v1.12.13

### ISSUE THREAD

**Issue by ziasultan2** [FirebaseExtended/flutterfire#2676]
FCM is not showing in real device as well as simulator after updating flutter version to V1.12.13 hotfix 9 but it's coming to device and printing fcm message on android studio console

**Comment by TahaTesser** [comment]
Hi @ziasultan2 
Please upgrade to `(Channel stable, v1.17.2` and `firebase_messaging: ^6.0.16`
**After upgrade** Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you
