### ISSUE TITLE
Failed installation - nothing has appeared in firebase console 

### ISSUE THREAD

**Issue by nausharipov** [FirebaseExtended/flutterfire#2678]
The GoogleService-Info.plist file is in iOS folder (previously it was in Runner folder, and firebase messaging works in both cases), 
firebase_crashlytics: ^0.1.3+3 is in pubspec.yaml, 
added buildphase script with and without info.plist path
and added Crashlytics.instance.enableInDevMode = true; and FlutterError.onError = Crashlytics.instance.recordFlutterError; into main.dart,
and finished the Android installation as instructed,
launched the iOS app on real device

but "Add the SDK, then build and run your app" is still shown in the firebase console in both android and iOS. 
Have I done something wrong or what?

flutter doctor --verbose
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.17.2 at /Users/admin/dev/flutter
    • Framework revision 5f21edf8b6 (3 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone • ... • ios • iOS 13.5

**Comment by TahaTesser** [comment]
Hi @nausharipov 
Did you create an app id and new firebase app?
Make sure the app id matches with firebase's app id

and place plist here using xcode,  import Firebase and configure()

<img width="273" alt="Screenshot 2020-06-02 at 7 04 44 PM" src="https://user-images.githubusercontent.com/48603081/83527123-fd849c00-a504-11ea-8ae7-3e8a916fe65b.png">

Also add this to `AppDelegate.swift`
```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

and uninstall previous version and install the app
Thank you
