### ISSUE TITLE
cloud_Firestore store query returns null when the app is used in a different time zone : Flutter

### ISSUE THREAD

**Issue by momo1606** [FirebaseExtended/flutterfire#2685]
I have developed an app in UAE(GMT +4 gulf standard time). When the following query is executed with system time zone being as mentioned above , i get the required data. When the app is used in a different country or if i change my system time to a different time zone(i changed it to GMT+5:30 Indian standard time), the query returns null and i get an error when extracting the data.

```
Future getdetails() async {
  DateTime dt=DateTime.now().toUtc();
  QuerySnapshot r = await Firestore.instance.collection('maqarat_male').
  where('date',isEqualTo: Timestamp.fromDate(DateTime(dt.year,dt.month,dt.day))).getDocuments();

  print(r.documents[0].documentID);
  return r;

}
```

Data is present in cloud firestore no matter what time is fetched using DateTime.now().
Even if I use DateTime.now().toUtc() i get the same error.

i also queried the above using static values instead of DateTime generated values.

```
Future getdetails() async {
  //DateTime dt=DateTime.now().toUtc();
  QuerySnapshot r = await Firestore.instance.collection('maqarat_male').
  where('date',isEqualTo: Timestamp.fromDate(DateTime(2020,6,2))).getDocuments();

  print(r.documents[0].documentID);
  return r;

}
```
now with my system time being set to time zone GMT+4 i get the data and am able to execute the print statement
![image](https://user-images.githubusercontent.com/47382068/83521718-ad9bda00-a4f0-11ea-9ab0-c0eeae6a370e.png)
 
and after changing my system time to a different timezone(this time GMT+3 Arabian Standars Time) i ran across this error while executing the same function.

![image](https://user-images.githubusercontent.com/47382068/83522070-2d29a900-a4f1-11ea-80ad-1562a40bc3af.png)

Is the issue with the cloud_function package? i am using cloud_firestore: ^0.13.5

i could also create a document in firestore with any time zone.
So the problem is with the read operations.

these are the logs

```
E/flutter ( 9032): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter ( 9032): #0      List.[] (dart:core-patch/growable_array.dart:146:60)
E/flutter ( 9032): #1      getdetails (package:mahadalzahra/main.dart:96:20)
E/flutter ( 9032): <asynchronous suspension>
E/flutter ( 9032): #2      MyApp.build (package:mahadalzahra/main.dart:104:5)
E/flutter ( 9032): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
E/flutter ( 9032): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
E/flutter ( 9032): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter ( 9032): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter ( 9032): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 9032): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 9032): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 9032): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
E/flutter ( 9032): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
E/flutter ( 9032): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
E/flutter ( 9032): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
E/flutter ( 9032): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
E/flutter ( 9032): #15     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
E/flutter ( 9032): #16     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
E/flutter ( 9032): #17     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 9032): #18     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 9032): #19     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 9032): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 9032): #21     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 9032): #22     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 9032): #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 9032): #24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 9032): #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 9032): #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 9032): #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 9032): 
E/flutter ( 9032): [ERROR:flutter/shell/common/shell.cc(213)] Dart Error: Unhandled exception:
E/flutter ( 9032): RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter ( 9032): #0      List.[] (dart:core-patch/growable_array.dart:146:60)
E/flutter ( 9032): #1      getdetails (package:mahadalzahra/main.dart:96:20)
E/flutter ( 9032): <asynchronous suspension>
E/flutter ( 9032): #2      MyApp.build (package:mahadalzahra/main.dart:104:5)
E/flutter ( 9032): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
E/flutter ( 9032): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
E/flutter ( 9032): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter ( 9032): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
E/flutter ( 9032): #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
E/flutter ( 9032): #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
E/flutter ( 9032): #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
E/flutter ( 9032): #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
E/flutter ( 9032): #11     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
E/flutter ( 9032): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 9032): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 9032): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 9032): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by TahaTesser** [comment]
Hi @momo1606 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Please refrain from screenshots if not needed
Thank you"

**Comment by momo1606** [comment]
> Hi @momo1606
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
> Please refrain from screenshots if not needed
> Thank you"

C:\Users\G5\AndroidStudioProjects\akhul_qurani>flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17763.1217], locale en-US)
    • Flutter version 1.17.1 at C:\flutter\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2





C:\Users\G5\AndroidStudioProjects\akhul_qurani>
C:\Users\G5\AndroidStudioProjects\akhul_qurani>flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17763.1217], locale en-US)
    • Flutter version 1.17.1 at C:\flutter\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\G5\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\JetBrains\IntelliJ IDEA 2018.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\G5\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.




C:\Users\G5\AndroidStudioProjects\akhul_qurani>flutter run --verbose
[  +19 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +55 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[   +1 ms] executing: [C:\flutter\flutter/] git tag --contains HEAD
[ +188 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.1
[   +8 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +94 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] executing: C:\Users\G5\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +40 ms] List of devices attached
[   +2 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +48 ms] No supported devices connected.
[  +14 ms] "flutter run" took 226ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///C:/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by momo1606** [comment]
> Hi @momo1606
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
> Please refrain from screenshots if not needed
> Thank you"

Code- this is what i executed for test purpose



`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:mahadalzahra/homepage.dart';
import 'package:flutter/services.dart';
import 'package:mahadalzahra/splash_screen.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(new MyApp());
  });
}

Future getdetails() async {
  DateTime dt=DateTime.now().toUtc();
  QuerySnapshot r = await Firestore.instance.collection('maqarat_male').
  where('date',isEqualTo: Timestamp.fromDate(DateTime(dt.year,dt.month,dt.day))).getDocuments();

  print(r.documents[0].documentID);
  return r;

}
class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context){
    getdetails();
    return MaterialApp(
      title: 'AlAkhul Qurani',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: Color(0xFFFFFFFF),
        primaryColor: Color(0xFF003CE7),
      ),
      home: SplashScreen(),
    );

  }

}
`

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (31 hours ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPhone 11  • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.5 19F96
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by greghesp** [comment]
@momo1606 

Ive tested this with the rework that is currently [in progress](https://github.com/FirebaseExtended/flutterfire/issues/2582)

When you pass `isEqualTo: Timestamp.fromDate(DateTime(dt.year,dt.month,dt.day)))`, it creates a timestamp at the start of that day such as `2020-07-13 00:00:00.000`.   

As you're using "isEqualTo" it's looking for that exact timestamp.

If you want to get all documents for the whole day, you need to use multiple where statements like so

```
QuerySnapshot querySnapshot = await Firestore.instance.collection('myCollection')
    .where('createdAt', isGreaterThanOrEqualTo: Timestamp.fromDate(DateTime(dt.year, dt.month, dt.day)))
    .where('createdAt', isLessThanOrEqualTo: Timestamp.fromDate(DateTime(dt.year, dt.month, dt.day + 1)))
    .getDocuments();
```
