### ISSUE TITLE
Firebase Cloud Messaging(FCM) : push Notifications are working in android perfectly following the docs but in IOS receiving message only when app is in foreground but when the app is in background or terminated,not receiving any message in onLaunch or on onResume callback,instead when i open the app getting the message .

### ISSUE THREAD

**Issue by praveen-francium** [FirebaseExtended/flutterfire#2695]
I am trying to send notifications from firebase cloud messaging to IOS Simulator but i am not receiving notification when app is in background or terminated and receiving the message only when it is in foreground.i.e onResume() and onLaunch() are getting message and onMessage alone is receiving message.

To Reproduce

Created APNs Auth Key and Configured in Firebase

Enabled Capabilities:

1. - Push Notifications
2. - Background Mode (Background Fetch and Remote Notifications)

Attached the output of flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!
```

### **Pubspec.yaml**
```
firebase_messaging: ^6.0.16
firebase_auth: ^0.16.0
```

**Comment by praveen-francium** [comment]
@daikini please give suggestion regarding this

**Comment by praveen-francium** [comment]
Can anyone help me regarding this issue?

**Comment by whatamelon** [comment]
same issue

**Comment by iapicca** [comment]
Hi @praveen-francium 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1799) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
