### ISSUE TITLE
[remote_config] macOS Support

### ISSUE THREAD

**Issue by AndroidNils** [FirebaseExtended/flutterfire#2697]
Currently there is no support for Flutter macOS

Remote Config is a Key firebase feature that should be cross platform supported.

**Comment by EliasDeuss** [comment]
@cbenhagen Any chance you have time to work on this?

**Comment by Salakar** [comment]
MacOS support for Remote Config has landed on master and a pre-release is available, so I'm going to go ahead and close this issue now, thanks everyone!

https://firebase.flutter.dev/docs/remote-config/overview
