### ISSUE TITLE
[FirebaseMLCommon] Undefined symbols for ios builds

### ISSUE THREAD

**Issue by bradd-pktlzyer** [FirebaseExtended/flutterfire#2702]
**Describe the bug**
Using FirebaseMLKit in a flutter project causes a link error. Reference [FirebaseMLCommon ios sdk #5744](https://github.com/firebase/firebase-ios-sdk/issues/5744).

**To Reproduce**
1. flutter build ios --debug
2. See error or incorrect behavior

```
Undefined symbols for architecture x86_64:
  "_GPBClearOneof", referenced from:
      _FBMLx_CLCCCounter_ClearCounterIdOneOfCase in FirebaseMLCommon(Counters.pbobjc_734172a066036ea5b86df252f1620848.o)
ld: symbol(s) not found for architecture x86_64
```

**Expected behavior**
Expecting to build and link without error.

**Additional context**
Reported on ios sdk [FireabaseMLCommon](https://github.com/firebase/firebase-ios-sdk/issues/5744), Podfile and Pod spec are listed in that bug as well. Please let me know if there is any additional info you need.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by paulb777** [comment]
The specific flutter issue is https://github.com/firebase/firebase-ios-sdk/issues/5744#issuecomment-639212080

**Comment by iapicca** [comment]
Hi @bradd-pktlzyer 
are you implementing firebaseML on native side or you are using [firebase_ml_vision](https://pub.dev/packages/firebase_ml_vision)?
Could you please provide your `flutter run --verbose` 
and your `pubspec.yaml`. 
Thank you

**Comment by bradd-pktlzyer** [comment]
@iapicca I am using firebase_ml_vision, better yet, i was able to get a flutter demo app to reproduce the issue, here is the [repo](https://github.com/bradd-pktlzyer/ml_error_demo), let me know if you need anything else

**Comment by qimingweng** [comment]
Seeing this issue as well. This seems pretty severe.

**Comment by russellwheatley** [comment]
Hey @bradd-pktlzyer, are you still seeing this issue? This was a while ago and a number of the underlying sdks have since had major updates.

**Comment by russellwheatley** [comment]
The underlying issue appears fixed on the firebase ios sdk. Will reopen if this is not the case.
