### ISSUE TITLE
firebase_ml_vision to support  RM4SCC Barcode 

### ISSUE THREAD

**Issue by kw2019ltd** [FirebaseExtended/flutterfire#2703]
firebase_ml_vision to support  RM4SCC Barcode 

https://www.activebarcode.com/codes/royalmail.html

**Comment by iapicca** [comment]
Hi @kw2019ltd 
this format doesn't seem to be supported by [firebase ml kit](https://firebase.google.com/docs/ml-kit/read-barcodes) from which [firebase_ml_vision](https://pub.dev/packages/firebase_ml_vision) depends on. 

Please see https://firebase.google.com/support for this type of request.

Closing, as this isn't an issue with FlutterFire itself. If you disagree, please write in the comments and I will reopen it.
Thank you
