### ISSUE TITLE
Firebase Authentication - Proxy support

### ISSUE THREAD

**Issue by john-yick** [FirebaseExtended/flutterfire#271]
**Is your feature request related to a problem? Please describe.**
Firebase Auth does not work within countries that restrict access to google.com such as China.

**Describe the solution you'd like**
Ability to add proxy support within the GoogleServices-info.plist to redirect traffic to a non-blocked proxy which could forward traffic onto the Google service.

**Additional context**
N/A

**Comment by Ehesp** [comment]
Hello - this issue is out of the hands of these plugins. Please create a ticket over at https://firebase.google.com/support/ where Firebase can help.
