### ISSUE TITLE
Firebase Messaging, implemneted android fix for silent messages being dropped.

### ISSUE THREAD

**Issue by rydal** [FirebaseExtended/flutterfire#2720]
**Is your feature request related to a problem? Please describe.**
Messages on android being dropped quietly.

**Describe the solution you'd like**
I've written an android service to put the messages in a database for the application to read when it is launched. This could be turned into a package,

**Additional context**
https://github.com/rydal/fluttergetmessages/

**Comment by TahaTesser** [comment]
Hi @rydal 
You can publish it as package, since this isn't flutterfire issue

I feel safe to close this issue, if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by rydal** [comment]
Hi Taha.

I would publish it as a package but that would require database configuration by the developer.  Leaving it here for reference by others.

Thanks.
