### ISSUE TITLE
[firebase_auth] this request is missing a recaptcha token

### ISSUE THREAD

**Issue by sooxt98** [FirebaseExtended/flutterfire#2722]
It only happens on some phone
![image](https://user-images.githubusercontent.com/13378059/83992484-0fda5c00-a983-11ea-8580-bbe3ceb0c6f2.png)

**Comment by sooxt98** [comment]
I found out it's because Huawei HMS
![image](https://user-images.githubusercontent.com/13378059/83997167-5da99100-a990-11ea-9ae8-cf2e662bac4a.png)

**Comment by Ehesp** [comment]
Hello - please try upgrading to the latest version of auth. If you continue to have more device specific issues, I'd advise raising an issue on the Android SDK repo: https://github.com/firebase/firebase-android-sdk
