### ISSUE TITLE
Plugin project :firebase_core_web not found. Please update settings.gradle. Plugin project :cloud_firestore_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by 12amansharma** [FirebaseExtended/flutterfire#2727]
in dependencies
cloud_firestore: ^0.13.6
permission_handler:` ^5.0.0+hotfix.9
firebase_core: ^0.4.5

**Comment by TahaTesser** [comment]
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2599

**Comment by akashdusky** [comment]
did u figure out ?

**Comment by hkmr** [comment]
Hi @12amansharma, Did you find the solution ?

**Comment by 12amansharma** [comment]
Yes I did just go to #2599 and follow instructions there.
