### ISSUE TITLE
firebase_auth: ^0.16.0 production Crash on android

### ISSUE THREAD

**Issue by niypoo** [FirebaseExtended/flutterfire#2730]
That I got it in Crashlytics 

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void k.b.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
```

it's happened 2 times on
Android  9

```
io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged (FirebaseAuthPlugin.java:45)
com.google.firebase.auth.zzp.run (zzp.java:24)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage (zzj.java)
android.os.Looper.loop (Looper.java:226)
android.app.ActivityThread.main (ActivityThread.java:7191)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:942)
```

and  happened 2 times on
Android  7.1.1

```
io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged (FirebaseAuthPlugin.java)
com.google.firebase.auth.zzp.run (zzp.java)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage (zzj.java)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6816)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1565)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1453)
```
<img width="1412" alt="Screen Shot 2020-06-09 at 2 00 58 PM" src="https://user-images.githubusercontent.com/13227239/84145219-c577de80-aa59-11ea-98e2-8a2b008a5b47.png">
<img width="1412" alt="Screen Shot 2020-06-09 at 2 00 32 PM" src="https://user-images.githubusercontent.com/13227239/84145222-c741a200-aa59-11ea-87bb-b1e769acef52.png">

**Comment by niypoo** [comment]
I have created an issue in flutter but I have added in flutter not here so I have added it in wrong place 
https://github.com/flutter/flutter/issues/58859

**Comment by hweiguang** [comment]
I am having this issue as well during my development and this only happens on Android. I am able to replicate the crash by the following steps.

1. Launch an app with a Google Sign In button.
2. Press the back button on the device. (Exiting the app via the home button will not crash)
3. The app should exit.
4. Open the app again.
5. Sign in with Google.
6. App crashes.

**Comment by matthewrice345** [comment]
This is happening on 0.16.1 as well.

**Comment by roughike** [comment]
Related to #2608.

There are two separate open PRs that seem to fix this:
* #2719 
* #2605

(`cloud_firestore` had a similar issue, #2517, that was fixed by #2733.)

**Comment by noinskit** [comment]
Friendly ping? These two open PRs have been idle for two weeks.

**Comment by noinskit** [comment]
Another ping? It's been over a month...

**Comment by cubuspl42** [comment]
There's a newer bug, that probably should've been closed as a duplicate:
https://github.com/FirebaseExtended/flutterfire/issues/2886

It's already closed, because the devs state that this will be fixed in the upcoming rework.

**Comment by jvidalorozco** [comment]
same problem 
I'll try to downgrade the version and hope it works

**Comment by dleyvac** [comment]
@jvidalorozco did it work?

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration

**Comment by joniaiuser** [comment]
@Salakar We have this set of plugins deployed in our production app and this error has appeared in our Crashlytics logs.

  #firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_analytics: ^6.0.0
  firebase_remote_config: ^0.4.0
  firebase_crashlytics: ^0.2.0-dev.5
  firebase_messaging: ^7.0.0
  firebase_performance: ^0.4.0
  firebase_dynamic_links: ^0.6.0

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin$3.onCodeAutoRetrievalTimeOut(FlutterFirebaseAuthPlugin.java:828)
       at com.google.firebase.auth.api.internal.zzfk.zza(zzfk.java:2)
       at com.google.firebase.auth.api.internal.zzfm.run(zzfm.java:4)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`
