### ISSUE TITLE
Ios app get previous token FCM version

### ISSUE THREAD

**Issue by Brax97** [FirebaseExtended/flutterfire#2738]
**Describe the bug**
**Only on iOS**, notifications are not displayed after installing, uninstalling and reinstalling the application.
This problem is caused by the fact that the build token is taken first when the application is started.
If the build were redone without uninstalling the app, the notifications would work again.
Because precisely the token is updated to the right version and no longer in the canceled one.

**To Reproduce**
1. Install application
2. Uninstall application
3. Reinstall application
4. Now there is the previous token FCM
5. If you reinstall application withouth uninstalling application it works

**Expected behavior**
I would like the token to be updated to the right version without having to install the application twice.

**Flutter doctor**
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F101, locale it)
    • Flutter version 1.17.1 at /Users/brian/Development/flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/brian/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/brian/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone di Brian  • 00008020-000E790E0A04002E • ios • iOS 13.4.1

• No issues found!
Process finished with exit code 0

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
