### ISSUE TITLE
confirmPasswordReset() is not implemented (web platform)

### ISSUE THREAD

**Issue by mark-zs** [FirebaseExtended/flutterfire#2742]
Any plans to implement this please?  Any suggested workaround?
Thanks!

**Comment by TahaTesser** [comment]
Looks like this is addressed [here](https://github.com/FirebaseExtended/flutterfire/issues/2582#issuecomment-631501764)

**Comment by Ehesp** [comment]
Closing - PR linked and will be released soon.
