### ISSUE TITLE
[<CLOUD FIRESTORE>] <Flutter Web Profile / Release Blob minified issue>

### ISSUE THREAD

**Issue by ssilverstein** [FirebaseExtended/flutterfire#2747]
**Describe the bug**

When making use of the Blob type to create a document field in Cloud Firestore, Flutter Web "profile" and "release" are unable to properly retrieve and read the document Blob field.

**To Reproduce**
1. Go to Firebase Console and create new project
2. Enable Database Cloud Firestore
3. Create new Fluter project
4. Add flutter web application to Firebase Project, retrieve config
5. Add config script to web/index.html
6. Add script CDN for firestore
7. import Cloud Firestore in pub.spec
8. Create an empty collection in Firebase Console.
9. Flutter app add document to cloud with a Blob as field value in Map<String, dynamic>
10. Flutter App get or snapshot document from firebase
11. access Blob field bytes
12. See error or incorrect behavior

**Expected behavior**
Expect to be able to retrieve and access Blob type from Firestore and make use of Blob bytes without error as in Andriod / iOS Debug / Profile / Release and Web debug.

**Additional context**

Flutter Web profile reads Blob object type as Instance of 'GeoPoint' and release as instance of 'minified' both unable to access the .bytes field of the Blob type

Web applications in Profile or release build can continue to write Blob fields to the firestore database. When application is run in debug mode application is able to read blobs written in profile or release mode properly.

When looking a web console for js_primitives - 

Could not load content for org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_primitives.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

Flutter Web Debug Mode - Expected Behavior in all modes
![flutter web debug](https://user-images.githubusercontent.com/50643964/84430176-216b7000-abde-11ea-8779-9c042d6a81c3.png)

Flutter Web Profile Mode - Blob returned as 'GeoPoint' bytes toString is null
![flutter web profile](https://user-images.githubusercontent.com/50643964/84430191-27f9e780-abde-11ea-8d7c-f4a95e2a2bb6.png)

Flutter Web Release Mode - Blob return as minified bytes toString is null
![flutter web release](https://user-images.githubusercontent.com/50643964/84430211-2f20f580-abde-11ea-9705-21c18020e4ab.png)

Firestore Document field is type blob in Firebase console
![firestore documnet blob field](https://user-images.githubusercontent.com/50643964/84430850-2977df80-abdf-11ea-906e-a3c56a2d4480.png)

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    ! CocoaPods 1.6.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.0)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.

```

**Comment by iapicca** [comment]
Hi @ssilverstein 
this issue appears to be the same as the one you [linked](https://github.com/FirebaseExtended/flutterfire/issues/2020) 
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
