### ISSUE TITLE
[cloud-functions] FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing

### ISSUE THREAD

**Issue by ronaldG19** [FirebaseExtended/flutterfire#2749]
I deployed my functions but I cannot start the app again even in release mode...

**Error**
Debugger attached.
Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail

**Initialized the following at the top of my index.js file**
```JavaScript
const functions = require('firebase-functions');
const admin = require("firebase-admin");
admin.initializeApp();
```

**Flutter doctor**
```Dart
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)
```

**NodeJS Version**
v8.17.0
**Firebase Version**
8.4.2

**Comment by iapicca** [comment]
Hi @ronaldG19 
the issue you are describing doesn't seems to involve flutterfire's [plugins](https://github.com/FirebaseExtended/flutterfire#available-flutterfire-plugins)
Closing, as this isn't an issue with Flutter itself. 
If you disagree, 
please run `flutter upgrade -f`
and provide your  updated`flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml`, 
a minimal reproducible code sample.
and I will reopen it.
Thank you
