### ISSUE TITLE
webdev doesn't recognize that firebase_auth is now supported for flutter_web

### ISSUE THREAD

**Issue by dhianabli** [FirebaseExtended/flutterfire#2750]
I get this build error whenever I try to build my flutter web project

**webdev could not run for this project.
You have a dependency on `firebase_auth` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.**

the firebase_auth plugin works fine on web when I run the app. Now that the firebase_auth plugin works on web and there is no need to import firebase_auth_web how can the dependency builder recognize that it is now supporting the web ?

**Comment by iapicca** [comment]
Hi @dhianabli 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`
and your `pubspec.yaml`. 
Thank you

**Comment by dhianabli** [comment]
**flutter doctor -v**
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /home/spectrum/development/flutter
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/spectrum/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

**flutter run --verbose**
[  +11 ms] executing: [/home/spectrum/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2738a1148ba6c9a6114df62358109407c3ef2553
[        ] executing: [/home/spectrum/development/flutter/] git tag --contains HEAD
[ +160 ms] Exit code 0 from: git tag --contains HEAD
[   +5 ms] 1.18.0-11.1.pre
[  +15 ms] executing: [/home/spectrum/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/spectrum/development/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] executing: [/home/spectrum/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +60 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: /home/spectrum/Android/Sdk/platform-tools/adb devices -l
[  +83 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +59 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +55 ms] Web Server • web-server • web-javascript • Flutter Tools
[   +1 ms] Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
[  +13 ms] "flutter run" took 246ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:334:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:777:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1192:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#30     _rootRun (dart:async/zone.dart:1184:13)
#31     _CustomZone.run (dart:async/zone.dart:1077:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**pubspec.yaml**

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.7.0
  dots_indicator: ^1.0.0
  timeago: ^2.0.26
  intl: ^0.16.1
  enum_to_string: ^1.0.9
  carousel_slider: ^2.1.0
  google_fonts: ^0.3.10
  url_launcher: ^5.4.2
  url_launcher_web: ^0.1.0
  google_maps: ^3.4.1
  flutter_typeahead: ^1.8.0
  fleva_icons: ^1.0.2
  string_validator: ^0.1.4
  provider: ^4.0.5
  fluttertoast: ^4.0.1
  rxdart: ^0.24.0
  image_picker_web: ^1.0.9
  #image_picker: ^0.6.7
  #image_picker_for_web: ^0.1.0
  introduction_screen: ^1.0.8
  mapbox_search: ^2.0.0
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/image0.jpg
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/image6.jpg
    - assets/images/user0.jpg
    - assets/images/user1.jpg

**Comment by dhianabli** [comment]
I am getting the error whenever I trigger a push build with codemagic

**Comment by iapicca** [comment]
Hi @dhianabli 
please make sure to specify the device
`[ +59 ms] More than one device connected; please specify a device with the '-d ' flag, or use '-d all' to act on all devices.`
Thank you

**Comment by dhianabli** [comment]
**flutter run --verbose -d chrome**
[  +12 ms] executing: [/home/spectrum/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2738a1148ba6c9a6114df62358109407c3ef2553
[        ] executing: [/home/spectrum/development/flutter/] git tag --contains HEAD
[ +184 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.18.0-11.1.pre
[  +10 ms] executing: [/home/spectrum/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/spectrum/development/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/home/spectrum/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +63 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: /home/spectrum/Android/Sdk/platform-tools/adb devices -l
[  +55 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Changing current working directory to: /home/spectrum/StudioProjects/startupcreators
[ +200 ms] Found plugin cloud_firestore at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.6/
[  +10 ms] Found plugin cloud_firestore_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[  +22 ms] Found plugin firebase_auth at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+3/
[   +3 ms] Found plugin firebase_auth_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[   +2 ms] Found plugin firebase_core at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +3 ms] Found plugin firebase_core_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +4 ms] Found plugin flutter_keyboard_visibility at
/home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[  +15 ms] Found plugin fluttertoast at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-4.0.1/
[  +16 ms] Found plugin image_picker_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-1.0.9/
[  +14 ms] Found plugin path_provider at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.10/
[   +1 ms] Found plugin path_provider_linux at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[   +2 ms] Found plugin path_provider_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[  +35 ms] Found plugin url_launcher at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.10/
[   +3 ms] Found plugin url_launcher_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[   +3 ms] Found plugin url_launcher_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+6/
[ +119 ms] Found plugin cloud_firestore at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.6/
[   +2 ms] Found plugin cloud_firestore_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[   +9 ms] Found plugin firebase_auth at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+3/
[   +2 ms] Found plugin firebase_auth_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[   +1 ms] Found plugin firebase_core at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +3 ms] Found plugin firebase_core_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +3 ms] Found plugin flutter_keyboard_visibility at
/home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +2 ms] Found plugin fluttertoast at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-4.0.1/
[   +6 ms] Found plugin image_picker_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-1.0.9/
[  +15 ms] Found plugin path_provider at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.10/
[   +2 ms] Found plugin path_provider_linux at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[   +3 ms] Found plugin path_provider_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[  +23 ms] Found plugin url_launcher at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.10/
[   +2 ms] Found plugin url_launcher_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[   +3 ms] Found plugin url_launcher_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+6/
[  +63 ms] Generating /home/spectrum/StudioProjects/startupcreators/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +304 ms] Launching lib/main.dart on Chrome in debug mode...
[  +81 ms] Updating assets
[+1054 ms] Syncing files to device Chrome...
[  +14 ms] Found plugin cloud_firestore at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.6/
[   +2 ms] Found plugin cloud_firestore_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[   +6 ms] Found plugin firebase_auth at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+3/
[   +2 ms] Found plugin firebase_auth_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[   +1 ms] Found plugin firebase_core at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +1 ms] Found plugin firebase_core_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +3 ms] Found plugin flutter_keyboard_visibility at
/home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +2 ms] Found plugin fluttertoast at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-4.0.1/
[   +4 ms] Found plugin image_picker_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-1.0.9/
[   +5 ms] Found plugin path_provider at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.10/
[        ] Found plugin path_provider_linux at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[        ] Found plugin path_provider_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[   +9 ms] Found plugin url_launcher at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.10/
[   +1 ms] Found plugin url_launcher_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[   +1 ms] Found plugin url_launcher_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+6/
[  +13 ms] Found plugin cloud_firestore at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.6/
[        ] Found plugin cloud_firestore_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[   +3 ms] Found plugin firebase_auth at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+3/
[   +1 ms] Found plugin firebase_auth_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[        ] Found plugin firebase_core at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +1 ms] Found plugin firebase_core_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +3 ms] Found plugin flutter_keyboard_visibility at
/home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +1 ms] Found plugin fluttertoast at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-4.0.1/
[   +3 ms] Found plugin image_picker_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-1.0.9/
[   +6 ms] Found plugin path_provider at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.10/
[   +1 ms] Found plugin path_provider_linux at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[        ] Found plugin path_provider_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[   +8 ms] Found plugin url_launcher at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.10/
[        ] Found plugin url_launcher_macos at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[        ] Found plugin url_launcher_web at /home/spectrum/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+6/
[   +6 ms] Generating /home/spectrum/StudioProjects/startupcreators/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +51 ms] <- reset
[  +10 ms] /home/spectrum/development/flutter/bin/cache/dart-sdk/bin/dart
/home/spectrum/development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/spectrum/development/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.UTLCKV/app.dill --libraries-spec
file:///home/spectrum/development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.YSZNLP --filesystem-scheme org-dartlang-app --initialize-from-dill
build/cache.dill --platform file:///home/spectrum/development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +14 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+29702 ms] Syncing files to device Chrome... (completed in 29,879ms, longer than expected)
[        ] Synced 34.5MB.
[        ] <- accept
[ +858 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:38131/devtools/browser/1509a50d-b412-4511-8cc4-c0c714b1d33b
[+7141 ms] Debug service listening on ws://127.0.0.1:33871/bs90SCSV-tQ=

[ +885 ms] Debug service listening on ws://127.0.0.1:33871/bs90SCSV-tQ=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".

**Comment by dhianabli** [comment]
this is the error i get on codemagic when i build 
![Screenshot from 2020-06-12 18-21-56](https://user-images.githubusercontent.com/33099326/84524289-02520880-acda-11ea-8813-3b619119121b.png)

**Comment by iapicca** [comment]
Hi @dhianabli 
if the issue does not occur locally, but only with your CI/CD
I recommend you to ask support directly to the service provider.
Closing, as this isn't an issue with Flutter itself. 
If you disagree, please write in the comments and I will reopen it.
Thank you
