### ISSUE TITLE
Any roadmaps for full desktop support? (windows & linux)

### ISSUE THREAD

**Issue by softmarshmallow** [FirebaseExtended/flutterfire#2758]
Not all plugins are required, but firebase auth has big reason to use for non-firebase fans, and who has their own backend. myself, personally use node server backend and onlu authentication on firebase. 

The flow and ease is wonderful, but it does not yet has any support for windows and linux platform. others are all supported greatly. 

I wonder if any plans ahead is provided.

**Comment by Ehesp** [comment]
Right now the focus is on Android, iOS & Web. That being said, it doesn't mean other platforms aren't planned, just not the immediate priority.
