### ISSUE TITLE
[firebase_auth] can't build iOS/macOS version on master

### ISSUE THREAD

**Issue by sma** [FirebaseExtended/flutterfire#2761]
I created a new Flutter project with the lastest master:

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.5 19F101, locale de-DE)
    • Flutter version 1.20.0-1.0.pre.42 at /Users/sma/Work/flutter
    • Framework revision 401690a64f (vor 2 Tagen), 2020-06-12 19:45:48 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1
```

I'm using these dependencies:

```
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
```

When running `flutter build ios` I get these errors:

```    /Users/sma/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/top_level.dart:1:8: Error: Not found: 'dart:html'
    import 'dart:html';
           ^
    /Users/sma/Work/flutter/packages/flutter/lib/src/foundation/_platform_web.dart:7:8: Error: Not found: 'dart:html'
    import 'dart:html' as html;
           ^
    /Users/sma/.pub-cache/hosted/pub.dartlang.org/js-0.6.2/lib/js.dart:8:1: Error: Not found: 'dart:js'
    export 'dart:js' show allowInterop, allowInteropCaptureThis;
    ^
    /Users/sma/.pub-cache/hosted/pub.dartlang.org/js-0.6.2/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
    export 'dart:js_util';
    ^
    /Users/sma/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:306:25: Error: The method 'allowInterop'
    isn't defined for the class 'Auth'.
     - 'Auth' is from 'package:firebase/src/auth.dart'
     ('/Users/sma/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                            ^^^^^^^^^^^^
    /Users/sma/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:310:26: Error: The method 'allowInterop'
    isn't defined for the class 'Auth'.
     - 'Auth' is from 'package:firebase/src/auth.dart'
     ('/Users/sma/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          var errorWrapper = allowInterop((e) => _changeController.addError(e));
                             ^^^^^^^^^^^^
    /Users/sma/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:340:25: Error: The method 'allowInterop'
    isn't defined for the class 'Auth'.
etc...
```

I get a similar result when running `flutter build macos --verbose`. Without `--verbose` no error is shown when the build eventually fails. (It takes about 5 minutes but that's another issue.)

**Comment by TahaTesser** [comment]
Hi @sma 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by sma** [comment]
I can't reduce my problem to a minimal example because each test takes about 5 minutes to run but I'll attach the output of `flutter build ios --verbose > log.txt 2>&1` of my application which depends only on: 
```
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  shared_preferences: ^0.5.7
```

[log.txt.gz](https://github.com/FirebaseExtended/flutterfire/files/4786288/log.txt.gz)

**Comment by sma** [comment]
I think, I found the line that triggers the problem. 

Create a new project with `flutter create foo`, add `cloud_firestore` as a dependency and add this line to the `main` function:

```flutter
print(firestore().collection('foo').doc('1').get());
```

Using `Firestore.instance.collection...` seems to work.

**Comment by TahaTesser** [comment]
@sma 
I don't believe `firestore()`  is correct initialization and not related to auth as pointed in title

**Comment by sma** [comment]
I know that I was wrong with blaming "firebase_auth".

The problem occurred after adding that framework plus code to access the user object. We did access it "the wrong way" using a "package:firebase/firestore.dart" import and `firestore()` instead of using "package:cloud_firestore/cloud_firestore.dart" and `Firestore.instance`. The "wrong way" worked in the context of a web app but not when trying to compile the Flutter project for iOS (or macOS). After replacing all instances of `firestore()` with the "right way", I could compile everything.

I'll try to find out where my colleague did find a tutorial that recommended the use of `firestore()` to access the user. I failed to notice that "firebase/firestore" is web-specific code that shouldn't be directly imported and used.

Perhaps it is possible to warn the user about this – somehow.

**Comment by TahaTesser** [comment]
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by sma** [comment]
Run `flutter create foo`. 
Then add `firebase_auth: 0.16.1` as a dependency. 
Then use this `main.dart`: 

```dart
import 'package:firebase/firebase.dart';

void main() {
  print(firestore().collection('users'));
}
```
Then run `flutter build ios --verbose`.
Notice the errors starting at line 5458.

[log.txt.gz](https://github.com/FirebaseExtended/flutterfire/files/4787519/log.txt.gz)

Also notice that importing that file and using that function was an error on our side I didn't notice. You can close the issue or replace it with a new issue that for example makes it more difficult to import files that shouldn't be importable.

**Comment by TahaTesser** [comment]
@sma 
Using code sample here above also crashes the app on Android and i am not sure you can firestore without instance

**Comment by sma** [comment]
Just to be clear: The problem wasn't a crashing app but a project that didn't build.

The `firestore()` function cannot work on iOS or Android because it is part of a web-specific firebase API which we were able to import without noticing that fact. In the meantime I learned from my colleague that he simply reused code that worked in a cloud function.

**Comment by TahaTesser** [comment]
@sma 
Thanks, i can reproduce it

**Comment by Salakar** [comment]
Closing as this is down to incorrect usage. `import 'package:firebase/firebase.dart';` is for Web only.  You should be using the cross platform Firebase packages listed here https://firebase.flutter.dev/ if you want to to use Firebase on Android, iOS & Web
