### ISSUE TITLE
Repetitive Firebase message in the console, each 3 seconds

### ISSUE THREAD

**Issue by marcglasberg** [FirebaseExtended/flutterfire#2765]
Each 3 seconds I get a message in the console, resulting in this:

```
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5918): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
```

**Comment by marcglasberg** [comment]
flutter doctor -v

[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [versÃ£o 10.0.18363.900], locale pt-BR)
    • Flutter version 1.17.3 at C:\flutter
    • Framework revision b041144f83 (11 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\marcg.DESKTOP-LP3T69M\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @marcglasberg  
Can you please provide a complete reproducible minimal code sample or does it happen with official code sample? Also `remote_config` version 
Thank you

**Comment by marcglasberg** [comment]
We'll update to the most recent Firebase plugins and then I'll let you know if the problem persists, and if so if we can give you more information or not.

**Comment by marcglasberg** [comment]
Seems the problem is gone. I will close this. Thanks.
