### ISSUE TITLE
[firebase_messaging] IOS foreground onMessage method not calling. Its working in simulator but not in real device and testflight  

### ISSUE THREAD

**Issue by MuraliYarraAnimatrics** [FirebaseExtended/flutterfire#2768]
In IOS onMessage method not calling when the app in the foreground. Notification are working fine While app in background or completely closed
`[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.3 at /Users/muraliyarra/workspace/flutter
    • Framework revision b041144f83 (12 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
`
`[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1`

I'm struggling with this from last week. Any help much appreciated

**Comment by TahaTesser** [comment]
Hi @MuraliYarraAnimatrics 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
