### ISSUE TITLE
[firebase_mesaging] onResume called when (ios) app in background

### ISSUE THREAD

**Issue by nielstj** [FirebaseExtended/flutterfire#277]
**Describe the bug**
On iOS, `onResume` from `configure` method called right after push notification received without any interaction.

**To Reproduce**
1. Run Flutter app.
2. Press home to put in background mode.
3. Send a push notification from Server (app still in background).
4. onResume called (print from the flutter log).

**Expected behavior**
`onResume` should be called only after push notification opened.

**Additional notes**
Tested on ios 12.4.1 and 13.1.1

**Comment by ordsen** [comment]
Same here - we're on `firebase_messaging: "5.1.4"` and `Flutter Channel stable, v1.9.1+hotfix.5`

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓
