### ISSUE TITLE
[FIREBASE_MESSAGING] Minor documentation issue in README.md for iOS Integration

### ISSUE THREAD

**Issue by sowens-csd** [FirebaseExtended/flutterfire#2771]
**Describe the bug**
The documentation shows this:
```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

And at least in my project it should have been this:

```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
}
```

Note the cast is no longer conditional. 

**To Reproduce**
1. Follow the iOS Integration instructions in the README.md
2. At step 5 make the code change suggested in the docs in Xcode
4. The Swift compiler will complain about the conditional cast with the error `Conditional cast from 'AppDelegate' to 'UNUserNotificationCenterDelegate' always succeeds`

**Expected behavior**
Code should have been error free

**Additional context**

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2017.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```
Conditional cast from 'AppDelegate' to 'UNUserNotificationCenterDelegate' always succeeds
```

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed up to date documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
