### ISSUE TITLE
[Firebase AdMob] InterstitialAd only loads once

### ISSUE THREAD

**Issue by JCKodel** [FirebaseExtended/flutterfire#278]
**Describe the bug**
The InterstitialAd only loads once (I'm not trying to show a interstitial twice! I'm trying to reload it after show).

**To Reproduce**
1. Create a InterstitialAd instance
2. On its listener, set `loaded = true` on the `loaded` event and `loaded = false` on the `closed` event, also, on the closed event, call `InterstitialAd.load()`
3. Load the ad with `InterstitialAd.load()`
3. Check if it is loaded with `InterstitialAd.isLoaded()`
4. Show it using `InterstitialAd.show()`

In the first run, this will happen: the ad will load, then the loaded event will trigger (loaded = true), then `.isLoaded()` will return true and `.show()` will show it. After it is closed, the closed event will trigger. Everything works as expected.

After that, the loaded event is never triggered again (but `InterstitialAd.isLoaded()` returns true). If I try to `.show()`, nothing happens (not even an exception).

`InterstitialAd .load()` always returns true.

Reloading the app (in debug) fixes (it will trigger once, then never more).

I tried to dispose the `InterstitialAd` and recrated it, but in the next run, the app will be terminated with a Chrome exception (something about the GPU driver).

**Expected behavior**
`InterstitialAd.load()` should:
1. Reload the interstitial and trigger the `loaded` event - or - the `failedToLoad` event
2. `InterstitialAd.isLoaded()` shouldn't report true when it is not loaded

**Additional context**
My app uses exactly the same method to display InterstitialAd and RewardedVideoAd, controlling a boolean variable based on the loaded, failedToLoad and closed events. RewardedVideoAd works fine everytime (so, is not a glitch in my code, I guess - the ads are reloaded and controlled by this boolean variable just fine).

**Comment by iapicca** [comment]
Hi 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/135)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
