### ISSUE TITLE
[firebase_auth] reauthenticate anonymous user which is linked / unlinked to email

### ISSUE THREAD

**Issue by erf** [FirebaseExtended/flutterfire#2782]
**Describe the bug**

I login with an anonymous user, i then link to email, and unlink again. 

Later, i try to link to email again, and i receive the error `ERROR_REQUIRES_RECENT_LOGIN`.

I read in the comments i should use the `reauthenticateWithCredential` method in these cases. I tried to use the email credentials, but then got the error `ERROR_WRONG_PASSWORD`, although the password should be correct. Am i supposed to reauthenticate using the anonymous credentials? How do i get them? I tried to sign in anonymous user again, but then a new anonymous user was created.

Please let me know what i'm supposed to do.

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.40.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
