### ISSUE TITLE
[firebase_messaging] Sound not working in V26 and above Android

### ISSUE THREAD

**Issue by AhmedAlaa96** [FirebaseExtended/flutterfire#2789]
Hi, everyone

I have an issue with sound  in firebase_messaging in APi v26 and above in android devices 
I got the notification and it's working fine like I need but without sound I tried many devices to check if device API version < 26 like Android Nougat ( 7 ) make a sound with the notification but
if API version >= 26 sound is gone 

Note: 

1. Send notification from firebase console with topic and segment no sound
1. Send notification from API with fcm token and no sound also

 

Can anyone help me with this ?

Thank you

**Comment by TahaTesser** [comment]
Hi @AhmedAlaa96 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` `pubsepc.yaml`  and a complete reproducible minimal code sample
Thank you

**Comment by AhmedAlaa96** [comment]
> Hi @AhmedAlaa96
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` your `pubsepc.yaml` and a complete reproducible minimal code sample
> Thank you

**My Code:**
```
  static void initNotification() {
    if (Platform.isIOS) {
      iosSubscription = _fcm.onIosSettingsRegistered.listen((data) {
        print(data);
        _saveDeviceToken();
      });

    } else {
      _saveDeviceToken();
    }
    _fcm.requestNotificationPermissions(IosNotificationSettings(sound: true,alert: true,badge: true));
    _fcm.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        _notificationData(message);

      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        _notificationData(message);
        // TODO optional
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
         _notificationData(message);
        // TODO optional
      },
    );
  }
```
**My `flutter doctor -v`**
```
Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at D:\Work\flutter
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ahmed\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\ahmed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

```
The  notification working fine but without sound in Android device whose with android version 8 or above (API V26)

**Comment by aliakkawi** [comment]
I am facing the exact same issue, did you find any solution? if yes please let me know. Thanks

**Comment by efraespada** [comment]
Same issue here

**Comment by xurei** [comment]
Same issue. Did anyone find a solution ?

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
