### ISSUE TITLE
Cloud firestorm unsafe operations

### ISSUE THREAD

**Issue by fbss101** [FirebaseExtended/flutterfire#2790]
Android studio shows this error: 
flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.6/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations. 

It only notifies this error sometimes. I am running the latest version of the cloud_firestore. I appeared before with older versions.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
