### ISSUE TITLE
FirebaseCore/Sources/Private/FirebaseCoreInternal.h' file not found

### ISSUE THREAD

**Issue by lizhaobomb** [FirebaseExtended/flutterfire#2795]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/lizh/Desktop/flutter/flutter_skype/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/User/FIRUser.m:20:9: fatal
    error: 'FirebaseCore/Sources/Private/FirebaseCoreInternal.h' file not found
    #import "FirebaseCore/Sources/Private/FirebaseCoreInternal.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/lizh/Desktop/flutter/flutter_skype/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/User/FIRUser.m:20:9: note: did
    not find header 'Sources/Private/FirebaseCoreInternal.h' in framework 'FirebaseCore' (loaded from
    '/Users/lizh/Desktop/flutter/flutter_skype/build/ios/Debug-iphonesimulator/FirebaseCore')
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build
    settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build
    settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 8.

**Comment by TahaTesser** [comment]
Hi @lizhaobomb 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by lizhaobomb** [comment]
Hi @TahaTesser 

this is flutter doctor -v

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/lizhao/opt/flutter
    • Framework revision 5f21edf8b6 (3 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lizhao/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/lizhao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 8 • 7CBE8738-4B53-4205-A41A-9970CFC27ADA • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

this is ``` flutter run --verbose```
[error_log.txt](https://github.com/FirebaseExtended/flutterfire/files/4805990/error_log.txt)

and pubspec.yaml

```
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.6
  shimmer: ^1.1.1
  gradient_app_bar: ^0.1.3
  emoji_picker: ^0.1.0
  image_picker: ^0.6.7+2
  path_provider: ^1.6.11
  firebase_storage: ^3.1.6
```
and Podfile.lock

[Podfile.txt](https://github.com/FirebaseExtended/flutterfire/files/4806010/Podfile.txt)


Thank you

**Comment by lizhaobomb** [comment]
Hi @TahaTesser 
[and this is my project repository you can try]
(https://github.com/lizhaobomb/flutter_skype)

**Comment by lizhaobomb** [comment]
Hi @TahaTesser is there anything i didn't done？any advice is super appreciate

**Comment by TahaTesser** [comment]
Hi @lizhaobomb 
You probably missed `AppDelegate.swift`, please add firebase to this class and `FirebaseApp.configure()` and run your app

```
import UIKit
import Flutter
import Firebase


@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

i just added that and ran your app, it runs and also builds

![Simulator Screen Shot - iPhone 11 - 2020-06-26 at 15 22 48](https://user-images.githubusercontent.com/48603081/85845336-b1561000-b7c1-11ea-9fb3-dcb333cbff64.png)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f73f498da1 (8 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (6 available)
    • SM M305F      • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E            • ios            •
      iOS 13.5.1
    • iPhone 11     • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS         • macOS                                • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server    • web-server                           • web-javascript •
      Flutter Tools
    • Chrome        • chrome                               • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!

``` 

</details>

**Comment by lizhaobomb** [comment]
hi @TahaTesser thanks for your suggestions，but unfortunately this doesn't solve my problem，
and I want to tell you that i ran into this problem by suddenly, i mean in the beginning all things goes well， on one day it can't run, maybe the cocoapods has somethings wrong ... please forgive my poor english

**Comment by lizhaobomb** [comment]
hi @TahaTesser when i new a purely native ios project with the podfile
```
  use_frameworks!

  # Pods for FirebaseDemo
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'BoringSSL-GRPC'
  pod 'gRPC-C++'
```
or maybe i just comment the statement ```use_modular_headers ``` in the podfile in the flutter project

 the problem has gone，i don't know why, anyway Thanks a lot, i will close the issue
