### ISSUE TITLE
Requesting DisableNetwork feature in firestore

### ISSUE THREAD

**Issue by pradeep121212** [FirebaseExtended/flutterfire#2800]
I am currently making a game which uses firestore as a backend. For multiplayer mode cloud is necessary, but for single player mode, the cache data from cloud is enough so that read/write will not be counted for billing. The game works perfectly when there is no internet. I just need DisableNetwork feature to make the game more optimistic.

**Comment by TahaTesser** [comment]
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/211
