### ISSUE TITLE
cloud_firestore: Allow where() to do prefix matching

### ISSUE THREAD

**Issue by jamesderlin** [FirebaseExtended/flutterfire#2801]
I came across https://medium.com/flutterdevs/implement-searching-with-firebase-firestore-flutter-de7ebd53c8c9 which recommends manually generating all possible prefixes for a search term.  I admittedly don't know anything about Firebase or cloud_firestore, but that approach sounds rather unergonomic and possibly inefficient.

Could [`Query.where`](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/where.html) have a `startsWith` or `stringStartsWith` parameter instead?

**Comment by Salakar** [comment]
Hey @jamesderlin, thanks for raising this feature request. Unfortunately this is out of scope of FlutterFire itself as we rely on the platform specific Firebase SDKs to provide functionality - so this would need to happen there first. 

I'd recommend raising this as a feature request on the Firebase website: https://firebase.google.com/support/troubleshooter/report/features

Thanks
