### ISSUE TITLE
[FIREBASE_ADMOB] Load interstitial after it is closed

### ISSUE THREAD

**Issue by garispe** [FirebaseExtended/flutterfire#2806]
**Describe the bug**
I load and show an `Interstitial Ad`. When I close it, I try to re-load the same `InterstitialAd` to have it preloaded to use next time, but the new load don't work

**To Reproduce**
1. Call interstitialAd.load()
2. Call interstitialAd.show()
3. Close it once is shown
4. Call interstitialAd.load()

**Expected behavior**
After ad was closed and load function was called again, I expected that the InterstitialAd will be loaded again and after some seconds is ready for use.

**Additional context**
* I use [firebase_admob ^0.9.3+2](https://pub.dev/packages/firebase_admob)
* I use test adUnits for now (`InterstitialAd.testAdUnit`)

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.4-pre.69, on Mac OS X 10.14.6 18G3020, locale en-AR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)
```

**Comment by TahaTesser** [comment]
Hi @garispe 
Can you please provide complete reproducible minimal code sample and please share actual behaviour you noticed  with logs
Thank you

**Comment by garispe** [comment]
Hi @TahaTesser 

I create an InterstitialAd and keep it on a HashMap to don't create a new every time.

```dart
void loadInterstitial(String adName, String adUnit) {
  InterstitialAdSpace adSpace;
  if (adSpacesByName.containsKey(adName)) {
    adSpace = adSpacesByName[adName];
  } else {
    InterstitialAd ad = InterstitialAd(adUnitId: adUnit, targetingInfo: targetInfo);
    ad.listener = (MobileAdEvent event) => handleAdEvent(event, adSpace);
    adSpace = InterstitialAdSpace(adName, adUnit, ad);
    adSpacesByName[adName] = adSpace;
  }
  adSpace.ad.load();
}
```

Then I show it:

```dart
InterstitialAd interstitial = adSpacesByName[adName].ad;
if (interstitial != null) interstitial.show();
```

When listen event `closed`, I try to call load() over same InterstitialAd instance:

```dart
if (event == MobileAdEvent.closed) {
  loadInterstitial(adSpace.name, adSpace.adUnit);
}
```

The output logs:

The first `loaded` event
```
DebugLogger: Event.loaded => withProperties: {name: name-of-interstitial}
```

The `opened` event when is shown
```
DebugLogger: Event.opened => withProperties: {name: name-of-interstitial}
```

Then, `closed` event:
```
DebugLogger: Event.closed => withProperties: {name: name-of-interstitial}
```

And I never see again`loaded` event or `failedToLoad`
