### ISSUE TITLE
RewardedVideoAdEvent.loaded is not working

### ISSUE THREAD

**Issue by Sourabh1251** [FirebaseExtended/flutterfire#2810]
I was trying to show circularProgressBar while ad is loading, so i added this condition inside Rewarded Ad Listener

RewardedVideoAd.instance.listener =
        (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
      final starChanger = Provider.of<StarChangeNotifier>(
          context, listen: false);
      if (**event == RewardedVideoAdEvent.loaded)** {
          MyGlobal.loadAdPressed = 2;
          print("Video add loaded");
          starChanger.setStar();
      }
      MyGlobal.stars = MyGlobal.stars + rewardAmount;
      starChanger.setStar();
    };

But for some reason listener is not sending callback after loading the video ad.

**Comment by TahaTesser** [comment]
Hi @Sourabh1251 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Zeynal7** [comment]
I have the exact same problem. Listener's loaded callback works 1 out of 15 times, so I have no idea how to check whether or not ad is loaded.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
