### ISSUE TITLE
Prevent FCM callbacks from handling exceptions

### ISSUE THREAD

**Issue by GENL** [FirebaseExtended/flutterfire#2811]
Inside of firebase cloud messaging callbacks such as onMessage, if any error occurs, no exception is raised so it's hard to debug. Can we prevent callbacks from catching error?

**Comment by TahaTesser** [comment]
Hi @GENL 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by GENL** [comment]
![image](https://user-images.githubusercontent.com/36866702/85289965-1cd17200-b490-11ea-8a20-69579b8ce487.png)

**Comment by GENL** [comment]
Callback code:

![image](https://user-images.githubusercontent.com/36866702/85290141-6cb03900-b490-11ea-88c0-894d71f70931.png)
