### ISSUE TITLE
[firebase_messaging] iOS background execution time for silent push notification

### ISSUE THREAD

**Issue by leonidl** [FirebaseExtended/flutterfire#2813]
I am trying to implement silent push notification support using firebase_messaging package.
In general, things works pretty well except fo one specific case: after iOS app has been terminated by user and a new silent push notification is sent, the app is launched but gets very little execution time before immediately being suspended.
Every subsequent push notification results in the app getting a bit more execution time. Eventually, all notifications arrive, but only as a result of a few push notifications being sent, the app then getting sufficient execution time and hence firebase_messaging getting completely initialized.

Obviously, the app has "Background Fetch" and "Remote notifications" flags enabled.

Any help on solving this will be very much appreciated.

**Comment by TahaTesser** [comment]
HI @leonidl 
Tested official [example](https://pub.dev/packages/firebase_messaging#-example-tab-) with app terminated, sent silent notifications and all notification arrive one at a time on iPhone XR


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f73f498da1 (4 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.106

• No issues found!
``` 

</details> 


Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by leonidl** [comment]
Hello @TahaTesser,

It appears I am getting notifications, but the execution time allocated to the app with each notification is very short (less than a second). As a result, my app does not have enough time to load itself properly and is only able to finish loading after a few notifications. My assumption was that each notification would provide about 30 seconds of execution time, but I am not seeing that.

Here is the output of flutter doctor -v:

leonid@leonidl-mbp10 phonerings % flutter doctor -v
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-CA)
    • Flutter version 1.19.0-4.1.pre at /Users/leonid/work/flutter
    • Framework revision f994b76974 (3 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/leonid/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/leonid/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (5 available)
    • Pixel 2    • HT84B1A02508                             • android-arm64  • Android 10 (API 29)
    • SM G973F   • RF8M331TCFN                              • android-arm64  • Android 10 (API 29)
    • iPhone8lla • 81fef7a65c8ca2e9b4fa26e6d69f4dcc5b1ca82a • ios            • iOS 13.5.1
    • Web Server • web-server                               • web-javascript • Flutter Tools
    • Chrome     • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

I currently am not able to attach a reproducible code.

Thank you,
Leo

**Comment by krishnakumarcn** [comment]
> after iOS app has been terminated by user and a new silent push notification is sent, the app is launched but gets very little execution time before immediately being suspended.


Hey sorry for asking this here. But I'm struggling to get firebase silent notifications(data-only firebase push) to work on iOS when the app is terminated by the user.
How did you manage to get this behavior? Even the flutterfire documentation says the terminated state is not supported.

@leonidl

**Comment by leonidl** [comment]
@krishnakumarcn 
The behaviour has been hit and miss, depending on the APN flags in push notification.
I guess, it is hard to rely on this behaviour being consistent, there I was forced to redesign the handling of push notifications.
Apple has said that starting from iOS 13 they will not allow background notifications with the highest priority (10), so I don't think we can rely on background notifications arriving in time in any case.

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation on all the various scenarios and setup steps: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
