### ISSUE TITLE
Adding firebase_database to Flutter project also add Firebase Analytics

### ISSUE THREAD

**Issue by jackkongjj** [FirebaseExtended/flutterfire#2814]
I integrated Firebase DB to my Flutter app by adding firebase_database package to pubspec.yaml and also import the GoogleService-Info.plist. (_I did set Analytics to NO when ask in the firebase web console_)

I am now constantly seeing this in my Android Studio console when running simulator:
6.25.0 - [Firebase/Analytics][I-ACS023130] Configuration not found. Using default configuration

I am also noticing that Podfile.lock now included bunch of packages from Firebase and Google. To name a few from the list:

- firebase_core_web
- firebaseAnalytics
- FirebaseAuthInterop
- FirebaseCoreDisgnostics
- FirebaseInstallations
- GoogleAppMeasurement
- GoogleDataTransport
- GoogleUtilities/UserDefaults
- GoogleUtilities/Reachability

Are all these packages needed just for using Firebase DB?
How to disable the Firebase/Analytics? (In GoogleService-info.plist IS_ANALYTICS_ENABLED is set to NO)

**Comment by TahaTesser** [comment]
Hi @jackkongjj 
Running latest `firebase_database: ^3.1.6` on a new project, i don't see` Configuration not found. Using default configuration` in the logs

please make sure you've build.gradle as follows
```
dependencies {
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}
apply plugin: 'com.google.gms.google-services'

``` 

no need to add analytics package in pubspec.yaml


```
Running Xcode build...
Xcode build done.                                           20.5s
Waiting for iPhone 11 to report its views...
Debug service listening on ws://127.0.0.1:53865/8yFRM7SvPCc=/ws
Syncing files to device iPhone 11...
flutter: Connected to second database and read 4
flutter: Child added: {Hello: world! 1}
flutter: Child added: {Hello: world! 2}
flutter: Child added: {Hello: world! 3}
flutter: Child added: {Hello: world! 4}
flutter: Child added: {Hello: world! 5}
flutter: Child added: {Hello: world! 6}
flutter: Child added: {Hello: world! 7}
```


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f73f498da1 (4 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.106

• No issues found!
``` 

</details> 

Thank you

**Comment by jackkongjj** [comment]
Thanks for the reply. Just to clarify, I didn't add the FirebaseAnalytics to the pubspec.yaml, which is why I am surprised that it is in the Podfile.lock.

Here is the console output when debugging:

> Launching lib/main.dart on iPhone 8 in debug mode...
Running pod install...                                              7.1s
Running Xcode build...
Xcode build done.                                           156.1s
Configuring the default Firebase app...
6.25.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
Configured the default Firebase app __FIRAPP_DEFAULT.
6.25.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
Debug service listening on ws://127.0.0.1:64396/XI4oZEU8DcE=/ws
Syncing files to device iPhone 8...
6.25.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60501000 started
6.25.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
6.25.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
6.25.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
6.25.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
6.25.0 - [Firebase/Analytics][I-ACS023130] Configuration not found. Using default configuration
6.25.0 - [Firebase/Analytics][I-ACS023130] Configuration not found. Using default configuration
6.25.0 - [Firebase/Analytics][I-ACS023130] Configuration not found. Using default configuration

**Comment by jackkongjj** [comment]
Hi,
So I create a new project from scratch, and without adding the GoogleService-info.plist yet. The moment I add the firebase_database to my pubspec.yaml, I am seeing the same set of packages added to Podfile.lock.

Here is the Podfile.lock, these are all the packages added after adding firebase_database:

<details>
  <summary>Podfile.lock</summary>

<p>

PODS:
  - Firebase/Core (6.25.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.5.1)
  - Firebase/CoreOnly (6.25.0):
    - FirebaseCore (= 6.7.1)
  - Firebase/Database (6.25.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 6.2.1)
  - firebase_core (0.0.1):
    - Firebase/Core
    - Flutter
  - firebase_core_web (0.1.0):
    - Flutter
  - firebase_database (0.0.1):
    - Firebase/Database
    - Flutter
  - FirebaseAnalytics (6.5.1):
    - FirebaseCore (~> 6.7)
    - FirebaseInstallations (~> 1.2)
    - GoogleAppMeasurement (= 6.5.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - FirebaseAuthInterop (1.1.0)
  - FirebaseCore (6.7.1):
    - FirebaseCoreDiagnostics (~> 1.3)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.3.0):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 3.1)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 1.30905.0)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseDatabase (6.2.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - leveldb-library (~> 1.22)
  - FirebaseInstallations (1.2.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/Environment (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.6)
    - PromisesObjC (~> 1.2)
   - GoogleAppMeasurement (6.5.1):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 1.30905.0)
  - GoogleDataTransport (6.1.1)
  - GoogleDataTransportCCTSupport (3.1.0):
    - GoogleDataTransport (~> 6.1)
    - nanopb (~> 1.30905.0)
  - GoogleUtilities/AppDelegateSwizzler (6.6.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.6.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.6.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.6.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.6.0)"
  - GoogleUtilities/Reachability (6.6.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.6.0):
    - GoogleUtilities/Logger


</p>
</details>

Is this right, that it adds all these packages in order to use firebase_database? Anyway to remove the Firebase/Analytics package?

Thanks!

**Comment by Salakar** [comment]
Hey the latest pre-release of Database now uses the `CoreOnly` pod on iOS/MacOS - so analytics should no longer be added now. Please give it a try, thanks!

https://firebase.flutter.dev/docs/database/overview
