### ISSUE TITLE
Receive notification only the app is in foreground

### ISSUE THREAD

**Issue by GENL** [FirebaseExtended/flutterfire#2815]
I build social network and I want to update the number of likes of a post using a push notification. But I don't want the users to be disturbed each time a post is liked when the app is in background. So is there a way to tell the mobile app to receive notification only when the app is in foreground?

Thanks

**Comment by siddhesh-tamhanekar** [comment]
you can use data message for that in which payload doesn't contain notification key. only data key is present.

**Comment by robrichardson13** [comment]
Potential fix mentioned here: https://github.com/FirebaseExtended/flutterfire/issues/2854#issuecomment-656316262
