### ISSUE TITLE
[Firebase Messaging] Shared data or a communication channel between a main process and a background isolate

### ISSUE THREAD

**Issue by Sorunome** [FirebaseExtended/flutterfire#2816]
**Is your feature request related to a problem? Please describe.**
We are using firebase messaging to handle push notifications in our app. In order to be able to generate the final push notification, we need to process the raw incoming data. For that, we use a client object and our database. When trying to cache the database, we noticed that when using `onBackgroundMessage` the database in the push handler and our main database thread were not the same. As such, said global cache variable was not shared between the two.

**Describe the solution you'd like**
Either a way to communicate between the main app thread and the worker, or a way to have a shared variable.

**Comment by TahaTesser** [comment]
Hi @Sorunome 
As far as i know you need platform channel here, you cannot platform channel on isolate yet  https://github.com/flutter/flutter/issues/13937

Thank you
