### ISSUE TITLE
[admob] handling issue "Issue: Violation of Interfering with Apps, Third-party Ads, ..."

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#2820]
**Describe the bug**
from internet resources, they say maybe the ad still show when the app is inactive (pause)
so i check the app state by WidgetsBindingObserver,

now to the main problem: the app state DELAYED

**To Reproduce**
please look at the line "HERE the app may go inactive"
```
    //
    if (!_interstitialAdShown) {
      //
      bool active = isActive();
      log.finest('active: ', active);
      //
      if (active) {
        //
        final load = await _interstitialAd.load();
        log.finest('load: ', load);
        // 
        bool active = isActive();
        log.finest('active: ', active);
        // **
        // ** HERE the app may go inactive
        // **
        if (load && active) {
          _interstitialAdShown = true;
          _interstitialAd.show(
            anchorOffset: 0.0,
            anchorType: AnchorType.bottom,
          );
        }
      }
    }
```

what else can i do now to pass the issue?

### EDIT

i dont know what exactly google talking about
they want playing fun, so i need to guess many days and many times

ref to google ad policy
https://support.google.com/googleplay/android-developer/answer/9857753

and ref to the section:
Interfering with Apps, Third-party Ads, or Device Functionality

the google example:
- The user navigates to the home screen from this app, and suddenly an ad appears on the homescreen.
- The user attempts to exit the app and navigate to the home screen, but instead, the expected flow is interrupted by an ad.

therefore, seems google state that the the "page ad" show after the app is pause / dispose
but you can see from the code, the state is delayed,
previous line the state checked, but next line show ad it would be in another state

**Comment by TahaTesser** [comment]
Hi @peterweb2005 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
