### ISSUE TITLE
[firebase_auth] Expose addIdTokenListener functionality

### ISSUE THREAD

**Issue by ryaanwells** [FirebaseExtended/flutterfire#2825]
### Problem
I use custom tokens to synchronise access permissions between Firestore and Storage but there's no easy way to react when the token changes. This forces me to tightly couple the call to refresh the token and the code to handle the change, complicating the BLOC pattern.

### Ideal situation
I'd like to be able to separate the request to refresh the token and handling token changes. This would allow me to:

- Call `firebaseUser.getIdToken(refresh: true)` whenever I know the ID token should be refreshed. This can remove the hard dependency on the BLOC state management class.
- Listen to the new "onIdTokenChanged" stream in the BLOC state management class and handle updates as appropriate.

### Issue Context
Boundary: we still have to manually trigger an update to retrieve token changes (`firebaseUser.getIdToken(refresh: true)`). This issue does **not** intend to cover automatically refreshing the token.
Reference: this stream natively exists on [Android (FirebaseAuth::addIdTokenListener)](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#public-void-addidtokenlistener-firebaseauth.idtokenlistener-listener) and [iOS (Auth#addIdTokenDidChangeListener)](https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/Auth#addidtokendidchangelistener_:)

**Comment by ryaanwells** [comment]
Happy to contribute but keen to understand how it fits in with https://github.com/FirebaseExtended/flutterfire/issues/2582 first :)

**Comment by Ehesp** [comment]
This has already been implemented in the rework, and hopefully will be available in the coming weeks once it's ready. Feel free to send up a PR to master though to get it integrated sooner, the functionality is identical to auth state changes, just with a different native listener.

**Comment by Ehesp** [comment]
Now implemented: https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/idTokenChanges.html
