### ISSUE TITLE
[admob] Failed load code

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#2830]
**Is your feature request related to a problem? Please describe.**
"failed load" can be many reasons, 
if code 3 (no content), app may ignore
but if other reasons, app may retry

**Describe the solution you'd like**
"call back function" return the code if failed load

**Comment by TahaTesser** [comment]
Hi @peterweb2005 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by peterweb2005** [comment]
sorry, no,

it is a featured request, i want to know the failed reason by the code

https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest

public static final int ERROR_CODE_INTERNAL_ERROR
public static final int ERROR_CODE_INVALID_REQUEST
public static final int ERROR_CODE_NETWORK_ERROR
public static final int ERROR_CODE_NO_FILL

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
