### ISSUE TITLE
 Unhandled Exception: PlatformException(error, Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority, null)

### ISSUE THREAD

**Issue by EvnLi** [FirebaseExtended/flutterfire#2832]
I/ViewRootImpl(17493): jank_removeInvalidNode all the node in jank list is out of time
E/flutter (17493): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority, null)
E/flutter (17493): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (17493): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (17493): <asynchronous suspension>
E/flutter (17493): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:335:40)
E/flutter (17493): #3      BarcodeDetector.detectInImage (package:firebase_ml_vision/src/barcode_detector.dart:200:38)

**Comment by EvnLi** [comment]
Running the demo,Scan qr code of album, a small number of phones will work, most phones will report this error (firebase_ML_vision /example)

**Comment by TahaTesser** [comment]
Hi @EvnLi 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
