### ISSUE TITLE
Firestore stopping xcode build

### ISSUE THREAD

**Issue by jackbuss** [FirebaseExtended/flutterfire#2833]
Hi,

Recently I've got MacBook and I've been installing all of the software that's needed for Flutter development, I've never had this issue before but since I've cloned a project from git, this error is stopping the build:

[ios/.symlinks/plugins/cloud_firestore] flutter pub get
Running "flutter pub get" in cloud_firestore-0.13.2...
Cannot open file, path = '/Users/jack/.pub-cache/global_packages/cloud_firestore/pubspec.lock' (OS Error: No such file or directory, errno = 2)
pub get failed (66; Cannot open file, path = '/Users/jack/.pub-cache/global_packages/cloud_firestore/pubspec.lock' (OS Error: No such file or directory, errno = 2))
exit code 66

Please can someone give me some insight on how to fix it?

Thanks,
Jack

**Comment by kroikie** [comment]
Could you try one of the following:

- `flutter clean`
- `flutter pub upgrade`
- delete the `.pub-cache` directory and try `flutter pub get` again.
