### ISSUE TITLE
[FIREBASE_MESSAGING] How to clear android notification badges/dots(introduced in Android 8.0) that appear on app icon in the launcher?

### ISSUE THREAD

**Issue by RanaOsamaAsif** [FirebaseExtended/flutterfire#2838]
**Describe the bug**
Whenever a firebase cloud messaging notification is received on Android Oreo(Android 8.0, API level 26) a dot appears on the app icon in the launcher. I couldn't find a way to mark to the notification as "seen" so that the notification dot disappears. Is the implementation for this missing or am I missing something?

**To Reproduce**
1. A new flutter project
2. Set up firebase could messaging in the app
3. Send notifications to device via Cloud Functions
4. Notification dot appears on the app icon
5. No clear way to make the dot go away

**Expected behavior**
A method call to clear the notification dots (introduced in Android 8.0 and above). Or some way to completely disable the notification dots via flutter so they do not appear.

**Additional context**
I have seen this behavior on some newer Huawei devices and specifically on Samsung Galaxy S8. I've tried using this package [https://github.com/g123k/flutter_app_badger/](url) but to no avail.

Just to make things a little more clear I'm talking about these notifications badges/dots: [https://developer.android.com/guide/topics/ui/notifiers/notifications#icon-badge](url)

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15 19A603, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

firebase_messaging: ^6.0.13
```

**Comment by TahaTesser** [comment]
Hi @RanaOsamaAsif 
Please try this [solution](https://github.com/flutter/flutter/issues/25030#issuecomment-491232528)

if the problem persist,  
Can you please provide your `pubspec.yaml` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
