### ISSUE TITLE
[firebase_messaging] UI not updated / animation freezing when configuring firebase messaging

### ISSUE THREAD

**Issue by timosturm** [FirebaseExtended/flutterfire#2848]
https://github.com/FirebaseExtended/flutterfire/blob/db92fc3d691da2409e096972e8c93a37cf33e7a9/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java#L97

This line was `if (!isIsolateRunning.get() && isApplicationForeground(backgroundContext)) {` some versions ago. Removing the second part seems to freeze animations and/or updates of the flutter ui after / when firebase messaging is configured.

Adding this back fixes my problem, any reason why this is the case?

`flutter doctor --verbose`:
```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/y/development/flutter
    • Framework revision f7a6a7906b (6 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/timo/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/local/android-studio-ide-191.5791312-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /usr/local/android-studio-ide-191.5791312-linux/android-studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @timosturm 
Can you please provide your `flutter doctor -v` `pubspec.yaml` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
