### ISSUE TITLE
Cannot shorten a short dynamic link. While it is really long.

### ISSUE THREAD

**Issue by braysonjohn148** [FirebaseExtended/flutterfire#2851]
E/flutter (25750): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(short_link_error, 400: Cannot shorten a short Dynamic Link: https://droopyposts.page.link/jTpt?utm_campaign=example-promo&ct=example-promo&pt=123456&sd=This%20link%20works%20whether%20app%20is%20installed%20or%20not!&st=Example%20of%20a%20Dynamic%20Link&amv=1&apn=com.xcgx.droopy&ibi=com.xcgx.droopy&imv=1.0.0&isi=123456789&link=http%3A%2F%2F18.220.131.37%2F&utm_medium=social&utm_source=orkut [https://firebase.google.com/docs/dynamic-links/rest#create_a_short_link_from_parameters], null)
[38;5;244mE/flutter (25750): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mE/flutter (25750): #1      MethodChannel._invokeMethod[39;49m
E/flutter (25750): <asynchronous suspension>
[38;5;244mE/flutter (25750): #2      MethodChannel.invokeMethod[39;49m
[38;5;244mE/flutter (25750): #3      MethodChannel.invokeMapMethod[39;49m
[38;5;248mE/flutter (25750): #4      DynamicLinkParameters.buildShortLink[39;49m
[38;5;248mE/flutter (25750): #5      DynamicLinkService.createFirstPostLink[39;49m
[38;5;248mE/flutter (25750): #6      _PostState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter (25750): #7      _InkResponseState._handleTap[39;49m
[38;5;244mE/flutter (25750): #8      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter (25750): #9      GestureRecognizer.invokeCallback[39;49m
[38;5;244mE/flutter (25750): #10     TapGestureRecognizer.handleTapUp[39;49m
[38;5;244mE/flutter (25750): #11     BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244mE/flutter (25750): #12     BaseTapGestureRecognizer.acceptGesture[39;49m
[38;5;244mE/flutter (25750): #13     GestureArenaManager.sweep[39;49m
[38;5;244mE/flutter (25750): #14     GestureBinding.handleEvent[39;49m
[38;5;244mE/flutter (25750): #15     GestureBinding.dispatchEvent[39;49m
[38;5;244mE/flutter (25750): #16     GestureBinding._handlePointerEvent[39;49m
[38;5;244mE/flutter (25750): #17     GestureBinding._flushPointerEventQueue[39;49m
[38;5;244mE/flutter (25750): #18     GestureBinding._handlePointerDataPacket[39;49m
[38;5;244mE/flutter (25750): #19     _rootRunUnary  (dart:async/zone.dart:1196:13)[39;49m
[38;5;244mE/flutter (25750): #20     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)[39;49m
[38;5;244mE/flutter (25750): #21     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)[39;49m
[38;5;244mE/flutter (25750): #22     _invoke1  (dart:ui/hooks.dart:275:10)[39;49m
[38;5;244mE/flutter (25750): #23     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)[39;49m
E/flutter (25750):
  
E/flutter (25750): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(short_link_error, 400: Cannot shorten a short Dynamic Link: https://droopyposts.page.link/jTpt?utm_campaign=example-promo&ct=example-promo&pt=123456&sd=This%20link%20works%20whether%20app%20is%20installed%20or%20not!&st=Example%20of%20a%20Dynamic%20Link&amv=1&apn=com.xcgx.droopy&ibi=com.xcgx.droopy&imv=1.0.0&isi=123456789&link=http%3A%2F%2F18.220.131.37%2F&utm_medium=social&utm_source=orkut [https://firebase.google.com/docs/dynamic-links/rest#create_a_short_link_from_parameters], null)
[38;5;244mE/flutter (25750): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mE/flutter (25750): #1      MethodChannel._invokeMethod[39;49m
E/flutter (25750): <asynchronous suspension>
[38;5;244mE/flutter (25750): #2      MethodChannel.invokeMethod[39;49m
[38;5;244mE/flutter (25750): #3      MethodChannel.invokeMapMethod[39;49m
[38;5;248mE/flutter (25750): #4      DynamicLinkParameters.buildShortLink[39;49m
[38;5;248mE/flutter (25750): #5      DynamicLinkService.createFirstPostLink[39;49m
[38;5;248mE/flutter (25750): #6      _PostState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter (25750): #7      _InkResponseState._handleTap[39;49m
[38;5;244mE/flutter (25750): #8      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter (25750): #9      GestureRecognizer.invokeCallback[39;49m
[38;5;244mE/flutter (25750): #10     TapGestureRecognizer.handleTapUp[39;49m
[38;5;244mE/flutter (25750): #11     BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244mE/flutter (25750): #12     BaseTapGestureRecognizer.acceptGesture[39;49m
[38;5;244mE/flutter (25750): #13     GestureArenaManager.sweep[39;49m
[38;5;244mE/flutter (25750): #14     GestureBinding.handleEvent[39;49m
[38;5;244mE/flutter (25750): #15     GestureBinding.dispatchEvent[39;49m
[38;5;244mE/flutter (25750): #16     GestureBinding._handlePointerEvent[39;49m
[38;5;244mE/flutter (25750): #17     GestureBinding._flushPointerEventQueue[39;49m
[38;5;244mE/flutter (25750): #18     GestureBinding._handlePointerDataPacket[39;49m
[38;5;244mE/flutter (25750): #19     _rootRunUnary  (dart:async/zone.dart:1196:13)[39;49m
[38;5;244mE/flutter (25750): #20     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)[39;49m
[38;5;244mE/flutter (25750): #21     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)[39;49m
[38;5;244mE/flutter (25750): #22     _invoke1  (dart:ui/hooks.dart:275:10)[39;49m
[38;5;244mE/flutter (25750): #23     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)[39;49m
E/flutter (25750):

I even tries the same example.

**Comment by TahaTesser** [comment]
Hi @braysonjohn148 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
