### ISSUE TITLE
[firebase_auth] currentUser reporting anonymous user incorrectly

### ISSUE THREAD

**Issue by cmkweber** [FirebaseExtended/flutterfire#288]
I'm still trying to create a reproducible, but firebase_auth is reporting an anonymous user as non-anonymous.

![Anonymous](https://user-images.githubusercontent.com/45799422/66519673-60747f00-eaad-11e9-9927-60c2c83c0422.JPG)

![FirebaseUser](https://user-images.githubusercontent.com/45799422/66519668-5c486180-eaad-11e9-9e86-dc0821b2af25.jpg)

Since this appears to only be happening with 'currentUser' it is probably related to how firebase is serializing the user to disk.

**Comment by cmkweber** [comment]
I have been able to create a reproducible now. It actually wasn't related to the serialization as it appears to happen immediately without having to exit application and reopen. The issue appears to be related to signing into an anonymous account while signed in to a non-anonymous account. The AuthResult returned from signInAnonymously is correct, but if you immediately check currentUser it only captures the changed UID but not the other properties, such as isAnonymous.

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/widgets.dart';

void main() async
{
  WidgetsFlutterBinding.ensureInitialized();

  runApp(
    Directionality(
      textDirection: TextDirection.ltr,
      child: AuthWidget()
    )
  );
}

class Button extends StatelessWidget
{
  final String label;
  final void Function() onTap;

  Button(this.label, this.onTap);

  @override Widget build(BuildContext context)
  {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        decoration: BoxDecoration(color: Color.fromRGBO(255, 255, 255, 1.0)),
        padding: EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
        child: Text(label, style: TextStyle(color: Color.fromRGBO(0, 0, 0, 1.0)))
      )
    );
  }
}

class AuthWidget extends StatefulWidget { @override AuthWidgetState createState() { return AuthWidgetState(); } }

class AuthWidgetState extends State<AuthWidget>
{
  AuthResult _result;
  FirebaseUser _user;

  void initState() { super.initState(); onRefresh(); }
  Future<void> onSign() async { _result = await FirebaseAuth.instance.signInWithEmailAndPassword(email: 'email@address.com', password: 'password123'); onRefresh(); }
  Future<void> onAnon() async { _result = await FirebaseAuth.instance.signInAnonymously(); onRefresh(); }
  Future<void> onOut() async { await FirebaseAuth.instance.signOut(); onRefresh(); }
  void onRefresh() async { _user = await FirebaseAuth.instance.currentUser(); setState(() {}); }

  @override Widget build(BuildContext context)
  {
    return Column(
      children: <Widget>[
        Spacer(),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: <Widget>[
            Button('sign in', onSign),
            Button('anon in', onAnon),
            Button('sign out', onOut)
          ]
        ),
        SizedBox(height: 20.0),
        Text('result uid'),
        Text(_result != null && _result.user != null ? _result.user.uid : ''),
        SizedBox(height: 20.0),
        Text('result isAnonymous'),
        Text(_result != null && _result.user != null ? _result.user.isAnonymous.toString() : ''),
        SizedBox(height: 20.0),
        Text('current uid'),
        Text(_user != null ? _user.uid : ''),
        SizedBox(height: 20.0),
        Text('current isAnonymous'),
        Text(_user != null ? _user.isAnonymous.toString() : ''),
        Spacer()
      ]
    );
  }
}
```

Using the demo application above, you can observe this by signing into an account using email provider, then signing in anonymously. You should observe that isAnonymous is correct in the result but incorrect in the currentUser. Sign out. Sign back in using email provider, then sign out, then sign in anonymously. This should produce the expected result since signing out persists the changes to currentUser.

Until this bug is addressed, to make sure state is persisted to currentUser, always call signOut before signing into another provider.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
