### ISSUE TITLE
[Crashlytics] Remove Fabric dependency

### ISSUE THREAD

**Issue by zmeggyesi** [FirebaseExtended/flutterfire#2881]
Firebase Crashlytics seems to be still using the deprecated Fabric SDK. This is no longer supported, and will stop working altogether on 2020-11-15.

Podspecs should be updated to no longer include Fabric, and code changes are necessary due to an updated API in Crashlytics.

Source: https://firebase.google.com/docs/crashlytics/upgrade-sdk

**Comment by tillchen** [comment]
Agreed! The documentation should also update for the setup.

**Comment by sanekyy** [comment]
Waiting for update.

**Comment by emostar** [comment]
Duplicate of #2038

**Comment by TahaTesser** [comment]
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2038
