### ISSUE TITLE
[Firestore] Six unintentional documents written to database

### ISSUE THREAD

**Issue by maxmoros** [FirebaseExtended/flutterfire#2887]
**Describe the bug**
Six unintentional documents have been written to new collections. Upon making a document write request, these six additional documents are attempted: 
_createTime
_fieldsProto
_readTime
_ref
_serializer
_updateTime

These documents trigger my cloud function and throw errors. However, the documents do not appear in my cloud firestore database. This leads me to believe that cloud_firestore is sending a broken request and firestore removes these documents immediately after triggering the cloud function.

These names do not exist in my code, but do exist in the document.js code.
[https://googleapis.dev/nodejs/firestore/latest/document.js.html](https://googleapis.dev/nodejs/firestore/latest/document.js.html)
 

**To Reproduce**
Write a document to a new collection that has a cloud function console logging the document id.
Try this until these six hidden document write attempts appear.

**Expected behavior**
I do not expect these documents to be written. I expect only the single document I request to be written to the database.

**Additional context**
[https://stackoverflow.com/questions/62702756/firebase-cloud-function-triggers-six-hidden-xxxxx-documents-in-new-collecti?noredirect=1#comment110886763_62702756](https://stackoverflow.com/questions/62702756/firebase-cloud-function-triggers-six-hidden-xxxxx-documents-in-new-collecti?noredirect=1#comment110886763_62702756)

**Flutter doctor**
Run `flutter doctor` and paste the output below:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Mac OS X 10.15.5 19F2096, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

• No issues found!

**Comment by maxmoros** [comment]
Ignore the Flutter Beta channel, I just switched that today to play with flutter web. My app is posted with the latest stable flutter version

**Comment by TahaTesser** [comment]
Hi @maxmoros 
Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by Salakar** [comment]
Hey this has been fixed as part of #2582 / #2913  - pending release.
