### ISSUE TITLE
Error on release on iOS, Firestore is not found

### ISSUE THREAD

**Issue by emanuel-cc** [FirebaseExtended/flutterfire#2888]
Cuando se pasa a compilar en modo release en IOS, no encuentra el cloud firestore

**Comment by TahaTesser** [comment]
Translated Description
When going to build in release mode on IOS, it can't find the cloud firestore

Hi @emanuel-cc 
Can you please provide your `flutter doctor -v` your `flutter run --release  --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Salakar** [comment]
Hola, como parte de nuestro trabajo en curso para el #2582, esto se ha resuelto en nuestra revisión de Firebase Firestore (#2913), que ahora se ha fusionado en maestro. Analizaremos la publicación de algunos lanzamientos previos en los próximos días. Gracias
