### ISSUE TITLE
[Firebase Cloud Messaging for Flutter ] [auto-increment the badge number based on notification received]

### ISSUE THREAD

**Issue by angelocapone** [FirebaseExtended/flutterfire#2893]
On iOS is it possible to auto-increment the badge number based on notification received?
I’m currently sending badge value as "1" in payload. So currently it is showing "1" even if I receive several notification. Unfortunately I can’t manage the count on the server side.

**Comment by TahaTesser** [comment]
Hi @angelocapone 
Can you please sure complete payload? 
Also you please provide your `flutter doctor -v`  and a complete reproducible minimal code sample
Thank you

**Comment by rmtmckenzie** [comment]
@angelocapone that's not possible with APNS and by extension also not possible with Firebase push notifications. Apple expects you to count the number of notifications for a particular device server-side and send with a badge number for that user - there's no increment feature available unfortunately.

**Comment by angelocapone** [comment]
@rmtmckenzie 
Thank you for the explanation.
