### ISSUE TITLE
[firebase_auth] <Exception has occurred. PlatformException (PlatformException(FirebaseException, An internal error has occurred. [ 7: ], null)) FLUTTER>

### ISSUE THREAD

**Issue by danielgchap** [FirebaseExtended/flutterfire#290]
Hey all,

I have a flutter app with Flutter v1.10.14 that points to Firebase and I'm on the master channel.
Absolutely NOTHING has changed in my code or my Firebase setup. 
All I did was got a Flutter Upgrade notice in Visual Studio and I did that.

Now every time I go to log into my app with credentials that definitely work I get the following:

Firebase Exception: "An internal error has occurred. [ 7: ]"

Here is the code being called, nothing is null, this has just suddenly started happening out of nowhere:

@override
  Future<FirebaseUser> signInWithEmailAndPassword(
      String email, String password) async {
    final AuthResult result = await _firebaseAuth.signInWithEmailAndPassword(
        email: email, password: password);
    return result.user;
  }

I'd really appreciate your help. There are no issues when flutter doctor is run.

**Comment by danielgchap** [comment]
A little more input:
 - I'm using a device that has been logging in just fine all day:

Also this:

E/FirebaseInstanceId( 3674): Token retrieval failed: SERVICE_NOT_AVAILABLE
W/BiChannelGoogleApi( 3674): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@4b2e98a
E/flutter ( 3674): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(FirebaseException, An internal error has occurred. [ 7: ], null)

**Comment by danielgchap** [comment]
This seemed to be associated with the firewall settings in my apartment. Sorry to waste your time if you're reading this!

**Comment by LewisRa** [comment]
> This seemed to be associated with the firewall settings in my apartment. Sorry to waste your time if you're reading this!

Hey, I believe I am having the same problem. How did you fix your issue with your firewall? Thanks in advance!

**Comment by marcmarder** [comment]
Same problem here!

**Comment by phj7777777** [comment]
I having the same issue before. And I found that this issue occurred because there is no internet connection for my phone.

**Comment by haroonkhan9426** [comment]
Having exactly same issue while testing on emulator:
PlatformException(FirebaseException, An internal error has occurred. [ 7: ], null).
Any suggested solution?

**Comment by Garande** [comment]
I have also encountered this problem several times but the solution that has been working for me was either to restart my emulator or recheck on my internet connectivity

**Comment by LewisRa** [comment]
> Having exactly same issue while testing on emulator:
> PlatformException(FirebaseException, An internal error has occurred. [ 7: ], null).
> Any suggested solution?

My wifi  firewall stopping my internet from working on my emulator. That was what helped me!

**Comment by arfa123** [comment]
check internet connection.

**Comment by simonry14** [comment]
In my case I hadn't enabled Anonymous Sign-in Method in the Firebase Console
