### ISSUE TITLE
[Firestore] Is composite index query possible?

### ISSUE THREAD

**Issue by najibghadri** [FirebaseExtended/flutterfire#2914]
Hello, just a very important question. 
As described in [/firestore/query-data/index-overview#queries_supported_by_single-field_indexes](https://firebase.google.com/docs/firestore/query-data/index-overview#queries_supported_by_composite_indexes) 
composite index queries are supported by chaining where() calls. Is it supported in cloud_firestore 0.13.7 too?

**Comment by najibghadri** [comment]
[cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart#L43](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart#L43)
Based on this it look like it is supported, but I would be glad for reassurance.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582 this was only fixed in our Firebase Firestore rework (#2913) - which has been merged into master today (but has not been published yet). We'll look at publishing some prereleases in the next few days. Thank you

**Comment by najibghadri** [comment]
@Salakar thank you.
