### ISSUE TITLE
[firebase_auth] Crash after call PhoneAuthProvider.getCredential on Flutter 1.9.1+hotfix.4

### ISSUE THREAD

**Issue by emersonsiega** [FirebaseExtended/flutterfire#292]
**Describe the bug**
After upgrade to Flutter stable (1.9.1+hotfix.4) we are getting a crash after call `PhoneAuthProvider.getCredential`.

We call to `verifyPhoneNumber`, the user receives the SMS code and put it in the verification input. After submit, my App call to `PhoneAuthProvider.getCredential` passing the verificationId obtained before and the code sent by the user. During this call my app crashes and show these error logs:

```
D/AndroidRuntime( 4965): Shutting down VM
E/AndroidRuntime( 4965): FATAL EXCEPTION: main
E/AndroidRuntime( 4965): Process: br.com.dizimofiel.soudizimista.mobile, PID: 4965
E/AndroidRuntime( 4965): java.lang.NoSuchMethodError: No virtual method getMetadata()Lcom/google/firebase/auth/FirebaseUserMetadata; in class Lcom/google/firebase/auth/FirebaseUser; or its super classes (declaration of 'com.google.firebase.auth.FirebaseUser' appears in /data/app/br.com.dizimofiel.soudizimista.mobile-LPE-0lslSPPi6rhbGIxUAA==/base.apk)
E/AndroidRuntime( 4965): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.mapFromUser(FirebaseAuthPlugin.java:741)
E/AndroidRuntime( 4965): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.access$300(FirebaseAuthPlugin.java:54)
E/AndroidRuntime( 4965): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:673)
E/AndroidRuntime( 4965): 	at com.google.android.gms.tasks.zzf.run(Unknown Source:23)
E/AndroidRuntime( 4965): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 4965): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4965): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4965): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime( 4965): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4965): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 4965): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**To Reproduce**
1. Verify phone number with `verifyPhoneNumber` method
2. Save the verificationId to use later
3. Call to `PhoneAuthProvider.getCredential` passing the verificationId and code received by SMS
4. The app will crash

**Expected behavior**
Do not crash.

**Additional context**
firebase_auth: Teste from versions `0.11.1+12` to `0.14.0+5`
Flutter `v1.9.1+hotfix.4`
(Unfortunately I can't test with Flutter `v1.7.8` due to [this problem](https://github.com/flutter/flutter/issues/34000))
Tested in: 
  - Android emulator - API 27
  - Motorola moto g3 - API 23

Flutter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale pt-BR)
    • Flutter version 1.9.1+hotfix.4 at /Users/emerson.siega/development/flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emerson.siega/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

**Comment by ElixirMike** [comment]
I have same setup, but when I call PhoneAuthProvider.getCredential , nothing happens. I don't see any errors, or anything, it just doesn't work. I would expect if calling with invalid validation and SMS code, it would return some kind of error or result. I get back and authCredential instance, but seems there is nothing there. This is how I'm calling it with hard coded verification id. 

AuthCredential authCredential =  PhoneAuthProvider.getCredential(
        verificationId: '55', smsCode: smsCode);

**Comment by mahmoudrabie** [comment]
I think using this plugin could give you some insights 
https://pub.dev/packages/firebase_crashlytics#-readme-tab-

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
