### ISSUE TITLE
[Firebase Auth] Unwanted Google Sign IN bot attack

### ISSUE THREAD

**Issue by dheerajsarwaiya** [FirebaseExtended/flutterfire#2922]
**Describe the bug**
Not sure if it is a bug or a kind of cyber attack. I have pretty new website and App. However recently I started seeing tons of new user sign ins from Google Sign In button on my website. The problem is none of these users do anything on the site, there is no record of those ever visiting the website or app. But I still see new users sign in on my firebase console. It is happening programmatically because the email addresses are always in the format of 
UserName.{sixDigitNumber}@gmail.com. 

When I login through my actual email address, I see my actual email in the firebase console.

So not sure, if this behavior is expected from google auth (like in apple sign in, user can mask their email).
Is using Google Sign In, open you to get attacked by Bots? If yes, how to fix it? 

**Google sign in implementation**
Using Firebase_Auth and google_sign_in flutter package
```
final FirebaseAuth _auth;
final GoogleSignIn _googleSignIn = GoogleSignIn();

      final GoogleSignInAccount account = await _googleSignIn.signIn();
      final GoogleSignInAuthentication _gauth = await account.authentication;
      final AuthCredential credential = GoogleAuthProvider.getCredential(
        accessToken: _gauth.accessToken,
        idToken: _gauth.idToken,
      );

      AuthResult result = await _auth.signInWithCredential(credential);

```

Is it expected behavior or my site is getting attacked by bots?

**Comment by TahaTesser** [comment]
Hi @dheerajsarwaiya 
This isn't related to flutterfire, as this is outside scope of the `firebase_auth` 
Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you
