### ISSUE TITLE
Crash on iOS14 onmessage

### ISSUE THREAD

**Issue by evripidesk** [FirebaseExtended/flutterfire#2923]
**Describe the bug**
I have an app that use push notifications on emulator iOS 13.5.1 the onMessage working fine on real device with iOS 14 onmessage crash the app you can check the screenshot below 
**To Reproduce**
```    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        setState(() {
          _messageText = "Push Messaging message: $message";
        });
        print("onMessage: $message");
        print(message['extraPayLoad1']);
        if (message['extraPayLoad1'] == 'valuestart') {
          _showItemDialog2(message);
        } else {
          _showItemDialog(message);
        }
      },
      onLaunch: (Map<String, dynamic> message) async {
        setState(() {
          _messageText = "Push Messaging message: $message";
        });
        _serialiseAndNavigate(message);

        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        setState(() {
          _messageText = "Push Messaging message: $message";
        });
        _serialiseAndNavigate(message);

        print("onResume: $message");
      },
    );
```

[https://imgur.com/txmOv2k](https://imgur.com/txmOv2k)

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.46.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @evripidesk 
Do you see any crash logs?  can you please provide  your `flutter run --verbose`? 
BTW iOS 14 isn't supported yet in Flutter
Thank you
