### ISSUE TITLE
[cloud_firestore_platform_interface] Pointer equality not normalising paths

### ISSUE THREAD

**Issue by IchordeDionysos** [FirebaseExtended/flutterfire#2928]
**Describe the bug**
Not sure did not test it yet. (Will write a test and open a PR if the problem is real).

The pointer implementation splits the path into components AND removes any empty element/removes leading/trailing slashes.

Which is basically what we want!
However, when checking for equality the implementation does not use any normalized form, but rather uses the user-provided path for equality checking, which leads to unexpected inequalities of document and collection references.

Look at the way DocumentReferences are created:
1. [Android/iOS implementation](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart#L67): No normalization there. That's okay as I believe the normalization should not be done by the implementing library.
2. [MethodChannelFirebaseFirestore](https://github.com/FirebaseExtended/flutterfire/blob/27d574e620c3a95792682397b12e54e40abe572f/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart#L247): Not there either. I think it's okay.
3. [MethodChannelCollectionReference](https://github.com/FirebaseExtended/flutterfire/blob/27d574e620c3a95792682397b12e54e40abe572f/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_collection_reference.dart#L29): No normalization. It's okay.
4. [Pointer](https://github.com/FirebaseExtended/flutterfire/blob/27d574e620c3a95792682397b12e54e40abe572f/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/internal/pointer.dart#L12): No normalization. This is problematic.

In the pointer, the low-level, internal representation of references there is no normalization of the path.

When checking for equality of two `DocumentReference`s/`CollectionReference`s the equality of the underlying `Pointer`s is checked.

So, let's play it through:
1. [DocumentReference.==](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_reference.dart#L101): Path property of references is compared.
2. [DocumentReference.path](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_reference.dart#L43): Path is returned from `Pointer`.
3. [Pointer.path](https://github.com/FirebaseExtended/flutterfire/blob/27d574e620c3a95792682397b12e54e40abe572f/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/internal/pointer.dart#L18): Path from `Pointer` is returned as provided by the user, see above steps.

**To Reproduce**
1. Import `cloud_firestore`
2. Use this source code:

```dart
final db = FirebaseFirestore.instance;
print(db.collection('test') == db.collection('/test'));
```
4. See that `false` is printed out.

**Expected behavior**
`db.collection('test') == db.collection('/test')` should evaluate to `true`.

**Additional context**
Discovered this bug while looking at the implementation of the `Pointer` class.

Will update this issue once I tested it out and validated it.

**Comment by IchordeDionysos** [comment]
Adding a test like this would fail:

```dart
test('Pointer equality with un-normalized paths', () {
  expect(Pointer('foo') == Pointer('/foo'), true);
  expect(Pointer('foo') == Pointer('/foo/bar'), false);
  expect(Pointer('foo') == Pointer('foo/'), true);
  expect(Pointer('foo') == Pointer('foo/bar/'), false);
});
```

**Comment by IchordeDionysos** [comment]
@Salakar I think this should block a release of rework of cloud_firestore :)

I will open a PR for it 😊

**Comment by Salakar** [comment]
cc @Ehesp

**Comment by Salakar** [comment]
@IchordeDionysos cool, PR welcome, let me know if you need any help with local setup, the contributing/local setup docs are still pending
