### ISSUE TITLE
Plugin project :firebase_core_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by jerfesoncam** [FirebaseExtended/flutterfire#2932]
Plugin project :firebase_core_web not found. Please update settings.gradle.

**Comment by HandersonSilva** [comment]
Estou com o mesmo problema..

**Comment by TahaTesser** [comment]
Please check this https://github.com/FirebaseExtended/flutterfire/issues/2796#issuecomment-656606329
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2796
