### ISSUE TITLE
FireStore FieldValue.increment minus values set the values instead of decreasing.

### ISSUE THREAD

**Issue by bdairy** [FirebaseExtended/flutterfire#2938]
**Describe the bug**
I have this code snippet:

   ```
transaction.update(_groupRef, {
          'counters': {
            'users': {
              'pending': FieldValue.increment(-1),
              'joined': FieldValue.increment(1)
            }
          }
        });
```

the in the pending section,, instead of decreasing by -1. it sets the value to -1. the increment works fine.. but the decrement is the problem.

` firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.5`

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-JO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by Ehesp** [comment]
Related https://github.com/FirebaseExtended/flutterfire/issues/2215

**Comment by bdairy** [comment]
> Related #2215

@Ehesp  I looked into this one before posting,, I thought it was the same but it is not,, his case is running twice,, my case that even if the original counter was 10,, FieldValie.increment(-1) will set it to -1.

**Comment by greghesp** [comment]
Hi @bdairy 

I've tested this, and Flutterfire works the same as the JS SDK in this instance.  A similar issue was raised [here](https://github.com/firebase/firebase-js-sdk/issues/1956)

If you want to updated existing nested fields, you need to use a [dot separated path](https://firebase.google.com/docs/reference/js/firebase.firestore.html#updatedata) like so:

```
transaction.update(_groupRef, {
    'counters.users.pending': FieldValue.increment(-1),
    'counters.users.joined': FieldValue.increment(1),
  }
});
```
