### ISSUE TITLE
[firebase_admob] inline banner

### ISSUE THREAD

**Issue by glennmichaelmejias** [FirebaseExtended/flutterfire#296]
a banner ads that can be put on listview or can be a child with any widgets.

**Comment by jesusmartinoza** [comment]
Currently is not possible with this package, maybe you can try with this one https://github.com/kmcgill88/admob_flutter/

**Comment by blasten** [comment]
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1175
