### ISSUE TITLE
[cloud_firestore] INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked

### ISSUE THREAD

**Issue by gabrielgpavan** [FirebaseExtended/flutterfire#2968]
Every time I click the button to execute the transaction when I'm offline, the application crashes. Can anyone tell me why? My code is as follows:

    import 'package:cloud_firestore/cloud_firestore.dart';
    import 'package:mobx/mobx.dart';

    part 'plantao_controller.g.dart';

    class Controller = ControllerBase with _$Controller;

    abstract class ControllerBase with Store {
      Future<bool> pegarPlantao({cpf, hospital, setor, dia, horario}) async {
        Map<String, dynamic> mapa = {};
        if (horario == '00:00-06:00') {
          mapa['00:00-06:00'] = cpf;
        } else if (horario == '06:00-12:00') {
          mapa['06:00-12:00'] = cpf;
        } else if (horario == '12:00-18:00') {
          mapa['12:00-18:00'] = cpf;
        } else if (horario == '18:00-00:00') {
          mapa['18:00-00:00'] = cpf;
        }
    final ref = Firestore.instance
        .collection(hospital)
        .document('Escala 2020')
        .collection(setor)
        .document(dia);

    final doc = await Firestore.instance
        .runTransaction((t) {
          t.update(ref, mapa);
        })
        .then((value) => true)
        .catchError((onError) => false);

        return doc;
      }

      Future<bool> passarPlantao({cpf, hospital, setor, dia, horario}) async {
        Map<String, dynamic> mapa = {};
        if (horario == '00:00-06:00') {
          mapa['00:00-06:00'] = '';
        } else if (horario == '06:00-12:00') {
          mapa['06:00-12:00'] = '';
        } else if (horario == '12:00-18:00') {
          mapa['12:00-18:00'] = '';
        } else if (horario == '18:00-00:00') {
          mapa['18:00-00:00'] = '';
        }

    final ref1 = Firestore.instance
        .collection(hospital)
        .document('Escala 2020')
        .collection(setor)
        .document(dia);

    final doc = await Firestore.instance
        .runTransaction((t) {
          t.update(ref1, mapa);
        })
        .then((value) => true)
        .catchError((onError) => false);

        return doc;
      }
    }

**Comment by TahaTesser** [comment]
Hi @gabrielgpavan 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample without using third party packages
Thank you

**Comment by gabrielgpavan** [comment]
I'm creating the business logic using third-party packages (mobx) because I have to use it in the app. As soon as we test again, I update the answer

**Comment by shikhrsngh9044** [comment]
@TahaTesser  app is crashing when no internet connection or internet connection is weak is there any way to handle this issue
