### ISSUE TITLE
[firebase_messaging] APNs Key renewal no notification received.

### ISSUE THREAD

**Issue by duncanhoggan** [FirebaseExtended/flutterfire#297]
I had to recreate the APNs key for apple devices and now the userbase that had the app installed with the previous key can't receive notifications.

Is there any way to renew this without users uninstalling and reinstalling.
I've experimented with deleteInstanceID but that doesn't seem to resolve the issue.

**Comment by duncanhoggan** [comment]
My bad, its way too easy to open an issue...

**Comment by iapicca** [comment]
Hi @duncanhoggan 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by duncanhoggan** [comment]
@iapicca Thanks I haven't had a chance to get the code sample setup been way too busy. Will reopen when i have more info.
