### ISSUE TITLE
What is flutterfire's versioning nomenclature?

### ISSUE THREAD

**Issue by maguro** [FirebaseExtended/flutterfire#2979]
Is there a doc that explains flutter fire's versioning nomenclature?

**Comment by maguro** [comment]
That issue is a roadmap announcement.  I think it would mix concerns to place this question there as it's plain that it's fast becoming a junk drawer.

**Comment by rrousselGit** [comment]
Sorry for the late reply!

FlutterFire is using [semantic versioning](https://semver.org/)
