### ISSUE TITLE
[firestore] edit firestore document with listen locally doesn't update when changed map  

### ISSUE THREAD

**Issue by kareldebedts** [FirebaseExtended/flutterfire#2982]
In Firestore For Flutter ^0.12.11 , I was able to get documents like this:

var myList = [];

Firestore.instance
    .collection('talks')
    .where("topic", isEqualTo: "flutter")
    .snapshots()
    .listen((data) =>
        data.documents.forEach((doc) => myList.add(doc));

and then "edit" the documents locally like this:
var index = 0;
myList[index].data["topic"] = "otherTopic";

But when I upgraded to Firestore ^0.13.7, this doesn't work anymore.
I don't get an error, It just doesn't change. If I print myList[index].data["topic"], it remains "flutter".

(downgraded back to ^0.12.11, to test it & it works).

Is this a bug or has the way to do this changed in the update?

Thanks!

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  var myList = [];
  var index = 0;

  @override
  void initState() {
    super.initState();
    Firestore.instance
        .collection('talks')
        .where("topic", isEqualTo: "flutter")
        .snapshots()
        .listen((data) => data.documents.forEach((doc) {
              setState(() {
                myList.add(doc);
              });
            }));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Container(
              child: Text(myList[index].data['topic'] ?? ''),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                FlatButton(
                  child: Text('load'),
                  onPressed: () {
                    print(myList[index].data);
                  },
                ),
                FlatButton(
                  child: Text('update'),
                  onPressed: () {
                    setState(() {
                      myList[index].data['topic'] = "otherTopic";
                    });
                  },
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}


``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (6 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by anpega** [comment]
Hi, I'm experiencing similar issue. My application works fine, reading and writing data from/to Firestore, but suddenly it is not able to fetch a document from Firestore. The code awaits forever in the call to get() from the cloud_firestore package. At the same time I start getting the following console log every few seconds:

I/my_app(28139): Background concurrent copying GC freed 79567(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 535us total 394.302ms
I/my_app(28139): Background concurrent copying GC freed 93543(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/5MB, paused 317us total 153.503ms
I/my_app(28139): Background concurrent copying GC freed 85531(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 63us total 138.569ms
I/my_app(28139): Background concurrent copying GC freed 87029(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/5MB, paused 147us total 121.018ms
I/my_app(28139): Background concurrent copying GC freed 88772(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 95us total 102.315ms
I/my_app(28139): Background concurrent copying GC freed 87310(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/5MB, paused 105us total 122.714ms
I/my_app(28139): Background concurrent copying GC freed 87208(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 138us total 1.010s

Downgrading cloud_firestore to 0.12.11 doesn't help, so it must be something else.

I'm running the application in a emulator. Hot restart doesn't work when I face the issue and I need to re-launch the application to be able to reach the db again.

Any clue what could the issue be? Thanks

**Comment by russellwheatley** [comment]
This is really out of date. In the current implementation, you won't be able to update the data in-place as each `DocumentSnapshot.data()` returns a fresh `Map<String, dynamic>`. But the api has changed significantly so I'm going to close this.
