### ISSUE TITLE
[firebase_auth] dependencies problem with firebase_core 0.5.0-dev.1

### ISSUE THREAD

**Issue by csotomon** [FirebaseExtended/flutterfire#2988]
**Describe the bug**
Following the FlutterFire web page instructions to install the authorization module [https://firebase.flutter.dev/docs/auth/overview](https://firebase.flutter.dev/docs/auth/overview) i adde the firebase dependencias :

```yaml
firebase_core: "0.5.0-dev.1"
firebase_auth: "0.16.1"
```
as the web webpage instructions.

but when i run `flugger pub get` instruction, the command failed with this error.
```sh
Because firebase_auth >=0.15.5+2 depends on firebase_core ^0.4.4 and kepler depends on firebase_core 0.5.0-dev.1, firebase_auth >=0.15.5+2 is forbidden.
So, because kepler depends on firebase_auth 0.16.1, version solving failed.
Running "flutter pub get" in kepler...                                   
pub get failed (1; So, because kepler depends on firebase_auth 0.16.1, version solving failed.)
```

**To Reproduce**
1. open the `pubspec.yaml` file
2. Add the firebase_auth dependency to your projects pubspec.yaml file:
```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.5.0-dev.1"
  firebase_auth: "0.16.1"
```
4. Download the dependency by running the following command in your project:
```sh
$ flutter pub get
```
**Expected behavior**
You will se the package installation error

**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F101, locale es-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @csotomon 
Please use `firebase_core 0.4.5` with `firebase_auth: "0.16.1`, since auth  doesn't support `firebase_core 0.5.0-dev.1` yet 
When `firebase_auth` has dev release, you would be use with `firebase_core 0.5.0-dev.1`  
Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by csotomon** [comment]
I think that you should fix de documentation, because this generates confusion.
