### ISSUE TITLE
Lookup user by (Email/PhoneNumber/UUID)

### ISSUE THREAD

**Issue by andrefedev** [FirebaseExtended/flutterfire#2991]
There should be a way to search for a user using their email or phone number. The nodejs library can search for a user for each provider.

A real use case would be that before authenticating a user she would like to be able to hit the database to validate if the email is associated with any user. Another example is that if the user logs in with a phone number, they will not be able to know if the user is already registered. I think that if they want to convert firebase as a first class citizen to flutter, they should have a firebase admin sdk for dart, otherwise we might think that the project does not have great interest or support for flutter.

**Comment by TahaTesser** [comment]
Hi @andrefedev 
Is this possible using firebase sdk for android or ios?  if yes, can you please link it?
Thank you

**Comment by andrefedev** [comment]
I don't understand your question, are you suggesting to use native Firebase SDK libraries for Android / iOS in a Flutter project?

**Comment by TahaTesser** [comment]
Hi @andrefedev 
I am asking if this can be done with Firebase without using Flutter on native platforms or it's just nodejs library that can do this

**Comment by Ehesp** [comment]
Hello - this is an admin only feature so won't land in this library (which is for clients).
