### ISSUE TITLE
[<cloud_firestore>] Add FieldValue.arrayRemove() and FieldValue.arrayUnion() support inside arrays

### ISSUE THREAD

**Issue by ramnim** [FirebaseExtended/flutterfire#2998]
I have a document which has a field of nested arrays. Trying to update the inside array with FieldValue.arrayRemove and FiledValue.arrayUnion but got the following exception:

`E/flutter ( 5101): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Invalid data. FieldValue.arrayRemove() is not currently supported inside arrays, null)`

arrayRemove and arrayUnion can be extended to nested arrays.

Document structre in firestore:
```
{
 "orders":
  [
    {"items":
      [
        {
        }
      ],
    }
  ]
}
```

Using the following Firestore query:

```
await Firestore.instance.collection('customer')
      .document(xxxxxxxx).updateData({'orders':[{'items': FieldValue.arrayRemove([item])}]});
```

**Comment by Ehesp** [comment]
Hello, this is an unsupported operation on the Firebase SDKs. You should instead build up the `orders` array with the nested array and set this instead.
