### ISSUE TITLE
[cloud_firestore] Possible regression

### ISSUE THREAD

**Issue by jogboms** [FirebaseExtended/flutterfire#3000]
I used to be able to get the collection reference of a query. This was removed in #2913

```
// query.dart
CollectionReference reference() => CollectionReference._(_delegate.reference(), firestore);
```

I do not know why this was removed, is there any alternate way of doing this?

cc @Salakar

**Comment by Ehesp** [comment]
Hi @jogboms generally we followed the SDK guidelines for the implementation work. A `CollectionReference` extends a `Query` therefore calling `reference()` would just return itself anyway.

E.g, doing this should work:

```
dynamic foo = FirebaseFirestore.instance.collection('foo').limit(3);

if (foo is CollectionReference)
  print('path ${foo.path}');
}
``` 

What's your use-case?

**Comment by Ehesp** [comment]
Ok sorry I got that wrong 🤦 

I'd advise plucking the reference and re-using it:

```dart
CollectionReference foo = FirebaseFirestore.instance.collection('foo');
Query bar = foo.limit(2);

// use foo and bar separately. 
```

**Comment by jogboms** [comment]
Hey @Ehesp 

Sorry for the delay. It was more of me trying to figure out why it was removed. I seem to be the only one complaining stilll.
The way I had the architecture was a separate service exposes the collection based on a certain query and that is all it knows about. 

```Query expenses(user) => instance.collection('expenses').where('accountID', isEqualTo: user)```

Then a trivial usage,

```expenses(user).reference().document(id)```

I admit, this can be refactored to instead combine the `user` and `id` into one query.

**Comment by kroikie** [comment]
Hi @jogboms I agree that would be useful. It is however not available in the [native SDKs](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/Query) so really should not be available here. We are trying to stay inline with the native SDKs as much as possible. Sorry we removed this function, I hope your refactor is not too painful.

**Comment by jogboms** [comment]
Yeah. A refactor was the way to go. The only way that made more sense. Thanks for the clarification @kroikie
