### ISSUE TITLE
[<firebase_in_app_messaging>] <Can't get FirebaseInstallations ID>

### ISSUE THREAD

**Issue by dpedrinha** [FirebaseExtended/flutterfire#3002]
I have a running firebase project with no problems.

But I just started testing in_app_messaging and I got stuck on the first step: Getting the FirebaseInstallations ID.

I just can't find it on my logcat or any log console.

I'm using:
  ```
firebase_messaging: 6.0.16
  firebase_core: 0.4.5
  firebase_auth: 0.16.1
  firebase_dynamic_links: 0.5.1
  cloud_firestore: 0.13.7
  firebase_analytics: ^5.0.15
```

I'm following this tutorial [https://pub.dev/packages/firebase_messaging](https://pub.dev/packages/firebase_messaging)

**Comment by darshankawar** [comment]
Hi @dpedrinha,
Can you please clarify if you are looking to use `firebase_messaging` or `in_app_messaging` plugin ? Looking at your description, you want to use `in_app_messaging` plugin but the tutorial link you shared is of `firebase_messaging`.

For `in_app_messaging`, follow this tutorial : https://pub.dev/packages/firebase_in_app_messaging  and you may want to add `firebase_in_app_messaging: ^0.1.2` dependency accordingly.

If problem persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample.
Thanks.

**Comment by dpedrinha** [comment]
Oh wow! Sorry, I was so tired I was looking at two different things at the same time.

You are right. With your help I focused on the firebase_messaging and all is good.

Sorry and thank you.
