### ISSUE TITLE
[Firebase Performance] Update Firebase Performance dependency to the latest

### ISSUE THREAD

**Issue by zijianjoy** [FirebaseExtended/flutterfire#3008]
**Describe the bug**
Currently Firebase Performance dependency is 17.0.0, see [code reference](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_performance/android/build.gradle#L35). We have received user report for a [bug](https://github.com/firebase/firebase-android-sdk/issues/1786) that has been fixed in 19.0.8. 

Request to upgrade Firebase Performance dependency to version 19.0.8.

**Comment by Ali1Ammar** [comment]
any update

**Comment by zijianjoy** [comment]
As of Oct 26, https://github.com/FirebaseExtended/flutterfire/blob/c2dd1dd42b3e5f0dd85f99f007767b6688c026d4/packages/firebase_core/firebase_core/android/gradle.properties has been updated to `bom` v25.12.0, which contains `firebase-perf` 19.0.9. 

Would you like to check whether this issue has been resolved on your end? Thank you!

Reference: https://firebase.google.com/support/release-notes/android#bom_v25-12-0

**Comment by markusaksli-nc** [comment]
Closing since this has been fixed
