### ISSUE TITLE
Firebase Auth (Accent problem with verification message)

### ISSUE THREAD

**Issue by andrefedev** [FirebaseExtended/flutterfire#3013]
I don't know if this error should precisely go here. But I am trying to integrate firebase auth and select the Spanish template where the message has accents. But when the message arrives by sms it arrives malformed. I have tried for several days, is there any solution for this?

![Screenshot_20200723-193256_Messages](https://user-images.githubusercontent.com/14114839/88351487-1e56ba00-cd1c-11ea-90f3-646c702f6e98.jpg)

**Comment by darshankawar** [comment]
Hi @andrefedev,
What plugin are you using to receive sms ? Is it [flutter_sms](https://pub.dev/packages/flutter_sms) ?

**Comment by andrefedev** [comment]
Hi @darshankawar I use the official firebase_auth package and call the FirebaseAuth.instance.verifyPhoneNumber method. Sometimes the message arrives correctly but from another number, those that have been incorrectly formatted are always from number #87651.

**Comment by Salakar** [comment]
@andrefedev your best bet is to submit a bug report to the Firebase team directly here: https://firebase.google.com/support/troubleshooter/report/features

We only wrap the Firebase SDKs and aren't doing anything special in FlutterFire to cause this behaviour.
