### ISSUE TITLE
[<FIREBASE_PRODUCT>] <TITLE> The plugin cloud_firestore could not be built due to the issue above.  

### ISSUE THREAD

**Issue by ahmedGibran** [FirebaseExtended/flutterfire#3014]
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 22s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      83.0s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.   
Running Gradle task 'assembleAarRelease'..

**Comment by darshankawar** [comment]
Hi @ahmedGibran,
I see there's a similar [issue](https://github.com/FirebaseExtended/flutterfire/issues/1896) that has various solutions you can try to resolve your issue.
Can you try them and see if it works for you ?

**Comment by ahmedGibran** [comment]
@darshankawar I have seen all the suggested solutions, but still the problem persists The problem only occurs when issuing a release and not debug

**Comment by ahmedGibran** [comment]
Finally I found the solution only. I had a problem issuing the SDK inside the settings file inside the gradle
First, you should go to the next track if you are facing the same problem:
Open Android Studio.
Select Open an existing Android Studio Project.
Open Gradle Script.
Now open the file "Settings"
Change the following from:
     compileSdkVersion 27
to me
     compileSdkVersion 30
Now just do it
Select Sync project with Gradle files from above
Now run Flutter clean
I really hope you have benefited

**Comment by athlona64** [comment]
> Finally I found the solution only. I had a problem issuing the SDK inside the settings file inside the gradle
> First, you should go to the next track if you are facing the same problem:
> Open Android Studio.
> Select Open an existing Android Studio Project.
> Open Gradle Script.
> Now open the file "Settings"
> Change the following from:
> compileSdkVersion 27
> to me
> compileSdkVersion 30
> Now just do it
> Select Sync project with Gradle files from above
> Now run Flutter clean
> I really hope you have benefited

This is solved me
