### ISSUE TITLE
[Cloud Messaging] Flutter app continues to receive FCM notifications after user clears the app cache

### ISSUE THREAD

**Issue by JaiMistry** [FirebaseExtended/flutterfire#3016]
**Describe the bug**
Currently within my Flutter application users can send messages to each other which is done using Firebase Cloud Messaging. The problem is if a user were to manually clear their app's cache/storage (which would also sign them out), they will continue to still receive push notifications on their device.

**To Reproduce**
1. Save fcm token
2. Close app
3. Delete cache/storage
4. Send message

**Expected behavior**
The user shouldn't receive notifications from the app after clearing its cache/storage.

**Additional context**
Is there any way to possibly detect when a user clears their cache/storage? This way it might be possible to perhaps trigger a cloud function that could remove that user's token so that they don't receive any notifications.

**Flutter doctor**
Run `flutter doctor` and paste the output below:
```powershell
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.17.5 at C:\Users\Jai Mistry\Documents\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Jai Mistry\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.47.2)
    • VS Code at C:\Users\Jai Mistry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by Minituff** [comment]
Seems like this is a common problem. I found this StackOverflow [post](https://stackoverflow.com/questions/57753125/how-to-setup-firebase-to-stop-receiving-cloud-messages-after-clear-app-cache).
I am facing this same problem. Thankfully, this is a really uncommon situation, but it is still not ideal.

**Comment by ncuillery** [comment]
@Minituff The SO link is no longer valid.

I have the same problem, I have a settings screen in my app where the user can subscribe or unsubscribe to different kinds of notifications, i.e different FCM topics.

Problem is: if I store the state of the subscriptions in storage and the user wipes the app data, I can't know which topics he has subscribed anymore.

I came to the conclusion that the state of the subscriptions should be saved in the backend (like Firestore). However it would be great if we had a API to get the current subscriptions (like `FirebaseMessasing().getTopics()`)

**Comment by russellwheatley** [comment]
Closing this as it isn't an issue with the `firebase_messaging` package.
