### ISSUE TITLE
mlvision text recognizer not working in some devices

### ISSUE THREAD

**Issue by PranayRaj2801** [FirebaseExtended/flutterfire#3018]
when i run the code im getting the following error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(textRecognizerError, Waiting for the text recognition model to be downloaded. Please wait., null)

**Comment by darshankawar** [comment]
Hi @PranayRaj2801,
Please provide `flutter doctor -v`, and a minimal complete reproducible code sample and the steps that shows the issue. Also mention the devices on which you tried.
Thanks.

**Comment by PranayRaj2801** [comment]
> Hi @PranayRaj2801,
> Please provide `flutter doctor -v`, and a minimal complete reproducible code sample and the steps that shows the issue. Also mention the devices on which you tried.
> Thanks.

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-IN)
    • Flutter version 1.17.5 at C:\src\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\iail_\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\iail_\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\iail_\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.44.1)
    • VS Code at C:\Users\iail_\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


 edge_detection: 1.0.4
  image_picker: 0.6.5+2
  carousel_slider: 2.0.0
  firebase_storage: 3.1.5
  http: 0.12.0+4
  firebase_ml_vision: 0.9.4





i tried on samsung M40(my device) and nexus 6 API28(emulator)

**Comment by darshankawar** [comment]
Hi @PranayRaj2801,
Will also need a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.
