### ISSUE TITLE
[firebase_auth] Add signInType parameter in FirebaseUser.

### ISSUE THREAD

**Issue by dungnv2602** [FirebaseExtended/flutterfire#302]
- My situtation: I want to check if sign-in type of FirebaseUser object is Email&Password type, so that I can send email verification to their email. But I don't want to send for other sign-in types.

- My workaround for now: 
![take_02](https://user-images.githubusercontent.com/19910775/66714496-d0eb0b00-ede1-11e9-8be2-3db90f808e3e.png)
=> You can see that it's very ugly.

- My sugesstion: There is a need for a parameter named 'signInType' in FirebaseUser object which contains an enum like this
'enum SignInType {
  PHONE,
  EMAIL,
  GOOGLE,
  FACEBOOK,
  TWITTER,
  GITHUB,
  OTHER,
}'

**Comment by Salakar** [comment]
Hey @dungnv2602 - I think this is already possible using the auth provider classes, e.g. 

```dart
if (firebaseUser.providerData[1].providerId == EmailAuthProvider.providerId) {
 // .. 
}
```

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/lib/src/auth_provider/email_auth_provider.dart#L8
