### ISSUE TITLE
[firebase_remote_config] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#304]

**Comment by kroikie** [comment]
@amirh
    
    The issue at https://github.com/flutter/flutter/issues/41876 has been closed and moved here. Future collaboration
    on this issue will be done here.

**Comment by creativecreatorormaybenot** [comment]
@kroikie This is still a duplicate of #72.

**Comment by kroikie** [comment]
@creativecreatorormaybenot thanks we will note that during triage.

**Comment by kirstywilliams** [comment]
Closing. Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/72
