### ISSUE TITLE
[Crashlytics] The plugin uses Fabric but it is dead/ultra-deprecated

### ISSUE THREAD

**Issue by danielgomezrico** [FirebaseExtended/flutterfire#3049]
Current setup suggest that you do the setup with fabric and it has shut down on March 31, 2020.

Check:
- Fabric site: https://get.fabric.io/ site.
- Migration to Firebase/Crashlytics: https://firebase.google.com/docs/crashlytics/migration-post-linking

**Comment by Infucio** [comment]
Any luck figuring out a way around ?

Tried the migration steps and added pod 'Firebase/Crashlytics' to podfile under pod plugins, while i got the new pod, it doesn't seem to be willing to work altogether, although no fatal issues.

**Comment by kroikie** [comment]
We are currently working on an update to the crashlytics plugin which will migrate off the fabric SDKs. However this will still not support fatal crashes so flutter errors will still be reported as non fatals.

**Comment by AndrewSheetMetal** [comment]
So, I had issues, 
that the app gave me the expected log output when I tried 
`Crashlytics.instance.crash();`
but the Firebase Console did not recognized any Crashlytics implementation.
It always shows the "add SDK and force a crash" loading indicator.

For Android I figured out a solution:
android/app/build.gradle:
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-crashlytics:17.1.1' 
}

// For Crashlytics
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
```

android/build.gradle:
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'  // Google Services plugin
        
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
}

```

For iOS it did not worked:
I added 
`pod 'Firebase/Crashlytics'`
but Firebase Console still does not recognize my crashlytics implementation

After I read this issue and also https://github.com/FirebaseExtended/flutterfire/issues/2038
I think I just had luck, that it works for android now.

However, does anyone can help me setting up crashlytics for iOS?

**Comment by wkrause13** [comment]
@AndrewSheetMetal, you may have already tried this, but did you try launching your application from the simulator directly? I had trouble getting crashes to show up for iOS until I closed my app, closed Xcode and then reopened my app from the simulator manually.

**Comment by Sthefanny** [comment]
> So, I had issues,
> that the app gave me the expected log output when I tried
> `Crashlytics.instance.crash();`
> but the Firebase Console did not recognized any Crashlytics implementation.
> It always shows the "add SDK and force a crash" loading indicator.
> 
> For Android I figured out a solution:
> android/app/build.gradle:
> 
> ```
> dependencies {
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.1.1'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
>     implementation 'com.google.firebase:firebase-crashlytics:17.1.1' 
> }
> 
> // For Crashlytics
> apply plugin: 'com.google.gms.google-services'
> apply plugin: 'com.google.firebase.crashlytics'
> ```
> 
> android/build.gradle:
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.3.50'
>     repositories {
>         google()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.5.0'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.3'  // Google Services plugin
>         
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
>     }
> }
> ```
> 
> For iOS it did not worked:
> I added
> `pod 'Firebase/Crashlytics'`
> but Firebase Console still does not recognize my crashlytics implementation
> 
> After I read this issue and also #2038
> I think I just had luck, that it works for android now.
> 
> However, does anyone can help me setting up crashlytics for iOS?

'm having this same problem with iOS

**Comment by AndrewSheetMetal** [comment]
> @AndrewSheetMetal, you may have already tried this, but did you try launching your application from the simulator directly? I had trouble getting crashes to show up for iOS until I closed my app, closed Xcode and then reopened my app from the simulator manually.

It doesn't work on real device and simulator

**Comment by lewisstevens1** [comment]
> We are currently working on an update to the crashlytics plugin which will migrate off the fabric SDKs. However this will still not support fatal crashes so flutter errors will still be reported as non fatals.

Is there anyway we can follow this? It would help to know when we can transition as we keep having people mention the deprication notice all alot.

**Comment by mvolpato** [comment]
It looks like [0.2.0](https://pub.dev/packages/firebase_crashlytics/changelog#020) uses the Firebase Crashlytics SDK.

There is a [migration guide](https://firebase.flutter.dev/docs/migration/) for us to migrate from the Fabric version to the Firebase version.
