### ISSUE TITLE
[firebase_auth] signInAnonymously() returns new user on Android each time

### ISSUE THREAD

**Issue by lukaszciastko** [FirebaseExtended/flutterfire#3053]
Calling `FirebaseAuth.instance.signInAnonymously()` on Android creates a new anonymous user every time.

On the web, the current user is being returned if it is already signed in.

I haven't tested this on iOS.

**Expected behavior**

As per documentation, if there is an anonymous user signed in already, it should be returned.
This behaviour is correct on the Web but incorrect on Android.

**Additional context**

I'm using firebase_auth: ^0.16.1. I only tested this bug on Android and on the Web.

**Flutter doctor**

```
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.3)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by kroikie** [comment]
@Ehesp do you think this will be resolved in the coming auth update?

**Comment by kroikie** [comment]
@lukaszciastko I'm not able to repro this issue. I'm using the example app in the firebase_auth plugin and from there [I can call isgnInAnonymously](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#L349) multiple times and it returns the same user.

Can you try with the example app and see if you are still getting a new user each time?

**Comment by lukaszciastko** [comment]
@kroikie, I did some testing with the example app, and, initially, I couldn't reproduce the issue until I found the missing link - you need to log in with email/password (I haven't tried other methods) first.

So, if you install the app (I completely forgot to clear cash when re-installing my app) and try to log in anonymously - there is no issues and you get the same user each time.

However, the following steps should let you reproduce the error:

1. Sign in with email & password.
2. Sign in anonymously. Your previous account is signed out and you get a new UID.
3. Sign in anonymously again. You're getting a new account but you should get the same account.
4. Sign out.
5. Sign in anonymously. You get a new UID.
6. Sign in anonymously again - you get the same UID as before.

I wasn't able to run the app against firebase_auth from the master branch - I get issues solving dependencies, but I tested this against _Latest: 0.16.1_ and _Prerelease: 0.17.0-dev.1_, and the behaviour is consistent.

**Comment by darshankawar** [comment]
Hi @lukaszciastko,
Can you try with latest `firebase_auth` [version](https://pub.dev/packages/firebase_auth/install) on latest stable or master and see if you still experiencing the issue ? 
Thanks.
