### ISSUE TITLE
Firebase Core - Switch environments on the fly

### ISSUE THREAD

**Issue by ollydixon** [FirebaseExtended/flutterfire#3054]
Just like the JS version it would be super handy if we could switch environments say (dev/prod) on the fly.
There is an implementation of FirebaseApp.config but it's disabled during runtime. Not sure why.

At the moment it's really difficult to determine on TestFlight/Google Play etc what is the "dev/prod" build using Flutter and building twice is annoying.

**Comment by kroikie** [comment]
Are you trying to point to a different project on the fly? The current [dev version of core](https://pub.dev/packages/firebase_core/versions/0.5.0-dev.2) does allow you to initialize different apps then you can determine which FirebaseApp is used when retrieving instances of other plugins like `firestore` for example:

```await Firebase.initializeApp(
    name: 'SecondaryApp',
    options: const FirebaseOptions(
        appId: 'my_appId',
        apiKey: 'my_apiKey',
        messagingSenderId: 'my_messagingSenderId',
        projectId: 'my_projectId'
    )
);
```

```FirebaseApp secondaryApp = Firebase.app('SecondaryApp');

Firestore firestore = Firestore.instanceFor(
  app: secondaryApp
);

firestore
  .collection('users')
  .snapshots()
  .listen((QuerySnapshot snapshot) {
     // Query snapshot of the users collection on the SecondaryApp
  });
```

**Comment by ollydixon** [comment]
@kroikie thanks; is there any ETA when that would be in production? We cannot use Flutter dev for production pipelines :-)

This would be really really awesome if it worked in Prod, being able to switch environments is key for testers. Installing different builds and making multiple builds for 1 app (imagine 5 builds for 1 version..) is just miserable corporate experience.

**Comment by ollydixon** [comment]
@kroikie kroikie

I created a project switcher but I'm having some problems with the dependencies.

Currently have

```
  firebase_core: ^0.5.0-dev.2
  cloud_firestore: ^0.14.0-dev.1
  firebase_auth: ^0.17.0-dev.2
  firebase_messaging: ^7.0.0-dev.1
  firebase_dynamic_links: ^0.5.0+11
```

But getting the following error

```
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.0-dev.1, which depends on
          Firebase/CoreOnly (~> 6.26.0)
    Specs satisfying the `Firebase/CoreOnly (= 6.23.0), Firebase/CoreOnly (~> 6.26.0)` dependency were found, but they required a higher minimum deployment target.
```

Also for anyone that is interested the switcher looks like so:
```

import 'dart:io';
import 'package:firebase_core/firebase_core.dart';
import 'package:path_provider/path_provider.dart';

final fileName = "firebase_config";

enum FirestoreConfigSetting { DEV, PROD }
FirestoreConfigSetting currentFirestoreConfig;

loadFireStoreConfig() async {
  final dir = await getApplicationDocumentsDirectory();
  final file = await File(dir.path + '/' + fileName);
  final exists = await file.exists();

  String config = await file.readAsString();

  if (!exists) {
    config = 'DEV';
  } else {
    config = await file.readAsString();
  }

  if (config == 'DEV') {
    currentFirestoreConfig = FirestoreConfigSetting.DEV;
    Firebase.initializeApp(
      name: --',
      options: FirebaseOptions(
        projectId: '--',
        databaseURL: '--',
        apiKey: '--',
        appId: Platform.isIOS
            ? '--'
            : '--',
        iosBundleId: '--',
        androidClientId:
            '--',
        iosClientId:
            '--',
        storageBucket: '--',
        messagingSenderId: '--',
      ),
    );
  }
  if (config == 'PROD') {
    currentFirestoreConfig = FirestoreConfigSetting.PROD;
    Firebase.initializeApp(
      name: '--',
      options: FirebaseOptions(
        projectId: '--',
        databaseURL: '--',
        apiKey: '--',
        appId: Platform.isIOS
            ? '--'
            : '--',
        iosBundleId: '--',
        androidClientId:
            '--',
        iosClientId:
            '--',
        storageBucket: '--',
        messagingSenderId: '--',
      ),
    );
  }
}

switchFirestoreConfig(FirestoreConfigSetting direstoreConfigSetting) async {
  final dir = await getApplicationDocumentsDirectory();
  final jsonFile = File(dir.path + '/' + fileName);
  if (direstoreConfigSetting == FirestoreConfigSetting.DEV) {
    jsonFile.writeAsStringSync("DEV");
  }
  if (direstoreConfigSetting == FirestoreConfigSetting.PROD) {
    jsonFile.writeAsStringSync("PROD");
  }

  await loadFireStoreConfig();
}
```

Is loaded in 'main' like so:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await loadFireStoreConfig();

  runApp(MyApp());
}
```

**Comment by ollydixon** [comment]
Having some issues with the dependencies

At the moment I've got:

```
  firebase_core: ^0.5.0-dev.2
  cloud_firestore: ^0.14.0-dev.1
  firebase_auth: ^0.17.0-dev.2
  firebase_messaging: ^7.0.0-dev.1
  firebase_dynamic_links: ^0.5.0+11
  firebase_analytics: ^6.0.0-dev.1
```

But there are tons of errors with the pods. (cleaned, updated, removed lock, etc)

Is there anything I'm supposed to do with these dev packages?

**Comment by darshankawar** [comment]
Hi @ollydixon,
There has been recent [updates](https://firebase.flutter.dev/) on Firebase plugins and I'd encourage you to update each of the listed above to latest and see if you are still getting the issues.
Thanks.

**Comment by ollydixon** [comment]
@darshankawar thanks for the reply; I'm using the new versions now but there's some issues with the pods adding various build phases that break our build servers. Also it seems to be incompatible with Flutter 1.20.X

The switching doesn't seem to work either, probably the most important thing for us and Firebase :-)
