### ISSUE TITLE
[firestore_core] Release build failing due to  androidx incompatibility

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#306]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.4\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Debug build is fine
release build is failing

**Comment by kroikie** [comment]
@bij0y

The issue at https://github.com/flutter/flutter/issues/42041 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @bij0y
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Hi @bij0y
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/17)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
