### ISSUE TITLE
Widgets are not rendering or building on Notification Click (firebase_messaging)

### ISSUE THREAD

**Issue by ganger1** [FirebaseExtended/flutterfire#3063]
@kroikie flutter_local_notifications library for Notification everything is working fine. But in Android, if an App is removed from App stack (Slide remove from recent Activity) than I got the notification and click on it, Widgets are not rendered properly, Buttom Navigation, AppBar, Text are disappearing.

[https://stackoverflow.com/questions/63178927/flutter-widgets-are-not-rendering-on-notification-click](url)

**Flutter Doctor**
`[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!
`

**Comment by darshankawar** [comment]
Hi @ganger1,
`flutter_local_notifications` is a 3rd party plugin. Can you try the same steps with only using `firebase_messaging` and see if you still experience the issue ?
