### ISSUE TITLE
[dynamic_links] No error checking for bad uriPrefix

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#3064]
When creating a `DynamicLinkParameters` with a _bad_ `uriPrefix`, the subsequent call to `buildShortLink` does not respond.

Consider the following code:
```dart
final dynamicLinkParameters = DynamicLinkParameters(
  uriPrefix: 'https://abc123.app.goo.gl',
  link: Uri.parse('https://example.com/'),
  androidParameters: AndroidParameters(
      packageName: 'com.example.android',
      minimumVersion: 125,
  ),
  iosParameters: IosParameters(
      bundleId: 'com.example.ios',
      minimumVersion: '1.0.1',
      appStoreId: '123456789',
  ),
  googleAnalyticsParameters: GoogleAnalyticsParameters(
      campaign: 'example-promo',
      medium: 'social',
      source: 'orkut',
  ),
  itunesConnectAnalyticsParameters: ItunesConnectAnalyticsParameters(
    providerToken: '123456',
    campaignToken: 'example-promo',
  ),
  socialMetaTagParameters:  SocialMetaTagParameters(
    title: 'Example of a Dynamic Link',
    description: 'This link works whether app is installed or not!',
  ),
);
```

If the `uriPrefix` was just `'abc123.app.goo.gl'` (missing the `https://`), then the subsequent call to build the short link simply does not respond:

```dart
    final shortDynamicLink = await dynamicLinkParameters.buildShortLink();
```

Obviously, I figured this out the hard way.  😒 

**Expected behavior**
I would expect one of the following behaviors when a `uriPrefix` is missing a _uri scheme_:
1. Defaults to `https`.
2. `DynamicLinkParameters` constructor throws an invalid argument exception.
3. `buildShortLink` method throws an invalid argument exception.

A _hang_ was most unexpected and frustrating.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by russellwheatley** [comment]
Hey @awhitford, we have reworked the dynamic links plugin  and we have made `uriPrefix` a required property as can be seen [here](https://github.com/FirebaseExtended/flutterfire/blob/9476444e2fa25796b32bb31e5dba9ace9ead1e36/packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/dynamic_link_parameters.dart#L12). Thanks.
