### ISSUE TITLE
Dart only package

### ISSUE THREAD

**Issue by pdmshrestha** [FirebaseExtended/flutterfire#3065]
Currently using firebase on flutter requires native configuration and dependencies. Is There any plan for dart only firebase package? Similar to firebase web?

**Comment by darshankawar** [comment]
Hi @pdmshrestha,
There are couple of dart firebase packages available.

https://pub.dev/packages/firebase
https://pub.dev/packages/firedart

See if they serves per your requirement.

**Comment by pdmshrestha** [comment]
Thanks. I am aware of those packages. My question was,  is there any plan for official package?

**Comment by darshankawar** [comment]
Well, the https://pub.dev/packages/firebase plugin is developed by Google and Firebase team members. I'll leave this issue open for further tracking.

**Comment by kroikie** [comment]
Hi @pdmshrestha the goal is to use the existing native SDKs to provide support in a many places as possible. Building Dart implementations of existing native SDKs is not on the roadmap.
