### ISSUE TITLE
[cloud_firestore]: Could not reach Cloud Firestore backend.

### ISSUE THREAD

**Issue by zeyadsharo** [FirebaseExtended/flutterfire#3067]
![image](https://user-images.githubusercontent.com/33178745/88952415-165cc400-d2a0-11ea-9339-7efe403c4790.png)
![image](https://user-images.githubusercontent.com/33178745/88952910-caf6e580-d2a0-11ea-8153-f201d66d57bb.png)
![image](https://user-images.githubusercontent.com/33178745/88953584-ced73780-d2a1-11ea-9467-ebd8434e1122.png)

```
Future getdata() async {
    Firestore db = Firestore.instance;
    var data = await db.collection('event_details').getDocuments();
    var details = data.documents.toList();
    details.forEach((element) {
      print(element.documentID);
    });
  }
```
W/Firestore(  885): (21.3.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore(  885):
W/Firestore(  885): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
Reloaded 1 of 537 libraries in 344ms.

**Comment by kroikie** [comment]
@zeyadsharo Could you provide some context around when this issue shows up:

1. Does it show up in all cases or just sometimes?
1. Is it happening on a particular platform iOS or Android?
1. Any steps to reproduce?
1. Are you seeing the same with the example app in this repo?
1. Can you try using the [pre-release](https://pub.dev/packages/firebase_core/versions/0.5.0-dev.2) version of the firestore plugin and see if the issue persists?
