### ISSUE TITLE
[Cloud_Firestore] Release build failing due to Androidx incompatibility

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#307]
I'm getting
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.9.13+1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

The debug build is fine
but release build is failing.

I tried every solution I got here.
minSdkVersion, compileSdkVersion everything

**Comment by kroikie** [comment]
@bij0y

The issue at https://github.com/flutter/flutter/issues/42040 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @bij0y
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Hi @bij0y
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/17)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
