### ISSUE TITLE
firebase core web error

### ISSUE THREAD

**Issue by tahrimhossain** [FirebaseExtended/flutterfire#3070]
I am trying to setup Firebase in my Flutter app. I have followed all the directions in the firebase website and also the flutter website to setup firebase including editing the pubspec.yaml file, editing the app level build.gradle file and the project level build.gradle file. when i run the app i get this error

`/Users/tahrim/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin 2.java:7: error: class FirebaseCoreWebPlugin is public, should be declared in a file named FirebaseCoreWebPlugin.java
public class FirebaseCoreWebPlugin implements FlutterPlugin {           
       ^                                                                
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':firebase_core_web:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 2s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         3.0s
Exception: Gradle task assembleDebug failed with exit code 1`

flutter doctor output

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-BD)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] Connected device (1 available)

• No issues found!
`

**Comment by kroikie** [comment]
Hi @tahrimhossain this looks like your android build is failing. Could you include the firebase dependencies you are using. Also what are you trying to run, web app or android app?

**Comment by tahrimhossain** [comment]
i am trying to build an android app.
my dependencies are -
firebase_auth: ^0.16.1
cloud_firestore: ^0.13.7

**Comment by Salakar** [comment]
Please could you try the latest versions, I believe this was now fixed.
