### ISSUE TITLE
[firebase_storage] FirebaseStorage.instance.ref().child(path).getDownloadURL never returns

### ISSUE THREAD

**Issue by MathiasSolling** [FirebaseExtended/flutterfire#3074]
When 10+ different users are requesting getDownloadURL for the same path at the same time, for some users it hangs in await and never returns:

`
FirebaseStorage.instance.ref().child(path).getDownloadURL();
`

I'm referencing mp3 files and I have validated that the files are present in storage and 9 out of 10 clients are able to fetch the files. Once it fails, shortly after the client that first failed to get the download URL is able to fetch another one without problems.

**Comment by noobcoder17** [comment]
Is it important to get the download URL from a storage reference in the client side ? 
If it is not, then you can save a download URL in Cloud Firestore or in Realtime Database and give the URL from there to the client side every time.

I may be wrong, as I don't know what is your purpose in doing this. 
```FirebaseStorage.instance.ref().child(path).getDownloadURL();```

**Comment by russellwheatley** [comment]
Hey @MathiasSolling, the storage package has gone through a number of major releases since this issue. Are you able to let us know if this issue persists? Thanks.
