### ISSUE TITLE
[Firebase Core] FutureBuilder With Firebase.initializedApp() Not Resolved

### ISSUE THREAD

**Issue by andrefedev** [FirebaseExtended/flutterfire#3075]
I'm trying to initialize Firebase with FutureBuilder as the documentation recommends, but I'm having problems. With a simple application placing the FutureBuilder in a Widget or even in the main void, the promise is never resolved and remains pending.

    firebase_core: "0.5.0-dev.2"
    firebase_analytics: "^6.0.0-dev.1"
    firebase_auth: "0.17.0-dev.1"

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale es-419)
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    [✓] Android Studio (version 4.0)
    [✓] VS Code (version 1.47.3)
    [✓] Connected device (1 available)

    • No issues found!

### Code Example..

    void main() {
      runApp(MyApp());
    }

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter',
          debugShowCheckedModeBanner: false,
          home: HomeScreen(),
        );
      }
    }

    class HomeScreen extends StatefulWidget {
      @override
      _HomeScreenState createState() => _HomeScreenState();
    }

    class _HomeScreenState extends State<HomeScreen> {
      @override
      Widget build(BuildContext context) {
        return FutureBuilder<FirebaseApp>(
          future: Firebase.initializeApp(),
          builder: (BuildContext context, AsyncSnapshot<FirebaseApp> snapshot) {
            if (snapshot.hasData) {
              // this never happens the promise remains unresolved.
              return CatalogScreen();
            } else {
              return Container(
                color: Colors.white,
                child: CircularProgressIndicator(),
              );
            }
          },
        ),
      );
    }

Another problem that I notice is that when the application is initialized for the first time, the animation of the **CircularProgressIndicator** widget never occurs, it remains static.

**Comment by TahaTesser** [comment]
Hi @andrefedev 
Can you please explain why you checking data in `initializedApp`. Did you mean to Firetore to heck data for catalog screen?

**Comment by Ehesp** [comment]
There could be an error being thrown but you don't check for that, try something like:

```dart
class FlutterFireInit extends StatelessWidget {
  final Future<FirebaseApp> _init = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _init,
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          return Center(
              child: Text(
                  "Something went wrong during initalization: ${snapshot.error}"));
        }

        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return CatalogScreen();
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}
```
