### ISSUE TITLE
[firebase_auth] User created by Email and Password method is able to login without verify his Email

### ISSUE THREAD

**Issue by ingluife** [FirebaseExtended/flutterfire#3076]
**Describe the bug**
A user created by email and password using the method `createUserWithEmailAndPassword` is able to login after execute `updateProfile` method, with have no verified his email with the link sent.

I have a user flow, where the user signUp with Email and password. Because the method `createUserWithEmailAndPassword` only accepts the `email` and `password` parameters, I update the user data (displayName) before sent the verification link.
When the user uses the verification link sent before, firebase says `Try to verify your email again....`. In this context, the user is able to log in with has no verified his email.

**To Reproduce**
1. User the firebaseAuth method `createUserWithEmailAndPassword`
2. Update the user data using the FirebaseUser method `updateProfile` to set the DisplayName
4. Try to verify the user email with the link received.

**Expected behavior**
If the user has no verified his email with the verification link sent to his email couldn't log in.

**Additional context**
- The package version used is: **firebase_auth: ^0.15.5+3**

This is a Dart code used:
```    
AuthResult result = await _firebaseAuth
    .createUserWithEmailAndPassword(email: userEmail, password: userPassword).catchError((error){
           _errorMessage = error.message;
           _errorCode = error.code;
     }).then((AuthResult authResult) async {

          ///Update the user profile to set the **displayName**
          UserUpdateInfo userUpdateInfo = UserUpdateInfo();
          userUpdateInfo.displayName = userFullName;
          await authResult.user.updateProfile(userUpdateInfo);

          ///Send the verification link to the user
          await authResult.user.sendEmailVerification();
          return authResult;
     });
```

This is the result when the user uses the verification link:

<img width="496" alt="Screen Shot 2020-08-01 at 23 11 18" src="https://user-images.githubusercontent.com/17582750/89113839-52348c80-d44c-11ea-91a6-d4400d149731.png">

**Flutter doctor**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.5 19F101, locale en-AR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by darshankawar** [comment]
Hi @ingluife,
I see that you are on `v1.12.13+hotfix.8` whereas the latest stable is `1.17.5`. Also the latest `firebase_auth` plugin version is `0.16.1`. Can you try to upgrade to these versions and see if you still experience the issue ?

**Comment by Salakar** [comment]
Please try the latest version of the plugin; https://firebase.flutter.dev/docs/auth/overview - it was recently reworked. If it's still an issue then please provide a reproducible example, thanks.
