### ISSUE TITLE
Querying to different firebase project

### ISSUE THREAD

**Issue by casualcoder404** [FirebaseExtended/flutterfire#3077]
**Is your feature request related to a problem? Please describe.**
I've two different projects on firebase. But I'd like to access or establish communication between them.

**Describe the solution you'd like**
There should be some documentation on how to achieve this through cloud_firestore

**Additional context**
https://firebase.googleblog.com/2016/12/working-with-multiple-firebase-projects-in-an-android-app.html

**Comment by russellwheatley** [comment]
If I understand the issue correctly, this is already possible. [See here](https://firebase.flutter.dev/docs/core/usage#initializing-secondary-apps)
