### ISSUE TITLE
[cloud_firestore][firebase_auth] Cant build iOS app on due to flutter framework not found GoogleDataTransportCCTSupport

### ISSUE THREAD

**Issue by sinhaseemant** [FirebaseExtended/flutterfire#3078]
Describe the bug
I have tried almost everything. I've tried different versions of cloud_firestore too.It works well on android but there's something wrong with iOS version and firebase because same problem is occurring in Firebase Auth package nothing seems to work
To Reproduce
1.Create a new project and add latest cloud_firestore package and firebase_auth package
2.Run without debugging on an iOS emulator
3.Build will be failed with following error
**Expected behavior**
Flutter app should build

**Additional context**
logs for error

` Xcode build done.                                           74.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳

   ld: framework not found GoogleDataTransportCCTSupport
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
`

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.141, on Mac OS X 10.15.4 19E287,
    locale en-IN)
    • Flutter version 1.21.0-6.0.pre.141 at
      /Users/Languagenectar/Documents/flutter
    • Framework revision c748f1a7aa (35 hours ago), 2020-07-31 17:45:18 -0700
    • Engine revision 280bbfc763
    • Dart version 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/Languagenectar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/Languagenectar/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category
```

**Comment by darshankawar** [comment]
Hi @sinhaseemant,
Can try following to see if it works for you ?

```
cd ios
pod deintegrate
cd ..
flutter pub cache repair
flutter build ios
```

**Comment by sinhaseemant** [comment]
> Hi @sinhaseemant,
> Can try following to see if it works for you ?
> 
> ```
> cd ios
> pod deintegrate
> cd ..
> flutter pub cache repair
> flutter build ios
> ```

same issue persists ...didnt work

**Comment by darshankawar** [comment]
@sinhaseemant,
Can you try following:

1. Delete ios/App.framework
2. Delete Podfile.lock
2. cd ios and then run `pod repo update` followed by `flutter run`

**Comment by riccardo-lomazzi** [comment]
I have the same errors and none of the above solutions worked for me.
I'm on Flutter 1.20 Stable Channel.

**Comment by stx** [comment]
Same problem.

**Solution:** Remove this from *Xcode > Targets > Runner > Other Linker Flags:*

    -framework
    GoogleDataTransportCCTSupport

Ran into this problem with *flutter_plugin_android_lifecycle* as well as seen in https://github.com/flutter/flutter/issues/63220.

No idea if this is a good idea or not, but Flutter won't build otherwise.

Is **Other Linker Flags** safe to modify? What builds the list?

**Comment by ThinkSimple** [comment]
> Same problem.
> 
> **Solution:** Remove this from _Xcode > Targets > Runner > Other Linker Flags:_
> 
> ```
> -framework
> GoogleDataTransportCCTSupport
> ```
> 
> Ran into this problem with _flutter_plugin_android_lifecycle_ as well as seen in [flutter/flutter#63220](https://github.com/flutter/flutter/issues/63220).
> 
> No idea if this is a good idea or not, but Flutter won't build otherwise.
> 
> Is **Other Linker Flags** safe to modify? What builds the list?

Fixed it for me!

**Comment by Salakar** [comment]
Closing this as there seems to be a solution provided above. I'd also recommend trying the latest versions of the plugins that were release last week - lots of updates & improvements.
