### ISSUE TITLE
Failing to use google authorization + flutter fire

### ISSUE THREAD

**Issue by paapu88** [FirebaseExtended/flutterfire#3079]
Dear Developers,
I'd like to use google authorization and firebase database in my flutter+dart in android. Have not managed this yet.
Tried various things and finally cloned this repo to see if it works, no luck.
So below is what I did:

```
git clone https://github.com/FirebaseExtended/flutterfire.git
cd flutterfire/packages/firebase_auth/firebase_auth/example/lib
flutter run
Changing current working directory to:
/home/hu-mka/git/Omat/flutterfire/packages/firebase_auth/firebase_auth/example
Because firebase_auth_example depends on firebase_auth from path which depends on firebase_core ^0.5.0-dev.1, firebase_core ^0.5.0-dev.1 is required.
So, because firebase_auth_example depends on firebase_core ^0.4.4, version solving failed.
Running "flutter pub get" in example...                                 
pub get failed (1; So, because firebase_auth_example depends on firebase_core
^0.4.4, version solving failed.)
```

Tried removing dependencies using 'any' but failed with that.  **Is there a working example somewhere (google authorization + firebase)?**
(I have ubuntu 20.04, and usb connected android phone)
Terveisin, Markus

**Comment by darshankawar** [comment]
Hi @paapu88,
Can you specifically try `firebase_core: ^0.4.5` or the dev pre-release version `firebase_core: ^0.5.0-dev.2` to see if this atleast gets you started ?
Thanks.

**Comment by kroikie** [comment]
@paapu88 Please set the `firebase_core` version in the example `pubsepc.yaml` to `firebase_core: ^0.5.0-dev.2`. Sorry for the confusion here, I'll update the example to avoid this issue.

**Comment by paapu88** [comment]
Thank's and sorry for slow response (this is a weekend hobby project...).
After git pull today (8.8.2020) the procedure I described above works out of the box.
Thanks for the quick fix!

**Comment by paapu88** [comment]
But it looks like in the demo (and what I tested earlier) that one actually cannot log in using the demo. I attach here three screen shot to clarify. Google login comes ok, but after that nothing happens (a white stripe is showing after google login, though)
![Screenshot_20200808-093803](https://user-images.githubusercontent.com/6195764/89704346-b4652400-d95b-11ea-8ce7-f24c4e231d27.png)
![Screenshot_20200808-093841](https://user-images.githubusercontent.com/6195764/89704350-bcbd5f00-d95b-11ea-83fc-1c6026291d1e.png)
