### ISSUE TITLE
[firebase_auth] java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference

### ISSUE THREAD

**Issue by fabioselau077** [FirebaseExtended/flutterfire#3080]
How to resolve? It was working correctly and overnight it was giving this error...
![image](https://user-images.githubusercontent.com/57275833/89127836-eb9c8680-d4be-11ea-8ffd-a57040fc74c8.png)

**Comment by darshankawar** [comment]
Hi @fabioselau077,
Can you try `flutter pub cache repair` or `flutter clean` and then run `flutter run` to see if it works for you ?
If problem persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by kroikie** [comment]
@fabioselau077 this looks like you are trying to sign in with a null credential. Could you confirm that the credential you are using to sign in is non-null?
