### ISSUE TITLE
firebase_auth doesn't expose checkActionCode neither applyActionCode?

### ISSUE THREAD

**Issue by dariocasas** [FirebaseExtended/flutterfire#3082]
Hello! When trying  to customise Firebase authentication templates with custom dns and flutter web, I found this problem:

 ```
checkCode() async {
    FirebaseAuth auth = FirebaseAuth.instance;

    String code = 'xxxxxxx';
    try {
      await auth.checkActionCode(code);
      await auth.applyActionCode(code);

      // If successful, reload the user:
      await FirebaseAuth.instance.currentUser()
        ..reload();

    } catch (e) {
      if (e.code == 'invalid-action-code') {
        print('The code is invalid.');
      }
    }
```
where Dart analysis says:
error: The method 'checkActionCode' isn't defined for the type 'FirebaseAuth'.
error: The method 'applyActionCode' isn't defined for the type 'FirebaseAuth'.

I'm using  firebase_auth 0.16.1

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-6.0.pre.141, on Microsoft Windows [versão 10.0.18363.959], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)

• No issues found!

Thanks

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

Please could you update to the new version as these two methods are now supported. If you have any problems with them or the updated plugins please raise a new GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
