### ISSUE TITLE
 FAILURE: Build failed with an exception.  

### ISSUE THREAD

**Issue by sandroarnaldo** [FirebaseExtended/flutterfire#3085]
FAILURE: Build failed with an exception.

```
* Where:
Build file '/Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/build.gradle' line: 18

* What went wrong:
Could not compile build file '/Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/build.gradle'.
> startup failed:
  build file '/Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/build.gradle': 18: unexpected token: } @ line 18, column 1.
     }
     ^

  1 error
```

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```
BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!
```

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}
```

```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com" // Google's Maven repository
        }
    }
}

```
```
rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by darshankawar** [comment]
Hi @sandroarnaldo,
There's seems to be an extra closing bracket per the error:

```
build file '/Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/build.gradle': 18: unexpected token: } @ line 18, column 1.
     }
     ^
```

Also, this issue doesn't seem to be related to Firebase. If problem persists and there are no Firebase related plugin which is causing the issue, please consider opening issue in flutter/flutter repo (https://github.com/flutter/flutter/issues)

Closing this, as this doesn't seem to be an issue with any of the Firebase plugins. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by sandroarnaldo** [comment]
I commented on line 18, and now there is another connection error with facebook login

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/sandroarnaldodasilva/projetosflutter/colorsdj/android/app/src/main/AndroidManifest.xml:13:9-14:60: AAPT: error: resource string/faceboook_app_id (aka br.com.colorsdj.colorsdj:string/faceboook_app_id) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm)

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}


allprojects {
    repositories {
        // google()  ////// line 18 unexpected token///////
        jcenter()
        maven {
            url "https://maven.google.com" // Google's Maven repository
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by sandroarnaldo** [comment]
I/Choreographer(12658): Skipped 391 frames!  The application may be doing too much work on its main thread.
E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
I/flutter (12658): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)
E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!
