### ISSUE TITLE
[<FIREBASE_ADMOB>] <Video ad volume control for Ads>

### ISSUE THREAD

**Issue by uzumaki258** [FirebaseExtended/flutterfire#3086]
Hello, 

Google Mobile Ads allowed developers to control the volume of the ad have sounds.

https://developers.google.com/admob/android/global-settings

It makes the app really user-friendly because the ads won't startle users.
Really helpful if it is available in Flutter.
Thank you

**Comment by darshankawar** [comment]
May be related to [2673](https://github.com/FirebaseExtended/flutterfire/issues/2673)

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
