### ISSUE TITLE
[<FIREBASE_PRODUCT>] <Error After installing cloud_firestore: ^0.14.0-dev.1>

### ISSUE THREAD

**Issue by sachavieuxroy** [FirebaseExtended/flutterfire#3088]
After installing cloud_firestore: ^0.14.0-dev.1
error: Undefined name 'FirestoreWeb'. (undefined_identifier at [sachavieuxroycom] lib\generated_plugin_registrant.dart:19)

**Comment by Ehesp** [comment]
Please follow the issue template, showing some code samples too. Without this we can't help.

**Comment by sachavieuxroy** [comment]
Project does not work with flutter web as it did before, just a few week ago . The code to the project https://drive.google.com/file/d/1_awFqZiMDMmMGYscTZKQRFnB3bEmlypE/view?usp=drivesdk

------------------------------------------------------------------------

NAME: Sacha VIEUX ROY

EMAIL: mail@sachavieuxroy.com

PREFERED TELEPHONE:  +33.6.95.54.11.17

U.S.A TELEPHONE: +1-407-792-0854

WHATSAPP ID (PHONE):  +33 6 95 54 11 17

________________________________
