### ISSUE TITLE
Cloud Firestore - A method to get adjacent documents with one call

### ISSUE THREAD

**Issue by zenkog** [FirebaseExtended/flutterfire#3089]
**Is your feature request related to a problem? Please describe.**

When we want to provide the adjacent documents to the user we had to do two queries. I.e: to get the previous documents in the list and to get the preceding documents in the list.
But the problem is that it is quite tedious to fetch these documents because we don't have the reference for the data before and after that, thus 
we need to use something like `startAt` or `endAt` with `limit`.
We need to fetch twice (once for the data before and once for the data after) then we need to combine them in the list which could be error prone

**Describe the solution you'd like**
I'd like to suggest to create a function that can get a document and its adjacent documents. Something like `.getDocumentsWithAdjacent` (apologize for a lousy name, just on top of my head)
So instead of using `startAt` or `endAt` kind of commands, we can use parameters something like `previousCount` and `afterCount`.

Usage:
```
Firestore.instance.collection('restaurants').document(docId).getDocumentsWithAdjacent(previousCount: 3, afterCount: 6);
```

**Additional context**
For the sake of user experience, when a user select a data (Document) we wanna make available the adjacent data to the user (i.e: both the previous data and the preceding data). Probably like 2-3 data previous data and 4-6 preceding data, which the developer can set by themselves. Therefore, without fetching the whole list of documents from the collection nor making multiple function calls, we can get enough data for the user to navigate around with better user experience. Something like shining a "spotlight" to a location.

In many cases when an app need to show a list of something that needs two level of display. Such as reviews, profiles, orders, etc. It needs to be shown in two levels: 
1. Overview / list without details
2. Detailed page.

In the past, people had to go back and forth between detailed page and overview / list page. But this behavior is disappearing now. Just like Instagram app for example, the user can tap on a post to see its detail. Then the user can scroll up and down to see the adjacent post details easily because when the user tap on a post, some of the data before and after that post also being loaded.

Another example: A restaurant search app that shows a list of restaurant in an area.
When a user tap somewhere in the middle of the list of restaurant, then the restaurant details is being displayed, but the user want to scroll (either horizontally or vertically) to see the adjacent restaurant in the list so we need to load the data for that also.

So I hope this could be a good suggestion and could help many developers

Thanks

**Comment by Ehesp** [comment]
Hello - thanks for the suggestion. I'm afraid we won't be implementing that since it moves away from the Firebase APIs. Another reason for not doing this, is that it would still have to internally query the additional documents, but this would be done behind the scenes meaning you get no visibility on the extra database reads (potentially causing unexpected costs).

Something like this would need to land in the main Firebase SDKs. Maybe submitting your request [here](https://firebase.google.com/support/troubleshooter/report/features) would be best. Thanks!
