### ISSUE TITLE
[firebase_messaging] Message lost when app terminated

### ISSUE THREAD

**Issue by alejandroaap** [FirebaseExtended/flutterfire#3091]
In the Readme file of cloud_messaging plugin, which can be found at https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging#receiving-messages , it is referenced that when app is terminated the data message on Android device is lost because the plugin not supported. In the case of ios the message is stored by FCM and delivered to app via onMessage when the app is brought back to foreground.

My question is, Are you going to implement the option to handle notifications with data when the application is finished?

**Comment by lazylazyllama** [comment]
I think the readme for android is wrong. In my case handling data messages even when the app is terminated worked after doing the following steps:

Applikation.kt
```kotlin
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
import com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {

  override fun onCreate() {
    super.onCreate()
    FlutterFirebaseMessagingService.setPluginRegistrant(this)
  }

  override fun registerWith(registry: PluginRegistry?) {
    if (registry != null) {
      FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
      FlutterLocalNotificationsPlugin.registerWith(registry.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"))
    }
  }
}
```

Also I had to set "priority" to "high" and "content_available" to "true" in the message payload:
```json
{
	"to": "/topics/schulinfoapp_beta-v4_283",
	"data": {
		"dataid": "Test data",
		"moduleId": "113a20f6-08ce-47a5-a85c-b0179b6b862a"
	},
	"priority": "high",
	"mutable_content": true,
	"content_available": true,
	"time_to_live": 86400
}
```

**Comment by lazylazyllama** [comment]
I also want to mention that: 
`FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))`

merely is a workaround and was used to be done by the GeneratedPluginRegistrant back in the days. But since android embedding v2 its not done by the GeneratedPluginRegistrant anymore because it should work without that, but it doesn't ... so we have to hack around it for a little bit right know :(

**Comment by cuong292** [comment]
@lazylazyllama its can show noti,but not possible to get the data of it

**Comment by lazylazyllama** [comment]
> @lazylazyllama its can show noti,but not possible to get the data of it
> 

Yes because normal notifications don't need dart code to be executed in the background.

But data messages need to be handled by the dart background service, which needs the plugin to implement v2 embedding correctly. There already is an open pr for that.

**Comment by cuong292** [comment]
@lazylazyllama any work arround for it yet? something like native stuff which get notification from Java code to Flutter ? I really need this for my application

**Comment by lazylazyllama** [comment]
> I think the readme for android is wrong. In my case handling data messages even when the app is terminated worked after doing the following steps:
> 
> Applikation.kt
> ```kotlin
> import io.flutter.app.FlutterApplication
> import io.flutter.plugin.common.PluginRegistry
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
> import io.flutter.plugins.GeneratedPluginRegistrant
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
> import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
> import com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin
> 
> class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
> 
>   override fun onCreate() {
>     super.onCreate()
>     FlutterFirebaseMessagingService.setPluginRegistrant(this)
>   }
> 
>   override fun registerWith(registry: PluginRegistry?) {
>     if (registry != null) {
>       FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"))
>       FlutterLocalNotificationsPlugin.registerWith(registry.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"))
>     }
>   }
> }
> ```
> 
> Also I had to set "priority" to "high" and "content_available" to "true" in the message payload:
> ```json
> {
> 	"to": "/topics/schulinfoapp_beta-v4_283",
> 	"data": {
> 		"dataid": "Test data",
> 		"moduleId": "113a20f6-08ce-47a5-a85c-b0179b6b862a"
> 	},
> 	"priority": "high",
> 	"mutable_content": true,
> 	"content_available": true,
> 	"time_to_live": 86400
> }
> ```

This code did the trick for me. That's all I can do for you. There also are tons of open issues with many many workarounds that all are somewhat similar. You should get it to be working after some playing around. Also keep in mind, that not only firebase is doing it wrong but also plugins like flutter local notifications have similar issues. So make sure that firebase really is the issue in your case.

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has been been heavily reworked, along with documentation, since this issue was raised: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
