### ISSUE TITLE
[FirebaseCorePlugin] <cannot find symbol>

### ISSUE THREAD

**Issue by gouda-s** [FirebaseExtended/flutterfire#3097]
plugin dependencies

firebase_core: ^0.4.5
cloud_firestore: ^0.13.7  

build failing with  below error

.../flash_chat/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:17: error: cannot find symbol
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FirebaseCorePlugin());
                                                                       ^
  symbol:   class FirebaseCorePlugin
  location: package io.flutter.plugins.firebase.core

**Comment by kroikie** [comment]
Please add the contents of `GeneratedPluginRegistrant.java`, I think `flutter clean` and rebuild should resolve this issue.

**Comment by gouda-s** [comment]
GeneratedPluginRegistrant.java contents:

package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FirebaseCorePlugin());
  }
}


Tried flutter clean. Still the issue persists.

**Comment by gouda-s** [comment]
Does any answers to it? unable to get through this.

**Comment by lizhuoyuan** [comment]
+1

**Comment by gouda-s** [comment]
Does anyone have anything on this??

**Comment by darshankawar** [comment]
Hi @gouda-s,
Please try upgrading `firebase_core` and `cloude_firestore` plugins to latest versions. I tried the same on latest Stable (1.20.2) and was able to build the app properly:

```
  firebase_core: ^0.5.0
  cloud_firestore: 0.14.0+2
```
```
Launching lib/main.dart on SM G975F in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
```

**Comment by gouda-s** [comment]
@darshankawar Thanks. The new version works fine. I guess issue was with the earlier version.
