### ISSUE TITLE
[cloud_firestore] WEB Expected a value of type 'JSObject<Tc>', but got one of type 'NativeJavaScriptObject'

### ISSUE THREAD

**Issue by rodgav** [FirebaseExtended/flutterfire#3098]
![image](https://user-images.githubusercontent.com/30939186/89331645-b9725c80-d657-11ea-97a5-e685285828e4.png)
flutter run -d chrome....

**Comment by kroikie** [comment]
@bankenro does this happen with any particular type of data being retrieved?

**Comment by bankenro** [comment]
> @bankenro ¿sucede esto con algún tipo particular de datos que se recuperan?
![unknown](https://user-images.githubusercontent.com/30939186/89440727-aae87b80-d711-11ea-9535-9bfecd07cf9c.png)

**Comment by bankenro** [comment]
> @bankenro ¿sucede esto con algún tipo particular de datos que se recuperan?

![InShot_20200805_115214504](https://user-images.githubusercontent.com/30939186/89441045-29451d80-d712-11ea-864c-22c5730833e3.jpg)

**Comment by darshankawar** [comment]
Hi @bankenro,
Are you still experiencing this issue ? Is this on web or mobile ?
Can you provide `flutter doctor -v` and a minimal complete reproducible code that shows the issue ?
Also please upgrade `cloud_firestore` to latest version, try again and see if it resolves your issue.
Thanks.

**Comment by bankenro** [comment]
> Hola @bankenro ,
> ¿sigues teniendo este problema? ¿Es esto en la web o en el móvil?
> ¿Puede proporcionar `flutter doctor -v`un código mínimo reproducible completo que muestre el problema?
> Además, actualice `cloud_firestore`a la última versión, intente nuevamente y vea si resuelve su problema.
> Gracias.

Well, I already updated to the new version, I do not know if it will continue to give the error on the web because the truth that obviates the tracking on the web. so that option is no longer available on the web. it would be to try. regards

**Comment by russellwheatley** [comment]
Hey @rodgav, are you still experiencing this problem?
