### ISSUE TITLE
Firebase Notification IOS

### ISSUE THREAD

**Issue by sharmavishal914** [FirebaseExtended/flutterfire#3099]
**Randomly notification stopped working on IOS.**

1) Using firebase_messaging: ^6.0.16.

2) FirebaseAppDelegateProxyEnabled is set to "NO" & Tried with false too.

3) In didFinishLaunchingWithOptions 
```
if (@available(iOS 10.0, *)) {
  [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
}
```
4) Tried with this method too 
```
override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Mixpanel.mainInstance().people.addPushDeviceToken(deviceToken) //For Mixpanel purposes, not needed if not using
    Messaging.messaging().apnsToken = deviceToken //*THIS WAS MISSING*
    super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken) //Not sure if calling super is required, but did anyway
  }
```

I am using Channel stable, v1.17.5 version of FLUTTER

I am facing this issue from last 1 week, Notifications starts coming & breaks automatically, Showing notRegistered error on api side, please help.

**Comment by luis-cruzt** [comment]
I'm having the same issue.

**Comment by sharmavishal914** [comment]
Hi @luis-cruzt ,
I found the issue, to get fcm token use
```
Stream<String> fcmStream = _firebaseMessaging.onTokenRefresh;
    fcmStream.listen((token) {
      print("Refreshed Notifications Token: $token");
      SecurityManager securityManager = sl.get<SecurityManager>();
      securityManager.notificationToken = token;
    });
```
Now its working fine,

**Comment by luis-cruzt** [comment]
After running the app directly from xcode, the notifications came again.

First i ran flutter build ios

And then opened xcode and ran the build.

Everything is working again finally.
