### ISSUE TITLE
I/Choreographer(12658): Skipped 391 frames!  The application may be doing too much work on its main thread. E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation. I/flutter (12658): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null) E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation. E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.

### ISSUE THREAD

**Issue by sandroarnaldo** [FirebaseExtended/flutterfire#3101]
I/Choreographer(12658): Skipped 391 frames!  The application may be doing too much work on its main thread.
E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
I/flutter (12658): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)
E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
E/FirebaseInstanceId(12658): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by kroikie** [comment]
@sandroarnaldo it would be useful to resubmit this issue with more details about what you are trying and what is going wrong. I'm going to close this one.
