### ISSUE TITLE
 ════════ Exception caught by image resource service ════════════════════════════ 

### ISSUE THREAD

**Issue by sandroarnaldo** [FirebaseExtended/flutterfire#3103]
════════ Exception caught by image resource service ════════════════════════════
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI sandroitj@gmail.com

When the exception was thrown, this was the stack
#0      _HttpClient._openUrl  (dart:_http/http_impl.dart:2282:9)
#1      _HttpClient.openUrl  (dart:_http/http_impl.dart:2200:7)
#2      IOClient.send 
package:http/src/io_client.dart:31
#3      HttpFileService.get 
package:flutter_cache_manager/…/web/file_service.dart:32
#4      WebHelper._download 
package:flutter_cache_manager/…/web/web_helper.dart:76
...
Image provider: CachedNetworkImageProvider("sandroitj@gmail.com", scale: 1.0) 
 Image key: CachedNetworkImageProvider("sandroitj@gmail.com", scale: 1.0): CachedNetworkImageProvider("sandroitj@gmail.com", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by kroikie** [comment]
@sandroarnaldo This does not look like a Firebase related issue. I'll close this. Feel free to open another issue with more detail on how FlutterFire may be the issue.
