### ISSUE TITLE
[flutter_auth] Listen to email verification

### ISSUE THREAD

**Issue by haarts** [FirebaseExtended/flutterfire#3112]
**Is your feature request related to a problem? Please describe.**
I'm logging in with `flutter_auth` well enough and when a new user signs up I'm fine with them being immediately logged in. But I would really like my user to verify the email address. To that end I use `sendEmailVerification`. But what I would just love is that, when the user actually verifies their email, I could listen to that event. 

**Describe the solution you'd like**
Something in line with the `onAuthStateChanged` stream would be great. Or perhaps the user property `isEmailVerified` should be a `Stream<bool>` instead of a simple `bool`.

Perhaps there's another method to achieve what I want and I'm just missing it?

**Comment by netcob64** [comment]
Same for me...
For now, I had a waiting page after signin where the user can say that he has checked the verification email (and ask to resend verification email). When he says that he has checked the verification link in the email sent by firebase, my app check for flag isEmailVerified thanks a firebase function (the only way for me to check this flag without asking the user to sign out and sign in again...)... A little boring isn't it compared to a isEmailVerified stream directly in the app....

**Comment by feinstein** [comment]
The new version of the library has a stream for this, check it out.
