### ISSUE TITLE
[cloud_firestore] Note on console for "unchecked or unsafe operations"

### ISSUE THREAD

**Issue by CaLouro** [FirebaseExtended/flutterfire#3114]
My problem is not really a bug or a problem, but I've been getting the message bellow on my debug console almost every time I build my code. 
```
Note: C:\Users\caios\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.7\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
```

Although it is working fine for me at the moment, I fear it could be a problem for the future or for some devices that try to run my app.

As stated on the message, I'm using cloud firestore version 0.13.7. And I wanted to know if there is some way to make it 'safe' or if it's a message that I should just overlook.

**Comment by Ehesp** [comment]
Shouldn't need to worry, it's more of an informational message. 

Due to how Flutter and Native work together, this is fairly common and is usually "fixed" by suppressing the output.

**Comment by darshankawar** [comment]
Hi @CaLouro,
Based on @Ehesp's comment, I am closing this as non-issue.
