### ISSUE TITLE
Firebase Analytics Flutter Example doesn't work

### ISSUE THREAD

**Issue by Dersh** [FirebaseExtended/flutterfire#3115]
**Describe the bug**
I have downloaded Flutter Example but failed to build it.

**To Reproduce**
1. Go to https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics/example
2. Clone repo for source codes
3. Do flutter pub get in the folder

**Expected behavior**
Pubs should be updated, the project should build without errors

**Flutter doctor**
Run `flutter doctor` and paste the output below:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0, on Mac OS X 10.15.5 19F101, locale ru-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (4 available)

I met 2 issues
#1
[i] flutter pub get
Running "flutter pub get" in i...                               
Could not find a file named "pubspec.yaml" in "/Users/user/Desktop/cm".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/user/Desktop/cm".)
exit code 66

#2 in main.dart
Undefined name 'Firebase'.
Try correcting the name to one that is defined, or defining the name.dartundefined_identifier

**Comment by darshankawar** [comment]
Hi @Dersh,
I tried to replicate the issue you mentioned, but I was able to run firebase_analytics example properly without any issues.
I am on latest Stable (1.20.1).  

I cloned the `flutterfire` repo and then opened the specific package example `firebase_analytics` as  flutterfire -> packages ->firebase_analytics ->firebase_analytics -> example.

![Screen Shot 2020-08-07 at 4 41 28 PM](https://user-images.githubusercontent.com/67046386/89640497-57bb2800-d8cd-11ea-91dd-1f1864e7baa3.png)
![Screen Shot 2020-08-07 at 4 41 39 PM](https://user-images.githubusercontent.com/67046386/89640503-58ec5500-d8cd-11ea-851a-33cd469b762f.png)

**Comment by sudiptachatterjee** [comment]
I've run into a similar problem. I went to `flutterfire/packages/firebase_auth/firebase_auth/example` and ran `flutter pub get`. I got this as the output:

> Because every version of firebase_dynamic_links from path depends on firebase_core from hosted and firebase_auth_example depends on firebase_core from path, firebase_dynamic_links from path is forbidden.
> So, because firebase_auth_example depends on firebase_dynamic_links from path, version solving failed.
> Running "flutter pub get" in example...
> pub get failed (1; So, because firebase_auth_example depends on firebase_dynamic_links from path, version solving
> failed.)

**Comment by paapu88** [comment]
Same thing here: 
```
date
su 23.8.2020 20.55.38 +0300
cd ~/git/Omat/flutterfire/packages/firebase_auth/firebase_auth/example
git pull
Already up to date.
flutter doctor  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

flutter pub get
Because every version of firebase_dynamic_links from path depends on firebase_core from hosted and firebase_auth_example depends on firebase_core from path, firebase_dynamic_links from path is forbidden.
So, because firebase_auth_example depends on firebase_dynamic_links from path, version solving failed.
Running "flutter pub get" in example...                                 
pub get failed (1; So, because firebase_auth_example depends on
firebase_dynamic_links from path, version solving failed.)

```

Is this example working for anyone???
It would be nice to get on with flutter & google authentication.

**Comment by paapu88** [comment]
I made a new issue, with the same contents as @sudiptachatterjee at https://github.com/FirebaseExtended/flutterfire/issues/3300
(because it is about firebase_auth, not about firebase_analytics as here.)

**Comment by Salakar** [comment]
Closing in favor of #3300.

```
Could not find a file named "pubspec.yaml" in "/Users/user/Desktop/cm".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/user/Desktop/cm".)
```

This seems to indicate an issue outside of this library also.
