### ISSUE TITLE
[firebase_messaging] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#312]

**Comment by kroikie** [comment]
@amirh

The issue at https://github.com/flutter/flutter/issues/41874 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @amirh
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by creativecreatorormaybenot** [comment]
@kroikie Was this not closed in https://github.com/FirebaseExtended/flutterfire/pull/1564?

Otherwise, I think that https://github.com/FirebaseExtended/flutterfire/issues/1754 and https://github.com/FirebaseExtended/flutterfire/issues/2017 are more relevant now.

**Comment by Salakar** [comment]
Closing this as already implemented in #1564.
