### ISSUE TITLE
[flutter_auth] Github authentication

### ISSUE THREAD

**Issue by astronaute77** [FirebaseExtended/flutterfire#3120]
Hi,

Please add an example on how to get the Github Oauth code.

Right now, I’m unable to find any working examples anywhere using third party providers.

Thank you

**Comment by kroikie** [comment]
Hi @astronaute77 you must use get the GitHub Auth token either directly or using a 3rd party plugin.

If you are signing in using a redirect then you must setup a dynamic link (deep link) to extract the code once the github sign in process is complete. Firebase dynamic links or other plugins can be used for this.

Once you have that token you will need to create a [`GitHubAuthCredential`](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart#L205) object. Then using that credential sign in with [`signInWithCredential`](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart#L205)

**Comment by astronaute77** [comment]
Hi @kroikie , the solution you pasted doesn’t work, and even if it did, it asks to change the Firebase callback URL which is something I cannot do. I also have a web application using the same Github Sign in and the callback has to remain the same (the one from Firebase).

Are you telling me that I have to choose between mobile app and web app? Or did I understand this incorrectly?

Right now I don’t see how I can get the token without changing the callback, please advise or reopen.

Thank you

**Comment by kroikie** [comment]
You don't have to change the URL, [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links) allows your mobile app to handle URLs in the right way depending on the platform they are running on. So when on a mobile device the same URL will open your app and you can parse the URL extracting the code and use it to complete the sign in process. If on a desktop the redirect will take the user to your web app.

**Comment by astronaute77** [comment]
Okay I’ll try that, thank you for your help.

**Comment by astronaute77** [comment]
Hi @kroikie I created a dynamic link and can catch it in the application just fine using Firebase lib but the parameter Github is sending to the callback `?code=xxx` is not transmitted, it is lost during the conversion. And I cannot see any setting in dynamic links to preserve the parameters.

I opened a bug:
https://github.com/FirebaseExtended/flutterfire/issues/3125

Do you have any other workaround for me to test?
If not, please reopen this ticket.
