### ISSUE TITLE
[firestore] Cannot use filestore on non-main isolates.

### ISSUE THREAD

**Issue by CircleOnCircles** [FirebaseExtended/flutterfire#3124]
It had been discuss #1815, [here](https://stackoverflow.com/a/62357178/3969942) and [here](https://stackoverflow.com/questions/59120325/cannot-execute-firebase-query-within-isolate)

**To Reproduce**
## First, create a function that access firestore 
```dart
Future runOneTime(String userId) async {
  final databaseReference = Firestore.instance;
  final users = databaseReference.collection('users');
  final files = databaseReference.collection('files');
}
```
## Second call the code in an isolate
e.g. 
```dart
Button(
                  text: "sync",
                  onPressed: () async {
                    await compute(runOneTime, userId);
                  },
                )
```

## Error is printed
```
E/flutter (12393): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (12393): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (12393): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (12393): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (12393): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (12393): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (12393): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:375:5)
E/flutter (12393): #4      new MethodChannelFirestore (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:27:13)
E/flutter (12393): #5      FirestorePlatform.instance (package:cloud_firestore_platform_interface/cloud_firestore_platform_interface.dart:63:19)
E/flutter (12393): #6      new Firestore (package:cloud_firestore/src/firestore.dart:26:42)
E/flutter (12393): #7      Firestore.instance (package:cloud_firestore/src/firestore.dart:29:36)
E/flutter (12393): #8      runOneTime (package:gebwai/tasks/image_sync.dart:150:39)
E/flutter (12393): #9      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:75:34)
E/flutter (12393): #10     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:83:65)
E/flutter (12393): #11     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (12393): #12     _spawn (package:flutter/src/foundation/_isolates_io.dart:80:18)
E/flutter (12393): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
E/flutter (12393): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (12393): 
```

**Expected behavior**
Able to use firestore on any isolate

**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19042.423], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[!] Android Studio (version 3.6)
    X Unable to determine bundled Java version.
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

```
My flutter workflow is working properly, although the message suggests another.

I would like to ask. Is this intentional or a by-product of a singleton? Do you have any workarounds for the moment?

**Comment by TahaTesser** [comment]
<details> 
<summary>main_dev.dart</summary> 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

Future<void> runSomething(int id) async {
  final databaseReference = Firestore.instance;
  final books = databaseReference.collection('books');
  print(books.id);
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Firestore Example'),
        ),
        body: Center(
          child: BookList(),
        ),
        floatingActionButton: FloatingActionButton(onPressed: () async {
          // await runOneTime();
          var value = await compute(runSomething, 0);
        }));
  }
}

class BookList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance.collection('books').snapshots(),
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (snapshot.hasError) return new Text('Error: ${snapshot.error}');
        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return new Text('Loading...');
          default:
            return new ListView(
              children:
                  snapshot.data.documents.map((DocumentSnapshot document) {
                return new ListTile(
                  title: new Text(document['title']),
                  subtitle: new Text(document['author']),
                );
              }).toList(),
            );
        }
      },
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.176, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-8.0.pre.176 at /Users/tahatesser/Code/flutter_master
    • Framework revision d9637ed784 (7 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

```

</details>

**Comment by shaunramsey** [comment]
How would one achieve this affect then on iOS? 

In specific, calling firebase/firestore methods on a non-main isolate?  

Does this work differently on iOS than Android?

**Comment by ened** [comment]
@shaunramsey try `WidgetsBinding.ensureInitialized();` before calling somewhere else. If the isolate supports plugins, you should be good to go.

**Comment by CircleOnCircles** [comment]
I did some googling on the keyword `isolate supports plugins flutter`.
I found that the flutter team recognized this. but the workaround is huge for avg. dev.

Relate to: https://github.com/flutter/flutter/issues/21925

[maybe] workaround?
1. https://pub.dev/packages/isolate_handler
2. https://github.com/rmawatson/flutter_isolate
3. https://stackoverflow.com/a/57664794/3969942

**Comment by CircleOnCircles** [comment]
> 
> 
> @shaunramsey try `WidgetsBinding.ensureInitialized();` before calling somewhere else. If the isolate supports plugins, you should be good to go.

I wonder if we could explicitly initialize the plugin on isolate.

**Comment by deadsoul44** [comment]
> 1. https://pub.dev/packages/isolate_handler
> 2. https://github.com/rmawatson/flutter_isolate

These packages enable calling `WidgetsBinding.ensureInitialized()` on isolate but they are not able to send complex objects which make them useless. I want to listen to Firestore on an isolate but it seems that it is currently not possible and listening to Firestore locks the main thread very badly.

**Comment by ened** [comment]
@deadsoul44 You can run firestore on a separate isolate - please also refer to #4209 for a updated version.

The example on the top mentions the [`compute`](https://api.flutter.dev/flutter/foundation/compute.html) function though, which may not be the best choice for something that long-running.

**Comment by deadsoul44** [comment]
Hi @ened thank you very much for the great work. I had to use `isolate_handler` package and serialize the map on the main thread. I couldn't read the whole discussion but I wonder if your PR allows to send complex objects especially `built_value` classes?

**Comment by ened** [comment]
@deadsoul44 send from where to where?
Rgd. complex objects there are some limitations:
 - From isolate to isolate, you can only serialize/deserialize what Dart offers you to send [via SendPort](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html).
 - From isolate to the platform (native side) you essentially send the same, but you can adjust the `message codec`, so that it _appears_ to send complex objects.

I'm not super clear on the intention or use case you are after. You've mentioned before that listening on Firestore locks up the main thread badly. Can you explain more about that or submit a test case / example project?

**Comment by deadsoul44** [comment]
I mean from isolate to main thread. I want to listen to Firestore on an isolate and serialize the map to `built_value` classes and send them to main thread because serializing them in the main thread affects the performance. 

I solved "locking main thread" problem partially by using `isolate_handler` package and by decreasing Firestore document size. 

It seems that `compute` function is able to return complex objects in this example: https://flutter.dev/docs/cookbook/networking/background-parsing#4-move-this-work-to-a-separate-isolate

But in the docs, it also talks about the limitations of SendPort:
https://api.flutter.dev/flutter/foundation/compute.html

I am confused how and when we are able to send complex objects from an isolate to main thread.

**Comment by ened** [comment]
You could probably serialise your objects to JSON and send the from isolate to main thread. I'm more interested in the actual issue though. 

How big is the document? How many fields & how many changes per second? 

How do you measure if the main thread stutters? Does it still stutter if you remove _any_ display of the values and just fetch then print them?

**Comment by deadsoul44** [comment]
The documents have hundreds of fields so many that it is crashing the browser when trying to open.

I didn't measure the stutters but it can be ignored now.

**Comment by russellwheatley** [comment]
AS the OP's issue was regarding the use of Firestore on a separate isolate which is now possible and working, I'm going to close this issue. Please open another issue if you have have found another problem.
