### ISSUE TITLE
[Firebase Dynamic Links] Query parameters are lost during conversion

### ISSUE THREAD

**Issue by astronaute77** [FirebaseExtended/flutterfire#3125]
Dynamic Link 
`https://monadeo.page.link/github_auth?code=xxxxx`

Converts to:

**Observed:**
`https://monadeo-test.firebaseapp.com/__/auth/handler`

**Expected:**
`https://monadeo-test.firebaseapp.com/__/auth/handler?code=xxxxx`

It’s impossible to use dynamic links to login in Flutter using Github Sign in because of the above.
This is a real working link that you can test in the browser and see by yourself.

**Comment by TahaTesser** [comment]
Hi  @astronaute77 
There is already an issue for question you asking
I see there's an open issue addressing the case you described. https://github.com/FirebaseExtended/flutterfire/issues/1740
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
