### ISSUE TITLE
[firebase_messaging] Unable to capture notification payload in iOS after app is terminated

### ISSUE THREAD

**Issue by nagarwa2** [FirebaseExtended/flutterfire#3126]
Unable to receive notification message when iOS app is terminated. I have configured all three methods - onMessage, onResume and onLaunch. When the app is in foreground or background this works properly. Note this is happening in iOS only.

Must be a way to capture notifications in terminated app.

**Comment by TahaTesser** [comment]
Hi @nagarwa2 
This can only happen when app is brought in foreground  
Please https://pub.dev/packages/firebase_messaging#receiving-messages
```
Message is stored by FCM and delivered to app via onMessage when the app is brought back to foreground.
```

**Comment by acoutts** [comment]
I have a similar problem in my app but I tracked it down to one of my libraries implementing `didFinishLaunchingWithOptions` and it's hijacking the launch intent, preventing the firebase_messaging lib from ever seeing it.

Maybe check that you don't have any conflicting libs like this.
