### ISSUE TITLE
[FIREBASE AUTH] The link provided in documentation  is not working.

### ISSUE THREAD

**Issue by bharat-biradar** [FirebaseExtended/flutterfire#3129]
**Describe the bug**
The link provided for FirebaseAuthException class in the documentation for error handling leads to webpage that doesnt exist.
May be the link is outdated.If this is the case please update it.There are many similar links in the docs that lead to same problem.Please look into it
![Page not found · GitHub · GitHub - Google Chrome 09-08-2020 20_11_27](https://user-images.githubusercontent.com/62872048/89734920-93482480-da7c-11ea-930a-d3027b38af51.png)

**To Reproduce**
I'm referring to this documentation [(link)](https://github.com/FirebaseExtended/flutterfire/blob/master/docs/auth/error-handling.mdx)

I am attaching the response given by the link

**Comment by kroikie** [comment]
Hi @bharat-biradar this class is coming in the new version of Auth, it should be published as dev soon.
