### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by XTechDeveloper** [FirebaseExtended/flutterfire#3130]
Hi @gsusI 
Please add this in flutter app -> android -> settings.gradle
```
def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
```

if you disagree please write in the comments and I will reopen it 
Thank you

_Originally posted by @TahaTesser in https://github.com/FirebaseExtended/flutterfire/issues/2599#issuecomment-632651771_

I am getting this error now:
<ij_msg_gr>Project resolve errors<ij_msg_gr><ij_nav>C:\ornekler\learning_animals\android\build.gradle<ij_nav><i><b>root project 'android': Unable to resolve additional project configuration.</b><eol>Details: org.apache.tools.ant.BuildException: Basedir C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\android does not exist</i>

I think it is because of this line in settings.gradle:
def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()

**Comment by TahaTesser** [comment]
Hi @XTechDeveloper 
This is being resolved in rework  of flutterfire, please check this comment https://github.com/FirebaseExtended/flutterfire/issues/2796#issuecomment-656606329
You can remove the `settings.gradle`

Closing,. If you disagree, please write in the comments and I will reopen it.
Thank you
