### ISSUE TITLE
[firebase_messaging] All push notifications never appear in system tray, but are logged as 'Recently dismissed"

### ISSUE THREAD

**Issue by jt274** [FirebaseExtended/flutterfire#3134]
**Describe the bug**
I am using firebase_messaging with a flutter app. This app has not been worked on in a few months, but push notifications were previously working as expected. Sending a notification through a cloud function, or a test notification through the Firebase console would come through 100% of the time, and if the app was in the background the notification would play a sound and appear in the system tray (on virtual and physical devices).

After running the app recently, push notifications do not go into the system tray under any circumstances. In an Android 11 virtual device, the notification history for the device shows the notifications come through, but are listed under "Recently dismissed". They are placed here immediately and there is no sound or notification shown to the user.

I had recently moved from firebase_messaging 5.1.4 to 6.0.16. But moving back to 5.1.4 did not resolve the issue.

If the app is in the foreground, onMessage fires successfully. onBackgroundMessage was also added as per the readme instructions, but it does not fire under any circumstances (app in foreground, background, or closed). And again, under no circumstances do notifications go to the system tray. The notification from the cloud function is the same as before:

`notification: {
        title: title,
        body: body,
      },
      data: {
        type: dataType,
        content: dataContent,
        click_action: 'FLUTTER_NOTIFICATION_CLICK',
      },
      android: {
        notification: {
          channel_id: 'mychannel',
        },
        priority: 'high',
      },
      token: token
    };`

**Expected behavior**
Test notification sent from Firebase console should enter the device notification system tray and play a sound, remaining until dismissed by the user.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] Connected device (2 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @jt274 
Using official [example](https://pub.dev/packages/firebase_messaging/example)  on `firebase_messaging: ^6.0.16`, notifications appear normal when is terminated

![Screenshot_1597233272](https://user-images.githubusercontent.com/48603081/90012454-04781980-dcc1-11ea-8471-ac06ecdf58e4.png)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
```

</details> 

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample and steps by steps to reproduce this issue on Android 11 emulator
Thank you
