### ISSUE TITLE
[cloud_firestore] "select" operator on query

### ISSUE THREAD

**Issue by algirdasmac** [FirebaseExtended/flutterfire#3137]
**Is your feature request related to a problem? Please describe.**
Flutter is moving to the web very fast and it is really important to secure your data (what you are returning from database).
Firebase has this [StructuredQuery](https://firebase.google.com/docs/firestore/reference/rest/v1/StructuredQuery), where you can select fields, which you can get back.
Unfortunately - cloud_firestore package does not support this operator yet.

**Describe the solution you'd like**
There should be "select" operator on queries with the possibility to provide an object (Projection) and get documents with this data.

**Comment by Ehesp** [comment]
Hello,

Projection isn't available on the client SDKs, see [here](https://github.com/firebase/quickstart-js/issues/164). You can raise a feature request here: https://firebase.google.com/support/troubleshooter/report/features
