### ISSUE TITLE
[firebase_dynamic_links] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#314]

**Comment by kroikie** [comment]
@amirh

The issue at https://github.com/flutter/flutter/issues/41872 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @amirh
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Ehesp** [comment]
This is now available in the latest plugin version
