### ISSUE TITLE
[FIREBASE_auth] Cant install new pre-release

### ISSUE THREAD

**Issue by Bilonik** [FirebaseExtended/flutterfire#3148]
**Describe the bug**

Trying to install  firebase_auth: "0.18.0-dev.1" (according to the new CHANGELOG.md ) 

Because firebase_auth_web 0.2.0-dev.1 depends on firebase_auth_platform_interface ^1.0.0 and no versions of firebase_auth_web match >0.2.0-dev.1 <0.3.0, firebase_auth_web ^0.2.0-dev.1 requires firebase_auth_platform_interface ^1.0.0.
And because firebase_auth >=0.18.0-dev.1 depends on firebase_auth_platform_interface ^2.0.0-dev.1, firebase_auth_web ^0.2.0-dev.1 is incompatible with firebase_auth >=0.18.0-dev.1.
So, because XXX depends on firebase_auth 0.18.0-dev.1 which depends on firebase_auth_web ^0.2.0-dev.1, version solving failed.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by Bilonik** [comment]
#3147

**Comment by kroikie** [comment]
This should be resolved now. point to `firebase_auth: ^0.18.0-dev.2`
