### ISSUE TITLE
[Firestore] QuerySnapshot documents should not return empty list when collection of documents is absent

### ISSUE THREAD

**Issue by happyharis** [FirebaseExtended/flutterfire#3153]
**Is your feature request related to a problem? Please describe.**
When querying for a collection that is absent, expected to return an Error object or null. However, was returned an empty list. This is not an accurate representation of the Firestore database structure. In my opinion, an empty list represents that there is an empty collection.

**Describe the solution you'd like**
Instead of an empty list returned when querying an absent collection, return null, an error object or a QuerySnapshot object with an error message.

**Additional context**
```dart
// names collection absent
final snapshot = await Firestore.instance.collection('names').getDocuments();
final documents = snapshot?.documents;

// expected
print(documents); // error

// reality
print(documents); // []
```

**Comment by Ehesp** [comment]
Please follow the issue template.

**Comment by happyharis** [comment]
I followed the template for a feature request. I don't think this is a bug, unless otherwise. Please advice on this.

**Comment by hdavidmb** [comment]
I also tried fetching data without internet connection expecting to get some error, but got empty list instead.
I agree it should return some error in those cases.

**Comment by russellwheatley** [comment]
I believe this is as intended. A query against an empty (non-existent) collection, returns an empty [snapshot](https://github.com/firebase/firebase-ios-sdk/issues/4317#issuecomment-554471305).

**Comment by hdavidmb** [comment]
> I believe this is as intended. A query against an empty (non-existent) collection, returns an empty [snapshot](https://github.com/firebase/firebase-ios-sdk/issues/4317#issuecomment-554471305).

Yeah, but what in the case there is no internet connection or some other error happens? It should throw an exception or error instead of an empty list.

**Comment by russellwheatley** [comment]
[Quote from link I pasted from a Firebase maintainer](https://github.com/firebase/firebase-ios-sdk/issues/4317#issuecomment-554471305):

> If you issue a Collection Query against an empty cache, we will raise an empty snapshot.
> If you fetch a document via DocumentReference.get(), we will raise an error if we do not have a cached copy and the device is offline.

i.e. if you're offline (querying cache) and the thing you query isn't in your cache (and therefore not in your database):

- a collection query will return an empty list.
- a document query will throw an error.
