### ISSUE TITLE
Reward ad invades iPhone X safe area

### ISSUE THREAD

**Issue by belisqui** [FirebaseExtended/flutterfire#3167]
![7FEFF0C1-C4B2-47AD-95F4-6FCB67321551](https://user-images.githubusercontent.com/46362183/90138639-a2034400-ddba-11ea-84f6-a0c74aab438e.png)
I cant find a way to stop the reward ad from invading the safe area in the iPhone X family. What is the way to fix this? I cannot close the ad since it sits behind the clock.

**Comment by TahaTesser** [comment]
Hi @belisqui 
I see there's an open issue addressing the case you described. https://github.com/FirebaseExtended/flutterfire/issues/3090
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
