### ISSUE TITLE
[firebase_auth] Invalid Token - Bug appears when creating duplicate apps with different Bundle ID's

### ISSUE THREAD

**Issue by PhilBelanger42** [FirebaseExtended/flutterfire#3169]
**Describe the bug**
Okay, so I had developed an app (programmed in flutter) using the firebase_auth dart package, and that app is working perfectly fine, no issues.

The issue arrises when I try to duplicate the app for a second Bundle ID. (Think same client, different end-user customer-base). Every single time I boot up the app, authentication doesn't even let me enter in a phone number, just giving me an "Invalid Token" error.

flutter: Phone Auth Verification Failed: Invalid token.

**To Reproduce**

I do start with a perfectly clear, clean copy of the app, that I have run on multiple devices, and it works. I then replace the Bundle ID, download the new google-services.plist from Firebase (That has the correct Bundle ID and other information), (replacing the original, and making sure to include it in the runner directory through XCode, so the program knows), and replace the pertinent details such as the url in the info.plist, and the API Key in the AppDelegate.swift.

I've ensured that the Bundle ID I'm trying to develop on is covered via the Apple Provisioning Profiles in my Apple Developer Account.

**Expected behavior**
I should be able to create a copy of the app, under a new Bundle ID, and have it work exactly as the original.

**Additional context**
I've cleaned the build folder, updated to newer versions and various branches, but I keep getting stymied at this point in the project. I've looked through all of the similar problems in your archives, but none of the advice or suggestions anyone has given has been able to help me.

This app does have Push Notifications active, and requires them to work.

Again, to be clear, without changing ANY code, I have a fully function variant of the app. But when changing to a new version of the Bundle ID, I get this error.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```

[✓] Flutter (Channel master, 1.21.0-10.0.pre.70, on Mac OS X 10.15.6 19G73, locale en-CA)

    • Flutter version 1.21.0-10.0.pre.70 at /Users/iosdev/Developer/flutter

    • Framework revision 0629030a05 (12 hours ago), 2020-08-13 00:01:03 -0400

    • Engine revision 7571e7c380

    • Dart version 2.10.0 (build 2.10.0-11.0.dev)


 

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

    • Android SDK at /Users/iosdev/Library/Android/sdk

    • Platform android-29, build-tools 29.0.2

    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java

    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

    • All Android licenses accepted.


[✓] Xcode - develop for iOS and macOS (Xcode 11.6)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • Xcode 11.6, Build version 11E708

    • CocoaPods version 1.9.3


[✓] Android Studio (version 3.5)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin version 42.1.1

    • Dart plugin version 191.8593

    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)


[✓] VS Code (version 1.47.3)

    • VS Code at /Applications/Visual Studio Code.app/Contents

    • Flutter extension version 3.13.2


[✓] Connected device (1 available)

    • Phillip’s iPhone (mobile) • ce2e8494b57ead1f7c37d1c18b8f6b22e797f5e4 • ios • iOS 13.5.1

    ! Error: Phillip’s iPhone is not connected. Xcode will continue when Phillip’s iPhone is connected. (code -13)


• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @PhilBelanger42 
You can't have different ID for same configuration, you need to new app for new different bundle ID and then google services plist and put int new project and you can use same authentication and database from this job and app bundle should be matched with firebase app bundle. if you're changing bundle id for your app, you can reuse existing plist. Correct me if i am mistaken

<img width="994" alt="Screenshot 2020-08-17 at 3 44 22 PM" src="https://user-images.githubusercontent.com/48603081/90385400-b720f100-e0a0-11ea-836b-54f4859d6cfe.png">

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by PhilBelanger42** [comment]
@TahaTesser Thanks for your response, however I think I must not have done a sufficiently thorough job explaining exactly what I have done to resolve this.  I will attempt to elaborate.

So yes, I'm aware that this should be treated a completely separate app.  It has it's own firebase project, it's own google-services.plist, it's own API-Key (for certain functions) and others.  As far as I know though, I HAVE changed all of those things.  The list as follows:

As Push Notifications are required, I created a new Provisioning Profile from this helpful guide 
https://firebase.google.com/docs/cloud-messaging/ios/certs

Created and registered a new App in Firebase Console, that has the new Bundle ID, and associated info, and downloaded it.

Removed the previous Google-Services.plist (and all references to it), and only then included the new file in the project.

Changed the bundle-id in the actual info.plist in XCode 11.

So in Essence, the ONLY thing that should have anything to do with the previous app, is the base code itself, and how it functions.  (At least as far as I'm aware.  If I'm wrong, PLEASE let me know!)

A minimal-reproducible sample may not be possible, but I will definitely attempt to do so over the next few days.

as for flutter-doctor --verbose, I will paste here.

[✓] Flutter (Channel master, 1.21.0-10.0.pre.70, on Mac OS X 10.15.6 19G73, locale en-CA)
    • Flutter version 1.21.0-10.0.pre.70 at /Users/iosdev/Developer/flutter
    • Framework revision 0629030a05 (6 days ago), 2020-08-13 00:01:03 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/iosdev/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Phillip’s iPhone (mobile) • ce2e8494b57ead1f7c37d1c18b8f6b22e797f5e4 • ios • iOS 13.5.1
    ! Error: Phillip’s iPhone is not connected. Xcode will continue when Phillip’s iPhone is connected. (code -13)

• No issues found!


Hopefully this helps you to identify any possible area of issue!

**Comment by PhilBelanger42** [comment]
Discovered the error, it wasn't code.  There was information missing from the Firebase Console, which I had not been made aware of.  The code itself works fine.
