### ISSUE TITLE
[firebase_messaging] After adding the code pushed in the background, the push cannot be received

### ISSUE THREAD

**Issue by lizhuoyuan** [FirebaseExtended/flutterfire#3170]
I did that:
```
dependencies {
  // ...

  implementation 'com.google.firebase:firebase-messaging:<latest_version>'
}

```

add Application 

add onBackgroundMessage

and then , I can not reveive push

**Comment by darshankawar** [comment]
Hi @lizhuoyuan,
Did you follow all the steps listed in the [document](https://pub.dev/packages/firebase_messaging) ?
You may want to try the official [example](https://pub.dev/packages/firebase_messaging/example) and see how to receive push notification.

If problem persists, provide `flutter doctor -v`, `pubspec.yaml` and minimal complete reproducible code sample.
Thanks.

**Comment by lizhuoyuan** [comment]
@darshankawar  thank you.
Sometimes good sometimes bad, I suspect it is a network problem.
I will close it when I know more things
