### ISSUE TITLE
[Firebase messaging] Not able to access packages within the background message handler, when application is in background or killed

### ISSUE THREAD

**Issue by lokeshlal** [FirebaseExtended/flutterfire#3176]
**Describe the bug**
Not able to access packages within the background message handler, when application is in background or killed.

For example: when accessing the shared preference or cloud firestore getting similar error messages

`MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preference
`

Is this the intended behavior of the plugin background message handler.

We only want to handle the data messages and update the local store and set some notifications and then update the remote store.

Thanks

EDIT: 
However I can use FlutterLocalNotificationPlugin. Is this because, local notification plugin is registered in native implementation.
Can someone tell me how to register a plugin with native android and iOS.

**Comment by darshankawar** [comment]
Hi @lokeshlal,
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample including the steps you take when you see the issue ?
Also see [this](https://github.com/FirebaseExtended/flutterfire/issues/1590) issue which I think talks about similar issue and see if the PR merged in that ticket is helpful to you.

**Comment by lokeshlal** [comment]
Flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.20.1 at D:\softwares\flutter
    • Framework revision 2ae34518b8 (9 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\lokeshlal\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

Code sample

```
firebaseMessaging.configure(
      onBackgroundMessage: myBackgroundMessageHandler,
    );

static Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) async {
    Map<String, dynamic> obj = {};
    await Firestore.instance.collection("user").document("123").get().forEach((snapshot) {  //  <- error comes in this line, when trying to access get
      obj = snapshot.data;
    });
}
```

**Comment by lokeshlal** [comment]
Got it.

Just have to register the plugin

`import io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin
`
and then in registerWith

```
if (!registry!!.hasPlugin("io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin")) {
    CloudFirestorePlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin"));
}
```
