### ISSUE TITLE
[Firebase Performance] :app:transformClassesAndResourcesWithR8ForRelease, :app:checkReleaseDuplicateClasses

### ISSUE THREAD

**Issue by bkr32** [FirebaseExtended/flutterfire#3178]
**Describe the bug**
After adding Firebase Performance as described here https://firebase.google.com/docs/perf-mon/get-started-android?authuser=0 for the android build, i get the `Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'` error when attempting `flutter build apk` to bypass this issue i attempted to build with `flutter build apk --no-shrink` but ended up with yet another error `Execution failed for task ':app:checkReleaseDuplicateClasses'.`

**To Reproduce**
1. Add firebase performance monitoring for the android build as mentioned here https://firebase.google.com/docs/perf-mon/get-started-android?authuser=0
2. Attempt to build release candidate with `flutter build apk`
3. See error or incorrect behavior

**Expected behavior**
Android build should proceed without any problem

**Flutter doctor**

```
[√] Flutter (Channel beta, 1.20.0-7.4.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-KE)
    • Flutter version 1.20.0-7.4.pre at D:\flutter
    • Framework revision 916c3ac648 (13 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/32/AppData/Local/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/32/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\32\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

```

**Comment by russellwheatley** [comment]
This is a stale issue, the firebase android sdk & flutter have also had major releases since this issue was created so I'm going to close. Will reopen if this is still a problem.
