### ISSUE TITLE
[firebase_dynamic_links] OnLink only called every other time

### ISSUE THREAD

**Issue by guihackmann** [FirebaseExtended/flutterfire#3179]
**Describe the bug**
With the app minimized, the first time I click on a shared link, the `onLink` callback works fine, the second it doesn't get called, then the third time it works again, and so forth.

**To Reproduce**
1. With the app minimized, click on a shared link.
2. **(1st try)** - As a result, the app maximizes, and calls `onLink` `onSuccess` (perfect).
3. Then, minimize the app again, then click on the same link.
4. **(2nd try)** - As a result, the app maximizes, but it calls `onLink` `onError`
5. Then, minimize the app again, then click on the same link.
6. **(3rd try)** - As a result, the app maximizes, and calls `onLink` `onSuccess` (perfect).

**Expected behavior**
I would expect the `onLink` `onSuccess` to be called every time, but for some reason, it only works on odd number of tries.

**Additional context**
Here is my code.

`initDynamicLinks() async {
    final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance
        .getInitialLink();

    final Uri deepLink = data?.link;

    if (deepLink != null) {

      bool isPartida = deepLink.pathSegments.contains("partida");
      if(isPartida){
        var partidaId = deepLink.queryParameters["partidaId"];
        if(partidaId != null){
          Navigator.of(context).push(
              MaterialPageRoute(builder: (context) => Partida(partidaId: partidaId)));
        }}}

    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {

          final Uri deepLink = dynamicLink?.link;

          if (deepLink != null) {

            var isPartida = deepLink.pathSegments.contains("partida");
            if(isPartida){
                var partidaId = deepLink.queryParameters["partidaId"];

              if(partidaId != null){
                Navigator.of(context).push(
                    MaterialPageRoute(builder: (context) => Partida(partidaId: partidaId)));
              }}}},
        onError: (OnLinkErrorException e) async {
          print(e.message);
        });}`

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

```

**Comment by tejerolucas** [comment]
Im going crazy with the same issue,but sometimes you can get a row of three success message but then the pattern starts again.

**Comment by leochiu-work** [comment]
Same issue here, only works in odd numbers of tries.

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-HK)
    • Flutter version 1.22.0 at /Users/leochiu/Documents/Sources/flutter
    • Framework revision d408d302e2 (5 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/leochiu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (2 available)            
    • SM A515F (mobile)        • R58N9318TRB                              • android-arm64 • Android 10 (API 29)
    • Chi Ho’s iPhone (mobile) • 6e805e3b7ea518ced638b5b6eafddf06cf289318 • ios           • iOS 14.0.1
    ! Error: Chi Ho’s iPhone is busy: Copying cache files from device. Xcode will continue when Chi Ho’s iPhone is finished. (code -10)
```

**Comment by ShaneZhang-tw** [comment]
Any idea on this?
meet the same issue for iOS.

**Comment by russellwheatley** [comment]
Hey @guihackmann, Dynamic Links has been reworked and as such the API has [changed quite a bit](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_dynamic_links/firebase_dynamic_links/CHANGELOG.md).  

Please upgrade to the latest version and create a new issue if you discover a problem. Thanks.
