### ISSUE TITLE
Could not determine the dependencies

### ISSUE THREAD

**Issue by eliasmeireles** [FirebaseExtended/flutterfire#3181]
**Describe the bug**

Trying to upgrade my version to the 0.5.3, the the firebase dynamic links wont to find the firebase dependencies.

**To Reproduce**

FAILURE: Build failed with an exception.

* What went wrong:

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.core.firebase:core.firebase-dynamic-links:16.1.8.
     Required by:
         project :app > project :firebase_dynamic_links

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TahaTesser** [comment]
Hi @eliasmeireles 
Can you please provide your `flutter doctor -v`,your `build.gradle` from Flutter App->android your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
