### ISSUE TITLE
Issue with FlutterFire Cloud Firestore documentation

### ISSUE THREAD

**Issue by ankitgoel1602** [FirebaseExtended/flutterfire#3183]
I have noticed an issue with FlutterFire Cloud Firestore documentation. Everywhere on the page https://firebase.flutter.dev/docs/firestore/usage, it is mentioned to use FirebaseFirestore to create an instance or to perform any other operation but this seems to be changed to Firestore.instance instead of FirebaseFirestore.instance.

**Comment by joniaiuser** [comment]
FirebaseFirestore.instance is the new approach in the developer's preview.. Think the documentation has already been updated in preparation for the upcoming release.

**Comment by TahaTesser** [comment]
Hi @ankitgoel1602 
Thanks for filing the issue but this is new approach it's already documented in dev version and doc page 
https://pub.dev/packages/cloud_firestore/versions/0.14.0-dev.1/example 
https://firebase.flutter.dev/docs/firestore/usage
Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you
