### ISSUE TITLE
[cloud_firestore] .hasData returns true no matter what with Document Streams

### ISSUE THREAD

**Issue by EliasDeuss** [FirebaseExtended/flutterfire#3184]
**Describe the bug**
If you have a StreamBuilder and are streaming a document not a collection, .hasData will return true even if the document doesn't exist. This can be found in 0.13.7 (current latest), and later versions.

**To Reproduce**
1. Create a StreamBuilder
2. Reference a document in the stream section with .snapshots() (make sure the document doesn't exists in that location)
3. print .hasData
4. See error or incorrect behavior

**Expected behavior**
.hasData should return false if the document doesn't exists.

**Additional context**

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.0, on macOS 11.0 20A5343j, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.0)
[✓] Connected device (3 available)
```

If anyone has a workaround that would work for now because this is blocking a release. Thanks

**Comment by EliasDeuss** [comment]
@FirebaseExtended/invertase I think this should be looked at.

**Comment by TahaTesser** [comment]
Hi @EliasDeuss 
Thanks for filling the issue, i can reproduce it on `cloud_firestore 0.13.7` and `cloud_firestore: ^0.14.0-dev.1` too 
There is no `books` collection on my firestore but it returns `false` then `true`

### versions
```
  cloud_firestore: ^0.14.0-dev.1
  firebase_core: ^0.5.0-dev.2
```

### logs
```
flutter: false
flutter: true
```
<details> 
<summary>code sample</summary> 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

bool USE_FIRESTORE_EMULATOR = false;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if (USE_FIRESTORE_EMULATOR) {
    FirebaseFirestore.instance.settings = Settings(
        host: 'localhost:8080', sslEnabled: false, persistenceEnabled: false);
  }
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: BookList(),
      ),
    );
  }
}

class BookList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: FirebaseFirestore.instance.collection('books').snapshots(),
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (snapshot.hasError) return new Text('Error: ${snapshot.error}');

        print(snapshot.hasData);

        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return new Text('Loading...');
          default:
            return new ListView(
              children: snapshot.data.docs.map((DocumentSnapshot document) {
                return new ListTile(
                  title: new Text(document.data()['title']),
                  subtitle: new Text(document.data()['author']),
                );
              }).toList(),
            );
        }
      },
    );
  }
}

```

</details>

**Comment by Ehesp** [comment]
Hey @EliasDeuss this is actually correct behaviour.

The [`hasData`](https://api.flutter.dev/flutter/widgets/AsyncSnapshot/hasData.html) implementation checks for whether `data` is `null` on the Stream. In the case of Firestore, it always returns data, in our case a `QuerySnapshot` or `DocumentSnapshot`. Even if no document(s) exists, it will always return one of these thus `hasData` is always `true`.

Instead, you should check whether a document exists (via `snapshot.exists`): https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/DocumentSnapshot/exists.html

**Comment by EliasDeuss** [comment]
@Ehesp I have tried ```snapshot.exists``` and it just gives the error. 

```
The getter 'exists' isn't defined for the type 'AsyncSnapshot<DocumentSnapshot>'.
```

**Comment by EliasDeuss** [comment]
@Ehesp ```.exists``` doesn't work with ```AsyncSnapshot<DocumentSnapshot> snapshot```.
