### ISSUE TITLE
[cloud_firestore] Xcode build extremely slow (Flutter macOS)

### ISSUE THREAD

**Issue by nilsreichardt** [FirebaseExtended/flutterfire#3185]
## Summary of Issue
Simply adding `cloud_firestore` to `pubspec.yaml` results in a huge increase in Flutter macOS XCode build times. The issue can be recreate with nothing more than a simple flutter create application and minor changes to pubspec.yaml.

## Build Times
> ### Default App without `cloud_firestore: ^0.13.7`
> ![IMG_0024](https://user-images.githubusercontent.com/48603081/90399616-dcb9f480-e0b8-11ea-95ee-05fc9bfe68a9.PNG)
> 
> ### Default App with `cloud_firestore: ^0.13.7`
> ![IMG_0025](https://user-images.githubusercontent.com/48603081/90399621-de83b800-e0b8-11ea-870c-ad2617340ed0.PNG)
> 
> ### Default App without `cloud_firestore: ^0.14.0-dev.1`
> ![IMG_0026](https://user-images.githubusercontent.com/48603081/90399589-cf046f00-e0b8-11ea-917b-49be3846dd5f.PNG)
> 
> ### Default App with `cloud_firestore: ^0.14.0-dev.1`
> ![IMG_0027](https://user-images.githubusercontent.com/48603081/90399592-d1ff5f80-e0b8-11ea-86fe-0c627b4faa1e.PNG)
> 
Tested by @TahaTesser 

There is also already an closed issue (#349), but this issue is only for the iOS XCode build problem.

<details>
<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.55, on Mac OS X 10.15.5 19F101,
    locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.48.0)
[✓] Connected device (3 available)
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone
      von Roland is connected. (code -13)

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
### Default App with no `cloud_firestore: ^0.13.7`
![IMG_0024](https://user-images.githubusercontent.com/48603081/90399225-4259b100-e0b8-11ea-8737-e68e35dbbd6e.PNG)


### Default App with  `cloud_firestore: ^0.13.7`
![IMG_0025](https://user-images.githubusercontent.com/48603081/90399230-438ade00-e0b8-11ea-8698-88830d520124.PNG)



### Default App with no `cloud_firestore: ^0.14.0-dev.1`
![IMG_0026](https://user-images.githubusercontent.com/48603081/90399158-248c4c00-e0b8-11ea-8f3e-5a32a3f3146b.PNG)



### Default App with  `cloud_firestore: ^0.13.7`
![IMG_0027](https://user-images.githubusercontent.com/48603081/90399192-3241d180-e0b8-11ea-8d40-352a5f59e04e.PNG)

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.114, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-10.0.pre.114 at /Users/tahatesser/Code/flutter_master
    • Framework revision b2c0970aa7 (27 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

```

</details>

**Comment by AndroidNils** [comment]
@TahaTesser Thank you for testing! 😍 I added the result to the ticket description 👍

**Comment by cbalmeida** [comment]
More than a year and still waiting for some solution. It's very frustrating when you see they give a s* about this issue.

**Comment by AndroidNils** [comment]
@cbalmeida Luckily they found a workaround for iOS after more than half a year. Maybe we will have a workaround in 2021 ;)

**Comment by Salakar** [comment]
Some context as to why this doesn't work for iOS: https://github.com/invertase/firestore-ios-sdk-frameworks/issues/11#issuecomment-675190015

**Comment by Salakar** [comment]
https://github.com/invertase/firestore-ios-sdk-frameworks is now supported on macOS since Firebase iOS SDK v7.4.0, see #4698 for a detailed example of integrating.

Please try it out and let me know how much it helps, thanks

**Comment by russellwheatley** [comment]
As Mike has mentioned, you may now use the precompiled iOS version. For (if) any further updates regarding macOs build times, I'd follow #4698.
