### ISSUE TITLE
Cloud Firestore  module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by anas-aw** [FirebaseExtended/flutterfire#3189]
**Describe the bug**
 module 'cloud_firestore' not found

**Flutter doctor**
Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-JO)
    • Flutter version 1.20.1 at /Users/AAwad/Documents/flutter
    • Framework revision 2ae34518b8 (10 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/AAwad/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • 4CAD8DAF-B843-4915-A4DA-AB8562F674CD • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

Xcode's output:
↳
/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'cloud_firestore' not found
@import cloud_firestore;

**Comment by TahaTesser** [comment]
Hi @anas-aw 
Could please delete podfile and generate again 
Execute following root of your `ios` folder
`rm -rm podfile`
`pod init`
`pod install`

If the problem, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
