### ISSUE TITLE
[FIREBASE_AUTH] Firebase Phone Authentication Error: The SMS Code Has Expired.

### ISSUE THREAD

**Issue by sunilmishra** [FirebaseExtended/flutterfire#3193]
Firebase Phone Authentication is not working on the Real Android Phone (e.g Pixel 2, Samsung g9 etc...). 

I received the SMS code from Firebase successfully, But When I entered the correct code (within 1-2 seconds) and ask for verify. It's always throw the exception. 

**PlatformException(ERROR_SESSION_EXPIRED): The SMS code has expired. Please re-send the verification code to try again.**
 
Here is my sample code: 
```
try {
      final AuthCredential credential = PhoneAuthProvider.credential(
        verificationId: _verificationId,
        smsCode: _smsController.text,
      );
      final authResult = await _auth.signInWithCredential(credential);
      final User user = authResult.user;  
    } catch (e) {
      print(e);
    }
  }
```

**Note:** 
1. I have already added **SHA-1** (from release build) using command `./gradlew signingReport`. using https://developers.google.com/android/guides/client-auth to firebase auth console.

2. It's only happening in **ANDROID PHONES** not on Emulator(with Test Numbers).

3. When i Checked https://console.firebase.google.com/project/MY-PROJECT/authentication/users. 
    I saw User has been created successfully using my given PhoneNumber.
  - why getting Exception if `User` has created on console.

Flutter version:
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

All Firebase libraries are also up to date.

**Comment by TahaTesser** [comment]
Hi @sunilmishra 

Using  latest `firebase_auth: ^0.16.1` on physical Android with official [example](https://pub.dev/packages/firebase_auth/example), no issues phone authentication. 
```
I/BiChannelGoogleApi(26321): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@b35695f
D/FirebaseAuth(26321): Notifying id token listeners about user ( 8YX4GQPeyEgfYq474` ).
D/FirebaseAuth(26321): Notifying auth state listeners about user ( 8YX4GQPeyEgfYq474` ).
```

<img width="989" alt="Screenshot 2020-08-17 at 4 43 20 PM" src="https://user-images.githubusercontent.com/48603081/90390363-d28ffa00-e0a8-11ea-9324-f572efe7a915.png">

Can you please uninstall the app, reinstall with with latest `firebase_auth`
