### ISSUE TITLE
[firebase_auth] Refresh Google OAuth Access Token after Google Sign In

### ISSUE THREAD

**Issue by hudson-dev** [FirebaseExtended/flutterfire#3195]
I am trying to figure out how to refresh an OAuth Access Token after a user signs in using Google Sign In within my Flutter app. 

Currently, I have set up a Firebase cloud function to run and retrieve a user's access token from Firestore, and then from there make a request to the Google Calendar API. The access token is originally retrieved after a user signs in via Google Sign In. 

```
Future<FirebaseUser> signInWithGoogle() async {
    try {
      GoogleSignInAccount _signInAccount = await _googleSignIn.signIn();
      GoogleSignInAuthentication _signInAuthentication =
          await _signInAccount.authentication;
```

      final AuthCredential credential = GoogleAuthProvider.getCredential(
          accessToken: _signInAuthentication.accessToken,
          idToken: _signInAuthentication.idToken);

      AuthResult result = await _auth.signInWithCredential(credential);

      // This is where I store the access token in Firestore to be retrieved by my cloud function
      _storageMethods.setAccessToken(
          userId: result.user.uid,
          accessToken: _signInAuthentication.accessToken);

      FirebaseUser user = result.user;

      return user;
    } catch (e) {
      print(e);
      return null;
    }

The main issue here is that the Google Sign-In is not returning back a Refresh Token after a user signs in. Without this refresh token, I cannot access the Google Calendar API after the 1 hour expiration time, without making the user have to login again.

I really need this feature added as soon as possible and I don't understand the rationale for why the Google Sign In would not return the Refresh Token along with the access and id token. I have already looked at  #1079 however the issue has been closed without a resolution.

**Comment by TahaTesser** [comment]
CC: @Salakar

**Comment by Salakar** [comment]
> The main issue here is that the Google Sign-In is not returning back a Refresh Token after a user signs in.

Correct. Please raise this issue/feature request on the Google Signin plugin repo:https://github.com/flutter/plugins/tree/master/packages
