### ISSUE TITLE
[Cloud Messaging] Number of notifications openned not working for iOS app

### ISSUE THREAD

**Issue by chamartt** [FirebaseExtended/flutterfire#3201]
Hi, 

I used your plugin for my Flutter/Dart application.

My firebase is corretly configured as I can use Firestore or sent/receive notifications on Android and iOS.

But I have a problem with Cloud Messaging on iOS : I don't have openning data in my dashboard for my iOS application.
Android works well.

Can you please help me ?

Thank you in advance.

**Comment by kroikie** [comment]
Hi @chamartt, I'm sorry you are not seeing your opens in your dashboard. However the best place to get assistance with that would be to file a support ticket at firebase.google.com/support

I'm going to close this issue, if you think this is directly related to FlutterFire please feel free to open another issue.
