### ISSUE TITLE
[firebase_admob] version solving failed

### ISSUE THREAD

**Issue by RaviKavaiya** [FirebaseExtended/flutterfire#3209]
**Describe the bug**
Today, I saw that many packages got updates. And I updated them. Unfortunately, I got below error on `firebase_admob`:

```
Because firebase_admob 0.9.3+4 depends on firebase_core ^0.4.2+1 and no versions of firebase_admob match >0.9.3+4 <0.10.0, firebase_admob ^0.9.3+4 requires firebase_core ^0.4.2+1.

So, because myapp depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.
pub get failed (1; So, because myapp depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.)
```

**To Reproduce**
pubspec.yaml:
```
firebase_core: ^0.5.0
firebase_admob: ^0.9.3+4
```

**Expected behavior**
The package `firebase_admob` should be updated to use new `firebase_core`...

**Flutter doctor**
```
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.3 19D76, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)
```

**Comment by kroikie** [comment]
Hi @RaviKavaiya this is a known issue and we are working on updating admob to work with the new plugins. Till then if you are using AdMob you will have to stay with `v0.4.5` of firebase_core.

I'll leave this open to track moving admob to new core.

**Comment by RaviKavaiya** [comment]
Hello @kroikie thanks. Can you tell me an expected timeline about new plugin? Because, I am developing an app that depends on all these (majorly, new cloud_firestore plugin)...

**Comment by kavehmb** [comment]
any update on this?

**Comment by mulderpf** [comment]
I am struggling with the same issue.  I am a little bit frustrated by this, because we are encouraged as developers to use the whole Firebase eco-system with Flutter (and I would go as far as to say that this is a selling point in terms of stability and trust that because all the plugins are from the same company, things would stay in-sync).  I guess I cannot upgrade any of my Firebase components now until Admob is updated.

**Comment by maheshkumar2150** [comment]
Any new news?
v0.4.5 of firebase_core does not work with other firebase plugins.

**Comment by beagle-barks** [comment]
Same problem here. I'm using almost all firebase plugins, and cannot upgrade. Very frustrating

**Comment by SwissCheese5** [comment]
Same issue

**Comment by kimteapung** [comment]
Is there any possible date to resolve the issue? Thank you.

**Comment by Salakar** [comment]
AdMob compatibility update has been merged. Will publish a dev release tomorrow. Thanks everyone

**Comment by kw2019ltd** [comment]
@Salakar  what about firebase_crashlytics ?

**Comment by Salakar** [comment]
https://github.com/FirebaseExtended/flutterfire/discussions/3371

**Comment by marciorr** [comment]
Any idea when the release will be available?

**Comment by maheshkumar2150** [comment]
> AdMob compatibility update has been merged. Will publish a dev release tomorrow. Thanks everyone

Super! Thanks

**Comment by maheshkumar2150** [comment]
> AdMob compatibility update has been merged. Will publish a dev release tomorrow. Thanks everyone

Hi

Just waiting for the release..

**Comment by praveentcom** [comment]
Please release it team, we’re waiting for almost a week and a half.

**Comment by john990** [comment]
> AdMob compatibility update has been merged. Will publish a dev release tomorrow. Thanks everyone

Hi, it looks like there is still no new version. When will it be released? We are waiting, thank you. 
:(

**Comment by Salakar** [comment]
`0.10.0-dev.1` is up now

**Comment by amanv8060** [comment]
is this dev release suitable for production app?

**Comment by flschlosser** [comment]
Having the same question as @amanv8060, is the dev release suitable for production?

**Comment by luismarcilio** [comment]
Same issue here...
I can't downgrade firebase_core because of other dependencies:

**Comment by marcqtan** [comment]
> is this dev release suitable for production app?

any answers here?

**Comment by ndhbr** [comment]
> is this dev release suitable for production app?

I did it. No complaints so far.
