### ISSUE TITLE
[web]: How to use firebase phone auth in flutter web

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#322]
finding it difficult to get ApplicationVerifier for _firebaseAuth.signInWithPhoneNumber(phoneNumber, ApplicationVerifier

**Comment by CoderJerry** [comment]
When can we expect phone auth feature for flutter web ?

**Comment by yvzoncu** [comment]
i have no idea but i can share another thing i noticed regarding this issue. Google is banning the user after this error. switch user and continue testing.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
