### ISSUE TITLE
controller!=null is not true

### ISSUE THREAD

**Issue by itssidhere** [FirebaseExtended/flutterfire#3220]
After upgrading the flutterfire plugins . I am repeatedly getting this error

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart': Failed assertion: line 159 pos 12: 'controller != null': is not true.

**Comment by Ehesp** [comment]
Closing - please don't remove the issue template, it is there to help us know your environment and setup.
