### ISSUE TITLE
[cloud_firestore_platform_interface] controller != true

### ISSUE THREAD

**Issue by itssidhere** [FirebaseExtended/flutterfire#3222]
**Describe the bug**
After updating flutterfire plugins I am getting this error occasionally 

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart': Failed assertion: line 159 pos 12: 'controller != null': is not true.

**To Reproduce**
I am getting this error usually when I query a collection

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart': Failed assertion: line 159 pos 12: 'controller != null': is not true.
E/flutter ( 9482): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
E/flutter ( 9482): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
E/flutter ( 9482): #2      MethodChannelFirebaseFirestore._handleError
E/flutter ( 9482): #3      MethodChannelFirebaseFirestore._handleDocumentSnapshotError 
package:cloud_firestore_platform_interface/…/method_channel/method_channel_firestore.dart:113
E/flutter ( 9482): #4      MethodChannelFirebaseFirestore._handleDocumentSnapshotEvent 
package:cloud_firestore_platform_interface/…/method_channel/method_channel_firestore.dart:103
E/flutter ( 9482): #5      new MethodChannelFirebaseFirestore.<anonymous closure> 
package:cloud_firestore_platform_interface/…/method_channel/method_channel_firestore.dart:38
E/flutter ( 9482): #6      MethodChannel._handleAsMethodCall 
package:flutter/…/services/platform_channel.dart:409
E/flutter ( 9482): #7      MethodChannel.setMethodCallHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:377
E/flutter ( 9482): #8      _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:199
E/flutter ( 9482): #9      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
E/flutter ( 9482): #10     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter ( 9482): #11     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 9482): #12     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 9482): #13     _invoke3  (dart:ui/hooks.dart:289:10)
E/flutter ( 9482): #14     _dispatchPlatformMessage  (dart:ui/hooks.dart:164:5)
E/flutter ( 9482):
```

**Comment by larssn** [comment]
I had the same issue, after upgrading from 0.13 to 0.14

I fixed it by bumping the version of analytics in build.gradle from
```
implementation 'com.google.firebase:firebase-analytics-ktx:17.4.3'
implementation 'com.google.firebase:firebase-analytics:17.4.3'
```
to
```
implementation 'com.google.firebase:firebase-analytics-ktx:17.5.0'
implementation 'com.google.firebase:firebase-analytics:17.5.0'
```

**Comment by TahaTesser** [comment]
Tried to reproduce several times, no such errorr

```
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
```

<details> 
<summary>code sample</summary> 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  print('Initialized default app $app');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: BookList(),
      ),
    );
  }
}

class BookList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: FirebaseFirestore.instance.collection('books').snapshots(),
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (snapshot.hasError) return new Text('Error: ${snapshot.error}');
        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return new Text('Loading...');
          default:
            return new ListView(
              children: snapshot.data.docs.map((DocumentSnapshot document) {
                return new ListTile(
                  title: new Text(document.data()['title']),
                  subtitle: new Text(document.data()['author']),
                );
              }).toList(),
            );
        }
      },
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\Code\flutter_stable
    • Framework revision bbfbf1770c (6 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details> 


Please add these in `pubspec.yaml` and try again
```
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
```

if the problem persist, Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by itssidhere** [comment]
As I said it's occasional it happens if I query collections again rapidly according to me. I am not able to reproduce it on demand

**Comment by itssidhere** [comment]
@TahaTesser #3237

**Comment by Ehesp** [comment]
Okay so digging into this one, this assertion is thrown when a snapshot handler throws a native error, and for some reason the StreamController for that subscription no longer exists.

I manage to get this myself but couldn't replicate consistently.

**Comment by Ehesp** [comment]
Found the issue! PR linked.

**Comment by Salakar** [comment]
Fix merged. Release will be out in the next hour or so.

**Comment by Salakar** [comment]
Release with a fix is now published. Latest versions can be seen [here](https://firebase.flutter.dev/docs/migration/#2-update-firebase-plugins). 

Thanks again for the bug report :)

**Comment by itssidhere** [comment]
@Salakar  Thanks for fixing it quickly

**Comment by larssn** [comment]
Already fixed! Impressive, thanks for your hard work guys.

**Comment by joknjokn** [comment]
I just had this `'controller != null': is not true` error. I'm on 0.14.0+2. Is it supposed to be fixed in that version?

**Comment by Ehesp** [comment]
Yeah it should be. If you still havre the issue can you reproduce it consistently?

**Comment by joknjokn** [comment]
I have only seen it once (emulator), and not sure when/where it happened. I'll let you know if it happens again.

**Comment by joknjokn** [comment]
I just had it again. Could have been after adding a document to Firestore (using .set), or in relation to a StreamBuilder using Firestore.

```
E/flutter ( 5308): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart': Failed assertion: line 159 pos 12: 'controller != null': is not true.
E/flutter ( 5308): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 5308): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 5308): #2      MethodChannelFirebaseFirestore._handleError (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:159:12)
E/flutter ( 5308): #3      MethodChannelFirebaseFirestore._handleQuerySnapshotError (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:84:5)
E/flutter ( 5308): #4      MethodChannelFirebaseFirestore._handleQuerySnapshotEvent (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:74:7)
E/flutter ( 5308): #5      new MethodChannelFirebaseFirestore.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:32:18)
E/flutter ( 5308): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:432:55)
E/flutter ( 5308): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:385:33)
E/flutter ( 5308): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
E/flutter ( 5308): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
E/flutter ( 5308): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 5308): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5308): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5308): #13     _invoke3 (dart:ui/hooks.dart:281:10)
E/flutter ( 5308): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
E/flutter ( 5308): 

```

**Comment by Ehesp** [comment]
@joknjokn It'll be the StreamBuilder - could you share the code which you're using to stream the data?

**Comment by marcmarder** [comment]
It happens to me too. When I start the App from the VSCode-Debugger OR on the device (using the build apk). 
But it works fine when using the Terminal and `flutter run --verbose`. Hope this helps somehow.

**Comment by exptk3** [comment]
I had the same problem. This usually occurs when many items are fetched into the stream.
This makes it impossible to make most of the Flutter apps that use Firebase, so I think it is a problem that needs to be solved quickly.

* package
firebase_auth: ^0.18.0+1
cloud_firestore: ^0.14.0+2
firebase_storage: ^4.0.0
firebase_admob: ^0.10.0-dev.1
firebase_messaging: ^7.0.0
cloud_functions: ^0.6.0
firebase_core : ^0.5.0
...

* code
_streamSubscription = stream.listen((item) async {});
Here stream is collection stream.

* error log
E/flutter (24517): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart': Failed assertion: line 159 pos 12: 'controller != null': is not true.
E/flutter (24517): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (24517): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (24517): #2      MethodChannelFirebaseFirestore._handleError (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:159:12)
E/flutter (24517): #3      MethodChannelFirebaseFirestore._handleQuerySnapshotError (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:84:5)
E/flutter (24517): #4      MethodChannelFirebaseFirestore._handleQuerySnapshotEvent (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:74:7)
E/flutter (24517): #5      new MethodChannelFirebaseFirestore.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_firestore.dart:32:18)
E/flutter (24517): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:432:55)
E/flutter (24517): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:385:33)
E/flutter (24517): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
E/flutter (24517): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
E/flutter (24517): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24517): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24517): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24517): #13     _invoke3 (dart:ui/hooks.dart:281:10)
E/flutter (24517): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)

**Comment by Ehesp** [comment]
I've added a PR for this which protects against the crash. It's not a full solution but should help against these unwanted errors.

**Comment by itssidhere** [comment]
@Ehesp Please have a look at #3354
