### ISSUE TITLE
[firebase_auth] 0.18 Changelog doesn't incude emailVerified

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#3228]
I upgraded from 0.16 to 0.18 and I can see `FirebaseUser.isEmailVerified` was changed to `User.emailVerified`, so there's no `is` anymore (which I personally don't like, I read it better with the `is`), but this wasn't included on the Changelog.

**Comment by TahaTesser** [comment]
https://pub.dev/packages/firebase_auth/changelog

**Comment by alfiepoleon** [comment]
Still not added, fairly easy to find but still. :)

**Comment by Ehesp** [comment]
Will close this one off - fairly dated now - apologies it was missed.
