### ISSUE TITLE
[firebase_auth] Please provide a way to set displayName

### ISSUE THREAD

**Issue by stephenhuey** [FirebaseExtended/flutterfire#3231]
I'm not seeing any way to set the displayName with Firebase Auth.  My preference would be to set it when creating the account, but I was surprised to see when trying even `0.18.0` (the latest version) that I'm not finding any way to set the `displayName` in Firebase Authentication anytime, even after account creation!  

[You can set displayName with Node.js but not Flutter](https://firebase.google.com/docs/auth/admin/manage-users#node.js_4)

While I get why you would not want all of the function parameters at that link to be available (should not be allowed to set `emailVerified` on the client side), I'm not thinking of any reason why you should be prohibited from setting `displayName` for the user in a Flutter app.   

It seems the only way to get around this is to call a Firebase function to create the account.  :( 

Please show me the light if I am mistaken!

**Comment by stephenhuey** [comment]
Apparently you can update a FirebaseUser like so:

[firebaseUser.updateProfile(userUpdateInfo)](https://stackoverflow.com/questions/61580479/flutter-firebase-i-am-trying-to-change-displayname-but-displayname-is-null-on)

Well, I suppose this is acceptable, though I was relying on having the information available in an onCreate trigger and unfortunately that would only be available in an onUpdate trigger since it's a second call to Firebase Auth.  That would be acceptable if Firebase Auth had onUpdate triggers!  Apparently people have wanted onUpdate triggers for a while, probably longer than this:

[Asking for onUpdate trigger a year and a half ago](https://groups.google.com/g/firebase-talk/c/U4j2JYnsPlM?pli=1)

Any chance of either being able to submit additional parameters with the email and password on create, or an onUpdate trigger?

**Comment by Ehesp** [comment]
There is a [`userChanges`](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/userChanges.html) API to help with this locally. Other than that, it would need to exist on the wider Firebase ecosystem SDKs.

**Comment by stephenhuey** [comment]
Yes, the method I mentioned is the Flutter version of that and I'm making use of that behind the scenes as a sort of band-aid solution.  I appreciate your response.  If anyone has onCreate triggers depending on the displayName, the only way to get around this omission is to create the user with a cloud function that has access to Admin.  I'd use a Firebase Auth onUpdate trigger instead, but Firebase Auth has no onUpdate trigger.  :(
