### ISSUE TITLE
FirebaseException was thrown building MyApp(dirty): [core/no-app] No Firebase App '[DEFAULT]' has been created

### ISSUE THREAD

**Issue by gurulnd-git** [FirebaseExtended/flutterfire#3235]
This happened when updating firebase_auth to 0.18 and its dependencies,if we switch back to older version it works

firebase_auth: ^0.18.0
cloud_firestore: ^0.14.0
google_sign_in: ^4.5.1
firebase_core: ^0.5.0
firebase_core_web: ^0.2.0

to

firebase_auth: ^0.16.1
cloud_firestore: ^0.13.7
google_sign_in: ^4.5.1
firebase_core: ^0.4.5
firebase_core_web: ^0.1.1+2

**Comment by thearaks** [comment]
I noticed that the initialization became somewhat non-blocking in the latest version (0.14.0) so you need to handle it asynchronously:

```dart
Firebase.initializeApp().then((_) => doYourStuffWithFirebase());
```

**Comment by TahaTesser** [comment]
Hi @gurulnd-git 

You need to include this in main method  from https://pub.dev/packages/cloud_firestore/example
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

```

Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by lucasdessy** [comment]
@TahaTesser fix does work but if you close the app with the back button then open it again, it will throw the error again. I couldn't find a fix for that.

**Comment by TahaTesser** [comment]
@lucasdessy flutter run -v again
