### ISSUE TITLE
[firebase_admob] Prepare your apps for iOS 14 issue

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [FirebaseExtended/flutterfire#3236]
We need to add this to the package `firebase_admob`.

The issue is in Admob's dashboard.

```
Prepare your apps for iOS 14 Apple announced the new AppTrackingTransparency framework, which requires changes to your iOS apps. Implement the GMA SDK 7.64.0 (or later) and set up consent messaging to help prevent a significant loss in ad revenue.
```

<img src="https://i.imgur.com/UN5q6Y2.png" />

**Comment by Ehesp** [comment]
@kroikie one to take up internally 👍

**Comment by ianpark** [comment]
This is urgently required. how do we get this done asap?

**Comment by kroikie** [comment]
I believe this should now be resolved. The `firebase_admob` plugin now depends on required AdMob pod #3347

**Comment by deniza** [comment]
Hey guys. I just published a package to solve this problem. Just use this package, build your apps using Xcode 12 and publish to an ios 14 device for a test drive.

https://pub.dev/packages/app_tracking_transparency

@kroikie I am afraid but updating admob framework does not solve this issue. First we should  build our app using latest Xcode 12 (currently in beta). Then we call ATTrackingManager functions to request tracking permissions. After these steps firebase_admob sdk can actually use tracking identifier to serve personalized ads.
