### ISSUE TITLE
[cloud_firestore] Add `Source.cacheAndServer` flag

### ISSUE THREAD

**Issue by cubuspl42** [FirebaseExtended/flutterfire#3241]
It would be practical to have a functionality that allows you to ask Firestore: "please give me this value from cache, but fall back to server if this key doesn't exist in cache".

Usage could look like this:
```dart
final snapshot = await documentReference.get(source: Source.cacheAndServer);
```

This issue is basically a copy of https://github.com/FirebaseExtended/flutterfire/issues/765, which was closed with response ["this is already implemented"](https://github.com/FirebaseExtended/flutterfire/issues/765#issuecomment-617713542). That issue is now locked. As the mentioned feature is obviously not implemented, I'm creating a new one.

**Comment by Ehesp** [comment]
Firestore queries such as [Document.get](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/DocumentReference/get.html) support [GetOptions](https://pub.dev/documentation/cloud_firestore_platform_interface/latest/cloud_firestore_platform_interface/GetOptions-class.html) which supports setting a [Source](https://pub.dev/documentation/cloud_firestore_platform_interface/latest/cloud_firestore_platform_interface/Source-class.html).

Is this what you have in mind or something else?

**Comment by creativecreatorormaybenot** [comment]
@Ehesp The question is asking for **cache first** and only retrieve from server if cache fails. Only the opposite is currently supported.

**Comment by cubuspl42** [comment]
Yes, I'm aware of the `Source` enum. I'm suggesting to add a new value to it.

`Source.serverAndCache` tries _first_ server, _then_ cache (if you can't access the server, i.e. the device is offline).

This issue (as well as the closed one) is a request for the opposite behavior: to try _first_ cache, _then_ server (if the cache can't answer the query, i.e. the document is not present in cache). I'd personally also add a side effect or attempting to refresh the cache asynchronously in the background, but without waiting for the response.

**Comment by cubuspl42** [comment]
@Ehesp I'd also like to add that two previous iterations of this issue (https://github.com/flutter/flutter/issues/19078 and https://github.com/FirebaseExtended/flutterfire/issues/765) had over 60 upvotes. Closing **and** locking the latter with response "we have something opposite of what you ask" is, in my personal opinion, unprofessional and not in the open source spirit.

**Comment by Ehesp** [comment]
We can only support what the native Firebase SDKS support, for example on [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/Source).

**Comment by cubuspl42** [comment]
This functionality can be implemented on top of native Android API. It's just a bit tricky and so worth to be included in the library itself. If it's absolutely unacceptable to have any functionality not directly present in the native API, then please refer to something, even if it's a team-internal agreement.

**Comment by Ehesp** [comment]
I agree the functionality would be good to have, however this is something which needs to be rolled out across the wider Firebase eco-system. Creating a [feature request](https://firebase.google.com/support/troubleshooter/report/features) would be a good place to start.

If this is urgent, then I'd suggest wrapping the existing API by making a request to a cached document, and if that fails force a server request).

**Comment by cubuspl42** [comment]
> however this is something which needs to be rolled out across the wider Firebase eco-system

I didn't know that. I had a more distributed model in my head, i. e. that it would be acceptable to add a feature first to one implementation, and then add propagate it to others. Otherwise adding a simple feature is nearly a corporation-scale event. But if your policy is more centralized, then I respect that.

> Creating a feature request would be a good place to start.

Thank you, I might do that. I'm not sure if you share a similar experience, but in general officially-hosted Google feature request forms seem to act like a pipe to `/dev/null` from perspective of a non-Googler, at least compared to GitHub issues. My motivation to use them is extremely low.

**Comment by cubuspl42** [comment]
@Salakar Hi Mike, I can see that you downvoted my previous comment. If you have any insights or thoughts about the matters I brought up, then I'd like to know your point of view.

**Comment by flutterfrank** [comment]
@cubuspl42 Maybe this helps you: https://pub.dev/packages/firestore_cache

**Comment by Ehesp** [comment]
Going to close this based on the above conversations - happy to discuss though.
