### ISSUE TITLE
Erro [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by Raphael-Jose-Ferraro-IRForever** [FirebaseExtended/flutterfire#3242]
After new update(0.5.0) returned this: 
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

**Comment by Ehesp** [comment]
Hey, make sure you follow the [new documentation](https://firebase.flutter.dev/docs/overview) - which also includes a migration guide.
