### ISSUE TITLE
[all products] Windows Support Documentation

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [FirebaseExtended/flutterfire#3243]
This issue is to document the process of adding Windows support to FlutterFire plugins and to discuss the possibility.

**Comment by esDotDev** [comment]
It would be great to know even some rough timeline on when Windows development will begin, and whether it's considered fairly feasible / low effort.

**Comment by Ehesp** [comment]
It's considered, however priority right now is Android, iOS & Web.

**Comment by YazeedAlKhalaf** [comment]
So by changing the title to documentation, do you mean that the implementation is there but needs docs, or am I getting it wrong?

**Comment by jeffmilanes** [comment]
any updates?

**Comment by WashingtonlGarcia** [comment]
> alguma atualização?


I want saber too

**Comment by WashingtonlGarcia** [comment]
> alguma atualização?


I also want to know

**Comment by DevKang** [comment]
I am waiting for it ~! :)

**Comment by Ehesp** [comment]
I think it's worth dropping this issue as relevant: https://github.com/firebase/firebase-cpp-sdk/issues/42#issuecomment-591073497

The C++/Windows SDK is designed for mobile games, thus a lot of the implementations are stubs - we'd end up with a fragmented experience.
