### ISSUE TITLE
[all products] Linux Support Documentation

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [FirebaseExtended/flutterfire#3244]
This issue is to document the process of adding Linux support to FlutterFire plugins and to discuss the possibility.

**Comment by YazeedAlKhalaf** [comment]
So by changing the title to documentation, do you mean that the implementation is there but needs docs, or am I getting it wrong?

**Comment by Salakar** [comment]
Duplicate of https://github.com/FirebaseExtended/flutterfire/discussions/5557
