### ISSUE TITLE
Firebase Auth Causes the Application to crash

### ISSUE THREAD

**Issue by ritvij-saxena** [FirebaseExtended/flutterfire#3249]
**Code:**

main.dart

```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return StreamProvider<FirebaseUser>.value(
      value: AuthService().user,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Wrapper(),
      ),
    );
  }
}
```
wrapper.dart
```
class Wrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final FirebaseUser user = Provider.of<FirebaseUser>(context);
    if(user!=null){
      return HomePage();
    }else{
     return LoginPage();
    }
  }
}
```

On the homepage.dart, I have a form, the app crashes when I try to fill out the form.

 
Error: 
> W/Firestore(23276): (21.3.0) [FirestoreCallCredentials]: Failed to get token: com.google.android.gms.common.api.ApiException: 8: The connection to Google Play services was lost.
> I/BiChannelGoogleApi(23276): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@a3533fe
> W/DynamiteModule(23276): Local module descriptor class for com.google.firebase.auth not found.
> I/FirebaseAuth(23276): [FirebaseAuth:] Preparing to create service connection to gms implementation
> I/Choreographer(23276): Skipped 44 frames!  The application may be doing too much work on its main thread.
> Lost connection to device.

or 

> W/GmsClient(26079): IGmsServiceBroker.getService failed
> W/GmsClient(26079): android.os.DeadObjectException
> W/GmsClient(26079): 	at android.os.BinderProxy.transactNative(Native Method)
> W/GmsClient(26079): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/GmsClient(26079): 	at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source:13)
> W/GmsClient(26079): 	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:244)
> W/GmsClient(26079): 	at com.google.android.gms.common.api.internal.zabo.run(com.google.android.gms:play-services-base@@17.1.0:11)
> W/GmsClient(26079): 	at android.os.Handler.handleCallback(Handler.java:873)
> W/GmsClient(26079): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> W/GmsClient(26079): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
> W/GmsClient(26079): 	at android.os.Looper.loop(Looper.java:193)
> W/GmsClient(26079): 	at android.os.HandlerThread.run(HandlerThread.java:65)
> W/DynamiteModule(26079): Local module descriptor class for com.google.firebase.auth not found.
> I/FirebaseAuth(26079): [FirebaseAuth:] Preparing to create service connection to gms implementation
> W/InputMethodManager(26079): IME died: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
> W/InputMethodManager(26079): android.os.DeadObjectException
> W/InputMethodManager(26079): 	at android.os.BinderProxy.transactNative(Native Method)
> W/InputMethodManager(26079): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputMethodSession$Stub$Proxy.updateSelection(IInputMethodSession.java:224)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager.updateSelection(InputMethodManager.java:1653)
> W/InputMethodManager(26079): 	at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:71)
> W/InputMethodManager(26079): 	at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:92)
> W/InputMethodManager(26079): 	at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:442)
> W/InputMethodManager(26079): 	at io.flutter.plugin.editing.InputConnectionAdaptor.finishComposingText(InputConnectionAdaptor.java:133)
> W/InputMethodManager(26079): 	at android.view.inputmethod.BaseInputConnection.closeConnection(BaseInputConnection.java:161)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:225)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputConnectionWrapper.closeConnection(IInputConnectionWrapper.java:211)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.deactivate(InputMethodManager.java:588)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1315)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:526)
> W/InputMethodManager(26079): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> W/InputMethodManager(26079): 	at android.os.Looper.loop(Looper.java:193)
> W/InputMethodManager(26079): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> W/InputMethodManager(26079): 	at java.lang.reflect.Method.invoke(Native Method)
> W/InputMethodManager(26079): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> W/InputMethodManager(26079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> W/InputMethodManager(26079): IME died: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
> W/InputMethodManager(26079): android.os.DeadObjectException
> W/InputMethodManager(26079): 	at android.os.BinderProxy.transactNative(Native Method)
> W/InputMethodManager(26079): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputMethodSession$Stub$Proxy.updateCursorAnchorInfo(IInputMethodSession.java:327)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager.updateCursorAnchorInfo(InputMethodManager.java:1781)
> W/InputMethodManager(26079): 	at io.flutter.plugin.editing.InputConnectionAdaptor.finishComposingText(InputConnectionAdaptor.java:141)
> W/InputMethodManager(26079): 	at android.view.inputmethod.BaseInputConnection.closeConnection(BaseInputConnection.java:161)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:225)
> W/InputMethodManager(26079): 	at com.android.internal.view.IInputConnectionWrapper.closeConnection(IInputConnectionWrapper.java:211)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.deactivate(InputMethodManager.java:588)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1315)
> W/InputMethodManager(26079): 	at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:526)
> W/InputMethodManager(26079): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> W/InputMethodManager(26079): 	at android.os.Looper.loop(Looper.java:193)
> W/InputMethodManager(26079): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> W/InputMethodManager(26079): 	at java.lang.reflect.Method.invoke(Native Method)
> W/InputMethodManager(26079): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> W/InputMethodManager(26079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> W/DynamiteModule(26079): Local module descriptor class for com.google.firebase.auth not found.
> I/FirebaseAuth(26079): [FirebaseAuth:] Preparing to create service connection to gms implementation
> I/resssdriverlit(26079): Background concurrent copying GC freed 14611(632KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/4MB, paused 2.488ms total 100.611ms

**flutter doctor -v**

> [√] Flutter (Channel master, v1.15.4-pre.51, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
>     • Flutter version 1.15.4-pre.51 at D:\Flutter Course\flutter_windows_v1.0.0-stable\flutter
>     • Framework revision dc636069fc (6 months ago), 2020-02-12 22:22:49 -0800
>     • Engine revision e0ebaea590
>     • Dart version 2.8.0 (build 2.8.0-dev.9.0 e4c39721c4)
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\ritvi\AppData\Local\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-30, build-tools 29.0.2
>     • Java binary at: D:\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at D:\Android Studio
>     • Flutter plugin version 48.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3)
>     • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [!] VS Code (version 1.48.0)
>     • VS Code at C:\Users\ritvi\AppData\Local\Programs\Microsoft VS Code
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (3 available)
>     • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
>     • Chrome              • chrome        • web-javascript • Google Chrome 84.0.4147.125
>     • Web Server          • web-server    • web-javascript • Flutter Tools
> 
> ! Doctor found issues in 2 categories.

**Comment by Salakar** [comment]
I think this may be that Google Play services is out of date on your Android device, could you check & update it if possible - thanks.

Also could you provide a copy of your `android/build.gradle` and `android/app/build.gradle` files.

**Comment by ritvij-saxena** [comment]
**android/build.gradle**

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**android/app/build.gradle**

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.myapp"
//        minSdkVersion 16
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
```



**Emulator Details**

> Name: Pixel_3a_API_28
> CPU/ABI: Google Play Intel Atom (x86)
> Path: C:\Users\ritvi\.android\avd\Pixel_3a_API_28.avd
> Target: google_apis_playstore [Google Play] (API level 28)
> Skin: pixel_3a
> SD Card: 512M
> fastboot.chosenSnapshotFile: 
> runtime.network.speed: full
> hw.accelerometer: yes
> hw.device.name: pixel_3a
> hw.lcd.width: 1080
> hw.initialOrientation: Portrait
> image.androidVersion.api: 28
> tag.id: google_apis_playstore
> hw.mainKeys: no
> hw.camera.front: emulated
> avd.ini.displayname: Pixel 3a API 28
> hw.gpu.mode: auto
> hw.ramSize: 1536
> PlayStore.enabled: true
> fastboot.forceColdBoot: no
> hw.cpu.ncore: 4
> hw.keyboard: yes
> hw.sensors.proximity: yes
> hw.dPad: no
> hw.lcd.height: 2220
> vm.heapSize: 256
> skin.dynamic: yes
> hw.device.manufacturer: Google
> hw.gps: yes
> hw.audioInput: yes
> image.sysdir.1: system-images\android-28\google_apis_playstore\x86\
> showDeviceFrame: yes
> hw.camera.back: virtualscene
> AvdId: Pixel_3a_API_28
> hw.lcd.density: 440
> hw.arc: false
> hw.device.hash2: MD5:0e6953ebf01bdc6b33a2f54746629c50
> fastboot.forceChosenSnapshotBoot: no
> fastboot.forceFastBoot: yes
> hw.trackBall: no
> hw.battery: yes
> hw.sdCard: yes
> tag.display: Google Play
> runtime.network.latency: none
> disk.dataPartition.size: 6442450944
> hw.sensors.orientation: yes
> avd.ini.encoding: UTF-8
> hw.gpu.enabled: yes

**Comment by HTibs** [comment]
same issue

**Comment by tomrozb** [comment]
Updating emulator solved the issue for me:

**Comment by Salakar** [comment]
> Updating emulator solved the issue for me:
> 
> `com.google.android.gms.common.api.ApiException: 8: The connection to Google Play services was lost.`
> 
> If you're running tests on an emulator on CI that may solve the problem for you
> 
> ```
> android-sdk-macosx/tools/bin/sdkmanager "system-images;android-27;google_apis_playstore;x86"
> flutter emulators --create --name android-27-x86-gapi
> flutter emulators
> flutter emulators --launch android-27-x86-gapi
> ```

For anyone else facing this issue, make sure you're emulator is up to date and you're using an emulator that has Google Play Services.
