### ISSUE TITLE
[firebase_crashlytics] Automatic StackTrace will include the library

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#3250]
The new version of the library added automatic stack traces in case none were provided, that's good, but looking at the implementation I think (didn't test) it will include the calls to `_recordError` and `recordError`, which is repetitive and useless, so it would be nicer to have them filtered out.

**Comment by cubuspl42** [comment]
Possibly related to https://github.com/FirebaseExtended/flutterfire/issues/3310

**Comment by Salakar** [comment]
Closing in favour of #3310 - of which is on our internal radar at the moment so hoping to have this looked at soon.
