### ISSUE TITLE
FCM broken on Android with version 7.0.0

### ISSUE THREAD

**Issue by ollydixon** [FirebaseExtended/flutterfire#3252]
```Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)```

With version 7.0.0 live data notifications are broken. (used for things like instant messaging).

Tested on real device and on emulator that were previous working with older version.

Does anyone bother to test these plugins on release?

**Comment by Salakar** [comment]
There has been no underlying changes to FCM in v7.0.0 - major version was only to signify dependency on `firebase_core` and related changes.

> Does anyone bother to test these plugins on release?

If you could take the time to fill out the provided issue template and add detail of what is wrong; that would certainly be a lot more helpful. Thanks!

**Comment by ollydixon** [comment]
The issues from this library have been crazy this year. So many bugs. I think we'll look into migrating away from Firebase.

**Comment by Salakar** [comment]
Sorry about the issues you've had. There is significant improvements in quality coming to all the packages. Check out the roadmap issue if you haven't already: https://github.com/FirebaseExtended/flutterfire/issues/2582

We've only been here the last ~3 months so can't speak for prior to that, but, we do heavily test changes and even provide visible public evidence of such on PRs e.g. https://github.com/FirebaseExtended/flutterfire/pull/3021. We've also added hundreds of new end-to-end integration and unit tests in the past 3 months to Core, Auth, Firestore, Crashlytics, Storage & Functions.

**Comment by ollydixon** [comment]
@Salakar ok thanks for the nice response :-)
