### ISSUE TITLE
Firebase Admin SDK support for Dart

### ISSUE THREAD

**Issue by wstrange** [FirebaseExtended/flutterfire#3254]
Having a native Dart Admin SDK would allow us to use Dart on the front and backend. 

This would be the Dart equivalent of:
https://firebase.google.com/docs/firestore/client/libraries#firebase_admin_sdks

**Comment by kroikie** [comment]
@wstrange I think this would be a valuable addition. I will pass on this request to the Admin SDK team. However I don't think there is much we can do here, so I'll close it.
