### ISSUE TITLE
[website] The Dark Theme links should have a different backgound color

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#3255]
`Future`, `StatefulWidget` and `FutureBuilder` is hard to read on that light-blue on top of the grey, on top of the dark background:

![image](https://user-images.githubusercontent.com/8120472/90689800-043ec780-e247-11ea-85b5-754b344da391.png)

This colors should be different, maybe make the grey background lighter, or change the blue tone of the link text.

**Comment by Salakar** [comment]
Good spot; does this better:

![image](https://user-images.githubusercontent.com/5347038/90691397-2e09e580-e26b-11ea-8024-378bb0ff468e.png)

**Comment by Salakar** [comment]
Update is deploying - will be live shortly. Thanks again for the feedback, really appreciated 🎉

**Comment by feinstein** [comment]
> 
> 
> Good spot; does this look better:
> 
> ![image](https://user-images.githubusercontent.com/5347038/90691397-2e09e580-e26b-11ea-8024-378bb0ff468e.png)

Yep, a lot, thanks.
