### ISSUE TITLE
 Use Firebase Code in platform channel

### ISSUE THREAD

**Issue by tmthecoder** [FirebaseExtended/flutterfire#3260]
**Describe the Bug**
Before the migration of firebase_auth to use firebase_core, I could import the Firebase libraries in both iOS and Android native instances, but after this, I am unable to do so.

**To Reproduce**
1. Create a Flutter project
2. Add Firebase to the project
3. Make a method channel 
4. Try to use firebase with said method channel in native code

**Expected behavior**
I expected to be able to use Firebase methods in both Java and Swift as it says not to add any pods or Gradle implementations.

**Additional context**
I tested adding the pods and Gradle implementations. It does work that way. Are there any drawbacks to doing so?

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on macOS 11.0 20A5343i, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)

[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

**Comment by kroikie** [comment]
@tmthecoder Is there a reason why you can't use the Flutter level dependency?

**Comment by tmthecoder** [comment]
@kroikie yes. I am working with Android background services and iOS today extensions, both of which can't run dart code to my belief

**Comment by kroikie** [comment]
@tmthecoder I see no drawbacks for adding the native dependencies directly. Please report any issues you run into.

**Comment by tmthecoder** [comment]
@kroikie I'll be sure to do so, thanks for clearing it up. So far I haven't had any problems

**Comment by Ehesp** [comment]
Yeah if you're using them directly in your own app, it's best to be explicit about that in your own build setup - the important part is keeping the versions aligned.

Will close, happy to discuss though.
