### ISSUE TITLE
[<Firebase core>] <No app has been configured yet. Error retrieving thread information: (ipc/send) invalid destination port>

### ISSUE THREAD

**Issue by Abdullah-Zakhoi** [FirebaseExtended/flutterfire#3261]
**I made a new app and did the steps in Decs but when I run the app, it is run correctly but still have errors on console**

**my console errors:**
<img width="1000" alt="Screen Shot 2020-08-20 at 6 31 17 AM" src="https://user-images.githubusercontent.com/66040295/90713797-c7a6b680-e2ae-11ea-9f9f-80a4b17b22bd.png">

**I put `FirebaseSDKVersion` on my podfile like this**
<img width="1025" alt="Screen Shot 2020-08-20 at 6 35 01 AM" src="https://user-images.githubusercontent.com/66040295/90713992-4bf93980-e2af-11ea-92e8-28163a3c5ee3.png">

**my `pub file`**
<img width="790" alt="Screen Shot 2020-08-20 at 6 36 22 AM" src="https://user-images.githubusercontent.com/66040295/90714083-8e227b00-e2af-11ea-9361-589d9d0d7f7e.png">

**my testing code**
``` 
import 'package:flutter/material.dart';

// Import the firebase_core plugin
import 'package:firebase_core/firebase_core.dart';

void main() {
  runApp(App());
}

class App extends StatefulWidget {
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  // Set default `_initialized` and `_error` state to false
  bool _initialized = false;
  bool _error = false;

  // Define an async function to initialize FlutterFire
  void initializeFlutterFire() async {
    try {
      // Wait for Firebase to initialize and set `_initialized` state to true
      await Firebase.initializeApp();
      setState(() {
        _initialized = true;
      });
    } catch (e) {
      // Set `_error` state to true if Firebase initialization fails
      setState(() {
        _error = true;
      });
    }
  }

  @override
  void initState() {
    initializeFlutterFire();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Show error message if initialization failed
    if (_error) {
      return MaterialApp(
        home: Scaffold(
          body: Center(
            child: Text('Error 1'),
          ),
        ),
      );
    }

    // Show a loader until FlutterFire is initialized
    if (!_initialized) {
      return MaterialApp(
        home: Scaffold(
          body: Center(
            child: Text('loading'),
          ),
        ),
      );
    }

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text(' my awesome app'),
        ),
      ),
    );
  }
}

```

**Comment by kroikie** [comment]
@Abdullah-Zakhoi I think this may be similar to:
https://github.com/flutter/flutter/issues/63025

**Comment by darshankawar** [comment]
Hi @Abdullah-Zakhoi,
Can you try to remove `firebase_core` plugin and related code and then run the app to see if you still get the error ?
Trying to see if the error is indeed due to `firebase_core` plugin or due to the upgrade as mentioned by @kroikie above.
Thanks.
