### ISSUE TITLE
[firebase_auth] google sign-in crashes on production mode

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#327]
Hello everyone, i've used flutter packages like: 
- firebase_auth: ^0.11.1+8
- google_sign_in: 4.0.4

to (well) sign-in into Google using **Firebase**. In development mode, the app runs well and get authenticated, but in production mode, the app crashes when the Google sign-in popup displays. I've also set the SHA certificates.

Can you guess what the problem is? Thanks in advance!

**Comment by kroikie** [comment]
@Lynxgsm

The issue at https://github.com/flutter/flutter/issues/41362 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @Lynxgsm
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
