### ISSUE TITLE
[firebase_crashlytics, firebase_core] In what order should they be initialized? An example in docs would be great.

### ISSUE THREAD

**Issue by joknjokn** [FirebaseExtended/flutterfire#3271]
Now that we have to run initializeApp on Firebase before anything Firebase-related in the app, I can't seem to figure out a good way to make that work with firebase_crashlytics. I tried the examples of initializeApp using FutureBuilder or StatefulWidget, but both make Crashlytics not work.

Crashlytics should wrap around runApp(), so how can we initialize firebase_core correctly in relation to that, using the examples?

I understand that I'm probably doing something wrong, but I can't figure out what.

Thanks for any help.

**Comment by PeterHdd** [comment]
Try:

```
void main() async {
  // Set `enableInDevMode` to true to see reports while in debug mode
  // This is only to be used for confirming that reports are being
  // submitted as expected. It is not intended to be used for everyday
  // development.
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  Crashlytics.instance.enableInDevMode = true;

  // Pass all uncaught errors to Crashlytics.
  FlutterError.onError = Crashlytics.instance.recordFlutterError;

  runZoned(() {
    runApp(MyApp());
  }, onError: Crashlytics.instance.recordError);
}
```

**Comment by joknjokn** [comment]
Thanks, Peter. It seems to be working now.

I didn't try just awaiting initializeApp in main. I assumed that it would not be good practice, since the examples suggests FutureBuilder or StatefulWidget with handling of error/loading. But if I it's okay to just await it like that, I hope they include your suggestion in their examples (in both firebase_core and firebase_crashlytics). :-)
