### ISSUE TITLE
[firebase_core] Restarting secondary Firebase app on iOS fails to find existing app

### ISSUE THREAD

**Issue by rich-j** [FirebaseExtended/flutterfire#3277]
Restarting our Flutter program that uses `secondary Firebase apps` on iOS fails to find existing Firebase apps. The same program works fine on Flutter web and previously worked on iOS before migrating to `firebase_core: ^0.5.0`.

Our program first tries to restore a Firebase app that was created in a previous session:

    Firebase.app("test");

If that fails (i.e. first run of the program) then we initialize a new Firebase app:

    Firebase.initializeApp(name: "test", options: firebaseOptions);

The issue that we encounter is summed up by these exceptions that are thrown:

    [core/no-app] No Firebase App 'test' has been created - call Firebase.initializeApp()

    [core/duplicate-app] A Firebase App named "test" already exists

So Firebase thinks that the app doesn't exist and already exists...

This seems to be caused by Firebase not yet finalizing initialization. After ` Firebase.initializeApp` throws the `[core/duplicate-app]` exception, we can then call `Firebase.app("test");` and get the existing app (our current workaround). These issues don't occur when running the same program on the web.

Also the list of available apps `Firebase.apps` is not populated on iOS until after the exception. We would prefer to use this list to get Firebase apps that are carried over from previous sessions.

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale en-US)

  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
```

**Comment by GyuriMajercsik** [comment]
This happens to me as well. Basically, hot reload doesn't work anymore when using a different FirebaseApp.

**Comment by Salakar** [comment]
Based on your code above I can't see where you're initialising the defaults, as documented here: https://firebase.flutter.dev/docs/overview/#initializing-flutterfire, specifically you should be calling `await Firebase.initializeApp();` without any arguments before working on any other apps. Internally `await Firebase.initializeApp();` will make other apps it discovers natively available to Dart.

**Comment by rich-j** [comment]
@Salakar yes, we have already initialized the *primary* Firebase app - this is a *secondary* app. Our code returns a `Future` that is functionally composed together that has an effective `await` at a higher level.

It does appear that this bug is fixed, along with others (e.g. https://github.com/FirebaseExtended/flutterfire/issues/3746) with the refactoring that has been done since `firebase_core: 0.5.0` - so closing.
