### ISSUE TITLE
Firebase_Auth check email verfied before sign in

### ISSUE THREAD

**Issue by yurikong** [FirebaseExtended/flutterfire#3281]
There must be a way to check if a user is email verified before firebase signs in the user with email and password!
Currently on the API the method signs in the user without check if it's verified. If I use authStateChanges() to control which page to show to the user and when the user signs in but not email verified, I have to manually sign them out, and that cause problem

"
Future<UserCredential> signInWithEmailAndPassword (
{@required String email,
@required String password}
)
Attempts to sign in a user with the given email address and password.

If successful, it also signs the user in into the app and updates any authStateChanges, idTokenChanges or userChanges stream listeners.
"

**Comment by Salakar** [comment]
This is how the Firebase API works, you have to sign in to know the status of the user, so this is working as intended. Unless you have specific reasons for doing so - you don't need to sign your user out, you could just block interactions and request that they verify their account.
