### ISSUE TITLE
firebase_analytics >=6.0.0 incompatible with firebase_admob 0.9.3+4

### ISSUE THREAD

**Issue by da7om85** [FirebaseExtended/flutterfire#3282]
Because firebase_analytics >=6.0.0 depends on firebase_core ^0.5.0 and firebase_admob 0.9.3+4 depends on firebase_core ^0.4.2+1, firebase_analytics >=6.0.0 is incompatible with firebase_admob 0.9.3+4.

And because no versions of firebase_admob match >0.9.3+4 <0.10.0, firebase_analytics >=6.0.0 is incompatible with firebase_admob ^0.9.3+4.

please fix this issue.

**Comment by Salakar** [comment]
Closing in favor of https://github.com/FirebaseExtended/flutterfire/issues/3209 - same issue, AdMob needs updating.
