### ISSUE TITLE
[firebase_auth] Secondary Firebase app auth currentUser "disappears" on reinitialized iOS

### ISSUE THREAD

**Issue by rich-j** [FirebaseExtended/flutterfire#3283]
When we reinitialize our program on iOS the `currentUser` eventually becomes `null`. The same program works fine on web. Also when the user is first authenticated the issue doesn't happen - it only occurs on iOS when reinitializing and using the cached credentials.

Here is a simple code snippet that shows the issue - note we are running this in a secondary Firebase app:

```dart
    final origUser = firebaseAuth.currentUser;
    print("Init sees origUser: ${origUser.email}");
    firebaseAuth.userChanges().listen((user) => print("Init userChanges: ${user?.email}"));
    Timer(Duration(seconds:1), () {
      final watchedUser = firebaseAuth.currentUser;
      print( watchedUser == null ? "Delay doesn't see user!!!" : "Delay sees user: ${watchedUser.email}");
      origUser.getIdToken().then( (token) => print("Delay got origUser token: ${token.substring(0, 10)}") );
      firebaseAuth.userChanges().listen((user) => print("Delay userChanges: ${user?.email}"));
    } );
```

When we reinitialize our program on iOS we get:

```
Init sees origUser: rtest@ft.com
Init userChanges: rtest@ft.com
Delay doesn't see user!!!
Delay userChanges: null
Delay got origUser token: eyJhbGciOi
```

Note that `currentUser` is available at first after reinitializing. Also we can use the captured `origUser` after the delay to `getIdToken()` so the user is still valid. We just can no longer request the `currentUser` or use the streams.

Secondary Firebase apps on iOS do have an issue with reinitializing that we previously reported #3277 that could be related.

When we run on the web or when first authenticated on iOS we correctly get:

```
Init sees origUser: rtest@ft.com
Init userChanges: rtest@ft.com
Delay sees user: rtest@ft.com
Delay userChanges: rtest@ft.com
Delay got origUser token: eyJhbGciOi
```

We encountered this issue when migrating an existing program to the new libraries.

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale en-US)

  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
```

**Comment by Ehesp** [comment]
@rich-j Thanks for the issue. Could you explain what you mean by `reinitialize our program`? Do you mean Hot Reload/Restart? Or quitting the app and restarting?

**Comment by Ehesp** [comment]
Replicated & fixed in the linked PR. Cheers.
