### ISSUE TITLE
[firebase_messaging] Is there a way not to load all dependencies?

### ISSUE THREAD

**Issue by MaximMonakhov** [FirebaseExtended/flutterfire#3289]
Is there a way not to load all dependencies? 
I need only messaging, but pod also loads analytics, some diagnostics and other utilities
This results in a larger application size.

**Comment by Salakar** [comment]
The latest version of messaging is using the `CoreOnly` podspec, so analytics etc shouldn't be being pulled in, could you try that. You didn't fill out the issue template so I don't know what version you're on.
