### ISSUE TITLE
[CloudFunctions] Requests works in Postman, but trigger exceptions when sending them using the CloudFunctions module.

### ISSUE THREAD

**Issue by mickael-h** [FirebaseExtended/flutterfire#3290]
**Describe the bug**
When I call a Cloud Function using HttpsCallable.call, it crashes with an exception saying "Response is not valid JSON object.".

**To Reproduce**
1. Create a Cloud Function and deploy it.
2. Test it in Postman.
3. Test it using FlutterFire.
4. See the exception.

**Expected behavior**
Not crashing and seeing the same response as in the browser.

**Additional context**
My callable function:
```
exports.callableTest = functions.region('europe-west1')
.https.onCall((data, context) => {
    return {"text": "Hello World"};
});
```

The result in Postman:
![image](https://user-images.githubusercontent.com/7953005/90982648-c0123680-e568-11ea-946c-19a2d6123ec9.png)

The result in my app:
![image](https://user-images.githubusercontent.com/7953005/90982723-50507b80-e569-11ea-9e5a-17c864805262.png)

**Flutter doctor**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale fr-FR)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.48.1)
[√] Connected device (1 available)

```
Exception has occurred.
PlatformException (PlatformException(functionsError, Cloud function failed with exception., {code: INTERNAL, details: null, message: Response is not valid JSON object.}))
```

**Comment by vixez** [comment]
What fixes it for me is returning an object, instead of a string in the Cloud Function.

Doesn't work:
```
response.send(result);
```

Works:
```
response.send({
  'data': result
});
```

Of course this is not a proper solution. If you are unable to modify the function's output due to implementations in client applications this won't work.

**Comment by mickael-h** [comment]
> response.send(result);

Are you by any chance using https.onRequest instead of https.onCall?

**Comment by vixez** [comment]
@mickael-h 
Yes, I am. With onCall I wasn't able to pass the parameters through to the cloud function (query, params and body were all `undefined`).

I have now noticed that Flutter Web does not work, so I'm looking into that as well.

**Comment by mickael-h** [comment]
How do you check for authentication then?

**Comment by vixez** [comment]
@mickael-h Haven't reached that part yet, sorry

**Comment by TahaTesser** [comment]
Hi @mickael-h 
I cannot reproduce the issue using the official example 
Can you please provide your `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? instead of screenshots
Thank you

**Comment by mickael-h** [comment]
Hi @TahaTesser 
I'll try to find some time to create a minimal code sample to reproduce the problem.
In the meantime, my project is public, if you wish to take a look.
The problematic piece of code is in lib/controllers/planning_controller.dart
https://github.com/mickael-h/bus_guide
