### ISSUE TITLE
[firebase_auth] Web "userChanges" stream providing null user when "currentUser.reload()" called

### ISSUE THREAD

**Issue by rich-j** [FirebaseExtended/flutterfire#3291]
Firebase auth `userChanges()` stream is providing a `null` user on the web. The same code works on iOS. No - we did not `signOut()` the user which would correctly provide a `null`. 

This is in our email address verified watcher which polls for user changes using `reload()`. (Why do we need to poll for data changes from a "real-time DB" is another discussion...). We only use this stream during our create new user processing to verify the email address.

```dart
  /// Watch for updates to the user emailVerified which requires polling
  Stream<User> get watchEmailVerified => _firebaseAuth.userChanges()
      .doOnData((user) => print("Watcher userChanges ${user?.email} ${user?.emailVerified}"))
      .where((user) => user != null)   // TODO remove - should never be null, stream only available while signed in
      .distinct((u1, u2) => u1.emailVerified == u2.emailVerified )
      .doOnListen(() => _startEmailAddressVerifiedWatcher())
      .doOnCancel(() => _stopEmailAddressVerifiedWatcher());

  /// Firebase "real time DB" - have to poll for auth email verify status updates...
  Timer _watcher;
  void _stopEmailAddressVerifiedWatcher() => _watcher?.cancel();
  void _startEmailAddressVerifiedWatcher() {
    _watcher?.cancel();
    _watcher = Timer.periodic( Duration(seconds: 5), (timer) => _firebaseAuth.currentUser.reload() );
  }
```

The above code uses [RxDart](https://pub.dev/packages/rxdart) `.doOnListen/Cancel` to control starting and stopping the polling. We've also added a `print` for debugging and a filter to stop downstream errors. What's notable is the use of `reload()` to force user information to be updated which will be seen by the `userChanges()` stream.

On the web this is our output:

```
UserChanges rtest@ft.com false
UserChanges null null
UserChanges null null
UserChanges null null
```

On iOS we get this (which is what we expect):

```
UserChanges rtest@ft.com false
UserChanges rtest@ft.com false
UserChanges rtest@ft.com true        <-- We validated the email address before this
UserChanges rtest@ft.com true
```

We encountered this issue when migrating an existing program to the new libraries.

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale en-US)

  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
```

**Comment by Salakar** [comment]
cc @Ehesp - any idea on this one?

**Comment by Ehesp** [comment]
Wow this was a derp on my part 🤦‍♂️ PR up to fix it. Sorry about that.
