### ISSUE TITLE
On Hot reload Firebase.initApp rebuilds the tree

### ISSUE THREAD

**Issue by Flucadetena** [FirebaseExtended/flutterfire#3292]
Hi I've updated to the newly released FlutterFire and as we now have to initialize the app at the top of the project, every time I hot reload, the app reinitializes Firebase and destroys the current widget tree, making Hot reload useless.

**To Reproduce**
I simply implemented the example from the docs:

```
class FlutterFireInit extends StatelessWidget {
  final Widget child;
  const FlutterFireInit({Key key, @required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // Initialize FlutterFire
      future: Firebase.initializeApp(),
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          // return SomethingWentWrong();
          print('Something went wrong in Flutter Fire');
        }

        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return child;
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return Container();
      },
    );
  }
}
```

I separated it into its own widget but tried it directly in the 'MyApp()' widget and got the same result.

**Expected behavior**
Keep state on Hot reload.

**Flutter doctor**
```
Doctor summary:
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.1)
[✓] Connected device (1 available)

• No issues found!
```

Jus in case my pubspec version:

  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+1
  firebase_analytics: ^6.0.0
  firebase_dynamic_links: ^0.6.0
  firebase_auth: ^0.18.0+1

Thanks! :)

**Comment by Ehesp** [comment]
Hmm, I think this is a documentation issue / oversight, which boils down to [this statement](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) in the FutureBuilder docs:

```
The future must have been obtained earlier, e.g. during State.initState, State.didUpdateConfig, or State.didChangeDependencies. It must not be created during the State.build or StatelessWidget.build method call when constructing the FutureBuilder. If the future is created at the same time as the FutureBuilder, then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.
```

Could you try the following:

```dart
class FlutterFireInit extends StatelessWidget {
  final Widget child;
  const FlutterFireInit({Key key, @required this.child}) : super(key: key);

  Future<FirebaseApp> _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // Initialize FlutterFire
      future: _initialization,
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          // return SomethingWentWrong();
          print('Something went wrong in Flutter Fire');
        }

        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return child;
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return Container();
      },
    );
  }
}
```

It's creating a new future each time the `build` method is called, rather than reusing one which is already completed I think.

**Comment by Ehesp** [comment]
@Flucadetena Added a PR - could you try this for me and I'll move the PR to be merged. I have tried locally myself and it does fix the problem for me.

**Comment by Flucadetena** [comment]
Hi Ehesp, as soon as I get home I'll test this and let you know. Thanks a lot! :)

**Comment by Flucadetena** [comment]
Hey @Ehesp the statement of the FutureBuilder explain it perfectly. It work for me, but I had to change it to a `StatefulWidget` and initialize Firebase in `initState()`. Using the code you left me I got multiple errors:

1º Couldn't use const in the constructor
2º Calling InitializeApp() there fired before the app was ready.

I leave the code that worked here in case it helps:
`class FlutterFireInit extends StatefulWidget {
  final Widget child;
  const FlutterFireInit({Key key, @required this.child}) : super(key: key);

  @override
  _FlutterFireInitState createState() => _FlutterFireInitState();
}

class _FlutterFireInitState extends State<FlutterFireInit> {
  Future<FirebaseApp> _initialization;

  @override
  void initState() {
    _initialization = Firebase.initializeApp();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // Initialize FlutterFire
      future: _initialization,
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          // return SomethingWentWrong();
          print('Something went wrong in Flutter Fire');
        }

        //TODO: See what to do with this
        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return widget.child;
        }

        // Otherwise, show something whilst waiting for initialization to complete
        //TODO: Change for splash just in case
        return Container();
      },
    );
  }
}
`
