### ISSUE TITLE
[<FIREBASE_PRODUCT>] <Cloud_Firestore>

### ISSUE THREAD

**Issue by ghost** [FirebaseExtended/flutterfire#3294]
```

════════ Exception caught by widgets library ═══════════════════════════════════
Class 'DocumentSnapshot' has no instance method '[]'.
Receiver: Instance of 'DocumentSnapshot'
Tried calling: []("totalAmount")
The relevant error-causing widget was
    StreamBuilder<DocumentSnapshot> 
lib\dashboard.dart:24
════════════════════════════════════════════════════════════════════════════════
```
![Bunnii Investors – Cloud Firestore – Firebase console and 10 more pages - Sam Ngoma - Microsoft​ Edge 23_08_2020 09_38_30 (2)_LI](https://user-images.githubusercontent.com/65399956/90974676-41e07080-e525-11ea-9e4b-747ad0e29566.jpg)

![dashboard dart - bunnii_investors - Visual Studio Code 23_08_2020 09_46_45_LI](https://user-images.githubusercontent.com/65399956/90974759-e82c7600-e525-11ea-8144-af2d019dd81a.jpg)

**Comment by Salakar** [comment]
Great :)
