### ISSUE TITLE
firebase_crashlytics breaking Android path_provider MissingPluginException

### ISSUE THREAD

**Issue by vogttho** [FirebaseExtended/flutterfire#3295]
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_pr

works if i remove  firebase_crashlytics:  ^0.1.4+1

**To Reproduce**
add the following dependencies

  google_maps_flutter: ^0.5.30
  http: ^0.12.2
  cupertino_icons: ^0.1.3
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  fluster: ^1.1.2
  flutter_linkify: ^3.1.3
  twitter_api: ^0.1.2
  firebase_core: ^0.5.0
  firebase_crashlytics:  ^0.1.4+1

**Flutter doctor**
FLUTTER DOCTOR:
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale de-CH)
• Flutter version 1.21.0-9.1.pre at /Users/me/work/dev/tools/flutter
• Framework revision be9bc8c (vor 3 Tagen), 2020-08-18 09:46:08 -0700
• Engine revision 267070c17a
• Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
• Android SDK at /Users/me/Library/Android/sdk
• Platform android-30, build-tools 30.0.1
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.6, Build version 11E708
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 48.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
• IntelliJ at /Applications/IntelliJ IDEA.app
• Flutter plugin version 47.1.3
• Dart plugin version 201.7846.93

[✓] VS Code (version 1.47.3)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.13.2

[✓] Connected device (1 available)
• SM G955F (mobile) • ce031713435368f40c • android-arm64 • Android 9 (API 28)

```
Paste output here
```

**Comment by darshankawar** [comment]
Hi @vogttho,
I am unable to replicate the issue on latest Stable (1.20.2). I add the mentioned dependencies and ran `flutter run` which installed the app properly, without any issues.

```
Launching lib/main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        53.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
```
I tested on Android 8.1.0.

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

Can you try to switch to latest stable or master and try again to see if it works for you ?
Thanks.

**Comment by Salakar** [comment]
A new Crashlytics plugin has now landed on master which should solve this issue.

Checkout the migration guide to get started on upgrading to the new Crashlytics plugin: https://firebase.flutter.dev/docs/migration/
