### ISSUE TITLE
Firebase_Auth 0.18 currentUser exception: getter 'uid' isn't defined for the type Future<FirebaseUser> Function()

### ISSUE THREAD

**Issue by mehdiRezzagHebla** [FirebaseExtended/flutterfire#3298]
Just updated the `firebase_auth` to the latest version 0.18.0+1
In the official documentation, to access the `uid` of the currently signed in user we have to do the following:
```
FirebaseAuth auth = FirebaseAuth.instance;

if (auth.currentUser != null) {
  print(auth.currentUser.uid);
}
```
However, when implementing this code an exception is raised: 

```
The getter 'uid' isn't defined for the type 'Future<FirebaseUser> Function()
```

Please help.

**Comment by mehdiRezzagHebla** [comment]
@Salakar 

> I don't think your update has applied correctly, 'Future<FirebaseUser> Function() is from the older version of the plugin. Try >flutter clean and then flutter pub get again - I think your build is out of date.

 The problem still persists, when I ctrl + click on `.currentUser;` it takes me to 
```...>flutter_windows_1.17.3-stable>.pub-cach>hosted>pub.dartlang.org>firebase_auth-0.16.1>lib>src>firebase_auth.dart>FirebaseAuth```
 which is odd since the installed versions are:
```
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"
  firebase_core: "0.5.0"
```
```
 // is connected ?
  @override
  Future<UserCustom> isConnected() async {
    try {
      var user = await _auth.currentUser;
      if (user != null){

        return _userToUserModel(user);
      }
      return null;
    } catch (e) {
      rethrow;
    }
  }

  // method that transforms FirebaseUser object to UserCustom Object
  UserCustom _userToUserModel(FirebaseUser user) {
    if (user == null) {
      return null;
    }
    return UserCustom(uid: user.uid);
  }

// custom user model
class UserCustom {
  String uid;
  UserCustom({@required this.uid});
}
```

Here is the exception message: 
The argument type 'Future<FirebaseUser> Function()' can't be assigned to the parameter type 'FirebaseUser'.

**Comment by loicgeek** [comment]
> 
> 
> @Salakar
> 
> > I don't think your update has applied correctly, 'Future Function() is from the older version of the plugin. Try >flutter clean and then flutter pub get again - I think your build is out of date.
> 
> The problem still persists, when I ctrl + click on `.currentUser;` it takes me to
> `...>flutter_windows_1.17.3-stable>.pub-cach>hosted>pub.dartlang.org>firebase_auth-0.16.1>lib>src>firebase_auth.dart>FirebaseAuth`
> which is odd since the installed versions are:
> 
> ```
>   firebase_auth: "^0.18.0+1"
>   cloud_firestore: "^0.14.0+2"
>   firebase_core: "0.5.0"
> ```
> 
> ```
>  // is connected ?
>   @override
>   Future<UserCustom> isConnected() async {
>     try {
>       var user = await _auth.currentUser;
>       if (user != null){
> 
>         return _userToUserModel(user);
>       }
>       return null;
>     } catch (e) {
>       rethrow;
>     }
>   }
> 
>   // method that transforms FirebaseUser object to UserCustom Object
>   UserCustom _userToUserModel(FirebaseUser user) {
>     if (user == null) {
>       return null;
>     }
>     return UserCustom(uid: user.uid);
>   }
> 
> // custom user model
> class UserCustom {
>   String uid;
>   UserCustom({@required this.uid});
> }
> ```
> 
> Here is the exception message:
> The argument type 'Future Function()' can't be assigned to the parameter type 'FirebaseUser'.

The user is now retrieved synchronously, So you dont have to write `var user = await _auth.currentUser;` just write `var user = _auth.currentUser;`
