### ISSUE TITLE
FirebaseFirestore - Documentation - ".data" not working as documented

### ISSUE THREAD

**Issue by mellowcello77** [FirebaseExtended/flutterfire#3299]
**Describe the bug**

Documentation shows how to read data as below. This however does not work.
Map<String, dynamic> data = **snapshot.data**();

It only works when your use an extra ".data" as below:
Map<String, dynamic> data = **snapshot._data_.data**();

Not standard Firebase usage, is this intended?

https://firebase.flutter.dev/docs/firestore/usage

**Comment by Salakar** [comment]
Looks like the example is incorrect here: https://firebase.flutter.dev/docs/firestore/usage/#one-time-read
