### ISSUE TITLE
[firebase_auth] providerId renamed to PROVIDER_ID

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#3301]
`firebase_auth` 0.18.0 introduced a bunch of changes, including that _Providers_ (`EmailAuthProvider`, `FacebookAuthProvider`, `GoogleAuthProvider`, `TwitterAuthProvider`) used to have a [`providerId`](https://pub.dev/documentation/firebase_auth/0.16.0/firebase_auth/GoogleAuthProvider/providerId-constant.html) constant, but that was replaced with a static property called [`PROVIDER_ID`](https://pub.dev/documentation/firebase_auth_platform_interface/latest/firebase_auth_platform_interface/GoogleAuthProvider/PROVIDER_ID.html).

Aren't the **SCREAMING_CAPS** of `PROVIDER_ID` a violation of [Dart Style](https://dart.dev/guides/language/effective-dart/style)?

**Comment by quentinleguennec** [comment]
And worth, `PROVIDER_ID` is not const as `provider_id` use to be, which is a (non documented) breaking change, as it breaks `switch`.

**Comment by russellwheatley** [comment]
Thanks for the feedback! Whilst it does go against Dart's style _preference_, this is now a major version removed, and we feel it's worked out pretty well and adequately documented.
