### ISSUE TITLE
FireStore: Store Icon and Color data

### ISSUE THREAD

**Issue by ycv005** [FirebaseExtended/flutterfire#3302]
Hey there, 
I was looking for a way to store data like Icons and Colors to the FireStore so that on fetching data, I could pass them to respective widget or argument so that Icons and Colors could be represented. I didn't found a right way, so asking here and if this is not present, could you bring it to next update & made is possible.

Thanks

**Comment by EliasDeuss** [comment]
@ycv005 You can't store colors or icons but you can create a string key that your code can read then return the correct color that matches the key.
