### ISSUE TITLE
[<firebase_messaging>] <IOS Push notification not working if you run from xcode | from vscode works fine>

### ISSUE THREAD

**Issue by n0tc0ding** [FirebaseExtended/flutterfire#3304]
**Describe the bug**
I am working with phone authentication using firebase_auth ^0.18.0+1 and push notifications using firebase_messaging ^7.0.0 and flutter 1.20.2. 

If i build my application and run it using vscode the registration with the phone works fine, the push notifications send from my website are displayed correctly and the notifications send from firebase console are displayed correctly. However, if i build on Xcode the phone registration works fine, the push notification send from my website are not displayed nor the debug window on xcode show the message but the push notification send from firebase console are displayed correctly.

I am not sure if this will be the same when the app go to app store since I always will build the .IPA from Xcode.

**Comment by TahaTesser** [comment]
Hi @n0tc0ding 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
