### ISSUE TITLE
FIRBASE_ADMOB <Use RequestConfiguration.Builder().setTestDeviceIds>

### ISSUE THREAD

**Issue by Tharindu-dart** [FirebaseExtended/flutterfire#3306]
I/Ads     ( 8629): Starting ad request.
I/Ads     ( 8629): SDK version: afma-sdk-a-v202510999.15301000.1
I/Ads     ( 8629): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("466DB241059402DAA456E55B301****") to get test ads on this device.
W/Ads     ( 8629): Not retrying to fetch app settings
I/Ads     ( 8629): Starting ad request.
I/Ads     ( 8629): SDK version: afma-sdk-a-v202510999.15301000.1
I/Ads     ( 8629): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("466DB241059402DAA456E55B30*****") to get test ads on this device.
W/Ads     ( 8629): Not retrying to fetch app settings
I/Ads     ( 8629): Starting ad request.
I/Ads     ( 8629): SDK version: afma-sdk-a-v202510999.15301000.1
I/Ads     ( 8629): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("466DB241059402DAA456E55B3*****") to get test ads on this device.
W/Ads     ( 8629): Timed out waiting for ad response.
I/Ads     ( 8629): Scheduling ad refresh 60000 milliseconds from now.
W/Ads     ( 8629): Failed to load ad: 2
W/Ads     ( 8629): Timed out waiting for ad response.
W/Ads     ( 8629): Failed to load ad: 2
W/flutter ( 8629): onRewardedVideoAdFailedToLoad: 2
W/Ads     ( 8629): Timed out waiting for ad response.
W/Ads     ( 8629): Failed to load ad: 2
W/flutter ( 8629): onAdFailedToLoad: 2

**Test ads are not showing for current device .**but when i checked it using another device it shows ads without any error.
What is **Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("466DB241059402DAA456E55B3*****") to get test ads on this device.**.

How to solve this error, I tested different admob applications on this device ,but same result (But with other devices no issues happen)

**Comment by darshankawar** [comment]
Hi @Tharindu-dart,
Can you try the official [example](https://pub.dev/packages/firebase_admob/install) and confirm to include app id [setup](https://pub.dev/packages/firebase_admob#androidmanifest-changes).
Also, did you by any chance had reset the current device ?
If problem persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample.
Thanks.

**Comment by Tharindu-dart** [comment]
> Hi @Tharindu-dart,
> Can you try the official [example](https://pub.dev/packages/firebase_admob/install) and confirm to include app id [setup](https://pub.dev/packages/firebase_admob#androidmanifest-changes).
> Also, did you by any chance had reset the current device ?
> If problem persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample.
> Thanks.

Yes i tried official flutter admob codelab example.
And i setup all the things exactly.

Only that current device had this problem, And i run same app on two different devices and working perfectly(show ads).
I have no chance reset, but i restart, delete app cache , change wifi connection and much more but still same on that device.
