### ISSUE TITLE
Update Android SDK from 28 to latest stable version in existing flutter packages

### ISSUE THREAD

**Issue by cyanglaz** [FirebaseExtended/flutterfire#3324]
Update Android SDK from 28 to latest stable version in existing flutter packages.

example: https://github.com/flutter/plugins/blob/master/packages/connectivity/connectivity/android/build.gradle

There is still written "compileSdkVersion 28"

Expected: packages should use the latest stable version.

This issue relates to #54382

This is the same issue as https://github.com/flutter/flutter/issues/64396 for flutter/plugins repo

**Comment by Salakar** [comment]
Thanks for the heads up @cyanglaz - we'll get this looked at.

**Comment by Salakar** [comment]
This was done quite some time back, closing the issue slipped through so closing it now. Thanks
