### ISSUE TITLE
Unexpected Pod downgrade when upgrading Flutter Fire dependencies

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#3328]
When I recently upgraded my projects to use the **latest Flutter Fire dependencies** recently released, I noticed that my **Pods were unexpected downgraded**.  Some examples include:

Pod | Before | After |
----------- | ------ | ----- |
Firebase/Analytics | 6.29.0 | 6.26.0
Firebase/Auth | 6.29.0 | 6.26.0
Firebase/Core | 6.29.0 | 6.26.0
Firebase/Database | 6.29.0 | 6.26.0
Firebase/DynamicLinks | 6.29.0 | 6.26.0
Firebase/Firestore | 6.29.0 | 6.26.0
Firebase/Functions | 6.29.0 | 6.26.0
Firebase/Messaging | 6.29.0 | 6.26.0
Firebase/RemoteConfig | 6.29.0 | 6.26.0
Firebase/Storage | 6.29.0 | 6.26.0
FirebaseABTesting | 4.1.0 | 3.2.0
FirebaseAuth | 6.7.1 |6.5.3
FirebaseCore | 6.9.2 | 6.7.2
FirebaseDatabase | 6.4.0 | 6.2.1
FirebaseDynamicLinks | 4.2.0 | 4.0.8
FirebaseFirestore | 1.16.3 | 1.15.0
FirebaseFunctions | 2.7.0 | 2.5.1
FirebaseMessaging | 4.6.1 | 4.4.1
FirebaseRemoteConfig | 4.8.0 | 4.5.0
FirebaseStorage | 3.8.0 | 3.6.1

I see the following message when running `pod update`:
```
cloud_firestore: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
cloud_functions: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
```

I think this is coming from:
https://github.com/FirebaseExtended/flutterfire/blob/031cf88c7656f8fcba9eb510ba0d5d6ccf36653b/packages/firebase_core/firebase_core/ios/firebase_core.podspec#L15

I expected that the `Firebase/*` pods would have upgraded from version 6.29.0 to **6.30.0**.  (Instead they were downgraded to 6.26.0.)

**Flutter doctor**
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.2 at /Users/anthony/flutter
    • Framework revision bbfbf1770c (11 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Platform android-R, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile)     • B7F2DF40-38F4-4D13-81B0-D47A17126D4F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • iPad (7th generation) (mobile) • 91CAF267-2193-4752-A4B2-E035A2B3FC87 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Comment by awhitford** [comment]
I was able to achieve the upgrade that I expected by manually adding this to my `Podfile`:
```
$FirebaseSDKVersion = '6.30.0'
```

However, should the _default_ Firebase version truly be version 6.26.0 and not 6.30.0?  Because I would not expect that this modification to be necessary.  When using the latest stable dependencies, I expect the latest stable pods to match.

Also, the documentation [here](https://firebase.flutter.dev/docs/overview#iosmacos) gives an example specifying
```
$FirebaseSDKVersion = '21.1.0'
```
🐛

**Comment by Salakar** [comment]
The reason they look like they're downgraded was because this packages all previously pretty much included  the Firebase pods as 'any' version so pulled in the lastest version irregardless of whether it was tested to be compatible with the Dart wrapper or not and this caused a lot of issues.

The new plugins now specify a specific version that is tested and known to be compatible with the FlutterFire implementation. We added the override flag also, as you've found, for those who like to live on the edge 😀  6.26 was the version about 2 months ago when we started the rework and we'll probably bump it up again when the next batch of reworked plugins land.

**Comment by Salakar** [comment]
> Also, the documentation [here](https://firebase.flutter.dev/docs/overview#iosmacos) gives an example specifying
> 
> ```
> $FirebaseSDKVersion = '21.1.0'
> ```
> 
> 🐛

Would you mind sending a PR to change the example to 6.30.0? There's an edit button at the bottom of the page that will take you to the correct file 🤓 thanks

**Comment by Salakar** [comment]
Closing this now as this change is expected and docs have been updated too. Thanks again for the PR!
