### ISSUE TITLE
Problem with wifi connection in Firebase Database on Android

### ISSUE THREAD

**Issue by augusto-nc** [FirebaseExtended/flutterfire#3332]
Firebase Database has a known unresolved issue with Wifi connection failures with Android SDK [.](https://github.com/firebase/firebase-android-sdk/issues/1258) The problem does not occur with Web version and IOS. What are the chances of this problem occurring or not with FlutterFire on Android?

https://github.com/firebase/firebase-android-sdk/issues/1258

**Comment by Salakar** [comment]
If there's an issue on the Android SDK the there'll be an issue on FlutterFire for Android - we use the Firebase Android SDK in the plugins.

I'd recommend tracking that issue there and/or raising an issue with Firebase Support if needed.
