### ISSUE TITLE
[firebase_auth] Error in signOut method documentation

### ISSUE THREAD

**Issue by mbilalakmal** [FirebaseExtended/flutterfire#3339]
https://github.com/FirebaseExtended/flutterfire/blob/60f9da26a9c5af2da61b2dccb44e12d9b831898d/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart#L548-L555

`/// If successful, it also signs the user in into the app...`

This is evidently erroneous, as the signOut method 'signs out' the current user and notifies the streams (by emitting null value for User).

**Comment by Ehesp** [comment]
Ah yes, probably a copy-paste error. Feel free to send up a PR, I'll get around to this sometime today if there isn't one.

Cheers

**Comment by mbilalakmal** [comment]
> Ah yes, probably a copy-paste error. Feel free to send up a PR, I'll get around to this sometime today if there isn't one.
> 
> Cheers

I did submit a PR, but for some reason it is failing 1 check (firebase_auth / apple (pull_request) Failing after 1m — apple).

**Comment by Ehesp** [comment]
Thanks - d/w, CI just being a bit flakey at the moment. Will get it merged.
