### ISSUE TITLE
[<Firebase_Auth>] Unable to Catch SignInWithEmailAndPassword Exception

### ISSUE THREAD

**Issue by dhanniex82** [FirebaseExtended/flutterfire#3341]
I'm on Android platform.
I've been trying to catch and display the exception for wrong email or password on the app screen.

here's my code:
```
try {
        await FirebaseAuth.instance
              .signInWithEmailAndPassword(
                  email: _emailTextController.text,
                  password: _passwordTextController.text)
                  .then((u) {
                      Navigator.push(
                          context,MaterialPageRoute(builder: (context) => HomePage()),
                        );
                      });
                    } on FirebaseAuthException catch (e) {
                      setState(() {
                        errorMessage = e.message;
                      });
                      print(e.code);
                      print(e.message);
                    }
```
It worked fine with firebase_auth: ^0.16.1. I could catch and display the exception and app doesn't stop so I can make correction and re-try login.

flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.19041.450], locale id-ID)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.1)
[√] Connected device (4 available)

• No issues found!
```

**Comment by Ehesp** [comment]
Web/Android/iOS?

**Comment by dhanniex82** [comment]
Android.
I manage to catch it on Web platform after adding user null check after .then method.
but still couldn't catch it on android platform.

**Comment by Ehesp** [comment]
@dhanniex82 Can you update that repo (and link it here again) with the code and I'll try on Android.

**Comment by dhanniex82** [comment]
@Ehesp I have updated the repo.
please check https://github.com/dhanniex82/flutterFireAuthExample
you can try with web platform, it caught the exception and display it on screen but doesn't work on android platform.
email: dhannie@email.com, password: 123456

**Comment by Ehesp** [comment]
Seems to be working for me:

![image](https://user-images.githubusercontent.com/842078/91291190-9b96a400-e78c-11ea-9104-9161685cf92f.png)

**Comment by dhanniex82** [comment]
so far I have tried a few things.
flutter clean -> failed
tried on android 8 emulator -> failed
tried on android 9 emulator -> failed
tried on real phone -> failed.
then I switched from vs code to Android Studio IDE -> passed. It caught the exception and keep the app running.
not sure what happened with my vs code but I see from your screenshot that you are using vs code.
