### ISSUE TITLE
[FIREBASE EMULATORS] Add docs & example for Firebase Emulators

### ISSUE THREAD

**Issue by deadsoul44** [FirebaseExtended/flutterfire#3348]
Docs & examples for Flutter are definitely needed for Firebase Emulators. For example, in the following page, there are examples for ios, android and web but there is nothing for Flutter.

https://firebase.google.com/docs/emulator-suite

Thank you for the awesome work.

**Comment by Salakar** [comment]
We do cover this here for Firestore: https://firebase.flutter.dev/docs/firestore/usage#emulator-usage

The same for Functions too in the upcoming rework. Is there any particular documentation you think should be added? Thanks

**Comment by deadsoul44** [comment]
There is nothing else for now. Thank you.
