### ISSUE TITLE
[CLOUD FUNCTIONS] Getting DEADLINE_EXCEEDED during cloud function call

### ISSUE THREAD

**Issue by matthew-carroll** [FirebaseExtended/flutterfire#3351]
I'm executing a callable cloud function via Flutter on Android and I'm getting back a `DEADLINE_EXCEEDED` error.

The call takes about 12 seconds to complete. The official function timeout in the Firebase console is 60 seconds. Therefore, it seems like the client is imposing its own timeout that is much stricter than it should be.

Is this expected behavior? If so, is there a way to change the timeout period?

In my particular case I am generating a PDF and sending it via email so there is no way to break up the behavior. I could return early and assume the email is sent, but I'd rather that my users wait a little longer and receive definite confirmation of success or failure.

**Comment by pradt** [comment]
I've just received this as well, and a google search has lead me here. In my case i'm using Flutter/android and using a callable function which is executing about 10-12 seconds. My callable function is calling an external api to authenticate and get a token and a second api to get a list, then doing a batch write to 79 documents (no transformation of data etc... ). There's nothing in the Firestore logs of an error, and the batch commit appears to have committed successfully.

**Comment by tfang17** [comment]
+1 on this issue.

**Comment by russellwheatley** [comment]
Hey @matthew-carroll, you can explicitly set the timeout limit [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/example/lib/main.dart#L59). Let me know if this solves your problem. Thanks.

**Comment by otopba** [comment]
Same issue
