### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] Cloud_Firestore: 0.14.0+2 Local module descriptor class for providerinstaller not found

### ISSUE THREAD

**Issue by mehdiRezzagHebla** [FirebaseExtended/flutterfire#3358]
After signing in my user with email & password (haven't tested with anonymous sign in or other methods), and relaunching the emulator (still signed in) when I try to write into the data base I get this error and the database content remains unchanged.
I don't know what is the meaning of this error but I wanted to let you know in case no one reported this issue.

```
W/DynamiteModule(16590): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(16590): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(16590): Failed to load providerinstaller module: No acceptable module found. 
                            Local version is 0 and remote version is 0.
```

**Comment by Ehesp** [comment]
This log isn't anything to do with FF. Can you follow the issue template?

**Comment by Jatin-kumar-97** [comment]
i also got same problem???got any solution
![Capture](https://user-images.githubusercontent.com/54402567/92105156-0b95d180-ee00-11ea-997c-528a4db24539.JPG)

**Comment by mehdiRezzagHebla** [comment]
> i also got same problem??? do you guys got any solution????
> ![Capture](https://user-images.githubusercontent.com/54402567/92105156-0b95d180-ee00-11ea-997c-528a4db24539.JPG)
> 

Not yet, don't even know for sure if this is FlutterFire related.

**Comment by Ansary-cpu** [comment]
W/DynamiteModule(18632): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(18632): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(18632): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.



any sol?????

**Comment by mehdiRezzagHebla** [comment]
@Ansary-cpu not yet.

**Comment by Ansary-cpu** [comment]
@mehdiRezzagHebla thank u

**Comment by Ansary-cpu** [comment]
Any Sol?????????????

**Comment by cocacrave** [comment]
`W/DynamiteModule(12527): Local module descriptor class for providerinstaller not found.
W/ConnectivityManager.CallbackHandler(12527): callback not found for CALLBACK_AVAILABLE message
I/DynamiteModule(12527): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(12527): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/ConnectivityManager.CallbackHandler(12527): callback not found for CALLBACK_AVAILABLE message`

Same message here after updating packages:
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_dynamic_links: ^0.6.0

**Comment by Ehesp** [comment]
Is this actually causing an issue or is it just a log? I don't think there is any FlutterFire specific issue here?

**Comment by TahaTesser** [comment]
Hi @mehdiRezzagHebla @cocacrave  @Ansary-cpu
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Paulavancamp** [comment]
I am experiencing the same issue!!! I am trying to create a new document using the user.uid after I create a new user account. 

![flutter firestoreservice error](https://user-images.githubusercontent.com/25617235/99001442-1ce21500-24f8-11eb-8765-8116bba2c272.JPG)

**Comment by TahaTesser** [comment]
@Paulavancamp 
Can you please file a new issue, thank you!
