### ISSUE TITLE
[firebase_core] Multiple bundle_id in google-services.json

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#336]
Hi experts,
Although my App looks to work ok, the generated google-services.json includes 2 entries:
```
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "xxx",
        "android_client_info": {
          "package_name": "br.com.gorges.secondapp"
        }
      },
```
but it also has:
```
    {
      "client_info": {
        "mobilesdk_app_id": "xxx",
        "android_client_info": {
          "package_name": "br.com.gorges.myfirstapp"
        }
      },
```
I downloaded it as described in Firebase Console.

I am wondering why the info from 1st app is there and whether Flutter might use it improperly.

Should I leave this? Or how to fix it?
If this is a Firebase Console bug, Flutter instructions might give directions to clean it.

**Comment by kroikie** [comment]
@egorges

The issue at https://github.com/flutter/flutter/issues/40536 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hello @egorges

I'm re-posting your [last message](https://github.com/flutter/flutter/issues/40536#issuecomment-533912319) from the closed issue

<details>
  <summary> **_read_** </summary>
> Hello ...
> I created the first project with Firebase Console:
> https://console.firebase.google.com/project/my-project/overview
> Project Overview
> Add app
> Select platform, and so on.
> 
> Did the same with the 2nd one - which is an unrelated App.
> 
> Although I understand I could have several "package_name"s should I have .debug and other .profile version, the case is that the generated google-services.json in the 2nd app is improperly referencing the 1st one.
> 
> Thanks in advance.
</details>

Are you still experiencing the same issue?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
