### ISSUE TITLE
 [Firebase messaging] Push notification keep calling

### ISSUE THREAD

**Issue by evripidesk** [FirebaseExtended/flutterfire#3361]
Facing issue like when my app is in background or terminate mode and notification will come and will tap on notification tray all works good and dialog box appears with notification. But when I go on other page and come back to previous one all time I get again the dialog box with the notification detail, I have to terminate the app so can “forget” notification

How can I fix this

**Comment by TahaTesser** [comment]
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by evripidesk** [comment]
`class _HomeState extends State<Home> {
  void initState() {
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        setState(() {
          _messageText = "Push Messaging message: $message";
        });
        print("onMessage: $message");
        print(message['extraPayLoad1']);
        if (message['extraPayLoad1'] == 'valuestart') {
          _showItemDialog2(message);
        } else {
          _showItemDialog(message);
        }
      },
      onLaunch: (Map<String, dynamic> message) async {
        setState(() {
          _messageText = "Push Messaging message: $message";
        });
        _serialiseAndShowModal(message);

        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        setState(() {
          _messageText = "Push Messaging message: $message";
        });
        _serialiseAndShowModal(message);

        print("onResume: $message");
      },
    );

`
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.47.3)
 
[✓] Connected device (1 available)            

• No issues found!`

`dependencies:
  firebase_messaging: ^7.0.0

`
