### ISSUE TITLE
latest firebase_admob and firebase_core version solving

### ISSUE THREAD

**Issue by Ma-Altaiir** [FirebaseExtended/flutterfire#3363]
Because firebase_admob >=0.9.1 depends on firebase_core ^0.4.2+1 and sample-project depends on firebase_core ^0.5.0, firebase_admob >=0.9.1 is forbidden.

So, because sample-project depends on firebase_admob ^0.9.3+4, version solving failed.

**Comment by Salakar** [comment]
See #3347 - it's in progress, there's just some issues with the new SDK that are being sorted.
