### ISSUE TITLE
Error connecting to the service protocol on configuring firebase 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#337]
I get the error  in terminal as:
```
Configuring the default Firebase app...
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c2521bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010b7f0735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c252015 +[NSException raise:format:] + 197
	3   Runner                              0x000000010751b86a +[FIRApp configure] + 138
	4   Runner                              0x0000000107988e19 -[FLTCloudFirestorePlugin init] + 217
	5   Runner                              0x0000000107988c1c +[FLTCloudFirestorePlugin registerWithRegistrar:] + 300
	6   Runner                              0x0000000107516f9b +[GeneratedPluginRegistrant registerWithRegistry:] + 123
	7   Runner                        <…>
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:52825/4HIVHFrzR-8=/ws
```

**Comment by kroikie** [comment]
@vimanshu

The issue at https://github.com/flutter/flutter/issues/40509 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @vimanshu
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
