### ISSUE TITLE
🐛 [cloud_firestore] Web Performance Regression

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#3373]
## Bug report

When upgrading the `cloud_firestore` plugin from `0.13.7` to `0.14.0` on Flutter web, all document reads seem to take way longer than before, sometimes x5.

### Steps to reproduce

1. Run a Flutter web project with `cloud_firestore` `0.13.7`.
2. Run the same project with `cloud_firestore` `0.14.0+2` (requires migration).
3. Compare performance.

### Expected behavior

I would expect reads to take the same time, however, that does not occur.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, locale en-150)
[✓] Chrome - develop for the web
```

</details>

**Comment by Ehesp** [comment]
Can you post a reproduction? What sort of data are you reading, how big, is it via a query?

I've just tried on web and the results are instant.

**Comment by creativecreatorormaybenot** [comment]
@Ehesp It is any read actually. The map size is sometimes really small, e.g.:

```
map<string, string>
reference
map<map<string, string>
```

And the maps have 3 entries at most. Sometimes, loading such a document will take up to a few seconds.  
And every user is experiencing this right now with the web app using `cloud_firestore` `0.14.0+2`.

I am wondering if there might be an issue with Cloud Firestore in general right now. Because we all are accessing from central europe and it actually seems like we have the same issue on mobile (to some extent), but I am not sure if reads take 5 seconds there 😶

**Comment by creativecreatorormaybenot** [comment]
@Ehesp OK I just checked to confirm.

It turns out that the migration to `0.14.0` happened at the same time as Firestore getting slow.  
The same happens on `0.13.7` **now**. I confirmed this by reverting for a moment.

Do you have any idea how to troubleshoot this issue/where Firestore reports request times for all projects in a region?

**Comment by rdonoso** [comment]
it happen the same to me... i am thinking to rollback the entire "upgrade"

**Comment by rdonoso** [comment]
i can figure out what it is causing me this issue, basically was because i added another index that does not perform very well in firestore

**Comment by russellwheatley** [comment]
I'm going to close this out as this appears to be a Firestore server issue. Will reopen if I'm mistaken and it is actually a problem with the firestore package.
