### ISSUE TITLE
🐛 [Firebase_Messaging] Application error

### ISSUE THREAD

**Issue by Raphael-Jose-Ferraro-IRForever** [FirebaseExtended/flutterfire#3377]
This class

package my_package;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
### Steps to reproduce

use recomendation documents

Erro in 
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

and 

    FlutterFirebaseMessagingService.setPluginRegistrant(this);

**Comment by darshankawar** [comment]
Hi @Raphael-Jose-Ferraro-IRForever,
Please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete code sample that shows the issue.
Thanks.
