### ISSUE TITLE
[📚] Is google-services.json still required? 

### ISSUE THREAD

**Issue by esDotDev** [FirebaseExtended/flutterfire#3390]
https://firebase.flutter.dev/docs/overview Does not mention adding the google-services.json at any point. 

Is this still required? I seem to recall it being mentioned somewhere else, but now I can't find it anywhere in the setup instructions. Only iOS and MacOS mention this step.

If not required, I'm confused how the app authenticates with Firebase since I'm not passing any credentials in the `Initialize()` call.

**Comment by Ehesp** [comment]
It should be within the specific platform setup documentation.

**Comment by snackosphere** [comment]
This is an excellent question. How does the app know what Firebase account to connect to?

**Comment by snackosphere** [comment]
For Android, this step is listed on the Android page as "Once your Android app has been registered, download the configuration file from the Firebase Console (the file is called google-services.json). Add this file into the android/app directory within your Flutter project."

**Comment by esDotDev** [comment]
Ya sorry not sure how I missed that, thx
