### ISSUE TITLE
🐛 [Firebase_dynamic_url] Invalid dynamic Link

### ISSUE THREAD

**Issue by maheshkumar2150** [FirebaseExtended/flutterfire#3392]
Requested URL (https://wyr.page.link/?id=argyle) must be a parsable and complete DynamicLink.

If you are the developer of this app, ensure that your Dynamic Links domain is correctly configured and that the path component of this URL is valid.

I am facing the problem only with iOS iPhone
Working fine in android,

firebase_dynamic_links 0.6.0
Flutter 1.20.2 Stable on ios

**Comment by maheshkumar2150** [comment]
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (2 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

final String _url = 'https://wyr.page.link';
final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: _url,
      link: Uri.parse(
          '$_url?id=$id'),
      androidParameters: AndroidParameters(
        packageName: 'com.example.mahesh,
        minimumVersion: 1,
      ),
      iosParameters: IosParameters(
        bundleId: 'com.example.mahesh',
        minimumVersion: '1.0.0',
        appStoreId: '',
      ),
      socialMetaTagParameters: SocialMetaTagParameters(
        title: 'Some title',
        description:
            'Some Description',
      ),
    );

**Comment by Xgamefactory** [comment]
what was the solution ? we are facing same issue

**Comment by maheshkumar2150** [comment]
I dont have paid developer account. There are some settings which needs to be modified.
I dont have paid account
