### ISSUE TITLE
🐛 [firebase_auth] Has UserUpdateInfo() been deprecated?

### ISSUE THREAD

**Issue by igbokwenu** [FirebaseExtended/flutterfire#3393]
Since update firebase_auth: ^0.18.0+1, UserUpdateInfo() has been messing up app builds. I saw a few mentions of this issue on stack but cant seem to find any solutions.

**Comment by darshankawar** [comment]
It seems `UserUpdateInfo()` has been deprecated for `UserInfo()`, because I am able to retrieve user's details such as `displayName`, `email`, `uid`,` phoneNumber` by creating instance of `UserInfo()`.

![Screen Shot 2020-08-31 at 5 51 58 PM](https://user-images.githubusercontent.com/67046386/91719310-b022d400-ebb2-11ea-88e9-5dfeb4a7ff5a.png)

**Comment by workbird** [comment]
I am also facing with this issue

![image](https://user-images.githubusercontent.com/70068586/91849483-ca73b500-ec79-11ea-8ded-6a4c0d4885d6.png)

**Comment by Salakar** [comment]
See https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User/updateProfile.html

```dart
await FirebaseAuth.instance.currentUser.updateProfile(displayName: 'new name');

**Comment by workbird** [comment]
Thanks for update.

Its great if you provide the solution in detail. I am not that much good in flutter .
![image](https://user-images.githubusercontent.com/70068586/92035314-23337280-ed8c-11ea-8bb8-1f0f0c857ed9.png)

**Comment by anirudh-jwala** [comment]
> @igbokwenu,
> It seems `UserUpdateInfo()` has been deprecated for `UserInfo()`, because I am able to retrieve user's details such as `displayName`, `email`, `uid`,` phoneNumber` by creating instance of `UserInfo()`.
> 
> ![Screen Shot 2020-08-31 at 5 51 58 PM](https://user-images.githubusercontent.com/67046386/91719310-b022d400-ebb2-11ea-88e9-5dfeb4a7ff5a.png)

What is the argument that `UserInfo updateUser = UserInfo();` is expecting to have? When passed UserCredential object that is holding the essential 'user' further to be holding email, displayurl, etc it is still creating error

**Comment by uttusharma** [comment]
Here is an example on updating additional user info:

```
UserCredential result = await _firebaseAuth.createUserWithEmailAndPassword( email: event.user.email, password: event.user.password);
User firebaseUser = result.user;
firebaseUser.updateProfile( displayName: "example user", photoURL: "https://example.com/example.jpg");

```
