### ISSUE TITLE
[📚] It's not clear where the code in the Usage section goes - Authentication

### ISSUE THREAD

**Issue by snackosphere** [FirebaseExtended/flutterfire#3394]
The Usage section for Firebase Authentication should indicate where the sample code should be placed. It's not clear to a new developer if that code should be in a Widget or in the main method.

**Comment by sumitsingh1698** [comment]
hi, I would like to help you. will you give me more detail what you want to say?

**Comment by snackosphere** [comment]
The issue I described is clear enough.  If you have a solution, submit a pull request.

**Comment by snackosphere** [comment]
The examples should be like the "Write your first Flutter app" codelab featured in the Flutter docs.  For each code sample, it shows the filename that it's in and the full class.

**Comment by Ehesp** [comment]
All FlutterFire code (apart from AdMob) can be run anywhere, whether it be within a FutureBuilder, StreamBuilder or directly within an init state method. The reason it is not shown as a class is because it totally depends on how you architecture your application.

**Comment by snackosphere** [comment]
Thank you for the clarification.
