### ISSUE TITLE
[firestore] Invalid argument when using whereIn

### ISSUE THREAD

**Issue by Shibynator** [FirebaseExtended/flutterfire#3399]
I'm currently playing around with firestore and flutter.

When I tried the whereIn-filter I encountered a strange error.

```
Stream<List<Topic>> getTopics() {
    return _topics
        .orderBy('name')
        .where(FieldPath.documentId,
            whereIn: ["KPOf8RnAG6eKiuM97bkA", "O4PMgvLSNKcSNPEofqOl"]
                .toList()) 
        .snapshots()
        .map((list) {
      return list.docs.map((doc) {
        return Topic.fromJson(doc.id, doc.data());
      }).toList();
    });
  }
```

The strange thing is that when I debug the result+mapping everything seems to be ok, but when hooking up a StreamBuilder it returns an error:

**Client specified an invalid argument. Note that this differs from failed-precondition. invalid-argument indicates arguments that are problematic regardless of the state of the system (e.g., an invalid field name).**

Any idea?

Regards 

Daniel

**Comment by russellwheatley** [comment]
Hey Daniel, 
                   I've just used your function (slight tweak, I mapped maps in-place) and created a StreamBuilder with no problems on an iOS simulator. I'm using:
```
cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
```

Could you provide a [reproducible](https://stackoverflow.com/help/minimal-reproducible-example) example, please.

**Comment by Shibynator** [comment]
I'm using android and cloud_firestore: ^0.14.0+2.

I'm afraid not, at least not without a lot of work on my side. Could you please first check if you get it also running on Android?

**Comment by cmregazzo** [comment]
Good night,

I have the same problem reported in the call.

I only use Flutter on Android.

Any solution to such a problem?

**Comment by Peet-A** [comment]
same issue here !!!

**Comment by FranRiadigos** [comment]
@russellwheatley @Shibynator @Peet-A 

Still happening on `cloud_firestore: 1.0.3`, but it seems it should've been fixed already.
Check what **Jon Skeet** has replied.

https://stackoverflow.com/questions/61906792/firestore-wherein-query-with-fieldpath-documentid-is-throwing-exception
```
final query = collection.where(FieldPath.documentId,
          // workaround: collection.doc(e.id)
          whereIn: stringIds.map((e) => collection.doc(e.id)).toList());
```

**Comment by russellwheatley** [comment]
I'm going to close this as the issue is stale and I cannot reproduce. Happy to reopen if a reproducible sample is forwarded.
