### ISSUE TITLE
[📚] Do we need SSL certs for Messaging on IOS? The docs are not clear.

### ISSUE THREAD

**Issue by esDotDev** [FirebaseExtended/flutterfire#3404]
The [docs](https://firebase.flutter.dev/docs/messaging/ios-integration) simply say to create a cert, but there are multiple types of cert.

When setting up my Push Notifications, I see this "Configure" box which is not mentioned in your docs: 
![image](https://user-images.githubusercontent.com/736973/91662634-de17f380-eaa0-11ea-8aa3-4652806d0e8a.png)

Bringing me here: 
![image](https://user-images.githubusercontent.com/736973/91662648-ef610000-eaa0-11ea-94f5-6bd8202c16d3.png)

And here: 
![image](https://user-images.githubusercontent.com/736973/91662656-fd168580-eaa0-11ea-8a96-94d10e42187e.png)

I'm guessing we don't need this, because we are using APN Auth Key, but the docs are unclear here, and I don't want to waste 4 or 5 hrs after finding out these don't work in production...

**Comment by esDotDev** [comment]
Also, is there a reason the docs here: https://pub.dev/packages/firebase_messaging are so diferent than the steps here: https://firebase.flutter.dev/docs/messaging/ios-integration ?

I'm confused which I should follow, the ones on pub.dev has several additional steps, the one on flutter.dev is presumably more recent?

**Comment by DEVSOG12** [comment]
@esDotDev  You should check out flutter firebase [docs](https://firebase.flutter.dev/docs/messaging/ios-integration) . This explains it well!! You can check the [documentation](https://firebase.flutter.dev/docs)on how to use most of the firebase plugins in flutter.

**Comment by esDotDev** [comment]
I linked to those docs. My confusion is that the docs on pub.dev are different than the docs on: 
https://firebase.flutter.dev/docs/messaging/ios-integration

Should we consider the instructions on pub.dev deprecated?

Additionally, the docs do not mention whether we need to deal with the "Configure" btn on Push Entitlement. If the answer is no, this would be a good thing to mention.

**Comment by Ehesp** [comment]
The README/pub.dev docs are due an upgrade when we get around to them. Follow the documentation website docs for now. 

Also in regards to your initial question, yes you'll need to configure the certificate for whatever environment you're using.

**Comment by Ashar2shahid** [comment]
Another thing that is not mentioned is that you have to upload those certificates to firebase as well apart from the keys

**Comment by esDotDev** [comment]
Really? Thanks! 

I really can't stress enough how important it is that these docs are complete and exhaustive. Please keep in mind the 3 day approval cycle, and the extremely high testing/deploy time can be if errors are detected in production here. This can literally eat up days or even weeks of dev-time because you miss some tiny setting somewhere.

Please keep in mind the audience is often windows/android devs who know nothing about any of this stuff and just need a straight line from A > B in bullet form.

**Comment by Ashar2shahid** [comment]
@esDotDev yeah agree I spent 4 days trying to figure this out on IOS, another thing to keep in mind is to ask for notifications in IOS when initializing FCM in flutter. This isn't mentioned anywhere in the docs and is frustrating when you spend 2 days wondering what you did wrong. 

```
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  @override
  void initState() {
    super.initState();
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
      },
    );

   _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(
            sound: true, badge: true, alert: true, provisional: false));

    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });

    _firebaseMessaging.getToken().then((String token) {
      print("token: $token");
    });
  }
```

Here is the code.

In the end I didn't have to use the authenitcation key I generated on the Apple developer platform. Instead I generated 2 certificates both for Development and Production and used them instead of the key in firebase console. I can recieve push notifications this way on IOS but the image is not being displayed. If you figure out a way to get the image to display let me know. 

One more thing to keep in mind while processing additional data in notification via the data field is that it is received differently in IOS and Android. 

On Android, the message contains an additional field data containing the data. On iOS, the data is directly appended to the message and the additional data-field is omitted.

To receive the data on both platforms:
```
    var data = message['data'] ?? message;
    String expectedAttribute = data['expectedAttribute'];
```

**Comment by Ehesp** [comment]
The docs will be getting a full overhaul when we get around to working on messaging.

**Comment by esDotDev** [comment]
Not to be too much of a squeaky wheel but this sure would've been nice to know when the announcement was made last mth about these new extensions. I fully switched over, thinking they were good to go, and now realize the team is in a "They'll be done when they're done" head space, which puts my project in pretty bad spot. 

Thanks @Ashar2shahid for all the tips, that is immensely helpful

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging documentation which has been significantly updated along with major version updates: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview) If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
