### ISSUE TITLE
[firebase_dynamic_links] better error message when building dynamic link 

### ISSUE THREAD

**Issue by Xgamefactory** [FirebaseExtended/flutterfire#3405]
Hi. we are build dynamic link with this plugin. as definded in your example readme.
link is created but giving not found error when clicked.

_Dynamic Link Not Found
Short URL (https://*****.page.link/promo_mk1ay2aD3X?_imcp=0) not found

If you are the developer of this app, ensure that your Dynamic Links domain is correctly configured and that the path component of this URL is valid._

  ```
firebase_core: ^0.5.0
  firebase_dynamic_links: ^0.6.0

flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-TR)
    • Flutter version 1.20.2 at /Users/******
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2
```

**Comment by TahaTesser** [comment]
Hi @Xgamefactory 
`If you are the developer of this app, ensure that your Dynamic Links domain is correctly configured and that the path component of this URL is valid._` 

The error seems straight forward, is your dynamic links setup is property done? Can you please change URL and provide a screenshot and Can you please provide and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by Xgamefactory** [comment]
Thanks for reply.
After changing link parameter of DynamicLinkParameters to my custom website redirect url problem has gone.
But there should be an error  feedback on building dynamic link 
i mean final Uri dynamicUrl = await parameters.buildUrl(); should throw an error but it returns generated unique deeplink.

**Comment by russellwheatley** [comment]
Closing this out as this issue has been resolved.
