### ISSUE TITLE
Cloud vision Api

### ISSUE THREAD

**Issue by sameep-s** [FirebaseExtended/flutterfire#3406]
Hey there, flutter team kindly make an instance to use Cloud Vision Api for flutter and a detailed tutorial will be helpful.

**Comment by darshankawar** [comment]
Hi @sameep-s,
Is this a proposal towards a specific firebase plugin ? 
Also, note that, Flutter has a separate repo for tracking : https://github.com/flutter/flutter/issues
Thanks.

**Comment by sameep-s** [comment]
@darshankawar Thanks for sharing the flutter repo.

**Comment by darshankawar** [comment]
@sameep-s,
It seems the issue you described isn't specific to firebase. I am going ahead and closing it as non-issue.
If you disagree, or think it was closed by mistake, write in comments and I'll reopen. 
Thanks.
