### ISSUE TITLE
🐛 [firebase_admob] Cannot load a new (or a few) RewardedAd while showing preloaded one

### ISSUE THREAD

**Issue by alectogeek** [FirebaseExtended/flutterfire#3407]
## Bug report

I need to show a few rewarded ads in a row but the package doesn't let me do so.
According to package documentation, I can load 1 ad at a time, so I tried to load the next video as soon as I started showing already preloaded one.

Though according to android AdMobv SDK documentation, there is a new API allowing to load more than one ad at a time. (https://developers.google.com/admob/android/rewarded-ads#loading_multiple_rewarded_ads)

---

### Flutter doctor

`flutter doctor`:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Hi @alectogeek,
Can you provide the admob plugin version you are using ? There's a [new](https://pub.dev/packages/firebase_admob/versions/0.10.0-dev.1) dev release of the plugin that you might want to try, if not already.

Also, if problem persists, please provide a minimal reproducible code sample that shows the issue.
Thanks.

**Comment by alectogeek** [comment]
Hi @darshankawar,
I use the latest available on the pub 0.9.3+4 version. 
I will try the dev version, thanks!

**Comment by alectogeek** [comment]
@darshankawar unfortunately, it didn't work.

Looks like I have a similar issue as in https://github.com/FirebaseExtended/flutterfire/issues/1178.
The minimal reproducible code sample can be found there, it's exactly what I'm trying to do. But in my case, I really need to be able to show a few Rewarded ads in a row! So it would be cool to be able to start loading the next video while the user watches the preloaded one.

In #1178 it is said that there is a native SDK limitation, but according to [current documentation](https://developers.google.com/admob/android/rewarded-ads#loading_multiple_rewarded_ads), there is a new API allowing to load multiple videos (if I understood it correctly).

Thanks!

**Comment by alectogeek** [comment]
Any updates here?
Should we... wait for any updates in the nearest future?

**Comment by alectogeek** [comment]
@darshankawar can I somehow help to accelerate feature this feature implementation/fix? We really need an ability to show a few ads in a row to earn in our apps.

**Comment by Pielgrin** [comment]
Is there any update ?

**Comment by briasullivan** [comment]
Any updates here? Unity allows using multiple instances of RewardedVideoAds to reflect the different Ad Units (recommended by Admob documentation). I'm not seeing how to do that with Flutter.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
