### ISSUE TITLE
[firebase_admob] iOS 14 App Tracking Transparency authorization

### ISSUE THREAD

**Issue by tonypottera24** [FirebaseExtended/flutterfire#3412]
According to google's document
https://developers.google.com/admob/ios/ios14

Starting in iOS 14, IDFA will be unavailable until an app calls the App Tracking Transparency framework to present the app-tracking authorization request to the end user. If an app does not present this request, the IDFA will automatically be zeroed out which may lead to a significant loss in ad revenue.

It would be helpful if firebase_admob can add a function to request tracking.
```
import AppTrackingTransparency
import AdSupport
...
func requestIDFA() {
  ATTrackingManager.requestTrackingAuthorization(completionHandler: { status in
    // Tracking authorization completed. Start loading ads here.
    // loadAd()
  })
}
```

**Comment by TahaTesser** [comment]
Hi @tonypottera24 
This is resolved in https://github.com/FirebaseExtended/flutterfire/issues/3236 and merged https://github.com/FirebaseExtended/flutterfire/issues/3236#issuecomment-682079621

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
