### ISSUE TITLE
Planning to upgrade Firebase Core dependencies?

### ISSUE THREAD

**Issue by mwolffalonso** [FirebaseExtended/flutterfire#3416]
Hi, i am having this conflict when trying to install Flutter_Analytics:

Because no versions of firebase_admob match >0.9.3+4 <0.10.0 and firebase_admob 0.9.3+4 depends on firebase_core ^0.4.2+1, firebase_admob ^0.9.3+4 requires firebase_core ^0.4.2+1.

And because firebase_analytics >=6.0.0 depends on firebase_core ^0.5.0, firebase_admob ^0.9.3+4 is incompatible with firebase_analytics >=6.0.0.

So, because twitter_alarm depends on both firebase_analytics ^6.0.0 and firebase_admob ^0.9.3+4, version solving failed.
pub get failed (1; So, because twitter_alarm depends on both firebase_analytics ^6.0.0 and firebase_admob ^0.9.3+4, version solving failed.)

I will install an older version of Analytics, but would be better to move forward all dependencies if possible, correct?

Thanks,
Martin.

**Comment by HofmannZ** [comment]
See #3209

**Comment by TahaTesser** [comment]
Hi @mwolffalonso 
I see this is resolved in  https://github.com/FirebaseExtended/flutterfire/issues/3209
Please try this package https://github.com/FirebaseExtended/flutterfire/issues/3209#issuecomment-682524356
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by mwolffalonso** [comment]
Hello Taha, 

Thank you very much! 

Regards, 
Martin. 

----- Mensaje original -----

De: "Taha Tesser" <notifications@github.com> 
Para: "FirebaseExtended/flutterfire" <flutterfire@noreply.github.com> 
CC: "mwolffalonso" <martin.wolff@vera.com.uy>, "Mention" <mention@noreply.github.com> 
Enviados: Martes, 1 de Septiembre 2020 7:46:42 
Asunto: Re: [FirebaseExtended/flutterfire] Planning to upgrade Firebase Core dependencies? (#3416) 





Hi @mwolffalonso 
I see this is resolved in #3209 
Please try this package #3209 (comment) 
If you disagree, please write in the comments and I will reopen it. 
Thank you
