### ISSUE TITLE
[firebase_crashlytics] Version Error

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#342]
### On https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#6

The codelab specifies to use version 3.2.1 of ```com.google.gms:google-services``` and **not to use a higher version**. However, version 3.2.1 has a bug and does not find the google-services.json file (```Could not find google-services.json while looking in [src/nullnull/profile, src/profile/nullnull, src/nullnull, src/profile, src/nullnullProfile]```). 

This bug is not present in version 4.3.1 of ```com.google.gms:google-services```. See first comment on [this SO answer](https://stackoverflow.com/a/47565868/1046444).

To make matters more confusing, but the codelab then links to [this guide](https://firebase.google.com/docs/android/setup#manually_add_firebase) which specifies 4.3.1 as the version to use on the Android side.

**Comment by kroikie** [comment]
@alemangui

The issue at https://github.com/flutter/flutter/issues/39721 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @alemangui
are you still experiencing this issue with the latest version of Flutter?
([crashlytics](https://pub.dev/packages/firebase_crashlytics) is the same version you tried before)
Thank you

**Comment by iapicca** [comment]
Hi @kroikie 
are you experiencing the same issue with the new version? `firebase_crashlytics 0.1.1+2`
thank you

**Comment by kroikie** [comment]
I believe this is resolved, we can close this and if it is still an issue anyone affected can open a new issue.

**Comment by ditman** [comment]
This is still broken, here's another report of the same:

https://github.com/FirebaseExtended/flutterfire/issues/1494#issuecomment-559214754

**Comment by ditman** [comment]
(The codelab still needs fixing IMO)
