### ISSUE TITLE
admob is old for core. cloud firestore didnt work with admob

### ISSUE THREAD

**Issue by yusufozill** [FirebaseExtended/flutterfire#3428]
Because firebase_admob 0.9.3+4 depends on firebase_core ^0.4.2+1 and no versions of firebase_admob match >0.9.3+4 <0.10.0, firebase_admob ^0.9.3+4 requires firebase_core ^0.4.2+1.

So, because omunotsays depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.
pub get failed (1; So, because omunotsays depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.)
exit code 1

admob depends on firebase core 0.4.2 but  cloud_firestore depends on 5 and they  dont work with together

pls update

**Comment by TahaTesser** [comment]
Hi @yusufozill 
I see this is resolved in  https://github.com/FirebaseExtended/flutterfire/issues/3209
Please try this package https://github.com/FirebaseExtended/flutterfire/issues/3209#issuecomment-682524356

Just tried these, no conflict the following packages
```
  firebase_core: ^0.5.0
  firebase_admob: ^0.10.0-dev.1
```

If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by yusufozill** [comment]
yes Its work, Thank you so much, I've been looking for days. finally Its work with cloudfirestore
