### ISSUE TITLE
Does FlutterFire Firestore module query from cache if docs are available in cache?

### ISSUE THREAD

**Issue by incrypt0** [FirebaseExtended/flutterfire#3429]
This is more of a doubt than an issue. I have tried asking at other places but i think its more of a flutterfire specific thing than a firebase thing.

Does flutterfire firestore plugin query data from cache and only pull documents when there is changed documents in cloud when using the `Firestore.Collection.get()` method.
That is if i have a `get()` method called everytime i open the app will firestore read all the documents from cloud even if no docs are changed and everything is available in cache ? Or does it pull documents only when there is changed documents in cloud?

Ive tried checking the read counts using GCP console but couldn't arrive at a conclusion. Can someone clarify this.

**Comment by Ehesp** [comment]
We implement the underlying SDKs so behaviour should mimic web/android/ios.

Basically it goes like this:

1. You perform a query.
2. Connection to the server is carried out to get server results.
3a. If server responds within 10 seconds, you get server result back (internally, the cache is updated).
3b. If no response is there within 10 seconds, documents are read from the cache. 

You can force the library to read from cache or server exclusively by using GetOptions. 

This is a good post to help understand the overall issue better: https://medium.com/firebase-developers/firestore-clients-to-cache-or-not-to-cache-or-both-8f66a239c329
