### ISSUE TITLE
Firestore fail occasionaly when attempt to do any transaction

### ISSUE THREAD

**Issue by richard457** [FirebaseExtended/flutterfire#3437]
## Bug report

**Describe the bug**
Expect for firestore to complete transaction

```
final  DocumentReference documentReference =
      FirebaseFirestore.instance.collection(collection).doc(docId);
      
      return FirebaseFirestore.instance.runTransaction((Transaction transaction)async{
        final DocumentSnapshot snapshot = await transaction.get(documentReference);
        if(!snapshot.exists){
          return false;
        }else{
          return true;
        }
      });
```

### Steps to reproduce

Use

```
final  DocumentReference documentReference =
      FirebaseFirestore.instance.collection(collection).doc(docId);
      
      return FirebaseFirestore.instance.runTransaction((Transaction transaction)async{
        final DocumentSnapshot snapshot = await transaction.get(documentReference);
        if(!snapshot.exists){
          return false;
        }else{
          return true;
        }
      });
```

4. See error or incorrect behavior

PlatformException (PlatformException(firebase_firestore, com.google.firebase.firestore.FirebaseFirestoreException: UNAVAILABLE: Channel shutdownNow invoked, {code: unavailable, message: The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.}))

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by TahaTesser** [comment]
Hi @richard457 
Can you please provide your `flutter doctor -v` your `pubspec.yaml` and a complete reproducible minimal code sample
Thank you

**Comment by richard457** [comment]
pubspec.yaml
`name: appname
description: 

version: 1.3.0

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  expandable: ^2.2.0
  flutter_launcher_icons: ^0.7.3
  flutter_local_notifications: ^1.4.4
  google_fonts: ^1.1.0
  path:
  flutter_svg:
  shared_preferences: 0.5.2
  shimmer: ^1.1.1
  sqflite: ^1.3.0
  url_launcher: ^5.0.2
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  auto_route: ^0.3.1
  yegobox_flutter_calendar: ^1.0.0
  pigment: ^1.0.3
  datetime_picker_formfield:
  percent_indicator: ^2.1.5
    # social sign_in
  firebase_auth: 
  google_sign_in: ^4.5.3

  flutter_twitter: 
  
  # end of social auth.
    # firebase
  firebase_core: ^0.5.0
  # firebase_messaging: ^6.0.12
  # firebase_analytics: ^5.0.11
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+6
  flutter_facebook_auth: "^0.2.3"
  # flutter_facebook_login: ^3.0.0
  # end of firebase dependencies.
  fluttertoast: ^7.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  built_value_generator: ^7.0.9
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  adaptive_icon_foreground: "assets/images/icon/icon_fg.png"
  adaptive_icon_background: "assets/images/icon/icon_bg.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/twitter_logo.png
    - assets/maradona.jpg
    - assets/player.jpg
    - assets/fire_2.png
    - assets/profile_image.jpg
    - assets/fire_red.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf



#  flutter build appbundle --build-name=1.3.0  --build-number=130`

**Flutter doctor**
` flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-029)       

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.2)
[√] Connected device (1 available)

• No issues found!`

**Comment by richard457** [comment]
**Reproduce **
`Future<bool> documentExist({String docId, String collection}) async {
 try{
    final  DocumentReference documentReference =
      FirebaseFirestore.instance.collection(collection).doc(docId);
      
      return FirebaseFirestore.instance.runTransaction((Transaction transaction)async{
        final DocumentSnapshot snapshot = await transaction.get(documentReference);
        if(!snapshot.exists){
          return false;
        }else{
          return true;
        }
      });
 }on PlatformException catch(e){
   print(e);
   return false;
 }
}`

**Comment by TahaTesser** [comment]
Hi @richard457 
I am unable to reproduce the issue using code sample on both ios and android 

<details> 
<summary>code sample</summary> 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
          // child: BookList(),
          ),
      floatingActionButton: FloatingActionButton(onPressed: () {
        documentExist(collection: 'zones', docId: 'XGHOfbIeUNLcjLAfeLEp')
            .then((value) => print(value));
      }),
    );
  }

  Future<bool> documentExist({String docId, String collection}) async {
    try {
      final DocumentReference documentReference =
          FirebaseFirestore.instance.collection(collection).doc(docId);

      return FirebaseFirestore.instance
          .runTransaction((Transaction transaction) async {
        final DocumentSnapshot snapshot =
            await transaction.get(documentReference);
        if (!snapshot.exists) {
          return false;
        } else {
          return true;
        }
      });
    } on PlatformException catch (e) {
      print(e);
      return false;
    }
  }
}

```

</details> 

Can you please provide steps to reproduce

**Comment by richard457** [comment]
These are step to reproduce, if for example I am checking if a document exist or not in a collection
   var collectionRef = FirebaseFirestore.instance.collection('users');

    var doc = await collectionRef.doc('bYAi1wMhHXm0i720Xwfoe').get();
    print( doc.exists);
**bYAi1wMhHXm0i720Xwfoe** Document Id does not exist therefore it produce error when the document exist it return true as expected.

**Comment by TahaTesser** [comment]
Hi @richard457 
I just tried again, couldn't reproduce any error 

<details> 
<summary>code sample</summary> 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
          // child: BookList(),
          ),
      floatingActionButton: FloatingActionButton(onPressed: () async {
        var collectionRef = FirebaseFirestore.instance.collection('users');
        var doc = await collectionRef.doc('bYAi1wMhHXm0i720Xwfoe').get();
        print(doc.exists);
      }),
    );
  }

  Future<bool> documentExist({String docId, String collection}) async {
    try {
      final DocumentReference documentReference =
          FirebaseFirestore.instance.collection(collection).doc(docId);

      return FirebaseFirestore.instance
          .runTransaction((Transaction transaction) async {
        final DocumentSnapshot snapshot =
            await transaction.get(documentReference);
        if (!snapshot.exists) {
          return false;
        } else {
          return true;
        }
      });
    } on PlatformException catch (e) {
      print(e);
      return false;
    }
  }
}

```

</details> 

```
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Xcode build done.                                           195.0s
Connecting to VM Service at ws://127.0.0.1:64058/JpHzzsWBYL8=/ws
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
flutter: false
```
```
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
```

**Comment by JoshRice1** [comment]
@TahaTesser I am having this same issue but it is very intermittent.  Most cases for me at least seem to only happen when the app is resumed.  Mine isn't tied to a transaction through it is in the execution of a query.  I see it in some other places like transactions as well, the latest release of the package finally exposed this error as before it was just a generic platform exception that gave not details.

Also, one strange thing is that other calls seem to work and data is loaded and written to just fine.  It is very intermittent though and hard to reproduce and doesn't happen consistently (at least in my experience).  I have had no luck reproducing this when hooked up to a debugger (Not sure but kind of feels like an async issue where things are slowed down on the debugger so it works fine).  Also, it seems to be prevalent when the network connection isn't great.

Sorry just giving a brain dump of what I have noticed to help find the issue as it is one of the biggest complaints we have on our app.

**Comment by russellwheatley** [comment]
I don't think this is a bug. If you try to query a document when offline, you will get a platform error. If you're online, you will not. This is by design I believe.
