### ISSUE TITLE
[📚] Documentation on firebase hosting

### ISSUE THREAD

**Issue by sidrao2006** [FirebaseExtended/flutterfire#3448]
A simple documentation can be provided for hosting flutter web apps using firebase hosting

In future command line tool can be released in pub which downloads and interacts with the firebase CLI to directly configure the web app using the existing pubspec.yaml file and the web/index.html without prompting for user input.
An option to override these configurations can also be provided

**Comment by alfredobs97** [comment]
Hello! Firebase hosting is a service that cannot interact directly with Flutter.

If you want to deploy a Flutter web project, you can build the app with:

`flutter build web --release`

And after this step, login in firebase with firebase CLI and type:

`firebase init`

Select the project and hosting service with the output: build/web. And upload with

`firebase deploy`

There is a code to integrate with Github Actions to deploy a flutter web app directly:

[Gist](https://gist.github.com/alfredobs97/70be7f0d29cec798ffb945da22f5cb0c)

**Comment by sidrao2006** [comment]
Yep, thanks. This is exactly what I want on the flutterfire website as a guide to beginners

**Comment by Ehesp** [comment]
This is unrelated to FlutterFire - the docs on the official Firebase website can guide you to how to host websites (something unrelated to FlutterFire). 

In short, Firebase just hosts HTML files. Flutter has docs on how to generate those files via Flutter web.

**Comment by sidrao2006** [comment]
Ok thanks
