### ISSUE TITLE
[📚] Documentation and support for Firebase extensions

### ISSUE THREAD

**Issue by sidrao2006** [FirebaseExtended/flutterfire#3449]
Firebase extensions which are in beta also need to be added to flutterfire along with documentation.

**Comment by Ehesp** [comment]
Could you provide an example? Firebase Extensions are part of the Firebase suite - FlutterFire is just a standalone implementation of Firebase for Flutter. I'm not sure why extensions would need to be on the FlutterFire docs.

**Comment by sidrao2006** [comment]
For integration with flutter apps, docs can be provided

**Comment by sidrao2006** [comment]
Actually, firebase does provide enough docs for extensions.
Sorry for the trouble
