### ISSUE TITLE
[firebase_messaging] users can't get FCM token

### ISSUE THREAD

**Issue by krongnang** [FirebaseExtended/flutterfire#3455]
## Bug report

**235/3177 (7.4%) can't not get FCM token**

Currently, our app have 3177 Android user and 235 user can't get FCM token?
I need to find the main reason, I don't think GPS not available in all failed devices!

Thanks!

**Comment by TahaTesser** [comment]
Hi @krongnang 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your 
Thank you
