### ISSUE TITLE
Flutter plugins assume that there will be an Activity available at registration

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#346]
If [android_alarm_manager](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager) is being used, it will try to register all plugins at `Application.onCreate`, right?

If so, [cloud_firestore](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L80), [firebase_database](https://github.com/flutter/plugins/blob/master/packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java#L55) and [in_app_purchase](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java#L73) will get a null reference to the activity, right?

**Comment by kroikie** [comment]
@BugsBunnyBR

The issue at https://github.com/flutter/flutter/issues/38692 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
@matthew-carroll 
@collinjackson
@mklim

**Comment by iapicca** [comment]
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/19)addressing the case you described.
