### ISSUE TITLE
🐛 [firebase_auth] userChanges() docs are misleading

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#3461]
The new API has the `userChanges()` `Stream<User>`, this is its documentation:

```dart
  /// Notifies about changes to any user updates.
  ///
  /// This is a superset of both [authStateChanges] and [idTokenChanges]. It
  /// provides events on all user changes, such as when credentials are linked,
  /// unlinked and when updates to the user profile are made. The purpose of
  /// this Stream is to for listening to realtime updates to the user without
  /// manually having to call [reload] and then rehydrating changes to your
  /// application.
```

After testing  I can verify that this part is wrong: 

>The purpose of this Stream is to for listening to realtime updates to the user **without manually having to call [reload]**

I was trying to verify a user's email address, without calling `user.reload()` periodically and I didn't get any updates on `userChanges()`. It only emitted updates when I called `user.reload()`.

The docs makes it looks like the library will detect server changes automatically, without having to call `reload()`, so either the documentation is wrong or there's a bug in the implementation that's not automatically emitting updates for `user.emailVerified`.

**Comment by yamauchieduardo** [comment]
Using the `userChanges` stream I can listen all the custom-claims changes?

When I readed the new documentation I understood that. But, when I tested the method changing the currentUser token in server, the `userChanges` stream doesn't  do nothing. 

This is a bug? or the documentation is wrong?

**Comment by feinstein** [comment]
Try calling `user.reload()` and see if it works. For that specific case `idTokenChanges()` should work as well if you prefer a more specific approach.

This issue is about how we need to call `user.reload()` in order to get updates, while the docs don't mention it.

PS: Issues are usually prioritized by 👍 so that's the only emoji that can actually help things gets solved/clarified quicker.

**Comment by yamauchieduardo** [comment]
I will test, but its is confuse. In the documentation `userChanges` is a superset of both `authStateChanges` and `idTokenChanges`. Supose if something trigger `idTokenChanges` will trigger `userChanges` too, alright?

**Comment by feinstein** [comment]
Yes, you are correct, I was just saying you can use them both, if you prefer to be more specific.

**Comment by russellwheatley** [comment]
I believe this is a documentation issue. The observer is not triggered when various properties on a user record are changed. Documentation for when it is triggered for [idTokenChanges](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.IdTokenListener) &  [authStateChanges](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.AuthStateListener#public-methods) for android.
