### ISSUE TITLE
🐛 [firebase_auth] Should version 0.16.1+1 be used ?

### ISSUE THREAD

**Issue by humazed** [FirebaseExtended/flutterfire#3468]
## Bug report

**Describe the bug**
when calling pub get I'm getting

>  pub get failed (1; Because karam_al_reef_consumer depends on firebase_auth ^0.16.1+1 which doesn't match any versions, version solving failed.)

I don't want to update to the latest version because it has many breaking changes, and the latest one fails to send the SMS code which makes it unusable.

**Comment by darshankawar** [comment]
Hi @humazed,
Can you provide `pubspec.yaml` ? Not sure how you are seeing `firebase_auth ^0.16.1+1`, because in versions list, I see `^0.16.0` and `^0.16.1`.

**Comment by humazed** [comment]
from here https://pub.dev/packages/firebase_auth/changelog

![image](https://user-images.githubusercontent.com/8838182/92409396-c398e680-f140-11ea-95fe-929f5b0a021f.png)
I want the fix in 0.16.1+1  without updating to the latest version but it is not published yet.

**Comment by TahaTesser** [comment]
Hi @humazed 
Can you please `0.16.1+1` without `^`

**Comment by humazed** [comment]
I'm sure it won't work because the version doesn't exist in the versions list

![image](https://user-images.githubusercontent.com/8838182/92491965-21860680-f1f3-11ea-8121-b65dac15cb98.png)

**Comment by darshankawar** [comment]
We do see pub error after adding the said firebase_auth version:

```
Running "flutter pub get" in flutterfiredemo...                 
Because flutterfiredemo depends on firebase_auth ^0.16.1+1 which doesn't match any versions, version solving failed.
pub get failed (1; Because flutterfiredemo depends on firebase_auth ^0.16.1+1 which doesn't match any versions, version solving failed.)
Process finished with exit code 1


```
But not sure if we should be using that version of the plugin since it's not listed [here](https://pub.dev/packages/firebase_auth/versions).

**Comment by russellwheatley** [comment]
I'm afraid you will have to update your versions at some point. I'm pretty sure that error is because you're mixing null-safe/non null-safe packages and pub get is failing. I'm going to close this issue, but if you feel there is a problem with the current auth SMS implementation, feel free to open a new issue.
