### ISSUE TITLE
[📚] Conflicting docs for Firebase Messaging (CHANGE ME)

### ISSUE THREAD

**Issue by deadsoul44** [FirebaseExtended/flutterfire#3469]
In firebase_messaging readme, you say add firebase_messaging dependency to app/build.gradle:

https://pub.dev/packages/firebase_messaging#getting-started

![readme](https://user-images.githubusercontent.com/31016182/92307264-bb547600-ef9d-11ea-8911-2932a439376b.PNG)

But in migration guide, you say remove any firebase product dependency from app/build.gradle:

https://firebase.flutter.dev/docs/migration/#a-android-installation

![migration](https://user-images.githubusercontent.com/31016182/92307275-e2ab4300-ef9d-11ea-9097-add73cae1386.PNG)

Which one is correct?

**Comment by prakharb10** [comment]
Hi, I'd like to work on this

**Comment by alfredobs97** [comment]
Hey! 
I see the migration guide and I remove the dependency in build.gradle but it doesn´t work so I think the correct is the first documentation and you have to set the firebase-messaging dependency

**Comment by Abhishek01039** [comment]
Hello @prakharb10 
https://github.com/FirebaseExtended/flutterfire/pull/4012
This reverts the docs 
Please see this https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.9
Thanks

**Comment by Salakar** [comment]
The one on pub currently in your screenshot is the old stable version. The new website and migration guide is for the dev release as @Abhishek01039 mentioned above.

This will be promoted to stable in a few days.
