### ISSUE TITLE
🐛 [firebase_messaging] Action buttons are not yet supported in notifications

### ISSUE THREAD

**Issue by sumit2393** [FirebaseExtended/flutterfire#3472]
We are in need to implement action button in notifications but due to certain limitations of this plugin we are not being able to create it. It is requested to kindly provide the action buttons support in the push notification. Thhis issue is already created before by many users but it is closed with no reason. It is a support request.

**Comment by darshankawar** [comment]
Hi @sumit2393,
Please see [this](https://github.com/FirebaseExtended/flutterfire/issues/1484#issuecomment-618278471) comment and a workaround to implement action buttons. Also note that the ticket was closed with `won't fix` as a resolution, which indicates that `firebase_messaging` plugin may not get action buttons, and you'll need to use `flutter_local_notifications` to add that.
Hope it helps.
