### ISSUE TITLE
firebase_auth Android crash when using the Github AuthProvider

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#348]
When signing in with GithubAuthProvider credentials with Firebase Auth, the app crashes on Android (stack trace below). This happens because info.getProfile() in mapFromAdditionalUserInfo() has JSONObject.NULL values, and JSONObject.NULL is not null, so the message codec does not detect it as a null.

Most likely related to #37294

Stack trace:
`E/AndroidRuntime(31676): java.lang.IllegalArgumentException: Unsupported value: null
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(31676): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:691)
E/AndroidRuntime(31676): 	at com.google.android.gms.tasks.zzj.run(Unknown Source)
E/AndroidRuntime(31676): 	at android.os.Handler.handleCallback(Handler.java:836)
E/AndroidRuntime(31676): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(31676): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(31676): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/AndroidRuntime(31676): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31676): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1067)
E/AndroidRuntime(31676): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)`

**Comment by jmbartho** [comment]
Why is this closed? 

What's the recommended fix? 
(Commenting out the line on the plugin from the other thread worked for me for now...)

**Comment by kroikie** [comment]
@jmbartho see discussion in original issue: https://github.com/flutter/flutter/issues/37681

If this is still an issue for you please file an issue with the required information.

**Comment by jmbartho** [comment]
I'm happy to repost everything, but it seems redundant to me. Everything seems to be the same as https://github.com/flutter/flutter/issues/37681 

Commenting out this line works:
//additionalUserInfoMap.put("profile", info.getProfile());

I'm signing in to Twitter with mine. Same null error. Everything else is the same.

**Comment by kroikie** [comment]
@jmbartho sorry for the duplication however it will help us track the bug and assign someone to look into a solution.

**Comment by rafern** [comment]
@jmbartho @kroikie the fix isn't in stable yet for some reason, so the bug still occurs. i put some instructions on how to switch to the dev channel in the original thread if you want to give it a shot. i've also asked in the pr thread to get the fix as a 1.9.1 hotfix but there hasn't been a response so far, so... :(

**Comment by kroikie** [comment]
@rafern thanks for pinging this issue. Is this an issue with the Firebase Auth plugin or the Flutter engine?

**Comment by rafern** [comment]
@kroikie its an issue with the engine: https://github.com/flutter/engine/pull/11283

**Comment by kroikie** [comment]
@rafern I see what you mean. I'll check when is the next available opportunity this can be merged into stable.

**Comment by rafern** [comment]
@kroikie Thank you!

**Comment by kroikie** [comment]
@rafern I did some checking and asking but the [wiki](https://github.com/flutter/flutter/wiki/Release-process#applying-emergency-fixes) has a pretty clear process for hotfixes. 

```
This process should not be used for non-security fixes
```

However since we intend to release to stable every quarter or so, it should not be too long before the fix is in stable. Sorry we can't get this in sooner.

**Comment by rafern** [comment]
@kroikie thanks for checking anyway, because now we know its going to be added in the near future
