### ISSUE TITLE
Cloud Function implementation method missing

### ISSUE THREAD

**Issue by parthghedia** [FirebaseExtended/flutterfire#3481]
MissingPluginException(No implementation found for method CloudFunctions#call on channel plugins.flutter.io/cloud_functions)

**Comment by darshankawar** [comment]
Hi @parthghedia,
Please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue. Also make sure you follow the instructions and setup is per migration [guide](https://firebase.flutter.dev/docs/migration/).
Thanks.

**Comment by hyobbb** [comment]
Same issue.

[✓] Flutter (Channel master, 1.22.0-10.0.pre.14, on Mac OS X 10.15.6 19G2021, locale en-KR)
    • Flutter version 1.22.0-10.0.pre.14 at /Users/mac/flutter
    • Framework revision 6d1242dd4b (10 days ago), 2020-08-31 03:53:04 -0400
    • Engine revision 784e6d746e
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!


dependency =>  cloud_functions: ^0.6.0

running exactly the same example code the plug in provide.

// Copyright 2018, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_functions/cloud_functions.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _response = 'no response';
  int _responseCount = 0;

  @override
  Widget build(BuildContext context) {
    final HttpsCallable callable = CloudFunctions.instance
        .getHttpsCallable(functionName: 'repeat')
          ..timeout = const Duration(seconds: 30);
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Cloud Functions example app'),
        ),
        body: Center(
          child: Container(
            margin: const EdgeInsets.only(top: 32.0, left: 16.0, right: 16.0),
            child: Column(
              children: <Widget>[
                Text('Response $_responseCount: $_response'),
                MaterialButton(
                  child: const Text('SEND REQUEST'),
                  onPressed: () async {
                    try {
                      final HttpsCallableResult result = await callable.call(
                        <String, dynamic>{
                          'message': 'hello world!',
                          'count': _responseCount,
                        },
                      );
                      print(result.data);
                      setState(() {
                        _response = result.data['repeat_message'];
                        _responseCount = result.data['repeat_count'];
                      });
                    } on CloudFunctionsException catch (e) {
                      print('caught firebase functions exception');
                      print(e.code);
                      print(e.message);
                      print(e.details);
                    } catch (e) {
                      print('caught generic exception');
                      print(e);
                    }
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}


I/flutter (  823): caught generic exception
I/flutter (  823): MissingPluginException(No implementation found for method CloudFunctions#call on channel plugins.flutter.io/cloud_functions)

Got this error.

**Comment by siddhantkothari** [comment]
I am getting the same error: MissingPluginException(No implementation found for method CloudFunctions#call on channel plugins.flutter.io/cloud_functions)
---------------------------------------------------------------------------------------
Flutter Doctor:
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.4 at D:\Flutter\src\flutter
    • Framework revision fba99f6cf9 (4 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\siddh\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code, 64-bit edition (version 1.49.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • sdk gphone x86 (mobile) • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

---------------------------------------------------------------------------------------
Pubspec.yaml :
name: xxxxxxxx
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  google_sign_in:
  cloud_functions: ^0.6.0
  provider:

  firebase_database:

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

---------------------------------------------------------------------------------------

**Comment by zxcvbnmmohd** [comment]
I literally just had that error. As I was googling for a solution I just did a quick flutter clean,  reformatted the call to Cloud Functions as below, similar to what is on FlutterFire Cloud Function example app, and the ran the app and it worked just fine!

Future<Map<dynamic, dynamic>> notifyMatchedUser({Map<dynamic, dynamic> data}) async {
    final HttpsCallable httpsCallable = CloudFunctions.instance
        .getHttpsCallable(functionName: Constants.usersMatchedNotification)
          ..timeout = const Duration(seconds: 30);

    try {
      final HttpsCallableResult httpsCallableResult = await httpsCallable.call(data);

      return httpsCallableResult.data as Map<dynamic, dynamic>;
    } on CloudFunctionsException catch (e) {
      print('caught firebase functions exception');
      print(e.code);
      print(e.message);
      print(e.details);
    } catch (e) {
      print('caught generic exception');
      print(e);
    }
  }
