### ISSUE TITLE
[firebase_auth_web] Support to signInWithPhoneNumber on stable branch

### ISSUE THREAD

**Issue by cacianokroth** [FirebaseExtended/flutterfire#3485]
Good afternoon, when will it be possible to signInWithPhoneNumber?
Or if it already exists, do you have any example of how to apply it?
Thank you.

**Comment by Ehesp** [comment]
It's merged, just needs a release. We're working on some tooling to help automate releases since manually it takes a very long time. It'll be available in the next one so keep an eye out 😃

**Comment by cacianokroth** [comment]
Thank you, @Ehesp!
I forked the project and pointed everything to master and it is working very well.
Regards.

**Comment by bankenro** [comment]
> Thank you, @Ehesp!
> I forked the project and pointed everything to master and it is working very well.
> Regards.

In master it is not working for me.

 Error: Type 'RecaptchaVerifierSize' not found.
 Error: Type 'RecaptchaVerifierTheme' not found.
 Error: Type 'RecaptchaVerifierOnSuccess' not
 Error: Type 'RecaptchaVerifierOnError' not found.
 Error: Type 'RecaptchaVerifierOnExpired' not found.
 Error: The method 'linkWithPhoneNumber' isn't defined for the class 'UserPlatform'.

my pubspec.yaml :
 firebase_auth:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_auth/firebase_auth
