### ISSUE TITLE
[📚] FutureBuilder initialization sample is broken on Flutter 1.20

### ISSUE THREAD

**Issue by domesticmouse** [FirebaseExtended/flutterfire#3490]
I'm attempting to implement the [Initializing Flutterfire](https://firebase.flutter.dev/docs/overview#initializing-flutterfire) FutureBuilder approach with Flutter 1.20 and hitting the following exception:

```bash
$ flutter --version
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (7 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
$ flutter run -d iPhone
Launching lib/main.dart on iPhone 8 in debug mode...
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        13.4s
Xcode build done.                                           36.1s
Waiting for iPhone 8 to report its views...                          4ms
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:93:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:106:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:145:62)
#3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:151:35)
#4      MethodChannel.invokeMethod (package:flutter/src/services/platfor<…>
Syncing files to device iPhone 8...                                135ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 8 is available at: http://127.0.0.1:63589/nxc57idb0bs=/

Application finished.
```

My `main.dart` looks like this:
```
import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  // Create the initilization Future outside of `build`:
  final Future<FirebaseApp> _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutterfire Demo',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutterfire Demo'),
        ),
        body: FutureBuilder(
          // Initialize FlutterFire:
          future: _initialization,
          builder: (context, snapshot) {
            // Check for errors
            if (snapshot.hasError) {
              return Center(child: Text('${snapshot.error}'));
            }

            // Once complete, show your application
            if (snapshot.connectionState != ConnectionState.done) {
              return Center(child: Text('Loading'));
            }

            // Otherwise, show something whilst waiting for initialization to complete
            return Center(child: Text('Success!'));
          },
        ),
      ),
    );
  }
}
```

While I can work around this by adding `WidgetsFlutterBinding.ensureInitialized();` to `main`, that is an ugly hack. It'd make more sense to only promote the `StatefulWidget` approach.

**Comment by TahaTesser** [comment]
I can reproduce the issue
This solves it 
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}
```

**Comment by domesticmouse** [comment]
I'd prefer not to promote `WidgetsFlutterBinding.ensureInitialized();` if at all possible =)

**Comment by domesticmouse** [comment]
An idea is to add some form of widget to the FirebaseAuth package that handles initialization along the lines of the following:

```dart
class FirebaseInit extends StatefulWidget {
  FirebaseInit({@required this.child});
  final Widget child;

  @override
  _FirebaseInitState createState() => _FirebaseInitState();
}

class _FirebaseInitState extends State<FirebaseInit> {
  bool _initialized = false;
  String _error;

  void initializeFlutterFire() async {
    try {
      await Firebase.initializeApp();
      setState(() {
        _initialized = true;
      });
    } catch (err) {
      setState(() {
        _error = '$err';
      });
    }
  }

  @override
  void initState() {
    super.initState();
    initializeFlutterFire();
  }

  @override
  Widget build(BuildContext context) {
    if (_error != null) {
      return Center(child: Text(_error));
    }
    if (!_initialized) {
      return Center(child: CircularProgressIndicator());
    }

    return widget.child;
  }
}
```

The above is just a sketch, and I'm sure that we could harden it (like, say, logging the error message instead of splatting it to screen).

**Comment by domesticmouse** [comment]
Hey @ditman, am I being over zealous by trying to avoid `WidgetsFlutterBinding.ensureInitialized();`?

**Comment by ditman** [comment]
> Hey @ditman, am I being over zealous by trying to avoid `WidgetsFlutterBinding.ensureInitialized();`?

@domesticmouse not sure, but I [had similar doubts earlier](https://github.com/FirebaseExtended/codelab-friendlyeats-flutter/pull/5#pullrequestreview-484394852) :) I checked [the docs](https://api.flutter.dev/flutter/widgets/WidgetsFlutterBinding/ensureInitialized.html) and it *seems* it can be used exactly for this purpose:

> You only need to call this method if you need the binding to be initialized before calling runApp.

(I normally had only seen this used within tests)

It'd be awesome to figure out what "asynchronous" thing your Future is losing its race against and the `FutureBuilder` case Just Worked™, I've used a similar approach to make a [deferred-loaded app before](https://github.com/FirebaseExtended/codelab-friendlyeats-flutter/blob/done/lib/main.dart#L23-L26) (note how the ensureInitialized was also added there :/).

**Comment by domesticmouse** [comment]
I remember `WidgetsFlutterBinding.ensureInitialized();` becoming required in various places in about the 1.17 timeframe for various usecases. I'm happy to roll back my stance and just add the ensure initialized call to the sample in the documentation to prevent people hitting it and getting confused at the error.

I'm unsure who to chat with about debugging why this is required. I'm guessing it is something deep in the FFI bindings =)

**Comment by goderbauer** [comment]
What reservations do you have against calling `WidgetsFlutterBinding.ensureInitialized()`? It's exactly what `runApp` does internally as well, there really shouldn't be any harm in doing so.

**Comment by ditman** [comment]
@goderbauer personally, I had only seen it used in tests before, never had seen a "normal" app calling it directly (but I didn't find anything in the docs advising *against* it).

**Comment by domesticmouse** [comment]
Okiday, we just had a meeting on this and calling `ensureInitialized` in main before `runApp` is totally ok to do. So if we can get the sample updated as @TahaTesser suggested in https://github.com/FirebaseExtended/flutterfire/issues/3490#issuecomment-688816602 that'd be fantastic =)

**Comment by ditman** [comment]
I suspect this is the affected file: https://github.com/FirebaseExtended/flutterfire/blame/master/docs/overview.mdx#L67

**Comment by Ehesp** [comment]
I'm still a bit confused here. Wouldn't this effect other plugins which call a native method immediately? What is FlutterFire doing which causes this issue specifically (when you don't add `WidgetsFlutterBinding.ensureInitialized();`)?

**Comment by boeledi** [comment]
With version 1.22.4 (stable), even adding the

```
WidgetsFlutterBinding.ensureInitialized()
```
as the first line in the main() does not solve the issue.  I am still getting the exception.

I am running

firebase_core: ^0.5.2+1
firebase_remote_config: ^0.4.2
