### ISSUE TITLE
Flutter FCM Notification clearing when tap but not opening app (One Plus Device)

### ISSUE THREAD

**Issue by ThalapathySiva** [FirebaseExtended/flutterfire#3491]
When I receive notification in oneplus device and click the notification, it works as expected, but if the received notification is in the tray for more than five minutes and then on pressing that notification, the app does not open and gets cleared from the notification tray. This behavior happens only with oneplus device, but not with other devices like samsung, realme, nokia, etc.

**Comment by acoutts** [comment]
You'll want to add some more information to help debug the issue. At a minimum, what versions of flutter and your FCM library are, and some minimal reproducible code for the issue demonstrating how you've setup the library.

**Comment by ThalapathySiva** [comment]
@acoutts
Flutter Version : 1.20.2
FCM Library : firebase_messaging: ^7.0.0


Code that i have implemented : 
    void firebaseCloudMessagingListeners() async {
    if (Platform.isIOS) iOSPermission();
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        _showNotificationWithDefaultSound(message);
        print("onMessage when app in foreground");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume when app in background");
        _pageOpenForOnLaunch(message);
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch when app in terminate state");
        _pageOpenForOnLaunch(message);
      },
    );
  }

In those function i have handled to navigate to respective pages.Problem is not opening the app itself.

**Comment by darshankawar** [comment]
@ThalapathySiva,
Are your `onMessage`, `onResume` methods being called when you tap on notification ?
Can you provide `flutter run --verbose` when it doesn't open the app ?
Thanks.

**Comment by ThalapathySiva** [comment]
@daikini  thanks for your reply, actually nope its not even opening the app, only the notification disappears and its happening only in One plus device.

**Comment by darshankawar** [comment]
Per OP, the issue is only happening on specific device (One Plus) which I don't have to replicate. Keeping this issue open for further analysis.

**Comment by carlos-labrador** [comment]
@ThalapathySiva  I got same problem with a JetPhone.

the folowing solution works for me:
![image](https://user-images.githubusercontent.com/22735837/103869903-54db9200-510e-11eb-96c9-294683ed2743.png)

Just in case.

**Comment by russellwheatley** [comment]
Hey @ThalapathySiva, is this still an issue for you after upgrading to the latest `firebase_messaging` version `"^10.0.3"`?

**Comment by russellwheatley** [comment]
Closing this due to lack of response.
