### ISSUE TITLE
[firebase_in_app_messaging] Package on pub.dev is v0.0.1 but repo is v0.0.1+2

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#350]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/firebase_in_app_messaging/pubspec.yaml

`Readme.md `also missing pub.dev link here: 

https://github.com/flutter/plugins/blob/master/packages/firebase_in_app_messaging/README.md

**Comment by kroikie** [comment]
@workerbee22

The issue at https://github.com/flutter/flutter/issues/37539 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @workerbee22
can you please describe the issue in detail
thank you

**Comment by workerbee22** [comment]
Pub.dev says it is 0.0.1+3 .... but in the repo it is 0.0.1+4 here https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_in_app_messaging/pubspec.yaml
