### ISSUE TITLE
🐛 [cloud_firestore] stops syncing data for some users.

### ISSUE THREAD

**Issue by m-j-g** [FirebaseExtended/flutterfire#3504]
## Bug report

**Describe the bug**
I'm running cloud_firestore ^0.14.0+2 in production.  Most of the time there is not a problem, but I'm semi-regularly getting support calls where the firestore data isn't syncing, WHILE they are successfully making calls to my cloud_functions https calls. 

My app often is displaying data from firestore, but uses cloud_function https calls to modify the data for a number of reasons.  So the user is making these calls successfully, and the data from firestore never updates. 

/Users/mgaines/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/mgaines/flutter
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mgaines/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

PUBSPEC.YAML
version: 1.1.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0
  share: ^0.6.4+5
  provider: ^4.3.1
  rxdart: ^0.24.0
  shimmer: ^1.0.1
  hidden_drawer_menu: 2.0.1
  carousel_slider: ^2.1.0
  cached_network_image: ^2.3.1
  clay_containers: any
  dash_chat: 1.1.14
  flutter_form_builder: ^3.13.3
  image_picker: ^0.6.7+7
  transparent_image: ^1.0.0
  flutter_keyboard_visibility: ^3.2.2
  flutter_svg: ^0.18.1
  numberpicker: ^1.2.0
  equatable: ^1.2.4
  octo_image: ^0.2.1
  shared_preferences: ^0.5.10
  permission_handler: ^5.0.1
  sign_in_with_apple: ^2.5.2
  audioplayers: ^0.15.1 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^5.5.0
  google_fonts: ^1.1.0
  flutter_slidable: 0.5.5
  animations: ^1.1.2

  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  cloud_functions: ^0.6.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  firebase_crashlytics: ^0.1.4+1
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  video_player: ^0.10.12+2
  # the issue thread: https://github.com/FirebaseExtended/flutterfire/pull/255
  firebase_dynamic_links: #^0.5.1
    git:
      url: https://github.com/mrmilu/flutterfire.git
      path: packages/firebase_dynamic_links
      ref: PR-255-v1

**Comment by TahaTesser** [comment]
Hi @m-j-g 
Can you please provide your `flutter doctor -v` your `pubspec.yaml`
Thank you
