### ISSUE TITLE
Firebase Test Lab Robo Test support

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#353]
Firebase offer a nice way to test android app automatically (or semi automatically if you provide a Robo Script) called Robo test in their Test Lab section https://firebase.google.com/docs/test-lab/android/robo-ux-test

Would be nice if Flutter application can be test that way too.

Currently when you upload the APK, there is 2 issues:
- it open the app, wait for the first screen to show, then exit the app. It doesn't try to automatically explore the app
- We can't provide a Robo Script because the AS plugin to do that doesn't record anything for a flutter app

That way of testing is quite nice as it doesn't need that much work to actually do something, and firebase allow a large choice of devices. Doing such UI test will help finding UI problem (so it also benefit iOS, desktop and web platform too)

**Comment by kroikie** [comment]
@jaumard

The issue at https://github.com/flutter/flutter/issues/36681 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by vishna** [comment]
Imo the focus should be getting firebase team to support flutter instrumentation tests and flutter team fixing some annoying bugs they have in the instrumentation framework.

**Comment by collinjackson** [comment]
> Imo the focus should be getting firebase team to support flutter instrumentation tests and flutter team fixing some annoying bugs they have in the instrumentation framework.

@vishna I'm curious which bugs you're referring to.

**Comment by collinjackson** [comment]
This isn't an issue with the Flutterfire plugins, so I'm closing the Flutterfire issue and moving the discussion back to the flutter/flutter issue tracker: https://github.com/flutter/flutter/issues/36681
