### ISSUE TITLE
[firebase_admob]  how does "nonPersonalizedAds: true" work in MobileAdTargetingInfo class?

### ISSUE THREAD

**Issue by badranmo** [FirebaseExtended/flutterfire#3540]
Hello,

For the firebase_admob package - how does "nonPersonalizedAds: true" work in MobileAdTargetingInfo class? Does it set all ads to all users regardless of their location to non personalized or only those in the UK and EU?
If the Admob account settings are set to personalized ads and MobileAdTargetingInfo class is set to nonPersonalized ads , will ALL users get non personalized ads or only those in the EU and UK? I couldn't see a clear explanation in the docs.

Thanks

**Comment by badranmo** [comment]
Any update on this one?

**Comment by badranmo** [comment]
@darshankawar is there anything I can do to get an answer on this question?

**Comment by badranmo** [comment]
hi @markusaksli-nc  - thank you waiting for an update from your side.

**Comment by markusaksli-nc** [comment]
This issue is on the team's radar. Don't have a definite answer yet though. Since there is no documentation for this property in the upstream API I wouldn't rely on it.

**Comment by badranmo** [comment]
@markusaksli-nc . Just to share that in admob documentation, it seems that the Ad manager expects a tag to switch between personalized and non personalized Ads which I assume that this may be the one. Some details are below in these 2 links

https://support.google.com/admanager/answer/7673898
https://support.google.com/admanager/answer/7678538

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
