### ISSUE TITLE
Issue while building the app for release.

### ISSUE THREAD

**Issue by 11kush11** [FirebaseExtended/flutterfire#3552]
For some reason, from the time I have updated the firestore plugin, I have been having issues while building the app for release. I have also changed my complieSdkVersion to 30 and upgraded to graded 6.1.1. 

Issue:
Running "flutter pub get" in fodafinal...                           0.8s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Plugin project :url_launcher_macos not found. Please update settings.gradle.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\1kush\AndroidStudioProjects\gamefinal\build\app\intermediates\flutter\debug\libs.jar.
         > Transform's input file does not exist: C:\Users\1kush\AndroidStudioProjects\gamefinal\build\app\intermediates\flutter\debug\libs.jar. (See https://issuetracker.goo
gle.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 24s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      85.9s
Gradle task assembleRelease failed with exit code 1

**Comment by darshankawar** [comment]
Hi @11kush11,
This does not seem to be an issue with firestore upgrade, but with the combination of compilesdk version and gradle version which lint isn't happy about.
Please check [this](https://github.com/flutter/flutter/issues/58247) issue and various solutions mentioned and see if they work for you.
Thanks.
