### ISSUE TITLE
[📚] Android Firebase SDK override should be rootProject.ext instead of project.ext

### ISSUE THREAD

**Issue by red42** [FirebaseExtended/flutterfire#3554]
[This section](https://firebase.flutter.dev/docs/overview/#android) describes how to override the Firebase SDK version. However, in my tests, I could only make it work using `rootProject.ext` instead of `project.ext`.

For instance, this is what I'm using to override the SDK version:
```
rootProject.ext {
    set("FlutterFire", [
            FirebaseSDKVersion: "25.4.1",
    ])
}
```

I could not make it work following the documentation, using `project.ext`.

**Comment by geecat** [comment]
I was just looking for a documentation for FirebaseSDKVersion: XXX.
Where can I check what is the latest version?

**Comment by red42** [comment]
@geecat for Android, you can check the [release notes](https://firebase.google.com/support/release-notes/android) - use the Bill of Materials (BoM) version number. It's easier to find on the right side column.

iOS is easier, as the [release notes](https://firebase.google.com/support/release-notes/ios) section names are the SDK versions themselves.
