### ISSUE TITLE
[firebase_dynamic_links] Programmatically getting the data of a Firebase Dynamic Link

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#356]
## Use case

I am sending Push Notifications to users that contain some custom data. One of the fields inside that custom data is a dynamic link. I would like to use the [Firebase Dynamic Liks ](https://pub.dev/packages/firebase_dynamic_links) plugin to get the real link value programmatically and then use that to change the screens in the app.

Example of push notification custom data:
```dart
final pnCustomData = {
    "dynamicLink": "my-app.page.link/6LnV" // the real link for the Android app is `/settings`
} // this will inside the push notification payload
```

## Proposal

I was thinking to add a method inside `FirebaseDynamicLinks.instance` to get the link's data based on the URL, something like this:
```dart
final url = pnCustomData['dynamicLink'];
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getLink(url);
```

## Current behavior
Right now I can get the Dynamic Link data ONLY IF the user opened such a link from another app using:
```dart
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.retrieveDynamicLink();
```

**Comment by kroikie** [comment]
@IonelLupu

The issue at https://github.com/flutter/flutter/issues/36056 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue; I'm going to close this issue in favour of trying the latest release.
