### ISSUE TITLE
[📚] Overview: Overriding Native SDK Versions

### ISSUE THREAD

**Issue by Loris156** [FirebaseExtended/flutterfire#3564]
I tried to change the native Firebase SDK version for my Android app because I needed an important bug fix. The documentation says I should add

```
project.ext {
  set('FlutterFire', [
    FirebaseSDKVersion: 'xxx'
  ])
}
```
to the `/android/app/build.gradle` file. This didn't work and the old version was still in use. I tried adding these lines to `/android/build.gradle` and it worked this time.

So I think the documentation must be changed and show the correct `build.gradle` file.

**Comment by red42** [comment]
Just wanted to link #3554 - same issue, but different solution/workaround. Either editing `/android/build.gradle` or changing `project.ext` to `rootProject.ext` will work.
