### ISSUE TITLE
Send verification email with ActionCodeSettings failed in iOS

### ISSUE THREAD

**Issue by maple76** [FirebaseExtended/flutterfire#3571]
Flutter auth api call: Future<void> sendEmailVerification([ActionCodeSettings actionCodeSettings]) did not work for iOS.

It works for Android, from https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java

Tasks.await(firebaseUser.sendEmailVerification(getActionCodeSettings(actionCodeSettings))); will generate dynamic link for verification link. However it did not implement for iOS: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m

```objc
  [currentUser sendEmailVerificationWithCompletion:^(NSError *_Nullable error) {
    if (error != nil) {
      result.error(nil, nil, nil, error);
    } else {
      result.success(nil);
    }
  }];
```

It only send regular email without similar call for android, instead it should call api: 

```objc
- (void)sendEmailVerificationWithActionCodeSettings:
            (nonnull FIRActionCodeSettings *)actionCodeSettings
                                         completion:
                                             (nullable void (^)(
                                                 NSError *_Nullable))completion;
```

It seems to me that the feature did not implement in iOS. Is that correct?

Thanks,

**Comment by darshankawar** [comment]
Hi @maple76,
According to [this](https://github.com/FirebaseExtended/flutterfire/issues/221) issue, the feature was added in latest release of firebase_auth plugin.
Can you switch to latest master and see if it's there or missing still ?
Thanks.

**Comment by maple76** [comment]
Thanks @darshankawar 
I think it's still in master, you can check the implementation. From the code snippet below (from master), iOS still not sends email with ActionCodeSettings. Note it's implemented for android and I can verify that. BTW, I am using:   firebase_auth: ^0.18.0+1.

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m

////////////////////
- (void)userSendEmailVerification:(id)arguments
             withMethodCallResult:(FLTFirebaseMethodCallResult *)result {
  FIRAuth *auth = [self getFIRAuthFromArguments:arguments];
  FIRUser *currentUser = auth.currentUser;
  if (currentUser == nil) {
    result.error(kErrCodeNoCurrentUser, kErrMsgNoCurrentUser, nil, nil);
    return;
  }

  [currentUser sendEmailVerificationWithCompletion:^(NSError *_Nullable error) {
    if (error != nil) {
      result.error(nil, nil, nil, error);
    } else {
      result.success(nil);
    }
  }];
}
////////////////////////

**Comment by MATTYGILO** [comment]
I am having the same issue and my users are having problems i really need this fixed

**Comment by MATTYGILO** [comment]
I am on   firebase_auth: ^0.18.0+1 and I am still facing this issue. It seems that only emails initially send verification link from android device work from ios

**Comment by maple76** [comment]
any update?
