### ISSUE TITLE
🐛 [firebase_crashlytics] 0.2.0-dev.5's requirement of stack_trace 1.9.5 makes plugin require Flutter 1.20

### ISSUE THREAD

**Issue by Moncader** [FirebaseExtended/flutterfire#3577]
## Bug report

firebase_crashyltics officially supports Flutter 1.12.13+hotfix.5 or higher.
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml#L35

Recently there was a dependancy on stack_trace package upgraded to 1.9.5.
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml#L22

However, the official flutter_test packages from your current flutter install also has a dependancy on stack_trace.

I use Flutter 1.17 and it requires 1.9.3 and therefore you get this conflict on pub get

`Because every version of flutter_test from sdk depends on stack_trace 1.9.3 and firebase_crashlytics >=0.2.0-dev.1 depends on stack_trace ^1.9.5, flutter_test from sdk is incompatible with firebase_crashlytics >=0.2.0-dev.1.`

Therefore it's not currently possible to use this plugin on anything but the latest stable version of Flutter.

Either we need to upgrade the dependancy on Flutter to 1.20, or, preferably, relax the version requirements on stack_trace.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.6 19G2021, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (1 available)
```

</details>

**Comment by TahaTesser** [comment]
Hi @Moncader 
I see there's an open issue addressing the case you described. https://github.com/FirebaseExtended/flutterfire/issues/3503
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
