### ISSUE TITLE
🐛 firebase_dynamic_links shows clipboard banner every launch on iOS 14.

### ISSUE THREAD

**Issue by m-j-g** [FirebaseExtended/flutterfire#3586]
The issue is discussed here:
https://github.com/firebase/firebase-ios-sdk/issues/5893

The problem for the flutter plugin is that it seems we can't access version 6.28.0 and so we can't set the property created in that version to fix the issue:
`To disable pasteboard access, set the Info.plist property FirebaseDeepLinkPasteboardRetrievalEnabled to false.`

Is there anyways we can get a build that uses a more recent version?

**Comment by darshankawar** [comment]
Hi @m-j-g,
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks,

**Comment by m-j-g** [comment]
Just add dynamic_links to a new project and run it on iOS 14.

**Comment by droidpl** [comment]
I have the same issue. To fix this, the property `FirebaseDeepLinkPasteboardRetrievalEnabled` was added into the dynamic links library in [6.28.0](https://firebase.google.com/support/release-notes/ios#version_6280_-_july_14_2020), however the current version of the SDK used is the 6.26.0, thus the property doesn't work. Would it be a possibility to upgrade the version?

**Comment by billymahmood** [comment]
Hi guys,


Is there any update on this?

**Comment by m-j-g** [comment]
@billymahmood 

I looked into it for a week and couldn't find a solution.  I ended up having to completely remove dynamic links from my app (which is in production).  I had to make a tough decision between the feature that required dynamic links and with showing a warning to the user every time they launched the app.  Obviously, you can't have a credible app with a warning from the OS showing up every time your app starts.

**Comment by m-j-g** [comment]
Looks like this was finally updated this week.  Seems to be working properly.
