### ISSUE TITLE
Could not run flutter app on iOS after installing Firebase services

### ISSUE THREAD

**Issue by TagidickTagidick** [FirebaseExtended/flutterfire#3590]
## Bug report

**Describe the bug**
In the new version of Xcode (Xcode 12.0) after adding firebase services in my flutter app it writes that Xcode build is done and nothing happens.

### Steps to reproduce

1. Create a flutter app.
2. Add firebase services for iOS to your flutter app (I added GoogleServices.plist, initialized pod with pod 'Firebase/Analytics', configured firebase in AppDelegate and run pod install).
3. Run the project.

### Expected behavior

App is launching, wow.

---

## Additional context

It worked fine until I added firebase services.
Could not launch my app from simulator even if I tap on it.

![Запись-экрана-2020-09-19-в-14 22 53](https://user-images.githubusercontent.com/49733518/93666083-e225a880-fa83-11ea-9c36-7860181951c2.gif)

Also I have this issue by running pod install. Maybe resolving it will help
<details><summary>Click To Expand</summary>

```

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

```

</details>

It's my first time installing firebase on iOS. So, maybe I'm doing something wrong?

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale ru-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.4.2 [collection]
- boolean_selector 2.0.0 [source_span string_scanner]
- characters 1.0.0
- charcode 1.1.3
- clock 1.0.1 [meta]
- collection 1.14.13
- fake_async 1.1.0 [clock collection]
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- path 1.7.0
- sky_engine 0.0.99
- source_span 1.7.0 [charcode collection meta path term_glyph]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- string_scanner 1.0.5 [charcode meta source_span]
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.2.0 [collection]
- vector_math 2.0.8
```

</details>

---

**Comment by knissophiliac** [comment]
Which iOS version is your simulator using? I'm having a similar problem with my released iOS app. It launches with white screen in iOS 12

**Comment by TagidickTagidick** [comment]
> Which iOS version is your simulator using? I'm having a similar problem with my released iOS app. It launches with white screen in iOS 12

It uses the newest version of iOS (14.0)

**Comment by knissophiliac** [comment]
Did you followed this step? [https://firebase.flutter.dev/docs/overview#initializing-flutterfire](url)

**Comment by TagidickTagidick** [comment]
> Did you follow this step? https://firebase.flutter.dev/docs/overview#initializing-flutterfire

I tried, but it doesn't work. This is my Podfile

```

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '6.30.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.26.0'

end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

```

Maybe I'm doing something wrong?

**Comment by darshankawar** [comment]
Hi @TagidickTagidick 
Can you try [this](https://github.com/flutter/flutter/issues/66222#issuecomment-695802808) solution and see if it works for you ?
Thanks.
