### ISSUE TITLE
[firebase_auth][📚] signOut complete flow dart docs incomplete

### ISSUE THREAD

**Issue by freitzzz** [FirebaseExtended/flutterfire#3599]
The `signOut` method dart documentation states the following:

```
Signs out the current user.

If successful, it also signs the user in into the app and updates any authStateChanges, idTokenChanges or userChanges 
stream listeners.
```

It depicts that stream listeners will get notified if the sign out operation is successful. However it does not say what happens or which code is thrown if the operation is not successful. What happens if the operation is not successful?

**Comment by Ehesp** [comment]
If it's not successful an error will be thrown and the operation won't have completed, thus not signing anyone out. Can't say what error will be thrown, since it could be one from internals.

**Comment by freitzzz** [comment]
> If it's not successful an error will be thrown and the operation won't have completed, thus not signing anyone out. Can't say what error will be thrown, since it could be one from internals.

What internal errors are you referencing here?

**Comment by Ehesp** [comment]
Anything the native SDK spits out (e.g. if Firebase was down, or a null pointer exception occurred). These usually come back with an `unknown` code.

**Comment by darshankawar** [comment]
Hi @freitzzz,
Does [this](https://github.com/FirebaseExtended/flutterfire/issues/3599#issuecomment-695961316) and [this](https://github.com/FirebaseExtended/flutterfire/issues/3599#issuecomment-696003341) answer your question ?
Thanks.

**Comment by freitzzz** [comment]
> this

Yes, thank you
