### ISSUE TITLE
Firestore offline query taking upwards of 10 minutes to complete

### ISSUE THREAD

**Issue by aidanstay** [FirebaseExtended/flutterfire#3609]
The first few times I thought this happened I thought that the app had crashed, but apparently it's just taking forever to load in offline mode. Does anyone know how to solve this problem?

The bug occurs in a section of code that runs getDocument in a for loop.

using: 
firebase_core: ^0.5.0
cloud_firestore: ^0.14.0+2
firebase_auth: ^0.18.0+1
google_sign_in: ^4.5.1

problem occurs in iOS simulator and on Android device

**Comment by TahaTesser** [comment]
Hi @aidanstay 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you
