### ISSUE TITLE
[firebase_messaging] getToken not works after call deleteInstanceID() in IOS device

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#362]
I do not need to keep the same registration token. so I'm using deleteInstanceID () on logout. But after calling deleteInstanceID () I no longer get any token with getToken ().  I am using firebaseMessaging.setAutoInitEnabled(true); but still not works .
 I realized that this only happens if I call configure () before. This problem does not occur in the ios emulator and Android device. Only IOS device.
Has anyone had the same problem?

Iphone 6s, IOS 12.3.1
Flutter doctor
```
> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
```

**Comment by kroikie** [comment]
@hebersousa

The issue at https://github.com/flutter/flutter/issues/34636 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @hebersousa
are you still experiencing this issue with the latest version of Flutter and [firebase_messaging](https://pub.dev/packages/firebase_messaging)? 
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by BondarenkoStas** [comment]
Closing the issue in favour of https://github.com/FirebaseExtended/flutterfire/issues/258 to avoid duplication. Please follow it there and upvote.

**Comment by hebersousa** [comment]
> Hi @hebersousa
> are you still experiencing this issue with the latest version of Flutter and [firebase_messaging](https://pub.dev/packages/firebase_messaging)?
> If so can you please provide your `flutter doctor -v`?
> Also, to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Thank you

@iapicca 
I have tested on flutter stable v1.9.1 + hotfix.6 and it works properly.
