### ISSUE TITLE
Firebase admob 0.9.3+4 and  0.10.0-dev.1 not working with firebase_core: ^0.5.0

### ISSUE THREAD

**Issue by Ram121** [FirebaseExtended/flutterfire#3621]
When I import firebase_admob: ^0.9.3+4 with firebase_core: ^0.5.0 it shows following error

Because firebase_admob >=0.9.1 <0.10.0-dev.1 depends on firebase_core ^0.4.2+1 and yourapp depends on firebase_core ^0.5.0, firebase_admob >=0.9.1 <0.10.0-dev.1 is forbidden.

When I import firebase_admob:0.10.0-dev.1 with firebase_core: ^0.5.0 it does not show any error but app force closes immediately after install 

flutter doctor
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

Edit: I am using android studio 4.1 RC3

**Comment by darshankawar** [comment]
Hi @Ram121,
For `firebase_admob: ^0.9.3+4` version, you'll need to use core's `v0.4.5` version. Please see [this](https://github.com/FirebaseExtended/flutterfire/issues/3209#issuecomment-675247334) comment.

Also, when you use the admob's pre-release version, are you initializing `firebase_core` in your main() method ?
Thanks

**Comment by surpriso1997** [comment]
I am having the same issue but in ios. 

 [!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
      In Podfile:
        firebase_admob (from `.symlinks/plugins/firebase_admob/ios`) was resolved to 0.10.0-dev.1, which depends on
          Firebase/CoreOnly (~> 6.26.0)

    None of your spec sources contain a spec satisfying the dependency: `Firebase/CoreOnly (~> 6.26.0)`.

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

I have tried downgrading admob and other firebase plugins version. I do not use firebase_core version directly.

**Comment by Ram121** [comment]
> Hi @Ram121,
> For `firebase_admob: ^0.9.3+4` version, you'll need to use core's `v0.4.5` version. Please see [this](https://github.com/FirebaseExtended/flutterfire/issues/3209#issuecomment-675247334) comment.
> 
> Also, when you use the admob's pre-release version, are you initializing `firebase_core` in your main() method ?
> Thanks
> 

@darshankawar Thanks for the reply
Yes I have initialized firebase core as following 

final Future<FirebaseApp> _initialization = Firebase.initializeApp();

Wrapped material app with future builder

return FutureBuilder( future: _initialization, builder: (context, snapshot) {

About using core 0.4.5, I have read that post but for that I have to downgrade other plugins also

My intent of creating new topic was to register the bug and find out working solution for latest plugins

**Comment by darshankawar** [comment]
@Ram121 There's going to be a new version of `admob` rolling out very soon, that will likely fix this issue, so stay tuned.

**Comment by Ram121** [comment]
> @Ram121 There's going to be a new version of `admob` rolling out very soon, that will likely fix this issue, so stay tuned.
> 
@darshankawar 
Ok, thanks 👍

**Comment by mshahzaib1629** [comment]
Any update on  this issue? I'm working on a production app and deadline is just around the corner, when the update is expected?

**Comment by Ram121** [comment]
> Any update on  this issue? I'm working on a production app and deadline is just around the corner, when the update is expected?

Please check there is updated plugin available 
firebase_admob: ^0.10.0
Most probably this will solve problem but I have not tried yet so not closed the issue

**Comment by Ram121** [comment]
Update : still problem seems there, only adding firebase_admob: ^0.10.0 force closes app on launch with following error

2020-10-01 20:29:13.384 5902-5902/com.techmechdevelopers.garagetech E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.techmechdevelopers.garagetech, PID: 5902
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzyc.attachInfo(com.google.android.gms:play-services-ads-lite@@19.1.0:33)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@19.1.0:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        	... 10 more


Tried the implementation which is working with previous plugins, it is also showing same error

**Comment by Salakar** [comment]
Updating to the latest plugin version is the correct approach and will solve this issue.
