### ISSUE TITLE
Change number on Firebase Phone Auth

### ISSUE THREAD

**Issue by bhanuka96** [FirebaseExtended/flutterfire#3622]
My application has option called change number. (change number feature is user type incorrect number the first time then he can change it after sending OTP) -Just change the text.(not phone authentication number changed).

User changed his number after send otp to the first number. Now, user click verify button(with the second number's otp). User can successfully login to his second number account. but this error message is pop up.

**[firebase_auth/invalid-verification-code] The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user.**

I think the firebase auth plugin tries to verify his first number.

**Comment by bhanuka96** [comment]
I refresh the auth instance on my change tap event. Is it okay please confirm it?

```
      void changeOnPressed() {
        _auth = FirebaseAuth.instance;
      }
```

Now, it's working

**Comment by darshankawar** [comment]
@bhanuka96,
`_auth = FirebaseAuth.instance` will create new firebase auth instance that will take the updated phone number, which is expected.
If this is working at your end and not seeing the issue anymore, you may go ahead and close this issue.
Thanks.

**Comment by bhanuka96** [comment]
@darshankawar this is not working, I deleted my answer

**Comment by TahaTesser** [comment]
Hi @bhanuka96 
Are you still experiencing this issue? Please provide steps to reproduce 

Can you please provide your `flutter doctor -v` your `flutter run --verbose`, your `pubspec.yaml` and a complete reproducible minimal code sample
Thank you
