### ISSUE TITLE
[firebase_crashlytics 0.2.0] [!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_e_7_d.txt Response: 500 

### ISSUE THREAD

**Issue by rash1k** [FirebaseExtended/flutterfire#3624]
When installing the plugin according to the official documentation, the project is not built.

>CocoaPods' output:
↳
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Error output from CocoaPods:
↳

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_e_7_d.txt Response: 500 
<html>
<head>
<title>Fastly error: unknown domain cdn.cocoapods.org</title>
</head>
<body>
<p>Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.</p>
<p>Details: cache-hhn4065-HHN</p></body></html>

Error running pod install
Error launching application on iPhone SE (1st generation). 

> 

## Flutter doctor

<details>
  <summary>Click to expand!</summary>

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale ru)
    • Flutter version 1.20.4
    • Framework revision fba99f6cf9 (8 дней назад), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone SE (1st generation) (mobile) • 9399616A-1A6A-48C8-AFEB-AA7EE00F2274 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
<details>

**Comment by awhitford** [comment]
`cdn.cocoapods.org` is legit; it looks like you had a networking issue accessing it.  Flush your DNS cache and try again?

**Comment by rash1k** [comment]
> `cdn.cocoapods.org` is legit; it looks like you had a networking issue accessing it. Flush your DNS cache and try again?

Thank you very much, the problem is solved for some reason, there was no access, on different local machines.
