### ISSUE TITLE
🐛 [firebase_admob] Keep getting Ad failed to load: 3 while try to display first test interstitial 

### ISSUE THREAD

**Issue by mikron123** [FirebaseExtended/flutterfire#3629]
Trying to display a test ad for the first time, check the Android XML settings.. but I keep getting:

`W/flutter (32272): onAdFailedToLoad: 3
I/Ads     (32272): Ad failed to load : 3`

code:

`await FirebaseAdMob.instance.initialize(appId: "ca-app-pub-XXXXXXX~XXXXXX"); `

    myInterstitial = InterstitialAd(
      adUnitId: InterstitialAd.testAdUnitId, 
      //targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) {
        print("InterstitialAd event is $event");
        if (event == MobileAdEvent.loaded)
          myInterstitial.show();
      },
    );
    
    await myInterstitial.load();

**Comment by darshankawar** [comment]
Hi @mikron123,
Please make sure you've setup the admob correctly as mentioned in the plugin [document](https://pub.dev/packages/firebase_admob). Also visit the official admob [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob/example) to see if you are missing anything.
If problem persists, please provide `flutter doctor -v` along with a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by mikron123** [comment]
I'm already trying for hours - the example works fine, but once I change the namespace to an app that's already in the store, the test ads fails(!) if I just make up a name space - e.g. com.asffafsa.asaa it works! if I take a namespace of my app that's already at the store with ads, the test ads in the project won't event load and fail with code 3.

**Comment by mikron123** [comment]
It doesn't show specifically for a specific app namespace which is directed to children.. HOWEVER the older non flutter version display ads freely in production as we speak... what is it blocked on here?

**Comment by darshankawar** [comment]
@mikron123 There's going to be new version of `admob` rolling out soon that will likely fix the issue. Stay tuned.
Thanks.

**Comment by mikron123** [comment]
> @mikron123 There's going to be new version of `admob` rolling out soon that will likely fix the issue. Stay tuned.
> Thanks.

Thanks for the reply! can you elaborate about the problem?

**Comment by mikron123** [comment]
> @mikron123 There's going to be new version of `admob` rolling out soon that will likely fix the issue. Stay tuned.
> Thanks.

When is it going to be fixed? We have a converted to Flutter version that cannot be released since ads are not showing up at all..
Thanks

**Comment by darshankawar** [comment]
@mikron123 there's new plugin version out. https://pub.dev/packages/firebase_admob/changelog
Please check and see if it works for you.
Thanks.

**Comment by mikron123** [comment]
@darshankawar thanks, I was able to solve it by giving the actual app id, and not the test app id. seems like the test app id only works with projects with namespaces that do not exist yet.

**Comment by darshankawar** [comment]
@mikron123 
Glad to know.
Closing this as resolved. If you disagree, write in comments and I'll reopen.
Thanks.
