### ISSUE TITLE
🐛 Flutter for web: Firebase initialization forces to reveal sensitive data

### ISSUE THREAD

**Issue by kinex** [FirebaseExtended/flutterfire#3632]
## Bug report

Initializing Firebase as instructed [here](https://firebase.flutter.dev/docs/installation/web) reveals sensitive data like API key to public. All this data will be publicly visible: 
```javascript
      var firebaseConfig = {
        apiKey: "...",
        authDomain: "[YOUR_PROJECT].firebaseapp.com",
        databaseURL: "https://[YOUR_PROJECT].firebaseio.com",
        projectId: "[YOUR_PROJECT]",
        storageBucket: "[YOUR_PROJECT].appspot.com",
        messagingSenderId: "...",
        appId: "1:...:web:...",
        measurementId: "G-...",
      };
```
From my understanding at least `apiKey`, `messagingSenderId`, `appId `and `measurementId` are possibly sensitive data that should not be made available publicly.

### Steps to reproduce

1. Create a new Flutter Web app
2. Initialize Firebase following instructions [here ](https://firebase.flutter.dev/docs/installation/web) 
3. Launch the app in a browser
4. Right click browser window and select "View source"
5. All Firebase config data can be seen in the source code.

### Expected behavior

It should be possible to hide Firebase config data.

---

Flutter (Channel beta, 1.22.0-12.1.pre)

**Comment by TahaTesser** [comment]
I can reproduce, it can see all the configuration data is VISIBLE even we build app in release mode `flutter build web` and according to release documentation for web `A release build is both minified and tree shaking has been performed` but HTML data is clearly visible https://flutter.dev/docs/deployment/web and ALL the firebase configuration is visible
