### ISSUE TITLE
🐛 [firebase_admob] Debug version shows testAd, but release version shows a real Ad even on a test device

### ISSUE THREAD

**Issue by xl-hacker** [FirebaseExtended/flutterfire#3638]
## Bug report

1. I have an approved admob account
2. I have added my (Android) device ID to testDevices in MobileAdTargetingInfo.
3. When I load the app in debug mode onto my Android device "flutter run -d <device>", it correctly shows a bannerAd tagged with "test Ad".
4. When I load the app in release mode onto the same device "flutter run -d <device> --release", it shows a regular banner ad without the "test Ad" annotation. The device is the same, the ID is included in testDevices, so not sure why that should happen.

This worries me because I want to test with this device in release mode if possible, but having a real ad there might cause issues with my admob account.

Flutter doctor on master channel below.

### Flutter doctor

flutter doctor -v
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.36, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.22.0-10.0.pre.36 at <location>
    • Framework revision bcfad2068e (3 weeks ago), 2020-09-01 08:34:25 -0400
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at <location>
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = <location>
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • SM A102U (mobile)                   • RF8MC0NVQJE                          • android-arm    • Android 9 (API 28)
    • Android SDK built for x86 (mobile)  • emulator-5554                        • android-x86    • Android 8.0.0 (API 26) (emulator)
    • iPhone SE (2nd generation) (mobile) • 5A4B0C02-87C8-4DFC-806D-A3AACB93242F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)                    • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
