### ISSUE TITLE
Flutter firebase not working on ios

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#364]
When I run flutter with firebase core it fails. 

I have the GoogleService-Info.plist placed in ios/runner folder.

Emulator: Iphone X ios 10
Android studio: 3.3.1
Flutter: 1.5.4-hotfix.2
Flutter doctor: no errors

`
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           107.0s
Configuring the default Firebase app...
6.2.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
6.2.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
6.2.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
6.2.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011104612b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001106daf41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001110bb245 +[NSException raise:format:] + 197
	3   Runner                              0x000000010c599072 +[FIRApp configure] + 562
	4   Runner                              0x000000010ca00d66 -[FLTCloudFirestorePlugin init] + 214
	5   Runner                              0x000000010ca00b64 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 292
	6   Runner                              0x000000010c3dbe89 +[GeneratedPluginRegistrant registerWithRegistry:] + 121
	7   Runner                        <…>

Running with latest versions for firebase 

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.0+5
  cloud_firestore: ^0.12.5
  firebase_auth:  ^0.11.1+6

`

**Comment by workerbee22** [comment]
@kroikie How is this closed? It is still an issue.

**Comment by workerbee22** [comment]
@kroikie Why was this issue immediately closed after moving without fix, workaround or explanation?
