### ISSUE TITLE
🐛 [Firebase Auth] Unable to reset email or password as Firebase site not found.

### ISSUE THREAD

**Issue by MatthewCoetzee412** [FirebaseExtended/flutterfire#3641]
## Bug report

I recently attempted to implement the ability to reset a user's email and password in my Flutter application. It sent the email successfully but shortly after I clicked on the URL link I was met with a "Site Not Found". Multiple options on why this message was being displayed were listed below but they had to do with Firebase Hosting or using a custom domain of which I use neither of them. I viewed multiple Youtube tutorials to see if they ran into similar problems but the link took them to a elegantly formatted website where they were able to reset their email or password.

Below is the error I'm faced with on the site:

![image](https://user-images.githubusercontent.com/42652264/94094605-3633e280-fe20-11ea-8f4d-77eee9765c79.png)

### Steps to reproduce

I'm am not entirely sure how to reproduce this problem as I haven't seen anyone else get this problem.

---

### Expected behavior

It should display an elegant UI where the user is able to reset their email or password.

---

## Additional context

I have activated Firebase hosting, and have the templates setup alongside the correct Flutter code.

---

**Comment by darshankawar** [comment]
Hi @MatthewCoetzee412,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Also you may try to run the plugin's official [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example/lib) and see if you get same error.
Thanks.

**Comment by MatthewCoetzee412** [comment]
###
Flutter Doctor:
---
[√] Flutter (Channel dev, 1.22.0-9.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-ZA)
    • Flutter version 1.22.0-9.0.pre at C:\flutter\flutter
    • Framework revision 7a43175198 (4 weeks ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Matthew Coetzee\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\Matthew Coetzee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • SM A307FN (mobile) • RZ8MC05H2WF • android-arm64 • Android 10 (API 29)

• No issues found!

---

I'm not sure that code is the problem. I think Firebase is the problem as its a Site not found problem.

Below is my Flutter Code:

Reset Email:

```Dart
  Future<void> resetEmailAddress(
      String newEmail, String oldEmail, String password) async {
    var authResult = await _authInstance.signInWithEmailAndPassword(
        email: oldEmail, password: password);
    await authResult.user.updateEmail(newEmail);
    await _instance
        .collection('users')
        .doc(authResult.user.uid)
        .update({'email': newEmail});
  }
```

Reset password:

```Dart
  Future<void> resetPassword(String email) async {
    await _authInstance.sendPasswordResetEmail(email: email);
  }
```

Thanks!
- Matt

**Comment by TahaTesser** [comment]
Hi @MatthewCoetzee412 
Thanks for filing the issue but this is the not created flutterfire itself, emails are sent by firebase itself, `firebase_auth` only triggers it and tells firebase you want to be reset this account. You should be able to face the same  issue even if you firebase on other platforms 

However, just tried it and had no issues
![image](https://user-images.githubusercontent.com/48603081/96582459-f1a14700-12f8-11eb-908e-916e9dc73a86.png)

![image](https://user-images.githubusercontent.com/48603081/96582426-e2ba9480-12f8-11eb-9f09-9935a6a82a59.png)

<details> 
<summary>complete code sample</summary> 

```dart

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            RaisedButton(
              child: Text('Reset password'),
              onPressed: () async {
                await FirebaseAuth.instance
                    .sendPasswordResetEmail(email: 'taha@nevercode.io');
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

</details> 

```
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
```

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
