### ISSUE TITLE
[firebase_auth/invalid-verification-code] On Firebase phone auth

### ISSUE THREAD

**Issue by bhanuka96** [FirebaseExtended/flutterfire#3644]
my app is crashed when the user types the wrong pin code.

`[firebase_auth/invalid-verification-code] The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user.`

**Comment by Ehesp** [comment]
This is expected behaviour, you need to catch this error and handle it in the UI yourself.

**Comment by bhanuka96** [comment]
> This is expected behaviour, you need to catch this error and handle it in the UI yourself.

@Ehesp I already caught. but app is crashed. please don't close a bug without any solutions

**Comment by Ehesp** [comment]
Please follow the issue template with full reproduction code and someone will be able to help.

**Comment by bhanuka96** [comment]
@Ehesp 😂
