### ISSUE TITLE
🐛 [firebase_dynamic_links] Missing my dynamic link flow from play store

### ISSUE THREAD

**Issue by Ranjithsp6** [FirebaseExtended/flutterfire#3647]
I am using a firebase dynamic link with the query parameter in it. It's working fine when the app is already installed, I can retrieve the link and parameters passed. But when the app is not already installed, the link redirects to the play store then if the user hits the open button from the store, it launches the app and showing link and parameters are null.

Kindly guide me through this issue!

**Comment by darshankawar** [comment]
@Ranjithsp6 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by piyushrathodIn** [comment]
I am having the same issue while using Google Chrome browser.

**Comment by piyushrathodIn** [comment]
Hi @Ranjithsp6  could you try to update Google Chrome on your Android device? I had same issue but after updating to the latest version, the issue has been disappear now the link works with both combination i.e. Chrome is running in the background and Chrome is not started at all.
Please inform me if this works for you.
