### ISSUE TITLE
🐛 [Cloud Messaging (firebase_messaging)] IOS firebase connection stuck on 'Run your app to verify installation'

### ISSUE THREAD

**Issue by kartercs** [FirebaseExtended/flutterfire#3649]
Hello,

I'm working on a Flutter application on both iOS and Android, for this I need to use notifications and I made it work on android successfully.

I now wanted to do the same for iOS and I have problems connecting the app to the firebase backend, I followed step by step the Tutorial on the [firebase_messaging pub.dev](https://pub.dev/packages/firebase_messaging) but I can't get it to connect on the 5th and last task on the the firebase backend. It's stuck on 'Run your app to verify installation, you might need to uninstall and reinstall it again'.

![Sans titre](https://user-images.githubusercontent.com/19304535/94116904-e2d78980-fe4b-11ea-9d3c-d8f3cdbf72a8.png)

Of course I downloaded the GoogleService-Info.plist and put it next to info.plist and I've added the FirebaseAppDelegateProxyEnabled key as well as this code in the AppDelegate :

```swift
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

I also made sure to activate the push notifications and background modes capabilities on Xcode and created and uploaded my apn auth key  : 

![APNKey](https://user-images.githubusercontent.com/19304535/94116372-3eedde00-fe4b-11ea-88dc-21968aa0a607.png)

and i tried to flutter clean and flutter run again after all of this

But somehow it still doesn't work at all and stuck on the same message, yet what  I really don't understand is taht I can use the firebase tool to get the user Token for example

Here is my flutter doctor :  

![pqer4](https://user-images.githubusercontent.com/19304535/94116612-8ffdd200-fe4b-11ea-85aa-5a543c572598.png)

Some tells me to bypass this but if i do i can't get the notifications on the iphone which is central on my app.

Can anyone help me with this? I found a lot of issues for this but no clear answer have been given yet. I don't have any error message or really anything more that could help identify what's wrong there.

Thanks a lot in advance

**Comment by darshankawar** [comment]
@kartercs,
Did you try by running the app on a device and then uninstall it manually and run it again while you see that message ? You might have to do that couple of times until the backend recognises the integration with iOS.

**Comment by kartercs** [comment]
Thanks for your answer @darshankawar yes from yesterday when you posted i must have tried that like 5-6 times, i tried again this morning but still nothing happens on the firebase end.

**Comment by kartercs** [comment]
Do I need to have a mobile connection on the iphone? Like a sim card ? I already have the wifi and since you can do it on emulator it must not be needed right?

**Comment by TahaTesser** [comment]
Hi @kartercs 
Uninstall your app and make sure you're connected to a stable internet connection and run the app again, this is not to Flutterfire or `cloud_messaging`. Since it's firebase console related 

Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you
