### ISSUE TITLE
[firebase_crashlytics] which version of Google Services plugin?

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#365]
The readme doc for firebase_crashlytics says add:
  classpath 'com.google.gms:google-services:4.2.0'
but on the Firebase Flutter setup page:
  https://firebase.google.com/docs/flutter/setup
it says:
  Note: Flutter is currently compatible with version 3.2.1 of the Google Services plugin.

Which is correct? ...and does it matter?

Thanks
-Gary

**Comment by kroikie** [comment]
@ghunter99

The issue at https://github.com/flutter/flutter/issues/34357 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @ghunter99
are you still experiencing this issue with the latest version of Flutter and [firebase_crashlytics](https://pub.dev/packages/firebase_crashlytics)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
