### ISSUE TITLE
On Launch triggered multiple times

### ISSUE THREAD

**Issue by joharputr** [FirebaseExtended/flutterfire#3656]
```
firebaseMessaging.configure(
        onMessage: (Map<String, dynamic> message) async {
          final notification = message['data'];
          print("onMessage");
          await Navigator.of(context, rootNavigator: true).push(
              MaterialPageRoute(builder: (context) => Rating('onMessage')));
          print('cek onMessage body  = ${notification['name']} raw = $message');
        },
        onResume: (Map<String, dynamic> message) async {
          await print('cek onResume firebase = $message');
          await Navigator.of(context, rootNavigator: true).push(
              MaterialPageRoute(builder: (context) => Rating('onResume')));
        },
        onLaunch: (Map<String, dynamic> message) async {
          if (!_isConfigured) {
            print("onLaunch");
            print('cek onLaunch firebase = $message');
            await Navigator.of(context, rootNavigator: true).push(
                MaterialPageRoute(builder: (context) => Rating('onLaunch')));

            _isConfigured = true;
          }
        },
        onBackgroundMessage: myBackgroundMessageHandler);
```

on launch triggered again when we close the application with back button

**Comment by TahaTesser** [comment]
Hi @joharputr 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by danielwalczak** [comment]
I had the same issue, but I noticed that I trigger `configure` twice, I fix that and it's working fine.

**Comment by joharputr** [comment]
hi @TahaTesser 
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale id-ID)
    • Flutter version 1.20.4 at D:\master\flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\master\sdk_android\commandlinetools-win-6514223_latest
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\master\sdk_android\commandlinetools-win-6514223_latest
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • RMX1821 (mobile) • Y5ZD8LMFHYF6I7JF • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by joharputr** [comment]
@danielwalczak you call configure twice in init state?

**Comment by danielwalczak** [comment]
Yes I have it in initState, but the way I setup splash screen -> home screen redirect did trigger `configure` twice, When I fixed this issue, everything was ok. I thought you might have similar issue.

**Comment by TahaTesser** [comment]
Hi @joharputr 
Can you please provide complete `flutter run --verbose` with onunch trigger multiple times e and a complete reproducible minimal code sample
Thank you
