### ISSUE TITLE
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility. Running Gradle task 'assembleAarRelease'... Building plugin firebase_core...

### ISSUE THREAD

**Issue by Prashant4900** [FirebaseExtended/flutterfire#3678]
**I will clone a flutter project from GitHub when I tried to lunch it's it's will show error like this** ![IMG-20200928-WA0098.jpg](https://user-images.githubusercontent.com/62440911/94433288-b4441080-01b5-11eb-9af2-a6e1f1a68a1a.jpg)![IMG-20200928-WA0097.jpg](https://user-images.githubusercontent.com/62440911/94433306-bad28800-01b5-11eb-8376-9f518e18c36d.jpg)

**But when updated all the package then it's will show this error** ![IMG-20200928-WA0099.jpg](https://user-images.githubusercontent.com/62440911/94433438-f3726180-01b5-11eb-9d74-f7b8ebbe7a5d.jpg)

#pub.yaml

`
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_splash: ^1.0.0
  provider: ^4.3.2+2
  flutter_svg: ^0.18.0
  geolocator: ^6.0.0+4
  pinput: ^0.2.5
  http: ^0.12.2
  flutter_progress_hud: ^1.0.2
  shared_preferences: ^0.5.12
  cached_network_image: ^2.3.2
  google_sign_in: ^4.5.4
  webview_flutter: ^0.3.24
  random_string: ^2.1.0
  url_launcher: ^5.7.2
  date_time_format: ^0.1.1
  autocomplete_textfield: ^1.7.3
  loading: ^1.0.2
  progress_dialog: ^1.2.4
  expand_widget: ^1.0.0+2
  firebase_messaging: ^7.0.0
  flutter_launcher_icons: ^0.7.3
  carousel_pro: ^1.0.0
  firebase_core: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assests/doorakart_icon.png"

`
#Flutter Doctor
`

#Flutter Doctor
C:\Src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)
    • Flutter version 1.20.4 at C:\Src\flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\prash\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\prash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0`

Flutter Run
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     G:\Test Projects\College\d_project\android\Projects\College\d_project\android\app\src\main\AndroidManifest.xml:12:5-39:19: AAPT: error: resource mipmap/launcher_icon (aka aditya.raj.d_project:mipmap/launcher_icon) not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin firebase_core...

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'firebase_core'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Exception: The plugin firebase_core could not be built due to the issue above.

`
gradel.properties
`android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
`
build.gradel
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId ""
        minSdkVersion 21
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("key.jks")
            storePassword "doorakart"
            keyAlias "key"
            keyPassword "doorakart"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}

apply plugin: 'com.google.gms.google-services'
`

**Comment by darshankawar** [comment]
@Prashant4900 
This doesn't seem to be an issue with Firebase, but more of a Flutter issue which has a separate repo for tracking. Please open this issue here : https://github.com/flutter/flutter/issues.
Closing from here.

**Comment by Prashant4900** [comment]
> @Prashant4900 
> This doesn't seem to be an issue with Firebase, but more of a Flutter issue which has a separate repo for tracking. Please open this issue here : https://github.com/flutter/flutter/issues.
> Closing from here.

Ok thanks
