### ISSUE TITLE
🐛 [firebase_auth] iOS doesn't return `quotaExceeded` error

### ISSUE THREAD

**Issue by DamianW93** [FirebaseExtended/flutterfire#3680]
## Bug report

When a user exceeds the maximum number of phone verification requests he gets `verifyPhoneNumberError ` instead of `quotaExceeded`.

### Steps to reproduce

1. Call `verifyPhoneNumber` multiple times.
2. Phone number is blocked due to to many requests.
4. Android app gets 'quotaExceeded' error and an iOS app gets `verifyPhoneNumber`.

### Expected behavior

Both platforms should get the same error, described what happened, which is `quotaExceeded` error.

---

### Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.2)
[✓] Connected device (1 available)

• No issues found!
```
---

### Flutter dependencies

```
firebase_auth: 0.16.1
```
---

**Comment by darshankawar** [comment]
@DamianW93 
The latest and re-worked plugin version is `^0.18.1`. Can you upgrade to latest and try again to see if it works for you ?
Thanks.
