### ISSUE TITLE
Cant find changelog for Crashlytics 0.2.0

### ISSUE THREAD

**Issue by ajain-bst** [FirebaseExtended/flutterfire#3681]
Where can I find release notes or change log for different versions of the crashlytics plugin?

I tried asking this on the discussions tab but got no response:
https://github.com/FirebaseExtended/flutterfire/discussions/3418

**Comment by darshankawar** [comment]
@ajain-bst 
Did you check `changelog` section of the plugin ?
https://pub.dev/packages/firebase_crashlytics/changelog

**Comment by ajain-bst** [comment]
Thank you Darshan. The changelog led me to the migration guide is what I was really looking for in the first place.
https://firebase.flutter.dev/docs/migration

Closing this issue. Thank you for the response Darshan.
