### ISSUE TITLE
Flutter firebase_auth signinwithredirect() Microsoft

### ISSUE THREAD

**Issue by bobosette** [FirebaseExtended/flutterfire#3687]
Hi everybody. I'm trying to set a login with microsoft page with Flutter web and firebase_auth.

I'm using 
`FirebaseAuth.instance.signInWithRedirect(provider);`

and the provider is defined like this 
`OAuthProvider provider = new OAuthProvider('microsoft.com'); `

When I run the example I get this error
`[firebase_auth/operation-not-allowed] The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase     
console, under the sign-in method tab of the Auth section.`

but on my console Microsoft sign-in method is already setted up.

How can I fix this??

Thanks

**Comment by darshankawar** [comment]
@bobosette 
Have you configured the redirect URL at `microsoft` developer settings ?
Also, the latest FlutterFire social authentication [guide](https://firebase.flutter.dev/docs/auth/social) doesn't seem to have an example of how to use `signInWithRedirect()` method or other signIn methods for Microsoft login, so not sure if it's possible / supported on web yet.
Thanks.

**Comment by bobosette** [comment]
Yes. I've configured the redirect url. I saw the documentation, there's a
plug in for every type of authentication except Microsoft, so I think that
for now it isn't supported. I though I could implemented in another way but
it's tough

Il giorno gio 1 ott 2020 alle ore 12:17 darshankawar <
notifications@github.com> ha scritto:

**Comment by russellwheatley** [comment]
At the moment, microsoft is not supported on `firebase_auth`. We already have a ticket tracking this: https://github.com/FirebaseExtended/flutterfire/issues/7057 so I'm going to close this in favour of directing people to that ticket. Thanks.
