### ISSUE TITLE
🐛 [firebase_auth] Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#3695]
I clicked to Debug my App on IntelliJ IDEA, it deployed on an Android AVD and I got this crash:

```
I/BiChannelGoogleApi(18287): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@f9314ee
D/FirebaseAuth(18287): Notifying id token listeners about user ( xxxxxxxxxxxxxxxxxxxxxxxx ).
D/FirebaseAuth(18287): Notifying id token listeners about user ( xxxxxxxxxxxxxxxxxxxxxxxx ).
W/Firestore(18287): (21.4.3) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.
```

(I removed the user id and redacted it as `xxxxxxxxxxxxxxxxxxxxxxxx`).

The error message says there was an exception due to a token change, I have no idea what piece of code triggered this as the App just crashed and I couldn't get any insights. Also I can't replicate it again.

There's nothing on crashlytics, which disturbs me a lot because I have:

```dart
FlutterError.onError = Crashlytics.instance.recordFlutterError;
```

And 

```dart
runZoned(
    () => runApp(ItineratyApp()),
    onError: Crashlytics.instance.recordError,
    zoneSpecification: ZoneSpecification(
      print: (self, parent, zone, message) {
        if (isDebug) { // we only print in a debug build.
          parent.print(zone, message);
        }
      },
    ),
  );
```

So any errors should be dispatched to Crashlytics no matter what. Maybe the error was on the Android plugin side and the Crashlytics plugin won't catch those?

It's really uncomfortable to think that users might be getting crashes without we even knowing.

I am using the latest version of the `firebase_auth` plugin: `^0.18.0+1`, but didn't update yet `firebase_crashlytics: ^0.1.4+1`.

**Comment by dackers86** [comment]
Hi @feinstein 

This is difficult to debug without an example project to run through. Do you have an example we could use in the meantime?

Could this be a build error on the Flutter side.


Also, could you try running the following and returning any input?

`flutter doctor`

Then retry with

`flutter clean`
`flutter run` -- with your android device

Thnaks

**Comment by feinstein** [comment]
Hi @dackers86 

> This is difficult to debug without an example project to run through. Do you have an example we could use in the meantime?

Unfortunately I really can't reproduce this. Reading the error message I think something happen with the token at the server side and the library couldn't handle it, but I have no idea on how to replicate it.

>Could this be a build error on the Flutter side.

I don't think so, the App launched fine, I didn't get any build errors and once I built it again things worked just fine (due to a new Token I think).

`flutter doctor`:

[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.48.2)
[√] Connected device (1 available)

• No issues found!


The error only appeared once, so I guess there's no point in `flutter clean` `flutter run`.

Issue #2187 seems to be related, but @Ehesp closed the referenced issue at the end saying it was fixed on the latest version. Since it's locked I can't comment there, so I opened a new one.

**Comment by Ehesp** [comment]
Is this happening on prod builds? I have some vague memories of the SHA-1 needing to be added (could be totally wrong).

**Comment by feinstein** [comment]
I have only seen this problem once.

**Comment by dackers86** [comment]
Seems very similar to https://github.com/FirebaseExtended/flutterfire/issues/2699.

Some time will needed to replicate as this difficult to reproduce.

**Comment by flutterfrank** [comment]
I had the same error message two times but the app did not crash.
W/Firestore( 3529): (21.4.3) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.
[....]
W/Firestore( 3529): (21.4.3) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.

**Comment by feinstein** [comment]
Do you have some sort of "catch all" for exceptions?

**Comment by flutterfrank** [comment]
try{
[...]
} catch (e) {
        print( '[...]' + e.toString());
}

I do not use crashlytics and I can not remember, that I saw a print in debug console.

**Comment by feinstein** [comment]
I use crashlytics and it's supposed to catch all the uncatched exceptions that bubble-up (that's what I meant by a "catch all").

**Comment by shinriyo** [comment]
[FirestoreCallCredentials]: Failed to get token: flutter

what is this? google's bug?

**Comment by shinriyo** [comment]
firebase_auth: ^0.18.1+2

**Comment by russellwheatley** [comment]
> I had the same error message two times but the app did not crash. W/Firestore( 3529): (21.4.3) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change. [....] W/Firestore( 3529): (21.4.3) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.

These are warnings, not errors which is why it didn't crash. 

Crashlytics has gone through some major updates since this issue was raised, please follow the [Crashlytics example app setup](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart#L24-L31) for the recommended way to catch errors.
