### ISSUE TITLE
[Android Installation📚] Android package name

### ISSUE THREAD

**Issue by Akora-IngDKB** [FirebaseExtended/flutterfire#3698]
In the docs, it states:

> The "Android package name" must match your local project's package name that was created when you started the Flutter project. The current package name can be found in the manifest tag within the project's /android/app/src/main/AndroidManifest.xml file.

I set up a project whose package name (in the manifest) was different from the application id (in the module build.gradle).

Following the docs, I used the package name and build failed as the package name wasn't found in my firebase console.

I switched and used the application id in the `app/build.gradle` and it worked.

In the official firebase android installation [guide](https://firebase.google.com/docs/android/setup#register-app), it mentions:
> Find your app's package name in your module (app-level) Gradle file, usually app/build.gradle (example package name: com.yourcompany.yourproject).

**Comment by dackers86** [comment]
HI @Akora-IngDKB 

Thanks for posting this issue and the associated PR. 

In your project both `/android/app/src/main/AndroidManifest.xml` and `app/build.gradle` should contain the same value.

Is there a reason why your example would contain a different value for the application id?


This could be an edge case as normally the `/android/app/src/main/AndroidManifest.xml` would be sufficient?

**Comment by Akora-IngDKB** [comment]
I personally encountered this when working collaborating in a project. The developer who started the project didn't specify the `--org` when creating it, thus the default package name was `com.example.project_name`.

When integrating Firebase, I needed to use the package name that will be used in production instead.
Changing just the `applicationId` in the `app/buiid.gradle` is enough for Firebase to work so I didn't have to change that in the manifest as it will cause errors in the Kotlin codes.


Also, the official Firebase Guide mentions that in the `app/build.gradle` instead of that in the `AndroidManifest.xml`.
I think the FlutterFire docs should also follow suit for consistency.

**Comment by dackers86** [comment]
Thanks fore explanation @Akora-IngDKB .You're correct. 

Tested this locally and it all seems ok. Approval added to the PR.
