### ISSUE TITLE
The RTDB increment sample can now use the increment() operation

### ISSUE THREAD

**Issue by puf** [FirebaseExtended/flutterfire#3711]
https://github.com/FirebaseExtended/flutterfire/blob/5f3665b20f030b3e4a759744e5d1f41c7f641f0f/packages/firebase_database/example/lib/main.dart#L100-L118

This example should be updated to use the new `increment()` operation. Since it's also really useful to have an example of a transaction, I'd recommend leaving that code too.

**Comment by LSambo02** [comment]
Hi Frank, What would be the best way to get the new value since it looks like the ```update()``` returns a void()?

**Comment by LSambo02** [comment]
Hi @puf, What would be the best way to get the new value since it looks like the update() returns a void()?

**Comment by rosariopfernandes** [comment]
What if we moved `_messagesRef.push().set(...)` to the event listener attached to `_counterRef`?

https://github.com/FirebaseExtended/flutterfire/blob/5f3665b20f030b3e4a759744e5d1f41c7f641f0f/packages/firebase_database/example/lib/main.dart#L73-L83

**Comment by Salakar** [comment]
The rework of RTDB is scheduled for early next year which includes adding support for Web & macOS as well as an updated example app. I'll make sure this gets addressed in the updated example.

If however we get some time before then I don't see why we can't add some better examples into the example app. We'd also be willing to accept & assist with a PR if someone fancies doing it :)
