### ISSUE TITLE
[📚] Documentation typo in example

### ISSUE THREAD

**Issue by Bobleyl** [FirebaseExtended/flutterfire#3714]
In the documentation for FlutterFire->Firestore->Usage->DocumentQuery there is a bad example where it uses the deprecated reference for "document".  It should instead read "doc".

**Comment by lordvins226** [comment]
Can you provide the link?

**Comment by diamondlee7** [comment]
> Can you provide the link?

@Bobleyl I have begun work on this issue.

**Comment by GAyan17** [comment]
I want to work on this issue can you please assign it to me?

**Comment by kasirajr** [comment]
#3724 fixed the and cla is passing
