### ISSUE TITLE
Transfer Google Admob App to Firebase Admob

### ISSUE THREAD

**Issue by ghost** [FirebaseExtended/flutterfire#3719]
`firebase_admob` requires a Firebase App (and therefore Firebase Project) to be registered. But my Android App is registered on the old Google Admob.

- There seems to be no way to transfer my Google Admob App to Firebase Admob.
- I cannot delete my Google Admob App
- I cannot use `firebase_admob` without a Firebase Project.

What do I do?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
