### ISSUE TITLE
firebase_messaging not customizing notification when app is not in foreground

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#372]
I need to group notifications about messages from different users. Firebase push notification is grouping achieved by using `flutter_local_notification` plugin. This is done inside onMessage() callback set up during firebase configuration. But when app is not in foreground this grouping and other customer styling can not be done. I had given `"tag"` field in `notification` section of firebase push notification. This will show only one notification according to the `tag`. But i need to add custom styling also when app not in foreground as like when the app is in foreground. How can i achieve this ?

**Comment by kroikie** [comment]
@Nethram

The issue at https://github.com/flutter/flutter/issues/32484 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @Nethram
are you still experiencing this issue with the latest version of Flutter and [firebase_messaging](https://pub.dev/packages/firebase_messaging)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by antigones** [comment]
I'm having the same issue: I grouped the notifications but when the app is in the background, notifications just arrive as single notifications and the grouping is not applied.
This is flutter doctor -v output:

[√] Flutter (Channel master, v1.18.1-pre.9, on Microsoft Windows [Versione 10.0.17763.1098], locale it-IT)
    • Flutter version 1.18.1-pre.9 at D:\flutter
    • Framework revision f9c58bea49 (8 hours ago), 2020-04-04 21:31:55 -0700
    • Engine revision cb6fc30534
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 80ae6ed91d)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

Here is a [link ](https://github.com/antigones/flutter_fcm_notifications)of my source code.
In the same repository you will find screenshots of the issue.

**Comment by antigones** [comment]
I filed a new issue as suggested.
