### ISSUE TITLE
[📚][firebase_auth] Send Verification Email does not send code, but sends verification link?

### ISSUE THREAD

**Issue by dshundal94** [FirebaseExtended/flutterfire#3721]
In the FlutterFire documentation, when user is sending a verification email, the documentation shows that Firebase will send a unique code to the email: 
![image](https://user-images.githubusercontent.com/16771047/94772378-54dd3080-036e-11eb-966e-6d8089e0bfb0.png)
I would prefer to use a code, but when I send a verification email, a link is sent instead. Can you update the documentation, to show how a code is sent instead. Currently, in the firebase console, the email template for verification email is still showing a verification link:
![tempsnip](https://user-images.githubusercontent.com/16771047/94772435-76d6b300-036e-11eb-9408-424e8094c1aa.png)

**Comment by Akora-IngDKB** [comment]
The code is sent as a parameter (`oobCode`) of the verification link.
Eg. `https://example.firebaseapp.com/__/auth/action?mode=<action>&oobCode=<code>`

**Comment by dshundal94** [comment]
Got it, I misunderstood the documentation and thought it would send something like '123456', a 6 digit code that could be entered and verified within the flutter app.
