### ISSUE TITLE
plugin firebase_auth throws error on _onAuthStageChangedHandler

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#373]
`_onAuthStageChangedHandler()` throws an exception when the `currentUser` is `null` in:

```dart
_authStateChangedControllers[id].add(currentUser);
```

Exception:
```
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(null)
```

<img width="1114" alt="Screen Shot 2019-05-10 at 13 51 07" src="https://user-images.githubusercontent.com/125300/57522185-ae346200-732a-11e9-9396-44c1856fa395.png">

**Comment by kroikie** [comment]
@herkulano

The issue at https://github.com/flutter/flutter/issues/32482 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @herkulano
are you still experiencing this issue with the latest version of Flutter [firebase_auth](https://pub.dev/packages/firebase_auth)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by herkulano** [comment]
I no longer have the issue, I don't know when it stopped, but it was some time ago.

**Comment by iapicca** [comment]
Hi @herkulano 
I'm glad you solved the issue,
thank you for letting me know
