### ISSUE TITLE
[firebase_auth] FirebaseUser.reload() should update the user with the correct info

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#374]
To match the behavior of native SDKs, calling `reload()` on a `FirebaseUser` should update its info -- you shouldn't have to call `currentUser()` again.

See flutter/flutter#32324

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/32431 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by awhitford** [comment]
I am also interested in ensuring that the `reload` triggers an update for [`onAuthStateChanged` ](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/onAuthStateChanged.html) listeners because I have widgets that need to be redrawn when the FirebaseUser is modified.

**Comment by feinstein** [comment]
I made a package to fix this, grab it here: [firebase_user_stream](https://pub.dev/packages/firebase_user_stream) 

In the Readme I explain the issues and how the package fixes them, there are examples and etc, enjoy!

**Comment by Ehesp** [comment]
Since https://github.com/FirebaseExtended/flutterfire/issues/717 has more activity and examples, closing this one in favour.
