### ISSUE TITLE
[📚] Apply plugin errors (crashlytics)

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#3741]
I tried to apply the gradle plugin at the end of the file as the docs say [here](https://firebase.flutter.dev/docs/crashlytics/overview#a-android):

![image](https://user-images.githubusercontent.com/8120472/94867700-1b60ff80-0418-11eb-8778-56674c4da800.png)

But I also followed the original docs [here](https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android#firebase-crashlytics-sdk_8) to improve build times, which shows the plugin has to be applied before. Indeed there's an error if the plugin isn't applied before:

![image](https://user-images.githubusercontent.com/8120472/94867862-69760300-0418-11eb-867b-91277ce1e65a.png)

**Comment by IllogicalTree** [comment]
I have submitted a pull request which should address this issue #3753

**Comment by Salakar** [comment]
Thanks for flagging, this has been fixed in the above linked PR.

**Comment by feinstein** [comment]
It's my pleasure to improve the Flutter experience.
