### ISSUE TITLE
Push notification not received in iOS.

### ISSUE THREAD

**Issue by devduttnetsutra** [FirebaseExtended/flutterfire#3754]
I implemented all the steps given in plugin. And Testing Notification from Firebase Console. Receiving Notification On Android but not in iOS. Permission is granted for push notification.

**Comment by darshankawar** [comment]
@devduttnetsutra 
Please provide `flutter doctor -v`, iOS version. Can you also check if `onLaunch` and `onResume` are getting called while running on iOS ?
Thanks.
