### ISSUE TITLE
firebase_auth onAuthStateChanged doesn't refresh from Firebase

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#376]
I know that the whole point of onAuthStateChanged is to get when a user logs in and out. From my understanding, the FirebaseUser is cached in the device. 
I'm however facing an issue. When I'm using onAuthStateChanged with the Js/Web SDK it catches all changes even those in Firebase. For example deleting/disabling a user, verifying email etc. 
But in Flutter when I delete a user from firebase console or when a user verifies their email it doesn't seem to update. The user has to completely log out and then try to log back in. or use ` reload()` method

**Comment by feinstein** [comment]
I made a package to fix this, grab it here: [firebase_user_stream](https://pub.dev/packages/firebase_user_stream) 

In the Readme I explain the issues and how the package fixes them, there are examples and etc, enjoy!
