### ISSUE TITLE
[📚][firebase_messaging] README.md documentation needs to be modified.

### ISSUE THREAD

**Issue by ainusdev** [FirebaseExtended/flutterfire#3762]
Dear development team.
The document content of firebase_messaging needs some modification.

Among the contents of the iOS-related work description, the following are incorrect.

<key>FirebaseAppDelegateProxyEnabled</key>
<false/>

This should be changed.

<key>FirebaseAppDelegateProxyEnabled</key>
<string>NO</string>

Information related to this can be found at the link below.
https://firebase.google.com/docs/cloud-messaging/ios/client?hl=en

I'm always grateful for using it well.

Thank you.

**Comment by dackers86** [comment]
Hi @ainusdev.

This appears to be optional configuration according to the documentation, Could you provide an example of how you feel this would need to be implemented?

I am assuming that you are referring to our documentation at https://firebase.flutter.dev/docs/messaging/ios-integration?

**Comment by ainusdev** [comment]
Hello.  Thanks for contacting us.  As you say, it is correct to be optional.  But if I set the value to <false/> everything doesn't work.  You must delete the content from the document or change the content with <string>NO</string>.  Thank you.

나의 iPhone에서 보냄

**Comment by dackers86** [comment]
Hi @ainusdev.

Apologies, I'm unable to find a reference to `FirebaseAppDelegateProxyEnabled ` in our documentation.

Happy to review if this reference can be shown.

Thanks!

**Comment by devjeff** [comment]
I have also found an incorrect description of the plugin's behaviour on android when the app is terminated. The description on the table states that a data message is lost in case the app is terminated. This is actually wrong. 

The android system wakes up the app, the plugin creates the flutter background view and calls the onBackgroundMessage callback by passing the message content. This works pretty well, although one should mention in the docs that the headless flutter view used by the onBackgroundMessage callback runs in a different dart isolate and is not initialized the same way as the app's entry point (main method is not called). Thus, one needs to initialize every app component that is required to handle the data message within the onBackgroundMessage callback.

The behaviour is actually the same as in the case where the app is simply in background. The same background flutter view is called in this case.

**Comment by dackers86** [comment]
Hi @devjeff 

Yes that would be great. Please follow https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=good+first+issue%2C+type%3A+documentation&template=---documentation-feedback.md&title=%5B%F0%9F%93%9A%5D+Your+documentation+feedback+title+%28CHANGE+ME%29.

We also accept PRs, if you would like to contribute in that way.

Thanks!

**Comment by devjeff** [comment]
All right, I can create a new issue and a PR for the documentation update.

**Comment by Salakar** [comment]
I can't find any usages of `FirebaseAppDelegateProxyEnabled` in our documentation anymore so I'm going to go ahead and close this issue.
