### ISSUE TITLE
🐛 cloud_firestore DocumentSnapshot.data() not working on iOs

### ISSUE THREAD

**Issue by dekadevelop** [FirebaseExtended/flutterfire#3765]
## Bug report

if I run [MyDocumentSnapshot].data() on android I get the document and I can read its fields.
But if I try the same code on iOs [MyDocumentSnapshot].data() is NULL 

### Steps to reproduce

Get a document in a reference
ref = [DocumentReference];  (es: location/IT/areas/region)
doc = await ref.get();

doc.data() is null on iOs but it has the correct value on Android

**Comment by Ehesp** [comment]
Please follow the issue template.
