### ISSUE TITLE
Expose pubspec.yaml plugin version to plugins for analytics

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#378]
The latest Firebase release included a `registerLibrary` API on `FIRApp` that can be used to register plugins for version analytics.

Exposing the plugin version to plugins will enable Flutterfire plugins to register as versioned third-party libraries with an automatically updated version number.

```
/**
 * Registers a given third-party library with the given version number to be reported for
 * analytics.
 *
 * @param name Name of the library.
 * @param version Version of the library.
 */
+ (void)registerLibrary:(nonnull NSString *)name withVersion:(nonnull NSString *)version;
```

See https://github.com/firebase/firebase-ios-sdk/blob/55814996a1a0d1bc5efdb666ec88278fea57229e/Firebase/Core/Private/FIRAppInternal.h#L142

### Work required

  * [ ] Update Flutter [engine](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L559) to make `FlutterEngineRegistrar` have a public `pluginVersion` String getter and accept plugin version as an argument to `registrarForPlugin`. Plugins will be able to read their version off of the registrar as they register themselves.
  * [ ] Update [flutter_tools](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/plugins.dart) to pass the version string from the pubspec.yaml to `registrarForPlugin` in the `GeneratedPluginRegistrant`.
  * [ ] Decide on a canonical platform name convention, probably something like 'fire-flutter-core' for firebase_core, to match what the other Firebase platforms are doing.
  * [ ] Once the engine and framework changes are widely available, update all Flutterfire plugins to call `registerLibrary` with the provided version.

### Alternative approach

We could hard code the version numbers of plugins into the source code and just update it whenever the plugin version changes. We could write a test script running on Cirrus that ensures this hard coded version stays up to date with what's in pubspec.yaml.

@kroikie

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/32267 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This is now implemented
