### ISSUE TITLE
[📚] firebase_admob 0.10.0+1 - Using native ads (CHANGE ME)

### ISSUE THREAD

**Issue by 123dma** [FirebaseExtended/flutterfire#3780]
I am having a hard time understanding how to implement AdsNatives, the documentation is not clear enough as to the settings that must be made in MainActivity for the natives to work.  

When following the documentation in its entirety, reference errors (such as the one provided below) are found that end up discouraging use.

https://stackoverflow.com/questions/63886478/error-cannot-find-symbol-firebaseadmobplugin-registernativeadfactoryfluttereng

**Comment by nemoryoliver** [comment]
Following...

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
