### ISSUE TITLE
[📚] storage Documentation mentions non existent state property on UploadTask

### ISSUE THREAD

**Issue by crtl** [FirebaseExtended/flutterfire#3783]
In the [documentation for storage upload](https://firebase.flutter.dev/docs/storage/usage/#handling-tasks) the following is written:

> The state property of a snapshot indicates a TaskState. The state can be one of the following values on stream snapshots:
> TaskState.running - Indicates the task is currently running.
> TaskState.paused - Indicates the task is paused.
> TaskState.complete - The task has completed and no more events will be sent.

but in the current plugin version there is no such property.

Plugin version is `4.0.1`.

PS:
While writing this issue I have found more onconsistencies in the docs, maybe they need a complete review.

**Comment by helenaford** [comment]
Good spot, thanks for letting us know. Have pushed up a p/r with fix.
We encourage any feedback and contributions 😃  if you find any other inconsistencies, please share them here or feel free to open a p/r.
