### ISSUE TITLE
[firebase_messaging] Please add, subscribed and unsubscribe with a specific callback, where you can find out if it was done with successes or mistakes.

### ISSUE THREAD

**Issue by Romavic** [FirebaseExtended/flutterfire#3785]
https://github.com/FirebaseExtended/flutterfire/blob/7825d3e55cdcad498278640998a53850ac821229/packages/firebase_messaging/lib/firebase_messaging.dart#L153

https://github.com/FirebaseExtended/flutterfire/blob/7825d3e55cdcad498278640998a53850ac821229/packages/firebase_messaging/lib/firebase_messaging.dart#L158

**Comment by helenaford** [comment]
Hey, not sure about the current version, but in the rework (which is in progress), if they fail an error will be thrown. The behaviour is described in the [native docs](https://firebase.google.com/docs/cloud-messaging/ios/topic-messaging#subscribe_the_client_app_to_a_topic)
`For cases where the subscription cannot be completed, the subscription throws an error that you can catch...`

I believe this way is preferred to see the error from native sdk. Also, keeps in line with the rest of the plugins and the API.

**Comment by Romavic** [comment]
@helenaford thanks for answer me... now i understood.

**Comment by TahaTesser** [comment]
Hi @helenaford
If this is already addressed in rework, can we close this issue?
Thank you
