### ISSUE TITLE
[firebase_remote_config] Setup instructions are only for Android, iOS is missing

### ISSUE THREAD

**Issue by MisterJimson** [FirebaseExtended/flutterfire#3787]
I had opened this issue over a year ago but I guess it was deleted when the repo was moved or when the issues were transferred from the main flutter repo.

The readme for firebase_remote_config: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config has instructions for setting up Android, but not iOS.

**Comment by darshankawar** [comment]
@MisterJimson 
There's similar open issue describing your case, [1134](https://github.com/FirebaseExtended/flutterfire/issues/1134).
Please follow-up there for updates and any questions.
Closing this as duplicate.

**Comment by MisterJimson** [comment]
Ah there it is. Thanks
