### ISSUE TITLE
🐛 [FIREBASE ML VISION Kit] Redirects you to strange Google Corporate page if billing not set up in Flutter

### ISSUE THREAD

**Issue by Bracciata** [FirebaseExtended/flutterfire#3795]
## Bug report

**Describe the bug**
If you do not have a billing setup for cloud image labeling then it prints the following `PlatformException (PlatformException(imageLabelerError, If you haven't set up billing, please go to Firebase console to set up billing: https://firebase.corp.google.com/u/0/project/_/overview?purchaseBillingPlan=true. If you are specifying a debug Api Key override and turned on Api Key restrictions, make sure the restrictions are set up correctly, null, null))`
### Steps to reproduce

1. Run the ML Vision Kit example in flutter
2. After enabling Vision API run the app again and select cloud image labeling from the dropdown in the top right.
3. Error is` PlatformException (PlatformException(imageLabelerError, If you haven't set up billing, please go to Firebase console to set up billing: https://firebase.corp.google.com/u/0/project/_/overview?purchaseBillingPlan=true. If you are specifying a debug Api Key override and turned on Api Key restrictions, make sure the restrictions are set up correctly, null, null))`

### Expected behavior

Expected to link me to the enable billing page for my Firebase project.
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by TahaTesser** [comment]
Hi @Bracciata 
This is one of the requirements  https://cloud.google.com/vision/automl/docs/quickstart for Vision API
Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you
