### ISSUE TITLE
[cloud_firestore] offline mode not working 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#381]
We want to use the Firestore offline-mode.

We tried different versions, all giving other behaviors.

The latest version of this library (0.11.0) is giving the error (while device is in Aeroplane mode) :
     ### **UNAVAILABLE: Unable to resolve host firestore.googleapis.com**

Apparently, the library is not aware that we're in offline mode.

I installed the dependency:
     cloud_firestore: ^0.11.0

In order to create new objects, I'm re-using a generic method that I developed 1 year ago:
```

  _Future<dynamic> createObject(T obj) async {
    final TransactionHandler createTransaction = (Transaction tx) async {
      final DocumentSnapshot ds = await tx.get(_objectCollection.document());

      obj.id = ds.documentID;

      final Map<String, dynamic> data = obj.toMap();

      await tx.set(ds.reference, data);

      return data;
    };

    return Firestore.instance.runTransaction(createTransaction).then((mapData) {
      var objNew = obj.createNew();   

      return objNew.fromMap(mapData);
    }).catchError((error) {
      print('error: $error');
      return null;
    });
  }_
```

**Comment by kroikie** [comment]
@frankps

The issue at https://github.com/flutter/flutter/issues/32193 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @frankps
are you still experiencing this issue with the latest version of Flutter and [cloud_firestore](https://pub.dev/packages/cloud_firestore)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
