### ISSUE TITLE
🐛 [firebase_crashlytics] runZoneGuarded not working in ios

### ISSUE THREAD

**Issue by mehtahardikr** [FirebaseExtended/flutterfire#3815]
## Bug report

**Describe the bug**
When use runZoneGuarded its not catching issue from ios side.

### Steps to reproduce

1. Add firebase_crashlytics 
2. init firebase

```  
runZonedGuarded(() async {
    runApp(MyApp());
  }, (error, stackTrace) {
    FirebaseCrashlytics.instance.recordError(error, stackTrace);
  });
```

### Expected behavior

its should catch error , right now its shows maroon screen with yellow font.  Please find attached.
![Simulator Screen Shot - iPhone XR - 2020-10-08 at 12 30 05](https://user-images.githubusercontent.com/12496655/95460720-ed893700-0992-11eb-8af9-773f32983b8b.png)

For Android its working fine.

and this error also remains same. 
6.26.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.13.6 17G65, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Android Studio (version 4.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details> <summary>Click To Expand</summary>

```
Dart SDK 2.10.0
Flutter SDK 1.22.0

dependencies:
- connectivity 0.4.9+3 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- country_currency_pickers 1.0.1 [flutter]
- cupertino_icons 0.1.3
- firebase_analytics 6.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- http 0.12.2 [http_parser path pedantic]
- intl 0.16.1 [path]
- meta 1.3.0-nullsafety.3
- package_info 0.4.3 [flutter]
- pubnub 2.0.1 [pool dio meta crypto cbor encrypt convert pedantic xml]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- uuid 2.2.2 [crypto convert]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- args 1.6.0
- asn1lib 0.6.5
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- cbor 3.2.0 [typed_data convert meta]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+5 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dio 3.0.10 [http_parser path]
- encrypt 4.0.3 [args asn1lib clock collection crypto pointycastle]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.0 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 1.0.2
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]

```
</details>
---

**Comment by mehtahardikr** [comment]
@dackers86  : i reported for same but no response from them. i am using latest firebase_crashlytics version.` ( ^0.2.1)`
https://github.com/FirebaseExtended/flutterfire/issues/3725

**Comment by TahaTesser** [comment]
Hi @mehtahardikr 
The official example has `runZonedGuarded` included, I tried the issue on ios using `firebase_crashlytics: ^0.2.1+1`,  there is no error
<details> 
<summary>complete code sample</summary> 

```dart
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

// Toggle this to cause an async error to be thrown during initialization
// and to test that runZonedGuarded() catches the error
final _kShouldTestAsyncErrorOnInit = false;

// Toggle this for testing Crashlytics in your app locally.
final _kTestingCrashlytics = true;

main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZonedGuarded(() async {
    runApp(MyApp());
  }, (error, stackTrace) {
    print('runZonedGuarded: Caught error in my root zone.');
    FirebaseCrashlytics.instance.recordError(error, stackTrace);
  });
}

// ignore: public_member_api_docs
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  // Set default `_initialized` and `_error` state to false
  bool _initialized = false;
  bool _error = false;

  void testAsyncErrorOnInit() async {
    Future<void>.delayed(const Duration(seconds: 2), () {
      final List<int> list = <int>[];
      print(list[100]);
    });
  }

  // Define an async function to initialize FlutterFire
  void initializeFlutterFire() async {
    try {
      // Wait for Firebase to initialize and set `_initialized` state to true
      await Firebase.initializeApp();

      if (_kTestingCrashlytics) {
        // Force enable crashlytics collection enabled if we're testing it.
        await FirebaseCrashlytics.instance
            .setCrashlyticsCollectionEnabled(true);
      } else {
        // Else only enable it in non-debug builds.
        // You could additionally extend this to allow users to opt-in.
        await FirebaseCrashlytics.instance
            .setCrashlyticsCollectionEnabled(!kDebugMode);
      }

      // Pass all uncaught errors to Crashlytics.
      Function originalOnError = FlutterError.onError;
      FlutterError.onError = (FlutterErrorDetails errorDetails) async {
        await FirebaseCrashlytics.instance.recordFlutterError(errorDetails);
        // Forward to original handler.
        originalOnError(errorDetails);
      };

      setState(() {
        _initialized = true;
      });
      if (_kShouldTestAsyncErrorOnInit) testAsyncErrorOnInit();
    } catch (e) {
      // Set `_error` state to true if Firebase initialization fails
      print(e);
      setState(() {
        _error = true;
      });
    }
  }

  @override
  void initState() {
    initializeFlutterFire();
    super.initState();
  }

  Widget get appContent {
    if (_error) {
      return Center(child: Text(_error.toString()));
    } else if (!_initialized) {
      return Center(child: Text("Loading"));
    }

    return Column(
      children: <Widget>[
        RaisedButton(
            child: const Text('Key'),
            onPressed: () {
              FirebaseCrashlytics.instance
                  .setCustomKey('example', 'flutterfire');
              _scaffoldKey.currentState.showSnackBar(SnackBar(
                content: Text(
                    'Custom Key "example: flutterfire" has been set \n'
                    'Key will appear in Firebase Console once app has crashed and reopened'),
                duration: Duration(seconds: 5),
              ));
            }),
        RaisedButton(
            child: const Text('Log'),
            onPressed: () {
              FirebaseCrashlytics.instance.log('This is a log example');
              _scaffoldKey.currentState.showSnackBar(SnackBar(
                content: Text(
                    'The message "This is a log example" has been logged \n'
                    'Message will appear in Firebase Console once app has crashed and reopened'),
                duration: Duration(seconds: 5),
              ));
            }),
        RaisedButton(
            child: const Text('Crash'),
            onPressed: () async {
              _scaffoldKey.currentState.showSnackBar(SnackBar(
                content: Text('App will crash is 5 seconds \n'
                    'Please reopen to send data to Crashlytics'),
                duration: Duration(seconds: 5),
              ));

              // Delay crash for 5 seconds
              sleep(const Duration(seconds: 5));

              // Use FirebaseCrashlytics to throw an error. Use this for
              // confirmation that errors are being correctly reported.
              FirebaseCrashlytics.instance.crash();
            }),
        RaisedButton(
            child: const Text('Throw Error'),
            onPressed: () {
              _scaffoldKey.currentState.showSnackBar(SnackBar(
                content: Text('Thrown error has been caught \n'
                    'Please crash and reopen to send data to Crashlytics'),
                duration: Duration(seconds: 5),
              ));

              // Example of thrown error, it will be caught and sent to
              // Crashlytics.
              throw StateError('Uncaught error thrown by app');
            }),
        RaisedButton(
            child: const Text('Async out of bounds'),
            onPressed: () {
              _scaffoldKey.currentState.showSnackBar(SnackBar(
                content: Text(
                    'Uncaught Exception that is handled by second parameter of runZonedGuarded \n'
                    'Please crash and reopen to send data to Crashlytics'),
                duration: Duration(seconds: 5),
              ));

              // // Example of an exception that does not get caught
              // // by `FlutterError.onError` but is caught by
              // // `runZonedGuarded`.
              runZonedGuarded(() {
                Future<void>.delayed(const Duration(seconds: 2), () {
                  final List<int> list = <int>[];
                  print(list[100]);
                });
              }, FirebaseCrashlytics.instance.recordError);
            }),
        RaisedButton(
            child: const Text('Record Error'),
            onPressed: () async {
              try {
                _scaffoldKey.currentState.showSnackBar(SnackBar(
                  content: Text('Recorded Error  \n'
                      'Please crash and reopen to send data to Crashlytics'),
                  duration: Duration(seconds: 5),
                ));
                throw 'error_example';
              } catch (e, s) {
                // "context" will append the word "thrown" in the
                // Crashlytics console.
                // await FirebaseCrashlytics.instance
                //     .recordError(e, s, context: 'as an example');
              }
            }),
      ],
    );
  }

  /// Given a [Widget], wrap and return a [MaterialApp].
  MaterialApp withMaterialApp(Widget body) {
    return MaterialApp(
      home: Scaffold(
        key: _scaffoldKey,
        appBar: AppBar(
          title: const Text('Crashlytics example app'),
        ),
        body: body,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return withMaterialApp(Center(child: appContent));
  }
}

```

</details>

**Comment by mehtahardikr** [comment]
@TahaTesser  : still there is something error.

```
6.26.0 - [Firebase/Crashlytics][I-CLS000000] Failed to remove file /Users/USERA/Library/Developer/CoreSimulator/Devices/DF5EBE13-4FC9-4888-AB3B-1745FE80BCFF/data/Containers/Data/Application/6B1638B6-0873-4529-A633-48AAD09FB8CD/Library/Caches/com.crashlytics.data/io.com.app/v5/reports/active/9de6d6533b084a87bf7bb75a5f8ea5bc: Error Domain=NSCocoaErrorDomain Code=4 "“9de6d6533b084a87bf7bb75a5f8ea5bc” couldn’t be removed." UserInfo={NSFilePath=/Users/USERA/Library/Developer/CoreSimulator/Devices/DF5EBE13-4FC9-4888-AB3B-1745FE80BCFF/data/Containers/Data/Application/6B1638B6-0873-4529-A633-48AAD09FB8CD/Library/Caches/com.crashlytics.data/io.com.app/v5/reports/active/9de6d6533b084a87bf7bb75a5f8ea5bc, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x60000003ab50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by dackers86** [comment]
@mehtahardikr I'm going to assume this is Crashlytics as opposed to runZoneGuarded.

Closing in favour of https://github.com/FirebaseExtended/flutterfire/issues/3725 unless we can show it is a different issue...

**Comment by dackers86** [comment]
Can I also check if this is a migration from Fabric?

I'm wondering if the following would help https://github.com/FirebaseExtended/flutterfire/issues/3918#issuecomment-714863064

**Comment by mehtahardikr** [comment]
@dackers86  : there is no migration from fabric. its fresh added firebase crashlytics.

**Comment by mehtahardikr** [comment]
@dackers86  : you are closing in favor of #3725  , but there is no update on that.

**Comment by dackers86** [comment]
@mehtahardikr I mean as to keep the conversation in one place, please keep an eye out for any updates in referenced issue.
