### ISSUE TITLE
[firebase auth] Error code 39 (QuotaExceeded) message is too vague, shows on blaze plan 

### ISSUE THREAD

**Issue by pohpas** [FirebaseExtended/flutterfire#3817]
Hi!
I get an internal error, code 39 when using calling the verifyphone method of phone sign in. Can you give me any specifics, what causes this error? Is there a list? 
Thanks a lot in advance!

**Comment by markusaksli-nc** [comment]
Hi @pohpas 
Could you please provide the contents of your `pubspec.yaml`, `flutter doctor -v`, and the relevant `flutter run -v` logs of the error?
Thank you

**Comment by haroonkhan9426** [comment]
Getting the same issue.

**Comment by mahmoudsfares** [comment]
same issue

**Comment by mahmoudsfares** [comment]
I had the same problem then I knew what was this about, Error code 39 means that you've created too many credentials in a short period of time, you need to wait for a couple hours then try again and it'll work normally.

**Comment by haroonkhan9426** [comment]
Ohhhh...
Then It should be mentioned in the documentation.

**Comment by ashwalcs** [comment]
It is mentioned in docs
https://firebase.google.com/docs/reference/unity/namespace/firebase/auth
The "AuthError" Enum provides descriptions for all error codes. E.C. 39 is QuotaExceeded.
But is there a way to track the current usage of this quota

**Comment by markusaksli-nc** [comment]
Could any of you please provide the full logs you get for this error?

**Comment by pohpas** [comment]
> Could any of you please provide the full logs you get for this error?

Unfortunately, this error only occurred when I ran the app in production mode with no debugging, sorry.

**Comment by markusaksli-nc** [comment]
Well in any case the error message could probably be improved with at least a reference to the error code enum.

**Comment by ambativamsi** [comment]
few users reporting this error recently.
my project is already in blaze plan.

**Comment by asgaraliyev** [comment]
It is relating to sending too many request to firebase api from same ip address.You need to add your phone number to whitelist in firebase console

**Comment by russellwheatley** [comment]
Hey @pohpas, are you still receiving the same fairly vague error message? I believe that is coming from the native sdk.

**Comment by russellwheatley** [comment]
Given the age and lack of response, I'm going to close this out. Will reopen if there is confirmation this is still an issue.
