### ISSUE TITLE
[📚] [Firebase-auth] : Please provide a complete Streambuilder based example

### ISSUE THREAD

**Issue by giorgio79** [FirebaseExtended/flutterfire#3818]
Hello,
Looking at the auth docs they stop short of providing a complete Flutter Material app based example, with a Scaffold and a Streambuilder.

Can this please be provided?
https://firebase.flutter.dev/docs/auth/usage

**Comment by Salakar** [comment]
cc @rrousselGit - might be a good UI related one for you :)

**Comment by rrousselGit** [comment]
@giorgio79 What would you expect such an example to contain?

**Comment by giorgio79** [comment]
Thanks Remi , I got this sorted meanwhile googling around. 

Reading this https://firebase.flutter.dev/docs/auth/usage/   I noticed the piecemeal code snippets, and would have been nice to have a full login / logout Google social auth example :)

**Comment by rrousselGit** [comment]
Are you maybe looking for the auth example application? https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example

It has a "full" login flow.

**Comment by giorgio79** [comment]
Wow thanks Remi. Looks fab.

Perhaps a link from https://firebase.flutter.dev/docs/auth/usage/ could be nice.

How do people find that sample? I haven't back when I posted here. 🙂
