### ISSUE TITLE
No Notification receive in background for IOS

### ISSUE THREAD

**Issue by mobiledev2014** [FirebaseExtended/flutterfire#3819]
I am using flutter 1.22 stable, Xcode 12, Firebase 7.0.3 and IOS 14 for device but the notification only works in foreground, Please help me find the solution

**Comment by dackers86** [comment]
Hi @mobiledev2014.

Could you provide an example of the code you are using so we can attempt to replicate the issue.

Thanks

**Comment by pengw00** [comment]
I think you might miss add click_action attribute when sending message in backend

**Comment by campioncino** [comment]
I have the same (old) issue.

There's no way to get the firebase message in background for iOS.

The messages are correct and they arrive when the app is in foreground

That's the message: 

`"to": "dAMWn_x6TACR6clI_Oe62s:APA91bFtfnR9VrXl0J_HNB8WAdLJdOp8p8FZsqzDLqSwqsOS8RlepqTVJp2zzETJj78AAwVSfz4PYmjqoPpnpUWL72DpdWfkyeXkaWmyPjqYfgF1_7qWB6X5w4MIW7_kKs8ESuFvGAFg",
	"body": "this is a body",
	"title": "this is a title",
	"priority": "high",
	"data": {
		"click_action": "FLUTTER_NOTIFICATION_CLICK",
		"id": "1",
		"status": "done"
	}`

When the app is in background, there's no way to get the message, but when you put the app in foreground you get the message back.

Have you ever solved this problem?
Few month ago i followed this solution https://github.com/FirebaseExtended/flutterfire/pull/2016

Many updates, but same problems ?

**Comment by dackers86** [comment]
Hi @campioncino 

You are correct https://github.com/FirebaseExtended/flutterfire/pull/2016 is related, please follow this for any updates.

Fyi. It's my understanding this will be apart of the messaging rework, please see https://twitter.com/elliothesp/status/1314479419667476480
