### ISSUE TITLE
[Cloud-firestore]:DocumentSnapshotPlatform.get._findKeyValueInMap (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:82:7) 

### ISSUE THREAD

**Issue by Chandrakant123456** [FirebaseExtended/flutterfire#3827]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@Chandrakant123456 
You need to fill the template with actual description, steps to replicate, expected and actual results you are getting. The template seems to be empty, so we can't help you in identifying the issue. Please provide `flutter doctor -v`, a minimal complete reproducible code sample that shows the issue.
thanks.
