### ISSUE TITLE
🐛 [cloud_firestore flutter] error message does not specify which field is missing "field does not exist within the DocumentSnapshotPlatform"

### ISSUE THREAD

**Issue by giorgio79** [FirebaseExtended/flutterfire#3828]
## Bug report
When I am trying to read the snapshot into its class, I am getting an error message 

"field does not exist within the DocumentSnapshotPlatform" but it does not say which field. Probably, because it is a nested class with other classes deeper.

Anyway to figure out which field is missing?

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Ehesp** [comment]
Can you give a code example?

**Comment by darshankawar** [comment]
@giorgio79 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by yokartiklebron** [comment]
error message does not specify which field is missing but my project is small, I was able to observe the error in my query.
This problem occurs when I expect a value in the field.
In my small project, I aim to extract an icon if the user does not have a photo, but I get this error.
I check the availability of the user's photo in the users collection area on the cloud firestore.

This problem happened after the update.

cloud_firestore: ^0.13.6 to ^0.14.1+3

**Comment by Ehesp** [comment]
Hey, this isn't possible I'm afraid. The SDKs would need to iterate your entire dataset, and when this is large/deeply-nested it isn't feasible due to performance.

**Comment by giorgio79** [comment]
This is IT so everything is possible. Perhaps have an sql table for email, phone and FB user id and just query that. That is lightning fast with GBs of data....

**Comment by giorgio79** [comment]
PS I am willing to chip in if you give it a try

**Comment by fenchai23** [comment]
I am also getting the same error, what's weird is that all fields exist but the same error is output.

`field does not exist within the DocumentSnapshotPlatform`

**Comment by Sreadon** [comment]
I had this error, seems like doing this works fine: 
`yourVariable = (snapshot.data().containsKey("yourVariable") ? snapshot['yourVariable'] : null),` 

I'm not sure, but previously I think this was working:
`yourVariable =  snapshot['yourVariable'] ?? null,`
