### ISSUE TITLE
[Cloud Firestore]  transactions doc  has typo

### ISSUE THREAD

**Issue by arbaazaj** [FirebaseExtended/flutterfire#3831]
There is a typo in second bullet point where it says:

> Transactions will fail is the client is offline, they cannot use cached data

where it should be **if** rather then **is** after **transactions will fail**

Link: [https://firebase.flutter.dev/docs/firestore/usage#transactions](url)

**Comment by janethavi** [comment]
Can I work on this issue?

**Comment by SirusCodes** [comment]
It is fixed `Transactions will fail when the client is offline, they cannot use cached data`
Can be closed.

**Comment by janethavi** [comment]
> It is fixed `Transactions will fail when the client is offline, they cannot use cached data`
> Can be closed.

Okay
