### ISSUE TITLE
[📚] Suggested Google key restrictions per package

### ISSUE THREAD

**Issue by 2math** [FirebaseExtended/flutterfire#3838]
Hi,
I think will be helpful to add in the documentation, which restrictions we have to add to a key, when add a specific Firebase package.
Currently in my project I had a key already which was restricted to Map API only and it looks like once added Firebase to the project, it uses the same key for it. I had to spend a day to figure it out why is not working and I can confirm that there are many people with same problem out there, which end up with same solution to remove key restrictions. 
Thanks in advance!

**Comment by Salakar** [comment]
The documentation for Android, iOS, macOS & Web now all explicitly state that the Firebase key/configuration details are to be retrieved from the Firebase apps section on the Firebase console - so I think this does cover this.
