### ISSUE TITLE
🐛 firebase_auth from facebook  PhotoURL update

### ISSUE THREAD

**Issue by megatron78** [FirebaseExtended/flutterfire#3839]
## Bug report

**Describe the bug**
PhotoURL when linked User from Facebook always get  a generic picture and  not profile's picture.
https://graph.facebook.com/{id}/picture
Since september 2020 Facebook need token to get picture.

### Steps to reproduce

final AuthCredential credential = FacebookAuthProvider.credential(result.accessToken.token,);
final User user = (await FirebaseAuth.instance.signInWithCredential(credential)).user;
print("Signed in Facebook photo: " + user.photoURL);

Not show profile picture, just a generic one.

Thanks in advance.

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Ehesp** [comment]
If you log out the provider List data, does it show in there for the Facebook one?

**Comment by megatron78** [comment]
No, it only shows a generic image.

**Comment by rodrigoAb21** [comment]
yep, it only shows a generic image.

**Comment by dcoleyoung** [comment]
Maybe related to this change https://developers.facebook.com/docs/graph-api/changelog/version8.0#users

> Starting October 24, 2020, the GET /{user-id}/picture endpoint (GET /{user-id}?fields=picture) will require an App-Scoped User ID (ASID) for tokenless requests. If you query the User with a non-ASID, you must include an App, Client, or User Access Token in the request. Refer to the User Picture reference for details.

**Comment by dreyes17** [comment]
This a possible workaround that works for me: 

final res = await _fbSignIn.logIn(permissions: [
      FacebookPermission.publicProfile,
      FacebookPermission.email
    ]);

    switch (res.status) {
      case FacebookLoginStatus.Success:
        final FacebookAccessToken fbToken = res.accessToken;
        final AuthCredential credential =
            FacebookAuthProvider.credential(fbToken.token);
          final UserCredential authResult =
              await _firebaseAuth.signInWithCredential(credential);
          User fbUser = authResult.user;
          String photoUrl = fbUser.photoURL + "?height=500&access_token=" + fbToken.token;

Hope it will be helpful!

**Comment by megatron78** [comment]
It works like a charm! Thanks for share.

**Comment by RamezSleem** [comment]
this worked for me: 
` String photoUrl = user.photoURL + "?height=500&access_token=" + accessToken.token;`
`user.updateProfile(photoURL: photoUrl);`

**Comment by dcoleyoung** [comment]
I'm using firebase_auth 0.15.3+1, which still needs UpdateUserInfo

    String photoUrl = user.photoUrl + "?height=500&access_token=" + myToken.token;
    UserUpdateInfo updateInfo = UserUpdateInfo();
    updateInfo.photoUrl = photoUrl;
    await user.updateProfile(updateInfo);

**Comment by dcoleyoung** [comment]
@dreyes17 Is the query parameter ?height=500, truly required? I think the image is natively 50x50

**Comment by dreyes17** [comment]
> @dreyes17 Is the query parameter ?height=500, truly required? I think the image is natively 50x50

No it just depend on how big you want the image to be.

**Comment by gregoryshoniwa** [comment]
@dreyes17 

well what i simply did was add a new photoURL2 like this in by code

payload.user.photoURL2 = payload.additionalUserInfo.profile.picture.data.url;

this will be in a signin function then you can refer to it if someone logs in with faceback

**Comment by aperezhra** [comment]
Hello Folks! 
Do you have any workaround for this?

I have a use case where I update firebase user's photoURL with the Facebook tokenized profile photo, but these changes are not reflected to my User stream until the next time log back in.

Please help.

**Comment by Salakar** [comment]
A workaround was posted above to use the token urls [here](https://github.com/FirebaseExtended/flutterfire/issues/3839#issuecomment-778662902) - this is probably the ay forward. FlutterFire is just a wrapper around the official native Firebase SDKs so there's not much we can do here to improve this
