### ISSUE TITLE
Flutter Cloud_Firestore NotEquals support

### ISSUE THREAD

**Issue by sjrphx** [FirebaseExtended/flutterfire#3850]
In a September 17th update, it was was announced that Firestore now supports "Not Equal" queries. 
-https://firebase.google.com/support/release-notes/js#version_7210_-_september_17_2020

The latest cloud_firestore Flutter plugin (0.14.1+3) doesn't look like it supports this yet, I wasn't able to spot its addition in the version log and the API calls aren't available. Is there any information on when this will be added?

Thanks!

**Comment by dackers86** [comment]
Please find updates at https://github.com/FirebaseExtended/flutterfire/pull/3748
