### ISSUE TITLE
[firebase_crashlytics] log should print if debugging and enableInDevMode is not set

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#387]
Feature Request
---
When a consumer calls `Crashlytics.instance.log(msg)` while debugging (and without `enableInDevMode` set), we should print the `msg` to the console. When teams write meaningful debug statements, they should be useful in both production and development. Sometimes we may throw some quick temporary `prints` but we're not really discussing those ones.

Use Case
---
Flutter developer/team "X" just implemented Firebase Crashlytics via Flutter's plugin and swapped all their meaningful `print` statements to `Crashlytics.instance.log(msg)`, but now all their logs are gone. They wrote a wrapper method that does both print and log to Crashlytics.

Of course, we could leave it up to them to write the wrapper if they chose, but opening this to get community's thoughts on it.

**Comment by kroikie** [comment]
@jeffscaturro-aka

The issue at https://github.com/flutter/flutter/issues/30591 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
[1151](https://github.com/FirebaseExtended/flutterfire/issues/1151)

**Comment by Salakar** [comment]
Given the age of this issue and that Crashlytics has had a major rework since; I'm going to close this issue in favour of trying the latest release.
