### ISSUE TITLE
🐛 [firebase_crashlytics 0.2.1+1] ios can't execute run script 

### ISSUE THREAD

**Issue by sukonin** [FirebaseExtended/flutterfire#3879]
Trying replace deprecated Fabric with new API and faced with this issue. 
My configuration next:
![image](https://user-images.githubusercontent.com/26312066/96249775-59ccf180-0fb6-11eb-91f0-fd20f0c23b9d.png)

Output logs
![image](https://user-images.githubusercontent.com/26312066/96249717-47eb4e80-0fb6-11eb-8fd1-a158a684bd22.png)

Also tried with 
![image](https://user-images.githubusercontent.com/26312066/96249994-c5af5a00-0fb6-11eb-82a2-23b70fa77b19.png)

Output logs
![image](https://user-images.githubusercontent.com/26312066/96250202-263e9700-0fb7-11eb-939a-a1c5a6d905ae.png)

Also added `pod 'Firebase/Crashlytics'  pod 'Firebase/Analytics'` to Podfile but still have issue.

`flutter doctor -v`

`[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale ru-RU)
    • Flutter version 1.17.5 at /Users/andrew/Public/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrew/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Volumes/Storage/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052

[✓] Connected device (1 available)
    • iPhone • 692e206e44bd729d3ff3c6f1d06012dfef401636 • ios • iOS 13.5.1`

**Comment by dackers86** [comment]
Hi @sukonin.

There is a guide for migrating from Fabric, have you followed these steps?

https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

**Comment by sukonin** [comment]
> Hi @sukonin.
> 
> There is a guide for migrating from Fabric, have you followed these steps?
> 
> https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

Hello @dackers86 , as I can see, this tutorial only for native application, doesn't it?

**Comment by dackers86** [comment]
We also have some migration notes located here.

https://firebase.flutter.dev/docs/migration

**Comment by TahaTesser** [comment]
Hi @sukonin 
For native, please check https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=ios
For new plugins, https://firebase.flutter.dev/docs/migration

**Comment by sukonin** [comment]
Thank you. It works
