### ISSUE TITLE
🐛 [Firestore] Query firestore ruturns null while using correct code and data do exists.

### ISSUE THREAD

**Issue by 0100101101001011** [FirebaseExtended/flutterfire#3883]
## Bug report

I am trying to query a collection in my firestore. But it keeps returning nothing. The firebase auth works fine and flutter doctor is ok.

**Describe the bug**
```
Future getDocs() async {
      print('Reading Firebase');
      QuerySnapshot querySnapshot = await FirebaseFirestore.instance.collection("collection").get();
      print(querySnapshot);
      var list = querySnapshot.docs;
      print(list.length);
    }
```

This is the console output:
![image](https://user-images.githubusercontent.com/13026382/96275087-e520a400-1003-11eb-8a28-42ea6069b851.png)

This is my firestore and the log shows it has been read by the code above:
![image](https://user-images.githubusercontent.com/13026382/96275405-48123b00-1004-11eb-963c-871509bb174b.png)
![image](https://user-images.githubusercontent.com/13026382/96275443-506a7600-1004-11eb-8b22-9d52a20f9a6e.png)

This is the widget code:
![image](https://user-images.githubusercontent.com/13026382/96276024-0df56900-1005-11eb-875a-d8de86ef6e35.png)

**Comment by 0100101101001011** [comment]
Firebase auth works fine.

**Comment by fabrice-ndja** [comment]
I have the same problem I would be glad to know that there is a solution for this problem. But the only solution for now at my level is to go back to the previous version.

**Comment by 0100101101001011** [comment]
> I have the same problem I would be glad to know that there is a solution for this problem. But the only solution for now at my level is to go back to the previous version.
