### ISSUE TITLE
🐛 [cloud_functions] Flutter web debug mode produces exception when calling cloud function

### ISSUE THREAD

**Issue by vinayak-3by4digitech** [FirebaseExtended/flutterfire#3892]
## Bug report

**Describe the bug**
When calling a cloud function, flutter web does not return the correct response (only in debug mode)

### Steps to reproduce

1. call any cloud function with 

```
var response = await CloudFunctions.instance.getHttpsCallable(
      functionName: 'functionName',
    )
.call({'param':parameter})
.catch((e)=>print(e));
```
2. Run with 
flutter run -d chrome

3. This results in "Expected a value of type 'Map<String, dynamic>', but got one of type 'String'" in the console

### Expected behavior

response.data should contain the value returned from the cloud function 

---

## Additional context

Same issue does not happen on Android or on Web build. Issue is only on the debug mode for web
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.6 19G73 x86_64, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)

• No issues found!```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.11.0-213.1.beta
Flutter SDK 1.23.0-18.1.pre
vritual 1.1.1+1

dependencies:
- cloud_firestore 0.13.7 [flutter meta firebase_core cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.5.0 [meta flutter firebase_core cloud_functions_platform_interface cloud_functions_web]
- cupertino_icons 0.1.3
- draggable_scrollbar 0.0.4 [flutter]
- firebase_analytics 5.0.15 [meta flutter firebase_analytics_platform_interface]
- firebase_auth 0.16.1 [meta firebase_core firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.4.5 [firebase_core_platform_interface flutter meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_clean_calendar 1.0.2+1 [flutter date_utils intl]
- flutter_speed_dial 1.2.5 [flutter]
- font_awesome_flutter 8.8.1 [flutter]
- package_info 0.4.1 [flutter]
- provider 4.1.3 [flutter nested collection]
- random_string 2.0.1
- share 0.6.4+3 [meta flutter]
- shared_preferences 0.5.7+3 [meta flutter shared_preferences_platform_interface shared_preferences_macos shared_preferences_web]
- url_launcher 5.4.11 [flutter url_launcher_platform_interface url_launcher_web url_launcher_macos]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 1.1.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.1.1+2 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 1.1.0 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 1.1.0 [cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- collection 1.15.0-nullsafety.3
- date_utils 0.1.0+3 [intl]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.1 [flutter meta]
- firebase_auth_platform_interface 1.1.8 [flutter meta plugin_platform_interface]
- firebase_auth_web 0.1.3+1 [firebase_auth_platform_interface flutter flutter_web_plugins firebase http_parser meta js]
- firebase_core_platform_interface 1.0.4 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.1.1+2 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.1 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.1
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.4
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- pedantic 1.9.0
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.2 [meta]
- pub_semver 1.4.4 [collection]
- quiver 2.1.3 [matcher meta]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.2 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_macos 0.0.1+7 [flutter]
- url_launcher_platform_interface 1.0.7 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.1+6 [url_launcher_platform_interface platform_detect flutter flutter_web_plugins meta]
- vector_math 2.1.0-nullsafety.3```

</details>

---

**Comment by TahaTesser** [comment]
Hi @vinayak-3by4digitech 
You seem to be using an older version of `cloud_functions`, I have no issues when using the latest `cloud_functions: ^0.6.0+1`  on the web 
<img width="383" alt="Screenshot 2020-10-21 at 8 40 17 PM" src="https://user-images.githubusercontent.com/48603081/96739653-a745c600-13dd-11eb-9cc9-7fd3a3e23ede.png">


<details> 
<summary>complete code sample</summary> 

```dart
// Copyright 2018, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:cloud_functions/cloud_functions.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _response = 'no response';
  int _responseCount = 0;

  @override
  Widget build(BuildContext context) {
    final HttpsCallable callable = CloudFunctions.instance
        .getHttpsCallable(functionName: 'repeat')
          ..timeout = const Duration(seconds: 30);
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Cloud Functions example app'),
        ),
        body: Center(
          child: Container(
            margin: const EdgeInsets.only(top: 32.0, left: 16.0, right: 16.0),
            child: Column(
              children: <Widget>[
                Text('Response $_responseCount: $_response'),
                MaterialButton(
                  child: const Text('SEND REQUEST'),
                  onPressed: () async {
                    try {
                      final HttpsCallableResult result = await callable.call(
                        <String, dynamic>{
                          'message': 'hello world!',
                          'count': _responseCount,
                        },
                      );
                      print(result.data);
                      setState(() {
                        _response = result.data['repeat_message'];
                        _responseCount = result.data['repeat_count'];
                      });
                    } on CloudFunctionsException catch (e) {
                      print('caught firebase functions exception');
                      print(e.code);
                      print(e.message);
                      print(e.details);
                    } catch (e) {
                      print('caught generic exception');
                      print(e);
                    }
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details> 


Test function 
```ts
import * as functions from 'firebase-functions';

// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript
//
// export const helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });


export const repeat = functions.https.onCall((data, context) => {
    return {
        repeat_message: data.message,
        repeat_count: data.count + 1,
    }
});
```

Please update your package or try again in a new project using the code I provided above
