### ISSUE TITLE
On Message, Launch, resume not working when I updated this package from 6.0.16 IOS

### ISSUE THREAD

**Issue by sheheryarkhan501** [FirebaseExtended/flutterfire#3893]
I am testing on real device for ios, previously these call backs were called when I clicked on the notification.
Now, after updating to the latest version, these functions are not called. 
Any reason?

**Comment by nikolaihen** [comment]
Might be related to this issue: https://github.com/FirebaseExtended/flutterfire/issues/3894

**Comment by TahaTesser** [comment]
Hi @sheheryarkhan501 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`  your `flutter run --verbose`, and a complete reproducible minimal code sample
Thank you
