### ISSUE TITLE
[📚] Current documentation to setup FCM for iOS is misleading/broken

### ISSUE THREAD

**Issue by nikolaihen** [FirebaseExtended/flutterfire#3894]
A couple of weeks ago, push notifications suddenly stopped working on iOS 13+. I can't tell you how many hours I spent debugging this. It turns out the documentation for how to setup an iOS client to receive FCM notifications is misleading/broken.

**Here's a link to the documentation which lead you to create an APN auth key instead of the SSL .p12 certificates required for it to work:** https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_certificate

**Here's a link to a recent SO post with more people experiencing the same issue:** https://stackoverflow.com/questions/61569583/firebase-notifications-received-on-ios-12-but-not-received-on-ios-13/64388368

**Comment by karamage** [comment]
I'm a first time contributor.
I would like to start working on this issue.

But as it is my first time, there are many things I don't understand.
It may take some time.

**Comment by darshankawar** [comment]
@nikolaihen 
There's similar [open](https://github.com/FirebaseExtended/flutterfire/issues/3404) issue describing your case regarding iOS integration documents being not clear.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
