### ISSUE TITLE
firebase_ml_custom not compatible with cloud_firestore

### ISSUE THREAD

**Issue by ricardochen** [FirebaseExtended/flutterfire#3896]
firebase_ml_custom depends on core 6.27.0 while cloud_firestore depends on core 6.26.0

[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In snapshot (Podfile.lock):
    Firebase/CoreOnly (= 6.26.0, ~> 6.26.0)

  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.1-3, which depends on
      Firebase/CoreOnly (~> 6.26.0)

    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.1-3, which depends on
      Firebase/Firestore (~> 6.26.0) was resolved to 6.26.0, which depends on
        Firebase/CoreOnly (= 6.26.0)

    firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.0.1, which depends on
      Firebase/MLModelInterpreter (~> 6.27.0) was resolved to 6.27.0, which depends on
        Firebase/CoreOnly (= 6.27.0)

made it work by importing the plugin locally and changed   s.dependency 'Firebase/MLModelInterpreter', "~> 6.27.0" to   s.dependency 'Firebase/MLModelInterpreter', "~> 6.26.0"

However this 'Firebase/MLModelInterpreter', "~> 6.26.0" also includes tensorflowlitec.framework that conflicts with package tflite_flutter .  Not sure if 6.27.0 have tensorflowlitec.framework included.

**Comment by darshankawar** [comment]
Getting same error after adding `firebase_ml_custom` and `firebase_core` while trying to run on iOS. I am on latest stable.

```
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.1-3, which depends on
          Firebase/CoreOnly (~> 6.26.0)

        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.1-3, which depends on
          Firebase/Firestore (~> 6.26.0) was resolved to 6.26.0, which depends on
            Firebase/CoreOnly (= 6.26.0)

        firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.0.1, which depends on
          Firebase/MLModelInterpreter (~> 6.27.0) was resolved to 6.27.0, which depends on
            Firebase/CoreOnly (= 6.27.0)

    CocoaPods could not find compatible versions for pod "FirebaseCore":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.1-3, which depends on
          Firebase/CoreOnly (~> 6.26.0) was resolved to 6.26.0, which depends on
            FirebaseCore (= 6.7.2)


```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

**Comment by urbanmania** [comment]
Same here but using v0.0.4

firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.0.1, which depends on
          Firebase/MLModelInterpreter (~> 6.27.0) was resolved to 6.27.0, which depends on
            Firebase/CoreOnly (= 6.27.0)

Also, if you look at **firebase_ml_custom.podspec** the version there is 

`"name": "firebase_ml_custom",
  "version": "0.0.1",
  "summary": "A new Flutter plugin.",`

**Comment by Theunodb** [comment]
```
[!] CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter":
  In Podfile:
    firebase_ml_custom (from `.symlinks/plugins/firebase_ml_custom/ios`) was resolved to 0.2.0-1, which depends on
      Firebase/MLModelInterpreter (= 8.0.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/MLModelInterpreter (= 8.0.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

**Comment by Theunodb** [comment]
Any development on this? Is there something we can do to help speed this up?

**Comment by Alecia1997** [comment]
Any feedback on this yet?

**Comment by Johan-glitch1412** [comment]
I am also facing this issue

**Comment by Theunodb** [comment]
Anyone know of a workaround on ios?

**Comment by Mmisiek** [comment]
I am stuck on "CocoaPods could not find compatible versions for pod "Firebase/MLModelInterpreter" in "pod install".
There was some workarounds for Android which works but I can't find solution for iOS which is blocking my deployment :(

**Comment by russellwheatley** [comment]
Unfortunately, `ml_custom` is a [deprecated plugin](https://firebase.flutter.dev/) and there will be no further work on it.
