### ISSUE TITLE
application java

### ISSUE THREAD

**Issue by Nurullah1995** [FirebaseExtended/flutterfire#3898]

**Comment by darshankawar** [comment]
@Nurullah1995 
Whenever opening an issue, please use the New Bug Report [template](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) to fill out the details.

Closing, as no information is provided.
