### ISSUE TITLE
CAPTCHA code works on simulator, but on physical iPhone I get the errors `Token mismatch` and then `ERROR_MISSING_VERIFICATION_ID

### ISSUE THREAD

**Issue by dunky-star** [FirebaseExtended/flutterfire#3911]
Same problem with `firebase_auth: 0.15.5+3`: on the simulator, I get the CAPTCHA code and it works, on a physical iPhone I get the errors `Token mismatch` and then `ERROR_MISSING_VERIFICATION_ID, The phone auth credential was created with an empty verification ID`.

Everything seems to have set up well on firebase (certificates, APNs, etc.): the normal notifications work well.

EDIT: I made it working adding these 2 override methods in the AppDelegate.swift
```
//Auth
override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
           let firebaseAuth = Auth.auth()
           firebaseAuth.setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
 }
 override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
           let firebaseAuth = Auth.auth()
           if (firebaseAuth.canHandleNotification(userInfo)){
               print(userInfo)
               return
           }
}
```
Don't forget to add `import FirebaseAuth` !

_Originally posted by @rignaneseleo in https://github.com/FirebaseExtended/flutterfire/issue_comments/602762080_

**Comment by dunky-star** [comment]
After the "add import FirebaseAuth" to AppDelegate. When trying to build the archive for publishing, it keep popping error and exit abnormally.

No such module 'FirebaseAuth'

**Comment by darshankawar** [comment]
@dunky-star 
You seem to be using an older version of `firebase_auth`. Please check the current version per [changelog](https://pub.dev/packages/firebase_auth/changelog), upgrade to latest and try again to see if it works.
If issue perists, provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by dunky-star** [comment]
Hi, darshankawar 
Thanks, just solved it a while ago. The mistake was on my side.
I was using **open -a Xcode x.xcodeporj** instead of **open -a Xcode x.xcworkspace**.

**Comment by darshankawar** [comment]
Closing this as non-issue.
