### ISSUE TITLE
🐛 [firebase_core] Fatal issue: FirebaseSDKVersion has to be increased

### ISSUE THREAD

**Issue by serhii-k** [FirebaseExtended/flutterfire#3915]
Hi guys,
I really want to bring to your attention **a fatal issue** of using the FirebaseSDKVersion=25.3.1 for Android (firebase_core/android/gradle.properties).

After migrating to the new set of FlutterFire plugins, and running the build on one of my test devices, my app just crashed during its launch!

For the 25.3.1, firebase_crashlytics uses the version 17.0.0 of the Firebase Crashlytics library, which causes this crash when migrating data. This issue has been already fixed in 17.0.1.

As @red42 mentions in #3530 the FirebaseSDKVersion for Android should be at least 25.4.1 (just a minor shift from the current 25.3.1, and hopefully without any issues for other plugins).

Please see the full details inside #3530. By opening this new issue, I just want to really make it visible.

Thank you!

**Comment by markusaksli-nc** [comment]
Hi @serhii-k 
Could you please thumbs up the original issue and comment with this suggestion there? I'm going to have to close the current one as a duplicate.
Thank you
