### ISSUE TITLE
FirebaseApp.configure not setting options

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#392]
```
Future<void> loadFromFirebase() async {

  var options = new FirebaseOptions(
    googleAppID: "***",
    apiKey: "**",
    databaseURL: "**",
  );
  
  final FirebaseApp app = await FirebaseApp.configure(
    name: "name", 
    options: options
  );

  var database = new FirebaseDatabase(app: app);
}
```

When `app` is created the `options` property shows a number of errors  

![image](https://user-images.githubusercontent.com/15944178/54872240-03d3a000-4db9-11e9-9a46-add5af83c4d6.png)

Then when creating `database` the databaseURL is null which means it somehow has not been set up correctly in `app` (as my understanding is that it should grab it from `app`)

The logs don't indicate anything about this issue. What am I missing?

**Comment by kroikie** [comment]
@nikeshjobanputra

The issue at https://github.com/flutter/flutter/issues/29856 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @nikeshjobanputra
are you still experiencing this issue with the latest version of Flutter and [firebase_database](https://pub.dev/packages/firebase_database)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
