### ISSUE TITLE
[firebase_auth] errors codes are incorrect

### ISSUE THREAD

**Issue by ollydixon** [FirebaseExtended/flutterfire#3921]
Previously we had error codes working correctly on signup/login. Now the errors codes thrown are different. We didn't know until users were complaining about it.

When was this deprecated? And why wasn't it done correctly?

Example of previous error pickup =

```
if (e is PlatformException) {
      if (e.code == 'ERROR_EMAIL_ALREADY_IN_USE') {
           message = lang('error_email_already_in_use');
      }
      if (e.code == 'ERROR_WEAK_PASSWORD') {
           message = 'The password was weak, try another. Perhaps longer with more special characters.';
      }
      if (e.code == 'ERROR_INVALID_EMAIL') {
           message = lang('error_invalid_email_signup');
     }
}
```

Now the error codes throw look like this: ```firebase/EMAIL_ALREADY_IN_USE```

**Comment by dackers86** [comment]
HI @ollydixon 

Our documentation shows that your original code is correct (https://firebase.flutter.dev/docs/auth/usage/#emailpassword-registration--sign-in). Can you confirm which version of `auth` you are using.

We have templates for correctly tracking and issues https://github.com/FirebaseExtended/flutterfire/issues/new/choose. 

Using this will support in finding the issue. Thanks!

**Comment by ollydixon** [comment]
I'm using ```firebase_auth: 0.18.0``` the original no longer works. There is also another auth section with 12 switch cases, I had to change this one to this for now:

```
    if (e is FirebaseAuthException) {
      if (e.code == 'email-already-in-use') {
        message = lang('error_email_already_in_use');
      }
      if (e.code == 'invalid-email') {
        message = lang('error_invalid_email_signup');
      }
      if (e.code == 'weak-password') {
        message = 'The password was weak, try another. Perhaps longer with special characters.';
      }
    }
```

**Comment by ollydixon** [comment]
@dackers86 this is a diaster I imagine so many apps using Firebase auth will have silient errors now. This wasn't deprecated with any warnings; previosuly we were told what the values were; now we don't know.
 
<img width="991" alt="Screenshot 2020-10-20 at 14 41 16" src="https://user-images.githubusercontent.com/6940726/96587291-72087d80-12e2-11eb-87d1-462abb04dbbb.png">

**Comment by markusaksli-nc** [comment]
Printing `FirebaseAuthException.code` using `firebase_auth: ^0.18.1+2` outputs:
```
I/flutter ( 4998): email-already-in-use
```

Can't find anything in the [changelog](https://pub.dev/packages/firebase_auth/changelog) regarding this being changed, aside from [0.18.0](https://pub.dev/packages/firebase_auth/changelog#0180):

> Added a new FirebaseAuthException class (extends FirebaseException)

**Comment by Salakar** [comment]
@dackers86 could you send a PR up to add this to the changelog please? Ping me on slack if you need more info. Thanks

**Comment by ollydixon** [comment]
@markusaksli-nc @Salakar we've almost implemented a solution with the new codes (tested them all). Will this be changed again or not? (We really need enums tbh)

**Comment by Ehesp** [comment]
https://github.com/FirebaseExtended/flutterfire/pull/3402 there is this PR up, some discussion in there

**Comment by Salakar** [comment]
Closing in favour of https://github.com/FirebaseExtended/flutterfire/issues/3273
