### ISSUE TITLE
🐛 [Auth && Firestore] Claims not being honoured

### ISSUE THREAD

**Issue by jimmyff** [FirebaseExtended/flutterfire#3922]
Hi, I've been stuck with this issue for a few days, I've exahusted all the documentation and I've been speaking with the firebase support team about who have gone as far as they can and are referring me back to flutter support. Everything seems in order in terms of firebase rules etc yet the issue persist which I think means there is either a bug in my implementation of auth & firebase or I've found a bug.

I have a very simple firebase security rule that references a custom claim. It works perfectly when running locally via the emulator but it fails with permission denied when deployed to firebase. 

The only thing I can think is that the custom claim is not being made available to the firestore security rules for some reason. I know that they are there in the client as the query that is failing (get request to /account/foobar) is using a custom claim (os_uid) which is pulled from the getTokenResult()  as the documentID (foobar). I'm also printing the result of getTokenResult() to console and I can see all of my claims are there alongside the usual firebase ones. I can confirm that if I change this rule to 'allow read: if true;'  then my app loads correctly, it's definitely this rule that is failing and I honestly can't figure out why!

Here is the client code that handles `User` change event, the firestore document load action at the bottom (to account/..) is the one that is failing with permission denied. I have included the output of this code at the bottom. Also I'm forcing the refresh of the token.
```dart
    final idToken = await _firebaseUser.getIdToken(true);
    log.fine('Token: $idToken');
    final idTokenResult = await _firebaseUser.getIdTokenResult();
    final claims = idTokenResult.claims;
    log.fine('loaded claims');
    log.info(claims);

    // handle new user, has auth profile but no account
    if (claims == null || claims.isEmpty || !claims.containsKey('os_uid')) {
      state = AuthState.noAccount;
    
    // handle user with account
    } else {
      final accountDoc =
          await firestore.doc('account/${claims['os_uid']}').get();
```
You can see from this code, that /account/$os_uid will only get requested if the os_uid claim is present. The document path that is failing contains the os_uid provided by the claim loaded via the client app. So the client app knows that the claim is present, yet the firestore rules seems to not know.

Here are my rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /account/{os_uid} {
      allow read: if request.auth.token.os_uid == os_uid;
    }
    match /profile/{os_uid} {
      allow read;
    }
    match /queue/{os_uid} {
      allow read;
    }
    match /conversation/{conversation_ref} {
      allow read;
    }
  }
}
```
(currently simplified whilst I try to figure out this issue). These work on the local firestore emulator.

The claims are set in a cloud function, there is some ACL stuff before, but the line of interest is:
```dart
  await admin.auth().setCustomUserClaims(
      newClaimsMsg.auth_uid, newClaimsMsg.claims.toJsonMap());
```

Here is the log output of the app initalising and failing with permission denied, you can see that the custom claims are present alongside the firebase claims:
```
I/flutter ( 6874): 46:47 Auth/FINE: Token: eyJh...foobar...
I/flutter ( 6874): 46:50 Auth/FINE: loaded claims
I/flutter ( 6874): 46:50 Auth/INFO: {osp_text: true, os_uid: 00000000-0000-0000-0000-000000000001, picture: https://foobar, firebase: {identities: {google.com: [113826926223foobar], email: [foobar@gmail.com]}, sign_in_provider: google.com}, user_id: ukeIILtVQ1eJW9es934Bc452ZCw1, aud: onesceneapp, exp: 1603124744, iat: 1603121144, iss: https://securetoken.google.com/onesceneapp, sub: ukeIILtVQ1eJW9es934Bc452ZCw1, name: Jimmy Foobar, email: foobar@gmail.com, email_verified: true, osp_claims: true, auth_time: 1602772318, osp_photos: true, os_initials: JFF, os_admin: true, os_staff: true}
I/flutter ( 6874): 46:89 Gcp/FINE: Initalised Gapi & PubSub.
W/Firestore( 6874): (21.4.3) [Firestore]: Listen for Query(target=Query(account/00000000-0000-0000-0000-000000000001 order by __name__);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
```

You can see from the log output that: 
 * the custom claims are there along side the firestore claims
 * the path that is failing, contains the os_uid. The user_id is the one that has the custom claims (that was provided to the cloud function as 'auth_uid' when setting the claims.

Any help in resolving this issue would be greatly appreciated.

Thanks

**Comment by jimmyff** [comment]
I've just realised I have another issue outstanding (#3692) whereby I have had to make my cloud function available to `allUsers` as `allAuthenticatedUsers` was failing with permission denied despite the fact I was authenticated. Perhaps I'm doing something fundamentally wrong with auth so my authentication status is not reflected in my cloud function calls or my firestore queries?

**Comment by TahaTesser** [comment]
Hi @jimmyff 
Can you please provide a complete reproducible minimal code sample and steps to reproduce this issue? 
Thank you

**Comment by jimmyff** [comment]
Hey @TahaTesser 
Of course my minimal example works first time 😡 -so I'm now trying to figure out the discrepancy... 

Will let you know when I have an update! 😅 Thanks
