### ISSUE TITLE
Android app crashes when I add firebase_crashlytics dependency

### ISSUE THREAD

**Issue by neigaard** [FirebaseExtended/flutterfire#3927]
I am trying to use crashlytics in my Flutter app, but as soon as I add `firebase_crashlytics: ^0.2.1+1` to my pubspec.yaml and run the app it immediatly crashes with this error:
`E/AndroidRuntime(10185): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(10185): Process: dk.brf.applab1.debug, PID: 10185
E/AndroidRuntime(10185): android.database.sqlite.SQLiteException: table event_payloads already exists (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE event_payloads (sequence_num INTEGER NOT NULL, event_id INTEGER NOT NULL, bytes BLOB NOT NULL,FOREIGN KEY (event_id) REFERENCES events(_id) ON DELETE CASCADE,PRIMARY KEY (sequence_num, event_id))
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1769)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.lambda$static$3(com.google.android.datatransport:transport-runtime@@2.2.1:109)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager$$Lambda$4.upgrade(Unknown Source:0)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.upgrade(com.google.android.datatransport:transport-runtime@@2.2.1:182)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SchemaManager.onUpgrade(com.google.android.datatransport:transport-runtime@@2.2.1:152)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
E/AndroidRuntime(10185): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$1.produce(Unknown Source:2)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(com.google.android.datatransport:transport-runtime@@2.2.1:517)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.getDb(com.google.android.datatransport:transport-runtime@@2.2.1:82)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(com.google.android.datatransport:transport-runtime@@2.2.1:549)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer.lambda$ensureContextsScheduled$1(com.google.android.datatransport:transport-runtime@@2.2.1:54)
E/AndroidRuntime(10185): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.WorkInitializer$$Lambda$1.run(Unknown Source:2)
E/AndroidRuntime(10185): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10185): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10185): 	at java.lang.Thread.run(Thread.java:764)`

When googling this it seems to be an old bug that was fixed in crashlytics 17.0.1. I have tried adding the following dependency in my android/app/build.gradle:
`implementation 'com.google.firebase:firebase-crashlytics:17.2.2'
implementation 'com.google.firebase:firebase-analytics:17.6.0'`

And then I get absolutly no error messages but my app still crashes (the error messages I am getting and not getting are on/off it seems, so maybe it is the same error but it is just not displayed in Android Studio).

Also I have the `apply plugin: 'com.google.gms.google-services'` line in build gradle, but if I add `apply plugin: 'com.google.firebase.crashlytics'` to my build.gradle I get this error:

`A problem occurred evaluating project app.
   Plugin with id com.google.firebase.crashlytics not found.`

Any ideas please?

**Comment by mgonzalezc** [comment]
Hello @neigaard , I think you can find a workaround for this issue in https://github.com/firebase/firebase-android-sdk/issues/1531

**Comment by darshankawar** [comment]
@mgonzalezc 
Have you followed the migration [document](https://firebase.flutter.dev/docs/crashlytics/overview) in order to use `firebase_crashlytics` plugin ? It has update steps on the plugin usage. 
If you've already done so, please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.
