### ISSUE TITLE
[cloud_firestore] Expose AutoIdGenerator

### ISSUE THREAD

**Issue by agordeev** [FirebaseExtended/flutterfire#3960]
It'd be great if the library exposes `AutoIdGenerator`, which is currently located in `cloud_firestore_platform_interface/lib/src/method_channel/utils/auto_id_generator.dart`. It's convenient to know the id before the document is stored.
#49

**Comment by bbugh** [comment]
We have need of this for CloudStorage, we have use case where we need to write a few files and need to create a "folder" using the same auto-id as the document. After the CloudStorage write, we need to put the paths into the document before writing. 

There currently doesn't seem to be a way to do this without writing, doing storage, and then re-writing the document. This could be shortened by simply generating the id ourselves first.

**Comment by russellwheatley** [comment]
I believe this isn't something we'll be exposing. Following the general Firebase pattern of creating a document id, you ought to create a document reference and use the generated id like so:

```dart
String id = FirebaseFirestore.instance.collection('collectionPath').doc().id;
```
