### ISSUE TITLE
flutter says [core/not-initialized] Firebase has not been correctly initialized. Have you added the "google-services.json" file to the project?

### ISSUE THREAD

**Issue by aviralstud** [FirebaseExtended/flutterfire#3967]
I have already inserted the .json file as specified and done everything as per the firebase specifications. sending my app and project level build gradle for reference

app level

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "parastone.krishi_tech"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation platform('com.google.firebase:firebase-bom:25.12.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
}
rootProject.ext {
    set('FlutterFire', [
            FirebaseSDKVersion: '25.12.0'
    ])
}

project level

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by dackers86** [comment]
@aviralstud Please follow the guide located at https://firebase.flutter.dev/docs/overview.

This should help you setup a basic app which you can then build on top of.

**Comment by TungWang** [comment]
same problem

**Comment by TungWang** [comment]
@dackers86 I did what exactly the document says ( https://firebase.flutter.dev/docs/overview ), but the problem didn't solve.

**Comment by Crisfon6** [comment]
I have the same problem any solution for this?, i follow step by step of the tutorial.

**Comment by lucascorrea30** [comment]
I found the solution!

Follow these steps:

https://stackoverflow.com/questions/63804012/flutter-firebase-and-android-issue-unable-to-initialise-cannot-find-google-se

After that, execute:
flutter build apk --debug
flutter build apk --profile
flutter build apk --release

and then, run app! it works for me!

**Comment by francescogatto** [comment]
Same problem with the last version

**Comment by Oghosa1** [comment]
This should solve the problem:
1. Make sure you have your google-services.json file in the right place
2. add this to app/build.gradle : apply plugin: `apply plugin: 'com.google.gms.google-services`

**Comment by TungWang** [comment]
Try this

https://stackoverflow.com/questions/65209096/flutter-default-firebaseapp-is-not-initialized-in-this-process-com-viainno-homeg/65209224?noredirect=1#comment115352814_65209224

**Comment by sanjidbillah** [comment]
I am facing this issue. badly needed a solution

**Comment by francescogatto** [comment]
It's incredible, but i resolved with a new fireabse project

**Comment by markusaksli-nc** [comment]
@aviralstud Is this still relevant?

**Comment by yosus** [comment]
got this error too. Need to ensure you have this in the `app/build.gradle` file. The [old v7 of the firebase messaging package](https://pub.dev/packages/firebase_messaging/versions/7.0.3) does mention it.

```
apply plugin: 'com.google.gms.google-services'
```
