### ISSUE TITLE
🐛 [firebase_crashlytics] Unable to set user identifier to null

### ISSUE THREAD

**Issue by agordeev** [FirebaseExtended/flutterfire#3985]
## Bug report

Version 0.2.1+1.

Why the package doesn't allow to reset user id?

```dart
  Future<void> setUserIdentifier(String identifier) {
    // Why do we need this line?
    assert(identifier != null);
    return _delegate.setUserIdentifier(identifier);
  }
```

How do I suppose to set `null` as user id after he's logged out?

PS: Firebase analytics accepts nulls just fine.

**Comment by markusaksli-nc** [comment]
Hi @agordeev 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/3937.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by agordeev** [comment]
@markusaksli-nc thanks for the prompt reaction, Markus.
The issue you're referencing is asking "why it doesn't accept null". It's quite clear to my why it doesn't (because of the assertion). I propose to change the behavior and remove the assert statement. 

So this issue is quite different from #3937. Please reopen.
