### ISSUE TITLE
Flutter firebase_auth - userChanges() behavior without reload()

### ISSUE THREAD

**Issue by zzterrozz** [FirebaseExtended/flutterfire#3994]
Hi, 

I tested on `user.emailVerified` & the Stream `userChanges()` is not updating without  calling `user.reload()`

```
  /// Notifies about changes to any user updates.
  ///
  /// This is a superset of both [authStateChanges] and [idTokenChanges]. It
  /// provides events on all user changes, such as when credentials are linked,
  /// unlinked and when updates to the user profile are made. The purpose of
  /// this Stream is to for listening to realtime updates to the user without
  /// manually having to call [reload] and then rehydrating changes to your
  /// application.
  Stream<User> userChanges() => _pipeStreamChanges(_delegate.userChanges());
```

This part doesn't match the implementation: 
`The purpose of this Stream is to for listening to realtime updates to the user without manually having to call [reload] and then rehydrating changes to your application.`

**Comment by darshankawar** [comment]
@zzterrozz 

According to the document, `reload()` is called during below scenarios : `credentials are linked`, `unlinked` and when the `user's profile is updated`.  Are you using any of these scenarios while using `userChanges()` ?

If so,Please provide `flutter doctor -v` and a minimal code sample that shows the issue you are facing.

**Comment by zzterrozz** [comment]
@darshankawar 


In the documentation [https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/userChanges.html](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/userChanges.html) : 

[...] The purpose of this Stream is to for listening to realtime updates to the user without manually having to call `reload` and then rehydrating changes to your application.

But in reality, when the user confirm's his email address, the `emailVerified property` [https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User/emailVerified.html](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User/emailVerified.html) new boolean value is not sent to the Stream<User> without calling `reload`

```
void reloadUserData() async {
    await FirebaseAuth.instance.currentUser.reload();
  }
```

**Comment by darshankawar** [comment]
@zzterrozz 
That seems to be correct if you look at [this](https://firebase.flutter.dev/docs/auth/usage) documentation where it says, if `emailVerification` is successful, `reload` the user.
```

FirebaseAuth auth = FirebaseAuth.instance;

// Get the code from the email:
String code = 'xxxxxxx';

try {
  await auth.checkActionCode(code);
  await auth.applyActionCode(code);

  // If successful, reload the user:
  auth.currentUser.reload();
} on FirebaseAuthException catch (e) {
  if (e.code == 'invalid-action-code') {
    print('The code is invalid.');
  }
}
```

**Comment by zzterrozz** [comment]
@darshankawar 
In this same documentation you can find:

`Alternatively, if you need all user change events which also include authentication state changes and id token changes, you can subscribe via the userChanges() method. This stream provides realtime updates to the User class without having to call reload(), such as when credentials are linked, unlinked and when the user's profile is updated.`

Whereas when you listen to this `userChanges` stream & a user is verifying his email address, the new emailVerified boolean value (from false to true) is not added to the sink. 
It then requires to `reload` manually the user to update the emailVerified value.

**Comment by larssn** [comment]
Seeing the same behavior for email validation: `emailVerified` remains false until you do a `user.reload()`.

This goes against what the docs claims as @zzterrozz says.
Was wondering why nothing was happened, so yeah, it's bugged.

**Comment by larssn** [comment]
I've looked into a bit of code. `userChanges` does not appear to be a native Android or iOS feature. Not sure how they're managing to listen for those changes when the underlying framework doesn't support it.

**Comment by 1993alexey** [comment]
The same here. Please add this functionality because the documentation is misleading. I was surprised to find out that email verification doesn't trigger `userChanges ` after spending a day implementing my code around the idea of real-time user changes.

**Comment by Ehesp** [comment]
The reason `userChanges` was added is that because in reactive applications such as Flutter, most of the time you'd find yourself calling a method, then calling `reload` and passing the reloaded user into state. Instead we just do this for you to reduce code.

That being said, the documentation could be clearer. We can't trigger events for things such as email verification because we don't know about them. I'll get this actioned to improve the docs.

**Comment by russellwheatley** [comment]
Hey @zzterrozz, there is a PR in the works that will clarify what to expect with auth events. To be clear, you will not receive a `userChanges()` event if you update the `user.emailVerified` property via the Firebase admin SDK for example.
