### ISSUE TITLE
🐛 [firebase_ml_vision] Can't find ml-vision-image-label-model that works with the latest plugin update

### ISSUE THREAD

**Issue by leonardocustodio** [FirebaseExtended/flutterfire#3995]
Hello,

After the last update of firebase plugins. I can't find any version of ml-vision-image-label-model that will work.

Here is the log output:

 ```
  Dependency failing: com.google.android.gms:play-services-vision:20.0.0 -> com.google.android.gms:play-services-vision-co
  mmon@[19.0.2], but play-services-vision-common version was 19.1.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@{strictly 24.1.0}
  -- Project 'app' depends on project 'firebase_ml_vision' which depends onto com.google.firebase:firebase-ml-vision@20.0.
  0
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@{strictly 20.0.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-common@{strictly 19.1.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@20.0.2
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-label@{strictly 18.0.4}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision@{strictly 20.0.0}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-labeling-internal@{strictly 16.0.0}
```

Before this last update I was using the **20.0.1** model:
`api 'com.google.firebase:firebase-ml-vision-image-label-model:20.0.1'`

With this plugin versions:
```
firebase_core: ^0.5.0+1
firebase_messaging: ^7.0.3
firebase_analytics: 6.0.2
firebase_crashlytics: 0.2.1+1
firebase_remote_config: 0.4.0+2
firebase_admob: 0.10.0+2
firebase_auth: 0.18.1+2
cloud_functions: ^0.6.0+1
firebase_ml_vision: 0.9.7
```

And it was working fine. After updating to:
```
firebase_core: ^0.5.1
firebase_messaging: ^7.0.3
firebase_analytics: ^6.1.0
firebase_crashlytics: ^0.2.2
firebase_remote_config: ^0.4.1
firebase_admob: ^0.10.1
firebase_auth: ^0.18.2
cloud_functions: ^0.6.0+1
firebase_ml_vision: ^0.9.8
```

I can't find any version that will work anymore..... I tried the latest 20.0.2 and also all 19+ versions....

Regards,
Leonardo

**Comment by leonardocustodio** [comment]
So I decided to update the plugins one by one, to see which one was incompatible.....

When using:
`api 'com.google.firebase:firebase-ml-vision-image-label-model:20.0.1'`

If we upgrade from
`firebase_ml_vision: 0.9.7`

to
`firebase_ml_vision: 0.9.8`

It still works........ The problem happens when upgrading the firebase_core to:
`firebase_core: 0.5.1`

When upgrading the core from 0.5.0+1 to 0.5.1 it starts to give the error. We would expect to have to upgrade the image-label-model to the latest version as well that is 20.0.2 but that doesn't fixes the issue. Actually no versions from 19-20 fixes this issue.

**Comment by kw2019ltd** [comment]
same getting this issue

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in barcode_pro_app...}
event sent after app closed: {id: 0, progressId: null, finished: true}
Launching lib\main.dart on HD1903 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-vision:20.0.0 -> com.google.android.gms:play-services-vision-co
  mmon@[19.0.2], but play-services-vision-common version was 19.1.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@{strictly 24.1.0}
  -- Project 'app' depends on project 'firebase_ml_vision' which depends onto com.google.firebase:firebase-ml-vision@20.0.
  0
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-common@{strictly 19.1.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-barcode-model@16.1.0
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-barcode-model@{strictly 16.1.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-label@{strictly 18.0.4}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision@{strictly 20.0.0}

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1

using below:
  #fireBase
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.2
  firebase_analytics: ^6.1.0
  firebase_messaging: ^7.0.3
  firebase_ml_vision: ^0.9.8
  firebase_remote_config: ^0.4.1

**Comment by kw2019ltd** [comment]
@TahaTesser

**Comment by darshankawar** [comment]
@leonardocustodio 
I tried the official `firebase_ml_vision` plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example) using latest Master version and updated the `firebase_core` and `ml_vision` plugin to latest per your comments, but was able to compile and run the app without any issues.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.165, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.24.0-4.0.pre.165 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e444b1e3fa (7 hours ago), 2020-10-30 00:41:52 -0400
    • Engine revision 99cc50dfff
    • Dart version 2.11.0 (build 2.11.0-266.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)           • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Web Server (web)                    • web-server                               •
      web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                                   •
      web-javascript • Google Chrome 86.0.4240.111

• No issues found!


```

</details>

Are there any specific steps to replicate the issue ?

**Comment by leonardocustodio** [comment]
Hello @darshankawar,

I didn't need to do anything to happen the issue. I've just updated the plugin. But did you also add: 
`api 'com.google.firebase:firebase-ml-vision-image-label-model:20.0.1'`

On the app level build.gradle dependencies? Also I did not say on my comment but the problem in compiling is happening on Android, haven't tested with iOS yet.

Also, here is my flutter doctor that I haven't posted before:

```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.508], locale pt-BR)
    • Flutter version 1.22.2 at C:\flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\NVPACK\android-sdk-windows
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\NVPACK\android-sdk-windows
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Leonardo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by leonardocustodio** [comment]
Hmmm on the example it is using version 17.0.2
I've downgraded to it and also it doesn't work, the same compiling error on android when using firebase_core 0.5.1 and ml_vision 0.9.8

ps.: I'm using the 20.0.1 instead of 17.0.2 because it was the version supported on the previous version by match making on: https://firebase.google.com/support/release-notes/android

Still even with the 17.0.2 on the example it does not work.

**Comment by sceee** [comment]
This suddenly also popped up on my end after updating `firebase_core: 0.5.0+1` to `0.5.1`.
Downgrading fixes it for me.

**Comment by kw2019ltd** [comment]
@darshankawar  pls check it its backward compatible break

**Comment by kw2019ltd** [comment]
@darshankawar i just donwlaoded FirebaseExtended project and build the example of firebase_ml_vision\example

same issue you can try it.

Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\kotai\AndroidStudioProjects\flutterfire\packages\firebase_ml_vision\example>flutter build apk
Warning: You are using these overridden dependencies:
! firebase_core 0.5.1 from path ..\..\firebase_core\firebase_core
Running "flutter pub get" in example...                             6.1s
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-vision:20.0.0 -> com.google.android.gms:play-services-vision-co
  mmon@[19.0.2], but play-services-vision-common version was 19.1.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@{strictly 24.1.0}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-face-contour-internal@{strictly 16.0.0}
  -- Project 'app' depends on project 'firebase_ml_vision' which depends onto com.google.firebase:firebase-ml-vision@20.0.
  0
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@{strictly 20.0.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-common@{strictly 19.1.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@17.0.2
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-face-model@{strictly 20.0.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-label@{strictly 18.0.4}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision@{strictly 20.0.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-face-model@17.0.2
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-labeling-internal@{strictly 16.0.0}

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      45.0s
Gradle task assembleRelease failed with exit code 1


![image](https://user-images.githubusercontent.com/47334522/97776904-da721d00-1b74-11eb-95d8-11b0b97dedf4.png)

**Comment by Jartz** [comment]
I solved it this way.
implementation 'com.google.android.gms:play-services-vision:20.1.2'
implementation 'com.google.android.gms:play-services-vision-common:19.1.2'
implementation 'com.google.android.gms:play-services-vision-image-label:18.1.0'

<img width="1159" alt="Captura de Pantalla 2020-10-31 a la(s) 10 48 55 p  m" src="https://user-images.githubusercontent.com/19338050/97794710-64e56b80-1bcb-11eb-9d31-415d1587e4cb.png">

**Comment by ahyar4y** [comment]
> 
> 
> I solved it this way.
> implementation 'com.google.android.gms:play-services-vision:20.1.2'
> implementation 'com.google.android.gms:play-services-vision-common:19.1.2'
> implementation 'com.google.android.gms:play-services-vision-image-label:18.1.0'
> 
> <img alt="Captura de Pantalla 2020-10-31 a la(s) 10 48 55 p  m" width="1159" src="https://user-images.githubusercontent.com/19338050/97794710-64e56b80-1bcb-11eb-9d31-415d1587e4cb.png">

Somehow this solved my issue, thank you

**Comment by kw2019ltd** [comment]
We need flutter to solve it, flutter example also failing so better to wait
for flutter to provide a fix

**Comment by darshankawar** [comment]
Was able to replicate this issue using plugin's official example on latest stable. 

<details>
<summary>console log</summary>

```
Launching lib/main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-vision:20.0.0 -> com.google.android.gms:play-services-vision-co
  mmon@[19.0.2], but play-services-vision-common version was 19.1.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@{strictly 24.1.0}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-face-contour-internal@{strictly 16.0.0}
  -- Project 'app' depends on project 'firebase_ml_vision' which depends onto com.google.firebase:firebase-ml-vision@20.0.
  0
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@{strictly 20.0.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-common@{strictly 19.1.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-face-model@{strictly 20.0.2}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@20.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-label@{strictly 18.0.4}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision@{strictly 20.0.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-face-model@17.0.2
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-labeling-internal@{strictly 16.0.0}

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Exception: Gradle task assembleDebug failed with exit code 1




```

</details>

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (4 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!


```

</details>

**Comment by csandovalgt** [comment]
is there any fix for this issue? the solution that worked for @Jartz didn't work for me

**Comment by comyuno** [comment]
> is there any fix for this issue? the solution that worked for @Jartz didn't work for me

After hours of debugging I came up with this fix:
pubspec.yaml:
  firebase_core: ^0.5.1
  firebase_ml_vision: ^0.9.8
app/build.gradle:    
```
dependencies {
        api 'com.google.firebase:firebase-ml-vision-face-model:20.0.2'
    }
```
`   implementation 'com.google.android.gms:play-services-vision:20.1.1'
    implementation 'com.google.android.gms:play-services-vision-common:19.1.1'
    implementation 'com.google.android.gms:play-services-vision-image-label:18.0.5'
    implementation 'com.google.android.gms:play-services-vision-face-contour-internal:16.0.2'`

it's basically what google recommends here: https://firebase.google.com/support/release-notes/android

**Comment by guilhermedaldim** [comment]
Is there any solution to this problem? None of the solutions worked for me

**Comment by csandovalgt** [comment]
> Is there any solution to this problem? None of the solutions worked for me

Hi, finaly today I make my app works.  Today (nov 6) the team released a new version 0.9.9 in pub.dev. Also app/build.gradle is:

`implementation 'com.google.firebase:firebase-config:20.0.0'
implementation 'com.google.android.gms:play-services-vision:20.1.2'
    implementation 'com.google.android.gms:play-services-vision-common:19.1.2'
    implementation 'com.google.android.gms:play-services-vision-image-label:18.1.0'`

thank you @comyuno , also your comment guided me to the right configuration in my gradle file.

**Comment by guilhermedaldim** [comment]
That didn't work for me, what version of `com.google.gms: google-services` on android / build.gradle?

**Comment by guilhermedaldim** [comment]
> > Is there any solution to this problem? None of the solutions worked for me
> 
> Hi, finaly today I make my app works. Today (nov 6) the team released a new version 0.9.9 in pub.dev. Also app/build.gradle is:
> 
> `implementation 'com.google.firebase:firebase-config:20.0.0'`
> `implementation 'com.google.android.gms:play-services-vision:20.1.2'`
> `implementation 'com.google.android.gms:play-services-vision-common:19.1.2'`
> `implementation 'com.google.android.gms:play-services-vision-image-label:18.1.0'`
> 
> thank you @comyuno , also your comment guided me to the right configuration in my gradle file.

I managed to make it work, but I had to add to the app/build.grade `googleServices {disableVersionCheck = true}` 

P.S: add ``googleServices {disableVersionCheck = true}`` after `apply plugin: 'com.google.gms.google-services'`

**Comment by k0shk0sh** [comment]
for anyone who got the build up and running using any of the above but then the whole vision don't work anymore, here is the proper solution for it: 

```
    implementation 'com.google.android.gms:play-services-vision-common:19.1.2'
    implementation 'com.google.android.gms:play-services-vision:20.1.2'
    implementation 'com.google.android.gms:play-services-vision-image-labeling-internal:16.0.5'
    api 'com.google.firebase:firebase-ml-vision:24.1.0'
    api 'com.google.firebase:firebase-ml-vision-image-label-model:20.0.2'
```

**Comment by kw2019ltd** [comment]
@darshankawar pls update firebase ml example so we can do the same and no need to guess

**Comment by kw2019ltd** [comment]
fix if you using barcode:

```
dependencies {
 api 'com.google.firebase:firebase-ml-vision-barcode-model:16.1.2'
 api 'com.google.firebase:firebase-ml-vision:24.1.0'
 implementation 'com.google.android.gms:play-services-vision-common:19.1.2'
 implementation 'com.google.android.gms:play-services-vision:20.1.2'
 implementation 'com.google.android.gms:play-services-vision-image-label:18.1.0'
}
```

**Comment by kw2019ltd** [comment]
now we have new big issue, follow on link
https://github.com/FirebaseExtended/flutterfire/issues/4090

**Comment by leonardocustodio** [comment]
Not even the downgraded version is working anymore. I've downgrade everything back to the versions of the beginning and removed all extra dependencies that I've added in effort to work with ml_vision.

And I'm also getting the "java.lang.IllegalArgumentException: Service not registered: lx@226fed8" error. And I'm pretty sure I'm not using a cached version since I did a flutter clean and deleted every packages before getting them back.

I think this error is not related to the ml_vision itself but to some kind of dependency that is being pulled regardless of the pubspec version. Probably a changed that was made in the last few days since this error was not happening a few days ago with the versions on the beginning of the report.

I think this issue should be in top priorities now.

**Comment by bharat-biradar** [comment]
I am facing the same problem.I want to use image labelling and face detection.
If anyone has found the solution please mention it

**Comment by cfchris** [comment]
Hopefully more details will help this be fixed... 

(Thank you @comyuno for what I think has finally fixed my issue.)

I have tried to use `flutter pub upgrade` a few times now over the course of weeks. Every time I did that, it would cause build errors mentioning "firebase". So, I'm going through it step by step as I type this to provide some details.

Before I attempt to update again, `flutter pub outdated` says the following:

```
$ flutter pub outdated
Dependencies                      Current                Upgradable             Resolvable             Latest
firebase_messaging                *7.0.2                 7.0.3                  7.0.3                  7.0.3
firebase_ml_vision                *0.9.7                 0.9.10                 0.9.10                 0.9.10
```

Because Firebase plugins are the only ones (so far) that have caused issues with `flutter pub upgrade`, I am going to start by using fixed version expressions in my pubspec.yaml.

```
  firebase_messaging: 7.0.2
  firebase_ml_vision: 0.9.7
```

`flutter pub get` and `flutter run`. Still working.

Now with my fixed versions for the two plugins that I have in pubspec.yaml, I ran `flutter pub upgrade`. This updated a bunch of transitive dependencies (but not `firebase_messaging` and `firebase_ml_vision`).

`flutter run`. And, we're broken.

```
* What went wrong:                                                      
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
                                                                        
  Dependency failing: com.google.android.gms:play-services-vision:20.0.0 -> com.google.android.gms:play-services-vision-co
  mmon@[19.0.2], but play-services-vision-common version was 19.1.0.    
                                                                        
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.                                                 
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@{strictly 24.1.0}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-face-contour-internal@{strictly 16.0.0}
  -- Project 'app' depends on project 'firebase_ml_vision' which depends onto com.google.firebase:firebase-ml-vision@20.0.
  0                                                                     
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-common@{strictly 19.1.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-face-model@{strictly 20.0.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-label@{strictly 18.0.4}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision@{strictly 20.0.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-face-model@17.0.2
```

Looking back, I now see that `flutter pub outdated` said that I had transitive "firebase" dependencies as follows:
```
firebase                          *7.3.0                 -                      -                      7.3.3
firebase_core                     *0.5.0                 0.5.3                  0.5.3                  0.5.3
firebase_core_platform_interface  *2.0.0                 2.1.0                  2.1.0                  2.1.0
firebase_core_web                 *0.2.0                 0.2.1+1                0.2.1+1                0.2.1+1
```

I don't like that I'm in a place where `flutter pub upgrade` breaks my build. And I'm nearly positive that other people are having the same issue I am having where they _don't_ update their plugins (like `firebase_ml_vision`), but, `flutter pub upgrade` breaks their build. So, I'm going to try to find a set of fixed versions that work. (`git reset --hard && flutter clean && flutter pub get`) BRB.

Alright, I updated my pubspec.yaml to the following:

```
  firebase_core: 0.5.0
  firebase_messaging: 7.0.2
  firebase_ml_vision: 0.9.7
```

I can `flutter pub upgrade` and `flutter run` and it will build and run. So, the above is what people that aren't ready to upgrade _yet_ might want to put in their pubspec.yaml.

Now, let's see if I can update and get it working with the newest version of the two Firebase plugins that we are using.

```
  firebase_core: 0.5.3
  firebase_messaging: 7.0.3
  firebase_ml_vision: 0.9.10
```

`flutter pub get && flutter run`. Updating to the versions above caused the error that I posted above. Following @comyuno's example, I updated the build.gradle as follows:

```
// From (Broke)
dependencies {
    api 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'
    implementation 'com.google.firebase:firebase-core:17.2.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

// To (Works)
dependencies {
    api 'com.google.firebase:firebase-ml-vision-face-model:20.0.2'
    implementation 'com.google.android.gms:play-services-vision:20.1.1'
    implementation 'com.google.android.gms:play-services-vision-common:19.1.1'
    implementation 'com.google.android.gms:play-services-vision-image-label:18.0.5'
    implementation 'com.google.android.gms:play-services-vision-face-contour-internal:16.0.2'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

With the 3 fixed versions of the Firebase plugin deps in my pubspec.yaml and the updated deps in my build.gradle, I can now `flutter pub upgrade && flutter clean && flutter run` and everything works.

I hope this is helpful to the Firebase plugin authors (and anyone that was stuck like I was). It feels like there should have been somethign in the changlog for firebase_ml_vision (somewhere between versions 0.9.7 and 0.9.10) explaining what changes are required in the build.gradle file. (I always run `flutter pub outdated` and then read all the changlogs for the dependencies before I update them.)

**Comment by manzoorfarmani** [comment]
> > I solved it this way.
> > implementation 'com.google.android.gms:play-services-vision:20.1.2'
> > implementation 'com.google.android.gms:play-services-vision-common:19.1.2'
> > implementation 'com.google.android.gms:play-services-vision-image-label:18.1.0'
> > <img alt="Captura de Pantalla 2020-10-31 a la(s) 10 48 55 p  m" width="1159" src="https://user-images.githubusercontent.com/19338050/97794710-64e56b80-1bcb-11eb-9d31-415d1587e4cb.png">
> 
> Somehow this solved my issue, thank you

This Solve my issue..
