### ISSUE TITLE
Firebase Database setPersistenceCacheSizeBytes 

### ISSUE THREAD

**Issue by albertlai431** [FirebaseExtended/flutterfire#3996]
I've been trying to debug my flutter app for days; immediately after building, it's been saying "lost connection to device" without giving me any stack trace or error code. Turns out it was because of this line: `db.setPersistenceCacheSizeBytes(1000000);`

Since the minimum is 1MB, once I set `cacheSize` to be 1048576 (1MB) or greater, it stopped crashing!

Here are some suggestions:
1. State the min and max `cacheSize`'s in the [documentation](https://pub.dev/documentation/firebase_database/latest/firebase_database/FirebaseDatabase/setPersistenceCacheSizeBytes.html)
2. Perhaps implement some error catching so we know what's causing the problem

Thanks 😄

Edit: this only shows up on an iOS simulator on MacOS, not on Android simulator on Windows (it might be perhaps something on my end??)

**Comment by russellwheatley** [comment]
Thanks for the suggestion, @albertlai431. In the docs you reference, it does say "Cache sizes smaller than 1 MB or greater than 100 MB are not supported.". Whilst the error itself not bubbling up from the platform to your app is annoying, it is not something Flutterfire has much control over I'm afraid.
