### ISSUE TITLE
Flutterfire web support (Unify Flutterfire and firebase-dart API)

### ISSUE THREAD

**Issue by collinjackson** [FirebaseExtended/flutterfire#40]
Right now the Flutterfire and firebase-dart packages have a similar but not quite identical Dart API for Firebase. Unifying these implementations around a common API package could enable re-use of code across web and mobile.

**Comment by slightfoot** [comment]
And of course.

https://github.com/fluttercommunity/firebase_flutter_sdk

**Comment by apps-transround** [comment]
Regarding unifying: it would be also great to officially support Dart in Firebase Cloud Functions similarly to: [firebase_functions_interop](https://pub.dev/packages/firebase_functions_interop)

**Comment by samtstern** [comment]
cc @kroikie @puf

**Comment by kroikie** [comment]
Since the native SDKs have the support of documentation should we have both firebase-dart and FlutterFire stay as close to the native SDK APIs as possible?

**Comment by startupgurukul** [comment]
Flutter web +  this = <3

It would be a true enabler for developers and a super powerful Cross platform full stack development tool

**Comment by Kleak** [comment]
With Flutter desktop it could be really mind blowing to have the same code for mobile, desktop and web. 
https://github.com/fluttercommunity/firebase_flutter_sdk seems promising but i hope one day the Firebase team will integrate it here to show good support.

**Comment by alarmatwork** [comment]
I will copy here current output what happens if you are trying to use these plugins with web (just for others to find this ticket more easily). 

I assume this issue is addressing web as well.

Flutter 1.10.11-pre.7 • channel master • https://github.com/flutter/flutter.git

```
$ flutter run -d chrome
Downloading Web SDK...                                              1.4s
Running "flutter pub get" in demoapp…                              0.5s
 
Launching lib/main.dart on Chrome in debug mode...
Throwing away cached asset graph due to Dart SDK update.                
Skipping compiling demoapp|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

firebase_core|lib/firebase_core.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings


```

**Comment by RicCu** [comment]
Hi,
Is there anything in particular I could contribute help move this along? And/or any pointers on where to start looking?

**Comment by collinjackson** [comment]
Marking this as resolved since we now have four web-enabled FlutterFire packages. Please follow the [FlutterFire README](https://github.com/FirebaseExtended/flutterfire) and [Flutter Web Plugins](https://github.com/flutter/flutter/projects/69) board for the latest status on web support.

Huge thanks to @amrfarid140 @ditman @hterkelsen for making this possible.
