### ISSUE TITLE
🐛 [firebase_storage 5.0.0-dev.4] Update SDK to 26

### ISSUE THREAD

**Issue by dvird** [FirebaseExtended/flutterfire#4013]
In order to present percent progress, TaskState.running should send events after every few bytes.
Today its sending only 2 3 4 events, which is not enough for presenting well progress on our screen.

old SDK has StorageTaskEventType.progress which worked great, but since the refactor youve made its not working anymore

**Comment by Ehesp** [comment]
This is the native SDK, we just relay the events on as they come through so it's nothing we've changed. The SDK versions have updated though.

**Comment by TahaTesser** [comment]
Hi @dvird 
As mentioned above this is from native SDK, with no changes from the plugin itself
Thank you

**Comment by dvird** [comment]
@TahaTesser @Ehesp firebase storage is now 26, but flutter use 25. i read somewhere they fixed it already

**Comment by russellwheatley** [comment]
As mentioned, this isn't something we have control over. More over, we're now using `26.2.0` android BOM version which ought to fix the android sdk issue.
