### ISSUE TITLE
🐛 [firebase_core] Firebase.initializeApp() gives Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core) when I implement an android function in MainActivity.kt or MainActivity.java

### ISSUE THREAD

**Issue by DenizKucukozturk** [FirebaseExtended/flutterfire#4019]
## Bug report

**Describe the bug**
For an app I am developing I need to use both firebase functionalities and native android libraries. Before using native android libraries I tested with some basic android code in my project and get Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core) error while testing with physical android device. I have no idea what its causing.

### Steps to reproduce

1. Initialize Firebase in the main() method:
```     
  void main() {
     WidgetsFlutterBinding.ensureInitialized();
     Firebase.initializeApp();
     runApp(MaterialApp(home: MyApp()));
}
```

2. Overwrite configureFlutterEngine in MainActivity.kt with some dummy method call :
```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        MethodChannel(flutterEngine.dartExecutor, "methodChannelDemo")
                    .setMethodCallHandler { call, result ->
                            if (call.method == "foo" ) {
                                result.success( 42 )
                            }
                        }
                    }
          }
```
3. Set up widget as
```
class _MyHomePageState extends State<MyHomePage> {
  static const MethodChannel methodChannel = MethodChannel('methodChannelDemo');

  static Future<int> foo() async {
    final result = await methodChannel.invokeMethod<int>('foo');
    print(result);
    return result;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          children: [
            SizedBox(
              height: 50.0,
            ),
            Center(
                child: RaisedButton(
              child: Text('METHOD CHANNEL DEMO'),
              onPressed: () => foo(),
            ))
          ],
        ),
      ),
    );
  }
}
```

4. This is the error:
```
E/flutter (29647): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (29647): #0      MethodChannel._invokeMethod                 package:flutter/…/services/platform_channel.dart:157
E/flutter (29647): <asynchronous suspension>
E/flutter (29647): #1      MethodChannel.invokeMethod                   package:flutter/…/services/platform_channel.dart:332
E/flutter (29647): #2      MethodChannel.invokeListMethod             package:flutter/…/services/platform_channel.dart:345
E/flutter (29647): #3      MethodChannelFirebase._initializeCore      package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:30
E/flutter (29647): #4      MethodChannelFirebase.initializeApp            package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:75
E/flutter (29647): #5      Firebase.initializeApp                             package:firebase_core/src/firebase.dart:43
E/flutter (29647): #6      main                                                       package:new_project/main.dart:7
E/flutter (29647): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (29647): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (29647): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (29647): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (29647): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (29647): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (29647): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (29647): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (29647):
```

### Flutter doctor

Here is flutter doctor -v:

<details><summary>Click To Expand</summary>

```
Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-TR)
    • Flutter version 1.22.3 at /Users/denizkucukozturk/Desktop/flutter
    • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/denizkucukozturk/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • HTC U Ultra (mobile) • FA81Z1700636 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

</details>

---

### Flutter dependencies

Here is flutter `pub deps -- --style=compact`. Other than adding firebase_core: ^0.5.0 to pubspec.yaml I did not changed any other dependencies.

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.3
Flutter SDK 1.22.3
new_project 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- firebase_core 0.5.1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.2 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- pedantic 1.9.2 [meta]
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.4+1 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

```bash
Restarted application in 1,910ms.
E/flutter (10137): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
[38;5;244mE/flutter (10137): #0      MethodChannel._invokeMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter (10137): <asynchronous suspension>
[38;5;244mE/flutter (10137): #1      MethodChannel.invokeListMethod[39;49m
 package:flutter/…/services/platform_channel.dart
E/flutter (10137): <asynchronous suspension>
[38;5;248mE/flutter (10137): #2      MethodChannelFirebase._initializeCore[39;49m
 package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart
E/flutter (10137): <asynchronous suspension>
[38;5;248mE/flutter (10137): #3      MethodChannelFirebase.initializeApp[39;49m
 package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart
E/flutter (10137): <asynchronous suspension>
[38;5;248mE/flutter (10137): #4      Firebase.initializeApp[39;49m
 package:firebase_core/src/firebase.dart
E/flutter (10137): <asynchronous suspension>
E/flutter (10137):
I/GED     (10137): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/SurfaceView(10137): 88026481 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
D/Surface (10137): Surface::disconnect(this=0x7972226000,api=1)
D/ViewRootImpl(10137): setSurfaceViewCreated, created:false
D/Surface (10137): Surface::disconnect(this=0x7972226000,api=-1)
D/SurfaceView(10137): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView(10137): try to resquest 90Hz
D/ViewRootImpl(10137): set screen refresh mode 0 due to SurfaceView-88026481
D/ColorExSystemServiceHelper(10137): checkColorExSystemService className = com.google.android.gms.measurement.service.MeasurementBrokerService
I/Choreographer(10137): Skipped 6 frames!  The application may be doing too much work on its main thread.
I/GED     (10137): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
D/Surface (10137): Surface::disconnect(this=0x79c33ba000,api=1)
V/PhoneWindow(10137): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@dde1be8, this = DecorView@fc78285[MainActivity]

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by DevyankShaw** [comment]
Replace your main method with the below one:  
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MaterialApp(home: MyApp()));
}
```

**Comment by DenizKucukozturk** [comment]
> Replace your main method with the below one:
> 
> ```
> Future<void> main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp();
>   runApp(MaterialApp(home: MyApp()));
> }
> ```

I still get the same exact error, doesn't work

**Comment by DevyankShaw** [comment]
> > Replace your main method with the below one:
> > ```
> > Future<void> main() async {
> >   WidgetsFlutterBinding.ensureInitialized();
> >   await Firebase.initializeApp();
> >   runApp(MaterialApp(home: MyApp()));
> > }
> > ```
> 
> I still get the same exact error, doesn't work

Kindly share the logs now after replacing with the above snippet.

**Comment by DenizKucukozturk** [comment]
> > > Replace your main method with the below one:
> > > ```
> > > Future<void> main() async {
> > >   WidgetsFlutterBinding.ensureInitialized();
> > >   await Firebase.initializeApp();
> > >   runApp(MaterialApp(home: MyApp()));
> > > }
> > > ```
> > 
> > 
> > I still get the same exact error, doesn't work
> 
> Kindly share the logs now after replacing with the above snippet.

errors are exactly same but here you go 
<details><summary>Click To Expand</summary>

```
/flutter ( 2151): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter ( 2151): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter ( 2151): <asynchronous suspension>
E/flutter ( 2151): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter ( 2151): #2      MethodChannel.invokeListMethod
package:flutter/…/services/platform_channel.dart:345
E/flutter ( 2151): #3      MethodChannelFirebase._initializeCore
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:30
E/flutter ( 2151): #4      MethodChannelFirebase.initializeApp
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:75
E/flutter ( 2151): #5      Firebase.initializeApp
package:firebase_core/src/firebase.dart:43
E/flutter ( 2151): #6      main
package:new_project/main.dart:7
E/flutter ( 2151): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 2151): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 2151): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 2151): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 2151): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 2151): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 2151): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 2151): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 2151):


```
</details>

**Comment by saisantosh2095** [comment]
I am facing a similar issue.
I am uploading videos to server using a background service. All other firebase functionalities are working fine (auth, storage, firestore, firebase database) but while using it in background service it throws the following exception

`E/flutter (20277): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)

E/flutter (20277): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (20277): asynchronous suspension

E/flutter (20277): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)

E/flutter (20277): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)

E/flutter (20277): #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)

E/flutter (20277): #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)

E/flutter (20277): #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)

E/flutter (20277): #6      uploadParticipation (package:hunt/components/videoPlayer/CallbackDispatcher.dart:357:20)

E/flutter (20277): #7      uploadImage (package:hunt/components/videoPlayer/CallbackDispatcher.dart:350:12)

E/flutter (20277): asynchronous suspension

E/flutter (20277): #8      processImageService (package:uploader/components/videoPlayer/CallbackDispatcher.dart:261:24)

E/flutter (20277): #9      _rootRunUnary (dart:async/zone.dart:1198:47)

E/flutter (20277): #10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)

E/flutter (20277): #11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)

E/flutter (20277): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)

E/flutter (20277): #13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)

E/flutter (20277): #14     Future._completeWithValue (dart:async/future_impl.dart:529:5)

E/flutter (20277): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)

E/flutter (20277): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)

E/flutter (20277): #17     processImage (package:uploader/components/videoPlayer/CallbackDispatcher.dart)

E/flutter (20277): #18     _rootRunUnary (dart:async/zone.dart:1198:47)

E/flutter (20277): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)

E/flutter (20277): #20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)

E/flutter (20277): #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)

E/flutter (20277): #22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)

E/flutter (20277): #23     Future._completeWithValue (dart:async/future_impl.dart:529:5)

E/flutter (20277): #24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)

E/flutter (20277): #25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)

E/flutter (20277): #26     FlutterFFmpeg.executeWithArguments (package:flutter_ffmpeg/flutter_ffmpeg.dart)

E/flutter (20277): #27     _rootRunUnary (dart:async/zone.dart:1198:47)

E/flutter (20277): #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)

E/flutter (20277): #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)

E/flutter (20277): #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)

E/flutter (20277): #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)

E/flutter (20277): #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)

E/flutter (20277): #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)

E/flutter (20277): #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)

E/flutter (20277): #35     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)

E/flutter (20277): #36     _rootRunUnary (dart:async/zone.dart:1198:47)

E/flutter (20277): #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)

E/flutter (20277): #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)

E/flutter (20277): #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)

E/flutter (20277): #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)

E/flutter (20277): #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)

E/flutter (20277): #42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)

E/flutter (20277): #43     _rootRun (dart:async/zone.dart:1190:13)

E/flutter (20277): #44     _CustomZone.run (dart:async/zone.dart:1093:19)

E/flutter (20277): #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)

E/flutter (20277): #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)

E/flutter (20277): #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)

E/flutter (20277): #48     _startMicrotaskLoop (dart:async/sched`

**Comment by saisantosh2095** [comment]
I am facing a similar issue.
I am uploading videos to server using a background service. All other firebase functionalities are working fine (auth, storage, firestore, firebase database) but while using it in background service it throws the following exception

`E/flutter (20277): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (20277): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (20277): <asynchronous suspension>
E/flutter (20277): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (20277): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter (20277): #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter (20277): #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter (20277): #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)
E/flutter (20277): #6      uploadParticipation (package:hunt/components/videoPlayer/CallbackDispatcher.dart:357:20)
E/flutter (20277): #7      uploadImage (package:hunt/components/videoPlayer/CallbackDispatcher.dart:350:12)
E/flutter (20277): <asynchronous suspension>
E/flutter (20277): #8      processImageService (package:hunt/components/videoPlayer/CallbackDispatcher.dart:261:24)
E/flutter (20277): #9      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20277): #10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20277): #11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20277): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20277): #13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20277): #14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20277): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (20277): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (20277): #17     processImage (package:hunt/components/videoPlayer/CallbackDispatcher.dart)
E/flutter (20277): #18     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20277): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20277): #20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20277): #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20277): #22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20277): #23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20277): #24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (20277): #25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (20277): #26     FlutterFFmpeg.executeWithArguments (package:flutter_ffmpeg/flutter_ffmpeg.dart)
E/flutter (20277): #27     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20277): #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20277): #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20277): #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20277): #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20277): #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20277): #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (20277): #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (20277): #35     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (20277): #36     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20277): #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20277): #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20277): #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20277): #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20277): #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (20277): #42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (20277): #43     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (20277): #44     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20277): #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (20277): #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (20277): #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (20277): #48     _startMicrotaskLoop (dart:async/sched`

**Comment by DevyankShaw** [comment]
Have @saisantosh2095 and @DenizKucukozturk both of you added the firebase_core plugin with the latest version?

**Comment by saisantosh2095** [comment]
Hi @DevyankShaw, these are the firebase plugin versions I am using.
```
firebase_auth: 0.18.2
cloud_firestore: 0.14.2
firebase_database: 4.2.0
firebase_storage: 5.0.0
firebase_core: 0.5.1
firebase_messaging: 7.0.3
firebase_remote_config: 0.4.1
firebase_crashlytics: 0.2.2
firebase_analytics: 6.1.0
firebase_dynamic_links: 0.6.1

**Comment by DevyankShaw** [comment]
> Hi @DevyankShaw, these are the firebase plugin versions I am using.
> 
> ```
> firebase_auth: 0.18.2
> cloud_firestore: 0.14.2
> firebase_database: 4.2.0
> firebase_storage: 5.0.0
> firebase_core: 0.5.1
> firebase_messaging: 7.0.3
> firebase_remote_config: 0.4.1
> firebase_crashlytics: 0.2.2
> firebase_analytics: 6.1.0
> firebase_dynamic_links: 0.6.1
> ```

Try the below commands:
- flutter clean
- flutter run

-

**Comment by saisantosh2095** [comment]
> > Hi @DevyankShaw, these are the firebase plugin versions I am using.
> > ```
> > firebase_auth: 0.18.2
> > cloud_firestore: 0.14.2
> > firebase_database: 4.2.0
> > firebase_storage: 5.0.0
> > firebase_core: 0.5.1
> > firebase_messaging: 7.0.3
> > firebase_remote_config: 0.4.1
> > firebase_crashlytics: 0.2.2
> > firebase_analytics: 6.1.0
> > firebase_dynamic_links: 0.6.1
> > ```
> 
> Try the below commands:
> 
> * flutter clean
> * flutter run

Tried this, no use. Firebase throws exception when I implement an android function in MainActivity.kt or MainActivity.java

**Comment by virgule-xyz** [comment]
I face the same problem.

The Flutter log gives this group as the start of fault :

```
/// Calls the native Firebase#initializeCore method.
  ///
  /// Before any plugins can be consumed, any platforms using the [MethodChannel]
  /// can use initializeCore method to return any initialization data, such as
  /// any Firebase apps created natively and any constants which are required
  /// for a plugin to function correctly before usage.
  Future<void> _initializeCore() async {
    List<Map> apps = await channel.invokeListMethod<Map>(
      'Firebase#initializeCore',
    );

    apps.forEach(_initializeFirebaseAppFromMap);
    isCoreInitialized = true;
  }
```

in method_channel_firebase.dart

Is this helping you ?

**Comment by danielgchap** [comment]
I am now experience this on Android release builds....
Thanks

`E/flutter (26814): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (26814): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)
E/flutter (26814): <asynchronous suspension>
E/flutter (26814): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345)
E/flutter (26814): <asynchronous suspension>
E/flutter (26814): #2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30)
E/flutter (26814): <asynchronous suspension>
E/flutter (26814): #3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75)
E/flutter (26814): <asynchronous suspension>
E/flutter (26814): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43)
E/flutter (26814): <asynchronous suspension>
E/flutter (26814): #5      main (package:instapray/main.dart:20)
E/flutter (26814): <asynchronous suspension>
E/flutter (26814): 
`

**Comment by Renkon117** [comment]
adding  `multiDexEnabled true` to app/build.gradle file solved problem for me

```
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.yourapp.path"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }
```

**Comment by devj3ns** [comment]
Thankfully I got it fixed for me! (Flutter Channel beta, 1.25.0-8.1.pre)

**My Solution:**
I changed the Gradle versions to the following:

```classpath 'com.android.tools.build:gradle:3.6.4'``` in android/build.gradle

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip`  in  android/gradle/wrapper/gradle-wrapper.properties 

Version 3.5.4 and 3.6.0 in android/build.gradle work as well, 4.0.0 and above don't work.

**Comment by russellwheatley** [comment]
Hey @DenizKucukozturk, are you still experiencing this issue on the latest version of `firebase_core` `1.3.0`?

**Comment by moxran** [comment]
I got the same error message, I restarted the android studio and it's gone.

**Comment by russellwheatley** [comment]
Considering the lack of activity, I'm going to assume that this is no longer an issue. Please open a new issue if you believe you have found a problem that requires attention with the latest version of `firebase_core`.
