### ISSUE TITLE
FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#402]
Note: C:\Tools\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-2.0.2+1\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by kroikie** [comment]
@kw2019ltd

The issue at https://github.com/flutter/flutter/issues/28771 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @kw2019ltd
are you still experiencing this issue with the latest version of Flutter and [firebase_analytics](https://pub.dev/packages/firebase_analytics)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you"

**Comment by kw2019ltd** [comment]
you can close it now its fine now

**Comment by BondarenkoStas** [comment]
@kw2019ltd was it solved by using more recent firebase_analytics?
