### ISSUE TITLE
FirebaseCorePlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#403]
Note: C:\Tools\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.1+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by jayant07** [comment]
hey you closed the issue. Could you tell me how you fixed it?

**Comment by cmonney** [comment]
@jayant07 the solution specified on https://github.com/flutter/flutter/issues/28770 worked for me.
