### ISSUE TITLE
🐛 [firebase_messaging 8.0.0-dev.5]  firebase_messaging 8.0.0-dev.5 not receiving notifications in ios simulator

### ISSUE THREAD

**Issue by mo-ah-dawood** [FirebaseExtended/flutterfire#4038]
## Bug report

**Describe the bug**
firebase_messaging 8.0.0-dev.5  not receiving  notifications in ios simulator and token not come in android emulator

### Steps to reproduce

- Set up notifications as explained  in docs
- run application in ios simulator IPhone 11 pro max & IPhone 12
- Get token => success
- liten onMessage stream
- Send notification from firebase console
- Not receiving any thing
- Sets app in background
- No headup notification 

- tested the same code in android emulator
- token take to long time to come and after while throw an error that cannot conver hashmap to string

-tested the same code in android device 
-every thing works fine

**Comment by RenanDelfanti** [comment]
Same here

**Comment by Ehesp** [comment]
Notifications don't work on a simulator on iOS, you need a real device. One of the restrictions Apple (randomly) puts in place. I'll make this more obvious in docs.

**Comment by RenanDelfanti** [comment]
@Ehesp Yes, it doesn't work.
But in the previous version of this pluging it appeared in the logs.

**Comment by RenanDelfanti** [comment]
![Captura de tela 2020-11-05 103438](https://user-images.githubusercontent.com/8375899/98247581-8e4b2200-1f52-11eb-86fc-09b3cbb244e5.jpg)

**Comment by Ehesp** [comment]
Ok so that worked via direct channels to FCM (think of it as a websocket) while the app is open, which allowed messages to be received while the app is open. In the latest Firebase SDKs they have removed this, and now everything goes via APNs, hence why you don't see messages in the foreground on a simulator anymore.

**Comment by Ehesp** [comment]
Going to close as working as expected - for the crashes, can you please make a new issue following the template with example code/payload etc, Cheers
