### ISSUE TITLE
🐛 [FirebaseCrashlytics] Flutter Errors are catched only in release mode

### ISSUE THREAD

**Issue by salim-lachdhaf** [FirebaseExtended/flutterfire#4041]
catching Flutter errors (like `StateError`) should works in both Release and debug mode, but it works ALWAYS  only in release mode !

i already added this:
 ```
// Pass all uncaught errors to Crashlytics.
  Function originalOnError = FlutterError.onError;
  FlutterError.onError = (FlutterErrorDetails errorDetails) async {
    await FirebaseCrashlytics.instance.recordFlutterError(errorDetails);
    // Forward to original handler.
    originalOnError(errorDetails);
  };
```

**Comment by markusaksli-nc** [comment]
Hi @salim-lachdhaf 
Can you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by Ehesp** [comment]
Can you check https://firebase.flutter.dev/docs/crashlytics/usage#toggle-crashlytics-collection

**Comment by salim-lachdhaf** [comment]
> [√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [version 6.1.7601], locale fr-FR)
>     • Flutter version 1.22.1 at E:\SDK\FlutterSDK
>     • Framework revision f30b7f4db9 (4 weeks ago), 2020-10-08 10:06:30 -0700
>     • Engine revision 75bef9f6c8
>     • Dart version 2.10.1
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at E:\SDK\Android\Sdk
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_HOME = E:\SDK\Android\Sdk
>     • ANDROID_SDK_ROOT = E:\SDK\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 50.0.1
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] Connected device (1 available)
>     • SM T813 (mobile) • 64fd402f04e9bba0 • android-arm64 • Android 7.0 (API 24)
> 
> • No issues found!

> 
> Dart SDK 2.10.1
> Flutter SDK 1.22.1
> flutter_hm2 2.0.15+20
> 
> dependencies:
> - barcode_flutter 1.1.2 [flutter]
> - cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
> - cupertino_icons 1.0.0
> - device_info 1.0.0 [flutter device_info_platform_interface]
> - dropdown_search 0.4.6 [flutter]
> - esys_flutter_share 1.0.2 [flutter path_provider]
> - exif 1.0.3 [args collection convert sprintf]
> - firebase_core 0.5.1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
> - firebase_crashlytics 0.2.2 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
> - flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
> - flutter_barcode_scanner 1.0.1 [flutter flutter_plugin_android_lifecycle]
> - flutter_launcher_icons 0.8.1 [image args yaml path]
> - fluttertoast 7.1.1 [flutter flutter_web_plugins]
> - ftpconnect 0.1.6 [archive path flutter]
> - http 0.12.2 [http_parser path pedantic]
> - image 2.1.18 [archive xml meta]
> - image_cropper 1.3.1 [flutter]
> - image_picker 0.6.7+12 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
> - intl 0.16.1 [path]
> - json_annotation 3.1.0
> - modal_progress_hud 0.1.3 [flutter]
> - multi_image_picker 4.7.14 [flutter meta]
> - native_state 1.1.1 [flutter]
> - package_info 0.4.3+2 [flutter]
> - percent_indicator 2.1.8 [flutter]
> - preferences 5.2.1 [flutter shared_preferences]
> - reorderables 0.3.2 [flutter]
> - shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
> - uuid 2.2.2 [crypto convert]
> - xml 4.5.1 [collection convert meta petitparser]
> - xml2json 4.4.0 [xml]
> 
> dev dependencies:
> - build_runner 1.10.4 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging
>  meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
> - flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string
> _scanner term_glyph typed_data]
> - json_serializable 3.5.0 [analyzer build build_config json_annotation meta path source_gen]
> 
> transitive dependencies:
> - _fe_analyzer_shared 12.0.0 [meta]
> - analyzer 0.40.6 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
> - archive 2.0.13 [crypto args path]
> - args 1.6.0
> - async 2.5.0-nullsafety.1 [collection]
> - boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
> - build 1.5.0 [analyzer async convert crypto logging meta path glob]
> - build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
> - build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
> - build_resolvers 1.4.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
> - build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher y
> aml]
> - built_collection 4.3.2 [collection quiver]
> - built_value 7.1.0 [built_collection collection fixnum quiver]
> - characters 1.1.0-nullsafety.3
> - charcode 1.2.0-nullsafety.1
> - checked_yaml 1.0.2 [json_annotation source_span yaml]
> - cli_util 0.2.0 [path]
> - clock 1.1.0-nullsafety.1
> - code_builder 3.5.0 [built_collection built_value collection matcher meta]
> - collection 1.15.0-nullsafety.3
> - convert 2.1.1 [charcode typed_data]
> - crypto 2.1.5 [collection convert typed_data]
> - dart_style 1.3.9 [analyzer args path source_span]
> - device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
> - fake_async 1.2.0-nullsafety.1 [clock collection]
> - ffi 0.1.3
> - file 5.2.1 [intl meta path]
> - firebase 7.3.2 [http http_parser js]
> - firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
> - firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
> - firebase_crashlytics_platform_interface 1.1.2 [flutter meta collection firebase_core plugin_platform_interface]
> - fixnum 0.10.11
> - flutter_blurhash 0.5.0 [flutter meta]
> - flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
> - flutter_plugin_android_lifecycle 1.0.11 [flutter]
> - flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
> - glob 1.2.0 [async collection node_io path pedantic string_scanner]
> - graphs 0.2.0
> - http_multi_server 2.2.0 [async]
> - http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
> - image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
> - io 0.3.4 [charcode meta path string_scanner]
> - js 0.6.2
> - logging 0.11.4
> - matcher 0.12.10-nullsafety.1 [stack_trace]
> - meta 1.3.0-nullsafety.3
> - mime 0.9.7
> - node_interop 1.2.0 [js]
> - node_io 1.1.1 [node_interop path]
> - octo_image 0.3.0 [flutter flutter_blurhash]
> - package_config 1.9.3 [path charcode]
> - path 1.8.0-nullsafety.1
> - path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
> - path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
> - path_provider_macos 0.0.4+6 [flutter]
> - path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
> - path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
> - pedantic 1.9.2 [meta]
> - petitparser 3.1.0 [meta]
> - platform 2.2.1
> - plugin_platform_interface 1.0.3 [meta]
> - pool 1.4.0 [async stack_trace]
> - process 3.0.13 [file intl meta path platform]
> - pub_semver 1.4.4 [collection]
> - pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
> - quiver 2.1.4+1 [matcher meta]
> - rxdart 0.24.1
> - shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
> - shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
> - shared_preferences_platform_interface 1.0.4 [meta flutter]
> - shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
> - shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
> - shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
> - shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
> - sky_engine 0.0.99
> - source_gen 0.9.8 [analyzer async build dart_style glob meta path pedantic source_span]
> - source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
> - sprintf 4.1.0
> - sqflite 1.3.1+2 [flutter sqflite_common path]
> - sqflite_common 1.0.2+1 [synchronized path meta]
> - stack_trace 1.10.0-nullsafety.1 [path]
> - stream_channel 2.1.0-nullsafety.1 [async]
> - stream_transform 1.2.0
> - string_scanner 1.1.0-nullsafety.1 [charcode source_span]
> - synchronized 2.2.0+2
> - term_glyph 1.2.0-nullsafety.1
> - test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
> - timing 0.1.1+2 [json_annotation]
> - typed_data 1.3.0-nullsafety.3 [collection]
> - vector_math 2.1.0-nullsafety.3
> - watcher 0.9.7+15 [async path pedantic]
> - web_socket_channel 1.1.0 [async crypto stream_channel]
> - win32 1.7.3 [ffi]
> - xdg_directories 0.1.2 [meta path process]
> - yaml 2.2.1 [charcode collection string_scanner source_span]
