### ISSUE TITLE
🐛 [firebase_analytics] first_open event is being fired many times by same app instance

### ISSUE THREAD

**Issue by alectogeek** [FirebaseExtended/flutterfire#4045]
## Bug report
I'm comparing data from different analytics services and see that first_open in firebase_analytics is duplicated (or even worse).
For example, in Android:
```
First_open: 1 Nov (comparison with appsFlyer):
AppsFlyer 267
Firebase 475

First_open: 1 Nov (comparison with google ads considering compaign)
Google Ads report: 122
Firebase (Audience: adsCompaign): 231 
```
So the difference is up to 47 percent!

Then I went to BigQuery and tried to understand what is going on.

My query was:
```
SELECT user_pseudo_id FROM `analytics_210753586.*`, UNNEST(user_properties) AS user_properties, UNNEST(event_params) AS event_params  
WHERE 
  event_name = 'first_open' AND
  user_properties.key = "first_open_time" 
  AND CAST(user_properties.value.int_value AS int64) BETWEEN 1604098800000 AND 1604185200000
  AND device.operating_system = 'ANDROID'
```
and I could see that the first_open event is duplicated 7 times each! For iOS the duplication is 6 times for each. But here I'm not sure if my query is correct.

My custom events sending using `FirebaseAnalytics().logEvent()` seems to be ok.

Firebase analytics package version is firebase_analytics 6.0.1 for android and 6.1.0 for iOS.

### Flutter doctor
<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

• No issues found!

```

</details>

**Comment by markusaksli-nc** [comment]
Strange, I get 1 event for every device when testing with the latest flutter master `1.24.0-8.0.pre.113` and `firebase_analytics: ^6.1.0` using the official example.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.113, on Microsoft Windows [Version 10.0.19041.572], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.113 at C:\Development\flutter_master
    • Framework revision a75b5b6c8f (4 hours ago), 2020-11-06 01:19:02 -0500
    • Engine revision 0693ee04d1
    • Dart version 2.12.0 (build 2.12.0-21.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 86.0.622.61

• No issues found!
```
</details>

Are you sure the baseline for AppsFlyer is correct? Is the event exactly the same?

**Comment by alectogeek** [comment]
In AppsFlyer I use my custom event which I report in my main function. I added the same custom event for firebase, so looking forward to further results. Will notify you about my observes.

**Comment by alectogeek** [comment]
So, I did an additional investigation and I found some interesting facts. 
I compared data from the firebase dashboard, BigQuery, and AppsFlyer.

First I compared the range from 3 to 9 November for the android platform:

> firebase - 1442
> BQ - 863
> appsFlyer - 847
> GP console -  668

Then I tried to compare a bit larger range using one additional event. Here is data from 3 sources with some screenshots:

From Oktober 20 to Oktober 30 from BigQuery:
> first_open - 3156
> user_swiped_1_section - 3139

![image](https://user-images.githubusercontent.com/18165303/98708585-9dcad080-2381-11eb-98fe-fab8aae371b4.png)

From Oktober 20 to Oktober 30 from Firebase dashboard:
> first_open - 5530
> user_swiped_1_section - 3158

![image](https://user-images.githubusercontent.com/18165303/98708603-a4594800-2381-11eb-9b39-1aadeaae246b.png)

> GP installs 20 - 30 Oktober:
> 3307

How is that possible that the firebase dashboard show way more first_open events even in comparison with BigQuery?

**Comment by Ctrl-X** [comment]
As far as I can tell, it seems that `first_open`  is fired one time after each app update. 

I created a Firebase analytics account that I only use for testing, so I can track what's going on.

When I update my app in the appStore/playStore ,  `first_open` is fired again and even worst :  `first_open_time` is reset to the current `first_open` timestamp .

IT doesn't keep track of the all time `first_open_time`.

So I had to create a specific event to keep track of the all time first open ( called it _all_time_first_launch_)

Hope this could help investigation...

**Comment by russellwheatley** [comment]
Hey folks, this issue is something to be addressed by the firebase analytics SDK directly for either the `firebase-android-sdk` or `firebase-ios-sdk` repositories. These events are automatically fired and Flutterfire has no control over them. Here's a [useful page](https://support.google.com/firebase/answer/9234069?visit_id=637757733767611784-1324655723&rd=1) found via Firebase Analytics official documentation which describes what to expect for automatic events.
