### ISSUE TITLE
🐛 [firebase_dynamic_links] Clipboard notification on app start in iOS 14

### ISSUE THREAD

**Issue by justinmc** [FirebaseExtended/flutterfire#4051]
## Bug report

On iOS 14, when an app that's using firebase_dynamic_links is started, a notification will be displayed that the app has pasted from the clipboard.

This is a new security feature of iOS 14.  It's likely unavoidable for firebase_dynamic_links based on my understanding.  Just wanted to make sure that the team is aware in case there's anything to do here, otherwise you can close this.

### Steps to reproduce

1. Start any app using firebase_dynamic_links on an iOS 14 device.
2. The notification will be shown.

### Expected behavior

Some users may 

## Additional context

This came up in the Flutter repo: https://github.com/flutter/flutter/issues/60145#issuecomment-723009975

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.102, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!
```

</details>

---

**Comment by omatt** [comment]
To add context, iOS FDL SDK checks pasteboard for Dynamic Links for a reliable FDL flow https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages

The clipboard/pasteboard notification doesn't have functional impact apart from the possibility of creating a bad impression to the user.

More info:
https://github.com/firebase/firebase-ios-sdk/issues/5893#issuecomment-657724741

**Comment by markusaksli-nc** [comment]
Does this happen only on the first time or something? I'm not seeing this on the latest flutter master `1.24.0-8.0.pre.149` running a slightly modified version of the official example on iOS 14.1 physical.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.149, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.149 at /Users/markus/development/flutter_master
    • Framework revision 8e7748e74c (11 hours ago), 2020-11-08 20:32:04 -0800
    • Engine revision 0f7cdca65f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (5 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.1
    • iPhone 12 Pro Max (mobile)  • 1C7EE787-1EC9-427C-AFEE-224EF736BBCA     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 86.0.4240.183
    ! Error: Nevercode’s iPhone is busy: Copying cache files from device. Xcode will continue when Nevercode’s iPhone is finished. (code -10)

• No issues found!
```
</details>

```
  firebase_core: ^0.5.2
  firebase_dynamic_links: ^0.6.2
  url_launcher: ^5.7.10
```

**Comment by markusaksli-nc** [comment]
Nevermind, the official response was in the [linked comment](https://github.com/firebase/firebase-ios-sdk/issues/5893#issuecomment-657724741).

> During the very first launch of the app (post-install), FDL sdk will check the pasteboard to see whether the app was installed as a result of clicking on an FDL.
> 
> It is possible that some apps might have misconfigured their FDL integration, where the pasteboard is checked at every app launch. This happens when the app fails to call dynamicLinkFromCustomSchemeURL method described in FDL docs.

Though this would indicate that the notification shouldn't show up multiple times?

**Comment by benPesso** [comment]
This video shows how popular apps (though not necessarily Flutter-based) have the same issue (due to using the Dynamic Links library): https://youtu.be/pRSWdtoUAjo

As you can see, it is triggered on every launch of the app. I would imagine Flutter's library is not much different than this.

Besides that, even it only happens on the first launch - that's a problem that should be fixed. 😉

**Comment by russellwheatley** [comment]
I believe [this issue](https://github.com/flutter/flutter/issues/60145) has been resolved now so we can close it out.
