### ISSUE TITLE
FirebaseAuth login with custom token gives me ERROR_INTERNAL_ERROR on ios

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#406]
On Android it works fine, but on iOS I get this:

```
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={error_name=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x280038930 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 400;
    errors =     (
                {
            domain = global;
            message = "API key not valid. Please pass a valid API key.";
            reason = badRequest;
        }
    );
    message = "API key not valid. Please pass a valid API key.";
    status = "INVALID_ARGUMENT";
}}}}
```

**Comment by kroikie** [comment]
@long1eu

The issue at https://github.com/flutter/flutter/issues/28631 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @long1eu
are you still experiencing this issue with the latest version of Flutter and [firebase_auth](https://pub.dev/packages/firebase_auth)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
