### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by SimonDziak** [FirebaseExtended/flutterfire#4066]
I am having a problem with the integration to iOS devices. Text detection is not working properly. It is detecting text incorrectly or not at all. The same code works perfectly on Android Emulator.

**Comment by bdlukaa** [comment]
Can you please tell us more information? Which plugin are you using?

**Comment by SimonDziak** [comment]
Firebase ML Vision

**Comment by darshankawar** [comment]
@SimonDziak 
Please provide `flutter doctor -v`. Can you try the official `ml_vision` plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example) and see if you get same issue ?

**Comment by SimonDziak** [comment]
I fixed the problem. The issue is in your plugin and specifically the way iOS takes pictures. To solve the problem with the orientation of the device.

**Comment by darshankawar** [comment]
Closing this as resolved. If you have specific / similar issue in the plugin. Feel free to write in comment or open a new issue.
thanks.
