### ISSUE TITLE
[📚] Setup steps should clearly mention to ignore/not ignore the firebase console setup steps

### ISSUE THREAD

**Issue by nt4f04uNd** [FirebaseExtended/flutterfire#4093]
The current documentation says to modify the `build.gradle` only in the "Getting Started" section. But when I create the application in the firebase, there's more lines of code that firebase says to me to add there. That's confusing to me - so, have I to put these lines in there or not?

![image](https://user-images.githubusercontent.com/39104740/98821286-68d18300-2440-11eb-9b4b-a85deb51d64d.png)

The same applies to the `Podfile` on iOS

![image](https://user-images.githubusercontent.com/39104740/98821455-a33b2000-2440-11eb-9ced-567edfa2a38e.png)

**Comment by Tihan-Nico** [comment]
Is it in the FlutterFire documentation or in the official Firebase documentation?

**Comment by nt4f04uNd** [comment]
@TahaTesser I had to be more straightforward

There's a FlutterFire docs that have the steps to enable the anylitcs described here https://firebase.flutter.dev/docs/analytics/overview
Also, there are basic plugin setup described here https://firebase.flutter.dev/docs/overview

But if you create an application in the firebase console, there's a few additional instructions they give you, that you can see on the screenshots above.

So are they valid, are they not? Are they redundant or are they required?

**Comment by Tihan-Nico** [comment]
@nt4f04uNd Ok I understand what you trying to ask now.

The answer to your question is NO. The console setup is invalid when your working with flutter the only time you will follow the Firebase console setup is when your creating a native application on Android/iOS.

If you're creating a new flutter app and your using firebase the only thing you need to add in your gradle files are the following.
In your `android/build.gradle` you add the following.
`buildscript {

    repositories {
      // Check that you have the following line (if not, add it):
      google()  // Google's Maven repository
    }

    // ...

    dependencies {
      // ...

      // Add the following line:
      classpath 'com.google.gms:google-services:4.3.4'  // Google Services plugin
    }
}

allprojects {
    // ...

    repositories {
      // Check that you have following line (if not, add it):
      google()  // Google's Maven repository
      // ...
    }
}`

In your module (app-level) Gradle file (usually `android/app/build.gradle`), apply the Google Services Gradle plugin.
`// Add the following line:
apply plugin: 'com.google.gms.google-services'  // Google Services plugin

android {
  // ...
}`

When you want to add firebase libraries to your flutter app you add them in your `pubspec.yaml` file. Keep in mind to always add your `firebase_core: ^verion` library to your  `pubspec.yaml` file. Another thing to keep in mind is that the firebase libraries used in your flutter app should correspond accordingly with each other.

Links for if you need help or get stuck

FlutterFire migration guide:
https://firebase.flutter.dev/docs/migration/

Add Firebase to your Flutter app:
https://firebase.google.com/docs/flutter/setup?platform=android

**Comment by nt4f04uNd** [comment]
I just tried doing following only the steps from flutter fire documentation. It won't work and you still need to add classpath/apply/implementation, at least for crashlytics. I haven't tested the others

**Comment by Salakar** [comment]
Please use the official Flutter specific documentation for Firebase here: https://firebase.flutter.dev/docs/overview
