### ISSUE TITLE
🐛 [cloud_firestore_web] Failed to save inner Timestamp (timestamp in a map in a list)

### ISSUE THREAD

**Issue by alextekartik** [FirebaseExtended/flutterfire#4132]
## Bug report

* Fail to save timestamp if its value is in a map itself in a list

### Steps to reproduce

1. Try to save (firestore.set) the following object:

```dart
{
  'list': [
    {'timestamp': Timestamp(1, 2)}
  ]
}
```
2. Error: `[cloud_firestore/unknown] Invalid argument (dartObject): Could not convert: Instance of 'DateTime'`
3. It only fails on the Web

### Expected behavior

It should save correctly

---

## Additional context

Saving an object like this works though:

```dart
{
    'timestamp': Timestamp(1, 2)
}
```

One issue is that Timestamp are converted to DateTime (loosing some precision) and firebase web implementation does not support timestamp correctly (it converts everything to date time)

One solution would be to a have a real Timestamp type (like Blob) in firebase browser implementation.

**Comment by alextekartik** [comment]
It appears my report is incorrect. We only loose the microsecond precision

**Comment by alextekartik** [comment]
After more testing, it does indeed fail. It only fails on the Web.

We can save an object like this

```dart
{
    'timestamp': Timestamp(1, 2)
}
```

but not

```dart
{
    'timestamp': [Timestamp(1, 2)]
}
```

**Comment by markusaksli-nc** [comment]
Hi @alextekartik 
This was previously https://github.com/FirebaseExtended/flutterfire/issues/4063 and has already been fixed.
Closing this as a duplicate.
Thank you
