### ISSUE TITLE
Adding display name and phone number to firebase auth

### ISSUE THREAD

**Issue by Petersvictor** [FirebaseExtended/flutterfire#4134]
How can i add display name and phone number to firebase auth and also be able to edit them

**Comment by markusaksli-nc** [comment]
Hi @Petersvictor 
Please take a look at [User](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User-class.html) ([User.updateProfile](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User/updateProfile.html) and [User.updatePhoneNumber](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/User/updatePhoneNumber.html)).
Does this solve the issue for you?
Thank you
