### ISSUE TITLE
[firebase_admob] how does "nonPersonalizedAds: false" work in MobileAdTargetingInfo class? 

### ISSUE THREAD

**Issue by badranmo** [FirebaseExtended/flutterfire#4137]
if nonPersonalizedAds is set to false or true  in MobileAdTargetingInfo, will it override the settings in the admob console under blocking controls  EU Consent section of the admob console  or the settings in the console overrides this setting in the code? I didn't find anything in the documentation that explains this part. Due to legal impacts in the EU may you please help with a clarification? I have opened a request previously (issues/3540 with the link below) without an answer since several weeks, please help. My target is to allow users to choose from the app settings personalized or non personalized Ads.

https://github.com/FirebaseExtended/flutterfire/issues/3540

![image](https://user-images.githubusercontent.com/54552866/99366311-1c16fd80-28c1-11eb-8a91-54e9939d664e.png)

**Comment by markusaksli-nc** [comment]
Hi @badranmo 
Sorry to see your question has gone without attention for so long. I can't actually find any reference to this parameter in the native Firebase SDKs.
I'm still going to have to close this issue as a dupliacate of #3450 but I'll try to get an answer.
Thank you
