### ISSUE TITLE
🐛 [firebase_crashlytics] Facing problem to upgrade latest version firebase_crashlytics 0.2.3

### ISSUE THREAD

**Issue by SwapnilDhotre** [FirebaseExtended/flutterfire#4144]
## Bug report

**Describe the bug**
When I updated firebase crashlytics to latest version it prints below logs. In dependencies I have only firebase_crashlytics so there could not be any other dependency conflict. In long logs I found below to be important one add below.

[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
In snapshot (Podfile.lock):
Firebase/CoreOnly (= 6.34.0)

In Podfile:
firebase_core (from .symlinks/plugins/firebase_core/ios) was resolved to 0.5.2, which depends on
Firebase/CoreOnly (~> 6.33.0)

You have either:

out-of-date source repos which you can update with pod repo update or with pod install --repo-update.
changed the constraints of dependency Firebase/CoreOnly inside your development pod firebase_core.
You should run pod update Firebase/CoreOnly to apply changes you've made.

Full logs
[ErrorLogs.txt](https://github.com/FirebaseExtended/flutterfire/files/5560893/ErrorLogs.txt)

### Steps to reproduce

1. Go to 'pubspec.yaml'
2. Just add 'firebase_crashlytics: 0.2.3' which is the latest available for now

### Expected behavior

Should resolve firebase_core internal dependencies automatically.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.1 19B88, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.9.2
Flutter SDK 1.20.4
flutter_cmms 1.1.0+2

dependencies:
- app_font_awesome 0.0.1 [flutter]
- archive 2.0.13 [crypto args path]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- connectivity 0.4.9+5 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cookie_jar 1.0.1
- couchbase_lite 2.5.1+8 [uuid flutter]
- crypto 2.1.5 [collection convert typed_data]
- csv 4.1.0
- cupertino_icons 0.1.3
- dio 3.0.9 [http_parser path]
- dio_cookie_manager 1.0.0 [cookie_jar dio]
- encrypt 4.1.0 [args asn1lib clock collection crypto pointycastle]
- firebase_crashlytics 0.2.3 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_messaging 6.0.16 [meta platform flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 3.2.0 [flutter bloc provider]
- flutter_downloader 1.4.4 [flutter]
- flutter_inappwebview 4.0.0+4 [flutter uuid mime]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_uploader 1.2.0 [flutter]
- get_it 1.1.0
- http 0.12.2 [http_parser path pedantic]
- intl 0.16.1 [path]
- json_annotation 3.1.0
- libphonenumber 1.0.1 [flutter built_value]
- mailto 0.2.0+3 [meta]
- mediautility 0.0.1 [flutter json_annotation]
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pedantic 1.9.0
- provider 4.3.2+2 [flutter nested collection]
- qr_code_scanner 0.0.13 [flutter]
- rxdart 0.23.1
- scrollable_positioned_list 0.1.8 [flutter meta]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- timezone 0.5.9 [path]
- url_launcher 5.7.6 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- video_thumbnail 0.2.2 [flutter]
- webview_flutter 0.3.24 [flutter]

dev dependencies:
- build_runner 1.10.1 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.0 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 6.0.0 [meta]
- analyzer 0.39.14 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- asn1lib 0.8.1
- async 2.4.2 [collection]
- bloc 3.0.0 [meta rxdart]
- boolean_selector 2.0.0 [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.0.0
- charcode 1.1.3
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.1.4 [path]
- clock 1.0.1 [meta]
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.14.13
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- fake_async 1.1.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.3 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- logging 0.11.4
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.2.0 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.7.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 3.0.4 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.0
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.7.0 [charcode collection meta path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- stream_transform 1.2.0
- string_scanner 1.0.5 [charcode meta source_span]
- synchronized 2.2.0+2
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.2.0 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.0.8
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @SwapnilDhotre 
Things to try:

1. `flutter clean`
2. In `ios` folder `pod install --repo-update`
3. In `ios` folder `rm podfile.lock` and `pod install`
4. If those don't work you can `rm -rf ~/.cocoapods/repos` and `pod setup`

Let me know if any of these solve it for you.
Thank you

**Comment by zainalarifinid** [comment]
hi @markusaksli-nc I have similar problem like this one.
```
!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In snapshot (Podfile.lock):
    Firebase/CoreOnly (= 6.34.0)

  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.3, which depends on
      Firebase/CoreOnly (~> 6.33.0)


You have either:
 * changed the constraints of dependency `Firebase/CoreOnly` inside your development pod `cloud_firestore`.
   You should run `pod update Firebase/CoreOnly` to apply changes you've made.
```
I have try your solution, but it doesn't work.

**Comment by SwapnilDhotre** [comment]
Hi @markusaksli-nc  

Sorry for late reply but I have tried above but issue still persist. For android the same is working fine.

Thanks,
Swapnil

**Comment by markusaksli-nc** [comment]
Have you already tried `You should run pod update Firebase/CoreOnly to apply changes you've made.` as mentioned in the error?

**Comment by SwapnilDhotre** [comment]
@markusaksli-nc ,

Yes I have tried that too.

**Comment by markusaksli-nc** [comment]
What version of CocoaPods are you using?

**Comment by SwapnilDhotre** [comment]
@markusaksli-nc ,

I have cocoapods-1.10.0 in my system.

**Comment by markusaksli-nc** [comment]
Running out of things to try here but `pod update Firebase/Core` could be worth a shot.

**Comment by SwapnilDhotre** [comment]
@markusaksli-nc ,

Tried above cmd prints below logs.

Updating local specs repositories
Analyzing dependencies
firebase_core: Using Firebase SDK version '6.33.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '6.33.0' defined in 'firebase_core'
[!] CDN: trunk Repo update failed - 20 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.1/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.2/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.3/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.4/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.5/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.6/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.0.0-beta.7/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.1.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.1.1/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.2.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.3.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.3.1/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.4.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.5.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.6.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.6.1/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/4.6.2/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/7.0.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/e/7/d/FirebaseCrashlytics/7.1.0/FirebaseCrashlytics.podspec.json Response: Timeout was reached

**Comment by SwapnilDhotre** [comment]
Hi @markusaksli-nc ,

Finally I one solution worked for me is Delete **Pod folder** and **podfile.lock** file and run app again. Then it degrades to **Firebase/CoreOnly (~> 6.33.0)** internally which resolves this issue.

Thanks,
Swapnil
