### ISSUE TITLE
[📚] Error in Application.java in "Optionally handle background messages" (CHANGE ME)

### ISSUE THREAD

**Issue by MauroDiamantino** [FirebaseExtended/flutterfire#4147]
Hello guys, there is an error in the steps to setup the app to process messages in the background. In the second step, you're asked to create a file called _Application.java_ in _<app-name>/android/app/src/main/java/<app-organization-path>/_ and it is given the content to put in there, but there is an error in the following section:
```
@Override
public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
}
```
Which should be changed for:
```
@Override
public void registerWith(PluginRegistry registry) {
  FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
}
```
And the following import should be added at the top:
`import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin;`
Please correct that.

**Comment by markusaksli-nc** [comment]
Closing since this is no longer relevant
