### ISSUE TITLE
🐛 [firestore] After a while I get FirebaseException: cloud_firestore/unauthenticated

### ISSUE THREAD

**Issue by jimmyff** [FirebaseExtended/flutterfire#4170]
After authenticating firebase_auth my app has timer that updates the timestamp in a firestore document every 5 minutes (basically an online indicator). After leaving the app running for a period of time (perhaps 30mins - 1 hour), eventually I get:

`FirebaseException ([cloud_firestore/unauthenticated] The request does not have valid authentication credentials for the operation.)`

I've tried to look in to this but as far as I can tell firebase should manage renewing the authentication token itself?

**Comment by markusaksli-nc** [comment]
Hi @jimmyff 
Could you please provide you `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you
