### ISSUE TITLE
Issue when App Started.

### ISSUE THREAD

**Issue by harshmodi3812** [FirebaseExtended/flutterfire#4174]
Exception thrown while unbinding
W/ConnectionTracker(21568): java.lang.IllegalArgumentException: Service not registered: lp@bb21fbd
W/ConnectionTracker(21568): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
W/ConnectionTracker(21568): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
W/ConnectionTracker(21568): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(21568): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):1)
W/ConnectionTracker(21568): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):2)
W/ConnectionTracker(21568): 	at lq.D(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):10)
W/ConnectionTracker(21568): 	at lc.a(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):2)
W/ConnectionTracker(21568): 	at ee.run(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):3)
W/ConnectionTracker(21568): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(21568): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(21568): 	at ix.run(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):6)

**Comment by marvinJ10** [comment]
HI,
Adding the line below in the dependencies section of the android/app/build.gradle magically gets rid of the above error.
  dependencies {
    //fix  the error: java.lang.IllegalArgumentException: Service not registered: lp@bb21fbd
    implementation 'com.google.android.gms:play-services-basement:17.5.0'    
}

**Comment by harshmodi3812** [comment]
Still Showing error.

W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: lp@dbc75e
        at
android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
        at
android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
        at
ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17
(100406-0):1)
        at
ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17
(100406-0):2)
        at
lq.D(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17
(100406-0):10)
        at
lc.a(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17
(100406-0):2)
        at
ee.run(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17
(100406-0):3)
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at
ix.run(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17
(100406-0):6)

**Comment by MstrZeroOne** [comment]
I have the same error. I'm using the firebase_messaging package. When I send a new notification I get this error;

**Comment by paynekw** [comment]
I'm seeing the same.

**Comment by davidgalarza** [comment]
Any update?

**Comment by harshmodi3812** [comment]
It's solved my error by adding two dependencies in app level build gradle file.  

com.google.android.gms:play-services-basement:17.5.0

com. google. firebase:firebase-analytics:18.0.0.
