### ISSUE TITLE
🐛 [firebase_messaging] if background locator callback is running in background FCM does not work 

### ISSUE THREAD

**Issue by tanvish99** [FirebaseExtended/flutterfire#4177]
## Bug report

**Describe the bug**
When the callback of the background locator starts running in the background the FCM throws this error and notifications are not received on the client's side
W/FirebaseInstanceId(14619): Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.
W/FirebaseInstanceId(14619): Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.
But as soon as the Background locator stops running in the background the FCM starts again and notifications are received

### Expected behavior

The client-side should also receive the notifications when the background locator is running in the background 

---

**Comment by markusaksli-nc** [comment]
Hi @tanvish99 
What do you mean by the background locator callback?
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you
