### ISSUE TITLE
'Application.java is not on the classpath of project app' error

### ISSUE THREAD

**Issue by k0302** [FirebaseExtended/flutterfire#4187]
I'm working on a Flutter app and web where I want to implement device-to-device notification. But I'm having trouble with Application.java file. I inserted the file in the directory as advised, but an error appears on top of the 'Application.java' file saying 'Applicaton.java is not on the classpath of project app...'. I guess it's the only reason I can find why I don't succeed in getting any notification. Is this Application.java file essential? Some tutorials skip this 'Application.java' making part and their apps work nicely. Can I skip only making Application.java file ? What is this Application.java file for?

**Comment by markusaksli-nc** [comment]
Hi @k0302 
The pub page for the messaging plugin already offers an explanation here.

> By default background messaging is not enabled. To handle messages in the background:

This was a step for enabling background messaging in embedding V1. If you are not using background messaging there would be no need for this. It's worth mentioning that this will no longer be necessary in the new version of the plugin (currently prerelease) unless you are still using embedding V1 (which you shouldn't).

Does this answer your question?
Thank you

**Comment by k0302** [comment]
Really? That is the best news I've heard recently.  Hopefully, I hope to use it before my app is finished. Can you tell me when I can use this new version?

**Comment by markusaksli-nc** [comment]
Technically all you need to do is add the new version in your `pubspec.yaml` `firebase_messaging: ^8.0.0-dev.8` but I would also recommend you take a look at the [pub page](https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.8) for an updated example of how to use the plugin, and the [official documentation](https://firebase.flutter.dev/docs/messaging/overview/) for the updated integration steps.

**Comment by k0302** [comment]
Hi, Markus! I tried my best to implement it with new version, but I failed. I create '_firebaseMessagingBackgroundHandler', 'AndroidNotificationChannel', and 'FlutterLocalNotificationsPlugin' at the top level in main.dart as shown on https://firebase.flutter.dev/docs/messaging/usage. After that, I created 'saveTokenToDatabase', 'FirebaseMessaging.onMessage.listen' in my homepage's initState. I can update user's token, but no notification happen. What have I missed? Please let me know.

**Comment by markusaksli-nc** [comment]
Does the [official example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib) not work for you?

**Comment by k0302** [comment]
I tried the official example, but no notification came. When I click the floating button at the bottom, I'm supposed to get a notification, right? My console says 'FCM request for device sent!', but no notification comes and on the 'message stream' button on the screen says 'no message received'. What needs to be done?

**Comment by markusaksli-nc** [comment]
That functionality is set up a bit weird in the example right now. Just use Firebase console or a POST request to FCM to send the notification.

Terminal command
```bash
curl https://fcm.googleapis.com/fcm/send -H "Content-Type:application/json" -X POST -d @send.json -H "Authorization: key=<Your key from firebase console here>"
```
`send.json`
```json
{
  "notification": {
    "body": "this is a body",
    "title": "this is a title"
  },
  "priority": "normal",
  "to": "<FCM token>"
}
```

**Comment by k0302** [comment]
The first line is to be written on Terminal, but where should I write this part - send.json {"notification": { "body": "this is a body",
    "title": "this is a title" },  "priority": "normal",  "to": "<FCM token>"}?

**Comment by markusaksli-nc** [comment]
Include a file in the path you are using terminal from (probably the project root) named `send.json` and add the contents there.

You can also just use the interface in firebase console but it's more of a hassle.

**Comment by k0302** [comment]
Thanks for answering so many questions. But I get 'invalid key' error this time. Which key from firebase console are you referring to? I see 'web API key', 'server key from cloud messaging section', and other key-looking strings in my firebase console. I tried all of them, but all ended up 'invalid key' error

**Comment by markusaksli-nc** [comment]
It is the server key from cloud messaging in project settings. Make sure you remove the angled brackets.
`key=AAcVh...`
