### ISSUE TITLE
Dynamic links short url throws platform exemption

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#419]
I tried using dynamic_links plugin and able to create dynamic links. But when I tried to shorten uri using 
```dart
final Uri dynamicUrl = await parameters.buildUrl();
final ShortDynamicLink shortDynamicLink = await parameters.buildShortLink();
final Uri shortUrl = shortDynamicLink.shortUrl; 
```
and 

```dart
final Uri dynamicUrl = await parameters.buildUrl();
final ShortDynamicLink shortenedLink = await DynamicLinkParameters.shortenUrl(
  Uri.parse('https://example.page.link/?link=https://example.com/&apn=com.example.android&ibn=com.example.ios'dynamicUrl),
  DynamicLinkParametersOptions(ShortDynamicLinkPathLength.unguessable),
);
final Uri shortUrl = shortenedLink.shortUrl;
```
but both the tries resulted me in platform exemption only. I'm using `Xiaomi redmi 5A running on MIUI 10 Global 9.2.15 beta based on Android 8.1.0 `for testing

**Comment by kroikie** [comment]
@harshapulikollu

The issue at https://github.com/flutter/flutter/issues/28395 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @harshapulikollu
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by felixwortmann** [comment]
@iapicca I am still having this issue. I am using an Pixel 2 Emulator with API 29.
### This line of code throws:
```dart
final ShortDynamicLink dynamicUrl = await parameters.buildShortLink();
```
It works when used with 
```dart
final Uri dynamicUrl = await parameters.buildUrl();
```
### The exact error message:
```
E/flutter (25847): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(short_link_error, 8: , null)
```

### Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-DE)
    • Flutter version 1.12.13+hotfix.9 at C:\Users\user\flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6015.39
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6015.53

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by braysonjohn148** [comment]
Any solutions>>..?

**Comment by braysonjohn148** [comment]
#2851
