### ISSUE TITLE
📚 [firebase_auth] The class 'User' of FirebaseAuth has a very generic name

### ISSUE THREAD

**Issue by faihan6** [FirebaseExtended/flutterfire#4196]
The class 'User' of FirebaseAuth has a very generic name. It conflicts with my(and many other people's code) which has another class named 'User'. It doesn't make sense to represent actual User object(of my application logic) with a different name and to represent 'FirebaseUser' with a generic name 'User'. Please change it back to 'FirebaseUser'.

**Comment by Salakar** [comment]
There is already a discussion on this topic please see that.

**Comment by faihan6** [comment]
Can you please send the link of that discussion @Salakar

**Comment by softronaut** [comment]
I couldn't find the topic also. I would expect libraries shouldn't occupy the generic names. I hope next release you'll revert the depreciation of `FirebaseUser` class. Importing package with an alias is not actually developer friendly.

**Comment by faihan6** [comment]
The only thing we can do as of now is to extend a user-defined CustomFirebaseUser Class from the 'User' class
