### ISSUE TITLE
After migrating to firebase_messaging 8.0.0-dev.8 messages are not delivered - iOS

### ISSUE THREAD

**Issue by vladaman** [FirebaseExtended/flutterfire#4198]
After we migrated to firebase_messaging 8.0.0-dev.8 we can't get messaging to work on iOS. Worked perfectly before, also in the Simulator and iOS device.

- Flutter 1.12.4
- Dart 2.10.4
- Simulator iPhone 11 - 14.2

It's not clear from documentation if the AppDelegate should or should not contain **[FIRApp configure];** or if **FirebaseAppDelegateProxyEnabled** is needed in Info.plist

FCM works on Android. Seems like the iOS will not receive any notification for some unknown reason.

We also added Remote notifications in Background modes.

**AppDelegate.m**
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
@import Firebase;
@import GoogleMaps;
	
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // [FIRApp configure];
    [GeneratedPluginRegistrant registerWithRegistry:self];
    [GMSServices provideAPIKey:@"xxxxxxx"];

    if (@available(iOS 10.0, *)) {
      [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
    }

  // [application registerForRemoteNotifications];
  // [END register_for_notifications]
    //
    // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}


@end
```

Might be related to https://github.com/FirebaseExtended/flutterfire/issues/4185

**Comment by ahmetakil** [comment]
Hi, were you able to handle background messages for ios in the previous version? 
We were trying to catch background events whenever the app was terminated but wasn't able to 

So we migrated to version 8.0.0-dev.8 but now, none of the notifications work

**Comment by BasanthVerma** [comment]
I receive notifications on iPhone sometimes, but it's always a remote notification if it's received. Also clicking on notification doesn't work on iPhone for me.

iPhone XR 14.0.1
Flutter 1.22.3 • channel stable 
firebase_messaging 8.0.0-dev.8

**Comment by Salakar** [comment]
Please note this on the docs:

![image](https://user-images.githubusercontent.com/5347038/101296874-cc6f8600-381d-11eb-8b5f-eb855239bf1b.png)

You need to test on a real device with APNs properly integrated by following the guide here: https://firebase.flutter.dev/docs/messaging/apple-integration
