### ISSUE TITLE
[firebase_storage] Download progress

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#420]
Hello,

file upload progress was implemented in version 1.0.3, but download progress is still missing. 
there is already a TODO in filrebase_storage.dart at line 146:

/// TODO: Move into own file and build out progress functionality

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_storage/lib/src/firebase_storage.dart

**Comment by kroikie** [comment]
@ethael

The issue at https://github.com/flutter/flutter/issues/28389 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by creativecreatorormaybenot** [comment]
@kroikie The link in the issue comment should be this instead now: https://github.com/FirebaseExtended/flutterfire/blob/04b7954788ca291e3841877c0f6b6e9b0a8d8ad3/packages/firebase_storage/lib/src/firebase_storage.dart#L128

Additionally, this issue potentially needs some labels.

**Comment by kroikie** [comment]
@creativecreatorormaybenot done. thanks for flagging

**Comment by elliott-io** [comment]
Is there an expected delivery date for this functionality?

**Comment by NaheleMoon** [comment]
Any progress on this? It's frustrating that we can get progress on uploads but not on downloads.

**Comment by javiernanni** [comment]
I really need this to work... I'm a solo dev building a humble bootstrapped project, but would be willing to make a small donation if that helps incentivize this feature request being prioritized.

Not sure $30-50 will move the needle, but I'm a bit desperate and it feels right to offer a contribution instead of demanding sth gets built :D

**Comment by oseiasmribeiro** [comment]
It's very strange not to have such an option.

**Comment by awazgyawali** [comment]
This is very very urgent for me, I'll send a PR ASAP.

**Comment by yanivshaked** [comment]
@awazgyawali Is this already a part of the official firebase for flutter release?
If so, start which version; If not, how soon is it supposed to be?

Thanks!

**Comment by yanivshaked** [comment]
> @awazgyawali Is this already a part of the official firebase for flutter release?
> If so, starting which version; If not, how soon is it supposed to be?
> 
> Thanks!

I just noticed version 5.0.0-dev.1 has this feature. Thanks!

**Comment by Ehesp** [comment]
Closing off since preview is available.
