### ISSUE TITLE
[cloud_firestore] There is no easy way to close a stream of snapshot.

### ISSUE THREAD

**Issue by mashahbazi** [FirebaseExtended/flutterfire#4203]
There is no easy way to close a stream of snapshot. You must close all of listener and wait until garbage collector destroy stream instance then it listener remove.
Why we can't have a stremController so we can close it?

**Comment by darshankawar** [comment]
@mashahbazi 
This sounds like a feature request. Can you provide a use case of the issue you are facing and a proposal which would help to resolve it ?
