### ISSUE TITLE
I hate my life because of changing the package  every month 

### ISSUE THREAD

**Issue by TheKhaled** [FirebaseExtended/flutterfire#4205]
I really suffer and disappointed from  changing the package  every month  
I 'm very confusing about it  , I can't study any course because  this , 
and when I use the old package the project doesn't run 
I have been trying for 3 week why the project doesn't want to run , finally I found that the problem is in the old package 
I don't know why you do this !!  tell me are you happy when you change  the syntax  only !!!

**Comment by sidrao2006** [comment]
@TheKhaled , sorry for your inconvenience 
As mentioned, this project is under development. Also, changes are being made to make the packages more compatible and to align them with Firebase products available for other products.

**Comment by diegogarciar** [comment]
@TheKhaled I use this [dev package](https://pub.dev/packages/dapackages) that updates the dependencies on the `pubspec.yalm` I run it once a week and saves me some trouble.

PD: Be aware that it sometimes specifies a version that hasn't been released so you have to discard that package change.

**Comment by TheKhaled** [comment]
@diegogarciar  
Many thanks to you
but what will happen when they update also the syntax  of the code ?

**Comment by diegogarciar** [comment]
You'll probably scream

**Comment by Ehesp** [comment]
As we roll out fixes, bug fixes and integrate features we roll them out ASAP. This is the tradeoff vs waiting for months and shipping single releases with a massive amounts of updates.
