### ISSUE TITLE
[📚] Your documentation feedback title (CHANGE ME)

### ISSUE THREAD

**Issue by Niroop4444** [FirebaseExtended/flutterfire#4208]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary: I was looking to Authenticate with Firebase in Flutter Using a Custom Authentication System, but couldn't find any documents regarding that.

**Comment by markusaksli-nc** [comment]
Hi @Niroop4444 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
