### ISSUE TITLE
🐛 [firebase_messaging] Unbind Exception

### ISSUE THREAD

**Issue by ethan-shumate** [FirebaseExtended/flutterfire#4213]
## Bug report
W/ConnectionTracker(21748): Exception thrown while unbinding
W/ConnectionTracker(21748): java.lang.IllegalArgumentException: Service not registered: lp@49ff17c
W/ConnectionTracker(21748): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
W/ConnectionTracker(21748): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
W/ConnectionTracker(21748): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(21748): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):1)
W/ConnectionTracker(21748): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):2)
W/ConnectionTracker(21748): 	at lq.D(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):10)
W/ConnectionTracker(21748): 	at lc.a(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):2)
W/ConnectionTracker(21748): 	at ee.run(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):3)
W/ConnectionTracker(21748): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(21748): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(21748): 	at ix.run(:com.google.android.gms.dynamite_measurementdynamite@204217081@20.42.17 (120400-0):6)

**Describe the bug**
After following the steps in the readme to set up firebase_messaging, and following the documentation change referenced here: https://github.com/FirebaseExtended/flutterfire/issues/4147
my app works. The notifications appear to be working as expected however my debug console is filled with the following:
Exception thrown while unbinding
java.lang.IllegalArgumentException: Service not registered: lp@49ff17c

### Steps to reproduce

1.) Follow steps in readme of firebase_messaging pub package here: https://pub.dev/packages/firebase_messaging/example
2.) Use the correction that is listed here: https://github.com/FirebaseExtended/flutterfire/issues/4147
3.) Send a test notification from firebase.
4.) Read debug console.

### Expected behavior
No errors.

**Comment by markusaksli-nc** [comment]
Hi @ethan-shumate 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4090.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
