### ISSUE TITLE
[firebase_auth] Persisting authentication state in mobile apps.

### ISSUE THREAD

**Issue by marinalexandru** [FirebaseExtended/flutterfire#4220]
## Current findings 
During a security audit some concerns were raised regarding user auth storage. The only reference in the documentation we could find related to mobile authentication state persistence is here https://firebase.flutter.dev/docs/auth/usage/#persisting-authentication-state and it does not specifically state how the sensitive data is stored for mobile apps. 
Our findings indicate that, at least for Android, the tokens (both the Firebase user token and the refresh token) are stored in shared preferences at app level (com.google.firebase.auth).
On iOS side we could not find any traces of where the data is stored.

## Concerns and expected behaviour
Those token values (at least for Android) seem to be stored in plain, and we could even use the token to impersonate a user. In this Android security recommendation https://developer.android.com/topic/security/best-practices#internal-storage the note states that an encrypted file should be preferred for sensitive data and in consequence we were expecting to find at least the shared prefs values encrypted. Is this a security concern or is this the intended behaviour here? 

## Further action
If this is intended, is there any way we could change/modify this behaviour? Maybe even bypassing the storage mechanism altogether?  
For example for web there is the following method:
```dart
FirebaseAuth.instance.setPersistence
```
that can alter the persistence mode. Is there anything similar we could use for mobile? Was thinking of setting the persistence to None and storing the refresh and user token in our encrypted DB and recreate the Firebase user from there.

## Documentation
If this is intended by design, the authentication state storage mechanism for mobile apps should be at least explicitly documented per each platform and this could be moved to a documentation change request.

**Comment by marinalexandru** [comment]
Or should we address this issue/question directly on the native Firebase SDK for Android issues page? https://github.com/firebase/firebase-android-sdk/issues

**Comment by russellwheatley** [comment]
Hey @marinalexandru, your intuition is correct. This library is a thin wrapper around the native SDKs and underlying implementation details, such as security, ought to be raised on the respective native repos. Thanks for raising the issue  so people can track progress [here](https://github.com/firebase/firebase-android-sdk/issues/2388)
