### ISSUE TITLE
🐛 [cloud_functions_web] CloudFunctions calls the "us-central1" server even if the regions is set to "europe-west1"

### ISSUE THREAD

**Issue by denkoul** [FirebaseExtended/flutterfire#4226]
## Bug report

When calling a "europe-west1" function, the url is looks the function in the "us-central1" server, and eventually crashes, even if setting the region to europe.

### Steps to reproduce

call a function and set the region, like this
`HttpsCallable callable = FirebaseFunctions.instanceFor(region: 'europe-west1').httpsCallable('function-name');`

### Expected behavior

The function must be called to the europe-west1 server.

## Additional context

Rolling back to 3.0.1 fixes the issue

**Comment by markusaksli-nc** [comment]
Hi @denkoul 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by denkoul** [comment]
### Doctor
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-GR)
    • Flutter version 1.24.0-10.2.pre at /Users/denkoul/Development/flutter
    • Framework revision 022b333a08 (8 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/denkoul/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (4 available)
    • SM A750FN (mobile) • 32004eec46aeb58d                     • android-arm64  • Android 10 (API 29)
    • iPhone 11 (mobile) • BB2BF3F0-34E1-4094-85BE-BC70F618BA0A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 87.0.4280.67
    ! Error: denkoul-iPhone is not connected. Xcode will continue when denkoul-iPhone is connected. (code -13)

• No issues found!

### Deps
dependencies:
- apple_sign_in 0.1.0 [flutter]
- autocomplete_textfield 1.7.3 [flutter]
- badges 1.1.4 [flutter]
- barcode_widget 1.5.0 [flutter barcode meta]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- cloud_firestore 0.14.3+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.7.0 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- cloud_functions_web 3.0.1 [firebase_core cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- connectivity 2.0.2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- crypto 2.1.5 [collection convert typed_data]
- device_info 1.0.0 [flutter device_info_platform_interface]
- file_picker 2.1.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase 7.3.2 [http http_parser js]
- firebase_auth 0.18.3+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2+1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.3+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_database 4.3.0 [flutter firebase_core]
- firebase_storage 5.1.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- fl_chart 0.12.0 [flutter path_drawing equatable]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_fadein 1.1.1 [flutter]
- flutter_speed_dial 1.2.5 [flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_timeline 0.1.1+13 [flutter]
- flutter_typeahead 1.8.8 [flutter flutter_keyboard_visibility]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_webrtc 0.5.7 [flutter]
- fluttertoast 7.0.4 [flutter flutter_web_plugins]
- get 3.17.1 [flutter]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- interval_time_picker 0.1.0+1 [flutter]
- just_audio 0.5.6 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid flutter]
- mime 0.9.7
- package_info_plus 0.5.0 [flutter package_info_plus_platform_interface package_info_plus_web package_info_plus_macos]
- photo_view 0.10.3 [flutter]
- progress_indicators 0.1.5 [flutter]
- pull_to_refresh 1.6.3 [flutter]
- responsive_builder 0.3.0 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 5.7.6 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- uuid 2.2.2 [crypto convert]
- webview_flutter 1.0.7 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.3 [collection]
- audio_session 0.0.9 [flutter flutter_web_plugins rxdart]
- barcode 1.17.1 [meta qr]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- clock 1.1.0-nullsafety.3
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 3.0.2 [flutter meta firebase_core plugin_platform_interface]
- collection 1.15.0-nullsafety.5
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- equatable 1.2.5 [collection meta]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+1 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.3 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_platform_interface 1.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_keyboard_visibility 3.3.0 [flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.3
- just_audio_platform_interface 1.1.1 [flutter meta plugin_platform_interface]
- just_audio_web 0.1.1 [just_audio_platform_interface flutter flutter_web_plugins meta]
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_info_plus_macos 0.1.0 [flutter]
- package_info_plus_platform_interface 0.1.0 [flutter meta plugin_platform_interface]
- package_info_plus_web 0.1.0 [http package_info_plus_platform_interface platform_detect flutter flutter_web_plugins meta]
- path 1.8.0-nullsafety.3
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- platform 2.2.1
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.5 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.5
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]

**Comment by Ehesp** [comment]
@denkoul what version of the Firebase Web SDK are you using?

**Comment by denkoul** [comment]
> @denkoul what version of the Firebase Web SDK are you using?

https://www.gstatic.com/firebasejs/**8.0.0**/firebase-app.js

**Comment by Ehesp** [comment]
Ok I suspect that's the problem. I believe we currently test against 7:

![image](https://user-images.githubusercontent.com/842078/100347561-79a3fc00-2fdd-11eb-883f-3c10d62e1595.png)

**Comment by denkoul** [comment]
Actually the problem got fixed if I add 
`  cloud_functions_web: 3.0.1  #temp fix because 3.1.0 breaks`
to the pubspec. But this is a temp solution and can't stay there forever.

**Comment by Ehesp** [comment]
Hmm ok, we can look into that, sounds like an issue with the interop code.

**Comment by denkoul** [comment]
> Hmm ok, we can look into that, sounds like an issue with the interop code.

Seems like the 3.1.0 version of the cloud_functions_web plugin contains the bug. If I force-downgrade it to 3.0.1 I can still work.

**Comment by wliumelb** [comment]
I am having the same issue

**Comment by wliumelb** [comment]
Hi, I think I have located the bug. @Ehesp
