### ISSUE TITLE
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.3+1\android\src\main\java\io\flutter\plugins\firebase\firebase_auth\FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by adelabdelstar** [FirebaseExtended/flutterfire#4237]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Salakar** [comment]
Please raise a new issue with the issue template **fully** completed.
