### ISSUE TITLE
[firebase_ml_vision] GS1 Databar Expanded Stacked

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#425]
Hello,

I am trying to scan a barcode of type "Databar Expanded Stacked" from GS1:

![image](https://user-images.githubusercontent.com/9054058/53134653-00dd5980-3546-11e9-9d27-a08f58ea8a05.png)

This is an example barcode which encodes "011234567890123-ABCabc"

When I scan for this type of barcode I get nothing back

**Comment by kroikie** [comment]
@phasee

The issue at https://github.com/flutter/flutter/issues/28236 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @phasee
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
