### ISSUE TITLE
🐛 [Locale-Emulator] Run error……

### ISSUE THREAD

**Issue by maidlover** [FirebaseExtended/flutterfire#4252]
## Bug report

**Describe the bug**
When I open some game with LE,than error show up.

### Steps to reproduce

1. Open some Galgame(like 遊聖天使プリマヴェールDrei) with LE 2.4.1.0
2. Error code:C00736B1

### Expected behavior

can't run game

---

## Additional context

The most of Galgame can be run by LE.Also can run most of Japanese TXT.I run it on Win7 and success,but when I change Win10 than LE show up this issue.All of the suggestion I already tried,but none of those work.

---

<details><summary>Click To Expand</summary>

```
---------------------------
Locale Emulator Version 2.4.1.0
---------------------------
Error Number: C00736B1

Commands: "F:\PriveDrei.exe" 



Microsoft Windows NT 10.0.19042.0 x64

NTDLL.DLL: 10.0.19041.610

KERNELBASE.DLL: 10.0.19041.572

KERNEL32.DLL: 10.0.19041.546

USER32.DLL: 10.0.19041.610

GDI32.DLL: 10.0.19041.546



If you have any antivirus software running, please turn it off and try again.

If this window still shows, try go to Safe Mode and drag the application executable onto LEProc.exe.

If you have tried all above but none of them works, feel free to submit an issue at

https://github.com/xupefei/Locale-Emulator/issues.





You can press CTRL+C to copy this message to your clipboard.


---------------------------
确定   
---------------------------

```

</details>

---

@xupefei   need help:(

**Comment by TahaTesser** [comment]
Hi @maidlover 
Are you sure you're filling this issue in the correct repository?  I don't see anything related to Flutterfire
Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you
