### ISSUE TITLE
🐛 [FirebaseMessaging] java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by wangxingxing123654** [FirebaseExtended/flutterfire#4260]
W/FirebaseMessaging(29863): Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used.
W/ConnectionTracker(29863): Exception thrown while unbinding
W/ConnectionTracker(29863): java.lang.IllegalArgumentException: Service not registered: lp@1a23de0
W/ConnectionTracker(29863): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1870)
W/ConnectionTracker(29863): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1848)
W/ConnectionTracker(29863): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:755)
W/ConnectionTracker(29863): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):1)
W/ConnectionTracker(29863): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):2)
W/ConnectionTracker(29863): 	at lq.D(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):10)
W/ConnectionTracker(29863): 	at lc.a(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):2)
W/ConnectionTracker(29863): 	at ee.run(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):3)
W/ConnectionTracker(29863): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(29863): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(29863): 	at ix.run(:com.google.android.gms.dynamite_measurementdynamite@204217083@20.42.17 (120408-0):6)

**Comment by markusaksli-nc** [comment]
Hi @wangxingxing123654 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4090.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
