### ISSUE TITLE
[📚] firebase_admob - iOS App Tracking Transparency

### ISSUE THREAD

**Issue by ElaineSchwner** [FirebaseExtended/flutterfire#4271]
I sent an App to Apple review and followed the documentation.

An I got this message from Apple ResolutionCenter:

Specifically, we were unable to locate or trigger the App Tracking Transparency modal alert in your app.

- Please provide us with steps to locate the AppTrackingTransperancy in the app.

How do I call this modal?

Thank you

**Comment by peterweb2005** [comment]
x2

Guideline 2.1 - Information Needed

We're looking forward to completing the review of your app, but we need more information to continue. Specifically, we noticed that your app uses the AppTrackingTransparency framework, but we haven't been able to locate the relevant AppTrackingTransparency permission requests.

While it is not required to implement AppTrackingTransparency at this time, we check to make sure the implementation is compliant with our guidelines when we detect the framework in an app.

**Comment by zjamshidi** [comment]
Any update? What should we do for this prepration?

**Comment by markusaksli-nc** [comment]
`firebase_admob` will be [deprecated](https://github.com/FirebaseExtended/flutterfire/blob/48f7dd7f919bde3e5ed1c73d5c5e27458b51e5dd/packages/firebase_admob/README.md#deprecation-of-firebase_admob-plugin) in favor of [`google_mobile_ads`](https://pub.dev/packages/google_mobile_ads)

Please switch to it and if you run into this issue please open it at the [package repository](https://github.com/googleads/googleads-mobile-flutter/issues)
