### ISSUE TITLE
[firebase_ml_vision] multiple app support

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#428]
Originally was #23049 but I am creating this issue to track non-default Firebase app support in firebase_ml_vision specifically

@bparrishMines

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/28149 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
[611](https://github.com/FirebaseExtended/flutterfire/issues/611)

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of making a feature request over in Discussions.
