### ISSUE TITLE
[cloud_firestore] Add DocumentSnapshot().exists getter to cloud_firestore plugin to match the sdk

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#429]
It seems like most of the other supported languages support an "exists" getter based on the example here. Can we have one too?
https://firebase.google.com/docs/firestore/query-data/get-data

**Comment by kroikie** [comment]
@ThinkDigitalSoftware

The issue at https://github.com/flutter/flutter/issues/28129 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by ThinkDigitalSoftware** [comment]
Ok, thank you

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) (`snapshot.exists` now... exists 😅) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
