### ISSUE TITLE
[firebase_admob] Flutter Native admob UnifiedNativeAd error 

### ISSUE THREAD

**Issue by yeahse** [FirebaseExtended/flutterfire#4293]
![foi](https://user-images.githubusercontent.com/30281530/100834473-51217380-34af-11eb-90e4-563d7fe6857c.png)

 how to get rid of that red things

**Comment by darshankawar** [comment]
@yeahse 
Are you still facing this issue ?
If so, you may checkout [this](https://pub.dev/packages/firebase_admob#using-native-ads) documentation and see if it helps.
If issue still persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

**Comment by yeahse** [comment]
@darshankawar 
hi, yes I`m still facing this issue

I have already referenced this hundreds of times to make sure there is no mistake. https://pub.dev/packages/firebase_admob#using-native-ads

Everything is perfectly recognized except over there. The "formats" part is always a problem.

**Comment by darshankawar** [comment]
@yeahse 
It seems the native ads feature is not yet supported by the plugin. See this open issue https://github.com/FirebaseExtended/flutterfire/issues/1173.

Are you trying to add native ad ?
Can you provide a minimal reproducible code sample that includes the error you are seeing ?

**Comment by yeahse** [comment]
@darshankawar 
As stated in the question, that picture is all about it. It can't be executed because of the "formats", but everything else is recognized well.

**Comment by darshankawar** [comment]
@yeahse 
`flutter_native_admob` is a 3rd party plugin.
What steps we need to take in order to replicate the `formats` error you are seeing ?
Can you post the code in text format rather than in screenshots ?

**Comment by yeahse** [comment]
@darshankawar  
I think you have misunderstood I did not use the flutter_native_admob.
I use "firebase_admob 0.10.3 " and  Publisher Published by a pub.dev verified publisherfirebase.google.com
https://pub.dev/packages/firebase_admob#using-native-ads

**Comment by darshankawar** [comment]
@yeahse 
Thanks for clarifying. We would still need a complete minimal reproducible code sample that shows the issue.
In which file do you see this error ? Can you provide that along with steps to replicate as when do you get the error ?
