### ISSUE TITLE
🐛 [firebase_storage] New API is so confusing, old was better

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [FirebaseExtended/flutterfire#4295]
## Bug report

**Describe the bug**
New API after version 5.0.1 is weird and does not allow waiting for things to upload after that, maybe the docs are just not showing the potential but yea

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @YazeedAlKhalaf 
What do you mean "does not allow to upload after that"?

Upload methods like [`putFile`](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/Reference/putFile.html) return an [`UploadTask`](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/UploadTask-class.html) which implements `Future<TaskSnapshot>`. You can use this to wait for the upload to finish.

What exactly is missing here?
