### ISSUE TITLE
🐛 [firebase cloud messaging] Push notification not working in android

### ISSUE THREAD

**Issue by imJithin777** [FirebaseExtended/flutterfire#4298]
I have implemented fcm cloud messaging and I receive notification in foreground and background which invokes method onMessage and onResume but the problem persists when the app is closed or terminated, no push receiving to the device in android at that moment, iOS app works correctly.
Tried several methods like changing  notification structure coming from server side, including click_action, sending without notification message etc.  but no change. Can anybody provide me a solution for this.

**Comment by markusaksli-nc** [comment]
Hi @imJithin777 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Does the official example not work for you?
Thank you

**Comment by imJithin777** [comment]
Actually the issue of the notification not received when app terminated or closed is from android version 8.1 (Oreo) to downwards, for 9 to higher it works finely

**Comment by markusaksli-nc** [comment]
Could you please provide the missing information?

**Comment by Salakar** [comment]
Please correctly fill out the issue template, without this, we can not help you properly.

Locking and closing this issue. Feel free to raise another issue that correctly follows the issue template with more details

Thank you
