### ISSUE TITLE
[firebase_core] no firebase_core version after 0.4.5 works on iOS

### ISSUE THREAD

**Issue by eAvio** [FirebaseExtended/flutterfire#4314]
firebase_core version 0.4.5 is the latest version that I can use and still build / launch my project on iOS successfully. If I use a newer version, the build completes, but the app closes as soon as it launches without returning any errors.

If anyone could help me out here, It would be much appreciated as I need the latest version of firebase on my project.

Thank you

**Comment by victrmart** [comment]
I'm with the same problem :/

**Comment by imeDevelopers** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/4317

**Comment by Salakar** [comment]
Please make sure you've followed the setup guide on the documentation; https://firebase.flutter.dev/docs/installation/ios - specifically integrating the Firebase config files.

If this is still and issue then please raise a proper issue with the template filled out with as much detail as possible.
