### ISSUE TITLE
[firebase_core] Big Problem !!!

### ISSUE THREAD

**Issue by imeDevelopers** [FirebaseExtended/flutterfire#4317]
look at this !!!
https://github.com/flutter/flutter/issues/71631

**Comment by SushantChandla** [comment]
If you want to use latest version check out [Migration Guide.](https://firebase.flutter.dev/docs/migration)

**Comment by markusaksli-nc** [comment]
Hi @imeDevelopers 
What exact issue are you having with everything on the latest version?
Could you please provide your `flutter doctor -v`, `flutter pub deps -- --style=compact`, and error logs?
Thank you

**Comment by Salakar** [comment]
Closing due to no information provided and issue template was not followed.


If you have a genuine issue then please create a new issue and provide as much detail as possible, e.g. include the exact error/stack trace you're seeing and follow the issue template.
