### ISSUE TITLE
Flutter FCM android payload and routing issue

### ISSUE THREAD

**Issue by khandilist** [FirebaseExtended/flutterfire#4319]
I found a problem where if we put key "route" within the "data", then when user click on the notification (when application is closed), flutter will directly redirect into that "route" set on the payload.
For example:
> DATA='{"notification": {"body": "Mesage Body","title": "Message title"}, "priority": "high", "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done", "route": "/order_detail"}, "to": "xxxxx"}'

Then it will automatically open screen that its route name is "/order_detail".
Its kinda weird and might lead into a problem when that screen need an extra arguments but not passed during notification click during application launch.

It's only happened in android, but run normally in iOS.

Please advice.

**Comment by darshankawar** [comment]
@khandilist 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
