### ISSUE TITLE
[firebase_messaging] Resetting badge number on applicationDidBecomeActive creates strange behavior for the user

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#433]
I'm using the `firebase_messaging` plugin for push notifications. On iOS this plugins resets the badge number on each `applicationDidBecomeActive` in the `AppDelegate`. This also clears all notifications in the notifications center.

This creates unexpected behavior for the user in several cases:
1. if the user receives several notifications at once he is only able to click on one notification since the other notifications are deleted after the app is opened
2. if the user opens the app directly after receiving a notification the notifications are also lost
3. if we show a local notification using the flutter_local_notifications plugin while the app is the foreground the notification disappears once the user tries to open the notification center.

Please fix this behavior like described in the TODO or make it configurable so the badge number is not reset. In our case we are not sending a badge number with the push notification so resetting it is not needed.

**Comment by kroikie** [comment]
@grundid

The issue at https://github.com/flutter/flutter/issues/28093 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @grundid
(and hello to @DarshanGowda0  as well)
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
