### ISSUE TITLE
🐛 [firebase_messaging] No instructions on Document for kotlin packages 

### ISSUE THREAD

**Issue by rusaik** [FirebaseExtended/flutterfire#4337]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Salakar** [comment]
There is no code you need change/add/modify on native for Android (Java or Kotlin) so I'm not sure what instructions you're looking for?
