### ISSUE TITLE
🐛 [cloud_firestore] fatal error: module map file

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#4347]
When I add the cloud_firestore dependency to my flutter app, the ios build is failing.

The build failure is as follows...

```
    fatal error: module map file
    '/Users/myUserName/src/MobileApp/ios/Pods/Headers/Private/openssl_grpc/BoringSSL-GRPC.modulemap' not found
    1 error generated.
```

**Comment by markusaksli-nc** [comment]
Hi @safield 
Not really sure how this could be related to firebase dependencies. It seems like https://github.com/grpc/grpc/issues/20631 is the problem.
Could you provide your `flutter run -v and `flutter pub deps -- --style=compact`?
Thank you
