### ISSUE TITLE
How to verify the phonenumber via otp without sign in firebase in flutter?

### ISSUE THREAD

**Issue by rtdev882** [FirebaseExtended/flutterfire#4349]
I'm using the firebase auth plugin in a flutter, In order to verify the OTP from the firebase, we need to call  **signInWithCredential**
`FirebaseAuth.instance.signInWithCredential( PhoneAuthProvider.getCredential(
  verificationId: verificationId,
  smsCode: otp,
));`

I don't want to sign in to firebase to verify the OTP, is there is any way to verify only the OTP without sign in to firebase.Please provide me solution

My enviroment details:
  **firebase_auth: ^0.15.5+3**
environment:
  sdk: ">=2.7.0 <3.0.0"

Do you want any other details, please let me know?

**Comment by darshankawar** [comment]
@rtdev882 
When you sign-in, the OTP is sent to the registered phone number. If you want to verify OTP without sign-in, there's no way to know on which phone the OTP to send to. So I am not sure if your use case / ask is feasible or possible. When you use phone to sign-in, the phone number is used as authenticator. 
See [this](https://firebase.flutter.dev/docs/auth/phone) document for more information.

Also, your question doesn't describe a bug or feature request, so it's better suited for Stackover flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing from here.
