### ISSUE TITLE
 '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).

### ISSUE THREAD

**Issue by maheshwaran-p** [FirebaseExtended/flutterfire#4363]

**Comment by darshankawar** [comment]
@maheshwaran-p 
Looking at the error, this doesn't seem to be an issue with Firebase, but the crash seems to be coming from Flutter. I'd suggest you to open this issue in Flutter repo https://github.com/flutter/flutter/issues and provide all the required details such as `flutter doctor -v`, platform on which you are seeing this crash along with a minimal code sample that shows the crash. Don't just put the crash in the title, also provide some description of the issue there.

If you think this crash is due to any firebase plugins you are using, write in comments and I'll reopen this.

**Comment by maheshwaran-p** [comment]
import 'package:package_info/package_info.dart';
import 'package:firebase_remote_config/firebase_remote_config.dart';


@override
  void initState() {
    _notificationService.setupNotification();
    _pushNotificationService.initialise();
    getInitialUri().then((value) {
      if (value != null) postid = value.query.toString();
    });
     try {
    versionCheck(context);
  } catch (e) {
    print(e);
  }


versionCheck(context) async {
  
  //Get Current installed version of app
  final PackageInfo info = await PackageInfo.fromPlatform();
  double currentVersion = double.parse(info.version.trim().replaceAll(".", ""));

  //Get Latest version info from firebase config
  final RemoteConfig remoteConfig = await RemoteConfig.instance;

  try {
    // Using default duration to force fetching from remote server.
    await remoteConfig.fetch(expiration: const Duration(seconds: 10));
    await remoteConfig.activateFetched();
    remoteConfig.getString('force_update_current_version');
    double newVersion = double.parse(remoteConfig
        .getString('force_update_current_version')
        .trim()
        .replaceAll(".", ""));
    if (newVersion > currentVersion) {
      _showVersionDialog(context);
    }
  } on FetchThrottledException catch (exception) {
    // Fetch throttled.
    print(exception);
    print('new version is the:');
       print(' force_update_current_version');
  } catch (exception) {
    print('Unable to fetch remote config. Cached or default values will be '
        'used');
  }
}


_showVersionDialog(context) async {
  await showDialog<String>(
    context: context,
    barrierDismissible: false,
    builder: (BuildContext context) {
      String title = "New Update Available";
      String message =
          "There is a newer version of app available please update it now.";
      String btnLabel = "Update Now";
      String btnLabelCancel = "Later";
      return Platform.isIOS
          ? null
          : new AlertDialog(
              title: Text(title),
              content: Text(message),
              actions: <Widget>[
                FlatButton(
                  child: Text(btnLabel),
                  onPressed: () => _launchURL('https://play.google.com/store/apps/details?id=com.hiphop.hiphop'),
                ),
                FlatButton(
                  child: Text(btnLabelCancel),
                  onPressed: () => Navigator.pop(context),
                ),
              ],
            );
    },
  );
}

_launchURL(String url) async {
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

**Comment by darshankawar** [comment]
@maheshwaran-p 
When do you get the error ?
I see you have `firebase_remote_config`, `url_launcher` and `package_info` in your code.
Can you try to segregate by removing each plugin one and one and see if when and where do you get the error ?

**Comment by maheshwaran-p** [comment]
I have an issue with firebase_remote_config plugin only.

**Comment by maheshwaran-p** [comment]
Problem solved thanks for your support.😊
