### ISSUE TITLE
🐛 [firebase_messaging 7.0.3] notification not received when application is in foreground (iOS)

### ISSUE THREAD

**Issue by robvr** [FirebaseExtended/flutterfire#4375]
## Bug report

Push Notification is not received when the application is in foreground and the notification field is set in the payload. In background and terminated it works. This is happening only on iOS devices.

### Expected behavior
**onMessage** listener to be triggered

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.14.6 18G103 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    ! CocoaPods 1.7.4 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 4 categories.

**Comment by darshankawar** [comment]
@robvr 
Can you try the official `firebase_messaging` plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if you get same behavior ?

**Comment by robvr** [comment]
I've tried the official example and this behavior still persists. The problem is with the **notification** field, if the payload of the push notification contains this field then it is not received when the application is in foreground. But if I remove this field then it won't be received in background and terminated.

**Comment by darshankawar** [comment]
@robvr 
Can you provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by orestesgaolin** [comment]
@robvr please check if you remove the `FirebaseAppDelegateProxyEnabled` key from the Info.plist but keep the AppDelegate code

```swift
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
	override func application(
		_ application: UIApplication,
		didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
	) -> Bool {
		GeneratedPluginRegistrant.register(with: self)
		if #available(iOS 10.0, *) {
			UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
		}
		return super.application(application, didFinishLaunchingWithOptions: launchOptions)
	}
}
```

After removing the key I was able to receive the push notification on iOS when the app was in the foreground

**Comment by robvr** [comment]
@orestesgaolin Thank you very much for your suggestion! Push notifications now are working as they should!

**Comment by orestesgaolin** [comment]
@darshankawar I belive this may be error in the readme for the plugin

**Comment by darshankawar** [comment]
@orestesgaolin Would you be willing to file a new issue for it if it doesn't exist already ? A new issue will help to track it in better way.
