### ISSUE TITLE
Problemas con lectura ocr en ios

### ISSUE THREAD

**Issue by jcazalELPAKOMICHI** [FirebaseExtended/flutterfire#4395]
En ios no funciona la lectura ocr por que por alguna razón, la imagen hay que voltearla -90º asi como tambien hay que voltear el reflejo de la misma.

**Comment by darshankawar** [comment]
@jcazalELPAKOMICHI 
Please provide the issue description in English since I don't understand the language in which you posted this issue.

**Comment by carlos-labrador** [comment]
Translation:
```In ios the ocr reading does not work because for some reason, the image must be turned -90º as well as the reflection of it must also be turned.```

**Comment by darshankawar** [comment]
@jcazalELPAKOMICHI 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. Also specify which firebase plugin are you referring to in this issue.

**Comment by robert36580** [comment]
I’m not exactly sure how I got onto this email string. But I have issues with keyboards switching unexpectedly on iOS. Particularly on my iPad when using Apple Pencil and scribble. My phone number always hangs up whenever I fill it from contacts.  I’m not sure if this is of any help with what you’re talking about. I have suddenly been getting a lot of email over the last 24 hours. So much and given my limited time on the platform, I’m having a hard time discerning who is talking about what.

I should also mention this seems to follow a trending problem. Between copy and paste and dictation.




Sent from my iPhone

On Dec 23, 2020, at 9:02 PM, Google Open Source Bot <notifications@github.com> wrote:

﻿

Hey @jcazalELPAKOMICHI<https://github.com/jcazalELPAKOMICHI>. We need more information to resolve this issue but there hasn't been an update in 7 weekdays. I'm marking the issue as stale and if there are no new updates in the next 7 days I will close it automatically.

If you have more information that will help us get to the bottom of this, just add a comment!
