### ISSUE TITLE
[Firebase_messaging] : Documentation is outdated for Android implementation

### ISSUE THREAD

**Issue by bambinoua** [FirebaseExtended/flutterfire#4396]
The code of `Application.java`  crashes the gradle process because of this error mesage
`PluginRegistry cannot be converted to FlutterEngine`

It looks like the Java code is outdated.
```java
package io.flutter.plugins.firebasemessagingexample;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}```

**Comment by darshankawar** [comment]
@bambinoua 
Can you try [this](https://github.com/FirebaseExtended/flutterfire/issues/1904#issuecomment-580868406) and [this](https://github.com/FirebaseExtended/flutterfire/issues/1904#issuecomment-634156508) solution and see if it works for you ?

**Comment by asmodeoux** [comment]
> @bambinoua
> Can you try [this](https://github.com/FirebaseExtended/flutterfire/issues/1904#issuecomment-580868406) and [this](https://github.com/FirebaseExtended/flutterfire/issues/1904#issuecomment-634156508) solution and see if it works for you ?

I've just checked and it works, but documentation should still be updated

**Comment by bambinoua** [comment]
> Can you try this and this solution and see if it works for you ?
Yep. I already found those solution but... initially we trust the package docs.

**Comment by darshankawar** [comment]
@bambinoua I agree.

**Comment by rignaneseleo** [comment]
Is this related to the new version 8.0.0-dev.11 or the old one?

**Comment by Salakar** [comment]
Based on `FlutterFirebaseMessagingService` this looks like it's for the old version of messaging. I'm closing this in favour of switching to the new version of the messaging plugin.

If this is still a documentation issue on the new version of messaging please could you raise a new issue relevant to the new version as the code has since changed. Based on a quick review of the docs I don't think this is going to be an issue now though.
