### ISSUE TITLE
[remote_config] Web support

### ISSUE THREAD

**Issue by passsy** [FirebaseExtended/flutterfire#4409]
`firebase_remote_config` doesn't have support for the web platform.
There are no blockers, it's just not implemented.

Official js web API: https://firebase.google.com/docs/remote-config/use-config-web

**Comment by markusaksli-nc** [comment]
Hi @passsy 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/2115.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
