### ISSUE TITLE
🐛 [firebase_auth] sendSignInLinkToEmail user-not-found error code

### ISSUE THREAD

**Issue by amitkot** [FirebaseExtended/flutterfire#4442]
## Bug report

When calling `sendSignInLinkToEmail()` the documentation suggests handling a `FirebaseAuthException` with error code `user-not-found`.

This method can be used for both sign-up and login. What does this error mean in the context of sign-up?

### Steps to reproduce

1. Call `FirebaseAuth.instance.sendSignInLinkToEmail()`.
2. Catch `FirebaseAuthException` with a `user-not-found` code.
4. Indicate error to the user - what error?

**Comment by russellwheatley** [comment]
Hey @amitkot, you're correct. That error is unnecessary for the `sendSignInLinkToEmail()`. As far as i can tell, there are no code samples on the docs that indicate this error ought to be caught when calling `sendSignInLinkToEmail()`, so I'm going to close this issue.

**Comment by amitkot** [comment]
@russellwheatley thanks, created a PR to remove this from the method docs.
