### ISSUE TITLE
 Name is reserved. Type, name: event, dynamic_link_app_open

### ISSUE THREAD

**Issue by rafaelsimonassi** [FirebaseExtended/flutterfire#4452]
Hello,

I am trying make firebase_dynamic_link works, but I getting the error:

  Name is reserved. Type, name: event, dynamic_link_app_open

Basically the steps to reproduce are:

1) install firebase_dynamic_links: ^0.6.3
2) In a stateful Widget invoke the initDynamicLinks() method inside the initState() method.
3) The initDynamicLinks() method contains the following code:

```
void initDynamicLinks() async{
    print('InitDyanmicLinks()');
    FirebaseDynamicLinks.instance.onLink(
          onSuccess: (PendingDynamicLinkData dynamicLink) async {
            final Uri deepLink = dynamicLink?.link;
            print('OnSuccess event!');

            if (deepLink != null) {
              Navigator.pushNamed(context, deepLink.path);
            }
          },
          onError: (OnLinkErrorException e) async {
            print('onLinkError');
            print(e.message);
          }
        );
        
        final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
        final Uri deepLink = data?.link;

        if (deepLink != null) {
          Navigator.pushNamed(context, deepLink.path);
        }
 }

```
4) Create a Dynamic Link in Firebase

5) In an external app, for example, Whatsapp, invoke the link created in step 4

6) There are 4 prints in the code above, just the first one is invoked. The other ones are never reached. And also, the following errors are showed in the VisualCode console:

> E/FA      ( 3644): Name is reserved. Type, name: event, dynamic_link_app_open
> E/FA      ( 3644): Invalid event name. Event will not be logged (FE): dynamic_link_app_open

7) As you can see I just used the same example available in firebase_dynamic_link plugin.

**Comment by TahaTesser** [comment]
Hi @rafaelsimonassi 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by rafaelsimonassi** [comment]
### Flutter Doctor
PS C:\src\b_prj\b> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [versÃ£o 10.0.18363.1256], locale pt-BR)
\Deseja finalizar o arquivo em lotes (S/N)?  s
Deseja finalizar o arquivo em lotes (S/N)? s
PS C:\src\bazzar_prj\bazzar> flutter doctor -v
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [versÃ£o 10.0.18363.1256], locale pt-BR)
    • Flutter version 1.20.3 at D:\flutter\flutter_1_17
    • Framework revision 216dee60c0 (4 months ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\rafas\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\rafas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • ASUS X00TDB (mobile) • JCAXB6013376F4Z • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @rafaelsimonassi 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by xJon** [comment]
@TahaTesser He did, he basically linked the example function from the [package's description](https://pub.dev/packages/firebase_dynamic_links).
I'm encountering the same issue.

**Comment by TahaTesser** [comment]
Hi @rafaelsimonassi  @xJon 
Using a complete official example, no issues when using generated links
### Preview
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/103282045-7ea00500-49fa-11eb-9ff1-153c87a97806.gif)


<details> 
<summary>code sample</summary> 

```dart
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';

import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MaterialApp(
    title: 'Dynamic Links Example',
    routes: <String, WidgetBuilder>{
      '/': (BuildContext context) => _MainScreen(),
      '/helloworld': (BuildContext context) => _DynamicLinkScreen(),
    },
  ));
}

class _MainScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MainScreenState();
}

class _MainScreenState extends State<_MainScreen> {
  String _linkMessage;
  bool _isCreatingLink = false;
  String _testString =
      "To test: long press link and then copy and click from a non-browser "
      "app. Make sure this isn't being tested on iOS simulator and iOS xcode "
      "is properly setup. Look at firebase_dynamic_links/README.md for more "
      "details.";

  @override
  void initState() {
    super.initState();
    initDynamicLinks();
  }

  void initDynamicLinks() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;

      if (deepLink != null) {
        Navigator.pushNamed(context, deepLink.path);
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });

    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink != null) {
      Navigator.pushNamed(context, deepLink.path);
    }
  }

  Future<void> _createDynamicLink(bool short) async {
    setState(() {
      _isCreatingLink = true;
    });

    final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: 'https://testtriage.page.link',
      link: Uri.parse('https://dynamic.link.example/helloworld'),
      androidParameters: AndroidParameters(
        packageName: 'com.nevercode.triage',
        minimumVersion: 0,
      ),
      dynamicLinkParametersOptions: DynamicLinkParametersOptions(
        shortDynamicLinkPathLength: ShortDynamicLinkPathLength.short,
      ),
      iosParameters: IosParameters(
        bundleId: 'com.nevercode.triage',
        minimumVersion: '0',
      ),
    );

    Uri url;
    if (short) {
      final ShortDynamicLink shortLink = await parameters.buildShortLink();
      url = shortLink.shortUrl;
    } else {
      url = await parameters.buildUrl();
    }

    setState(() {
      _linkMessage = url.toString();
      _isCreatingLink = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Dynamic Links Example'),
        ),
        body: Builder(builder: (BuildContext context) {
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                ButtonBar(
                  alignment: MainAxisAlignment.center,
                  children: <Widget>[
                    RaisedButton(
                      onPressed: !_isCreatingLink
                          ? () => _createDynamicLink(false)
                          : null,
                      child: const Text('Get Long Link'),
                    ),
                    RaisedButton(
                      onPressed: !_isCreatingLink
                          ? () => _createDynamicLink(true)
                          : null,
                      child: const Text('Get Short Link'),
                    ),
                  ],
                ),
                InkWell(
                  child: Text(
                    _linkMessage ?? '',
                    style: const TextStyle(color: Colors.blue),
                  ),
                  onTap: () async {
                    if (_linkMessage != null) {
                      await launch(_linkMessage);
                    }
                  },
                  onLongPress: () {
                    Clipboard.setData(ClipboardData(text: _linkMessage));
                    Scaffold.of(context).showSnackBar(
                      const SnackBar(content: Text('Copied Link!')),
                    );
                  },
                ),
                Text(_linkMessage == null ? '' : _testString)
              ],
            ),
          );
        }),
      ),
    );
  }
}

class _DynamicLinkScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Hello World DeepLink'),
        ),
        body: const Center(
          child: Text('Hello, World!'),
        ),
      ),
    );
  }
}

``` 

</details>

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_dynamic_links: ^0.6.3
  url_launcher: ^5.7.10
```

```
Launching lib/main.dart on Taha’s iPhone in debug mode...
 lib/main.dart
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           22.7s
Connecting to VM Service at ws://localhost:65044/ws

```

**Comment by rafaelsimonassi** [comment]
Hello Taha,

I restarted a fresh app, for some reason it is working now. I suspect that
after a flutter clean the FirebaseDynamicLinks.instance.onLink is being
called .
So, for now, please close this issue.


Regards,





Em ter., 29 de dez. de 2020 às 08:53, Taha Tesser <notifications@github.com>
escreveu:

**Comment by TahaTesser** [comment]
Hi @rafaelsimonassi 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
