### ISSUE TITLE
[firebase_core] The links in the documentation are outdated/broken

### ISSUE THREAD

**Issue by asashour** [FirebaseExtended/flutterfire#4461]
During development with Firebase, I came through an error and the URL in that error is broken.

Specifically, the links in [firebase_core_exceptions.dart](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_core_exceptions.dart)

E.g.

- https://firebaseextended.github.io/flutterfire/docs/installation/web
- https://firebaseextended.github.io/flutterfire/docs/installation/android
- https://firebaseextended.github.io/flutterfire/docs/installation/ios

**Comment by SirusCodes** [comment]
I would like to work on it.

**Comment by TahaTesser** [comment]
@SirusCodes 
Feel free to send a PR
Thanks!
