### ISSUE TITLE
🐛 [firebase_admob] onAdFailedToLoad: 0 | Ad failed to load : 0

### ISSUE THREAD

**Issue by cheuhyakuroku** [FirebaseExtended/flutterfire#4487]
## Bug report

**Describe the bug**
i can't load BannerAd
i use firebase_admob 0.10.3
and follow firebase_admob document guide 

## Additional context

[+3789 ms] W/ConnectionTracker( 5970): Exception thrown while unbinding
[        ] W/ConnectionTracker( 5970): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzji@16f5f7f
[        ] W/ConnectionTracker( 5970):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
[        ] W/ConnectionTracker( 5970):  at android.app.ContextImpl.unbindService(ContextImpl.java:1786)
[        ] W/ConnectionTracker( 5970):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.measurement.internal.zzio.zzag(com.google.android.gms:play-services-measurement-impl@@17.6.0:245)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.measurement.internal.zzio.zzal(com.google.android.gms:play-services-measurement-impl@@17.6.0:262)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.measurement.internal.zzio.zzc(com.google.android.gms:play-services-measurement-impl@@17.6.0:336)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.measurement.internal.zzir.zza(com.google.android.gms:play-services-measurement-impl@@17.6.0:2)
[  +12 ms] W/ConnectionTracker( 5970):  at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:7)
[        ] W/ConnectionTracker( 5970):  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
[        ] W/ConnectionTracker( 5970):  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ] W/ConnectionTracker( 5970):  at com.google.android.gms.measurement.internal.zzfs.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:21)
[+140762 ms] D/DynamitePackage( 5970): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
[  +52 ms] I/WebViewFactory( 5970): Loading com.google.android.webview version 87.0.4280.101 (code 428010133)
[  +16 ms] W/euhyakuroku.nh( 5970): Insufficient pre-allocated space to mmap vdex.
[  +31 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
[  +35 ms] I/cr_LibraryLoader( 5970): Loaded native library version number "87.0.4280.101"
[        ] I/cr_CachingUmaRecorder( 5970): Flushed 5 samples from 5 histograms.
[ +139 ms] D/EgretLoader( 5970): EgretLoader(Context context)
[        ] D/EgretLoader( 5970): The context is not activity
[  +19 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
[   +6 ms] W/cr_media( 5970): Requires BLUETOOTH permission
[  +12 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[   +4 ms] D/ForceDarkHelper( 5970): updateByCheckExcludeList: pkg: io.github.cheuhyakuroku.nhk activity: io.github.cheuhyakuroku.nhk.MainActivity@a852048
[  +19 ms] D/DynamitePackage( 5970): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[  +11 ms] D/ForceDarkHelper( 5970): updateByCheckExcludeList: pkg: io.github.cheuhyakuroku.nhk activity: io.github.cheuhyakuroku.nhk.MainActivity@a852048
[   +6 ms] I/Ads     ( 5970): This request is sent from a test device.
[  +25 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +18 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
[  +22 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
[        ] I/DynamiteModule( 5970): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:204204100
[        ] I/DynamiteModule( 5970): Selected remote version of com.google.android.gms.ads.dynamite, version >= 204204100
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[  +17 ms] I/DynamiteModule( 5970): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:204204100
[        ] I/DynamiteModule( 5970): Selected remote version of com.google.android.gms.ads.dynamite, version >= 204204100
[   +5 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +11 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[   +5 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[  +22 ms] I/AudioManager( 5970): In isSpeakerphoneOn(), calling application: io.github.cheuhyakuroku.nhk
[        ] D/AudioManager( 5970): getStreamVolume isRestricted mode = 0
[        ] D/AudioManager( 5970): getStreamVolume isRestricted mode = 0
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[   +3 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[  +83 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +2 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
[  +21 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
[   +1 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +14 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[  +18 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[   +1 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[  +64 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +48 ms] W/Ads     ( 5970): Not retrying to fetch app settings
[  +20 ms] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/euhyakuroku.nh( 5970): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[+10325 ms] W/flutter ( 5970): onAdFailedToLoad: 0
[   +5 ms] I/Ads     ( 5970): Ad failed to load : 0

---

**Comment by xavkir-Howkoq-sycwu3** [comment]
Hola

**Comment by cheuhyakuroku** [comment]
> Hola

What's up man?

**Comment by markusaksli-nc** [comment]
Hi @cheuhyakuroku
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by Infinical** [comment]
Hello @markusaksli-nc 

`Dart SDK 2.10.4
Flutter SDK 1.22.5
soccerbit 1.0.0+1

dependencies:
- animations 1.1.2 [flutter]
- auto_route 0.6.9 [flutter meta]
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- firebase_admob 0.10.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_icons 1.1.0 [flutter]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- get 3.23.1 [flutter]
- get_it 5.0.3 [async meta]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- injectable 1.0.5 [get_it]
- observable_ish 2.1.4 [collection]
- onesignal_flutter 2.6.2 [flutter]
- path 1.8.0-nullsafety.1
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sizer 1.1.8 [flutter]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_migration_service 1.0.4 [flutter sqflite shared_preferences get_it]
- square_in_app_payments 1.5.1 [flutter built_value built_collection meta]
- stacked 1.7.6 [flutter provider observable_ish]
- stacked_hooks 0.1.3+2 [flutter flutter_hooks provider]
- stacked_services 0.6.0+1 [flutter get]

dev dependencies:
- auto_route_generator 0.6.10 [build source_gen analyzer path build_runner auto_route]
- build_runner 1.10.10 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- injectable_generator 1.0.6 [build source_gen path glob analyzer injectable collection]

transitive dependencies:
- _fe_analyzer_shared 12.0.0 [meta]
- analyzer 0.40.6 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.6.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.5 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.0 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.5 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.10 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_hooks 0.15.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- provider 4.3.2+3 [collection flutter nested]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]`

`[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/infi/Software/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/infi/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/share/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /usr/share/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • JAT L29 (mobile) • 9EH0119A25000159 • android-arm • Android 9 (API 28)`

**Comment by cheuhyakuroku** [comment]
I'm sorry, this is my fault. I used DNS ad blocking service on my wifi router.  When I turned off DNS the problem was solved :(
