### ISSUE TITLE
🐛 [cloud_firestore] Creating documents with "-" charcter in the name creates subcollections

### ISSUE THREAD

**Issue by josesoni1** [FirebaseExtended/flutterfire#4498]
## Bug report

when creating documents with "-" charcter on its name the library creates subcollections

### Steps to reproduce

with the following code:
```
FirebaseFirestore.instance
  .collection("EventsByDate")
    .doc("06-15-2020").set({
      "name": "Flutter Demo Day",
      "venue": "Javits center"
    });
```
It creates Docuement 06
Subcollection 15
Document 2020

### Expected behavior

That "-" is considered as part of the name of the document and doesn create new subcollections 

---

## Additional context

---

**Comment by markusaksli-nc** [comment]
Hi @josesoni1 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you
