### ISSUE TITLE
Same issue here, please is there any answers yet??

### ISSUE THREAD

**Issue by Captured-Heart** [FirebaseExtended/flutterfire#4499]
Same issue here,

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

_Originally posted by @praveen-gm in https://github.com/FirebaseExtended/flutterfire/issues/640#issuecomment-619951204_

**Comment by markusaksli-nc** [comment]
Please see https://github.com/FirebaseExtended/flutterfire/issues/3114#issuecomment-670445067

Closing this as a non-issue.
