### ISSUE TITLE
[firebase_dynamic_links]  sometimes got error NSPOSIXErrorDomain Code=53 "Software caused connection abort"

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#450]
As in link, there is a case of error at the completion of handleUniversalLink.
[firebase/firebase-ios-sdk#2303](https://github.com/firebase/firebase-ios-sdk/issues/2303)

**Comment by kroikie** [comment]
@ko2ic

The issue at https://github.com/flutter/flutter/issues/27810 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @ko2ic
I see your [PR](https://github.com/flutter/plugins/pull/1182) has been merged
therefore I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
