### ISSUE TITLE
Error: A problem occurred configuring project ':firebase_auth_web', Could not find method implementation()

### ISSUE THREAD

**Issue by Innovancet** [FirebaseExtended/flutterfire#4509]
i was trying to run my app after connecting my flutter app to firebase core and auth plugns, when I encountered this error

Here is the entire text:

  FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 362

* What went wrong:
A problem occurred configuring project ':firebase_auth_web'.
> Could not find method implementation() for arguments [project ':firebase_core'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by markusaksli-nc** [comment]
Hi @Innovancet 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Also please see https://firebase.flutter.dev/docs/migration/#a-android-installation
Thank you
