### ISSUE TITLE
[firebase_ml_vision] plugins have flaky iOS compile failures

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#451]
See https://cirrus-ci.com/task/5391245930135552 for an example.

```
    === BUILD TARGET firebase_ml_vision OF PROJECT Pods WITH CONFIGURATION Release ===
    In file included from /Users/anka/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.0+1/ios/Classes/FirebaseCorePlugin.m:7:
    In file included from /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/packages/firebase_ml_vision/example/ios/Pods/Headers/Private/Firebase/Firebase.h:8:
    In file included from /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/packages/firebase_ml_vision/example/ios/Pods/Headers/Public/FirebaseAnalytics/FirebaseAnalytics/FirebaseAnalytics.h:1:
    In file included from /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/packages/firebase_ml_vision/example/ios/Pods/Headers/Public/FirebaseAnalytics/FirebaseAnalytics/FIRAnalytics+AppDelegate.h:3:
    /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/packages/firebase_ml_vision/example/ios/Pods/Headers/Public/FirebaseAnalytics/FirebaseAnalytics/FIRAnalytics.h:4:9: fatal error: 'FIRParameterNames.h' file not found
    #import "FIRParameterNames.h"
            ^~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

I've occasionally seen these errors locally, but never figured out how to consistently reproduce them.  They generally "fix themselves" in CI after running the check a second time.

/cc @bparrishMines

**Comment by kroikie** [comment]
@mklim

The issue at https://github.com/flutter/flutter/issues/27797 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @mklim 
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release.
