### ISSUE TITLE
[📚] [Firebase Messaging] Remove notifications from system tray if app is manually re-opened by user

### ISSUE THREAD

**Issue by Wes1324** [FirebaseExtended/flutterfire#4516]
I have noticed that when I receive notifications from the Gmail app, if I open the Gmail app without clicking on the notification then the notification icon still disappears from the system tray.

In my Flutter app however, when I receive notifications, if I open the app without clicking on the notification then the notification remains in the system tray until I manually remove it.

I would like to know how I can implement the Gmail app notification behaviour in my own Flutter app please. I can see nothing in the documentation about how to do this.

There was a similar issue opened about this (#766) however a solution was never suggested and the issue has now been closed following the most recent release.

If it isn't currently possible then I would like to suggest it as an improvement.

**Comment by Koliham** [comment]
This is something I would also like to have. I want the payload of the notification to be consumed and the notification to be dismissed, when the app is opened without clicking on the notification.
I asked StackOverflow, but no answer yet:
https://stackoverflow.com/questions/65534105/flutter-firebase-messaging-consume-notification-when-app-is-started

**Comment by Chinmay-KB** [comment]
I do know how to do this in native android, and I think I can make it work in this case as well. Can anyone confirm if this can/should we worked upon?

**Comment by Wes1324** [comment]
@Chinmay-KB, [FlutterFire's README.md file](https://github.com/FirebaseExtended/flutterfire/blob/master/README.md) states that pull requests are most welcome. Please see the [FlutterFire contribution guidelines](https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md) here and thank you in advance if you make this behaviour possible.

**Comment by Wes1324** [comment]
This issue was holding up the release of my app, so I have made a plugin package that allows for the dismissal of notifications and iOS badge counts programmatically. It can be found here: https://pub.dev/packages/eraser

I'm not sure if it would be possible to incorporate this functionality into the FCM plugin but my plugin resolves my problem so I am closing this issue. I hope my plugin can help people that encounter the same problem in the future.
