### ISSUE TITLE
🐛 [firebase_auth] Creating user with Facebook fails

### ISSUE THREAD

**Issue by RCook1990** [FirebaseExtended/flutterfire#4524]
## Bug report

Firebase Auth sign in works fine for anonymous, google, apple, and email. Currently is not working for Facebook login, returning the error message:

```
Unhandled Exception: [firebase_auth/invalid-credential] The supplied auth credential is malformed or has expired. [ Unsuccessful debug_token response from Facebook: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190,"fbtrace_id":"ATs-4V9W16inLGb7FOgUZPS"}} ]
```

Others with similar problems ([here](https://stackoverflow.com/questions/65265093/the-supplied-auth-credential-is-malformed-or-has-expired-flutter-facebook-log) and [here](https://stackoverflow.com/questions/54922944/fb-login-firebase-auth-error-the-supplied-auth-credential-is-malformed-or-h)) have been due to incorrect setup, usually Facebook App ID and Secret not matching between Facebook, Firebase, and within the project. These have been checked repeatedly. I have tried using the Firebase REST api to create the user, again works for other providers, but still returns the same error when attempting via Facebook.

Facebook login works fine and returned access token works fine when calling FB graph api directly.

If my setup is incorrect and not a bug, perhaps the [documentation](https://firebase.flutter.dev/docs/auth/social/#facebook) needs updating.

### Steps to reproduce

For example using the packages

```
  firebase_core: "^0.5.3"
  firebase_auth: "^0.18.4"
  flutter_facebook_auth: "^1.0.0"
```

And executing

```
final result = await FacebookAuth.instance.login();
final FacebookAuthCredential facebookAuthCredential = FacebookAuthProvider.credential(result.token);
await FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/russellkirk/Development/Flutter
    • Framework revision 1aafb3a8b9 (7 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/russellkirk/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

```

</details>

**Comment by markusaksli-nc** [comment]
Hi @RCook1990 
Have you done this?

> Ensure the "Facebook" sign-in provider is enabled on the Firebase Console. with the Facebook App ID and Secret set.

And from firebase console

> To complete set up, add this OAuth redirect URI to your Facebook app configuration.

Seems like this could be where the message stems from.

Also I would recommend you update to the latest `flutter_facebook_auth: ^1.0.2+2` since 

> Added loginBehavior (Android) to allow select the auth UI like webview, native app or dialogs.

Thank you

**Comment by RCook1990** [comment]
Hi @markusaksli-nc,

Yes, the Facebook sign-in method has been enabled on Firebase and the redirect URI copied to the Facebook console. I copied over the App ID and Secret again just now, and the problem persists. I've also updated to `flutter_facebook_auth: ^1.0.2+2`, and tried the various loginBehaviours.

Thanks for your help

**Comment by markusaksli-nc** [comment]
Are you trying to create with an admin or tester facebook account?

From doing some digging it still seems like the issue could be from you copying a key slightly wrong somewhere https://stackoverflow.com/q/54922944/7007353.

**Comment by RCook1990** [comment]
I've been primarily using my admin account for testing, but I have also created a test user and got the same problem.

It does seem like I have must have mis-copied something, however I keep checking over my config and re-pasting all the relevant keys for this reason and unfortunately the issue persists. I have created a fresh project and re-setup everything and still get the problem. I have also checked if my keys have any whitespace I'm accidentally adding. So as far as I can tell all my keys should be correct, but I shall keep checking.

**Comment by RCook1990** [comment]
Still not working after checking keys, secrets, etc.

For example here are the App Id and Secret in the Facebook console
![Screenshot 2021-01-05 at 11 12 56](https://user-images.githubusercontent.com/28235222/103648251-785add00-4f54-11eb-9a70-fed336bee20a.png)
And here they are in the Firebase console along with the redirect URL...
![Screenshot 2021-01-05 at 12 19 07](https://user-images.githubusercontent.com/28235222/103648496-e2738200-4f54-11eb-980e-85f3f7af60e9.png)
Which has been copied back to the Facebook console
![Screenshot 2021-01-05 at 12 34 08](https://user-images.githubusercontent.com/28235222/103648227-6c6f1b00-4f54-11eb-8657-fd43ba567e75.png)
To setup for Android the ID was put into the manifest
![Screenshot 2021-01-05 at 12 30 43](https://user-images.githubusercontent.com/28235222/103648616-12bb2080-4f55-11eb-952d-bd2035c5cbea.png)
And for iOS in info.plist
![Screenshot 2021-01-05 at 12 58 39](https://user-images.githubusercontent.com/28235222/103649293-20bd7100-4f56-11eb-8ae3-877b5899a3d1.png)

I appreciate the censored keys aren't exact proof, but hopefully convincing evidence. 

As same error occurs in Android and iOS, I'm inclined to think the issue is not with the OS-specific configurations in the manifest and info.plist for example. And since the Facebook access token returned by the login is valid and correctly works when input into Graph Api requests, I don't think the Facebook login has been incorrectly setup.

It seems like either the keys are wrong on the Firebase, or some settings on Firebase or Facebook consoles must be wrong. Although as you can see the keys are correct and so are the settings (as far as I can tell). Not sure where to go from here.

**Comment by markusaksli-nc** [comment]
I can't say where this could be coming from at this point. Labeling this for some further investigation.

**Comment by siddhantkothari** [comment]
I am facing the same problem. I rechecked AppID and App Secret. The OAuth Redirect is also set. Calling Facebook API directly is working(I can retrieve name, email and id of user). The only notable difference from @RCook1990's settings are: 
1. In Facebook login for gaming settings only "Client OAuth Login" is "Yes". 
2. I have not set any namespace in Facebook console.

@RCook1990 Please post solution if you have solved this issue. Thanks.

**Comment by siddhantkothari** [comment]
Also, when I put the redirect URI in "Redirect URI Validator", it gives an error: 
```
This is an invalid redirect URI for this application
You can make this URI valid by adding it to the list of valid OAuth redirect URIs above
```

![image](https://user-images.githubusercontent.com/25146125/103805571-c7e6f900-5079-11eb-900f-23ae59418b6b.png)
Note: both the blacked URIs in the image are same.

**Comment by RCook1990** [comment]
@siddhantkothari  If I find a fix, I will post it here, but still stuck for now. As for the error when you input the redirect URI, you need to enable Login for Web in order for the check to work. Also make sure after you input the URI into Valid OAuth Redirect URIs, you hit save.

**Comment by RCook1990** [comment]
Problem solved! Issue was not with firebase_auth, but with how the app is set up on the Facebook developer console. When first creating the app you are presented with the following menu

![Screenshot 2021-01-21 at 12 20 08](https://user-images.githubusercontent.com/28235222/105350838-a3dff780-5be3-11eb-9c92-8eeb06a73c5c.png)

I originally selected "Build or Connect to a Game" as it says it is used when connecting to a gaming app played on or off the Facebook Platform, which is what best describes my app. I re-setup the app on FB, but now chose "Build Connected Experiences" and now it works. No idea why though.
