### ISSUE TITLE
🐛 [flutter_messaging] how to get push notification app closed

### ISSUE THREAD

**Issue by sante85** [FirebaseExtended/flutterfire#4530]
## Bug report
if I not open push notification on system bar, my app not receive notification on event handler

**Describe the bug**
if I not open push notification on system bar, my app not receive notification on event handler.

### Steps to reproduce

app registered to topic
app closed
Send push notification -> flutter messaging will be notify my event handler to save notification
when i open app, notification is  not showed

### Expected behavior
app registered to topic
app closed
Send push notification -> flutter messaging call an event handler to store notification on my service or shared preference
when i open app, notification is showed (such as whatsapp application)

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.17.5, on Microsoft Windows [Versione 10.0.19042.685], locale it-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[!] Android Studio (not installed)
[√] Connected device (1 available)

### Flutter dependencies

firebase_core: 0.5.2+1
  firebase_messaging: 7.0.3
  flutter_local_notifications: 3.0.2

**Comment by markusaksli-nc** [comment]
Hi @sante85 
This sounds like an issue with the background messaging setup. Since you are using a quite outdated version of flutter it could cause some incompatibility. I would recommend updating to at least the new stable. Could you try to see if the new `firebase_messaging: ^8.0.0-dev.11` version fixes the issue for you?
Thank you

**Comment by sante85** [comment]
Hi,
i have configured backgroung handler

FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();

Future<dynamic> _backgroundMessageHandler(Map<String, dynamic> message) {
  var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      'your channel id', 'your channel name', 'your channel description',
      importance: Importance.high, priority: Priority.high);
  var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
  var platformChannelSpecifics = new NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics);
  NotificationService.getInstance().addNotification(message);
  flutterLocalNotificationsPlugin.show(0, "a", "body", platformChannelSpecifics);
}

......

package com.example.plants_market;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}

but is never called -> app in background or app closed

**Comment by markusaksli-nc** [comment]
Yes, what I said previously still applies.

There is no need for this native workaround on the new dev version and that's why it could solve the issue for you. The version you are using will be replaced soon.

**Comment by sante85** [comment]
ok, but  firebase_messaging: 7.0.3 is the last?

**Comment by markusaksli-nc** [comment]
`firebase_messaging: ^8.0.0-dev.11` is the lates version.

**Comment by sante85** [comment]
Exist a guide to migrate?

**Comment by markusaksli-nc** [comment]
See the documentation at https://firebase.flutter.dev/docs/migration#messaging and https://firebase.flutter.dev/docs/messaging/overview#3-android-integration

**Comment by sante85** [comment]
with 8.x
i have  
No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

**Comment by markusaksli-nc** [comment]
Have you called `Firebase.initializeApp()`?

**Comment by sante85** [comment]
yes, i have resolved it.

Best regards

Il giorno lun 4 gen 2021 alle ore 08:12 Markus Aksli <
notifications@github.com> ha scritto:

**Comment by markusaksli-nc** [comment]
Closing this as solved based on your last message.
