### ISSUE TITLE
[firebase_ml_vision] Camera Lag on FirebaseVision.instance.textRecognizer().processImage

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#454]
## Steps to Reproduce
I am using this code https://github.com/bparrishMines/mlkit_demo
Everything works fine but sincerely the firebase_ml_vision looks like a lag when its processing? Is it normal or is there a better implementation?
I have disabled almost everything from the app and its the processImage what its taking the processing time FirebaseVision.instance.textRecognizer().processImage

**Comment by kroikie** [comment]
@pmcarlos

The issue at https://github.com/flutter/flutter/issues/27716 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi 
Did the [proposed solution](https://github.com/flutter/flutter/issues/27716#issuecomment-482522788) worked? 
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
