### ISSUE TITLE
🐛 [FirebaseMLVision] Firebase ML Vision doesn't work on CameraImage 

### ISSUE THREAD

**Issue by rupa6** [FirebaseExtended/flutterfire#4549]
## Bug report

I am trying to detect faces on the stream of `CameraImages` (provided by [camera plugin](https://github.com/flutter/plugins/blob/master/packages/camera/camera/lib/src/camera_image.dart#L118)) and using a similar transformation as pointed in [example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_ml_vision/example/lib/scanner_utils.dart) to convert YUV_420 to NV_21. But Firebase is not able to recognize any face in `CameraImage` while if the same is applied on a clicked photo it does it very well.

### Steps to reproduce

Try to run the example in FirebaseMLVision and detect a face in CameraPreviewScanner.

## Additional context
I tried these two things which couldn't work for me - 
- Switching to the old version of `camera` and `firebase_ml_vision` in pubspec. 
- Using the same example code with my `pubspec` & android folder (due to dependency conflicts).

**Comment by rupa6** [comment]
While I was about to lose, it just worked with camera version '0.5.8+1' and firebase_ml_vision: '0.8.0'. :)

Probably this should be transferred to the camera plugin team because I tried with the same firebase_ml_vision and the latest camera plugin which didn't work for me.

**Comment by markusaksli-nc** [comment]
Closing this as solved based on your last comment

**Comment by rupa6** [comment]
I think this should not be closed as `solved` because it wasn't working on the latest camera version. Perhaps, this should be assigned to the camera team for further inspection on the latest version.
