### ISSUE TITLE
[all] D8: Cannot fit requested classes in a single dex file

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#455]
Including multiple firebase_ plugins simultaneously in a `pubspec.yaml` file is enough to [exceed the amount of Java methods that can be included in an Android APK by default, so compilation breaks](https://developer.android.com/studio/build/multidex).

## Repro steps

1. `flutter create foo`
2. Edit the `pubspec.yaml` to add the extra deps below.

```yml
dependencies:
  cloud_firestore: any
  firebase_core: any
  firebase_database: any
  firebase_ml_vision: any
  firebase_performance: any
  firebase_remote_config: any
  firebase_storage: any
```

3. `flutter build apk`

## Error output

```
flutter build apk
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.4s
D8: Cannot fit requested classes in a single dex file (# methods: 76505 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
```

## Fix for affected apps

This can be addressed in affected apps using the plugins by [turning on multidexing](https://developer.android.com/studio/build/multidex#mdex-gradle) in their build following the same steps as a typical Android app.

## Fix for the plugins?

It's not clear to me what should be done about this. It ties into wider ongoing discussions about abstracting underlying platform code.

1. We could grep or lint for this error in `flutter tool` and print out a log pointing users to something explaining this error, what multidexing is, how to turn it on.
2. We could warn for this in the README of the firebase plugins themselves since they're likely to be used in combination.
3. There may be a way to turn on multidexing for an app within a plugin? I'm not sure if this is actually preferable here even if it's possible. Multidexing has [downsides](https://developer.android.com/studio/build/multidex#dev-build).
4. Could we proguard the plugins without turning proguard on for entire apps that include them? This would prune unused methods and make it a lot harder to hit this error, but wouldn't totally prevent it.

/cc @Sun3
/cc @dnfield @Hixie @amirh

**Comment by kroikie** [comment]
@mklim

The issue at https://github.com/flutter/flutter/issues/27702 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @mklim
You might want to check this possible [solution](https://github.com/FirebaseExtended/flutterfire/issues/700)
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by austinmarner** [comment]
I too had the same problem I just changed my min SDK version above 21 in the manifest, It solved the problem for me

**Comment by nguyenxndaidev** [comment]
For now, changing min SDK to 21 means losing ~5-6% old devices. Do you plan to make firebase sdk to work with SDK 16?

**Comment by nguyenxndaidev** [comment]
Found this useful document https://developer.android.com/studio/build/multidex

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release. Additionally we have some [multidex related documentation now on the documentation website.](https://firebase.flutter.dev/docs/installation/android#enabling-multidex)
