### ISSUE TITLE
🐛 [firebase_messaging] Invalid eventTimestamp shown in notification

### ISSUE THREAD

**Issue by rajveermalviya** [FirebaseExtended/flutterfire#4553]
## Bug report

**Describe the bug**
If custom `eventTimestamp` is specified when sending notification from firebase admin sdks (tested on Node.js & Golang)
the notification time always defaults to `51y`.

![photo_2021-01-02_17-46-36](https://user-images.githubusercontent.com/36819268/103457139-82959500-4d22-11eb-9f88-3438c16091a2.jpg)

### Steps to reproduce

1. Send this notification from Node.js firebase-admin-sdk
```ts
const msg: messaging.Message = {
  token: token,
  android: {
    notification: {
      title: title,
      body: body,
      eventTimestamp: new Date(),
    },
  },
};

await firebaseMessaging.send(msg);
```
2. See the incorrect time shown in notification.

### Expected behavior

The custom `eventTimestamp` specified in `msg` should have been used.
Instead it's taking 0 (because 2021-51 = 1970; which is zero in unix epoch).

---

## Additional context

From glancing the source code [`remoteMessageNotificationToMap`](https://github.com/FirebaseExtended/flutterfire/blob/542917a50758413b63f82ab3213263f640a8877b/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java#L79) doesn't seem to use [`RemoteMessage.Notification.getEventTime()`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getEventTime()).

also when specifying  `eventTimestamp` it seems like [`RemoteMessage.getSentTime()`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage#public-long-getsenttime) returns zero, so [`RemoteMessage.Notification.getEventTime()`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getEventTime()) should be used instead.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_IN.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core: 0.5.3
firebase_messaging: 7.0.3
```

</details>

---

**Comment by rajveermalviya** [comment]
same behavior with `firebase_messaging: ^8.0.0-dev.11`

**Comment by TahaTesser** [comment]
Hi @rajveermalviya 
Please use `event_time` property with time in milisseconds.
```js
const functions = require('firebase-functions');

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });


const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);




const payload = {
    'notification': {
        'title': 'this is a title',
        'body': 'this is a body',
        'event_time':'1577817000000'
    },
    'data': {
        'click_action': 'FLUTTER_NOTIFICATION_CLICK',
        'id': '1',
        'status': 'done',
    }
};

exports.sendnotification = functions.https.onRequest((request, response) => {

    const tokens = request.query.fcm || "Unknown"
    response.send("Notification is sent to".concat(tokens));

    return admin.messaging().sendToDevice(tokens, payload);
});
```
You're seeing 51 years due to incorrect payload. Check this [answer](https://stackoverflow.com/a/59560373) 


Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by rajveermalviya** [comment]
Thanks but I can't find `event_time` in root `notification` documented anywhere. 

[nodejs](https://firebase.google.com/docs/reference/admin/node/admin.messaging.Notification)
[nodejs sdk source](https://github.com/firebase/firebase-admin-node/blob/eecbe414e9bea5489db37cd1f39ee8776c5b96a6/src/messaging/index.ts#L90)
[golang](https://pkg.go.dev/firebase.google.com/go/v4@v4.1.0/messaging#Notification)

Also, i think you are mistaken, even in the [answer](https://stackoverflow.com/questions/59560153/fcm-in-android-notification-payload-event-time/59560373#59560373) that you linked, if you look at the question `event_time` is used in `android.notification` not in root `notification`.
And Node.js sdk only accepts `Date` obj in [`android.notification.eventTimestamp`](https://github.com/firebase/firebase-admin-node/blob/eecbe414e9bea5489db37cd1f39ee8776c5b96a6/src/messaging/index.ts#L560) and then converts it to timestamp in milliseconds [implicitly](https://github.com/firebase/firebase-admin-node/blob/eecbe414e9bea5489db37cd1f39ee8776c5b96a6/src/messaging/messaging-internal.ts#L458).

Okay back to issue - `android.notification.eventTimestamp` is the only way to add custom timestamp to notifications & it it's not supported by FlutterFire.

I mentioned in the description too but I guess it was overlooked -
[remoteMessageNotificationToMap](https://github.com/FirebaseExtended/flutterfire/blob/542917a50758413b63f82ab3213263f640a8877b/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java#L79) doesn't seem to use [RemoteMessage.Notification.getEventTime()](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getEventTime()).

And when `eventTimestamp` is specified it seems like [RemoteMessage.getSentTime()](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage#public-long-getsenttime) returns zero, so [RemoteMessage.Notification.getEventTime()](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getEventTime()) should be used as a fallback.

**Comment by TahaTesser** [comment]
Hi @rajveermalviya 
Thanks for clarifying

**Comment by russellwheatley** [comment]
The admin SDK no longer has a [custom timestamp](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.notificationmessagepayload.md#notificationmessagepayload_interface) available, and this isn't something Flutterfire has control over in any event. Notifications are intercepted by the Firebase messaging SDK.
