### ISSUE TITLE
[firebase_auth] Web authentication status not persistent across site reload

### ISSUE THREAD

**Issue by kushalgoel786** [FirebaseExtended/flutterfire#4556]
## Bug report

**Describe the bug**
While Developing for Flutter Web, contradicting to what is stated in the FlutterFire Docs, the authentication state is not persisted for the user.

**Comment by TahaTesser** [comment]
Hi @kushalgoel786
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
