### ISSUE TITLE
firebase_auth

### ISSUE THREAD

**Issue by johnyenatu** [FirebaseExtended/flutterfire#4569]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:firebase_auth/src/firebase_auth.dart': Failed assertion: line 642 pos 12: 'codeAutoRetrievalTimeout != null': is not true.  my code is working perfectly 1 weak ago but now it is throwing this error

**Comment by TahaTesser** [comment]
Hi @johnyenatu 
Did you update `firebase_auth`? 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`  a complete reproducible minimal code sample
Thank you

**Comment by sudarshanmoram** [comment]
Unhandled Exception: 'package:firebase_auth/src/firebase_auth.dart': Failed assertion: line 633 pos 12: 'codeAutoRetrievalTimeout != null': is not true. 

my code is working perfectly for flutter firebase plugins:
 firebase_auth: ^0.14.0+5, 
firebase_core: ^0.4.0+9, 
cloud_firestore: ^0.13.0+1

 Now updated to :
firebase_auth: ^0.20.0+1, 
firebase_core: ^0.7.0, 
cloud_firestore: ^0.16.0 
its throwing error.
