### ISSUE TITLE
[cloud_firestore] error - Cannot fit requested classes in a single dex file

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#457]
If I try to put both Auth and Firestore plugins in the same project, I get the above error. But I can only put ONE plugin in the dependencies section.
What is problem?

Here, these two versions work independently but not together.
```yml
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.6
```

**Comment by kroikie** [comment]
@BenHayat

The issue at https://github.com/flutter/flutter/issues/27682 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @BenHayat
Did the proposed [solution](https://github.com/flutter/flutter/issues/27682#issuecomment-504689285) worked? 
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by akatriel** [comment]
Changing minSDK version in the app's Build.Gradle to >=21 is a potential fix.
