### ISSUE TITLE
🐛 [firebase_messaging] Flutter Firebase messaging service not working on IOS Archive IPA

### ISSUE THREAD

**Issue by hamza-gaya** [FirebaseExtended/flutterfire#4577]
My token is correct. Although I have tried revoking the certificate and APN key and generated a new provisioning profile for my flutter iOS app and reconfigured my app again with this new certificate, provisioning profile and the APN key. I also removed the reference of my google info.plist file in runner in xcode and re added the reference again. I also removed my entire app from the firebase and then generated a new file google-info.plist file and then added the reference again in the xcode in main runner folder but nothing worked. Also I have tried deleting the reference and file of entitlement included in the runner folder and reconfigured capabilities of background modes and push notification but still no luck. One day before it worked magically after some time but now it's not working on Archive IPA, Although we are recieving notifications in debug and release mode while building our app from mac. I don't know what the fuck is going on in this stupid IOS technology. However all things are working fine and smoothly on android apk. In short I have tried all things but nothing works.

This is my raw json data while testing from post man:
{
	"to" : 
    "esvDPL_gZ0PckAzrH35KWo:APA91bHMA23iTQii7y8V1Ws2BSBkVqQXA0edfcFJATdZNyHJTLUoWZbCRiPcBVjqiTAWarc4OdzyBdMVItj4V1P4MBo0i5ivoXdOFzU89XBUwsYBq7EzHDfzyiLwyGhxzVjtdQw8JYHO",
	"collapse_key" : "New Message",
	"notification" : {
        "body" : "Body of Your Notification",
        "title": "Title of Your Notification"
	},
	"data" : {
        "body" : "Body of Your Notification",
        "title": "Title of Your Notification"
	}
}
below is my screen shot of the result
<img width="1440" alt="Screenshot 2021-01-06 at 11 09 12 AM" src="https://user-images.githubusercontent.com/62129887/103735528-152e8080-5010-11eb-849a-4c7ea359d8f9.png">

**Comment by markusaksli-nc** [comment]
Hi @hamza-gaya
First off have you tried just sending a notification to the entire ios package from firebase console? 

Secondly, I see that you are using the legacy FCM HTTP API.  This should be fine but you could try to send it through the v1 API instead. That's actually what the upstream docs recommend https://firebase.google.com/docs/cloud-messaging/migrate-v1

> Currently FCM provides these raw server protocols:

> *   FCM HTTP v1 API
> *   Legacy HTTP protocol
> *   Legacy XMPP Protocol

> Your app server can use these protocols separately or in tandem. Because it is the most up-to-date and most flexible for sending messages to multiple platforms, the FCM HTTP v1 API is recommended wherever feasible.

You can send through the v1 API with either a JWT token in postman or the admin SDK. See this comment for examples https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877.

Could you please also provide the `flutter doctor -v` and `flutter pub deps -- --style=compact` of the build environment project?
Thank you

**Comment by hamza-gaya** [comment]
@markusaksli-nc, Yes I could provide you the results of these commands but I am sending and receiving notification in my flutter app using their respective plugins of firebase messaging and flutter local notifications using firebase console it doesn't send message to my device so that's why we used this post man structure to test it because we could not get any error report from the firebase console. But after 1 day gap my apps started receiving notifications on IPA. But Now I again generated IPA of my apps from Xcode and still this issue persists. Any help would greatly be appreciated!

Here is my flutter doctor -v screenshot:
<img width="1440" alt="Screenshot 2021-01-13 at 5 24 58 PM" src="https://user-images.githubusercontent.com/62129887/104452300-a380a480-55c4-11eb-9630-5ff8db64865b.png">


and here is my flutter pub deps -- --style=compact result:
<img width="1440" alt="Screenshot 2021-01-13 at 5 26 40 PM" src="https://user-images.githubusercontent.com/62129887/104452399-c57a2700-55c4-11eb-946e-ccb3629d61ae.png">
<img width="1440" alt="Screenshot 2021-01-13 at 5 26 57 PM" src="https://user-images.githubusercontent.com/62129887/104452412-cc089e80-55c4-11eb-9b31-6cd53b44a767.png">

**Comment by hamza-gaya** [comment]
Please help me urgently because my work is stuck with this bug

**Comment by hamza-gaya** [comment]
Unistalling the app and then reinstalling it and again uninstalling the app and reinstalling it again the app on my iphone 7 on second attempt notifications started receiving on my device for now but this is not a permanent solution to it. It might frustrate the end user.

**Comment by markusaksli-nc** [comment]
I'm not seeing this issue with the latest `firebase_messaging: ^8.0.0-dev.14`.

<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.313, on macOS 11.1 20C69 darwin-arm,
    locale en-GB)
    • Flutter version 1.26.0-2.0.pre.313 at
      /Users/nevercode/development/flutter_master
    • Framework revision 1cb0a24a46 (35 hours ago), 2021-01-12 21:39:27 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
</details>

Would you consider updating to the latest version of the package? It is a lot more stable and there have been major improvements. The version you are using will be replaced soon. There are a lot of breaking changes https://firebase.flutter.dev/docs/migration/#messaging.

**Comment by hamza-gaya** [comment]
Ok @markusaksli-nc  I'll give it a try and tell you about this

**Comment by hamza-gaya** [comment]
Thanks Markus for solving my issue, now I can happily deliver my project to the client. I have tested it on iphone 7 and iphone X as well it works. Thanks a lot for helping me and responding me promptly.  Flutter team should update their documentation with latest updates and plugins as well in these links: https://pub.dev/packages/firebase_messaging, https://pub.dev/packages/firebase_core and https://pub.dev/packages/firebase_analytics. I was following their pub dev article and that's why I was stuck on this in iphone. But thanks a lot for solving the issue @markusaksli-nc

**Comment by markusaksli-nc** [comment]
No problem, glad I was able to help.

Closing the issue as solved.

**Comment by GilbertoGmobil** [comment]
> Thanks Markus for solving my issue, now I can happily deliver my project to the client. I have tested it on iphone 7 and iphone X as well it works. Thanks a lot for helping me and responding me promptly. Flutter team should update their documentation with latest updates and plugins as well in these links: https://pub.dev/packages/firebase_messaging, https://pub.dev/packages/firebase_core and https://pub.dev/packages/firebase_analytics. I was following their pub dev article and that's why I was stuck on this in iphone. But thanks a lot for solving the issue @markusaksli-nc

Could You share your code? I'm with a similar problem : https://github.com/FirebaseExtended/flutterfire/issues/4687. Thank you
