### ISSUE TITLE
[📚] Missing square brackets in the regexp in firebase_messaging/FirebaseMessaging/subscribeToTopic

### ISSUE THREAD

**Issue by ma-ruz** [FirebaseExtended/flutterfire#4578]
Current text:
topic must match the following regular expression: "a-zA-Z0-9-_.~%{1,900}".

Should be:
topic must match the following regular expression: "[a-zA-Z0-9-_.~%]{1,900}".

**Comment by dackers86** [comment]
Hi @ma-ruz 

Can you confirm the source of where you are getting the current text?

**Comment by ma-ruz** [comment]
Hi @dackers86 ,
it's on https://pub.dev/documentation/firebase_messaging/8.0.0-dev.11/firebase_messaging/FirebaseMessaging/subscribeToTopic.html
Seems like there are square brackets in the docs source but they are converted to formatting as <code> so probably some escape character is missing...
