### ISSUE TITLE
[firebase_auth] User is signed out after updating the app from App Store

### ISSUE THREAD

**Issue by timofeykovalenko** [FirebaseExtended/flutterfire#4579]
## Bug report

Firebase has "sign out" state when app updating from app store.

### Steps to reproduce
1. App with firebase version 0.16.1
2. Publish app to app store.
3. Has app with "sign in" state
4. App with firebase version 0.18.4+1
5. Publish app to app store.
6. Update existed app from app store
7. App has "sign out" state instead of "sing in"

### Expected behavior

 App has "sign in" state

**Comment by markusaksli-nc** [comment]
Hi @timofeykovalenko 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What exactly do you mean by "sign in" or "sign out" state?
Thank you

**Comment by timofeykovalenko** [comment]
@markusaksli-nc I mean, user use the app, and user is logged in. Then user downloaded new version from app store, and when user open the app, login is gone and user should login again.

`flutter doctor -v` results:
`[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at XXXXX/flutter_sdk/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at XXXXX/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0
`

`flutter pub deps -- --style=compact ` resuls:

`dependencies:
- cached_network_image 2.4.1 [flutter flutter_cache_manager octo_image]
- device_info 1.0.0 [flutter device_info_platform_interface]
- easy_localization 2.3.3 [flutter intl shared_preferences args path flutter_localizations]
- facebook_app_events 0.8.2 [flutter]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.4 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_database 4.4.0 [flutter firebase_core]
- firebase_remote_config 0.4.3 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_auth 1.0.2+2 [flutter]
- flutter_inapp_purchase 3.0.1 [http meta flutter platform]
- flutter_local_notifications 3.0.2 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- intl 0.16.1 [path]
- launch_review 2.0.0 [flutter]
- lottie 0.7.0+1 [archive characters charcode collection flutter logging meta path vector_math]
- notification_permissions 0.4.8 [flutter]
- package_info 0.4.3+2 [flutter]
- path 1.8.0-nullsafety.1
- provider 4.3.2+3 [collection flutter nested]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 2.5.4 [meta flutter]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.2 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- octo_image 0.3.0 [flutter flutter_blurhash]
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.22 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.4+1 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+3 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
`

**Comment by markusaksli-nc** [comment]
Not sure if this is just an issue with the native sdk or not.

**Comment by timofeykovalenko** [comment]
According documentation login session should alive, so I don't think it is a feature.

**Comment by devolab** [comment]
any news on this? We have exactly the same issue on both Apple and Google play store. When the user does an update and they are logged in, they get kicked out and asked to login again.

**Comment by senagbe** [comment]
@markusaksli-nc this is a critical issue for us so I can volunteer one of my dev team to look at this if we can get direction for where to look. I'm pretty sure this is not a native issue since I'm involved with a separate app which also uses Firebase Auth (Native) on Android and iOS and is able to update without logged in state being lost.
@devolab is a colleague. and I have 2 Flutter/Native devs who rely on this plugin and one of which I can commit full time to this issue.

**Comment by markusaksli-nc** [comment]
@senagbe This shouldn't be an issue in the code in this repository since we're only delegating calls to the native SDK. It could be the difference in the underlying native SDK version in both cases or how Flutter builds do code signing causing the old keychain to become obsolete.

Since this is being caused by updates it's a bit of a pain to test but you could try something like setting the native Firebase SDK constraint to be the same on both the flutter and native projects to rule that out. If the flutter build tool is at fault I'm not sure where to look but if you find the cause there it would have to be raised in flutter/flutter.

Due to the reason mentioned above, there really isn't anywhere I would be able to point you to in this repository.

**Comment by senagbe** [comment]
@markusaksli-nc thanks for pointing us in the right direction. I have a couple of developers investigating this so we'll let you know what, if anything we find.

**Comment by jangruenwaldt** [comment]
Same issue here! Very terrible for users, e.g. if anonymous sign in might loose their data.

**Comment by Ehesp** [comment]
> Update: Okay, great news! 1.1.3 version of this plugin fixes it, 1.1.2 

There was a generic issue which popped up where users on iOS weren't being "loaded" in on app load, which has now been fixed. I don't think this is related to the OP issue.

Generally the issue described here is something which we have no control over. As already mentioned we  collect the data from the native SDKs and pass them to Dart land. 

My only underlying thought here is that as internal SDK versions are being updated in FlutterFire with releases, the native SDKs might have to lose user authentication state in some cases where new features/deprecations are in place. Total guess though.

I'd be inclined to pass this as a Firebase SDK issue - if possible creating a native simple reproduction and then creating an issue on the Firebase GitHub repo would be a good place to start.

**Comment by jangruenwaldt** [comment]
> > Update: Okay, great news! 1.1.3 version of this plugin fixes it, 1.1.2
> 
> There was a generic issue which popped up where users on iOS weren't being "loaded" in on app load, which has now been fixed. I don't think this is related to the OP issue.
> 
> Generally the issue described here is something which we have no control over. As already mentioned we collect the data from the native SDKs and pass them to Dart land.
> 
> My only underlying thought here is that as internal SDK versions are being updated in FlutterFire with releases, the native SDKs might have to lose user authentication state in some cases where new features/deprecations are in place. Total guess though.
> 
> I'd be inclined to pass this as a Firebase SDK issue - if possible creating a native simple reproduction and then creating an issue on the Firebase GitHub repo would be a good place to start.

Sorry, I should have been more clear. Version 1.1.2 of firebase_auth had a bug, that caused users to be signed out after updating from the app store. Version 1.1.3 fixed that. We do not encounter this bug anymore. But this is, infact, not related to OP issue. I only commented here, since I was experiencing the same behaviour as OP, albeit for a different reason, as it turns out.
