### ISSUE TITLE
InterstitialAd listener not working

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#458]
## Steps to Reproduce

My app consists of BannerAd and InterstitialAd. Whenever I initialise both type of ads, listener of InterstitialAd not responding, always intercept by BannerAd listener.

If interstitial ad is loaded:
`BannerAd event is MobileAdEvent.loaded`, expect `InterstitialAd event is MobileAdEvent.loaded`

If interstitial ad is clicked:
`BannerAd event is MobileAdEvent.clicked`, expect `InterstitialAd event is MobileAdEvent.clicked`

If interstitial ad is closed:
`BannerAd event is MobileAdEvent.closed`, expect `InterstitialAd event is MobileAdEvent.closed`

```dart
void main() {
  BannerAd bannerAd;
  bannerAd = BannerAd(
    adUnitId: BannerAd.testAdUnitId,
    size: AdSize.fullBanner,
    listener: (MobileAdEvent event) {
      print('BannerAd event is $event');
      if (event == MobileAdEvent.loaded) {
        bannerAd.show();
      }
    },
  )..load();

  InterstitialAd interstitialAd;
  interstitialAd = InterstitialAd(
      adUnitId: InterstitialAd.testAdUnitId,
      listener: (MobileAdEvent event) {
        print('InterstitialAd event is $event');
      }
  )..load();
  
  Future.delayed(Duration(seconds: 5), () async {
    if (await interstitialAd.isLoaded()) {
      interstitialAd.show();
    }
  });
}
```

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D42, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.2)
[✓] Connected device (3 available)
```

**Comment by kroikie** [comment]
@anderscheow

The issue at https://github.com/flutter/flutter/issues/27671 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by alejantab** [comment]
Some solution?

**Comment by kroikie** [comment]
@alejantab sorry no solution yet. We are working on it and will provide updates here.

**Comment by iPatel007** [comment]
I added BannerAd and  InterstitialAd in same page and getting same issue. So in this case, is there   chance to suspend app due to wrong impression?

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/135
https://github.com/FirebaseExtended/flutterfire/issues/63
https://github.com/FirebaseExtended/flutterfire/issues/464

**Comment by iapicca** [comment]
Hi @anderscheow
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/63)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
