### ISSUE TITLE
[📚] Docs imports shouldn't have 

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#4587]
The docs provide double quotes on the versions to download:

![image](https://user-images.githubusercontent.com/8120472/103893671-6c922680-50cc-11eb-91d4-21bc37c32d9d.png)

But those versions don't need it.

______________

Also, the copy button will copy the whole text, it should only copy the highlighted part.

**Comment by asashour** [comment]
> Also, the copy button will copy the whole text, it should only copy the highlighted part.

Could you please advise where this is referenced?

**Comment by feinstein** [comment]
Just open any docs that have an example and click on the copy button over the top and try to paste it.

**Comment by dackers86** [comment]
Hi @feinstein 

The docs are currently developed through Docusaurus and Prism via https://v2.docusaurus.io/docs/markdown-features/#code-blocks.

I don't think that type of feature is implemented. These could be a useful feature for future versions of the documentation, but it seems they cannot be improved at this time.

**Comment by feinstein** [comment]
Oh, I see, so I will close this issue then, thanks a lot!
