### ISSUE TITLE
Firebase Deeplinks not returned after first install in release mode - iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#459]
## Steps to Reproduce

1. Create a deeplink using Firebase console.
2. Make sure app is not installed.
3. Tap on deeplink, navigates to App Store, download the app.
4. App opens after install.
5. Deeplink is null in _retrieveDynamicLink().

Please note this happens only in AppStore (release builds), when I do the same steps in debug mode I get the deeplink tapped.

I am using https://pub.dartlang.org/packages/firebase_dynamic_links.

## Logs

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Users/user/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] VS Code (version 1.31.0)
    • VS Code at /Users/karthiksa/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone X • 9389873 • ios • iOS 12.1.3

• No issues found!

```

**Comment by kroikie** [comment]
@KarthikSCP

The issue at https://github.com/flutter/flutter/issues/27658 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by tapkain** [comment]
Hello, is there any quick fix on this? Or any details where to look for the problem?

**Comment by iapicca** [comment]
Hi @KarthikSCP
(and hello to @tapkain as well)
if are you still experiencing this issue with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by tapkain** [comment]
@iapicca Checked it out, seems like on the debug version it's working. Will deploy today to app store and check on the release version

**Comment by tapkain** [comment]
The version from App Store doesn’t work... this means the whole plugin right now for iOS is useless...

**Comment by CedYF** [comment]
I have this same problem of not being able to get the data from the App Store.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release.
