### ISSUE TITLE
[cloud_firestore] Convert Timestamp to DateTime

### ISSUE THREAD

**Issue by Levi-Lesches** [FirebaseExtended/flutterfire#46]
Is there a really good reason why this library doesn't use DateTime? Is there a significant difference between the two?

**Comment by jgithaiga** [comment]
You can call `toDate()` on a Cloud Firestore Timestamp to convert it to DateTime.
```
DocumentSnapshot snapshot = ....
DateTime dateCreated = snapshot.data["dateCreated"]?.toDate();
```

**Comment by collinjackson** [comment]
> Well, I need to serialize it into JSON first, so neither Timestamp not DateTime really work for me. What I ended up doing was essentially what `Timestamp.toDate` does -- convert to microseconds and then deserialize that back into a DateTime after reading back the JSON.
> 
> But I'm just curious as to why Timestamp is even used in the first place. Since it so conveniently converts to DateTime anyway, is there a reason why it's even used?

I think the main reason is that we're trying to match the other Firebase client SDKs as much as possible.

I don't think there's anything actionable here so I'm closing it, but please let me know if you feel I'm mistaken.

**Comment by Levi-Lesches** [comment]
If there is literally not one difference between `Timestamp` and `DateTime`, then we can majorly simplify the API by getting rid of `Timestamp`s. It would help the average Flutter user and simplify a lot of everyone's code + logic.
