### ISSUE TITLE
🐛 [firebase_messaging] Firebase messaging notification is not showing when the app is in foreground

### ISSUE THREAD

**Issue by dsourav** [FirebaseExtended/flutterfire#4609]
**Bug Description:**

I am trying to use [firebase_messaging](https://pub.dev/packages/firebase_messaging) and [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) plugin for sending notification to app. I am sending test notifications from the firebase console using fcm token of the device but the notification is only receiving while the app is in the background. Any help will be appreciated thanks in advance.

**Here is my code:**

```
class FirebaseNotificationService {
  
 // final _navigationService = locator<NavigationService>();

  FirebaseMessaging _firebaseMessaging;


  get firebaseMessaging => _firebaseMessaging;

  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =  FlutterLocalNotificationsPlugin();

  FirebaseNotificationService._internal() {
   _firebaseMessaging = FirebaseMessaging();
   configLocalNotification();
  firebaseCloudMessagingListeners();
   
  }

  static final FirebaseNotificationService _instance =
      FirebaseNotificationService._internal();
  static FirebaseNotificationService get instance {
    return _instance;
  }

  Future<String> deviceToken() async {
    var token = await _firebaseMessaging.getToken();
    return token;
  }

  void firebaseCloudMessagingListeners() {

   _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
       print(message);
        showNotification(message);
    
      },
      onResume: (Map<String, dynamic> message) async {
          print("called");
      },
      onLaunch: (Map<String, dynamic> message) async {
          print("called");
      },
    );
  }

    void configLocalNotification() {
    var initializationSettingsAndroid = new AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = new IOSInitializationSettings();
    var initializationSettings = new InitializationSettings(android:initializationSettingsAndroid,iOS: initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }

    void showNotification(message) async {
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      Platform.isAndroid ? 
      'high_importance_channel': 
      'com.devbrid.ouiDating',
      'This channel is used for important notifications.',
      '',
      playSound: true,
      enableVibration: true,
      importance: Importance.max,
      priority: Priority.high,
  
    );
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics =
        new NotificationDetails(android: androidPlatformChannelSpecifics,iOS: iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        0,"hi",
        // message['notification']['title'].toString(), 
        "jello",
      //  message['notification']['body'].toString(),
         platformChannelSpecifics,
        payload: json.encode(message));
        
  }
}

class MyApp extends StatelessWidget {


  MyApp(){
    FirebaseNotificationService.instance;
  }

  @override
  Widget build(BuildContext context) {     
    return MaterialApp(
      title: 'Oui Dating',
      theme: ThemeData(
          primarySwatch: Colors.red,
          dialogBackgroundColor: Colors.black,
          dialogTheme: DialogTheme(
            backgroundColor: Colors.black,
          )),
      onGenerateRoute: RouteTo.generateRoute,
      initialRoute: RouteTo.splashView,
      navigatorKey: locator<NavigationService>().navigatorKey,
    );
  }
}
```

AndroidManifest.xml File:

<details><summary>Click To Expand</summary>

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.devbrid.oui_dating">
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />    
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
   
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Oui Dating"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"     android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
              <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @dsourav 
Does the [official example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib) with the latest `firebase_messaging: ^8.0.0-dev.11` not work for you? Which callback or stream isn't being called exactly?
Thank you

**Comment by dsourav** [comment]
**flutter doctor -v** 

[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/devsrv/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/devsrv/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /home/devsrv/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/devsrv/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • A3 (mobile) • A3201809040987 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

**flutter pub deps -- --style=compact**

Dart SDK 2.10.4
Flutter SDK 1.22.5
oui_dating 1.0.0+1

dependencies:
- agora_rtc_engine 3.2.1 [flutter flutter_web_plugins json_annotation]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.7.2 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- cupertino_icons 0.1.3
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_database 4.4.0 [flutter firebase_core]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_storage 4.0.1 [flutter firebase_core]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_datetime_picker 1.4.0 [flutter]
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_local_notifications 2.0.2 [flutter platform flutter_local_notifications_platform_interface timezone]
- geocoder 0.2.1 [meta flutter]
- geoflutterfire 2.2.1 [flutter cloud_firestore rxdart]
- geolocator 6.1.5 [flutter geolocator_platform_interface]
- get_it 5.0.1 [async meta]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- image_picker 0.6.7+12 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- nuts_activity_indicator 0.1.1 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- provider 4.3.2+2 [flutter nested collection]
- rxdart 0.24.1
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- stacked 1.7.6 [flutter provider observable_ish]
- timeago 2.0.28

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 3.0.3 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.1.1 [firebase_core firebase_core_web cloud_functions_platform_interface flutter flutter_web_plugins http_parser meta js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- geolocator_platform_interface 1.0.8 [flutter meta plugin_platform_interface vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- js 0.6.2
- json_annotation 3.1.1
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- observable_ish 2.1.4 [collection]
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.8.0-nullsafety.1
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0-nullsafety.3 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

I am using  **firebase_messaging: ^7.0.3** and not tried with **firebase_messaging: ^8.0.0-dev.11**.
The below function isn't calling when the app is in the foreground but it's calling when the app is in the background

```
 void firebaseCloudMessagingListeners() {
   _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
       print(message);
        showNotification(message);
    
      },
      onResume: (Map<String, dynamic> message) async {
          print("called");
      },
      onLaunch: (Map<String, dynamic> message) async {
          print("called");
      },
    );
      }

```

**Comment by Salakar** [comment]
Please make sure you've followed the documentation here: https://firebase.flutter.dev/docs/messaging/notifications#foreground-notifications

This is confirmed working in the example app for `firebase_messaging`

**Comment by dsourav** [comment]
> Please make sure you've followed the documentation here: https://firebase.flutter.dev/docs/messaging/notifications#foreground-notifications
> 
> This is confirmed working in the example app for `firebase_messaging`

The example app is using  firebase_messaging: ^8.0.0-dev.11 version if I am not wrong. But I am using a different version.

**Comment by markusaksli-nc** [comment]
The new example app is available at https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib

Would you consider updating to the latest version of the package? It is a lot more stable and there have been major improvements. The version you are using will be replaced soon. See https://firebase.flutter.dev/docs/migration/#messaging.

**Comment by dsourav** [comment]
> The new example app is available at https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
> 
> Would you consider updating to the latest version of the package? It is a lot more stable and there have been major improvements. The version you are using will be replaced soon. See https://firebase.flutter.dev/docs/migration/#messaging.

I got it. Thanks a lot...
