### ISSUE TITLE
Firestore plugin compilation fails because of missing header files

### ISSUE THREAD

**Issue by sma** [FirebaseExtended/flutterfire#4628]
## Bug report

I cannot compile macOS application using `cloud_firestore` 0.15.0 and latest master.

```
ld: warning: dylib (/Users/sma/Work/tellorium_poc/build/macos/Build/Products/Release/BoringSSL-GRPC/openssl_grpc.framework/openssl_grpc) was built for newer macOS version (10.12) than being linked (10.9)
/Users/sma/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.15.0/macos/Classes/FLTFirebaseFirestorePlugin.m:8:9: fatal error: 'Private/FLTDocumentSnapshotStreamHandler.h' file not found
#import "Private/FLTDocumentSnapshotStreamHandler.h"                    
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    
1 error generated.                                                      
note: Using new build system                                            
note: Building targets in parallel                                      
note: Planning build                                                    
note: Constructing build description                                    
** BUILD FAILED **          
```

I checked the folder and the header file is indeed missing. 

The previous version 0.14.4 did work.

### Steps to reproduce

1. my flutter version:

        [✓] Flutter (Channel master, 1.26.0-2.0.pre.288, on macOS 11.1 20C69 darwin-x64, locale de-DE)
        [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
        [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
        [✓] Chrome - develop for the web
        [✓] Android Studio (version 4.0)
        [✓] VS Code (version 1.52.1)
        [✓] Connected device (2 available)

2. my `pubspec.yaml` includes:

        dependencies:
          cloud_firestore: ^0.15.0
          firebase_core: ^0.6.0

3. run `flutter build macos`

### Expected behavior

It should successfully compile.

### Additional info

contents of `Private` folder:

```
-rw-r--r--  1 sma  staff   401 13 Jul  2020 FLTFirebaseFirestoreReader.h
-rw-r--r--  1 sma  staff  1856 13 Jul  2020 FLTFirebaseFirestoreUtils.h
-rw-r--r--  1 sma  staff   396 13 Jul  2020 FLTFirebaseFirestoreWriter.h
```
headers included in `FLTFirebaseFirestorePlugin.m`:

```
#import "Private/FLTDocumentSnapshotStreamHandler.h"
#import "Private/FLTFirebaseFirestoreUtils.h"
#import "Private/FLTQuerySnapshotStreamHandler.h"
#import "Private/FLTSnapshotsInSyncStreamHandler.h"
#import "Private/FLTTransactionStreamHandler.h"
```

It looks like the above file is not the only one that is missing.

**Comment by ened** [comment]
@sma  Please run "pod install" in the `ios` folder & try again.

**Comment by sma** [comment]
My project has only a `macos` folder. I have Cocoapods 1.10.1 installed. I ran `pod install` in `macos` but this changes nothing. Running `flutter build` automatically runs `pod install`, I think. 

Here is the relevant portion of the `Podfile.lock` file that changed from since I used the previous version:

```
- cloud_firestore (0.15.0):
    - Firebase/CoreOnly (~> 7.3.0)
    - Firebase/Firestore (~> 7.3.0)
    - firebase_core
    - FlutterMacOS
  - Firebase/CoreOnly (7.3.0):
    - FirebaseCore (= 7.3.0)
  - Firebase/Firestore (7.3.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 7.3.0)
  - firebase_core (0.6.0):
    - Firebase/CoreOnly (~> 7.3.0)
    - FlutterMacOS
  - FirebaseCore (7.3.0):
    - FirebaseCoreDiagnostics (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.3.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30906.0)
  - FirebaseFirestore (7.3.0):
    - abseil/algorithm (= 0.20200225.0)
    - abseil/base (= 0.20200225.0)
    - abseil/memory (= 0.20200225.0)
    - abseil/meta (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/time (= 0.20200225.0)
    - abseil/types (= 0.20200225.0)
    - FirebaseCore (~> 7.0)
    - "gRPC-C++ (~> 1.28.0)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 2.30906.0)
  - FlutterMacOS (1.0.0)
  - GoogleDataTransport (8.1.0):
    - nanopb (~> 2.30906.0)
  - GoogleUtilities/Environment (7.1.1):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.1.1):
    - GoogleUtilities/Environment
```

I still think that the this folder `https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/macos/Classes/Private` is missing the private header files mentioned in my previous posting. Just compare it with `https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/ios/Classes/Private` which contains more files. Furthermore, the missing files where added 4 days ago I my guess is, you forget to commit them for the macos folder.

**Comment by ened** [comment]
@sma yes that makes sense. I was relying on the CI to warn me. Will issue a PR asap. Thank you for reporting. 

@Salakar FYI

**Comment by Salakar** [comment]
> @sma yes that makes sense. I was relying on the CI to warn me. Will issue a PR asap. Thank you for reporting. 
> 
> @Salakar FYI

Oh, I missed this as well, just needs relative symlinks creating in the macos folder for the missing files `ln -s`

**Comment by Salakar** [comment]
PR is up, with CI changes that should pick this up as well now in future 🙈 

Waiting on CI and if all good then will do a release.

**Comment by Salakar** [comment]
FYI: CI being broken has highlighted a couple of other issues, so the version to fix this is gonna have to be a major version as the new Firebase iOS SDK also has a new minimum deployment target for osx.
