### ISSUE TITLE
🐛 [firebase_crashlytics] Cannot import

### ISSUE THREAD

**Issue by remoteshell** [FirebaseExtended/flutterfire#4630]
## Bug report

**Describe the bug**
flutter pub get
Cannot import the package

import 'package:firebase_crashlytics/firebase_crashlytics.dart';
does not exist

### Steps to reproduce

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^0.3.0
  firebase_core: "0.6.0"
  firebase_storage: "^6.0.0"
  firebase_analytics: ^7.0.0
  firebase_auth: ^0.19.0+1
  cloud_firestore: ^0.15.0

### Expected behavior

expected to be able to import package

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by remoteshell** [comment]
rsherbel@Richards-MBP iPhotoWallet % flutter pub deps -- --style=compact
Dart SDK 2.10.4
Flutter SDK 1.22.5
iPhotoWallet 1.0.0+1

dependencies:
- cloud_firestore 0.15.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.0
- firebase_analytics 7.0.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.19.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.6.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.3.0 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_storage 6.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 3.0.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 3.0.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+5 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+2 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.5 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_platform_interface 1.0.3 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+2 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- pedantic 1.9.2 [meta]
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3

**Comment by markusaksli-nc** [comment]
Hi @remoteshell 
Is this just an analysis error or does it affect actual builds? Are you using Android Studio?
You can try `flutter pub cache repair` and `flutter clean` followed by `flutter pub get`.
Thank you

**Comment by remoteshell** [comment]
Hi Markus,

I am using android studio and it was an analysis error.  Took like 2 hours to figure it out.

Thank you for taking the time to respond.

**Comment by markusaksli-nc** [comment]
In that case, you could try File > Invalidate Caches / Restart > Invalidate and Restart

This has fixed the analysis issue for me before.

**Comment by remoteshell** [comment]
I agree close it
