### ISSUE TITLE
🐛 [firebase_crashlytics][firebase_dynamic_links] pub get failed

### ISSUE THREAD

**Issue by wangxingxing123654** [FirebaseExtended/flutterfire#4632]
## Bug report

**Describe the bug**
[flutter_use_redux] flutter pub get
Running "flutter pub get" in flutter_use_redux...               
Because no versions of firebase_dynamic_links match >0.6.3 <0.7.0 and firebase_dynamic_links 0.6.3 depends on firebase_core ^0.5.3, firebase_dynamic_links ^0.6.3 requires firebase_core ^0.5.3.

And because firebase_crashlytics >=0.3.0 depends on firebase_core ^0.6.0, firebase_dynamic_links ^0.6.3 is incompatible with firebase_crashlytics >=0.3.0.

So, because flutter_use_redux depends on both firebase_crashlytics ^0.3.0 and firebase_dynamic_links ^0.6.3, version solving failed.
pub get failed (1; So, because flutter_use_redux depends on both firebase_crashlytics ^0.3.0 and firebase_dynamic_links ^0.6.3, version solving failed.)
exit code

**Comment by markusaksli-nc** [comment]
Hi @wangxingxing123654 
The update to the latest FlutterFire packages has to be applied to all of them since it was due to an update to core.

> * BREAKING FEAT: forward port to firebase-ios-sdk v7.3.0.
>   * Due to this SDK upgrade, iOS 10 is now the minimum supported version by FlutterFire. Please update your build target version.

This means you need to update all of the FlutterFire packages to the latest.

Try updating to
```yaml
firebase_core: ^0.6.0
firebase_crashlytics: ^0.3.0
firebase_dynamic_links: ^0.7.0
```

Does this fix the issue for you?
Thank you
