### ISSUE TITLE
Add WidgetsFlutterBinding.ensureInitialized(); in the Futurebuilder Example

### ISSUE THREAD

**Issue by nathvarun** [FirebaseExtended/flutterfire#4645]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

Error in console when initialising firebase: 
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized() first.

How to reproduce the error: 
Use the Future builder code snippet from the official docs : https://firebase.flutter.dev/docs/overview/#initializing-flutterfire

Fix : 
In the documentation where it uses the Futurebuilder example to initialise firebase, the app throws an error. 
In order to make the example work you need to add   WidgetsFlutterBinding.ensureInitialized(); in the main method of the App.

```

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

void main() {
 WidgetsFlutterBinding.ensureInitialized(); // need to add this here. 
  runApp(App());
}

class App extends StatelessWidget {
  // Create the initialization Future outside of build:
  final Future<FirebaseApp> _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // Initialize FlutterFire:
      future: _initialization,
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          return SomethingWentWrong();
        }

        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return MyAwesomeApp();
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return Loading();
      },
    );
  }
}

```

**Comment by dackers86** [comment]
Current PR at https://github.com/FirebaseExtended/flutterfire/pull/3489
