### ISSUE TITLE
🐛 [firebase_ml_vision] Execution failed for task ':app:checkDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by zee-kay1** [FirebaseExtended/flutterfire#4647]
## Bug report

I am trying to run my application on a device but I keep getting this error, kindly help me with this error.
Also I am using firebase ml kit, if this helps too.

### Expected behavior

I am trying to run a text recognition algorithm using firebase ml kit but it keeps giving me this error. 

---

## Additional context

First i tested the app on emulator it was installed correctly, but when i tried to run it on my android device it kept giving me this error and now it is also giving same error on emulator too.

---

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```
PASTE OUTPUT INSIDE HERE
```

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
Duplicate class com.google.android.gms.internal.vision.zze found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzf found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzg found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzh found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzi found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzv found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzw found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)

 Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 3m 55s
Exception: Gradle task assembleDebug failed with exit code 1

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

dependencies:
- camera 0.6.4+5 [flutter camera_platform_interface pedantic]
- cupertino_icons 0.1.3
- firebase_ml_vision 0.9.10 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- intl 0.16.1 [path]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel st
ring_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- camera_platform_interface 1.5.0 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- cross_file 0.1.0 [flutter http meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]

```

**Comment by dackers86** [comment]
Hi @zee-kay1 

Please follow the instructions at https://firebase.flutter.dev/docs/installation/android to get your application ready.

It appears you need to configure Android according to the `Doctor` report

**Comment by zee-kay1** [comment]
how am i supposed to configure android ?
and i have followed all the instruction needed for firebase installation.

**Comment by markusaksli-nc** [comment]
Hi @zee-kay1 
You need to run `flutter doctor --android-licenses` and accept the android licenses.
Could you try upgrading to the latest `firebase_ml_vision: ^0.10.0`?
Thank you

**Comment by zee-kay1** [comment]
Hi @markusaksli-nc 
i upgraded to firebase_ml_vision ^0.10.0 and recompiled my app it gave me the error and asked me to add firebase_core in your dependencies, after adding this dependency i recompiled the app and now it is giving me this error:
![ee](https://user-images.githubusercontent.com/77362530/105162643-b8b18200-5b34-11eb-8ff3-f3dc6f9dc9fa.png)

**Comment by markusaksli-nc** [comment]
That is just an adb error. Try manually uninstalling the app on the phone, make sure storage is not full.

You can also run `flutter clean` in the project.

**Comment by zee-kay1** [comment]
It worked, I ran flutter clean first and then turned off the "Verify apps via USB" in developer options and then my app was installed successfully. Thanks much @markusaksli-nc
