### ISSUE TITLE
🐛 [firebase-auth] try catch not working on Flutter Firebase Auth Exception

### ISSUE THREAD

**Issue by fame1302** [FirebaseExtended/flutterfire#4648]
## Bug report

**Try Catch not working on Flutter Firebase Auth Exception**
Try catch not working when handle **FirebaseAuthException**, and always get **Uncaught Exception** on code editor (I use VSCode, and also try on InteliJ IDEA), and i need to resume the debugger again and again.

### Sample Code :

```
class AuthServices {
  final FirebaseAuth _auth;
  AuthServices(this._auth);

  Future<String> signInWithEmail({String mail, String pass}) async {
      try {
        await _auth.signInWithEmailAndPassword(email: mail, password: pass);
        return "Login Success";
      } on FirebaseAuthException catch (e) {
        return e.message;
      }
  }

}
```
when i call function **signInWithEmail** i always get Uncaught Exeption before the **on catch** event.

**This Example of Exeption :**
```
Exception has occurred.
PlatformException (PlatformException(firebase_auth, com.google.firebase.auth.FirebaseAuthInvalidUserException: There is no user record corresponding to this identifier. The user may have been deleted., {code: user-not-found, additionalData: {}, message: There is no user record corresponding to this identifier. The user may have been deleted.}))
``` 

in that case, instead i get the **e.message** on debug console, i always get the uncaught exception and make me to resume the Debugger again and again.

### Flutter doctor
This is my Flutter doctor result :

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.685], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!
```

</details>

---

**Comment by atnegrete** [comment]
Seems there's been a few reports of this issue... this one has some pretty good content #https://github.com/flutter/flutter/issues/20223

Basically, as far as I can tell, the easiest fix for you for now would be to not filter out the exceptions by the FirebaseAuthException, just catch PlatformException (i'd just catch all honestly), and then use the error codes to figure out what went wrong.

Hopefully someone fixes this at some point...or maybe it already has been in a newer version..

**Comment by markusaksli-nc** [comment]
Hi @fame1302 
Could you provide your `flutter pub deps -- --style=compact`?
Thank you
