### ISSUE TITLE
[firebase_messaging] pub get fails on v7.0.3 because it depends on an older firebase_core version

### ISSUE THREAD

**Issue by erolasan** [FirebaseExtended/flutterfire#4650]
Hi please fix the dependency for firebase_messaging on firebase_core, I am currently getting this when I do pub get the newest version: 
```
Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.
So, because 'xxx' depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed
```

in my pubspec i have this :
```
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0
  firebase_messaging: ^7.0.3
```

**Comment by ThrowJojo** [comment]
I can confirm this too, I'm seeing the same output after trying to upgrade:

```
Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.
So, because addiction_counter depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed.
pub get failed (1; So, because addiction_counter depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed.)
```

**Comment by Akorius** [comment]
I have the same problem

>   firebase_core: ^0.7.0
>   firebase_crashlytics: ^0.4.0
>   firebase_performance: ^0.5.0+1
>   firebase_messaging: ^7.0.3
>   firebase_analytics: ^7.0.1

  
  Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.
So, because x-x-x depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed.

**Comment by lvlrSajjad** [comment]
@erolasan I used this version:   firebase_messaging: 8.0.0-dev.14 and it worked for me.
But now I have another problem, pod install doesn't work:
```
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    Firebase/MLVisionFaceModel was resolved to 5.0.0, which depends on
      Firebase/CoreOnly (= 5.0.0)

    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
      Firebase/CoreOnly (= 7.3.0)

CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
      Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCore (= 7.3.0)

    firebase_storage (from `.symlinks/plugins/firebase_storage/ios`) was resolved to 7.0.0, which depends on
      Firebase/Storage (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseStorage (~> 7.3.0) was resolved to 7.3.0, which depends on
          FirebaseCore (~> 7.0)

CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 0.4.0, which depends on
      Firebase/Crashlytics (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCrashlytics (~> 7.3.0) was resolved to 7.3.0, which depends on
          GoogleDataTransport (~> 8.0)

    firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.5.0-1, which depends on
      Firebase/Performance (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebasePerformance (~> 7.3.0) was resolved to 7.3.0, which depends on
          GoogleDataTransport (~> 8.1)

CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
      Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCore (= 7.3.0) was resolved to 7.3.0, which depends on
          FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.4.0, which depends on
            nanopb (~> 2.30907.0)

    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 0.4.0, which depends on
      Firebase/Crashlytics (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCrashlytics (~> 7.3.0) was resolved to 7.3.0, which depends on
          nanopb (~> 2.30906.0)

```

**Comment by geecat** [comment]
Same for me

Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.

You upgraded all packages but forgot to update firebase_messaging.
Please do it,  otherwise there is no point in this upgrade.

**Comment by Zeehshan** [comment]
> Hi please fix the dependency for firebase_messaging on firebase_core, I am currently getting this when I do pub get the newest version:
> 
> ```
> Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.
> So, because 'xxx' depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed
> ```
> 
> in my pubspec i have this :
> 
> ```
>   cloud_firestore: ^0.16.0
>   firebase_auth: ^0.20.0
>   firebase_core: ^0.7.0
>   firebase_analytics: ^7.0.1
>   firebase_crashlytics: ^0.4.0
>   firebase_messaging: ^7.0.3
> ``
Same for me

**Comment by RicardoRB** [comment]
Same here

**Comment by tranvietha2809** [comment]
Also having this problem.

**Comment by kamlesh9070** [comment]
Also having this problem.

**Comment by mohammadsm220** [comment]
this will help 
https://firebase.flutter.dev/docs/migration/

**Comment by erolasan** [comment]
@mohammadsm220 it did help thanks! Closing the issue

**Comment by bmdesai0309** [comment]
I have this error

Because cloud_firestore >=0.16.0 depends on firebase_core ^0.7.0 and flash_chat depends on firebase_core ^0.6.0, cloud_firestore >=0.16.0 is forbidden.
So, because flash_chat depends on cloud_firestore ^0.16.0, version solving failed.
pub get failed (1; So, because flash_chat depends on cloud_firestore ^0.16.0, version solving failed.)

**Comment by muhammed-amein** [comment]
i have the same error

**Comment by shredding** [comment]
So the solution is to install a dev branch (^8.0.0-dev.14) for firebase_messaging? Isn't that a really bad idea?

**Comment by niypoo** [comment]
> So the solution is to install a dev branch (^8.0.0-dev.14) for firebase_messaging? Isn't that a really bad idea?

indeed it's very bad for who seeking to stability

**Comment by hare989** [comment]
> So the solution is to install a dev branch (^8.0.0-dev.14) for firebase_messaging? Isn't that a really bad idea?

For me, it fails even if I install ^8.0.0-dev.14. 

Error message:
Because firebase_messaging >=8.0.0-dev.13 depends on firebase_core_platform_interface ^3.0.1 and firebase_crashlytics >=0.5.0-1.0.nullsafety.1 depends on firebase_core_platform_interface >=4.0.0-1.0.nullsafety.0 <4.0.0-2.0.nullsafety.0, firebase_messaging >=8.0.0-dev.13 is incompatible with firebase_crashlytics >=0.5.0-1.0.nullsafety.1.

> firebase_core: ^0.8.0-nullsafety.1
  firebase_crashlytics: ^0.5.0-1.0.nullsafety.1
  firebase_messaging: ^8.0.0-dev.14

This versions setup is from https://firebase.flutter.dev/docs/migration/

**Comment by Epikur86** [comment]
When I remove the versions  behind messaging  and core, it works :

  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0
  cloud_functions:  ^0.9.0
  firebase_messaging:
  firebase_core:
  firebase_storage: ^7.0.0

**Comment by israellias** [comment]
Same problem

**Comment by appsailor** [comment]
Not working for me. I'm getting the following error.

Because firebase_analytics 7.0.1 depends on firebase_core ^0.7.0 and no versions of firebase_analytics match >7.0.1 <8.0.0, firebase_analytics ^7.0.1 requires firebase_core ^0.7.0.
So, because scorebud depends on both firebase_core ^0.8.0-nullsafety.1 and firebase_analytics ^7.0.1, version solving failed.
pub get failed (1; So, because scorebud depends on both firebase_core ^0.8.0-nullsafety.1 and firebase_analytics ^7.0.1, version solving failed.)

My pubspec.yml has the following firebase section copied from the migration guide:
 environment:
  sdk: ">=2.12.0-0 <3.0.0"

  firebase_core: "^0.8.0-nullsafety.1"
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: "^0.21.0-nullsafety.0"
  firebase_crashlytics: "^0.5.0-1.0.nullsafety.1"
  cloud_firestore: "^0.16.0"
  firebase_storage: "^7.0.0"
  firebase_messaging: "^8.0.0-dev.14"
  firebase_remote_config: "^0.8.0-dev.0"
  # Updated to work with new core only plugins (no new changes):
  firebase_admob: "^0.11.0+1"
  firebase_analytics: "^7.0.1"

----
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64)
    • Flutter version 1.25.0-8.3.pre at /Volumes/DataDev/flutter/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

**Comment by fabirt** [comment]
Please fix this issue, same error following the [migration guide](https://firebase.flutter.dev/docs/migration).

Dependencies:
```
firebase_core: ^0.8.0-nullsafety.1
firebase_messaging: ^8.0.0-dev.14
```

Error:
```
Because firebase_messaging >=8.0.0-dev.13 depends on firebase_core ^0.7.0 and test depends on firebase_core ^0.8.0-nullsafety.1, firebase_messaging >=8.0.0-dev.13 is forbidden.
```

**Comment by glenfordwilliams** [comment]
same error

```
Because firebase_admob >=0.11.0+1 depends on firebase_core ^0.7.0 and ... depends on firebase_core ^0.8.0-nullsafety.1, firebase_admob >=0.11.0+1 is forbidden.
```

```
 cloud_firestore:	^0.16.0
  cloud_functions:	^0.9.1-nullsafety.1
  firebase_auth:	^0.21.0-nullsafety.0
  firebase_core:	^0.8.0-nullsafety.1
  firebase_crashlytics:	^0.5.0-1.0.nullsafety.1
  firebase_storage:	^7.0.0
  firebase_messaging:	^8.0.0-dev.14
  firebase_remote_config:	^0.8.0-dev.0
  firebase_admob: ^0.11.0+1
```

**Comment by CasperPas** [comment]
copy-paste from the guide and it's not working, keeps saying errors that they're not compatible with each others. Really annoying!

**Comment by glenfordwilliams** [comment]
Opened #4885 because documentation doesn't work

**Comment by hsnbsst** [comment]
the same problem continues with me

```
  firebase_core: ^0.8.0-nullsafety.1
  firebase_auth: ^0.21.0-nullsafety.0
  firebase_crashlytics: ^0.5.0-1.0.nullsafety.1
  firebase_messaging: ^8.0.0-dev.14
  firebase_database: ^6.0.0
  firebase_analytics: ^7.0.1
```

```
Because firebase_analytics >=7.0.1 depends on firebase_core ^0.7.0 and mafya depends on firebase_core ^0.8.0-nullsafety.1, firebase_analytics >=7.0.1 is forbidden.

So, because mafya depends on firebase_analytics ^7.0.1, version solving failed.
pub get failed (1; So, because mafya depends on firebase_analytics ^7.0.1, version solving failed.)
exit code 1

```

**Comment by edgarfroes** [comment]
Why is this closed if the problem persists?

Having the same problem with copy and paste from the migration documentation.

**Comment by edgarfroes** [comment]
Error persists on a brand new flutter project. Used these dependencies:

```
 firebase_auth: "^0.20.0+1"
 firebase_crashlytics: "^0.4.0+1"
 cloud_firestore: "^0.16.0"
 cloud_functions: "^0.9.0"
 firebase_storage: "^7.0.0"
 firebase_messaging: "^7.0.3"
```

Error message:

```
Running "flutter pub get" in flutter...                         
Because firebase_messaging >=7.0.3 <8.0.0-dev.7 depends on firebase_core ^0.5.0+1 and firebase_storage >=7.0.0 depends on firebase_core ^0.7.0, firebase_messaging >=7.0.3 <8.0.0-dev.7 is incompatible with firebase_storage >=7.0.0.

So, because sandbox depends on both firebase_storage ^7.0.0 and firebase_messaging ^7.0.3, version solving failed.
pub get failed (1; So, because sandbox depends on both firebase_storage ^7.0.0 and firebase_messaging ^7.0.3, version solving failed.)
```

**Comment by ahmedwadod** [comment]
I solved it by changing `firebase_messaging` version to `^8.0.0-dev.14`

**Comment by edgarfroes** [comment]
> I solved it by changing `firebase_messaging` version to `^8.0.0-dev.14`

Thanks, it worked, but it not a fix for the problem, you know what I mean? I could have stability issues. Will test it though.

**Comment by rednikisfun** [comment]
Can anyone reopen the issue, cause it still persists

**Comment by r3ddev1l** [comment]
> @mohammadsm220 it did help thanks! Closing the issue

Hello @erolasan , the issue still persists so could you please reopen the issue? I'd rather not open another issue for the same problem.

**Comment by roderikpeeters** [comment]
Here also having issues...

**Comment by SpiegelSoft** [comment]
Same issue here

**Comment by SimeonZV** [comment]
> this will help
> https://firebase.flutter.dev/docs/migration/

@mohammadsm220 @erolasan Could you please share what was helping you to resolve this issue in the migration guide? I still experience this although I believe I followed the migration guide. Thanks!

**Comment by melvinotieno** [comment]
Also having this issue. What is the way forward please as I have a deadline to complete a project which currently heavily relies on firebase.

**Comment by edgarfroes** [comment]
> Also having this issue. What is the way forward please as I have a deadline to complete a project which currently heavily relies on firebase.

@melvinotieno the only way to go now would be to set `firebase_messaging` version to `^8.0.0-dev.14`

**Comment by shengguow** [comment]
I changed firebase_auth version to ^0.18.4+1, works for me.

**Comment by roderikpeeters** [comment]
> I changed firebase_auth version to ^0.18.4+1, works for me.

Can you give a reference on what other versions you used in your pubspec?

**Comment by shengguow** [comment]
> > I changed firebase_auth version to ^0.18.4+1, works for me.
> 
> Can you give a reference on what other versions you used in your pubspec?
Sure.

firebase_core: ^0.5.0+1
firebase_auth: ^0.18.4+1
firebase_messaging: ^7.0.3

**Comment by omarreess** [comment]
Same issue here , But 
when i removed version it worked without error
` firebase_messaging:`

**Comment by nialljvs** [comment]
Following - please reopen until fix has landed in stable.

**Comment by NecoHorne** [comment]
following, same issue migration docs not working, would prefer to stay on stable branch and not beta.

**Comment by DogeeeXD** [comment]
Having the same problem:
Because firebase_messaging >=7.0.3 <8.0.0-dev.7 depends on firebase_core ^0.5.0+1 and pewpewchat depends on firebase_core ^0.7.0, firebase_messaging >=7.0.3 <8.0.0-dev.7 is forbidden.

Current workaround: Leave firebase_messaging version to blank.
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_messaging:
  
Following for fix.

**Comment by VisalGGEZ** [comment]
> Same issue here , But
> when i removed version it worked without error
> ` firebase_messaging:`

for Me Android work fines but iOS error

**Comment by FirdousNath** [comment]
> > Same issue here , But
> > when i removed version it worked without error
> > ` firebase_messaging:`
> 
> for Me Android work fines but iOS error

for me also [getting this error on iOS](https://github.com/FirebaseExtended/flutterfire/issues/4994)

**Comment by lcsvcn** [comment]
I am having same issue, any prevision to fix this (real fix, not adding a dev dependence) ? I think they need to release a stable version 8.0.0, but don't know when it will be launched...

**Comment by Tryneeth** [comment]
The matching versions are:

```
firebase_core: ^0.7.0
firebase_messaging: 6.0.16
```

This works for me... 👍👌

**Comment by ahmedwadod** [comment]
> > I solved it by changing `firebase_messaging` version to `^8.0.0-dev.14`
> 
> Thanks, it worked, but that's not a fix for the problem, if you know what I mean. I could have stability issues. Will test it though.

Indeed it's an issue, but Flutterfire is still an ongoing project and we will have to deal with those problems for a while.
I have tested this solution and it's working well so far.

**Comment by tijanirf** [comment]
Anyone already tried using `firebase_messaging ^8.0.0-dev.14` on production? Especially on the iOS side. Any response would be appreciated, thanks in advance.

**Comment by AbirAhsan** [comment]
Same issue here

**Comment by fauzyahmad** [comment]
Yes I have the same issue here. Really hope that version ^8.0.0 stable can be released soon

**Comment by muhammed-amein** [comment]
hey @fauzyahmad can you look at this
https://t.co/T3yVelwSff?amp=1

**Comment by believeInJha** [comment]
Can anyone reopen the issue, cause it still persists

**Comment by kendall-lu** [comment]
Issue still persists

**Comment by emme1009** [comment]
same issue, I´m worried to try a dev-dependency on production.

**Comment by edgarfroes** [comment]
@mohammadsm220 can you reopen this for us?
