### ISSUE TITLE
🐛 [firebase_messaging] registerBackgroundMessageHandler null

### ISSUE THREAD

**Issue by sante85** [FirebaseExtended/flutterfire#4652]
## Bug report

**Describe the bug**
E/flutter (11335): Receiver: null
E/flutter (11335): Tried calling: toRawHandle()
E/flutter (11335): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (11335): #1      MethodChannelFirebaseMessaging.registerBackgroundMessageHandler (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:181:42)
E/flutter (11335): #2      FirebaseMessagingPlatform.onBackgroundMessage= (package:firebase_messaging_platform_interface/src/platform_interface/platform_interface_messaging.dart:107:14)
E/flutter (11335): #3      FirebaseMessaging.onBackgroundMessage (package:firebase_messaging/src/messaging.dart:103:31)

### Steps to reproduce
i have set 
 FirebaseMessaging.onBackgroundMessage(
            (message) => _backgroundMessageHandler(message));

static Future<dynamic> _backgroundMessageHandler(RemoteMessage event) {
    print(event);
  }

### Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.17.5, on Microsoft Windows [Versione 10.0.19042.685], locale it-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
X Android license status unknown.
Try re-installing or updating your Android SDK Manager.
See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[!] Android Studio (not installed)
[√] Connected device (1 available)

### Flutter dependencies
firebase_core: 0.5.3
  firebase_messaging: 8.0.0-dev.11
  flutter_local_notifications: 3.0.3

**Comment by Salakar** [comment]
> ```
> FirebaseMessaging.onBackgroundMessage(
> (message) => _backgroundMessageHandler(message));
> 
> static Future _backgroundMessageHandler(RemoteMessage event) {
> print(event);
> }
> ```
> 

This is incorrect; you're making an inline anonymous function and what also appears to be a class method `_backgroundMessageHandler`.

As per the [docs](https://firebase.flutter.dev/docs/messaging/usage#background-messages):

 - It must not be an anonymous function.
 - It must be a top-level function (e.g. not a class method which requires initialization).

Here's a more detailed example;

```dart
// your dart/package imports here
// your dart/package imports here
// your dart/package imports here

// A top level function - notice it's not nested inside any class or other function body.
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print("Handling a background message: ${message.messageId}");
}

// Some time later e.g. in your main() function;
void main() {
  // Notice i'm passing `_firebaseMessagingBackgroundHandler` directly, and not wrapping it in another
  // function like in your example 
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(MyApp());
}
