### ISSUE TITLE
[firebase_crashlytics] MissingPluginException(No implementation found for method Crashlytics#didCrashOnPreviousExecution on channel plugins.flutter.io/firebase_crashlytics)

### ISSUE THREAD

**Issue by avioli** [FirebaseExtended/flutterfire#4658]
https://github.com/FirebaseExtended/flutterfire/blob/7f9f9573aa403c234e71b99143a3d89534042355/packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m#L93

Should be:

```obj-c
  } else if ([@"Crashlytics#didCrashOnPreviousExecution" isEqualToString:call.method]) {
```

The `macos` implementation file suffers from the same issue.

**Comment by Salakar** [comment]
I will get this fixed today with additional tests added, thanks for flagging
