### ISSUE TITLE
🐛 [Firebase_messaging] web package has conflits with dart:html

### ISSUE THREAD

**Issue by jamesblasco** [FirebaseExtended/flutterfire#4663]
## Bug report

**Describe the bug**
The firebase messaging web package can't compile because has confligts with the html package

```zh
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging_web-0.1.0-dev.5/lib/src/interop/notification_interop.dart:14:16: Error: JS interop class 'NotificationJsImpl' conflicts with natively supported class 'Notification' in 'dart:html'.
abstract class NotificationJsImpl {
               ^
Failed to compile application.
```

**Comment by jdeltoft** [comment]
this just came out of the blue for me.  I didn't upgrade anything I know of.  I did recently include intl in my pubspec.yaml, for working with Date Strings but I know it built after that.  And anyway I removed it and my build still fails.  Here is my flutter doctor.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on Mac OS X 10.14.6 18G7016 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
    ! Device emulator-5566 is offline.

• No issues found!
```

I did a 'flutter clean' and then my crash says:

```
Target dart2js failed: Exception: ../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-0.1.0-dev.5/lib/src/interop/notification_interop.dart:14:16:
Error: JS interop class 'NotificationJsImpl' conflicts with natively supported class 'Notification' in 'dart:html'.
abstract class NotificationJsImpl {
               ^
Error: Compilation failed.

```

**Comment by Vinzent03** [comment]
I have the same problem. In my case it happened after an update to the latest flutter dev version. Every package is up to date.
```
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-0.1.0-dev.5/lib/src/interop/notification_interop.dart:14:16: Error: JS interop class 'NotificationJsImpl' conflicts with
natively supported class 'Notification' in 'dart:html'.
abstract class NotificationJsImpl {
```
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-8.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (2 available)

• No issues found!
```

**Comment by Papajik** [comment]
Same here also on dev channel.  For now i am going back to previous flutter version by running  **flutter downgrade** command.

**Comment by creativecreatorormaybenot** [comment]
Adding to @Vinzent03's info:

```
Flutter 1.26.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision b9d06fffb2 (10 days ago) • 2021-01-07 18:36:48 -0800
Engine • revision 42a8d4c681
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)
```

```
firebase_messaging_web-0.1.0-dev.3
```

**Comment by creativecreatorormaybenot** [comment]
@Salakar If the "no-template" thing is an issue, I am glad to provide reproducible steps for you.

Flutter web consistently does not compile on web for me.

**Comment by jdeltoft** [comment]
I went to flutter beta channel, and web now builds fine for me.  Guess dev is a bit too bleeding edge for me still.  Thankful that flutter channel change wasn't too hard

**Comment by Ehesp** [comment]
Hmm just tried on latest `dev` channel, building the messaging example app with no issues:

![image](https://user-images.githubusercontent.com/842078/108983490-d4a1c980-7686-11eb-836f-382cb6fd8c7d.png)

Am I missing something? :)

**Comment by russellwheatley** [comment]
Also no problem building web on `dev` & `beta` channel.

![Screenshot 2021-03-01 at 11 45 56](https://user-images.githubusercontent.com/16018629/109503254-effb4300-7a91-11eb-9252-c846bce429d4.png)

Using latest dependencies:

```yaml
  firebase_core: "^1.0.0"
  firebase_messaging: "^9.0.0"
```

If someone could provide a repro of this issue, I'm happy to debug.

**Comment by russellwheatley** [comment]
As a side, I'd also `flutter upgrade` your `dev` channel as this might explain the discrepancy.

**Comment by russellwheatley** [comment]
I'm going to assume this isn't an issue anymore as it has gone quiet. Will reopen if it is still a problem.
