### ISSUE TITLE
AndroidX incompatibilitiese 

### ISSUE THREAD

**Issue by samithe7** [FirebaseExtended/flutterfire#4664]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\samiu\.gradle\caches\transforms-2\files-2.1\a3b8085db30285646632e9aaa0c95070\play-services-ads-lite-19.6.0\AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by bdlukaa** [comment]
Try running `flutter clean` and running the app again

**Comment by samithe7** [comment]
without  admob plugin app  run   but after add admob plugin  show this massage

**Comment by bdlukaa** [comment]
I had the same issue. I just upgraded the project gradle version to `3.5.4`

**Comment by hamzamogni** [comment]
I am experiencing the same issue. Didn't work even after running `flutter clean` .

**Comment by hamzamogni** [comment]
I opened another issue [https://github.com/FirebaseExtended/flutterfire/issues/4669](url) following the issues reporting template.

**Comment by Jay-flow** [comment]
I'm having the same problem. Let me know if anyone knows the solution. 😭
`firebase_admob version: ^0.11.0+1`
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/jay-flow/.gradle/caches/transforms-2/files-2.1/0dc4181583bc0660025808e34a9b6695/play-services-ads-lite-19.6.0/AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.
```

**Comment by Jay-flow** [comment]
> I had the same issue. I just upgraded the project gradle version to `3.5.4`

Thank you. It is work for me :)

**Comment by 2shrestha22** [comment]
> I had the same issue. I just upgraded the project gradle version to `3.5.4`

Yes I did the same.

**Comment by lalitjarwal** [comment]
Update  classpath 'com.android.tools.build:gradle:3.5.0' 
to  classpath 'com.android.tools.build:gradle:3.5.4' in build.gradle

**Comment by abdullah4one** [comment]
I am using classpath 'com.android.tools.build:gradle:4.1.2' and not solved my problem

**Comment by 2shrestha22** [comment]
> I am using classpath 'com.android.tools.build:gradle:4.1.2' and not solved my problem

Use 3.5.4 or 4.0.1
