### ISSUE TITLE
Mention the platform :ios, '9.0' line in ios/Podfile and platform :osx, '10.12' in macos/Podfile in docs relating to minimum iOS and macOS targets

### ISSUE THREAD

**Issue by lumenier1** [FirebaseExtended/flutterfire#4666]
I've updated to latest `firebase_core: ^0.7.0` and `firebase_admob: ^0.11.0+1` but now `flutter run` fails because of cocoapods:

```
Running "flutter pub get" in app...                                 0,5s
 
Launching lib/main.dart on iPhone 11 Pro in debug mode...
 
Running pod install...                                              1,1s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `firebase_admob` from `.symlinks/plugins/firebase_admob/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_statusbarcolor` from `.symlinks/plugins/flutter_statusbarcolor/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "firebase_admob":
      In Podfile:
        firebase_admob (from `.symlinks/plugins/firebase_admob/ios`)

    Specs satisfying the `firebase_admob (from `.symlinks/plugins/firebase_admob/ios`)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro.
```

And my `pubspec.yaml`:

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_admob: ^0.11.0+1
```

The irony that any twitching with pods from this list doesn't help:
https://stackoverflow.com/a/63506237/5246900
https://stackoverflow.com/a/64676861/5246900
https://github.com/FirebaseExtended/flutterfire/issues/3479#issuecomment-690033471
https://github.com/FirebaseExtended/flutterfire/issues/3352#issuecomment-680854071

`flutter clean`
`pod repo update`
`rm ios/Podfile`
`pod repo update`
`pod update`
`pod install`
`flutter run`
... e.t.c.

PLEASE HELP!

**Comment by SirBepy** [comment]
I have the same issue.

**Comment by markusaksli-nc** [comment]
Hi @lumenier1 @SirBepy 
You just need to update the iOS target in Xcode to at least 10.0. This was the reason for the version bump in all the FlutterFire packages.

> * BREAKING FEAT: forward port to firebase-ios-sdk v7.3.0.
>   * Due to this SDK upgrade, iOS 10 is now the minimum supported version by FlutterFire. Please update your build target version.

Firebase admob works just fine on the latest versions.

Let me know if you run into any more issues.
Thank you

**Comment by lumenier1** [comment]
> Hi @lumenier1 @SirBepy
> You just need to update the iOS target in Xcode to at least 10.0. This was the reason for the version bump in all the FlutterFire packages.
> 
> > * BREAKING FEAT: forward port to firebase-ios-sdk v7.3.0.
> >   
> >   * Due to this SDK upgrade, iOS 10 is now the minimum supported version by FlutterFire. Please update your build target version.
> 
> Firebase admob works just fine on the latest versions.
> 
> Let me know if you run into any more issues.
> Thank you

Hi Markus,
Thank you for the answer!
I've just tested `firebase_core: ^0.7.0` and `firebase_admob: ^0.11.0+1` package combination only on the blank new app and it fails out of the box with the same error.
Yes, then I figured out how to fix it by increasing target version, but still some twitching required on the `Podfile` and it takes not less that 15 minutes literally to install pods.

In my case changing this line helped in `ios/Podfile`:
`platform :ios, '12.0'`

**Comment by markusaksli-nc** [comment]
This line is commented out by default when the podfile is generated by commands like `flutter pub upgrade` or `flutter pub get`
```python
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
...
```
But since you figured it out I take it the issue be closed as solved?

**Comment by lumenier1** [comment]
> This line is commented out by default when the podfile is generated by commands like `flutter pub upgrade` or `flutter pub get`
> 
> ```python
> # Uncomment this line to define a global platform for your project
> # platform :ios, '9.0'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> ...
> ```
> 
> But since you figured it out I take it the issue be closed as solved?

Thank you for answer. It would be great to add this note to `firebase_admob` package docs in installation section or readme file.

**Comment by markusaksli-nc** [comment]
This is already mentioned in the docs at https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions and in the changelog so the documentation should be enough.

However a bit about the podfile line could be added just in case.

**Comment by markusaksli-nc** [comment]
I actually meant this should be the issue to track the documentation fix so we should keep it open.

**Comment by lumenier1** [comment]
> I actually meant this should be the issue to track the documentation fix so we should keep it open.

Totally agree with you since additional step is required for proper setup.
Would be great to add this step not only to  https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions
But also to https://pub.dev/packages/firebase_admob/

**Comment by russellwheatley** [comment]
Closing this as `firebase_admob` is now deprecated in favour of  [google_admob_ads](https://pub.dev/packages/google_mobile_ads), and as such, has no documentation on flutterfire docs website.
