### ISSUE TITLE
🐛 [firebase dynamic links ] cannot open app in ios 

### ISSUE THREAD

**Issue by wangxingxing123654** [FirebaseExtended/flutterfire#4670]
firebase_dynamic_links: ^0.7.0

when clicked the dynamic link app ,cannot open the app , it will show a preview page, and didnot open the app

**Comment by wangxingxing123654** [comment]
void initFireBaseDynamicLinks() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;
      Get.log('deeplink $deepLink');
      if (deepLink != null) {
        Future.delayed(Duration(seconds: 1), () {
          Navigator.push(
              Get.context,
              MaterialPageRoute(
                  builder: (context) => WebViewPage(
                      url: "${ImageConfig.siteHostName}/appBlankPage",
                      redirectUrl: deepLink.toString())));
        });
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
    });
      final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;
     Get.log('deeplink2 $deepLink');
  }

**Comment by wangxingxing123654** [comment]
`FirebaseDynamicLinks.instance.onLink `cannot listen , when click the email

**Comment by markusaksli-nc** [comment]
Hi @wangxingxing123654 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by wangxingxing123654** [comment]
➜  flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.1 20C69, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/chicv/Downloads/flutter
    • Framework revision 84f3d28555 (3 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/chicv/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/chicv/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by wangxingxing123654** [comment]
Dart SDK 2.10.2
Flutter SDK 1.22.2


dependencies:
- align_positioned 1.2.8 [matrix4_transform flutter]
- appsflyer_sdk 6.0.5 [flutter]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.1 [flutter]
- circular_profile_avatar 1.0.7 [flutter cached_network_image]
- connectivity 2.0.0 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cookie_jar 1.0.1
- cupertino_icons 0.1.3
- dio 3.0.10 [http_parser path]
- dio_cookie_manager 1.0.0 [cookie_jar dio]
- event_bus 1.1.1
- firebase_crashlytics 0.3.0 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.7.0 [flutter firebase_core]
- flustars 0.3.3 [flutter common_utils sp_util synchronized path_provider]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_app_upgrade 1.1.0 [flutter dio]
- flutter_branch_sdk 1.3.0 [flutter]
- flutter_countdown_timer 1.3.0 [flutter]
- flutter_dotenv 2.1.0 [flutter meta]
- flutter_form_builder 3.14.0 [flutter flutter_typeahead intl flutter_chips_input datetime_picker_formfield flutter_colorpicker signature validators date_range_picker flutter_touch_spin image_picker image_picker_for_web rating_bar country_pickers phone_number]
- flutter_html 1.0.0 [html csslib css_colors video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_inappwebview 5.0.0 [flutter uuid mime]
- flutter_redux 0.6.0 [meta redux flutter]
- flutter_staggered_grid_view 0.3.2 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- flutter_swiper 1.1.6 [flutter transformer_page_view flutter_page_indicator]
- flutter_widget_from_html 0.5.1+3 [cached_network_image chewie flutter flutter_layout_grid flutter_svg flutter_widget_from_html_core html url_launcher video_player webview_flutter]
- get 3.15.0 [flutter]
- image_picker 0.6.7+12 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- json_annotation 3.1.0
- logger 0.9.4
- oktoast 2.3.2 [flutter]
- onesignal_flutter 2.6.1 [flutter]
- package_info 0.4.3+2 [flutter]
- path_provider 1.6.21 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pull_to_refresh 1.6.2 [flutter]
- redux_thunk 0.3.0 [redux]
- sp_util 1.0.1 [flutter synchronized shared_preferences]
- sticky_headers 0.1.8+1 [flutter meta]
- validators 2.0.1 [vin_decoder]
- vertical_tabs 0.2.0 [flutter]
- webview_flutter 1.0.3 [flutter]

dev dependencies:
- build_runner 1.10.3 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.0 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 11.0.0 [meta]
- analyzer 0.40.4 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- basic_utils 2.7.0-rc.1 [http logging json_annotation pointycastle convert crypto]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.1 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- chewie 0.9.10 [open_iconic_flutter video_player wakelock flutter]
- chewie_audio 1.0.0+1 [open_iconic_flutter video_player screen flutter]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- common_utils 1.2.1 [decimal crypto convert]
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+5 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- country_pickers 1.3.0 [flutter]
- crypto 2.1.5 [collection convert typed_data]
- css_colors 1.0.2 [flutter]
- csslib 0.16.2 [source_span]
- dart_style 1.3.7 [analyzer args path source_span]
- date_range_picker 1.0.6 [flutter]
- datetime_picker_formfield 1.0.0 [flutter intl]
- decimal 0.3.5 [rational]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core 0.6.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+2 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.5 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_chips_input 1.9.4 [flutter]
- flutter_colorpicker 0.3.4 [flutter]
- flutter_keyboard_visibility 3.2.2 [flutter]
- flutter_layout_grid 0.10.2 [collection flutter meta quiver]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_touch_spin 1.0.1 [flutter intl]
- flutter_typeahead 1.8.8 [flutter flutter_keyboard_visibility]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.5.1+3 [flutter html]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- image_picker_for_web 0.1.0+2 [image_picker_platform_interface flutter flutter_web_plugins meta js]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- matrix4_transform 1.1.5 [flutter]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- open_iconic_flutter 0.3.0 [flutter]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- phone_number 0.6.3 [flutter]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.0
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- random_string 2.1.0
- rating_bar 0.2.0 [flutter]
- rational 0.3.8
- redux 4.0.0+3
- rxdart 0.24.1
- screen 0.0.5 [flutter]
- shared_preferences 0.5.12+2 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- signature 3.2.0 [flutter image]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- transformer_page_view 0.1.6 [flutter]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher 5.7.5 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- vin_decoder 0.1.2 [meta basic_utils http random_string]
- wakelock 0.1.4+2 [flutter]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

**Comment by wangxingxing123654** [comment]
> Hi @wangxingxing123654
> Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
> Thank you

yes.thank u very much

**Comment by wangxingxing123654** [comment]
> > Hi @wangxingxing123654
> > Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
> > Thank you
> 
> yes.thank u very much

but android worked very well

**Comment by markusaksli-nc** [comment]
Are you getting the data from the link correctly?

Have you tried running the [official example code](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_dynamic_links/example/lib/main.dart)?
