### ISSUE TITLE
FirebaseDynamicLinks retrieveDynamicLink() only retrieves the links in Firebase, not the link that opened the app

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#468]
I've followed Diego's [Flutter : Firebase Dynamic Link](https://medium.com/@diegoveloper/flutter-firebase-dynamic-link-6f1b79278ce0) tutorial but the method FirebaseDynamicLinks.instance.retrieveDynamicLink() doesn't return the link that opened the app. To quote Diego's article:

> FirebaseDynamicLinks.instance.retrieveDynamicLink() is the call that is responsible for obtaining the deep link in the case our application was opened from the dynamic link.

But it doesn't. Instead it just pulls the dynamic links that exist in the Firebase dynamic links console. I have one link there that I initially created for testing purposes. This method always returns that link, even when opening the app using a link I created using DynamicLinkParameters.

Is there another way to get the link that opened the app? The [current documentation](https://firebase.google.com/docs/dynamic-links/android/receive?authuser=0) from Firebase doesn't mention how to do it in Flutter.

I'm using Flutter version 1.1.8 and firebase_dynamic_links 0.1.0+1 (as 0.2.0 seems to be broken at the moment)

**Comment by kroikie** [comment]
@Daniel-WM-Roy

The issue at https://github.com/flutter/flutter/issues/27439 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi 
I see a [PR ](https://github.com/flutter/plugins/pull/1687)merged related to this issue;
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
