### ISSUE TITLE
🐛 [firebase_messaging] ^8.0.0-dev.14 causes badge issues

### ISSUE THREAD

**Issue by m-j-g** [FirebaseExtended/flutterfire#4682]
## Bug report

**Describe the bug**
I've been using messaging in my app for a year with correct behavior.  I just upgraded to firebase_messaging: ^8.0.0-dev.14 and followed the migration guide.  Everything is working except on iOS the badge icon on the application is all messed up.  Sometimes it never goes away no matter what I try.  Sometimes it won't show up, but when you click on the icon the badge turns on while it's expanding, and then when you minimize you see it until it finishes minimizing.

Never had anything like this before upgrading the messaging version.

### Expected behavior
Should clear when the app is opened.

**Comment by markusaksli-nc** [comment]
Hi @m-j-g 
Please see https://github.com/FirebaseExtended/flutterfire/issues/4145#issuecomment-739571979
If you believe that this is caused specifically by this plugin please provide your `flutter -doctor -v`, `flutter pub deps -- --style=compact` and a 
[minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third-party plugins.

Closing this as we do not control this behavior.
Thank you

**Comment by shic** [comment]
Create another issue https://github.com/FirebaseExtended/flutterfire/issues/4930 , hope that we can solve this problem together
