### ISSUE TITLE
🐛 [FCM on iOS] I Cant receive FCM with the app in background or killed, only in foreground (in android it works)

### ISSUE THREAD

**Issue by GilbertoGmobil** [FirebaseExtended/flutterfire#4687]
## Bug report

**Describe the bug**
Using FCM with flutter in android, the messages are delivered normally (both fore and background), but in iOS I only receive the pushing if the app is opened (if it is closed or in background, when you opens the app it shows the notification

### Steps to reproduce

This is the dart code that manages the pushs:
```dart
Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) async {
  if (message.containsKey('data')) {
    // Handle data message
    final dynamic data = message['data'];
  }

  if (message.containsKey('notification')) {
    // Handle notification message
    final dynamic notification = message['notification'];
  }

  // Or do other work.
}


class PushNotificationsManager {

  PushNotificationsManager._();

  factory PushNotificationsManager() => _instance;

  static final PushNotificationsManager _instance = PushNotificationsManager
      ._();

  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  final NotificationPlugin _notificationPlugin = NotificationPlugin();

  Future<void> init() async {
    if (Platform.isIOS) {
      _firebaseMessaging.requestNotificationPermissions(
          IosNotificationSettings());
    }
    _firebaseMessaging.configure(
      // Called when the app is in the foreground and we receive a push notif.
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: ${message}");
        print(message['notification']['body']);
        _notificationPlugin.showNotification(
            title: 'TEST',
            content: message['notification']['body']
        );
        //sendNotification();
      },
      // Called when the app has been closed completely and its opened
      // from the notification directly

      //onBackgroundMessage: Platform.isAndroid ? myBackgroundMessageHandler:null,
      onBackgroundMessage: myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        if(Platform.isIOS){
          message = _modifyNotificationJson(message);
        }
      },
      // Called when the app is in the background and its opened from the notif
      onResume: (Map<String, dynamic> message) async {
        print("onMessage: ${message}");
        if(Platform.isIOS){
          message = _modifyNotificationJson(message);
        }
      },
    );

  }

  Map _modifyNotificationJson(Map<String, dynamic> message) {
    message['data'] = Map.from(message ?? {});
    message['notification'] = message['aps']['alert'];
    return message;
  }


  Future sendNotification(String body, String title) async {
    final String url = 'https://fcm.googleapis.com/fcm/send';
    var notification;
    notification =
    '{"notification": {"body": "${body}", "title": "${title}", "content_available": "true", "click_action": "FLUTTER_NOTIFICATION_CLICK"}, "priority": "high", "to": "MYTOPIC"}';
    final response = await http.post(
        url,
        headers: <String, String>{
          "Content-Type": "application/json",
          "Keep-Alive": "timeout=5",
          "Authorization": "key=MYKEY"
        },
        body: notification
    );

    print(response.body);
  }
}
```

AppDelegate.swift:
```swift
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      // For iOS 10 display notification (sent via APNS)
      UNUserNotificationCenter.current().delegate = self

      let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
      UNUserNotificationCenter.current().requestAuthorization(
        options: authOptions,
        completionHandler: {_, _ in })
    } else {
      let settings: UIUserNotificationSettings =
      UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
      application.registerUserNotificationSettings(settings)
    }

    application.registerForRemoteNotifications()
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}


```

### Expected behavior

Be able to receive notifications in background with an iOS device.

### Things I've tried

1 Create a key in developers.apple and apply it within firebase
2 feed my project with googleservices.plist
3 turn on Push Notifications and Background Modes, and enable Background fetch and Remote notifications under Background Modes.

**Comment by kroikie** [comment]
@GilbertoGmobil are you able to receive notification messages (display) when the app is in the background?

**Comment by GilbertoGmobil** [comment]
> @GilbertoGmobil are you able to receive notification messages (display) when the app is in the background?

I only receive notifications when the app is opened. In background or killed, it did not receive

**Comment by kroikie** [comment]
Could you provide an example of the message/payload you are sending to the API?

**Comment by GilbertoGmobil** [comment]
> Could you provide an example of the message/payload you are sending to the API?

```'{"notification": {"body": "${body}", "title": "${title}", "content_available": "true", "click_action": "FLUTTER_NOTIFICATION_CLICK"}, "priority": "high", "to": "MYTOPIC"}';```

**Comment by kroikie** [comment]
@GilbertoGmobil if you are sending a notification message then you should be ok to remove `content_available`. Could you give that a try?

**Comment by GilbertoGmobil** [comment]
> @GilbertoGmobil if you are sending a notification message then you should be ok to remove `content_available`. Could you give that a try?

Ok, I will remove this tag and tell what happens

**Comment by GilbertoGmobil** [comment]
> @GilbertoGmobil if you are sending a notification message then you should be ok to remove `content_available`. Could you give that a try?

I tried it and still the same behavior

**Comment by GilbertoGmobil** [comment]
If I try to send a message through Firebase Console, I get the same behavior too

**Comment by markusaksli-nc** [comment]
Background messages only work for me with `content_available` set as true.

Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?

**Comment by GilbertoGmobil** [comment]
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64,
    locale pt-BR)
    • Flutter version 1.22.5 at /Users/interno/Documents/FlutterSDK/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/interno/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Lenovo K33a48 (mobile) • 37f49ac2                                 •
      android-arm • Android 7.0 (API 24)
    • iPad (mobile)          • 661041b09cc8cf8269938c513f46783e87db4c69 • ios
      • iOS 14.3
    ! Error: iPad is busy: Copying cache files from device. Xcode will continue
      when iPad is finished. (code -10)

------------------------------------------------------------------------------

Dart SDK 2.10.4
Flutter SDK 1.22.5
app_md 1.0.0+1

dependencies:
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.1 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cpfcnpj 1.0.3
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- email_validator 1.0.6
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_storage 5.2.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_barcode_scanner 1.0.1 [flutter flutter_plugin_android_lifecycle]
- flutter_local_notifications 3.0.1 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flux_validator_dart 1.0.3
- hive 1.4.4 [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- http 0.12.2 [http_parser path pedantic]
- image_picker 0.6.7+14 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- mask_shifter 0.1.0 [flutter]
- mask_text_input_formatter 1.1.0 [flutter]
- open_file 3.0.3 [flutter ffi]
- path_provider 1.6.22 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pdf 1.12.0 [archive barcode crypto image meta path_parsing utf vector_math]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- printing 3.7.1 [flutter flutter_web_plugins image js meta pdf plugin_platform_interface]
- provider 4.3.2+2 [flutter nested collection]
- qr_code_scanner 0.0.13 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- table_calendar 2.3.1 [flutter intl simple_gesture_detector]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- build_runner 1.10.0 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 0.7.2+1 [build source_gen hive analyzer dartx]

transitive dependencies:
- _fe_analyzer_shared 6.0.0 [meta]
- analyzer 0.39.14 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- barcode 1.17.1 [meta qr]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 5.2.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.1.4 [path]
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- code_builder 3.4.1 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- dartx 0.5.0 [collection path crypto characters time meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+1 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_local_notifications_platform_interface 2.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- html 0.14.0+3 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.0
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.0
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- qr 1.3.0 [meta]
- quiver 2.1.3 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- simple_gesture_detector 0.1.4 [flutter]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 1.3.0
- timezone 0.5.9 [path]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- utf 0.9.0+5
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

> Background messages only work for me with `content_available` set as true.
> 
> Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?

**Comment by GilbertoGmobil** [comment]
I'm dealing with it since day 9.. Please someone help me

**Comment by GilbertoGmobil** [comment]
I just tried to copy the AppDelegate example from firebase documentation and my application opens with a white screen... link :https://github.com/firebase/quickstart-ios/blob/7b30d9ea9e380f965df69c17656060e7b5a41caf/messaging/MessagingExampleSwift/AppDelegate.swift#L40-L55

**Comment by eldarkk** [comment]
> I just tried to copy the AppDelegate example from firebase documentation and my application opens with a white screen... link :https://github.com/firebase/quickstart-ios/blob/7b30d9ea9e380f965df69c17656060e7b5a41caf/messaging/MessagingExampleSwift/AppDelegate.swift#L40-L55

i have AppDelegate.swift like below:
<script src="https://gist.github.com/eldarkk/bf904bd1efa5c0baec30ccf8e5ac63af.js"></script>

**Comment by markusaksli-nc** [comment]
I'm going to provide the same advice here that solved the issue on #4577 

Would you consider updating to the latest version of the package `firebase_messaging: ^8.0.0-dev.14`? It is a lot more stable and there have been major improvements. 

The version you are using will be replaced soon. There are a lot of breaking changes https://firebase.flutter.dev/docs/migration/#messaging. You can find the new official code sample [here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib).

**Comment by GilbertoGmobil** [comment]
It worked with the version 8.0.0-dev.14. Thank You @markusaksli-nc

**Comment by Eddybrtn** [comment]
@GilbertoGmobil Can you share a working code sample please ? I'm using version 8.0.0-dev.14 too but the background handler or `onMessage` are never called

**Comment by GilbertoGmobil** [comment]
ENSURE that all this steps are did: https://firebase.flutter.dev/docs/messaging/apple-integration . In my case my apn in firebase was with a wrong team ID, so, ensure you did it all as the documentation said.

With this code you be able to receive a test notification from firebase console (call in some point):
```
  Future<void> init() async {

    if(Platform.isIOS){
      NotificationSettings settings = await _firebaseMessaging.requestPermission(
        alert: true,
        announcement: false,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional: false,
        sound: true,
      );
    }

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print("This is the message: ${message}");
      _notificationPlugin.showNotification(
          title: message.notification.title,
          content: message.notification.body
      );
    });

  }
```
I keep my appDelegate as in the question.

> @GilbertoGmobil Can you share a working code sample please ? I'm using version 8.0.0-dev.14 too but the background handler or `onMessage` are never called on iOS
