### ISSUE TITLE
[firebase_messaging] ^8.0.0-dev.14 fails to find firebase-common for Android

### ISSUE THREAD

**Issue by paod634** [FirebaseExtended/flutterfire#4688]
## Bug report

**Describe the bug**
When I attempt to build on Android (on device/emulator), I'm getting an exception:

```
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
Could not find com.google.firebase:firebase-common
```

### Steps to reproduce

1. Import these 2 packages
2. Build on Android
3. See error in build

### Expected behavior

I expect to be able to build with no exceptions thrown.

---

## Additional context

I pinpointed the issue down to this line: https://github.com/FirebaseExtended/flutterfire/pull/4332/files#diff-2c4eea23b5624817aad89ebeefdc2b88c945c25835adce7c8159735914ef230fL39 which seems to have just changed in 
8.0.0-dev.14 from 8.0.0-dev.13.

My gradle.properties:
```android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

gradle-wrapper.properties uses gradle:
```distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip```

### Flutter dependencies

The only 2 packages I'm using are:
```  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_remote_config: ^0.6.0
```

**Comment by markusaksli-nc** [comment]
Hi @paod634 
I'm not seeing this. Have you run `flutter clean` and then `flutter pub get`?
Are you not able to run the official example with 
```yaml
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_remote_config: ^0.6.0
  flutter_local_notifications: ^3.0.3
  http: ^0.12.2
```
Could you please also provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by Prayer-RecycleSmart** [comment]
having the same issue
