### ISSUE TITLE
🐛 [firebase_auth] The Other sign-in methods link in the official document does not work.

### ISSUE THREAD

**Issue by Jay-flow** [FirebaseExtended/flutterfire#4696]
## Bug report
The Other sign-in methods link in the official document does not work.
https://firebase.flutter.dev/docs/auth/usage/#other-sign-in-methods

![image](https://user-images.githubusercontent.com/29420674/104808287-80eec580-5828-11eb-92ac-ed924433ca46.png)

When moving the Other sign-in methods link, it goes to the following error page:
https://firebase.flutter.dev/docs/auth/usage/social#apple
![image](https://user-images.githubusercontent.com/29420674/104808320-c4e1ca80-5828-11eb-814a-14be5edd329b.png)

**Comment by Salakar** [comment]
cc @Ehesp 🙈 it's back again

**Comment by Ehesp** [comment]
This makes zero sense 😓 Will pull locally and check again.

**Comment by russellwheatley** [comment]
As far as I can tell, these links work now.
