### ISSUE TITLE
[cloud_firestore] causes NSException/Crash

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#470]
I have a local instance of `firebase` (and `cloud_firestore`), which in turn I want to use for debugging.

I've tried (and failed) to get this to work:

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

/// Returns a local firestore dataset.
Future<Storage> debugFirebaseStorage() async {
  const debugId = 'DEBUG';
  const debugUrl = 'http://localhost:5000';
  final debugApp = await FirebaseApp.configure(
    name: 'DEBUG',
    options: FirebaseOptions(
      googleAppID: debugId,
      databaseURL: debugUrl,
    ),
  );
  final firestore = Firestore(app: debugApp);
  return Storage.fromFirebase(firestore: firestore);
}
```

The documentation for `configure reads`, confusingly:

```dart
  /// Configures an app with the given [name] and [options].
  ///
  /// Configuring the default app is not currently supported. Plugins that
  /// can interact with the default app should configure it automatically at
  /// plugin registration time.
  ///
  /// Changing the options of a configured app is not supported. Reconfiguring
  /// an existing app will assert that the options haven't changed.
  static Future<FirebaseApp> configure({
    @required String name,
    @required FirebaseOptions options,
  })
```

At runtime, the following crash occurs, closing the app (it is not handled by Flutter):

```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ec931e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010e328031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ed08975 +[NSException raise:format:] + 197
	3   Runner                              0x0000000109c40033 +[FIRApp addAppToAppDictionary:] + 291
	4   Runner                              0x0000000109c3f54d +[FIRApp configureWithName:options:] + 1101
	5   Runner                              0x000000010a04db31 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 3041
	6   Flutter                             0x000000010b3449a2 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	7   Flutter                             0x000000010b361616 _Z<…>
Lost connection to device.
```

... so, tl;dr:

* [ ] How do I connect to a local database without hardcoding it in my `.plist`?
* [ ] Should Flutter be handling this crash without the app closing?

**Comment by kroikie** [comment]
@matanlurey

The issue at https://github.com/flutter/flutter/issues/27370 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by Dabaiee** [comment]
I am experiencing the same problem. Here is my flutter doc -v and other information as follows.
(base) tongzhoudeMacBook-Pro:firebase_setup2 tongzhou$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.5.4 at /Users/tongzhou/flutter
    • Framework revision b593f5167b (8 months ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tongzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.2
    • Dart plugin version 183.4588.61

[✓] Connected device (1 available)
    • iPhone Xʀ • 955E6861-2483-4F72-8955-7E99EC1E7C3C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
