### ISSUE TITLE
🐛 [firebase_auth] `FirebaseAuth.instance.userChanges()` stream is not listening to user profile changes. 

### ISSUE THREAD

**Issue by osaxma** [FirebaseExtended/flutterfire#4700]
## Bug report

**Describe the bug**

In a flutter app, I'm listening to the following inside a `streamBuilder`:

```dart 
return StreamBuilder<User>(
      stream: FirebaseAuth.instance.userChanges(),
      builder:  (context, snapshot) { 
         // logic based on `User` snapshot data to determine which screen to return. 
        ....
        ....
        ....
        return screen;
       }
      );
```

Using the admin sdk in a node js server, I'm updating the user data manually for testing:

```ts
// update display name and photoURL 
admin.auth().updateUser("user_id", {displayName: "some display name",  photoURL: "a photo URL", });

// update custom claims
admin.auth().setCustomUserClaims( "user_id", customClaims);

```

The stream doesn't update even though the data is updated on Firebase Authentication. I've verified by retrieving the user data through `admin.auth().getUser("user_id")`.

### Expected behavior

 `FirebaseAuth.instance.userChanges()` stream is supposed to be listening to changes on the user profile as documented:

>  [userChanges()] provides events on all user changes, such as when credentials are linked, unlinked and when updates to the **user profile** are made.

---

## Additional context

`userChanges()` is updating properly to sign-in and sign-out events. Also it's updating properly upon the expiration of the `IdToken`.  

The problem appears on both iOS and Web on the latest master (`1.26.0-2.0.pre.396`) and the latest firebase auth (`0.20.0+1`). 

Even after a `hot reload` and `hot restart` , `userChanges()` doesn't update the data. 

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.396, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

```

</details>

---

### Firebase dependencies

<details><summary>Click To Expand</summary>

```
  firebase_core : ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_analytics: ^7.0.1
  cloud_functions: ^0.9.0
```

</details>

---

**Comment by osaxma** [comment]
The same issue when listening to `FirebaseAuth.instance.idTokenChanges()`, the stream doesn't listen to changes in user profile or custom claims updates which are part of the JWT. So when any of the user data updates, the JWT updates, hence `FirebaseAuth.instance.idTokenChanges()` should also update upon these changes.

**Comment by markusaksli-nc** [comment]
I was able to reproduce this on Android as well on the latest master `1.26.0-2.0.pre.402` with `firebase_auth: ^0.20.0+1` using the official example and https://github.com/FirebaseExtended/flutterfire/pull/4635.
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.26.0-2.0.pre.402, on Microsoft Windows [Version 10.0.19041.746], locale et-EE)
    • Flutter version 1.26.0-2.0.pre.402 at C:\Development\flutter_master
    • Framework revision 2a188eeca3 (32 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```
</details>

**Comment by larssn** [comment]
Seeing the same behavior, but for email validation: `emailVerified` remains false until you do a `user.reload()`

**Comment by aperezhra** [comment]
Hello Folks! 
Do you have any workaround for this?

I have a use case where I update firebase user's photoURL with the Facebook tokenized profile photo, but these changes are not reflected to my User stream until the next time log back in.

Please help.

**Comment by aperezhra** [comment]
> > Hello Folks!
> > Do you have any workaround for this?
> > I have a use case where I update firebase user's photoURL with the Facebook tokenized profile photo, but these changes are not reflected to my User stream until the next time log back in.
> > Please help.
> 
> Run `.reload()` on the firebase user. This refreshes the object with the latest data from the server.
> 
> Just be aware that this promise will hang forever if offline.

Thanks @larssn. This is what I've tried, I placed a reload in two different places, but none of them refreshes the photoURL.

Next time I log back in, then the photo is loaded correctly.

**This is on my AuthService**
```
  void updateProfilePhoto({String photoURL}) {
    _auth.currentUser.updateProfile(photoURL: photoURL);
    _auth.currentUser.reload();
  }
```

**Which is called from the AuthBloc**
```
        // Updating profile photo
        var profileImageUrl =
            await facebookSignIn.getProfileImageUrl(width: 400);
        authService.updateProfilePhoto(photoURL: profileImageUrl);
```

**Also reloading the User snapshot right before rendering the profile photo**
```
return Scaffold(
      body: Center(
        child: StreamBuilder<User>(
            stream: authBloc.currentUser,
            builder: (context, snapshot) {
              // If no data on the spnapshot
              if (!snapshot.hasData) return CircularProgressIndicator();
              snapshot.data.reload();
              // Rendering user profile
              print("Home - Rendering user profile");
              return Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircleAvatar(
                    backgroundImage: NetworkImage(
                        snapshot.data.photoURL.replaceFirst("s96", "s400")),
                    radius: 60,
                  ),
                  SizedBox(
                    height: 20,
                  ),
                  Text(
                    snapshot.data.displayName,
                    style: TextStyle(fontSize: 35),
                  ),
                  SizedBox(
                    height: 100,
                  ),
                  FutureBuilder<Container>(
                      future: buildSignOutButton(context),
                      builder: (context, snapshot) {
                        // The following line checks for when there's still no data to display
                        if (!snapshot.hasData)
                          return CircularProgressIndicator();
                        // Returning the SignInButton
                        return snapshot.data;
                      })
                ],
              );
            }),
      ),
    );
```

Related Issues

- [Innim/flutter_login_facebook#49](https://github.com/Innim/flutter_login_facebook/issues/49)
- [FirebaseExtended/flutterfire#3839](https://github.com/FirebaseExtended/flutterfire/issues/3839)

**Comment by aperezhra** [comment]
> > Hello Folks!
> > Do you have any workaround for this?
> > I have a use case where I update firebase user's photoURL with the Facebook tokenized profile photo, but these changes are not reflected to my User stream until the next time log back in.
> > Please help.
> 
> Run `.reload()` on the firebase user. This refreshes the object with the latest data from the server.
> 
> Just be aware that this promise will hang forever if offline.

Finally I nailed it, no need for a reload() the only thing I had to do is to replace the authStateChanges() Stream with the userChanges() Stream.

```
  // Stream for Current User
  Stream<User> get currentUser {
    print("FirebaseAuthService - Stream currentUser");
    return _auth.userChanges();
  }
```

I couldn't find the online documentation for this Stream, but according to VSCode 

> () → Stream<User>
> 
> Notifies about changes to any user updates.
> 
> This is a superset of both [authStateChanges] and [idTokenChanges]. It provides events on all user changes, such as when credentials are linked, unlinked and when updates to the user profile are made. The purpose of this Stream is for listening to realtime updates to the user state (signed-in, signed-out, different user & token refresh) without manually having to call [reload] and then rehydrating changes to your application.
>

**Comment by markusaksli-nc** [comment]
Well the whole issue is about the `userChanges` stream not firing in response to certain events.

**Comment by russellwheatley** [comment]
Hey folks, this isn't a bug. `userChanges()` does not fire to when changes  are made via the Firebase admin sdk. I'm raising a PR to improve the documentation surrounding the auth event listeners.
