### ISSUE TITLE
🐛 [firebase_messaging] Completely Crashes Web apps on Safari

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#4714]
## Bug report

When adding a `firebase_messaging: ^8.0.0-dev.12` dependency, running on Flutter web **on Safari**, the app crashes completely on start up (Flutter does not finish initializing and you only see a blank page). This happens both in `debug` and `release` mode.

### Steps to reproduce

1. Add `firebase_messaging: ^8.0.0-dev.12` depenedency
2. Follow https://firebase.flutter.dev/docs/installation/web and https://firebase.flutter.dev/docs/messaging/overview#5-web-only-add-the-sdk.
3. Reference the library in code. It is not necessary that any messaging code is executed.
4. Run on Flutter web (`flutter run -d chrome`).
5. Open the localhost port in Safari.

On Safari, you will see the following error in the JS console:

```
Unhandled Promise Rejection: FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).
```

**More importantly**, the Flutter app **does not start**. It crashes on startup (in the `registerWith` call).

### Expected behavior

It is okay that Firebase Messaging is not supported on Safari (see https://stackoverflow.com/a/45555509/6509751).

However, it is not okay that the whole web app crashes on Safari, even when not even calling messaging code.

---

## Additional context

* #4584 is related but it is not that important.

This issue is critical because our whole web app does not run on Safari, even though we already do not call messaging code on web.

I solved this issue by creating a [stub branch](https://github.com/simpleclub-extended/flutterfire/commit/fb3bc3c047c5378a100442713fdda16a8d5f8ff8) that removes the web implementation in `firebase_messaging_web` and allows me to just override `firebase_messaging_web`, so we can still use the current mobile version.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.3.pre at /Library/flutter
    • Framework revision 5d36f2e7f5 (3 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase 7.3.3 [http http_parser js]
- firebase_analytics 7.0.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.19.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.6.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.3.0 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.7.0 [flutter firebase_core]
- firebase_in_app_messaging 0.3.0 [meta flutter firebase_core]
- firebase_messaging 8.0.0-dev.12 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- firebase_performance 0.5.0 [flutter firebase_core]
- firebase_remote_config 0.5.0 [flutter firebase_core]
- firebase_storage 6.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]

```

</details>

---

**Comment by markusaksli-nc** [comment]
Hey @creativecreatorormaybenot 
I'm not seeing this on the latest beta `1.25.0-8.3.pre` with `firebase_messaging: ^8.0.0-dev.14`.
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/nevercode/development/flutter_stable
    • Framework revision 5d36f2e7f5 (5 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
</details>

It was likely fixed in `firebase_messaging_web: ^0.1.0-dev.5`:

> FIX: check is supported before init web (#4644).

Can you confirm whether this persists on the latest version?

**Comment by creativecreatorormaybenot** [comment]
@markusaksli-nc It looks like that PR fixes exactly that, yes 👍

**Comment by markusaksli-nc** [comment]
Thanks, closing this as solved.
