### ISSUE TITLE
🐛 [firebase_remote_config] flutter pub giving error on getting 0.8.0-dev.0 with core 0.7.0

### ISSUE THREAD

**Issue by inceptusp** [FirebaseExtended/flutterfire#4719]
## Bug report

Remote config with firebase_core 0.7.0 gives the following error on pub get:
```
Because firebase_remote_config >=0.8.0-dev.0 depends on firebase_remote_config_platform_interface ^0.1.0-dev.0 which depends on firebase_core ^0.5.2, firebase_remote_config >=0.8.0-dev.0 requires firebase_core ^0.5.2.

So, because **** depends on both firebase_core ^0.7.0 and firebase_remote_config ^0.8.0-dev.0, version solving failed.
pub get failed (1; So, because **** depends on both firebase_core ^0.7.0 and firebase_remote_config ^0.8.0-dev.0, version solving failed.)
exit code 1
```

### Steps to reproduce

1. Add ```firebase_remote_config: ^0.8.0-dev.0``` and ```firebase_core: ^0.7.0``` to pubspec
2. Run a ```flutter pub get```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.19042.746], locale pt-BR)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

**Comment by britannio** [comment]
Was 0.7.0 supposed to be a pre-release?

**Comment by britannio** [comment]
> > Was 0.7.0 supposed to be a pre-release?
> 
> No, 0.7.0 is the latest release of core and needed by others updated firebase plugins, only remote_config is giving this error

Ah, I should've specified that I was asking about firebase_remote_config 0.7.0. There's a pre-release of 0.8.0-dev.0 and it's changelog contains notes for 0.7.0 but the latest resolvable version is 0.6.0

Anyway, the issue you're facing should be fixed via https://github.com/FirebaseExtended/flutterfire/pull/4689, they just need to publish a new release.

**Comment by FilledStacks** [comment]
Anyone have a workaround for this? I'm trying to go over to the "better packages" but I can't even get the package on my PC 😅

**Comment by pinkfish** [comment]
Has this been fixed?  Makes this package almost impossible to use right now.

**Comment by inceptusp** [comment]
@pinkfish no, they need to launch an update... For now, you can try dependency override, put this on your pubspec:
```
dependency_overrides:
  firebase_core: ^0.7.0
```

**Comment by SeanZom** [comment]
Follow this [Migration Guide](https://firebase.flutter.dev/docs/migration/) to update the packages, but got:
```
Because firebase_remote_config >=0.8.0-dev.0 depends on firebase_remote_config_platform_interface ^0.1.0-dev.0 which depends on firebase_core ^0.5.2, firebase_remote_config >=0.8.0-dev.0 requires firebase_core ^0.5.2.
```

Any update??

**Comment by YegorMedvedev** [comment]
The same for me...
```
Because firebase_remote_config >=0.8.0-dev.0 depends on firebase_remote_config_platform_interface ^0.1.0-dev.0 which depends on firebase_core ^0.5.2, firebase_remote_config >=0.8.0-dev.0 requires firebase_core ^0.5.2.
```

Have anyone found workaround?

**Comment by bidimensional** [comment]
Same problem here..

**Comment by SeanZom** [comment]
> Please thumbs up the original issue comment instead of commenting that you have the same issue unless you have anything unmentioned to contribute.
> 
> To be clear here, the problem is just with the very early and unfinished prerelease `firebase_remote_config: ^0.8.0-dev.0`. You can just use the latest `firebase_remote_config: ^0.6.0` instead.

Using  the migration guide on FlutterFire with `firebase_remote_config: ^0.6.0` doesn't work either

**Comment by markusaksli-nc** [comment]
What issue are you specifically having with that version? @SeanZom

**Comment by Salakar** [comment]
This should have been resolved since this issue has been made, please try the latest release.
