### ISSUE TITLE
Because "App Name" depends on firebase_auth 0.18.1+2 which depends on firebase_core ^0.5.0+1, firebase_core ^0.5.0+1 is required.

### ISSUE THREAD

**Issue by Bac-Pham** [FirebaseExtended/flutterfire#4722]
please help me
Because food_delivery_app depends on firebase_auth 0.18.1+2 which depends on firebase_core ^0.5.0+1, firebase_core ^0.5.0+1 is required.
So, because food_delivery_app depends on firebase_core ^0.7.0, version solving failed.
pub get failed (1; So, because food_delivery_app depends on firebase_core ^0.7.0, version solving failed.)
Process finished with exit code 1
i have use 
cupertino_icons: 1.0.0
  google_maps_flutter: 1.0.3
  google_map_location_picker: 4.0.0
  mvc_pattern: 6.3.0
  global_configuration: 1.6.0
  http: 0.12.2
  html: 0.14.0+4
  shared_preferences: ^0.5.12+2
  flutter_html: 1.0.2
  flutter_svg: 0.18.1
  location: 3.0.2
  webview_flutter: 0.3.24
  url_launcher: 5.7.7
  firebase_messaging: ^8.0.0-dev.14
  cached_network_image: 2.3.3
  fluttertoast: 4.0.1
  flutter_staggered_grid_view: 0.3.2
  #intl_utils: 1.8.0
  carousel_slider: 2.3.1
  cloud_firestore: ^0.16.0
  firebase_auth: 0.18.1+2
  firebase_core: ^0.7.0

**Comment by ercadev** [comment]
You have upgraded `firebase_core` and not `firebase_auth`
You should set
`firebase_auth: ^0.20.0+1`
Which depends on the correct `firebase_core` version
