### ISSUE TITLE
App crashing on using Phone authentcation on android real device

### ISSUE THREAD

**Issue by harshagr64** [FirebaseExtended/flutterfire#4723]
I wanted to use Phone Authentication for my flutter app.

I already setup SHA-1 key for my project.

as soon as I enters Phone Number and hit submit button. App crashes without giving any error on console.

**Comment by Shiba-Kar** [comment]
add this in app level gridle ``implementation "androidx.browser:browser:1.2.0"``

**Comment by Shiba-Kar** [comment]
> I wanted to use Phone Authentication for my flutter app.
> 
> I already setup SHA-1 key for my project.
> 
> as soon as I enters Phone Number and hit submit button. App crashes without giving any error on console.

While you are reporting bugs please provide the error too.

**Comment by harshagr64** [comment]
Actually, it is not showing any error on the console.

It is just showing lost connection to device and app crashes.

Thank you for your help, it actually worked but it is taking to a Web page for verifying so, how can I remove this shifting ?? @Shiba-Kar

**Comment by Nandan-Wewhare** [comment]
> add this in app level gridle `implementation "androidx.browser:browser:1.2.0"`

@Shiba-Kar doesn't solve the issue still.

**Comment by Nandan-Wewhare** [comment]
```
E/AndroidRuntime(12549): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder;
E/AndroidRuntime(12549): 	at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.2:13)
E/AndroidRuntime(12549): 	at com.google.android.gms.internal.firebase-auth-api.zztw.zzb(com.google.firebase:firebase-auth@@20.0.2:7)
E/AndroidRuntime(12549): 	at com.google.android.gms.internal.firebase-auth-api.zztw.onPostExecute(Unknown Source:2)
E/AndroidRuntime(12549): 	at android.os.AsyncTask.finish(AsyncTask.java:755)
E/AndroidRuntime(12549): 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
E/AndroidRuntime(12549): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
E/AndroidRuntime(12549): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(12549): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(12549): 	at android.app.ActivityThread.main(ActivityThread.java:7592)
E/AndroidRuntime(12549): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12549): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(12549): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(12549): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.browser.customtabs.CustomTabsIntent$Builder" on path: DexPathList[[zip file "/data/app/com.tribus.raj_criminal_cases-zmM8k_ZANdrNWQOnse7hcw==/base.apk"],nativeLibraryDirectories=[/data/app/com.tribus.raj_criminal_cases-zmM8k_ZANdrNWQOnse7hcw==/lib/arm64, /data/app/com.tribus.raj_criminal_cases-zmM8k_ZANdrNWQOnse7hcw==/base.apk!/lib/arm64-v8a, /system/lib64, `/system/product/lib64]]
```

**Comment by darshankawar** [comment]
@harshagr64 
Is your issue resolved or still facing crash ? 
Before you can use your phone authentication on Android device, you need to add SHA-256 which is required for Android device verification. Try that and see if it resolves your issue.

**Comment by darshankawar** [comment]
@Nandan-Wewhare 
Regarding the error you are getting, there's similar open issue for it, https://github.com/FirebaseExtended/flutterfire/issues/4651. Follow-up there for updates.

**Comment by harshagr64** [comment]
Yes, my issue is resolved without adding SHA-256 in firebase project @darshankawar. 
Thank you for your suggestion.

**Comment by darshankawar** [comment]
Thanks for confirming @harshagr64. Closing this as resolved.

**Comment by Shiba-Kar** [comment]
@harshagr64 Have you done this https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification?
