### ISSUE TITLE
🐛 [firebase_messaging]Background notifications not working on iOS with Flutter package firebase_messaging

### ISSUE THREAD

**Issue by RNSuthar** [FirebaseExtended/flutterfire#4725]
I've come across many questions like this on StackOverflow and Github, but I haven't found the answer.

I have an Apple development profile, and I've uploaded APNs Auth Key to Firebase.

I have enabled Background fetch, Remote notifications and Background processing, as well as Push Notifications in my xCode.

**Comment by GilbertoGmobil** [comment]
I have the same problem: https://github.com/FirebaseExtended/flutterfire/issues/4687 and cant find a solution

**Comment by markusaksli-nc** [comment]
Hi @RNSuthar 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by viskanic** [comment]
@RNSuthar Take a look @ https://firebase.flutter.dev/docs/messaging/notifications/#handling-interaction

Background messages work for me on iOS after adding the FirebaseMessaging.onMessageOpenedApp.listen method.
