### ISSUE TITLE
[firebase_core] 0.7.0-nullsafety.0 is migrated out-of-order / should have been 0.8.0-nullsafety.0

### ISSUE THREAD

**Issue by jonasfj** [FirebaseExtended/flutterfire#4728]
[Semantic Versioning version 2.0.0-rc.1.](https://semver.org/spec/v2.0.0-rc.1.html) works such that: `0.7.0 > 0.7.0-nullsafety.0`.

Essentially, the null-safety port from January 15th has a lower version number than the latest stable version from January 12th.

It's recommended that bump the major version when migrating to null-safety, see: [migration guide](https://dart.dev/null-safety/migration-guide#package-version).

Context: https://github.com/dart-lang/sdk/issues/44711

**Comment by markusaksli-nc** [comment]
Is this still relevant now that `1.0.0` is out?

**Comment by jonasfj** [comment]
Nope, publishing 1.0.0 also solved this issue.
