### ISSUE TITLE
🐛 [firebase_messaging: 8.0.0-dev.14] Unable to receive background messages on iOS

### ISSUE THREAD

**Issue by bobyuloffice** [FirebaseExtended/flutterfire#4734]
## Bug report

I recently switched to `firebase_messaging 8.0.0-dev.14`  because I found out that it supports background message handling in iOS devices. After switching to `firebase_messaging 8.0.0-dev.14` and making some changes, both `onMessage` and `backgroundMessage` work perfectly in Android. In iOS, `onMessage` works but `backgroundMessage` still does not work. 
In the previous versions of `firebase_messaging`, I was at least able to get notifications when the app resumed, but `firebase_messaging 8.0.0-dev.14` does not even give me the notifications when it resumes...

Some things I've tried:

1. I found an issue regarding `firebase auth`. However, I'm not using firebase auth.
2. I tried `flutter clean` and ran it again to no avail.
3. In my pubspec.yaml, I have both `firebase_messaging: ^8.0.0-dev.14` and `firebase_core: ^0.7.0`. I do NOT have `firebase_auth`
4. My payload contains both priority and content_available: 
```
message = {
    "notificaton": {
         "title": "hello world",
         "body": "hello world"
    },
    "priority": "high",
    "content_available": True,
    "data": {
       "info": {...}
    }
}
```
5. Tried it with both iphone6 and iphone8. Neither worked.
6. Set the target ios version to 10 and 11, neither worked.

### Flutter doctor
```

[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS)
    • Flutter version 1.26.0-1.0.pre at...
    • Framework revision 63062a6443,
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at ...
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    ....• ios • iOS 12.5.1

• No issues found!
```

### Runner

<img width="610" alt="runner" src="https://user-images.githubusercontent.com/70477996/105127187-ada22600-5b23-11eb-91bf-b47db61c067e.png">

### `AppDelegate.swift`

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```
### pubspec.yaml
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^8.0.0-dev.9
  flutter_local_notifications: ^3.0.3
  http: ^0.12.2
  shared_preferences: ^0.5.12+4 
```

### Versions I've tried
`firebase_messaging: ^8.0.0-dev.11`, `firebase_messaging: ^8.0.0-dev.14`, `firebase_messaging: ^8.0.0-dev.8` 

Any suggestions would be much appreciated.

**Comment by viskanic** [comment]
@bobyuloffice Take a look @ https://firebase.flutter.dev/docs/messaging/notifications/#handling-interaction

Background messages work for me on iOS after adding the `FirebaseMessaging.onMessageOpenedApp.listen` method.

**Comment by bobyuloffice** [comment]
> @bobyuloffice Take a look @ https://firebase.flutter.dev/docs/messaging/notifications/#handling-interaction
> 
> Background messages work for me on iOS after adding the `FirebaseMessaging.onMessageOpenedApp.listen` method.

I tried it, still didn't work.

**Comment by bobyuloffice** [comment]
> @bobyuloffice Take a look @ https://firebase.flutter.dev/docs/messaging/notifications/#handling-interaction
> 
> Background messages work for me on iOS after adding the `FirebaseMessaging.onMessageOpenedApp.listen` method.

`onMessageOpenedAll.listen` requires user to tap the notification. If not, the message gets lost which is a problem.

**Comment by GilbertoGmobil** [comment]
If you send a test in Firebase Console, it works?

**Comment by markusaksli-nc** [comment]
Hi @bobyuloffice 
Does the official example not work for you?
Have you tried sending through the v1 API instead?

Seems to be working just fine for me on the latest master `1.26.0-2.0.pre.420` with `firebase_messaging: ^8.0.0-dev.14`.
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.420, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.420 at /Users/nevercode/development/flutter_master
    • Framework revision b362d6f480 (48 minutes ago), 2021-01-20 18:47:51 +0800
    • Engine revision b58dbc88fc
    • Dart version 2.12.0 (build 2.12.0-240.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 88.0.4324.96

• No issues found!

```
</details>

**Comment by bobyuloffice** [comment]
> If you send a test in Firebase Console, it works?

when my app is in background, I get the notification on the top of the screen, but `onBackgroundMessageHandler` does not get called.

**Comment by bobyuloffice** [comment]
> Hi @bobyuloffice
> Does the official example not work for you?
> Have you tried sending through the v1 API instead?
> 
> Seems to be working just fine for me on the latest master `1.26.0-2.0.pre.420` with `firebase_messaging: ^8.0.0-dev.14`.
> flutter doctor -v
> 
> ```
> [✓] Flutter (Channel master, 1.26.0-2.0.pre.420, on macOS 11.1 20C69 darwin-arm, locale en-GB)
>     • Flutter version 1.26.0-2.0.pre.420 at /Users/nevercode/development/flutter_master
>     • Framework revision b362d6f480 (48 minutes ago), 2021-01-20 18:47:51 +0800
>     • Engine revision b58dbc88fc
>     • Dart version 2.12.0 (build 2.12.0-240.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/nevercode/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       � https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       � https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] Connected device (3 available)
>     • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
>     • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.1 20C69 darwin-arm
>     • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 88.0.4324.96
> 
> • No issues found!
> ```

**Comment by bobyuloffice** [comment]
@markusaksli-nc I just ran the example code from here: (https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.14/example). `onMessage` works like a charm but `background handler` never gets called.

**Comment by eldarkk** [comment]
If u want to get silent notification, try to remove **"notification**" key from payload.. As i know, Silent notification shouldnt contain notificaton key.

**Comment by bobyuloffice** [comment]
@eldarkk  I think you are confusing android to ios. For android, what you say is true, but iOS, without notification, you don't receive anything.

**Comment by eldarkk** [comment]
> @eldarkk I think you are confusing android to ios. For android, what you say is true, but iOS, without notification, you don't receive anything.

It works only for Silent IOS pushes. (Without showing on display, Silent Message, waking up app)

**Comment by bobyuloffice** [comment]
@eldarkk if you send it without notificaton, does it trigger your background message handler? because I just tried it and still got nothing.

**Comment by eldarkk** [comment]
> @eldarkk if you send it without notificaton, does it trigger your background message handler? because I just tried it and still got nothing.

i havent tried 8.0.0 version. im still on 7.0.3, on which backgroundMessageHandler doesnt work at all on ios.

**Comment by bobyuloffice** [comment]
I've tried many variations but for `firebase_messaging: 8.0.0-dev.14`, if I don't have `notification`, I don't receive anything (even `onMessage` does not work without `notification` in my payload). 

Here's my payload:
```

message = {
    "notification": {
        "title": "hello",
        "body": "world"
    },
    "priority": "high",
    "content_available": True,
    "data": {
         "item1": {...},
         "item2": {...}
     }
}

```
I'm using aws lambda with boto3 (i.e. python3) and this is how I publish it:

```
sns_client.publish(
    TargetArn = <user endpoint>,
    MessageStructure='json',
    Message=json.dumps({
        "GCM": json.dumps(message)
    })
)
```

**Comment by eldarkk** [comment]
> I've tried many variations but for `firebase_messaging: 8.0.0-dev.14`, if I don't have `notification`, I don't receive anything (even `onMessage` does not work without `notification` in my payload) on ios (android works just fine).
> 
> Here's my payload:
> 
> ```
> 
> message = {
>     "notification": {
>         "title": "hello",
>         "body": "world"
>     },
>     "priority": "high",
>     "content_available": True,
>     "data": {
>          "item1": {...},
>          "item2": {...}
>      }
> }
> ```
> 
> I'm using aws lambda with boto3 (i.e. python3) and this is how I publish it:
> 
> ```
> sns_client.publish(
>     TargetArn = <user endpoint>,
>     MessageStructure='json',
>     Message=json.dumps({
>         "GCM": json.dumps(message)
>     })
> )
> ```

From my knowledge, **onMessage**, **onLaunch**, **onResume** handlers does work with regular push payload (like u have shown in 1st message) when push notification is shown or tapped by user.. But **onBackgroundMessage** handler doesnt get fired from regular push payloads (**!!!**). Its being called only in case of push payload contains **"content_available": true,** (and probably doesnt contain "notification" part)

**Comment by bobyuloffice** [comment]
@eldarkk  Are you saying the current stable version of firebase messaging (`firebase_messaging:7.0.0`) can handle backgroundmessage on ios devices if you send it with `content_available=true`? Is yours working?

**Comment by eldarkk** [comment]
> @eldarkk Are you saying the current stable version of firebase messaging (`firebase_messaging:7.0.0`) can handle backgroundmessage on ios devices if you send it with `content_available=true`? Is yours working?

on stable it doesnt work at all.

**Comment by bobyuloffice** [comment]
After days of trial and error, I have finally fixed it!!!!!!!!! I had to add `content_available` inside `notification`. For those using aws sns to push notifications, here is my payload:

```
{
  "GCM": "{ \"notification\": {\"title\": \"hello\", \"body\": \"world\", \"badge\": \"5\", \"content_available\": true}, \"priority\": \"high\",  \"data\": {\"time_to_live\": 3600, \"collapse_key\": \"deals\"}}"
}
```
