### ISSUE TITLE
🐛 cloud_firestore Query

### ISSUE THREAD

**Issue by 3rsin3rgul** [FirebaseExtended/flutterfire#4759]
Hello I am trying to make this query
```dart
FirebaseFirestore.instance.collection('ads')
            .where('state', isEqualTo: 1)
            .where('land', isEqualTo: widget.userModel.land)
            .where('choice', isEqualTo: widget.userModel.choice)
            .where('type', isEqualTo: widget.userModel.type)
            .where('price', isGreaterThan: widget.userModel.minimumPrice)
            .where('price', isLessThan: widget.userModel.maximumPrice)
            .where('userId', isNotEqualTo: widget.userModel.uid)
            .orderBy('createdDate', descending: false).limit(10);
```

But I am getting this response as error:
```
'package:cloud_firestore/src/query.dart': Failed assertion: line 254 pos 18:
'field == orders[0][0]': The initial orderBy() field '[[FieldPath([createdDate]), false]][0][0]' has
to be the same as the where() field parameter 'FieldPath([price])' when an inequality operator is
invoked.
```

Is there any way to handle this kinda query ?

**Comment by Dror88** [comment]
Your query has a couple of issues, you can't run it with firestore. From the docs:

> If you include a filter with a range comparison (<, <=, >, >=), your first ordering must be on the same field [[1]](https://firebase.google.com/docs/firestore/query-data/order-limit-data#limitations)

> In a compound query, range (<, <=, >, >=) and not equals (!=) comparisons must all filter on the same field. [[2]](https://firebase.google.com/docs/firestore/query-data/queries#query_limitations)

**Comment by russellwheatley** [comment]
Your query is failing validation. As @Dror88 has illustrated, you need to perform compound queries on the same property.
