### ISSUE TITLE
🐛 [firebase_analytics] missing macos platform plugin

### ISSUE THREAD

**Issue by ekuleshov** [FirebaseExtended/flutterfire#4766]
The documentation page says macos is supported https://github.com/FirebaseExtended/flutterfire#firebase_analytics

But there is no macos platform implementation available anywhere.

**Comment by Krunal3909** [comment]
Can I work on this issue?

**Comment by rrousselGit** [comment]
Sorry for not answering @Krunal3909!

In general, if you want to work on something, raising a PR is the simplest. We would be glad to review them!
