### ISSUE TITLE
firebase_auth 0.6.7 doesn't exist

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#477]
The changelog was updated to include a 0.6.7 version in flutter/plugins#775, but the `pubspec.yaml` was never updated to match so no 0.6.7 version can ever be published onto pub. `0.6.7` and `0.7.0` should probably be combined in `CHANGELOG.md`.

/cc @collinjackson

**Comment by kroikie** [comment]
@mklim

The issue at https://github.com/flutter/flutter/issues/27247 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi 
I noticed several merged PR in the an [issue ](https://github.com/flutter/flutter/issues/27258)
related to your initial issue.
Is this issue still actual or needs to be closed?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
