### ISSUE TITLE
🐛 [In App Messaging] Module 'firebase_in_app_messaging' not found

### ISSUE THREAD

**Issue by bpfeiffer187** [FirebaseExtended/flutterfire#4770]
## Bug report

**Describe the bug**
after implementing the in app messaging plugin in pubSpec.yaml xcode is tossing the following error.
![image](https://user-images.githubusercontent.com/37454342/105503952-312f5480-5c95-11eb-9c70-0655189d15c3.png)

### Steps to reproduce

1. Go to pubSpec.yaml
2. 
![image](https://user-images.githubusercontent.com/37454342/105504020-473d1500-5c95-11eb-925e-45a5c5929ad3.png)

2. xCode-clean build folder
4. ![image](https://user-images.githubusercontent.com/37454342/105503952-312f5480-5c95-11eb-9c70-0655189d15c3.png)

### Expected behavior

should build and load on device

---

## Additional context

i do get this from the output in error if i run from vsCode
Error output from Xcode build:
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORRegistrar.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORStorageEventSelector.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORPlatform.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORStorageProtocol.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORUploader.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORAssert.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORLifecycle.h' [-Werror,-Wincomplete-umbrella]
    <module-includes>:1:1: error: umbrella header for module 'GoogleDataTransport' does not include header 'GDTCORReachability.h' [-Werror,-Wincomplete-umbrella]
    8 errors generated.
    /Users/a14226/amicaFlutterWorkSpace/amica-mobile-flutter/ios/Pods/FirebaseCoreDiagnostics/GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h:18:9: fatal error: could not build module 'GoogleDataTransport'
    <module-includes>:1:1: error: umbrella header for module 'GoogleUtilities' does not include header 'GULLoggerCodes.h' [-Werror,-Wincomplete-umbrella]
    1 error generated.
    10 errors generated.
Error launching application on iPhone 11.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @bpfeiffer187 
Could you try this https://stackoverflow.com/a/58543307/7007353?
Thank you

**Comment by bpfeiffer187** [comment]
thank you, tried that and still no go.

**Comment by bpfeiffer187** [comment]
FYI did get this fixed, need to run flutter clean, and delete my pod lock file manually.
