### ISSUE TITLE
🐛 [firebase_admob] Smart Banner height - higher than 90

### ISSUE THREAD

**Issue by EducatedDeer** [FirebaseExtended/flutterfire#4788]
## Bug report
I am using smart-banner ads and they are supposed to be 32-50-90 dp heights,
I am observing this issue second time on the Pre-Launch reports. Banner ad is so large, it is definately higher than 90 dp

Also I allocated a place for banners on the bottom you can see, I will add a normal behaving screenhot and others.

### Steps to reproduce

1. use smart banners
2. check pre-launch report screenshots
4. I saw this 2 times on the Russian devices from google

### Expected behavior
Smart banner highest ad height = 90 dp

### **Banner is not at the bottom as you see then a video comes at the second screenshot**

![11](https://user-images.githubusercontent.com/45289988/105573819-4c6f9200-5d71-11eb-84ac-bdb1950039f0.png)
![12](https://user-images.githubusercontent.com/45289988/105573825-55606380-5d71-11eb-94e6-5b120688b8ef.png)
![13](https://user-images.githubusercontent.com/45289988/105573862-73c65f00-5d71-11eb-99f2-1570413b74b1.png)

### **Normal behaving ad**

![10](https://user-images.githubusercontent.com/45289988/105573865-7cb73080-5d71-11eb-9e07-6f502d87de4c.png)

**Comment by markusaksli-nc** [comment]
Hi @EducatedDeer 
Are you just seeing reports of this or are you able to provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by EducatedDeer** [comment]
**I can't reproduce it because I can't control the ads served. 
Can this ad from the screenshot come from "size: AdSize.smartBanner" ?

It is working fine on Test Ads on my emulator, highest ad height is 90 on test ads.
I saw the same ad on the last 2 versions of the app on the pre-launch reports**

> 
**flutter doctor -v**

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 6.3.9600], )
    • Flutter version 1.22.5 at D:\Flutter SDK\flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\ANDROIDSDK\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\ANDROIDSDK\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • Samsung Galaxy Note 10 (mobile) • android-x86 • Android 9 (API 28)

• No issues found!
> 

> 

**flutter pub deps -- --style=compact**

Dart SDK 2.10.4
Flutter SDK 1.22.5

dependencies:
- audioplayers 0.17.2 [uuid path_provider flutter flutter_web_plugins]
- auto_size_text 2.1.0 [flutter]
- awesome_dialog 1.3.0 [flutter simple_animations flare_flutter]
- confetti 0.5.4+1 [flutter random_color vector_math]
- firebase_admob 0.10.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- i18n_extension 1.4.5 [sprintf args flutter]
- launch_review 2.0.0 [flutter]
- package_info 0.4.3+2 [flutter]
- provider 4.3.2+3 [collection flutter nested]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- step_progress_indicator 0.2.5+8 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- random_color 1.0.5 [flutter]
- sa_v1_migration 1.1.2 [flutter]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- simple_animations 2.4.2 [flutter supercharged sa_v1_migration pedantic]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sprintf 4.1.0
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
>

**Comment by markusaksli-nc** [comment]
Could you provide the code and setup you are using to load the smart banners?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
