### ISSUE TITLE
[firebase_auth] linkWithCredential uses current user instead of user object on which the function is called

### ISSUE THREAD

**Issue by jeanmatthieud** [FirebaseExtended/flutterfire#48]
I'm trying to manage the 'ERROR_CREDENTIAL_ALREADY_IN_USE' error when linking an account to another, by following the android guide: https://firebase.google.com/docs/auth/web/account-linking#link-email-address-and-password-credentials-to-a-user-account

In the last code section, when the credentials are already in use:
* User logged in with account [A], and submitted credentials [C]
* SignIn on the already existing account [B] with credentials [C]
* Retrieve app's data linked to account [B]
* Delete the existing account [B]
* Link user account [A] to the credentials [C] and SignIn with credentials [C]
* Import data of account [B] on the linked user

Ugly code:
```dart
AuthResult authResult;
final FirebaseUser previousUser = await FirebaseAuth.instance.currentUser();
try {
  authResult = await previousUser.linkWithCredential(credential);
} on PlatformException catch (err) {
  if (err.code == 'ERROR_CREDENTIAL_ALREADY_IN_USE') {
    // Signin to the existing account
    authResult = await FirebaseAuth.instance.signInWithCredential(credential);
    // TODO : Get data from the authResult.user account
    // Delete existing account
    // TODO : better deletion error management
    await authResult.user.delete();
    // Link previous user
    authResult = await previousUser.linkWithCredential(credential);
    // TODO : merge previous account data to current account
  } else {
    throw err;
  }
}
```

Sadly, calling `previousUser.linkWithCredential()` seems to use `firebaseAuth.getCurrentUser()` and not the user on which the call has been done, resulting into an `USER_REQUIRED` error.
See `FirebaseAuthPlugin.java:275`

**Comment by jeanmatthieud** [comment]
After digging the source code, I realized that the plugin always uses the currentUser linked to the FirebaseApp.
The workaround I found to manage more than one user is to create a secondary FirebaseApp, FirebaseAuth and FirebaseStore.

**This is far from ideal, and a call on a method of a FirebaseUser should not use the currentUser but the user on which the method has been called.**

```dart
AuthResult authResult;
final FirebaseUser previousUser = await FirebaseAuth.instance.currentUser();

final firebaseAppTemp = await FirebaseApp.configure(name: 'temporaryApp', options: await FirebaseAuth.instance.app.options);
final FirebaseAuth firebaseAuthTemp = FirebaseAuth.fromApp(firebaseAppTemp);
final Firestore firestoreTemp = Firestore(app: firebaseAppTemp);

try {
  authResult = await currentUser.linkWithCredential(credential);
} on PlatformException catch (err) {
  if (err.code == 'ERROR_CREDENTIAL_ALREADY_IN_USE') {
    // Signin to the existing account
    authResult = await firebaseAuthTemp.signInWithCredential(credential);
    // TODO : Data migration - NOW USING 'firestoreTemp'
    // Delete existing account
    // TODO : better deletion error management
    await authResult.user.delete();
    // Link previous user
    authResult = await previousUser.linkWithCredential(credential);
    // TODO : merge previous account data to current account - NOW USING 'firestoreTemp'
  } else {
    throw err;
  }
}
```

**Comment by Ehesp** [comment]
> This is far from ideal, and a call on a method of a FirebaseUser should not use the currentUser but the user on which the method has been called.

Unfortunately this isn't possible since Dart vs Native code can't keep track of different user instances.

That being said, work is being done to pass back an updated credential via the error as expected.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

Please could you update to the new version. If you have any problems with the updated plugins please raise a new GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
