### ISSUE TITLE
 [firebase_admob] Interstitial Ad not showing on emulator devices

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#480]
## Steps to Reproduce

I'm using `firebase_admob` for my apps, yesterday it works perfectly...the ads were showing in the emulator devices. But today, it's suddenly throw an error. Can you guys help me?

## Logs

```
E/flutter ( 5531): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5531): PlatformException(load_failed_ad, cannot reload a failed ad, id=461653319, null)
E/flutter ( 5531): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 5531): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter ( 5531): <asynchronous suspension>
E/flutter ( 5531): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:521:61)
E/flutter ( 5531): <asynchronous suspension>
E/flutter ( 5531): #3      InterstitialAd.load (package:firebase_admob/firebase_admob.dart:307:12)
E/flutter ( 5531): #4      _IntiyState.build.<anonymous closure> (package:subscribepewds/inti.dart:542:21)
E/flutter ( 5531): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 5531): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 5531): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 5531): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 5531): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter ( 5531): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 5531): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
E/flutter ( 5531): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 5531): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 5531): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 5531): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 5531): #16     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5531): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

**Comment by kroikie** [comment]
@haikalpe123

The issue at https://github.com/flutter/flutter/issues/27233 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @haikalpe123
Did the proposed [solution ](https://github.com/flutter/flutter/issues/27128#issuecomment-458274311)worked? 
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
