### ISSUE TITLE
🐛 [firebase_messaging 8.0.0 dev14] How to send scheduled notifications?

### ISSUE THREAD

**Issue by GilbertoGmobil** [FirebaseExtended/flutterfire#4811]
I'm sending now this request:
```
 '{"data": {"click_action": "FLUTTER_NOTIFICATION_CLICK"} ,"notification": {"body": "${body}", "title": "${title}", "sound": "default"}, "priority": "high", "to": "mytopic"}';
```

Can I, through some parameter schedule this notification to show only in a given day? for example, I want this notifications arrives in the user phones in 01/02. It is possible?

While searching I found this json:
```dart
{ 
 "to": "/topics/discount-offers", 
 "priority": "high",
 "data" : {
  "title" : "🎅 Christmas Offer 🎄",
  "message" : "Grab 90% Discount 😍 on Mobile Phones",
  "isScheduled" : "true",
  "scheduledTime" : "2019-12-13 14:12:00"
 }
}
```

So, I tried to copy "isScheduled" and "scheduledTime" in my project, but it doesn't work.. It continues delivering the message when I send. What can I do to show the notification only in the "scheduledTime"?

This is my json now:
```dart
'{"data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "isScheduled": "true","scheduledTime": "2021-01-26 12:20:00", "title" : "TITLE_HERE","message" : "MESSAGE_HERE",} ,"priority": "high", "to": "myopic"}';
```

*UPDATE

The notification have to be received in the date selected, in foreground, in background and when the user taps on it, it have to open a given screen.
At this moment I'm receiving in foreground, background and redirecting to a given page, BUT, it receives when the message is sent through POST... Have to be delivered in the 'scheduledTime' date/time

**Comment by markusaksli-nc** [comment]
Hi @GilbertoGmobil 
There is no way to schedule a notification through the API. You can only schedule it using Firebase Console, in your own Node.js server, or using a Cloud Function.

I'm guessing [this](https://medium.com/mindorks/scheduling-fcm-push-notifications-on-device-android-2d3bb9653b4d) is the guide you were looking at, in which case the full solution entails a number of other steps:

> * We’ll send Data payload with scheduling information to the FCM topic.
> * Process received notification in a device, Schedule it using `AlarmManager`.
> * At the Scheduled time, create `WorkManager` for background processing and display notification on the system tray.

You can try to implement a similar background scheduling and handling solution in Flutter, schedule it through the Firebase Console GUI, or just work on your own serverside solution.

For how to get started sending notifications using Node take a look at https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877.
Thank you
