### ISSUE TITLE
FATAL EXCEPTION: Firebase-Messaging-Intent-Handle

### ISSUE THREAD

**Issue by kecson** [FirebaseExtended/flutterfire#4812]
firebase_messaging: ^7.0.3

Public to Google play was rejected, and the feedback reported an error:

01-25 18:49:58.993: E/AndroidRuntime(11990): FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
01-25 18:49:58.993: E/AndroidRuntime(11990): Process: com.google.android.youtube, PID: 11990
01-25 18:49:58.993: E/AndroidRuntime(11990): java.lang.NoClassDefFoundError: aewt
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at aewu.b(PG:1)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.a(PG:230)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.get(PG:247)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at aevw.b(PG:1)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at dud.al(PG:5)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at dud.aw(PG:4)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at dud.bg(PG:8)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.a(PG:232)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.get(PG:247)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at afke.a(PG:1)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at aeri.b(PG:1)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at dud.fv(PG:4)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.c(PG:269)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.get(PG:247)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at amfk.a(PG:1)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at eiu.K(PG:5)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at dud.fV(PG:7)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.d(PG:334)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at duc.get(PG:247)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at avgp.run(Unknown Source)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at usj.run(PG:2)
01-25 18:49:58.993: E/AndroidRuntime(11990): 	at java.lang.Thread.run(Thread.java:831)

**Comment by markusaksli-nc** [comment]
Hi @kecson 
Please see https://stackoverflow.com/a/64839467/7007353.
Closing since this is not an issue with the plugin itself.
Thank you

**Comment by kecson** [comment]
> Hi @kecson
> Please see https://stackoverflow.com/a/64839467/7007353.
> Closing since this is not an issue with the plugin itself.
> Thank you

Ok.
