### ISSUE TITLE
🐛 [firebase_storage] Why cant I get the files inside my folders in Firebase Storage

### ISSUE THREAD

**Issue by GilbertoGmobil** [FirebaseExtended/flutterfire#4843]
I'm using Firebase Storage with this structure within:

Photos
-MyPhotos
--photo1.png
--photo2.png

With this code:
```dart
  Future<ListResult> loadLab() async {
    var result = await _storage.ref().child('Photos/').listAll();

    result.prefixes.forEach((Reference ref) {
      print('Found directory: $ref');

    });
    result.items.forEach((Reference ref) {
      print('Found file: $ref');
    });
    return Future.value(result);
  }
``` 

But my return is, "Found directory: Reference(app: [DEFAULT], fullPath: Photos/MyPhotos)"... Why it don't return my items inside myPhotos too? How can I do it?

**Comment by Nandan-Wewhare** [comment]
This is because it returns a Reference object and by accessing its 'fullPath' property you will have to first get the full path to MyPhotos folder and then use the listAll() method on that full path.
