### ISSUE TITLE
Firebase PhoneAuth - signInWithCredential returns null reference

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#485]
I have updated to `firebase_auth: ^0.8.0+1` and some other google related dependencies today.
Lots of breaking changes, like it was told in the changelogs. To solve that I did:
- migrated my Flutter project to AndroidX
- replaced `signInWithPhoneNumber`, which is not available anymore,  with the new methode using the `AuthCredential`

Now I facing a new issue. I do the following request.
```dart
FirebaseUser user;
final AuthCredential credential = PhoneAuthProvider.getCredential(
  verificationId: _verificationId,
  smsCode: _smsCode,
);
try {
  user = await _auth.signInWithCredential(credential);
} catch (e) {
  print(e.message);
}
```
`signInWithCredential` returns an error with the message 
```
null reference
```
It happens always when I try to signup with a test number as well with a real number.
The strangest thing is, when I am using a real number, that after stopping the app and restart debugging it, I get a `FirebaseUser` from my `onAuthStateChanged` listener. No clue why. Please help!!

Here is the log from the debug console:

```
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): java.lang.NullPointerException: null reference
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.google.firebase.auth.FirebaseAuth.signInWithCredential(Unknown Source:137)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:398)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:107)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.app.ActivityThread.main(ActivityThread.java:7470)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**UPDATE**
I have modified my code to 
```
user = await _auth.signInWithCredential(credential);
user = await _state.auth.currentUser();
```
Still, if I am using a test number I get **null reference** twice.
If I am using a real number I get **null reference** from `auth.signInWithCredential(credential)`
But `state.auth.currentUser();` returns a valid `FirebaseUser`

**Comment by AyushRai3096** [comment]
Has this issue been resolved ?
I'm facing this issue and tried many different things as discussed on this platform. But still I'm facing the same issue.
The signInWithCredential() is not working and returning an error which says: 
PlatformException(error, null reference, null)
If anybody has a fix, please provide it here.
Thanks.
