### ISSUE TITLE
🐛 [firebase_remote_config dev] Rename class name RemoteConfig to FirebaseRemoteConfig to match documentation

### ISSUE THREAD

**Issue by snorreks** [FirebaseExtended/flutterfire#4853]
## Bug report

**Describe the bug**
The version firebase_remote_config: ^0.8.0-dev.0, has the old classname RemoteConfig instead of FirebaseRemoteConfig that it says in the documentation.

**Comment by markusaksli-nc** [comment]
I can't even get past the version solving for `0.8.0-dev.0` yet. But I guess this is enough to show that the issue exists.

https://github.com/FirebaseExtended/flutterfire/blob/5fddc966a12d98cbe958ac03cddc93d4c99e5afe/packages/firebase_remote_config/firebase_remote_config/lib/src/remote_config.dart#L13

Documentation:
```dart
FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.instance;
```

**Comment by russellwheatley** [comment]
Flutterfire documentation demonstrates `RemoteConfig` API usage [here](https://firebase.flutter.dev/docs/remote-config/usage).
