### ISSUE TITLE
🐛 [Firebase Storage] firebase storage 7.0.0 requires firebase core 0.7.0 (Flutter Dev Channel)

### ISSUE THREAD

**Issue by godfreycomputing** [FirebaseExtended/flutterfire#4858]
## Bug report

**Describe the bug**
Flutter version 1.26.0-12.0.pre requires firebase core 0.8.0-nullsafety.1 and firebase storage requires 7.0.0 requires firebase core 0.7.0.  There is a version mismatch causing pub get to fail.

### Steps to reproduce

1. Switch to flutter dev channel
2. run flutter upgrade
3. download firebase core ^0.8.0-nullsafety.1 for dependency match
4. download firebase storage 7.0.0 (Latest version on Pub.dev.  No dev version exists)
5. run flutter pub get

### Expected behavior

flutter pub get should run without errors.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel dev, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-12.0.pre at C:\Development\flutter_sdk\flutter
    • Framework revision a706cd2112 (2 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\godfr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PThe pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @godfreycomputing 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4855.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
