### ISSUE TITLE
🐛 [firebase_auth] Crash on FirebaseAuth.verifyPhoneNumber

### ISSUE THREAD

**Issue by nashnub** [FirebaseExtended/flutterfire#4874]
## Bug report

**Describe the bug**
Crash after a while on FirebaseAuth.verifyPhoneNumber function execution.
There is a crash on firebase_auth version 0.20.0+1.
There is no crash on firebase_auth version 0.18.4+1.

### Steps to reproduce

1. FirebaseAuth.verifyPhoneNumber function

### Expected behavior

No crash

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @nashnub 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4651.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
