### ISSUE TITLE
[Firebase ML Kit] Strange value always read

### ISSUE THREAD

**Issue by svprdga** [FirebaseExtended/flutterfire#4876]
It doesn't matter where I point the camera, version 0.10.0 of firebase_ml_vision is always reading a strange value:

`Value type: BarcodeValueType.text`
`Raw value: {"typeNumber": "0", "errorCode": "3", "version": "242"}`

Why does this happen? As I said, as soon as I start the camera this value is scanned from nowhere...

**Comment by markusaksli-nc** [comment]
Hi @svprdga 
Please open a new issue regarding this and fill out the entire template.
Thank you
