### ISSUE TITLE
firebasecore and firebasefirestore error in flutter android🐛 [FirebaseFirestore&Firebase Core] Your issue title here

### ISSUE THREAD

**Issue by alihassan143** [FirebaseExtended/flutterfire#4883]
Note: C:\Users\aliha\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\aliha\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by maherelamary** [comment]
run flutter clean
flutter build cache repair 
flutter pub upgrade 
flutter pub get 
flutter clean and run you code

**Comment by markusaksli-nc** [comment]
Hi @alihassan143 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/3876.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
