### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by k0302** [FirebaseExtended/flutterfire#4886]
I am using cloud functions to send 2 kinds of notifications to users. First kind of notification is triggered on event A , and the second kind of notification on event B. My problem is that I want to redirect users to page A on event A notification click, and to page B on event B notification click, but my app opens as it closes the last time on any notification click, not distinguishing between the 2 pages. Please tell me how to redirect to 2 different pages on 2 different kinds of notification click.
Here is my cloud functions code for message on event A;
 
      const message = {
      "notification": {
      title: ..,
      body: ..
       }, 
        "data": {click_action: "FLUTTER_NOTIFICATION_CLICK"},
        token: token};
Here is my cloud functions code for message on event B;

       const message = {
      "notification": {
      title: ..,
      body: ..
       }, 
        "data": {click_action: "FLUTTER_NOTIFICATION_CLICK", screen: "PageB"},
      token: token};

Here is my `firebasemessaging.configure` code in flutter `main.dart` file.

      @override
      void initState() {
      firebaseMessaging.configure(
        onMessage: (Map<String, dynamic> message) async {
      
      final dynamic data = message["data"];
      if (data["screen"].toString() == "PageB") {
        Navigator.push(...(context) => PageB())); //MY navigator method to page B
      } else {
        Navigator.push(...(context) => PageA())); //my navigator method for Page A 
      }
      }, 
      onResume: (Map<String, dynamic> message) async {
                  //same as above
      }, 
      onLaunch: (Map<String, dynamic> message) async {
                 //same as above
      }
      });
      super.initState();
      }

**Comment by markusaksli-nc** [comment]
Hi @k0302 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Would you be able to create a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to demonstrate the issue?
Thank you

**Comment by Ehesp** [comment]
Please create a new issue following the template @k0302 - there is no title or any information pointing to what versions of anything you're running making it impossible to debug. Thanks.
