### ISSUE TITLE
🐛 [firebase_messaging 7.0.3] Broken Application.java types

### ISSUE THREAD

**Issue by kari538** [FirebaseExtended/flutterfire#4887]
## Bug report

The app refuses to build, using the resources provided in the package documentation. The error message is: 

>/path/Application.java:23: error: incompatible types: PluginRegistry cannot be converted to FlutterEngine
>        GeneratedPluginRegistrant.registerWith(registry);"

This seems to refer to this line in the Application.java file provided by the package docs:

```
    @Override
    public void registerWith(PluginRegistry registry) { 
        GeneratedPluginRegistrant.registerWith(registry);
    }
```

Following a suggestion by Android Studio, I tried to cast "registry" to FlutterEngine type:

```
    @Override
    public void registerWith(PluginRegistry registry) { 
        GeneratedPluginRegistrant.registerWith((FlutterEngine) registry);
    }
```

Now, the app builds, and it shows a token on the screen. But it crashes when receiving a Firebase Cloud Message from the Firebase console. The new error msg is: 

>E/AndroidRuntime(27272): FATAL EXCEPTION: main
>E/AndroidRuntime(27272): Process: <package_name>, PID: 27272
>E/AndroidRuntime(27272): java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: <b><r>java.lang.ClassCastException: io.flutter.app.FlutterPluginRegistry cannot be cast to io.flutter.embedding.engine.FlutterEngine</b></r>

Seems my cast attempt wasn't very popular... I can't get past this.

### Steps to reproduce

Using Android Studio:

1. Follow the instructions on the package readme page. Including:
  a. Registering a Firebase app on firebase.google.com and adding google-services.json file from there to project
  b. Making all the suggested changes to both gradle.build files, pubspec file and AndroidManifest file
  c. Creating the Application.java file suggested in the same location as MainActivity.java
  d. etc, etc...
2. Copy-paste Example code into main file
4. Run

---

## Additional context

A very weird thing about it is that it actually worked for a while this morning... I have no idea how that happened! But it did, I received notification messages, clicked on them and was navigated to the app...

I've been updating Flutter and Gradle in an attempt to make this work. Maybe that has something to do with it... I dunno! Although I can't recall making any upgrades between when it worked and when it stopped working again...

The only thing I do remember doing in that time was to run my normal main file in the same project. Because I already had a Firebase app, so I just made a new main file in that project where I put the Example code to run separately. So now, I ran my normal main file where the messaging functionality was only partially implemented. Then I sent myself a message from the Console and the app crashed. I thought this was quite normal, given that I wasn't done with implementing the messaging stuff!...

But then, I ran the Example main again, and sent myself another message. Now, even that version crashed, and since then, it has been as described above.

My current versions:

```
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (9 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

------------------------------------------------------------
Gradle 6.8.1
------------------------------------------------------------

Build time:   2021-01-22 13:20:08 UTC
Revision:     31f14a87d93945024ab7a78de84102a3400fa5b2

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
OS:           Windows 10 10.0 amd64
```

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18362.1082], locale sv-SE)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 3 categories.
```

</details>

(This is obviously nonsense, since I'm using both Dart and Flutter... but it has been like this since an Android Studio upgrade and it doesn't affect the performance so I'm leaving it.)

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
my_giggz 1.0.0+1

dependencies:
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_w
eb]
- cupertino_icons 0.1.3
- dio 3.0.10 [http_parser path]
- firebase_auth 0.18.4 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 3.0.2 [flutter platform flutter_local_notifications_platform_interface timezone]
- modal_progress_hud 0.1.3 [flutter]
- navigation_history_observer 1.0.3+1 [flutter built_collection]
- rflutter_alert 1.1.0 [flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matche
r meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- built_collection 4.3.2 [collection quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js
]
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface j
s]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matc
her]
- timezone 0.5.9 [path]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

**Comment by kari538** [comment]
Ok, somebody gave me the tip to try this:

https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Will see how it goes...

**Comment by zhangyc** [comment]
but ,it is not solved...i had this problem also

**Comment by zhangyc** [comment]
> Fixed it! 🙂
> 
> @lucianoiam gave me the tip to try this:
> 
> https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
> 
> Following instructions in that link (which were for MainActivity.java but I figured it could work for Application.java too), I altered my Application.java file from the package docs to look like this:
> 
> ```dart
> package  <package_name>;
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterActivity;
> import io.flutter.embedding.engine.FlutterEngine;
> import io.flutter.plugin.common.MethodChannel;
> import io.flutter.plugins.GeneratedPluginRegistrant;
> 
> public class Application extends FlutterActivity{   //from https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
>     private static final String CHANNEL = "samples.flutter.dev/battery";
> 
> //original from firebase_messaging:
> //public class Application extends FlutterApplication implements PluginRegistrantCallback {
> //    @Override
> //    public void onCreate() {
> //        super.onCreate();
> //        FlutterFirebaseMessagingService.setPluginRegistrant(this);
> //    }
> //    @Override
> //    public void registerWith(PluginRegistry registry) { //original
> ////    public void registerWith(FlutterEngine registry) {
> ////        GeneratedPluginRegistrant.registerWith(registry);   //original
> //        GeneratedPluginRegistrant.registerWith((FlutterEngine) registry);
> //    }
> 
>     @Override
>     public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>         new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
>                 .setMethodCallHandler(
>                         (call, result) -> {
>                             // Your existing code
>                         }
>                 );
>     }
> 
> }
> ```
> 
> (The MainActivity.java file already looked like suggested in that link.)
> 
> Then, according to the same instructions, in AndroidManifest.xml I changed the:
> 
> ```
>     <application
>         android:name=".Application"
>         .../>
> ```
> 
> to:
> 
> ```
>     <application
>         .../>
> ```
> 
> (Just removing the name line.)
> 
> And now it works again! 😃 Though it doesn't navigate... but I'll figure that out. At least it doesn't crash anymore!
> 
> Thanks a lot! 😊
  use it
    FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));

**Comment by kari538** [comment]
> but ,it is not solved...i had this problem also

Did you change the Application.java file and AndroidManifest.xml files exactly as I described above?

You may have to restart your IDE...

**Comment by kari538** [comment]
The remaining problem now is that the phone doesn't receive notifications if the app is terminated... 😒 And the package docs say it should. (Not data msgs but notifications.)

Quite an important feature of a push msg!!...

**Comment by markusaksli-nc** [comment]
Hi @kari538 
Would you please consider upgrading to the latest non-nullsafety version of the plugin `firebase_messaging: ^8.0.0-dev.14`? This whole workaround is no longer necessary on it and it is a lot more stable in general.
Thank you

**Comment by kari538** [comment]
So what would upgrading to `firebase_messaging: ^8.0.0-dev.14` give me, exactly?

And what does it require?

If it's as simple as just downloading that version with `pub get` and then everything works the way it should, then yeah, that sounds nice indeed!... 🙂

But if it means I now need to upgrade a whole lot of other firebase packages, and in the end I'll need to venture into an unstable version of Dart to make it work... 😒 then I think I'd rather wait for your next stable release.

So which way is it?

**Comment by markusaksli-nc** [comment]
Well there have been a lot of breaking changes to the codebase so you would need to implement those according to https://firebase.flutter.dev/docs/migration#messaging. Since the previous versions of the FF packages are incompatible with the new ones due to an update in the underlying iOS SDK constraint you would need to update your other FF packages as well.

You would not need to use any unstable dart version or anything like that. You just need to do some refactoring and take a look at the new official example for how to use the plugin. The upside is as I mentioned that it is a lot more stable and all native code workarounds are no longer necessary.

I've seen multiple issues like this get resolved just by upgrading to the new version. The new installation guide is athttps://firebase.flutter.dev/docs/messaging/overview

**Comment by kari538** [comment]
Ok, thanks for that very clarifying answer! 🙂 I'll give it a try and see how it goes.

**Comment by markusaksli-nc** [comment]
Yeah thats just another side effect of the fix to https://github.com/FirebaseExtended/flutterfire/issues/4885 

That can actually be considered a documentation bug since I'm pretty sure

> If you are using Flutter Android Embedding V2 (Flutter Version >= 1.12) then no additional integration steps are required for Android.

isn't true for `7.0.3`.

**Comment by kari538** [comment]
Yeah, it's not working...

So, if there are no additional integration steps required, does that mean I should delete my Application.java file, etc...?
