### ISSUE TITLE
FCM message formats are different on ios and android

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#4890]
Two messages formatted the exact same way on my server back end, arrive on ios and android with different format.

Ideally format would consistent across platforms with a proper abstraction layer implemented....

Android:
`{notification: {body: Hi! This is the body!, title: Cool Title!}, data: {identifier: newMove, uid: 1, click_action: FLUTTER_NOTIFICATION_CLICK, optionalParam: 20}}
`
iOS
`{from: 876172905429, uid: 2, notification: {title: Cool Title!, e: 1, body: Hi! This is the body!}, collapse_key: com.me.myapp, identifier: newMove, optionalParam: 20, click_action: FLUTTER_NOTIFICATION_CLICK}: `

**Comment by markusaksli-nc** [comment]
Hi @safield 
This repository only wraps the upstream native Firebase SDKs. We do not control how the implementation interprets the message downstream. There is a fundamental difference in how the messages are delivered to each platform (for example the Firebase Cloud Messaging APNs interface uses the Apple Push Notification service (APNs) to send notifications to iOS).

Do you have any specific issue with accessing the notification payload content within dart code or is this just about the format?
Thank you

**Comment by Ehesp** [comment]
@safield Can you please create a new issue following the template so we can help.

There is a new version out which totally overhauls how incoming messages are treated on all platforms.
