### ISSUE TITLE
🐛 [cloud_firestore] set document method update wrong field when trying to update value in map

### ISSUE THREAD

**Issue by kithe-raker** [FirebaseExtended/flutterfire#4892]
I have used `set` method to update the value in `map` which is the a field in document, and I have found that the value in that 
`map` wasn't update. Instead the field `map.key` was created.

```dart
       await FirebaseFirestore.instance
                        .collection('Test')
                        .doc('testing')
                        .set({'map.first': FieldValue.increment(2)},
                            SetOptions(merge: true));
```
expectation
<img width="519" alt="ภาพหน้าจอ 2564-02-01 เวลา 15 09 48" src="https://user-images.githubusercontent.com/54874488/106431233-8a6e6380-649f-11eb-86e3-cd2b065f0cae.png">

what I've got
<img width="519" alt="ภาพหน้าจอ 2564-02-01 เวลา 15 10 31" src="https://user-images.githubusercontent.com/54874488/106431299-a40fab00-649f-11eb-97b7-f41b38a11abd.png">

**Comment by markusaksli-nc** [comment]
Hi @kithe-raker 
Is there any documentation that states that this should work? Why not just use this?
```dart
  await FirebaseFirestore.instance
      .collection('Test')
      .doc('testing')
      .set({'map':{'first': FieldValue.increment(2)}}
      , SetOptions(merge: true));
```
Thank you

**Comment by kithe-raker** [comment]
@markusaksli-nc Thank for response.
I've found that `map.key` long time ago in some of firebase youtube video, so I can't remember.
but if I use `update` instead, it works fine.
```dart
 await FirebaseFirestore.instance
                    .collection('Test')
                    .doc('testing')
                    .update({'map.first': FieldValue.increment(2)});
```

however your solution seem to be better. forget to think about that, sorry.

**Comment by Salakar** [comment]
As far as I know, dot notation for fields is only supported on `update()` and not `set()`, @Ehesp just tried it on the official Firebase JS SDK and got the same behaviour we're seeing here. 

The solution provided by @markusaksli-nc is the correct way as far as I know to set nested fields without replacing whole maps, using `SetOptions(merge: true)`.

**Comment by kithe-raker** [comment]
@Salakar Ok. Thank for explain. My bad gonna close this issue now.
