### ISSUE TITLE
🐛 [firebase_messaging] App crashes when receiving message under certain circumstances

### ISSUE THREAD

**Issue by tusharnikam-htp** [FirebaseExtended/flutterfire#4896]
## Bug report

**Describe the bug**
App crashes when trying to receive a FCM message after the app has been killed using Android's task manager.
The message reaches the device but the app seems unable to restart. Sending a message to the app in the "killed" state generates the following lines in logcat:

### Steps to reproduce

  Check notifications are properly working while the app is running
  Kill the app using the swipe up gesture in the task list
  Send a FCM to the app

#### This should not appear in logcat:

![terminal log](https://i.ibb.co/YQcZwVH/log.png)

## Additional context

When I sent notification from Firebase Console app close and this type of error was shown

![After notification sent](https://i.ibb.co/8xhf3s8/firebase-fcm.jpg)

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B29 darwin-arm, locale en-IN)
    • Flutter version 1.22.6 at /Users/htpapp1/tools/flutter
    • Framework revision 9b2d32b605 (10 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/htpapp1/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • SM A505F (mobile) • RZ8M71JQ7PM • android-arm64 • Android 10 (API 29)
```

</details>

### Flutter dependencies

![Source code ](https://i.ibb.co/bg3mkyp/code.png)

**Comment by markusaksli-nc** [comment]
Hi @tusharnikam-htp 
First off please refrain from posting screenshots, we can't copy the text and it makes finding the issue impossible for anyone facing the same problem.

Secondly please consider upgrading to the latest version `firebase_messaging: ^8.0.0-dev.14`. There have been major stability improvements and the native code workarounds are no longer necessary. The version you are using will be replaced soon and it is likely the cause of the issue.

Upgrading to the latest version of firebase messaging will also mean you will need to upgrade all of your firebase plugins, as the new versions are incompatible with the old ones (see https://firebase.flutter.dev/docs/migration). Beware that the nullsafety versions aren't fully supported yet so I don't recommend you use them.

If you are still facing this issue on the latest version you can provide your 
`flutter pub deps -- --style=compact` and error logs.
Thank you

**Comment by tusharnikam-htp** [comment]
@markusaksli-nc  I update the all package and follow [FlutterFire](http://firebase.flutter.dev/) and the issue will be resolved :) 


As of now I am closing this issue
