### ISSUE TITLE
[cloud_firestore] Need id generator like createId() function in AngularFire

### ISSUE THREAD

**Issue by eugvb** [FirebaseExtended/flutterfire#49]
In some cases I need generate id before store document in firestore.
In AngularFire there is function `createId()`
In Flutter I can `import 'package:cloud_firestore/src/utils/auto_id_generator.dart'` (since 0.12.8, push_id_generator before)
and then use `AutoIdGenerator.autoId()`
But it's not true way, because I should import implementation files from another package.

**Comment by cmkweber** [comment]
CollectionReference has an **add** method which returns an auto-generated ID:

[https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/CollectionReference/add.html](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/CollectionReference/add.html)

**Comment by eugvb** [comment]
Maybe it is not perfect way, but I persist Document Id inside it. So I need generate id before calling `add()` method.

**Comment by Kretin1** [comment]
I use: 
    String id = reference.document().documentID;

Then apply the id within the document and any other documents, then save.

**Comment by eugvb** [comment]
Ok, storing Document Id in itself not good practice. So in this case no need for id generation.

But what about transaction or batch writes?
For example, I want to add document to collection and then store it Id in other document
```
Firestore.instance.runTransaction((tx) async {
  String docId = 'docId';//It should be generated
  await tx.set(Firestore.instance.collection('collection').document(docId), {'some':'data'});
  //There i need docId to store it in other Document
  await tx.set(Firestore.instance.collection('collection2').document('DocumentId2'), {'docId':docId});
});
```
`Transaction` doesn't have `add` method, so I need use `set` with generated id.
With Batch write situation is similar.

**Comment by cmkweber** [comment]
Use document without passing a path:
[https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/CollectionReference/document.html](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/CollectionReference/document.html)
This generates a unique id without setting it within database like add does.

**Comment by eugvb** [comment]
It is solution, thank you

**Comment by sultanmyrza** [comment]
I know its late but here is what I did

```
String randomId() {
    var _randomId = Firestore.instance.collection('').document().documentID;
    print(randomId());
    return _randomId;
}
```

**Comment by Limitless-Kode** [comment]
> I know its late but here is what I did
> 
> ```
> String randomId() {
>     var _randomId = Firestore.instance.collection('').document().documentID;
>     print(randomId());
>     return _randomId;
> }
> ```

Can this produce a unique ID. I am thinking it would somehow create an ID that already exists.

**Comment by cmkweber** [comment]
They are unique: [https://stackoverflow.com/questions/46618719/firestore-are-ids-unique-in-the-collection-or-globally](https://stackoverflow.com/questions/46618719/firestore-are-ids-unique-in-the-collection-or-globally)

**Comment by Gintasz** [comment]
> I know its late but here is what I did
> 
> ```
> String randomId() {
>     var _randomId = Firestore.instance.collection('').document().documentID;
>     print(randomId());
>     return _randomId;
> }
> ```

Doesn't work on web at the present moment (cloud_firestore: 0.13.7), getting this error:
Function Firestore.collection() requires its first argument to be of type non-empty string, but it was: ""
