### ISSUE TITLE
@markusaksli-nc  Dependedncies issue

### ISSUE THREAD

**Issue by faraax-oct** [FirebaseExtended/flutterfire#4913]
@markusaksli-nc 

**_Pubspec.yaml_**
name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

I still cant use few dependencies like firebase user
![Capture1](https://user-images.githubusercontent.com/76065391/106592116-1bfbd500-6575-11eb-8b06-c5cfa4f0ab0f.PNG)

_Originally posted by @faraax-oct in https://github.com/FirebaseExtended/flutterfire/issues/4875#issuecomment-771559199_

**Comment by markusaksli-nc** [comment]
You don't need to open a separate issue for this
