### ISSUE TITLE
[firebase_admob] check if rewarded video is loading

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#492]
Using flutter and this plugin (https://pub.dartlang.org/packages/firebase_admob),

**How can I check if the Rewarded video is load?** 

I received this Exception :

`PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)`

I can not find methods to check if the video is loaded.

Thank you.

**Comment by kroikie** [comment]
@Jhon2524

The issue at https://github.com/flutter/flutter/issues/26971 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @Jhon2524
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
