### ISSUE TITLE
Upgrade Plugin

### ISSUE THREAD

**Issue by dunganh23121995** [FirebaseExtended/flutterfire#4920]
Hello. Now, the Flutter framework upgrades 1.22.x. In the Application.java not import "import io.flutter.app.FlutterApplication;", replace that is "import io.flutter.embedding.android.FlutterActivity;". That is not Override onCreate(). I think you need to update for the newest version. Thanks.

**Comment by markusaksli-nc** [comment]
This is no longer relevant for the latest version of firebase messaging anyway. https://pub.dev/packages/firebase_messaging/versions/9.0.0-1.0.nullsafety.0
