### ISSUE TITLE
🐛 [firebase_messaging 7.0.3] problema em receber push apns no iOS

### ISSUE THREAD

**Issue by jheimes-silveira** [FirebaseExtended/flutterfire#4923]
firebase_messaging 7.0.3

I performed all the steps of the tutorial to receive push, it works perfectly on Android, however on iOS I can't get the push, on iOS I even generate the token, I get the token right, but to send the push it is not working

on iOS I already tried to create an apns certificate with .p8 extension and it didn't work, I tried to create the sandbox certifications and also production with .p12 extension and added the same ones in firebase in the cloud message and even with that it's not working

**Comment by edgarfroes** [comment]
@jheimes-silveira could you please update your issue's title to English? É nóis :)

**Comment by edgarfroes** [comment]
> firebase_messaging 7.0.3
> 
> I performed all the steps of the tutorial to receive push, it works perfectly on Android, however on iOS I can't get the push, on iOS I even generate the token, I get the token right, but to send the push it is not working
> 
> on iOS I already tried to create an apns certificate with .p8 extension and it didn't work, I tried to create the sandbox certifications and also production with .p12 extension and added the same ones in firebase in the cloud message and even with that it's not working

Did you insert the generated APN in the Firebase Console > Project configuration > Cloud Messaging page?

**Comment by markusaksli-nc** [comment]
Hi @jheimes-silveira 
Have you followed all the steps of https://firebase.flutter.dev/docs/messaging/apple-integration carefully?
Could you try upgrading to the latest non-nullsafety version `firebase_messaging: ^8.0.0-dev.14`?
Thank you

**Comment by imhafeez** [comment]
Notifications are not working on iOS with me as well. When the app is in background I can receive it. but not in the foreground.
I am using `firebase_messaging: ^8.0.0-dev.14`
