### ISSUE TITLE
[RemoteConfig] example link is broken on readme

### ISSUE THREAD

**Issue by danielgomezrico** [FirebaseExtended/flutterfire#4925]
Hi

The link in the readme https://pub.dev/packages/firebase_remote_config:

![image](https://user-images.githubusercontent.com/76348/106662935-08e70600-6571-11eb-85d0-81e4d3aec242.png)

Is broken, it points to: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/example

I believe that it should be:
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config/example

I can't find where is this readme on the repository so I am not been able to contribute that change.

**Comment by rrousselGit** [comment]
Closing as the latest version (0.10.x-dev) doesn't have this issue
