### ISSUE TITLE
firebase_storage event updates

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#493]
are too infrequent.  using this:

```dart
final StorageReference _taskRef = FirebaseStorage.instance.ref().child(_fileName);

    final StorageUploadTask _task = _taskRef.putFile(
      attachment,
      metadata,
    );
```

and then listening to the stream:

```dart
StreamBuilder<StorageTaskEvent>(
  stream: _task.events,
  builder: (context, AsyncSnapshot<StorageTaskEvent> snapshot) {

    final StorageTaskSnapshot _data = snapshot.data.snapshot;
    print('progress = ${_data.bytesTransferred} / ${_data.totalByteCount}');
```

results in updates maybe once every M.  in repeated trials with a 3.2M file, i get roughly the same thing every time:
```
progress = 133 / 3178281
progress = 8325 / 3178281
progress = 1106053 / 3178281
progress = 1949829 / 3178281
progress = 3178281 / 3178281
```
i understand the need for large-ish chunk sizes, but gaps this large make it effectively impossible to render progress.

**Comment by kroikie** [comment]
@blaneyneil

The issue at https://github.com/flutter/flutter/issues/26916 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @blaneyneil
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by blaneyneil** [comment]
i am not.  the chunks are now smoothed so it's good UI.

**Comment by iapicca** [comment]
Hi @blaneyneil 
I'm glad that you fixed the issue
thank you for letting me know
