### ISSUE TITLE
🐛 Not all the data requested is being retrieved

### ISSUE THREAD

**Issue by cavedweller** [FirebaseExtended/flutterfire#4937]
### Description
I am not sure if its my code or something else but i am requesting information from an api, all the JSON information is returned correctly when i run the url trigger on the web but when i request the data in flutter there is information missing.

### Example Response

**_Web information returned_** 

`{"data":[{"name":"follower_count","period":"day","values":[{"value":0,"end_time":"2021-01-01T08:00:00+0000"},....etc `

**_flutter information returned__** 

`[{period: day, values: [{end_time: 2021-01-01T08:00:00+0000, value: 0},....etc `

As you can see there reponse is missing out the first bit of the JSON data which is throwing a whole bunch of errors.

### Typescript code

```
export const FollowerCountService = functions.https.onRequest((refrence, response) => {
  admin.firestore().collection('users').doc(uid).get().then(function(doc){
    if(doc.exists){
      axios.get(*api url*).then((resp:any) => {
        response.send(resp.data); 
        return resp.data;
      });
    }else{
      console.log("No such document!");
    }
  }).catch(function(error) {
    console.log("Error getting document:", error);
});
```

### Flutter code

```
 HttpsCallable callable = CloudFunctions.instance
        .getHttpsCallable(functionName: 'FollowerCountService');
    callable().then((v) {
      print(v.data);
    });
```

### Flutter doctor

```
Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-ZA)
    • Flutter version 1.22.6 at C:\Users\user\flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • SM G950F (mobile) • ce081718e4a08f1b04 • android-arm64 • Android 9 (API 28)
```

### Flutter dependencies

All dependancies are running the latest version

Appologies for any errors, this is my first time using cloud functions

**Comment by markusaksli-nc** [comment]
Hi @cavedweller 
Without knowing what kind of documents are used with firestore here it would be hard to diagnose the problem. Please try to reduce the issue to the minimum amount of fields and provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Could you also provide your `flutter pub deps -- --style=compact`?
Thank you
