### ISSUE TITLE
[cloud_firestore] runTransaction throws isolate errors!

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#495]
Im trying to use transaction to get multiple `DocumentSnapshot` and update them afterward, but it just keeps reporting isolate related errors. Someone please help me with it. 

Please check the detail below, basically it works fine when you only try to get/update one `DocumentSnapshot`, but in the case of multiple `get`/`update` things gets nasty. I have already been stuck for multiple days. 

I have even encountered cases that when it reach `await transaction.get(itemReferences[i]); `, it jumps to `print("complete");` immediately and then come back to get another snapshot then update action, which throws error as well. To be honest, I did not expect transaction to be this hard to use.
 Please can someone take a look at it.

iOS simulator
```yml
cloud_firestore: ^0.8.2+3
```

```dart
Future<String> postOrder(List<DocumentReference> itemReferences) {
  final TransactionHandler updateTransaction = (Transaction transaction)async {
    List<DocumentSnapshot> fetchedDocs = [];
    for (int i = 0; i < itemReferences.length; i++) {
      DocumentSnapshot fetchedDoc = await transaction.get(itemReferences[i]);
      fetchedDocs.add(fetchedDoc);
    }
    for (int i = 0; i < fetchedDocs.length; i++) {
      await transaction.update(itemReferences[i], fetchedDocs[i].data);
    }
  };

  return Firestore.instance.runTransaction(updateTransaction).then((response){
    print("complete");
  });
}
```
Error ouput:
```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c5231bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010bac1735 objc_exception_throw + 48
	2   Runner                              0x00000001077b409e -[FSTTransaction lookupDocumentsForKeys:completion:] + 238
	3   Runner                              0x000000010767c5d7 -[FIRTransaction getDocument:completion:] + 951
	4   Runner                              0x000000010767cf3e -[FIRTransaction getDocument:error:] + 414
	5   Runner                              0x00000001078c6c9b __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.458 + 347
	6   libdispatch.dylib                   0x000000010dce94e1 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010dcea54b _dispatch_client_callout + 8
	8   libdisp<…>
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"440","method":"resume","params":{"isolateId":"isolates/408554185"}}
Failed to send request: {"jsonrpc":"2.0","id":"441","method":"getStack","params":{"isolateId":"isolates/408554185"}}
```

btw, just caught the error output of the rare case where it jumps to print("complete") immediately
```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001126351bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000111bd3735 objc_exception_throw + 48
	2   Runner                              0x000000010d8c84ff -[FSTTransaction ensureCommitNotCalled] + 111
	3   Runner                              0x000000010d8c5fef -[FSTTransaction lookupDocumentsForKeys:completion:] + 63
	4   Runner                              0x000000010d78e5d7 -[FIRTransaction getDocument:completion:] + 951
	5   Runner                              0x000000010d78ef3e -[FIRTransaction getDocument:error:] + 414
	6   Runner                              0x000000010d9d8c9b __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.458 + 347
	7   libdispatch.dylib                   0x0000000113ede4e1 _dispatch_call_bloc<…>
Lost connection to device.
```

**Comment by kroikie** [comment]
@PandaGeek1024

The issue at https://github.com/flutter/flutter/issues/26885 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @PandaGeek1024
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
