### ISSUE TITLE
🐛 [Authentication] When user changes password or account is disabled from Console, no event fires on client event streams

### ISSUE THREAD

**Issue by muzzah** [FirebaseExtended/flutterfire#4950]
## Bug report

**Describe the bug**

None of the expected events fire on the client when the user completes actions outside the application that should result in an event to the client to notify the application

### Steps to reproduce

Subscribe to any of the event stream available on the FirebaseAuth class (User, auth, token).

Then through the  Web console, you can send a password reset email or disable user. 

When any of these events are completed, no event is received on the client.

### Expected behavior

The event streams should fire an event on the client notifying the app of such events

Using following firebase libraries

cloud_firestore: ^0.16.0
firebase_core: ^0.7.0
firebase_auth: ^0.20.0

**Comment by markusaksli-nc** [comment]
I at least didn't get any update in the stream when I deleted the user and only after manually reloading got

```
E/flutter (31704): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
E/flutter (31704): #0      MethodChannelUser.reload (package:firebase_auth_platform_interface/src/method_channel/method_channel_user.dart:121:7)
E/flutter (31704): <asynchronous suspension>
E/flutter (31704): #1      User.reload (package:firebase_auth/src/user.dart:257:5)
E/flutter (31704): <asynchronous suspension>
E/flutter (31704): 
```

Tested on the latest master `1.26.0-18.0.pre.210` with `firebase_auth: ^0.20.0+1` using https://github.com/FirebaseExtended/flutterfire/pull/4635
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.26.0-18.0.pre.210, on Microsoft Windows [Version 10.0.19041.746], locale et-EE)
    • Flutter version 1.26.0-18.0.pre.210 at C:\Development\flutter_master
    • Framework revision a77388e670 (4 hours ago), 2021-02-04 22:51:04 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!
```
</details>

**Comment by muzzah** [comment]
This is a pretty big regression IMO. As per the firebase auth docs

```
  /// Notifies about changes to any user updates.
  ///
  /// This is a superset of both [authStateChanges] and [idTokenChanges]. It
  /// provides events on all user changes, such as when credentials are linked,
  /// unlinked and when updates to the user profile are made. The purpose of
  /// this Stream is to for listening to realtime updates to the user without
  /// manually having to call [reload] and then rehydrating changes to your
  /// application.
  Stream<User> userChanges() => _pipeStreamChanges(_delegate.userChanges());
```

Its completely broken. We have no way of knowing when the user is valid or not as a result of this and having to call reload is discouraged by firebase itself. Without this, we also run in to massive issues when using the user if the user is invalidated causing crashes and exceptions.

**Comment by yulkin2002** [comment]
Has there been any update on this?
I have the same issue and it's a security concern. When is this going to be fixed?

**Comment by russellwheatley** [comment]
Hey folks, I've clarified further what is expected should a user be deleted or disabled via the console or firebase admin SDK. This isn't a bug I'm afraid, it is just the behaviour of the underlying implementation of the web, iOS & android firebase SDKs that this library wraps around.

**Comment by YazeedAlKhalaf** [comment]
Okay so isn't there any workaround that can be done to get a stream of user data?

This functionality seems important.

For example, I would want the app to go to the register screen when the user is disabled or deleted. That way the app doesn't break or something like that. Now I have to somehow call the reload method which is not ideal and not really practical.
