### ISSUE TITLE
[cloud_firestore] Issue

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#496]
I am having issue when using `startAt()` `endAt()` when ordering by `title` which is a string

It works when i am using `startAt()` `endAt()` when ordering by `rank` which is a number

It also works when i am using `startAt()` and not using `endAt()` when ordering by `title`

It should work regardless if it is type number or type string.
I think it's a bug.

What i have tried:
1. created indexes on Firestore

Here is the full code:
```dart
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:async';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Future getItemsTitle() async {
    QuerySnapshot snapshot5 = await Firestore.instance
        .collection('items')
        .orderBy("title", descending: false)
        .startAt([1])
        .endAt([2])
        .limit(2)
        .getDocuments();

    print(snapshot5.documents[0].data['title']);
    print(snapshot5.documents[1].data['title']);
  }

  Future getItemsRank() async {
    QuerySnapshot snapshot5 = await Firestore.instance
        .collection('items')
        .orderBy("rank", descending: false)
        .startAt([1])
        .endAt([2])
        .limit(2)
        .getDocuments();

    print(snapshot5.documents[0].data['title']);
    print(snapshot5.documents[1].data['title']);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          padding: EdgeInsets.all(50.0),
          child: Column(
            children: <Widget>[
              RaisedButton(
                  child: Text("Get By Rank"),
                  onPressed: () {
                    getItemsRank();
                  }),
              RaisedButton(
                  child: Text("Get By Title"),
                  onPressed: () {
                    getItemsTitle();
                  }),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by kroikie** [comment]
@momoDragon

The issue at https://github.com/flutter/flutter/issues/26872 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @momoDragon
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
