### ISSUE TITLE
Pose Detection

### ISSUE THREAD

**Issue by HollererJ** [FirebaseExtended/flutterfire#4961]
Is there also a way to use the Pose Detection with this package ?

**Comment by markusaksli-nc** [comment]
Assuming this is about ML vision you probably could do it with a custom ML model but it's going to take some work implementing the model and using the output.

In any case it isn't part of the default ML vision models.

**Comment by startupgurukul** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/3397
