### ISSUE TITLE
[Google Maps] Support marker clustering

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#497]
*Edited by amirh:*

This is a request to  support marker clustering similarly to https://developers.google.com/maps/documentation/android-sdk/utility/marker-clustering

**Comment by kroikie** [comment]
@m7amdElberawy

The issue at https://github.com/flutter/flutter/issues/26863 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by pro100svitlo** [comment]
any update?

**Comment by kroikie** [comment]
@pro100svitlo no update yet; sorry for the delay.

Since this issue is not related to Firebase; I'll close this and reopen the [original issue](https://github.com/flutter/flutter/issues/26863) in the flutter/flutter repo. Please continue to track it there.
