### ISSUE TITLE
MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core) on Android

### ISSUE THREAD

**Issue by Bestfastfire** [FirebaseExtended/flutterfire#4977]
I have seen that there is another issue that has not been resolved. #3212

The user did not explain well what happens and how the discussion was closed I decided to open another one.

This started with me a short time ago, I already tested it on `stable, beta, dev and master` channels and the problem persists.

**THE BUG**

If I run: `flutter run --release` works fine, but if I generate an apk / bundle release `flutter build apk --release`, when I install it on a device the bug appears.

I was able to monitor it by giving a `flutter run --release` on the device, closing the app, and installing the apk after, as the terminal is still receiving the app log, you can see that the bug appears.

I tested with all versions of `firebase_core`  >= 0.5.0 and the bug persists

I am currently using this version:

`[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19042.746], locale pt-BR)`

Edit:

Before anyone comments "Just put` await Firebase.initializeApp (); `" of course I already did this, all tests were done correctly, this problem started with me recently (1 week), and the code has not been changed , before it worked perfectly.

**Comment by Bestfastfire** [comment]
Another interesting thing, if I generate the `apk` in the profile mode `flutter build apk --profile` and install it on the device it works well too, and since the profile is basically the unsigned release if I'm not mistaken, the problem could be due to the signature file? I will do this test now and report here, generate a new jks to test.

**Comment by Bestfastfire** [comment]
> Another interesting thing, if I generate the `apk` in the profile mode `flutter build apk --profile` and install it on the device it works well too, and since the profile is basically the unsigned release if I'm not mistaken, the problem could be due to the signature file? I will do this test now and report here, generate a new jks to test.

It didn't work, the problem still continues, I'll try to downgrade the flutter but from what I saw in the other issue #3212 there was a user who did it in 1.20 but it also didn't work

**Comment by Bestfastfire** [comment]
I tested on the versions:

1.17.5 - Stable
1.20.0 - Stable
1.20.3 - Stable

With different versions of `firebase_core` and in all of them the same problem persists.

I did the tests on windows, now I will try to do these same tests on the `Mac`, maybe there will be some results.

**Comment by Bestfastfire** [comment]
I did it on `mac` and it also didn't work

**Comment by markusaksli-nc** [comment]
Hi @Bestfastfire 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by Bestfastfire** [comment]
> Hi @Bestfastfire
> Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
> Thank you

Sure, but I don't think it will make a difference, if you saw my previous messages you saw that I used several versions and channels of flutter both on `windows` and on `mac`:

**flutter doctor -v**

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale pt-BR)
    • Flutter version 1.24.0-10.2.pre at /Users/wotonsampaio/Documents/packages/flutter
    • Framework revision 022b333a08 (3 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wotonsampaio/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available
```

**flutter pub deps -- --style=compact**

```
Dart SDK 2.12.0-29.10.beta
Flutter SDK 1.24.0-10.2.pre
myr_flutter 1.0.2+3

dependencies:
- animated_splash_screen 1.0.1+2 [flutter page_transition]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.1 [flutter]
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- country_pickers 1.3.0 [flutter]
- cpfcnpj 1.0.3
- cupertino_icons 0.1.3
- date_format 1.0.9
- enum_to_string 1.0.13
- expandable 4.1.4 [flutter]
- file_picker 2.1.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_database 6.0.0 [flutter firebase_core]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- fluttertoast 7.1.1 [flutter flutter_web_plugins]
- fragment_navigate 1.1.0 [flutter rxdart]
- image_cropper 1.3.0 [flutter]
- image_picker 0.6.7+12 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- mask_text_input_formatter 1.1.0 [flutter]
- modal_progress_hud 0.1.3 [flutter]
- open_file 3.0.3 [flutter ffi]
- package_info 0.4.3+4 [flutter]
- path_provider 1.6.22 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pdf 1.11.2 [meta vector_math utf crypto archive barcode image path_parsing]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- platform_device_id 0.1.1 [flutter device_info]
- printing 3.7.1 [flutter flutter_web_plugins image js meta pdf plugin_platform_interface]
- rxdart 0.24.1
- shared_preferences 0.5.12+2 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- super_rich_text 0.2.1+1 [flutter url_launcher]
- url_launcher 5.7.6 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.0.2 [crypto convert]
- youtube_player_flutter 7.0.0+7 [flutter flutter_inappwebview]

dev dependencies:
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_native_splash 0.1.9 [yaml image color]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.3 [collection]
- barcode 1.17.1 [meta qr]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- clock 1.1.0-nullsafety.3
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.5
- color 2.1.1
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- device_info 0.4.2+9 [flutter device_info_platform_interface]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.2 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_inappwebview 4.0.0+4 [flutter uuid mime]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.3
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- mime 0.9.7
- octo_image 0.3.0 [flutter flutter_blurhash]
- page_transition 1.1.7+2 [flutter]
- path 1.8.0-nullsafety.3
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- qr 1.3.0 [meta]
- quiver 2.1.4+1 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.5 [collection]
- url_launcher_linux 0.0.1+3 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- utf 0.9.0+5
- vector_math 2.1.0-nullsafety.5
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

```

**Comment by Bestfastfire** [comment]
I even remembered now, I have another project with firebase that and I'm absolutely sure it was working because + - 01/18 I sent a release to the store and tested the apk with the client. I will generate an apk of it now to see if the problem also resolves.

**Comment by Bestfastfire** [comment]
Sorry for the delay, I took the test now as another app and oddly enough it worked, `firebase_core` is in the same version as the app that didn’t work,` build: gradle` and `google-services` too, it seems to me so the problem may be conflict with another plugin, I will continue doing more tests and if you find something I report here

**Comment by Bestfastfire** [comment]
Sorry for the delay, I did the test now as another app and as incredible as it seemed it worked, `firebase_core` is in the previous version that needed to call` Firebase.initializeApp()` to work, `0.4.4`, the `build : gradle` and `google-services` are in the same version, I’ll downgrade the other project to that version and test it, but I know that all >= `0.5.0` don’t work because I’ve already tested it.

**Comment by Bestfastfire** [comment]
> Sorry for the delay, I did the test now as another app and as incredible as it seemed it worked, `firebase_core` is in the previous version that needed to call `Firebase.initializeApp()` to work, `0.4.4`, the `build : gradle` and `google-services` are in the same version, I’ll downgrade the other project to that version and test it, but I know that all >= `0.5.0` don’t work because I’ve already tested it.

Unfortunately it did not work, it was missing another method of the plugin `MissingPluginException (No implementation found for method FirebaseDatabase#setPersistenceEnabled on channel plugins.flutter.io/firebase_database)`, it seems that when creating the build the native methods of the firebase plugins are not being compiled, there may be some conflict with another plugin, I will do some more tests and remove plugin by plugin to see which may be generating the conflict.

If after all it still doesn't work, I'll create a new project with the same package, copy all the code and test.

**Comment by Bestfastfire** [comment]
I was removing plugin by plugin until there were only the ones from firebase and it still didn't work, the same problem persists ... I will now create a new project with a new package, add it in firebase, copy all the code there and do the test again.

**Comment by Bestfastfire** [comment]
EUREKA, I found out! The problem is in the version of the project-level `gradle`, if it is >=  `4.0.0` the error appears, in the new project I created the code it worked correctly but I saw that it was in the `classpath 'com.android.tools .build: gradle: 3.5.4'`, and I saw that the previous one was in the `classpath 'com.android.tools.build: gradle: 4.1.2'`, I downgraded the previous version and Voilà, it worked too!

**Comment by Bestfastfire** [comment]
I'll go back to `firebase_core` for versions >= `0.5.0` to see if it will work there too

**Comment by Bestfastfire** [comment]
It really worked, I'm happy, I didn't know what to do anymore and I didn't imagine that the problem could be this.

Solution:
- my_project/android/build.gradle (case build:gradle >= 4.0.0)

change:
`classpath 'com.android.tools.build:gradle:4.x.x'`

to:
`classpath 'com.android.tools.build:gradle:3.5.4'`

Now:
- my_project/android/gradle/wrapper/gradle-wrapper.properties:

change:
`distributionUrl=https\://services.gradle.org/distributions/gradle_version.zip`

to:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`
