### ISSUE TITLE
📚 GoogleService-Info.plist in the iOS/MacOS installation document should be GoogleService-Info.xml

### ISSUE THREAD

**Issue by idy** [FirebaseExtended/flutterfire#4978]
![image](https://user-images.githubusercontent.com/687349/107161498-07399a00-69d8-11eb-8519-7c8b894a76e2.png)

The file name of the downloaded file in the picture is `GoogleService-Info.xml`, one need to manually rename it to `.plist` and then follow the instructions in [macos](https://firebase.flutter.dev/docs/installation/macos) and [ios](https://firebase.flutter.dev/docs/installation/ios) docs. This is not mentioned in these documents. If you run Firebase.initializeApp() without modifying the file name, the following error will be reported:

```
Exception: initial firebase error: [core/not-initialized] Firebase has not been initialized. Please
check the documentation for your platform.
```

**Comment by idy** [comment]
This may also be a file download bug.

**Comment by britannio** [comment]
I tried this out and it downloaded a file ending with `.plist` as expected.

**Comment by peterpoliwoda** [comment]
Downloads a .plist file for me too. I think this can be put to bed.

**Comment by idy** [comment]
It's weird. When I use chrome to download this file, the file name change to GoogleService-Info.xml
![image](https://user-images.githubusercontent.com/687349/107304334-d2067800-6abb-11eb-9639-49189b9e8bc2.png)

```
Version 88.0.4324.146 (Official Build) (arm64)
```

When I use safari to download this file, the file name keeps GoogleService-Info.plist

![image](https://user-images.githubusercontent.com/687349/107304653-7ab4d780-6abc-11eb-83c2-00234b331fff.png)

**Comment by idy** [comment]
I think this issue is not about flutterfire, the documentation is right. I will create a support case with firebase.
