### ISSUE TITLE
🐛 [firebase_messaging] Get first data message on iOS when app is terminated

### ISSUE THREAD

**Issue by letsar** [FirebaseExtended/flutterfire#4981]
## Bug report

I have an app where we send data messages. On **iOS** when the app is terminated, the first message awakes the app but the `onBackgroundMessage` handler from the Dart side is never called. If we send another data message just after the first one, the latter is correctly received on the Dart side through the `onBackgroundMessage` handler.

### Steps to reproduce

1. Add the `firebase_messaging: ^8.0.0-dev.14` dependency in the pubspec.yaml of an app.
2. Configure the app so that it can receive push notifications from FCM on iOS.
3. Add a handler to `FirebaseMessaging.onBackgroundMessage()` function and log this call so that it can be track with Console.app.
4. Launch the app, and then terminate it.
5. Send a first FCM background notification (makes sure to follow the Apple documentation: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)
6. Send a second one

### Expected behavior

Both notifications are logged

### Actual behavior

Only the second one is logged

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @letsar 
I'm not seeing this with the official example. The first data only notification is received from the terminated state just fine.
Could you provide your `flutter pub deps -- --style=compact` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by letsar** [comment]
That's strange. How can I test the provided example to see if I can also reproduce it? Maybe we did something wrong, but when I look at the example code, it seems that we do pretty much the same things.

I think that the issue I saw in our app is because the notification is sent into the channel before the dart code had a chance to subscribe to it, therefore it's lost.
I forked the plugin to play with initialMessage and set it from the first notification as well, and I can get it from the dart side, bu any subsequent push notifications done before the dart side is completely initialized is lost.

**Comment by markusaksli-nc** [comment]
If you say it's set up the same then it shouldn't probably make a difference but if you can easily substitute the official example in and try it out it might be telling.

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib

**Comment by letsar** [comment]
I was able to run the official example and indeed it received the first data only notification while terminated. The background handler was not set as soon as possible in our code, that's why we were not able to get the first notification.

Now it seems that if we send multiple notifications quickly, when the app wakes up, only the last one is send to the dart code. I've also experienced a notification loss from the dart side, with the official example, when the app is terminated.

Have you a lead on that?

**Comment by markusaksli-nc** [comment]
How fast do you mean?

I counted them and got every one printed on the dart side.

```
default	12:12:18.542119+0200	Runner	flutter: Handling a background message 1612951937645460
default	12:12:18.551136+0200	Runner	flutter: FCM Token: <FCM Token>
default	12:12:19.627218+0200	Runner	flutter: Handling a background message 1612951939348749
default	12:12:21.458293+0200	Runner	flutter: Handling a background message 1612951941100098
default	12:12:23.709764+0200	Runner	flutter: Handling a background message 1612951943246018
default	12:12:26.174761+0200	Runner	flutter: Handling a background message 1612951945778528
default	12:12:28.829426+0200	Runner	flutter: Handling a background message 1612951948467796
default	12:12:31.465688+0200	Runner	flutter: Handling a background message 1612951951082902
```
