### ISSUE TITLE
🐛 [google_sign_in] My iOS app crashes when I click the "Sign in with Google" button

### ISSUE THREAD

**Issue by Python3-8** [FirebaseExtended/flutterfire#4983]
## Bug report

**Describe the bug**
I have a "Sign in with Google" button that is supposed to bring up a Google sign in page. When I click the button, my app crashes: https://user-images.githubusercontent.com/66139317/107186684-5668d600-69aa-11eb-8ed7-f276355a343b.mov. I'm currently learning Flutter and mobile application development, so I don't know much about FlutterFire, Android SDKs and NDKs, and iOS.

### Steps to reproduce

1. Run `flutter create bug_app`
2. Add Firebase to the iOS version of the app
4. Update the `lib` folder: [lib.zip](https://github.com/FirebaseExtended/flutterfire/files/5945745/lib.zip)
5. Update `pubspec.yaml`:
```yml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
```
6. Start an iOS simulator and run `flutter run` or click "Debug" above the `Future<void> main() async` function in VS Code.

### Expected behavior

I expected for my app to display a Google sign in page when I clicked the button.

---

## Additional context

I was having [this](https://github.com/flutter/flutter/issues/75605) issue before and after I fixed my `auth.dart` file, my app started crashing when I click the button.

Here's the output of `flutter run --verbose`: [flutter-run-verbose.log](https://github.com/FirebaseExtended/flutterfire/files/5945846/flutter-run-verbose.log)

---

### Flutter doctor

Run `flutter doctor -v` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/user/AppDependencies/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • EFDE6DB3-4511-4D88-AB75-AC43706CE6D1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```
This reminds me of another issue I've been facing. I've installed the Flutter and Dart plugins in Android studio but the Flutter CLI keeps saying I haven't

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
learning_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

**Comment by Python3-8** [comment]
I just tested my app on an Android Emulator. The button opens up a "Sign in with Google" dialog but I'm not taken to `MyHomePage`.

**Comment by markusaksli-nc** [comment]
Hi @Python3-8 
Do you also face this issue if you run the official example code?
There don't seem to be any crash logs before the debug connection is just lost. Could you try getting them through the Console app on your mac? You can filter the logs to the `Runner` process.
Thank you

**Comment by Python3-8** [comment]
I'm new to Flutter and iOS, so I don't get what you mean.

**Comment by Python3-8** [comment]
What does this error mean?

![Screen Shot 2021-02-09 at 11 26 00 AM](https://user-images.githubusercontent.com/66139317/107403188-6d9ee500-6aca-11eb-90a6-b01af229940a.png)

**Comment by markusaksli-nc** [comment]
The entire official example project has some version constraints and is set up to run through CI with a newer version of flutter. It would be better if you use the code instead of running the entire example. You can just copy and paste the dart files in the `lib` folder into your project and they should work if you have these dependencies in `pubspec.yaml`.
```yaml
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  firebase_dynamic_links: ^0.7.0+1
  flutter_signin_button: ^1.1.0
```
As for the console app you can just `cmd + space` and look for `console` on your mac, it should bring it up. It's used to get native logs from the devices connected to your mac. If you are new I would recommend you first try to run the official example code to make sure that this isn't just a mistake in your dart code.

**Comment by Python3-8** [comment]
I tried this, but my app crashes and the Flutter ouput says "Configuring default Firebase app" or something and never finishes: https://user-images.githubusercontent.com/66139317/107566461-90082f80-6baa-11eb-8765-eaeed8c11dad.mp4

**Comment by markusaksli-nc** [comment]
Have you carefully followed https://firebase.flutter.dev/docs/installation/ios

**Comment by Python3-8** [comment]
I followed these instructions: https://www.youtube.com/watch?v=EXp0gq9kGxI

**Comment by Python3-8** [comment]
I got the app to launch, but the app crashes again when I click the "Sign in with Google" button.

Here are the logs:
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...

Running Xcode build...
 └─Compiling, linking and signing...                        12.6s
Xcode build done.                                           25.5s
Waiting for iPhone 12 Pro Max to report its views...                10ms
Syncing files to device iPhone 12 Pro Max...                       414ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:50065/h0PFin6gPQM=/
flutter: PlatformException(google_sign_in, Your app is missing support for the following URL schemes: com.googleusercontent.apps.543332529575-rrhdarbb3e490929fp6na4vo23hkl8vb, NSInvalidArgumentException, null)
Lost connection to device.
```

Screen recording: https://user-images.githubusercontent.com/66139317/107678978-a45b3380-6c61-11eb-989c-a6cb1d054fba.mp4

**Comment by markusaksli-nc** [comment]
You have not added the URL scheme as mentioned in the documentation for `google_sign_in`.

> Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.
```xml
<!-- Put me in the [my_project]/ios/Runner/Info.plist file -->
<!-- Google Sign-in Section -->
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<!-- TODO Replace this value: -->
			<!-- Copied from GoogleService-Info.plist key REVERSED_CLIENT_ID -->
			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
		</array>
	</dict>
</array>
<!-- End of the Google Sign-in Section -->
```

**Comment by Python3-8** [comment]
Thanks, it worked!
