### ISSUE TITLE
[firebase_admob] pauses video when app goes to background

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#499]
When user switches app during rewarding video playback and brings it back to active state, video is paused. Yes, if user clicks on "close" button he/she is prompted to resume the video, but it would be nice to have an API to automatically continue playing video

**Comment by kroikie** [comment]
@lesnitsky

The issue at https://github.com/flutter/flutter/issues/26829 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @lesnitsky
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
