### ISSUE TITLE
flutter dynamic link issues 

### ISSUE THREAD

**Issue by nageshadhavbncoe** [FirebaseExtended/flutterfire#4990]
Invalid event name. Event will not be logged (FE): dynamic_link_app_open

this are the error comes while i am opening the app while i am clicking on the link and after clicking the apps are started but its moving to homepage instead of moving to another page how to resolve the issues

**Comment by markusaksli-nc** [comment]
Hi @nageshadhavbncoe 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4716.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
