### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging class doesn't have configure()

### ISSUE THREAD

**Issue by Sepehr13** [FirebaseExtended/flutterfire#4993]
## Bug report

**Describe the bug**
It's pretty straightforward. in the latest firebase_messaging plugin ( ^7.0.3 ), the FirebaseMessaging class doesn't have configure() function. any other alternative?

**Comment by markusaksli-nc** [comment]
Hi @Sepehr13 
Actually it was removed in the prerelease version that came after `7.0.3` (`8.0.0-dev.1`). You can always look for explanations to deprecations in https://firebase.flutter.dev/docs/migration

In this case as mentioned in https://firebase.flutter.dev/docs/migration#messaging

>BREAKING: configure() has been removed in favor of calling specific static methods which return Streams.

>**Why?:** The previous implementation of configure() caused unintended side effects if called multiple times (either to register a different handler, or remove handlers). This change allows developers to be more explicit about registering handlers and removing them without effecting others via Streams.

You can find how to use the new implementation in the [official example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart).
https://github.com/FirebaseExtended/flutterfire/blob/c3b13af41e2fadc22a44ebbcd14a8ac4736d9e75/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L50
https://github.com/FirebaseExtended/flutterfire/blob/c3b13af41e2fadc22a44ebbcd14a8ac4736d9e75/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L127-L154
Thank you
