### ISSUE TITLE
🐛 [firebase_auth] build failed after adding this library

### ISSUE THREAD

**Issue by HetalGohil** [FirebaseExtended/flutterfire#4995]
## Bug report

**Describe the bug**
Execution failed for task ':firebase_auth:processDebugGoogleServices'.
> No matching client found for package name 'io.flutter.plugins.firebase.auth'

**Comment by markusaksli-nc** [comment]
Hi @HetalGohil 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
