### ISSUE TITLE
Test of RemoteConfig with UserProperty doesn't refresh

### ISSUE THREAD

**Issue by avi-mastov** [FirebaseExtended/flutterfire#4996]
My use case is this:

I'm trying to A/B test only new users.
All users have a UserProperty `created_at` which marks their creation date (format `yyyyMMdd`). The A/B test criteria are created_at >= some date and app version >= some version. I'm testing using Flutter SDK `firebase_remote_config` v0.6.0. There are very few users who are found eligible for the test in comparison with actual new users.

I have to fetch the remote config early at start up because there is configuration I need to use right away, before authenticating the user. After authentication, I set the `created_at` property and try to refresh the RemoteConfig, but I get the same default value instead of the A/B test variant (I defined it for 90% of users, but actually getting 0% after testing about 7 times). I gave the RemoteConfig an expiration of 1 second, in order to be able to refresh it when I need, but to no avail.

I must state that in checks I made several weeks ago on Flutter firebase_remote_config v0.4.3, it worked. Perhaps something was changed in the backend? I upgraded the SDK to 0.6.0 (the latest release), but it didn't help.

Thank you.
Avi

<img width="1134" alt="Lumen_–_Remote_Config_–_Firebase_console" src="https://user-images.githubusercontent.com/22952984/107384381-94750f80-6afa-11eb-96f9-41eaa23aa6b2.png">

**Comment by markusaksli-nc** [comment]
Hi @avi-mastov 
Could you please raise this in https://firebase.google.com/support/troubleshooter/report/bugs first to make sure it's not an upstream bug. If it isn't then you can open a new issue here with the details.

When opening an issue, please try to provide all of the information indicated in the template. Closing this for now.
Thank you.
