### ISSUE TITLE
[firebase_admob] should treat app installation as reward

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#500]
I'm not sure if it should work this way by design, but IMO if user already had an interaction with rewarding ad (clicked on install), plugin should emit `rewarded` event

**Comment by kroikie** [comment]
@lesnitsky

The issue at https://github.com/flutter/flutter/issues/26828 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
