### ISSUE TITLE
firebase_auth verifyPhoneNumber issue when same device verification

### ISSUE THREAD

**Issue by mayurm-virtueinfo** [FirebaseExtended/flutterfire#5002]
flutter package version : firebase_auth: ^0.20.0+1

FirebaseAuth.instance.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: Duration(milliseconds: (1000*60)),
      verificationCompleted: (PhoneAuthCredential phoneAuthCredential) async {},
      verificationFailed: (FirebaseAuthException exception) {},
      codeSent: (String verificationId, [int forceResendingToken]) async {},
      codeAutoRetrievalTimeout: (verificationId) {},
)

When i user this code it works perfact if code is sent in another device. But when code is send in the same device at that time both 'codeSent' and 'verificationCompleted' method is called.

So, How can i handle this ?

**Comment by markusaksli-nc** [comment]
Hi @mayurm-virtueinfo 
When sending the code to the same device the `verificationCompleted` callback is called on Android if the code can be automatically detected. You can use the PhoneAuthCredential to sign in or link without needing to enter the code.

This is the intended behavior and you can see how to use it in the official example.
https://github.com/FirebaseExtended/flutterfire/blob/c3b13af41e2fadc22a44ebbcd14a8ac4736d9e75/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#L440-L489
Thank you
