### ISSUE TITLE
🐛 [firebase_messaging] pub get fails on v7.0.3 because it depends on an older firebase_core version

### ISSUE THREAD

**Issue by believeInJha** [FirebaseExtended/flutterfire#5024]
Hi please fix the dependency for firebase_messaging on firebase_core, I am currently getting this when I do pub get the newest version:

```
Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.
So, because 'xxx' depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed
```

my pubspec.yaml : 
```cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0
  firebase_messaging: ^7.0.3
```

**Comment by chandupalasith** [comment]
same problem here. This bug caused other errors also

**Comment by markusaksli-nc** [comment]
"Hi @...
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4955.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
