### ISSUE TITLE
A problem occurred evaluating root project 'firebase_auth'.

### ISSUE THREAD

**Issue by gunasekharravilla** [FirebaseExtended/flutterfire#5026]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.3+1\android\build.gradle' line: 26       

* What went wrong:
A problem occurred evaluating root project 'firebase_auth'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Exception: The plugin firebase_auth could not be built due to the issue above.

**Comment by markusaksli-nc** [comment]
Hi @gunasekharravilla 
Please use the latest version `firebase_auth: ^0.20.0+1`
Closing because the version you are using is outdated and none of the information in the template has been provided.
Thank you

**Comment by austinhogan11** [comment]
im using the ^0.20.0+1 version and getting the same issue
