### ISSUE TITLE
🐛 [firebase_ml_vision] error: package io.flutter.plugins.firebasemlvision does not exist

### ISSUE THREAD

**Issue by mukkulsingh** [FirebaseExtended/flutterfire#5036]
## Bug report

**Describe the bug**
Flutter build crashes after updating the beta channel of flutter
### Steps to reproduce

1. Create flutter project with old flutter version
2. add firebase ml vision
3. try to run the project

### Expected behavior
build and install the app in simulator or physical device.

---

## Additional context

```
android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:22: error: package io.flutter.plugins.firebasemlvision does not exist
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasemlvision.FirebaseMlVisionPlugin());
                                                                          ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (3 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>

</summary>

flutter pub deps -- --style=compact
Dart SDK 2.12.0-259.9.beta
Flutter SDK 1.26.0-17.5.pre
fitway_crm 1.2.88+107

dependencies:
- android_intent 0.3.7+7 [flutter platform meta]
- barcode_scan 3.0.1 [protobuf flutter]
- camera 0.7.0+2 [flutter camera_platform_interface pedantic quiver]
- connectivity 2.0.2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- country_code_picker 1.7.0 [flutter modal_bottom_sheet]
- country_pickers 1.3.0 [flutter]
- currency_pickers 1.0.6 [flutter]
- dartz 0.9.2
- data_connection_checker 0.3.4
- dio 3.0.10 [http_parser path]
- dropdown_search 0.4.8 [flutter]
- equatable 1.2.6 [collection meta]
- fancy_dialog 1.0.4 [flutter]
- firebase_ml_vision 0.10.0 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.2 [flutter bloc provider]
- flutter_google_places 0.2.6 [flutter rxdart google_maps_webservice http]
- flutter_icons 1.1.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_money_formatter 0.8.3 [flutter intl]
- flutter_multiselect 0.5.1 [flutter]
- flutter_native_image 0.0.5+3 [flutter]
- flutter_pdfview 1.0.4 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_socket_io 0.6.0 [flutter]
- fluttertoast 7.1.6 [flutter flutter_web_plugins]
- font_awesome_flutter 8.11.0 [flutter]
- geolocator 6.2.0 [flutter geolocator_platform_interface geolocator_web]
- get_it 5.0.6 [async meta]
- google_map_location_picker 4.1.6 [flutter flutter_localizations intl google_maps_flutter geolocator android_intent provider http stack_trace package_info]
- google_maps_flutter 1.2.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_webservice 0.0.19 [http meta]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image 2.1.19 [archive xml meta]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.15.8 [path]
- multiselect_formfield 0.1.5 [flutter]
- numberpicker 1.3.0 [flutter infinite_listview]
- onesignal_flutter 2.6.2 [flutter]
- open_appstore 1.0.2 [flutter]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- provider 4.3.3 [collection flutter nested]
- qr_flutter 3.2.0 [flutter qr]
- razorpay_flutter 1.2.3 [flutter eventify]
- responsive_framework 0.0.14 [flutter]
- share_extend 1.1.9 [meta flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sqflite 1.3.2+3 [flutter sqflite_common path]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed
_data]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]
- mockito 4.1.4 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]

dependency overrides:
- intl 0.15.8 [path]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- bloc 6.1.1 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- camera_platform_interface 1.5.0 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.2.0 [path]
- clock 1.1.0
- code_builder 3.6.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- cross_file 0.1.0 [flutter http meta]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- eventify 0.1.4
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- fixnum 0.10.11
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geolocator_platform_interface 1.0.9 [flutter meta plugin_platform_interface vector_math]
- geolocator_web 1.0.0 [flutter flutter_web_plugins geolocator_platform_interface]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_maps_flutter_platform_interface 1.2.0 [flutter meta plugin_platform_interface stream_transform collection]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- infinite_listview 1.0.1+1 [flutter]
- js 0.6.3
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- modal_bottom_sheet 1.0.0+1 [flutter]
- nested 0.0.4 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- package_info 0.4.3+4 [flutter]
- path 1.8.0
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.10.0
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- protobuf 1.1.1 [fixnum]
- pub_semver 1.4.4 [collection]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_gen 0.9.10+2 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite_common 1.0.3+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- watcher 0.9.7+15 [async path pedantic]
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @mukkulsingh 
Have you tried `flutter clean` and then `flutter run`?
Thank you

**Comment by mukkulsingh** [comment]
@markusaksli-nc 
Yes i did it and everything which i found on stackoverflow and github.  i struggled for 2 days to solve this but nothing worked

**Comment by markusaksli-nc** [comment]
Do you get this error if you `flutter create` a new project and just add the dependency as well?

**Comment by mukkulsingh** [comment]
@markusaksli-nc no

**Comment by mukkulsingh** [comment]
@markusaksli-nc  
Sorry !!! Actually it is throwing an error for new project too!
Running Gradle task 'assembleDebug'...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.10.0\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':firebase_ml_vision'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':firebase_ml_vision'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by markusaksli-nc** [comment]
This should be solved with https://github.com/FirebaseExtended/flutterfire/issues/4141#issuecomment-738702407

**Comment by mukkulsingh** [comment]
@markusaksli-nc  Yeah does worked for me
