### ISSUE TITLE
🐛 [firebase_messaging] version solving failed

### ISSUE THREAD

**Issue by sm2017** [FirebaseExtended/flutterfire#5040]
## Bug report

**Describe the bug**
The documentation clearly said
![image](https://user-images.githubusercontent.com/19644997/107945690-3edeae00-6fa5-11eb-9179-d4ff9a7ac38e.png)

I get the following error, when I run `flutter pub get`

```
Because firebase_messaging >=7.0.3 <8.0.0-dev.7 depends on firebase_core ^0.5.0+1 and app depends on firebase_core ^0.7.0, firebase_messaging >=7.0.3 <8.0.0-dev.7 is forbidden.
So, because app depends on firebase_messaging ^7.0.3, version solving failed.
pub get failed (1; So, because app depends on firebase_messaging ^7.0.3, version solving failed.)
```

### Steps to reproduce

1. add `firebase_core: "^0.7.0"` and `firebase_messaging: "^7.0.3"` to `pubspec.yaml`
2. run `flutter pub get`

### Expected behavior

Obviously it must works

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
```

</details>
<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>
---

**Comment by alibubere9** [comment]
That's some sort of an issue I've veen experiencing. And ios couldn't build if I bring down `firebase_messaging` down to 6.0.16 as I've explained here

**Comment by markusaksli-nc** [comment]
Hi @sm2017 
Please upgrade to the latest non-nullsafety version `firebase_messaging: ^8.0.0-dev.14`.
There is already an issue to track that the wrong version is mentioned in the documentation https://github.com/FirebaseExtended/flutterfire/issues/4955.
Closing since the newest version of `firebase_core` is incompatible with older versions of all of the plugins due to a bump in the underlying iOS native SDK and this is not an issue with the plugins themselves.
Thank you
