### ISSUE TITLE
[📚] Your documentation feedback title (CHANGE ME)

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [FirebaseExtended/flutterfire#5041]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:
I think in firebase auth we need to add the implementation of the browser for phone auth or at least mentioning it in a note with a link to the original docs. Since it is a new thing and most people get confused about it. The reCaptcha thingy that happens for a second.

in Android, this is what I know but I didn't try iOS yet:

add this to `app/build.gradle`:
`implementation "androidx.browser:browser:1.2.0"`

and enable android device verification API for your project

**Comment by markusaksli-nc** [comment]
Closing since this isn't relevant anymore
