### ISSUE TITLE
🐛 [cloud_firestore] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

### ISSUE THREAD

**Issue by sureace** [FirebaseExtended/flutterfire#5048]
## Getting error like Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

**Describe the bug**
When i try to make any firebase call, i am getting issue like "Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds. This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend. "

But wifi network is perfectly working fine. I am able to access internet without any issue. when i turn off wifi and turn on Mobile data network, then it start working. One more strange issue is, some times i can not access firebase console cloud firestore database with wifi network. I don't have any firewalls. I am using Firebase Blaze plan. Cloud Storage rules are set to read.

We can't say user to choose Mobile data network instead of wifi right. Could you please tell me what should i do. What is the issue firebase has to work with WIFI.

Flutter doctor
---------------
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

• No issues found!

Pubspec.yaml
---------------
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^0.5.5
  cross_connectivity: ^2.0.1
  provider: ^4.3.3
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  google_sign_in: ^4.5.9
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.7
  meta: ^1.2.4
  sign_in_with_apple: ^2.5.4
  pin_code_fields: ^6.0.2
  sms_autofill: ^1.2.7
  bot_toast: ^3.0.5
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1
  sqflite: ^1.3.2+3
  rxdart: ^0.25.0
  introduction_screen: ^1.0.9
  dots_indicator: ^1.2.0
  qr_code_scanner: ^0.3.4
  mqtt_client: ^8.2.0
  flutter_slidable: ^0.5.7
  wifi: ^0.1.5
  dio: ^3.0.10
  country_pickers: ^1.3.0
  crypto: ^2.1.5
  cryptography: ^1.4.1
  shimmer: ^1.1.2
  local_auth: ^0.6.3+4
  cupertino_icons: ^1.0.0

Thanks
Sureace

**Comment by markusaksli-nc** [comment]
Hi @sureace 
Is this with a release build on a physical device or just a debug build on an emulator?
Thank you

**Comment by Maverick099** [comment]
I am also facing the same issue while running the app on the emulator.
