### ISSUE TITLE
: 'package:firebase_auth/src/firebase_auth.dart': Failed assertion: line 633 pos 12: 'codeAutoRetrievalTimeout != null': is not true.

### ISSUE THREAD

**Issue by RahulSharma-ji** [FirebaseExtended/flutterfire#5063]
new version

error:
E/flutter (31725): #4      LoginScreen.build.<anonymous closure>
package:MDUchampion_p1/LoginScreen.dart:134
E/flutter (31725): #5      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter (31725): #6      _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter (31725): #7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (31725): #8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (31725): #9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (31725): #10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter (31725): #11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter (31725): #12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter (31725): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (31725): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (31725): #15     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:120
E/flutter (31725): #16     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:106
E/flutter (31725): #17     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:358
E/flutter (31725): #18     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter (31725): #19     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter (31725): #20     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter (31725): #21     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter (31725): #22     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter (31725): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (31725): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31725): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (31725): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (31725): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (31725):

**Comment by markusaksli-nc** [comment]
Hi @RahulSharma-ji 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
