### ISSUE TITLE
Firebase ML kit operation progress

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#507]
As at the time of creating this issue, there's no way to monitor the progress of a Firebase ML kit operation such as text recognition performed over a network. 

It's possible that I just use a CircularProgressIndicator until the Future in which I'm running the operation is complete but I think this would make for a good UX since users can now know how far their ML recognition process has gone in percentage.

Something like this is possible in Firebase Storage Upload, but I've scratched through the ML kit docs and found nothing like it.

**Comment by kroikie** [comment]
@thedejifab

The issue at https://github.com/flutter/flutter/issues/26576 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Closing this one - currently it's not supported by the underlying SDKs so it isn't possible to implement.

If it becomes available, feel free to re-create a new issue as a feature request.
