### ISSUE TITLE
firebase_messaging control on notification

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#508]
Hi,
In my app , I used FCM and have problem to control the notification (for example to remove/hide them programmatically), or use Vibration on recieve a notification or group messaging by tag of the message.
how can I do that ? I can't find any way!
thanks

**Comment by kroikie** [comment]
@1abzar

The issue at https://github.com/flutter/flutter/issues/26531 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @1abzar
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

https://github.com/FirebaseExtended/flutterfire/pull/53
https://github.com/FirebaseExtended/flutterfire/issues/1055
https://github.com/FirebaseExtended/flutterfire/issues/766
https://github.com/FirebaseExtended/flutterfire/issues/829

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
