### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/firebase_firestore/query/63713a56-5907-449c-a9d4-3520145d7545)

### ISSUE THREAD

**Issue by oussaid1** [FirebaseExtended/flutterfire#5088]
please help ,  i keep getting this after null safety upgrade.

Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel plugins.flutter.io/firebase_firestore/query/63713a56-5907-449c-a9d4-3520145d7545:
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/firebase_firestore/query/63713a56-5907-449c-a9d4-3520145d7545)

When the exception was thrown, this was the stack
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:545
<asynchronous suspension>

flutter doctor -v
[✓] Flutter (Channel beta,
    1.26.0-17.6.pre, on Linux, locale
    en_GB.UTF-8)
    • Flutter version 1.26.0-17.6.pre at
      /home/oussaid/snap/flutter/common/
      flutter
    • Framework revision a29104a69b (4
      days ago), 2021-02-16 09:26:56
      -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build
      2.12.0-259.12.beta)

[✓] Android toolchain - develop for
    Android devices (Android SDK version
    30.0.3)
    • Android SDK at
      /home/oussaid/Android/Sdk
    • Platform android-30, build-tools
      30.0.3
    • Java binary at:
      /snap/android-studio/current/andro
      id-studio/jre/bin/java
    • Java version OpenJDK Runtime
      Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at
      /snap/android-studio/current/andro
      id-studio
    • Flutter plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/plug
      in/9212-flutter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plug
      in/6351-dart
    • android-studio-dir =
      /snap/android-studio/current/andro
      id-studio
    • Java version OpenJDK Runtime
      Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • ONEPLUS A5000 (mobile) • 7ccf9fe0
      • android-arm64  • Android 10 (API
      29)
    • Chrome (web)           • chrome
      • web-javascript • Google Chrome
      88.0.4324.182

• No issues found!

**Comment by oussaid1** [comment]
I tried:
- flutter clean then flutter pub get .
- changed flutter channel from dev to beta 
- created new project and setup firebase 
- all my projects work fine before null safety upgrade , as soon as i upgrade the packages , i get this error 
the firebase_auth works fine.

**Comment by markusaksli-nc** [comment]
Hi @oussaid1 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5083.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by oussaid1** [comment]
Thank you so much for your service, i have applied a workaround ,
Thanks again.
