### ISSUE TITLE
Cloud Firestore: document more about the stream returned by the  `snapshots` methods of the `Query` and `DocumentReference` classes

### ISSUE THREAD

**Issue by vinayluzrao** [FirebaseExtended/flutterfire#5090]
The following information is very useful, but missing: 
1) which kind of stream it is (https://dart.dev/tutorials/language/streams#two-kinds-of-streams)
2) exactly when firestore reads start and stop occuring:
- do they start before or after `.listen`ing?
- do they continue even after `.cancel`ing the `StreamSubscription`?
- in case it is a broadcast stream, do they stop once every `StreamSubscription` has been `.cancel`led?

It is important for a user of the method to know this in at least two scenarios:
- minimizing the amount of performed Firestore reads
- avoiding a bug in case of multiple subscriptions to `.snapshots()` and it turning out to be a single subscription stream. This bug can be quite hard to catch, especially heavy use of stream transformations, for example, using something like the `rxdart` library.

**Comment by SoftMaster19** [comment]
Until we get a definitive answer, the runtimeType of the returned stream is an internal _MapStream, and it's isBroadcast property is true.

**Comment by rrousselGit** [comment]
As far as I know, all streams in firebase are broadcast streams that are active only if there's at least one listener.

**Comment by Ehesp** [comment]
> which kind of stream it is (dart.dev/tutorials/language/streams#two-kinds-of-streams)

It's a broadcast stream, you can see the returned stream [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart#L106)

> exactly when firestore reads start and stop occuring:

When you call `listen` on returned stream, a native event is fired to subscribe to events within the native SDKS.

Internally, this creates an EventChannel, which native posts data to and Dart subscribes to. Each time there's an event, a snapshot is created and forwarded onto the initial stream.

When you `cancel` the stream, the EventChannel stream is also cancelled, which signals to native to also stop subscribing.

To answer your quesions:

- do they start before or after .listening? : After
- do they continue even after .canceling the StreamSubscription? : Nope
- in case it is a broadcast stream, do they stop once every StreamSubscription has been .cancelled? : Yes

I'll close, but feel free to ask anymore questions.
