### ISSUE TITLE
Cloud Firestore: document whether calling `.snapshots` multiple times with the same query will have the reads be shared or not

### ISSUE THREAD

**Issue by vinayluzrao** [FirebaseExtended/flutterfire#5091]
It is unclear whether calling the method `.snapshots()` (and consequently `.listen(...)`), of the`Query` and `DocumentSnapshot` classes, multiple times and with the same "logical" query (i.e. not necessarily the same `Query` or `DocumentSnapshot` object, but with identical querying parameters) will:
- multiply the amount of reads, or
- have the optimization where the reads are shared among all listeners.

This is very useful information for properly minimizing the read cost and client network bandwidth usage.

**Comment by lukaszciastko** [comment]
IMO, the amount of reads should go up, as this is how Streams work. You need to share the Stream yourself - e.g. by using ValueConnectableStream from RxDart.

**Comment by rrousselGit** [comment]
cc @Salakar, looks familiar to a discussion we had previously

So if my understanding is correct, Firebase shares the reads across snapshots streams.  
The first value pushed on a new stream is from the offline cache. And following values are pushed to all snapshots at once.

**Comment by russellwheatley** [comment]
In a nutshell; if you create two different `Query` instances with the exact same parameters, the `Query.snapshot()` observers will read from the database twice (AFAIK). As mentioned, you should share the `Stream` instance in your code created by the `Query.snapshot()`.
