### ISSUE TITLE
Firebase Auth authStateChanges doesn't work

### ISSUE THREAD

**Issue by RAHEYO** [FirebaseExtended/flutterfire#5095]

**Comment by RAHEYO** [comment]
`import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:google_fonts/google_fonts.dart';

import './screens/chat_screen.dart';
import './screens/login_or_sign_up_screen.dart';
import './screens/auth_screen.dart';
import './constants.dart';
import './databases/fire_auth.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light().copyWith(
        buttonTheme: ThemeData.light().buttonTheme.copyWith(
              buttonColor: kSecondaryWhite,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(7)),
            ),
        primaryColor: kPrimaryBlack,
        accentColor: kSecondaryWhite,
        textTheme: GoogleFonts.arvoTextTheme(),
      ),
      initialRoute: '/',
      builder: EasyLoading.init(),
      routes: {
        '/': (context) => StreamBuilder<User>(
              stream: FirebaseAuth.instance.userChanges(),
              builder: (context, snapshots) {
                if (snapshots.connectionState == ConnectionState.active) {
                  if (snapshots.hasData) {
                    return ChatScreen();
                  } else {
                    return AuthScreen();
                  }
                } else {
                  return Container();
                }
              },
            ),
        ChatScreen.id: (context) => ChatScreen(),
        AuthScreen.id: (context) => AuthScreen(),
        LoginOrSignUpScreen.id: (context) => LoginOrSignUpScreen(),
      },
    );
  }
}
###

**Comment by markusaksli-nc** [comment]
Hi @RAHEYO 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
