### ISSUE TITLE
Messaging send-with-console link is outdated and results in 404

### ISSUE THREAD

**Issue by markbeij** [FirebaseExtended/flutterfire#5097]
At https://pub.dev/packages/firebase_messaging#sending-messages there's a link to https://firebase.google.com/docs/cloud-messaging/send-with-console, which results in 404 Not found

**Comment by markusaksli-nc** [comment]
Seems like this was moved to each native subsection separately (for example https://firebase.google.com/docs/cloud-messaging/js/send-with-console)

**Comment by rrousselGit** [comment]
Closing, since the the issue was fixed
