### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by markbeij** [FirebaseExtended/flutterfire#5098]
The [documentation](https://pub.dev/packages/firebase_messaging#receiving-messages) says Data Message on Android while app is terminated: not supported by plugin, message is lost.
Why is this? I'm recreating a native app with Flutter and don't want to alter the API.
Is there any technical reason for this?

**Comment by markusaksli-nc** [comment]
Hi @markbeij 
That was true for the old version and it required a native workaround. The latest non-nullsafety version `firebase_messaging: ^8.0.0-dev.14` will work from a terminated state (unless you force-quit the app on android). The updated documentation is at https://firebase.flutter.dev/docs/messaging/usage#receiving-messages
