### ISSUE TITLE
[cloud_firestore] Android Build failing - Log attached

### ISSUE THREAD

**Issue by thecoffeehog** [FirebaseExtended/flutterfire#51]
Note: /Users/uditchugh/Desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/uditchugh/Desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/0.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/1.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/49.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/50.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/51.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/52.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/53.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/56.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/58.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/59.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/60.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/61.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/62.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/63.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/66.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/67.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/68.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/69.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/70.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/71.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/72.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/73.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/74.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/75.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/76.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/77.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/79.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/80.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/81.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/82.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/83.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/85.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/86.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/87.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/88.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/89.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/90.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/91.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/92.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/93.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/94.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/95.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/96.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/97.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/99.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/100.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/101.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/102.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/103.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/104.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/105.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/106.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/107.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/108.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/109.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/110.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/111.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/112.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/113.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/114.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/115.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/116.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/117.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/118.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/119.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/120.jar, /Users/uditchugh/Desktop/dev/pawfect/build/app/intermediates/transforms/dexBuilder/debug/121.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by crushman1** [comment]
I am also having this issue, i did all the usual stuff. This is the only thing standing between me and a good nights sleep...

**Comment by sarinupreti** [comment]
getting this error

**Comment by crushman1** [comment]
To solve this issue i had to update android studio and flutter thwn creatw a new project. Then add each dependancy one by one ensuring that the thing compiles after each dependancy is added. Took me a whole afternoon

**Comment by thecoffeehog** [comment]
In my case, it got solved by removing all dependencies from pubspec.yaml and adding them back.
