### ISSUE TITLE
Problem signing-out from Firebase

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#510]
I'm having troubble signing-out from Firebase. I'm calling `_signOut()` when I tap a button:
```dart
final GoogleSignIn _googleSignIn = GoogleSignIn();
final FirebaseAuth _auth = FirebaseAuth.instance;

static Future<void> _signOut() async {
    await _auth.signOut();
    await _googleSignIn.signOut();
  }
```
But when I call `googleUser.authentication` on my SignIn function it skips the google login page and returns a valid GoogleSignInAuthentication. It seems that the user is not properly signedOut therefore its data is used `googleUser.authentication`.
What could I do to fix this?

**Comment by kroikie** [comment]
@rma6

The issue at https://github.com/flutter/flutter/issues/26447 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @rma6
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
