### ISSUE TITLE
With Flutter didn't get firebase_in_app_messaging popup button click callback

### ISSUE THREAD

**Issue by devappbirds** [FirebaseExtended/flutterfire#5100]
we are trying to implement screen redirection base on dynamic link button click, but we didn't get code for firebase_in_app_messaging popup button click callback.

we are using below plugin :

https://pub.dev/packages/firebase_in_app_messaging

**Comment by markusaksli-nc** [comment]
Hi @devappbirds 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
