### ISSUE TITLE
[📚] Use of Firestore Emulator - HTTP connection

### ISSUE THREAD

**Issue by radvansky-tomas** [FirebaseExtended/flutterfire#5102]
Could you please add same text from Cloud Function emulators to firestore one:

https://firebase.flutter.dev/docs/functions/usage/#emulator-usage

I spend hours trying to figure out why my app does not write to emulator...and it was caused by missing plist/manifest settings allowing insecure HTTP communication :(

**Comment by markusaksli-nc** [comment]
The documentation should have something like
```dart
import 'package:flutter/foundation.dart';
//...
String host = defaultTargetPlatform == TargetPlatform.android
    ? '10.0.2.2:8080'
    : 'localhost:8080';
FirebaseAuth.instance.useEmulator('http://$host');
```
What were the missing settings exactly?

**Comment by pxsanghyo** [comment]
For android, should this...

```xml
    <application
        android:usesCleartextTraffic="true"
```

go in `android/app/src/debug/AndroidManifest.xml` instead of main like the doc says?

For iOS, is it safer to add...

```xml
<key>NSAppTransportSecurity</key>    
<dict>
    <key>NSAllowsLocalNetworking</key>
    <true/>
</dict>
```

since you don't have to remove it each time you deploy.

**Comment by russellwheatley** [comment]
The docs have been updated to reflect the necessary config.
