### ISSUE TITLE
firebase_analytics not reporting in streaming on setCurrentScreen

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#511]
If I run the `setCurrentScreen` in the example app in flutter it doesn't show up in the StreamView of Firebase Analytics.  However, if I run `setCurrentScreen` and then I run test standard event types I get all the event types logged and I get the `setCurrentScreen` event.  Is this expected behaviour?  Should I be seeing the `setCurrentScreen` event in the StreamView after I click the button?

**Comment by kroikie** [comment]
@RoughIndustries

The issue at https://github.com/flutter/flutter/issues/26432 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @RoughIndustries
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
