### ISSUE TITLE
[firebase-admob] interference  with push pole sdks 

### ISSUE THREAD

**Issue by mojanimator** [FirebaseExtended/flutterfire#5123]
this plugin uses firebase service (firebase messaging or firebase core) . the other plugins for pushpole (like signal) for flutter need listening to firebase messaging service   . when using  firebase_admob, those plugins crash and terminate their service when application run starts. 
please take me a  solution for this situation .a way to can access to this listener and add another serices to that or something else .

this is a solution (i think) for native android and i cant find a way for flutter plugins 

public class MyFCMService extends FlutterFirebaseMessagingService {
    @Override
    public void onNewToken(String s) {
        co.ronash.pushe.Pushe.getFcmHandler(this).onNewToken(s);
        super.onNewToken(s);
    }
    @Override
    public void onDeletedMessages() {
        co.ronash.pushe.Pushe.getFcmHandler(this).onDeletedMessages();
        super.onDeletedMessages();
    }
    @Override
    public void onSendError(String s, Exception e) {
        co.ronash.pushe.Pushe.getFcmHandler(this).onSendError(s, e);
        super.onSendError(s, e);
    }
    @Override
    public void onMessageSent(String s) {
        co.ronash.pushe.Pushe.getFcmHandler(this).onMessageSent(s);
        super.onMessageSent(s);
    }
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        if (!co.ronash.pushe.Pushe.getFcmHandler(this).onMessageReceived(remoteMessage)) {
            // It is for fire base, otherwise the condition will handle the message for Pushe
            super.onMessageReceived(remoteMessage);
        }
    }
}

**Comment by markusaksli-nc** [comment]
Hi @mojanimator 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by mojanimator** [comment]
i said the issue .there is no problem example. this two plugins not works together due to firebase listener
