### ISSUE TITLE
[📚] [firebase_messaging] Please update the documentation for how to navigate from within onLaunch/onResume 

### ISSUE THREAD

**Issue by MilesAdamson** [FirebaseExtended/flutterfire#5126]
The following is found on https://pub.dev/packages/firebase_messaging for handling notifications being tapped:

```
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        _showItemDialog(message);
      },
      onBackgroundMessage: myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        _navigateToItemDetail(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
        _navigateToItemDetail(message);
      },
    );
```

The example project linked 404's, and the example project actually in the repo does not show how to navigate in these methods without a `BuildContext`.

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/example

It is not clear how one would navigate somewhere in the app from a top-level function without a navigator or build context, but it is implied it is possible in your example code.

**Comment by markusaksli-nc** [comment]
Closing since this is no longer relevant

**Comment by brunovsiqueira** [comment]
@markusaksli-nc why is it not relevant? I can't update my dependency to the last version due to the fact I am not using null saftery yet. So, I need to use 8.0.0-dev.14 which has the mentioned problem.

**Comment by markusaksli-nc** [comment]
`configure()` was already removed as of `8.0.0-dev.1` in favor of calling specific static methods which return Streams. This is also why there is no mention of it anymore in either the pub.dev page, or the official documentation, or the official code example. The last non-nullsafety version `8.0.0-dev.14` you are using no longer has the method. As the method has been removed and the new version is in stable there no longer should be any documentation for it.

As for the official example link, it's true it seems to break all quite often and we try to fix them whenever that happens. You can always more easily find the latest official example for every Flutterfire package from the `example` directory of the package in this repository. For firebase messaging it is in:

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
