### ISSUE TITLE
[firebase_ml_vision] example about processing byte stream from image

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#513]
Hi,
in firebase_ml_vision example
https://github.com/flutter/plugins/blob/master/packages/firebase_ml_vision/example/lib/main.dart
i can't find an example to process text recognition from new method FirebaseVisionImage.fromBytes (not file path).

Please can you update this officiale example code to understand how to use
- method FirebaseVisionImage.fromBytes
- Uint8List param (maybe obtained by CameraPreview class of Camera package)
- FirebaseVisionImageMetadata

Thank you!
Lewix

**Comment by kroikie** [comment]
@lewixlabs

The issue at https://github.com/flutter/flutter/issues/26361 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @lewixlabs
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

https://github.com/flutter/flutter/issues/26348

**Comment by lewixlabs** [comment]
Hi,
no latest firebase_ml_vision work without issues, I can get image stream (with camera plugin) and extract data from it.
You can find my example project,  not update anymore but you can use it as starting point.
https://github.com/lewixlabs/mlkit_ocr_realtime

Hi,
Lewix

**Comment by iapicca** [comment]
Hi @lewixlabs
given your last message I feel safe to close this issue,
if you disagree please write in the comments 
and I will reopen it. 
Thank you
