### ISSUE TITLE
[plugin] Firebase message notification with actions

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#514]
I need to add some actions in my notifications (like `reply`, `delete`, `mark as read`...). I wonder how it's possible with this plugin ? 

From what I know on iOS you need to set the category under `click_action` but from the doc of the plugin `click_action` need to be set to `FLUTTER_NOTIFICATION_CLICK` so impossible to do more than one category. 

For Android, there no way to add actions on our notification because the plugin is showing the notification by itself and from what I know we can't hook those to add our actions.

So it would be nice if we can put whatever we want on `click_action` like this we can set category for iOS. 

On Android side, would be nice to be able to set all possible values of our `click_action` on the manifest like we have to do with `FLUTTER_NOTIFICATION_CLICK` and also notify the plugin that those values need to be used like a notification click. 
We also need a hook on the plugin to add one or more actions to the notification that will be added. 

Of course it will force us to do native code, but for this I don't see any other options. For now the plugin only allow you to do really basic notifications, it should be more flexible.

**Comment by kroikie** [comment]
@jaumard

The issue at https://github.com/flutter/flutter/issues/26358 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/22099

**Comment by Ehesp** [comment]
This functionality should live in a 3rd party plugin, https://pub.dev/packages/flutter_local_notifications for example.

Messaging is responsible for receiving and sending messages via FCM, and displaying basic notifications when the app is in the background (via the native SDKs).

**Comment by jaumard** [comment]
@Ehesp I'm not agree with that, FCM give us the ability to do such customizations, why the plugin should not support those and do only basic notifications ?

**Comment by Ehesp** [comment]
FCM doesn't provide that functionality, it only provides support for basic notifications (title, body, image). The notification SDKs provide support for building rich notifications, which are classed as "local notifications".

**Comment by Salakar** [comment]
Closing in favour of using `flutter_local_notifications` for this functionality.
