### ISSUE TITLE
[📚] Example link is returning Page not found

### ISSUE THREAD

**Issue by rahul-lohra** [FirebaseExtended/flutterfire#5140]
Link to documentation - https://pub.dev/packages/firebase_messaging
Please see the attached screenshot and the highlighted text. The link is giving page not found
![image](https://user-images.githubusercontent.com/9371518/109079520-0ec1a880-7725-11eb-971e-f1dc53fddf9e.png)

**Comment by markusaksli-nc** [comment]
Closing since this is no longer relevant
