### ISSUE TITLE
🐛  Flutter iOS App Crashing with "Default app has already been configured"

### ISSUE THREAD

**Issue by HadyMash** [FirebaseExtended/flutterfire#5147]
## Bug report

**Describe the bug**
When I add the Firebase packages to the iOS files, the app crashes.

### Steps to reproduce

1. Create a new application (doesn't matter if you change the home screen layout).
2. Add a Bundle id from Xcode
3. Create a new Firebase iOS Application
4. Add the Bundle ID and nickname the app anything, leave the App Store ID empty
5. Download GoogleService-Info.plist and add it to Runner/Runner from Xcode
6. Add the following to the Podfile:
```
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
```
7. Run `pod install`
8. Add the `import Firebase` to the top of the AppDelegate file
9. Add `FirebaseApp.configure()` before the return statement in the last function below the `Bool`
10. Add the following packages to the pubspec.yaml file
```
firebase_core: ^0.7.0
firebase_auth: ^0.20.1
cloud_firestore: ^0.16.0+1
```
11. Make the `main()` function asyncronous by adding `async` before the curly brace.
12. Add the following before the `runApp();` function:
```
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
```
13. Import `firebase_core` package into main.dart.
14. Navigate to the flutter application location and open the iOS directory with Xcode.
15. Apply any recommended changes, Xcode should do them automatically (the recommended changes I got were to update the minimum version to iOS 12.0 in multiple files. They also should appear as warnings and not errors.
16. Run the app.
17. It should crash

### Expected behavior

The app to run normally. The default template app should run with no errors in the debug console.

---

## Additional context
*The project runs normally on Android, the issue occurs just on iOS.
I use VS Code as my main IDE so I ran the project from there.
I tried running it from XCode and got the following exception:
```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (8435CB31-AB36-4803-8F23-AC223243A180) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12 Pro Max
```

Xcode then highlighted the error to be here:
![Screen Shot 2021-02-25 at 4 20 49 PM](https://user-images.githubusercontent.com/63734405/109160840-c095bf00-778f-11eb-9fd8-0038a7a7d53a.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.27.0-9.0.pre.85, on macOS 11.2.1 20D74
    darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0-73.0.dev
Flutter SDK 1.27.0-9.0.pre.85
firebase_ios_test 1.0.0+1

dependencies:
- cloud_firestore 0.16.0+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.2
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 3.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0

```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @HadyMash 
I don't exactly understand. Did you add the firebase packages manually in the podfile? There is no need to do that. Please follow the official documentation at 
https://firebase.flutter.dev/docs/installation/ios 
https://firebase.flutter.dev/docs/auth/overview 
https://firebase.flutter.dev/docs/firestore/overview/
Thank you

**Comment by HadyMash** [comment]
Hello @markusaksli-nc,
Thank you for your reply.

What I did was follow the instructions on Firebase when adding an iOS app.
I did not add the Firebase packages manually to the Podfile. What I download the plist file, added it to Runner/Runner, then I went to the Podfile and at the very end added the 2 lines Firebase told me to add:

> `# add pods for desired Firebase products`
> `# https://firebase.google.com/docs/ios/setup#available-pods`

Then I ran pod install.
I also added the packages to the pubspec.yaml file.

The only thing I did differently to the instructions you sent was drag the .plist file into the Runner Folder inside of the Runner in the .xcworspace (runner/runner) instead of right clicking runner and then selecting the add a file option.

Please let me know if this helps or if you need any more information or clarification. I will try to create a new app and use the add file option from the right click menu instead and let you know how it goes. Thank you for your help!

**Comment by HadyMash** [comment]
I tried again and everytime I follow the instructions on Firebase when adding an app, the app crashes and won't start up with the same exception. The problem seems to be with the AppDelegate file as that is where the exception occurs.

**Comment by HadyMash** [comment]
I got it to work. What I was doing before was following all the instructions on Firebase when adding an iOS app and not a Flutter app. All I needed to do was just add the .plist file and Flutter would do the rest.

**Comment by pankrys** [comment]
@HadyMash I have some problem. Where did you found instructions for Flutter app? I see only for "iOS add application" on my Firebase app application page.

**Comment by HadyMash** [comment]
Hello @pankrys, I hope your doing well.

The instructions are not on the adding an app screen on Firebase, you would still click on an iOS app but you wouldn't follow all of the instructions.

All you need to do is add the bundle id on firebase. Then download the .plist file and add it to the runner folder inside of Xcode (Runner/Runner), then add the the firebase packages to the pubspec.yaml file and when you run your app flutter will do the rest. You do not need to do anything to your podfile or the appdelegate or any other files. Flutter will do all of that for you. That should be all.

So to make it into short steps:
1. Add the Bundle ID into firebase
2. Download the GoogleServices-Info.plist and add it to the runner folder from Xcode
3. Add Firebase core (and other firebase packages you want) to the pubspec.yaml file.
4. Ignore the rest of the instructions on Firebase and your app should work, running it should fix all the problems.

Here's a video that should help: https://youtu.be/Mx24wiPilHg?t=234

Hope this helps, if you need any more clarification, please let me know!
