### ISSUE TITLE
[📚] Inconsistency in instructions for FCM

### ISSUE THREAD

**Issue by jimmyff** [FirebaseExtended/flutterfire#5150]
Package docs says add an intent-filter, mifration docs says this is old and should be removed. Maybe I've misread but I'm confused now?

---

Readme for FCM packages:
https://pub.dev/packages/firebase_messaging

```
Note: When you are debugging on Android, use a device or AVD with Google Play services. Otherwise you will not be able to authenticate.

(optional, but recommended) If want to be notified in your app (via onResume and onLaunch, see below) when the user clicks on a notification in the system tray include the following intent-filter within the <activity> tag of your android/app/src/main/AndroidManifest.xml:

  <intent-filter>
      <action android:name="FLUTTER_NOTIFICATION_CLICK" />
      <category android:name="android.intent.category.DEFAULT" />
  </intent-filter>
```
---

Migration documentation:
https://firebase.flutter.dev/docs/migration/

```
Messaging only: If you added the previous versions intent-filter to your android/app/src/main/AndroidManifest.xml file, remove it:

- <intent-filter>
-    <action android:name="FLUTTER_NOTIFICATION_CLICK" />
-    <category android:name="android.intent.category.DEFAULT" />
- </intent-filter>
```

**Comment by helenaford** [comment]
Hey, could you link me to the README where it mentions to add intent-filter? failing to see it right now.

But, I'd go with the migration guide though, as I believe that's kept up-to-date, and also matches the docs: https://firebase.flutter.dev/docs/messaging/overview

**Comment by jimmyff** [comment]
Huh, that's so weird. I could have sword I just copied & pasted the URLs that I took the extracts from but I can only assume I must have been looking at v7.0.3: https://pub.dev/packages/firebase_messaging/versions/7.0.3

Weird, sorry about that!
