### ISSUE TITLE
Error updating information on Firebase

### ISSUE THREAD

**Issue by Alvaro-99** [FirebaseExtended/flutterfire#5161]
Hello! I want to update information on the database on Firebase with the following code:

class _PostXXXState extends State {
var _isLiked = false;
var likesCount;
var key;

int getLikesCount(likes) {
var likes = this.widget.likes;
var key = this.widget.key.toString();
if (likes != null && _isLiked == true) {
likesCount = likes + 1;
FirebaseFirestore.instance.collection('post').doc('Post XXX').collection('posts').doc(key).update({'likes': likesCount});
return likesCount;
}
}
}

When I type the code above, I keep getting the same error on my debug console:
"[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: [cloud_firestore/not-found] Some requested document was not found.
#0 MethodChannelDocumentReference.update
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:59

#1 DocumentReference.update
package:cloud_firestore/src/document_reference.dart:98
#2 _PostStatsXXXState.getLikesCount
package:projectXXX/…/post_xxx/post_stats_xxx.dart:79
#3 _PostStatsXXXState.build
package:projectXXX/…/post_xxx/post_stats_xxx.dart:114
#4 StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#5 ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#6 StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
#7 Element.rebuild
package:flutter/…/widgets/framework.dart:4343
#8 BuildOwner.buildScope (package:flutter/src/wid<…>"

From my understanding, the problem is the "doc(key)", where flutter cannot identify which document to update. How do I fix this?

Thanks!

**Comment by Alvaro-99** [comment]
The problem is that the document already exists, I only need to update the number of likes every time a user clicks on the "like" button. When I replace the "key" for the actual path for a specific document, it does work, but for some reason when I put the "key" = path (so that it is done dynamically each document that has been pressed "like"), it does not recognize that there is a valid path. So my question, is how can I fix this? Thanks

**Comment by Alvaro-99** [comment]
I think the problem is in my logic to bring the key (I must have done something wrong). I just checked, the problem is that actual "key" of the document is **KQWB9MLzWkYHMgLH1r0v** (this the actual existing key of one of the docs), but when I use the "key" in my code, the "key" is **[<'KQWB9MLzWkYHMgLH1r0v'>]**  , which makes flutter think that the document does not exist. Do you know how I can get rid of the **[<'** does is placed before and after the actual key? Thanks

**Comment by rish07** [comment]
@Alvaro-99 
```
String key = "[<'KQWB9MLzWkYHMgLH1r0v'>]";
  key = key.split("'")[1];
```

**Comment by markusaksli-nc** [comment]
Hi @Alvaro-99 
When opening an issue, please choose the correct category and try to provide all of the information indicated in the template.
Closing this issue, since it isn't a documentation issue and no information has been provided.
Thank you.
