### ISSUE TITLE
[firebase_admob] (ios) Some apps haven't been configured to use Apple's SKAdNetwork

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#5163]
## admob console

Some apps haven't been configured to use Apple's SKAdNetwork To ensure you're getting credit for all ads activity, like app installs, be sure to configure SKAdNetwork with Google's network IDs.

--
which i had updated as described in the section

https://developers.google.com/admob/ios/ios14?hl=en-GB#skadnetwork

**Comment by peterweb2005** [comment]
may close?
cant see the notification these days

**Comment by markusaksli-nc** [comment]
Closing as solved then
