### ISSUE TITLE
push notification to topics via REST

### ISSUE THREAD

**Issue by kururu-abdo** [FirebaseExtended/flutterfire#5178]
i have tried to push notification to specific topic
i followed the documentation but i  found that the object has 'to' key
and i changed it to 'topic' key
but this  idea has not succeed:(

`var response = await http.post(
    'https://fcm.googleapis.com/fcm/send',
     headers: <String, String>{
       'Content-Type': 'application/json',
       'Authorization': 'key=$serverToken',
     },
     body: jsonEncode(

// <String ,dynamic>{
//   "message":<String ,dynamic>{
//   "topic" :"general" ,
//  'to': await firebaseMessaging.getToken(),
//   "notification": <String ,dynamic>{
//         "body":"This is an FCM notification message!",
//         "title":"FCM Message"
//       },

//   'priority': 'high',

//   "data" : <dynamic ,dynamic>{
//          'click_action': 'FLUTTER_NOTIFICATION_CLICK',
//          'id': '1',
//          'status': 'done' ,
//          'screen' :'Lectures'
//       }
//   }
// }

     <String, dynamic>{
       'notification': <String, dynamic>{
         'body': 'there are new lecture added for you ,   check it now!',
         'title': 'new lecure Added'
       },
       'topic':'general',
       'priority': 'high',
       'data': <String, dynamic>{
         'click_action': 'FLUTTER_NOTIFICATION_CLICK',
         'id': '1',
         'status': 'done' ,
         'screen' :'Lectures'
       },
      // 'to': await firebaseMessaging.getToken(),
    },
    ),

  );

`

**Comment by markusaksli-nc** [comment]
Hi @kururu-abdo 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
