### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by vogttho** [FirebaseExtended/flutterfire#5183]
Since all of these issues are closed I create a new one. For me and as I can see many others this is still an issue. It's breaking! I am not able to continue with my project!

Because http >=0.13.0 depends on http_parser ^4.0.0 and firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, http >=0.13.0 is incompatible with firebase >=7.0.0 <9.0.0.
And because firebase_storage >=8.0.0 depends on firebase_storage_web ^1.0.0 which depends on http ^0.13.0, firebase >=7.0.0 <9.0.0 is incompatible with firebase_storage >=8.0.0.

**Comment by markusaksli-nc** [comment]
Hi @vogttho 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
