### ISSUE TITLE
🐛 [Cloud Firestore]  fatal error: module     'cloud_firestore' not found

### ISSUE THREAD

**Issue by imdarpn** [FirebaseExtended/flutterfire#5197]
## Bug report

**Describe the bug**
[Cloud Firestore]  fatal error: module     'cloud_firestore' not found

**Pub dependencies**

dependencies:
  flutter:
    sdk: flutter
  flutter_twitter_login:
    git: git://github.com/eudangeld/flutter_twitter_login.git
  cached_network_image: ^2.1.0
  cloud_firestore: ^0.14.3
  connectivity: ^0.4.2

  cupertino_icons: ^0.1.2
  dio: ^3.0.8
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0

  firebase_auth: ^0.18.0+1
  firebase_crashlytics: ^0.2.3
  firebase_database: ^4.0.0
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_facebook_login: ^3.0.0
  flutter_launcher_icons: ^0.7.5

  flutter_libphonenumber: ^0.3.11
  flutter_page_transition: ^0.1.6
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.2
  snapchat: ^0.0.2
  flutter_svg: ^0.18.0

  flutter_tags: ^0.4.8+2
  flutter_typeahead: ^1.8.0
  fluttertoast: ^7.1.0
  font_awesome_flutter: ^8.5.0
  geocoder: ^0.2.1
  geocoding: ^1.0.5
  geolocator: ^6.1.1
  getflutter: ^1.1.3
  google_maps_flutter: ^0.5.33
  google_maps_place_picker: ^0.10.0
  google_sign_in: ^4.5.6

  http: ^0.12.2
  image_cropper: ^1.3.0
  image_picker: ^0.6.5+2
  intl: ^0.16.1
  intl_phone_number_input: ^0.5.2+2
  jiffy: ^3.0.1
  libphonenumber: ^1.0.2
  location: ^3.0.2

  lottie: ^0.7.0+1
  page_transition: ^1.1.5
  page_view_indicators: ^1.3.1
  path_provider: ^1.4.0

  pin_code_fields: ^6.0.1
  provider: ^4.0.1

  recase: ^3.0.1
  rxdart: ^0.24.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.3+4
  shimmer: ^1.1.2
  simple_auth: ^2.0.7
  simple_auth_flutter: ^2.0.4

  sliding_up_panel: ^1.0.2
  snapchat_flutter_plugin: ^0.0.3+2
  speech_bubble: ^0.0.6
  steps_indicator: ^0.3.1
  syncfusion_flutter_core: ^18.4.31
  syncfusion_flutter_sliders: ^18.4.30-beta
  timeago: ^2.0.26
  url_launcher: ^5.7.2
  walkthrough: ^0.0.3
  webview_flutter: ^0.3.22+1
  firebase_remote_config: ^0.3.1+1
  
  
  **Flutter Doctor**
  
  
  [✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/home/code/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/home/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/home/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 1660D7FC-9C03-4295-A47D-0B689681F7A6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

**Comment by markusaksli-nc** [comment]
Hi @imdarpn 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
