### ISSUE TITLE
Add firebase_admob: ^0.9.0+6 and execute 'flutter build apk' with Gradle task assembleRelease failed with exit code 1

### ISSUE THREAD

**Issue by AuXue** [FirebaseExtended/flutterfire#52]
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0.5s
Resolving dependencies...                                           1.4s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       1.1s
Gradle task assembleRelease failed with exit code 1

Remove firebase_admob: ^0.9.0+6 works fine

**Comment by geekydiamond** [comment]
I'm getting the same problem on both assembleDebug and assembleRelease

**Comment by dipinarora9** [comment]
I am facing the same issue. Moreover, I tried running the old code of my app (that was working earlier), but that is also giving me the same error.

I have tried everything from changing the distribution url to changing the build gradle tools version.

Somebuddy please help!

**Comment by BondarenkoStas** [comment]
@AuXue Please report if the issue is resolved

**Comment by crossplatfrom** [comment]
@dipinarora9 This worked but also had to edit android\app\build.gradle to add the below settings:

defaultConfig {
  ...
  multiDexEnabled true
}

**Comment by dipinarora9** [comment]
@crossplatfrom yes true..
I forgot to mention it earlier. Thanks for the informative!

**Comment by BondarenkoStas** [comment]
@crossplatfrom Thank you! Then I think it's safe to close, you comment will be helpful for community.
