### ISSUE TITLE
[plugin] firebase_messaging: onMessage, onResume and onLaunch should be Stream

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#520]
📦 [firebase_messaging](https://pub.dartlang.org/packages/firebase_messaging) is really helpful to me. I'm grateful to the creator of this package, but I have more proper idea of API to receive/consume messages.

You know, there's Stream in Dart and almost all of similar things with these are made of Stream. I think `FirebaseMessaging#configure()` should be deleted and replaced with the API like following instead.

- `FirebaseMessaging`
    - `Stream<Map<String, dynamic>> get FirebaseMessaging.onMessage`
    - `Stream<Map<String, dynamic>> get FirebaseMessaging.onResume`
    - `Stream<Map<String, dynamic>> get FirebaseMessaging.onLaunch`

I just want to know what you think about this idea. Thank you for your reading.

Also here is wrapper to handle messages with Stream (for now): https://gist.github.com/axross/1f5129204ae9ab0b75e491ddf3702d90

**Comment by kroikie** [comment]
@axross

The issue at https://github.com/flutter/flutter/issues/26129 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Closing this one - no plans to support them as streams as this would require breaking changes.
