### ISSUE TITLE
FirebaseMessaging( 5810): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

### ISSUE THREAD

**Issue by JeanUGit** [FirebaseExtended/flutterfire#5204]
Problemas al utilizar onBackgroundMessage() de la libreria de firebase_messaging

**Comment by markusaksli-nc** [comment]
Hi @JeanUGit 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
