### ISSUE TITLE
🐛 [V1 vs 0.*] A v1 in components contains a v0.2.0 support

### ISSUE THREAD

**Issue by comlaterra** [FirebaseExtended/flutterfire#5209]
## Bug report

`firebase_analytics` is defined as `v1` but in its support web is `0.2.0`. 
Aee [Analytics Pubspec.yaml](https://github.com/FirebaseExtended/flutterfire/blob/48f7dd7f919bde3e5ed1c73d5c5e27458b51e5dd/packages/firebase_analytics/firebase_analytics/pubspec.yaml#L17)

> The minimum support version is the maximum version of the component.

The most clear example is the Firebase Analytics ( see [Analytics Pubspec.yaml](https://github.com/FirebaseExtended/flutterfire/blob/48f7dd7f919bde3e5ed1c73d5c5e27458b51e5dd/packages/firebase_analytics/firebase_analytics/pubspec.yaml#L17) )

### Steps to reproduce

Visit the [Analytics Pubspec.yaml](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/pubspec.yaml)

### Expected behavior

If `firebase_analytics` is `v1`, all it's "versions" must meet the same quality standard.

As I see it, the options are:
* Upgrade `firebase_analytics_web` to `v1`
* Downgrade `firebase_analytics` to under `v1`
* Remove the `firebase_analytics_web: ^0.2.0` dependency.

## Additional context

The impact of this issue is that the support to a certain platforms negatively impact the support to major platforms, the component may be used as stable `v1` version, but you have to deal with the dependency tree of a `0.2.0` version.

**Comment by markusaksli-nc** [comment]
Hi @comlaterra 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5202.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
