### ISSUE TITLE
🐛 [firebase_analytics] Firebase analytics web dependency problem

### ISSUE THREAD

**Issue by Zeynal7** [FirebaseExtended/flutterfire#5210]
##  Firebase analytics WEB dependency problem. Need to update WEB dependency from firebase to latest version

1. Firebase analytics WEB depends on firebase ^7.3.0 (latest is 9.0.0)
2. firebase ^7.3.0 depends on http >=0.11.3 <0.13.0
3. And I am using http 0.13.0
If someone can, please update version of firebase in analytics_web to latest (null safe) version. Thanks.

I don't use web version, if there is any way to exclude web version, please, let me know.

**Comment by dukaric1991** [comment]
Same issue here.

**Comment by cbenhagen** [comment]
@dukaric1991 please just add a 👍 instead of adding "same issue here" comments. This just sends unnecessary notifications to everyone subscribed to an issue. Thanks :)

**Comment by bhagirath** [comment]
Because every version of firebase_analytics_web depends on firebase ^7.3.0 which depends on http >=0.11.3 <0.13.0, every version of firebase_analytics_web requires http >=0.11.3 <0.13.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0, firebase_analytics >=7.1.0 requires http >=0.11.3 <0.13.0.

**Comment by NebiSarigul** [comment]
Important issue.

**Comment by dsgriffin** [comment]
any temporary solution for this?

**Comment by markusaksli-nc** [comment]
Hi @Zeynal7 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5202.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
