### ISSUE TITLE
[firebase_crashlytics] Support for Flutter Web?

### ISSUE THREAD

**Issue by verscph** [FirebaseExtended/flutterfire#5211]
Hi,

Are there any plans to get Crashlytics supported for Flutter Web?

Tx!

**Comment by markusaksli-nc** [comment]
Hi @verscph 
You can see our plans at https://github.com/FirebaseExtended/flutterfire/issues/2582
As for your question, this repository only wraps the upstream native Firebase SDKs. As there is no JS Crashlytics SDK for Web yet (only Android, iOS, and Unity), we cannot implement it. You can file a feature request for it at [Firebase Support](https://firebase.google.com/support/troubleshooter/report/features)
Thank you
