### ISSUE TITLE
[📚] IOS notifications not working

### ISSUE THREAD

**Issue by VladislavYakonyuk** [FirebaseExtended/flutterfire#5223]
Executed await Firebase.initializeApp(); 
Calling FirebaseMessaging.onMessage.listen(_firebaseMessagingService.onMessage);

I send notification via firebase console, but nothing comes to IOS. 

firebase_messaging: ^8.0.0-dev.1

I can't find the necessary native code for IOS in the documentation, I checked everything on the IOS Simulator

**Comment by helenaford** [comment]
Hi, for iOS you need to test on a real device. Messaging doesn't work on the simulator sadly. https://firebase.flutter.dev/docs/messaging/usage for reference.
