### ISSUE TITLE
[FlutterFire plugins] - Lack of pattern to enable the emulator

### ISSUE THREAD

**Issue by yamauchieduardo** [FirebaseExtended/flutterfire#5224]
The FlutterFire plugins have diferent ways to enable the emulator:

### Firebase Auth

`await firebaseAuth.useEmulator(host);`

### Cloud Firestore

`firestore.settings = const Settings(host: host);`

### Firebase Functions

`await firebaseFunction.usesFunctionsEmulator(origin: host);`

Wouldn't it be better if every plugin were enable the emulator in the same way? using `usesEmulator` method or something like the cloud firestore way.

**Comment by smasinde** [comment]
Although I cannot think of any at the moment, maybe there are use cases where you would need to use a live version of one of the plug-ins but the others are fine locally?

**Comment by Salakar** [comment]
For additional info see my comment on https://github.com/FirebaseExtended/flutterfire/discussions/6057#discussioncomment-703941

We're aware of this and plan to make some API changes here in the coming weeks.

**Comment by devj3ns** [comment]
Are there any updates, is currently worked on implementing this feature?

Because I think this would be a huge improvement, I look forward when it's done 😀

**Comment by rrousselGit** [comment]
One thing we should keep in mind when designing the new API is hot-reload/hot-restart.

At the moment we have some issues where disabling the emulator doesn't take effect until the app is fully restarted.
