### ISSUE TITLE
Realtime database, not sound null safety

### ISSUE THREAD

**Issue by nimr77** [FirebaseExtended/flutterfire#5225]
Error with null safety in dart2.12
 After updating my project that requires realtime database, I had this problem with firebase realtime database that is still sound null safety, and using the dart2.9

**Comment by markusaksli-nc** [comment]
Hi @nimr77 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5207.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
