### ISSUE TITLE
[firebase_analytics]android crash

### ISSUE THREAD

**Issue by hyccode** [FirebaseExtended/flutterfire#5229]
![image](https://user-images.githubusercontent.com/26076350/110066878-7030e980-7dad-11eb-811d-37ca6c7a1b58.png)
huawei phone

**Comment by markusaksli-nc** [comment]
Hi @ffriande 
When opening an issue, please try to provide all of the information indicated in the template. Also please refrain from using screenshots instead of pasting the text. It makes referencing the issue impossible.
Closing this issue, since no information has been provided.
Thank you.
