### ISSUE TITLE
firebase_ml_vision: faceDetector detects faces on Android but not iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#524]
## Steps to Reproduce

1. The attached flutter face detection app uses faceDetector in firebase_vision_ml. It works well on Android, detecting faces well. But on iOS, it runs but does not detect any face.  
2. The app code is here: https://gist.github.com/xipengshen/9685ef7a2e86f4b7ad9ed4cf1161d156

**Comment by kroikie** [comment]
@xipengshen

The issue at https://github.com/flutter/flutter/issues/25945 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @xipengshen
given the merged [PR ](https://github.com/flutter/plugins/pull/1225)and the related closed issues [ [1](https://github.com/FirebaseExtended/flutterfire/issues/771), [2](https://github.com/flutter/flutter/issues/19000) ];
 I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by thanhbinh84** [comment]
I face the same issue, face detector works well on Android but not iOS, it always returns empty face list. 

Flutter 
- firebase_ml_vision: ^0.9.4
Pod: 
platform :ios, '10.0'
- Firebase/MLVision (6.28.1):
    - Firebase/CoreOnly
    - FirebaseMLVision (~> 0.21.0)

iOS 13.5.1, iPhone Xr 

Thank you.

**Comment by thanhbinh84** [comment]
> I face the same issue, face detector works well on Android but not iOS, it always returns empty face list.
> 
> Flutter
> 
> * firebase_ml_vision: ^0.9.4
>   Pod:
>   platform :ios, '10.0'
> * Firebase/MLVision (6.28.1):
>   
>   * Firebase/CoreOnly
>   * FirebaseMLVision (~> 0.21.0)
> 
> iOS 13.5.1, iPhone Xr
> 
> Thank you.

Sorry, I missed the final step to make it works on iOS 
add pod 'Firebase/MLVisionFaceModel' into pod file 
Run `pod update `
