### ISSUE TITLE
🐛 [firebase_remote_config] Getting dependency issue with new firebase_core 1.0.0

### ISSUE THREAD

**Issue by gouthamravella** [FirebaseExtended/flutterfire#5246]
## Bug report
Getting the below dependency issue. Can you please update the firebase_core to version 1.0.0
Because firebase_remote_config >=0.6.0 <0.9.0-dev.0 depends on firebase_core ^0.7.0 and app depends on firebase_core ^1.0.0, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is forbidden.
So, because app depends on firebase_remote_config ^0.6.0, version solving failed.

### Steps to reproduce

1. flutter run
---

**Comment by markusaksli-nc** [comment]
Hi @gouthamravella 
The null-safety versions of the packages are not compatible with older versions. Please use `firebase_remote_config: ^0.9.0-dev.0` if you want to use core `1.0.0`
Thank you
