### ISSUE TITLE
🐛 [firabase_messaging] sometimes connected to firabase_messaging for iOS

### ISSUE THREAD

**Issue by rakafajars** [FirebaseExtended/flutterfire#5257]
How do I fix firebase_messaging which sometimes runs on iOS ?

This problem is very confusing, why the firebase_messaging on iOS is always sent late and sometimes not sent greetings at all.

whereas in the ios emulator firebase_messaging and local notif running very well

what should I fix or change to make it work on iOS?

Firebase messaging version : 
`firebase_messaging: ^7.0.3
`

**Flutter doctor**
Run flutter doctor and paste the output below:

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-ID)
    • Flutter version 1.22.6 at /Users/gitsindonesia/FlutterSDK/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gitsindonesia/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0
```

**Comment by markusaksli-nc** [comment]
Hi @rakafajars 
Please `flutter upgrade` to Flutter 2.0 stable and use the latest `firebase_messaging: ^9.0.0`. Follow the migration guide and new setup guides at
https://firebase.flutter.dev/docs/migration#messaging
https://firebase.flutter.dev/docs/messaging/overview
https://firebase.flutter.dev/docs/messaging/apple-integration
Closing since this relates to a version that has been deprecated and on an old Flutter version.
Thank you
