### ISSUE TITLE
[📚] "Improve iOS Build Times" specify incorrect pod version for Flutter 2.0

### ISSUE THREAD

**Issue by MichaelM97** [FirebaseExtended/flutterfire#5260]
The [Improve iOS Build Times](https://firebase.flutter.dev/docs/overview#improve-ios-build-times) documentation suggests to specify the `FirebaseFirestore` pod using version `6.26.0`.

When building with Flutter 2.0 & the latest Firebase depdency versions, this causes the following build failure:

> Resolving dependencies of `Podfile`
>       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.6.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_5_d_c.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/5/d/c/Mantle/2.1.6/Mantle.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_e_9_d.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/e/9/d/SDWebImageWebPCoder/0.8.2/SDWebImageWebPCoder.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_d_4_0.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/5.0.2/GoogleSignIn.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_6_d_6.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/6/d/6/libPhoneNumber-iOS/0.9.15/libPhoneNumber-iOS.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_b_3_c.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/b/3/c/FBSDKLoginKit/9.0.1/FBSDKLoginKit.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_3_7_4.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/3/7/4/TOCropViewController/2.6.0/TOCropViewController.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_f_2_a.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/f/2/a/FirebaseRemoteConfig/7.6.0/FirebaseRemoteConfig.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/f/2/a/FirebaseRemoteConfig/7.3.0/FirebaseRemoteConfig.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_d_c_1.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/d/c/1/FirebaseABTesting/7.6.0/FirebaseABTesting.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_8_b_d.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/7.6.0/FirebaseCore.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_2_f_7.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/2/f/7/FirebaseInstallations/7.6.0/FirebaseInstallations.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_0_8_4.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.2.2/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.0.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.1.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.1.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.2.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.2.2/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.0.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.1.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.1.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.2.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.2.2/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_3_c_c.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/3/c/c/FirebaseStorage/7.6.0/FirebaseStorage.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_2_d_6.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/2/d/6/FirebaseMessaging/7.6.0/FirebaseMessaging.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_e_5_6.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/e/5/6/FirebasePerformance/7.6.0/FirebasePerformance.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_e_7_d.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/e/7/d/FirebaseCrashlytics/7.6.0/FirebaseCrashlytics.podspec.json exists! Returning local because checking is only perfomed in repo update
>     [!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
>       In Podfile:
>         FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `6.26.0`)
> 
>         cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 1.0.0, which depends on
>           Firebase/Firestore (= 7.3.0) was resolved to 7.3.0, which depends on
>             FirebaseFirestore (~> 7.3.0)

Updating the pod version from `6.26.0` to `7.3.0` fixes the issue, so maybe this should be mentioned in the documentation?

**Comment by russellwheatley** [comment]
The iOS version has been updated to `7.3.0` in the [documentation](https://github.com/FirebaseExtended/flutterfire/pull/5869). Thanks for the feedback!
