### ISSUE TITLE
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/tagged_text/tagged_text.dart:295:36: Error: No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by sirius53** [FirebaseExtended/flutterfire#5261]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/tagged_text/tagged_text.dart:295:36: Error: No named parameter with the name 'nullOk'.
            MediaQuery.of(context, nullOk: true)?.textScaleFactor ??
                                   ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sirius53** [comment]
I tried solve this bug all of the day I tried all things what I read but  I can't solve this problem
I Tried
1.delete build file
2.Update minsdk version 
3.Copy all of codes from this project to other new flutter project
4.flutter clean and flutter catch...
5.uninstall android studio and rebuild new flutter zip
please help me guys ı have in toruble all of the day

**Comment by markusaksli-nc** [comment]
Hi @sirius53 
Please open a new issue in the plugin owner's repository
https://github.com/google/flutter.widgets/issues
Closing since the issue doesn't have anything to do with firebase and has none of the information in the template.
Thank you
