### ISSUE TITLE
Flutter FCM - Custom Notification Sound

### ISSUE THREAD

**Issue by karthikeyanp307** [FirebaseExtended/flutterfire#5268]
Hi Team,

I need to set a custom notification sound while receiving the firebase notification in my Flutter application. I tried adding the custom sound to the android project inside res/raw folder and to the iOS directly to the Runner project. While sending the notification, I have included the sound: "custom_sound" in the payload as below.

"notification" : {
      "body" : "body",
      "title" : "title",
      "sound" : "custom_sound"
    }

"android":{
       "notification":{
          "sound":"custom_sound"
       }
    }

"apns" : {
      "aps": {
             "sound": "custom_sound"
      }
}

After several attempts, only the default notificaiton sound is getting played. Let me know if we need to do anything to make this work.

Thanks.

**Comment by markusaksli-nc** [comment]
Hi @karthikeyanp307 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4521.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
