### ISSUE TITLE
"API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device."

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#528]
I tried to set up the firebase_auth plugin, but I get this error: 
```
API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
```
I included it in the pubspecs.yaml like so:
`firebase_auth: ^0.6.6`

I followed Google's instructions to set it up on the Firebase docs.

I am testing this app on a Kindle Fire HD.

Any help would be much appreciated!

**Comment by anhouchaimi** [comment]
Same thing happened !!!
