### ISSUE TITLE
🐛 [firebase_core] iOS "fatal error: could not build module 'firebase_core'" after upgrading to Flutter 2.0.1

### ISSUE THREAD

**Issue by Djmartel** [FirebaseExtended/flutterfire#5284]
## Bug report

**Describe the bug**
Upgraded to Flutter 2.0 and received the error "include of non-modular header inside framework module"

### Steps to reproduce

1. Create a new flutter project (with Objective-C iOS?)
```
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.1
  firebase_auth_web: ^1.0.0
  firebase_database: ^6.1.0
  firebase_analytics: ^7.1.1
  firebase_messaging: ^9.0.0
  firebase_analytics_web: ^0.2.0
  http_parser: ^4.0.0
```
2. Run the application on iOS Simulator
3. The following error appears:
```
...flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.0.0/ios/Classes/FLTFirebaseMes
    sagingPlugin.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePluginRegistry.h>
```

### Expected behavior

A successful build for the iOS simulator

---

## Additional context

I created a Swift file in Xcode that generated a Runner-Bridging-Header.h. Is this causing the CompileSwift error?

Full Error
```
    2 warnings generated.
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    While building module 'firebase_core' imported from
    /Users/danielmartel/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.0.0/ios/Classes/FLTFirebaseMes
    sagingPlugin.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/danielmartel/Documents/MantaPoolThermometer/mobile/ios/Pods/Target Support
    Files/firebase_core/firebase_core-umbrella.h:13:
    In file included from
    /Users/danielmartel/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.0/ios/Classes/FLTFirebaseCorePlug
    in.h:11:
    /Users/danielmartel/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.0/ios/Classes/FLTFirebasePlugin.h
    :9:9: error: include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin':
    '/Users/danielmartel/Documents/MantaPoolThermometer/mobile/ios/Pods/Headers/Public/FirebaseCore/FirebaseCore.h'
    [-Werror,-Wnon-modular-include-in-framework-module]
    #import <FirebaseCore/FirebaseCore.h>
            ^
    1 error generated.
    /Users/danielmartel/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-9.0.0/ios/Classes/FLTFirebaseMes
    sagingPlugin.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePluginRegistry.h>
     ~~~~~~~^
    2 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.0.1 at /Users/danielmartel/development/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/danielmartel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 1DD66FAA-1AE3-463C-AEDB-8102455B0267 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.1
manta 1.0.0+1

dependencies:
- camera 0.5.8+17 [flutter]
- characters 1.1.0
- charts_flutter 0.9.1 [charts_common collection flutter intl logging meta]
- cupertino_icons 0.1.2
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 1.0.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.0.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 6.1.0 [flutter firebase_core]
- firebase_messaging 9.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_auth 1.0.2+2 [flutter]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- permission_handler 6.0.1 [flutter meta permission_handler_platform_interface]
- qr_code_scanner 0.3.5 [flutter]
- rxdart 0.22.4

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- charcode 1.2.0
- charts_common 0.9.1 [collection intl logging meta vector_math]
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase 9.0.0 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.0 [http_parser meta path pedantic]
- js 0.6.3
- logging 0.11.3+2
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- pedantic 1.11.0
- permission_handler_platform_interface 3.0.0+1 [flutter meta plugin_platform_interface]
- plugin_platform_interface 2.0.0 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @Djmartel 
Could you please use the latest versions of all the packages and try running these commands in your `ios` directory?
```bash
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
pod install
```'
Thank you

**Comment by Djmartel** [comment]
> ```shell
> pod cache clean --all
> ```

I still receive the same error after doing this.

**Comment by Djmartel** [comment]
After upgrading to 2.0.1 I had to include `pod 'FirebaseAuth'` in my Podfile otherwise I would get a `library not found for -lFirebaseAuth` error. 

Do you think adding the Swift bridge somehow disrupted the way my dependencies were getting read? Should I try to move from Objective-C to Swift only?

**Comment by markusaksli-nc** [comment]
Hard to say, if you just create a new flutter project using only swift (`flutter create -i swift`) and try to use the dependencies does it work?

**Comment by Djmartel** [comment]
@markusaksli-nc I just did this and it built fine. I'm going to migrate my iOS folder to Swift and see if this fixes it in my real app.

**Comment by markusaksli-nc** [comment]
Adding back the wait label for that

**Comment by Djmartel** [comment]
So I started moving things over 1 by 1 and found the issue seems to be related to my Podfile but I'm not really sure what specifically. Does anything stand out as incorrect? If I remove all of the pods at the bottom the new project runs fine, but I think that is because my code isn't using them yet.

`# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        'PERMISSION_SENSORS=0'
      ]
    end
  end
end



pod 'GoogleUtilities/AppDelegateSwizzler'
pod 'GoogleUtilities/MethodSwizzler'
pod 'GoogleUtilities/Network'
pod 'GoogleUtilities/NSData+zlib'
pod 'GoogleUtilities/AppDelegateSwizzler'
pod 'GoogleUtilities/Environment'
pod 'GoogleUtilities/Logger'
pod 'GoogleUtilities/UserDefaults'
pod 'GoogleUtilities/Reachability'
pod 'FirebaseAuth'`

**Comment by markusaksli-nc** [comment]
Why do you have these lines?
```
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
```
Also you mentioned you added `pod 'FirebaseAuth'` because of an error but it should not be necessary, as it only imports it on the native side. If you've added `firebase_auth` to `podspec.yaml` it should already work.

**Comment by Djmartel** [comment]
I ended up just moving forward with removing my iOS directory and creating a new one with Swift and it fixed my issues. Not really sure why/how but I'll take it.
