### ISSUE TITLE
🐛 [firebase_messaging] Flutter Web can't initialize after upgrading to 9.0.0

### ISSUE THREAD

**Issue by dvaldivia** [FirebaseExtended/flutterfire#5287]
Hi, I'm upgrading from firebase_messaging `7.0.3` to the latest `9.0.0` on a `Flutter 2.0.1` app, everything on native (iOS and Android) is working, however the web version is broken due to errors, I found that there's a requirement to add [according to the documentation](https://firebase.flutter.dev/docs/messaging/overview/#5-web-only-add-the-sdk)

```
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-messaging.js"></script>
```

however the [example on the repo ](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/web/index.html) actually uses
```
<script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-messaging.js"></script>
```

but there's no hosted version of the `9.0.0` dependency anywhere, i was wondering if that could be causing the loading problems, right now I get a complaint the app is not initialized 
```

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:61276/0g3uiyJln9U=/ws
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```

but I do initialize it on my main.dart
```
Future<Null> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
```

So I don't have much options to debug at this point, I'm not sure if I need to also initialize the app from the javascript like in the example I found on the repo

**Comment by markusaksli-nc** [comment]
Hi @dvaldivia
Have you followed the [general web guide](https://firebase.flutter.dev/docs/installation/web)? 
If you have then please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`.
Thank you

**Comment by dvaldivia** [comment]
@markusaksli-nc yeah, I followed other samples and also added javascript code to initialize firebase on the `index.html` which is not clear from the pub.dev or the github instructions, that solved the issue
