### ISSUE TITLE
🐛 Firebase Messaging - FirebaseMessaging.onMessage has different behavior for different platforms

### ISSUE THREAD

**Issue by MobileMon** [FirebaseExtended/flutterfire#5297]
When tapping a notification while the app is completely killed,  FirebaseMessaging.onMessageOpenedApp has different behavior for iOS and Android

The method is called for iOS but not for Android

The 2 platforms should act the same, one way or the other.

While the app is running or the app is in the foreground, the issue is not present. Its when the app is in a completely killed state, the issue occurs

**Comment by markusaksli-nc** [comment]
Hi @MobileMon 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
