### ISSUE TITLE
cloud_firestore_web package not working in Flutter 2 web

### ISSUE THREAD

**Issue by jerryhamby** [FirebaseExtended/flutterfire#5301]
I building a very simple web app and I tried to add the cloud_firestore_web package and I'm getting this error.
BTW, firebase_core package is working in the app. I tried both 1.0.0 and 1.0.1 cloud_firestore.

Need some advice, I really need to connect to firestore.

The breakpoint stops here:
Future main() async {
registerPlugins(webPluginRegistrar);
await ui.webOnlyInitializePlatform();
if (entrypoint.main is _UnaryFunction) {
return (entrypoint.main as _UnaryFunction)([]);
}
return (entrypoint.main as _NullaryFunction)();
}

TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:53545/packages/firebase_core_web/src/interop/core.dart.lib.js:42:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:53545/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:988:64)
    at Function.registerWith (http://localhost:53545/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:842:73)
    at Object.registerPlugins (http://localhost:53545/packages/web_test/generated_plugin_registrant.dart.lib.js:28:46)

### Steps to reproduce

Super simple to reproduce:
1- Open new web project
2- include cloud_firestore_web: ^1.0.1 into the podspec.yaml doc.
3- run "start debugging" (see errors above)

### Flutter doctor

jerryhamby@Jerrys-iMac web_test % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.0.1 at /Users/jerryhamby/Desktop/FlutterExamples/flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jerryhamby/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
jerryhamby@Jerrys-iMac web_test % 

---

### Flutter dependencies

jerryhamby@Jerrys-iMac web_test % flutter pub deps  
Dart SDK 2.12.0
Flutter SDK 2.0.1
web_test 1.0.0+1
|-- cloud_firestore_web 1.0.1
|   |-- cloud_firestore_platform_interface 4.0.0
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 2.0.0
|   |       '-- meta...
|   |-- firebase_core 1.0.1
|   |   |-- firebase_core_platform_interface 4.0.0
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   '-- plugin_platform_interface...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   '-- meta...
|   |-- firebase_core_web 1.0.1
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- flutter...
|   |-- flutter_web_plugins 0.0.0
|   |   |-- characters...
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- js...
|   |   |-- meta...
|   |   |-- typed_data...
|   |   '-- vector_math...
|   '-- js 0.6.3
|-- cupertino_icons 1.0.2
|-- flutter 0.0.0
|   |-- characters 1.1.0
|   |-- collection 1.15.0
|   |-- meta 1.3.0
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0
|   |   '-- collection...
|   '-- vector_math 2.1.0
'-- flutter_test 0.0.0
    |-- async 2.5.0
    |   '-- collection...
    |-- boolean_selector 2.1.0
    |   |-- source_span...
    |   '-- string_scanner...
    |-- characters...
    |-- charcode 1.2.0
    |-- clock 1.1.0
    |-- collection...
    |-- fake_async 1.2.0
    |   |-- clock...
    |   '-- collection...
    |-- flutter...
    |-- matcher 0.12.10
    |   '-- stack_trace...
    |-- meta...
    |-- path 1.8.0
    |-- source_span 1.8.0
    |   |-- charcode...
    |   |-- collection...
    |   |-- path...
    |   '-- term_glyph...
    |-- stack_trace 1.10.0
    |   '-- path...
    |-- stream_channel 2.1.0
    |   '-- async...
    |-- string_scanner 1.1.0
    |   |-- charcode...
    |   '-- source_span...
    |-- term_glyph 1.2.0
    |-- test_api 0.2.19
    |   |-- async...
    |   |-- boolean_selector...
    |   |-- collection...
    |   |-- matcher...
    |   |-- meta...
    |   |-- path...
    |   |-- source_span...
    |   |-- stack_trace...
    |   |-- stream_channel...
    |   |-- string_scanner...
    |   '-- term_glyph...
    |-- typed_data...
    '-- vector_math...
jerryhamby@Jerrys-iMac web_test %

**Comment by augustkimo** [comment]
Did you add the packages scripts in your index.html file? When I forget to do this I get the same error. Ensure Firebase is initialized and and scripts are added, go through the Firebase web setup documentation/guide for more info.

**Comment by jerryhamby** [comment]
I didn't add anything to index.html. I will look into tis approach.
Here is my basic index.html code:
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>vdex_flutter</title>
</head>
<body>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>

**Comment by jerryhamby** [comment]
Sorry somethings are missing:
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>vdex_flutter</title>
</head>
<body>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>

**Comment by augustkimo** [comment]
You need to:
1: add the scripts for all the SDKs you are using + 
2: initialize with your config info

The guide can be found here:
https://firebase.google.com/docs/web/setup#add-sdks-initialize

**Comment by jerryhamby** [comment]
I'm getting the another error.
PS- I don't know how to find the measurementId, so I didn't include. Is it important?
What am I doing wrong???

FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at Object.u [as app] (https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js:1:17078)
    at Object.app$ [as app] (http://localhost:50672/packages/firebase_core_web/src/interop/core.dart.lib.js:42:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:50672/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:988:64)
    at Function.registerWith (http://localhost:50672/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:842:73)
    at Object.registerPlugins (http://localhost:50672/packages/web_test/generated_plugin_registrant.dart.lib.js:28:46)

<body>
       <script defer src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
       <script defer src="https://www.gstatic.com/firebasejs/8.2.10/firebase-auth.js"></script>
       <script defer src="https://www.gstatic.com/firebasejs/8.2.10/firebase-firestore.js"></script>
       <script defer src="./init-firebase.js"></script>
       <script>
        var firebaseConfig = {
          apiKey: "AI…",
          authDomain: "vdex…",
          databaseURL: "https://vdex…",
          projectId: "vdex…",
          storageBucket: "vdex…,
          messagingSenderId: "408…",
          appId: "1:408…",
        };
        firebase.initializeApp(firebaseConfig);
      </script>
</body>

**Comment by markusaksli-nc** [comment]
Hi @jerryhamby 
Please follow the official documentation on what versions to use in the `index.html` script imports.
https://firebase.flutter.dev/docs/installation/web
https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk
https://firebase.flutter.dev/docs/auth/overview#3-web-only-add-the-sdk
You can get all of the configuration details including your measuerementId using the `firebase apps:sdkconfig` command.
Thank you
