### ISSUE TITLE
🐛 [firebase_remote_config] Update dependency constraints

### ISSUE THREAD

**Issue by AnavrinApps** [FirebaseExtended/flutterfire#5308]
## Bug report
**Describe the bug**
Running "flutter pub get" in test_app...     

Because firebase_remote_config >=0.6.0 <0.9.0-dev.0 depends on firebase_core ^0.7.0 and firebase_performance 0.6.0 depends on firebase_core ^1.0.0, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is incompatible with firebase_performance 0.6.0.
And because no versions of firebase_performance match >0.6.0 <0.7.0, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is incompatible with firebase_performance ^0.6.0.
So, because test_app depends on both firebase_performance ^0.6.0 and firebase_remote_config ^0.6.0, version solving failed.
pub get failed (1; So, because test_app depends on both firebase_performance ^0.6.0 and firebase_remote_config ^0.6.0, version solving failed.)
exit code 1

**Comment by markusaksli-nc** [comment]
Hi @AnavrinApps 
You need to use `firebase_remote_config: ^0.9.0-dev.0` or newer to use it with the latest versions of the other firebase packages.
Thank you
