### ISSUE TITLE
🐛 [firebase_messaging] getting foreground notification tap callback in the onMessageOpenedApp on behalf of onMessage in iOS.

### ISSUE THREAD

**Issue by DhavalRKansara** [FirebaseExtended/flutterfire#5309]
Using firebase_messaging, I am getting the foreground notification call back in the `onMessageOpenedApp` method on behalf of `onMessage` method.

**Comment by markusaksli-nc** [comment]
Hi @DhavalRKansara 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by DhavalRKansara** [comment]
@markusaksli-nc I have added firebase notification in my flutter application and I am performing different operations when the user clicks on the notification while the app is in the foreground, background, and terminated state...

While the app is in the background or terminated state and the user clicks on the notification then first I authenticate the user using a four-digit pin and then redirecting the user to a specific screen using notification data...


So In the Android, as mentioned in the [FlutterFire-Notification](https://firebase.flutter.dev/docs/messaging/notifications/), I am getting notification tap callback as below.

- **onMessage** - when the app is in the foreground (i am using the flutter_local_notification here as mentioned in doc.)
- **onMessageOpenedApp** - when app is in background
- **getInitialMessage** - when ap is terminated

But the same thing word different in ios for the foreground notification, The problem is I am receiving foreground notification by default and getting tap event of the foreground notification in the **onMessageOpenedApp** where I am not able to identify that user tap on the foreground notification or background notification...

**Comment by markusaksli-nc** [comment]
Like I said it's impossible to know what versions you are talking about on which flutter version, on which device etc. Please just open a new issue and fill out the **entire** issue template.

Also it seems much easier to do this by just listening to app lifecycle state instead of notification events.
