### ISSUE TITLE
UploadTask.onComplete is not showing

### ISSUE THREAD

**Issue by code-RK** [FirebaseExtended/flutterfire#5310]
Future<String> uploadItemImage(mFileImage) async {
    final Reference reference = FirebaseStorage.instance.ref().child("Items");
    UploadTask uploadTask =
        reference.child("product $productId.jpg").putFile(mFileImage);
    TaskSnapshot taskSnapshot = await uploadTask; // onComplete is missing
    String downloadUrl = await taskSnapshot.ref.getDownloadURL();
    return downloadUrl;
  }

**Comment by markusaksli-nc** [comment]
Hi @code-RK 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
