### ISSUE TITLE
🐛 [firebase_analytics] don't use language version 2.12 when not migrating to null-safety

### ISSUE THREAD

**Issue by jonasfj** [FirebaseExtended/flutterfire#5311]
The following 3 lines are found in [`pubspec.yaml` for `firebase_analytics`](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/pubspec.yaml):
```
environment:
  sdk: ">=2.12.0-0 <3.0.0"

# This version is not null-safe but has been created to allow compatibility with already null-safe FlutterFire packages such as `firebase_core`.
```

The line `sdk: ">=2.12.0-0 <3.0.0"` says the package as opted into null-safety.
This should not be done before all dependencies and libraries in the package are migrated.

Which from the comment at the bottom of the file it appears they aren't.

This will cause problems for people trying to migrate to null-safety, as our tooling will tell them that `firebase_analytics` analytics is migrated. But in practice it is not.

@Salakar, what is the motivation for increasing the SDK lowerbound to `2.12.0` and there by signaling null-safety support?

I don't see `firebase_analytics` being used by other null-safety migrated packages, and I see no reason why it can't have lower bound `2.10.0`, even though it's depending on `firebase_core` which might be null-safety migrated and have lowerbound `2.12.0`.

**Comment by firatcetiner** [comment]
When can we expect at least a separate null-safe version of this package? I use `firebase_analytics` in almost every project of mine, as well as the projects at my company, and this package the only reason we cannot opt-in our apps into null-safety.  I hope this package gets attention like many other Firebase plugins that opted-in null-safety.

**Comment by xinoxapps** [comment]
Has this library been overseen during the null-safety-migration? Or is there a show stopper we should be aware of..

It is extremely frustrating that the migrating tool said we are ready to go and it doesn't appear to be the case after 2 days of work..

**Comment by cedteg** [comment]
I have migrated it for own purposes

So you can test it

```
firebase_analytics: 
    git:
      url: git://github.com/cedteg/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics
```

**Comment by Drakota** [comment]
For everyone subscribed to this issue, firebase_analytics has pushed [prerelease versions](https://pub.dev/packages/firebase_analytics/versions/8.0.0-dev.2) that solves this issue. I'm now able to run my application with full sound null safety. 🎉

![image](https://user-images.githubusercontent.com/22665836/114043747-90444480-9854-11eb-9083-d381c5209385.png)

**Comment by Salakar** [comment]
Hey all 👋 thanks for your patience. As mentioned above by @Drakota there is now a full nullsafety prerelease available; https://pub.dev/packages/firebase_analytics/versions/8.0.0-dev.2 - please check it out and switch over to it.

The same applies to dynamic links if you're using that package also.
