### ISSUE TITLE
Getting empty list while using FaceContour class.

### ISSUE THREAD

**Issue by viprocket1** [FirebaseExtended/flutterfire#5312]
I want to get coordinates of face contour I'm using the code below, but I am getting an empty list in return.

`    for (var i = 0; i < faces.length; i++)  {
      final List<Offset> positionsList = faces[i].getContour(FaceContourType.face).positionsList;
      print(positionsList);
    }`

Thank you for helping.

**Comment by markusaksli-nc** [comment]
Hi @viprocket1 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
