### ISSUE TITLE
🐛 [remote_config] Upgrade to sound null safety and supporting core 1.0.0

### ISSUE THREAD

**Issue by ammaratef45** [FirebaseExtended/flutterfire#5313]
https://github.com/FirebaseExtended/flutterfire/discussions/4182 doesn't mention anything about upgrading to null safety and I can't find any thing that tracks the upgrade to support core version `1.0.0`

What is the plan for this?

**Comment by markusaksli-nc** [comment]
Hi @ammaratef45 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5207.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
