### ISSUE TITLE
🐛 [firebase_ml_vision]  Which version is compatible

### ISSUE THREAD

**Issue by bakboem** [FirebaseExtended/flutterfire#5319]
## Bug report

**Describe the bug**

[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
      In snapshot (Podfile.lock):
        Firebase/CoreOnly (= 7.3.0)

      In Podfile:
        Firebase/MLVisionBarcodeModel was resolved to 5.0.0, which depends on
          Firebase/CoreOnly (= 5.0.0)

        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 1.0.1, which depends on
          Firebase/CoreOnly (= 7.3.0)

**podFile:** 
  `target 'Runner' do
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionLabelModel'
  pod 'Firebase/MLVisionTextModel'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end`

**pubspec.yaml**
`environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^1.0.0 
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  flutter_signin_button: ^2.0.0-nullsafety.0
  google_sign_in: ^5.0.0
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^9.0.0
  flutter_facebook_auth: ^3.0.0+1
  sign_in_with_apple: ^3.0.0`

**Comment by markusaksli-nc** [comment]
Hi @bakboem 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4625.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
