### ISSUE TITLE
🐛 [Firebase Auth] Null check operator used on a null value after signInWithCredential or linkWithCredential

### ISSUE THREAD

**Issue by yassinsameh** [FirebaseExtended/flutterfire#5323]
## Bug report

After updating the Firebase auth package to ^1.0.1, Using the firebase method verifyPhoneNumber() when automatic verification happens in the verificationCompleted callback or i submit a number OTP and i take the phone credential and attempt to signInWithCredential or linkWithCredential. I first get a successful login then a null check operator error: 

```
1) Notifying id token listeners about user ( aCoFE4l9S8XXXXXX ).
2) Null check operator used on a null value.
Line number 2 happens in the catch section not the FirebaseAuthException i have displayed below.
```

**Note: When i replace the line
 ` await _firebaseAuth.signInWithCredential(phoneCredential); or await _firebaseAuth.linkWithCredential(phoneCredential); `
 with 
`signInWithEmailAndPassword `as an example everything works fine.**

### Steps to reproduce
After 

```
Future<bool> submitOtp({String verificationId, String enteredCode}) async {
  
    auth.PhoneAuthCredential phoneCredential =
        auth.PhoneAuthProvider.credential(
            verificationId: verificationId, smsCode: enteredCode);
    try {
      print('Gonna try credential');

      await _firebaseAuth.signInWithCredential(phoneCredential);
      //The print below is not reached.
      print('Signed user successfully);
      return true;
    } on auth.FirebaseAuthException catch (e) {
      print('Firebase auth exception occured');
      print(e.toString());
      return false;
    } catch (e) {
      print('Normal catch exception occured');
      print(e.toString());
      return false;
    }
  }
```

### Flutter doctor

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.1 at C:\Users\yassin\Downloads\Programming files\Flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\yassin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\yassin\Downloads\Programming files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\yassin\Downloads\Programming files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM A515F (mobile) • XXXXXXX • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!```

</details>

---

### Flutter dependencies

firebase_core: ^1.0.0
firebase_auth: ^1.0.1
provider: ^5.0.0
```

**Comment by yassinsameh** [comment]
The issue is gone, i'm not entirely sure what the cause was, **That is to say I believe that the error has nothing to do with signInWithCredential or linkWithCredential.** It should be the case however that more information in general should be provided as to the cause of the error.

**Comment by markusaksli-nc** [comment]
Closing this as solved for now
