### ISSUE TITLE
🐛 [firebase_messaging] Adding latest version to project blocks app badge on macOS

### ISSUE THREAD

**Issue by seanmc86** [FirebaseExtended/flutterfire#5328]
## Bug report

**Describe the bug**
If I add the following to pubspec.yaml and launch a Flutter app on macOS, my app badge notification count no longer shows. I am updating the badge counter using a separate plugin, nothing to do with firebase messaging. This works if I do not include firebase messaging in my app.

```
dependencies:
  firebase_messaging: 9.0.0
```

Removing the dependency again does not fix this. Even stopping the app, running flutter clean, deleting the Pods folder and Podfile.lock all do not help. I have to remove the entire macOS folder in my project and recreate it for the badge to show again.

### Steps to reproduce

1. flutter create --platforms=macos
2. Add firebase_messaging: 9.0.0 to pubspec.yaml
3. Try to update the app badge counter. You could for example use this package to do so on macOS: https://pub.dev/packages/flutter_app_icon_badge
4. Adding firebase_messaging 9.0.0 requires an update of the Podfile platform :osx version to 10.12 from the default 10.11 (could this be an issue?)

### Expected behavior

The firebase messaging package does not interfere with the app badge.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.54.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.1
gif_test 1.0.0+1

dependencies:
- app_badge 1.0.0 [flutter app_badge_platform_interface app_badge_linux app_badge_macos app_badge_windows]
- firebase_messaging 9.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- cupertino_icons 1.0.2
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- app_badge_linux 0.0.1+4 [flutter]
- app_badge_macos 1.0.0 [flutter]
- app_badge_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- app_badge_windows 1.0.0 [flutter]
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @seanmc86 
Could you confirm if you just try to use the badging package on its own with `10.12` if it works? We should have no code to even do anything with badging.
Thank you

**Comment by seanmc86** [comment]
Apologies, this issue was tangential to updating to the latest version and was not caused by it, but rather a change in one of the recent macOS updates.
