### ISSUE TITLE
🐛 [firebase_in_app_messaging] in-app message popup not show when Firebase event trigger

### ISSUE THREAD

**Issue by devappbirds** [FirebaseExtended/flutterfire#5331]
## Bug report

**Describe the bug**
We are using FirebaseAnalytics for fire event when user perform action that time in-app message popup not showing with flutter project

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @devappbirds 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
