### ISSUE TITLE
🐛 [PhoneAuthProvider] credential incompatibility with currentUser.updatePhoneNumber

### ISSUE THREAD

**Issue by heychirag** [FirebaseExtended/flutterfire#5337]
## Bug report

**Describe the bug**

The `PhoneAuthCredential.credential` API returns a credential of type `AuthCredential`, but `currentUser.updatePhoneNumber` accepts a parameter of type `PhoneAuthCredential`.

From the comments, it seems like the code should never have made to production

```
  /// Create a new [PhoneAuthCredential] from a provided [verificationId] and
  /// [smsCode].
  // TODO(rrousselGit): Should this return a PhoneAuthCredential instead?
  static AuthCredential credential({
    required String verificationId,
    required String smsCode,
  }) {
    return PhoneAuthCredential._credential(verificationId, smsCode);
  }
```
Notice the **TODO** marked above. And here is the code for `updatePhoneNumber`

```
  /// Updates the user's phone number.
  ///
  /// A credential can be created by verifying a phone number via [verifyPhoneNumber].
  ///
  /// A [FirebaseAuthException] maybe thrown with the following error code:
  /// - **invalid-verification-code**:
  ///  - Thrown if the verification code of the credential is not valid.
  /// - **invalid-verification-id**:
  ///  - Thrown if the verification ID of the credential is not valid.
  Future<void> updatePhoneNumber(PhoneAuthCredential phoneCredential) async {
    await _delegate.updatePhoneNumber(phoneCredential);
  }
```

Ideally, the code should never have been released. This needs to be prioritized for the fix in the next release.

### Steps to reproduce

The above description should suffice.

### Expected behavior

One part of code should be compatible with the other. The APIs should return and accept same kind of Objects.

---

## Additional context

A unit test should have been in place to prevent this from happening.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @heychirag 
I see there's an open issue addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by iamshaunwu** [comment]
@markusaksli-nc 

```
 final AuthCredential _credential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);                            
await _auth.currentUser.updatePhoneNumber(_credential);
```

The error message is **"The argument type 'AuthCredential' can't be assigned to the parameter type 'PhoneAuthCredential'."**. 

Basically, updatePhoneNumber requires a PhoneAuthCredential. Unless there is another way to do this with documentations, we will not be able use the updatePhoneNumber function. 

By the way, in the firebase_auth package under phone_auth.dart, there is a TODO -   // TODO(rrousselGit): Should this return a PhoneAuthCredential instead?

Appreciate if you can reopen this case and shed great light. Thanks!
