### ISSUE TITLE
🐛 [firebase_dynamic_links] Null safety warning missing

### ISSUE THREAD

**Issue by wolframm** [FirebaseExtended/flutterfire#5338]
I upgraded my Flutter app to Null Safety after running `flutter pub outdated --mode=null-safety`, which prints:

```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name       Current  Upgradable  Resolvable  Latest   

direct dependencies: all support null safety.

dev_dependencies: 
build_runner       ✗1.11.5  ✗1.11.5     ✗1.11.5     ✗1.12.1  
json_serializable  ✗4.0.2   ✗4.0.2      ✗4.0.2      ✗4.0.2   
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```

This leads one to assume that the app will run in sound null safety once you put all the required `!`s and `?`s.

But, when trying to run the app after making all changes, the `firebase_dynamic_links` package  throws the following error:

`Error: A library can't opt out of null safety by default, when using sound null safety.`

This is because it uses the language version comment `// @dart=2.9`, which seems to trick `flutter pub outdated --mode=null-safety` into reporting full null safety support.

Please upgrade `firebase_dynamic_links` to null safety.

**Comment by markusaksli-nc** [comment]
Hi @wolframm 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5207.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
