### ISSUE TITLE
🐛 [firebase_ml_vision] Android gradle dependencies documentation incorrect/outdated

### ISSUE THREAD

**Issue by ATmare** [FirebaseExtended/flutterfire#5344]
## Bug report

**Describe the bug**
I try to build an android app with firebase_ml_vision. On the emulator it works, when I run "flutter build apk" I get the following error: 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugAndroidTestCompileClasspath'.
   > Could not find com.google.firebase:firebase-ml-vision:.
     Required by:
         project :app > project :firebase_ml_vision

I followed the [ML Kit migration guide](https://developers.google.com/ml-kit/migration/android#before_1) and updated my gradle files. 

### Steps to reproduce

1. cd project-dir
2. flutter build apk
2. See error

### Expected behavior

Apk should get built.

---

## Additional context

Please offer a recommendation, which package-versions should be used and how the app/build.gradle and build.grade files should be edited to perform on-device text-recognition. Almost all documents and tutorials I found seem to cause problems because of incompatible package versions.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.16299.1087], locale de-AT)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.0
maresi_ml_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_ml_vision 0.11.0 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- pedantic 1.11.0
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---
---

### app/build.gradle additions

the following lines have been added to the app/build.gradle file:

<details><summary>Click To Expand</summary>

```
android {
    compileSdkVersion 30
    ...
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.maresi_ml_test"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
//    implementation platform('com.google.firebase:firebase-bom:26.7.0')
//    implementation 'com.google.android.gms:play-services-vision:20.0.0'
//    implementation 'com.google.firebase:firebase-ml-vision:24.0.3'
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition:16.1.3'
}

apply plugin: 'com.google.gms.google-services'
```

</details>

---
### android/build.gradle additions

the following lines have been added to the app/build.gradle file:

<details><summary>Click To Expand</summary>

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.5'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @ATmare 
I'm not seeing this, could you try runnig `flutter clean` or deleting your `.gradle/caches` folder?
Thank you

**Comment by haraldkofler** [comment]
I'm experiencing the same problem. Seems like after upgrading to flutter 2.0.2 (coming from 1.22.6).
Not 100% sure if it is caused by the flutter upgrade.

To fix the issue I added the following to the build.gradle:

`
dependencies{
   ...
   implementation 'com.google.firebase:firebase-ml-vision:24.1.0'
   ...
}
`

AFAIK this dependency should not be needed for my case, as I only want to use the mlKit barcode scanner, without cloud interaction.
Actually my app builds with flutter build apt to a size of 56MB, before it had ~20MB. I think that adding this dependency increased the app's size!?

**Comment by ATmare** [comment]
> 
> 
> Hi @ATmare
> I'm not seeing this, could you try runnig `flutter clean` or deleting your `.gradle/caches` folder?
> Thank you

Hi @markusaksli-nc I tried it with flutter clean several times which did not work... so I started the project (with flutter create app_name) completely new from scratch and the above error did not occur anymore after that. The new problem I got was, that the model did not work on my physical android device, when I installed it via apk. In Debug mode (when I had my physical device connected via USB cable) and also on the android studio emulator everything worked as expected. 

After 2 days of debugging without finding a solution for that new problem I went for another approach, which was the following: 
1. git clone [this project](https://github.com/mwitiderrick/text-recognition/tree/master/android )
2. create a firebase project with the same package name as the guy from the above link uses (com.example.object_detection) to avoid package-renaming bugs
3. copy all my .dart files from the lib folder in the lib folder of the cloned project, replace the google-services.json file in android/app with my own file. 
4. added the additional dependencies I need in pubspec.yaml
5. try flutter run and flutter build apk --split-per-abi

This seems to work for me at them moment, so I think it maybe has to do with the andoid folder that gets created by using "flutter create xyz" or something?? .... Since this workflow is completely frustrating and your documentation at [the vision readme](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision) even links to 404-dead links, I would really want to read an up-to-date documentation or recommendation for a clean setup (including the specification of **exact versions** and **necessary changes in the android gradle files or android manifest**), which will not break the app using flutter 2.0 and ml_vision for on-device text-recognition.... 

To be honest it is more than disappointing and annoiying to waste hours of lifetime just figuring out which of the flutterfire firebase packages are compatible with each other, which work at all and which will hopefully not break the app completely...

**Comment by ATmare** [comment]
> 
> 
> I'm experiencing the same problem. Seems like after upgrading to flutter 2.0.2 (coming from 1.22.6).
> Not 100% sure if it is caused by the flutter upgrade.
> 
> To fix the issue I added the following to the build.gradle:
> 
> `dependencies{ ... implementation 'com.google.firebase:firebase-ml-vision:24.1.0' ... }`
> 
> AFAIK this dependency should not be needed for my case, as I only want to use the mlKit barcode scanner, without cloud interaction.
> Actually my app builds with flutter build apt to a size of 56MB, before it had ~20MB. I think that adding this dependency increased the app's size!?
> 
> I also tried to do a flutter clean, but the app doesn't build without the dependency added.

Hi @haraldkofler , 
thanks for the advice! At some point I added this line too to the gradle file and to be honest, I tried a lot to get it to work so I do not remember if it was this change that caused the difference. 
Relating to the size of your apk: 
By running the command _flutter build apk_ my app is about 50MB too, but that's because all the ABIs are merged into one fat apk file.
Using flutter _build apk --split-per-abi_ with my current workflow described above I get apks with about 20MB each.

**Comment by markusaksli-nc** [comment]
Based on the steps that worked for you it seems the issue was depending on any of the separate ml vision gradle dependencies. As the setup that works for me also does not depend on them. This seems to be due to the dependency being added to the package gradle project directly (which has also led to https://github.com/FirebaseExtended/flutterfire/issues/4767)

In any case the current documentation at https://pub.dev/packages/firebase_ml_vision is outdated for android.

**Comment by botond-kopacz** [comment]
Using the following Firebase dependencies in pubspec.yaml the issue is easily reproduceable: 
-   firebase_core: 1.0.1
-   firebase_auth: 1.0.1
-   firebase_database: 6.1.0
-   firebase_storage: 8.0.0
-   firebase_ml_vision: 0.11.0
-   firebase_remote_config:  0.9.0-dev.0
-   firebase_analytics: [7.1.1](url)
-   firebase_crashlytics: 1.0.0


There is no need for sample project or flutter doctor.  Lastest Flutter (only mod is the pubspec.yaml + running the sample code) will result in issue:
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.0.
  2]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.firebase:firebase-ml-vision-image-label-model:17.0.2 -> com.google.android.gms:play-servi
  ces-vision-common@[17.0.2], but play-services-vision-common version was 19.1.2.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@{strictly 24.1.0}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-common@{strictly 19.1.2}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@{strictly 17.0.2}
  -- Project 'app' depends onto com.google.android.gms:play-services-vision-image-label@{strictly 18.1.0}
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision-image-label-model@17.0.2
  -- Project 'app' depends onto com.google.firebase:firebase-ml-vision@24.1.0
  -- Project 'app' depends onto com.google.android.gms:play-services-vision@{strictly 20.1.2}

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.
```

**Comment by Salakar** [comment]
Hey, :wave:, the `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks
