### ISSUE TITLE
flutter_cloud_messaging

### ISSUE THREAD

**Issue by abdulla-bey01** [FirebaseExtended/flutterfire#5348]
can not run project has flutter_cloud_messagind dependency on iOS side

> [!] CocoaPods could not find compatible versions for pod "firebase_cloud_messaging":
  In Podfile:
    firebase_cloud_messaging (from `.symlinks/plugins/firebase_cloud_messaging/ios`)

Specs satisfying the `firebase_cloud_messaging (from `.symlinks/plugins/firebase_cloud_messaging/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by markusaksli-nc** [comment]
Hi @abdulla-bey01 
Please update your ios deployment target to at least 10.0 as mentioned in the official documentation
https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions
Thank you

**Comment by abdulla-bey01** [comment]
my xcode version is 12.4
cocoapods version is 1.10.1
deployment target is 10.0
but still same error

**Comment by markusaksli-nc** [comment]
You need to run `flutter clean` to clear old caches after changing project config. Also `firebase_cloud_messaging` is not the official firebase package for cloud messaging 

https://pub.dev/packages/firebase_messaging

**Comment by abdulla-bey01** [comment]
thanks, firebase_messaging is work for me!!
