### ISSUE TITLE
Unhandled Exceptions (PlatformException)

### ISSUE THREAD

**Issue by exampaqs** [FirebaseExtended/flutterfire#5355]
## Bug report
Exception has occurred.
PlatformException (PlatformException(firebase_auth, com.google.firebase.auth.FirebaseAuthInvalidUserException: There is no user record corresponding to this identifier. The user may have been deleted., {code: user-not-found, additionalData: {}, message: There is no user record corresponding to this identifier. The user may have been deleted.}, null))

**Describe the bug**
I guess this is an unhandled exception from firebase package itself.

### Steps to reproduce

Here is my code:
`//Sign In with Email and Password

  Future<Map<String, dynamic>> login(Map<String, String> userData) async {
    try {
      UserCredential result = await _auth.signInWithEmailAndPassword(
          email: userData['email'], password: userData['password']);
      //use this to confirm if user's email is athenticated
      User user = result.user;
      if (user.emailVerified) {
        return await _signInUser(userData, userId: user.uid, isRelogin: false);
      } else {
        //Email Address is not Verified
        return {
          'error': 'Kindly verify your Email Address via the Link sent to you!'
        };
      }
    } on FirebaseAuthException catch (_) {
      //Email/Password Combination is wrong
      return {'error': 'Email/Password combination do not match!'};
    } catch (e) {
      return {'error': 'Email/Password combination do not match!'};
    }
  }
`

### Expected behavior

I expected  `_auth.signInWithEmailAndPassword(
          email: userData['email'], password: userData['password']) `  to return a user instance but that line threw and error. 

## Additional context

Code was working until i upgraded my dependencies to firebase_auth: ^1.0.1

**Comment by markusaksli-nc** [comment]
Hi @exampaqs 
Please use the `createUserWithEmailAndPassword` method if you want to register a new user.
You can always take a look at the official code sample for an example of how to use the package.
Thank you

**Comment by exampaqs** [comment]
@markusaksli-nc 
I'm not trying to create user, I'm trying to login Users with email and password
the problem occurs on this method `signInWithEmailAndPassword`.

**Comment by markusaksli-nc** [comment]
Does the user actually exist? The exception usually just means the user you are trying to log in has been deleted.

**Comment by exampaqs** [comment]
Yes, the user exist. Infact if the password is correct, the error does not come up. the error shows when the password is incorrect

**Comment by markusaksli-nc** [comment]
I'm not seeing this with `firebase_auth: ^1.0.1`
```
FirebaseAuthException
[firebase_auth/wrong-password] The password is invalid or the user does not have a password.
```
