### ISSUE TITLE
🐛 [Firebase Auth] There is no clearPersistence() 

### ISSUE THREAD

**Issue by mabujaber** [FirebaseExtended/flutterfire#5363]
**Describe the bug**
Ther is no way to clear the persist user authentication through the API, the only way to do so to wipe the data from the or erase all content and setting. This is can be handled in case we use a simulator/emulator while it's really hard to do that in real devices. 

I saw an issue it was opened and closed (#2185) by one of the contributors which they assume that the issue only related to firestore but the issue raised for both firestore and auth. 
  

We need to know if there is any workaround can help to clean all the persistence for all firebase especially firebase_auth

**Comment by markusaksli-nc** [comment]
Hi @mabujaber 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4661.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
