### ISSUE TITLE
Firebase phone auth

### ISSUE THREAD

**Issue by Hopheylalal** [FirebaseExtended/flutterfire#5364]
I get error - [firebase_auth/missing-client-identifier] This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.

I enabling Device Check API.
then i get release sha1 sha256 by ./gradlew signingReport and add it to firebase console 
then add new google-service.json to project

also i add another fingerprint from google Play App Signing

still do not working. Somebody help.

Everything working in debug mode!

**Comment by markusaksli-nc** [comment]
Hi @Hopheylalal 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
