### ISSUE TITLE
Incorrect documentation for RewardedVideoAd (Syntax error)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#538]
I am using firebase_admob for showing ads, both banner and interstitial worked but when I was implementing the RewardedVideoAds, I got syntax error. 

### Code (From Docs)
```dart
RewardedVideoAd.instance.listener =
    (RewardedVideoAdEvent event, [String rewardType, int rewardAmount]) {
  if (event == RewardedVideoAdEvent.rewarded) {
    setState(() {
      // Here, apps should update state to reflect the reward.
      _goldCoins += rewardAmount;
    });
  }
};
```

### Code (My own)
This minimises above code to reflect the error. (Both code shows syntax error)
```dart
void loadVideoAd() {
  RewardedVideoAd.instance.listener = (RewardedVideoAdEvent event, [String rewardType, int rewardAmount]) {
    if (event == RewardedVideoAdEvent.rewarded) {}
  };
}
```

### Syntax Error
A value of type `(RewardedVideoAdEvent, [String, int]) -> Null` can't be assigned to a variable of type `(RewardedVideoAdEvent, {rewardType: String, rewardAmount: int}) -> void`

<img width="1540" alt="screenshot 2018-12-17 at 9 45 08 pm" src="https://user-images.githubusercontent.com/40364434/50099851-116f0c00-0245-11e9-9d89-b3801d217054.png">

### Feedback
The documentation for RewardedVideoAd is very poor. They also have syntax error. Probably the docs have not been updated since long.

**Comment by kroikie** [comment]
@dark-chocolate

The issue at https://github.com/flutter/flutter/issues/25464 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @dark-chocolate
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by dark-chocolate** [comment]
@iapicca The issue has been solved, please close it.

**Comment by iapicca** [comment]
Hi @dark-chocolate 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
