### ISSUE TITLE
[firebase storage] iOS - could not build module 'firebase_core' vers. 8.0.0

### ISSUE THREAD

**Issue by albellulo** [FirebaseExtended/flutterfire#5392]
Hi,

I'm experiencing this problem after an upgrade of Firebase plugin:

1 error generated.
    /Users/alberto/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-8.0.0/ios/Classes/FLTFirebaseStoragePlugin.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePluginRegistry.h>

Already tried:

- Flutter clean
- Pod update

Pubspec:

  # firebase
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.0
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_messaging: ^9.0.0

Thanks for the help!

**Comment by markusaksli-nc** [comment]
Hi @albellulo 
Could you try running these commands in your `ios` directory?
```bash
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
pod install
```
Is the issue present if you create a new `flutter create` project and add the dependencies?
Thank you
