### ISSUE TITLE
[📚] Phone Verification Android Set up

### ISSUE THREAD

**Issue by mrgnhnt96** [FirebaseExtended/flutterfire#5393]
This might be explained already, just difficult to find...

When setting up for Phone Auth, the docs for iOS set up works just fine, but android fails for whatever reason.

After some digging I found that I was missing a dependency within the `app/build.gradle`. I needed to add the following under dependencies.

`implementation "androidx.browser:browser:1.2.0"`

This is for the reCaptcha verification. 

Is this the correct way to handle this? Or should the docs be updated to include this step?

**Comment by markusaksli-nc** [comment]
Hi @mrgnhnt96 
That workaround is correct for now. This is a known issue https://github.com/FirebaseExtended/flutterfire/issues/4651
This could still be added to the documentation for Phone Auth until that gets solved.
Thank you

**Comment by russellwheatley** [comment]
#4651 is now resolved and this workaround is no longer needed.
