### ISSUE TITLE
🐛authentication Your issue title here

### ISSUE THREAD

**Issue by Puspharaj** [FirebaseExtended/flutterfire#5400]
Looks strange, Did I miss something here?.

Flutter version - 2.0.1 stable,
Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

I'm running the website using main run mode. Not the terminal mode of run( different issue).

When authenticating using google signin at firebase, It doesn't take the mobile number password, So the case should be either email or mobile and the password.

1). Email authentication only works, when choosing mobile and password it says reset the password. Strange and weird.

2). The terminal mode can remember my login session successfully, but the run mode from main.dart causing reset and not remembering the session, meaning i have to login using email every time if close the VScode and opening it again Or windows. - all this happened in developing mode not into the production because I have not tested it in production.

Please look into it. Thanks!

**Comment by Puspharaj** [comment]
Authentication Web
Status: complete, shipped 🚢 .
This added in the follow new feature changes;
support for EmailAuthProvider.credentialWithLink
support for FirebaseAuth.setSettings
support for User.tenantId
**### FirebaseAuthException now supports email & credential properties**
ActionCodeInfo now supports previousEmail field

**Comment by markusaksli-nc** [comment]
Hi @Puspharaj 
I don't exactly understand the issue here. Could you specify what is the expected vs actual behavior?
Could you provide your `flutter pub deps -- --style=compact`?
Thank you

**Comment by Puspharaj** [comment]
expected : session long live auth.
actual : session no longer lived and google sign in to auth again.

When I enter mobile no in google signin it's days reset the password.

**Comment by markusaksli-nc** [comment]
So on mobile, you need to sign in again after some time with google sign in?

**Comment by Puspharaj** [comment]
typo every where, sorry for that. @markusaksli-nc, when I use/ run from main.dart **run** function in VSCODE, The signin session gets reset every time. Let's say when I close the VSCODE, I need to again supply the gmail login, email and password. 

If I try to supply the mobile no, It's says please reset the password. (will add picture).
![image](https://user-images.githubusercontent.com/4646391/112708726-bde6d080-8ed9-11eb-9d0f-a7a5af708d28.png)

This is clearly not implemented right now.  At least the session could have remembered instead of login every time. 

But the session remembering no longer an issue when run the flutter web application from the terminal like. flutter run -d chrome --web-port 5552.

**Comment by markusaksli-nc** [comment]
This behavior simply happens due to the persistence being saved in the browser based on the different ports in use when you just `flutter run -d chrome`. This isn't something we can really change ourselves. You can get around this by either adding the port option in the VSCode run configuration or running from terminal.

As for the mobile behavior that is from the native google sign in side, we don't actually process the password.

Closing since there really isn't anything for us to fix here.

**Comment by Puspharaj** [comment]
nope, would you try simple counter app with authentication in vscode?, the application even doesn't remember the authenticated user. Meaning every time have to login again, after app closed or windows restarted. The port seems to be no effect at all.
