### ISSUE TITLE
Firebase Messaging is Not working On "7.0.3" version

### ISSUE THREAD

**Issue by m1narul** [FirebaseExtended/flutterfire#5401]
Firebase messaging is not working in IOS but working good in ANDROID.
Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>NettMob</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>NettMob</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>To capture profile photo please grant camera access</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>This app needs access to location when open.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app needs access to location always open.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location when open.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>App needs access to photo lib for profile images</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

Added Fun()
// ignore: missing_return
Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) {
  if (message.containsKey('data')) {
    // Handle data message
    final dynamic data = message['data'];
    print(data);
  }

  if (message.containsKey('notification')) {
    // Handle notification message
    final dynamic notification = message['notification'];
    print(notification);
  }

  // Or do other work.
}
class Splash extends StatefulWidget {
  @override
  _SplashState createState() => new _SplashState();
}

class _SplashState extends State<Splash> with SingleTickerProviderStateMixin {
  final LandingController _landingController = Get.put(LandingController());
  AnimationController animationController;
  Animation<double> animation;
  var _visible = true;
  FirebaseMessaging firebaseMessaging = new FirebaseMessaging();  //String _selectedLang;

  startTime() async {
    var _duration = new Duration(seconds: 3);
    return new Timer(_duration, _landingController.toLanding);
  }

  @override
  void initState() {
    super.initState();
    //_selectedLang = LocalizationService.langs.first;
    animationController = new AnimationController(
        vsync: this, duration: new Duration(seconds: 2));
    animation = new CurvedAnimation(
        parent: animationController, curve: Curves.easeInOut);

    animation.addListener(() => this.setState(() {}));
    animationController.forward();

    setState(() {
      _visible = !_visible;
    });
    firebaseMessaging.configure(onLaunch: (Map<String, dynamic> msg) async {
      print("onlaunch");
      //isNotification = true;
    }, onResume: (Map<String, dynamic> msg) async {
      print("onresume");
      //isNotification = true;
    }, onMessage: (Map<String, dynamic> msg) async {
      print("onmessage");
      _landingController.showNotification();
      //isNotification = true;
      //onBackgroundMessage: myBackgroundMessageHandler;
    }
    ,onBackgroundMessage:GetPlatform.isIOS ? null : myBackgroundMessageHandler,
    );
    firebaseMessaging.requestNotificationPermissions(
      const IosNotificationSettings(
        sound: true,
        alert: true,
        badge: true,
      ),
    );
    firebaseMessaging.onIosSettingsRegistered.listen((setting) {});
    firebaseMessaging.getToken().then((token) {
      updateToken(token);
    });
    startTime();
  }

  @override
  void dispose() {
    animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ScreenConstant.setScreenAwareConstant(context);
    return Scaffold(
      backgroundColor: AppColors.commonColor,
      body: SafeArea(
        child: Stack(
          fit: StackFit.expand,
          children: <Widget>[
            //LanguageDropDown
            /*Positioned(
              top: 20,
              right: 20,
              child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                  icon: Icon(Icons.keyboard_arrow_down_rounded,color: AppColors.white,),
                  hint: Text(AppLabels.Language.tr,style: TextStyles.titleWhite,),
                  items:  LocalizationService.langs.map((String lang) {
                    return DropdownMenuItem(value: lang, child: Text(lang));
                  }).toList(),
                  onChanged: (String value) {
                    // updates dropdown selected value
                    setState(() => _selectedLang = value);
                    // gets language and changes the locale
                    LocalizationService().changeLocale(value);
                    startTime();
                    ShareStore().saveData(store: KeyStore.lang,object: _selectedLang);
                  },
                ),
              )
            ),*/
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                new Image.asset(
                  Assets.splashLogo,
                  width: /*animation.value **/ 250,
                  height: /*animation.value **/ 250,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
  updateToken(String token) {
    debugPrint("Token : $token");
    if (!mounted) return;
    _landingController.updateToken(token);
  }
}
Added GoogleService-Info.plist as respective location.
Getting the notification when The app is in Resume state. But on Background or Killed state Not geting Any Notification When App is lunching than again getting all the notification. Please help.

**Comment by markusaksli-nc** [comment]
Hi @m1narul 
The version you are using is outdated. If the issue persists on the latest `firebase_messaging: ^9.0.0` please open a new issue, follow the issue template, and provide all of the information indicated in the template.
Thank you
