### ISSUE TITLE
RESOLVED 🐛 [cloud_firestore] No podspec found for `cloud_firestore` in `.symlinks/plugins/cloud_firestore/ios`

### ISSUE THREAD

**Issue by vwdewaal** [FirebaseExtended/flutterfire#5419]
## Bug report
I start with a fresh flutter default project.  The only thing I'm doing is adding 
    cloud_firestore: ^1.0.1
to dependencies in pubspec.yaml.  pub get runs fine, but when I try to run the app I get the error message
**Describe the bug**

### Steps to reproduce
1. Open Android studio
2. Create new flutter project
3. add cloud_firestore: ^1.01 to pubspec.yaml
4. do pub.get
5. run app on ios12 simulator

### Expected behavior
I expect the default application to run in the simulator.  

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-x64,
    locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
    ! Error: Vw is not connected. Xcode will continue when Vw is connected. (code -13)

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    [!] No podspec found for `cloud_firestore` in `.symlinks/plugins/cloud_firestore/ios`

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 12 Pro Max.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by vwdewaal** [comment]
Just a further note.  I'm Using Android Studio 4.2 Beta 6.  OSX.
<img width="649" alt="Screenshot 2021-03-21 at 22 30 09" src="https://user-images.githubusercontent.com/10742649/111923008-009d4880-8a95-11eb-9cef-354eb717b4a8.png">

**Comment by markusaksli-nc** [comment]
Hi @vwdewaal 
Did you run `flutter clean` first?
Have you updated your iOS deployment target to at least 10.0?
Thank you

**Comment by vwdewaal** [comment]
Hi Markus,
Yes I did.  I did a short screen recording off my whole process
https://youtu.be/5bkem9pXEgg. 

It shows my whole process for creating the application, running it first time, adding cloud_firestore to pubspec.yaml, and then the error.

**Comment by markusaksli-nc** [comment]
Please try these exact steps and let me know if it still fails
From terminal:
1. `flutter create bug`
2. `cd bug`
3. `flutter pub add cloud_firestore`
4. `open ios/Runner.xcodeproj`
5. Make sure there are no issues with signing and the default package identifier

In your video you did not uncomment the `platform :ios, '10.0'` line at the top of the `Podfile` so it changed nothing. The step you added to `post_install` is not necessary. 

6. You should just change the version in the second line and uncomment it. 

Your `Podfile` should look like this:
<details>
 <summary>Podfile</summary>

```python
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
# You should add this here to improve build times
# pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.3.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
</details>

7. Run from terminal with `flutter run` or from Android Studio

This is of course neglecting the firebase setup (adding the plist) but it should not throw any errors during `pod install` when building.

**Comment by vwdewaal** [comment]
That seems to have sorted it. I notice we're in 1.0.2 now. Maybe that was it?

**Comment by markusaksli-nc** [comment]
Possibly ¯\_(ツ)_/¯

I didn't see this with either version in the first place and it's weird it cropped up but since this is the only report of this I think we can close the issue.
