### ISSUE TITLE
[cloud_firestore] `setData` does not return future in offline mode

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#542]
sdk versions:

```
dart: ">=2.1.0-dev.5.0 <=2.2.0"
flutter: ">=0.2.4 <2.0.0"
cloud_firestore: "0.8.2+3"
```
#### Summary:
Firestore `setData` does not return the `Future` or any kind of indication if device is offline. Code execution stops at
``` dart 
await _firestore.document("users/$userId").setData(data, merge: true);
``` 
It should return the `Future` with some additional information so that further code can execute and branch out based on that `Future` response.

#### Full Description:
I'm developing an app using `BLoC` pattern and using `firestore` with offline data mode enabled. As the `BLoC` pattern says, inputs are `sink` and outputs are `stream`.

I've a profile screen where I'm taking data from user, saving it to `firestore` and on successful save navigating user to main screen.

Using `BLoC` pattern, I've a sink `usernameUpdate` where I accept `ProfileNameModel`. On save button click, I add data to `usernameUpdate` sink. In `bloc`, I'm listening this incoming data and saving it to `firestore`. This is how my `bloc` looks like.
``` dart
final _usernameUpdate = PublishSubject<ProfileNameModel>();
  Sink<ProfileNameModel> get usernameUpdate => _usernameUpdate.sink;
  Observable<bool> get usernameUpdated =>
      _usernameUpdate.asyncMap((model) async {
        var updatedUser = user.value.rebuild((r) => r
          ..name = model.name
          ..username = model.username);
        await _repository.updateUser(updatedUser.toDocument(), updatedUser.id);
        return true;
      });
```
This is `repository` code.

``` dart
Future<void> updateUser(Map<String, dynamic> data, String userId) {
    return _firestore
        .document("$_userCollection/$userId")
        .setData(data, merge: true);
  }
```
On my widget screen I'm listening `usernameUpdated` `stream`. Once I receive data, I navigate user to main screen. 

The above setup works fine when working with active data connection. If the data connection is not available, `updateUser` function does not return `Future` and execution stuck at
``` dart
await _repository.updateUser(updatedUser.toDocument(), updatedUser.id);
``` 
Though the data is saved locally, it never executes `return true;` and UI screen does not get data from the `stream` it is listening and does not navigate to main screen.

Once device get data connection, `firestore` sdk internally writes data to server and then it returns the `future`.

#### Expected
`setData` should return the `Future` with additional information so that next code can execute and branch out based on the response from that `Future`.

**Comment by kroikie** [comment]
@neerajyadav

The issue at https://github.com/flutter/flutter/issues/25415 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @neerajyadav
Did the proposed [solution ](https://github.com/flutter/flutter/issues/25415#issuecomment-536954331
)worked for you?
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by neerajyadav** [comment]
Thanks @iapicca . Technically the video does not show a solution. Looks like this is intended behaviour and `setData` completion handler only get called after server confirms the write. The video shows a pattern how you should use `setData` and what should not be wrote in completion handler.
Well logically its a right move, completion handler execute only after server write confirm. App should not do UI changes in this completion handler.
I think this issue is not relevant anymore. You can close it now.

**Comment by kroikie** [comment]
@neerajyadav thanks for the confirmation.
