### ISSUE TITLE
SocketException: Reading from a closed socket

### ISSUE THREAD

**Issue by stanojevicboban** [FirebaseExtended/flutterfire#5422]
While this is not a blocking issue, not is it breaking the app, but I am getting the following error:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
SocketException: Reading from a closed socket
_RawReceivePortImpl._handleMessage (dart:isolate)
```

I don't have a lot of information on this, except that it happened (so far) only on Samsung Galaxy Note9 device with Android 10. It could be that the internet connection simply broke off before the entire packet is sent, but I guess we could patch this up so the issue is handled by the package itself.

**Comment by markusaksli-nc** [comment]
Hi @stanojevicboban 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
