### ISSUE TITLE
Unable to handle application state from outside of the application

### ISSUE THREAD

**Issue by Rajkumar07793** [FirebaseExtended/flutterfire#5425]
![policyFCM](https://user-images.githubusercontent.com/31760975/111995766-4f072180-8b3f-11eb-8247-b65307ec93da.png)

I am using flutter media notifications with firebase messaging to handle play and pause of music when application is in background but after update of firebase messaging i am unable to handle the state of application due to attached image's issue

**Comment by markusaksli-nc** [comment]
Hi @Rajkumar07793 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
