### ISSUE TITLE
[firebase_messaging] RemoteMessage does not include tag for overwriting notifications

### ISSUE THREAD

**Issue by zaidkazi** [FirebaseExtended/flutterfire#5432]
## Bug report

There is no property for the Android tag that is sent from server

### Steps to reproduce

From the server I can send something like 
`           android: {
                    notification: {
                        tag: "mytag123",
                        channelId: 'mychannel',
                        priority: "high",
                    }
                },`

### Expected behavior

The tag should be included in the remote message or the AndroidNotification within the message

**Comment by Salakar** [comment]
@russellwheatley / @rrousselGit looks like this would be a quick one to add:

 1. `RemoteMessage.Notification` on Android does support [`getTag()`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getTag())
 2. We can add it to Android here: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java#L79 e.g.:

```java
   if (notification.getTag() != null) {
      androidNotificationMap.put("tag", notification.getTag());
    }
```
 3. Finally adding to Dart [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart#L102) and [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart#L30-L43).

**Comment by zaidkazi** [comment]
Thanks guys appreciate it
