### ISSUE TITLE
Warnings from the firebase_analytics plugin on Android: FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#544]
## Steps to Reproduce

1. Create a new project
2. Add a dependency for `firebase_analytics: ^1.0.6`
3. `flutter run`

## Logs

```
[+1999 ms] > Task :firebase_analytics:compileDebugJavaWithJavac
[   +4 ms] Note:
C:\code\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-1.0.6\android\src\main\java\io\flutter\plugins\fir
ebaseanalytics\FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
[   +3 ms] Note: Recompile with -Xlint:unchecked for details.
```

```
Analyzing analyticsissue...
No issues found! (ran in 13.7s)
```

```
[√] Flutter (Channel master, v1.1.2-pre.36, on Microsoft Windows [Version 10.0.17134.471], locale en-GB)
    • Flutter version 1.1.2-pre.36 at C:\code\flutter
    • Framework revision c5251cdc02 (8 hours ago), 2018-12-14 16:09:17 -0800
    • Engine revision 101b27da7a
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\mulde\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\mulde\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by kroikie** [comment]
@mulderpf

The issue at https://github.com/flutter/flutter/issues/25402 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @mulderpf
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by vijaykholiya** [comment]
This error is what I get
Note: /home/vijay_sharma/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-1.2.0+1/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Output of flutter doctor -v:

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at /home/vijay_sharma/Downloads/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/vijay_sharma/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/vijay_sharma/Android/Sdk
    • Java binary at: /home/vijay_sharma/Documents/Android Studio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/vijay_sharma/Documents/Android Studio/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-community/216
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.25

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
