### ISSUE TITLE
why there are  auto import Admob  sdk ,and google play gives warning 

### ISSUE THREAD

**Issue by wangxingxing123654** [FirebaseExtended/flutterfire#5446]
in our project ,we just use [ firebase_crashlytics: ^0.4.0+1
  firebase_dynamic_links: ^0.7.0+1
  firebase_messaging: ^8.0.0-dev.14
],we don't use Admob,BUT google play gives us warning that we have import admob sdk ,is it that could lead our app stopped by the google

**Comment by markusaksli-nc** [comment]
Hi @wangxingxing123654 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

_FYI the versions you are using are all outdated, please use the latest versions from pub.dev_
