### ISSUE TITLE
[cloud_firestore] on iOS online mode only does not work

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#548]
I want to get results only from the server and not from the cache.

Apparently this setting should do what I want : 
`Firestore.instance.settings(persistenceEnabled: false)`

but I'm still getting results from queries when I turn airplane mode ON, at least for iOS (didn't test yet on Android).

**Comment by kroikie** [comment]
@diegolaballos

The issue at https://github.com/flutter/flutter/issues/25284 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @diegolaballos
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

https://github.com/FirebaseExtended/flutterfire/issues/856

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
