### ISSUE TITLE
[📚] firebase_messaging 9.0.1: Unable to navigate while using onBackgroundMessage

### ISSUE THREAD

**Issue by ycv005** [FirebaseExtended/flutterfire#5481]
I want to navigate to particular screen while I get notification from Firebase. 
I am able to do navigate when the App is in Foreground but unable to navigate when App is in on Background or Terminated. 

when calling function from main () : `FirebaseMessaging.onBackgroundMessage` get triggered and then I am unable to navigate as I don't get context.

when calling function from other function like initState or some else location: `FirebaseMessaging.onBackgroundMessage` didn't trigger or being called.

with Firebase_messaging: 7.0.3, it was possible. There is some documentation missing or implementation missing or I missed something. Help needed.

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('here Got a message whilst in the background!');
  print("here Handling a background message: ${message.messageId}");
  print('here Message data: ${message.data}');
  if (message == null) {
    return;
  }
  final String url = message.data['url'];
 // TODO: How to navigate from here, as no context would be available when this function the main ()
}

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp();
  }
```

**Comment by markusaksli-nc** [comment]
Hi @ycv005 
Background message handlers spawn a separate isolate and as such cannot affect the UI thread directly
https://firebase.flutter.dev/docs/messaging/usage#background-messages
It is possible to take this into account (i.e set a variable and use it to determine navigation)
Thank you

**Comment by ycv005** [comment]
May you tell me an example of how to navigate, as I am unable to update the a variable or call a setState from there. Also, I feel now older approach was better as I have able to change UI or take an logic action either its foreground or background.

**Comment by echomartha** [comment]
@ycv005 i am also facing the same issue, do you already solved it?

**Comment by ycv005** [comment]
No, I switched back to version 7.0.3

**Comment by echomartha** [comment]
@ycv005 oh okay

**Comment by ycv005** [comment]
I don't know why the Team has deprecated the Flow which works in any way. @markusaksli-nc

**Comment by ycv005** [comment]
> Hi @ycv005
> Background message handlers spawn a separate isolate and as such cannot affect the UI thread directly
> https://firebase.flutter.dev/docs/messaging/usage#background-messages
> It is possible to take this into account (i.e set a variable and use it to determine navigation)
> Thank you

An example to mentioned in the doc would be good, like how to navigate on using the background messages.
