### ISSUE TITLE
Hi @TahaTesser. Im facing the same issue. Could you help me get rid of this? TIA

### ISSUE THREAD

**Issue by khalils99** [FirebaseExtended/flutterfire#5486]
Hi @TahaTesser 

I'm not experiencing any of the issues anymore. 

thanks

_Originally posted by @osaxma in https://github.com/FirebaseExtended/flutterfire/issues/3792#issuecomment-715200393_

**Comment by TahaTesser** [comment]
Hi @khalils99 
When filing an issue, please follow the templates and provide all the details 
Closing as no info was provided 
Thank you
