### ISSUE TITLE
FCM via APNs Integration - Changes to be made on NotificationService.swift is not documented

### ISSUE THREAD

**Issue by abinmittu** [FirebaseExtended/flutterfire#5498]
On Apple integration of Cloud Messaging (https://firebase.flutter.dev/docs/messaging/apple-integration), Step 3 mentions changes to be made on NotificationService.m file. But I have a NotificationService.swift file. The changes to be made on NotificationService.swift is not documented. If possible can someone help. I am still struggling to get image displayed on notification.

**Comment by markusaksli-nc** [comment]
You can choose Objective C as the language when creating the extension and the guide will work but this should be better documented
