### ISSUE TITLE
onAdFailedToLoad: 3

### ISSUE THREAD

**Issue by oscarshaitan** [FirebaseExtended/flutterfire#55]
Even when I create the key around 2 month ago, I still geting the anoying **onAdFailedToLoad: 3**
What I can do about that?

**Comment by BondarenkoStas** [comment]
@oscarshaitan Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by AlexisThink** [comment]
I have the same problem, i put everything like i see on the example of the package

**Comment by Ehesp** [comment]
It looks as though you're trying to show an advert before it's loaded, therefore nothing can show. Try the below:

```dart
bannerAd = createBannerAd();

// Wait for the banner to load
await bannerAd.load();

// Once loaded, show it
bannerAd.show();
```

I'll close this one for now, please let me know (with a code example) if it still fails to load and I can reopen. 

Thanks
