### ISSUE TITLE
[docs] firebase_messaging ios install guide remove step 4) Remove the use_frameworks! line from ios/Podfile

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#550]
Since #9694 has been closed. The docs should be updated to remove step 4 of the iOS Integration section of the firebase_messaging readme (causes confusion).
> Remove the use_frameworks! line from ios/Podfile (workaround for flutter/flutter#9694).

Direct link to the README: https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/README.md

**Comment by kroikie** [comment]
@danwulff

The issue at https://github.com/flutter/flutter/issues/25172 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @danwulff
given the merged [PR ](https://github.com/flutter/plugins/pull/1532)
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by yamsergey** [comment]
The docs still require to remove `use_frameworks!`.
![image](https://user-images.githubusercontent.com/666661/74023405-e3e0a700-499f-11ea-8d49-69832d1d8689.png)

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓
