### ISSUE TITLE
[cloud_firestore/unknown] error-Invalid argument (dartObject): Could not convert: Instance of 'Timestamp'

### ISSUE THREAD

**Issue by Puspharaj** [FirebaseExtended/flutterfire#5506]
Flutter Web application here - 2.0.1

I'm in the middle of production release, please help asap. Thanks!!

Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

  equatable: ^2.0.0
  firebase_auth: ^1.0.1
  google_sign_in: ^4.5.1
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_core_web: ^1.0.2
  cloud_firestore_web: ^1.0.3
  firebase_storage: ^8.0.1
  firebase_analytics: ^7.0.1

  #2153

I believe this is seems to be resolved but pops up again, cloud_firestore_web: ^1.0.3 to eliminate the error. 

I have bunch of nested objects in main object, While trying to save into firebase firestore , it's throws the error.
This is the object I'm going to save it in firestore.  Item list having timestamp that causing this error again.

             `[Item(78bfc5b6-8208-4ffa-ae19-71226afa9717, Timestamp(seconds=1615961406, 
              nanoseconds=388000000), Timestamp(seconds=1615961406, nanoseconds=388000000)), 
              Item(78bfc5b6-8208-4ffa-ae19-71226afa9717, Timestamp(seconds=1615961406, 
              nanoseconds=388000000), Timestamp(seconds=1615961406, nanoseconds=388000000)), 
              Item(78bfc5b6-8208-4ffa-ae19-71226afa9717, Timestamp(seconds=1615961406, 
              nanoseconds=388000000), Timestamp(seconds=1615961406, nanoseconds=388000000))]
              `

The error occurs at the list of timestamp i gues. Any help appreciated. Thanks!

**Comment by markusaksli-nc** [comment]
Hi @Puspharaj 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Puspharaj** [comment]
` 
                    class Track extends Equatable {
                      const Track({this.id, this.createdDate, this.updatedDate, this.track});
                    
                      final String? id;
                      final List<String>? track;
                      final Timestamp? createdDate;
                      final Timestamp? updatedDate;
                    
                      static const empty = Track(id: '', track: null);
                    
                      @override
                      List<Object?> get props => [id, track, updatedDate, createdDate];
                    
                      TrackEntity toEntity() {
                        return TrackEntity(
                          this.id,
                          this.track,
                          this.createdDate,
                          this.updatedDate,
                        );
                      }
                    
                      static Track fromEntity(TrackEntity entity) {
                        return Track(
                          id: entity.id,
                          track: entity.track,
                          createdDate: entity.createdDate,
                          updatedDate: entity.updatedDate,
                        );
                      }
                    }`

This kind of example model to List<Track> then, when trying to save it in firestore. It's says the above error. Right I can't give reproducible code. Will may do it if it's not working from your side later.

**Comment by darshankawar** [comment]
@Puspharaj 
The above code seems to be from your production app. We would like to have a minimal reproducible code that we can directly copy paste and run to verify the issue you are facing.

**Comment by Puspharaj** [comment]
Ok, please wait for day or two I can post the exact code with error.

**Comment by Salakar** [comment]
cc @Ehesp could this be a converter handler missing here on web for Timestamp in a nested object?

**Comment by Ehesp** [comment]
Tried setting/updating with nested data with Timestamps, all working ok here.

**Comment by Puspharaj** [comment]
Would you please provide the git sample? thanks!!

**Comment by Ehesp** [comment]
```
    FirebaseFirestore.instance
        .doc('foo/bar')
        .set({
          'foo': {
            'bar': [Timestamp.now(), Timestamp.now()]
          }
        })
        .then(print)
        .catchError(print);
```

**Comment by Puspharaj** [comment]
Let me try with my minimal code.

**Comment by Puspharaj** [comment]
Windows crashed, need to patch things up, will provide the minified version shortly.

**Comment by Puspharaj** [comment]
I have tried out the sample by @Ehesp and it's working, But let me close this for now, Will reopen for my specific case were I use Model and Entity data type conversion were things getting really weird. Will soon report my use case error. Thanks! for everyone who took their time to look into this.
