### ISSUE TITLE
_firebaseMessagingBackgroundHandler not trigger on IOS

### ISSUE THREAD

**Issue by vinodjohn007** [FirebaseExtended/flutterfire#5510]
I am creating an application that when a push notifications came app background process do some changes in firebase database. it is working perfectly in Android. But in IOS background process not trigger.

void main() async {
  
  await Firebase.initializeApp();
  
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    print('Got a message whilst in the foreground!');
    print('Message data: ${message.data}');

    if (message.notification != null) {
      print('Message also contained a notification: ${message.notification}');
    }

  
  });

  runApp(MyApp());
 
}

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('trigger........');
}

please help anyone know the issue.

**Comment by Hasilt** [comment]
Looks like this question is better suited for stackoverflow or other community forums. btb, ios  data background messages won't work when the app is terminated/not running state.

**Comment by markusaksli-nc** [comment]
Hi @Hasilt 
Please make sure your iOS background message contains the `content_available: true` key. This is added automatically to data-only messages on the FCM v1 HTTP API (which is also used if you send messages using the Admin SDK) but on the deprecated HTTP API you will need to add it manually.

https://firebase.flutter.dev/docs/messaging/usage#message-types

Please see if this helps and if it still doesn't work please file a new issue and follow the template and provide all of the indicated information.
Thank you
