### ISSUE TITLE
[📚] Cloud Messaging requires a Service Worker registration for Web

### ISSUE THREAD

**Issue by KissBalazs** [FirebaseExtended/flutterfire#5515]
The tutorial for using Messaging https://firebase.flutter.dev/docs/messaging/overview lacks an important part, it does not talk about the required extra service worker for Web ([see my SO question about the matter](https://stackoverflow.com/questions/66867680/flutter-failed-to-register-a-serviceworker-for-scope-with-script-the-script-has))

Importing the following scripts in `index.html`: 
```
 <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-messaging.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-functions.js"></script>
```
Threw this error:
```
:1337/dart_sdk.js:7025 Uncaught (in promise) Error: [firebase_messaging/failed-service-worker-registration] Messaging: 
We are unable to register the default service worker. 
Failed to register a ServiceWorker for scope ('http://localhost:1337/firebase-cloud-messaging-push-scope') with script ('http://localhost:1337/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). .
    at Object.throw_ [as throw] (:1337/dart_sdk.js:5334)
    at firebase_messaging_web.FirebaseMessagingWeb.new.getToken (:1337/packages/firebase_messaging_web/firebase_messaging_web.dart.lib.js:112)
 ...
```
I had to create and register a default ` navigator.serviceWorker.register("/firebase-messaging-sw.js");` file, and the problem went away.

**Comment by shinewanna** [comment]
same issue.

**Comment by dopecoder** [comment]
Hi, Please take a look at [https://firebase.flutter.dev/docs/messaging/usage#handling-messages](url) for documentation.

You have to provide a vapidKey when getToken is called through flutter web. 
The `firebase-service-worker.js` in not needed unless you want to receive notifications in the background.

This issue can be closed.

**Comment by markusaksli-nc** [comment]
The exception is thrown even when you provide a `vapidKey` in `getToken` unless you provide the service worker.

**Comment by aarajput** [comment]
This is how i fixed my issue.
**Solution:**
1. Create file `firebase-messaging-sw.js` inside web folder.
2. Add below script inside that folder.

```
importScripts('https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.6.1/firebase-messaging.js');
firebase.initializeApp({
    apiKey: "API_KEY",
    authDomain: "AUTH_DOMAIN",
    databaseURL: "DATABASE_URL",
    projectId: "PROJECT_ID",
    storageBucket: "STORAGE_BUCKET",
    messagingSenderId: "MESSAGING_SENDER_ID",
    appId: "APP_ID",
    measurementId: "MEASUREMENT_ID"
});
const messaging = firebase.messaging();
```

**Note:** Please replace values with your own.

**Comment by devxpy** [comment]
This is actually documented [here](https://firebase.flutter.dev/docs/messaging/usage/#background-messages) (web tab).
