### ISSUE TITLE
🐛 [cloud_functions] Example app not working in flutter web

### ISSUE THREAD

**Issue by vishnuagbly** [FirebaseExtended/flutterfire#5517]
## Bug report
I was trying to learn how to use the cloud functions package for flutter web, so I tried to run the example app provided, but when I click on the run cloud function it gives me an error. 

### Steps to reproduce

Clone flutterfire repository

1. Go to 'packages/cloud_functions/cloud_functions/example'
2. run 'flutter run'
4. Click on the "Call Function" Button, and see the error

### Expected behavior
The expected behavior would be without the error.
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.0 at D:\flutter
    • Framework revision 60bd88df91 (4 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.dev

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\vishnu Agarwal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.0
cloud_functions_example 0.0.0

dependencies:
- cloud_functions 1.0.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 0.1.3
- firebase_core 1.0.2 [meta firebase_core_platform_interface firebase_core_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- drive 0.0.1-6.0.pre [test_api flutter_test flutter_driver cli_util stack_trace universal_platform source_map_stack_trace flutter]
- flutter_driver 0.0.0 [file meta path vm_service webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- cloud_functions 1.0.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cloud_functions_platform_interface 5.0.0 [meta plugin_platform_interface firebase_core flutter]
- cloud_functions_web 4.0.2 [js cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core 1.0.2 [meta firebase_core_platform_interface firebase_core_web flutter]
- firebase_core_platform_interface 4.0.0 [meta plugin_platform_interface flutter]
- firebase_core_web 1.0.2 [js meta firebase_core_platform_interface flutter flutter_web_plugins]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.1.4 [path]
- clock 1.1.0
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- coverage 0.15.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- file 6.0.0 [meta path]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]        
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- http_multi_server 3.0.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- node_preamble 1.4.13
- package_config 1.9.3 [path charcode]
- path 1.8.0
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.0.0 [file path platform]
- pub_semver 2.0.0 [collection]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.2.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0 [collection]
- universal_platform 0.1.3
- vector_math 2.1.0
- vm_service 5.5.0 [meta]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @vishnuagbly 
What is the error you are getting?
Thank you

**Comment by vishnuagbly** [comment]
@markusaksli-nc there are no errors in the terminal, but here is the screenshot of the app:-

![Screenshot (1)](https://user-images.githubusercontent.com/53317018/112991470-c6166880-9184-11eb-8ff2-48a2f0a62bd9.png)

I guess this is not a user-specific problem but from the firebase cloud functions side only.

**Comment by markusaksli-nc** [comment]
Have you started the emulator and have the cloud function set up? Also if you cloned the flutterfire repository I'm assuming you did not change the package identifiers or the provided firebase credentials?

In general does the issue persist if you set up your own project and just use the example code?

**Comment by vishnuagbly** [comment]
> Have you started the emulator and have the cloud function set up? Also if you cloned the flutterfire repository I'm assuming you did not change the package identifiers or the provided firebase credentials?
> 
> In general does the issue persist if you set up your own project and just use the example code?

Why do I need my own cloud function to run the example app, doesn't flutter fire have its own cloud function and firebase project?

**Comment by markusaksli-nc** [comment]
The example app uses the emulator so naturally, if you have not set up the emulator it will not work. Also if your goal is to learn how to use cloud functions you will need to create your own cloud functions anyway.

**Comment by Salakar** [comment]
> The example app uses the emulator so naturally, if you have not set up the emulator it will not work. Also if your goal is to learn how to use cloud functions you will need to create your own cloud functions anyway.

Correct, we use the functions emulator in our example so you'd need to start the emulator if you're using out example and Firebase project config.
