### ISSUE TITLE
🐛 [admob] Adfraud 

### ISSUE THREAD

**Issue by dvird** [FirebaseExtended/flutterfire#5521]
There is a problem that every app im uploading with flutter Admob, google play detecting it as ad fraud.
In the beginning, I thought its an accident but now after 5 apps of flutter and 4 of native, all 5 detect as fraud, and all 4 native workings well.

**Comment by markusaksli-nc** [comment]
Hi @dvird 
`firebase_admob` will be [deprecated](https://github.com/FirebaseExtended/flutterfire/blob/48f7dd7f919bde3e5ed1c73d5c5e27458b51e5dd/packages/firebase_admob/README.md#deprecation-of-firebase_admob-plugin) in favor of [`google_mobile_ads`](https://pub.dev/packages/google_mobile_ads)

Please switch to it and if you run into any issues please open them at the [package repository](https://github.com/googleads/googleads-mobile-flutter/issues)
Thank you
