### ISSUE TITLE
firebase_ml_vision 0.11.0 Error With  Flutter 2.0.3 • channel stable

### ISSUE THREAD

**Issue by aomlovebank1212** [FirebaseExtended/flutterfire#5534]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.11.0\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':firebase_ml_vision'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':firebase_ml_vision'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                      1,895ms
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Salakar** [comment]
You need to add `firebase_core` as a dependency in your pubspec and follow the documentation starting from here; https://firebase.flutter.dev/docs/overview

> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?
