### ISSUE TITLE
Firebase Admob ad_not_loaded even though ad was loaded.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#554]
Firebase Admob ad_not_loaded even though ad was loaded.
isolation: Android and iOS

ERROR: 
Error on Android
``` Console
I/Ads     ( 5084): Ad is not visible. Not refreshing ad.
I/Ads     ( 5084): Scheduling ad refresh 60000 milliseconds from now.
```
Error on iOS
```Console
Exception has occurred.
PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)
```
DEBUG CONSOLE: 
`( 7041): Ad is not visible. Not refreshing ad.`

CODE: 
``` Dart
import 'package:flutter/material.dart';
import 'package:firebase_admob/firebase_admob.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyAppState> {
  

@override
  void initState() {
    super.initState();
    print("Coins: $_coins");
    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
    RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
    RewardedVideoAd.instance.listener =
        (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
      print("RewardedVideoAd event $event");
      if (event == RewardedVideoAdEvent.rewarded) {
        setState(() {
          _coins += rewardAmount - 6;
        });
        print("Coins: $_coins");
      }
    };
  }

  playAd() {
    if (_coins == 0) {
      RewardedVideoAd.instance.show();
      print("Coins $_coins");
    } else {
      setState(() {
        _coins += -1;
        RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
      });
      print("Coins $_coins");
    }
  }

@override 
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("My App"),
        ),
        body:
        Center(
          child: FlatButton(
            child: Text("Play ad"),
            onPressed: () => playAd(),
          )
        ),
    );
  }

}

```

REPRODUCE: 
Setup admob environment as instructed at [Dart packages: firebase_admob](https://pub.dartlang.org/packages/firebase_admob)

FIX: 
```dart
playAd() {
    if (_coins == 0) {
      setState(() {
        RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
      });
      RewardedVideoAd.instance.show();
      print("Coins $_coins");
    } else {
      setState(() {
        _coins += -1;
        RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
      });
      print("Coins $_coins");
    }
  }
```

SUGGESTION: 
Add .load() to end of the streams, especially for `RewardedVideoAd`

_Originally posted by @JosephDunivan in https://github.com/flutter/flutter/issue_comments#issuecomment-444805824_

**Comment by kroikie** [comment]
@JosephDunivan

The issue at https://github.com/flutter/flutter/issues/25022 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @JosephDunivan
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by iapicca** [comment]
solution proposed on the "twin issue" on Flutter
https://github.com/flutter/flutter/issues/25022#issuecomment-568923339
