### ISSUE TITLE
Cloud functions plugin should throw correct exception on timeout

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#555]
When there is a timeout in the call to a cloud function the plugin throws `FormatException: Invalid envelope`  exception which is misleading. Please see  [Timeout issue](https://github.com/pulyaevskiy/firebase-functions-interop/issues/43) which contains all the details.

**Comment by kroikie** [comment]
@kostaa

The issue at https://github.com/flutter/flutter/issues/24997 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @kostaa
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Salakar** [comment]
Given the age of this issue and that Functions has had a major rework since; I'm going to close this issue in favour of trying the latest release.
