### ISSUE TITLE
Firebase_auth no passwordless signon method

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#557]
It would be great to have an implementation for passwordless signon. Its an option in firebase but not the plugin. Can we add a method and documentation for this?

**Comment by kroikie** [comment]
@JosephDunivan

The issue at https://github.com/flutter/flutter/issues/24995 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @JosephDunivan
given the merged [PR](https://github.com/flutter/plugins/pull/1159) I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 

https://github.com/FirebaseExtended/flutterfire/issues/613

Thank you
