### ISSUE TITLE
Gradle issue with firebase plugins

### ISSUE THREAD

**Issue by momoDragon** [FirebaseExtended/flutterfire#56]
**Error:**
> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

My project has been configured to work with Android X and i am getting this issues when i import 
cloud_firestore: ^0.12.9+1

issues do not appear when all packages have been removed

**Comment by momoDragon** [comment]
Ok i think there is a glitch with the packages.
I had to run this in terminal: 
flutter pub pub cache repair

And after that the error went away

**Comment by bigworld12** [comment]
I have this problem, ran `flutter pub pub cache repair`, but still get the same error 
```
> Task :app:processDebugGoogleServices FAILED
Parsing json file: (project path hidden)\android\app\google-services.json
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
```

**Comment by momoDragon** [comment]
this is my build gradle version:
classpath 'com.android.tools.build:gradle:3.2.1'


try following mine

**Comment by bigworld12** [comment]
thanks, I already solved it, check my issue here https://github.com/FirebaseExtended/flutterfire/issues/69
