### ISSUE TITLE
Firebase storage getdownloadurl doens't work on ios

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#560]
```dart
StorageReference storageReference = storage.ref();
    final StorageReference imagesRef = storageReference.child('posters/$uuid');

    StorageUploadTask uploadTask = imagesRef.putFile(_imageFile);
    print(imagesRef.getDownloadURL());

    var imageURL = await (await uploadTask.onComplete).ref.getDownloadURL();
```

about await getDownloadURL works well on android but doesn't work on ios

**Comment by kroikie** [comment]
@thinkcsww

The issue at https://github.com/flutter/flutter/issues/24967 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @thinkcsww
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by thinkcsww** [comment]
I resolved it by update firebase version
