### ISSUE TITLE
🐛 [cloud_firestore: ^1.0.3] SPI doesn't work:  org.gradle.api.GradleException: Could not generate ServiceRegistry

### ISSUE THREAD

**Issue by yihanseattle** [FirebaseExtended/flutterfire#5639]
## Bug report

**Describe the bug**
[cloud_firestore: ^1.0.3] and lower version doesn't work with Java SPI in a [Native host + add-to-app] hybrid project. Seems like the class file from the [cloud_firestore: ^1.0.3] will throw an IOException when using with SPI. But all other firebase dependencies works perfectly fine, currently has [firebase_messaging: ^9.1.0], [firebase_analytics: ^7.1.1], [firebase_crashlytics: ^1.0.0]. The error below only occurs after adding  [cloud_firestore: ^1.0.3].

Please provide immediate help, suggestions, or explanation if I understand the issue correctly. Seems like it's caused by Java by the SPI library. Did the [cloud_firestore: ^1.0.3] built differently from other Flutter firebase package? Why other packages are fine such as [firebase_messaging: ^9.1.0], [firebase_analytics: ^7.1.1], [firebase_crashlytics: ^1.0.0]? 

What are the options for me now? Can I get the source for [cloud_firestore: ^1.0.3] and compile it locally as Source Dependency on my local machine inside Flutter project? Do we have a tutorial doc for that? 

Detailed error message below: 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/7017516/113389745-6915e080-9345-11eb-8d20-6db179a989bf.png">

- Caused by: org.gradle.api.GradleException: Could not generate ServiceRegistry

- Caused by: java.io.IOException: invalid constant type: 19 at 5

- Cause: invalid constant type: 19 at 5

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/7017516/113390055-de81b100-9345-11eb-8dca-f5e39e874da0.png">

- Caused by: org.gradle.api.GradleException: Could not generate ServiceRegistry

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/7017516/113389983-c742c380-9345-11eb-9b2e-2af192c4af3d.png">

- Caused by: java.io.IOException: invalid constant type: 19 at 5

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/7017516/113389944-b6924d80-9345-11eb-918e-c43febbe0c3d.png">

- Cause: invalid constant type: 19 at 5

### Steps to reproduce

1. In Flutter, add [cloud_firestore: ^1.0.3] in the dependency
2. In Native Android host project, add a Java SPI module denpendency.
4. See error or incorrect behavior

### Expected behavior

Java SPI dependency should be able to load all class files. 

---

## Additional context

all other firebase dependencies works perfectly fine, currently has [firebase_messaging: ^9.1.0], [firebase_analytics: ^7.1.1], [firebase_crashlytics: ^1.0.0]. The error below only occurs after adding  [cloud_firestore: ^1.0.3].

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
yihan_macbook:~ yihan$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.3 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- pedantic 1.9.2 [meta]
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0

```

</details>

---

---

### Flutter doctor

Run `flutter --version` and paste the output below:

<details><summary>Click To Expand</summary>

```
yihan_macbook:~ yihan$ flutter --version
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

</details>

---

**Comment by darshankawar** [comment]
> 2\. In Native Android host project, add a Java SPI module denpendency.

@yihanseattle Not well versed with Java SPI, so can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use to verify this issue ?
