### ISSUE TITLE
🐛 [firebase_remote_config] RemoteConfig should support Web now that FlutterWeb is stable

### ISSUE THREAD

**Issue by eggnstone** [FirebaseExtended/flutterfire#5644]
## Bug report

firebase_remote_config
RemoteConfig should support Web now that FlutterWeb is stable.

**Comment by darshankawar** [comment]
@eggnstone 
Please follow-up in the discussion here: https://github.com/FirebaseExtended/flutterfire/discussions/5593
Closing this as duplicate.
