### ISSUE TITLE
The method 'signInWithGoogle' isn't defined for the type 'FirebaseAuth'.  Try correcting the name to the name of an existing method, or defining a method named 'signInWithGoogle'.

### ISSUE THREAD

**Issue by saeed2g9** [FirebaseExtended/flutterfire#5645]
```
class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  final GoogleSignIn googleSignIn = GoogleSignIn();
  final FirebaseAuth firebaseAuth = FirebaseAuth.instance;
  SharedPreferences preferences;
  bool loading = false;
  bool isLoggedin = false;

  @override
  void initState() {
    super.initState();
    isSignedIn();
  }

  void isSignedIn() async {
    setState(() {
      loading = true;
    });

    preferences = await SharedPreferences.getInstance();
    isLoggedin = await googleSignIn.isSignedIn();

    if (isLoggedin) {
      Navigator.pushReplacement(
          context, MaterialPageRoute(builder: (context) => Homepage()));
    }

    setState(() {
      loading = false;
    });
  }

  Future handleSignIn() async {
    preferences = await SharedPreferences.getInstance();

    setState(() {
      loading = true;
    });

    GoogleSignInAccount account = await googleSignIn.signIn();
    GoogleSignInAuthentication authentication = await account.authentication;

    User user = await firebaseAuth.signInWithGoogle(
        idToken: authentication.idToken,
        accessToken: authentication.accessToken);

    if (user != null) {
      final QuerySnapshot result = await FirebaseFirestore.instance
          .collection("users")
          .where("id", isEqualTo: user.uid)
          .getDocuments();

      final List<DocumentSnapshot> documents = result.documents;

      if (documents.length == 0) {
        FirebaseFirestore.instance
            .collection("users")
            .document(user.uid)
            .setData({
          "id": user.uid,
          "username": user.displayName,
          "profilePicture": user.photoURL,
        });

        await preferences.setString("id", user.uid);
        await preferences.setString("username", user.displayName);
        await preferences.setString("photoUrl", user.photoURL);
      } else {
        await preferences.setString("id", documents[0]['id']);
        await preferences.setString("username", documents[0]['username']);
        await preferences.setString("photoUrl", documents[0]['photoUrl']);
      }
      Fluttertoast.showToast(msg: "Login Successful");
      setState(() {
        loading = false;
      });
      Navigator.pushReplacement(
          context, MaterialPageRoute(builder: (context) => Homepage()));
    } else {
      Fluttertoast.showToast(msg: "Login Failed :(");
    }
  }

```

**Comment by samuk190** [comment]
You're using a newer version of firebase which has changed some methods name.

Try to make it like this and it should work
`  final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();

    final GoogleSignInAuthentication googleAuth =
        await googleUser!.authentication;

    final AuthCredential credential = GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    final User? user = (await _auth.signInWithCredential(credential)).user;
    print("signed In" + user!.displayName!);
    return user;`

**Comment by darshankawar** [comment]
@saeed2g9 
Not sure which version of `firebase_auth` you are using, but check out the updated usage of the plugin here for your reference and update your code accordingly. https://firebase.flutter.dev/docs/auth/usage

**Comment by saeed2g9** [comment]
Thank you very much 


Sent from Yahoo Mail for iPhone


On Monday, April 5, 2021, 07:16, Samuel Wallace Assuncao ***@***.***> wrote:




You're using a newer version of firebase which has changed some methods name.

Try to make it like this and it should work

` final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
final GoogleSignInAuthentication googleAuth =
    await googleUser!.authentication;

final AuthCredential credential = GoogleAuthProvider.credential(
  accessToken: googleAuth.accessToken,
  idToken: googleAuth.idToken,
);

final User? user = (await _auth.signInWithCredential(credential)).user;
print("signed In" + user!.displayName!);
return user;`

**Comment by markusaksli-nc** [comment]
Closing this as solved based on your last message.

**Comment by Duc56789** [comment]
Được gửi từ iPhone của tôi

**Comment by Duc56789** [comment]
Được gửi từ iPhone của tôi

> Vào ngày 16 thg 4, 2021, lúc 16:52, saeed2g9 ***@***.***> đã viết:
> 
> ﻿
> Thank you very much 
> 
> 
> Sent from Yahoo Mail for iPhone
> 
>
