### ISSUE TITLE
[cloud_firestore] Documentation for the reference data type required

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#565]
Personally I would like to be able to decide whether referenced documents' data is included in queries or not. It seems to me that referenced documents each need a second request to be retrieved. However, it would of course be nice to know if this were true.

Not only in flutter but in other frameworks (such as VueFire) the reference data type seems to be inconsistently handled, which means it is not reliable to use the reference data type.

At first glance I was very happy that firestore has a reference field, but in practice it took a lot more time to understand how to use it poorly than to just use strings and retrieve the documents manually.

I think it's certainly an issue to implement the reference type (without a warning) if they make the development process more difficult than implementing the functionality yourself.

**Comment by kroikie** [comment]
@RobinManoli

The issue at https://github.com/flutter/flutter/issues/24819 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by MichalDanielDobrzanski** [comment]
Any update on this?

**Comment by Salakar** [comment]
Hey this has been fixed as part of #2582 / #2913  - pending release.
