### ISSUE TITLE
Module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by luccaayerza** [FirebaseExtended/flutterfire#5652]
I am coding an app that is made on Flutter. I use Firebase Firestore as a database. I added cloud_firestore as a dependency in pubspec.yaml. When I build the apk for android it works perfectly fine, but in Xcode when I'm trying to build the app for iOS I have an error ( attached image ) 'Module cloud_firestore' not found, all the other dependencies are working. I've tried everything: pod install, pod update, remove Podfile, remove Podfile.lock, I even created a blank app and added cloud_firestore as dependency and it still happens.

**Comment by Salakar** [comment]
👋  - please see https://stackoverflow.com/questions/64362285/flutter-on-ios-fatal-error-module-cloud-firestore-not-found

Thanks

**Comment by luccaayerza** [comment]
Hello @Salakar, thanks for answering. I tried what you suggested and other things but I couldn't solve it. Do you have any other suggestions to fix it? Thanks

**Comment by mattostanik** [comment]
@luccaayerza I saw your issue while experiencing the same problem myself: Module 'cloud_firestore' not found. It seems like this same issue is getting posted repeatedly here, and it keeps getting closed without a clear resolution.

The solution that worked for me was to delete the entire ios directory in my Flutter project then rebuild it with "flutter create -i swift .". It was time consuming but it solved the problem after all of the other suggestions I found did not work.

**Comment by luccaayerza** [comment]
> @luccaayerza I saw your issue while experiencing the same problem myself: Module 'cloud_firestore' not found. It seems like this same issue is getting posted repeatedly here, and it keeps getting closed without a clear resolution.
> 
> The solution that worked for me was to delete the entire ios directory in my Flutter project then rebuild it with "flutter create -i swift .". It was time consuming but it solved the problem after all of the other suggestions I found did not work.

Thank you.
