### ISSUE TITLE
Writing DateTime to Firestore via Ipad produces incorrect server-side timestamp

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#566]
I know this issue is solved for iPhones but on the iPad I still get the date as "January 17, 1970" when writing any date to Cloud Firestore.

**Comment by kroikie** [comment]
@mabinici

The issue at https://github.com/flutter/flutter/issues/24809 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @mabinici
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
