### ISSUE TITLE
[Cloud-Firestore] Update documentation to reflect query limitations using `arrayContains` and `whereNotIn` in the same query.

### ISSUE THREAD

**Issue by saveKenny** [FirebaseExtended/flutterfire#5661]
When I run the above query:

```
snapshot = await FirebaseFirestore.instance
          .collection('dialogs')
          .where('active', isEqualTo: true)
          .where('end_time', isGreaterThan: DateTime.now())
          .orderBy('end_time')
          .where('users', arrayContains: globals.user.userId)
          .where('readers', whereNotIn: [globals.user.userId])
          .orderBy('priority')
          .limit(1)
          .get();
```

I'm getting:

> An error occurred while parsing query arguments, see native logs for more information. Please report this issue.

I have uploaded a [question to stackoverflow](https://stackoverflow.com/q/66891023/12695188) but so far there were no answers (There are more details on stackoverflow).

Please help me to figure out if it's a bug or a problem in my query. I have read the [firestore query documentation](https://firebase.google.com/docs/firestore/query-data/queries) and everything should be just fine.

Thanks!

**Comment by saveKenny** [comment]
I have checked my logchats and found out the above exception:

> Invalid Query. You cannot use 'not_in' filters with 'array_contains' filters.

While Firebase [documentation](https://firebase.google.com/docs/firestore/query-data/queries) does not mention that. The documentation says that 'not_in' and 'array_contains_any' cannot be on the same query.

I don't know if it's relevant to you but the Firebase documentation need to be updated.

Regards

**Comment by darshankawar** [comment]
@saveKenny Thanks for digging in and identifying the error.
According to the documentation https://firebase.google.com/docs/firestore/query-data/queries#query_limitations, it mentions:

`You can use at most one in, not-in, or array-contains-any clause per query. You can't combine in , not-in, and array-contains-any in the same query.`

Is that statement confusing or need to be better worded ? Also, How would you like the document to be updated with ?

**Comment by saveKenny** [comment]
Hey @darshankawar thanks for replying. Yes the documentation should mention that `array-contains` is also cannot be combined at the same query. 

From what is written I do not understand that `array-contains` has also restrictions same as that `array-contains-any` cannot be combined with `not-in` and `in`.

**Comment by darshankawar** [comment]
Thanks for clarifying.

**Comment by saveKenny** [comment]
I don't think it's the right place for documentation issue. Also I cannot find a place to report documentation issues.

I decided to report this issue to Firebase support team, They will deliver the issue to the relevant team.

**Comment by darshankawar** [comment]
I agree.

**Comment by darshankawar** [comment]
@saveKenny I think I misread your last comment. Can you share the issue link here so that it'll be useful for others coming here with same issue.
Also, I think we can close this issue, since you've already reported it to Firebase support team.

**Comment by saveKenny** [comment]
I have opened a direct request to Firebase support team since there is no place for documentation issues. It's a direct request via mail so it cannot be shared here :\
