### ISSUE TITLE
[UnimplementedError] Unable to fetch data from firebase firestore flutter web

### ISSUE THREAD

**Issue by awaisdev5765** [FirebaseExtended/flutterfire#5664]
```
Error: UnimplementedError
at Object.throw_ [as throw] (http://localhost:51075/dart_sdk.js:5334:11)
at bind (http://localhost:51075/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3434:21)
at bind.next ()
at runBody (http://localhost:51075/dart_sdk.js:39052:34)
at Object._async [as async] (http://localhost:51075/dart_sdk.js:39083:7)
at Function.bind (http://localhost:51075/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3431:20)
at getNtpOffset (http://localhost:51075/packages/ntp/ntp.dart.lib.js:128:63)
at getNtpOffset.next ()
at http://localhost:51075/dart_sdk.js:39032:33
at _RootZone.runUnary (http://localhost:51075/dart_sdk.js:38889:58)
at _FutureListener.thenAwait.handleValue (http://localhost:51075/dart_sdk.js:33875:29)
at handleValueCallback (http://localhost:51075/dart_sdk.js:34435:49)
at Function._propagateToListeners (http://localhost:51075/dart_sdk.js:34473:17)
at _Future.new.[_completeWithValue] (http://localhost:51075/dart_sdk.js:34315:23)
at async._AsyncCallbackEntry.new.callback (http://localhost:51075/dart_sdk.js:34338:35)
at Object._microtaskLoop (http://localhost:51075/dart_sdk.js:39176:13)
at _startMicrotaskLoop (http://localhost:51075/dart_sdk.js:39182:13)
at http://localhost:51075/dart_sdk.js:34689:9

```
Note
ANDROID AND IOS WORKING PERFECTLY JUST FACING ISSUE IN WEB

**Comment by darshankawar** [comment]
@awaisdev5765 
Can you provide `flutter doctor -v`, `flutter pub deps -- --style=compact` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this issue ?
Thanks.

**Comment by awaisdev5765** [comment]
+20 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +127 ms] Skipping pub get: version match.
[ +64 ms] Found plugin cloud_firestore at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/
[ +14 ms] Found plugin cloud_firestore_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.1+2/
[ +17 ms] Found plugin firebase_analytics at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.16/
[ +4 ms] Found plugin firebase_analytics_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[ +5 ms] Found plugin firebase_auth at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/
[ +5 ms] Found plugin firebase_auth_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+3/
[ +2 ms] Found plugin firebase_core at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/
[ +4 ms] Found plugin firebase_core_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+1/
[ +8 ms] Found plugin flutter_facebook_login at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[ +17 ms] Found plugin fluttertoast at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/
[ +16 ms] Found plugin google_sign_in at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.9/
[ +6 ms] Found plugin google_sign_in_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[ +32 ms] Found plugin path_provider at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
[ +2 ms] Found plugin path_provider_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[ +3 ms] Found plugin path_provider_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[ +4 ms] Found plugin path_provider_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[ +28 ms] Found plugin shared_preferences at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[ +2 ms] Found plugin shared_preferences_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[ +2 ms] Found plugin shared_preferences_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[ +5 ms] Found plugin shared_preferences_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[ +4 ms] Found plugin shared_preferences_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[ +180 ms] Found plugin cloud_firestore at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/
[ +4 ms] Found plugin cloud_firestore_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.1+2/
[ +10 ms] Found plugin firebase_analytics at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.16/
[ +3 ms] Found plugin firebase_analytics_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[ +1 ms] Found plugin firebase_auth at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/
[ +5 ms] Found plugin firebase_auth_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+3/
[ +3 ms] Found plugin firebase_core at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/
[ +3 ms] Found plugin firebase_core_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+1/
[ +4 ms] Found plugin flutter_facebook_login at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[ +3 ms] Found plugin fluttertoast at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/
[ +12 ms] Found plugin google_sign_in at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.9/
[ +2 ms] Found plugin google_sign_in_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[ +26 ms] Found plugin path_provider at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
[ +2 ms] Found plugin path_provider_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[ +2 ms] Found plugin path_provider_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[ +4 ms] Found plugin path_provider_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[ +17 ms] Found plugin shared_preferences at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[ +1 ms] Found plugin shared_preferences_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[ +1 ms] Found plugin shared_preferences_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[ +2 ms] Found plugin shared_preferences_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[ +1 ms] Found plugin shared_preferences_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[ +49 ms] Generating /Users/awaisrehmn/AndroidStudioProjects/my_hussain/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +278 ms] Launching lib/main.dart on Chrome in debug mode...
[ +163 ms] Updating assets
[ +144 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[ +3 ms] Waiting for connection from debug service on Chrome...
[ +11 ms] Found plugin cloud_firestore at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/
[ +1 ms] Found plugin cloud_firestore_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.1+2/
[ +4 ms] Found plugin firebase_analytics at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.16/
[ +1 ms] Found plugin firebase_analytics_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[ +1 ms] Found plugin firebase_auth at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/
[ +1 ms] Found plugin firebase_auth_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+3/
[ ] Found plugin firebase_core at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/
[ +1 ms] Found plugin firebase_core_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+1/
[ +2 ms] Found plugin flutter_facebook_login at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[ +4 ms] Found plugin fluttertoast at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/
[ +4 ms] Found plugin google_sign_in at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.9/
[ +1 ms] Found plugin google_sign_in_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[ +11 ms] Found plugin path_provider at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
[ +2 ms] Found plugin path_provider_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[ +1 ms] Found plugin path_provider_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[ +3 ms] Found plugin path_provider_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[ +9 ms] Found plugin shared_preferences at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[ ] Found plugin shared_preferences_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[ ] Found plugin shared_preferences_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[ +1 ms] Found plugin shared_preferences_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[ +1 ms] Found plugin shared_preferences_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[ +45 ms] Found plugin cloud_firestore at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/
[ +1 ms] Found plugin cloud_firestore_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.1+2/
[ +6 ms] Found plugin firebase_analytics at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.16/
[ +3 ms] Found plugin firebase_analytics_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[ +2 ms] Found plugin firebase_auth at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/
[ +1 ms] Found plugin firebase_auth_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+3/
[ +1 ms] Found plugin firebase_core at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/
[ +1 ms] Found plugin firebase_core_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+1/
[ +5 ms] Found plugin flutter_facebook_login at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
[ +4 ms] Found plugin fluttertoast at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/
[ +3 ms] Found plugin google_sign_in at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.9/
[ +2 ms] Found plugin google_sign_in_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[ +15 ms] Found plugin path_provider at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.28/
[ +2 ms] Found plugin path_provider_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[ +1 ms] Found plugin path_provider_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[ +1 ms] Found plugin path_provider_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[ +7 ms] Found plugin shared_preferences at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[ ] Found plugin shared_preferences_linux at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[ ] Found plugin shared_preferences_macos at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[ +3 ms] Found plugin shared_preferences_web at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[ +3 ms] Found plugin shared_preferences_windows at /Users/awaisrehmn/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[ +114 ms] <- reset
[ +14 ms] /Users/awaisrehmn/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/awaisrehmn/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/awaisrehmn/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/ln/9wtls7bj48l712r9z09140280000gn/T/flutter_tools.XR1BEE/flutter_tool.cdBzs7/app.dill --libraries-spec file:///Users/awaisrehmn/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/awaisrehmn/AndroidStudioProjects/my_hussain/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/ln/9wtls7bj48l712r9z09140280000gn/T/flutter_tools.XR1BEE/flutter_tools.k6aYGL --filesystem-scheme org-dartlang-app --initialize-from-dill build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///Users/awaisrehmn/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[ +27 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+30020 ms] Waiting for connection from debug service on Chrome... (completed in 30.3s)
[ +1 ms] Synced 45.9MB.
[ ] <- accept
[ ] Caching compiled dill
[ +99 ms] Using Google Chrome 89.0.4389.114
[ +586 ms] [CHROME]:
[ +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:55617/devtools/browser/c0c2e1a5-8132-4b72-87e1-ef3154b1d055
[+1374 ms] DwdsInjector: Received request for entrypoint at http://localhost:55596/main_module.bootstrap.js
[ +7 ms] MetadataProvider: Loading debug metadata...
[ +23 ms] MetadataProvider: Loaded debug metadata
[ +13 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:55596/main_module.bootstrap.js
[+2907 ms] DevHandler: Debug service listening on ws://127.0.0.1:55647/heLTpq_heUM=/ws
ive just share adroid and web flutter -run igored ios

- 

- 

-

**Comment by awaisdev5765** [comment]
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-PK)
• Flutter version 2.0.3 at /Users/awaisrehmn/flutter
• Framework revision 4d7946a (2 weeks ago), 2021-03-18 17:24:33 -0700
• Engine revision 3459eb2436
• Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /Users/awaisrehmn/Library/Android/sdk
• Platform android-30, build-tools 30.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.4, Build version 12D4e
• CocoaPods version 1.10.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
• Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

**Comment by awaisdev5765** [comment]
<script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-app.js"></script> <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-auth.js"></script> <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-analytics.js"></script> <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-storage.js"></script> <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
i ve done everything which third party firebase mentioned for web

**Comment by markusaksli-nc** [comment]
Please provide your `flutter pub deps -- --style=compact` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by awaisdev5765** [comment]
Dart SDK 2.12.2
Flutter SDK 2.0.3
my_hussain 1.0.0+2

dependencies:
- app_intro 1.0.2 [flutter]
- apple_sign_in 0.1.0 [flutter]
- auto_size_text 2.1.0 [flutter]
- badges 1.2.0 [flutter]
- circular_countdown_timer 0.0.9 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- crypto 2.1.5 [collection convert typed_data]
- cupertino_icons 1.0.2
- firebase 7.3.3 [http http_parser js]
- firebase_analytics 5.0.16 [meta flutter firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_web 5.0.9 [googleapis_auth http js service_worker]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_automation 1.4.0 [flutter args yaml path http]
- flutter_custom_clippers 1.1.2 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_icons 1.1.0 [flutter]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- fluttertoast 7.1.8 [flutter flutter_web_plugins]
- font_awesome_flutter 8.12.0 [flutter]
- get 3.26.0 [flutter]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- mailer 3.3.0 [async logging intl mime path pedantic]
- ntp 1.0.8 [universal_io]
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- provider 4.3.3 [collection flutter nested]
- random_string 2.1.0
- responsive_framework 0.0.15 [flutter]
- route_generator 0.1.5 [flutter source_gen route_annotation analyzer build]
- rxdart 0.25.0
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 2.5.4 [meta flutter]
- simple_animations 2.5.1 [flutter supercharged sa_v1_migration pedantic]
- toast 0.1.5 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- analyzer 0.38.5 [args charcode collection convert crypto front_end glob html kernel meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.3 [analyzer args path source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- front_end 0.1.27 [kernel package_config meta]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- googleapis_auth 0.2.12+1 [crypto http]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- kernel 0.3.27 [args meta]
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 0.9.7
- nested 1.0.0 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.1.1 [node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.5 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- process 4.2.1 [file path platform]
- pub_semver 1.4.4 [collection]
- quiver 2.1.5 [matcher meta]
- route_annotation 0.2.1
- sa_v1_migration 1.1.2 [flutter]
- service_worker 0.2.4 [js]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_gen 0.9.4+6 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- universal_io 1.0.2 [crypto meta zone_local]
- vector_math 2.1.0
- watcher 0.9.7+15 [async path pedantic]
- win32 2.0.5 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
- zone_local 0.1.2

**Comment by markusaksli-nc** [comment]
Please upgrade to the latest version of `cloud_firestore`. If the issue persists please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by awaisdev5765** [comment]
i ve upgraded but facing same issue
