### ISSUE TITLE
🐛 [firebase_messaging] Not receiving remote notifications on macOS

### ISSUE THREAD

**Issue by efraespada** [FirebaseExtended/flutterfire#5668]
## Bug report

When sending notifications to macOS tokens, nothing happens on the app.
The same message works when sending notifications to Android and iOS tokens.

### Steps to reproduce

1. Send a message to any macOS token. 
2. Nothing enters on `FirebaseMessaging.onBackgroundMessage` or `FirebaseMessaging.onMessage.listen`.

### Expected behavior

Receiving remote notifications in macOS applications as in Android or iOS, where everything works.

---

### Flutter doctor
<details>
<summary>
Click To Expand
</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
[✓] Connected device (5 available)
```

</details>

**Comment by darshankawar** [comment]
@efraespada 
Per your comments here https://github.com/FirebaseExtended/flutterfire/issues/5473, seems to be the same issue you are facing ? Can this issue be tracked there ?

**Comment by efraespada** [comment]
I'm not sure.

This one is because there is no remote notification in macOS (`FirebaseMessaging.onBackgroundMessage` or `FirebaseMessaging.onMessage.listen`). 

By the moment with #5473 I'm allowing notifications manually in the _System Preferences_.

So I think they are different.

Other methods like `FirebaseMessaging.instance.getToken()` works as expected.

**Comment by darshankawar** [comment]
Labeling it based on the report above.

**Comment by efraespada** [comment]
I've tested my iOS `GoogleService-Info.plist` in the example project but it doesn't work on macOS either.

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example

**Comment by Duc333333** [comment]
https://www.cloudflare.com/img/athenian/interactive/8-1.svg

**Comment by russellwheatley** [comment]
I'm closing this in favour of tracking the same issue here: #5473
