### ISSUE TITLE
🐛 [firebase_remote_config] IOS doesn't fetch lists

### ISSUE THREAD

**Issue by ShaikaJar** [FirebaseExtended/flutterfire#5680]
In my app i try to fetch a list from remoteconfig. In android everything works. In ios i gett al values except for lists. The lists are correctly formated json.

**Comment by darshankawar** [comment]
@ShaikaJar 
Can you provide `flutter doctor -v`, [a complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter pub deps -- --style=compact` ?
Thanks.

**Comment by Filaind** [comment]
Have same issue on IOS

<details>
  <summary> flutter doctor -v</summary>

> [✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale ru-RU)
    • Flutter version 2.0.4 at /Users/stanislav/Documents/flutter
    • Framework revision b1395592de (6 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/stanislav/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
[✓] Connected device (2 available)
    • iPhone Stanislav (mobile) • 00008030-001975323E92802E • ios            • iOS 14.4.2
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 89.0.4389.114

</details>

<details>
  <summary>flutter pub deps</summary>
Dart SDK 2.12.2
Flutter SDK 2.0.4

dependencies:
- adaptive_dialog 0.10.0+5 [animations flutter meta]
- apple_sign_in 0.1.0 [flutter]
- auto_size_text 2.1.0 [flutter]
- cached_network_image 2.5.1 [flutter flutter_cache_manager octo_image]
- carousel_slider 3.0.0 [flutter]
- cupertino_icons 1.0.2
- delayed_display 1.1.0 [flutter]
- device_apps 2.0.2 [flutter]
- device_info 2.0.0 [flutter device_info_platform_interface]
- dio 4.0.0 [http_parser path]
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- event_bus 2.0.0
- expandable 5.0.1 [flutter]
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 0.9.0-dev.2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_animator 3.1.1 [flutter vector_math]
- flutter_easyloading 3.0.0 [flutter flutter_spinkit]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_login_vk 1.0.0 [async flutter]
- flutter_simple_rating_bar 0.0.3 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_staggered_animations 1.0.0 [flutter]
- flutter_staggered_grid_view 0.3.4 [flutter]
- flutter_xlider 3.4.0 [flutter]
- font_awesome_flutter 8.12.0 [flutter]
- get 4.1.1 [flutter]
- get_storage 2.0.2 [flutter get path_provider]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_crop 0.3.4 [flutter]
- image_gallery_saver 1.6.8 [flutter]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- in_app_review 2.0.1 [flutter in_app_review_platform_interface]
- intl 0.17.0 [clock path]
- jiffy 4.1.0 [intl]
- loading_indicator 1.2.0 [flutter async]
- location 4.1.1 [flutter location_platform_interface location_web meta]
- onesignal_flutter 2.6.3 [flutter]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- percent_indicator 2.1.9+1 [flutter]
- photo_view 0.11.1 [flutter]
- pin_code_fields 7.0.0 [flutter]
- pull_to_refresh 1.6.4 [flutter]
- screenshot 0.3.0 [flutter]
- share 2.0.1 [meta mime flutter]
- smooth_page_indicator 0.2.3 [flutter]
- socket_io_client 0.9.12 [logging socket_io_common]
- styled_text 1.0.3+4 [flutter xmlstream]
- system_settings 1.0.1 [flutter]
- uni_links 0.4.0 [flutter]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- uuid 3.0.3 [crypto]

transitive dependencies:
- animations 2.0.0 [flutter]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.0 [collection typed_data]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- easy_logger 0.0.2 [flutter]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.2.0-dev.1 [firebase_core flutter meta plugin_platform_interface]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_spinkit 5.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- in_app_review_platform_interface 2.0.2 [flutter url_launcher plugin_platform_interface platform]
- js 0.6.3
- location_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- location_web 3.0.0 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.0 [matcher]
- rxdart 0.24.1
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- socket_io_common 0.9.2 [logging]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 1.3.2+2 [flutter sqflite_common path]
- sqflite_common 1.0.3 [synchronized path meta]
- stack_trace 1.10.0 [path]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- xmlstream 0.12.0

</details>


Example code

> Future initRemoteConfig() async {
> remoteConfig = RemoteConfig.instance;

>  final defaults = <String, dynamic>{
    'safe_mode': false,
  };

>  await remoteConfig.setDefaults(defaults);

>  await remoteConfig.fetch();
>  await remoteConfig.activate();

>  var safemod = remoteConfig.getBool('safe_mode');
>  print(safemod); //Still return FALSE
}

![Снимок экрана 2021-04-07 в 22 36 00](https://user-images.githubusercontent.com/27895981/113930490-a1a83500-97f1-11eb-9350-b9268e817a50.png)

**Comment by darshankawar** [comment]
@Filaind 
Can you try the official `remote_config` plugin [example](https://github.com/truongsinh/flutter-plugins/tree/master/packages/firebase_remote_config/example) and check if you get same behavior ?
If so, can you provide an example of how you are setting a parameter to be a list, which isn't being fetched ?
Thanks.
