### ISSUE TITLE
Android integration - gradle plugin versions

### ISSUE THREAD

**Issue by rowild** [FirebaseExtended/flutterfire#57]
At https://pub.dev/packages/firebase_auth under "1." there is an example how to configure dependencies:
```
dependencies {
  // Example existing classpath
  classpath 'com.android.tools.build:gradle:3.2.1'
  // Add the google services classpath
  classpath 'com.google.gms:google-services:4.3.0'
}
```
This combination does not work and causes an error, this is what the debug console in VSCode prints:
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

(Running `flutter run --stacktrace` or `flutter run --info` does not work either, btw.)

I have never been an Android developer and have no idea, what is going on. Does the gradle plugin have a specific version dependency on the google services? Do I need to have a specific Android version running in my emulator? (Currently a Pixel 3 with API 27...)

The only combination that is working and actually builds the project is:
```
dependencies {
  classpath 'com.android.tools.build:gradle:3.2.1'
  // Add the google services classpath - v4.2.0 works!!
  classpath 'com.google.gms:google-services:4.2.0'
}
```

Please advice! And please improve the documentation! After all Flutter was made for people who do NOT develop with Java or Swift, right? Thank you!

**Comment by BondarenkoStas** [comment]
I created a PR to fix the doc here https://github.com/FirebaseExtended/flutterfire/pull/273

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration
