### ISSUE TITLE
Upgrade firebase_analytics to latest version.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#571]
Firebase analytics on pub seems old. Since many libraries are dependent on firebase_analytics, it results in broken app

**Comment by kroikie** [comment]
@pushangupta

The issue at https://github.com/flutter/flutter/issues/24569 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @pushangupta
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by pushangupta** [comment]
@iapicca The issue can now be safely closed. Its updated now. Thanks

**Comment by iapicca** [comment]
Hi @pushangupta 
thank you for letting me know
