### ISSUE TITLE
E/FlutterFcmService(20850): Fatal: failed to find callback W/FirebaseMessaging(20850): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

### ISSUE THREAD

**Issue by balait2013** [FirebaseExtended/flutterfire#5716]
Flutter Andriod app

i have faced the above issue, Please help us to resolve. Last 10 days i have tried.

my flutter doctor -v

Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_IN.UTF-8)
    • Flutter version 2.1.0-12.1.pre at /home/blackchalk/snap/flutter/common/flutter
    • Framework revision 8264cb3e8a (4 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/blackchalk/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/blackchalk/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /home/blackchalk/android-studio
    • Flutter plugin version 52.0.1
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Redmi Note 9 Pro (mobile) • deded95e • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 80.0.3987.132

• No issues found!

Thank you

**Comment by markusaksli-nc** [comment]
Hi @balait2013 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by balait2013** [comment]
I have provided all the flutter doctor information, any additional information. Kindly mentioned. 
Thank you

**Comment by markusaksli-nc** [comment]
You can just open a new issue. Try to provide all of the information indicated in the template and fill it out. Just an error message makes it unclear what code is raising the error, on what platform, using which version of the package etc.
