### ISSUE TITLE
[firebase_messaging] Stuck in pub get

### ISSUE THREAD

**Issue by ElaineSchwner** [FirebaseExtended/flutterfire#5719]
When I run in terminal flutter pub get is stuck.

It works fine for other libs, but firebase_messaging

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.1)
[✓] Connected device (3 available)

• No issues found!

**Comment by markusaksli-nc** [comment]
This kind of issue should be better suited for https://github.com/dart-lang/pub/issues or https://github.com/flutter/flutter/issues
