### ISSUE TITLE
[[firebase_auth ] account selection popup

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#574]
I'm using the firebase_auth package for email/pass, google, facebook sign in on iOS.

The problem I face is that once I sign in with google account, 
and then sign out. (`firebaseAuth.signOut()`, `googleSignIn.signOut()`)

And I sign in with google account again, 
it **doesn't show the account selection popup.**

I've use the `signInSilently()` as below:
```
GoogleSignInAccount googleSignInAccount = _googleSignIn.currentUser;
if (googleSignInAccount == null) googleSignInAccount = await _googleSignIn.signInSilently();
if (googleSignInAccount == null) googleSignInAccount = await _googleSignIn.signIn();
```

But it shows up the sign in process every time,
so I have to type the username every time.

Is there a way to solve this?
To enable the account selection popup.
Thanks a lot!

**Comment by kroikie** [comment]
@sean1776

The issue at https://github.com/flutter/flutter/issues/24486 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @sean1776
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by kroikie** [comment]
Closing since this looks like a Google Sign In issue and not Firebase related.
