### ISSUE TITLE
bug using firebase_admob(also the google mobile ads package) videorewarded and intertial ads

### ISSUE THREAD

**Issue by ninehichem** [FirebaseExtended/flutterfire#5749]
there is problem when calling :FirebaseAdMob.instance.initialize(appId:"your id");
and using the videorewarded or intertial 
the app exit 
connection lost to device 
as you can see in the picture !

my gradle version is 6.5 .
admob latest version .
i tried to clean flutter but same problem.
i hope you can fix it fast .
thanks
![problem](https://user-images.githubusercontent.com/36598259/114461933-39fa3d00-9b97-11eb-9c0e-3ed91c137ff5.png)
for the banner it works fine.

**Comment by 2shrestha22** [comment]
You should not be using firebase_admob, this plugin is discontinued in the favor of new plugin, google_mobile_ads. And I think firebase_admob is also removed from pub.dev. You will not get any support for this plugin.

Please close this issue and try google_mobile_ads. google_mobile_ads is working fine with current version 0.12.1.

**Comment by ninehichem** [comment]
> You should not be using `firebase_admob`, this plugin is discontinued in the favor of new plugin, `google_mobile_ads`. And I am not able to find `firebase_admob` in pub.dev also. You will not get any support for this plugin.
> 
> Please close this issue and try `google_mobile_ads`. `google_mobile_ads` is working fine with current version `0.12.1`.

hey sir, thanks for the reply
well i tried now the google mobile ads and stil same problem 
as you can see in this picture 
i opened also a new project and stil the same ..
![problem lagya](https://user-images.githubusercontent.com/36598259/114539778-ac0b6a00-9c09-11eb-8e3f-c0b0e73575d0.png)

**Comment by markusaksli-nc** [comment]
If you run into any issues with `google_mobile_ads` please open them at the [package repository](https://github.com/googleads/googleads-mobile-flutter/issues)

Closing this since `firebase_admob` is discontinued.

**Comment by ninehichem** [comment]
okay sir thx
