### ISSUE TITLE
Because firebase_remote_config >=0.6.0 <0.9.0-dev.0 depends on firebase_core ^0.7.0 and testApp depends on firebase_core ^1.0.3, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is forbidden.

### ISSUE THREAD

**Issue by JheiKrauzer0613** [FirebaseExtended/flutterfire#5750]
**[REQUIRED] Step 2: Describe your environment**
Android Studio version: 4.1.3
Firebase Component: Firebase Remote Config
Component version: 0.6.0

**[REQUIRED] Step 3: Describe the problem**
I am trying to use Firebase Remote Config for my current Flutter project but the current latest version of it is not compatible with the other firebase dependencies that I had (which all were also updated to the latest versions). I don't think sacrificing and downgrading my other dependencies just to use the remote config is not a good choice.

**Here are all the Firebase dependencies I currently had and their versions.**
firebase_core: ^1.0.3
firebase_storage: ^8.0.3
cloud_firestore: ^1.0.4
cloud_functions: ^1.0.3
google_mobile_ads: ^0.12.1
firebase_remote_config: ^0.6.0

**Here is the firebase remote config error log I always got when trying to add it to my dependencies.**
Because firebase_remote_config >=0.6.0 <0.9.0-dev.0 depends on firebase_core ^0.7.0 and testApp depends on firebase_core ^1.0.3, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is forbidden.
So, because testApp depends on firebase_remote_config ^0.6.0, version solving failed.

**Steps to reproduce:**

1. Add the latest version of the firebase remote config to the flutter project together with the other firebase dependencies listed above from their respective latest versions in the pubspec.yaml file.

2. Run the command in the console: flutter pub get

3. The error will appear in the console after.

**Comment by markusaksli-nc** [comment]
You need to use the latest `firebase_remote_config: ^0.9.0-dev.2` if you want to use it with the null-safe packages
