### ISSUE TITLE
🐛 [FIREBASE_REMOTE_CONFIG] getString empty

### ISSUE THREAD

**Issue by franvara** [FirebaseExtended/flutterfire#5754]
## Bug report

RemoteConfig don't receive any data. The documentation describes to add the following dependecies, firebase_core: "^0.7.0" and firebase_remote_config: "^0.9.0-dev.2",  but I need firebase_core: "^1.0.3" to use firebase_messaging: "^9.1.1".
If I use 

### Steps to reproduce

    Future<RemoteConfig> versionCheck() async {
        await Firebase.initializeApp();
        final RemoteConfig remoteConfig = await RemoteConfig.instance;
        double minVersion = double.parse(
            remoteConfig.getString('minVersion').trim().replaceAll(".", ""));
.......

remoteConfig.getString('minVersion') is empty ('')

In firebase console, the minVersion has the value of 0.0.1.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.17763.1577], locale es-AR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (3 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  http: ^0.13.1
  dartz: ^0.10.0-nullsafety.1
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  cached_network_image: ^3.0.0
  align_positioned: ^2.0.0
  assets_audio_player: ^3.0.3+2
  firebase_core: ^1.0.3
  firebase_analytics: ^7.1.1
  firebase_remote_config: ^0.9.0-dev.2
  firebase_messaging: ^9.1.1
  flutter_local_notifications: ^5.0.0+1
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  wiredash: ^0.6.2
  hive: ^2.0.2 #NoSQL Database
  path_provider: ^2.0.1
  carousel_slider: ^4.0.0-nullsafety.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @franvara 
Is this after calling `fetchAndActivate`?
Did you set a default for the value in `setDefaults`?
Thank you

**Comment by franvara** [comment]
@markusaksli-nc I don't use fetchAndActivate and setDefaults because a have the default options.
I have the new version of the firebase library and these methods aren't in the version firebase_remote_config: "^0.9.0-dev.2".
I tried to use activateFetched() but in the compilation there is the folowing error (with this and with others methods of RemoteConfig:
   Error: The method 'activateFetched' isn't defined for the class 'RemoteConfig'.
 - 'RemoteConfig' is from 'package:firebase_remote_config/firebase_remote_config.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.9.0-dev.2/lib/firebase_remote_config.dart').

**Comment by franvara** [comment]
@markusaksli-nc Thanks for your comment.
Finally, I put remoteConfig.fetch() and remoteConfig.activate() and the error was solved.

**Comment by markusaksli-nc** [comment]
Actually I mentioned the recently added `fetchAndActivate()` not `activateFetched()` (which was renamed to `activate()`. You can take a look at the new official example for how to efficiently use the new methods.

But glad you solved it.
