### ISSUE TITLE
[📚] Codelab link for Firebase Dynamic Links returns a 404 not found error

### ISSUE THREAD

**Issue by Tetracyl** [FirebaseExtended/flutterfire#5767]
The Codelab for the firebase dynamic links package (https://codelabs.developers.google.com/codelabs/flutter-firebase/#4) returns a 404 Not Found error when visited. 

If the Codelab has been removed then perhaps it should be deleted from the readme.

![image](https://user-images.githubusercontent.com/29833473/114719911-6378ad00-9cec-11eb-86fc-df8dcda4dbcf.png)
![image](https://user-images.githubusercontent.com/29833473/114719933-696e8e00-9cec-11eb-822f-39f8420fff88.png)

**Comment by Salakar** [comment]
I've [removed the link from the](https://github.com/FirebaseExtended/flutterfire/commit/727cafd9c2b24ae0c52225cd362941327cfd6f1c) readme as this codelabe no longer exists.
