### ISSUE TITLE
The plugin home page has a link to configure firebase for each of the platforms, and this link won't open!

### ISSUE THREAD

**Issue by balajahe** [FirebaseExtended/flutterfire#5788]
The plugin home page has a link to configure firebase for each of the platforms, and this link won't open!
https://pub.dev/packages/firebase_ml_vision
https://codelabs.developers.google.com/codelabs/flutter-firebase/#4

**Comment by Salakar** [comment]
I've updated the readme https://github.com/FirebaseExtended/flutterfire/commit/2913cea6657d5c64118bdcdd814ea0cf2523e1c3 to remove this link as these codelabs are no longer available
