### ISSUE TITLE
🐛 [firebase_messaging] Android didn't get any key-value from data map RemoteMessage 

### ISSUE THREAD

**Issue by pengw00** [FirebaseExtended/flutterfire#5789]
## Bug report

**Describe the bug**
Don't want to make any complain, but it is been a while. After upgrade to 2.0, in android didn't get any key-value from data(which is a map ``` this.data = Map<String, dynamic>```) inside RemoteMessage. Before that 1.0 is working.

### Steps to reproduce

1. Go to '.Android'.
2. 'Send message with payload(key value pair)'.
4. See error or incorrect behavior.

### Expected behavior

Expect to get the payload from data attribute of RemoteMessage.

**Comment by markusaksli-nc** [comment]
Hi @pengw00 
What exactly is the payload you are sending?
Thank you

**Comment by pengw00** [comment]
Thanks yours, getting the payload, don't know why, couldn't repro the issue now, so I will close this issue.
