### ISSUE TITLE
🐛 [firebase_messaging] Throw error when using with plugin assets_audio_player

### ISSUE THREAD

**Issue by lqmminh** [FirebaseExtended/flutterfire#5790]
Platform : Android

I use assets_audio_player: ^3.0.3+2 in my project with firebase_messaging: ^9.1.1. That all ok but when open application by click on notification message from firebase this throw:

MissingPluginException(No implementation found for method open on channel assets_audio_player)

**Comment by markusaksli-nc** [comment]
Hi @lqmminh 
Could you please provide your `flutter doctor -v`, `flutter pub deps -- --style=compact` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Are you sure this is being caused by `firebase_messaging`?
Thank you

**Comment by lqmminh** [comment]
<img width="673" alt="Screen Shot 2021-04-17 at 10 12 32" src="https://user-images.githubusercontent.com/46816270/115100216-6e8a4200-9f65-11eb-8243-a0fc145dd58b.png">
Hi. @markusaksli-nc 
Tks for reacted!

**Comment by lqmminh** [comment]
I'm not sure this is being caused by firebase_messaging. But i want research and find a solution for that!

**Comment by markusaksli-nc** [comment]
Could you provide the rest of the information as well? Please refrain from using screenshots, you can just paste the text.

**Comment by lqmminh** [comment]
Tks @mark-veenstra. I'm had remove assets_audio_player package in my project. That work fine.
