### ISSUE TITLE
duplicate registration id on different devices

### ISSUE THREAD

**Issue by Vikas-Jilla** [FirebaseExtended/flutterfire#58]
Hi

We followed all the steps correctly and deployed our app to the app store and play store as well. Now the issue is, when we see in our cloud DB, more than one user has same registration tokens(around 500 users have same registration IDs). 

Please help!

**Comment by kirstywilliams** [comment]
Closing this as appears to be a user issue rather than a bug. Please ask questions of this nature on StackOverflow with the tag `[flutter]` https://stackoverflow.com/questions/tagged/flutter
