### ISSUE TITLE
Offline mode for cloud firestore inserts duplicate documents

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#580]
We have an issue with Flutter connected to Cloud Firestore in offline mode.

Specifically, if you have a ListView builder that displays data from a **Firestore Collection**:

```dart

      StreamBuilder<QuerySnapshot>(
        stream: Firestore.instance.collection('flutter_data').snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData ||
              snapshot.connectionState == ConnectionState.waiting) {
            return CircularProgressIndicator();
          }
          
          return FirestoreListView(documents: snapshot.data.documents);
        },
      )
```

and you have a button that adds data to Firestore :

```dart

  void addTitle(String text) {
 
    Map<String, String> data = {'title': text};
    Firestore.instance.runTransaction((Transaction tx) async {
      var snapshot = await tx.get(Firestore.instance.document('flutter_data'));
      await tx.set(snapshot.reference, data);
    });
  }
```

Then assuming we have no network connection and add say the title -> test12345 , our listview builder will show the string **test12345** approx 5 times - we then turn on the connection, our app will then throw a PlatformException with the error :

```
**errorCode = 9**
**message = Transaction failed all retries**
```

And stack trace

```
> "LocalDownloadTask <3109D0D9-C5AA-456D-8A15-B6DFB23DA3B8>.<1>"
> ), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://app-measurement.com/config/app/1:841219028691:ios:4435fb28c55b69f4?platform=ios&app_instance_id=D2667171446D4FB3BBEDA454B4D5B89E&gmp_version=50200, NSErrorFailingURLKey=https://app-measurement.com/config/app/1:841219028691:ios:4435fb28c55b69f4?platform=ios&app_instance_id=D2667171446D4FB3BBEDA454B4D5B89E&gmp_version=50200, _kCFStream [<decode: missing data>]
> 5.9.0 - [Firebase/Analytics][I-ACS901017] Encounter network error. Code, error: -1003, Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x600001fdc180 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <3109D0D9-C5AA-456D-8A15-B6DFB23DA3B8>.<1>, _NSURLErrorRelatedURLSessionTaskError
```

More importantly, we now have '5' documents in Firestore - it appears that when in offline mode, for each retry that the local client sdk does, it stores the document that many times in Firestore and thus causes duplicates - we were only expecting **ONE** document to be added in Firestore.

**We therefore have two issues**

1. Our stream gets a new event from the client cache for each time it trys to add to cloud firestore
2. Cloud firestore incorrectly batches all the retries for the same document and duplicates the data on cloud firestore 

**For issue 1**
We are yet to find a workaround

**For issue 2** 
Ideally we would like to be able to interrogate something like a **_querysnapshot meta data_** and determine if the event that we receive from the stream is from the local cache , if so - we would check to see if we have already shown the new item in our listview and if so, just ignore the event., However - we cannot find anything that will give us access to this information.

![firestore](https://user-images.githubusercontent.com/18722796/48225805-cd5f3080-e395-11e8-9f20-3de2dda1da94.gif)

![image](https://user-images.githubusercontent.com/18722796/48225762-adc80800-e395-11e8-9198-fc3e14df58c2.png)

**Comment by kroikie** [comment]
@MsXam

The issue at https://github.com/flutter/flutter/issues/24123 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @MsXam
Did the proposed [solution](https://github.com/flutter/flutter/issues/24123#issuecomment-515175494) worked for you?
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by kroikie** [comment]
I think we can close this issue.
