### ISSUE TITLE
🐛 [firebase_messaging][v9.1.1][IOS] onBackground message is not working on IOS

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [FirebaseExtended/flutterfire#5801]
When I use `FirebaseMessaging.onBackgroundMessage` it works pretty fine on Android but looks like it is not doing anything on IOS. I was debugging a lot because I thought that this is something wrong from my side. But then I entered Firebase files and noticed that this callback sets top level function to instance (which is the object of `MethodChannelFirebaseMessaging` class). 

```
  static set onBackgroundMessage(BackgroundMessageHandler? handler) {
    _onBackgroundMessageHandler = handler;

    if (handler != null) {
      instance.registerBackgroundMessageHandler(handler);
    }
  }
```

And if the callback is not null, it calls registerBackgroundMessageHandler which itself checks if the platform is Android and registers this background process.
So when this call executes on an IOS device it runs into first if scope and simply makes a return from the registration function. (see code below).

```
  @override
  Future<void> registerBackgroundMessageHandler(
      BackgroundMessageHandler handler) async {
    if (defaultTargetPlatform != TargetPlatform.android) {
      return;
    }

    if (!_bgHandlerInitialized) {
      _bgHandlerInitialized = true;
      final CallbackHandle bgHandle = PluginUtilities.getCallbackHandle(
          _firebaseMessagingCallbackDispatcher)!;
      final CallbackHandle userHandle =
          PluginUtilities.getCallbackHandle(handler)!;
      await channel.invokeMapMethod('Messaging#startBackgroundIsolate', {
        'pluginCallbackHandle': bgHandle.toRawHandle(),
        'userCallbackHandle': userHandle.toRawHandle(),
      });
    }
  }
```

**Comment by sanekyy** [comment]
Same issue

**Comment by otopba** [comment]
Same issue +1

**Comment by Dohmanlechx** [comment]
Same issue +2

**Comment by Salakar** [comment]
The code above is correct, on our internal implementation there is no background isolate or native handler registration on iOS as iOS will launch your entire app in the background on a background notification, therefore the separate isolate is not required. On our implementation background messages directly go through the normal method channel instead: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart#L88-L93

As for your issue, please make sure you carefully follow the documentation on integrating with Apple;

 - https://firebase.flutter.dev/docs/messaging/overview#installation
 - https://firebase.flutter.dev/docs/messaging/apple-integration
 - https://firebase.flutter.dev/docs/messaging/server-integration

I can confirm it works and 9 times out of 10 it's usually misconfiguration issue. If anyone here thinks they have a genuine issue then can you raise a **new** issue with a lot more detail than 'it doesn't work' please, e.g.;

 - How are you sending the notification?
 - What's your full notification payload including FCM options?
 - Full code showing how you've registered your background handler, not just copy paste the functions, we need to see explicitly where you've called it and where your handler is located, e.g. it should be a top level function.
 - What device are you testing on, os version, make, model.
 - What specifically isn't working, background, foreground, seeing logs but not seeing notifications, etc, details here help.
 - Versions, Flutter, FlutterFire messaging, etc.
 - Related screenshots & log outputs.

**Comment by Dohmanlechx** [comment]
@Salakar I've followed everything already (double-checked just recently).

However, I have an important question: is `case 'Messaging#onBackgroundMessage':` supposed to trigger even if you dismiss the push notification?

**Steps to reproduce:**
1. Kill the app
2. Send a notification
3. Dismiss _(do not click)_ the notification from the phone
4. Start the app

**Expected result:**
The app runs `FirebaseMessaging.onBackgroundMessage()` because it is how it works on Android.

**Actual result:**
Nothing happens.

But it is maybe by design from Apple? That nothing will happen if you dismiss a push notification.

**Comment by bohdan1krokhmaliuk** [comment]
@Salakar followed the documentation and checked every step many times.

I made some more debugging on the [code](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart) that you provided and found that this [part](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart#L90-L93) of code is never executed, while this [part](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart#L73-L87) works fine.

To reproduce simply run the application on IOS device (I used iphone X), with `firebase_messaging: ^9.1.1`. Then put breakpoint on line 90 or 92  [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart#L90-L93), make sure that you choose debugging for packages as well at your IDE. Run the app, put the app in the background and emit push notification. As a result debugger will not catch that callback + if you had any print at you onBackgroundMessage handler - it will not be printed as well.

**Comment by Dohmanlechx** [comment]
@bohdan1krokhmaliuk For me, I can get the push notification even if the app is dead and when I click on it the app starts and triggers the handler method `FirebaseMessaging.onBackgroundMessage()`. So, I can confirm your issue isn't on the package. My main problem is that the push notification is entirely ignored if I **_dismiss_** it.

But I heavily suspect it's by design from Apple because when I have the app running in the background, send the notification and then dismiss it, and finally return to the app, I encounter the same issue - nothing happens.

**Comment by bohdan1krokhmaliuk** [comment]
> @bohdan1krokhmaliuk For me, I can get the push notification even if the app is dead and when I click on it the app starts and triggers the handler method `FirebaseMessaging.onBackgroundMessage()`. So, I can confirm your issue isn't on the package. My main problem is that the push notification is entirely ignored by the handler method if I **_dismiss_** it.

I can get a push notifications as well, even if the app is terminated, but the problem is `FirebaseMessaging.onBackgroundMessage(handler)` handler is never called (which is top-level function as required + all the apple side is set up the same way as in the documentation).
Btw as I do understand this handler must be called without clicking on it, it should be executed when the app is not opened, but just received the message. So there is nothing connected to dismissing the notification - it should be executed as soon as notification received (if the app is in the background or terminated)

@Dohmanlechx  is the handler working for you when your app is terminated? I am sending requests to my local DB to add data just to check if it is working when the app is terminated - and on android, it works fine. On IOS handler is never executed.

**Comment by Dohmanlechx** [comment]
@bohdan1krokhmaliuk Really? In that case, I've the same issue then. Because my logic in `FirebaseMessaging.onBackgroundMessage(handler)` is executed in Android but not in iOS. So the answer on your question is no.
