### ISSUE TITLE
Implemented in latest release

### ISSUE THREAD

**Issue by gauravmehta13** [FirebaseExtended/flutterfire#5804]
Implemented in latest release

_Originally posted by @Ehesp in https://github.com/FirebaseExtended/flutterfire/issues/1942#issuecomment-677526783_

not working for me, there is a constant recaptcha logo, that i an not able to remove

**Comment by gauravmehta13** [comment]
![Uploading Screenshot_20210417-131448.jpg…]()

**Comment by markusaksli-nc** [comment]
Hi @gauravmehta13 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
