### ISSUE TITLE
Network error!! Switching 7.22.1 to 8.4.1 flutter web

### ISSUE THREAD

**Issue by Puspharaj** [FirebaseExtended/flutterfire#5805]
```
<html>
  ...
  <body>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-firestore.js"></script>
  </body>
</html>
```

The above snippet leads to flutter web error saying that network error. might be not resolving?

**Comment by markusaksli-nc** [comment]
Hi @Puspharaj 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by Puspharaj** [comment]
Sorry my bad, it was an configuration issue, forget to close. Thanks
