### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] Startafter  (Pagination) does not work on iOS as expected (Getting duplicate)

### ISSUE THREAD

**Issue by zaidkazi** [FirebaseExtended/flutterfire#5806]
Using the startafter method to paginate my query works fine on Android not on iOS. Im passing a date value to paginate by 

I pass in start after (2021-04-15 20:35:07.618Z) as the field value to start after my pagination limit size is 3 items.

Im returned 3 items where the first is a duplicate again (2021-04-15 20:35:07.618Z)

**Comment by markusaksli-nc** [comment]
Hi @zaidkazi  
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by zaidkazi** [comment]
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.0.1 20B50 darwin-x64, locale en-CA)
    • Flutter version 2.0.1 at /Users/zaid/flutter
    • Framework revision c5a4b4029c (7 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zaid/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Pixel 3 XL (mobile)    • 8BGY0Z62Q                            • android-arm64  • Android 11 (API 30)
    • iPhone Xs Max (mobile) • 7C4E3B1A-41F7-47C0-928F-EFA6B3A7AEFF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.



[pubdeps.txt](https://github.com/FirebaseExtended/flutterfire/files/6346804/pubdeps.txt)

@markusaksli-nc  thanks!

**Comment by zaidkazi** [comment]
pub deps are attached in a text file in above post ^

**Comment by markusaksli-nc** [comment]
Could you provide [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with the exact document structure and code to reproduce the issue?
