### ISSUE TITLE
Flutter - Local module descriptor class for provider installer not found.

### ISSUE THREAD

**Issue by lokeshwar4** [FirebaseExtended/flutterfire#5810]
W/DynamiteModule( 6474): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 6474): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 6474): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
2
W/ConnectivityManager.CallbackHandler( 6474): callback not found for CALLBACK_AVAILABLE message
how to deal with this? i have changed firebase json manytimes but it always pops up

**Comment by markusaksli-nc** [comment]
Hi @lokeshwar4 
I see there's an open issue addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
