### ISSUE TITLE
Plugin Header file not found

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#582]
Recently I developed a plugin [system_setting](https://pub.dartlang.org/packages/system_setting), while it works fine in the example app inside the plugin. It cannot compile when using in other projects. 

The problem is `system_setting/system_setting-Swift.h` not found. This header file seems to be generated. But I can't find any information about it. Most of the plugins on pub are written in obj-c, so can't really get any hints from them. 

Here's the result of `flutter doctor -v`:
```
[✓] Flutter (Channel master, v0.10.3-pre.90, on Mac OS X 10.14 18A391, locale en-HK)
    • Flutter version 0.10.3-pre.90 at /Users/edwardwong/flutter
    • Framework revision db9fe3f827 (4 days ago), 2018-11-04 03:20:44 +0100
    • Engine revision 88cb78cdf6
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/edwardwong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/edwardwong/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4999

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by kroikie** [comment]
@Edward608

The issue at https://github.com/flutter/flutter/issues/24099 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @Edward608
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

https://github.com/flutter/flutter/issues/25676
https://github.com/flutter/flutter/issues/16049

**Comment by kroikie** [comment]
I don't think this is a FlutterFire related issue please continue discussion of it in the original issue which I have reopened.
