### ISSUE TITLE
🐛 [cloud_firestore] Stops iOS build from building.

### ISSUE THREAD

**Issue by HadyMash** [FirebaseExtended/flutterfire#5838]
## Bug report

**Describe the bug**
I have a Flutter project that is working just fine. I have the firebase core, auth, storage, and firestore installed. The project was working fine until yesterday, I think I might have upgraded the flutter sdk. Today it just wouldn't run the app. It would keep making a build that gets stuck in a loop or something that stops it from terminating so when I run another build after stopping it I would keep getting an error saying that the build failed due to concurrent builds and it will retry in 2, 4, 8, 16... seconds. I removed the firebase package and then the app worked. I tried adding it back and the same problem happened again.

### Steps to reproduce

1. Create a flutter project
2. Add it to firebase and add firebase core, auth, storage and cloud firestore packages in the pubspec.yaml file.
3. Run the app
4. You should see the same behvaiour.

### Expected behavior

The app should run normally.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.161, on macOS 11.2.3 20D91 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0-8.0.dev
Flutter SDK 2.2.0-11.0.pre.161
releaf 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_auth 1.1.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_storage 8.0.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- provider 5.0.0 [collection flutter nested]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- pedantic 1.11.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by HadyMash** [comment]
I also tried making a completely new project and and adding the packages to it and I got the same result. The app would run fine with firebase core, auth, and storage dependencies but when I added cloud_firestore the same problem happens and the app wouldn't build.

**Comment by markusaksli-nc** [comment]
Hi @HadyMash 
I'm guessing you just haven't added this?
https://firebase.flutter.dev/docs/overview#improve-ios-build-times

The link explains why this is happening.
Optimistically closing this as solved but let me know if the issue persists.
Thank you

**Comment by HadyMash** [comment]
Yes it worked, thanks a lot!
