### ISSUE TITLE
Add API to support fetching current notification setting

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#584]
Current firebase_messaging package only support get the notification setting after client called `requestNotificationPermissions`. But our project wants to know the setting before the system prompt, so that we do not have to show the permission page if user already grant us the permission.

It looks like below API on iOS:
https://developer.apple.com/documentation/uikit/uiapplication/1623092-currentusernotificationsettings?language=objc

**Comment by kroikie** [comment]
@bood

The issue at https://github.com/flutter/flutter/issues/24047 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @bood
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
