### ISSUE TITLE
flutter_admob is causing my app to crash on iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#585]
flutter_admob after showing a reward video sometimes freezes the app or crashes it. I don't get any logs just says disconnected device. On Android I can watch ad after ad over and over and it works just fine.

This is happening on AdMob versions firebase_admob: ^0.5.7 and above. I have tried the latest.

**Comment by kroikie** [comment]
@mjaffa-figure

The issue at https://github.com/flutter/flutter/issues/23927 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @mjaffa-figure
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
