### ISSUE TITLE
[firebase_messaging][v9.1.2][IOS] onBackgroundMessage is not working on iOS

### ISSUE THREAD

**Issue by Gordon1p7** [FirebaseExtended/flutterfire#5859]
## Bug report

**Describe the bug**
onBackgroundMessage is not working on iPhone SE first gen. iOS 14.4.2.
On Android its working.

### Steps to reproduce

```
Future<void> backgroundMessageHandler(RemoteMessage message) async {
  print('called backgroundMessageHandler');
  await Firebase.initializeApp();
  await SharedPreferencesManager.saveNotificationContents(message.data['nid']);
}

class MainMenu extends StatefulWidget {
  final NotificationManager? notificationManager;

  const MainMenu({Key? key, this.notificationManager}) : super(key: key);

  @override
  State<StatefulWidget> createState() => MainMenuState();
}

class MainMenuState extends State<MainMenu> {

@override
  void initState() {
    WidgetsFlutterBinding.ensureInitialized();
    Firebase.initializeApp().then((value) => print('firebase app initialized'));

    FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);
   super.initState();
 }
}
```

### Expected behavior

If I kill the app and send an fcm message like:

```
{
 "to" : "/topics/XYZ",
 "collapse_key" : "type_a",
 "notification" : {
     "body" : "Body",
     "title": "Title",
     "content-available" : "1"
 },
 "data" : {
     "click_action": "FLUTTER_NOTIFICATION_CLICK",
     "title": "Title",
     "nid": "500",
     "content-available" : "1"
 },
 "content-available" : "1"
}
```

I should get an output from:

`idevicesyslog -u b1700552fc852e0ada69ee1ba1f7992920affe07 | grep backgroundMessageHandler`

But on iOS 'called backgroundMessageHandler' gets never printed.

On Android i get logs:

![Bildschirmfoto 2021-04-21 um 10 08 10](https://user-images.githubusercontent.com/47775807/115521291-4ebb8c80-a28b-11eb-87de-f103603a75c4.png)

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  firebase_core: ^1.0.4
  firebase_analytics: ^8.0.1
  firebase_crashlytics: ^2.0.1
  firebase_messaging: ^9.1.2
```

</details>

---

**Comment by Salakar** [comment]
> If I kill the app

See [the docs on this](https://firebase.flutter.dev/docs/messaging/usage);

>  - On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.
>  - On Android, if the user force quits the app from device settings, it must be manually reopened again for messages to start working.

**Comment by Gordon1p7** [comment]
Hey @Salakar ,

thank you for the quick response!

Just to be clear here, in firebase_messaging 7 it was possible, if remember it right?
On Android its still working.

Best regards
