### ISSUE TITLE
🐛 [firebase_remote_config] Support for latest flutterfire dependencies with remote config

### ISSUE THREAD

**Issue by bssughosh** [FirebaseExtended/flutterfire#5886]
## Bug report

**Describe the bug**
Whenever the latest version of firebase remote config is added to the dependency, the dependency fails as it depends on an older version of firebase core, and that inturn on various flutter fire components used in the application.

I tried using the dev branch version of remote config, `0.9.0-dev.0`, but that is causing bugs in iOS. In iOS, there are some instances where the remote config code is executed but the values fetched are wrong and most of the time, the remote config code throws an error.

The error we got while we are fetching the values from remote config using a correct key.
```
_TypeError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>')
```

### Steps to reproduce

1. Add the following dependencies:
```
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  firebase_storage: ^8.0.0
```
2. Try adding the latest firebase remote config
```
firebase_remote_config: ^0.6.0
```
3. The pub get fails

### Expected behavior

The firebase remote config should not give dependency issues.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.4 at /Users/sughosh/development/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sughosh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Because firebase_remote_config >=0.6.0 <0.9.0-dev.0 depends on firebase_core ^0.7.0 and institution depends on firebase_core ^1.0.1, firebase_remote_config >=0.6.0 <0.9.0-dev.0 is forbidden.
So, because institution depends on firebase_remote_config ^0.6.0, version solving failed.
```

</details>

---

**Comment by Salakar** [comment]
Please upgrade to the versions indicated here; https://firebase.flutter.dev/docs/remote-config/overview

**Comment by bssughosh** [comment]
@Salakar 
I am using the latest firebase core: 1.0.4 but remote config depends on 0.7.0

So I am not able to use the version you told

**Comment by Salakar** [comment]
Apologies the docs are incorrect, Remote Config is compatible with the latest Firebase Core version, I've just pushed an update to the docs now which is deploying

**Comment by Salakar** [comment]
You can see a table of all the latest versions here; https://firebase.flutter.dev/docs/null-safety

**Comment by Salakar** [comment]
Ok the updated documentation is live; 

![image](https://user-images.githubusercontent.com/5347038/116218896-e7965000-a742-11eb-8398-47648f35718f.png)

**Comment by bssughosh** [comment]
> Ok the updated documentation is live;
> 
> ![image](https://user-images.githubusercontent.com/5347038/116218896-e7965000-a742-11eb-8398-47648f35718f.png)

Cool will check this out then

**Comment by bssughosh** [comment]
@Salakar After updating the libraries I got such an error for iOS

```
FirebaseException ([firebase_remote_config/internal] internal remote config fetch error

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:145:29)
<asynchronous suspension>
#3      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
<asynchronous suspension>
```
