### ISSUE TITLE
🐛 [firebase_performance] Performance is not fully implemented

### ISSUE THREAD

**Issue by danallen88** [FirebaseExtended/flutterfire#5888]
## Bug report

**Describe the bug**
I was asked to explicitly file a bug report from a member of the Firebase team (a Google Cloud Customer Engineer), so apologies if this is not the correct venue.  If anything, this feels more like a request for prioritizing this plugin on the roadmap, but I want to start the conversation.

As noted in  #4397, it is unclear what this plugin provides.  From reading the documentation and the source code, it appears that minimally the plugin supports the ability to manually wrap an HTTP client to extract information from network requests to send to Firebase, and to capture traces throughout the application (even at the UI layer).  While this minimum feature-set allows you to measure what you want, it does not provide guidance on what is possible to get or how to get it.

While that could be solved through documentation, the bigger issue is that the native plugin for Firebase Performance captures the network data automatically without the need for manual instrumentation from the consumer.  Additionally, it collects data on page load times in the native implementation without any instrumenting.  I understand that while Flutter is different, and perhaps it is impossible to do this in the same way that native implementations do, if the goal is to provide the same level of detail with no manual instrumentation, then this is not working as designed.

To quote the customer engineer: 
> Can you file a bug on this with your expectations. According to development the goal is to just have metrics work without any additional set up. 

Based on this, I don't think my assumptions above are misguided, but would love the team's thoughts on how we can get the most out of the Flutter plugin.  Thanks for your time and attention!

Dan

**Comment by russellwheatley** [comment]
Hi Daniel, to understand how the Firebase performance product works, it is worth exploring the [performance monitoring official documentation](https://firebase.google.com/docs/perf-mon). To be clear, the `firebase_performance` plugin is just a wrapper around the official Firebase native SDKs.

If you think your application can benefit from using it, we have now updated the `firebase_performance` [plugin documentation](https://firebase.flutter.dev/docs/performance/usage) recently on how to integrate it into your application. Hope this helps!

**Comment by danallen88** [comment]
@russellwheatley Thank you for taking a look.  I feel as though this issue was closed in error so perhaps I can provide some more context on why it was opened.

I have used this plugin for a native iOS app and it provides [screen rendering performance data](https://firebase.google.com/docs/perf-mon/screen-traces?platform=ios) which shows how long each native view takes to render (split out by view controllers).  With Flutter, this appears to no longer be possible with Flutter views, since all screens in a Flutter app become aggregated under a view controller called FlutterViewController.  There is no way to determine screen rendering time from one screen to the next.

Now, to be fair, the Flutter documentation you've linked does not mention this capability.  However, the information I've received to this point is that, being a wrapper around the native SDKs, it should just work the same.  This is a specific situation in which it definitively does not, and there's no clear way to provide parity on this feature.  I understand this is likely because everything that Flutter does for UI rendering happens in this ubiquitous FlutterViewController which is the level of abstraction that the Firebase native SDK stops collecting data at.  If it were possible to somehow distinguish between screens in this view controller so that we can analyze screen rendering times in a Flutter app by providing the SDK additional metadata (a custom name for example instead of the default *ViewController naming), then this feels like it would meet the use case.

**Comment by russellwheatley** [comment]
Hey @danallen88, I'm not sure this feature is going to be possible. Like you said, and as far as I'm aware, the underlying native SDK will not know when a Flutter view changes internally as it is only aware of the `FlutterViewController`. I don't think there is any way to square that circle. Would love to be proven wrong, so if you do find a way, please update here and we can look to make any changes that make it possible. Thanks.
