### ISSUE TITLE
I HAVE THIS FIREBASE FIRESTORE PROBLEM AND I DONT FIND A SOLUTION. THANKS

### ISSUE THREAD

**Issue by Zakaryababa** [FirebaseExtended/flutterfire#5889]
EDIT : I JUST REALIZED THAT IT HAPPENS EVEN WITH A SIMPLE SCREEN WITH AN APPBAR

[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.
[Fatal Error] firebase-firestore-22.1.2.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not resolve com.google.firebase:firebase-firestore:22.1.2.
Required by:
project :app > com.google.firebase:firebase-bom:27.0.0
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
Could not resolve com.google.firebase:firebase-firestore:22.1.2.
Required by:
project :app > project :cloud_firestore
> Could not resolve com.google.firebase:firebase-firestore:22.1.2.
> Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-firestore/22.1.2/firebase-firestore-22.1.2.pom
> Content is not allowed in prolog.
Content is not allowed in prolog.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by markusaksli-nc** [comment]
Hi @Zakaryababa 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
