### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] FirebaseMessaging.onMessageOpenedApp does not work

### ISSUE THREAD

**Issue by alexlovar** [FirebaseExtended/flutterfire#5892]
## Bug report

**Describe the bug**

i'm testing the official flutterfire  example for firebase_messaging, https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example the FCM notifications works in fore and background, i'm using the latest plugins:

firebase_messaging: ^9.1.2 
is supposed that the message screen must be show when the notification is tapped, but nothing happens, I don't even have the debug messages.

### Steps to reproduce
run the example from github, when you tap on notification, the event FirebaseMessaging.onMessageOpenedApp is not triggered

1. run the example
2. click on arrived notification
3. expect to open messages screen
4. nothings happens

### Expected behavior

the app must show the message screen

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [VersiÃ³n 10.0.19042.928], locale es-419)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (4 available)

• No issues found!
```
</details>

---

**Comment by markusaksli-nc** [comment]
Hi @alexlovar 
If you run the official example on android the notification will be presented in the foreground using `flutter_local_notifications`.
This is why the firebase messaging stream will not be fired when tapping the notification. 
Foreground notifications are just a limitation on android so you will need to take a look at how the `flutter_local_notifications` official example does things if you want to use tapping on the notification for interaction.
Thank you

**Comment by alexlovar** [comment]
so strange because the `flutter_local_notifications` plugin is include in the sample, but the example does not work correctly

**Comment by alexlovar** [comment]
hi @markusaksli-nc,  i'm  really lost trying to find how to solve this, the official example include the `flutter_local_notifications.` but when you tap the notification nothings happens:
i'm my onw app using FCM , with firebase messaging version ^9.1.3, i need to manage notification click event, but onforeground tap message does not work. on arrived msg a i get this in the console:
 `"Accessing hidden method Landroid/os/WorkSource;->add(I)Z (greylist,test-api, reflection, allowed)" ,`
  and FirebaseMessaging.onMessage.listen is not triggered, my onmessage function only have a print(¨msg¨)
  thanks

**Comment by shubhamssinghal** [comment]
Hi, On foreground onMessageOpenedApp didnt work anyone got solution for this?

**Comment by alexlovar** [comment]
yeah is a firebase bug, look this link: https://github.com/FirebaseExtended/flutterfire/issues/6011 
just put the  FirebaseMessaging.onMessage.listen((RemoteMessage message) just after gettoken:
