### ISSUE TITLE
Not able to detect Face in ios 14

### ISSUE THREAD

**Issue by ronitP12** [FirebaseExtended/flutterfire#5895]
i taken the pull and run the example and select the picture preview for and inside that i select face detect that is not able to detect face on my selected picture.

**Comment by nghialh73** [comment]
same problem

**Comment by markusaksli-nc** [comment]
Hi @ronitP12 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by ronitP12** [comment]
> Hi @ronitP12
> When opening an issue, please try to provide all of the information indicated in the template.
> Closing this issue, since no information has been provided.
> Thank you.

_faceDetector.processImage(visionImage)

this method is not returning any response or output.
