### ISSUE TITLE
🐛 [ML_VISION] Faces cannot be detected on IOS 14

### ISSUE THREAD

**Issue by nghialh73** [FirebaseExtended/flutterfire#5899]
## Bug report

**Describe the bug**
I upgrade package ml_vison to 0.12.0, my project has failed to detect faces on IOS 14. After that, I tried run example ml_vison and it also doesn't work.

### Steps to reproduce

1. Clone project flutterfire and open example FirebaseMLVision
2. Run example and select "Detect Face" in menu 
3. Faces are not detect
### Expected behavior

Expect faces detect

---

## Additional context

latest version

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  camera: ^0.8.1
  cupertino_icons: ^1.0.2
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_ml_vision:
    path: ../
  flutter:
    sdk: flutter
  image_picker: ^0.7.3

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../firebase_core/firebase_core_web```

</details>

---

**Comment by BhavyKoshti9spl** [comment]
same here! any solutions to this one ?

**Comment by markusaksli-nc** [comment]
This is because the official example `Podfile` doesn't contain any of the iOS pods for ML vision. The same issue was probably present for your project since you need to add both the dart package and the native ML vision components you want to use.

This is also mentioned in the documentation https://pub.dev/packages/firebase_ml_vision#ios

However adding these will be blocked on iOS by https://github.com/FirebaseExtended/flutterfire/issues/4625
