### ISSUE TITLE
[📚][firebase_messaging] Terrible iOS setup documentation

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [FirebaseExtended/flutterfire#5904]
The documentation does not clearly state to add this property into `Info.plist` when making setup for iOS messaging:

```
<key>FirebaseAppDelegateProxyEnabled</key>
	<string>0</string>
```

I have wasted a lot of time due to incomplete, unprofessional documentation on: https://firebase.flutter.dev/docs/messaging/apple-integration

This concerned iOS 14+, in particular.

Only with help of SO, YT and issue threads I was able to solve it. Not cool.

**Comment by rrousselGit** [comment]
Firebase is open-source.

Feel free to raise a PR if something is missing

**Comment by mikehardy** [comment]
I was curious so I consulted the example which is also open source and runs all the time in CI.
Appears to not be needed. That's probably why it is not in any document.
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/ios/Runner/Info.plist
