### ISSUE TITLE
[firebase_admob] please support nullsafety because new plugin has too many issues

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#5905]
https://github.com/googleads/googleads-mobile-flutter/issues
too many issues

CANT upgrade to flutter 2

**Comment by markusaksli-nc** [comment]
Hi @peterweb2005 
Please open a new issue on the mentioned repository if you are having problems with it.
`firebase_admob` has been deprecated.
Thank you
