### ISSUE TITLE
[📚][firebase_messaging] Provide feedback that iOS devices receive notifications only when in background.

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [FirebaseExtended/flutterfire#5906]
I am able to send notifications with my Firebase Console to my iOS 6 14+ OS.
I have followed these steps [https://firebase.flutter.dev/docs/messaging/apple-integration](https://firebase.flutter.dev/docs/messaging/apple-integration).

However, what is missing on this page is that notifications can be only received in the iOS when the app is killed. It does not work when the app is running (in foreground or in recents).

It will be good to clarify it since for a person coming from Android development this is not straightforward.

**Comment by markusaksli-nc** [comment]
Hi @MichalDanielDobrzanski 
This is not the expected behavior so can you open a new issue for this and fill out the template?
Thank you
