### ISSUE TITLE
🐛 [firebase_analytics] // Not opting by default null safety

### ISSUE THREAD

**Issue by NetFreaker** [FirebaseExtended/flutterfire#5907]
## Bug report

**Describe the bug**
//firebase_analytics_platform_interface-1.1.0/lib/firebase_analytics_platform_interface.dart:5:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^

**Comment by markusaksli-nc** [comment]
Hi @NetFreaker 
Please use the latest version of the package.
Thank you
