### ISSUE TITLE
FireBase Messagin Web error on Flutter Web Starting

### ISSUE THREAD

**Issue by astrO1** [FirebaseExtended/flutterfire#5910]
I'm trying to test my Flutter project that is working fine for Android and IOS, but when I'm trying to run on the web I get this error:

```
Cannot read property 'messaging' of undefined
    at new firebase_messaging_web.FirebaseMessagingWeb.new (http://localhost:63264/packages/firebase_messaging_web/firebase_messaging_web.dart.lib.js:171:41)
```

**Comment by markusaksli-nc** [comment]
Hi @astrO1 
Please add the corresponding JS SDK to any firebase package you want to use on web.
https://github.com/FirebaseExtended/flutterfire/issues/5910
Thank you
