### ISSUE TITLE
[firebase_auth] diconnect() causing error

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#592]
I am using google sign in with Firebase. First time I am able to log in and get user credentials as well but while pressing sign out button I am signing out in below lines and this works fine.
```dart
    await _auth.signOut();
    await _googleSignIn.signOut();
```

but when adding      `await _googleSignIn.disconnect();`
some times the user gets signed out properly then while logging in again the app freezes or sometimes the app freezes before signing the user out.

Below are the logs.
```
E/flutter (16617): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (16617): PlatformException(status, Failed to disconnect., null)
E/flutter (16617): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (16617): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (16617): <asynchronous suspension>
E/flutter (16617): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:217:58)
E/flutter (16617): <asynchronous suspension>
E/flutter (16617): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:269:28)
E/flutter (16617): #4      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (16617): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (16617): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (16617): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (16617): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
E/flutter (16617): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (16617): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by kroikie** [comment]
@ayush-12

The issue at https://github.com/flutter/flutter/issues/23625 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by DaniyarGilimov** [comment]
Any solutions? having the same issue here

**Comment by lpreimesberger** [comment]
I hit this too - disconnect() call will throw an exception if the session is already dropped/invalid and it gets SIGN_IN_REQUIRED back from revokeAccess().   I think the 'sometimes' comes into play just depending on how fast stuff happens.  Prolly disconnect() should return null in that case instead - but for me I just wrapped in a catch for PlatformException and carried on.

**Comment by Salakar** [comment]
Give that this error is originating inside the Google sign-in package, I'd recommend raising the issue on that plugins repo if this is still an issue, thanks.
