### ISSUE TITLE
🐛 [FIREBASE dynamic links] has add sha256, but it still warning Android app ''xxx.xx.xx.' lacks SHA256. AppLinks is not enabled for the app

### ISSUE THREAD

**Issue by wangxingxing123654** [FirebaseExtended/flutterfire#5923]
i have add sha256 at firebase admin , but it still warning  Android app 'xxx.xx.xx' lacks SHA256. AppLinks is not enabled for the app，so    FirebaseDynamicLinks.instance..onLink(success(){})  cannot be invoked

**Comment by markusaksli-nc** [comment]
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/5921
