### ISSUE TITLE
Firebase Messaging v9.1.2 not removing badge/notifications after app start at iOS 

### ISSUE THREAD

**Issue by jjoschyy** [FirebaseExtended/flutterfire#5925]
**1. Summary of my problem**
In an older version of firebase_messaging (v7.0.3) the badge and the notifications are automatically cleared on app start/resume. In v9.1.2 the badge and the notifications never change on app start/resume. Goal is to find a way to implement the "old" logic.
I used flutter Flutter 2.2.0-10.1.pre.

**2. What have I tried so far -** 
I updated the AppDelegate.swift with the following code. This works, but only on "startup" of the application. If i resume the app from background, it is ignored.

```
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {

    if #available(iOS 10.0, *) {
       application.applicationIconBadgeNumber = 0 
       let center = UNUserNotificationCenter.current()
       center.removeAllDeliveredNotifications()
       center.removeAllPendingNotificationRequests()
    }

    GeneratedPluginRegistrant.register(with: self)  
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  } 
}
```

Is there a way to update the AppDelegate to execute the code on "app resume", too?". Is there an other way, to configure firebase_messaging to work the old way?

Thanks a lot!

**Comment by ThinkSimple** [comment]
Im having the same kind of problem

**Comment by markusaksli-nc** [comment]
Hi @jjoschyy 
Please see https://github.com/FirebaseExtended/flutterfire/issues/4145#issuecomment-739571979
Thank you
