### ISSUE TITLE
🐛 [firebase_database] It is not null safe yet.

### ISSUE THREAD

**Issue by uc-dve** [FirebaseExtended/flutterfire#5931]
## Bug report

**Describe the bug**
Can you please update the plugin with null-safety. I am getting the below error.

![image](https://user-images.githubusercontent.com/28289763/116036809-d8e96380-a684-11eb-8143-dfa56398e882.png)

**Comment by markusaksli-nc** [comment]
Hi @uc-dve 
`firebase_database 7.0.0-dev.1` contains

> BREAKING REFACTOR: Migrate to sound null-safety (#5441).

Thank you
