### ISSUE TITLE
[📚] Add regions specific calls for emulators 

### ISSUE THREAD

**Issue by Valentin-Seehausen** [FirebaseExtended/flutterfire#5942]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

Hello from Berlin/Europe/Another Region that us-west1 :-)

I needed two hours to find out, that the call for the emulator should (of course) go to the instance create for the region, like this:

    FirebaseFunctions.instanceFor(region: 'europe-west1')
              .useFunctionsEmulator(origin: functionHost);

I think this would be very nice to have in the documentation.

Maybe even the fact, that a specified region needs to be reflected in the call in Flutter. 

            FirebaseFunctions.instanceFor(region: 'europe-west1')
            .httpsCallable(functionName);

What do you think?

**Comment by Salakar** [comment]
Hey 👋   https://firebase.flutter.dev/docs/functions/usage#specifying-regions - was this not visible when you visited the docs? Was there anything there that you think wasn't covered enough? Thanks!

**Comment by Valentin-Seehausen** [comment]
Hey, yes:

The emulator example is this:

    FirebaseFunctions.instance
      .useFunctionsEmulator(origin: 'http://localhost:5001');

And I think the emulator for a specified region should also be added:

    FirebaseFunctions.instanceFor(region: 'europe-west1')
          .useFunctionsEmulator(origin: 'http://localhost:5001');

It was not obvious to me, that you would need to specify the emulator for the regions. I think it would add clarity to add this example.
