### ISSUE TITLE
🐛 [firebase_auth] Cant catch the error when verification code sms is invalid.

### ISSUE THREAD

**Issue by a8888951** [FirebaseExtended/flutterfire#5948]
## Bug report

**Describe the bug**
Cant catch the error.

### Steps to reproduce

dependencies:
  flutter:
    firebase_core: ^1.1.0
    firebase_auth: ^1.1.2

try {
PhoneAuthCredential credential = PhoneAuthProvider.credential(verificationId: _verficationID, smsCode: pin);
await _FirebaseAuth.instance
         .signInWithCredential(credential)
         .then((value) async { print(value) });
          } catch (e) {
            print('failed');
          }

### Expected behavior

If I input correct SMS verify code, It can success print the user object.
If I input the wrong verify code, error was pop up and the app was crash.
The main problem is I can not catch the error when I use try{}catch(e){}

the error message below (shown on vs code):
PlatformException (PlatformException(firebase_auth, com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user., {code: invalid-verification-code, additionalData: {}, message: The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user.}, null))

![auth](https://user-images.githubusercontent.com/6872436/116241332-5e5d3880-a797-11eb-9fe0-edd1ba8bcd7b.jpg)

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)
    ! Device emulator-5566 is offline.

• No issues found!

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

Dart SDK 2.12.3
Flutter SDK 2.0.5
killjc_app 1.0.0+1

dependencies:
- animations 2.0.0 [flutter]
- apple_sign_in_safety 0.0.6 [flutter]
- cupertino_icons 1.0.2
- dio 4.0.0 [http_parser path]
- dio_cookie_manager 2.0.0 [cookie_jar dio]
- firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_easyloading 3.0.0 [flutter flutter_spinkit]
- flutter_facebook_auth 3.3.3+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_local_notifications 5.0.0+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_native_splash 1.1.8+4 [image meta path xml yaml universal_io]
- flutter_screenutil 5.0.0 [flutter]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- get 4.1.4 [flutter]
- get_storage 2.0.2 [flutter get path_provider]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- pinput 1.2.0 [flutter]
- settings_ui 1.0.0 [flutter]
- timer_builder 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- web_socket_channel 2.0.0 [async crypto stream_channel]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]  

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- cookie_jar 3.0.1
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_facebook_auth_platform_interface 2.4.2 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.4.2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_spinkit 5.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.0.0 [flutter]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @a8888951 
Debugging in VSCode will catch the error before the dart try/catch block has a chance.
Try to just run it in terminal using `flutter run`.
Thank you

**Comment by a8888951** [comment]
> flutter run

OK, thank a lot. I have try using flutter run, the error never show again.
So, It not a bug.
