### ISSUE TITLE
[📚] Firestore API reference is not published on pub.dev

### ISSUE THREAD

**Issue by puf** [FirebaseExtended/flutterfire#5949]
The latest Firestore API documentation is no longer published on https://pub.dev/documentation/cloud_firestore/latest/

Since that is even linked from https://firebase.flutter.dev/docs/firestore/overview/, I assume it's an oversight in publishing and not an intentional change of the link.

**Comment by markusaksli-nc** [comment]
This actually applies for all of the api reference links

**Comment by Salakar** [comment]
https://pub.dev/documentation/cloud_firestore/latest/log.txt looks like there was a docs error on pub.dev when publishing

**Comment by puf** [comment]
Hey folks, 

The missing documentation is quite disruptive for my ability to help people with Firestore questions.

Any update on when this will be fixed, or a location where we can find the docs in the meantime?

**Comment by markusaksli-nc** [comment]
Seems like it's fixed?

**Comment by puf** [comment]
The issue still existed when I posted my previous comment.
It is indeed fixed now.  Thanks!
