### ISSUE TITLE
🐛 [FIREBASE_AUTH] unsupported_event exception in JS Script

### ISSUE THREAD

**Issue by AldrinMathew** [FirebaseExtended/flutterfire#5954]
## Bug report

When the flutter app is launched, the script in the index.html for flutter web, throws an error regarding **unsupported_event** in the **generated_plugin_registrant.dart** file at line that says `FirebaseFirestoreWeb.registerWith(registrar);`.

### Steps to reproduce

1. Create a flutter app.
2. Add dependency firebase_auth: ^1.1.2
3. Add <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-auth.js"></script> to index.html
4. Run the App
5. See the following exception:
   ```
   Exception has occurred.
   "Error: unsupported_event at https://www.gstatic.com/firebasejs/8.4.1/firebase-auth.js:1:104874"
   ```

### Expected behavior

The App running as usual. Instead it just throws an exception and pauses.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.2.0-11.0.pre.189, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0-18.0.dev
Flutter SDK 2.2.0-11.0.pre.189
myapp 1.0.0+1

dependencies:
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.2
- firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.0.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- get 4.1.4 [flutter]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- http 0.13.1 [http_parser meta path pedantic]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
```

</details>

---

**Comment by AldrinMathew** [comment]
Related to #5662

**Comment by markusaksli-nc** [comment]
Hi @AldrinMathew 
The issue description here is confusing. You say that the issue is related to firebase auth but you have `FirebaseFirestoreWeb` in the generated plugin registrant? Could you also provide the full stack trace for the error you are seeing?
Not seeing this issue with the steps you described.
Thank you

**Comment by AldrinMathew** [comment]
@markusaksli-nc

It is confusing to me too. The exception message corresponds to the firebase_auth JS script file. But the line that the exception is displayed corresponds to the **generated_plugin_registrant.dart** and it says **FirebaseFirestoreWeb.registerWith(registrar);**

```
getFirestoreInstance (/home/aldrinmathew/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.7/lib/src/interop/firestore.dart:23)
new (/home/aldrinmathew/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.7/lib/cloud_firestore_web.dart:35)
registerWith (/home/aldrinmathew/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.7/lib/cloud_firestore_web.dart:28)
registerPlugins (/media/dev/projects/AAF/blenderverse/lib/generated_plugin_registrant.dart:17)
main (org-dartlang-app:/web_entrypoint.dart:14)
main$ (org-dartlang-app:/web_entrypoint.dart:13)
<asynchronous gap> (Unknown Source:0)
```

**Comment by AldrinMathew** [comment]
@markusaksli-nc

It is confusing to me too. The exception message corresponds to the firebase_auth JS script file. But the line that the exception is displayed corresponds to the **generated_plugin_registrant.dart** and it says **FirebaseFirestoreWeb.registerWith(registrar);**

The stacktrace:

```
getFirestoreInstance (/home/aldrinmathew/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.7/lib/src/interop/firestore.dart:23)
new (/home/aldrinmathew/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.7/lib/cloud_firestore_web.dart:35)
registerWith (/home/aldrinmathew/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.7/lib/cloud_firestore_web.dart:28)
registerPlugins (/media/dev/projects/AAF/myapp/lib/generated_plugin_registrant.dart:17)
main (org-dartlang-app:/web_entrypoint.dart:14)
main$ (org-dartlang-app:/web_entrypoint.dart:13)
<asynchronous gap> (Unknown Source:0)
```

**Comment by markusaksli-nc** [comment]
So you also have cloud firestore in the project? Have you added the cloud firestore import script?

**Comment by AldrinMathew** [comment]
@markusaksli-nc 

Yes

```
<script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-storage.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-auth.js"></script>
```

**Comment by markusaksli-nc** [comment]
Strange. Well the steps you provided don't really reproduce the issue. Could you try to nail it down to some minimal sample that still causes the error for you (such as just adding the dependencies to a new project)?

**Comment by AldrinMathew** [comment]
@markusaksli-nc 

I am not able to reproduce the issue in a newly created app. But I have the following Debug Output with errors in both the original app and the new sample app.

```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:....../......
Debug service listening on ws://127.0.0.1:....../......
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:....../......
Error handling 'checkPlatformOverride' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'checkBrightnessOverride' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'checkIsWidgetCreationTracked' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'serviceExtension' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
```

**Comment by AldrinMathew** [comment]
@markusaksli-nc 

Good news. I just deleted the entire project folder except the **lib** and **assets** folders & **pubspec.yaml** file.
I ran `flutter create myapp` and then restored the files accordingly. Now it runs perfectly for some reason.

I am still getting the following error on all my web apps.

```
Error handling 'checkPlatformOverride' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'checkBrightnessOverride' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'checkIsWidgetCreationTracked' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'serviceExtension' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
```

**Comment by AldrinMathew** [comment]
I believe this issue can be closed. But since the cause for the error is unknown, you may or may not want to keep the issue open. I am closing this anyway as the issue has been resolved on my end.

Thanks @markusaksli-nc for the quick response and help.

**Comment by webstoreportal** [comment]
I randomly started seeing this as well when auto breakpointing on exceptions

```
Exception has occurred.
"Error: unsupported_event
    at https://www.gstatic.com/firebasejs/8.4.1/firebase-auth.js:1:104874"
```

**Comment by AldrinMathew** [comment]
@webstoreportal @markusaksli-nc

I have the same issue again. When I uncheck those, then there are no exceptions shown, but then the login screen on my app is on an infinite loading because the document snapshot of my firebase database is not having results.

**Comment by markusaksli-nc** [comment]
Uncheck what exactly? Again, can you provide some concrete steps and/or a code sample?

**Comment by AldrinMathew** [comment]
The exception is shown when Firebase is initialized through the Generated Plugin Registrant. When I created a new project to solve the issue, the following options were automatically unchecked by VSCode. There were no exceptions shown when the following options are unchecked.

- [ ] **All Exceptions**
- [ ] **Uncaught Exceptions**

I thought it was solved. But then when I proceed with Database integration in my Web App, when I request a document snapshot, it is not returning any result. I have setup a loading screen while the data loads. It is loading infinitely, as the data is never loaded.

## Steps to Reproduce

The steps to reproduce seems to be simple.
1. Create a flutter app with **Web Support**. `flutter create myapp`
2. Add firebase dependencies to pubspec.yaml
3. Do `flutter pub get`
4. Add necessary initialization and JS scripts of the firebase services to index.html
5. Add Code to initialize Firebase services and then to get the necessary Document Snapshots
6. Run the app in Chrome: `flutter run -d chrome`

**Comment by markusaksli-nc** [comment]
What would really help here is a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

When just running the firestore official example on web and "get the necessary Document Snapshots" I'm not seeing any of these issues.

**Comment by halvorsen** [comment]
happens to me too in my web canvaskit builds on my project here: https://github.com/halvorsen/1Stack

[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)

**Comment by AldrinMathew** [comment]
@halvorsen
It always shows the exception when the All Exceptions breakpoint is set

**Comment by markusaksli-nc** [comment]
This is likely an issue with the VSCode debugger. It has been known to catch exceptions before they have a chance to be caught and properly handled in Dart.

**Comment by halvorsen** [comment]
That makes sense, it comes down to being a bit of an inconvenience since it happens immediately on app launches and makes it troublesome to run an 'all exceptions' breakpoint. Thanks for the responses. I am, in fact, running VSC.
