### ISSUE TITLE
🐛 [firebase_remote_config] Android error: FormatException: Invalid envelope

### ISSUE THREAD

**Issue by Sthefanny** [FirebaseExtended/flutterfire#5958]
## Bug report

After change firebase_remote_config from version 0.4.2 to 0.10.0-dev.0, iOS version is working fine, but on Android I'm getting FormatException: Invalid envelope

### Steps to reproduce

```
late RemoteConfig _remoteConfig;

RemoteConfigService._init() {
  _init();
}

void _init() async {
    _remoteConfig = RemoteConfig.instance;
    final defaults = <String, dynamic>{
      'test': '',
    };
    await _remoteConfig.setConfigSettings(RemoteConfigSettings(fetchTimeout: Duration(seconds: 10), minimumFetchInterval: Duration.zero));
    await _remoteConfig.setDefaults(defaults);
    await _refresh();
    Timer(Duration(hours: 12, minutes: 1), () => _refresh());
  }

Future<void> _refresh() async {
    try {
      await _remoteConfig.ensureInitialized();
      await _remoteConfig.fetchAndActivate();
      print('welcome message: ' + _remoteConfig.getString('test'));
    } on PlatformException catch (exception) {
      // Fetch exception.
      print(exception);
    } catch (exception) {
      print('Unable to fetch remote config. Cached or default values will be used');
      print(exception);
    }
}
```
Executing this on Android will go to the catch (exception) with the specified error.

### Expected behavior

Should return variable value added in the remoteConfig

---

## Additional context

Works fine on iOS

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.2 20D80 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @Sthefanny 
Not seeing this issue with 
```yaml
  firebase_core: ^1.1.0
  firebase_remote_config: ^0.10.0-dev.2
```
Could you check if the issue persists with the latest version? Could you provide the full exception stack trace?
Thank you

**Comment by Sthefanny** [comment]
> Hi @Sthefanny
> Not seeing this issue with
> 
> ```yaml
>   firebase_core: ^1.1.0
>   firebase_remote_config: ^0.10.0-dev.2
> ```
> 
> Could you check if the issue persists with the latest version? Could you provide the full exception stack trace?
> Thank you

I just updated the versions and still the same problem.

StackTrace
<details><summary>Click To Expand</summary>

```
stackTrace
#0      convertPlatformException (package:firebase_remote_config_platform_interface/src/method_channel/utils/exception.dart:9:5)
#1      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:155:13)
<asynchronous suspension>
#2      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
<asynchronous suspension>
#3      RemoteConfigService._refresh (package:cingulo/services/remote_config_service.dart:87:7)
<asynchronous suspension>
#4      RemoteConfigService._init (package:cingulo/services/remote_config_service.dart:80:5)
<asynchronous suspension>
```

</details>

**Comment by markusaksli-nc** [comment]
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Sthefanny** [comment]
> Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Sorry for the delay... I was trying to do as you asked, but when I created an app from scratch it worked, and it took me a long time to try to discover how to reproduce the problem...

So, I can't provide a sample because I could see it has something to do with the google-services.json. I need to say I didn't do this app from the beginning and the person who did is no longer working on it.. and also that I don't understand very much of google-services.json options...

As I said I created an app from scratch just to test remote-config and it worked, so I changed the contents from google-services from my app to this new one and it stopped working.

For obvious reasons, I won't post it here, but I noticed some differences in the app that is not working:
 - "oauth_client" -> has 2 items, both with certificate_hash information
 - "services" -> has 2 items (one is about "ios_info")

**Comment by markusaksli-nc** [comment]
It could be that the app has some outdated values while the config of the firebase project has been changed, leading to the issues. 
If you download a new `google-services.json` file from the app Firebase Console page -> Project setting -> Android apps -> `google-services.json`
And replace the one in the project does it work as expected?

**Comment by Sthefanny** [comment]
> It could be that the app has some outdated values while the config of the firebase project has been changed, leading to the issues.
> If you download a new `google-services.json` file from the app Firebase Console page -> Project setting -> Android apps -> `google-services.json`
> And replace the one in the project does it work as expected?

Nope.. I updated it but the same problem is happening.

**Comment by markusaksli-nc** [comment]
Does the device you are testing on have consistent internet connection or are you using emulator?

**Comment by Sthefanny** [comment]
> Does the device you are testing on have consistent internet connection or are you using emulator?

Yes and I also tested on the emulator and the same problem is happening

**Comment by markusaksli-nc** [comment]
Was not able to reproduce but labeling this based on the report for now

**Comment by tjarvstrand** [comment]
I also see this issue intermittently but I haven't been able to find a way to reproduce it manually.

>For obvious reasons, I won't post it here, ...

@Sthefanny the `google-services.json` doesn't actually contain any sensitive information. It is included inside the app binary that you distribute and can be extracted by anyone without too much effort.

**Comment by niypoo** [comment]
this issue show up to me when user use app in offline mode without internet
``` 
I/System.out(12440): (HTTPLog)-Static: isSBSettingEnabled false
D/FRCPlugin(12440): Sending fetchTimeout: 10
I/flutter (12440): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (12440): FormatException: Invalid envelope

```

**Comment by rockerhieu** [comment]
I also got this issue when migrate to `firebase_remote_config: ^0.10.0+1`

**Comment by rockerhieu** [comment]
So in the case of multiple `FirebaseApp`, these cases work:
- Use `RemoteConfig.instance`
- Use `RemoteConfig.instanceFor(Firebase.app())`

This case doesn't work for me:
- `RemoteConfig.instanceFor(app: secondaryApp)` where `secondaryApp != Firebase.app()`

To reproduce this error:
- Use the same example project for `firebase_remote_config`
- Modify `lib/main.dart`

```dart
Future<RemoteConfig> setupRemoteConfig() async {
  await Firebase.initializeApp();
  final secondaryApp = await Firebase.initializeApp(
      name: 'secondaryApp',
      options: const FirebaseOptions(
        apiKey: 'xxxxx,
        messagingSenderId: 'xxxx',
        projectId: 'xxxx',
        appId: 'xxxxx',
      ));
  final RemoteConfig remoteConfig = RemoteConfig.instanceFor(app: secondaryApp);
  await remoteConfig.setConfigSettings(RemoteConfigSettings(
    fetchTimeout: const Duration(seconds: 10),
    minimumFetchInterval: const Duration(hours: 1),
  ));
  await remoteConfig.setDefaults(<String, dynamic>{
    'welcome': 'default welcome',
    'hello': 'default hello',
  });
  RemoteConfigValue(null, ValueSource.valueStatic);
  return remoteConfig;
}
```

In my case, `secondaryApp` is another app in a different project than the default one. I also don't have App Check enabled. The reason why I have to do it like this is because of https://github.com/FirebaseExtended/flutterfire/issues/5844. Basically our app has a default `google-service.json` and allow to switch between firebase projects at runtime.

**Comment by rockerhieu** [comment]
This is the full stacktrace:

> I/flutter (28454): FormatException: Invalid envelope #0      convertPlatformException (package:firebase_remote_config_platform_interface/src/method_channel/utils/exception.dart:9:5)
> I/flutter (28454): #1      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:155:13)
> I/flutter (28454): <asynchronous suspension>
> I/flutter (28454): #2      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
> I/flutter (28454): <asynchronous suspension>
> I/flutter (28454): #3      WelcomeWidget.build.<anonymous closure> (package:firebase_remote_config_example/main.dart:62:13)
> I/flutter (28454): <asynchronous suspension>

**Comment by mk-dev-1** [comment]
Hi everyone,

I can confirm what @niypoo is saying: I can see this error whenever I am offline. Simply put the emulator into flight mode and the error will show up...

**Comment by rockerhieu** [comment]
@markusaksli-nc is there anything else that I should provide to get this issue addressed?

**Comment by MilesAdamson** [comment]
> * `RemoteConfig.instanceFor(app: secondaryApp)` where `secondaryApp != Firebase.app()`

I am having the exact same issue

**Comment by sunndog** [comment]
**exception:** 
FormatException (FormatException: Invalid envelope)

**stacktrace**:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:599:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:145:29)
<asynchronous suspension>
#3      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
<asynchronous suspension>
#4      _initializeRemoteConfig (package:firebase_rc/main.dart:28:3)
<asynchronous suspension>
#5      main (package:firebase_rc/main.dart:10:3)
<asynchronous suspension>

**Comment by AlexHartford** [comment]
I lost access to my old system and had to add a new SHA1 key for an app. Firebase auth, etc. working smoothly. However, I'm also getting the `Invalid envelope` error now when attempting to call `RemoteConfig.instance.fetchAndActivate()`. I am using version `0.10.0`. This problem was not occurring on my old system. I have downloaded a new `google-services.json` after adding the SHA1 key, and can verify that works because Firebase auth and storage are both working fine. Any idea what's going on here?

**Comment by shirakiya** [comment]
I faced the same issue when my smartphone does not connect Internet.

**Comment by tgpsantos** [comment]
Also getting this error in many of my users, in our case we do an internet connectivity check before fetching remote config data; if the user has no internet we don't fetch the data. In spite of this, other logs show us that 80% of these users seem to be linked to an unstable internet connection, and error also appears many times when the app is in background (but not exclusively, also happens on app init)

**Comment by anhphamduy** [comment]
Some of our users got the same error logs on both Android and iOS. I was able to replicate it after turning off the internet.

**Comment by mk-dev-1** [comment]
> I solved my problem: for some reason my android debug.keystore was the problem.
> 
> I added my keystore at firebase, downloaded the new google-services.json, added it to the android project, but I still was having the problem.
> 
> Another person from my team sent me his keystore and everything worked just fine.
> 
> I just found it out because I tried to use firebase_messaging and it gave me "Failed to get FIS auth token", so I realized it had something to do with firebase at all

Morning everyone, this is not working for me and I dont think it has got anything to do with the problem. Even if it has, the error should be caught properly. Can we re-open this?

**Comment by zmeggyesi** [comment]
I'm doing a connectivity check before fetching, and a lack of internet connectivity is almost certainly _not_ the issue here. There's something else at play, but I'm not sure yet what that is...
