### ISSUE TITLE
🐛 [Firebase Messaging] How can i send notification to subscriber only?

### ISSUE THREAD

**Issue by shinewanna** [FirebaseExtended/flutterfire#5959]
How can i send notification to subscriber only, i add topic on map but it doesn't work, it's still send to any topics.

```
  Future<void> sendNotification({String title, String subtitle}) async {
    await Future.delayed(Duration(seconds: 2));
    var data = {
      "notification": {"body": subtitle, "title": title},
      "priority": "high",
      "content_available": true,
      "data": {
        "click_action": "FLUTTER_NOTIFICATION_CLICK",
        "id": "1",
        "status": "done"
      },
      "topic": "all",
      "to": FirebaseConstant.token
    };
    final headers = {
      'content-type': 'application/json',
      'Authorization': FirebaseConstant.serverToken,
    };

    await postReq(
      FirebaseConstant.sendUrl,
      "",
      fd: data,
      headers: headers,
      isReturnFuture: true,
    );
  }
```

**Comment by markusaksli-nc** [comment]
Hi @shinewanna 
Please see https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877
To figure out how to send messages through the Firebase API please read the official documentation
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

As mentioned, if you have any other question feel free to seek help from the community. This place is reserved for bug reports with the Flutter implementation of the native Firebase SDKs.
Thank you
