### ISSUE TITLE
🐛 [cloud_firestore] Named app is not being used by firestore

### ISSUE THREAD

**Issue by MilesAdamson** [FirebaseExtended/flutterfire#5963]
## Bug report

**Describe the bug**
The named app which has been initialized and provided is not being used when accessing collections

### Steps to reproduce

1. Setup named app called "local"
2. Use it to access firestore
3. Access a collection fails when it tries to use the default app instead of the one provided

### Expected behavior

It uses the named app provided in `instanceFor`

---

## Additional context

![image](https://user-images.githubusercontent.com/29047682/116447030-ca31b680-a814-11eb-8885-9f37b36b7269.png)

---

Note we are on an old version due to some dependency hell when trying to upgrade all our plugins

```
  firebase_core: ^0.5.0
  cloud_firestore: 0.14.1+3
```

**Comment by markusaksli-nc** [comment]
Hi @MilesAdamson 
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Ehesp** [comment]
What platform is this?

**Comment by MilesAdamson** [comment]
Sorry I forgot to come back and post here. The issue was I thought I could delete the google services json files when using a different firebase app. If I still initialize a default one it works as expected
