### ISSUE TITLE
🐛 [firebase_auth] Unhandled Exception: type 'Null' is not a subtype of type 'int' when doing Phone Authentication on IOS

### ISSUE THREAD

**Issue by kuromukira** [FirebaseExtended/flutterfire#5968]
## Bug report

**Describe the bug**
I upgraded my dependencies to the latest version of firebase_auth and now I can't do phone number authentication on iOS.

firebase_analytics: ^8.0.2
firebase_auth: ^1.1.2
firebase_core: ^1.1.0
firebase_crashlytics: ^2.0.2
firebase_messaging: ^9.1.3
firebase_storage: ^8.0.5

Exception details:
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure> (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:573:21)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#8      _rootRun (dart:async/zone.dart:1346:47)
#9      _CustomZone.run (dart:async/zone.dart:1258:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:<…>
```

### Steps to reproduce

1. The usual Flutter Fire setup for phone number authentication
2. Sign-in using phone number
3. Boom! Exception occurred

### Expected behavior

There should be no bugs

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)
    ! Error: PHONE is not connected. Xcode will continue when PHONE is connected. (code -13)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.5
myApp 1.7.11

dependencies:
- badges 2.0.0-nullsafety.1 [flutter]
- bottom_navy_bar 6.0.0 [flutter]
- bubble 1.2.1 [flutter]
- file_picker 3.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 8.0.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.0.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 9.1.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 8.0.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 5.0.0+3 [flutter flutter_local_notifications_platform_interface platform timezone]
- font_awesome_flutter 9.0.0 [flutter]
- get_it 6.1.1 [async collection]
- myApp_core 1.7.11 [flutter equatable firebase_analytics firebase_auth firebase_core firebase_crashlytics firebase_messaging firebase_storage flutter_local_notifications font_awesome_flutter get_it hive hive_flutter http intl logger path provider tuple]
- myApp_ui 1.7.11 [flutter myApp_core badges camera cached_network_image dropdown_search flutter_spinkit flutter_svg loading_overlay page_transition pull_to_refresh]
- page_transition 2.0.1-nullsafety.0 [flutter]
- pinput 1.2.0 [flutter]
- provider 5.0.0 [collection flutter nested]
- smooth_page_indicator 0.3.0-nullsafety.0 [flutter]
- tuple 2.0.0 [quiver]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- import_sorter 4.5.0 [args tint yaml]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.1.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- camera 0.8.1 [flutter camera_platform_interface pedantic quiver]
- camera_platform_interface 2.0.1 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- cross_file 0.3.1+1 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- dropdown_search 0.5.0 [flutter]
- equatable 2.0.0 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.0 [flutter meta]
- firebase_analytics_web 0.3.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_spinkit 5.0.0 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.0.0 [flutter hive path_provider path]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.3
- loading_overlay 0.3.0 [flutter]
- logger 1.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- pull_to_refresh 1.6.4-nullsafety.0 [flutter]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- tint 2.0.0
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by kuromukira** [comment]
I tried on the updated Android Emulator in macOS Big Sur 11.3 and phone authentication works. This seems to be an issue in iOS only

**Comment by markusaksli-nc** [comment]
Hi @kuromukira 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5941.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Edord99** [comment]
> ## Bug report
> 
> 
> 
> **Describe the bug**
> 
> I upgraded my dependencies to the latest version of firebase_auth and now I can't do phone number authentication on iOS.
> 
> 
> 
> firebase_analytics: ^8.0.2
> 
> firebase_auth: ^1.1.2
> 
> firebase_core: ^1.1.0
> 
> firebase_crashlytics: ^2.0.2
> 
> firebase_messaging: ^9.1.3
> 
> firebase_storage: ^8.0.5
> 
> 
> 
> Exception details:
> 
> ```
> 
> [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
> 
> #0      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure> (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:573:21)
> 
> #1      _rootRunUnary (dart:async/zone.dart:1362:47)
> 
> #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
> 
> #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
> 
> #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> 
> #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
> 
> #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
> 
> #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
> 
> #8      _rootRun (dart:async/zone.dart:1346:47)
> 
> #9      _CustomZone.run (dart:async/zone.dart:1258:19)
> 
> #10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
> 
> #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:<…>
> 
> ```
> 
> 
> 
> ### Steps to reproduce
> 
> 
> 
> Steps to reproduce the behavior:
> 
> 
> 
> 1. The usual Flutter Fire setup for phone number authentication
> 
> 2. Sign-in using phone number
> 
> 3. Boom! Exception occurred
> 
> 
> 
> ### Expected behavior
> 
> 
> 
> There should be no bugs
> 
> 
> 
> ---
> 
> 
> 
> ### Flutter doctor
> 
> 
> 
> Run `flutter doctor` and paste the output below:
> 
> 
> 
> <details><summary>Click To Expand</summary>
> 
> 
> 
> ```
> 
> Doctor summary (to see all details, run flutter doctor -v):
> 
> [✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale en-PH)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> 
> [✓] Xcode - develop for iOS and macOS
> 
> [✓] Chrome - develop for the web
> 
> [✓] Android Studio (version 4.1)
> 
> [✓] VS Code (version 1.55.2)
> 
> [✓] Connected device (1 available)
> 
>     ! Error: PHONE is not connected. Xcode will continue when PHONE is connected. (code -13)
> 
> 
> 
> • No issues found!
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> ---
> 
> 
> 
> ### Flutter dependencies
> 
> 
> 
> Run `flutter pub deps -- --style=compact` and paste the output below:
> 
> 
> 
> <details><summary>Click To Expand</summary>
> 
> 
> 
> ```
> 
> Dart SDK 2.12.3
> 
> Flutter SDK 2.0.5
> 
> myApp 1.7.11
> 
> 
> 
> dependencies:
> 
> - badges 2.0.0-nullsafety.1 [flutter]
> 
> - bottom_navy_bar 6.0.0 [flutter]
> 
> - bubble 1.2.1 [flutter]
> 
> - file_picker 3.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
> 
> - firebase_analytics 8.0.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
> 
> - firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
> 
> - firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
> 
> - firebase_crashlytics 2.0.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
> 
> - firebase_messaging 9.1.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
> 
> - firebase_storage 8.0.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
> 
> - flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
> 
> - flutter_local_notifications 5.0.0+3 [flutter flutter_local_notifications_platform_interface platform timezone]
> 
> - font_awesome_flutter 9.0.0 [flutter]
> 
> - get_it 6.1.1 [async collection]
> 
> - myApp_core 1.7.11 [flutter equatable firebase_analytics firebase_auth firebase_core firebase_crashlytics firebase_messaging firebase_storage flutter_local_notifications font_awesome_flutter get_it hive hive_flutter http intl logger path provider tuple]
> 
> - myApp_ui 1.7.11 [flutter myApp_core badges camera cached_network_image dropdown_search flutter_spinkit flutter_svg loading_overlay page_transition pull_to_refresh]
> 
> - page_transition 2.0.1-nullsafety.0 [flutter]
> 
> - pinput 1.2.0 [flutter]
> 
> - provider 5.0.0 [collection flutter nested]
> 
> - smooth_page_indicator 0.3.0-nullsafety.0 [flutter]
> 
> - tuple 2.0.0 [quiver]
> 
> - url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
> 
> 
> 
> dev dependencies:
> 
> - flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
> 
> - import_sorter 4.5.0 [args tint yaml]
> 
> 
> 
> transitive dependencies:
> 
> - archive 3.1.2 [crypto path]
> 
> - args 2.1.0
> 
> - async 2.5.0 [collection]
> 
> - boolean_selector 2.1.0 [source_span string_scanner]
> 
> - cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
> 
> - camera 0.8.1 [flutter camera_platform_interface pedantic quiver]
> 
> - camera_platform_interface 2.0.1 [flutter meta plugin_platform_interface cross_file stream_transform]
> 
> - characters 1.1.0
> 
> - charcode 1.2.0
> 
> - clock 1.1.0
> 
> - collection 1.15.0
> 
> - cross_file 0.3.1+1 [flutter meta]
> 
> - crypto 3.0.1 [collection typed_data]
> 
> - dropdown_search 0.5.0 [flutter]
> 
> - equatable 2.0.0 [collection meta]
> 
> - fake_async 1.2.0 [clock collection]
> 
> - ffi 1.0.0
> 
> - file 6.1.0 [meta path]
> 
> - firebase 9.0.1 [http http_parser js]
> 
> - firebase_analytics_platform_interface 2.0.0 [flutter meta]
> 
> - firebase_analytics_web 0.3.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
> 
> - firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
> 
> - firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
> 
> - firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
> 
> - firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
> 
> - firebase_crashlytics_platform_interface 3.0.2 [collection firebase_core flutter meta plugin_platform_interface]
> 
> - firebase_messaging_platform_interface 2.1.3 [firebase_core flutter meta plugin_platform_interface]
> 
> - firebase_messaging_web 1.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
> 
> - firebase_storage_platform_interface 2.0.3 [collection firebase_core flutter meta plugin_platform_interface]
> 
> - firebase_storage_web 1.0.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
> 
> - flutter_blurhash 0.6.0 [flutter meta pedantic]
> 
> - flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
> 
> - flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
> 
> - flutter_plugin_android_lifecycle 2.0.1 [flutter]
> 
> - flutter_spinkit 5.0.0 [flutter]
> 
> - flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
> 
> - flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
> 
> - hive 2.0.4 [meta crypto]
> 
> - hive_flutter 1.0.0 [flutter hive path_provider path]
> 
> - http 0.13.1 [http_parser meta path pedantic]
> 
> - http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
> 
> - image 3.0.2 [archive meta xml]
> 
> - intl 0.17.0 [clock path]
> 
> - js 0.6.3
> 
> - loading_overlay 0.3.0 [flutter]
> 
> - logger 1.0.0
> 
> - matcher 0.12.10 [stack_trace]
> 
> - meta 1.3.0
> 
> - nested 1.0.0 [flutter]
> 
> - octo_image 1.0.0+1 [flutter flutter_blurhash]
> 
> - path 1.8.0
> 
> - path_drawing 0.5.0 [vector_math meta path_parsing flutter]
> 
> - path_parsing 0.2.0 [vector_math meta]
> 
> - path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
> 
> - path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
> 
> - path_provider_macos 2.0.0 [flutter]
> 
> - path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
> 
> - path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
> 
> - pedantic 1.11.0
> 
> - petitparser 4.1.0 [meta]
> 
> - platform 3.0.0
> 
> - plugin_platform_interface 2.0.0 [meta]
> 
> - process 4.2.1 [file path platform]
> 
> - pull_to_refresh 1.6.4-nullsafety.0 [flutter]
> 
> - quiver 3.0.1 [matcher]
> 
> - rxdart 0.26.0
> 
> - sky_engine 0.0.99
> 
> - source_span 1.8.0 [charcode collection path term_glyph]
> 
> - sqflite 2.0.0+3 [flutter sqflite_common path]
> 
> - sqflite_common 2.0.0+2 [synchronized path meta]
> 
> - stack_trace 1.10.0 [path]
> 
> - stream_channel 2.1.0 [async]
> 
> - stream_transform 2.0.0
> 
> - string_scanner 1.1.0 [charcode source_span]
> 
> - synchronized 3.0.0
> 
> - term_glyph 1.2.0
> 
> - test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
> 
> - timezone 0.7.0 [path]
> 
> - tint 2.0.0
> 
> - typed_data 1.3.0 [collection]
> 
> - url_launcher_linux 2.0.0 [flutter]
> 
> - url_launcher_macos 2.0.0 [flutter]
> 
> - url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
> 
> - url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
> 
> - url_launcher_windows 2.0.0 [flutter]
> 
> - uuid 3.0.4 [crypto]
> 
> - vector_math 2.1.0
> 
> - win32 2.0.5 [ffi]
> 
> - xdg_directories 0.2.0 [meta path process]
> 
> - xml 5.1.0 [collection meta petitparser]
> 
> - yaml 3.1.0 [collection source_span string_scanner]
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> ---
> 
>

**Comment by Edord99** [comment]
Gt
