### ISSUE TITLE
🐛 [firebase_ml_vision] Adding the Object Detection

### ISSUE THREAD

**Issue by wazini-john** [FirebaseExtended/flutterfire#5972]
I am trying to add object detection in my flutter app and can not find it in the documentation. Is this a bug or how do I implement it?

**Comment by markusaksli-nc** [comment]
Hi @wazini-john 
Please take a look at the official example for an example of how to use all the on-device and cloud ml vision APIs.
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example
Thank you
