### ISSUE TITLE
[📚] firebase_messaging example does not work on web

### ISSUE THREAD

**Issue by markusaksli-nc** [FirebaseExtended/flutterfire#5975]
The firebase messaging example should be changed to work on web. The first issue is that it will crash because of local notifications. This can be fixed with something like
```dart
AndroidNotificationChannel channel;
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  // Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  if (!kIsWeb) {
    /// Create a [AndroidNotificationChannel] for heads up notifications
    channel = AndroidNotificationChannel(
      'high_importance_channel', // id
      'High Importance Notifications', // title
      'This channel is used for important notifications.', // description
      importance: Importance.high,
    );

    /// Initialize the [FlutterLocalNotificationsPlugin] package.
    flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

    /// Create an Android Notification Channel.
    ///
    /// We use this channel in the `AndroidManifest.xml` file to override the
    /// default FCM channel to enable heads up notifications.
    await flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()?.createNotificationChannel(channel);

    /// Update the iOS foreground notification presentation options to allow
    /// heads up notifications.
    await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
  }

  runApp(MessagingExampleApp());
}
```
and in `onMessage.listen`
```dart
      if (notification != null && android != null && !kIsWeb) {
```

Then there is what was mentioned in https://github.com/FirebaseExtended/flutterfire/issues/5515

PS the example will also crash whenever a notification is successfully received because of local notification on macos.

**Comment by zepol-yerffej** [comment]
Also, the current example implies that [the flutter service worker can be registered alongside another service worker dedicated for FCM](https://github.com/FirebaseExtended/flutterfire/blob/aacabd1fe5ce4a99bceb4d24dbee2c6838581760/packages/firebase_messaging/firebase_messaging/example/web/index.html#L29). Following the example will cause this error:

`Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:4200/') with script ('http://localhost:4200/firebase-messaging-sw.js'): ServiceWorker script evaluation failed`

Commenting out the line linked above (as suggested [here](https://stackoverflow.com/q/63799227) and [here](https://medium.com/@rody.davis.jr/how-to-send-push-notifications-on-flutter-web-fcm-b3e64f1e2b76)) fixes the issue, but the app will lose the functionality that the generated Flutter service worker provides.

**Comment by JohnGalt1717** [comment]
Also the documentation for background notifications says that you should put the js file load for the service worker after the main.js but Flutter 2.2 which was just released doesn't load just the script it has a whole ceremony that also loads the service worker.

The result is that I can't find anywhere to load the firebase stuff and get "Cannot read property 'messaging' of undefined.

I can confirm that it does load firebase-messaging-sw.js and const messaging = firebase.messaging() is hit in the javascript when I put the service worker right before the setTimeout in the page but then main() from web_entrypoint throws the error about messaging being undefined thus blocking the use of firebase messaging.
