### ISSUE TITLE
🐛 [FCM On Message Recieved Flutter] method on message received is called twice

### ISSUE THREAD

**Issue by h4775346** [FirebaseExtended/flutterfire#5986]
## method on message received is called twice in Flutter

**Describe the bug**
when I get a message from FCM the method is called twice

### Steps to reproduce

---

### all that I could do
You can save the message-id in a variable then when a new message received twice, the first message-id will be saved in this variable and when it called twice the second time you will check if exists in your variable or not .. for example

```
String savedMessageId  = "";

 public void setupFCM() {

 FirebaseMessaging.onMessage.listen((RemoteMessage message) {
 if (savedMessageId != message.messageId)
        savedMessageId  = message.messageId;
      else
        return;


     // your code ...

}
  }
```

**Comment by markusaksli-nc** [comment]
Hi @h4775346 
Could you please provide your `flutter doctor -v`, `flutter pub deps -- --style=compact` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by kustraslawomir** [comment]
FUCKING PIECE OF SHIT
