### ISSUE TITLE
🐛 [FIREBASE_AUTH] Phone Auth throwing null exception causing the codeSent callback to never be called

### ISSUE THREAD

**Issue by brian-kayfitz** [FirebaseExtended/flutterfire#5989]
## Bug report

**Describe the bug**
There seems to be a null error when parsing the results of the phoneCodeSent callback from the iOS (and maybe Android) platform.  When parsing the the arguments map, if the `forceResendingToken` property is null, an exception will be thrown, even though the code is suppose to handle null values.

```dart
        } else if (name == 'Auth#phoneCodeSent') {
          final String verificationId = arguments['verificationId'];
          final int forceResendingToken = arguments['forceResendingToken'];

          codeSent(verificationId, forceResendingToken);
```

To remedy this, type inference can probably allow for nulls to be elegantly passed into the callback

```dart
        } else if (name == 'Auth#phoneCodeSent') {
          final verificationId = arguments['verificationId'];
          final forceResendingToken = arguments['forceResendingToken'];

          codeSent(verificationId, forceResendingToken);
```

### Steps to reproduce

1. Create a Firebase App With Phone Auth configured
2. Try to sign in with a phone number and complete the reCaptcha
3. Notice that the `codeSent` callback never gets called

### Expected behavior

`codeSent` should be called so users can enter the OTP code that was sent to them via sms

---

## Additional context

This is present in the latest version of Firebase Auth `1.1.2`

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-arm, locale
    en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)
```

</details>

---

**Comment by nzackoya** [comment]
+

**Comment by brian-kayfitz** [comment]
It looks like there I already an open pr that resolves this issue - https://github.com/FirebaseExtended/flutterfire/pull/5944

**Comment by brian-kayfitz** [comment]
As a temporary solution, I've pushed a fix to my fork of Firebase Auth.

You can add this to your pubspec

```yaml
dependency_overrides:
  firebase_auth_platform_interface:
    git:
      url: git@github.com:heartsradiant/flutterfire
      path: packages/firebase_auth/firebase_auth_platform_interface
```

**Comment by nzackoya** [comment]
> As a temporary solution, I've pushed a fix to my fork of Firebase Auth.
> 
> 
> 
> You can add this to your pubspec
> 
> 
> 
> ```yaml
> 
> dependency_overrides:
> 
>   firebase_auth_platform_interface:
> 
>     git:
> 
>       url: git@github.com:heartsradiant/flutterfire
> 
>       path: packages/firebase_auth/firebase_auth_platform_interface
> 
> ```
If you have just set int? it doesn't fix, after logging in the currentUser is null. I guess the bug is much deeper and this fix won't help

**Comment by RounakTadvi** [comment]
This bug needs to be fixed soon.

**Comment by markusaksli-nc** [comment]
Hi @brian-kayfitz 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5941.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by zumrywahid** [comment]
> > As a temporary solution, I've pushed a fix to my fork of Firebase Auth.
> > You can add this to your pubspec
> > ```yaml
> > dependency_overrides:
> > 
> >   firebase_auth_platform_interface:
> > 
> >     git:
> > 
> >       url: git@github.com:heartsradiant/flutterfire
> > 
> >       path: packages/firebase_auth/firebase_auth_platform_interface
> > ```
> 
> If you have just set int? it doesn't fix, after logging in the currentUser is null. I guess the bug is much deeper and this fix won't help

This doesn't help. I tested.
