### ISSUE TITLE
🐛 [ml_vision] APK double size with 0.12.0 coming from 0.9.10

### ISSUE THREAD

**Issue by jaumard** [FirebaseExtended/flutterfire#5990]
Hello,

My APK was doing 39MB, after upgrading ml_vision I'm getting 66MB!!! 

By checking the APK I see those new items: 

<img width="279" alt="Capture d’écran 2021-04-30 à 19 09 45" src="https://user-images.githubusercontent.com/2970449/116730402-bfc81600-a9e8-11eb-9da3-214c0ba9021a.png">

When previously I had only this:

<img width="629" alt="Capture d’écran 2021-04-30 à 19 10 15" src="https://user-images.githubusercontent.com/2970449/116730474-d40c1300-a9e8-11eb-877a-da88f47fa0c3.png">

Also gaining 9MB with "models":

<img width="664" alt="Capture d’écran 2021-04-30 à 19 19 28" src="https://user-images.githubusercontent.com/2970449/116730615-fe5dd080-a9e8-11eb-9dfe-48c7ce856b02.png">

Is those coming from this package too?? 

That's a huge issue to me, having a quick fix or workaround would be appreciated. 

I have checked the gradle file of the plugin and saw that:

```
  api "com.google.firebase:firebase-ml-vision"

        implementation 'com.google.android.gms:play-services-vision:20.1.1'
        implementation 'com.google.android.gms:play-services-vision-common:19.1.1'
        implementation 'com.google.android.gms:play-services-vision-face-contour-internal:16.0.3'
        implementation 'com.google.android.gms:play-services-vision-image-labeling-internal:16.0.5'
        implementation 'com.google.android.gms:play-services-vision-image-label:18.0.5'
        implementation 'com.google.firebase:firebase-ml-vision-face-model:20.0.2'
        implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.4'
```
Compare to previously:
```
api 'com.google.firebase:firebase-ml-vision:20.0.0'
        implementation 'com.google.firebase:firebase-common:16.1.0'
        implementation 'androidx.annotation:annotation:1.0.0'
        implementation 'androidx.exifinterface:exifinterface:1.0.0'
```

**Comment by tokyokamera** [comment]
I have some problem.Please fix it!

**Comment by jaumard** [comment]
I have deleted manually those lines and rebuild my APK:
```
implementation 'com.google.android.gms:play-services-vision-face-contour-internal:16.0.3'
        implementation 'com.google.android.gms:play-services-vision-image-labeling-internal:16.0.5'
        implementation 'com.google.android.gms:play-services-vision-image-label:18.0.5'
        implementation 'com.google.firebase:firebase-ml-vision-face-model:20.0.2'
        implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.4'

```
And my APK is back to 30MB

**Comment by markusaksli-nc** [comment]
Hi @jaumard 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4767.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
