### ISSUE TITLE
ML Vision is updated frequently and yet still uses the old ml vision library which doesn't compile anymore

### ISSUE THREAD

**Issue by Greatcallie** [FirebaseExtended/flutterfire#5994]
This package is updated frequently and yet still uses the old ml vision library which doesn't compile anymore. 

I have tried to update to the new library : GoogleMLKit/FaceDetection, and now pod installs but face recognition
just doesn't work anymore.

**Comment by markusaksli-nc** [comment]
Closing as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4625
