### ISSUE TITLE
🐛 [firebase_messaging ] notification data not received correctly after kill app 

### ISSUE THREAD

**Issue by mustafa-707** [FirebaseExtended/flutterfire#5998]
## Bug report

**Describe the bug**
In foreground and in background while app is open the the notification works perfect but when app is killed and the notification received and opened there's a weird behavior , which the app opens and went to home screen when i was send a route name ,So it expected to go to a specific screen , after much experiment with background top-level function , i found the following : 

1. it call it self after kill but too fast , which it not makes the app open the  specific screen
2. when i tried to made a delay it but it depend on device memory and the processes that happen to catch the notification parameter .
3. when app open screen that contain interstitial Ad the close button of the interstitial Ad close the notification screen (pop it).

# My Info : 

I used the dependency : `firebase_messaging : ^8.0.0-dev.15` with firebase core :  `0.7.0` cause its the latest version that support `flutter 1.66.2` and `dart 2.10`
it happened on both android and IOS 
i was used to  `firebase_messaging: ^7.0.3` without facing any problem

**Comment by markusaksli-nc** [comment]
Hi @mustafa-707 
Not being able to receive the background notification is the expected and documented behavior if the app is killed.
https://firebase.flutter.dev/docs/messaging/usage#receiving-messages
Thank you
