### ISSUE TITLE
[cloud_firestore] Query cursors should support DocumentSnapshots

### ISSUE THREAD

**Issue by larssn** [FirebaseExtended/flutterfire#60]
So the official example for pagination (https://firebase.google.com/docs/firestore/query-data/query-cursors#paginate_a_query) via query cursors seems to indicate that you can feed `startAfter` a DocumentSnapshot, and then start after that document in your next Query.

However when doing that, the error `Invalid argument: Instance of DocumentSnapshot` is thrown.

So consider this a feature request for further parity between the two APIs.

**Comment by creativecreatorormaybenot** [comment]
Hi there, you only need to append `Document` ,e.g. [`startAfterDocument`](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/startAfterDocument.html). I personally worked on making these stable, i.e. they should properly work in all scenarios.

**Comment by larssn** [comment]
Ah perfect, I missed that. Thanks.
