### ISSUE TITLE
Firebase Analytics missing reset function

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#600]
Firebase Analytics is missing the resetAnalyticsData option this is needed.

**Comment by kroikie** [comment]
@rlee1990

The issue at https://github.com/flutter/flutter/issues/23441 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release and raising a feature request in Discussions if necessary.
