### ISSUE TITLE
🐛 [firebase_auth] Phone auth not persisting on iOS

### ISSUE THREAD

**Issue by JoelRomero97** [FirebaseExtended/flutterfire#6013]
## Phone Auth is not persisting

**Description (Flutter)**
I am implementing phone auth (before flutter 2.0) and did the migration maybe 2 weeks ago, everything was working fine, but suddenly I updated the packages to the newest versions and phone auth is not working anymore, I mean, it is, but if I do a hot restart (or in TestFlight close the app and open it again) the app says that firebase current user has nothing, is not persisting the state.

### Steps to reproduce

1. Login into the app with phone auth
2. Hot restart
3. Not user logged in

### Expected behavior

1. Login into the app with phone auth
2. Hot restart
3. User logged in and go directly to home

**Comment by Qormix** [comment]
I'm having an issue with the Auth on iOS aswell, with the 1.1.2 package and firebase SDK 7.10.0 or 7.11.0

The FirebaseAuth.instance.authStateChanges() initially emits a null, but then no user.

While calling FirebaseAuth.instance.currentUser periodically does initially return null then a user.

**Comment by zumrywahid** [comment]
Happening to me as well. In the latest version.

**Comment by zumrywahid** [comment]
Temporary workaround 

  firebase_core: "1.1.0"
  firebase_auth: "1.1.0"
  cloud_firestore: "1.0.7"
  firebase_messaging: "9.1.3"
  firebase_storage: "8.0.5"
  
Note : Dont use ^ symbol.

**Comment by Salakar** [comment]
This was fixed by https://github.com/FirebaseExtended/flutterfire/pull/5987 - pending release later today - thanks.
