### ISSUE TITLE
ios error for firebase_messaging 

### ISSUE THREAD

**Issue by dasarijit88** [FirebaseExtended/flutterfire#6032]
I get error if i include firebase_messaging package in ios. It works perfect in android though.
My dependencies are below:
  provider: ^5.0.0
  http: ^0.12.0+2
  intl: ^0.15.8
  shared_preferences: ^0.5.3+1
  graphql_flutter: ^3.0.0
  fl_chart: ^0.20.1
  firebase_core: "^0.7.0"
  cloud_firestore: "^0.16.0+1"
  firebase_messaging: "6.0.13"
  image_picker: "^0.6.7+22"

Error:
Xcode build done.                                           63.3s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[2769]: Class AMSupportURLConnectionDelegate is implemented in both ??
    (0x200f178f0) and ?? (0x117e242b8). One of the two will be used. Which one is
    undefined.
    objc[2769]: Class AMSupportURLSession is implemented in both ?? (0x200f17940)
    and ?? (0x117e24308). One of the two will be used. Which one is undefined.
    2021-05-05 12:04:30.125 xcodebuild[2769:5546001]  DTDeviceKit: deviceType from
    00008006-001121CC3AEB002E was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+
    22/ios/Classes/FLTImagePickerPlugin.m:149:20: warning: 'UIAlertView' is
    deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use
    UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
        [[[UIAlertView alloc] initWithTitle:NSLocalizedString(@"Error", nil)
                       ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAle
    rtView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    1 warning generated.
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+
    22/ios/Classes/FLTImagePickerPhotoAssetUtil.m:17:44: warning:
    'UIImagePickerControllerReferenceURL' is deprecated: first deprecated in iOS
    11.0 - Will be removed in a future release, use PHPicker.
    [-Wdeprecated-declarations]
      NSURL *referenceURL = [info
      objectForKey:UIImagePickerControllerReferenceURL];
                                               ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIIma
    gePickerController.h:62:51: note: 'UIImagePickerControllerReferenceURL' has
    been explicitly marked deprecated here
    UIKIT_EXTERN UIImagePickerControllerInfoKey const
    UIImagePickerControllerReferenceURL API_DEPRECATED("Will be removed in a future
    release, use PHPicker.", ios(4.1, 11.0)) API_UNAVAILABLE(tvos); // an NSURL
    that references an asset in the AssetsLibrary framework
                                                      ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+
    22/ios/Classes/FLTImagePickerPhotoAssetUtil.m:21:47: warning:
    'fetchAssetsWithALAssetURLs:options:' is deprecated: first deprecated in iOS 11
    - Will be removed in a future release [-Wdeprecated-declarations]
      PHFetchResult<PHAsset *> *result = [PHAsset fetchAssetsWithALAssetURLs:@[
      referenceURL ]
                                                  ^
    In module 'Photos' imported from
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+
    22/ios/Classes/FLTImagePickerPhotoAssetUtil.h:6:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Photos.framework/Headers/PHAs
    set.h:74:1: note: 'fetchAssetsWithALAssetURLs:options:' has been explicitly
    marked deprecated here
    + (PHFetchResult<PHAsset *> *)fetchAssetsWithALAssetURLs:(NSArray<NSURL *>
    *)assetURLs options:(nullable PHFetchOptions *)options API_DEPRECATED("Will be
    removed in a future release", ios(8, 11), tvos(8, 11)) API_UNAVAILABLE(macos);
    ^
    2 warnings generated.
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:196:43: error: expected a type
    - (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage
    *)remoteMessage {
                                              ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:292:42: warning:
    'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNNotificationSettings
    [-Wdeprecated-declarations]
        didRegisterUserNotificationSettings:(UIUserNotificationSettings
        *)notificationSettings {
                                             ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been
    explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:303:53: error: nullability
    specifier 'nonnull' conflicts with existing specifier 'nullable'
        didReceiveRegistrationToken:(nonnull NSString *)fcmToken {
                                                        ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:308:24: error: expected a type
        didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                           ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:123:7: warning:
    'UIUserNotificationType' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
          UIUserNotificationType notificationTypes = 0;
          ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:125:30: warning:
    'UIUserNotificationTypeSound' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
            notificationTypes |= UIUserNotificationTypeSound;
                                 ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:128:30: warning:
    'UIUserNotificationTypeAlert' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
            notificationTypes |= UIUserNotificationTypeAlert;
                                 ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:131:30: warning:
    'UIUserNotificationTypeBadge' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
            notificationTypes |= UIUserNotificationTypeBadge;
                                 ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:134:7: warning:
    'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNNotificationSettings
    [-Wdeprecated-declarations]
          UIUserNotificationSettings *settings =
          ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been
    explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:135:39: warning:
    'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNNotificationSettings
    [-Wdeprecated-declarations]
              [UIUserNotificationSettings settingsForTypes:notificationTypes
              categories:nil];
                                          ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been
    explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:136:42: warning:
    'registerUserNotificationSettings:' is deprecated: first deprecated in iOS 10.0
    - Use UserNotifications Framework's -[UNUserNotificationCenter
    requestAuthorizationWithOptions:completionHandler:] and
    -[UNUserNotificationCenter setNotificationCategories:]
    [-Wdeprecated-declarations]
          [[UIApplication sharedApplication]
          registerUserNotificationSettings:settings];
                                             ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApp
    lication.h:250:1: note: 'registerUserNotificationSettings:' has been explicitly
    marked deprecated here
    - (void)registerUserNotificationSettings:(UIUserNotificationSettings
    *)notificationSettings API_DEPRECATED("Use UserNotifications Framework's
    -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]
    and -[UNUserNotificationCenter setNotificationCategories:]", ios(8.0, 10.0))
    API_UNAVAILABLE(tvos);
    ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:142:30: error: property
    'shouldEstablishDirectChannel' not found on object of type 'FIRMessaging *'
        [FIRMessaging messaging].shouldEstablishDirectChannel = true;
                                 ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:161:21: warning:
    'FIRInstanceID' is deprecated: FIRInstanceID is deprecated, please use
    FIRInstallations for installation identifier handling and use FIRMessaging for
    FCM registration token handling. [-Wdeprecated-declarations]
        [[FIRInstanceID instanceID]
                        ^
    In module 'FirebaseInstanceID' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Headers/Public/Firebase/Firebas
    e.h:74:
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:190:1: note: 'FIRInstanceID' has been explicitly
    marked deprecated here
    __deprecated_msg("FIRInstanceID is deprecated, please use FIRInstallations for
    installation "
    ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit
    .h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/
    Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Head
    ers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from
    macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:162:33: warning:
    'FIRInstanceIDResult' is deprecated: FIRInstanceIDResult is deprecated, please
    use FIRInstallations for app instance identifier handling and use FIRMessaging
    for FCM registration token handling. [-Wdeprecated-declarations]
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
                                    ^
    In module 'FirebaseInstanceID' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Headers/Public/Firebase/Firebas
    e.h:74:
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:153:1: note: 'FIRInstanceIDResult' has been
    explicitly marked deprecated here
    __deprecated_msg("FIRInstanceIDResult is deprecated, please use
    FIRInstallations "
    ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit
    .h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/
    Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Head
    ers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from
    macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:162:9: warning:
    'instanceIDWithHandler:' is deprecated: Use
    `Installations.installationID(completion:)` to get the app instance identifier
    instead. Use `Messaging.token(completion:)` to get FCM registration token
    instead. [-Wdeprecated-declarations]
            instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable
            instanceIDResult,
            ^
    In module 'FirebaseInstanceID' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Headers/Public/Firebase/Firebas
    e.h:74:
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:215:5: note: 'instanceIDWithHandler:' has been
    explicitly marked deprecated here
        __deprecated_msg("Use `Installations.installationID(completion:)` to get
        the app instance "
        ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit
    .h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/
    Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Head
    ers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from
    macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:172:21: warning:
    'FIRInstanceID' is deprecated: FIRInstanceID is deprecated, please use
    FIRInstallations for installation identifier handling and use FIRMessaging for
    FCM registration token handling. [-Wdeprecated-declarations]
        [[FIRInstanceID instanceID] deleteIDWithHandler:^void(NSError *_Nullable
        error) {
                        ^
    In module 'FirebaseInstanceID' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Headers/Public/Firebase/Firebas
    e.h:74:
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:190:1: note: 'FIRInstanceID' has been explicitly
    marked deprecated here
    __deprecated_msg("FIRInstanceID is deprecated, please use FIRInstallations for
    installation "
    ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit
    .h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/
    Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Head
    ers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from
    macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:172:33: warning:
    'deleteIDWithHandler:' is deprecated: Use `Installations.delete(completion:)`
    instead. Also check `Messaging.deleteData(completion:)`if you want to delete
    FCM registration token. [-Wdeprecated-declarations]
        [[FIRInstanceID instanceID] deleteIDWithHandler:^void(NSError *_Nullable
        error) {
                                    ^
    In module 'FirebaseInstanceID' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Headers/Public/Firebase/Firebas
    e.h:74:
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/FirebaseInstanceID/Firebase/Ins
    tanceID/Public/FIRInstanceID.h:321:33: note: 'deleteIDWithHandler:' has been
    explicitly marked deprecated here
                                    __deprecated_msg("Use
                                    `Installations.delete(completion:)` instead. "
                                    ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit
    .h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/
    Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Head
    ers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from
    macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:197:52: error: property
    'appData' not found on object of type '__strong id'
      [self didReceiveRemoteNotification:remoteMessage.appData];
                                                       ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:291:1: warning: implementing
    deprecated method [-Wdeprecated-implementations]
    - (void)application:(UIApplication *)application
    ^
    In module 'Flutter' imported from
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.h:5:
    /Users/arijitdas/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframe
    work/ios-armv7_arm64/Flutter.framework/Headers/FlutterPlugin.h:74:1: note:
    method 'application:didRegisterUserNotificationSettings:' declared here
    - (void)application:(UIApplication*)application
    ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:294:70: warning:
    'UIUserNotificationTypeSound' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
        @"sound" : [NSNumber numberWithBool:notificationSettings.types &
        UIUserNotificationTypeSound],
                                                                         ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:295:70: warning:
    'UIUserNotificationTypeBadge' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
        @"badge" : [NSNumber numberWithBool:notificationSettings.types &
        UIUserNotificationTypeBadge],
                                                                         ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:296:70: warning:
    'UIUserNotificationTypeAlert' is deprecated: first deprecated in iOS 10.0 - Use
    UserNotifications Framework's UNAuthorizationOptions
    [-Wdeprecated-declarations]
        @"alert" : [NSNumber numberWithBool:notificationSettings.types &
        UIUserNotificationTypeAlert],
                                                                         ^
    In module 'UIKit' imported from
    /Users/arijitdas/Flutter_App/tenantapp/ios/Pods/Target Support
    Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Develope
    r/SDKs/iPhoneOS14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUse
    rNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been
    explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/arijitdas/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-
    6.0.13/ios/Classes/FLTFirebaseMessagingPlugin.m:309:63: error: property
    'appData' not found on object of type '__strong id'
      [_channel invokeMethod:@"onMessage" arguments:remoteMessage.appData];
                                                                  ^
    17 warnings and 6 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by markusaksli-nc** [comment]
Hi @dasarijit88 
You are getting a bunch of errors for other packages during the build as well. The versions you are using are heavily outdated. Please use the latest versions of the firebase packages and see if the issue persists.
Thank you
