### ISSUE TITLE
🐛 [FLUTTER_FIREBASE] Flutter app refuses to run after i added firebase SDK

### ISSUE THREAD

**Issue by SmilingFarood** [FirebaseExtended/flutterfire#6038]
E/flutter ( 6636): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 6636): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 6636): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter ( 6636): 	at android.os.Looper.loop(Looper.java:173)
E/flutter ( 6636): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/flutter ( 6636): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 6636): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter ( 6636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter ( 6636):
F/flutter ( 6636): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(943)] Check failed: CheckException(env).
F/libc    ( 6636): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6636 (ample.boofinder), pid 6636 (ample.boofinder)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/STK-L21M/HWSTK-HF:10/HUAWEISTK-L21/10.0.0.274C185:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-05-05 15:22:23+0100
pid: 6636, tid: 6636, name: ample.boofinder  >>> com.example.boofinder <<<
uid: 10277
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(943)] Check failed: CheckException(env).
'
    x0  0000000000000000  x1  00000000000019ec  x2  0000000000000006  x3  0000007fc9285b40
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  899aede63c6eb69e  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000001  x15 0000158570aa9c90

**Comment by markusaksli-nc** [comment]
Hi @SmilingFarood 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
