### ISSUE TITLE
firebase_messaging onLaunch not triggered on iOS and Android(But it looks like channel messages can only be received once a widget was rendered? So I have to call configure inside initState and there is no other way?)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#604]
## Steps to Reproduce

I am using the firebase_messaging plugin. The `onResume` and `onMessage` callbacks are working fine. However the `onLaunch` callback is never triggered. I was trying to look a bit into the source code and added some `NSLog` messages here: 

https://github.com/flutter/plugins/blob/39ba555c4ccf640b2b31943d7befc9b5cba5781d/packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m#L66

I could see my log output so I would assume that I correctly called the `configure` method from dart which is then triggering the check for a `launchNotification` and then calls the `onLaunch` channel. However, that does not trigger my registered method...

Made this default setup on the dart side. I have a print method in the `onLaunch` that never prints. 
So the setup looks something like this. The first `configuring notifications` print is always printing, just have that in there as a check to see if printing in general works.

```dart
  PushNotification() : _firebaseMessaging = FirebaseMessaging() {
    print('configuring notifications');
    _firebaseMessaging.configure(onMessage: (Map<String, dynamic> message) {
      print('onMessage: $message');
    }, onLaunch: (Map<String, dynamic> message) {
      print('onLaunch: $message');
    }, onResume: (Map<String, dynamic> message) {
      print('onResume: $message');
    });
```

I am using the latest release version `2.0.2` of `firebase_messaging`

Am I doing something wrong or is this a bug? At first I thought maybe there is some race condition but from looking at the code, I think that can be ruled out, right? Because after calling `configure` the objective c code is then pushing the initial notification in the `onLaunch` channel.

**Comment by kroikie** [comment]
@wwwdata

The issue at https://github.com/flutter/flutter/issues/23293 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/flutter/issues/23293#issuecomment-432344449

**Comment by Ehesp** [comment]
Hello - please try using the latest version of messaging, as the one described in this issue is quite outdated.

If the issue still occurs, please let me know and I can reopen. Thanks!
