### ISSUE TITLE
🐛 [firebase_messaging] Quick reply in notification using fcm for IOS

### ISSUE THREAD

**Issue by bhanuka96** [FirebaseExtended/flutterfire#6040]
Is it possible to implement a quick reply notification to ios using fcm?

[sample](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.idownloadblog.com%2F2015%2F10%2F22%2Fwhatsapp-quickreply%2F&psig=AOvVaw0tkxHMOHCnMJJiLHdU6Xw1&ust=1620318604070000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCOjfpqr7svACFQAAAAAdAAAAABAD)

**Comment by markusaksli-nc** [comment]
Hi @bhanuka96 
The package does not provide an API to do this. Please take a look at the native options
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification
As far as I can tell this requires some native implementation and you would need to find a specific guide for this.
Thank you
