### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] onBackgroundMessage issue

### ISSUE THREAD

**Issue by ilhamchp** [FirebaseExtended/flutterfire#6044]
## Bug report

**Describe the bug**
I had an issue with firebase messaging, i already disable the onBackgroundMessage method call on main.dart, but the background message notification still appear on my phone. I already clean the project, and re run it on another laptop but its still appear.

### Steps to reproduce

1. `flutter run` on device
2. Quit / close the app
4. Send FCM to the app
5. Background notification appear

### Expected behavior

Background notification shouldn't appear

### Sample project

https://raw.githubusercontent.com/ilhamchp/Dial-OpenVidu/master/lib/main.dart?token=AIJRCUEGFDS3P2SPFK76HYDATTG3Y
---

## Additional context

Even though I don't disable the method, instead I change the implementation, it doesn't change anything.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3 20E232 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4
dial_openvidu 1.0.0+1

dependencies:
- cupertino_icons 0.1.3
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 5.0.0+3 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_webrtc 0.2.8 [flutter]
- html 0.14.0+3 [csslib source_span]
- shared_preferences 0.5.7+3 [meta flutter shared_preferences_platform_interface shared_preferences_macos shared_preferences_web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- csslib 0.16.2 [source_span]
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

Screenshot : 
<details><summary>Click To Expand</summary>

<img width="799" alt="Screen Shot 2021-05-06 at 13 59 19" src="https://user-images.githubusercontent.com/34804048/117254973-4e1e1b00-ae73-11eb-94d2-887307196a77.png">
<img width="490" alt="Screen Shot 2021-05-06 at 13 38 03" src="https://user-images.githubusercontent.com/34804048/117254998-55ddbf80-ae73-11eb-9fb5-680f1f7b951e.png">

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @ilhamchp 
Do you mean that the stream code is being called even when it isn't being listened to?
Or do you just mean that you are still receiving notification in the background?
Thank you

**Comment by Salakar** [comment]
Background messages that have a notification payload will always appear irregardless of whether you've registered a background listener or not as these are handled by the device itself, there's is no way to turn these off from your app other than don't send a notification message from your backend. 

Alternatively, send data only messages from your backend service and then register the background listener in your Flutter code, then inside your listener there you can choose whether to programatically (or not) create and display a local notification (using `flutter_local_notifications` for example) from your message data.
