### ISSUE TITLE
firebase_messaging - onTokenRefresh not firin

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [FirebaseExtended/flutterfire#6045]
Hi,

I have migrated to latest flutter messaging version but still ```FirebaseMessaging.instance.onTokenRefresh``` not firing once app first launched or anyime later.

I am reopening issue: https://github.com/FirebaseExtended/flutterfire/issues/5543

Also it was mentioned:
> Yes, the token seems to be updated appropriately with
>
> firebase_messaging: ^8.0.0-dev.14
>  flutter_local_notifications: ^4.0.1+2
>  http: ^0.13.1
>It could be that the call to getToken is this refreshing when the app is opened since they are both in initState in the official example. However there is already an open issue for the stream on its own not firing.

I do not understand this statement. Does that means that flutter_local_notifications and firebase_messaging not working together? What issue is opened?

**Comment by markusaksli-nc** [comment]
Hi @vytautas-pranskunas- 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5389.
Please follow up on that issue, I'm closing the current one as a duplicate.
Thank you
