### ISSUE TITLE
🐛 [firebase_storage] Can't create reference from url with non-english characters

### ISSUE THREAD

**Issue by haashem** [FirebaseExtended/flutterfire#6047]
## Bug report

**refFromURL(url) can't create reference for url's contains non-english characters**
See this file decoded url which contains farsi characters (file name is in farsi = `سیب`):

`https://firebasestorage.googleapis.com/v0/b/myapp-dev.appspot.com/o/stores/RNbhJ5EshrQ10GsCKww2SRq85Uq2/menu/dd2aa030-ad96-11eb-875a-292d39722e59/سیب?alt=media&token=ee6541ab-6b10-4fdf-990d-454688a2c3ea`

when I try to create reference from url via `refFromUrl` it can't detect farsi characters! and file name is omitted from path.
result: `stores/RNbhJ5EshrQ10GsCKww2SRq85Uq2/menu/dd2aa030-ad96-11eb-875a-292d39722e59`
expected: `stores/RNbhJ5EshrQ10GsCKww2SRq85Uq2/menu/dd2aa030-ad96-11eb-875a-292d39722e59/سیب`

the [regular expression](https://github.com/FirebaseExtended/flutterfire/blob/4594db947acb9a94fc802cf30dc94af7573548ac/packages/firebase_storage/firebase_storage/lib/src/utils.dart#L34) can't understand no-english characters.

is this intentional or I should consider as a bug?

### Expected behavior

`refFromUrl` should properly create reference from urls with non-english characters.

---

`firebase_storage: ^8.0.5`

**Comment by rostopira** [comment]
This is not a bug, using non ASCI characters in URL is invalid, it only works in your browser because unicode characters are percent-encoded. Try this to make valid url:
```dart
import 'dart:core';

var validUrl = Uri.encodeFull(urlWithTarsi);
```

**Comment by haashem** [comment]
In fact I have omitted some steps:

I have a function to delete files:
and fileUrl is:
`https://firebasestorage.googleapis.com/v0/b/myapp-dev.appspot.com/o/stores%2FRNbhJ5EshrQ10GsCKww2SRq85Uq2%2Fmenu%2Fdd2aa030-ad96-11eb-875a-292d39722e59%2F%D8%B3%DB%8C%D8%A8?alt=media&token=a19f545b-0fdf-4b8f-8a62-0644ff7f0ee9`

but `storage.refFromURL(fileUrl)` returns `stores/RNbhJ5EshrQ10GsCKww2SRq85Uq2/menu/dd2aa030-ad96-11eb-875a-292d39722e59` without file name! so the file reference is invalid. and I can't delete the file.

Under the hood, the aforementioned regular expression can't match the farsi characters!

```dart
@override
  Future<Either<FileStorageFailure, Unit>> delete(String fileUrl) {
    return storage
        .refFromURL(fileUrl)
        .delete()
        .then<Either<FileStorageFailure, Unit>>(
          (_) => const Right(unit),
          onError: (error) => Left(
            FileStorageFailure.unexpectedError(error.toString()),
          ),
        )
        .catchError((error) {
      return Left<FileStorageFailure, Unit>(
        FileStorageFailure.unexpectedError(error.toString()),
      );
    });
  }
```

**Comment by rostopira** [comment]
Hm, yeah, that looks like a bug to me. I think part in square brackets should be replaced with `^[]`

**Comment by haashem** [comment]
In the official documentation is written:

```
Reference paths and names can contain any sequence of valid Unicode characters, but certain restrictions are imposed including:

Total length of reference.fullPath must be between 1 and 1024 bytes when UTF-8 encoded.
No Carriage Return or Line Feed characters.
Avoid using #, [, ], *, or ?, as these do not work well with other tools such as the Firebase Realtime Database or gsutil.
```
https://firebase.google.com/docs/storage/web/create-reference

so regular expression should be updated to include all valid unicode characters expect the restricted characters.

**Comment by rostopira** [comment]
I've looked into android sdk source, and url parsing logic is much complicated there.

I think this part should be completely rewritten to match this implementation: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-storage/src/main/java/com/google/firebase/storage/internal/Util.java#L81

**Comment by haashem** [comment]
iOS Version is more readable and simpler:

https://github.com/firebase/firebase-ios-sdk/blob/2f457c268de531af287571a892941c59c9ed09e5/FirebaseStorage/Sources/FIRStoragePath.m#L56

**Comment by markusaksli-nc** [comment]
I think this should be considered the same issue as https://github.com/FirebaseExtended/flutterfire/issues/5965 since the root cause is pretty much the same.

As some of the discussion here is useful to clarify the mentioned issue could you comment there as well?
