### ISSUE TITLE
[cloud_firestore], [cloud_firestore_web] QueryDocumentSnapshot class missing in CHANGELOG.md

### ISSUE THREAD

**Issue by arnaudelub** [FirebaseExtended/flutterfire#6059]
I know that `QueryDocumentSnapshot implements DocumentSnapshot` so the breaking refactor for `DocumentSnapshot` in ^2.0.0 imply `QueryDocumentSnapshot` but maybe it should be listed as well in the **BREAKING REFACTOR** part of the CHANGELOG.md:
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/CHANGELOG.md
and
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md

**Comment by Arnold2381** [comment]
Can I take this up?

**Comment by arnaudelub** [comment]
I am ready to PR, i am just waiting for their answer, if it's what you mean

**Comment by Arnold2381** [comment]
Oh okay!

**Comment by Salakar** [comment]
cc @rrousselGit
