### ISSUE TITLE
🐛 [Firebase Messaging] getInitialMessage returns Null in iOS Terminated mode 

### ISSUE THREAD

**Issue by mustafa-707** [FirebaseExtended/flutterfire#6067]
## Bug report

Hello , i'm using firebase_messaging in my current project  in android the message is not null, but in iOS, the message is null, i was following flutterfire step-by-step with version 

`Firebase Messaging : ^8.0.0-dev.15`
and `flutter version 1.66.2`

the problem was already there and i was in this issue facing same problem :

# the closed issue 
Closing based on https://github.com/FirebaseExtended/flutterfire/issues/5706#issuecomment-832163575

Closing based on https://github.com/FirebaseExtended/flutterfire/issues/5706#issuecomment-832163575

_Originally posted by @markusaksli-nc in https://github.com/FirebaseExtended/flutterfire/issues/5706#issuecomment-832595512_

after confirming the problem was fixed by `flutter 2` and `Firebase Messaging : ^9.1.3`

i tried to convert my project and implement the new versions for all plugins , But sadly the problem still happens , and when dealing with iOS (real device - iphone 6s plus and iphone X) still facing the problem which it `getInitialMessage`  return null when open notification  while app terminated 

# my code 

i call this in main.dart after iniat. firebase core 

```
_firebaseMessaging.getInitialMessage()
        .then((RemoteMessage message) {
      print("init message");
      if (message != null) {
        print("init not null message");
      }
    });
    
 ```

please let me know if any one facing same problem , and I'm ready to give more information to fix this issue 

Thanks alot

**Comment by markusaksli-nc** [comment]
Hi @mustafa-707 
What do you mean exactly here? Is it that when you open the terminated app with the notification you are not getting the print? Logs are not printed in a release build or after terminating the app on iOS so I'm not sure how exactly you are checking for this.

Could you try running the official example? It should navigate to a notification screen if the initial notification is not null (in `initState`). 
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
I just checked this on a real iPhone 7 with `firebase_messaging: ^9.1.3` and it works as expected.
Thank you
Thank you

**Comment by mustafa-707** [comment]
Im using the iOS device console to check logs while in terminated mode the it prints with null after press on notification in terminated mode , i will check example and re build it after clean everything but already run it much times , idk if it a cache related problem , thank you

**Comment by mustafa-707** [comment]
Same thing after cleaning everything , even with the example all i got is null by getInitialMessage , also i tried to define it in deferent places and same issue happens , i'm calling it in my main.dart , and i give all permissions and background process  , background fetch and remote notification is granted with Xcode 

this is the dependencies in my project :

```
  firebase_crashlytics: ^2.0.2
  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  firebase_messaging: ^9.1.3

```
and this's the block of code  :
```
  void initState() {
    SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitDown,
    DeviceOrientation.portraitUp,]);
    Analytics.trackAppOpen();
    Analytics.trackScreenView(AnalyticsConstants.splashScreen);
    super.initState();
      FirebaseMessaging.instance.getInitialMessage().then((RemoteMessage message) {
        print("------> Firebase ------> payload  : $message"); // this prints null every time after comeback from terminated mode notification
      if (message != null) {
         CloudMessaging.handleOnBackground(message);  // this will route depend on data -> type
      }
    });

  }

```

and again its working good with android , but this all what happens all in iOS only

**Comment by markusaksli-nc** [comment]
Are there any errors logged for the process in the device logs that would point to a cause?

**Comment by mustafa-707** [comment]
no , just null

**Comment by mustafa-707** [comment]
yes it's work fine with foreground using `onMessage` and background using `onBackgroundMessage`

**Comment by mustafa-707** [comment]
still returning nulls `getInitialMessage`  after testing it on iOS 14 and 12,4 with new updates
```
  firebase_messaging: ^10.0.0

```
and flutter 2.2.0-stable

**Comment by mustafa-707** [comment]
still returning nulls `getInitialMessage`  after testing it on iOS 14 and iOS 12 with new updates
```
  firebase_messaging: ^10.0.2

```
and flutter 2.2.2-stable

**Comment by supidupicoder** [comment]
same issue here

**Comment by timohtey** [comment]
Same issue here

**Comment by mustafa-707** [comment]
finally solved by removing a plugin named `flutter_apns` also i checked removed an iOS <key> named `FirebaseAppdelegateProxyEnable` and now the `getInitialMessage` works as well as android on iOS
