### ISSUE TITLE
🐛 [remote_config] Web support

### ISSUE THREAD

**Issue by bounty1342** [FirebaseExtended/flutterfire#6085]
Hi,

Currently there is no support for Flutter Web.

Remote Config is a Key firebase feature that should be cross platform supported.

Issue https://github.com/FirebaseExtended/flutterfire/issues/2115 has been closed over a year now, but still no support and no ETA.

Regards

**Comment by Salakar** [comment]
> Issue #2115 has been closed over a year now, but still no support and no ETA.

It's closed in favour of the feature discussion here: https://github.com/FirebaseExtended/flutterfire/discussions/5593

**Comment by bounty1342** [comment]
Fair enough, unfortunately after 2 months, there is no answer on the discussion thread you mention.

**Comment by PlugFox** [comment]
@bounty1342 

Checkout my implementation:
https://gist.github.com/PlugFox/9e6b16890deacd0ae4855dae3491a149
