### ISSUE TITLE
[all] Flutter plugins assume that there will be an Activity available at registration

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#61]
If [android_alarm_manager](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager) is being used, it will try to register all plugins at `Application.onCreate`, right?

If so, [cloud_firestore](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L80), [firebase_database](https://github.com/flutter/plugins/blob/master/packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java#L55) and [in_app_purchase](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java#L73) will get a null reference to the activity, right?

**Comment by BugsBunnyBR** [comment]
duplicated https://github.com/FirebaseExtended/flutterfire/issues/19

**Comment by iapicca** [comment]
Hello @kroikie 
is this issue still meant to be open?

**Comment by kroikie** [comment]
No looks like we can close this since it is a dup of #19
