### ISSUE TITLE
FlutterFire plugins do mostly not support non-default firebase apps.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#611]
Hey, my plan was to make a Firebase debug project, which get's automatically used when being in debug mode with the help of `firebase_core`.
It should've gone something like this:
```dart
  final FirebaseOptions options = const FirebaseOptions(
    projectID: "****-debug",
    googleAppID: "1:36*******:android:**********",
    apiKey: "AIza***********************************",
    gcmSenderID: '29********' 
  );

    final FirebaseApp app = await FirebaseApp.configure(
      name: "****-debug",
      options: options,
    );

    Firestore firestore = Firestore(app: app);
    FirebaseAuth firebaseAuth = FirebaseAuth(app: app); //Not supported
    ....
    ....
```
I noticed that except a few plugins most don't support non-default FirebaseApps.
Supporting this would be a benefit, as there can be programmatically swichting between several Firebase projects without moving files.

### Plugins **not** supporting non-default FirebaseApps:
_Note: I mostly looked through the API-Docs, as I don't use all plugins in production:_

- [X] firebase_auth
- [ ] firebase_messaging
- [ ] firebase_analytics
- [ ] firebase_dynamic_links
- [ ] firebase_ml_vision
- [ ] firebase_performance
- [ ] firebase_remote_config
- [ ] cloud_functions

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/541
https://github.com/FirebaseExtended/flutterfire/issues/428
