### ISSUE TITLE
[firebase_storage] retrying failed upload

### ISSUE THREAD

**Issue by jamesdixon** [FirebaseExtended/flutterfire#6126]
Hi, is there a way to manually retry an upload if the maximum number of retries has been reached?

**Comment by Ehesp** [comment]
You should catch any errors with the code `storage/retry-limit-exceeded`, and then trigger your logic again. You can see a list of errors here: https://firebase.google.com/docs/storage/web/handle-errors

**Comment by jamesdixon** [comment]
Thanks, Elliot! I suppose I was looking for built-in API to handle it. Since we already have an `UploadTask`, it seems natural that we'd be able to call something like `retry()` on that task. Is there any sort of technical barrier in enabling something like that?
