### ISSUE TITLE
[📚] Firebase Messaging Handling Interaction example raises exception

### ISSUE THREAD

**Issue by Coronon** [FirebaseExtended/flutterfire#6134]
The [provided example ](https://firebase.flutter.dev/docs/messaging/notifications#handling-interaction) raises an exception as the `State.initState()` must be a void method without an 'async' keyword. The documentation should rather call another async function from within the `State.initState()` method.

![FlutterfireAsyncInitState](https://user-images.githubusercontent.com/33808743/118150300-affdf800-b412-11eb-8cb7-aed250d10de3.PNG)

**Comment by russellwheatley** [comment]
closed due to PR fix: https://github.com/FirebaseExtended/flutterfire/pull/6136
