### ISSUE TITLE
[📚] Firebase Messaging Handling Interaction example raises exception (2)

### ISSUE THREAD

**Issue by Coronon** [FirebaseExtended/flutterfire#6135]
The [provided example ](https://firebase.flutter.dev/docs/messaging/notifications#handling-interaction) can raise an exception as `null` can not be converted to a boolean (This bug should happen here). If `initialMessage` is `null` dart still attempts to access the field ['type'] of `null` (This bug actually happens) as dart seems to iterprets the following code:
```dart
initialMessage?.data['type'] == 'chat'
```
as
```dart
(initialMessage?.data)['type'] == 'chat'
```
and therefore errors with "NoSuchMethodError: The method '[]' was called on null." when `initialMessage` is `null`.

Even if this code would not try to access ['type'] (as one might expect) it is still exception prone as it would evaluate to `null` either way which can not be used inside an if.

The documentation states that the message must contain a data field with key 'type' but this would crash when the app is started without the interaction assumed here (normally opened)

**Comment by russellwheatley** [comment]
closed due to PR fix: https://github.com/FirebaseExtended/flutterfire/pull/6136
