### ISSUE TITLE
🐛 [firebase_messaging] setting onBackgroundMessage handler triggers app rebuild

### ISSUE THREAD

**Issue by jonbhanson** [FirebaseExtended/flutterfire#6137]
## Bug report

**Describe the bug**
When the onBackgroundMessage handler is set in Android, it triggers a rebuild of the entire app.

### Steps to reproduce

1. Open the attached example app.
2. Run the app and once it loads observe that the 'Building app...' message appears in the debugger console.  This message is displayed when the app widget is built. Hit the + button, which sets the background message handler and observe that the 'Building app...' message appears again, showing that setting the handler triggered a complete rebuild of the app.

### Expected behavior

The background message handler can be set without rebuilding the app.

### Sample project

[example.zip](https://github.com/FirebaseExtended/flutterfire/files/6474446/example.zip)

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4
example 1.0.0+1

dependencies:
- cupertino_icons 1.0.3
- firebase_messaging 9.1.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core 1.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.0.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @jonbhanson 
Stateful widgets are designed (and expected) to rebuild arbitrarily at runtime.
We do not control this behavior and as such this isn't really an issue with this plugin.
Thank you

**Comment by jonbhanson** [comment]
@markusaksli-nc I understand that widgets are expected to rebuild.  However, it seems troubling that an action from a plugin triggers the rebuilding of the entire app.  I haven't seen any other widget do that, and it makes me wonder if it is a sign that something should be done differently that would not trigger this side-effect?
