### ISSUE TITLE
🐛 [firestore] native error not bubbling

### ISSUE THREAD

**Issue by cedvdb** [FirebaseExtended/flutterfire#6139]
Some errors from native are not bubbling correctly to flutter / dart.

```
  @override
  Stream<T?> watchOneOfUser() {
    return colRef
        .where('createdBy', isEqualTo: _authRepository.authUser?.id)
        .limit(1)
        .snapshots()
        .map(converter.oneFromSnapshot)
        .doOnData((data) => Log.api.i('watch one of user $collection: $data'))
        .doOnError((e, st) => _handleError(e, 'watchOneOfUser'));
  }
```

`doOnError` here is never called, while the `doOnData` receives null.

The console output:

`W/Firestore(28460): (22.1.2) [Firestore]: Listen for Query(target=Query(users order by __name__);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}`

**Comment by rrousselGit** [comment]
I have tried quite a few things but I am unable to reproduce the issue.

Could you share a [minimalist, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by cedvdb** [comment]
Just letting you know that I didn't forget this, I'm busy with something right now but will try to find reproductible steps after I've finished my tasks.

**Comment by cedvdb** [comment]
Just letting you know that I didn't forget this and will try to find reproductible steps when I'm done with my current tasks
