### ISSUE TITLE
docs: Misleading example using withConverter

### ISSUE THREAD

**Issue by difelice** [FirebaseExtended/flutterfire#6156]
In **Firestore** recent documentation addition about Type Safety, the example under the "Typing CollectionReference and DocumentReference" section is misleading and throws an error.

This is what the example shows:
```dart
List<Movie> movies = await moviesRef
      .where('genre', isEqualTo: 'Sci-fi')
      .get()
      .then((snapshot) => snapshot.docs);
```

Following the full example setup, adding model `Movie` and `withConverter`, that snippets throws the following error:
```console
Exception has occurred.
_TypeError (type 'List<QueryDocumentSnapshot<dynamic>>' is not a subtype of type 'List<Movie>')
```

The following example for single document works as expected. Now, I'm not sure how `withConverter` is supposed to work for the above scenario. Replicating the single result code doesn't seem to help either:

```diff
List<Movie> movies = await moviesRef
      .where('genre', isEqualTo: 'Sci-fi')
      .get()
-     .then((snapshot) => snapshot.docs);
+     .then((snapshot) => snapshot.docs.map((doc) => doc.data()).toList());
```

The snapshot doesn't seem to honor `withConverter` for multiple documents:
```console
Exception has occurred.
_TypeError (type 'List<dynamic>' is not a subtype of type 'List<Movie>')
```

I hope all that makes sense. Thanks.

# Update

Fixing the snippet with proper casting on `map` works as expected 😅 :
```diff
List<Movie> movies = await moviesRef
      .where('genre', isEqualTo: 'Sci-fi')
      .get()
-     .then((snapshot) => snapshot.docs);
+     .then((snapshot) => snapshot.docs.map<Movie>((doc) => doc.data() as Movie).toList());
```

**Comment by difelice** [comment]
@rrousselGit ☝️ I'm not sure if the above was fixed already or if it is a legit issue. Thanks.

**Comment by larssn** [comment]
I'm hoping this works without the cast?

I'm referring to the cast in: `.then((snapshot) => snapshot.docs.map<Movie>((doc) => doc.data() as Movie).toList());`

**Comment by rrousselGit** [comment]
The cast isn't needed

**Comment by difelice** [comment]
> The cast isn't needed

Can you please confirm? The following snippet throws on my end:
```dart
List<Movie> movies = await moviesRef
      .where('genre', isEqualTo: 'Sci-fi')
      .get()
     .then((snapshot) => snapshot.docs.map<Movie>((doc) => doc.data()).toList());
```

```console
Exception has occurred.
_TypeError (type '(dynamic) => dynamic' is not a subtype of type '(QueryDocumentSnapshot<dynamic>) => Movie' of 'f')
```
Thanks.
