### ISSUE TITLE
Flutter App crashed when try to get FCM Token using Firebase messaging 9.1.4 version Flutter v2.0.6

### ISSUE THREAD

**Issue by AkshayDilod** [FirebaseExtended/flutterfire#6159]
PS D:\Flutter\uberdriver> flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\aksha\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\aksha\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\aksha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

## Bug report

debug console

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.Metadata" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ad.uberdriver-J39PFP_gLfa4AZplLRH1gw==/base.apk"],nativeLibraryDirectories=[/data/app/com.ad.uberdriver-J39PFP_gLfa4AZplLRH1gw==/lib/arm64, /data/app/com.ad.uberdriver-J39PFP_gLfa4AZplLRH1gw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

package used 

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_database: ^6.1.2
  fluttertoast: ^8.0.6
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  location: ^4.1.1
  provider: ^5.0.0
  http: ^0.13.3
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^9.0.0
  animated_text_kit: ^4.2.1
  flutter_geofire: ^2.0.0
  firebase_messaging: ^9.1.4
  flutter_local_notifications: ^5.0.0+4
  firebase_analytics: ^8.0.4

App-level Gradle 

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle" 

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:28.0.1')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-messaging'
}

the method called for to get FCM token

`Future<String> getToken() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;

    String token = await messaging.getToken(
      vapidKey:
          'Web Push certificatation key',
    );
    return token;
  }`

**Comment by PrinceThakur007** [comment]
i am also facing similar problem

**Comment by markusaksli-nc** [comment]
Hi @AkshayDilod 
Does the issue persist if you remove the gradle firebase dependencies?
Could you paste the full error logs and mention what device this happens on?
Thank you

**Comment by AkshayDilod** [comment]
> Hi @AkshayDilod
> Does the issue persist if you remove the gradle firebase dependencies?
> Could you paste the full error logs and mention what device this happens on?
> Thank you

I am using Honor 8 pro android device.

Launching lib\main.dart on DUK L09 in debug mode...
lib\main.dart:1
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:55876/9uUonKseLiA=/ws
I/FLTFireBGExecutor(24192): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
I/FLTFireMsgService(24192): FlutterFirebaseMessagingBackgroundService started!
E/AndroidRuntime(24192): FATAL EXCEPTION: pool-15-thread-1
E/AndroidRuntime(24192): Process: com.example.notificationttest, PID: 24192
E/AndroidRuntime(24192): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/Metadata;
E/AndroidRuntime(24192): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.lambda$getToken$1$FlutterFirebaseMessagingPlugin(FlutterFirebaseMessagingPlugin.java:165)
E/AndroidRuntime(24192): 	at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingPlugin$CIEVVSZZupyLaxqSu4HKcRkuppw.call(Unknown Source:4)
E/AndroidRuntime(24192): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/AndroidRuntime(24192): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(24192): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(24192): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(24192): 	at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(24192): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.Metadata" on path: DexPathList[[zip file "/data/app/com.example.notificationttest-CXPU92wiJGxG-JPxLYg2UQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.notificationttest-CXPU92wiJGxG-JPxLYg2UQ==/lib/arm64, /data/app/com.example.notificationttest-CXPU92wiJGxG-JPxLYg2UQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
E/AndroidRuntime(24192): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(24192): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(24192): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(24192): 	... 7 more
D/ZrHung.AppEyeUiProbe(24192): stop checker.
I/Process (24192): Sending signal. PID: 24192 SIG: 9
Lost connection to device.

**Comment by markusaksli-nc** [comment]
Could you provide your `android/build.gradle`?

**Comment by markusaksli-nc** [comment]
Your `android/build.gradle`, not your `android/app/build.gradle`.

**Comment by AkshayDilod** [comment]
> Your `android/build.gradle`, not your `android/app/build.gradle`.

sorry sir it's my fault send the app build,gradle.

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.8'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by PrinceThakur007** [comment]
@AkshayDilod  i have find a fix as we are using "com.google.firebase:firebase-bom:28.0.1" i think there is problem in this bom version and i tried with com.google.firebase:firebase-bom:27.0.0 and it works perfectly

**Comment by AkshayDilod** [comment]
@PrinceThakur007 
solution given by Mr. @PrinceThakur007 
i have find a fix as we are using "com.google.firebase:firebase-bom:28.0.1" i think there is problem in this bom version and i tried with com.google.firebase:firebase-bom:27.0.0 and it works perfectly
this bom is present in app/build.gradle

**Comment by markusaksli-nc** [comment]
Is there a reason for all of this native setup? The firebase packages set their native versions internally so this should not be necessary and will lead to issues like this. 
The last time this issue was opened it was being caused by setting `classpath 'com.google.gms:google-services:4.3.8'` in `android/build.gradle`.

I would recommend you just follow the tested versions in the official documentation and avoid setting your own native versions if possible.

https://firebase.flutter.dev/docs/installation/android

**Comment by PrinceThakur007** [comment]
@markusaksli-nc  when we intialize projrct in the firebase google gives us a bom version implementation platform('com.google.firebase:firebase-bom:28.0.1') which case this problem.

**Comment by markusaksli-nc** [comment]
For future reference keep in mind that the setup provided in Firebase Console is only meant for the native Firebase SDKs and isn't really suitable for Flutter. The documentation website I mentioned contains the whole setup procedure for the FlutterFire packages in a Flutter project.
