### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by richard457** [FirebaseExtended/flutterfire#6166]
is there a plan to support windows?

**Comment by richard457** [comment]
Plugin for firestore and authentication

**Comment by markusaksli-nc** [comment]
Hi @richard457 
This repository only wraps the Firebase SDKs so they can be used with Flutter. Platform support or developing new SDKs is up to the Firebase team, not us. Until they decide to develop a Firebase Windows SDK or Firebase pure Dart SDK, we won't be able to implement it. 
Currently the closest thing is Firebase for C++ however see https://github.com/FirebaseExtended/flutterfire/issues/3243#issuecomment-821123878. Once there is a rigorously supported Firebase desktop workflow it can probably be piped through `dart:ffi` (or if they decide to make a pure Dart Firebase SDK).

This request is better suited for https://firebase.google.com/support/troubleshooter/report/features until then.
Thank you
