### ISSUE TITLE
🐛 [flutter_performance] newTrace doesn't sanitize input, and crashes the whole application

### ISSUE THREAD

**Issue by steeling** [FirebaseExtended/flutterfire#6168]
## Bug report

**Describe the bug**
flutter perfomance newTrace crashes when passed the empty string

### Steps to reproduce

    final Trace myTrace = FirebasePerformance.instance.newTrace("");

### Expected behavior

Throw an error, don't crash the whole app.

---

## Additional context
 
 The rest of the template is really overkill for how simply described this issue is
---

**Comment by markusaksli-nc** [comment]
The reason the template requires you submit your `flutter doctor -v` and `flutter pub deps -- --style=compact` is because we have no idea what version of the plugin on which version of flutter causes the issue on which device with which OS version. It's also unclear what is causing the error without a full log or stack trace.

Running this on Android with `firebase_performance: ^0.7.0+2` doesn't cause any issue. Please provide the missing information.

**Comment by steeling** [comment]
Gotcha. This was done on the iOS simulator.

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/steeling/dev/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 215D06F4-6E9A-48E5-B28C-87B9A6E07B6B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 2 categories.



snippet from pubspec.lock: 

  firebase_performance:
    dependency: "direct main"
    description:
      name: firebase_performance
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.0+2"

**Comment by darshankawar** [comment]
@steeling 
Can you provide the crash log you get ?
