### ISSUE TITLE
FieldPath

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#617]
i think  FieldPath is missing in flutter firrestore, so please i think its an important thing that should not be left out the current stage of flutter. thanks

**Comment by kroikie** [comment]
@rayjadore

The issue at https://github.com/flutter/flutter/issues/22849 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
https://stackoverflow.com/a/52469844
