### ISSUE TITLE
🐛 [firebase_storage] XMLHttpRequest error is thrown while invoking getData in firebase_storage web plugin 

### ISSUE THREAD

**Issue by dillibabun** [FirebaseExtended/flutterfire#6172]
I'm trying to download the PDF from firebase storage where I have set the rules as
![image](https://user-images.githubusercontent.com/34679378/118605452-edc49d00-b7d3-11eb-9fec-f5cc1a18347e.png)

This is working properly in Android and in Web, we are facing XMLHttpRequest error.

## Steps to Reproduce
```
import 'dart:typed_data';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    getBytes();
  }

  void getBytes() async {
    if(!kIsWeb)
    {await Firebase.initializeApp();}
    firebase_storage.FirebaseStorage storage =
    firebase_storage.FirebaseStorage.instanceFor(
        bucket: 'flutterfirebase-6c279.appspot.com');
    firebase_storage.Reference pdfRef = storage.
    refFromURL('https://firebasestorage.googleapis.com/v0/b/flutterfirebase-6c279.appspot.com/o/GIS.pdf?alt=media&token=51654170-c140-4ffa-ae1a-9fb431d0dee2');//ref('GIS.pdf');
    await pdfRef.getDownloadURL().then((value) => print(value));
    await pdfRef.getData(104857600).then((value) { //size mentioned here is max size to download from firebase.
      _pdfBytes = value;
      setState(() {});
    });
  }
  @override
  Widget build(BuildContext context) {
    Widget child = Center(child: CircularProgressIndicator());
    if (_pdfBytes != null) {
      child = SfPdfViewer.memory(_pdfBytes!,onDocumentLoaded: (details){
        print(details.document.pages.count);
      },onDocumentLoadFailed: (details){
        print(details.description);
      },);
    }
    return Scaffold(
        appBar: AppBar(
            title: Text('Syncfusion Flutter PDF Viewer')),
        body:
        child);
  }
}
```

**Expected results:** PDF must be downloaded and displayed properly.

**Actual results:** 
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:63135/NMQIodVZ2kM=/ws

 Running with sound null safety 
Debug service listening on ws://127.0.0.1:63135/NMQIodVZ2kM=/ws
https://firebasestorage.googleapis.com/v0/b/flutterfirebase-6c279.appspot.com/o/GIS.pdf?alt=media&token=51654170-c140-4ffa-ae1a-9fb431d0dee2
Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 71:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>


    at Object.createErrorWithStack (http://localhost:63054/dart_sdk.js:5044:12)
    at Object._rethrow (http://localhost:63054/dart_sdk.js:37476:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63054/dart_sdk.js:37472:13)
    at Object._microtaskLoop (http://localhost:63054/dart_sdk.js:37332:13)
    at _startMicrotaskLoop (http://localhost:63054/dart_sdk.js:37338:13)
    at http://localhost:63054/dart_sdk.js:33109:9

```
<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.0.6 at C:\f\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DilliBabuN\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\DilliBabuN\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\DilliBabuN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment]
Hi @dillibabun 
Please provide your `flutter pub deps -- --style=compact` and the web sdk imports you are using in `index.html`.
Does this happen with any random PDF? Have you tried getting other files?
Thank you

**Comment by dillibabun** [comment]
Hi @markusaksli-nc ,

Please find index.html.

`<!DOCTYPE html>
<html>
<head>
  
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="firebaseflutter_app">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>firebaseflutter_app</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="https://www.gstatic.com/firebasejs/8.6.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.0/firebase-storage.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.0/firebase-analytics.js"></script>
  <script>
    var firebaseConfig = {
      storageBucket: "flutterfirebase-6c279.appspot.com",
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
  
  <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
  <script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
`

and Dart SDK 2.12.3
Flutter SDK 2.0.6
firebaseflutter_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.3
- firebase_core 1.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.0.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- syncfusion_flutter_pdfviewer 19.1.63-beta [flutter vector_math async http syncfusion_flutter_pdfviewer_platform_interface syncfusion_flutter_pdfviewer_web syncfusion_flutter_core syncfusion_flutter_pdf]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed
_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.0.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.6 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- syncfusion_flutter_core 19.1.63 [vector_math flutter]
- syncfusion_flutter_pdf 19.1.63-beta [flutter intl xml syncfusion_flutter_core crypto convert]
- syncfusion_flutter_pdfviewer_platform_interface 19.1.63-beta [flutter plugin_platform_interface]
- syncfusion_flutter_pdfviewer_web 19.1.63-beta [flutter flutter_web_plugins js meta syncfusion_flutter_pdfviewer_platform_interface]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]

**Comment by dillibabun** [comment]
Hi @darshankawar ,

I have replaced pdfviewer widget with Text widget and issue is reproduced. Please find the modified codes below.

import 'dart:typed_data';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
//import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List? _pdfBytes;

  @override
  void initState() {
    super.initState();
    getBytes();
  }

  void getBytes() async {
    if(!kIsWeb)
    {await Firebase.initializeApp();}
    firebase_storage.FirebaseStorage storage =
    firebase_storage.FirebaseStorage.instanceFor(
        bucket: 'flutterfirebase-6c279.appspot.com');
    firebase_storage.Reference pdfRef = storage.
    refFromURL('https://firebasestorage.googleapis.com/v0/b/flutterfirebase-6c279.appspot.com/o/GIS.pdf?alt=media&token=51654170-c140-4ffa-ae1a-9fb431d0dee2');//ref('GIS.pdf');
    await pdfRef.getDownloadURL().then((value) => print(value));
    await pdfRef.getData(104857600).then((value) { //size mentioned here is max size to download from firebase.
      _pdfBytes = value;
      setState(() {});
    });
  }
  @override
  Widget build(BuildContext context) {
    Widget child = Center(child: CircularProgressIndicator());
    if (_pdfBytes != null) {
      child = Text(_pdfBytes!.length.toString());
      // SfPdfViewer.memory(_pdfBytes!,onDocumentLoaded: (details){
      //   print(details.document.pages.count);
      // },onDocumentLoadFailed: (details){
      //   print(details.description);
      // },);
    }
    return Scaffold(
        appBar: AppBar(
            title: Text('Syncfusion Flutter PDF Viewer')),
        body:
        child);
  }
}

**Comment by dillibabun** [comment]
@markusaksli-nc , is there any updates ?

**Comment by darshankawar** [comment]
Thanks for the updated code sample. Using it, I was able to replicate the issue as below:

```
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1613:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 155:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 707:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 736:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 533:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>


    at Object.createErrorWithStack (http://localhost:51252/dart_sdk.js:5050:12)
    at Object._rethrow (http://localhost:51252/dart_sdk.js:37641:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51252/dart_sdk.js:37637:13)
    at Object._microtaskLoop (http://localhost:51252/dart_sdk.js:37497:13)
    at _startMicrotaskLoop (http://localhost:51252/dart_sdk.js:37503:13)
    at http://localhost:51252/dart_sdk.js:33274:9
```

Also tried the `getData()` method on the plugin's example using which I get the same error as above.

`https://firebasestorage.googleapis.com/v0/b/triage-79c7c.appspot.com/o/playground%2Ftest.pdf?alt=media&token=92cc9aad-422a-46c9-9e6a-8fce31d32fe1`

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.


```

</details>

**Comment by dillibabun** [comment]
any updates on this ?

**Comment by russellwheatley** [comment]
Hey @dillibabun, I was able to recreate the bug, but it was fixed once I set CORS using this [methodology](https://firebase.google.com/docs/storage/web/download-files#cors_configuration)
