### ISSUE TITLE
🐛 [authentication] Firebase emulator gives error on phone auth: SMS verification code request failed: unknown status code: 17499 Cleartext HTTP traffic to 10.0.2.2 not permitted

### ISSUE THREAD

**Issue by cedvdb** [FirebaseExtended/flutterfire#6178]
When trying to authenticate with a **test number** through the **authentication emulator** I'm hit with this error:

`[authentication] emulator phone gives error: SMS verification code request failed: unknown status code: 17499 Cleartext HTTP traffic to 10.0.2.2 not permitted`

I'm not sure if this is supposed to be supported or not by this library but it seems like it's possible [on android](https://stackoverflow.com/questions/45932348/use-emulator-with-android-firebase-sms-authentication/50331596)

**Comment by cedvdb** [comment]
could be related to https://github.com/FirebaseExtended/flutterfire/issues/2792 
I'll try the fix there

**Comment by darshankawar** [comment]
@cedvdb 
Can you provide `flutter doctor -v`, `flutter pub deps -- --style=compact` ?
Maybe check this merged PR to know if it's supported or not. https://github.com/FirebaseExtended/flutterfire/pull/4263

**Comment by Salakar** [comment]
https://firebase.flutter.dev/docs/installation/android/#enabling-use-of-firebase-emulator-suite

**Comment by cedvdb** [comment]
@Salakar that fixes the original issue but the flow is still not the same as without emulator https://github.com/FirebaseExtended/flutterfire/issues/6178#issuecomment-843169696

Without emulator, even with test phone numbers the callback codeSent is called. With emulator it is not.

> If providing a test phone number to either the verifyPhoneNumber or signInWithPhoneNumber methods, no SMS will actually be sent. You can instead provide the test code directly to the PhoneAuthProvider or with signInWithPhoneNumbers confirmation result handler.
