### ISSUE TITLE
With flutter web reaching stable release, not clear which firebase plugins are supported

### ISSUE THREAD

**Issue by steeling** [FirebaseExtended/flutterfire#6183]
Just added https://pub.dev/packages/firebase_performance to my app, and then realized web isn't supported.

Might be nice to add a note to each of the pub.dev's on this, or link to a page that mentions what's supported on web.

**Comment by darshankawar** [comment]
@steeling 
If you look at flutterfire page, there's a list of Firebase plugins that are in stable and beta along with platforms supported by each. https://firebase.flutter.dev/

It shows `firebase_performance` is in beta and currently only supports mobile. Also, the pub.dev link you shared shows platforms it supports (Android, iOS):

<img width="549" alt="Screenshot 2021-05-19 at 12 30 53 PM" src="https://user-images.githubusercontent.com/67046386/118769704-1618ce00-b89e-11eb-97a3-d7ee202ef551.png">

Other firebase plugin if supports web, shows up as below (Android, iOS, MacOS, Web):

<img width="511" alt="Screenshot 2021-05-19 at 12 31 24 PM" src="https://user-images.githubusercontent.com/67046386/118769799-2df05200-b89e-11eb-9230-3773e249c88b.png">


Hope this answers your question. 
I am going ahead and closing this based on details shared above. If you disagree, write in comments and I'll reopen it.

Thanks.
