### ISSUE TITLE
[firebase_dynamic_links] Require latest CocoaPod to avoid iOS deprecated usage rejection 

### ISSUE THREAD

**Issue by collinjackson** [FirebaseExtended/flutterfire#62]
https://github.com/flutter/flutter/issues/39470

**Comment by chenna-reddy** [comment]
:alarm_clock:

**Comment by ali-thowfeek** [comment]
@collinjackson I wonder why isn't this fixed yet. A comment in `[firebase_dynamic_links]` plugin says that `UIWebView` is used in iOS 7 only. Since flutter only supports iOS 8 onwards i wonder why stick to it.

**Comment by ali-thowfeek** [comment]
Im sorry. I didn't know this was fixed last month. The title suggests that, but i totally missed it.

https://github.com/firebase/firebase-ios-sdk/commit/31d6a12d2be0340e448aed6cbcb27134f067d3ab
https://github.com/firebase/firebase-ios-sdk/pull/3723/commits/d7ad90c43430e887df737c9643b1e38aaa3eec83

I'm going to submit my app today. So, If I manually apply the diff of the above two commits, would I be able to bypass the warning? Or would it break something?

**Comment by Ehesp** [comment]
Closing this issue for now - looks like it has been resolved in updates from October 2019. Please let me know if it still an issue and I can reopen.
