### ISSUE TITLE
🐛 [firebase analytics] Missing homepage in doc - gives -10 on pub.dev score

### ISSUE THREAD

**Issue by neiljaywarner** [FirebaseExtended/flutterfire#6200]
pub.dev shows 0/10 points: Provide a valid pubspec.yaml
Homepage URL doesn't exist.
under "follow dart file conventions"

**Comment by rrousselGit** [comment]
It's likely that pub tried to reach the URL when the site was down for some reason.

The URL works now.

**Comment by darshankawar** [comment]
@neiljaywarner 
The score has been updated and homepage url is working now, as also confirmed by Remi above.
https://firebase.flutter.dev/docs/analytics/overview/ is accessible.

Closing this as resolved.

**Comment by neiljaywarner** [comment]
Thanks!

....sent from my phone
