### ISSUE TITLE
🐛 [firebase_analytics] Version 8.0.3 broken due to pod update

### ISSUE THREAD

**Issue by rmargolinross** [FirebaseExtended/flutterfire#6201]
## Bug report

**Describe the bug**
It seems that the pods referenced by firebase_analytics are not locked. This means when the ios pods are updated, they break older versions of the flutter package on ios without any changes from the user. Right now I am getting 

```
.../.pub-cache/hosted/pub.dartlang.org/firebase_analytics-8.0.3/ios/Classes/FLTFirebaseAnalyticsPlugin.m:49:19: error: no known class method for selector 'setScreenName:screenClass:'
        [FIRAnalytics setScreenName:screenName screenClass:screenClassOverride];
```

on my builds due to the Firebase_Analytics pod version going from 7.11.0 to 8.0.0

### Steps to reproduce

1. Install firebase_analytics 8.0.3 on a fresh project
2. Try and build said project on ios

### Expected behavior

It should work

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en-US)
    • Flutter version 2.2.0 at /Users/rmargolinross/dev/flutter
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rmargolinross/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • iPhone (mobile)         • 07da1517197bd6155d47de15a47759f492e42c8d • ios            • iOS 14.4.2
    • iPhone 12 mini (mobile) • AD9976D1-BE17-47E6-A37B-CB3E3A9F3FBD     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by do4Mother** [comment]
same issue can't build ios using firebase_analytics latest version

**Comment by juanagu** [comment]
Same error here #6209

**Comment by darshankawar** [comment]
@rmargolinross 
Tried the steps to replicate on plugin's repo using latest stable (2.2.0) with which I didn't get the issue.

<img width="1101" alt="Screenshot 2021-05-21 at 1 43 08 PM" src="https://user-images.githubusercontent.com/67046386/119105261-c28fb700-ba3a-11eb-9821-c5dcf10e8217.png">

Tried with 8.0.3 and latest 8.1.0.

Can you upgrade to [latest](https://pub.dev/packages/firebase_analytics/install) version and try again to see if it helps ?

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.


```

</details>

Also, if issue persists, can you provide your cocoapods version ?

**Comment by cadaniel** [comment]
> The latest stable works fine. The issue is that old versions should not be breaking randomly. It is frustrating when one day your build works fine, and the next day, through no change on your side, your build fails, because the plugin you used did not lock down their versioning system correctly.

Honestly this.. 

This is getting so frustrating to use firebase products that have working compatibility pulled from underneath.

**Comment by darshankawar** [comment]
Thanks for confirming and noted the behavior using compatibility with older versions when they are being upgraded to latest.
Keeping this open for further investigation and for a check on backward compatibility.

**Comment by saltatory** [comment]
I want to jump in. I'm having a similar issue. 

I'm using older versions of firebase_analytics and firebase_dynamic_links. I cannot upgrade because other packages I rely on including https://github.com/comigor/artemis rely on older versions of packages like http that firebase also relies upon.

firebase_dynamic_links: 2.0.6

... relies upon 

firebase_analytics: 7.1.1

both of which rely on the iOS Firebase SDK 8.0.0. You can see right in the release notes for 8.0.0 that the setScreenName method was removed.

I cannot compile my project now without removing Firebase Analytics which is exactly what I have to do. 

It sure would be nice to have a point-release of either the SDK or the flutter packages that resolved this issue. I am not personally in control of my dependencies and I'm not sure how quickly they will upgrade.

**Comment by RomanSoviak** [comment]
I just removed analytics, cause projects has many dependencies and I cannot update analytics:

```
Because firebase_analytics >=8.0.0 <8.0.4 depends on firebase_analytics_web ^0.3.0 which depends on firebase ^9.0.1, firebase_analytics >=8.0.0 <8.0.4 requires firebase ^9.0.1.
And because firebase >=9.0.0 depends on http ^0.13.0, firebase_analytics >=8.0.0 <8.0.4 requires http ^0.13.0.
So, because shulak_mobile depends on both http ^0.12.0+4 and firebase_analytics 8.0.3, version solving failed.
pub get failed (1; So, because shulak_mobile depends on both http ^0.12.0+4 and firebase_analytics 8.0.3, version solving failed.)
```

**Comment by russellwheatley** [comment]
If you wish to lock the underlying native SDK version, you will have to target a specific `firebase_core` package to the native package you wish (See [CHANGELOG](https://pub.dev/packages/firebase_core/changelog)) or you can manually override the native SDK version as documented [here](https://firebase.flutter.dev/docs/manual-installation#overriding-firebase-sdk-versions).
