### ISSUE TITLE
🐛 [firebase_analytics] Firebase iOS SDK 7.3.0 re-introduces iOS 9 support, deployment target still 10.0

### ISSUE THREAD

**Issue by davidlawson** [FirebaseExtended/flutterfire#6204]
## Bug report

The Firebase iOS SDK 7.3.0 re-introduces iOS 9 support, but the minimum deployment target for firebase_analytics is still 10.0.

Firebase iOS SDK issue: firebase/firebase-ios-sdk#6882

Related PR (for firebase_crashlytics): FirebaseExtended/flutterfire#4626

**Comment by darshankawar** [comment]
Leaving this issue open for further investigation.
