### ISSUE TITLE
Error on firebase_ml_vision could not find com.google.firebas:firebase-ml-vision.

### ISSUE THREAD

**Issue by AlexOliveira123** [FirebaseExtended/flutterfire#6215]
I'm having a problem with firebase_ml_vision.. Can anyone help?

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_ml_vision:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_ml_vision:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-ml-vision:.
     Required by:
         project :firebase_ml_vision

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by darshankawar** [comment]
@AlexOliveira123 
Check [this](https://github.com/FirebaseExtended/flutterfire/issues/5922#issuecomment-836758219) comment. 

Closing this per the comment linked above.
