### ISSUE TITLE
Not able to log event

### ISSUE THREAD

**Issue by mouryaavadhesh** [FirebaseExtended/flutterfire#6217]
[debug] Event 4f3a2dd63311402aa0f89ecc53da173d was sent successfully.

**Comment by darshankawar** [comment]
@mouryaavadhesh 
Can you elaborate on this issue ? What plugin are you referring to and what's the exact issue are you facing with it, including `flutter doctor -v` and a minimal reproducible code sample ?

**Comment by mouryaavadhesh** [comment]
@google-oss-bot Yes still not able to see GA standard event like add_to_cart, login? I have tried that event 1000+ time in real-time I can see on debugging view bug apart from that when I trigger the event with the release, still can't see the standard event. Help me with that.
