### ISSUE TITLE
[cloud_firestore] Storing map data in array list

### ISSUE THREAD

**Issue by zekielkatmis** [FirebaseExtended/flutterfire#6222]
I try to make an app about health blog with Flutter. I want to store some data with arrays that contain map data. Although I can manually perform this on the Firestore, I'm getting some errors in coding.

Here is the Firestore screenshot.

![jC2hC](https://user-images.githubusercontent.com/61638692/119278857-a6ee0180-bc30-11eb-97c2-2871c8d6b520.png)

Here is the code which I try to add map data to the array.

`Future<bool> updateUserCases(String userId, Map newCase) async { await _firestoreDB.collection("users").doc(userId).update({ "userCases" : FieldValue.arrayUnion([newCase]) }); return true;`

I can add my map data to Firestore, but when I try to add it to the array, I get this error.

> E/flutter (10661): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/unknown] Invalid data. FieldValue.serverTimestamp() can only be used with set() and update()

Also I use latest version every package in my project. Could you help if there is a way I can fix this problem? Thank you.

**Comment by darshankawar** [comment]
@zekielkatmis 
I think StackOverflow is a better platform to ask solution for this problem. Please see https://flutter.dev/community for resources.
Closing from here as this doesn't sound like a bug. If you disagree or think this is a limitation of the plugin and would like to ask as a feature request, write in comments and I'll reopen it.

Thanks.
