### ISSUE TITLE
firebase_analytics Plugin using able to get custom events and other events for android on firebase but issue is adding every related material for IOS Mobile App and also on AppStore not getting any Data related to IOS.

### ISSUE THREAD

**Issue by marslannasr7koncepts** [FirebaseExtended/flutterfire#6226]
Even using Plugin and analytics related SDK added for IOS but still not showing any Data on Firebase Console instead of for Android it's showing accurately either Custom events or default events even other detail too.

**Comment by darshankawar** [comment]
@marslannasr7koncepts 
Can you provide `flutter doctor -v`, `flutter pub deps -- --style=compact` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows the issue you are facing ?
