### ISSUE TITLE
Firebase.initializeApp crashes on restarting flutter app - caused by using FirebaseAuth

### ISSUE THREAD

**Issue by biancashouse** [FirebaseExtended/flutterfire#6236]
if you run this code once, then restart it, the initializeApp will crash it:

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  FirebaseApp? app;

  try {
    app = await Firebase.initializeApp();
    var user = FirebaseAuth.instance.currentUser;
    print(user?.email);
  } on FirebaseException catch (e) {
    print(e.code);
  }

  print(app?.name);
}

```
iOS Simulator
versions:
...
  firebase_core: ^1.1.0
  firebase_auth: any
  firebase_storage: 8.0.0
  cloud_firestore: 2.2.0
...

**Comment by biancashouse** [comment]
After noticing the 'any' version on auth, I updated both core and auth to 1.2.0; the latest.
(My assumption was that :any in the yaml gets the very latest version).
Anyway, rerunning the above code twice now o.k.
Jeez lost a whole day trying to hunt this down.

**Comment by darshankawar** [comment]
@biancashouse 
I was about to suggest you to use the latest and greatest version of `core` and `auth` to see if issue still persists with it, but now looking at your above comment, the issue seems to have resolved ?

If so, can this be closed ?

**Comment by biancashouse** [comment]
Answer is indeed to use most recent versions of core and auth.

**Comment by biancashouse** [comment]
Yes, apologies, I should have closed it on finding that it was due to not
using the correct versions. Closed now. Many thanks.
