### ISSUE TITLE
Is Firebase available in mainland China

### ISSUE THREAD

**Issue by lesliebigfans** [FirebaseExtended/flutterfire#6239]
Is Firebase available in mainland China

**Comment by darshankawar** [comment]
@lesliebigfans 
This isn't in the control of flutterfire maintainers. You'll need to ask this question in firebase support: https://firebase.google.com/support/troubleshooter/contact

Also check this SO link for further reference.https://stackoverflow.com/questions/42605566/can-firebase-be-used-as-a-database-in-china-now

Closing from here.
