### ISSUE TITLE
🐛 [firebase_crashlytics] alternatives to crashlytics for flutter web?

### ISSUE THREAD

**Issue by sabetAI** [FirebaseExtended/flutterfire#6244]
Flutter web support for firebase crashlytics is listed as ["N/A"](https://firebase.flutter.dev/). What's the reasoning behind this and are there alternatives that support flutter web?

**Comment by darshankawar** [comment]
@sabetAI 
Flutterfire can't bridge web support as no underlying SDK exists. You may upvote [this](https://github.com/firebase/firebase-js-sdk/issues/710) issue and / or file a feature request in firebase sdk: https://firebase.google.com/support/troubleshooter/report/features

Closing from here.
