### ISSUE TITLE
[📚] [cloud_firestore] Please document how to mock cloud_firestore with e.g. Mockito

### ISSUE THREAD

**Issue by eggnstone** [FirebaseExtended/flutterfire#6250]
After the changes (withConverter) introduced with cloud_firestore v2.0.0 I cannot using mocking with Mockito anymore.
Please document how to properly mock with cloud_firestore.

**Comment by rrousselGit** [comment]
What is your issue with mockito?

**Comment by eggnstone** [comment]
Please see https://github.com/dart-lang/mockito/issues/338#issuecomment-848371915 and below.

As of Mockito 5.0.9 it is possible (again) to mock e.g. `DocumentReference<T>`.
It was not possible for a while because the `R withConverter<R>()` got introduced and that method returns an unknown type (R versus T).

I have troubles making my formerly working tests with firestore mocks to work again.
In the referenced issue you can see how I try to fix the mocking.
I assume I am not the only one using cloud_firestore and wanting to write proper tests, so it would be nice to give an example how to use mocking/mockito after the big 'withConverter' update.

**Comment by otopba** [comment]
Hi!
I use [fake_cloud_firestore](https://pub.dev/packages/fake_cloud_firestore). It's much easier than mocking a bunch of classes and methods

**Comment by Salakar** [comment]
We now have testing related documentation here: https://firebase.flutter.dev/docs/testing/testing

**Comment by russellwheatley** [comment]
Going to close this as we have testing documentation, and you could also use `fake_cloud_firestore` as mentioned above.
