### ISSUE TITLE
[firebase_dynamic_links: 2.0.4] FirebaseDynamicLinks.instance.onLink getting NULL

### ISSUE THREAD

**Issue by bhagyashreekhatri** [FirebaseExtended/flutterfire#6260]
Hie,

I am getting NULL in iOS (Only) the value of FirebaseDynamicLinks.instance.onLink() & FirebaseDynamicLinks.instance.getInitialLink(). Both are getting null. When tapped on deeplink my app is opening but the value of both the above functions i am getting null.

Here is my code:
---------pubspec.yaml-------------
dependencies:
  flutter:
    sdk: flutter

  firebase_dynamic_links: 2.0.4
  url_launcher: ^6.0.4
-------------------------------------------------------------

------------------------main.dart------------------------

@override
  void initState() {
    super.initState();
    initDynamicLinks();
  }

  Future<void> initDynamicLinks() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData? dynamicLink) async {
      final Uri? deepLink = dynamicLink?.link;
      print(deepLink);
      if (deepLink != null) {
        // ignore: unawaited_futures
        Navigator.pushNamed(context, deepLink.path);
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });

    final PendingDynamicLinkData? data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri? deepLink = data?.link;
    print(deepLink);
    if (deepLink != null) {
      // ignore: unawaited_futures
      Navigator.pushNamed(context, deepLink.path);
    }
  }

**Comment by darshankawar** [comment]
@bhagyashreekhatri 
Can you provide `flutter doctor -v` and `flutter pub deps -- --style=compact` ?

`When tapped on deeplink my app is opening but the value of both the above functions i am getting null.`

Is your app is foreground or in background or closed when you are tapping on deeplink ?

**Comment by bhagyashreekhatri** [comment]
I tried all the 3 scenario's in keeping an app in foreground, background and killed state as well. In all the scenarios its just opening the app via deeplink but getting null value for .onLink()

bellow is the response of  flutter pub deps -- --style=compact
Dart SDK 2.13.1
Flutter SDK 2.2.1
kiple 3.12.0+20000197

dependencies:
- badges 1.2.0 [flutter]
- barcode_flutter 1.1.2 [flutter]
- bubble_tab_indicator 0.1.4 [flutter]
- cached_network_image 2.5.1 [flutter flutter_cache_manager octo_image]
- camera 0.5.8+17 [flutter]
- connectivity 0.4.9+5 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cupertino_icons 1.0.0
- dart_ipify 1.0.2 [http]
- dartz 0.9.2
- date_format 1.0.9
- datetime_picker_formfield 1.0.0 [flutter intl]
- device_info 1.0.0 [flutter device_info_platform_interface]
- encrypt 4.1.0 [args asn1lib clock collection crypto pointycastle]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_dynamic_links 0.5.3 [flutter]
- firebase_messaging 8.0.0-dev.15 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- flustars 0.3.3 [flutter common_utils sp_util synchronized path_provider]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_datetime_picker 1.5.0 [flutter]
- flutter_expand_view 1.0.2 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_getuuid 0.0.1 [flutter]
- flutter_html 1.0.2 [html csslib css_colors video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_image_compress 0.7.0 [flutter]
- flutter_keyboard_visibility 4.0.6 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_local_notifications 3.0.3 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_luban 0.1.11 [flutter image]
- flutter_picker 1.1.5 [flutter]
- flutter_qr_reader 1.0.3 [flutter image_picker]
- flutter_screenutil 2.3.1 [flutter]
- flutter_social_content_share 0.0.4 [flutter]
- flutter_time_picker_spinner 1.0.6+1 [flutter]
- geocoding 1.0.5 [flutter geocoding_platform_interface url_launcher]
- get 3.26.0 [flutter]
- get_it 5.0.6 [async meta]
- get_version 0.2.2 [flutter package_info]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- local_auth 0.6.3+4 [flutter meta intl platform flutter_plugin_android_lifecycle]
- location 3.2.4 [flutter location_platform_interface location_web meta]
- marquee 1.7.0 [flutter fading_edge_scrollview]
- modal_progress_hud 0.1.3 [flutter]
- native_contact_picker 0.0.6 [flutter]
- native_device_orientation 0.3.0 [flutter]
- package_info 0.4.3+4 [flutter]
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- pin_code_fields 6.1.0 [flutter]
- provider 4.3.3 [collection flutter nested]
- pull_to_refresh 1.6.1 [flutter]
- qr_flutter 3.2.0 [flutter qr]
- rxdart 0.24.1
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- signalr_client 0.1.6 [flutter logging w3c_event_source]
- smooth_page_indicator 0.2.3 [flutter]
- string_validator 0.1.4
- timer_count_down 1.0.4+1 [flutter]
- uni_links 0.4.0 [flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]
- video_compress 2.1.1 [flutter]
- wakelock 0.1.4+2 [flutter]
- zendesk 2.0.0 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.8.1
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- chewie 0.9.10 [open_iconic_flutter video_player wakelock flutter]
- chewie_audio 1.0.0+1 [open_iconic_flutter video_player screen flutter]
- clock 1.1.0
- collection 1.15.0
- common_utils 1.2.4 [decimal crypto convert]
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- css_colors 1.0.2 [flutter]
- csslib 0.16.2 [source_span]
- decimal 0.3.5 [rational]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fading_edge_scrollview 1.1.4 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.6 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_keyboard_visibility_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 1.0.1 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geocoding_platform_interface 1.0.1+1 [flutter meta plugin_platform_interface]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- js 0.6.3
- location_platform_interface 1.1.0 [flutter meta plugin_platform_interface]
- location_web 1.0.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 0.0.4 [flutter]
- octo_image 0.3.0 [flutter flutter_blurhash]
- open_iconic_flutter 0.3.0 [flutter]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.1
- process 3.0.13 [file intl meta path platform]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- rational 0.3.8
- screen 0.0.5 [flutter]
- service_worker 0.2.4 [js]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sp_util 1.0.2 [flutter synchronized shared_preferences]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.3+3 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- w3c_event_source 1.3.2
- webview_flutter 0.3.24 [flutter]
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser] 

-----------------------------------------------------------
Below is the response of  flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.1 at /Users/bhagyashreehareshkathri/flutter
    • Framework revision 02c026b03c (3 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bhagyashreehareshkathri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

**Comment by darshankawar** [comment]
This seems to be a known issue on iOS and has an an open issue for tracking, https://github.com/FirebaseExtended/flutterfire/issues/1624
Please follow-up there for updates.
Closing this as duplicate.

**Comment by jbryanh** [comment]
I would like to point out that this issue #6260 experienced the issue when app was hot in background.  In issue #1624 , @blaneyneil says it's an uninstalled app that fails.  Different issues.
