### ISSUE TITLE
🐛 [firebase_messaging]  Cannot re-configure FirebaseApp default app

### ISSUE THREAD

**Issue by lironzemingo** [FirebaseExtended/flutterfire#6264]
I added firebase messaging to my Flutter project, with a certain Firebase project.
then it was decided that the app will be associated with a different Firebase account, and so I added the app to the new Firebase project, and removed it from the previous.
I replaced the google-services.json in the app, uninstalled and reinstalled. but when I call
` Firebase.initializeApp();`
the previous initialized app is returned (with the previous appId, projectID, etc).
`FirebaseMessaging.instance.getToken()`, and print the result. when I use the token to send a test-message from the console - it works when I send the message from the previous Firebase project, and not from the new.
I tried re-initializing the FirebaseApp with   
```
FirebaseOptions options = new FirebaseOptions.fromMap({
 'apiKey': '...',
     'appId': '...',
  'messagingSenderId': '...',
  'projectId': '...'
 });
Firebase.initializeApp('newApp', options);
```

but it doesn't work either.
What is happening here? is this a bug? How do I connect my app with thw new Firebase account?

**Comment by darshankawar** [comment]
@lironzemingo 
May be it's not recognizing the new google-services.json file which has new configuration.
Can you try to remove that file and run to see if it recognizes that the file is missing ?
If so, just try to clear all caches and run `flutter clean` to see if it helps.

Also, I'd suggest you to ask this question on support channel like StackOverflow with `firebase` tag to get help on it.

Closing from here as this doesn't seem to be a bug. If you disagree, write in comments and I'll reopen it.

Thanks.
