### ISSUE TITLE
🐛 CrashAnalytics iOS build fails with Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by sajanyamaha** [FirebaseExtended/flutterfire#6272]
```
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
          objc-class-ref in FIRCLSApplication.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
firebase_crashlytics: ^2.0.4
firebase_core: ^1.2.0
```
in XCode build phases
```
${PODS_ROOT}/FirebaseCrashlytics/run
input files , $(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
```
Xcode Version
`Version 12.4 (12D4e)`

in Podfile
```
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
```
Tried everything as explained in docs , build always fails with the above error , am i missing something ?

**Comment by darshankawar** [comment]
@sajanyamaha 
If you are running through Xcode, you are opening `Runner.xcworkspace` and then running right ?
Can you provide `flutter doctor -v` ?
Did you switch / change flutter channel and then tried to run which led to this error ?
Can you try to delete Podfile, Podfile.lock, Pods folder, Runner.xcworkspace, let flutter regenerate these files and check if it helps ?

**Comment by kmahyyg** [comment]
Same problem here for `arm64`.

Fully output of build log is:

![image](https://user-images.githubusercontent.com/16604643/120928203-38bc3b00-c716-11eb-9ce8-460adf1c4d77.png)

Flutter Doctor:

```
kmahyyg@Patricks-Mac ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at /Users/kmahyyg/devsdk/flutter
    • Framework revision 02c026b03c (10 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • <REDACTED>'s iPhone (mobile) • <REDACTED> • ios            • iOS 14.6
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 2 categories.

```

Also, there might be something to mention is that I followed all the instructions on the web site including change plist file and uncomment the platform line of `podfile` and set to ios 12.1, but there's always a warning says that my build target was set to 8.0:

The `Flutter.podspec` is always:
```
  s.ios.deployment_target = '8.0'
```

Flutter channel is always stable.

**Comment by kmahyyg** [comment]
I tried to delete `podfile` and all things you've mentioned above. Only build target error was fixed. The symbol in Crashlytics still is not found. I have to remove crashlytics now.

If I could have more information offered to help, It's my pleasure.

**Comment by kmahyyg** [comment]
@sajanyamaha 

```
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
``` 

I accidentally built the whole app fixing the problem which could not build `Firebase/Core`, I think which might be helpful to solve this issue. But I need more information.

Could you please attach the whole file of `Podfile` regenerated?

**Comment by sajanyamaha** [comment]
Actually the guidelines are a bit confusing for flutter users ,No need of any podfile edits ,
`Please note , the crashes are not intercepted in debug mode it seems .`

**Revert all changes , delete podfile.lock and Just follow these point-to-point**

1. From Xcode select Runner from the project navigation.
2. Select the Build Phases tab, then click + > New Run Script Phase.
3. Add ${PODS_ROOT}/FirebaseCrashlytics/run to the Type a script... text box.
4. Optionally you can also provide your app's built Info.plist location to the build phase's Input Files field: For example: $(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

Upload to Testflights , your firebase will now pick up the SDK .

**Comment by magicPiperS** [comment]
![BC97DF88-AF64-434C-8E5B-EF92345E6683](https://user-images.githubusercontent.com/84014488/120990452-27753c00-c7b3-11eb-9338-13808caf62e8.jpeg)

I guess we need to make these chars bold.
