### ISSUE TITLE
`Non-Image content-type returned` for embedded firebase storage urls?

### ISSUE THREAD

**Issue by sabetAI** [FirebaseExtended/flutterfire#6277]
I'm getting `Non-Image content-type returned` when embedding image links in my firebase storage generated by the `getDownloadURL()` method. For example, this error occurs with `![screenshot.png](...png)`. How can I fix this? Is this related to firebase or to how github reads embedded images?

Also I have read permissions allowed for non-auth reads in my firebase storage rules.

**Comment by darshankawar** [comment]
@sabetAI 
We are unable to see the screenshot you tried to link in the description, seems it didn't attach completely. 
Also, can you provide `flutter doctor -v` and version of storage plugin you are using ?

Can you also provide an example of embedding image link you are trying to download ?

**Comment by sabetAI** [comment]
`flutter doctor -v`

[√] Flutter (Channel master, 2.3.0-1.0.pre.172, on Microsoft Windows [Version 10.0.19043.985], locale en-CA)
    • Flutter version 2.3.0-1.0.pre.172 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3cbfe82d9d (5 weeks ago), 2021-04-29 16:47:42 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\alisa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.0-insider)
    • VS Code at C:\Users\alisa\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77        
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!

---

Link to example image:
https://firebasestorage.googleapis.com/v0/b/buildpronav.appspot.com/o/github-issues-screenshots%2Fba4f9be0-c161-11eb-8395-9dd94d401dd9.png?alt=media&token=e5d1f20f-8350-487e-ba08-ff3c9f375c7c,

![embed](https://firebasestorage.googleapis.com/v0/b/buildpronav.appspot.com/o/github-issues-screenshots%2Fba4f9be0-c161-11eb-8395-9dd94d401dd9.png?alt=media&token=e5d1f20f-8350-487e-ba08-ff3c9f375c7c)

**Comment by darshankawar** [comment]
@sabetAI 
Thanks for the details. I used the example image in plugin's repo [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and was able to upload and download the url properly without any issues.

<img width="304" alt="Screenshot 2021-06-01 at 1 56 52 PM" src="https://user-images.githubusercontent.com/67046386/120291831-5dad4a00-c2e1-11eb-87c7-0f3ae47b77e8.png">

<img width="350" alt="Screenshot 2021-06-01 at 1 59 04 PM" src="https://user-images.githubusercontent.com/67046386/120292060-92b99c80-c2e1-11eb-9447-effe115bdf14.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by sabetAI** [comment]
Cool, did you use this link https://firebasestorage.googleapis.com/v0/b/buildpronav.appspot.com/o/github-issues-screenshots%2Fba4f9be0-c161-11eb-8395-9dd94d401dd9.png?alt=media&token=e5d1f20f-8350-487e-ba08-ff3c9f375c7c directly, or re-upload and link it? I can find my firebase link in your post. Can you show the markdown/html you used to embed the image?

**Comment by darshankawar** [comment]
@sabetAI 
I used the image from the link you provided (that downloaded the png) and through plugin example app , uploaded it using `upload local file` and then downloaded the generated url.

<img width="334" alt="Screenshot 2021-06-02 at 12 36 18 PM" src="https://user-images.githubusercontent.com/67046386/120438551-269d6e00-c39f-11eb-9f16-1c1f7c087c1d.png">

I couldn't directly use your firebase link, maybe due to security rules, as it shows me below message:

`flutter: [firebase_storage/unauthorized] User is not authorized to perform the desired action.`

I tried below:

`firebase_storage.Reference ref = firebase_storage.FirebaseStorage.instance
        .refFromURL('https://firebasestorage.googleapis.com/v0/b/buildpronav.appspot.com/o/github-issues-screenshots%2Fba4f9be0-c161-11eb-8395-9dd94d401dd9.png?alt=media&token=e5d1f20f-8350-487e-ba08-ff3c9f375c7c')
        .child('playground')
        .child('/test.png');`

**Comment by sabetAI** [comment]
These are my storage rules:
```rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read; 
      allow write: if request.auth != null;
    }
  }
}
```
Is there a CORS header I'm missing somewhere?

**Comment by markusaksli-nc** [comment]
What do you mean by markdown/html? What exactly is your use case for using the download link?

**Comment by sabetAI** [comment]
Hi @markusaksli-nc, I've built a simple feedback api where a screenshot is taken and uploaded when the user presses the feedback button and adds a text description of their problem. I'm storing the screenshot in firebase storage, grabbing its download url with the `getDownloadURL()` method, then embedding that link in the text description using markdown/html ie `![screenshot.png](...png)`, which I upload to github as a new issue.

I've set my firebase storage rules to:
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read; 
      allow write: if request.auth != null;
    }
  }
}
```

but it appears @darshankawar is getting a `flutter: [firebase_storage/unauthorized] User is not authorized to perform the desired action.` error when accessing. In my own case I'm getting a `Non-Image content-type returned` when accessing the embedded link.

**Comment by markusaksli-nc** [comment]
Well in this case the plugin is actually working without any issues. The only problem seems to be on the embedding side where the markdown parser or HTML isn't recognizing the contents returned by the link. This isn't really an issue with the flutter implementation of Firebase storage but rather GitHub or the Firebase cloud storage backend.

I'm going to close the issue since this isn't really something we can fix but you can contact https://firebase.google.com/support or https://support.github.com/
