### ISSUE TITLE
🐛 [firebase_messaging] Android - small notification icon in the notification bar is a grey icon

### ISSUE THREAD

**Issue by aytunch** [FirebaseExtended/flutterfire#6281]
In iOS we have no such issue.
In Android, the App icon has no issue, however when a notification is received and being viewed in the notification tray, the icon is seen as a grey square.

This problem is seen currently on OnePlus 7T pro and OnePlus 6
On an older Samsung device (OS version unknown atm) displays the icon just fine.

![115574653-5a21ae80-a2b1-11eb-88e2-4b34f1ab573b](https://user-images.githubusercontent.com/6442915/120233874-65c4a580-c25f-11eb-92df-152b1404613a.png)

**Comment by darshankawar** [comment]
@aytunch 
Can you provide `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Are you using any plugin to display notification icons ?

Check if [this](https://stackoverflow.com/questions/54056662/firebase-notification-is-grey-flutter) SO link helps.

**Comment by piyush101** [comment]
I am facing same issue. Any updates?

**Comment by erkansahin** [comment]
I solved the problem using the solution below: 
https://github.com/flutter/flutter/issues/17941#issuecomment-412242466
