### ISSUE TITLE
[📚] [Cloud Firestore] Change all the cloud_firestore example with null_safety

### ISSUE THREAD

**Issue by TitusEfferian** [FirebaseExtended/flutterfire#6286]
flutter has announce [flutter 2.2](https://medium.com/flutter/announcing-flutter-2-2-at-google-i-o-2021-92f0fcbd7ef9) since the last google i/o, and Sound null safety is now the default for new projects. Most of our docs example still used legacy version of dart code. 

Instead of two seperated example (https://firebase.flutter.dev/docs/firestore/2.0.0_migration/) and (https://firebase.flutter.dev/docs/firestore/usage#one-time-read)

why don't we use null safety as the default docs and code snippet example?

**Comment by Salakar** [comment]
Related but for auth; #6308
