### ISSUE TITLE
Multifactor auth support

### ISSUE THREAD

**Issue by amitav13** [FirebaseExtended/flutterfire#6287]
Hi! 
We're migrating a native android app that uses [multifactor auth](https://cloud.google.com/identity-platform/docs/android/mfa) to flutter. I haven't been able to find any documentation on how to do this within the `auth` flutter sdk.  

1. Is this currently supported?
2. Is there any plan to support this? Or would we have to resort to native channel code for now?

**Comment by darshankawar** [comment]
@amitav13 
There's an open discussion thread on MFA, https://github.com/FirebaseExtended/flutterfire/discussions/2386
Please follow-up there for updates or you may comment in it to get more attention from the team.

Closing from here as a duplicate.
