### ISSUE TITLE
User? get user package:firebase_auth/firebase_auth.dart

### ISSUE THREAD

**Issue by InfinityCoder88** [FirebaseExtended/flutterfire#6295]
Hi friends,

I'm using **Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (6 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_database: ^7.0.0
**

I get this error with Firebase_auth:
```
User? get user
package:firebase_auth/firebase_auth.dart

Returns a [User] containing additional information and user specific methods.

A value of type 'User?' can't be assigned to a variable of type 'User'.
Try changing the type of the variable, or casting the right-hand type to 'User'.dart(invalid_assignment)
```
How can I fix this, thanks!
<img width="1249" alt="Screen Shot 2021-06-02 at 22 57 34" src="https://user-images.githubusercontent.com/6507433/120557971-a4409880-c3f6-11eb-9f67-c5ea250b8963.png">

**Comment by TitusEfferian** [comment]
you declared a variable with `User`, but the firebase auth returning a `User?` 
you may adjust the variable you declare with a null safety

**Comment by markusaksli-nc** [comment]
This is just a feature of nullsafety. You need to use a nullable type for user in this case.
