### ISSUE TITLE
firebase_admob warning message

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#631]
I just did copy and paste example code form `firebase_admob` plugin.
When I tapped `LOAD REWARDED VIDEO` console says this.

> <Google:HTML> You are currently using version 7.32.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
interstitial:didFailToReceiveAdWithError: No ad returned from any ad server. (MobileAd <FLTRewardedVideoAdWrapper: 0x6000013bb870> LOADING FLTRewardedVideoAdWrapper)

When I pressed `SHOW  REWARDED VIDEO`

> PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)

I literally didn't change anything. 

**Flutter doctor**

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
exit code 0
```

**Comment by kroikie** [comment]
@ghost

The issue at https://github.com/flutter/flutter/issues/22554 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing because the original issue is open and seems obsolete

**Comment by lvlrSajjad** [comment]
@kroikie @BondarenkoStas I have this problem too 
```
<Google> Cannot find an ad network adapter with the name(s): GADMAdapterFacebook. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
	[C16.1 DEA6FCF9-59BE-43E3-8D1C-E0DD120EA84C 192.168.8.61:50581<->172.217.18.138:443]
	Connected Path: satisfied (Path is satisfied), interface: utun2
```
I have installed and used admob plugin exactly like docs in pub.dev
