### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] onBackgroundMessage is not working in iOS when app is terminated.

### ISSUE THREAD

**Issue by MaheshKumarM-SCE** [FirebaseExtended/flutterfire#6320]
Hi. I used Flutter 2.2.1 and firebase_messaging: ^10.0.1. I can receive notifications with Android and onBackgroundMessage is working perfectly. But for iOS., I can receive notifications and **onBackgroundMessage** is not working after app is terminated.

### Steps to reproduce

1. flutter run on device
2. Quit / close the app
3. Send FCM to the app
4. Background notification appears but on onBackgroundMessage didnt work.

### Expected behavior
onBackgroundMessage should work after notification is received.

{
    "to" : "firebase_id",
    "mutable_content" : true,
    "content_available": true,
    "priority": "high",
         "notification": {
            "title": "How are you Jade",
            "body": "Did you sleep good?",
            "sound": "default",
            "type": 1,
            "click_action": "FLUTTER_NOTIFICATION_CLICK",
            "icon": "notification_icon",
            "priority": "high",
            "ttl": 10000,
            "android_channel_id": "notification_01"
        },
    "data" : {
        "content": {
            "id": 101,
            "channelKey": "good_morning_message_channel",
            "title": "How are you Jade",
            "body": "Did you sleep good?"
        }
    }
}

**Comment by luvishq** [comment]
Any update on this issue ?

**Comment by MaheshKumarM-SCE** [comment]
Hi, today I found that when I send firebase notification twice within 1.5 second, onBackgroundMessage is working in iOS even when the app is terminated. If anybody found onBackgroundMessage is not working for you, please try the above method, it is working. Is there any other solution to fix this.

**Comment by markusaksli-nc** [comment]
Hi @MaheshKumarM-SCE 
This is a native limitation of iOS in general, not just for Firebase. 
The way this issue manifests on the flutter implementation if firebase messaging is known and documented at https://firebase.flutter.dev/docs/messaging/usage#receiving-messages

> On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.

Thank you

**Comment by MaheshKumarM-SCE** [comment]
Hi... I would like to share the latest observations in this issue...

1. onBackgroundMessage is working in iOS if the app is in foreground, background or even terminated. 

2. I checked by closing the app and swiping it from the App Switcher and I sent the notifications after 5mins , I still received the notifications and onBackgroundMessage is working.

3.But, when I closed my app(app is in terminated state) and opened another app, I still receive notification but onBackgroundMessage  is not working this time. Please try this way and check if its working for you guys. Also, please tell me if there is any solution or workaround for this.

**Comment by markusaksli-nc** [comment]
How are you testing that the background message handle works when the app is terminated?

**Comment by MaheshKumarM-SCE** [comment]
I had a local preference value to increment and store the count each time onbackgroundMessage is executed.

Also, I created flutter local notification from onbackgroundMessage.
