### ISSUE TITLE
[📚] A value of type 'Object' can't be assigned to a variable of type 'Map<dynamic, dynamic>'.

### ISSUE THREAD

**Issue by VincentCauch** [FirebaseExtended/flutterfire#6324]
I am trying to retrieve data from firebase. This is the method:

Map gameretour = new Map();
Stream getUserEmpStreamSnapshots(BuildContext context) async* {

await FirebaseFirestore.instance.collection('GAME').doc(groupChatId).get().then((DocumentSnapshot documentSnapshot) {
  if (documentSnapshot.exists) {
    gameretour = **documentSnapshot.data()** ;
    print('Document data: ${documentSnapshot.data()}');
  } else {
    print('Document does not exist on the database');
  }
});
}

But documentSnapshot.data() is underlined in red and I have the error A value of type 'Object?' can't be assigned to a variable of type 'Map<dynamic, dynamic>'.
I don't know what is wrong with that method, I used similar method in another app that is working fine.

Thanks for the help.

**Comment by sanchitverma168** [comment]
try using "var" data type.

**Comment by markusaksli-nc** [comment]
Closing since this isn't a documentation issue and the suggested solution should work
