### ISSUE TITLE
error when creating Application.kt file for Firebase Messaging 10.0.1

### ISSUE THREAD

**Issue by AgungLaksana** [FirebaseExtended/flutterfire#6325]
I am trying to use latest FCM using `firebase_messaging: ^10.0.1` in my pubspec.yaml

from the documentation in here [https://firebase.flutter.dev/docs/messaging/overview#flutter-android-embedding-v1](url) , I have to create a Application.kt file in the Android project folder. from that documentation, the code is still in Java, so the Android Studio will convert it automatically to Kotlin like this
```

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService


class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingBackgroundService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}
```

but I have error like this https://i.stack.imgur.com/fVPMR.png

I have tried to import, but I will have another error like this: https://i.stack.imgur.com/T70Nw.png

it seems that I can't import PluginRegistry and I have error suggestion like this

> Add library 'Gradle: org.apache.maven:maven-ant-tasks:2.1.3' to classpath

but.... I don't understand. what should I do ? 
what is the code to be added to Application.kt (Kotlin) so I can use the Firebase Messaging?

I have no issue from Flutter Doctor

> [✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.2)
> [✓] VS Code (version 1.56.2)
> [✓] Connected device (4 available)
> 
> • No issues found!

**Comment by markusaksli-nc** [comment]
Hi @AgungLaksana 
Is your project on embedding v1 and if so have you considered upgrading?
Thank you

**Comment by AgungLaksana** [comment]
@markusaksli-nc yup you are right, I don't need to create Application.kt since I use Flutter 2.2.1
