### ISSUE TITLE
🐛 [firebase_admob] can't opt out of null safety .. when using sound null safety. // @dart=2.9

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#6328]
https://pub.dev/packages/firebase_admob/versions

Version | Min Dart SDK | Uploaded | &nbsp; | &nbsp;
-- | -- | -- | -- | --
0.11.2 | 2.12 | Jun 3, 2021 | &nbsp; | &nbsp;

**Comment by markusaksli-nc** [comment]
Hi @peterweb2005 
The firebase_admob plugin is deprecated in favor of [Google Mobile Ads SDK for Flutter](https://pub.dev/packages/google_mobile_ads).
Thank you

**Comment by peterweb2005** [comment]
should use 0.11.2 instead of 0.11.0+2?
