### ISSUE TITLE
onMessageOpenedApp is not getting called

### ISSUE THREAD

**Issue by yadav-aniket** [FirebaseExtended/flutterfire#6331]
After clicking on notification it opens app but onMessageOpenedApp is not getting called

**Comment by markusaksli-nc** [comment]
Hi @yadav-aniket 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Also please see https://github.com/FirebaseExtended/flutterfire/issues/6332
Thank you.
