### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessaging.onMessageOpenedApp.listen not working

### ISSUE THREAD

**Issue by AgungLaksana** [FirebaseExtended/flutterfire#6332]
I am using `firebase_messaging: ^10.0.1`  and `firebase_core: ^1.2.0` and also Flutter (Channel stable, 2.2.1)

I want if my user click the notification then I will open a specific page. so I have code like this in my HomePage
```

class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('FCM Notification clicked!');
      // do something after user click the notification
    });
    
  }
}
```

### Expected behavior
I expect that `print('FCM Notification clicked!');` will show after I click the push notification from the notification tray, but it seems this `FirebaseMessaging.onMessageOpenedApp.listen` never triggered after clicking the push notification.

I test it using real device (Redmi Note 7 and Samsung SM J200G) in debug mode but that stream never triggered

> ### Flutter doctor
> [✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.2)
> [✓] VS Code (version 1.56.2)
> [✓] Connected device (4 available)
> 
> • No issues found!

**Comment by erikkubica** [comment]
Same here https://github.com/FirebaseExtended/flutterfire/discussions/6255 I tried older/newer version of the flutter core and firebase messaging package and no luck. I noticed a weird thing about it, that when app is in background, I receive two notifications. From those two notifications, only one executes the onMessageOpenedApp

**Comment by yadav-aniket** [comment]
hey @AgungLaksana   I was facing the same issue , here is what I did to resolve it  for  notification  when app is in background 

this is code snippet from firebase_messaging doc

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();  //   
  await FirebaseMessaging.instance.getToken();  //  add this line  
  print('Handling a background message ${message.messageId}');
}

or 

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async { 
// remove    await Firebase.initializeApp();  
  print('Handling a background message ${message.messageId}');
}

**Comment by markusaksli-nc** [comment]
Hi @AgungLaksana 
Are you tapping on the notification received from FCM or are you using `flutter_local_notifications` in any way?
I'm not seeing this issue with the official example when tapping a notification (that isn't displayed by the local notification channel).
Thank you

**Comment by AgungLaksana** [comment]
@markusaksli-nc I am trying to follow the official example from here [https://pub.dev/packages/firebase_messaging/example](url) 

it seems to me that both `FirebaseMessaging.onBackgroundMessage` and `FirebaseMessaging.onMessage` use `FlutterLocalNotificationsPlugin`to display the notification. so both foreground and background from that example code will use flutter local notification right?

so I have problem when tapping a notification from `flutter_local_notifications`

**Comment by AgungLaksana** [comment]
@markusaksli-nc you are right, If I send FCM message using Firebase console to send Notification only message (not data) then `FirebaseMessaging.onMessageOpenedApp.listen ` will be triggered 

but If send data message payload from my own backend and then show it using `flutter_local_notifications` then it won't be triggered

**Comment by markusaksli-nc** [comment]
Well, then the issue is just that you need to use the callbacks for the local notification for getting tap events for the local notification. You should be able to find out how to do this from the `flutter_local_notifications` example.

https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/example/lib/main.dart

It all just depends on how you want to do things however, I do suggest that you read through the FCM API and see if you can use the remote message android payload options to do whatever you are doing with the data-only message spawning a local notification.

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification

If you try to process the silent remote notification to display a local notification it seems like you are adding an unnecessary step that will lead to issues like this (unless you absolutely need to for some reason).
