### ISSUE TITLE
🐛 [firebase_ml_vision] is discontinued. How to migrate my previous projects.

### ISSUE THREAD

**Issue by waqadArshad** [FirebaseExtended/flutterfire#6333]
Now I get this error.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-ml-vision:.
     Required by:
         project :app > project :firebase_ml_vision

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 59s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by markusaksli-nc** [comment]
Hi @waqadArshad 
Check https://github.com/FirebaseExtended/flutterfire/issues/5922#issuecomment-836758219
Thank you
