### ISSUE TITLE
firebase auth email

### ISSUE THREAD

**Issue by jaish702** [FirebaseExtended/flutterfire#6344]
/D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_interface-4.2.4/lib/src/method_channel/method_channel_firebase_auth.dart:244:34:
Error: A non-null value must be returned since the return type 'UserCredentialPlatform' doesn't allow null.
 - 'UserCredentialPlatform' is from 'package:firebase_auth_platform_interface/src/platform_interface/platform_interface_user_credential.dart'
 ('/D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_interface-4.2.4/lib/src/platform_interface/platform_interface_user_credential.dart ').
  Future<UserCredentialPlatform> createUserWithEmailAndPassword(

**Comment by markusaksli-nc** [comment]
Hi @jaish702 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
