### ISSUE TITLE
🐛 [firebase_auth] Sign-in method docs missing

### ISSUE THREAD

**Issue by sabetAI** [FirebaseExtended/flutterfire#6348]
On the [Firebase Auth page](https://firebase.flutter.dev/docs/auth/usage/#other-sign-in-methods), the links for the sign-in methods are broken:
![image](https://user-images.githubusercontent.com/28828395/121224653-c606a900-c856-11eb-8302-8cb1634ffc25.png)

For example, the [Apple Sign-in](https://firebase.flutter.dev/docs/auth/usage/social#apple) link is broken.

**Comment by markusaksli-nc** [comment]
These links should point to https://firebase.flutter.dev/docs/auth/social

For example, the Apple Sign-in link should point to 
https://firebase.flutter.dev/docs/auth/social#apple instead of https://firebase.flutter.dev/docs/auth/usage/social#apple

**Comment by russellwheatley** [comment]
Duplicate of: https://github.com/FirebaseExtended/flutterfire/issues/6751
