### ISSUE TITLE
🐛 [firebase_admob] 0.11.2 CocoaPods could not find compatible versions for pod "GoogleAppMeasurement"

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#6351]
## Bug report

    [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In Podfile:
        firebase_admob (from `.symlinks/plugins/firebase_admob/ios`) was resolved to 0.11.2, which depends on
          Google-Mobile-Ads-SDK (= 7.49.0) was resolved to 7.49.0, which depends on
            GoogleAppMeasurement (~> 6.0)

        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 8.1.1, which depends on
          Firebase/Analytics (= 8.0.0) was resolved to 8.0.0, which depends on
            Firebase/Core (= 8.0.0) was resolved to 8.0.0, which depends on
              FirebaseAnalytics (~> 8.0.0) was resolved to 8.0.0, which depends on
                FirebaseAnalytics/AdIdSupport (= 8.0.0) was resolved to 8.0.0, which depends on
                  GoogleAppMeasurement (= 8.0.0)

### Steps to reproduce

use 0.11.2

ALSO
0.11.0+2 also has another cocoapods dependency issuse

**Comment by peterweb2005** [comment]
when using 0.11.0+2
the dependencis conflict is

CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 0.0.1, which depends on
          Firebase/Analytics (~> 6.0) was resolved to 6.0.0, which depends on
            Firebase/Core (= 6.0.0) was resolved to 6.0.0, which depends on
              Firebase/CoreOnly (= 6.0.0)

        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
          Firebase/CoreOnly (= 7.3.0)

    CocoaPods could not find compatible versions for pod "FirebaseCore":
      In Podfile:
        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
          Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseCore (= 7.3.0)

        firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 0.4.0-1, which depends on
          Firebase/Crashlytics (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseCrashlytics (~> 7.3.0) was resolved to 7.3.0, which depends on
              FirebaseCore (~> 7.0)

    CocoaPods could not find compatible versions for pod "nanopb":
      In Podfile:
        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
          Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseCore (= 7.3.0) was resolved to 7.3.0, which depends on
              FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.9.0, which depends on
                nanopb (~> 2.30907.0)

        firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 0.4.0-1, which depends on
          Firebase/Crashlytics (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseCrashlytics (~> 7.3.0) was resolved to 7.3.0, which depends on
              nanopb (~> 2.30906.0)

**Comment by markusaksli-nc** [comment]
Hi @peterweb2005 
The firebase_admob plugin is deprecated in favor of [Google Mobile Ads SDK for Flutter](https://pub.dev/packages/google_mobile_ads) and has been discontinued. This plugin is not expected to work anymore and you should not use it. Please use the mentioned replacement instead.
Thank you
