### ISSUE TITLE
🐛 [FirebaseAuth] phone verification verificationId is null

### ISSUE THREAD

**Issue by MoffatMore** [FirebaseExtended/flutterfire#6354]
## Bug report

**Describe the bug**
When sms code is sent to the user for phone verification, 
VerificationId retried is null and the sms code retrieved is  phone number inside verificationCompleted method

### Expected behavior
verificationCompleted method was suppose to return phoneAuthCredential which contains smsCode and verificationId 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Below is a snapshot of flutter firebase phone verification i have implemented
</summary>

```
 Future<void> sendPhoneVerificationCode(String phoneNumber) async {
    await FirebaseAuth.instance.verifyPhoneNumber(
      autoRetrievedSmsCodeForTesting: phoneNumber,
      phoneNumber: '+267$phoneNumber',
      timeout: Duration(seconds: 60),
      verificationCompleted: (phoneAuthCredential) {
        this.smsCode = phoneAuthCredential.smsCode;
        this.verificationId = phoneAuthCredential.verificationId;

        logger.w('phone verification smsCode ${this.smsCode}');
        logger.w(
            'verification smsCode ${phoneAuthCredential.verificationId}');
      },
      verificationFailed: (error) {
        if (error.code == 'invalid-phone-number') {
          errorMessage = 'The provided phone number is not valid.';
        } else {
          errorMessage = error.message;
        }
      },
      codeSent: (verificationId, [forceResendingToken]) {
        this.verificationId = verificationId;
        logger.w('verificationId is $verificationId');
      },
      codeAutoRetrievalTimeout: (String verificationId) {
        this.verificationId = verificationId;
      },
    );
  }
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

   firebase: ^9.0.1
    firebase_auth: ^1.3.0
    firebase_messaging: ^10.0.1
</details>

---

**Comment by markusaksli-nc** [comment]
Hi @MoffatMore 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What device is this happening on?
Thank you

**Comment by MoffatMore** [comment]
@markusaksli-nc Thanks for the response here are the results of ```flutter doctor -v ```
![flutter doctoer](https://user-images.githubusercontent.com/12894381/121370114-bc577100-c93c-11eb-89f6-3b1faf5d3f54.PNG)

And also I am using Samsung A31 Android device with latest API 11,

**Comment by markusaksli-nc** [comment]
Could you also provide your `flutter pub deps -- --style=compact`? (and please refrain from using screenshots)

**Comment by MoffatMore** [comment]
Dart SDK 2.13.1
Flutter SDK 2.2.1
plug 1.0.0+1

dependencies:
- animations 2.0.0 [flutter]
- assets_audio_player 3.0.3+3 [flutter rxdart uuid http path_provider assets_audio_player_web]
- awesome_dialog 2.1.0 [flutter simple_animations flare_flutter]
- chewie 1.2.1 [cupertino_icons flutter provider video_player wakelock]
- equatable 2.0.2 [collection meta]
- expandable_text 2.2.0 [flutter]
- extended_image 4.1.0 [extended_image_library flutter meta]
- firebase 9.0.1 [http http_parser js]
- firebase_auth 1.3.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_messaging 10.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.1 [flutter bloc provider]
- flutter_custom_clippers 1.1.2 [flutter]
- flutter_form_bloc 0.20.1 [flutter flutter_bloc form_bloc rxdart flutter_keyboard_visibility collection intl]
- flutter_local_notifications 6.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_reaction_button 1.0.8 [flutter]
- flutter_shimmer 1.3.0 [flutter]
- flutter_swiper 1.1.6 [flutter transformer_page_view flutter_page_indicator]
- graphql 5.0.0 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- graphql_flutter 5.0.0 [graphql gql_exec flutter meta path_provider path connectivity_plus hive plugin_platform_interface]
- grouped_buttons 1.0.4 [flutter]
- hexcolor 2.0.4 [flutter flutter_web_plugins]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.0.0 [flutter hive path_provider path]
- image_picker 0.8.0+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- intro_slider 2.4.3 [flutter]
- like_button 2.0.2 [flutter]
- logger 1.0.0
- new_version 0.2.0 [flutter package_info_plus http html url_launcher]
- outline_material_icons 0.1.1 [flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- progress_indicators 1.0.0 [flutter]
- provider 5.0.0 [collection flutter nested]
- recase 4.0.0
- scoped_model 1.1.0 [flutter]
- shimmer 2.0.0 [flutter]
- smooth_star_rating 1.1.1 [flutter]
- timeago 3.0.2
- toast 0.1.5 [flutter]
- uuid 3.0.4 [crypto]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- args 2.1.1
- assets_audio_player_web 3.0.3+3 [flutter flutter_web_plugins]
- async 2.6.1 [meta collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- connectivity_plus 1.0.2 [flutter meta connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- connectivity_plus_linux 1.0.2 [flutter connectivity_plus_platform_interface dbus meta]
- connectivity_plus_macos 1.0.2 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.0.2 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.0.2 [connectivity_plus_platform_interface flutter]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- cupertino_icons 1.0.3
- dbus 0.2.5 [args meta pedantic xml]
- extended_image_library 3.1.0 [crypto flutter http_client_helper path path_provider]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.1 [meta path]
- firebase_auth_platform_interface 4.2.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.2.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flare_flutter 3.0.1 [collection flutter meta]
- flutter_keyboard_visibility 5.0.2 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_platform_interface 4.0.0 [flutter plugin_platform_interface]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- form_bloc 0.20.1 [meta bloc rxdart equatable quiver pedantic collection uuid]
- gql 0.13.0 [collection meta source_span]
- gql_dedupe_link 2.0.0 [meta gql_exec gql_link async]
- gql_error_link 0.2.0 [async gql_exec gql_link meta]
- gql_exec 0.3.0 [collection meta gql]
- gql_http_link 0.4.0 [meta gql gql_exec gql_link http http_parser]
- gql_link 0.4.0 [meta gql gql_exec]
- gql_transform_link 0.2.0 [gql_exec gql_link]
- html 0.15.0 [csslib source_span]
- http 0.13.3 [async http_parser meta path pedantic]
- http_client_helper 2.0.2 [http]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- normalize 0.5.3 [gql collection]
- package_info_plus 1.0.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.2 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.1.1 [flutter]
- package_info_plus_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.2 [http package_info_plus_platform_interface flutter flutter_web_plugins meta]
- package_info_plus_windows 1.0.1 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- simple_animations 3.1.1 [flutter supercharged pedantic]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- supercharged 2.0.0 [supercharged_dart flutter]
- supercharged_dart 2.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- transformer_page_view 0.1.6 [flutter]
- typed_data 1.3.0 [collection]
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player 2.1.5 [flutter flutter_test meta video_player_platform_interface video_player_web]
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.5.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.1.0+1 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+1 [flutter meta]
- wakelock_web 0.2.0+1 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.1.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]

**Comment by markusaksli-nc** [comment]
I was able to reproduce this with `firebase_auth: ^1.4.1` but this could be the intended native behavior since a `verificationId` is not required if the phone number is automatically verified?
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.3.0-17.0.pre.345, on Microsoft Windows [Version 10.0.19041.1052], locale et-EE)
    • Flutter version 2.3.0-17.0.pre.345 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1542ace4f (12 hours ago), 2021-06-13 20:59:02 -0400
    • Engine revision ab2c00c771
    • Dart version 2.14.0 (build 2.14.0-208.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7351085
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7442.40
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.1052]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!
```
</details>

**Comment by russellwheatley** [comment]
I've manually signed in and the [codeSent](https://github.com/FirebaseExtended/flutterfire/blob/9d4bbfb7766fb42f8c1140415f35f5bfcecfe823/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#L673) method receives the `verificationId` as expected (it is a non-null parameter). 

I've also signed in automatically and the [verificationCompleted](https://github.com/FirebaseExtended/flutterfire/blob/9d4bbfb7766fb42f8c1140415f35f5bfcecfe823/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#L656) method is called (as expected, this is where you get the `PhoneAuthCredential` to sign in). Automatic sign-in also triggers the `codeSent` method with another non-null value.

@MoffatMore  Which function are you seeing this problem as you mentioned the `verificationCompleted` which accepts only one `PhoneAuthCredential` parameter?


<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/russellwheatley/sdks/flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/russellwheatley/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/russellwheatley/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio copy.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • SM G960F (mobile) • 229c87d511057ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```
</details>

**Comment by MoffatMore** [comment]
@russellwheatley 
I was not able to retrieve verificationId from the following function, I can see from flutter doctor -v, you were testing with Andoid 10, can you try to simulate with latest Android 11? I was using it and thats when i encountered this issue


PhoneCodeSent codeSent =        (String verificationId, [int forceResendingToken]) async {      widget._scaffold.showSnackBar(const SnackBar(        content: Text('Please check your phone for the verification code.'),      ));      _verificationId = verificationId;    };

**Comment by russellwheatley** [comment]
@MoffatMore a couple of questions:

1. are you sure the user is not already signed in?
2. does the `verificationCompleted` function also get called? This indicates the user is automatically signed in and thus you don't need the `verificationId`.
