### ISSUE TITLE
[📚] Document MacOS sandbox config (outgoing connections)

### ISSUE THREAD

**Issue by sultanmyrza** [FirebaseExtended/flutterfire#6356]
I was trying to run flutter app on MacOS with firebase emulators enabled  
`firebase emulators:start --only firestore,functions,auth,storage`
I was getting this error 
```
Flutter Firebase Auth: A network error (such as timeout, interrupted connection or unreachable host) has occurred
```
I solved by allowing Outgoing Connections on the Xcode's Runner.xcworkspace
![image](https://user-images.githubusercontent.com/12681781/121333660-d1330500-c93a-11eb-8fb6-b1d803b9c7bb.png)
here is the full [thread ](https://stackoverflow.com/a/66008698/6133329)

We should update docs https://firebase.flutter.dev/docs/installation/macos#enabling-use-of-firebase-emulator-suite

**Comment by markusaksli-nc** [comment]
This isn't just required for the emulator suite, a lot of the plugins require this to work at all.

**Comment by Salakar** [comment]
Let's update https://firebase.flutter.dev/docs/installation/macos#enabling-use-of-firebase-emulator-suite to add this extra step - @sultanmyrza would you be willing to send a PR for this?

**Comment by sultanmyrza** [comment]
> Let's update https://firebase.flutter.dev/docs/installation/macos#enabling-use-of-firebase-emulator-suite to add this extra step - @sultanmyrza would you be willing to send a PR for this? There's an `Edit this page` link at the bottom of the documentation page that will take you to the right location to edit
@Salakar I just saw it sorry for late response.

It's my first pull request ever so I'm not sure was that right or not. Hope this helps somehow. If need to improve pull req or something let me know.
