### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "firebase_core":

### ISSUE THREAD

**Issue by s2yed** [FirebaseExtended/flutterfire#6357]
version '8.0.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "firebase_core":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`)

Specs satisfying the `firebase_core (from `.symlinks/plugins/firebase_core/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by markusaksli-nc** [comment]
The solution is mentioned in the same error message you posted.

Also from the official documentation https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions:

> FlutterFire supports an iOS deployment target of 10 or higher, in line with the requirements of the underlying firebase-ios-sdk.

**Comment by s2yed** [comment]
> The solution is mentioned in the same error message you posted.
> 
> Also from the official documentation https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions:
> 
> > FlutterFire supports an iOS deployment target of 10 or higher, in line with the requirements of the underlying firebase-ios-sdk.
> 
> You can fix this by setting the deployment target in Xcode or from the podfile



When he sold it and then did an update, it came back to the same old one
