### ISSUE TITLE
Support Linux desktop

### ISSUE THREAD

**Issue by sgehrman** [FirebaseExtended/flutterfire#6359]
Surprised to find out I can't built desktop apps using firebase.

**Comment by rrousselGit** [comment]
Hi @sgehrman 
This repository only wraps the Firebase SDKs so they can be used with Flutter. Platform support or developing new SDKs is up to the Firebase team, not us. Until they decide to develop a Firebase Windows SDK or Firebase pure Dart SDK, we won't be able to implement it.
Currently the closest thing is Firebase for C++ however see #5795. Once there is a rigorously supported Firebase desktop workflow it can probably be piped through dart:ffi.

This request is better suited for https://firebase.google.com/support/troubleshooter/report/features until then.
Thank you
