### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] onBackgroundMessage is not working in iOS.

### ISSUE THREAD

**Issue by karthikveluchamy-12121991** [FirebaseExtended/flutterfire#6377]
[FIREBASE_MESSAGING] onBackgroundMessage is not working in iOS when app is terminated and another app is opened.

Hi. I used Flutter 2.2.1 and firebase_messaging: ^10.0.1. I can receive notifications with Android and onBackgroundMessage is working perfectly. 
For iOS., I can receive notifications but onBackgroundMessage is not working if the app is closed & removed from the App switcher and Another is opened.

**Steps to reproduce**
flutter run on device
Quit / close the app & Open any other app(games, videos)
Send FCM to the app
Background notification appears but on onBackgroundMessage didnt work.

**Expected behavior**
Even if the app is terminated and another app is opened, onBackgroundMessage should work after notification is received.

{
"to" : "firebase_id",
"mutable_content" : true,
"content_available": true,
"priority": "high",
"notification": {
"title": "Good Morning hannah",
"body": "Morning walks are good for health",
"sound": "default",
"type": 1,
"click_action": "FLUTTER_NOTIFICATION_CLICK",
"icon": "notification_icon",
"priority": "high",
"ttl": 10000,
"android_channel_id": "notification_01"
},
"data" : {
"content": {
"id": 101,
"channelKey": "good_morning_message_channel",
"title": "Good Morning hannah",
"body": "Morning walks are good for health"
}
}
}

**Comment by markusaksli-nc** [comment]
Hi @MaheshKumarM-SCE 
Background messages will stop working on iOS once the app is terminated. This is a native limitation and is also documented at
https://firebase.flutter.dev/docs/messaging/usage#receiving-messages

> On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.

Thank you

**Comment by MaheshKumarM-SCE** [comment]
Hi @markusaksli-nc,  Please check the description. onBackgroundMessage is working for me in iOS even if the app is terminated. 

I also added details when it fails to work for me - when the app is terminated and another app is opened, onBackgroundMessage is not working.

**Comment by karthikveluchamy-12121991** [comment]
Hi @markusaksli-nc, Please check the description. onBackgroundMessage is working for me in iOS even if the app is terminated.

I also added details when it fails to work for me - when the app is terminated and another app is opened, onBackgroundMessage is not working.

**Comment by bilalgodesto** [comment]
@karthikveluchamy-12121991 Did you find any solution for this?

**Comment by MaheshKumarM-SCE** [comment]
No, still trying to figure out the solution or workaround

**Comment by bilalgodesto** [comment]
I have also posted bug on same topic. These should not closed its a genuine bug in firebase_messaging
