### ISSUE TITLE
🐛 [firebase_core] Execution failed for task ':cloud_firestore:generateDebugRFile'.        

### ISSUE THREAD

**Issue by pierre-gancel** [FirebaseExtended/flutterfire#6381]
FAILURE: Build failed with an exception.                                

> flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.3.0/android/build/intermediates/symbol_list_with_package_name/debug/package-aware-r.txt

**Comment by pierre-gancel** [comment]
> [✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en-GB)
>     • Flutter version 2.2.1 at /Users/pierre/flutter
>     • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
>     • Engine revision 0fdb562ac8
>     • Dart version 2.13.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/pierre/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.57.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.23.0

**Comment by markusaksli-nc** [comment]
Hi @pierre-gancel 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by pierre-gancel** [comment]
Dear @markusaksli-nc I am surprised by your comment and this brutal closing.

The information is in the title of the issue
Execution failed for task ':cloud_firestore:generateDebugRFile'

I then added all the information I had in the description :

FAILURE: Build failed with an exception.

flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.3.0/android/build/intermediates/symbol_list_with_package_name/debug/package-aware-r.txt

Then I provided the result of Flutter Doctor.

Would you like to know anything else in order to replicate this error ?

**Comment by markusaksli-nc** [comment]
Please open a new issue and fill out the template with all of the required information, describe the steps that lead to this error, provide the full stacktrace, etc.

**Comment by pierre-gancel** [comment]
I reopened an issue here : https://github.com/FirebaseExtended/flutterfire/issues/6393 ?

It seems to be linked with upgrading flutter above 2.0.0 as well as upgrading the following pub : 
**onesignal 3.0.0** 
which requires firebase_messaging
which requires firebase_core
