### ISSUE TITLE
[📚] FCM Setup guide omits platform specific details

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#6386]
The FCM setup guide located [here](https://firebase.flutter.dev/docs/messaging/usage/) fails to provide platform specific setup steps.

For example on android if you follow the guide, you will end up with an error because you have not added the google services dependency to your build.gradle file.

https://stackoverflow.com/questions/63804012/flutter-firebase-and-android-issue-unable-to-initialise-cannot-find-google-se

**Comment by futurelucas4502** [comment]
This is not a fault of the guide FCM is an add on for the firebase_core package.

![image](https://user-images.githubusercontent.com/48055553/121963410-fa4ffd00-cd61-11eb-900e-2fdc9f79d5a8.png)


In step 1 of setting up FCM, the firebase_core package is already added in the pubspec as seen in the image above. Therefore, you must follow the setup guide for firebase_core first.

The guide for firebase_core can be found in the getting started section here: https://firebase.flutter.dev/docs/overview/

**Comment by safield** [comment]
> This is not a fault of the guide FCM is an add on for the firebase_core package.
> 
> ![image](https://user-images.githubusercontent.com/48055553/121963410-fa4ffd00-cd61-11eb-900e-2fdc9f79d5a8.png)
> 
> In step 1 of setting up FCM, the firebase_core package is already added in the pubspec as seen in the image above. Therefore, you must follow the setup guide for firebase_core first.
> 
> The guide for firebase_core can be found in the getting started section here: https://firebase.flutter.dev/docs/overview/

Umm, then shouldn't the FCM guide start first thing with "Before starting, ensure you have setup firebase_core with this guide."? Its basically still the same problem as mentioned in the OP.

**Comment by markusaksli-nc** [comment]
I think this is a valid point since while the [`Getting Started`](https://firebase.flutter.dev/docs/overview) guide provides all of the detailed setup steps needed for all of the platforms, not all of the plugin setup pages mention it.

For some reason only cloud functions and auth contain this line as the first thing under [`Installation`](https://firebase.flutter.dev/docs/auth/overview#installation):

> Before installing the Cloud Functions for Firebase plugin, ensure that you have followed the [Getting Started](https://firebase.flutter.dev/docs/overview) documentation and have initialized FlutterFire.

This should be added to all of the plugins.

**Comment by AliAkberAakash** [comment]
Its mentioned in the overview:

> 1. Make sure to initialize Firebase
> Follow this guide to install firebase_core and initialize Firebase if you haven't already.

**Comment by russellwheatley** [comment]
Thanks for reporting, this has been added to each plugin's overview 👍
