### ISSUE TITLE
Firebase app check with API Restrictions

### ISSUE THREAD

**Issue by febg11** [FirebaseExtended/flutterfire#6391]
Im having a lot of trouble with flutter firebase app-check

Specifically, I have restricted my firebase using app-check and my debug sha-256 key. This works great :)

However, I have also set up a restriction for my firebase android json  api key using the credentials page in the google cloud platform console. This has been permitted to allow the following apis: 

Android Device Verification
Cloud Firestore API
Cloud Functions API
Firebase App Check API
Identity Toolkit API
Token Service API
Firebase Installations API

Now this works (everything shows as valid requests on the firebase console)  if I don't add an **Application** restriction.
 

Now if I add my debug android sha1 key (which is also generated alongside one I used for the sha256) and my package name everything becomes rejected. I receive the following error even when the user is logged in

```
E/StorageException(30038): StorageException has occurred.
E/StorageException(30038): User is not authenticated, please authenticate using Firebase Authentication and try again.
```

and this shows up as a malicious request in the console. Does anyone know why this could be happening? 

I have double checked the sha key and copy pasted my package name from the android manifest... I can't see what I am doing wrong

It's driving me nuts 

UPDATE

its definitely not api permissions. I have clicked do not restrict and it still doesnt work. It is something to do with the sha1 key or package name

These are the versions i am using

```
  firebase_messaging: 10.0.2                     
  firebase_storage: 8.1.3                       
  cloud_functions: 1.1.2                         
  firebase_auth: 1.4.1                         
  cloud_firestore: 2.2.2                          
  firebase_core: 1.3.0                          
  firebase_app_check: 0.0.1+2
```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.108, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```

I cannot add a reproducible example as this is directly linked to the settings in firebase/GCP

**Comment by markusaksli-nc** [comment]
Hi @febg11 
Have you considered taking this to https://firebase.google.com/support
Not sure how this relates to the specific plugin code that wraps the native Firebase SDK in this repository.
Thank you

**Comment by febg11** [comment]
Hi @markusaksli-nc. I have opened a ticket although i thought this could be linked something like the package not sending sha1 keys... I'm not really sure how this works but you know a lot more than me.

**Comment by markusaksli-nc** [comment]
Normally I would say that the FlutterFire plugins just wrap the native Firebase SDKs so they could be called from Dart code so unless we are passing some parameters incorrectly this should be up to the native SDK. However, this is somewhat complicated by the fact that App Check is in Beta on the backend side and our plugin for it is still in preview. It looks like some parts aren't even implemented yet?

https://github.com/FirebaseExtended/flutterfire/blob/1db77b689c1fa856194c628d8e11e69f848f82e0/packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/platform_interface/platform_interface_firebase_app_check.dart#L53-L71

I'm not familiar enough with how exactly the implementation works to provide some insight here so I'll label this for further investigation for the time being. Hopefully, you get some useful feedback from the support ticket as well.

**Comment by AliYar-Khan** [comment]
I am facing same issue ... Any work around of this ... stack trace is as follows :

```
I/FirebaseAuth(12132): [FirebaseAuth:] Preparing to create service connection to fallback implementation
W/System  (12132): Ignoring header X-Firebase-Locale because its value was null.
W/System  (12132): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(12132): Notifying id token listeners about user ( Deleted by me ).
D/FirebaseAuth(12132): Notifying auth state listeners about user ( Deleted by me ).
W/System  (12132): Ignoring header X-Firebase-Locale because its value was null.
W/System  (12132): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(12132): Notifying id token listeners about user ( Deleted by me ).
W/StorageUtil(12132): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
I/TetheringManager(12132): registerTetheringEventCallback:com.goochil.taxiapp
E/StorageException(12132): StorageException has occurred.
E/StorageException(12132): User is not authenticated, please authenticate using Firebase Authentication and try again.
E/StorageException(12132):  Code: -13020 HttpResult: 401
E/StorageException(12132): The server has terminated the upload session
E/StorageException(12132): java.io.IOException: The server has terminated the upload session
E/StorageException(12132): 	at com.google.firebase.storage.UploadTask.serverStateValid(UploadTask.java:339)
E/StorageException(12132): 	at com.google.firebase.storage.UploadTask.shouldContinue(UploadTask.java:308)
E/StorageException(12132): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:229)
E/StorageException(12132): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$StorageTask(StorageTask.java:1072)
E/StorageException(12132): 	at com.google.firebase.storage.-$$Lambda$StorageTask$q9YBoR_A8LB-JxTCx8JRQvabaZs.run(Unknown Source:2)
E/StorageException(12132): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(12132): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(12132): 	at java.lang.Thread.run(Thread.java:923)
E/StorageException(12132): Caused by: java.io.IOException: {  "error": {    "code": 401,    "message": "Firebase App Check token is invalid."  }}

```

**Comment by febg11** [comment]
@markusaksli-nc  Support team said it works for them, but I am not sure whether they were using flutter or just the regular android app check + firebase when they tested it.

I have recently purchased an ios developer license and it was also throwing the same error earlier when I used the bundle id as an ios app restriction. However, I have just tried unsetting/re-adding it and now works?  

@AliYar-Khan Have you had any luck with the android app restrictions?

**Comment by AliYar-Khan** [comment]
> 
> 
> @markusaksli-nc Support team said it works for them, but I am not sure whether they were using flutter or just the regular android app check + firebase when they tested it.
> 
> I have recently purchased an ios developer license and it was also throwing the same error earlier when I used the bundle id as an ios app restriction. However, I have just tried unsetting/re-adding it and now works?
> 
> @AliYar-Khan Have you had any luck with the android app restrictions?
> 
> ---------------- UPDATE
> 
> @markusaksli-nc This has to be linked to app check. If I leave my sha1 key/package name in the app restriction BUT turn off storage app check enforcement then I can still read firebase storage (e.g. getting dowloadURLs). Surely because this is working it means my sha1 package name restrictions are correct
> 
> When I turn app check enforcement back on everything starts failing again. Removing the app restriction removes all the problems but leaves me with an unsecured key.
> 
> Does this sound like a client or server side problem?

I have included the app check as 

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'recaptcha-v3-site-key');
  runApp(App());
}

and run on phyiscal device ... then the error is gone !!!
```

**Comment by febg11** [comment]
> > @markusaksli-nc Support team said it works for them, but I am not sure whether they were using flutter or just the regular android app check + firebase when they tested it.
> > I have recently purchased an ios developer license and it was also throwing the same error earlier when I used the bundle id as an ios app restriction. However, I have just tried unsetting/re-adding it and now works?
> > @AliYar-Khan Have you had any luck with the android app restrictions?
> > ---------------- UPDATE
> > @markusaksli-nc This has to be linked to app check. If I leave my sha1 key/package name in the app restriction BUT turn off storage app check enforcement then I can still read firebase storage (e.g. getting dowloadURLs). Surely because this is working it means my sha1 package name restrictions are correct
> > When I turn app check enforcement back on everything starts failing again. Removing the app restriction removes all the problems but leaves me with an unsecured key.
> > Does this sound like a client or server side problem?
> 
> I have included the app check as
> 
> ```
> Future<void> main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp();
>   await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'recaptcha-v3-site-key');
>   runApp(App());
> }
> 
> and run on phyiscal device ... then the error is gone !!!
> ```

And you have set app restrictions on your api key on the credentials page?

**Comment by AliYar-Khan** [comment]
for what ? @febg11

**Comment by febg11** [comment]
No my issue isn't that app check doesn't work. It's that it doesn't seem to work when we set sha1 app restrictions to the firebase API key

https://console.cloud.google.com/apis/credentials

**Comment by markusaksli-nc** [comment]
It sounds like this could be a client-side problem but as I mentioned I don't have much insight on the implementation here.

**Comment by russellwheatley** [comment]
Hey @febg11, did you manage to resolve your problem? App check has been updated a few times since you created this issue.
