### ISSUE TITLE
Dynamic link not opening correct page

### ISSUE THREAD

**Issue by liquidedgesolutions** [FirebaseExtended/flutterfire#6392]
We have a link in a forgot password email, that is supposed to open up a page in the screen in die app where the user can enter and confirm their new password.

At the moment, on 95% of the phones we test on, when you're on the login page, while clicking on the link, it opens the app, but it opens it to the login page, not the right page where the user is supposed to enter his new password.

When i'm on any other page, and then open the link in the email, it opens up correctly. 

It works on one android phone we have (android 11 - Red Velvet Cake) and on our simulator.   It SEEMS to work on "newer" phones,as the other phones we test with have Android 9, Android 7, and then we also have an iphone 8 and iphone SE. It doesn't work on any of those. 

We use firebase_dynamic_links and had it working about 6-8 weeks ago, and haven't changed anything in the code since, but now all of a sudden it doesn't work anymore. 

See also the codesnippet I've uploaded. We use Flutter version 2.0.6 currently.

![image](https://user-images.githubusercontent.com/80834007/122032539-0672a380-cdd0-11eb-8b39-d93c4f2329c2.png)

Could anyone assist? :-)

**Comment by markusaksli-nc** [comment]
Hi @liquidedgesolutions 
Have you upgraded your dynamic links dependency meanwhile? If not have you contacted firebase support?
https://firebase.google.com/support
Could you provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by liquidedgesolutions** [comment]
Hi

See below:

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- downloads_path_provider 0.1.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- file_picker_platform_interface 1.3.1 [flutter plugin_platform_interface]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_maps_flutter_platform_interface 1.2.0 [flutter meta plugin_platform_interface stream_transform collection]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- observable_ish 2.1.5 [collection]
- open_file 3.1.0 [flutter ffi]
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.0 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- process 4.1.0 [file path platform]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

![image](https://user-images.githubusercontent.com/80834007/122043968-3de74d00-cddc-11eb-8ea9-77bfc1ce66b6.png)

**Comment by markusaksli-nc** [comment]
You left the first part of your pub deps out. Also same question as before.

**Comment by liquidedgesolutions** [comment]
Apologies about that. See below.

We haven't contacted Firebase support, I did now, thanks for the suggestion.  Is there maybe a better/other way to open links to a specific page in the app?  Other than using Firebase, that we can try?

******************************************
************* flutter doctor *************
******************************************
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.1052], locale en-ZA)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.57.0)
[√] Connected device (2 available)

• No issues found!

******************************************************************
*************  flutter pub deps -- --style=compact   *************
******************************************************************
Dart SDK 2.13.3
Flutter SDK 2.2.2
remind 1.0.55+56

dependencies:
- autocomplete_textfield 1.7.3 [flutter]
- cupertino_icons 1.0.2
- dotted_border 1.0.7 [flutter path_drawing]
- dropdown_formfield 0.1.3 [flutter]
- file_picker 1.13.3 [flutter flutter_plugin_android_lifecycle file_picker_platform_interface]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_crashlytics 0.2.4 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.5.3 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_document_picker 4.0.1 [flutter]
- flutter_image_compress 1.0.0 [flutter]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_masked_text 0.7.0 [flutter]
- font_awesome_flutter 8.12.0 [flutter]
- get_it 3.1.0 [meta]
- google_maps_flutter 0.5.33 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- loading_overlay 0.2.1 [flutter]
- nova 0.0.1 [flutter intl http permission_handler downloads_path_provider open_file]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_macos 2.0.0 [flutter]
- provider 4.3.3 [collection flutter nested]
- provider_architecture 1.1.1+1 [flutter provider observable_ish]
- share 2.0.1 [meta mime flutter]
- sqflite 2.0.0+2 [flutter sqflite_common path]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- webview_flutter 2.0.4 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- downloads_path_provider 0.1.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- file_picker_platform_interface 1.3.1 [flutter plugin_platform_interface]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_maps_flutter_platform_interface 1.2.0 [flutter meta plugin_platform_interface stream_transform collection]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- observable_ish 2.1.5 [collection]
- open_file 3.1.0 [flutter ffi]
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.0 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- process 4.1.0 [file path platform]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

**Comment by liquidedgesolutions** [comment]
Hi everyone

We upgraded to the latest version of Flutter and the issue resolved itself.
