### ISSUE TITLE
🐛 Not getting proper payload data while clicking on notification in Android

### ISSUE THREAD

**Issue by RIddhiIroid** [FirebaseExtended/flutterfire#6397]
## Bug report

**In Data payload I receive the correct object but when I click on the push-  it is just showing the notifcationId no other parameters When app is OPEN*

**Comment by markusaksli-nc** [comment]
Hi @RIddhiIroid 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
