### ISSUE TITLE
[📚] App check installation doc mistake

### ISSUE THREAD

**Issue by nt4f04uNd** [FirebaseExtended/flutterfire#6413]
https://firebase.flutter.dev/docs/app-check/overview/#installation

There after the paragraph

> For legacy package imports, place the following ignore comment to hide Dart analyzer warnings:

I would expect to find these two lines

```dart
// ignore: import_of_legacy_library_into_null_safe
import 'package:firebase_app_check/firebase_app_check.dart';
```

But the ignore part is cut out

**Comment by nt4f04uNd** [comment]
Also, I believe that necessary `activate` call step is missing from the instructions

**Comment by rbrishabh** [comment]
I can help with this!

**Comment by enri90** [comment]
how does it work here? When one asks for assistance then is he forgotten?

[https://github.com/FirebaseExtended/flutterfire/issues/6310](url)
