### ISSUE TITLE
🐛 [firebase_messaging] Ver 10.0.2 minimised app not triggering on notification click

### ISSUE THREAD

**Issue by sajanyamaha** [FirebaseExtended/flutterfire#6416]
Using latest version `firebase_messaging: ^10.0.2` 

Removed the manifest details,
```
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```

**Step to reproduce :** The app is minimised and Notification received with payload.Click the notification.
**Issue 1 :** On click of notification no action is seen , even the app wont come to foreground .
**Issue 2 :** If manifest details retained the app would load up but `onMessage` or `onBackgroundMessage` or `onMessageOpenedApp` Nothing fires up .

The official documentation does not mention anywhere to remove the manifest details,I had to conclude it from various forums. Please someone explain the correct method of using ,

1. `onMessage` 
2. `onBackgroundMessage` 
3. `onMessageOpenedApp`

<details close>
<summary>Flutter Doctor</summary>
<p>

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3.1 20E241 darwin-x64, locale en-IN)
    • Flutter version 2.0.5 at xxxeloper/flutter
    • Framework revision adc687823a (9 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK atxxxdroid/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = xxxAndroid/sdk
    • ANDROID_SDK_ROOT = xxx/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
</p>
</details>

**Comment by markusaksli-nc** [comment]
Hi @sajanyamaha 
Where are you registering callbacks for these in your code? The intent filter isn't necessary anymore (and the key in the notification data isn't either).
Could you provide your `flutter pub deps -- --style=compact`?
Thank you
