### ISSUE TITLE
Implement OAuthCredential to use LinkedIn Access Token

### ISSUE THREAD

**Issue by kekko7072** [FirebaseExtended/flutterfire#6419]
I am using [linkedin_login](https://pub.dev/packages/linkedin_login) package to login to LinkedIn and obtain an accessToken to use to create a credential and then login to firebase using the credential. Could it work?
1) How can I create a Credential from the Linkedin Access info?
I tried using this but don't know what I should put in this fields
```
const OAuthCredential({
    required String providerId,
    required String signInMethod,
    this.accessToken,
    this.idToken,
    this.secret,
    this.rawNonce,
  })
```
Can someone explain me better all the required elements and explain me a showcase?

2) I can access using this credential and pass it to `signInWithCredential(credential)` ?

**Comment by markusaksli-nc** [comment]
Hi @kekko7072 
LinkedIn auth is not supported on Firebase yet so there is no official way to do this. You can create a custom token with something like https://github.com/firebase/functions-samples/tree/main/linkedin-auth
Thank you

**Comment by kekko7072** [comment]
Sorry but my question should be still open. In fact the example is not working because is based on old version of LinkedIn api.

**Comment by kekko7072** [comment]
Can I create custom token directly using firebase Auth package ?

**Comment by markusaksli-nc** [comment]
You can use the same principle to create a custom token from dart code
