### ISSUE TITLE
Firebase Phone Auth Proving to be unreliable

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#642]
So i have been having issues with the phone auth. The code NEVER comes whenever the testers are based in America. Also for iOS the code sending doesnt work the same way all the time, sometimes it asks for captha and sometimes it doesnt. On iOS i have to try for up to 2 days before i receive the code. Phone Auth is the only form of login my app uses so its really a deal breaker. Please help

**Comment by kroikie** [comment]
@iamjavademon

The issue at https://github.com/flutter/flutter/issues/22425 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@ iamjavademon do you still experience the problem?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
