### ISSUE TITLE
🐛 [firebase_auth] verifyBeforeUpdateEmail() method does not set currentUser.emailVerified to false

### ISSUE THREAD

**Issue by jsstanley** [FirebaseExtended/flutterfire#6426]
## Bug report

**Describe the bug**
On calling the `FirebaseAuth.instance.currentUser.verifyBeforeUpdateEmail()` method to update a user's email address, the bool value for `FirebaseAuth.instance.currentUser.emailVerified` is not set to `false`.

### Steps to reproduce

1. Have an existing authenticated user with a verified email address
1. Call the `FirebaseAuth.instance.currentUser.verifyBeforeUpdateEmail()` method to update the user's email address
1. Reload the user's authentication data using something like `await FirebaseAuth.instance.currentUser.reload()`
1. Check the value for `FirebaseAuth.instance.currentUser.emailVerified` without the user clicking the verification link sent to their newly specified email address
1. The value for `FirebaseAuth.instance.currentUser.emailVerified` returns `true`

### Expected behavior

On calling the `FirebaseAuth.instance.currentUser.verifyBeforeUpdateEmail()` method to update a user's email address, the bool value for `FirebaseAuth.instance.currentUser.emailVerified` *should* be set to `false`. Then, only once the user verifies their new email address by clicking the link provided in the email that was sent to them, `FirebaseAuth.instance.currentUser.emailVerified` should be set to `true`.

Currently, this does not happen, which makes the `currentUser.emailVerified` value useless in this scenario.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.3
Flutter SDK 2.2.2
project_name 1.0.0+1

dependencies:
- cloud_firestore 2.2.2 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_web 2.1.2 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cupertino_icons 1.0.3
- firebase_analytics 8.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 1.3.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- provider 5.0.0 [collection flutter nested]
- url_strategy 0.2.0 [flutter_web_plugins]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_auth_platform_interface 4.3.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- pedantic 1.11.1
- petitparser 4.1.0 [meta]
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- xml 5.1.2 [collection meta petitparser]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @jsstanley 
This repository just wraps the native Firebase SDKs so they could be called from Dart. This is just how the native SDKs work so if you would like to see them changed you are better served at https://firebase.google.com/support. That is unless you can point to some native documentation that says this is how it should work?
Then about the issue itself - I'm not sure why this behavior would be desirable? If the current email of the user is verified why should the verification status be removed by this call? If the user does not verify their new email the current email will have to be re-verified. 
This would make sense if the email was updated regardless of verification but the new email is used only once it has been verified.
Thank you

**Comment by jsstanley** [comment]
Hi @markusaksli-nc 

Thank you, I hadn't realised this was intended behaviour from the native SDKs. 

To answer your question about why this behaviour would be desirable, if the user initiates an action with the intention to change their email address using the `FirebaseAuth.instance.currentUser.verifyBeforeUpdateEmail()` method, they get sent an email both to their current and new email addresses. At this stage, as you correctly state, the email is not updated. However, in the email sent to the current email address, the user is informed that their email address *has* changed (`Your sign-in email for %APP_NAME% was changed to %NEW_EMAIL%.`) and it also contains a link to reset the sign-in email in case of unsolicited requests (`If you didn’t ask to change your email, follow this link to reset your sign-in email.`). What the user is informed of is not entirely reflective of what is actually happening and this was the source of my confusion as to why `emailVerified` was not updated accurately. Having realised that the email address does not change until verification, I agree that this would seem like intended behaviour to have the `emailVerified` value remain `true`.

This means there is currently no native implementation that holds the state of the verified status of the new email address. A workaround would be to add some fields in e.g. Cloud Firestore to update this as the original `FirebaseAuth.instance.currentUser.verifyBeforeUpdateEmail()` method is called and once the user clicks the verification link in the email sent to their new email address. As this is unlikely to be a particularly regular occurrence for users, I guess it would be an acceptable solution. However, as this is purely to do with authentication, I would expect that the native SDK would handle this more gracefully so I will get in touch with the Firebase support team, whom you kindly referred to.
