### ISSUE TITLE
🐛 [firebase_auth] I cannot reuse AppleCredential

### ISSUE THREAD

**Issue by AlexandrFarkas** [FirebaseExtended/flutterfire#6432]
## Bug report

I use these functions to sign with apple.
```
String _generateNonce([int length = 32]) {
    const charset = '0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._';
    final random = Random.secure();
    return List.generate(length, (_) => charset[random.nextInt(charset.length)]).join();
  }

  /// Returns the sha256 hash of [input] in hex notation.
  String _sha256ofString(String input) {
    final bytes = utf8.encode(input);
    final digest = sha256.convert(bytes);
    return digest.toString();
  }

  Future<OAuthCredential> signInWithApple() async {
    // To prevent replay attacks with the credential returned from Apple, we
    // include a nonce in the credential request. When signing in in with
    // Firebase, the nonce in the id token returned by Apple, is expected to
    // match the sha256 hash of `rawNonce`.
    final rawNonce = _generateNonce();
    final nonce = _sha256ofString(rawNonce);

    // Request credential for the currently signed in Apple account.
    final appleCredential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
      nonce: nonce,
    );

    // Create an `OAuthCredential` from the credential returned by Apple.
    final oauthCredential = OAuthProvider("apple.com").credential(
      idToken: appleCredential.identityToken,
      rawNonce: rawNonce,
    );

    // Sign in the user with Firebase. If the nonce we generated earlier does
    // not match the nonce in `appleCredential.identityToken`, sign in will fail.
    return oauthCredential;
  }
```

Then I pass oauthCredential to linkWithCredential ('cause I use anonymous users)
But, if I've logged in with this apple account once, I cannot link it. And, of course, it throws FirebaseAuthException with 'credential-already-in-use'.

Next, I try to signInWithCredential, and it works perfectly with all providers, except Apple.
Apple throws 'missing-or-invalid-nonce', because I cannot reuse the same credential twice.

On pure iOS I can retrieve new credential from FIRAuthErrorUserInfoUpdatedCredentialKey, but in Flutter I can't.

**So**
How to linkWithCredential, and then, on failure, perform signInWithCredential.

Recreating Apple Credential is not a solution, because it prompts a user.

**Comment by markusaksli-nc** [comment]
Hi @AlexandrFarkas 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by AlexandrFarkas** [comment]
Flutter doctor:
'''
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-RU)
    • Flutter version 2.2.1 at /Users/alexandr/development/flutter
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alexandr/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/alexandr/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0
```

Deps:
```
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.6 [firebase_core flutter]
- firebase_messaging 10.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 8.1.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- sign_in_with_apple 3.0.0 [flutter meta]
- flutter_facebook_auth 3.3.3+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
```

**Comment by AlexandrFarkas** [comment]
There is similar issue in React Native, which I managed to find.
[Stackoverflow](https://stackoverflow.com/questions/60640378/firebase-user-merge-apple-account-into-existing-one)

**Comment by AlexandrFarkas** [comment]
@markusaksli-nc Any progress on this? Could I PR, if needed?

**Comment by markusaksli-nc** [comment]
If you feel like you know how to solve it then sure, go ahead.

**Comment by kinex** [comment]
This fixed the issue at least in my own test device:
```dart
  Future<UserCredential> _linkOrSignInWithCredential(
      AuthCredential credential) async {
    UserCredential userCredential;
    if (_auth.currentUser?.isAnonymous == true) {
      // convert current anonymous account to a permanent account
      try {
        userCredential =
            await _auth.currentUser!.linkWithCredential(credential);
      } on FirebaseAuthException catch (e, s) {
        if (e.code == 'credential-already-in-use') {
          // use e.credential to avoid error "Error missing-or-invalid-nonce."
          userCredential =
              await _auth.signInWithCredential(e.credential ?? credential);
        } else {
          rethrow;
        }
      }
    } else {
      userCredential = await _auth.signInWithCredential(credential);
    }
    return userCredential;
  }
```

**Comment by AlexandrFarkas** [comment]
@kinex You're right, it's a solution.
