### ISSUE TITLE
FCM subscribeToTopic docs do not indicate if this is required to be called at app startup everytime.

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#6434]
Looking over these docs to learn how to subscribeToTopic...

https://firebase.flutter.dev/docs/messaging/usage/#topics

Although I assume this only needs to be called once for the lifetime of the app install, it would be nice if the docs could make clear whether this is the case, or if this needs to be called everytime on application startup.

Thanks

**Comment by Patil2099** [comment]
I would love to pick this up.
