### ISSUE TITLE
Firebase Crashlytics 'getting started' guide omits platform specific required steps.

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#6447]
If you following the Flutter Firebase Crashlytics getting started guide [here](https://firebase.flutter.dev/docs/crashlytics/usage/), you will end up with a runtime crash on android.

The guide fails to mention android specific setup steps in [this guide](https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android), and fails to link to the guide, or mention it as a pre-requisite.

This is a common theme with the flutterfire 'getting started' guides. They omit required steps for getting started, and assume that the developer following the guide somehow knows about them.

**Comment by markusaksli-nc** [comment]
What exact steps are missing from https://firebase.flutter.dev/docs/crashlytics/overview ?
