### ISSUE TITLE
FirebaseMessaging.onMessage.listen trigger five times

### ISSUE THREAD

**Issue by adnankhan74444** [FirebaseExtended/flutterfire#6455]
firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2 

FirebaseMessaging.onMessage.listen((RemoteMessage event) {
      print("message recieved");
      print(event.notification.body);
    });

Print:

flutter: message recieved
flutter:please check notification
flutter: message recieved
flutter:please check notification
flutter: message recieved
flutter:please check notification
flutter: message recieved
flutter:please check notification
flutter: message recieved
flutter:please check notification

**Comment by markusaksli-nc** [comment]
Hi @adnankhan74444 
Where are you listening to `onMessage`? Are you sure you aren't just listening to it multiple times?
Thank you

**Comment by z85510** [comment]
I've same problem
