### ISSUE TITLE
firebase_auth: verifyPhoneNumber should not sign in

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#646]
I want to link phone number to my user's account.

But I can't as `verifyPhoneNumber` implicitly signs in on native side.
https://github.com/flutter/plugins/blob/6341d3a5c7b36194ab0fd50a839b363579c3eb37/packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java#L161-L176

To be consistent with other methods, it should instead return Future<`sms code`>, and report `verificationId` with callback as it might be expired while waiting for the code sent.

```dart
/// 
Future<String> verifyPhoneNumber({
  @required String phoneNumber,
  @required Duration timeout,
  int forceResendingToken,
  @required PhoneCodeSent codeSent,
  @required PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout,
}) async {}

Future<FirebaseUser> signInWithPhoneNumber({
  @required String verificationId,
  @required String smsCode,
}) async {}

Future<FirebaseUser> linkWithPhoneNumber({
  @required String verificationId,
  @required String smsCode,
}) async {
```

But this is breaking change.

**Comment by kroikie** [comment]
@kdy1

The issue at https://github.com/flutter/flutter/issues/22304 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by creativecreatorormaybenot** [comment]
@kroikie This issue is closed, obsolent.
