### ISSUE TITLE
AppCheck - no MainActivity.java file in project as per install instructions

### ISSUE THREAD

**Issue by Zelfapp** [FirebaseExtended/flutterfire#6468]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/6467

<div type='discussions-op-text'>

<sup>Originally posted by **Zelfapp** June 24, 2021</sup>
[Install instructions](https://firebase.flutter.dev/docs/app-check/usage#activating-the-debug-provider-android) mention a MainActivity.java file to update. However, my Flutter project has no MainActivity.java. The instructions need to be updated for how to handle this situation. Where do I put the MainActivity.java file if no file exists or do I update MainActivity.kt that does exist, and if so what is the code for that?

![image](https://user-images.githubusercontent.com/11559805/123290442-8387d200-d4ce-11eb-9ffa-b0f9a79a4041.png)

![image](https://user-images.githubusercontent.com/11559805/123290842-d2ce0280-d4ce-11eb-9d62-6e6e0c741da9.png)

I've tried running `flutter create .` as many SO posts have suggested, but this does not create a MainActivity.java file in the project.

The contents of my android/app/src/main/kotlin/com/mysite/myapp/MainActivity.kt file:

```
package com.mysite.myapp

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

</div>

**Comment by PaulRudin** [comment]
The suggested changes to MainActivity.java seem to be unconditional with respect to the kind of build. 

Presumably the debug app check provider should be referenced only in debug builds not release builds? But the instructions don't address how to do this.

**Comment by cedvdb** [comment]
there needs to be a kotlin snippet in the documentation as well

**Comment by russellwheatley** [comment]
Hi there, we fully accept PRs if anyone is able to produce a Kotlin sample and update the documentation. We already have an issue tracking this very problem: https://github.com/FirebaseExtended/flutterfire/issues/2311 

I'll close this and suggest a thumbs up for that issue. Thanks.
