### ISSUE TITLE
[firebase_analytics] update example with new event to log screenview

### ISSUE THREAD

**Issue by Gonzaa25** [FirebaseExtended/flutterfire#6470]
The method **setCurrentScreen** is deprecated. 
The example lib only has the old method and needs to be updated with the new logEvent.

- code that needs an update

` await widget.analytics.setCurrentScreen(
      screenName: 'Analytics Demo',
      screenClassOverride: 'AnalyticsDemo',
    );
`

[Docs with deprecated and new method](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#logEvent(java.lang.String,%20android.os.Bundle))

[Actual package docs in pub.dev](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/setCurrentScreen.html)

**Comment by russellwheatley** [comment]
We have now updated the analytics API to match the latest. Please see the [changelog](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/CHANGELOG.md#900) for the latest. Thanks.

**Comment by Gonzaa25** [comment]
Awesome , Thanks @russellwheatley !
