### ISSUE TITLE
[📚] [firebase_messaging] [SNS] [iOS] Update Documentation for Flutter Messaging backgroundHandling on iOS

### ISSUE THREAD

**Issue by S4b3** [FirebaseExtended/flutterfire#6477]
Hello, I've been struggling for some time now with the `onBackgroundMessage` notification handler for iOS.
We're currently using AWS SNS to trigger notifications and apparently it uses deprecated HTTP APIs.
I came accross multiple issues opened on this repo regarding the same problem with people receiving their notification but not seeing the handler trigger.

After trying multiple solutions I found out that the only way to trigger handling on iOS was adding the following line inside the firebase message:
` "content_available":true `
leading to this as notification's body:

```
"notification": {
    body: event.body,
    title: event.title,
    "content_available": true
  },
    "data": event.data,
    "android": {
      "priority": "high"
    },
      "apns": {
        "headers": {
          "apns-priority": "10",
        }
      },
      "webpush": {
        "headers": {
          "Urgency": "high"
        }
      }
```
      
This line has not been very easy to find in the repo's documentation and it's the only way to make ios handling work.
Given that this problem is being referenced in #6320 #6290 #6112 #6077 and many more I'd like to suggest considering to dedicate a section to it to ensure it doesn't go unnoticed.

**Comment by param-thakker** [comment]
@S4b3 Were you able to find this snippet of code?

**Comment by russellwheatley** [comment]
Hey @S4b3, thanks for the suggestion. We have now included this in the [server integration](https://firebase.flutter.dev/docs/messaging/server-integration#using-tokens) aspect of our documentation.
