### ISSUE TITLE
🐛 [firebase_crashlytics] can't add Crashlytics to IOS

### ISSUE THREAD

**Issue by Tom3652** [FirebaseExtended/flutterfire#6479]
## Bug report

**Describe the bug**
The Crashlytics page in Firebase console is never showing for IOS app.
Here is the loading status always loading :
![image](https://user-images.githubusercontent.com/32631467/123491553-3bc09200-d617-11eb-914e-1ccc37b824ac.png)

### Steps to reproduce

1. Create a new Firebase project
2. Create a new Flutter project and add the [firebase_crashlytics](https://pub.dev/packages/firebase_crashlytics)  package
4. Follow this IOS config from the [documentation](https://firebase.flutter.dev/docs/crashlytics/overview/) : 
- From Xcode select Runner from the project navigation. 
- Select the Build Phases tab, then click + > New Run Script Phase.
- Add ${PODS_ROOT}/FirebaseCrashlytics/run to the Type a script... text box.
5. Follow the [documentation](https://firebase.flutter.dev/docs/crashlytics/usage) until the "Sending reports to Crashlytics" title (included) 
6. After crashing your app, restarting your app, see that Crashlytics is still loading in the Firebase Console.

### Expected behavior

See the Crashlytics dashboard page for the IOS app as we can see it for Android, with the first Crashlytics forced crash registered.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.3
Flutter SDK 2.2.2
testproject 1.0.0+1

dependencies:
- firebase_crashlytics 2.0.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.6 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0

```

</details>

---

**Comment by 159159951** [comment]
My case is the same!

**Comment by seanyyyyyy** [comment]
Hey guys, I can confirm I did eventually get crashlytics working on iOS in the last week or so after facing similar issues initially

from memory i did some extra things that were in the Firebase documentation that weren't mentioned on the flutterfire page:
e.g. add updated GoogleService-Info.plist 
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=ios#add-config-file

so yeah i would suggest go through these docs and try some of the iOS specific stuff https://firebase.google.com/docs/crashlytics/get-started?platform=ios

**Comment by EArminjon** [comment]
I did all the steps rights and problem still present. It's a major issue

**Comment by Tom3652** [comment]
I have reached out the firebase support and followed the steps they provided me (with debug enabled).
Awaiting for they answer as it is still not working so far, i will update the answer here if there is any

**Comment by EArminjon** [comment]
I found the solution. I read somewhere that we need to trick a little to call Firebase crash on iOS. So, just call Firebase recordReport, wait 3 min and you will see the report on your dashboard.

**Comment by Tom3652** [comment]
I have done your good suggestion but it's still loading :

```
await FirebaseCrashlytics.instance.recordError("Record error to Crashlytics", StackTrace.fromString("No StackTrace."), reason: "Init Crashlytics !");
```

And in the logs i can see : 

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: The following exception was thrown Init Crashlytics !:
flutter: Record error to Crashlytics
flutter: 
No StackTrace.
flutter: ----------------------------------------------------
```

I will add this comment to the Firebase ticket i have already made

**Comment by EArminjon** [comment]
Now close and reopen your app. Report record are send when the app is reopen

**Comment by Tom3652** [comment]
You are right ! 
Thanks again for your help i can see the dashboards now

**Comment by EArminjon** [comment]
Nice ! This must be added to the documentation.

**Comment by faslurrajah** [comment]
Make sure to disconnect the simulator from the Xcode debugger to see crashes in the Firebase console

**Comment by jaibyron** [comment]
I've tried the

> Nice ! This must be added to the documentation. https://firebase.flutter.dev/docs/crashlytics/usage
> 
> ```dart
> /* Tuto
> ** To activated your firebase dashboard, add this in your homepage initState.
> ** Open your app, execute this code and close it. When you will reopen it the record will be send to Firebase.
> ** Wait then 3minutes and you will see your dashboard <3
> */
> try {
>   throw Exception("Crash test");
> } catch (error, stack) {
>   FirebaseCrashlytics.instance.recordError(error, stack, reason: "Test");
> }
> ```

Have followed the steps at - https://firebase.flutter.dev/docs/crashlytics/overview/

and also tried the suggestion for throwing the crash and waiting 3 mins but am still not getting the dashboard... any ideas what I might be missing. Works fine for Android with no issue... :-/

**Comment by jaibyron** [comment]
@darshankawar - I'm still having an issue with this on iOS after following the guidance at: https://firebase.flutter.dev/docs/crashlytics/overview/

and also following the solution(s) suggested.

Can you provide any assistance to help me move forward?

**Comment by TharaniP** [comment]
> I have done your good suggestion but it's still loading :
> 
> ```
> await FirebaseCrashlytics.instance.recordError("Record error to Crashlytics", StackTrace.fromString("No StackTrace."), reason: "Init Crashlytics !");
> ```
> 
> And in the logs i can see :
> 
> ```
> flutter: ----------------FIREBASE CRASHLYTICS----------------
> flutter: The following exception was thrown Init Crashlytics !:
> flutter: Record error to Crashlytics
> flutter: 
> No StackTrace.
> flutter: ----------------------------------------------------
> ```
> 
> I will add this comment to the Firebase ticket i have already made

@EArminjon :  I can able to see the crashlogs in dashboard. But still could not see the detailed crash information.

And also i am getting this banner to Upload missing required dSYMs -> "Customers with bitcode-enabled apps have again reported that some dSYMs downloaded from App Store Connect are missing required UUIDs for a build. This may prevent crashes from appearing on the dashboard. We are looking into the re-emergence of this issue."

Please provide some information.

**Comment by LiorAgnin** [comment]
> add
> 
> ```
> try {
>   throw Exception("Crash test");
> } catch (error, stack) {
>   FirebaseCrashlytics.instance.recordError(error, stack, reason: "Test");
> }
> ```
> 
> then change `platform :ios, '10.0'` in Podfile work for me
 
Thanks, @cuong1112035 it works for me now. But unfortunately, another dependency needs ios 11.

**Comment by russellwheatley** [comment]
We do indicate how to see crash reports on the usage page of the docs [here](https://firebase.flutter.dev/docs/crashlytics/usage#sending-reports-to-crashlytics). To get setup, you can also follow the example app setup [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart). Will close for now as I don't believe there is anything more to action here.
