### ISSUE TITLE
🐛 [firebase_messaging] onBackgroundMessage breaks hot reload on vscode

### ISSUE THREAD

**Issue by tijanirf** [FirebaseExtended/flutterfire#6480]
## Bug report

I'm using `firebase_messaging 10.0.2` and already followed the [documentation](https://firebase.flutter.dev/docs/messaging/usage). My second hot reload always stuck and the further code changes will not be reflected in the app if I add `FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);`

The hot reload is working fine if i'm not using `FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);`.

### Steps to reproduce

1. Run the app in debug mode
2. Edit some text in the widget and save it, the text on the widget is updated.
3. Edit some text again in the widget and save it, the text on the widget is not updated. The hot reload indicator is showing and not disappear. 
<img width="508" alt="Screen Shot 2021-06-26 at 6 48 23 AM" src="https://user-images.githubusercontent.com/35812470/123494569-83144600-d64a-11eb-98b1-53b8fcbb4af2.png">
4. The further changes will not be reflected on the app

### Expected behavior

The hot reload will always work even I add `FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);`.

---

## Additional context

I notice two things that mentioned on the docs:

> Since the handler runs in its own isolate outside your applications context, it is not possible to update application state or execute any UI impacting logic. You can however perform logic such as HTTP requests, IO operations (updating local storage), communicate with other plugins etc.

and

> FlutterFirebase Messaging does now support debugging and hot reloading for background isolates, but only if your main isolate is also being debugged, e.g. run your application in debug and then background it by switching apps so it's no longer in the foreground.

I think this is the reason why the call stack shows two stacks on my screenshot, but I don't think it should be breaking the hot reload. I honestly not sure if this is the problem on the vscode side or the firebase side, please kindly correct me if I'm wrong. By the way, I haven't checked the behavior on the Android Studio.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel unknown, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at /Users/tijanirijalfadhilah/fvm/versions/2.2.1
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tijanirijalfadhilah/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Mi A2 Lite (mobile) • 4d5472090405 • android-arm64  • Android 9 (API 28)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 91.0.4472.114
```

</details>

---

**Comment by darshankawar** [comment]
@tijanirf 
There's similar open issue describing your case, https://github.com/FirebaseExtended/flutterfire/issues/4316
Please follow-up there for updates.
Also, per this comment, this was working on dev channel, so you may want to switch to latest dev and try again to see if it works or not. Accordingly you may comment in the original issue.

Closing this as duplicate.

**Comment by navalpatel5** [comment]
This is occurring with firebase_messaging: 10.0.0 to 10.0.4 with Android studio also. It is also happening when hotreloading using CLI.
