### ISSUE TITLE
🐛 [Core] Unable to set FirebaseOptions at runtime

### ISSUE THREAD

**Issue by sima-11** [FirebaseExtended/flutterfire#6490]
## Bug report

**Describe the bug**
I have `GoogleService-info.plist` and `google-service.json` embedded properly in the project (works as expected).
Then I was also trying to use `Firebase.initializeApp(options:)` to set a different set of configurations manually during app launch via `initState()` of the root `StatefulWidget`, in order to enable the app with multiple environments. But the configurations being picked up were always what was written in the physical google service files.

### Steps to reproduce

1. Add `GoogleService-info.plist` and `google-service.json` to the iOS and Android project as per described in the documentation.
2. In the root `StatefulWidget`, do
```
final app = await Firebase.initializeApp(options: {OPTIONS});
FirebaseAuth.instanceFor(app: app);
```
3. Go through standard username and password sign up process

### Expected behavior

User is registered under the corresponding environment

---

### Additional Questions

I think this might be expected behaviour. But if that is the case, when and where should `initializeApp(options:)` be used? Besides, based on what the physical file contains, it seems more of less a replicate of `FirebaseOptions`. Not sure why having this physical file is mandatory?

---

**Comment by darshankawar** [comment]
@sima-11 
I believe there's similar open discussion describing your case, https://github.com/FirebaseExtended/flutterfire/discussions/5626. Please follow-up there for updates and any questions you may have.

Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by sima-11** [comment]
@darshankawar Thanks for coming back to me. I checked the thread you suggested, but it was quite old (almost a year ago). I was using the latest package (version 1.3.0), but it didn't seem to allow me changing environment at runtime.

As I couldn't find info about whether this has been completed, some guidance would be very helpful (Also some confirmation about whether we can ditch the physical config file would also be quite helpful. As currently it seems a bit confusing).

If the feature is ready to use, there might then be a bug with it?

**Comment by sima-11** [comment]
@darshankawar Just to follow up and see if there's any update.

**Comment by sima-11** [comment]
@darshankawar It's been 11 days, man.

**Comment by sima-11** [comment]
Guys, is it common to wait for 21 days for a reply?
