### ISSUE TITLE
🐛 [firebase_auth] Firebase auth User is still logged in after uninstalling application IOS

### ISSUE THREAD

**Issue by Tom3652** [FirebaseExtended/flutterfire#6491]
## Bug report

**Describe the bug**
The ```FirebaseAuth.instance.currentUser``` is not null after the IOS app is uninstalled.

### Steps to reproduce

1. Setup a new Flutter project with Firebase 
2. Enable Firebase authentication (i can reproduce this regardless of the auth provider used, Google Sign in & EmailPassword methods for sure)
4. Run the app on IOS device and log in with an account 
5. Uninstall app (remove app) from the IOS device home screen. 
6. Rebuild the app and see the user still logged.

### Expected behavior

I expect that the ```FirebaseAuth.instance.currentUser``` is null (signed out) after the IOS application is removed.

### Sample project

The "longer" part of the setup is to make a new Firebase project and add the ```GoogleService-Info.plist```.
The Auth account can be created through the Firebase Console so no need more code.

This can look like this : 
```

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {

  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  
  @override
  void initState() {
    print(FirebaseAuth.instance.currentUser);
    FirebaseAuth.instance.signInWithEmailAndPassword(email: email, password: password);
    super.initState();
  }
  
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

## Additional context

After the first run, you can comment the ```FirebaseAuth.instance.signInWithEmailAndPassword(email: email, password: password);``` before uninstalling / rebuilding the app and then see in the logs the ```FirebaseAuth.instance.currentUser``` non null.
I will add that despite that the user is non null locally, the ```request.auth.uid``` in ```Firestore``` seems to be indeed null : 

```[cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.```

Also, i am seeing this log : ```8.0.0 - [Firebase/Auth][I-AUT000016] Invalid user token detected, user is automatically signed out.``` a bit later but my ```FirebaseAuth.instance.authStateChanges()``` ```Stream<User?>``` is not called, so i have an old user logged.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (4 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.3
Flutter SDK 2.2.2
test_ios_auth 1.0.0+1

dependencies:
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.3.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.3.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by AlexandrFarkas** [comment]
Why you expect this? Users' credentials are stored in KeyChain, which is not cleared after app uninstall.

**Comment by Tom3652** [comment]
Because i would like to make a new login session if the user has uninstalled the app and re install it.
It was even working like this not so long ago, speaking about the begining of year of i am not mistaken.

I have added a comment in the **Additional Context** section to specific that the user is actually logged out in the backend (because ```[cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.``` 
So user is non null locally, but my Firestore security rules prevent queries if ```request.auth.uid``` is null.

**Comment by darshankawar** [comment]
@Tom3652 
Can you try by using the `setPersistence()` method and and pass `NONE` value to it and see if it helps ?

https://firebase.flutter.dev/docs/auth/usage/#persisting-authentication-state

Also check [this](https://stackoverflow.com/a/27894791) SO link for further reference.

**Comment by Tom3652** [comment]
Well if this is the normal behaviour, i will adapt my code and dig into the error i am getting.
Thanks for the suggestion and the provided links but i am aware about this method and I want the ```persistence``` to be enabled anyway

**Comment by Tom3652** [comment]
I have made some changes in my code to adapt the behavior i wanted and it's working now, since i am not able to reproduce the denied permission with ```Cloud Firestore``` i assume there is no issue with ```firebase_auth```.
I am closing this, thanks for your replies !
