### ISSUE TITLE
🐛 [firebase_messaging] await FirebaseMessaging.instance.requestPermissions() always return AuthorizationStatus.authorized in android even though notifications are disabled on os level settings

### ISSUE THREAD

**Issue by vemarav** [FirebaseExtended/flutterfire#6492]
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 2.2.2 at /Users/vemarav/.flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vemarav/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/vemarav/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/vemarav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • CE628EC3-20A1-4B08-B337-DBE539FC1594 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3
      (simulator)

• No issues found!

firebase_analytics: ^7.1.1
firebase_core: ^1.0.1
firebase_dynamic_links: ^0.8.0
firebase_messaging: ^9.1.0

**Comment by darshankawar** [comment]
> firebase_analytics: ^7.1.1
> firebase_core: ^1.0.1
> firebase_dynamic_links: ^0.8.0
> firebase_messaging: ^9.1.0

@vemarav 
I see that you are using old versions of above listed plugins. I suggest you to upgrade all firebase plugins to latest and greatest versions and try again to see if it helps.

If not, please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue.
Thanks.
