### ISSUE TITLE
Firebase 6.7.0 crash hard_assert_apple.mm line 34

### ISSUE THREAD

**Issue by anatter** [FirebaseExtended/flutterfire#65]
I have the same issue in our flutter app as described here: [#3678](https://github.com/firebase/firebase-ios-sdk/issues/3678)

Crashlytics report:
`
Fatal Exception: NSInternalInconsistencyException
FIRESTORE INTERNAL ASSERTION FAILED: Expected to be called by the executor associated with this queue (expected executor: 'com.google.firebase.firestore', actual executor: 'com.apple.main-thread') (expected executor_->IsCurrentExecutor())
`

**Comment by gasperipi** [comment]
@anatter  
Updating the dependencies to the newest version _cloud_firestore: ^0.12.9+2_ in the pubspec.yaml file solved this problem for me.

**Comment by BondarenkoStas** [comment]
@anatter Please report if @gasperipi comment solved the issue

**Comment by anatter** [comment]
> 
> 
> @anatter Please report if @gasperipi comment solved the issue

Yes this solved the issue.
