### ISSUE TITLE
🐛 [firebase_messaging] The onMessage callback is called once, but notification comes up two times on foreground only. This bug happens only in iOS

### ISSUE THREAD

**Issue by Jaeki-Lee** [FirebaseExtended/flutterfire#6500]
**Describe the bug**
The onMessage callback is called once, but notification comes up two times on foreground only.
This bug happens only in iOS

**To Reproduce**

- With our message system 
1.Setup the plugin, A send message to B. 
2.Server sends a FCM message
3.onMessage callback and make notification with flutterLocalNotificationsPlugin.show() method 
4.Notification two times come up

- With firebase console 
1.Setup the plugin, send notification through Firebase console 
2.onMessage callback. However, I block flutterLocalNotificationsPlugin.show() if the signal come from Firebase console
3.Notification shows up one time

*FirebaseMessaging.onBackgroudMessage() / FirebaseMessaging.onMessage.listen() call the same method showNotification()

*In showNotification() flutterLocalNotificationsPlugin.show() method is used;

*In the background, the behavior is correct. However, on foreground notification comes up two times.

**Expected behavior**
- With our message system 
flutterLocalNotificationsPlugin.show() method makes a notification and the notification comes up one time.

- With firebase console
FirebaseMessaging.onMessage.listen -> showNotification() called, but flutterLocalNotificationsPlugin.show() is not called. Therefore, no notification come up

**Additional context**
If I make condition only platform is android call the method flutterLocalNotificationsPlugin.show() then, it makes notification only one time in foreground and background in iOS, but I don’t believe it is correct solution

**Comment by darshankawar** [comment]
@Jaeki-Lee 
Can you provide `flutter doctor -v`, `flutter pub deps -- --style=compact` and a minimal complete code sample ?

Also, does it work with `onResume` and `onLaunch` ?

**Comment by Jaeki-Lee** [comment]
**flutter doctor -v**

[✓] Flutter (Channel dev, 2.3.0-24.0.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-KR)
    • Flutter version 2.3.0-24.0.pre at /Users/jaekilee/root/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (3 weeks ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • SM N970U1 (mobile)     • R38M60EDGWK                              • android-arm64  • Android 11 (API
      30)
    • jaeki의 iPhone (mobile) • ca658c8479a257b72327ff4cc2c13213e0d55b4b • ios            • iOS 14.4.2
    • iPhone 11 Pro (mobile) • 2404DAF0-4346-486E-A00C-9E4BF42AB0EA     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome
      91.0.4472.114

**flutter pub deps -- --style=compact**
Dart SDK 2.14.0-188.0.dev
Flutter SDK 2.3.0-24.0.pre
seal_business 1.0.0+1

dependencies:
- barcode_scan_fix 1.0.2 [flutter]
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- connectivity 3.0.6 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- contacts_service 0.4.6 [flutter collection quiver]
- country_code_picker 1.7.0 [flutter modal_bottom_sheet]
- downloads_path_provider 0.1.0 [flutter]
- encrypt 4.0.2 [args asn1lib clock collection crypto pointycastle]
- exif 1.0.3 [args collection convert sprintf]
- file_picker 1.4.3+2 [flutter]
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 0.5.3 [flutter]
- firebase_messaging 10.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cupertino_localizations 1.0.1 [flutter flutter_localizations]
- flutter_downloader 1.6.1 [flutter]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_local_notifications 6.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_slidable 0.5.7 [flutter]
- flutter_sms 2.3.1 [flutter flutter_web_plugins plugin_platform_interface url_launcher]
- gallery_saver 2.1.0 [flutter path_provider http path]
- http 0.13.3 [async http_parser meta path pedantic]
- image_picker 0.8.0+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- linkable 1.0.9 [flutter url_launcher]
- open_file 2.1.1 [flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 4.3.0 [flutter meta]
- qr_flutter 3.2.0 [flutter qr]
- rxdart 0.23.1
- screenshot_callback 1.1.1 [flutter permission_handler]
- sqflite 1.3.2+4 [flutter sqflite_common path]
- uuid 2.0.4 [crypto convert]
- video_player 2.1.6 [flutter flutter_test meta video_player_platform_interface video_player_web]
- video_thumbnail 0.2.5+1 [flutter]
- wc_flutter_share 0.4.0 [flutter path_provider]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webview_flutter 0.3.24 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- cupertino_icons 1.0.3
- intl 0.17.0 [clock path]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.6.5
- async 2.7.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- connectivity_for_web 0.4.0 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 4.3.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.3.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_platform_interface 4.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.4.0
- modal_bottom_sheet 1.0.0+1 [flutter]
- nested 1.0.0 [flutter]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pointycastle 1.0.2
- process 4.2.1 [file path platform]
- provider 5.0.0 [collection flutter nested]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sprintf 4.1.0
- sqflite_common 1.0.3+3 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0
- test_api 0.4.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.5.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.1.0+1 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+1 [flutter meta]
- wakelock_web 0.2.0+1 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- win32 2.1.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

**Comment by Jaeki-Lee** [comment]
**Background notification setting**
Future<void> preloadRequirements() async {
    …
    FirebaseMessaging.onBackgroundMessage(_backgroundHandler);
    …
  }

Future<void> _backgroundHandler(RemoteMessage remoteMessage) async {
  await NotificationHelper.showNotification(remoteMessage);
}

**Foreground notification setting**
static Future<void> init(Function(String) onSelectNotification) async {
    …
    FirebaseMessaging.onMessage.listen(showNotification);
    …
 }

static Future<void> showNotification(RemoteMessage remoteMessage) async {

     …
     /*
	**Code that iOS two notification bug**
     */
      await flutterLocalNotificationsPlugin.show(
        int.parse(chatroomId),
        title,
        message,
        secondNotificationPlatformSpecifics,
        payload: chatroomId,
      );
   
    /*
	**For testing firebase console code, notification come from console 
	the if statement is null and not call flutterLocalNotificationsPlugin.show method**
    */
     if (int.parse(remoteMessage.data['chatroomId']) != null) {
        await flutterLocalNotificationsPlugin.show(
          int.parse(chatroomId),
          title,
          message,
          secondNotificationPlatformSpecifics,
          payload: chatroomId,
        );
      }

   /*
	**Temporarily fixed code iOS notification two times bug**
   */
     if (Platform.isAndroid) {
        await flutterLocalNotificationsPlugin.show(
          int.parse(chatroomId),
          title,
          message,
          secondNotificationPlatformSpecifics,
          payload: chatroomId,
        );
      }
}

**Comment by darshankawar** [comment]
> does it work with `onResume` and `onLaunch` ?

@Jaeki-Lee 
I wanted to know if you receive notification when app is in background, or only when it is in foreground ?

Can you also try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) with your setup and see if you still get same behavior ?

**Comment by Jaeki-Lee** [comment]
The two notification happen only in foreground.

I tried with the official plugin example and it was work fine but when I change code like this, then the notification happen two times in iOS

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      RemoteNotification notification = message.notification;
      AndroidNotification android = message.notification?.android;

      flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            channel.id,
            channel.name,
            channel.description,
            // TODO add a proper drawable resource to android, for now using
            //      one that already exists in example app.
            icon: 'launch_background',
          ),
        ),
      );
      
      if (notification != null && android != null && !kIsWeb) {}
    });

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('A new onMessageOpenedApp event was published!');
      Navigator.pushNamed(context, '/message',
          arguments: MessageArguments(message, true));
    });
  }

**Comment by darshankawar** [comment]
@Jaeki-Lee 
Can you try [this](https://github.com/FirebaseExtended/flutterfire/issues/6210#issuecomment-847824299) solution and see if it works ?

Also, I believe your issue is very similar to the one I linked.

**Comment by imrhk** [comment]
I am also having this issue.

**Comment by singhayush1403** [comment]
I also have this issue. Any fix?

**Comment by emreakcadag** [comment]
I am having the same issue. using firebase_messaging 10.0.4. Android works perfect but ios shows an alert on foreground. But should not show any alert, I already handle the showing or not logic with flutter_local_notifications

**Comment by emreakcadag** [comment]
I found the solution:
It was too obvious :D

`await instance.setForegroundNotificationPresentationOptions(alert: false, badge: true, sound: true);`

**alert** parameter should be false if you do not want FCM to handle foreground alerts.
