### ISSUE TITLE
🐛 [cloud_firestore] Can we use json_serializable package to serialize and deserialize user models?

### ISSUE THREAD

**Issue by jagadishnallappa** [FirebaseExtended/flutterfire#6502]
After generating part 'UserModel.g.dart'; successfully, I  got the following error upon trying to do  

```
if (user != null) {
      var uid = user.providerData.first.uid;
      var displayName = user.providerData.first.displayName;
      var email = user.providerData.first.email;
      var phoneNumber = user.providerData.first.phoneNumber;
      var providerId = user.providerData.first.providerId;
      var photoUrl = user.providerData.first.photoURL;
      UserModel userModel = UserModel(phoneNumber,
          uid: uid,
          displayName: displayName,
          email: email,
          providerId: providerId,
          photoUrl: photoUrl);
      Query query = users.where('uid', isEqualTo: uid);
      query.get().then((querySnapshot) => {
            if (querySnapshot.size < 1) {addUser(userModel)}
          });
    }
  }
```

And here is my UserModel.dart without any errors in the file.

import 'package:json_annotation/json_annotation.dart';

part 'UserModel.g.dart';

```
@JsonSerializable()
class UserModel {
  late String? uid;
  late String? displayName;
  late String? email;
  late String? phoneNumber;
  late String providerId;
  late String? photoUrl;

  UserModel(this.phoneNumber, {required this.uid, required this.displayName, required this.email,
      required this.providerId, required this.photoUrl});
  factory UserModel.fromJson(Map<String, dynamic> json) => _$UserModelFromJson(json);
  Map<String, dynamic> toJson() => _$UserModelToJson(this);
}
```

Offcourse, I could manually map each value. But as recommended here https://flutter.dev/docs/development/data-and-backend/json, to prevent 

> Manual decoding does not perform well when your project becomes bigger. Writing decoding logic by hand can become hard to manage and error-prone. If you have a typo when accessing a nonexistent JSON field, your code throws an error during runtime.

I used the plugin json_serializable to sort of automate it. 
But I got the following error:
Expected a value of type 'Map<String, dynamic>', but got one of type 'UserModel$'

Is this error expected due to incompatibility or am I doing something wrong? Please respond. Thank you very much. :)

**Comment by darshankawar** [comment]
@jagadishnallappa 
Your question is better suited for support channels like StackOverflow. Please see https://flutter.dev/community for resources.
Also, you can open this issue in plugin's dedicated repo to get more help: https://github.com/google/json_serializable.dart/issues

Closing from here, as this doesn't seem to be firestore specific issue.
