### ISSUE TITLE
🐛 [firebase_messaging] onBackgroundMessage is not getting called on iOS.

### ISSUE THREAD

**Issue by deepak786** [FirebaseExtended/flutterfire#6515]
In iOS when the app is in the background 

1. if we send a notification from the server then the notification is displayed but the `onBackgroundMessageHandler` is not called.
2. if we send a data message from the server then that is also not received as the `onBackgroundMessageHandler` is not called.

Below is the code to send the data message to the device.

```
function sendDueDateNotification(){
  // notification topic
  var topic = "due_date_12_11_2020";
  var type = "Due Date";
  var tag = "DUE_DATE";

  // message to send
  var message = {
    data: {
      tag: tag,
      topic: topic,
      type: type,
      title: 'O vencimento é amanhã!',
      body: 'Se já pagou, fique tranquilo(a).',
    },
    android: {
      ttl: 24*60*60*1000, // 1 day expiration (milliseconds)
      priority: 'normal',
    },
    apns: {
      payload: {
        aps: {
          contentAvailable: true,
        }
      },
      headers: {
        "apns-push-type": "background",
        "apns-priority": "5", // Must be `5` when `contentAvailable` is set to true.
        "apns-topic": "bundle_id", // bundle identifier,
      },
    },
    topic: topic
  };

  admin.messaging().send(message).then((response) => {
    // Response is a message ID string.
    console.log('Successfully sent message:', response);
  });
}
```

Here is the sample code where the above issues are reproducible https://github.com/deepak786/flutter_notifications_issue

**Comment by balinux** [comment]
For iOS; you must have a physical iOS device to receive messages.

Firebase Cloud Messaging integrates with the Apple Push Notification service (APNs), however APNs only works with real devices.

I've run it on the physical iOS device but still not working

**Comment by deepak786** [comment]
Ofcourse I have tested it on real device. 
That's why Im receiving the notifications. But the issue is onBackgroundHandler is not getting called.

**Comment by darshankawar** [comment]
@deepak786 
There's similar open issue describing your case, ie, `onBackgroundMessage` is not invoked when app is in background, https://github.com/FirebaseExtended/flutterfire/issues/6290.
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
