### ISSUE TITLE
🐛 [cloud_firestore] Invalid argument error when querying using a WithConverterDocumentReference

### ISSUE THREAD

**Issue by JPGarCar** [FirebaseExtended/flutterfire#6528]
## Bug report

**Describe the bug**
When trying the following query (using object names for clarification):
`Query.where('fieldname', isEqualTo: DocumentReference<Object>).snapshots()`
I get the following ArgumentError:
`Invalid argument (dartObject): Could not convert: Instance of '_WithConverterDocumentReference<Team>'`

I am querying a collection group where a field is equal to a document reference. In firestore the collection group documents have the field with the reference type.

I am using withConverter() in this project for both the collection group and the document reference I am using in the query.

### Steps to reproduce

The complete query code is:
```
FirebaseFirestore.instance
         .collectionGroup(this._name)
         .withConverter<T>(
          fromFirestore: this._fromFirestore,
          toFirestore: this._toFirestore
        ).where(
            'team', 
             isEqualTo: FirebaseFirestore
                .instance.collection('races').doc('storm the wall 2021')
                .collection('teams')
                .withConverter<Team>(
              fromFirestore: (snapshot, _) => Team.fromJson(snapshot.id, snapshot.data()!),
              toFirestore: (team, _) => team.toJson(),
            ).doc(id)
          ).snapshots()
```

### Expected behavior

I expected to get a snapshot of the query results.

### Sample project

It would be hard to show a sample project since there are a lot of different classes and files in play, but here is the repo: https://github.com/JPGarCar/stw_timing_web_app/tree/firebase-update

The reference I am searching for has a class of [Team.dart](https://github.com/JPGarCar/stw_timing_web_app/blob/firebase-update/lib/models/objects/Team.dart) problem is in line 40,
which extends [FirestoreCollectionObject.dart](https://github.com/JPGarCar/stw_timing_web_app/blob/firebase-update/lib/models/firestore/FirestoreCollectionObject.dart) which extends [FirestoreObject.dart](https://github.com/JPGarCar/stw_timing_web_app/blob/firebase-update/lib/models/firestore/FirestoreObject.dart)

The collection group I am searching on has a class of [RunCollection.dart](https://github.com/JPGarCar/stw_timing_web_app/blob/firebase-update/lib/models/collections/RunCollection.dart)
which extends [FirestoreCollectionGroup.dart](https://github.com/JPGarCar/stw_timing_web_app/blob/firebase-update/lib/models/firestore/FirestoreCollectionGroup.dart)

---

## Additional context

I used debug console to find the problem in line 40 of Team.dart. 

When I change the query object being searched to something else, like a string, there are no errors thrown.

Thank you in advance, and let me know if you need more access or more information!

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [Version 10.0.19042.1052], locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.9.0)
[√] Android Studio (version 4.2.0)
[√] VS Code (version 1.57.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0-188.5.beta
Flutter SDK 2.3.0-24.1.pre
race_timing_app 1.0.0+1

dependencies:
- cloud_firestore 2.3.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- date_time_format 2.0.1
- file_picker 3.0.3 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_auth 2.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- spreadsheet_decoder 2.0.0 [archive xml]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.7.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.2.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.2.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 2.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.4.0
- path 1.8.0
- petitparser 4.1.0 [meta]
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- xml 5.1.2 [collection meta petitparser]

```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @JPGarCar 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/6369.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
