### ISSUE TITLE
Firestore runTransaction timeout does not stop the transaction

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#653]
If you run a transaction with a timeout, when the timeout function runs, the transaction will still try its 5 attempts.

```
await Firestore.instance.runTransaction((Transaction tx) async {
          DocumentSnapshot postSnapshot = await tx.get(postRef);
          if (postSnapshot.exists) {
            await tx.update(postRef, mapData);
          }
        }).timeout(Duration(seconds: 5),onTimeout: (){throw("Timeout trying to update, maybe you're offline");});
```

To test: 

1. Turn off Wifi
2. Try to update
3. Wait for timeout
4. Turn Wifi on quickly
5. The update goes through to firestore

If you wait 25+ seconds before turning Wifi back on, it won't go through.

**Comment by kroikie** [comment]
@holyspidoo

The issue at https://github.com/flutter/flutter/issues/22140 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing based on https://github.com/flutter/flutter/issues/22140#issuecomment-475029809
