### ISSUE TITLE
🐛 FCM apns not ready yet

### ISSUE THREAD

**Issue by cogniantpavan** [FirebaseExtended/flutterfire#6530]
Getting error APNS not ready yet, Android notifications working fine, just ios giving error while generating registration id, APNS not ready yet, wait for APNS to be ready and retry.. tried it many times but no success

**Comment by markusaksli-nc** [comment]
Hi @cogniantpavan 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
