### ISSUE TITLE
I am unable solve error for more than 2 hours

### ISSUE THREAD

**Issue by danealbrain** [FirebaseExtended/flutterfire#6531]
type 'List<dynamic>' is not a subtype of type 'String'

here is my code

main.dart

```dart
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

FirebaseFirestore firestore = FirebaseFirestore.instance;
class HomePage extends StatefulWidget {
  const HomePage({ Key? key }) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  final Stream<QuerySnapshot> _jamatStream = FirebaseFirestore.instance.collection('Jamat').snapshots();
  //  late final List<String> Names;
  @override
  Widget build(BuildContext context) {
    return Scaffold(

        appBar: AppBar(
          title: Text("Home"),
          centerTitle: true,
          actions: [
            IconButton(onPressed: null, icon: Icon(Icons.exit_to_app))
          ],
        ),
        body: SafeArea(
          child: StreamBuilder(
            stream: _jamatStream,
            builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot){
                if (snapshot.hasError) {
                  return Text("Something went wrong");
                }

                if (snapshot.connectionState == ConnectionState.waiting) {
                  return Text("Loading");
                }

                return new ListView(
                  children: snapshot.data!.docs.map((document)
                  {
                      return Center(
            child: Container(
              width: MediaQuery.of(context).size.width / 1.2,
              height: MediaQuery.of(context).size.height / 6,
              child: Text("Title: " + document['name']),
            ),
          );
        }).toList(),
                );
            },
          ),
        ),

    );
  }
}
```

**Comment by danealbrain** [comment]
main.dart

import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

FirebaseFirestore firestore = FirebaseFirestore.instance;
class HomePage extends StatefulWidget {
  const HomePage({ Key? key }) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  final Stream<QuerySnapshot> _jamatStream = FirebaseFirestore.instance.collection('Jamat').snapshots();
  //  late final List<String> Names;
  @override
  Widget build(BuildContext context) {
    return Scaffold(

        appBar: AppBar(
          title: Text("Home"),
          centerTitle: true,
          actions: [
            IconButton(onPressed: null, icon: Icon(Icons.exit_to_app))
          ],
        ),
        body: SafeArea(
          child: StreamBuilder(
            stream: _jamatStream,
            builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot){
                if (snapshot.hasError) {
                  return Text("Something went wrong");
                }

                if (snapshot.connectionState == ConnectionState.waiting) {
                  return Text("Loading");
                }

                return new ListView(
                  children: snapshot.data!.docs.map((document)
                  {
                      return new ListTile(
                        title: new Text(document['name']),
                      );
                  }).toList(),
                );
            },
          ),
        ),

    );
  }
}

**Comment by danealbrain** [comment]
[flutter] flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\khalid khira\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\khalid khira\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • RMX2001 (mobile) • KZ69Q49DFYUOROX4 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 91.0.4472.124

! Doctor found issues in 2 categories.
exit code 0

**Comment by danealbrain** [comment]
W/ira.khira_jama(23268): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)

**Comment by danealbrain** [comment]
The relevant error-causing widget was
StreamBuilder<QuerySnapshot<Object?>>
package:khira_jamat/Screens/HomeScreen.dart:29
When the exception was thrown, this was the stack
#0      _HomePageState.build.<anonymous closure>.<anonymous closure>
package:khira_jamat/Screens/HomeScreen.dart:44
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
...
════════════════════════════════════════════════════════════════════════════════
8
W/ira.khira_jama(23268): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)

**Comment by markusaksli-nc** [comment]
Hi @danealbrain 
Please open a new issue and fill out the template.
Thank you
