### ISSUE TITLE
[📚] Emulator Usage sections not updated after `use<product>Emulator(host, port)` API update (#6439)

### ISSUE THREAD

**Issue by devj3ns** [FirebaseExtended/flutterfire#6532]
I seems that the following sections in the docs were not updated after the `use<product>Emulator(host, port)` API update (https://github.com/FirebaseExtended/flutterfire/pull/6439):

https://firebase.flutter.dev/docs/firestore/usage#emulator-usage
https://firebase.flutter.dev/docs/auth/usage#emulator-usage
https://firebase.flutter.dev/docs/functions/usage#emulator-usage
https://firebase.flutter.dev/docs/storage/usage#emulator-usage

BTW: thanks @russellwheatley for implementing https://github.com/FirebaseExtended/flutterfire/pull/6439. It made my code a lot cleaner! 😀

**Comment by russellwheatley** [comment]
Thanks for letting us know - will get this updated ASAP.
