### ISSUE TITLE
FirebaseMessaging.onMessageOpenedApp.listen method not working when application is open

### ISSUE THREAD

**Issue by rajputsk** [FirebaseExtended/flutterfire#6536]
on tap of notification   FirebaseMessaging.onMessageOpenedApp   method is not working . when application is open this method is not trigger on push tap.

**Comment by markusaksli-nc** [comment]
Hi @rajputsk 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
