### ISSUE TITLE
Realtime database `ServerValue.increment(int)` should take parameter of type `double` rather than of type `int`

### ISSUE THREAD

**Issue by RastislavMirek** [FirebaseExtended/flutterfire#6570]
Currently in Realtime database beta, `ServerValue.increment(int)` only supports incrementing / decrementing integer values.

Floating point increments / decrements would be useful, Cloud Firestore supports them.

**Comment by markusaksli-nc** [comment]
Hi @RastislavMirek 
This is better suited for https://firebase.google.com/support since we just wrap the native SDK functionality.
Thank you
