### ISSUE TITLE
🐛 [firebase_ml_vision] Galaxy Tab A7 face recognition doesn't work

### ISSUE THREAD

**Issue by MahmouedInit** [FirebaseExtended/flutterfire#6581]
## Bug report

**Describe the bug**
I've been using face recognition feature on Android "Mobile Phones", IOS and it works probably.
Also I've even tried it on another tablet "Galaxy Tab A -SM-T295" and it works just fine.
But when I'm trying it on "Galaxy Tab A7 - SM-T505N" It's doesn't even work or even give any errors.
Have been trying all orientations, rotations, landscape modes, portrait modes but nothing really works.

### Steps to reproduce

Run Example on "Galaxy Tab A7 - SM-T505N" and it won't work

### Expected behavior

That it would work fine

### Flutter doctor

<details><summary>Click To Expand</summary>

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1646], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.55.1)
[√] Connected device (4 available)

• No issues found!

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

- animated_text_kit 2.5.4 [flutter characters]
- camera 0.5.8+17 [flutter]
- cupertino_icons 0.1.3
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_ml_vision 0.12.0 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- http 0.12.2 [http_parser path pedantic]
- image 2.1.19 [archive xml meta]
- intl 0.17.0 [clock path]
- lottie 0.6.0 [flutter archive characters charcode collection logging meta path vector_math]
- native_device_orientation 1.0.0 [flutter meta]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- provider 4.3.3 [collection flutter nested]
- qr_code_scanner 0.4.0 [flutter]
- qr_flutter 3.2.0 [flutter qr]
- screen 0.0.5 [flutter]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- qr 1.3.0 [meta]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]

</details>

---

**Comment by markusaksli-nc** [comment]
The `firebase_ml_vision` package is now discontinued since its APIs have been deprecated and removed from the Android & iOS Firebase SDKs.

I'd recommend switching to the alternatives now;

 - **for on-device vision APIs**; switch to Google's standalone ML Kit library via [google_ml_kit](https://pub.dev/packages/google_ml_kit)
 - **for cloud vision APIs**; the recommended approach now is to use Firebase
Authentication and Functions, which gives you a managed, serverless gateway to the Google Cloud Vision APIs. For an example Functions project see the [vision-annotate-images](https://github.com/firebase/functions-samples/tree/master/vision-annotate-images) sample project. You'd deploy this project for example and then call the cloud function from your app with your image data to get the annotation result.

Apologies for any inconvenience here and best of luck switching over the the new APIs. `firebase_ml_custom` is not affected by this deprecation.

Thanks

**Comment by MahmouedInit** [comment]
@markusaksli-nc Have tried [google_ml_kit](https://pub.dev/packages/google_ml_kit) example on the tablet and got the same issue, sorry forgot to mention that.

**Comment by markusaksli-nc** [comment]
Well for issues with that plugin you should report them in their plugin repository. Since Google removed the ML Vision APIs from Firebase our plugin is discontinued and there's nothing we can really do to help you.

**Comment by MahmouedInit** [comment]
@markusaksli-nc  Okay, Thanks for help anyway.
