### ISSUE TITLE
Fails to Build flutter Apk

### ISSUE THREAD

**Issue by Ashaba123** [FirebaseExtended/flutterfire#6584]
flutter build apk --release --shrink --target-platform android-arm --split-per-abi

Result:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Me\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-2.0.0\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'firebase_auth'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

**Comment by parmarravi** [comment]
Could not build the apk!!  Same issue

**Comment by markusaksli-nc** [comment]
Hi @Ashaba123 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
