### ISSUE TITLE
Firebase messaging -> Foreground notification not showing on iOS

### ISSUE THREAD

**Issue by flutter-developer-lab** [FirebaseExtended/flutterfire#6595]
On Android everything works fine. But on IOS, when app in foreground no notification shown, and also onMessage is not called. if app in background or terminated, everything works fine.

### **Flutter Doctor:**

[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2 20D64 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

### **Flutter Dependencies:**

1. firebase_core: "^1.3.0"
2.  firebase_auth: ^2.0.0
3. firebase_messaging: ^10.0.3
4. firebase_analytics: ^8.1.2

I am sending notification from firebase console.

### CODE:

```
  if (Platform.isIOS) {
      NotificationSettings settings = await messaging.requestPermission(
        alert: true,
        announcement: false,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional:
            false, //to show message at lock screen  by default it is false
        sound: true,
      );
      if (settings.authorizationStatus == AuthorizationStatus.authorized) {
        print('User granted permission');
      } else if (settings.authorizationStatus ==
          AuthorizationStatus.provisional) {
        print('User granted provisional permission');
      } else {
        print('User declined or has not accepted permission');
      }
      //for foreground
      await messaging.setForegroundNotificationPresentationOptions(
        alert: true, // Required to display a heads up notification
        badge: true,
        sound: true,
      );
    }

 FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print("foreground message::::$message");
    });

```

**Comment by ccs1428** [comment]
Facing same issue, push message not receiving in iOS device. Have tried to send directly from firebase console.

**Comment by cccodaisy** [comment]
same issue

**Comment by markusaksli-nc** [comment]
Hi @flutter-developer-lab 
Have you requested notification permissions on the device? I'm not seeing it in the code you provided.
Could you try running the [official example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib)?
Thank you

**Comment by flutter-developer-lab** [comment]
Hi @markusaksli-nc
I follow flutterfire documentation. You can See in my code i request for permission. I also get allow notification dialog. if is there any other permission request. Could you please provide me some specific code.

**Comment by markusaksli-nc** [comment]
Nevermind, I just read over it for some reason. Have you tried running the example?

**Comment by Glexium** [comment]
I had this problem, I fixed it changing the file AppDelegate.swift like this:

@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()   
    GeneratedPluginRegistrant.register(with: self)
    return true 
    // original line was:
    // super.application(application, didFinishLaunchingWithOptions: launchOptions) //this line was working on older versions of 
    // iOS and stop working with iOS 14.7.1, at least in my case.
  }
}

Tested with firebase console and using postman https://fcm.googleapis.com/fcm/send with json

**Comment by saharvx9** [comment]
> I had this problem, I fixed it changing the file AppDelegate.swift like this:
> 
> @objc class AppDelegate: FlutterAppDelegate {
> override func application(
> _ application: UIApplication,
> didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
> ) -> Bool {
> FirebaseApp.configure()
> GeneratedPluginRegistrant.register(with: self)
> return true
> // original line was:
> // super.application(application, didFinishLaunchingWithOptions: launchOptions) //this line was working on older versions of
> // iOS and stop working with iOS 14.7.1, at least in my case.
> }
> }
> 
> Tested with firebase console and using postman https://fcm.googleapis.com/fcm/send with json

YOU ARE GENIUS!!!

**Comment by flutter-developer-lab** [comment]
Thanks @Glexium,
It's Working
