### ISSUE TITLE
🐛 [firebase_messaging 10.0.3] When using any of the firebase plugins it shows a trojan in virus total

### ISSUE THREAD

**Issue by Zacktamondo** [FirebaseExtended/flutterfire#6598]
## Bug report
When I am creating any project and using any firebase plugin if I build the apk and uploaded it to [virus total](virustotal.com) then I get that the app has a Trojan (Specifically Android.WIN32.FakeAdBlocker.a). 

### Steps to reproduce

1. Create new flutter project.
2. Go to pubsec.yaml
3. Add   firebase_messaging: ^10.0.3 to the dependencies.
4. Build the project as apk using `flutter build apk`
5. Upload the file to [virus total](virustotal.com).
6. Check the results.

### Expected behavior

The results of the scan will show a Trojan detected by MaxSecure antivirus, The Trojan name is (Android.WIN32.FakeAdBlocker.a)

### Sample project

The following is a new project with the firebase_messaging plugin and the apk scan result:
[Project Repo](https://github.com/Zacktamondo/flutter_project_with_firebase_plugin)
[Virus Total scan](https://www.virustotal.com/gui/file/0f54820d96f1694b8bded98f12238fb9e1a474fb69fe035092990e67c4c14002/detection)
---

### Flutter doctor

`flutter doctor` output:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /usr/bin/google-chrome-stable)
    ! /usr/bin/google-chrome-stable is not executable.
[✓] Android Studio (version 4.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

`flutter pub deps -- --style=compact` output:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4 
Flutter SDK 2.2.3 
flutter_application_1 1.0.0+1 
dependencies: 
- cupertino_icons 1.0.3 
- firebase_messaging 10.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta] 
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine] 
dev dependencies: 
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data] 
transitive dependencies: 
- async 2.6.1 [meta collection] 
- boolean_selector 2.1.0 [source_span string_scanner] 
- characters 1.1.0 
- charcode 1.2.0 
- clock 1.1.0 
- collection 1.15.0 
- fake_async 1.2.0 [clock collection] 
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta] 
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface] 
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta] 
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface] 
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta] 
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math] 
- js 0.6.3 
- matcher 0.12.10 [stack_trace] 
- meta 1.3.0 
- path 1.8.0 
- plugin_platform_interface 2.0.1 [meta] 
- sky_engine 0.0.99 
- source_span 1.8.1 [collection path term_glyph] 
- stack_trace 1.10.0 [path] 
- stream_channel 2.1.0 [async] 
- string_scanner 1.1.0 [charcode source_span] 
- term_glyph 1.2.0 
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher] 
- typed_data 1.3.0 [collection] 
- vector_math 2.1.0 

```

</details>

---

**Comment by ahmadalwareh** [comment]
Can confirm tried a new project and had the same results?

**Comment by ahmadalwareh** [comment]
I can confirm, tried a new project and had the same results.

**Comment by markusaksli-nc** [comment]
Seems reproducible

**Comment by Zacktamondo** [comment]
To add more info on the issue I tested it back to version **7.0.3** and still have the same issue.
And I found a scan of an APK dated back to **January** and had **no issue,** but when I refreshed the scan the issue appeared.
As I researched the issue appears only when the app isn't published on the google play store.
I may be wrong but this is what I got from retrying too many times and checking published apps using the same library with the same version.
Also I tried to send a false positive request to **MaxSecure** antivirus and I got no response.

**Comment by Tarek-989** [comment]
I'm facing the same issue.

**Comment by MhdSaleh** [comment]
I had the same issue, and it's a big deal because am not planning to publish some of my apps on google play so this makes my apps suspicious.

**Comment by Zacktamondo** [comment]
I can confirm that the issue is resolved, I re scanned some of the apks that I uploaded to virus total and it's all working fine.
