### ISSUE TITLE
Is that possible to disable iCloud synchronisation?

### ISSUE THREAD

**Issue by romk1n** [FirebaseExtended/flutterfire#66]
It seems after the login is done even if the app is uninstalled, the device being remembered. I believe it's because the flag `kSecAttrSynchronizable` is not set to false. is that possible to provide configuration where you can specify the way you want this to behave ?

**Comment by Salakar** [comment]
If this is still required would you mind raising a feature request here with more details such as where that flag should be set etc: https://github.com/FirebaseExtended/flutterfire/discussions/new?category_id=24213383

Thanks
