### ISSUE TITLE
[firebase_database] Wildcard

### ISSUE THREAD

**Issue by Bestfastfire** [FirebaseExtended/flutterfire#6601]
I tried do this but never trigger anything:

`ref.child('${value}/{fId}').onValue.listen ...`

This lib dont have wildcards support?

**Comment by markusaksli-nc** [comment]
Hi @Bestfastfire 
Not sure what you mean by "wildcard support". You are just using string interpolation to listen to a ref. It depends on what you are interpolating and if the ref is valid. Would need to know how you are using this call in a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).

This isn't really a documentation issue so I'm going to close it. If some part of the plugin isn't working as expected for you then you can open a bug report issue and fill out the template.
Thank you
