### ISSUE TITLE
🐛 [firebase_core] I faced a problem when I add firebase_core: ^1.3.0 library to my flutter project and run “flutter build ipa”

### ISSUE THREAD

**Issue by yazeed-mohammad** [FirebaseExtended/flutterfire#6604]
/* com.apple.ibtool.errors */
    /Users/yazeedmohammad/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/ios/Storyboards/WebView.storyboard: error: Interface
    Builder can’t determine the type of “WebView.storyboard”. This may be due to a missing SDK.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Encountered error while archiving for 

# my podfile:
```
 platform :ios, '10.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

$FirebaseSDKVersion = '8.0.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
 
```

**Comment by markusaksli-nc** [comment]
Hi @yazeed-mohammad 
It doesn't look like the error has anything to do with firebase?
Looks like this should be opened in https://github.com/pichillilorenzo/flutter_inappwebview/issues

(PS you should remove the `$FirebaseSDKVersion` line. As mentioned in the documentation FlutterFire manages this version internally and you should only override it if you need to.)
Thank you

**Comment by yazeed-mohammad** [comment]
Hello @markusaksli-nc.

Im dosn't used flutter_inappwebview library, but when I add firebase_core to project, this problem was shown.

Thank you.

**Comment by markusaksli-nc** [comment]
Have you tried adding it to a fresh project or deleting your `.pub-cache`?

**Comment by yazeed-mohammad** [comment]
@samlythemanly thank  you for your time.

I found this [solution](https://stackoverflow.com/a/64513759/12988168) to my problem and it's work fine.

solution: 
"There is a Firebase documentation for iOS phone verification setup:

To enable the Firebase SDK to use reCAPTCHA verification:

Add custom URL schemes to your Xcode project:

Open your project configuration: double-click the project name in the left tree view. Select your app from the TARGETS section, then select the Info tab, and expand the URL Types section.
Click the + button, and add a URL scheme for your reversed client ID. To find this value, open the GoogleService-Info.plist configuration file, and look for the REVERSED_CLIENT_ID key. Copy the value of that key, and paste it into the URL Schemes box on the configuration page. Leave the other fields blank. When completed, your config should look something similar to the following (but with your application-specific values):

https://firebase.google.com/docs/auth/ios/phone-auth?authuser=0

Works for Flutter too."
