### ISSUE TITLE
bnjr j'ai rencontrer le problème:

### ISSUE THREAD

**Issue by pascalsarr** [FirebaseExtended/flutterfire#6606]
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about totry using Jetifier to solve the incompatibility.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...

**Comment by markusaksli-nc** [comment]
Hi @pascalsarr 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by pascalsarr** [comment]
![Captkdxcure](https://user-images.githubusercontent.com/39752128/125642408-7533b22f-df34-4151-8b1f-200ef77fb5e2.JPG)

**Comment by markusaksli-nc** [comment]
Not sure what the issue is exactly without the full logs. As I mentioned you can open a new issue and fill out the template. Also please just copy/paste the logs instead of providing screenshots.
