### ISSUE TITLE
[firebase_messaging] Handling notification interaction (tap) when app in foreground (android)

### ISSUE THREAD

**Issue by contenta-rok** [FirebaseExtended/flutterfire#6611]
Hi,

I have set to show notifications when app is in the foreground.
I have been following instructions from documentation: https://firebase.flutter.dev/docs/messaging/notifications/#foreground-notifications and it shows notification normally. 

Problem is when I tap notification nothing happens. From following documentation, [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) plugin is added and show method is called to show notification.

I suspect that I need to change _onSelectNotification method and add my logic. How do I change that method, since plugin has already been initialized? I'm thinking correctly?

Code from documentation:
![slika](https://user-images.githubusercontent.com/73519437/125742322-f78c0090-e942-4d0e-9bdd-43f0ef508681.png)

![slika](https://user-images.githubusercontent.com/73519437/125742380-49fba614-4604-43b1-b607-e94939c3a627.png)

**Comment by markusaksli-nc** [comment]
Since the notification is shown by local notifications you can take a look at their [example](https://pub.dev/packages/flutter_local_notifications/example) for how to handle this.

**Comment by contenta-rok** [comment]
For anyone else struggling  with same problem, here is solution:
`
    final AndroidInitializationSettings androidInitializationSettings = AndroidInitializationSettings('app_icon');

    // Recreate initialization to set onSelectNotification.
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.initialize(androidInitializationSettings,
        onSelectNotification: (String payload) async {
          if (payload != null) {
            debugPrint('notification payload: $payload');
          }
        });    
`

Only needed to call initialize method to set onSelectNotification.
