### ISSUE TITLE
🐛 [firebase_auth] otp receive error

### ISSUE THREAD

**Issue by akesman** [FirebaseExtended/flutterfire#6615]
Hi, everybody
I live in Russia.For some reason, I do not receive an otp message from the operator "megafon". Although it is clear from the logs that everything works correctly. There are no problems with other operators.

**Comment by markusaksli-nc** [comment]
Hi @akesman 
If it is working for other operators it shouldn't be an issue with the plugin code in this repository. I recommend that you contact https://firebase.google.com/support and see if they can help you out.
Let me know if they believe it could be on our side but I'll close the issue for now.
Thank you

**Comment by akesman** [comment]
I have already contacted them (they are trying to eliminate it), I
also decided to write here. The problem is urgent


пт, 16 июл. 2021 г. в 16:08, Markus Aksli ***@***.***>:
