### ISSUE TITLE
MissingPluginException error on Firebase.initializeApp() calling when using FirebaseMessaging plugin in flutter tests

### ISSUE THREAD

**Issue by OrlovPetr** [FirebaseExtended/flutterfire#6616]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/6613

<div type='discussions-op-text'>

<sup>Originally posted by **OrlovPetr** July 15, 2021</sup>
Hello!
Can you help me with this problem.
Trying to start this test:
```
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('Test user instance', () async {
    /// Prepare user model for tests.
    await App().init();

    // expect(user.isAuth, true);
    // expect(user.miob, true);
    // expect(user.rememberMe, false);
  });
}
```

Method `App().init()` crashes on method `await InternalFirebase.whenAppStarted()` from `class InternalFirebase` which looks like this:
```
class InternalFirebase {
  static FirebaseMessaging _firebaseMessaging;

  static Future<void> whenAppStarted() async {
    await Firebase.initializeApp();

    _firebaseMessaging = FirebaseMessaging.instance;
    await _firebaseMessaging.requestPermission();
    await _firebaseMessaging.subscribeToTopic('APPS');
    await FirebaseNetwork(url: '${API_SERVICE_MAIN_URL}push/devices').registerDevice(_firebaseMessaging);
  }
}
```
I've been running tests in debug mode and crash is on this line: `await Firebase.initializeApp();`:
```
package:flutter/src/services/platform_channel.dart 156:7  MethodChannel._invokeMethod
MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
```

In pubspec.yaml I have this packages:
```
  firebase_messaging: ^10.0.3
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
```

Flutter doctor report:
```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19043.1110], locale ru-RU)
    • Flutter version 2.0.6 at C:\Flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/porlo/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/porlo/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!
```

This problem caused only on tests - in debug, profile and release modes all is ok.

I'm tried `flutter clean` and rebuild project, trying use hardcoded settings for` Firebase.initializeApp()` and looked to this issue: [https://github.com/FirebaseExtended/flutterfire/issues/3311](https://github.com/FirebaseExtended/flutterfire/issues/3311) but don't understand where is pb...</div>

**Comment by bardia-mhd** [comment]
Add updated version of `firebase_core :` to pubsec.yaml and add Firebase to your main.dart like this:
`import 'package:firebase_core/firebase_core.dart';

void main() async {
   WidgetsFlutterBinding.ensureInitialized();
   await Firebase.initializeApp();
   runApp(MyApp());
}`

**Comment by OrlovPetr** [comment]
> Add updated version of `firebase_core :` to pubsec.yaml and add Firebase to your main.dart like this:
> 
> ```
>   import 'package:firebase_core/firebase_core.dart';
>   
>   void main() async {
>      WidgetsFlutterBinding.ensureInitialized();
>      await Firebase.initializeApp();
>      runApp(MyApp());
>   } 
> ```
> 
> if it crashes again you can use `FirebaseCrashlytics.instance.crash();` to submit the crash report to the Firebase Console.
> 
> ```
> import 'package:flutter/foundation.dart' show kDebugMode;
> 
> // ...
> 
> if (kDebugMode) {
>   // Force disable Crashlytics collection while doing every day development.
>   // Temporarily toggle this to true if you want to test crash reporting in your app.
>   await FirebaseCrashlytics.instance
>       .setCrashlyticsCollectionEnabled(false);
> } else {
>   // Handle Crashlytics enabled status when not in Debug,
>   // e.g. allow your users to opt-in to crash reporting.
> }
> ```

I told about tests, not about debug, profile or release modes. Crashes only on tests.
And about crashlitycs - I don't understand how it can help me if this library require initialized Firebaze app, but crash happens just on initialization and I can't set any crashlytics methods because it throw exception:
`[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()`

**Comment by markusaksli-nc** [comment]
Hi @OrlovPetr 
It seems like you are trying to write a unit test for the behavior of your firebase logic? The FlutterFire plugins rely on delegating calls to the native SDKs to initialize and provide functionality. As with most unit tests these kinds of external dependencies are usually mocked (read https://flutter.dev/docs/testing#unit-tests for more).

As for how you should actually proceed then - you can take a look at how the tests in this repository have been written and take that as reference. 

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/test

The important part you need to know is that without running on an actual device you will not be able to delegate calls to any native SDKs and due to this you will run into the mentioned error.
Thank you

**Comment by OrlovPetr** [comment]
> Hi @OrlovPetr
> It seems like you are trying to write a unit test for the behavior of your firebase logic? The FlutterFire plugins rely on delegating calls to the native SDKs to initialize and provide functionality. As with most unit tests these kinds of external dependencies are usually mocked (read https://flutter.dev/docs/testing#unit-tests for more).
> 
> As for how you should actually proceed then - you can take a look at how the tests in this repository have been written and take that as reference.
> 
> https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/test
> 
> The important part you need to know is that without running on an actual device you will not be able to delegate calls to any native SDKs and due to this you will run into the mentioned error.
> Thank you

Thanks for your help! I'll look into the materials you mentioned and try to figure it out)
