### ISSUE TITLE
🐛 [cloud_firestore] Connection to Firestore blocked on some network types with no option for `experimentalForceLongPolling`

### ISSUE THREAD

**Issue by alexagat** [FirebaseExtended/flutterfire#6635]
## Bug report

**Describe the bug**
After deploying a Flutter web application many users report not being able to use it due to failing requests to read/write data. Specifically the gRPC network requests to `https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?...` are the ones failing.

All of the users experiencing this issues are on a corporate network or have some Firewall layer enabled. This same issue occurs with non-Flutter web applications built in Angular/React using the `firebase-js-sdk` SDK, but the javascript sdk allows for setting an option of `experimentalForceLongPolling` which seems to help. 

Documentation on JS SDK FirebaseFirestore options: https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#experimentalforcelongpolling

Related issues against the JS SDK: https://github.com/firebase/firebase-js-sdk/issues/1674 https://github.com/firebase/firebase-js-sdk/issues/2526

Unfortunately, `experimentalForceLongPolling` does not appear to be an option for the FlutterFire SDK. What options do we have to have better web support?

### Expected behavior

Flutter web applications do not experience inconsistent read or write behavior to Firestore due to the network settings.

**Comment by markusaksli-nc** [comment]
Not sure which version of the CDN it was introduced in but you could try to call it on the native side in the initialization script in `index.html`?

But for the actual issue you are facing I would also contact https://firebase.google.com/support

**Comment by Ehesp** [comment]
We have generally not implemented the experimental options (on any service). As a quick fix, I'd do as @markusaksli-nc suggested in the `index.html` file:

```html
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
  <script>
    // Initialize Firebase
    firebase.initializeApp({ ... });
	
	firebase.firestore().settings({ experimentalForceLongPolling: true })
  </script>
```

**Comment by alexagat** [comment]
@markusaksli-nc / @Ehesp thank you both for this suggestion. I didn't realize I could add these custom settings directly into the JS of our Flutter app, but that now makes perfect sense. I have deployed this on one of our test sites and it seems to be helping the issue.

**Comment by luantran2896** [comment]
I use firebase locally, it works fine, but when I deploy to the server, I get this error. Please help me

@firebase/firestore: Firestore (8.7.1): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=invalid-argument]: Invalid resource field value in the request.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

**Comment by Ehesp** [comment]
@luantran2896 I'd advise raising a ticket with Firebase support. This library is only wrapping the SDK so there isn't anything we'd be able to do to help with that.

**Comment by russellwheatley** [comment]
Closing this issue as there is nothing to action. We're not implementing experimental features as mentioned above.
