### ISSUE TITLE
[cloud_firestore] Issue reestablishing connection

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#664]
I'm currently facing an issue with a device (particularly a Redmi Note 3 • android-arm64 • Android 8.1.0 (API 27)). I have tested it with other 4 devices and didn't face this problem, though. 

Whenever I turn off Wifi and then turn it back on, the Firestore does not fire any event nor listen to changes, it simply acts like it was offline. If I close the app and start the app again it fires all the actions made at once (sure, because of the persistent mode). I would like to know if there's any way to force it to reestablish a connection with Firestore. Thanks!

**Comment by kroikie** [comment]
@madtocc

The issue at https://github.com/flutter/flutter/issues/21852 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@holyspidoo @madtocc is the issue still relevant?

**Comment by kirstywilliams** [comment]
Hey @holyspidoo @madtocc I'm closing this issue due to a lack of activity.

If you are still experiencing the issue, please try a more up-to-date version. If your issue persists with a recent version, please feel free to open a new issue detailing your issue.
