### ISSUE TITLE
Sing out

### ISSUE THREAD

**Issue by ayeshasiddika9196** [FirebaseExtended/flutterfire#6644]
Sing out

_Originally posted by @ayeshasiddika9196 in https://github.com/FirebaseExtended/flutterfire/discussions/6453#discussioncomment-1017155_

**Comment by markusaksli-nc** [comment]
Hi @ayeshasiddika9196 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
