### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by mallardexpress** [FirebaseExtended/flutterfire#6647]
## Bug report

**Describe the bug**
After turning persistence off, then using for a while without it, then turning back on - it reverts back to the data stored in the old persistence cache.

### Steps to reproduce

initial build
database.setPersistenceEnabled(true);
1. change some data

rebuild the app
database.setPersistenceEnabled(false);
2. change some data

rebuild the app
database.setPersistenceEnabled(true);
reverts to data cache 1

### Expected behavior

After disabling persistence, the cache should be cleared. 
Or there should be a way to manually clear the persistence cache.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @mallardexpress 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Comment by mallardexpress** [comment]
Cop out, no surprise
