### ISSUE TITLE
cloud_functions 3.0.0 change log

### ISSUE THREAD

**Issue by paul-appliquette** [FirebaseExtended/flutterfire#6652]
Latest [change log](https://pub.dev/packages/cloud_functions/changelog) entry reads as follows:

> 3.0.0 
> Note: This release has breaking changes.
> 
> CHORE: rm deprecated jcenter repository (#6431).
> BREAKING FEAT: use
> BREAKING FEAT: use

No detail given on what these "breaking changes" are?

**Comment by corentingiraud** [comment]
This may be a [pub.dev](https://pub.dev/) bug.

The updated changelog can be find [in the github repo](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/CHANGELOG.md).

**Comment by russellwheatley** [comment]
> This may be a [pub.dev](https://pub.dev/) bug.
> 
> The updated changelog can be find [in the github repo](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/CHANGELOG.md?rgh-link-date=2021-07-19T11%3A28%3A29Z).

As described above, we don't have control over the `pub.dev` output, but at least it can be found in the repo.
