### ISSUE TITLE
🐛 [firebase_storage] How to check File upload was success or fails

### ISSUE THREAD

**Issue by pmrajani** [FirebaseExtended/flutterfire#6655]
## I have app where i am using local database SQLite to upload one by one image to Firebase storage.

**Describe the bug**
Here is scenario, when i am trying to upload any Image from sqlite i can get snapshotEvents.listen event so i can easily update my local db with upload success status

But when i was uploading any image to firebase and if internet connection is gone, in that case firebase will put this task on sleeping (In this scenario, if user close app), When user will reopen app, Firebase will auto resume it But at that time my App don't have any reference to update that task status with my local DB

**Comment by markusaksli-nc** [comment]
Hi @pmrajani 
In this case, you can just check the storage references to see if it has been uploaded? In any case this is a question better suited for StackOverflow or the community in general since there is nothing actually wrong with the storage plugin here.
Thank you
