### ISSUE TITLE
Not able to receive notification on flutter IOS app using firebase_messaging

### ISSUE THREAD

**Issue by satishojha** [FirebaseExtended/flutterfire#6661]
Hi Team,

I have issues while using firebase_messaging flutter package.
The notifications work properly on android but fails on IOS.

On IOS simulator, I am able to receive notification while using the app. While on real IOS device, I am receiving the notifications only when the app is in killed state.
Further, when I am clicking on the notification badge when the app is in killed state, onLaunch event is not getting triggered.

If any one faced this issue and has a solution, please share.

**Comment by markusaksli-nc** [comment]
Hi @satishojha 
Please open a bug report and fill out the template with the requested details. It would also be helpful if you could mention which device this is happening on and provide a code sample (or just use the official example).
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
Thank you
