### ISSUE TITLE
🐛 [FirebaseInstallations] CORS "Origin" header is null

### ISSUE THREAD

**Issue by html-rulez-d00d** [FirebaseExtended/flutterfire#6663]
## Bug report

**Describe the bug**
There is concern on the use of the Origin header for the Firebase installation process. Our group had a penetration test run on our project's code and they flagged this issue as moderate. From the security teams findings, it appears the `POST /v1/projects/<project>/installations` uses an "Origin" header with a value of null. Their expectation is that either CORS should be disabled or to provide the Origin's value with the proper domain (ex: `Origin: https://firebaseinstallations.googleapis.com`).

Code location: `<root>/ios/Pods/FirebaseInstallations/FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m`

### Steps to reproduce

1.  Run any Flutter project with Firebase Core and Firebase Messaging as dependencies. Note: this issue was witnessed on an iOS device (an iOS app).
2. Capture the server request and response.

### Expected behavior

Cross-origin resource sharing (CORS) should be disabled if same-origin policy is not blocking
Or
If Cross-origin resource sharing (CORS) is needed. Then Origin should be set to the proper domain.
Origin: https://firebaseinstallations.googleapis.com

### Sample project

NA

---

## Additional context

- I am not an iOS developer so there should be no expectation that I can submit a PR / modify Objective-C. I simply did a search in my project on the affected url to locate the file where the request occurs.
- The Flutter plugins we use are **firebase_core: 1.3.0** & **firebase_messaging: 10.0.2**

---

### Flutter doctor

NA

---

### Flutter dependencies

NA

---

**Comment by markusaksli-nc** [comment]
Hi @html-rulez-d00d 
Since this is coming from the native SDK could you open this issue in https://github.com/firebase/firebase-ios-sdk since we don't control this behavior?
Thank you

**Comment by html-rulez-d00d** [comment]
Thank you for your quick response @markusaksli-nc ! And thanks for that direction, I was confused since there are so many moving parts with Firebase :)
