### ISSUE TITLE
[Firebase Messaging📚] Image notifications warning iOS

### ISSUE THREAD

**Issue by febg11** [FirebaseExtended/flutterfire#6664]
Hi 

Ive done the set up for image notifications which works fine but I am now getting a warning from apple app store connect about the image notification service version not matching the version of my app. 

![image](https://user-images.githubusercontent.com/50048162/126393082-a075a3bd-e87d-4f8e-b67c-785829b86e0e.png)

I can manually update it but it seems a terrible way of doing it, is there anyway to automate this that could be added to the documentation?

https://firebase.flutter.dev/docs/messaging/apple-integration/#advanced-optional-allowing-notification-images

I know this is only a warning but it would be nice to remove them 

Kind regards

**Comment by russellwheatley** [comment]
Hey @febg11, did you get to the bottom of this?
