### ISSUE TITLE
Cloud Messaging for macOS not receiving messages

### ISSUE THREAD

**Issue by maxbeech** [FirebaseExtended/flutterfire#6669]
I'm trying to get my Flutter application to receive messages using Cloud Messaging. This is working great on iOS, but for my Flutter macOS application, no matter what I try it's not working.

There seems to be no third party documentation online about how to do this, and am slightly unsure of the route to take when using the [official documentation](https://firebase.flutter.dev/docs/messaging/apple-integration/).

### What I have tried:

- Cleaning Flutter
- Removing pods and rebuilding
- Sending messages from both Firebase's test page as well as a Firebase Function

### What I am wondering if I have got wrong:

- In the documentation it says `For iOS; you must have a physical iOS device to receive messages.`, does this mean I should be doing something different when running a macOS app too?
- Where it says in the documentation, `This guide applies to both iOS & macOS Flutter apps, repeat each step for the platforms you require`, does it literally mean every single step, as some steps seem to be fine not being repeated eg....
- Can I reuse the same [Firebase iOS app and Apple key](https://firebase.flutter.dev/docs/messaging/apple-integration/#1-registering-a-key) or do I need to create a separate Firebase iOS app and separate Apple key?
- Can I use the same [identifier](https://firebase.flutter.dev/docs/messaging/apple-integration/#2-registering-an-app-identifier) as with my iOS implementation?

Thanks so much!

**Comment by markusaksli-nc** [comment]
Hi @maxbeech 
In answer to all of your questions:
- No, you can just run on your mac, however you need a build that has been notarized by apple (https://github.com/FirebaseExtended/flutterfire/issues/5717)
- You can use the same identifier and key
Does this answer your questions?
Thank you

**Comment by maxbeech** [comment]
Thanks so much @markusaksli-nc, this is **super** useful! I have just been able to test this hypothesis and can confirm that once using the notarized version, this works a treat! I really think this should be added to the documentation though.
