### ISSUE TITLE
🐛 [cloud_firestore] Disable offline persistence on web

### ISSUE THREAD

**Issue by ConcenTech** [FirebaseExtended/flutterfire#6672]
In my web app, I only want to listen to streams of data from the online database.

In the documentation there is the following information on offline persistence:

> This functionality is enabled by default, however it can be disabled if needed. The settings must be set before any Firestore interaction is performed:
> 
> ```dart
> // Web.
> await FirebaseFirestore.instance.enablePersistence();
> 
> // All other platforms.
> FirebaseFirestore.instance.settings =
>     Settings(persistenceEnabled: false);
> ```
> 

This reads as though offline persistence is disabled by default on web and can only be enabled?

Currently if listen to a stream, go offline and add a document to the collection I'm listening to, the new document appears in the stream.
Is this expected behaviour, as offline persistence hasn't been enabled.

I expected the write to fail, so I can then handle this case.

**Comment by markusaksli-nc** [comment]
Hi @ConcenTech 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What versions of the CDN are you importing in `index.html`?
Thank you

**Comment by ConcenTech** [comment]
Hi,
Please find the requested information below.

Thanks

<details>
<summary>flutter pub deps -- --style=compact</summary


Dart SDK 2.13.4
Flutter SDK 2.2.3

dependencies:
- cloud_firestore 2.4.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 1.1.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- debounce_throttle 2.0.0 [meta simple_observable]
- dependencies 0.1.5 [quiver disposables]
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_chat_ui 1.1.8 [flutter diffutil_dart equatable flutter_chat_types flutter_link_previewer intl meta photo_view]
- flutter_riverpod 0.14.0+3 [collection flutter meta riverpod state_notifier]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- intl 0.17.0 [clock path]
- responsive_builder 0.4.1 [flutter]
- system_theme 1.0.1 [system_theme_web flutter]
- vrouter 1.2.0+5 [flutter path_to_regexp url_strategy url_launcher move_to_background]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.3.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.3.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.8 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.10 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- diffutil_dart 2.0.0+1
- disposables 0.1.2 [quiver]
- equatable 2.0.3 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 4.3.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.3.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_chat_types 2.4.0 [equatable meta]
- flutter_link_previewer 2.2.1 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.14.2 [collection json_annotation meta]
- hive 2.0.4 [meta crypto]
- html 0.15.0 [csslib source_span]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- json_annotation 4.0.1
- linkify 4.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- move_to_background 1.0.2 [flutter]
- path 1.8.0
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- path_to_regexp 0.4.0
- pedantic 1.11.1
- photo_view 0.11.1 [flutter]
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- process 4.2.1 [file path platform]
- quiver 2.1.5 [matcher meta]
- riverpod 0.14.0+3 [collection freezed_annotation meta state_notifier]
- simple_observable 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.0 [meta]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- system_theme_web 0.0.2 [flutter flutter_web_plugins]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher 6.0.9 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- url_strategy 0.2.0 [flutter_web_plugins]
- vector_math 2.1.0
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
</details>

<details>
<summary>Flutter Doctor -v</summary>

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.71], locale en-GB)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kgcar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\kgcar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.71

• No issues found!
</details>

```html
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-functions.js"></script>
```

**Comment by markusaksli-nc** [comment]
I was able to reproduce the behavior but not sure if this is intended or not.
```yaml
cloud_firestore: ^2.4.0
```
```html
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.4.0-5.0.pre.166, on Microsoft Windows [Version 10.0.19041.1110], locale et-EE)
    • Flutter version 2.4.0-5.0.pre.166 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2dc11a85ff (11 hours ago), 2021-07-22 17:56:03 -0700
    • Engine revision fbbb3b3f7b
    • Dart version 2.14.0 (build 2.14.0-343.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7628.21
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

const USE_FIRESTORE_EMULATOR = false;
const COLLECTION = "basic-example";

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if (USE_FIRESTORE_EMULATOR) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }
  //await FirebaseFirestore.instance.enablePersistence();
  runApp(FirestoreExampleApp());
}

class FirestoreExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firestore Example App',
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Center(child: Body()),
        appBar: AppBar(
          title: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Text('Firestore Example: Basic'),
              StreamBuilder(
                stream: FirebaseFirestore.instance.snapshotsInSync(),
                builder: (context, _) {
                  return Text(
                    'Latest Snapshot: ${DateTime.now()}',
                    style: Theme.of(context).textTheme.caption,
                  );
                },
              )
            ],
          ),
        ),
      ),
    );
  }
}

class Body extends StatefulWidget {
  const Body({Key? key}) : super(key: key);

  @override
  _BodyState createState() => _BodyState();
}

class _BodyState extends State<Body> {
  var _colRef = FirebaseFirestore.instance.collection("$COLLECTION");
  var _collectionStream =
  FirebaseFirestore.instance.collection('$COLLECTION').snapshots();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        StreamBuilder(
          stream: _collectionStream,
          builder: (context, AsyncSnapshot snapshot) {
            // do some stuff with both streams here
            if (snapshot.hasError) {
              return Text('${snapshot.error}');
            }

            if (!snapshot.hasData) {
              return CircularProgressIndicator();
            }

            final data = snapshot.requireData;
            String docs = '';
            for (int i = 0; i < data.size; i++) {
              docs += data.docs[i].id;
              if (i != data.size - 1) docs += ', ';
            }

            return ListTile(
              title: const Text('Test collection:'),
              subtitle: Text(docs),
              leading: IconButton(
                icon: Icon(Icons.add),
                tooltip: "Add document",
                onPressed: () async {
                  await
                  _colRef.doc("${data.size}")
                      .set({"dummy": "document"});
                },
              ),
              trailing: IconButton(
                icon: Icon(Icons.remove),
                tooltip: "Remove document",
                onPressed: data.size == 0
                    ? null
                    : () async {
                  await data.docs[data.size - 1].reference.delete();
                },
              ),
              onTap: () async {
                var col =
                await _colRef.get();
                var docs = '$COLLECTION:\n';
                for (var value in col.docs) {
                  docs += value.id + value.data().toString() + "\n";
                }
                var message =
                    '${docs}isFromCache: ${col.metadata.isFromCache}';
                print(message);
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(message),
                  ),
                );
              },
              enableFeedback: true,
            );
          },
        ),
      ],
    );
  }
}
```
</details>

**Comment by russellwheatley** [comment]
Hey @ConcenTech, this is working as intended. 

On web, the default is to disable persistence. The documents are still in-memory, and once the browser tab is refreshed/closed, the data will be lost (i.e. not persisted). 

If you enable persistence, you will still have that data should you refresh/close the browser.

Below is a script you can run if you wish to see how firebase web handles it. Toggle the `enablePersistence()` to see docs persisted/not persisted once you close/refresh the browser.

Hope this helps.


```html
<html>
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
<script>
  
  var firebaseConfig = {
    // TODO - insert your own config here
  };
  firebase.initializeApp(firebaseConfig);
  var firestore = firebase.firestore();

  (async function init() {
    // TODO - Toggle enable persistence to see the difference
    // await firestore.enablePersistence();

    await firestore.disableNetwork();
    console.log('disabled network');
  })()

  const collection = 'flutter-tests';

  firestore.collection(collection).onSnapshot((snap) => {
    console.log('docs: ', snap.docs.length);
  });

  async function add() {
    await firebase.firestore().collection(collection).add({ doc: 'here' });
  }

</script>
<button onclick="add()">add</button>
</html>
```
