### ISSUE TITLE
🐛 [Firebase AppCheck + Cloud Functions] returns Unauthenticated

### ISSUE THREAD

**Issue by wazini-john** [FirebaseExtended/flutterfire#6675]
I have enabled app check in my project without enforcing anything.

I get `flutter: [firebase_functions/unauthenticated] Unauthenticated` when I make a call to a `cloud function`

added app check as seen below

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await RemoteConfigService().initialise();
  await FirebaseAppCheck.instance.activate();
  final sharedPreferences = await SharedPreferences.getInstance();
  runApp(
    ProviderScope(
      overrides: [
        sharedPrefsProvider.overrideWithValue(sharedPreferences),
      ],
      child: MyApp(),
    ),
  );
}
```
also added `await FirebaseAppCheck.instance.activate(webRecaptchaSiteKey: 'sampleKeyHere');` but nothing changes

added `pod 'Firebase/AppCheck'` in `Podfile` 

and 
```
let providerFactory = AppCheckDebugProviderFactory()
 AppCheck.setAppCheckProviderFactory(providerFactory)
```
in `AppDelegate` but nothing changes

in `pubspec.yaml`

```
  cloud_firestore: ^2.3.0
  cloud_functions: ^2.0.0
  firebase_analytics: ^8.1.1
  firebase_app_check: ^0.0.1+3
  firebase_auth: ^1.3.0
  firebase_database: ^7.1.1
  firebase_remote_config: ^0.10.0+2
  firebase_storage: ^10.0.1
```

cloud functions dependencies

```
"firebase-admin": "^9.9.0",
"firebase-functions": "^3.14.1",
```

**Comment by markusaksli-nc** [comment]
Hi @wazini-john 
Which device are you testing on? Have you enabled the relevant [attestation providers](https://firebase.google.com/docs/app-check)?

> App Check has built-in support for using the following services as attestation providers:
>- DeviceCheck or App Attest on iOS
>- SafetyNet on Android
>- reCAPTCHA v3 on web apps

Thank you

**Comment by wazini-john** [comment]
AppAttest on ios Simulator

**Comment by markusaksli-nc** [comment]
I'm not sure it works on simulators, have you tried on a physical device?

**Comment by wazini-john** [comment]
Not yet. We are still developing.
If it only works on physical devices. Is there a work around ? Or is there a way to remove it from the firebase project altogether?

**Comment by febg11** [comment]
This may be releted but all of a sudden I am getting this on my cloud functions. 

```
 FirebaseAppCheckError: The provided App Check token has expired. Get a fresh App Check token from your client app and try again.
```

This has only just started happening

I have also noticed app attest as an option on the firebase console that has my team ID already filled in? Is this different to device check, I currently have both enabled.

**Comment by febg11** [comment]
is there anyway i can remove app attest from the firebase console and just use device check?

**Comment by markusaksli-nc** [comment]
@wazini-john @febg11 I'm not aware of any workaround to this on iOS. Controlling this feature is up to the Firebase team and how they develop the functionality for Firebase Console. The FlutterFire plugins just wrap the Firebase SDKs to provide functionality. With a more backend issue like this on a beta feature, I would recommend you contact https://firebase.google.com/support

Labeling the issue for now due to multiple reports.

**Comment by wazini-john** [comment]
They have fixed it

**Comment by MaciejCaputa** [comment]
@wazini-john Can you provide the details on what has fixed it?

**Comment by nilsreichardt** [comment]
@wazini-john I would also be interested in a solution

**Comment by wazini-john** [comment]
This issue is not entirely fixed. Works on some functions and fails on others

**Comment by nilsreichardt** [comment]
I think it's related to: https://github.com/FirebaseExtended/flutterfire/issues/6794. But there are some differences: 
* In https://github.com/FirebaseExtended/flutterfire/issues/6794 it's not working for any function
* It's not working for simulator + real devices

**Comment by MaciejCaputa** [comment]
@wazini-john It fails for the ones that you deploy with upgraded versions of sdks.

**Comment by wazini-john** [comment]
So what's the best way forward @MaciejCaputa

**Comment by nilsreichardt** [comment]
@wazini-john There are some workarounds: https://github.com/FirebaseExtended/flutterfire/issues/6794#issuecomment-897129319

**Comment by markusaksli-nc** [comment]
Well https://github.com/FirebaseExtended/flutterfire/issues/6794 now better tracks the same issue so I think this can safely be closed as a duplicate (even though it is earlier).
