### ISSUE TITLE
cloud_functions plugin - undefined parameter

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#668]
I'm using   cloud_functions: ^0.0.4

when the below code executes cloud function does not receive values provided. The log from the cloud functions displays the paramerters passed as undefined for all of them. I made sure with debugging that the values are indeed being populated in the code and i have also used static data before i made a call to cloud function.  the regular http call with parameters works fine but it does not work with the cloud_functions plugin.

Any ideas what i am doing wrong here ?

```dart
resp = await CloudFunctions.instance.call(
        functionName: 'createFirebaseToken',
        parameters: <String, dynamic>{
          'uid': usr.id,
          'name': usr.displayName,
          'email': usr.mail,
        },
      );

```

this is what i see in the cloud function log in the firebase UI 

> parameters Received:  undefined, undefined, undefined

**Comment by kroikie** [comment]
@raviteja1982

The issue at https://github.com/flutter/flutter/issues/21477 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/flutter/issues/21477#issuecomment-514867956

**Comment by kroikie** [comment]
I think we can close this issue.
