### ISSUE TITLE
🐛 [cloud_firestore] release apk is not available to write and read firebase firestore data.

### ISSUE THREAD

**Issue by cpduran0622** [FirebaseExtended/flutterfire#6681]
## Bug report

Release apk is not available to write and read firebase firestore data.

But debut apk is working well.

Please help me.
Thanks

**Comment by markusaksli-nc** [comment]
Hi @cpduran0622 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Could you also try capturing any relevant logs with logcat?
Thank you

**Comment by cpduran0622** [comment]
https://stackoverflow.com/questions/67997146/firestore-release-apk-doesnt-read-and-write-unless-storage-works-flutter

I am having same problem with them.

**Comment by cpduran0622** [comment]
I got release apk with the command "flutter build apk" to send result to client.

And the release apk is not working to write and read data in firestore.

Maybe is it firebase rule?

**Comment by even-dev** [comment]
I have the same problem, It worked well a week ago but now I cannot read or write data while I changed nothing in my configuration files or in firebase.

**Comment by markusaksli-nc** [comment]
Have you made sure you have added your SHA 1 and SHA 256 keys to your project settings?

**Comment by even-dev** [comment]
@markusaksli-nc From the google play console, which keys do I have to add? The upload key certificate or the app signing key certificate?

**Comment by even-dev** [comment]
I re-add my sha1 and sha256 keys but It's doesn't work. I got this logs with logcat :

`07-23 14:06:23.766 19092 22672 W Firestore: (23.0.1) [p0]: (7b19cae) Stream closed with status: C1{code=INTERNAL, description=error in frame handler, cause=java.lang.IllegalAccessError: Illegal class access: 'e.b.M1.L.t.l' attemptin
g to access 'e.b.M1.x' (declaration of 'e.b.M1.L.t.l' appears in base.apk)
07-23 14:06:23.766 19092 22672 W Firestore:     at e.b.M1.L.t.l.c(Unknown Source:10)
07-23 14:06:23.766 19092 22672 W Firestore:     at e.b.M1.L.t.l.I(:5)
07-23 14:06:23.766 19092 22672 W Firestore:     at e.b.M1.x.run(Unknown Source:22)
07-23 14:06:23.766 19092 22672 W Firestore:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-23 14:06:23.766 19092 22672 W Firestore:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-23 14:06:23.766 19092 22672 W Firestore:     at java.lang.Thread.run(Thread.java:923)
07-23 14:06:23.766 19092 22672 W Firestore: }.
07-23 14:06:23.766   732   839 E Netd    : getNetworkForDns: getNetId from enterpriseCtrl is netid 0
07-23 14:06:23.768 19092 22569 I flutter : []
07-23 14:06:23.768 19092 22569 I flutter : user = null :(
`
"I flutter" is from my code.

**Comment by cpduran0622** [comment]
I add sha1 and sha256 key from the jks file used in the project.
Of course, the keys are not from play store console.
It is required to add sha1 and sha256 key of play store console to firebase project settings for firebase release apk?

**Comment by even-dev** [comment]
I found a solution. Try to add the following in your app/build.gradle : 
```gradle
buildTypes {
        release {
            shrinkResources false // line to add
            minifyEnabled false // line to add
            signingConfig signingConfigs.release
        }
    }
```

**Comment by cpduran0622** [comment]
It works. Thank you.

**Comment by reiui9** [comment]
> ```groovy-gradle
> 
>             shrinkResources false // line to add
>             minifyEnabled false // line to add
> ```

This is great  solution. You save my days Thanks :)
