### ISSUE TITLE
🐛 [firebase_core] firebase_core error

### ISSUE THREAD

**Issue by peter100u** [FirebaseExtended/flutterfire#6686]
## Bug report

**Describe the bug**
 I used the latest fluent environment and dart version, and then integrated the latest firebase fluent version, but there were some problems

### Flutter doctor

Run `flutter doctor` and paste the output below:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (5 available)

! Doctor found issues in 1 category.

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  flutter_colorpicker: 0.4.0
  cupertino_icons: ^1.0.2
  flutter_hooks: 0.18.0
  flutter_svg: 0.22.0
  get:
  styled_widget:
  lint:

### Flutter error 

E/flutter (21947): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (21947): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (21947): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (21947): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (21947): #3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:41)
E/flutter (21947): #4      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:37)
E/flutter (21947): #5      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:77:13)
E/flutter (21947): #6      Firebase.initializeApp (package:firebase_core/src/firebase.dart:41:47)
E/flutter (21947): #7      initServices (package:draw_talk/main.dart:34:18)
E/flutter (21947): #8      main (package:draw_talk/main.dart:10:9)
E/flutter (21947): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (21947): #10     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (21947): #11     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (21947): #12     _runZoned (dart:async/zone.dart:1789:10)
E/flutter (21947): #13     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (21947): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (21947): #15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (21947): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by markusaksli-nc** [comment]
Hi @peter100u 
Could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by axel-op** [comment]
I think the solution is to call `WidgetsFlutterBinding.ensureInitialized` before you call `runApp`, as shown in [the documentation](https://firebase.flutter.dev/docs/overview/):

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(App());
}
```
