### ISSUE TITLE
[firebase_admob] Could not hide ad immediately after displaying ad on flutter

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#669]
We have created the following class to display AdMob on flutter.

```dart
    import 'package:firebase_admob/firebase_admob.dart';
    import 'package:xxxxx/models/const.dart';
    
    class Ads {
      static BannerAd _bannerAd;
    
      static init() {
        FirebaseAdMob.instance.initialize(appId: Const.adAppId);
      }
    
      static BannerAd createBannerAd() {
        return new BannerAd(
          adUnitId: Const.adUnitId,
          size: AdSize.banner,
          targetingInfo: targetingInfo,
          listener: (MobileAdEvent event) {
            print("@@@ $event @@@");
          },
        );
      }
    
      static void showBanner() {
        if (_bannerAd == null) {
          _bannerAd = createBannerAd();
        }
    
        print('@@@ load @@@');
        _bannerAd.load().then((load) {
          print('@@@ show @@@');
          _bannerAd.show(anchorType: AnchorType.bottom);
        });
      }
    
      static void hideBanner() {
        print('@@@ dispose @@@');
        _bannerAd?.dispose();
        print('@@@ null @@@');
        _bannerAd = null;
      }
    
      static final MobileAdTargetingInfo targetingInfo = new MobileAdTargetingInfo(
        testDevices: Const.testDevices,
        keywords: Const.keywords,
        birthday: new DateTime.now(),
        gender: MobileAdGender.female,
      );
    }
```

The following values are correctly defined in the Const class.

`adAppId`, `adUnitId`, `testDevices`, `keywords`

`init()` is called immediately after startup.
`showBanner()` will be called when showing the ad.
`hideBanner()` will be called when hiding the ad.

These will work as expected in most cases.

But after `_bannerAd.show()` is called, the ad will not be hidden if `hideBanner()` is called before the listener receives `MobileAdEvent.loaded`.

[OK]
`_bannerAd.show()` -> receive `MobileAdEvent.loaded` -> `hideBanner()`
flutter: @@@ load @@@
flutter: @@@ show @@@
flutter: @@@ MobileAdEvent.loaded @@@
flutter: @@@ dispose @@@
flutter: @@@ null @@@

[NG]
`_bannerAd.show()` -> `hideBanner()` -> (receive `MobileAdEvent.loaded`)
flutter: @@@ load @@@
flutter: @@@ show @@@
flutter: @@@ dispose @@@
flutter: @@@ null @@@

This trouble occurred in ASUS Z017DA. iPad mini, iPhone 6 Plus and iPhone 4S were hidden normally at any timing. We can not test all models, but it may be a problem only for Android.

How can we avoid this if we do?

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.7.5, on Mac OS X 10.13.6 17G65, locale ja)
    • Flutter version 0.7.5 at /Applications/flutter
    • Framework revision eab5cd9853 (6 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xxxxx/src/android-sdks
    • Android NDK at /Users/xxxxx/src/android-sdks/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xxxxx/src/android-sdks
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (2 available)
    • ASUS Z017DA   • XXXXXXXXXXXXXXX                          • android-arm64 • Android 8.0.0 (API 26)
    • iPhone 6 Plus • xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx • ios           • iOS 11.4.1

• No issues found!
```

**Comment by kroikie** [comment]
@ganessaa

The issue at https://github.com/flutter/flutter/issues/21474 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by rockingdice** [comment]
This issue is a blocker for my app. I cannot hide the ad when the users choose to hide the ad by paying. Currently, I have to stop using Admob at all. This could be a very urgent requirement as there are many app developers who are using this like me.

**Comment by erperejildo** [comment]
> This issue is a blocker for my app. I cannot hide the ad when the users choose to hide the ad by paying. Currently, I have to stop using Admob at all. This could be a very urgent requirement as there are many app developers who are using this like me.

Same scenario here (and after 4 months)

**Comment by yunchiri** [comment]
Only solution is using another Admob package?

**Comment by erperejildo** [comment]
> Only solution is using another Admob package?

for me honestly it was. Also the official one doesn't support native ads

**Comment by yunchiri** [comment]
Thanks 

김영칠

**Comment by speedlightwp** [comment]
any updates? 

I have several ad units and different screen. When I am toggle/swipe between screens too "fast", the IOS able to close and open new ad perfectly fine however Android unable to dispose and close the old ad. Is there issues with Android OS?

**Comment by Skyost** [comment]
Is there any update about this one ? This issue has been reported on the [flutter repo](https://github.com/flutter/flutter/issues/21474) since september 2018.

**Comment by M1Joe** [comment]
Tossing my work around here in case it helps anyone.  Basically, only show the banner ad eent AFTER you receive the MobileAdEvent.loaded().

On init:
```
_bannerAd = createBannerAd()..load();
```

Load the ad
  ```
BannerAd createBannerAd() {
    return BannerAd(
      adUnitId: getAdUnitId(),
      size: AdSize.banner,
      targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) async {
        if (event == MobileAdEvent.loaded) {
          if (mounted) {
            showBannerAd();
          } 
        }
      },
    );
  }
```
Show the ad


```
  showBannerAd() {
    if (mounted) {
      _bannerAd.show(
        anchorType: AnchorType.bottom,
      );
    }
  }
```

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
