### ISSUE TITLE
[firebase_messaging] How to setGroup in the JSON?

### ISSUE THREAD

**Issue by lironzemingo** [FirebaseExtended/flutterfire#6691]
if collapseKey is set, will the notification be replaced with the new one on the users device? and also - is there a way  to setGroup in the message json? 

(a key to add here for exapmle:

`await admin.messaging().send({
  token: 'YOUR_TOKEN_HERE',
  apns: {
    payload: {
      aps: {
        threadId: 'foo',
        alert: 'Hello world',
      },
    },
  },
  android: {
    collapseKey: 'foo',
    notification: {
      title: 'Hello world',
    },
  },
});` )

‘collapseKey’ is not group. Don’t close without testing

Group notification https://developer.android.com/training/notify-user/group

_Originally posted by @bhanuka96 in https://github.com/FirebaseExtended/flutterfire/issues/1736#issuecomment-725411355_

**Comment by markusaksli-nc** [comment]
Hi @lironzemingo 
There is already an open issue for this https://github.com/FirebaseExtended/flutterfire/issues/6068
Please comment any relevant information on the mentioned issue.
Thank you
