### ISSUE TITLE
The method 'useFirestoreEmulator' isn't defined for the type 'FirebaseFirestore'. (Documentation)

### ISSUE THREAD

**Issue by dark-chocolate** [FirebaseExtended/flutterfire#6692]
In the [Emulator Usage docs](https://firebase.flutter.dev/docs/firestore/usage/#emulator-usage), there's a code

```dart
 FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
```

It may have existed in previous version of the [cloud_firestore plugin](https://pub.dev/packages/cloud_firestore) but it isn't there anymore.

> The method 'useFirestoreEmulator' isn't defined for the type 'FirebaseFirestore'. (Documentation)

**Comment by Patil2099** [comment]
I would love to work on it what would be the example then in the docs ? @dark-chocolate

**Comment by markusaksli-nc** [comment]
Hi @dark-chocolate 
Not sure what you mean by "isn't there"? It is still clearly defined in the source code and works in `cloud_firestore: ^2.4.0`.
https://github.com/FirebaseExtended/flutterfire/blob/4fbd97a4c2698d59003700c6cc1d1f110dc2deff/packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart#L108
Maybe you are on an outdated version?
Thank you

**Comment by dark-chocolate** [comment]
@markusaksli-nc I'm so sorry, it was showing something like 'undefined method' or something. But now it's not. Apologize :(
