### ISSUE TITLE
[firebase_in_app_messaging] Homepage

### ISSUE THREAD

**Issue by BugsBunnyBR** [FirebaseExtended/flutterfire#67]
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_in_app_messaging/pubspec.yaml homepage points to this repo, but looking at the link to HomePage here
https://pub.dev/packages/firebase_in_app_messaging
It is pointing to flutter/plugins.

So, the version in the plugin pubspec.yaml matches the one published, so I don't really know where is the bug. Was the homepage updated without a plugin release?

**Comment by Ehesp** [comment]
This is now resolved, links on Pub go correctly to this repo.
