### ISSUE TITLE
🐛 [firebase_core] it show an error when i start debugging 

### ISSUE THREAD

**Issue by AimenSayoud** [FirebaseExtended/flutterfire#6703]
when i start building the app it shows me this error
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :firebase_core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
```

it wasn't showing me this error only recently.

when i start building the project in the emulator  in android studio  this error shows 

i m using the latest version of firebase_core.

**Comment by markusaksli-nc** [comment]
Hi @AimenSayoud 
Are you overriding the internally managed firebase SDK version in your `build.gradle`?
Thank you

**Comment by AimenSayoud** [comment]
> Hi @AimenSayoud
> Are you overriding the internally managed firebase SDK version in your `build.gradle`?
> Thank you

No 
i added firebase to project
`
    dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:28.2.1')
    implementation "com.google.firebase:firebase-analytics"
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
`

`    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'

    }
`

**Comment by markusaksli-nc** [comment]
Well you are overriding the internally managed version with this line
```
implementation platform('com.google.firebase:firebase-bom:28.2.1')
```
Please remove the line if you do not specifically need to override the version. Adding this override is strictly **optional** and not recommended since the FlutterFire plugins are tested against a fixed internally managed version.

**Comment by AimenSayoud** [comment]
the same problem showing after removing it 
```
Launching lib\main.dart on SM M215F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :firebase_core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by markusaksli-nc** [comment]
Could you provide your `build.gradle` and `app/build.gradle`?

**Comment by AimenSayoud** [comment]
i resolve this problem by deleting 
the 
root.text of the firebase version it is in the 
/build.gradle
and i built the project again.
