### ISSUE TITLE
[firebase_messaging] onMessage, onResume ,onLaunch don't get triggered on iOS, but work perfectly fine on android

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#671]
While using the plugin `firebase_messaging: ^2.0.0`, everything works well, when receiving notifications on android devices.
 I see all print statements in `OnMessage`, `OnResume` and `OnLaunch` and the notification is the notification tray.
But on iOS, all i see is the basic(no data payload ) notification in the notification tray(I'm sending notifications from the firebase console). No Print statements are displayed in the above methods.
I can't seem to wrap my head around what's actually happening. 
When i also use the generated `FCM_TOKEN`, i get the notification(no payload data), but the methods are not triggered.

Can i please get some help @collinjackson . Please
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-CM)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by kroikie** [comment]
@trey-rosius

The issue at https://github.com/flutter/flutter/issues/21443 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing in favour of more recent one https://github.com/FirebaseExtended/flutterfire/issues/191
