### ISSUE TITLE
🐛 [Firestore] Document ChangeType error

### ISSUE THREAD

**Issue by mqhamdam** [FirebaseExtended/flutterfire#6724]
## Bug report

It's not a big bug.  But it was so hard to find its reason.
If I save document using FieldValue.serverTimestamp like this 
```dart
FirebaseFirestore.instance
.collection("channels")
.doc(widget.channelID)
.collection("posts")
.add({
"CREATED_AT": FieldValue.serverTimestamp(),
"TYPE": "TEXT",
"TEXT": _textEditingController.text,
});
```
Query Snapshot Document Change returns two types;
first, it returns DocumentChangeType.add
then after 1/2 seconds, it returns Modified change Type.
So every time I save one document I will get two snapshots. 
So to avoid second rebuilding in the app I just check if the "CREATED_AT" value is null don't rebuild widget. But it's not a very good solution. It would be good to have an option something like "call document modified" when using ServerSide write, update operations. 
Thanks!

**Comment by markusaksli-nc** [comment]
Hi @mqhamdam 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by mqhamdam** [comment]
@markusaksli-nc That's not a client-side error. The reason why I'm getting a second snapshot when listening to it is - Firestore modifies the document on serverside because of FieldValue.serverTimestamp();

**Comment by markusaksli-nc** [comment]
If you think this isn't dependent on the client behavior then we can't really do anything about it. This repository just wraps the native Firebase SDKs so they could be called from dart. This sounds like a more appropriate issue for https://firebase.google.com/support
