### ISSUE TITLE
Authentication via Facebook not retrieve idToken

### ISSUE THREAD

**Issue by waltersfilho** [FirebaseExtended/flutterfire#6731]
Guys, 

Using your lib (thanks for existing), logging in via facebook, I can't get the idToken (Bearer) and consequently authorize my backend.
Can you help me or is it something not implemented?

Thanks,
Reguards

**Comment by markusaksli-nc** [comment]
Hi @waltersfilho 
Not sure what you mean by our lib. Logging in through facebook is done with [`facebook_auth`](https://pub.dev/packages/flutter_facebook_auth). This issue seems better suited to their repository.
Thank you
