### ISSUE TITLE
🐛 [cloud_firestore/unknown] An error occured while parsing query arguments, see native logs for more information. Please report this issue.

### ISSUE THREAD

**Issue by mqhamdam** [FirebaseExtended/flutterfire#6742]
## Bug report

**Describe the bug**
using collection group to query collections.
```
//get current user id
 final currentUserId = FirebaseAuth.instance.currentUser!.uid;
final collectionGroup = await FirebaseFirestore.instance
        .collectionGroup("subscribers")
        .where(FieldPath.documentId, isEqualTo: currentUserId)
        .get();
```
document id is: 2baf82bb-301d-4a51-bd12-728fae89a7b2 (which is manually assigned user id using firebase admin sdk)

**Comment by markusaksli-nc** [comment]
Hi @mqhamdam 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you
