### ISSUE TITLE
🐛 [analytics, crashlytics, core, messaging] Remove unused deprecated V1 embedding

### ISSUE THREAD

**Issue by juliansteenbakker** [FirebaseExtended/flutterfire#6745]
## Bug report

Right now these plugins support both embedding V1 and V2. However because all of the plugins are migrated to null-safety, the minimum supported version of flutter always support embedding v2, and thus embedding v1 is not necessary anymore. Right now the embedding V1 causes deprecation warnings on all of these plugins.

### Steps to reproduce

1. Build the plugins and they will al give the following warnings:
```
warning: [deprecation] Registrar in PluginRegistry has been deprecated
  private PluginRegistry.Registrar registrar;
```

```
warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
```

### Expected behavior

When the old embedding is removed, no more warning is thrown.
This will also fix #3876

---

## Additional context

I don't think this will cause any backwards compatibility issues since all versions of flutter that are supported by these plugins do support embedding v2.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)

```

</details>

**Comment by russellwheatley** [comment]
Closing as this work has taken place.
