### ISSUE TITLE
firebase_auth does not support GitHub login, but Firebase Authentication does

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#675]
Feature request to support GitHub login with `firebase_auth`

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/21331 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing as it's fixed in https://github.com/flutter/plugins/pull/768
