### ISSUE TITLE
🐛firebase_in_app_messaging. .gradle\caches\transforms-2\files-2.1\68cd8030821684af96bc1be5fd14c743\firebase-inappmessaging-display-20.0.0\AndroidManifest.xml:14:5-20:15: AAPT: error: unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by DineshTaral12** [FirebaseExtended/flutterfire#6762]
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @DineshTaral12 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
