### ISSUE TITLE
firebase_in_app_messaging. .gradle\caches\transforms-2\files-2.1\68cd8030821684af96bc1be5fd14c743\firebase-inappmessaging-display-20.0.0\AndroidManifest.xml:14:5-20:15: AAPT: error: unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by DineshTaral12** [FirebaseExtended/flutterfire#6764]
getting issue when try to run the app, after adding firebase_in_app_messaging plugin.

.gradle\caches\transforms-2\files-2.1\68cd8030821684af96bc1be5fd14c743\firebase-inappmessaging-display-20.0.0\AndroidManifest.xml:14:5-20:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by darshankawar** [comment]
@DineshTaral12 

It seems to be pointing to gradle cache. Can you try by clearing the gradlew cache and try again ?

```
cd android
./gradlew clean
cd ..
flutter clean
flutter run
```

Also, when you add `firebase_in_app_messaging`, you'll need to follow other steps to properly make use of it.
See this link for Android integration and check if it helps: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_in_app_messaging/README.md#android-integration
