### ISSUE TITLE
[📚] FirebaseException error code list

### ISSUE THREAD

**Issue by sjoerd0301** [FirebaseExtended/flutterfire#6765]
Hi!

I'm having trouble finding all the different error codes which can be thrown through different plugins.
Currently I've found the auth exception codes [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart).

But for e.g. FirebaseStorage the codes aren't defined in the plugin source, i've found [this (web)](https://firebase.google.com/docs/storage/web/handle-errors) and [this (android)](https://firebase.google.com/docs/storage/android/handle-errors) but these differ.

I was wondering if there exists a list for every code every plugin can throw?
Because the plain codes aren't very user friendly.

edit:
Also, I've found the GRPC statuscodes though stackoverflow. I take it these are generic statuscodes? [GRPC](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md)

**Comment by darshankawar** [comment]
@sjoerd0301 
There's similar open issue describing your case, https://github.com/FirebaseExtended/flutterfire/issues/6326
Please follow-up there for updates.
Closing this as duplicate.

**Comment by sjoerd0301** [comment]
Please bear in mind that the other issue only addresses auth and functions

**Comment by darshankawar** [comment]
@sjoerd0301 
Yes, the other issue is probably for all flutterfire plugins too and not specific to only those 2 plugins. I'll bring this to team's notice.
