### ISSUE TITLE
🐛 [Messaging] FCM token does not refresh after deleting token via deleteToken() on iOS 

### ISSUE THREAD

**Issue by helenaford** [FirebaseExtended/flutterfire#6766]
## Bug report

**Describe the bug**
Prior to installations, `deleteToken` on iOS is used to refresh the token. Since the update, no longer invalidates the token.

Also please see the related issue for RNFB https://github.com/invertase/react-native-firebase/issues/5570

I believe you have to delete the installations id first which then makes subsequent calls of `deleteToken` generate a new one

1. call `await FirebaseMessaging.instance.deleteToken();`
2. call `await FirebaseMessaging.instance.getToken();`
4. See that the token has not changed

### Expected behavior

A new FCM token should be generated, and the old one should be invalidated

### Sample project

The current `messaging` example app on master branch, with the following button added:

```
      ElevatedButton(
          onPressed: () async {
            print('Example: Getting FCM before');
            String before = await FirebaseMessaging.instance.getToken();
            await FirebaseMessaging.instance.deleteToken();
            String after = await FirebaseMessaging.instance.getToken();
            print('CHANGED token?? : ${before != after}');
          },
          child: const Text('Delete token')),

```

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report. I see the same behavior using [latest](https://pub.dev/packages/firebase_messaging/install) messaging plugin version and using the plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and using the code snippet shared above.

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.107

• No issues found!



```

</details>

**Comment by helenaford** [comment]
@darshankawar thank you for confirming and testing it out. I have also opened an issue with the `ios SDK` repo https://github.com/firebase/firebase-ios-sdk/issues/8491

**Comment by Salakar** [comment]
Closing since it looks like the upstream issue has been addressed - thanks :)
