### ISSUE TITLE
get documents in array of strings cloud in flutter using cloud firestore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#677]
it seems it is harder than i think, i am building a flutter app and using cloud firestore as a database that is my simple database looks like
<img src="https://i.stack.imgur.com/32P6i.png">
what i want is to retrieve all documents of the collection "DriverList" in an array of string and retrieve its data in an array of object of driver class all the examples i found was building a new screen with widget that has a stream and a stream builder and return the content into a ListView

**Comment by kroikie** [comment]
@ahmedelsayedkhalafallah

The issue at https://github.com/flutter/flutter/issues/21281 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@ahmedelsayedkhalafallah is the issue still relevant?

**Comment by kroikie** [comment]
@ahmedelsayedkhalafallah You will have to use a Query to request all documents at `DriverList` path. That will return a `QuerySnapshot` which will contain all the `documents`. You will have to traverse the documents to create the String and Object arrays you desire.
