### ISSUE TITLE
[📚] [cloud-messaging] Page not found for "Send messages to topics" link

### ISSUE THREAD

**Issue by dark-chocolate** [FirebaseExtended/flutterfire#6777]
On [Topics](https://firebase.flutter.dev/docs/messaging/usage/#topics) page, there's a line:

> To learn more about how to send messages to devices subscribed to topics, view the [Send messages to topics](https://firebase.flutter.dev/docs/messaging/usage/server-integration#send-messages-to-topics) documentation.

But the link is broken.

**Comment by darshankawar** [comment]
Thanks for reporting.

<img width="1056" alt="Screenshot 2021-08-09 at 1 42 12 PM" src="https://user-images.githubusercontent.com/67046386/128677163-f33f53f5-f749-48b5-bdb9-0a75bfda1fd2.png">

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by darshankawar** [comment]
Closing this as resolved, since, clicking on `send messages to topic` link from the documentation properly opens the link.

Correct url: https://firebase.flutter.dev/docs/messaging/server-integration#send-messages-to-topics
