### ISSUE TITLE
drawercontroller stop at tint screen on both open and close drawer

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#678]
1. When drag or click icon to open drawer, drawer didn't open but the screen were tinted.  I can then drag out the drawer.  
2. When trigger `Navigator.pop(context);` The drawer closed but the screen remind tinted, need extra tap to clear.

Tested in android device and emulator, `drawerCallback` simply updated a variable
Code in
```dart
Scaffold(
drawer: DrawerController(child: DrawerOnly(), alignment: DrawerAlignment.start, drawerCallback: drawerCallback),
```
instead of (this works)
```
drawer: DrawerOnly(),
```

**Comment by kroikie** [comment]
@oberon168

The issue at https://github.com/flutter/flutter/issues/21272 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing basing on https://github.com/flutter/flutter/issues/21272#issuecomment-479868411
