### ISSUE TITLE
🐛 [cloud_firestore]  upgrading to ^2.4.0 breaks web - switching back to ^2.2.2 fixes it.

### ISSUE THREAD

**Issue by m-j-g** [FirebaseExtended/flutterfire#6781]
When I upgrade to cloud_firestore 2.3.0 OR 2.4.0 and change nothing else - web just loads a blank screen with the error below.  Switching back to ^2.2.2 and the error goes away and it loads again. 
The transitive dependency changes are
  cloud_firestore_platform_interface:   version: "5.1.2" ->  version: "5.3.0"
  cloud_firestore_web:     version: "2.1.2" -> version: "2.3.0"
  firebase_core:   version: "1.3.0" -> version: "1.4.0"

Works on iOS and Android

`Error: UnimplementedError: settings getter is not implemented
    at Object.throw_ [as throw] (http://localhost:7357/dart_sdk.js:5348:11)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings (http://localhost:7357/packages/cloud_firestore_platform_interface/src/platform_interface/utils/load_bundle_task_state.dart.lib.js:2146:17)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings [as settings] 
`

**Comment by ndharmateja** [comment]
@m-j-g I am getting the same issue even on ^2.2.2

**Comment by m-j-g** [comment]
> @m-j-g I am getting the same issue even on ^2.2.2

Does it work for you on any version? It seems you can get this error when your index.html file isn’t configured, so you might look at that. In my case it is setup and working on 2.2.2 but not on 2.4

**Comment by ndharmateja** [comment]
I have tried only 2.4.0 and 2.2.2. I haven't tried the remaining

> > @m-j-g I am getting the same issue even on ^2.2.2
> 
> Does it work for you on any version? It seems you can get this error when your index.html file isn’t configured, so you might look at that. In my case it is setup and working on 2.2.2 but not on 2.4

I have tried only 2.4.0 and 2.2.2
I will try other versions as well
What do you mean by configuring index.html? i am currently using 8.6.1 version of firebase js sdk

**Comment by m-j-g** [comment]
> > > @m-j-g I am getting the same issue even on ^2.2.2
> > 
> > 
> > Does it work for you on any version? It seems you can get this error when your index.html file isn’t configured, so you might look at that. In my case it is setup and working on 2.2.2 but not on 2.4
> 
> I have tried only 2.4.0 and 2.2.2
> I will try other versions as well
> What do you mean by configuring index.html? i am currently using 8.6.1 version of firebase js sdk

https://github.com/flutter/flutter/issues/69199

**Comment by ndharmateja** [comment]
> > > > @m-j-g I am getting the same issue even on ^2.2.2
> > > 
> > > 
> > > Does it work for you on any version? It seems you can get this error when your index.html file isn’t configured, so you might look at that. In my case it is setup and working on 2.2.2 but not on 2.4
> > 
> > 
> > I have tried only 2.4.0 and 2.2.2
> > I will try other versions as well
> > What do you mean by configuring index.html? i am currently using 8.6.1 version of firebase js sdk
> 
> [flutter/flutter#69199](https://github.com/flutter/flutter/issues/69199)

Yeah I did configure all that. Still facing the same issue in 2.2.2. Unable to use emulators.

**Comment by darshankawar** [comment]
@m-j-g 
I tried the official plugin example using latest version and on stable and it ran on web without any issues for me.

`cloud_firestore: "^2.4.0"`

```
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
```

<img width="621" alt="Screenshot 2021-08-10 at 1 31 22 PM" src="https://user-images.githubusercontent.com/67046386/128831155-a537697d-b13e-46b9-ab19-5bf8c06c49e6.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by m-j-g** [comment]
Guess I'll just stay on 2.2.2

**Comment by m-j-g** [comment]
It would be great if there were some steps to troubleshooting this.  I have spent the last 2 days just having to guess at changes, run it again and see if I don't get "Error: UnimplementedError: settings getter is not implemented".  This has really been a bad experience.  I have tried removing dependencies from both the index.html and the pubspec.yaml.  
I'm pretty certain its a change in:
name: cloud_firestore_platform_interface from 5.1.2 -> 5.3.0.  
Would hope that someone would know what is causing this.

**Comment by m-j-g** [comment]
Figured it out.
 final FirebaseFirestore _db = FirebaseFirestore.instance..settings = Settings();
Works on iOS & Android on cloud_firestore 2.4.0, and also works on all 3 on cloud_firestore 2.2.2, but not on the web for 2.4.0.  No error in the IDE, no breaking change announcement.  Frustrating loss of a couple of days.

**Comment by darshankawar** [comment]
@m-j-g 
Thanks for digging in. From what I saw in the documentation, `FirebaseFirestore.instance..settings = Settings();` is used if you want to configure offline persistence.
So, for mobile, the offline persistence is enabled by default and for web, it is disabled by default.

https://firebase.google.com/docs/firestore/manage-data/enable-offline

With below code snippet, for plugin version 2.2.0 to 2.4.0 and running on web:

```
FirebaseFirestore.instance.settings =
    Settings(persistenceEnabled: false);`
```

gives me the exact error that you reported. But to run on web, you need to use below snippet:

```
// Web.
await FirebaseFirestore.instance.enablePersistence();
```

https://firebase.flutter.dev/docs/firestore/usage/#access-data-offline

Can you try the same (above) for web using latest plugin version and see if you still get the same error ?

**Comment by m-j-g** [comment]
I'm not trying to enable persistence.  It was being used to set a custom cache size.

**Comment by darshankawar** [comment]
> It's more than persistence. There are 4 configurable settings. I'm not trying to enable persistence. It was being used to set a custom cache size.

@m-j-g 
Would be great if you could provide a code sample that shows the configurable settings, because per my earlier comment, `FirebaseFirestore.instance.settings` throws the same error on 2.2.0 and 2.4.0 on all platforms

**Comment by m-j-g** [comment]
final FirebaseFirestore _db = FirebaseFirestore.instance;
   _db.settings = Settings(cacheSizeBytes: 100000000);

nowI put a if (!kIsWeb) {} around the 2nd line, so that it doesn't crash on 2.4.0 web.

**Comment by darshankawar** [comment]
@m-j-g 
Tried again by adding below dependencies:

```
  cloud_firestore: "^2.2.2"
  cloud_firestore_web: ^2.1.2
  cloud_firestore_platform_interface: ^5.1.2
```

And then using the code snippet you provided above as:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if (USE_FIRESTORE_EMULATOR) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }

  final FirebaseFirestore _db = FirebaseFirestore.instance;
  _db.settings = Settings(cacheSizeBytes: 100000000);

  runApp(FirestoreExampleApp());
}
```

And ran it on web (flutter run -d chrome) which led to following error, same as yours:

```
Error: UnimplementedError: settings getter is not implemented
    at Object.throw_ [as throw] (http://localhost:50825/dart_sdk.js:5087:11)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings

```

Indicating this seems to be occuring for previous versions of the plugin as well. If this isn't a correct representation of the issue, can you provide the dependency versions on which it worked ?

**Comment by m-j-g** [comment]
2.2.2

**Comment by m-j-g** [comment]
The versions for the transitive are in the first post. When I switch to 2.2.2 or lower it works on web. I’ve had this in there for probably 6+ months and all the previous versions worked as well

**Comment by darshankawar** [comment]
I am unable to replicate it based on the details provided in above thread, so keeping it open for further insights from the team.
