### ISSUE TITLE
🐛 [dynamic_links] FirebaseDynamicLinks.instance.getInitialLink() does not return null after first call

### ISSUE THREAD

**Issue by djadu** [FirebaseExtended/flutterfire#6784]
## Bug report

**Describe the bug**
According to the documentation for FirebaseDynamicLinks.instance.getInitialLink(): 

> Attempts to retrieve the dynamic link which launched the app.
> This method always returns a Future. That Future completes to null if there is no pending dynamic link **or any call to this method after the the first attempt**.

However every time this method is called after launching the app the link is returned.

I am calling this method on initState of a StatefulWidget to launch the deep link, so the link is launched every time that widget page is viewed. This happens on both iOS and Android.

### Steps to reproduce

1. Create an app with at least 2 pages
2. The first page should have a stateful widget that calls `FirebaseDynamicLinks.instance.getInitialLink()` and launches the link if it's not null
3. Create and share a Firebase dynamic link to your app
4. Ensure your app is force closed on the device
5. Launch the link on the device that has the correct app version installed to handle the dynamic link
6. App launches as expected and dynamic link is launched within app
7. Go to another page or view in your app
8. Return to the page or view that launches the dynamic link
9. Dynamic link is launched again
10. Repeat 7 to 9 and behavior continues until app is force closed.

### Expected behavior

The first time `FirebaseDynamicLinks.instance.getInitialLink()` is called it should return the link, but subsequent calls should return null.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3

dependencies:
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.7 [firebase_core flutter]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report and steps to replicate. I see the same behavior using [latest](https://pub.dev/packages/firebase_dynamic_links/install) plugin version and on latest master.

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.40, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.40 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7d76a827c0 (13 hours ago), 2021-08-09 15:21:17 -0700
    • Engine revision 4fef55db10
    • Dart version 2.14.0 (build 2.14.0-385.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 92.0.4515.131

• No issues found!



```

</details>

**Comment by djadu** [comment]
thanks @darshankawar. I have implemented a workaround for now

**Comment by theochampion** [comment]
We are running into the same issue on our app in production, is there any updates on this?

**Comment by Hitesh2812** [comment]
Getting the same issue FirebaseDynamicLinks.instance.getInitialLink() does not return null after first call

**Comment by mpiparo** [comment]
same here.  - keeps returning link after first call instead of null. created a simple workaround with a class member flag, but it ain't pretty.. :-/

```
        PendingDynamicLinkData? initialLink;
        if (!initialLinkFetched) {
          initialLink = await _firebaseDynamicLinks.getInitialLink();
          initialLinkFetched = true;
        }
```

**Comment by Lcadiou** [comment]
Exact same problem here on our production app, the problem only happens on Android, iOS is fine.

**Comment by robyhuzwandar** [comment]
Does anyone have a solution?

**Comment by w00ter123456** [comment]
> same here. - keeps returning link after first call instead of null. created a simple workaround with a class member flag, but it ain't pretty.. :-/
> 
> ```
>         PendingDynamicLinkData? initialLink;
>         if (!initialLinkFetched) {
>           initialLink = await _firebaseDynamicLinks.getInitialLink();
>           initialLinkFetched = true;
>         }
> ```

well if you go to another screen and go back this wont work since that bool initialLinkFetched will be reset. If you save it as shared preference it also wont work because then you wont be able to open new concurrent links since the value is saved as true.

**Comment by w00ter123456** [comment]
> thanks @darshankawar. I have implemented a workaround for now

what is you're workaround? Can you share?

**Comment by mpiparo** [comment]
> > same here. - keeps returning link after first call instead of null. created a simple workaround with a class member flag, but it ain't pretty.. :-/
> > ```
> >         PendingDynamicLinkData? initialLink;
> >         if (!initialLinkFetched) {
> >           initialLink = await _firebaseDynamicLinks.getInitialLink();
> >           initialLinkFetched = true;
> >         }
> > ```
> 
> well if you go to another screen and go back this wont work since that bool initialLinkFetched will be reset. If you save it as shared preference it also wont work because then you wont be able to open new concurrent links since the value is saved as true.

That is true and something to keep in mind, but in my case I'm doing this in a top level bloc being provided downstream, so it's essentially global to the app, so it works across nav to pages. But we do really need a permanent solution for this, especially since it's not working as documented.

**Comment by daniel-hopkins** [comment]
Chiming in with the same issue

**Comment by daniel-hopkins** [comment]
I think I may at least fixed my initial crash. I moved the call to _after_ `WidgetsFlutterBinding.ensureInitialized();`
from
```
await _dynamicLinkService.handleDynamicLinks(); 
WidgetsFlutterBinding.ensureInitialized();
```
 to 
```
WidgetsFlutterBinding.ensureInitialized();
await _dynamicLinkService.handleDynamicLinks();
```

**Comment by w00ter123456** [comment]
I also worked out a workaround. 

Added a parameter with an unique random code to my dynamic link.
When creating the link im pushing this code to my database. When receiving the link im once again checking the database. if this code exists im dropping the row and send success back to the app. The second time the this row doesnt exist on my db so it cannot be called again.

**Comment by hiru-vn** [comment]
please fix the one on Android

**Comment by Lcadiou** [comment]
Is there any progress ?

**Comment by davideroffo** [comment]
any progress? having the same issue ...

**Comment by russellwheatley** [comment]
Hey guys, have you tried the latest dynamic links version? The API has been updated significantly and the latest version is now `4.0.3`. Please take a look at the [changelog here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_dynamic_links/firebase_dynamic_links/CHANGELOG.md).

**Comment by tungpham6195** [comment]
still got the same issue, even I tried the latest version `4.0.3`

**Comment by Lcadiou** [comment]
Yes, I've tried again without the workaround, and the problem is still the same, the link in not "consumed".

**Comment by desmeit** [comment]
I have the same issue.

**Comment by ChristianConstantNel** [comment]
Tested the new version 4.0.6. It seems to be working on Android, but not on IOS.
