### ISSUE TITLE
Error RemoteMessage not found

### ISSUE THREAD

**Issue by ArslanKhan99** [FirebaseExtended/flutterfire#6787]
```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {

  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print("Handling a background message: ${message.messageId}");

  // Use this method to automatically convert the push data, in case you gonna use our data standard
  AwesomeNotifications().createNotificationFromJsonData(message.data);
}
```

**Comment by ArslanKhan99** [comment]
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/firebase_messaging.dart:12:8: Error: Error when reading '/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-3.0.3/lib/firebase_messaging_platform_interface.dart': The system cannot find the path specified.

import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart';
       ^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/firebase_messaging.dart:14:1: Error: Error when reading '/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-3.0.3/lib/firebase_messaging_platform_interface.dart': The system cannot find the path specified.

export 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:14:3: Error: Type 'FirebaseMessagingPlatform' not found.
  FirebaseMessagingPlatform? _delegatePackingProperty;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:16:3: Error: Type 'FirebaseMessagingPlatform' not found.
  FirebaseMessagingPlatform get _delegate {
  ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:62:17: Error: Type 'RemoteMessage' not found.
  static Stream<RemoteMessage> get onMessage =>
                ^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:73:17: Error: Type 'RemoteMessage' not found.
  static Stream<RemoteMessage> get onMessageOpenedApp =>
                ^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:82:35: Error: Type 'BackgroundMessageHandler' not found.
  static void onBackgroundMessage(BackgroundMessageHandler handler) {
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:100:10: Error: Type 'RemoteMessage' not found.
  Future<RemoteMessage?> getInitialMessage() {
         ^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:142:10: Error: Type 'NotificationSettings' not found.
  Future<NotificationSettings> getNotificationSettings() {
         ^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:160:10: Error: Type 'NotificationSettings' not found.
  Future<NotificationSettings> requestPermission({
         ^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:14:3: Error: 'FirebaseMessagingPlatform' isn't a type.
  FirebaseMessagingPlatform? _delegatePackingProperty;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:17:41: Error: The getter 'FirebaseMessagingPlatform' isn't defined for the class 'FirebaseMessaging'.
 - 'FirebaseMessaging' is from 'package:firebase_messaging/firebase_messaging.dart' ('/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/firebase_messaging.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FirebaseMessagingPlatform'.
    return _delegatePackingProperty ??= FirebaseMessagingPlatform.instanceFor(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:63:7: Error: Getter not found: 'FirebaseMessagingPlatform'.
      FirebaseMessagingPlatform.onMessage.stream;
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:74:7: Error: Getter not found: 'FirebaseMessagingPlatform'.
      FirebaseMessagingPlatform.onMessageOpenedApp.stream;
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:82:35: Error: 'BackgroundMessageHandler' isn't a type.
  static void onBackgroundMessage(BackgroundMessageHandler handler) {
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/arsla/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging-10.0.4/lib/src/messaging.dart:83:5: Error: Getter not found: 'FirebaseMessagingPlatform'.
    FirebaseMessagingPlatform.onBackgroundMessage = handler;
    ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by darshankawar** [comment]
@ArslanKhan99 
Just posting error log won't help to identify the root-cause. Please use the `new issue -> bug report -> Get started` link and provide the requested details, so that we can properly address this issue.

**Comment by ArslanKhan99** [comment]
error resolved there was problem of multiple versions installation. remove all old versions solved the issue.
