### ISSUE TITLE
[firebase_messaging] onLaunch and onResume doesn't works

### ISSUE THREAD

**Issue by KyllianDM** [FirebaseExtended/flutterfire#68]
Hello,
In the example of firebase_messaging, the onLaunch and onResume callback doens't works, but onMessage works when the app is on the foreground.

**Comment by MahmoodBakhshayesh** [comment]
hello, 
i have the same problem, 
apparently it has something to do with notification channel id , because i get this message on console:
"Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used." 
and yet i don't know how to solve it.

**Comment by KyllianDM** [comment]
The notification channel is the « sort » of the notification (ex. : friend request, new message, promotion, etc).


________________________________
De : Mahmood Bakhshayesh <notifications@github.com>
Envoyé : Wednesday, September 4, 2019 8:48:46 AM
À : FirebaseExtended/flutterfire <flutterfire@noreply.github.com>
Cc : KyllianDM <kylliandm@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [FirebaseExtended/flutterfire] [firebase_messaging] onLaunch and onResume doesn't works (#68)


hello,
i have the same problem,
apparently it has something to do with notification channel id , because i get this message on console:
"Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used."
and yet i don't know how to solve it.

**Comment by KyllianDM** [comment]
Hey @MahmoodBakhshayesh, I've founded the source of the bug.
"Make sure to include click_action: FLUTTER_NOTIFICATION_CLICK as a "Custom data" key-value-pair (under "Advanced options") when targeting an Android device. The Firebase Console does not support sending data messages."
