### ISSUE TITLE
🐛 [firebase_storage] Update iOS SDK version to 8.5.0 to fix error on local emulators using http

### ISSUE THREAD

**Issue by afnx** [FirebaseExtended/flutterfire#6800]
I'm seeing the following error when I try to connect to local storage emulator using http in my local network (from iOS device to computer via local ip):

`Insecure fetch request has a scheme (http) not found in fetcher allowedInsecureSchemes ( @[] ):` 

I believe that the plugin currently depends on the version 8.3.0 of Firebase iOS SDK, but this issue has already been fixed in the newest version (8.5.0):

https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseStorage/CHANGELOG.md#850

Is it possible to update to the newest version anytime soon?

**Comment by markusaksli-nc** [comment]
Hi @afnx 
Have you done https://firebase.flutter.dev/docs/installation/ios#enabling-use-of-firebase-emulator-suite?
Thank you

**Comment by afnx** [comment]
Hi @markusaksli-nc. Yes, I've already done it.

**Comment by afnx** [comment]
@russellwheatley Oh, I didn't notice that PR. Thanks a lot.
