### ISSUE TITLE
A problem occurred configuring project ':firebase_core'. HELP!!

### ISSUE THREAD

**Issue by mmuttaqin** [FirebaseExtended/flutterfire#6802]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_core'.
> Could not resolve all artifacts for configuration ':firebase_core:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50.
     Required by:
         project :firebase_core > com.android.tools.build:gradle:3.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.lint:lint-gradle-api:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:gradle-api:3.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:common:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:manifest-merger:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.analytics-library:tracker:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4 > com.android.tools.analytics-library:shared:26.5.4
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.50/kotlin-stdlib-jdk8-1.3.50.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.50/kotlin-stdlib-jdk8-1.3.50.pom'.
               > repo.maven.apache.org: nodename nor servname provided, or not known
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.50.
     Required by:
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.lint:lint-gradle-api:26.5.4
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.50.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.50/kotlin-reflect-1.3.50.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.50/kotlin-reflect-1.3.50.pom'.
               > repo.maven.apache.org
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.0.
     Required by:
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-core:1.0.0-beta04
         project :firebase_core > com.android.tools.build:gradle:3.5.4 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0/kotlin-stdlib-1.3.0.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0/kotlin-stdlib-1.3.0.pom'.
               > repo.maven.apache.org
> Could not get unknown property 'android' for project ':firebase_core' of type org.gradle.api.Project.

**Comment by markusaksli-nc** [comment]
Hi @mmuttaqin 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Could you also provide your `android/build.gradle`?
Thank you
