### ISSUE TITLE
🐛 [firebase_dynamic_links] Links not opening correctly due to trailing slash in URL being removed

### ISSUE THREAD

**Issue by mvrsn** [FirebaseExtended/flutterfire#6805]
## Bug report
This problem has been reported in https://github.com/FirebaseExtended/flutterfire/issues/6242 already, but the issue has been stale/ignored for a long time so I decided to open up a new one so that we hopefully can get this problem solved

### The problem
When following the guide to get dynamic links to work for Firebase email login I ran into an issue that the app opens, but no dynamic link is being registered in the app so no listener is triggered

### Possible issue
I believe everything is set up correctly in my project, but when I click the link in the email the app opens as expected, but the `onLink` listener is never triggered. I started looking into the FirebaseDynamicLinks pod, and may have found an issue

Inside the `FIRDLIsURLForAllowedCustomDomain()` method in `FDLUtilities` the following check is happening: `urlStr.length > domainURIPrefixStr.length + 1 && ([urlStr characterAtIndex:domainURIPrefixStr.length] == '/')`

At first this looked legit, until I noticed that the `/` that is being looked for in `urlStr` is not actually there, and a `?` is found instead, meaning that `customDomainMatchFound` will be false

Looking at the link found in the email, the `/` is where it should be, so somewhere along the way this character seems to be intentionally or unintentionally removed from the URL making this if-statement fail

**Comment by jbryanh** [comment]
Thanks for opening another issue.  The more the merrier!  +1 on this.

**Comment by markusaksli-nc** [comment]
Hi @mvrsn 
Thanks for bringing this up, I'll make sure the issue gets the proper attention.
However, since this issue is just a duplicate I'm going to close it.
Thank you
