### ISSUE TITLE
FirebaseAdMobPlugin iPhone ok iPad NG

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#681]
FirebaseAdMobPlugin will display banner without problem on iPhone, but on iPad it will display "FirebaseAdMobPlugin <warning> adView: didFailToReceiveAdWithError: Request Error: No ad to show. (MobileAd <FLTBannerAd: 0x1c000e070> PENDING mobileAdId: 915310470 for: <GADBannerView : 0x13bd31cc0; frame = (0 0; 320 50); clipsToBounds = YES; layer = <CALayer: 0x1c4228ea0 >>) "becomes warning and the banner is not displayed.

**Comment by kroikie** [comment]
@Ken1101

The issue at https://github.com/flutter/flutter/issues/21204 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing based on that the original issue is open and seems obsolete
