### ISSUE TITLE
🐛 [Firebase_database] there is no method to send access_token with request to securely access firebase realtime database

### ISSUE THREAD

**Issue by uc-dve** [FirebaseExtended/flutterfire#6812]
## Bug report

**Describe the bug**
Is there any way to send an authentication token while read, set or update firebase real-time database, so we can set security rules on the database.
I didn't find anything like that, anywhere in the doc.

**Comment by markusaksli-nc** [comment]
Hi @uc-dve 
The authentication token should be automatically added if the user is signed in with https://pub.dev/packages/firebase_auth
Thank you
