### ISSUE TITLE
🐛 [Firebase_database] Getting data in wrong order from firebase realtime database

### ISSUE THREAD

**Issue by ayyysh04** [FirebaseExtended/flutterfire#6822]
**data output in console:**
![image](https://user-images.githubusercontent.com/74104690/129447289-43a7e21d-9e47-4442-993a-95c551899243.png)

**Code:**
FirebaseDatabase base = FirebaseDatabase( );
database = base.reference();
DataSnapshot? snap = await database!.get();
print(snap!.value);

**Database data :**
![image](https://user-images.githubusercontent.com/74104690/129447363-d00c072e-70bb-4edf-bdc1-0c14bce3c143.png)

**Comment by markusaksli-nc** [comment]
Hi @ayyysh04 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by SpajicM** [comment]
Realtime Database is data unordered, in native SDK as well.

Related: https://github.com/flutter/flutter/issues/19389

**Comment by markusaksli-nc** [comment]
Actually the missing information isn't important here as you mentioned the native sdk returns an unordered collection so this is intended behavior.
