### ISSUE TITLE
Please state in the google_sign_in package that it requires devices to pass SafetyNet

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#683]
I rooted my Pixel XL today and discovered that my Flutter app, which depends on google sign in to function, would not log in. Please state in the package description that passing SafetyNet is a requirement for the package to work as intended.

**Comment by kroikie** [comment]
@GroovinChip

The issue at https://github.com/flutter/flutter/issues/21179 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closed and re-opened the original issue as not related to firebase
