### ISSUE TITLE
🐛 [firebase_messaging] FirebaseMessagingException MessagingErrorCode: Unregistered.

### ISSUE THREAD

**Issue by ahguerraViridian** [FirebaseExtended/flutterfire#6837]
Hi,

We have an application where we need to send push notifications to clients. The application has been working properly for a couple of years now. Recently we have detected that we are receiving the following error: FirebaseMessagingException, MessagingErrorCode: Unregistered, Message: Requested entity was not found.

We have read the docs available here: https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode for the error: UNREGISTERED and none of the causes is met. For what we understand about the error code is that the firebase token is no longer valid or has expired which means that our app should renew the token when starting again. We have asked our clients to try the following:

- Close the app and open it again
- Delete the cache app
- Reinstall the app

None of the above attempts trigger the token refresh. The app keeps using the invalid token which generates the error UNREGISTERED when our backend send the push notification.

Our app is built using flutter with the plugin firebase_messaging v10.0.0
Our backend uses Firebase Admin .NET SDK v1.12.0

Here's flutter code from our app that requests the token:

```
String token = await FirebaseMessaging.instance.getToken();
store.dispatch(XStConfig(firebaseToken: token));
```

Here's flutter code from our app that refreshes the token:

```
FirebaseMessaging.instance.onTokenRefresh.listen((newToken) {
        store.dispatch(XStConfig(firebaseToken: newToken));
});
```

Is there anything we are missing? The application's main functions depend on push notifications.
Thanks in advance

**Comment by markusaksli-nc** [comment]
Hi @ahguerraViridian 
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
