### ISSUE TITLE
firebase_storage: StorageReference.getPath() returns different result on iOS and Android

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#684]
Using: `firebase_storage: "0.3.7"`, this code:

```dart
Future<void> uploadActivityPhoto(
  Activity activity,
  User user,
  File image,
) async {
  final String ext = extension(image.path);

  final DateTime now = new DateTime.now();

  final StorageReference ref = FirebaseStorage.instance.ref().child(
      "/users/${user.id}/activities/${activity.id}/${now.millisecondsSinceEpoch}$ext");

  final StorageUploadTask uploadTask = ref.putFile(image);

  final Uri imageURI = (await uploadTask.future).downloadUrl;
  final String storageRef = await ref.getPath();
 
  final Map<String, dynamic> imageData = <String, dynamic>{
    'url': imageUrl,
    'storage_ref': storageRef,
  };

  final CollectionReference collectionRef =
      Firestore.instance.collection('test_upload');

  collectionRef.document().setData(imageData);
}
```
When uploading files on iOS, "storage_ref" is set to, e.g.

`users/uZpqWlrXHabOrnqez4G8pAN2wRj1/activities/eAuMbEecePA3W5Dw8TYG/1535533628952.jpg`

while on Android it will prefix storage_ref with '/', so it becomes like this:

`/users/uZpqWlrXHabOrnqez4G8pAN2wRj1/activities/eAuMbEecePA3W5Dw8TYG/1535533628952.jpg`

**Comment by kroikie** [comment]
@bjornbjorn

The issue at https://github.com/flutter/flutter/issues/21158 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Just to confirm, ref paths should not start with a `/` so Android in this case is incorrect.

**Comment by Salakar** [comment]
Given the age of this issue and that Storage has had a major rework since; I'm going to close this issue in favour of trying the latest release.
