### ISSUE TITLE
Firestore to be able to update individual field in an array using arrayUnion

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#685]
Firestore to be able to update individual field in an array using arrayUnion

So far, no easy way to just update a single field in a array inside Firestore.

**Comment by cad0p** [comment]
so it's still not possible?

**Comment by kroikie** [comment]
@cad0p This should be fixed as indicated in the original issue:
https://github.com/flutter/flutter/issues/21148#issuecomment-449645405
