### ISSUE TITLE
🐛 [firebase_dynamic_links] dynamic links works fine on simulator but not on real iOS device. 

### ISSUE THREAD

**Issue by ayaanpathan** [FirebaseExtended/flutterfire#6856]
## Bug report

Hi. I have an app where the user can look for restaurants and their details. Now, I have integrated shareable links and deep linking to open a specific restaurant's details in the app from that dynamic link. This works perfectly fine on Android devices and iOS simulator, but not on real iOS device. I followed all the steps to configure the dynamic links properly. Can anyone help me with what I am missing?

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19043.1165], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Android Studio (not installed)
[√] Connected device (1 available)

```

</details>

---

Below is my code for reference:
<details><summary>Click To Expand</summary>

```
void initDynamicLinks() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;

      if (deepLink != null) {
        
        print("THIS IS THE DATA" + deepLink.toString());
      } else {
       
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });

    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink != null) {
      print(deepLink);
      print(deepLink.toString().substring(53));
      Future.delayed(const Duration(milliseconds: 4000), () {
        getRestaurantDetails(deepLink.toString().substring(53));
        setState(() {});
      });
    } else {
      getLoginStatus();
    }
  }
```

**Comment by markusaksli-nc** [comment]
Hi @ayaanpathan 
Can you please provide your `flutter pub deps -- --style=compact`? What exact device and iOS version does this occur on and how are you opening the link on the device?
Thank you
