### ISSUE TITLE
🐛 [firebase_analytics] log event name expired

### ISSUE THREAD

**Issue by OHeroJ** [FirebaseExtended/flutterfire#6859]
1. ecommerce_purchase  -> purchase
2. purchase_refund  -> refund

**Comment by markusaksli-nc** [comment]
This was supposed to be tracked in https://github.com/FirebaseExtended/flutterfire/issues/3876 but it has grown too vague, leaving this open as a more specific issue.

Sources:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#ECOMMERCE_PURCHASE
https://github.com/FirebaseExtended/flutterfire/blob/6304e493e1d3352400043a014e10acf261ca57f4/packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart#L345
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#PURCHASE_REFUND
https://github.com/FirebaseExtended/flutterfire/blob/6304e493e1d3352400043a014e10acf261ca57f4/packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart#L546

There are more of these https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#constant-summary

**Comment by russellwheatley** [comment]
Hi @OHeroJ, all events have been updated in the latest `firebase_analytics` rework. See [documentation](Could not publish configuration 'archives') for all available pre defined events. Thanks.
