### ISSUE TITLE
🐛 [CLOUD_FIRESTORE / FIREBASE_CORE] I CAN'T USE WHERE('email, isNotEqual: 'test@gmail.com) on flutter_web

### ISSUE THREAD

**Issue by rameklesia** [FirebaseExtended/flutterfire#6873]
![Screenshot_11](https://user-images.githubusercontent.com/70551597/130581916-2e6aea56-165c-43e9-aa16-2865fb560a6f.png)

I can't use isNotEqual in flutter_web
Its normal in android but not in flutterweb

**Comment by markusaksli-nc** [comment]
Hi @rameklesia 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What version of the CDN are you using?
Thank you

**Comment by rameklesia** [comment]
> 
> 
> Hi @rameklesia
> Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
> What version of the CDN are you using?
> Thank you

**Comment by rameklesia** [comment]
> 
> 
> Hi @rameklesia
> Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
> What version of the CDN are you using?
> Thank you
![image](https://user-images.githubusercontent.com/70551597/130778583-26b4d636-162b-470e-acfd-df861c69aede.png)
![image](https://user-images.githubusercontent.com/70551597/130778620-2430c23c-7c98-49f7-9d53-78a2a1fa8c94.png)

![image](https://user-images.githubusercontent.com

i dont have what is cdn because im new
![image](https://user-images.githubusercontent.com/70551597/130778743-fc59a7bb-65e1-455c-9927-32865f94ded3.png)
/70551597/130778637-04475d04-d0d8-4663-bd17-8ee8a111536a.png)

**Comment by markusaksli-nc** [comment]
Please use the recommended CDN versions in the documentation `8.6.1`
https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk

You should refrain from sending screenshots when you can just copy-paste the information but the pub deps you sent doesn't even have firebase plugins. I would just recommend you use the latest versions of the plugins.

**Comment by rameklesia** [comment]
> 
> 
> Please use the recommended CDN versions in the documentation `8.6.1`
> https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk
> 
> You should refrain from sending screenshots when you can just copy-paste the information but the pub deps you sent doesn't even have firebase plugins. I would just recommend you use the latest versions of the plugins.

Thanks !!
