### ISSUE TITLE
firebase_messaging: onMessage/onLaunch/onResume only give access to the data message payload. There is no way to get the notification object, the priority, sender, sentTime...

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#689]
On Android (and probably iOS as well), `FirebaseMessagingService` receives a [`RemoteMessage`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage) object when a notification or data message is received.

This object contains many useful properties, like the displayed notification text, key, message type, date...

Yet there is no way to receive this information in dart code. Only the data payload is sent to `onMessage`/`onLaunch`/`onResume`.

**Comment by kroikie** [comment]
@sir-boformer

The issue at https://github.com/flutter/flutter/issues/21043 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓
