### ISSUE TITLE
🐛 [firebase_analytics] PageView pages are not tracked out of the box as a screen_view event in Analytics

### ISSUE THREAD

**Issue by giorgio79** [FirebaseExtended/flutterfire#6907]
Hello,

I use PageView extensively in my app. I noticed the pages that the user views are not tracked in Firebase Analytics. Any tips on how to get individual pages in a PageView tracked as a screen_view event? It seems only Navigator namedRoutes are tracked out of the box, but PageView is another frequently used method to navigate in an app.

PageView link https://api.flutter.dev/flutter/widgets/PageView-class.html
Firebase Analytics https://pub.dev/packages/firebase_analytics

**Comment by markusaksli-nc** [comment]
Hi @giorgio79 
Please see the example app for a demonstration on how to use this functionality
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics/example/lib
Thank you
