### ISSUE TITLE
🐛 [firebase_analytics] No analytic data except after FirebaseAnalytic.resetAnalyticsData() is called.

### ISSUE THREAD

**Issue by zanecidan** [FirebaseExtended/flutterfire#6908]
I have a Flutter app integrated with Firebase. My Firebase analytic used to work normally even without having to include firebase_analytic plugin. But since my previous update, analytic data no longer being captured in the Firebase console.

I don't remember my previous versions of Firebase plugins but here are my current plugin versions:
firebase_core : 1.4.0
firebase_auth: 1.4.1
firebase_storage: 8.1.3
firebase_messaging: 10.0.4
cloud_firestore: 1.0.7
firebase_analytics: ^8.2.0

My Gradle:
implementation platform('com.google.firebase:firebase-bom:28.3.1')
implementation 'com.google.firebase:firebase-analytics'

My Flutter version:
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.0.6 at C:\src\flutter\flutter_windows_2.0.6-stable\flutter
    • Framework revision 1d9032c7e1 (4 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

Also while trying to solve this problem, I found out that calling FirebaseAnalytic.resetAnalyticsData() will make Firebase starting to capture the analytic data, however the user will be considered as a new user every time that function is called.

**Comment by markusaksli-nc** [comment]
Hi @zanecidan 
Please remove the native gradle overrides unless you absolutely need them and use the latest versions of the plugins (a listed at https://firebase.flutter.dev/) and see if the issue persists.
Thank you

**Comment by zanecidan** [comment]
Hi @markusaksli-nc 
I've removed the gradle overrides and updated my firebase plugins to latest versions as follow:
firebase_core : 1.6.0
firebase_auth: 3.1.0
firebase_storage: 10.0.3
firebase_messaging: 10.0.6
cloud_firestore: 2.5.1
firebase_analytics: 8.3.1

Unfortunately the issue still persists.

**Comment by markusaksli-nc** [comment]
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) of what fails for you? Have you tried running the example code?

**Comment by zanecidan** [comment]
I tried copy paste the sample code in my project main.dart, it didn't work too.

Also I found that other than calling resetAnalyticsData, deleting and reinstalling app would track 'first_open' very quickly the first time I open my App, but subsequent App open will again not being shown even in Firebase real-time analytic (stream view).

This is some logs I captured running debug logging:

> 09-03 13:04:07.853 V/FA      ( 6039): Recording user engagement, ms: 29538
> 09-03 13:04:07.858 V/FA      ( 6039): Connecting to remote service        
> 09-03 13:04:07.957 V/FA      ( 6039): Activity paused, time: 1034755535
> 09-03 13:04:08.071 D/FA      ( 6039): Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=29538, firebase_screen_class(_sc)=Launcher, firebase_screen_id(_si)=-8791346973117073258}]
> 09-03 13:04:08.123 V/FA      ( 6039): Connection attempt already in progress
> 09-03 13:04:08.123 D/FA      ( 6039): Connected to remote service
> 09-03 13:04:08.123 V/FA      ( 6039): Processing queued up service tasks: 2
> 09-03 13:04:08.146 V/FA-SVC  ( 2723): Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=29538, ga_screen_class(_sc)=Launcher, ga_screen_id(_si)=-8791346973117073258}]
> 09-03 13:04:08.457 V/FA-SVC  ( 2723): Upload scheduled in approximately ms: 353096
> 09-03 13:04:08.457 V/FA-SVC  ( 2723): Unscheduling upload
> 09-03 13:04:08.459 V/FA-SVC  ( 2723): Scheduling upload, millis: 353096
> 09-03 13:04:08.462 V/FA-SVC  ( 2723): Background event processing time, ms: 318
> 09-03 13:04:08.788 V/FA      (10701): onActivityCreated
> 09-03 13:04:08.884 V/FA      (10701): App measurement collection enabled
> 09-03 13:04:08.884 V/FA      (10701): App measurement enabled for app package, google app id: com.xxx.xxx, 1:565781699190:android:b236a89816eaca2a
> 09-03 13:04:08.885 I/FA      (10701): App measurement initialized, version: 42082
> 09-03 13:04:08.885 I/FA      (10701): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
> 09-03 13:04:08.885 I/FA      (10701): To enable faster debug mode event logging run:
> 09-03 13:04:08.885 I/FA      (10701):   adb shell setprop debug.firebase.analytics.app com.xxx.xxx
> 09-03 13:04:08.885 D/FA      (10701): Debug-level message logging enabled
> 09-03 13:04:08.952 V/FA      (10701): Connecting to remote service
> 09-03 13:04:08.968 V/FA      (10701): Connection attempt already in progress
> 09-03 13:04:08.972 V/FA      (10701): Connection attempt already in progress
> 09-03 13:04:09.411 V/FA      (10701): Activity resumed, time: 1034757095
> 09-03 13:04:09.421 I/FA      (10701): Tag Manager is not found and thus will not be used
> 09-03 13:04:09.447 V/FA      (10701): Connection attempt already in progress
> 09-03 13:04:09.447 V/FA      (10701): Connection attempt already in progress
> 09-03 13:04:09.761 D/FA      (10701): Connected to remote service
> 09-03 13:04:09.767 V/FA      (10701): Processing queued up service tasks: 5
> 09-03 13:04:09.811 V/FA-SVC  ( 2723): Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=6414919244431331223}]
> 09-03 13:04:09.818 V/FA-SVC  ( 2723): Upload scheduled in approximately ms: 351735
> 09-03 13:04:09.818 V/FA-SVC  ( 2723): Unscheduling upload
> 09-03 13:04:09.819 V/FA-SVC  ( 2723): Scheduling upload, millis: 351735
> 09-03 13:04:09.819 V/FA-SVC  ( 2723): Background event processing time, ms: 8
> 09-03 13:04:09.823 V/FA-SVC  ( 2723): Saving default event parameters, appId, data size: com.xxx.xxx, 2
> 09-03 13:04:13.150 V/FA      ( 6039): Inactivity, disconnecting from the service
> 09-03 13:04:14.939 V/FA      (10701): Inactivity, disconnecting from the service
> 09-03 13:04:15.220 V/FA      (10701): Connecting to remote service
> 09-03 13:04:15.223 D/FA      (10701): Connected to remote service
> 09-03 13:04:15.224 V/FA      (10701): Processing queued up service tasks: 1
> 09-03 13:04:15.235 V/FA-SVC  ( 2723): Logging event: origin=am,name=ad_query(_aq),params=Bundle[{ga_event_origin(_o)=am, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=6414919244431331223, ad_event_id(_aeid)=6414919244431331224}]
> 09-03 13:04:15.240 V/FA-SVC  ( 2723): Upload scheduled in approximately ms: 346313
> 09-03 13:04:15.240 V/FA-SVC  ( 2723): Unscheduling upload
> 09-03 13:04:15.242 V/FA-SVC  ( 2723): Scheduling upload, millis: 346313
> 09-03 13:04:15.242 V/FA-SVC  ( 2723): Background event processing time, ms: 7
> 09-03 13:04:20.235 V/FA      (10701): Inactivity, disconnecting from the service
> 09-03 13:05:04.268 V/FA      (10701): Connecting to remote service
> 09-03 13:05:04.280 D/FA      (10701): Connected to remote service
> 09-03 13:05:04.281 V/FA      (10701): Processing queued up service tasks: 1
> 09-03 13:05:04.290 V/FA-SVC  ( 2723): Logging event: origin=app,name=view_giveaway,params=Bundle[{ga_event_origin(_o)=app, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=6414919244431331223}]
> 09-03 13:05:04.312 V/FA-SVC  ( 2723): Upload scheduled in approximately ms: 297241
> 09-03 13:05:04.312 V/FA-SVC  ( 2723): Unscheduling upload
> 09-03 13:05:04.314 V/FA-SVC  ( 2723): Scheduling upload, millis: 297241
> 09-03 13:05:04.314 V/FA-SVC  ( 2723): Background event processing time, ms: 25
> 09-03 13:05:09.289 V/FA      (10701): Inactivity, disconnecting from the service

**Comment by markusaksli-nc** [comment]
Labeling this based on the report

**Comment by russellwheatley** [comment]
Hey @zanecidan, the Firebase Analytics plugin has been reworked now. Could you please upgrade to the latest and create a new issue with a reproducible sample if you find a problem? Thank you.
