### ISSUE TITLE
[cloud_firestore] isEqualTo matches against null

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#691]
```dart
QuerySnapshot _query = await someCollection
        .where('field1', isEqualTo: value1)
        .getDocuments();
```

this will match a doc even when value1 in the query is null, but in the doc itself it's populated.  likewise when you string together multiple `isEqualTo` statements.  it just returns everything in the collection.

**Comment by kroikie** [comment]
@blaneyneil

The issue at https://github.com/flutter/flutter/issues/21016 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This is a "non-issue" as is working as intended.

To query against `null` values, use the `isNull` filter:

```
QuerySnapshot _query = await someCollection
        .where('field1', isNull: true)
```
