### ISSUE TITLE
FirebaseStorage getDownloadURL not working on iOS (works on Web)

### ISSUE THREAD

**Issue by EricPHassey** [FirebaseExtended/flutterfire#6914]
Using the following "pseudo" code:
    
```
String anteriorOD = await FirebaseStorage.instance.ref().child(data[1]).getDownloadURL();
```

Works fine on Flutter Web, zero issues. Won't do anything when trying to run this on iPhone 12 Pro Max simulator. The code just hangs right at this line.

Are any special permissions required on iOS that isn't on web? Didn't notice anything in the documentation.

**Comment by markusaksli-nc** [comment]
Hi @EricPHassey 
This sounds more like a bug report since I can't immediately think of anything in the documentation.
Could you open a new bug report issue and fill out the template?
Thank you
