### ISSUE TITLE
Firebase Dynamic Link continued obtaining the last deep link 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#692]
_From @debutdeveloper on August 23, 2018 5:51_

URL: https://pub.dartlang.org/packages/firebase_dynamic_links

**Problem 1**
If our widget was already started, if you open the dynamic link again, it will never go through the initState() method again, so we will never get the deep link.

But it has solution,  WidgetsBindingObserver, by using which we can call link on app resumed.

**Problem 2**
In iOS, the AppLifecycleState.resume is called before the plugin gets the Deep Link. So link is not available by first time, and when we open app again we have link.

But we found solution for this by using some delay (Timer).

**Problem 3**
Major critical problem (No solution found).
In iOS, once we open the app, and get the deep Link using FirebaseDynamicLinks.instance.retrieveDynamicLink(), when we call it again, we continue obtaining the last deep Link, that is, since the call will be executed every time the widget enters the state of AppLifecycleState.resumed, and it happens, when the application is opened, either from a dynamic link or manually by the user, in iOS I had no way of knowing from where it was opened, because after getting a deep link, the method would bring back the same value even if it came out and entered the app manually.
As I observe the variable holding the deep link retained the old value, there must be need to clear that each time link is clicked.

_Copied from original issue: dart-lang/pub-dartlang-dart#1543_

**Comment by saidbeebay** [comment]
Please can you tell why this issue is closed? Is there a solution? Workaround?
We are still facing this problem on Android and iOS. 
We are in version 0.5.0+1.
Thanks for your help

**Comment by Nisthar** [comment]
@kroikie I can't receive the deep link after user installs the app through play store.
There is no "continue" button in play store.

**Comment by leejh10003** [comment]
@kroikie What's the reason this issue has been closed? I have the exactly same issue.
