### ISSUE TITLE
🐛 [firebase_messaging] FCM data message not coming when app is closed in ios

### ISSUE THREAD

**Issue by arif2k17-hot** [FirebaseExtended/flutterfire#6921]
I have integrated FCM in my flutter project with flutter_local_notification. Everything works as expected in Android. However, ios also works almost except when app is closed from history. When app is cleared from history messages are not triggering. I am using only data message in push notification. Please have a look below:
```
{
   "to": "/topics/global",
   "priority": "high",
   "content_available": true,
   "data": {
      "title": "Demo Title",
      "message": "Demo Message",
      "payload": "basic"
   }
}
```
As you can see there is no `notification` object in the json. This configuration is working fine on Android (foreground & background) and for ios only foreground. However, if i add the notification object in this json `surprisingly it works even the app is closed.`

But as i need to handle the notification manually that option doesn't fit for my use case. So i researched further and disabled Method Swizzling
```
<key>FirebaseAppDelegateProxyEnabled</key> 
<false/>
```
But that didn't help either. Now i'm kinda lost and can't find a way to achieve expected result. My `AppDelegate.swift` is given below
```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
   override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
    }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
**NOTE: The ios app is published in TestFlight and testing on a real device**

**Comment by markusaksli-nc** [comment]
Hi @arif2k17-hot 
Data-only messages are considered background messages and are subject to this limitation

> On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.

This is a known limitation of iOS and documented at https://firebase.flutter.dev/docs/messaging/usage

Sadly there isn't anything we can do to "fix" this behavior since it is a native limitation of the platform. However from the data in your message payload it looks like you could just get by using regular notifications instead?
Thank you

**Comment by arif2k17-hot** [comment]
Hi @markusaksli-nc 
Thanks for the reference. The message payload i attached is simplified i have more complex payload. I don't understand that if it's a limitation then how regular notification triggers in background? also during research i saw some people did solve the issue but the solve not work for everyone.

**Comment by QuentinSc** [comment]
> Hi @arif2k17-hot
> Data-only messages are considered background messages and are subject to this limitation
> 
> > On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.
> 
> This is a known limitation of iOS and documented at https://firebase.flutter.dev/docs/messaging/usage
> 
> Sadly there isn't anything we can do to "fix" this behavior since it is a native limitation of the platform. However from the data in your message payload it looks like you could just get by using regular notifications instead?
> Thank you

Hello,
For ly technical culture, how other app (discord for example) can show notifications even if killed by the user?
