### ISSUE TITLE
🐛 [cloud_functions] plugin uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by jimmyff** [FirebaseExtended/flutterfire#6926]
Hi. I'm using `cloud_functions: ^3.0.2` and I'm getting the following error when I try and get packages:

```
jimmyff@ubuntubox:~/dev/os_app$ flutter packages get
Running "flutter pub get" in os_app...                             1,306ms
The plugin `cloud_functions` uses a deprecated version of the
Android embedding.
To avoid unexpected runtime failures, or future build failures,
try to see if this plugin supports the Android V2 embedding.
Otherwise, consider removing it since a future release of Flutter
will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating
the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.
```
Any idea how to resolve this?

Thanks

**Comment by markusaksli-nc** [comment]
Hi @jimmyff 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/6770.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
