### ISSUE TITLE
🐛 [firebase_crashlytics] enable opt_in reporting not working correctly

### ISSUE THREAD

**Issue by eddiesTime** [FirebaseExtended/flutterfire#6934]
## Bug report

**Describe the bug**
Following the [documentation](https://firebase.flutter.dev/docs/crashlytics/usage#enable-opt-in-reporting) of firebase_crashlytics you can disable/enable the upload of crash reports to firebase with two options. 

1. Option: Disable the report natively via `AndroidManifest.xml` for Android or `Info.plist` for iOS.
2. Option: Run `FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);` inside you code and set it to `true` (default) when you want to enable crash report collection or to `false` when you want to disable it.

When using the first option, the configuration inside the `AndroidManifest.xml` seems to be ignored, because even when adding 
```xml
<meta-data
  android:name="firebase_crashlytics_collection_enabled"
  android:value="false" />
```
the report is still being uploaded.

For iOS, when adding 
```xml
<key>FirebaseCrashlyticsCollectionEnabled</key>
	<false/>
```
to the `Info.plist` no report is being uploaded as it's supposed to.

### Steps to reproduce

1. Create a new project `flutter create my_app`
2. Follow the firebase [documentation](https://firebase.flutter.dev/docs/crashlytics/overview/) for adding firebase_crashlytics
3. Exchange the `main()` inside your `main.dart` with the version below
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase.
  await Firebase.initializeApp();

  // Comment in/out when testing
  // FirebaseCrashlytics.instance.crash();
  runApp(MyApp());
}
```
4. Check whether you've configured firebase correctly by sending a report for Android and ios and verify it is being uploaded in the crashlytics dashboard
5. Follow the [documentation](https://firebase.flutter.dev/docs/crashlytics/usage#enable-opt-in-reporting) for opting-out reporting with option one (natively).
6. Delete the app from the emulator/simulator if it is installed to mimic the first install
7. Run the app and let it crash
8. Comment out `FirebaseCrashlytics.instance.crash();` and run the app again
9. Check the crashlytics dashboard.

### Expected behavior

When using option one to disable collection reporting via the `AndroidManifest.xml` no reports should be sent to firebase and displayed in the dashboard. For iOS, option one works as intended and no report is being uploaded.

### Sample project

https://github.com/eddiesTime/crashlytics_example

---

## Additional context

The same behavior has been discovered by another user recently and reported in #6874. I think he was on to something but assume he went with option two. 

I've been testing with the iOS Simulator and a Samsung Galaxy S7.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
crashlytics_example 1.0.0+1

dependencies:
- cupertino_icons 1.0.3
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.2.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.1 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Reproducible with 
```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.6.0-1.0.pre.160, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.6.0-1.0.pre.160 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f77c453ab6 (4 hours ago), 2021-09-02 00:58:19 -0400
    • Engine revision d877a4bbcd
    • Dart version 2.15.0 (build 2.15.0-68.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7621141\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7621141
    • Flutter plugin version 60.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5080.55
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!

```
</details>

**Comment by russellwheatley** [comment]
Hi @eddiesTime, this isn't something we have much control over I'm afraid. This setting is part of the official Firebase SDK, for further reading, please see [here](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android). 

Take note of this API:
```android
FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true);
``` 

Quote documentation:

> Enable collection for select users by calling the Crashlytics data collection override at runtime. The override value persists across launches of your app so Crashlytics can automatically collect reports. To opt out of automatic crash reporting, pass false as the override value. When set to false, the new value does not apply until the next run of the app.

You might need to set that API to `false` to remove persistence. If it still does not work, I'd suggest raising an issue on the official [android sdk repository](https://github.com/firebase/firebase-android-sdk).
