### ISSUE TITLE
[cloud_firestore] example for persistence

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#694]
_From @JacquesSchalkwyk on August 22, 2018 7:16_

URL: https://pub.dartlang.org/packages/cloud_firestore#-example-tab-

It would be greatly appreciated if an example is provided to set persistence with firestore.

_Copied from original issue: dart-lang/pub-dartlang-dart#1538_

**Comment by kroikie** [comment]
@isoos

The issue at https://github.com/flutter/flutter/issues/20901 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) (documentation now includes persistence examples) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
