### ISSUE TITLE
Regression with onSnapshot's "docsChange"

### ISSUE THREAD

**Issue by rrousselGit** [FirebaseExtended/flutterfire#6948]
From https://github.com/FirebaseExtended/flutterfire/pull/6819:

> I do want to raise an issue this commit created.
> 
> You've changed the behavior for listeners of this now cached connection.
> 
> The first listener will receive a full list of docChanges (with every record being represented as added) initially.
>
>The N+1 listener will only see recently updated records in docChanges initially and instead will need to rely on just docs to get a full list of the documents in the snapshot.
>
> Certainly a breaking change.  And goes against the documented behavior (that the initial stream event will contain all documents in the docChanges as added).

_Originally posted by @tcf909 in https://github.com/FirebaseExtended/flutterfire/issues/6819#issuecomment-912889170_

**Comment by rrousselGit** [comment]
That's a good point.
I'm not too familiar with docChanges. Are we expecting the initial call to simply contains all the "docs" with nothing else?

In particular I'm wondering if we can get this behaviour back without reverting this change.

Thought @Salakar / @russellwheatley ?

**Comment by tcf909** [comment]
> That's a good point.
> I'm not too familiar with docChanges. Are we expecting the initial call to simply contains all the "docs" with nothing else?

The currently documented behavior says the initial call will have the initial list of documents represented in docChanges as "added". This basically mirrors docs at this point. The SDK will also possibly provide the initial list from cache and follow up with a second call once a response is received from the server.

You still see this functionality in the first snapshots() handler, but again the second time you use snapshots() you don't see any of the initial documents listed in docChanges. It operates as a late joiner, but from the app code perspective it thinks it's a first joiner.

**Comment by russellwheatley** [comment]
I'm not sure we can revert to existing behaviour and also keep cached connections. To my mind, we'd have to keep a separate cache or make a DB call to mimic previous behaviour. I think @larssn raises an important point as well:

> Listening to query results
Firestore allows you to listen to the results of a query and get realtime updates when the query results change.

> When you listen to the results of a query, you are charged for a read each time a document in the result set is added or updated. You are also charged for a read when a document is removed from the result set because the document has changed. (In contrast, when a document is deleted, you are not charged for a read.)
> 
> Also, if the listener is disconnected for more than 30 minutes (for example, if the user goes offline), you will be charged for reads as if you had issued a brand-new query.

This would suggest that rebuilding the connection wouldn't result in an additional charge as we may have presumed.

**Comment by larssn** [comment]
I would probably roll it back, until it has been clarified if the PR is really needed (Firebase support should know). It's a breaking change that doesn't need to happen. If the change _is_ needed, then it needs to mirror the underlying API to the letter, which includes `docChanges`.

Also, I have to voice my concern regarding how that PR was handled. It was clearly merged without much scrutiny. Fortunately @tcf909 caught it, but it probably not a good idea to rely on your users to catch API disparities AFTER they've been merged. 🙂

Is there a product owner for each individual module, or how do you run things?

**Comment by Salakar** [comment]
+1 on a rollback for the time being until behaviour can be clarified and fixed - cc @russellwheatley / @rrousselGit 

> Also, I have to voice my concern regarding how that PR was handled. It was clearly merged without much scrutiny. Fortunately @tcf909 caught it, but it probably not a good idea to rely on your users to catch API disparities AFTER they've been merged.

This PR went through multiple reviews and discussions internally, things ultimately do get missed sometimes - it happens.

**Comment by rrousselGit** [comment]
I agree with the others. I'm OK with a revert

**Comment by Salakar** [comment]
PR is up to revert, will land it in todays release
