### ISSUE TITLE
🐛 [firebase_dynamic_links] Pressing to link triggers app restart even if it was in background at iOS

### ISSUE THREAD

**Issue by DmitriyYakovlev** [FirebaseExtended/flutterfire#6955]
## Bug report

At Android it works OK. When I have working app in background and press link, my app just receives callback and keep previous state.
But at iOS it looks like restart of application, becuse I can see Splash, then Home Screen and previous app state is lost.

  firebase_dynamic_links: ^2.0.9

### Expected behavior

Expected the same behavior as on Android

**Comment by markusaksli-nc** [comment]
Hi @DmitriyYakovlev 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What iOS version is this happening on?
Thank you
