### ISSUE TITLE
 🐛 [firebase_messaging] How to clear badge?

### ISSUE THREAD

**Issue by duzenko** [FirebaseExtended/flutterfire#6985]
Is there a way to clear badge from the app icon?

https://user-images.githubusercontent.com/3720039/96516649-8e021580-1235-11eb-9b89-ce6c03bb6ff9.png

https://github.com/FirebaseExtended/flutterfire/issues/3916
The suggested native workaround is not good. (explained [here](https://github.com/FirebaseExtended/flutterfire/issues/553#issuecomment-616246775))

**Comment by gulmensedat** [comment]
> here

- You can reset it from within the app with https://pub.dev/packages/flutter_app_badger. 
- Another way is to reset the badge with fcm.
```
                'notification': <String, dynamic>{
                  'body': body,
                  'title': title,
                  'badge': 0, //reset with 0
                  "sound": "default",
                },
                'priority': 'high',
```

**Comment by duzenko** [comment]
@gulmensedat I'm sorry I need a separate plugin to clear badge generated by this plugin? Is this the official answer?

**Comment by duzenko** [comment]
I have a task to clear notifications one by one as user navigates in the app
Is there an API for that?

**Comment by gulmensedat** [comment]
> @gulmensedat I'm sorry I need a separate plugin to clear badge generated by this plugin? Is this the official answer?

I suggested an alternative solution. I am using this way.

**Comment by pr-Mais** [comment]
I assume you are having this only on iOS, to solve it without using a package try adding the following code to **AppDelegate.swift** in `application` function

```swift
// Reset badge count
UIApplication.shared.applicationIconBadgeNumber = 0
```

it will reset the badge once the user opens the app.

**Comment by duzenko** [comment]
No, this is android and there should be flutter API to do this

**Comment by pr-Mais** [comment]
The image you posted shows an iOS badge.
By running the example app on Android I see that the badge (a dot) disappears once the notifications in the notifications centre are cleared, and I believe this is the native behavior on Android, check [here](https://developer.android.com/training/notify-user/badges).

**Comment by duzenko** [comment]
The iOS image is from the other github issue that was closed without any actual fix
I need to be able to cancel notifications one by one from Flutter

**Comment by markusaksli-nc** [comment]
Hi @duzenko 
Please see https://github.com/FirebaseExtended/flutterfire/issues/4145#issuecomment-739571979
Thank you
