### ISSUE TITLE
[📚] Messaging example is not null-safe

### ISSUE THREAD

**Issue by hazem-saeed** [FirebaseExtended/flutterfire#6987]
After I installed the package (and other packages needed in the example), I copied the example to try it out, but it didn't work.

Can you please edit the code in the example in the link below, to make it a working example?

Thanks in advance...

**Comment by pr-Mais** [comment]
Could you please provide the link for that example? and how exactly isn't it working?

**Comment by hazem-saeed** [comment]
> 
> 
> Could you please provide the link for that example? and how exactly isn't it working?

Sorry for the confusion. I thought I provided the link. Here's the link:
https://pub.dev/packages/firebase_messaging/example

When I copied the code in the provided example, and installed the necessary packages (aside from message.dart, message_list.dart, permissions.dart, token_monitor.dart). Many lines of code needed to be modified to make it work for the new null safety syntax.

**Comment by markusaksli-nc** [comment]
FYI the example works if you add
```dart
// @dart=2.9
```
to the top as in the example code but might as well migrate it to null-safety.

**Comment by hazem-saeed** [comment]
> 
> 
> FYI the example works if you add
> 
> ```dart
> // @dart=2.9
> ```
> 
> to the top as in the example code but might as well migrate it to null-safety.

Thank you for your reply. I did change the code to null-safety. And I didn't know about this: // @dart=2.9. Thanks for the tip.
