### ISSUE TITLE
I have this issue when  debug my project in my phone or emulator 

### ISSUE THREAD

**Issue by AhmedNoamn** [FirebaseExtended/flutterfire#6992]
that is the debug console:
V/AudioManager(25625): playSoundEffect   effectType: 0
W/Firestore(25625): (23.0.3) [Firestore]: Listen for Query(target=Query(chats/amLTIgw9h5XvpJxO9Pcu/messages order by __name__);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
E/flutter (25625): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
E/flutter (25625):

**Comment by markusaksli-nc** [comment]
Hi @AhmedNoamn 
This sounds like a bug report rather than a documentation issue.
Could you file a bug report and fill out the template with all of the required information?
Thank you
