### ISSUE TITLE
I can't get any data from cloud firestore 

### ISSUE THREAD

**Issue by AhmedNoamn** [FirebaseExtended/flutterfire#6996]
that is what i saw the debug console:
V/AudioManager(25625): playSoundEffect   effectType: 0
W/Firestore(25625): (23.0.3) [Firestore]: Listen for Query(target=Query(chats/amLTIgw9h5XvpJxO9Pcu/messages order by __name__);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
E/flutter (25625): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
E/flutter (25625):

**Comment by russellwheatley** [comment]
`PERMISSION_DENIED` means you need to set Firestore rules properly on you Firebase console. See official [docs](https://firebase.google.com/support/guides/security-checklist#security_rules)

**Comment by AhmedNoamn** [comment]
I can't access to rules and i don't know the reason
