### ISSUE TITLE
Realtime Database Clear Cache

### ISSUE THREAD

**Issue by gboscaro-imtech** [FirebaseExtended/flutterfire#6999]
How can I clear the cache on firebase_database 7.2.2?

I tried to set persistence to false and set cache size to 0, but it didn't work. I needed to delete my app and reistall.

**Comment by markusaksli-nc** [comment]
There is no API in the Firebase Database SDK to clear the current cache. You also cannot set the cache size to 0

> Cache sizes smaller than 1 MB or greater than 100 MB are not supported.

Thank you
