### ISSUE TITLE
🐛 [firebase_database] get() ignores query manipulations 

### ISSUE THREAD

**Issue by dvird** [FirebaseExtended/flutterfire#7007]
## Bug report

When using function "get()" instead of "once()" on a [Query] all the manipulations like limitToLast,orderByChild, and more.. are ignored.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^8.3.2
  cloud_firestore: ^2.5.2
  firebase_database: ^7.2.2
  firebase_dynamic_links: ^2.0.9
  firebase_messaging: ^10.0.7
  firebase_storage: ^10.0.3
  google_mobile_ads: ^0.13.4
#  firebase_app_check: ^0.0.2+1
  firebase_remote_config: ^0.11.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @dvird 
The native Firebase Realtime Database SDK returns unordered data (see https://github.com/flutter/flutter/issues/19389)
Thank you

**Comment by dvird** [comment]
@markusaksli-nc so why once() return it ordered

**Comment by markusaksli-nc** [comment]
https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-filtering

The difference is that `get` will query the API while `once` will use the listener. Ordered queries only work with a child listener. You can see this for yourself by running your ordered query in the script in `index.html` and refer to
https://firebase.google.com/docs/database/web/lists-of-data#sort_data

> This defines a query that **when combined with a child listener** synchronizes the client with...

Again this is how the native SDK works so it isn't up to our plugin code to change this behavior.
