### ISSUE TITLE
🐛 [firebase_storage] partsFromHttpUrl returning null when URL has a port specified

### ISSUE THREAD

**Issue by adamkoch** [FirebaseExtended/flutterfire#7019]
## Bug report

**Describe the bug**
When calling [`refFromURL(url)`](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/FirebaseStorage/refFromURL.html) with a url that includes a port, [`partsFromHttpUrl`](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_storage/firebase_storage/lib/src/utils.dart#L36) returns null due to the [regexp](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_storage/firebase_storage/lib/src/utils.dart#L49) not matching.

This appears to have broken after this fix/change:
https://github.com/FirebaseExtended/flutterfire/issues/6773
https://github.com/FirebaseExtended/flutterfire/pull/6848

### Steps to reproduce

Call [`refFromUrl()`](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/FirebaseStorage/refFromURL.html) from a url that includes a port such as 443 for https, for example:
https://firebasestorage.googleapis.com:443/v0/b/myapp.appspot.com/o/test%2Ffile.png?alt=media&token=91309a3a

Firebase Storage throws error:
```
'package:firebase_storage/src/firebase_storage.dart': Failed assertion: line 121 pos 14: 'parts != null': url could not be parsed, ensure it's a valid storage url
```

### Expected behavior
Call should succeed and url should be parsed.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0
Flutter SDK 2.5.0
deletemeagain 1.0.0+1

dependencies:
- cupertino_icons 1.0.3
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- pedantic 1.11.1
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
@russellwheatley Another minor issue with the regex
Needs to match an optional `(:\d+)?` or something here?
https://github.com/FirebaseExtended/flutterfire/blob/cc13c55d3bdd70c53a864d0cbaa0240d81f1d7c0/packages/firebase_storage/firebase_storage/lib/src/utils.dart#L24
