### ISSUE TITLE
Firebase auth causing dexmerger issue

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#703]
Kept on receiving Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

Whenever I try including the   firebase_auth: ^0.5.18 I get the DexMerger issue and I'm unsure why. There are no compile errors and simply commenting that single line out lets me download the app.

These sorts of issues have always been my kryptonite so I greatly appreciate any help and tips on how to debug these sorts of issues better in the future.

**Comment by kroikie** [comment]
@ashkan117

The issue at https://github.com/flutter/flutter/issues/20669 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
I think it's fine to close the issue basing on https://github.com/flutter/flutter/issues/20669#issuecomment-480457799
