### ISSUE TITLE
Cannot receive firebase analytics from IOS

### ISSUE THREAD

**Issue by saveKenny** [FirebaseExtended/flutterfire#7038]
I have configured my application based on the firebase_analytics package [documentation](https://pub.dev/packages/firebase_analytics). My Podfile starts with `$FirebaseAnalyticsWithoutAdIdSupport = true`. But I can only receive Android analytics.

![Screenshot from 2021-09-21 11-42-50](https://user-images.githubusercontent.com/62389332/134320132-a31866e2-3db5-4e22-ab14-e7c6b7cd20cd.png)

My code:
```
final FirebaseAnalytics analytics = FirebaseAnalytics();

void onGroupCreate(String groupId, double totalInvites, bool isStatus) {
      analytics.logEvent(
        name: "create_group",
        parameters: <String, dynamic>{
          'user_id': globals.user.userId,
          'group_id': groupId,
          'total_invites': totalInvites,
          'is_status': isStatus
        },
      );
    }
```
What am I doing wrong? The documentation does not mentioned additional information.

**Comment by markusaksli-nc** [comment]
@saveKenny That podfile edit is optional and you should do it only if you want to use Firebase Analytics without IDFA collection capability. I just ran the example and it works fine on iOS.

Are there any relevant errors or warnings logged?

**Comment by saveKenny** [comment]
Hey @markusaksli-nc thanks for replying. Everything seems to be just fine. No warnings and no errors. And yes I want Firebase Analytics without IDFA collection

**Comment by Rohithgilla12** [comment]
@saveKenny are you using a real device to log the events?
Just to verify

**Comment by saveKenny** [comment]
Yes I have tested the app via TestFlight on a real device. 

Also I just run the app on a simulator with `-FIRAnalyticsDebugEnabled` (https://stackoverflow.com/a/43110441/12695188) and I cannot see any analytics in my Firebase debugView. Do you think it is related?

**Comment by markusaksli-nc** [comment]
I tried with `$FirebaseAnalyticsWithoutAdIdSupport = true` and it still worked so it shouldn't matter. Just to be safe could you run these in your `ios` directory?
```bash
rm -rf build
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
pod install
```

Also make sure you are using the same app identifier as in Firebase Console

**Comment by saveKenny** [comment]
> I tried with `$FirebaseAnalyticsWithoutAdIdSupport = true` and it still worked so it shouldn't matter. Just to be safe could you run these in your `ios` directory?
> 
> ```shell
> rm -rf build
> rm -rf Pods
> rm -rf Podfile.lock
> rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
> pod cache clean --all
> flutter clean
> flutter pub get
> pod repo update
> pod install
> ```
> 
> Also make sure you are using the same app identifier as in Firebase Console

Unfortunately it didn't help. Would you like me to send you more information?

**Comment by markusaksli-nc** [comment]
I don't have many other great suggestions other than to check that you have the correct plist in the xcode project or to try running the example project with your config. You could also try filtering through `flutter run -v` or the device logs with the Console app to see if there is anything useful. 

It's hard to diagnose a silent failure without any logs or combing through the entire project setup. I'll label this to see if anyone else has ideas.

**Comment by saveKenny** [comment]
Hey @markusaksli-nc publishing some relevant files from the project. Hope it will get us some insights:

My `info.plist`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>AppName</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>AppName</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.####-#######</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSContactsUsageDescription</key>
	<string>This app requires contacts access to function properly.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires photos access to function properly.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

My `GoogleService-Info.plist`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CLIENT_ID</key>
	<string>####-######.apps.googleusercontent.com</string>
	<key>REVERSED_CLIENT_ID</key>
	<string>com.googleusercontent.apps.####-######</string>
	<key>ANDROID_CLIENT_ID</key>
	<string>####-######.apps.googleusercontent.com</string>
	<key>API_KEY</key>
	<string>####-######</string>
	<key>GCM_SENDER_ID</key>
	<string>####</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>######</string>
	<key>PROJECT_ID</key>
	<string>app-project-####</string>
	<key>STORAGE_BUCKET</key>
	<string>app-project-####.appspot.com</string>
	<key>IS_ADS_ENABLED</key>
	<false></false>
	<key>IS_ANALYTICS_ENABLED</key>
	<false></false>
	<key>IS_APPINVITE_ENABLED</key>
	<true></true>
	<key>IS_GCM_ENABLED</key>
	<true></true>
	<key>IS_SIGNIN_ENABLED</key>
	<true></true>
	<key>GOOGLE_APP_ID</key>
	<string>#:####:ios:######</string>
	<key>DATABASE_URL</key>
	<string>https://app-project-####.firebaseio.com</string>
</dict>
</plist>
```

**Comment by saveKenny** [comment]
Hey any news about this issue? (I have added my `info.plist` and `GoogleService-Info.plist` files).

**Comment by markusaksli-nc** [comment]
Not from me, no. Have you tried contacting [support](https://firebase.google.com/support)?

**Comment by saveKenny** [comment]
> Not from me, no. Have you tried contacting [support](https://firebase.google.com/support)?

Good idea, I will check with them.

**Comment by russellwheatley** [comment]
Hey @saveKenny, did you manage to resolve your problem? My sense is that this is a setup issue, but would like confirmation. Thanks!

**Comment by saveKenny** [comment]
Hey @russellwheatley,
The problem was that I **didn't have an IOS data stream** in my project analytics property. https://stackoverflow.com/a/69852960/12695188

**Comment by russellwheatley** [comment]
Hey @saveKenny, thanks for the update!
