### ISSUE TITLE
firebase_auth error message getters differ across platforms

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#704]
when using a standard `.catchError((e) {` the human readable message is contained in `e.details` if it's iOS but is in `e.message` when on Android.

**Comment by kroikie** [comment]
@blaneyneil

The issue at https://github.com/flutter/flutter/issues/20658 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
