### ISSUE TITLE
firebase_dynamic_links 0.6.3

### ISSUE THREAD

**Issue by hovanhung98hust** [FirebaseExtended/flutterfire#7077]
FirebaseDynamicLinks.instance.getInitialLink() not working on IOS

**Comment by markusaksli-nc** [comment]
Hi @hovanhung98hust 
Please `flutter upgrade` to at least the latest stable version, and use the latest `firebase_dynamic_links: ^2.0.9`.
If the issue persists please file a new bug report and fill out the template with all of the required information.
Thank you
