### ISSUE TITLE
🐛 [firebase_dynamic_link] Not clear dynamic links after retrieved

### ISSUE THREAD

**Issue by robyhuzwandar** [FirebaseExtended/flutterfire#7086]
## Bug report

**Describe the bug**
Not clear dynamic links after retrieved

### Steps to reproduce

1. I call the initial dynamic link at splash screen and home screen
2. open my app from dynamic link and open a specific page
4. back to the home page
5.  at the home page, I call again the dynamic link initial and  dynamic link open my link again and go to my specific page before

### Expected behavior

My expectation is when I call the dynamic link on the home page, it should not call my previous link because I already used it.so it should be clear from the cache

### Sample project

`Future<void> init(BuildContext context) async {
    FirebaseDynamicLinks.instance.onLink(
      onSuccess: (PendingDynamicLinkData dynamicLink) async {
        final Uri deepLink = dynamicLink?.link;
        if (deepLink != null) {
          handleRoute(context, deepLink.query);
        }
      },
      onError: (OnLinkErrorException e) async {},
    );

 
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;
    if (deepLink != null) {
      handleRoute(context, deepLink.query);
    }
  }`

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3 20E232 darwin-x64, locale en-ID)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.2
Flutter SDK 2.5.1

dependencies:
- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- camera 0.8.1+7 [camera_platform_interface flutter pedantic quiver]
- carousel_slider 4.0.0 [flutter]
- clipboard 0.1.3 [flutter]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- device_info 2.0.2 [flutter device_info_platform_interface]
- device_preview 0.7.4 [flutter flutter_localizations provider path_provider device_frame font_awesome_flutter http freezed_annotation json_annotation shared_preferences pedantic path]
- dio 4.0.0 [http_parser path]
- email_validator 2.0.1
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.3 [collection meta]
- facebook_app_events 0.12.0 [flutter]
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.9 [firebase_core flutter]
- firebase_messaging 10.0.7 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.10.0+5 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.1.0 [flutter bloc provider]
- flutter_feather_icons 2.0.0+1 [flutter]
- flutter_html 2.1.2 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_image_compress 1.1.0 [flutter]
- flutter_jailbreak_detection 1.7.0 [flutter]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_local_notifications 6.1.1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_native_image 0.0.6+1 [flutter]
- flutter_offline 2.0.0 [flutter connectivity wifi_info_flutter]
- flutter_screenutil 5.0.0+2 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- fluttercontactpicker 4.5.1 [flutter contact_picker_platform_interface contact_picker_web]
- formz 0.4.0
- geocoding 2.0.1 [flutter geocoding_platform_interface]
- get_it 7.2.0 [async collection]
- home_indicator 2.0.0 [flutter]
- image_cropper 1.4.1 [flutter]
- image_gallery_saver 1.7.0 [flutter]
- image_picker 0.8.4+2 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- jwt_decoder 2.0.1
- local_auth 1.1.8 [flutter flutter_plugin_android_lifecycle intl meta platform]
- location 4.3.0 [flutter location_platform_interface location_web]
- lottie 1.2.0 [archive characters flutter path vector_math]
- package_info 2.0.2 [flutter]
- path 1.8.0
- path_provider 2.0.5 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 8.1.6 [flutter meta permission_handler_platform_interface]
- pin_input_text_field 4.1.0 [flutter]
- pinput 1.2.0 [flutter]
- qr_code_scanner 0.5.2 [js flutter flutter_web_plugins]
- qr_flutter 4.0.0 [flutter qr]
- root_access 1.0.4 [flutter]
- share 2.0.4 [meta mime flutter]
- shimmer 2.0.0 [flutter]
- sms_autofill 2.1.2 [pin_input_text_field flutter]
- swipeable_page_route 0.2.2 [black_hole_flutter collection flutter list_diff meta supercharged]
- timelines 0.1.0 [flutter]
- toggle_switch 1.2.0 [flutter]
- tuple 2.0.0 [quiver]
- url_launcher 6.0.11 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wc_flutter_share 0.4.0 [flutter path_provider]
- webview_flutter 2.0.14 [flutter].```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @robyhuzwandar 
This looks like a duplicate case of https://github.com/FirebaseExtended/flutterfire/issues/6784
Closing it as such, let me know if you disagree.
Thank you
