### ISSUE TITLE
🐛 [firebase_messaging 10.0.8] Delay in getting notification

### ISSUE THREAD

**Issue by kaushal231291** [FirebaseExtended/flutterfire#7126]
Hi Team,

Our team is trying to integrate firebase notification into our flutter application. However, we are facing issues in receiving the notification. 

When sending notifications through either Firebase console or using fcm api, sometimes we do not receive the message at the client's end. And sometimes we receive the notification very late taking 15-20 minutes. 

However, initially we were able to receive notification messages instantaneously.

Note that we are not configuring the notifications in any special way i.e. by setting priority etc. We are simply sending notification messages.

My question is that is there  a specific reason why there is a delay in receiving the notifications. Is there something we can do to avoid this delay from our end. Also is there is limit as to how long it might take for a notification to reach the intended client.

Please share your inputs on this.

Thanks.

**Comment by ronpetit** [comment]
Same thing happening to me in two different Firebase projects, I notice it since yesterday

**Comment by markusaksli-nc** [comment]
Hi @kaushal231291 
We do not control the behavior of that drives the notification so this issue sounds like it is more suited for https://firebase.google.com/support/
Thank you
