### ISSUE TITLE
🐛 [firebase_messaging] Notification sound is not playing in Android

### ISSUE THREAD

**Issue by Softkeydel** [FirebaseExtended/flutterfire#7128]
## Bug report

Notification sound is not playing in Android

![Image 2021-10-04 at 5 19 12 PM](https://user-images.githubusercontent.com/16410754/135847000-42c03b56-3893-4454-a8d9-df822a488e1c.jpeg)
By default Allow Vibration is on but Allow sound is off. How to on Allow sound during the app installation??

**Comment by markusaksli-nc** [comment]
Hi @Softkeydel 
You can use the `sound` argument in `FirebaseMessaging.instance.requestPermission`
Thank you

**Comment by Softkeydel** [comment]
I'm using the code 
`await FirebaseMessaging.instance.requestPermission(
    alert: true,
    announcement: false,
    badge: true,
    carPlay: true,
    criticalAlert: true,
    provisional: true,
    sound: true,
  );
`

my problem is in android device but the above code mostly supporting the ios device as in requestPermission() the code is

`
Future<NotificationSettings> requestPermission({
    /// Request permission to display alerts. Defaults to `true`.
    ///
    /// iOS/macOS only.
    bool alert = true,

    /// Request permission for Siri to automatically read out notification messages over AirPods.
    /// Defaults to `false`.
    ///
    /// iOS only.
    bool announcement = false,

    /// Request permission to update the application badge. Defaults to `true`.
    ///
    /// iOS/macOS only.
    bool badge = true,

    /// Request permission to display notifications in a CarPlay environment.
    /// Defaults to `false`.
    ///
    /// iOS only.
    bool carPlay = false,

    /// Request permission for critical alerts. Defaults to `false`.
    ///
    /// Note; your application must explicitly state reasoning for enabling
    /// critical alerts during the App Store review process or your may be
    /// rejected.
    ///
    /// iOS only.
    bool criticalAlert = false,

    /// Request permission to provisionally create non-interrupting notifications.
    /// Defaults to `false`.
    ///
    /// iOS only.
    bool provisional = false,

    /// Request permission to play sounds. Defaults to `true`.
    ///
    /// iOS/macOS only.
    bool sound = true,
  }) {
    return _delegate.requestPermission(
      alert: alert,
      announcement: announcement,
      badge: badge,
      carPlay: carPlay,
      criticalAlert: criticalAlert,
      provisional: provisional,
      sound: sound,
    );
  }

`

**Comment by markusaksli-nc** [comment]
Sorry misread the issue here. It's true that the request mainly works on iOS have you tried this on multiple devices? I couldn't reproduce this on my SM G950F, works as expected. Maybe it's specific to your device notification settings?
