### ISSUE TITLE
[firebase_database][firebase_animated_list.dart] cannot use with dismissible

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#713]
Hello,

I believe that you cannot use `Dismissible()` with a `FirebaseAnimatedList()` because the latter will not remove the list item fast enough to not throw an on-screen error that a "dismissed widget is still in the tree".

I believe this is because it is waiting for a new snapshot to show up.

I have FirebaseDatabase persistence on.

Any insight is much appreciated, this is blocking without writing my own FirebaseAnimatedList() that exposes the ability to remove an item by index.

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/20505 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age of this issue, its inactivity and that Database has had several release since; I'm going to close this issue in favour of trying the latest release.
