### ISSUE TITLE
🐛 [Firebase Core & Firebase Auth] Deprecated Api warning

### ISSUE THREAD

**Issue by HaardikBhagtani** [FirebaseExtended/flutterfire#7130]
Note: C:\Users\Haardik\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.4.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: C:\Users\Haardik\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.0.1\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by GCamanes** [comment]
same here with more recent versions

Note: /Users/gcamanes/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.6.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: /Users/gcamanes/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.1.1/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by GCamanes** [comment]
tried again with most recent versions

Note: /Users/gcamanes/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: /Users/gcamanes/.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.1.2/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by markusaksli-nc** [comment]
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3876
