### ISSUE TITLE
unregister notification for write_timeout failed

### ISSUE THREAD

**Issue by desmeit** [FirebaseExtended/flutterfire#7136]
I use

firebase_core: ^1.7.0
 firebase_auth: ^3.1.2

Every time if I sign in or sign out I get this message in IOS:

```
[connection] nw_endpoint_handler_set_adaptive_read_handler [C8.1 2a00:1450:4016:808::200a.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed

[connection] nw_endpoint_handler_set_adaptive_write_handler [C8.1 2a00:1450:4016:808::200a.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
```

Can anyone tell me what this message is? Is this a known bug?

[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale de-DE)
    • Flutter version 2.5.1 at /Users/XXX/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

**Comment by markusaksli-nc** [comment]
Hi @desmeit 
This seems like just a debug message for connection timeouts.
This should be native behavior and we do not control it so your best bet is to contact https://firebase.google.com/support
Thank you

**Comment by desmeit** [comment]
Thank you very much and sorry for the duplicate. This was a mistake.
