### ISSUE TITLE
🐛 [firebase_crashlytics] java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.

### ISSUE THREAD

**Issue by alamsyahh15** [FirebaseExtended/flutterfire#7143]
## Bug report

Hello i have bug when use Firebase Crashlytic v.2.2.0, previously i have installed it and it runs normally in the app but suddenly this bug appears, and I dunno to fix this i'm search reference at stackoverflow there are some who suggest to add some add some code in the build.gradle file, but it still no effect,

this is the error log i caught : 

`**java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.**`

This my reference : 
https://stackoverflow.com/questions/63325427/firebase-crashlytics-java-lang-illegalstateexception-the-crashlytics-build-id

**Comment by markusaksli-nc** [comment]
Hi @alamsyahh15 
Have you followed all of the steps in https://firebase.flutter.dev/docs/crashlytics/overview/
Thank you

**Comment by alamsyahh15** [comment]
Oke thanks @markusaksli-nc this work it for me
