### ISSUE TITLE
[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff. (Production)

### ISSUE THREAD

**Issue by mianazeemdaula** [FirebaseExtended/flutterfire#7146]
## Bug report

**Describe the bug**
The app working fine in debugging mode but throw error in production

### Sample project
firebase_core: ^1.7.0
firebase_auth: ^3.1.2
cloud_firestore: ^2.5.3
firebase_storage: ^10.0.4

flutter_easyloading: ^3.0.3
  flutter_form_builder: ^6.1.0+1
  flutter_rating_bar: ^4.0.0
  flutter_verification_code: ^1.1.0
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  image_picker: ^0.8.4
  permission_handler: ^8.1.6
  agora_rtc_engine: ^4.0.7
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^3.1.0
  country_code_picker: ^2.0.2
  easy_loading: ^0.0.4
  firebase_messaging: ^10.0.8
### Flutter doctor
<details><summary>Click To Expand</summary>
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.928], locale en-PK)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio
[√] Connected device (3 available)

• No issues found!
</details>

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
Dart SDK 2.13.4
Flutter SDK 2.2.3
clubhouse 1.0.0+1

dependencies:
- agora_rtc_engine 4.0.7 [flutter flutter_web_plugins json_annotation]
- animated_bottom_navigation_bar 0.3.2 [flutter]
- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 2.5.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- cupertino_icons 1.0.3
- easy_loading 0.0.4 [flutter rxdart]
- firebase_auth 3.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.7.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.0.4 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_easyloading 3.0.3 [flutter flutter_spinkit]
- flutter_form_builder 6.1.0+1 [flutter flutter_localizations intl collection]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_verification_code 1.1.0 [flutter]
- font_awesome_flutter 9.1.0 [flutter]
- get 4.3.8 [flutter]
- image_picker 0.8.4+1 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- permission_handler 8.1.6 [flutter meta permission_handler_platform_interface]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.4.3 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- cross_file 0.3.1+5 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 2.0.3 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.3 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- modal_bottom_sheet 2.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 2.0.4 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.6.1 [flutter meta plugin_platform_interface]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.3 [file path platform]
- rxdart 0.27.2
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- universal_platform 1.0.0+1
- uuid 3.0.5 [crypto]
- vector_math 2.1.0
- win32 2.2.9 [ffi]
- xdg_directories 0.2.0 [meta path process]
</details>

---

**Comment by markusaksli-nc** [comment]
Hi @mianazeemdaula 
This error points to an issue in the network connection and usually shows up if the device is offline.
Is this on a device with a working internet connection? Have you tried it on multiple devices?
Thank you

**Comment by mianazeemdaula** [comment]
Yes I tried on multiple devices, Error comes only after release (flutter build apk) in debugging mode its work fine.

**Comment by markusaksli-nc** [comment]
Have you added your SHA-1 and SHA-256 keys to Firebase Console?
