### ISSUE TITLE
🐛 [all] main branch build fails because of removed registerWith function

### ISSUE THREAD

**Issue by juliansteenbakker** [FirebaseExtended/flutterfire#7157]
## Bug report

#7127 removed the registerWith function from the core plugin. Other plugins are however still depending on this. These references have to be removed in order to fix the build of the main branch.

### Steps to reproduce

See https://github.com/FirebaseExtended/flutterfire/runs/3816828774

**Comment by Salakar** [comment]
Closed in #7158
