### ISSUE TITLE
[firebase_analytics] Plugin does not properly report all types of route changes

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#716]
If you replace or remove the current route, I would expect it to be reported by `FirebaseAnalyticsObserver`; however, that class does not observer `didRemove` nor `didReplace`.

**Comment by kroikie** [comment]
@alanrussian

The issue at https://github.com/flutter/flutter/issues/20452 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age of this issue and lack of activity; I'm going to close this issue in favour of trying the latest release.
