### ISSUE TITLE
IOS does not report firebase_previous_screen with firebase analytics

### ISSUE THREAD

**Issue by dennisvanmaren** [FirebaseExtended/flutterfire#7160]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/7155

<div type='discussions-op-text'>

<sup>Originally posted by **dennisvanmaren** October  7, 2021</sup>
Hi

With firebase analytics on Android we receive the firebase_previous_screen parameters but with IOS this field is empty. Anyone have any idea how to get the firebase_previous_screen values? We use FirebaseAnalytics().setCurrentScreen to set the current screenname when a screen transition occurs. 

![image](https://user-images.githubusercontent.com/58005483/136331994-d8e1e6f3-1238-4c5f-80e9-5907969fe904.png)

Thanks

Dennis</div>

**Comment by darshankawar** [comment]
@dennisvanmaren 
Can you provide `flutter doctor -v` and a self-contained minimal reproducible code sample that we can use to verify this ?
Thanks.

**Comment by darshankawar** [comment]
@dennisvanmaren 
Is it occuring in CI/CD ? or locally ?
Are you able to replicate this behavior locally ? Can you try the official plugin [example](https://pub.dev/packages/firebase_analytics/example) and see if you get same issue or not ?
Thanks.
