### ISSUE TITLE
🐛 flutter_messaging iOS receiving data but not message.

### ISSUE THREAD

**Issue by rydal** [FirebaseExtended/flutterfire#7172]
## Bug report
iOS receives messsages in flutter using callback handler but message.data is null. Messages with notificaion are being received on the device, but no data is sent.

```
### Steps to reproduce
**Appdelegate.swift:**
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate,MessagingDelegate {
    override init() { FirebaseApp.configure() }

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)

    }

}
**Foreground and background handler:**

  static getMessages(_scaffoldKey, User user) {
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      IncomingMessage.process(message);
      _scaffoldKey.currentState.showSnackBar(
          SnackBar(
            content: Text('New Message!'),
            duration: Duration(seconds: 5),

          ));
    });
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      IncomingMessage.process(message);
      _scaffoldKey.currentState.showSnackBar(
          SnackBar(
            content: Text('New Message!'),
            duration: Duration(seconds: 5),

          ));
    });
  }

class IncomingMessage {

  static process(RemoteMessage remote_message) async {
    init_db();
    Database db = await database;
    Map<String,dynamic> message = remote_message.data;

    print(message.toString() + "RESULT");
...
}
**PHP sending:**
     $message = CloudMessage::fromArray([
                'token' => $token,
                'apns' => [
                    'headers' => [
                        'apns-priority' => '10',
                    ],
                    'payload' => [
                        'aps' => [

                            'data' => [...data])

                            ],


                        ],
                    ],
                ],

            ]);
```

**Result:**
flutter: {}RESULT
2021-10-11 21:47:19.734507+0100 Runner[7832:637519] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.

### Expected behavior
messsage data is not null.

---
**Doctor summary (to see all details, run flutter doctor -v):**
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.53.2)
[✓] Connected device (4 available)

• No issues found!

**Comment by darshankawar** [comment]
@rydal 
Can you provide the plugin version you are using ? 

The error you are getting:
```
`
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.`
```

Indicates that you are calling the index `([])` operator on `null`, so you may need to check your implementation where you are trying to access the index. Also you'll want to examine the stack trace and look at the line number where the failure occurred.

Also please check if you have correctly setup the configuration to send and receive messages per the document.https://firebase.flutter.dev/docs/messaging/overview/#4-apple-integration
