### ISSUE TITLE
🐛 [firebase_auth] Phone Auth OTP not getting delivered[ An invalid safety_net_token was passed. ]

### ISSUE THREAD

**Issue by ProjectSi5** [FirebaseExtended/flutterfire#7193]
I was using phone auth for many months, but randomly I stopped getting OTP's and this is the error that shows.

[SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17028 An invalid safety_net_token was passed.
I/flutter (26696): This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ An invalid safety_net_token was passed. ]

I have added the SHA 1 and 256 keys (both release and build) to my firebase project. I have also enabled the Android Device Verification API on google cloud.

**Comment by EngALAlfy** [comment]
same as you @DriesCruyskens

**Comment by tamirrab** [comment]
Same here!
I think it's over 4 hours now

**Comment by tamirrab** [comment]
My app is on the store a year,  it's suddenly happen! and users can't sign in

**Comment by EngALAlfy** [comment]
#firebase_auth: ^1.4.1
  firebase_auth: ^3.1.3
  two versions have the problem
  in release and debug

**Comment by varadkulk** [comment]
A temporary fix is to disable Android Device Verification API from Google Cloud Console

**Comment by simonesestito** [comment]
It looks fixed for me too, without applying any change in the app, its dependencies nor recompiling it
