### ISSUE TITLE
[firebase_remote_config] Upgrade to the Remote Config V2 SDKs

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#72]
The [current version of `firebase_remote_config`](https://pub.dev/packages/firebase_remote_config/versions/0.2.0+7) does not yet use the V2 SDKs.

https://firebase.googleblog.com/2019/08/remote-config-v2-sdk-update.html

**Comment by creativecreatorormaybenot** [comment]
There are missing functions:

>Another important update for smarter fetching is the introduction of the new **FetchTimeoutInSeconds** and **MinimumFetchIntervalInSeconds** parameters, which can be used together to provide smarter fetching policies for your app.

**Comment by naiduasn** [comment]
Any update on when will this be picked up?

**Comment by Salakar** [comment]
As far as I know we're using the latest Firebase SDKs already, was there something in particular that needs doing? If so please raise a feature request here: https://github.com/FirebaseExtended/flutterfire/discussions/category_choices
