### ISSUE TITLE
[📚] FCM Apple Integration

### ISSUE THREAD

**Issue by 3rsin3rgul-Corplife** [FirebaseExtended/flutterfire#7210]
Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

Please update this page -> https://firebase.flutter.dev/docs/messaging/apple-integration/
  "use_frameworks!" is missing on pod file.

target 'ImageNotification' do
  use_frameworks!
  pod 'Firebase/Messaging'
end

**Comment by russellwheatley** [comment]
Hey @3rsin3rgul-Corplife, the [documentation](https://firebase.flutter.dev/docs/messaging/apple-integration/#step-2---add-target-to-the-podfile) has been updated now. Thanks.
