### ISSUE TITLE
[plugins/firebase_auth] Access custom claims

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#723]
Hi community, I don't know if it's the right place to ask this. I use firebase for authenticating my users and I really need access to custom claims to have different behaviors in my applications based on some informations inside the custom claims.
The doc https://firebase.google.com/docs/auth/admin/custom-claims provides example for android, I've looked into the firebase_auth doc and code and found nothing related.
In my opinion it's a really important feature, maybe I've missed something somewhere, if it's the case I'm sorry.

**Comment by kroikie** [comment]
@arthurgustin

The issue at https://github.com/flutter/flutter/issues/20238 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by sperochon** [comment]
It seems to me that getting the custom claims is now available since the 0.14.0 version of firebase_auth with the following commit:
https://github.com/FirebaseExtended/flutterfire/commit/4870b94aa65f373ab9464a9551db8836f7a5305a

So, maybe this issue should be closed?

**Comment by creativecreatorormaybenot** [comment]
This is resolved, [see this](https://stackoverflow.com/a/58373886/6509751).
