### ISSUE TITLE
[firebase_storage] Continuing Uploads Across Process Restarts using Flutter

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#724]
Firebase - Cloud Storage - Continuing Uploads Across Process Restarts using Flutter

I am looking for the feature to upload files on firebase cloud storage and handle the poor network situations or continuing uploads across process restarts.

I have a reference in Android for the same.

Continuing Uploads Across Process Restarts
Reference - https://firebase.google.com/docs/storage/android/upload-files#continuing_uploads_across_process_restarts

I can't able to find this in flutter package 'firebase_storage' - https://pub.dartlang.org/packages/firebase_storage

Can anyone help? This feature is work in progress or it's already there in the package.

**Comment by kroikie** [comment]
@JigneshPatel23

The issue at https://github.com/flutter/flutter/issues/20226 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by kirstywilliams** [comment]
This functionality is implemented. See [documentation](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/StorageUploadTask/resume.html) here.
