### ISSUE TITLE
🐛 [Firestore] withConverter doesn't work with nullable documents

### ISSUE THREAD

**Issue by LucaDillenburg** [FirebaseExtended/flutterfire#7264]
## Bug report

**Describe the bug**
When using the ```withConverter``` function with a nullable type, if the ```fromFirestore``` returns a null (and it should be able to do that), the ```doc.data()``` throws an Exception.

### Steps to reproduce

1. Create a query using the ```withConverter``` method and a nullable class (i.e.: ```Data```). This query should have the following type: ```Query<Data?>```.
2. Get the query and map all documents to their datas: ```.map((doc) => doc.data())```
3. If any of ```fromFirestore``` calls returns null, it will throw an exception. Note: ```fromFirestore``` can return null if the map is empty or for any other reason (i.e.: the ).

### Expected behavior

Instead of throwing an exception, it should return the null value as it was intended by ```fromFirestore```. That way, instead of failing, the example above would result in ```Iterable<Data?>```.

### Sample project

```dart
import 'package:firebase/firestore.dart';

class Data {
  final String name;
  Data(this.name);
}

Stream<List<Data?>> get dataStream => FirebaseFirestore.instance
    .collection('data')
    .withConverter<Data?>(
      fromFirestore: (map, options) {
        final name = map['name'] as String?;
        if (name == null) return null;
        return Data(name);
      },
      toFirestore: (data, options) {
        assert(data != null);
        return {'name': data?.name};
      },
    )
    .snapshots()
    .map((snapshot) => snapshot.docs.map((doc) => doc.data()).toList());
```

---

## Additional context

I believe the problem is in the ```data()``` override in ```_WithConverterQueryDocumentSnapshot```:

```dart
class _WithConverterQueryDocumentSnapshot<T extends Object?>
    extends _WithConverterDocumentSnapshot<T>
    implements QueryDocumentSnapshot<T> {

/*...*/

  @override
  T data() => super.data()!;
  // This method results in an exception if ```T``` is nullable.
}
```

This is probably explained by the code below:

```dart
T force<T>(T? Function() data) {
  return data()!;
}
void main() {
  print(force<int?>(() => null));  // EXCEPTION
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0.1 21A559 darwin-arm, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by cedvdb** [comment]
The return type should be R? for a single document instead of R. For a query snapshot it's okay if it's `List<R>`.

Currently you either have `R` and `List<R>` or `R?` and `List<R?>` which makes zero sense. 

Here are workaround extensions

```dart
import 'package:cloud_firestore/cloud_firestore.dart';

extension DataList<R> on QuerySnapshot<R> {
  List<R> data() => docs.map((doc) => doc.data()).toList();
}

extension DataStream<R> on Stream<DocumentSnapshot<R>> {
  Stream<R?> data() => map((doc) => doc.data());
}

extension DataStream2<R> on Stream<List<DocumentSnapshot<R?>>> {
  Stream<List<R>> data() =>
      map((docs) => docs.map((doc) => doc.data()!).toList());
}

extension DataStream3<R> on Stream<QuerySnapshot<R?>> {
  Stream<List<R>> data() => map((doc) => doc.data() as List<R>);
}


```

**Comment by ciriousjoker** [comment]
Is this being looked at?

**Comment by MCiocio** [comment]
Is there anyone who has found at least a workaround to this problem?
