### ISSUE TITLE
firebase messaging

### ISSUE THREAD

**Issue by kratipandey57** [FirebaseExtended/flutterfire#7267]
hello team ,

i am getting notifications from firebase console in flutter ios but not in my app.

**Comment by kratipandey57** [comment]
Hello Team ,

I followed all the steps as given "https://firebase.flutter.dev/docs/messaging/apple-integration".
My app is receiving notifications from firebase console , but not from backend server side code.

**Comment by darshankawar** [comment]
@kratipandey57 
Can you provide `flutter doctor -v`, `pubspec.yaml` ?
Also, try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if it works for you.

**Comment by kratipandey57** [comment]
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 2.5.0 at /Users/amtagglobal/Documents/latest_flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/amtagglobal/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

**Comment by kratipandey57** [comment]
Pubspecfile





cupertino_icons: ^1.0.3
  json_annotation: ^4.1.0
  flutter_bloc: ^7.3.0
  bloc: ^7.2.0
  equatable: 2.0.3
  formz: 0.4.0
  json_serializable: ^5.0.2
  flip_card: 0.5.0
  dio: ^4.0.0
  shimmer: 2.0.0
  rxdart: ^0.27.2
  card_swiper: 1.0.4
  flutter_countdown_timer: 4.1.0
  intl: 0.17.0
  jiffy: 4.1.0
  bottom_navy_bar: ^6.0.0
  animations: 2.0.1
  blinking_text: ^1.0.1+2
  pin_code_fields: 7.3.0
  flutter_spinkit: 5.1.0
  universal_platform: 1.0.0+1
  sizer: ^2.0.15
  google_fonts: ^2.1.0
  flutter_screenutil: 5.0.0+2
  shared_preferences: 2.0.7
  file_picker: ^4.0.1
  permission_handler: ^8.1.6
  syncfusion_flutter_pdfviewer: 19.2.59-beta
  share: 2.0.4
  country_picker: 2.0.8
  image_picker: 0.7.0
  mime: 1.0.0
  path_provider: ^2.0.0
  file_utils: ^1.0.1
  flutter_launcher_icons: ^0.9.2
  firebase_messaging: 10.0.8
  #flutter_local_notifications: ^8.2.0
  flare_flutter:
  firebase_core: 1.8.0
  overlay_support: ^1.2.1
  open_file: ^3.2.1
  percent_indicator: ^3.4.0
  animated_check: ^1.0.5
  awesome_dialog: 2.1.1
  fluttertoast: 8.0.8
  firebase_analytics: ^8.3.1
  firebase_auth: ^3.1.0
  awesome_notifications: 0.0.6+12
  flutter_logs: 2.1.4

**Comment by kratipandey57** [comment]
Hello team ,

In "https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/exampl"

example , AppDelegate.h and AppDelegate.m file but in my app it has only AppDelegate.swift file , which file , we should use ?

**Comment by darshankawar** [comment]
If you have `AppDelegate.swift`, use `AppDelegate.m`.

**Comment by kratipandey57** [comment]
any example of this ?

**Comment by darshankawar** [comment]
Please check the official example which should give you the idea. The discussion here isn't leading us to anywhere to analyze the issue, so please provide us concrete steps to replicate along with minimal code sample to properly address this issue.
