### ISSUE TITLE
FirebaseMessaging.instance.getAPNSToken always return null

### ISSUE THREAD

**Issue by yonycherkos** [FirebaseExtended/flutterfire#7278]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/7273

<div type='discussions-op-text'>

<sup>Originally posted by **yonycherkos** October 30, 2021</sup>
**Describe the bug**
I have an issue on which i was not able to get APNs token on ios. the push notification works fine on android. I go through [FCM apple integration](https://firebase.flutter.dev/docs/messaging/apple-integration) steps repeated with no luck. I am stuck on this issue for weeks. 

*package versions and testing device*
- flutter: 2.2.3
- firebase_core: 1.8.0
- firebase_messaging: 10.0.9
- iPhone 7: 14.4.1 (real device)

*xcode configuration*

![Screen Shot 2021-10-30 at 6 25 31 PM](https://user-images.githubusercontent.com/45253598/139539510-11edcf2d-8f69-487f-a28b-16e7da44c6ab.jpeg)

<details>

  <summary>AppDelegate.swift</summary>
  
  ```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure() 
    GeneratedPluginRegistrant.register(with: self)
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

</details>

<details>

  <summary>debug console</summary>
  
  ```flutter: User granted permission
8.8.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '662970956514'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
flutter: APNSToken: null
flutter: Token: c0yzY5QV4EUFudl0fmcCfA:APA91bHzAM9e2jfPEoDBnHQE9xCIG-EwnGatI9RDYPJQ4Apm5tOujBsplHyAqTm2V7DEPXSmDaPcr1okv6qhP-eoWHNmPs3e8IgN9CI4ErS2-W54_EydI2ypZ9ckJNOluLV_ECtWyP4i
[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 85 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 85 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
```

</details>

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-x64, locale
    en-ET)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

• No issues found!Ï```

</details>

Thank you in advance.</div>

**Comment by darshankawar** [comment]
@yonycherkos 
Looking at the error you are getting, it could be due to a setup / configuration issue at your end. Try the solution mentioned in [this](https://github.com/FirebaseExtended/flutterfire/issues/6079#issuecomment-873590143) issue comment and see if it works for you.

**Comment by yonycherkos** [comment]
Hi @darshankawar, thank you for your response. I tried the solutions mentioned in issue #6079 with no luck. 

- disabled the FirebaseAppDelegateProxyEnabled.
- remove the APNs Authentication Key and regenerate the key. And just to mention I am using APNs Authentication Key not APNs certificate.

**Comment by darshankawar** [comment]
@yonycherkos 
Can you upgrade to latest stable (2.5.3) or latest master and try again ?

**Comment by JeanPOAlves** [comment]
I have the same problem

**Comment by yonycherkos** [comment]
For me, the issue was with my iPhone device. when I test it on another iPhone device it works fine.
