### ISSUE TITLE
firebase_auth - Other provider logins

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#728]
I noticed the sample for **firebase_auth** is based on just **phone** and **goggle** authentication.  (I got the **googleSignin** working following your example).  

**Question**
Will there be a **Facebook** and **Twitter** signin example from the firebase_auth team anytime soon -- since the firebase claims **"supporting email and password accounts, phone auth, and Google, Twitter, Facebook, and GitHub login, and more"** see https://firebase.google.com/products/auth/

1) Are there any plans to to provide this functionality (samples)?
2) Are there any plans to support Microsoft Azure/Azure B2C authentication? they are an OIDC provider; Azure B2C supports Google-Signin.
3) In the absence of (2) are there plans to support 'generic' OIDC providers?  This will help us fill in he 'gaps'
4) Can you share some kind of a planned feature timeline with us?

BTW:  the documentation on setting up/configuring the app was **right-on.**  The only problem I had was in the integration with the Firebase Console. As you know we search the web for possible solutions.  All my approaches failed until after the better part of an extended full day, I stumbled upon a codelabs 'tutorial' which pointed out that the SHA1 fingerprint for **debugging**  must use the 'debug.keystore' in **%USERINFO%** (windows environment).  Once I did that, my google Sign-in worked in seconds.

I suggest you either specify that on the setup page or provide a link to the relevant info.  I know it might be obvious to you -- bust just that one sentence could have save me over 10 hours..

**Comment by kroikie** [comment]
@samgithub-duplicate

The issue at https://github.com/flutter/flutter/issues/20092 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue (we have a social auth providers section on the website) & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration
