### ISSUE TITLE
🐛  [firebase_dynamic_links] Social Sharing Previews not working on Gettr

### ISSUE THREAD

**Issue by KennyChan94P** [FirebaseExtended/flutterfire#7280]
i managed to create a dynamic link with social sharing preview (title, description and image) and the details are shown when i share the link as a post on Facebook and as a tweet on Twitter.
but the link does not work in Gettr. when i share the link as a post on Gettr, it shows as a string but without the (title, description and image).
does anyone have any clue on how to show the (title, description and image) of the dynamic link on Gettr?
thank you.

**Comment by darshankawar** [comment]
@KennyChan94P 
This doesn't seem to be an issue in the plugin since it works on other platforms as you mentioned. You'll need to ask this question on support channels like Stackoverflow for further help.
Closing from here.
