### ISSUE TITLE
ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by kartik-trucksathi** [FirebaseExtended/flutterfire#7282]
In the new update of this plugin firebase token is not generate in the some of the devices. it throw the error SERVICE_NOT_AVAILABLE.

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
E/flutter ( 1741): #0      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)

**Comment by darshankawar** [comment]
> In the new update of this plugin

@kartik-trucksathi If you roll back to previous plugin version, does it work ?
Usually, that error is triggered could be by just a flaky connection. Also make sure you are not manually overriding the native Firebase SDK versions in your android/app/build.gradle.
Make sure the devices have a stable internet connection or test on a different network.

**Comment by kartik-trucksathi** [comment]
@darshankawar in the previous version it will work fine. but the new version of the plugin in the Mi device some times not working.

my android/app/build.gradle file
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.razorpay:checkout:1.5.13'
    implementation 'com.google.firebase:firebase-crashlytics:17.3.0'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.facebook.android:facebook-android-sdk:[8,9)'
}

**Comment by darshankawar** [comment]
@kartik-trucksathi 
Is this happening in debug or in release mode ?
Can you try by adding `classpath 'com.google.gms:google-services:4.3.3` or it's latest version to above file and see if it works ?
Also, try with plugin's official [example](https://pub.dev/packages/firebase_messaging/example) and see if you get same behavior or not.

**Comment by kartik-trucksathi** [comment]
@darshankawar 
Ok, Thank you
