### ISSUE TITLE
🐛 [firebase_dynamic_links] efr parameter not working on on Twitter

### ISSUE THREAD

**Issue by KennyChan94P** [FirebaseExtended/flutterfire#7283]
the dynamic link with efr=1 does not work on Twitter, i am still seeing the app preview page when clicking on the link.
however, on Facebook and iMessage, when i click on the same link, i do not see the app preview page.
does anyone have this problem?

**Comment by darshankawar** [comment]
@KennyChan94P 
It could be an issue with integration with Twitter using dynamic links as it could be a bit tedious to set it up. Also, this could be with the firebase setup and not necessarily with the plugin itself, so I just you to ask this question on stackoverflow or in firebase support for more help.

Closing from here.
