### ISSUE TITLE
🐛 [firebase_database] No error thrown, when losing rights, while listening on a child's value.

### ISSUE THREAD

**Issue by prime-rue** [FirebaseExtended/flutterfire#7285]
## Bug report

The onError function of a onValue stream is no longer triggered when the listener loses the right to read on this child.

```
1. Set database rules to:

"rules": {
  "foo": {
    ".read": true,
    ".write": true
  }
}
```

2. Open a value listener on child "foo":

```
database.reference().child("foo").onValue.listen((onData) {

}, onError: (onError) {

});
```

3. Set database rules to: (while listener is listening)

```
"rules": {
  "foo": {
    ".read": false,
    ".write": false
  }
}
```

### Expected behavior

Trigger the onError function with a permission_denied error inside, like in version 6.1.2 (last used version, which worked)

## Additional info

The following info is printed:
W/SyncTree( 7025): Listen at /foo failed: DatabaseError: This client does not have permission to perform this operation

### Flutter doctor

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale de-DE)
    • Flutter version 2.5.3 at C:\Users\Ant\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:/Programme/Android/SDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:/Programme/Android/SDK
    • ANDROID_SDK_ROOT = D:\Programme\Android\SDK
    • Java binary at: D:\Programme\JetBrains Toolbox\apps\AndroidStudio\ch-0\203.7784292\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Programme\JetBrains Toolbox\apps\AndroidStudio\ch-0\203.7784292
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\Programme\JetBrains Toolbox\apps\IDEA-U\ch-0\212.5457.46
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile)       • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 91.0.864.59

• No issues found!
```

**Comment by darshankawar** [comment]
@prime-rue 
Can you provide the complete error log along with `pubspec.yaml` ?
Also, what would be the use case which would require to change the rules while the firebase call is being listened to ?
Is there an easy way to call `onError` that triggers that exception ?
Thanks.

**Comment by prime-rue** [comment]
What do you mean with complete error log? 

This is the only given output:
`W/SyncTree( 7025): Listen at /foo failed: DatabaseError: This client does not have permission to perform this operation`

Setting the firebase rules manually was just an easy example. Imagine the rules are defined in such a way that nobody has reading rights anymore if a child is set to a certain value elsewhere.

Anyway the indication that the permission is no longer given, appears in the native system, why not in flutter as in version   firebase_database: 6.1.2?

My pubspec.yaml is:
```
name: myproject
description: description

version: 1.0.00+100000

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_database: ^8.0.1
  firebase_analytics: ^8.3.4
  firebase_messaging: ^11.1.0
  firebase_crashlytics: ^2.2.4

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```
Thank you.

**Comment by darshankawar** [comment]
@prime-rue 
The error `DatabaseError: This client does not have permission to perform this operation` indicates the plugin doesn't seem to have a valid permission to access the data. Is the listener being listened to any other database like firestore to authenticate user ? Because, somehow the listener is getting invalid due to which firebase throws the said error.

**Comment by prime-rue** [comment]
@darshankawar 
No, the fact that the listener is getting invalid is intended and right. My question is, why is the error only thrown somewhere but not in flutter, preferably in the onError function of the affected listener?!

**Comment by prime-rue** [comment]
@darshankawar 
I just tried and faced the same behavior I explained. Furthermore I noticed that the onDone function of the StreamSubscription isn't called either.

**Comment by darshankawar** [comment]
Keeping it open for further insights on this from team.

**Comment by Linkadi98** [comment]
My error message said `permission_denied`, I thought this will be treated like an exception so I tried to catch it but it wasn't. The listener was cancel without any specific reasons. I also tried to find in source code to see where the log came from but I couldn't find any. What should we do now?

**Comment by prime-rue** [comment]
I just upgraded to firebase_database: 9.0.2, it seems like what ever the problem was, it is fixed now. Error is thrown now again.
