### ISSUE TITLE
Did not find appCheck().getToken() method or any workaround.

### ISSUE THREAD

**Issue by tblazz** [FirebaseExtended/flutterfire#7286]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/7254

<div type='discussions-op-text'>

<sup>Originally posted by **tblazz** October 27, 2021</sup>
Hi, 

I did not find appCheck.getToken method in firebase_app_check lib in flutter.

For instance in my react project I used the app check generated token in my api call as follow : 
```
const appCheckTokenResponse = await firebase.appCheck().getToken(true);
config.headers["X-Firebase-AppCheck"] = appCheckTokenResponse.token
```

I want to do the same in flutter but I dont find any getToken method. Do you know if it is normal ? and if there is any workaround to accomplish this ? 

Thanks 
thomas</div>

**Comment by darshankawar** [comment]
@tblazz 
Since the plugin is in early access preview stage, it is likely that the said method will be added in future or once it hits stable. So till then, let's leave this question under discussions for tracking as you have already mentioned.
Closing from here.
