### ISSUE TITLE
Prevent short blink during authentification with firebase

### ISSUE THREAD

**Issue by desmeit** [FirebaseExtended/flutterfire#7288]
Users have to sign in for using my app and will then be signed in automatically, like this:

```
final firebaseUser = context.watch<User>();

 if (firebaseUser != null ) {
     
     return CupertinoHomePage();
  
}

return WalkThroughScreen();
```

This works very well, there is only one problem: While checking if firebaseUser is null or not, WalkThroughScreen(); is displayed very briefly (for a few milliseconds).

How can this be prevented? As I have read it is not possibnle to hide or show the splash screen manually.

```
[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.7 19H1217 darwin-x64, locale de-DE)
    • Flutter version 2.5.1 at /Users/XXX/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (7 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
```

**Comment by darshankawar** [comment]
@desmeit 
I am not sure if firebase_auth would have anything to do with showing any intermediate screen before authenticating users. I suggest you to ask this question on support channels like StackOverflow or Flutter's reddit page for solutions / workarounds.
Closing from here, as it doesn't seem to be an issue with the plugin.

**Comment by desmeit** [comment]
How can you be sure it's not a problem? It takes a moment until the UserData is loaded. How can I prevent WalkthroughScreen from being displayed during this time?
