### ISSUE TITLE
[auth] authStateChanges close

### ISSUE THREAD

**Issue by andrefedev** [FirebaseExtended/flutterfire#7310]
I am trying to use the method "**FirebaseAuth.instance.authStateChanges()**" to initialize my application, depending on the returned value it will show a login page or the dashboard page. I don't want to use a StreamBuilder because it means that I need to handle the "**ConnectionState.waiting**" to show a splash page while the user loads, the problem is that every time something is saved in my code this will be executed and the idea is to show the splash one you only see when initializing the app for the first time.

So I won't use a StreamBuilder but the question is authStateChanges () closes the connection under the hood or it should be handled manually to avoid memory loss.

```
void dispose() {
    // parent
    appNotifier.authStateChanges.close();
}

void _initializing() {
  appNotifier.authStateChanges.listen(
    (user) {
      appNotifier.setUser(user);
      if (_isInitializing) {
        _isInitializing = false;
        notifyListeners();
      }
    },
    onDone: () {
      debugPrint("event onDone");
    },
    onError: (e, s) {
      debugPrint("event onError $e");
    },
  );
}

build(BuildContext context) {
  return Navigator(
    key: // NavigatorKey,
    pages: _buildPages(),
    // other opts
  );
}

List<Page> _buildPages() {
  List<Page> stack = [];

  if (_isInitializing) {
    // Show AppInitSplashPage
  } else {
    if (appNotifier.user != null) {
      // Show DashboardPage
    } else {
      // Show AuthPage
    }
  }
  return stack;
}

```

**Comment by darshankawar** [comment]
@andrefedev 
Can you elaborate what exactly your issue is ? You opened it as a documentation issue, but what changes are you proposing in it ?
Thanks.
