### ISSUE TITLE
🐛 firebase_analytics logs not showing in firebase debug view

### ISSUE THREAD

**Issue by mclabs74** [FirebaseExtended/flutterfire#7312]
## Bug report

**Describe the bug**
Majority of my events not showing in the analytics debug view

### Steps to reproduce

1. clone and start sample project below (based on flutter skeleton)
2. open chrome dev tools console and turn on enable debug view logging
3. click around and see the gtag printing in the console, but nothing in firebase

see video
https://youtu.be/KnM4yyGfFgk

### Expected behavior

I would expect logs to appear in firebase debug view

### Sample project

https://github.com/mclabs74/flutter_analytics

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>
</summary>

```
Matt-MacBookPro:flutter_analytics mattc$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/mattc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mattc/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
Matt-MacBookPro:flutter_analytics mattc$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/mattc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mattc/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
see here
https://github.com/mclabs74/flutter_analytics/blob/main/flutter_analytics/pubspec.yaml
```

</details>

---

**Comment by darshankawar** [comment]
@mclabs74 
Can you also try the official plugin [example](https://pub.dev/packages/firebase_analytics/example) and see if it gives same behavior ?
Also, I am assuming this is on web ?

**Comment by mclabs74** [comment]
Hi @darshankawar , thanks for responding and for pointing me to the example. Yes, it is web. I tried the plugin example, and it is better. A few questions:

1. when I click on Test logEvent, it is several seconds before it appears in the debug view. is that normal? I was under the impression under debug mode, they show almost immediately.

https://youtu.be/wxJSoNUpW44

also, the event has several parameters 

https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/example/lib/main.dart#L72

which do not show in the Debug view. I tried opening all the attributes. do you know why? (I see that with the other events I checked, such as add_payment_info)

2. the example does not put the flutterfire initialization in the index.html, https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/example/lib/main.dart#L16

unlike this doc. https://firebase.flutter.dev/docs/installation/web/

are both places ok for the initializing firebase? 

Thanks again for getting back to me.

**Comment by darshankawar** [comment]
> 1. when I click on Test logEvent, it is several seconds before it appears in the debug view. is that normal? I was under the impression under debug mode, they show almost immediately.

Usually, the `seconds` column shows you the events that are logged in last 60 seconds. Same for minutes column which is usually for 30 minutes. Each event will have a timestamp which indicates time of the event it was logged on the device (web in your case), so you can look at that and see if it's reporting as soon as you click. 



> the event has several parameters

According to https://github.com/FirebaseExtended/flutterfire/blob/a91fa459add243b37a7da9a67fbe94f2116bb3ca/packages/firebase_analytics/firebase_analytics/example/lib/main.dart#L77  and hence you may be seeing only some paramaters and not all. You can access the link for more details.



> 1. the example does not put the flutterfire initialization in the index.html,

You may follow the flutterfire documentation for latest steps to initialize, ie, add only firebase-sdk in `index,html` and leave the entire initialization in the code, https://firebase.flutter.dev/docs/installation/web/#initializing-flutterfire

**Comment by mclabs74** [comment]
Thanks @darshankawar, one thing that is still confusing, for the event parameters used next to the comment 
```
Only strings and numbers (ints & doubles) are supported for GA custom event parameters
```
the main.dart method `_sendAnalyticsEvent` only sends strings and numbers, which is why it is confusing that they are not showing in the debug view.  Shouldn't all those parameters be logged?

**Comment by darshankawar** [comment]
@mclabs74 
Ideally yes, looking at the documentation specific to logging events: https://firebase.flutter.dev/docs/analytics/usage#logging-events which does mention that any additional parameters that we need to send.
Having said that, the plugin is still in beta and rework is going on to make it stable, so there's a chance that once it becomes stable, we may see the change / updates related to it. So I suggest you to keep an eye on https://github.com/FirebaseExtended/flutterfire/issues/6979

**Comment by mclabs74** [comment]
It does make sense to close. Thanks @darshankawar for all the help.
