### ISSUE TITLE
url_launcher on iOS has tap transparency on the top bar

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#733]
1. create scaffold with appBar and ListView for a body
2. add enough list items to be able to scroll down
3. use URL launcher on iOS
4. scroll down on the website
5. tap the native browser AppBar to scroll to home
6. go "back" to your app

At this point, you should notice that the ListView scrolls to home as if it's own appBar has been tapped

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/19951 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing it here and reopening in flutter/flutter as it doesn't seem to be related to firebase
