### ISSUE TITLE
🐛 [firebase_messaging] JobIntentService.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by l1z0b** [FirebaseExtended/flutterfire#7330]
When I compile my app after flutter clean and flutter pub get I get this error:

> Note: /Users/username/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.1.0/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java uses or overrides a deprecated API.

The plug in functions normally but I can't get rid of this error and I am worried that it will cause problems in the future, how can I solve this?

 **Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5 20G71 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)

**Comment by darshankawar** [comment]
@l1z0b 
That's more of a warning than an issue and most probably seems to be coming from native Android and it isn't necessarily an issue in the plugin. The library versions at native side may not match with what's in dart side and hence these warnings. You may try to update `minsdkversion` to 21 or 23 and see if it helps.

I am going ahead and closing this as not an issue in the plugin. You may look / search for similar issues on stackoverflow with solutions.  If you disagree, write in comments and I'll reopen it.

**Comment by l1z0b** [comment]
@darshankawar 
I am using firebase_messaging: ^11.1.0, I updated the minsdkversion to 21 but I get the same warning.
What do you mean by checking on latest master?

**Comment by darshankawar** [comment]
```
flutter channel master
flutter upgrade

```
