### ISSUE TITLE
🐛 [firebase_messaging] notification works for some time after installing app. But then notification stop completely

### ISSUE THREAD

**Issue by shehandmg** [FirebaseExtended/flutterfire#7336]
## Bug report

**Describe the bug**
First of all, I'm not sure this is a bug but I can't find anything wrong with the code and followed documentation to implement fcm in the app. I'm using aws sns to send notifications to devices via fcm. Notifications worked for some time for every user. but after some time(for some 3days, other 2week, etc) users stopped receiving notifications completely. Tried reinstalling app, adding app to unmonitored app(so os don't kill the bg process) but nothing worked.
On the other hand everything works in  aws server. Token update is also handled. What is the reason to notification to work at first and then  stop working after some time?

### Steps to reproduce

(app is for android only)

1.Implemented fcm in flutter app according to the documentation.>https://firebase.flutter.dev/docs/messaging/overview/  
2. firebase app configured.
3.run app and test notifications

### Expected behavior

App receive notifications at first and then stop receiving after some time.

### Sample project

I'm using aws sns to send notifications to users via firebase cloud messaging. App is built with flutter. Notifications work alright(background,foreground,killed) for some time but after that, notifications stops receiving completely.

Token refresh/update is handled. token updates on db.

There seems to be no issue with aws sns. I want to know is this the correct way of implementing fcm in a flutter app? is there anything wrong with the code?

AndroidManifest.xml----------------------------------------

...

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">

            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />

            
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
           
        </activity>
       
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="high_importance_channel" />

        
...

```
```
android > build.gradle

buildscript {
   ...

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.5'
    }
...
}
```


android > app > build.gradle

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:27.1.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.android.support:multidex:1.0.3'
    
}
```

```
and the main.dart background handler----------------------------------------

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'high_importance_channel', // id
  'High Importance Notifications', // title
  description:
      'This channel is used for important notifications.', // description
  importance: Importance.max,
);

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("fcm_bg_handler: message received");

  final payload = message.data;

  flutterLocalNotificationsPlugin.show(
      int.parse(payload["ID"]),
      payload["TYPE"] + " | " + payload["SITE_NAME"],
      payload["STATUS"] +
          " at " +
          payload["SITE_ID"] +
          "(" +
          payload["OCCURRED_TIME"] +
          ")",
      NotificationDetails(
        android: AndroidNotificationDetails(channel.id, channel.name,
            channelDescription: channel.description,
            icon: 'mipmap/ic_launcher',
            playSound: true,
            sound: RawResourceAndroidNotificationSound('alarm_ring_sweet'),
            importance: Importance.max,
            onlyAlertOnce: true),
      ));

  
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(MyApp());
}
```

---

## Additional context

There should be 100+ notifications sent everyday.  but don't receive a single notification now.
firebase_messaging: ^10.0.9
firebase_core: ^1.8.0

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] VS Code (version 1.62.1)
[√] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.3
Flutter SDK 2.5.2
app_name 1.0.16+16

dependencies:
- android_alarm_manager_plus 1.3.3 [flutter]
- another_flushbar 1.10.24 [pedantic flutter]
- clippy_flutter 1.1.1 [flutter]
- cupertino_icons 1.0.3
- custom_info_window 1.0.1 [flutter google_maps_flutter]
- firebase_core 1.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 9.0.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_ringtone_player 3.1.0 [flutter]
- google_maps_flutter 2.1.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 0.13.4 [async http_parser meta path]
- intl 0.17.0 [clock path]
- loading_indicator 1.2.0 [flutter async]
- path_provider 2.0.6 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 5.0.0 [collection flutter nested]
- toast 0.1.5 [flutter]

dev dependencies:
- build_runner 2.1.4 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.1.1 [build source_gen hive analyzer source_helper]

transitive dependencies:
- _fe_analyzer_shared 30.0.0 [meta]
- analyzer 2.7.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing 
watcher yaml]
- built_collection 5.1.1
- built_value 8.1.3 [built_collection collection fixnum meta]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_local_notifications_linux 0.3.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- google_maps_flutter_platform_interface 2.1.3 [collection flutter meta plugin_platform_interface stream_transform]
- graphs 2.1.0 [collection]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.3.0 [meta]
- logging 1.0.2
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- package_config 2.0.2 [path]
- path 1.8.0
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.2.10 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@shehandmg 
It's hard to tell as where exactly the issue could be. Did anything change in the device settings, like permissions ? Can you debug more by sending app in background and then check if `onBackgroundHandler` is being called to receive the messages ?
When you send the message, does it throw any kind of error or warning ? Also check the plugin's official [example](https://pub.dev/packages/firebase_messaging/example) for implementation and see if it helps. It sounds like it may have something to do with the implementation / fcm configuration rather than an issue in the plugin.

**Comment by shehandmg** [comment]
> @shehandmg It's hard to tell as where exactly the issue could be. Did anything change in the device settings, like permissions ? Can you debug more by sending app in background and then check if `onBackgroundHandler` is being called to receive the messages ? When you send the message, does it throw any kind of error or warning ? Also check the plugin's official [example](https://pub.dev/packages/firebase_messaging/example) for implementation and see if it helps. It sounds like it may have something to do with the implementation / fcm configuration rather than an issue in the plugin.

I have added the code. According to your knowledge can you see anything wrong with implementation?

**Comment by darshankawar** [comment]
@shehandmg 
I looked at your code sample, although not 100% sure, but the way you have implemented `onBackgroundMessage` could have something to do with it. For this, check the plugin's official [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib) and see if you have properly implemented all the handlers along with flutter local notification's implementation.

**Comment by shehandmg** [comment]
Issue was in backend. Not in the plugin or in flutter code.
