### ISSUE TITLE
🐛 [firebase_dynamic_links] Dynamic links not working for iOS app available only under TestFlight

### ISSUE THREAD

**Issue by jcblancomartinez** [FirebaseExtended/flutterfire#7338]
## Bug report

I've implemented a Flutter app for iOS and Android devices. I've configured universal links with firebase_dynamic_links.

The app has been deployed as internal testing only in Android and as testflight only in iOS. In Apple Store's "Pricing and Availability" tab, I've selected Spain in the regions where the app is available and in the iPhone, I'm authenticated with a Spanish account into Apple Store.

Dynamic links work perfectly in Android but not in iOS (from iPhone).

I want to test the correct behaviour of dynamic links for iOS before publicly launching.

Other than Flutter steps to set dynamic links up, I've taken the following iOS specific steps:

* I downloaded GoogleService-info.plist from Firebase console and added it to "ios/Runner" folder.
* I've configured FirebaseDynamicLinksCustomDomains in "ios/Runner/Info.plist" as 'https://www.domain.com/links'
* I've configured com.apple.developer.associated-domains in "ios/Runner/Runner.entitlements" as: 		 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:domain.com</string>
	</array>
</dict>
</plist>
```
I also debugged the dynamic links and it showed no errors or warnings.

### Steps to reproduce

1. Uninstall the app
2. Click on dynamic link from an iPhone
3. Apple's App Store gets opened and shows "App Not Available. The app is currently not available in your country or region"
4. Install the app in the iPhone via TestFlight
5. The app loads the dynamic link from step 2.

### Expected behavior

1. Install the app in an iPhone via TestFlight
2. Click on dynamic link from an iPhone
3. Apple's App Store gets opened showing the app page.
4. Install the app in the iPhone via App Store.
5. The app loads the dynamic link from step 2.  

### Sample project

```
  Future<void> init() async {
    if (!kIsWeb) {
      FirebaseDynamicLinks.instance.onLink(
          onSuccess: (PendingDynamicLinkData? dynamicLink) async =>
              _linkProcessor.processSuccess(dynamicLink),
          onError: (OnLinkErrorException e) async =>
              _linkProcessor.processError(e));

      final PendingDynamicLinkData? data =
          await FirebaseDynamicLinks.instance.getInitialLink();
      await _linkProcessor.processSuccess(data);
    }
  }

  Future<ShortDynamicLink> buildLinkToResource(
      {required String resourceType,
      required String resourceId,
      String? subResourceType,
      String? subResourceId,
      required String title}) async {
    String link = 'https://www.domain.com/resource/1';

    final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: 'https://www.domain.com/links',
      link: Uri.parse(link),
      socialMetaTagParameters: SocialMetaTagParameters(
        title: 'XXX | $title',
        description: !GetUtils.isNullOrBlank(subResourceType)! &&
                !GetUtils.isNullOrBlank(subResourceId)!
            ? 'entity.$subResourceType'.tr
            : 'entity.$resourceType'.tr,
        // imageUrl: Uri.parse(qImage)
      ),
      androidParameters: AndroidParameters(
        packageName: 'com.XXX.app',
        minimumVersion: 1,
      ),
      iosParameters: IosParameters(
          bundleId: 'com.XXX.app',
          appStoreId: 'appStoreId'),
      dynamicLinkParametersOptions: DynamicLinkParametersOptions(
          shortDynamicLinkPathLength: ShortDynamicLinkPathLength.short),
    );
    return await parameters.buildShortLink();
  }
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.7.0-3.1.pre, on macOS 11.6 20G165 darwin-x64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
Dart SDK 2.15.0-178.1.beta
Flutter SDK 2.7.0-3.1.pre
xxx_app 1.0.0+6

dependencies:
- amazon_cognito_identity_dart_2 1.0.3 [convert crypto http]
- aws_cognito_identity_api 0.2.0 [shared_aws_api]
- aws_pinpoint_api 0.2.0 [shared_aws_api]
- aws_s3_api 0.2.0 [shared_aws_api]
- aws_sts_api 0.2.0 [shared_aws_api]
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- cupertino_icons 1.0.3
- device_info_plus 3.1.1 [flutter device_info_plus_platform_interface device_info_plus_linux device_info_plus_macos device_info_plus_web device_info_plus_windows]
- elastic_client 0.3.8 [http http_client meta]
- firebase_dynamic_links 3.0.1 [firebase_core flutter]
- firebase_messaging 11.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- floating_action_bubble 1.0.9 [flutter]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_platform_widgets 1.9.5 [flutter]
- flutter_screenutil 5.0.0+2 [flutter]
- flutter_sound 8.3.9 [path_provider recase uuid provider flutter_spinkit path synchronized logger flutter flutter_sound_platform_interface flutter_sound_web]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_swiper 1.1.6 [flutter transformer_page_view flutter_page_indicator]
- flutter_switch 0.1.5 [flutter]
- flutter_typeahead 3.2.1 [flutter flutter_keyboard_visibility]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- font_awesome_flutter 8.12.0 [flutter]
- full_screen_image 1.0.2 [flutter]
- get 4.3.8 [flutter]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- http_interceptor 1.0.2 [http]
- image_picker 0.8.4+2 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- indexed_list_view 2.0.1 [flutter]
- keyboard_attachable 2.0.0 [flutter flutter_keyboard_visibility]
- material_floating_search_bar 0.3.4 [flutter meta]
- outline_gradient_button 2.0.0+1 [flutter]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- permission_handler 8.2.2 [flutter meta permission_handler_platform_interface]
- persistent_bottom_nav_bar 4.0.2 [flutter]
- pull_to_refresh 2.0.0 [flutter]
- quiver 3.0.1 [matcher]
- scroll_to_index 2.1.0 [flutter]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- synchronized 3.0.0
- timeago 3.1.0
- transformer_page_view 0.1.6 [flutter]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_strategy 0.2.0 [flutter_web_plugins]
- uuid 3.0.5 [crypto]
- video_player 2.2.7 [flutter meta video_player_platform_interface video_player_web html]
- video_thumbnail 0.4.3 [flutter]
- visibility_detector 0.1.5 [flutter]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- crypto 3.0.1 [collection typed_data]
- http 0.13.4 [async http_parser meta path]
- intl 0.17.0 [clock path]
- uuid 3.0.5 [crypto]
- xml 5.3.0 [collection meta petitparser]

transitive dependencies:
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- buffer 1.1.1
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- convert 3.0.1 [typed_data]
- cross_file 0.3.1+5 [flutter meta]
- csslib 0.17.0 [source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- device_info_plus_linux 2.1.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.2.1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.0 [device_info_plus_platform_interface ffi flutter win32]
- executor 2.2.2 [stack_trace]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_keyboard_visibility 5.1.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_linux 0.3.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_plugin_android_lifecycle 2.0.3 [flutter]
- flutter_sound_platform_interface 8.3.9 [flutter meta plugin_platform_interface logger]
- flutter_sound_web 8.3.9 [flutter_sound_platform_interface flutter logger flutter_web_plugins meta js]
- flutter_spinkit 5.1.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http_client 1.5.1 [buffer executor http]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.3 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- js 0.6.3
- json_annotation 3.1.1
- linkify 4.1.0
- lints 1.0.1
- logger 1.1.0
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.2.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.5 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.3.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.3 [file path platform]
- provider 5.0.0 [collection flutter nested]
- recase 4.0.0
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_aws_api 0.3.0 [crypto http json_annotation meta xml intl uuid]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.1
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.2.9 [ffi]
- xdg_directories 0.2.0 [meta path process]
</details>

---

**Comment by darshankawar** [comment]
@jcblancomartinez 
Thanks for the detailed report. When you say `dynamic links not working for ios app available only under testflight`, does that mean if app is installed via TestFlight, it does not recognize that the application is installed.?

**Comment by jcblancomartinez** [comment]
Hi @darshankawar

"it does not recognize that the application is installed" could be one of the reasons why the behaviour is unexpected but I don't have the confidence to say that is what's going on here.

Does it make sense?

Thanks.

**Comment by jcblancomartinez** [comment]
@darshankawar 

I've already found the issue. I was missing "www." in "com.apple.developer.associated-domains". It should be:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:www.domain.com</string>
	</array>
</dict>
</plist>

Thanks.

**Comment by SanketKarwa24** [comment]
I am facing the same issue.

I am using Firebase Dynamic Links, which have been working just fine when the application is installed directly using development profile. However, when I use the copy on Testflight,the dynamic link open the application but link is coming NULL.

I want to fetch parameters coming through link.
