### ISSUE TITLE
problem with firebase_admob 0.5.6.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#734]
Before used to work fine but after the update i cant build anymore my app on android. on IOS works fine. Flutter doctor shows everything ok.

```
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.0,16.0.0]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.1,16.0.1]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```

**Comment by kroikie** [comment]
@kondasoft

The issue at https://github.com/flutter/flutter/issues/19868 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Hello - due to the inactivity of this issue, I'm going to close it.

Please try upgrading Flutter & the plugin and if the problem will persists, create a new issue following the template.

Thanks!
