### ISSUE TITLE
🐛 [firebase_auth] ibi and isi not set in dynamic link when using sendSignInLinkToEmail with ActionCodeSettings

### ISSUE THREAD

**Issue by picaoao** [FirebaseExtended/flutterfire#7347]
## Bug report

**Describe the bug**

Using **sendSignInLinkToEmail** doesn't build correctly the email link when using ActionCodeSettings.

Only the `apn` and `amv` parametners are set as part of the link.
In order to work also for iOS, the `isi` and `ibi` should also be set.

If the app is not installed, it doesn't open the apple/google play store to install the app.
Nevertheless, if the the app is installed it works.

### Steps to reproduce

1. Create ActionCodeSettings:

```
Example:

 final acs = ActionCodeSettings(
      url:
          'https://$_deepLinkRedirectUrlPrefix/signup-email?email=$email',
      handleCodeInApp: true,
      iOSBundleId: _iosBundleId,
      androidPackageName: _androidBundleId,
      androidInstallApp: true,
      androidMinimumVersion: '12',
      dynamicLinkDomain: _deepLinkUrlPrefix,
    );
```
2. Invoke the sendSignInLinkToEmail
```
     _firebaseAuth.sendSignInLinkToEmail(
      email: email,
      actionCodeSettings: acs,
    );
```
3. Make sure you don't have the app installed

4. Open email app in your mobile device and click the link

5. The link follows to the continueURL (url parameter in ActionCodeSettings), and doesn't hit the store

### Expected behavior

When opening the link from the email, if the app isn't installed, it should go to the apple store or google play store to install, and not continue to **continueURL**

### Sample project

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-arm, locale en-PT)
    • Flutter version 2.5.3 at /Users/******/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/******/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Users/************/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cloud_firestore 2.5.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 3.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.11 [firebase_core flutter]
- firebase_messaging 10.0.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.0.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- cloud_firestore_platform_interface 5.4.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.4.4 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 6.1.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.4 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]

```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the detailed report. I see the same behavior using latest plugin version.

https://pub.dev/packages/firebase_auth/install

**Comment by picaoao** [comment]
Thanks, is there any way of working around this while we don't have a fix ?
It is an important engaging feature, as we can use a signup link to both install the app and redirect the user to a signup page (continuation)

**Comment by picaoao** [comment]
@Salakar @russellwheatley 

Following up on the report already above...

Effectively, the `ifl` parameter should be dropped in favor of the `isi` parameter for it to work. 
In my latest test the `ibi` is there, together with the `apn` and `amv`.

I picked the generated link (that I get in the email) and did this change above manually, copy/paste in the phone (iOS) and it worked like a charm.

**Comment by russellwheatley** [comment]
Hey @picaoao, I've had a look into this, not sure what we can do about it to be honest. We just wrap around iOS [sendSignInLinkToEmail](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#-sendsigninlinktoemail:actioncodesettings:completion:) method and pass in the properties on the [ActionCodeSetting](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRActionCodeSettings). 

It seems like an issue that would need to be raised on the [firebase-ios-sdk repo](https://github.com/firebase/firebase-ios-sdk) to find out why they aren't generating the application id parameter (`isi`) on the dynamic link.
