### ISSUE TITLE
[firebase_messaging] onBackgroundMessage does not works on iOs

### ISSUE THREAD

**Issue by DmitriyYakovlev** [FirebaseExtended/flutterfire#7350]
## Bug report

onBackgroundMessage on iOs does not works as expected
I can see the same issue here:
https://github.com/FirebaseExtended/flutterfire/issues/6112

This issue marked as CLOSED and there are no ability to write messages.
Looks like issue was locked and limited conversation to collaborators on 18 Jun
but it does not really solved

Please, provide us with actual status of this issue

**Comment by darshankawar** [comment]
@DmitriyYakovlev 
I think you are hitting https://github.com/FirebaseExtended/flutterfire/issues/6290.
Please follow-up in it for further updates.
Closing this as a duplicate.
