### ISSUE TITLE
[📚] Messaging: server-integration-send-messages-to-topics link is broken

### ISSUE THREAD

**Issue by neiljaywarner** [FirebaseExtended/flutterfire#7352]
this link is 404 https://firebase.flutter.dev/docs/messaging/usage/server-integration#send-messages-to-topics
but is referred to here https://firebase.flutter.dev/docs/messaging/usage/server-integration#send-messages-to-topics

**Comment by darshankawar** [comment]
Correct link should be https://firebase.flutter.dev/docs/messaging/server-integration#send-messages-to-topics

@neiljaywarner From which page / screen / document are you being referred to that link ?

**Comment by neiljaywarner** [comment]
@darshankawar  forgive me ,I'm not sure yet, but may I "hijack" the question a little and ask - is there anything else but "in topics" that can be used for a conditional FCM message... 

i wish there was a "easy" way - for public safety app - that you coudl send by zip code or city or something.
You can send to Firebase analytics audiences right?  Is that with api or only with console?
Yes, i apologize, out of scope question, i'll still look for hte broken link

**Comment by darshankawar** [comment]
@neiljaywarner 
Your question is probably better suited for support channels like StackOverflow. If you are proposing an enhancement in the plugin, please file a new issue with all required details.
Coming back to broken link, will wait to see how you got the broken link.
Thanks.
