### ISSUE TITLE
[Cloud Messaging] subscribe succcess

### ISSUE THREAD

**Issue by neiljaywarner** [FirebaseExtended/flutterfire#7353]
What is your suggested approach to track success/fail of topic subscribe?

Android native has a listener you can add for success.

**Comment by darshankawar** [comment]
@neiljaywarner 
Check [this](https://github.com/FirebaseExtended/flutterfire/issues/3785#issuecomment-704312156) issue comment and see if it helps to answer your question.

**Comment by neiljaywarner** [comment]
I think so but can you please mention in documentation to parallel Android
kotlin/java docs and surface the technique

....sent from my phone

**Comment by darshankawar** [comment]
I believe the request should belong to native sdk's repo and not here, since the plugin is just a wrapper around native firebase sdks and current behavior is preferred to be coming from native rather than from plugin itself.
Closing this as a duplicate of the linked issue.
