### ISSUE TITLE
[firebase_auth][web]: Add support for linkWithRedirect

### ISSUE THREAD

**Issue by doppio** [FirebaseExtended/flutterfire#7360]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/6070

<div type='discussions-op-text'>

<sup>Originally posted by **doppio** May  6, 2021</sup>
The auth package supports linking Firebase accounts via credential and phone number, but not via the pop-up based flow, which is preferred on web. The Firebase User API has a [linkWithPopup](https://firebase.google.com/docs/reference/js/firebase.User#linkwithpopup) function which I presume could be exposed through FlutterFire.

My use case is that I have enabled the "One account per email address" setting in my Firebase project. The FlutterFire documentation [explains](https://firebase.flutter.dev/docs/auth/error-handling#handling-account-exists-with-different-credential-errors) how to handle "account-exists-with-different-credential" errors when using  the recommended native flow, but an equivalent approach doesn't seem to be possible exclusively using the popup flow on web.

The same can be said for `linkWithRedirect`.</div>

**Comment by darshankawar** [comment]
@doppio 
`linkWithPopup` seems to have been added for web recently. See this merged PR: https://github.com/FirebaseExtended/flutterfire/pull/6562
I am updating this issue title to reflect the same. You can update the discussion thread per above.

**Comment by russellwheatley** [comment]
As mentioned, `linkWithPopup` is now available on web 🙏 . Thanks.
