### ISSUE TITLE
[FirebaseMessaging] instanceFor ?

### ISSUE THREAD

**Issue by imeDevelopers** [FirebaseExtended/flutterfire#7362]
Are you really still haven't add `FirebaseMessaging.instanceFor(app:)` Function ?
it exits in every firebase plugin and not in FirebaseMessaging plugin , i really don't know why !!

**Comment by imeDevelopers** [comment]
i found this comment:

//  Messaging does not yet support multiple Firebase Apps. Default app only.

but why !

**Comment by imeDevelopers** [comment]
i added this function:

```
  /// Returns an instance using a specified [FirebaseApp].
  static FirebaseMessaging instanceFor({required FirebaseApp app}) {
    return _firebaseMessagingInstances.putIfAbsent(app.name, () {
      return FirebaseMessaging._(app: app);
    });
  }
```

**Comment by imeDevelopers** [comment]
edited to:


```
  /// Returns an instance using a specified [FirebaseApp].
  static FirebaseMessaging get instanceFor({required FirebaseApp fbApp}) {
    return FirebaseMessaging._instanceFor(app: fbApp);
  }
```

**Comment by imeDevelopers** [comment]
then:

```
/// Returns an instance using a specified [FirebaseApp].
  static FirebaseMessaging instanceFor({required FirebaseApp app}) {
    return FirebaseMessaging._instanceFor(app: app);
  }
```

and it works ..

**Comment by darshankawar** [comment]
> but why !

firebase_messaging does not have multi app support on the native SDKs. If you read Flutterfire's [documentation](https://firebase.flutter.dev/docs/core/usage/#secondary-firebase-apps) for firebase_core, you will note that the native SDKs do not support secondary app usage for firebase_messaging.

You can also check out the documentation for android:

[firebase_messaging](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging#public-static-synchronized-firebasemessaging-getinstance) only allows you to set the default app instance.

[firebase_auth](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#public-static-firebaseauth-getinstance-firebaseapp-firebaseapp) & [cloud_firestore](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#getInstance(com.google.firebase.FirebaseApp)) allow you to set the app instance.

See this issue thread for your reference: https://github.com/FirebaseExtended/flutterfire/discussions/5565
Closing as this isn't an issue and something isn't actionable from messaging plugin side.
