### ISSUE TITLE
firebase_admob doesn't return height if using smartBanner

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#737]
if `BannerAd.size` is set to `AdSize.smartBanner`, `BannerAd.size.height` will not update to the actual height.

I understand this is probably because height is a constant, but since `firebase_admob` is an overlay I have to set padding of my Scaffold manually, so being able to get the height is critical.

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/19832 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing basing on the solutions in the original issue.
