### ISSUE TITLE
[cloud_firestore] Stream closed with status; description=Keepalive failed. The connection is likely gone

### ISSUE THREAD

**Issue by AliKales** [FirebaseExtended/flutterfire#7397]
when i use my firebase cloud code, after some minutes, if i want to use it again i get this error below:

**(24.0.0) [WatchStream]: (48761be) Stream closed with status: Status{code=UNAVAILABLE, description=Keepalive failed. The connection is likely gone, cause=null}.**

_I'm already using latest versions of firebase stuff_

**Comment by maheshmnj** [comment]
Hi @AliKales, Thanks for filing the issue. Please share the output of `flutter doctor -v` along with [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example). Does this issue occur often or sometimes? 
Looking at the [docs](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreException.Code#public-static-final-firebasefirestoreexception.code-unavailable), This seems to be issue on the firebase end which the plugin doesn't have any control, so please try again after sometime.


Thanks

**Comment by AliKales** [comment]
@maheshmnj Hi, yes this happens **always**

> [√] Flutter (Channel master, 2.6.0-12.0.pre.790, on Microsoft Windows [Version 10.0.19042.1348], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Community Edition (version 2020.1)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)
• No issues found!

Here is the code --

`await ref
            .orderBy("songId")
            .startAfter([lastSongId])
            .where('language', isEqualTo: language)
            .where('genre', isEqualTo: genre)
            .limit(10)
            .get()
            .then((querySnapshot) {
              for (var json in querySnapshot.docs) {
                listReturn.add(Song.fromJson(json.data()));
              }
            });`

**Comment by maheshmnj** [comment]
I can't reproduce this issue with `cloud_firestore: ^3.1.0`. Keeping this issue open for further investigation from the team.

**Comment by russellwheatley** [comment]
This seems like a problem with your internet connection.
