### ISSUE TITLE
🐛 [firebase_ml_vision] Can not build in android

### ISSUE THREAD

**Issue by liqiang1995** [FirebaseExtended/flutterfire#7399]
I tried the sample of firebase_ml_vision
But I could not build.

![image](https://user-images.githubusercontent.com/54995513/142745779-0f834c15-2845-483c-94ac-bad192d7900c.png)

I am using flutter 2.5.3 stable.

How can I fix this issue?

**Comment by maheshmnj** [comment]
Hi @liqiang1995, please share the output of `flutter doctor -v` the Android OS version and the version of the `firebase_ml_vision` for which the app fails to build.

Thanks

**Comment by akaldhafer** [comment]
according to the flutter dev the firebase_ml_vision currently discounted. I think they will release new update very soon. You may visit https://pub.dev/packages/firebase_ml_vision for more info.

**Comment by maheshmnj** [comment]
Thanks, @liqiang1995, Closing as `firebase_ml_vision` is no longer being maintained.
