### ISSUE TITLE
didReceiveRemoteNotification failed

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#741]
Hello! I use `firebase_auth` and `firebase_messaging` plugins.

For phone auth I use in my app delegate several methods:
1) `didRegisterForRemoteNotificationsWithDeviceToken`
2) `didReceiveRemoteNotification`
like described at [auth docs page](https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification)

but using these methods for auth I have an issue with `didReceiveRemoteNotification` in the `firebase_messaging` plugin. Only one of `didReceiveRemoteNotification` methods works

**Comment by kroikie** [comment]
@dimmetrius

The issue at https://github.com/flutter/flutter/issues/19758 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing basing on https://github.com/flutter/flutter/issues/19758#issuecomment-461554929
