### ISSUE TITLE
🐛 [firebase_storage] I CAN'T UPLOAD ANYTHING?

### ISSUE THREAD

**Issue by AliKales** [FirebaseExtended/flutterfire#7416]
When i try to use firebase_storage i get always error

here is the simple code that i copied from docs;

> Future handleTaskExample1() async {
    firebase_storage.UploadTask task = firebase_storage.FirebaseStorage.instance
        .ref('uploads/hello-world.txt')
        .putString('Hello World');

    try {
      // Storage tasks function as a Delegating Future so we can await them.
      firebase_storage.TaskSnapshot snapshot = await task;
      print('Uploaded ${snapshot.bytesTransferred} bytes.');
    } on FirebaseException catch (e) {
      // The final snapshot is also available on the task via `.snapshot`,
      // this can include 2 additional states, `TaskState.error` & `TaskState.canceled`
      print(task.snapshot);

      if (e.code == 'permission-denied') {
        print('User does not have permission to upload to this reference.');
      }
      // ...
    }
 

>  }

**But i get this error  below;**

> W/ExponenentialBackoff(18593): network unavailable, sleeping.
W/StorageUtil(18593): no auth token for request
W/NetworkRequest(18593): no auth token for request
W/NetworkRequest(18593): No App Check token for request.
W/System  (18593): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(18593): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
W/System  (18593): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(18593): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
W/NetworkRequest(18593): error sending network request POST https://firebasestorage.googleapis.com/[ _id of app on firebase.com_ ]
W/NetworkRequest(18593): javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x94ed8600: I/O error during system call, Connection reset by peer
W/NetworkRequest(18593): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/NetworkRequest(18593): 	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
W/NetworkRequest(18593): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
/NetworkRequest(18593): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/NetworkRequest(18593): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
W/NetworkRequest(18593): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:417)
W/NetworkRequest(18593): 	at com.google.firebase.storage.network.NetworkRequest.performRequestStart(NetworkRequest.java:250)
W/NetworkRequest(18593): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:270)
W/NetworkRequest(18593): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
W/NetworkRequest(18593): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:113)
W/NetworkRequest(18593): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
W/NetworkRequest(18593): 	at com.google.firebase.storage.UploadTask.sendWithRetry(UploadTask.java:477)
W/NetworkRequest(18593): 	at com.google.firebase.storage.UploadTask.beginResumableUpload(UploadTask.java:276)
W/NetworkRequest(18593): 	at com.google.firebase.storage.UploadTask.run(UploadTask.java:224)
W/NetworkRequest(18593): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$StorageTask(StorageTask.java:1072)
W/NetworkRequest(18593): 	at com.google.firebase.storage.-$$Lambda$StorageTask$q9YBoR_A8LB-JxTCx8JRQvabaZs.run(Unknown Source:2)
W/NetworkRequest(18593): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/NetworkRequest(18593): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/NetworkRequest(18593): 	at java.lang.Thread.run(Thread.java:764)

_FUTTER DOCTOR;_

> [√] Flutter (Channel master, 2.6.0-12.0.pre.790, on Microsoft Windows [Version 10.0.19042.1348], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Community Edition (version 2020.1)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

**Comment by AliKales** [comment]
When i try with Mobile internet connection it works fine but when i use Wi-Fi it doesnt work. So how am i gonna fix this?

**Comment by maheshmnj** [comment]
Hi @AliKales,  Thanks for filing the issue. 

> When I try with Mobile internet connection it works fine but when i use Wi-Fi it doesnt work. So how am i gonna fix this?

This seems to be an issue with your ISP, Closing as this isn't an issue with firebase_storage if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by maheshmnj** [comment]
@jamesdixon that issue seems related to the underlying infrastructure may be google apis or VPNs, firewalls, etc,  which the plugin does not have control on.
