### ISSUE TITLE
[firebase_auth] How can I handle FirebaseAuthUserCollisionException?

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#742]
I'm writing application using Firebase.
I want to show dialog when user enter the duplicated email in signup form.
There are many exception so I want to catch FirebaseAuthUserCollisionException.
But, I can't find anywhere, how can I use it?

**Comment by kroikie** [comment]
@baeharam

The issue at https://github.com/flutter/flutter/issues/19748 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by giorgio79** [comment]
Same here, I want to show the user a snackbox with the error message https://flutter.dev/docs/cookbook/design/snackbars

Should be basic to be able to access this collision...

**Comment by Salakar** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
