### ISSUE TITLE
[📚] Flutter Web with Firebase Emulator

### ISSUE THREAD

**Issue by kornha** [FirebaseExtended/flutterfire#7420]
Hello!

There is very little/no documentation for how to do this on the internet. The problem here is that the firebase `firebase.initializeApp(firebaseConfig);` is called in the index.html. How do we wish to direct to the emulator? Presumably in the index.html as well? Can we conditionally redirect? Looking for some thoughts on the appropriate approach here. Thank you!

**Comment by maheshmnj** [comment]
Looks like a valid documentation issue I could not find flutterfire docs for setting up Firebase Emulator for flutter web

@kornha meanwhile you may refer these and see if it helps.

https://fireship.io/snippets/firestore-emulator-flutter/
https://firebase.google.com/docs/emulator-suite/connect_and_prototype?database=Firestore#web

Thanks

**Comment by Ehesp** [comment]
Emulator usage is the same for any platform: https://firebase.flutter.dev/docs/firestore/usage#emulator-usage

Our e2e tests run on all platforms and use the following code: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart#L31

> The problem here is that the firebase firebase.initializeApp(firebaseConfig); is called in the index.html. How do we wish to direct to the emulator?

This is fine, it just creates a local Firebase App. Your emulator usage happens in Dart land.
