### ISSUE TITLE
🐛 [firebase auth] Cannot connect to emulator with hostname specified on iOS or Android

### ISSUE THREAD

**Issue by muzzah** [FirebaseExtended/flutterfire#7422]
## Bug report

**Describe the bug**
I have started the emulator locally using the following configuration
```
{
  "emulators": {
    "firestore": {
      "port": 8088,
      "host": "0.0.0.0"
    },
    "auth": {
      "port": "8082",
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true
    }
  }
}
```

And when I setup the firebase authentication instance I use following code
```
fireAuth.useAuthEmulator("siia.local.int", int.parse(8082));
```
where siia.local.int resolves to the ip on my local machine in the private IP space. This host is also used to connect to the firestore emulator. 

The app can connect without issues to the firestore emulator but fails to connect to the firestore auth emulator

```
[firebase_auth/network-request-failed] Network error (such as timeout, interrupted connection or unreachable host) has occurred.
```
Interestingly, on Android I get the following message

```
[firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ Cleartext HTTP traffic to siia.local.int not permitted ]
```

However, when I instead use 127.0.0.1 for the iOS simulator it works. 

### Steps to reproduce

As per above

### Expected behavior

Connection to firebase auth emulator should work

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
  cloud_firestore: ^3.1.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
```

</details>

---

**Comment by muzzah** [comment]
Just to add, if I allow cleartext to that hostname in Android by specifying it in the manifest file then I get the same error as the one from iOS as well

**Comment by darshankawar** [comment]
@muzzah 
Can you try / confirm couple of things ?

1. Are you using a hotspot connection to connect or through wifi ?
2. Can you check if any firewall rules are blocking the firebase_auth emulator to invoke properly ?
3. Add the IP assigned to your computer by router in your emulator configuration and see if it helps ?

**Comment by muzzah** [comment]
Seems to have been some kind of weird state issue. I dont know why but I did a content erase on the simulator and then reinstalled the app, it then worked. Sorry I couldnt provide further details. Ill close the issue and reopen if it persists
