### ISSUE TITLE
🐛 [FirebaseMessaging] Flutter web view plugin JavaScript Channel doesn't listen on Android 

### ISSUE THREAD

**Issue by bartukaan** [FirebaseExtended/flutterfire#7428]
When I initialize FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler) in main function,
webview javaScriptChannel doesnt listen any event on Android, but ios working well.
Anyone encountering this error?
Is there any idea for that situtation?

**Comment by Ehesp** [comment]
Please could you follow the issue template, providing versions, code examples and reproduction please.

**Comment by bartukaan** [comment]
Flutter version : 2.5.3,
dart: 2.14.4

flutter_webview_plugin: ^0.4.0 ( but I use edited version in my repo )

flutter_webview_plugin:
    git:
      url: https://github.com/bartukaan/flutter_webview_plugin.git
      ref: master
      
firebase_messaging: ^11.1.0 
  

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
....
  }
  
  
  WebviewScaffold(
          allowFileURLs: true,
          resizeToAvoidBottomInset: true,
          key: key,
          appBar: appBar(args),
          ignoreSSLErrors: true,
          url: args.fetchUrl!,
          withLocalStorage: true,
          withJavascript: true,
          debuggingEnabled: true,
          javascriptChannels: Set.from([
            JavascriptChannel(
              name: 'TEST',
              onMessageReceived: _onJSMsgRecv,
            ),
          ]),
          initialChild: Container(
            color: Colors.white,
            child: Center(
              child: CupertinoActivityIndicator(radius: 30),
            ),
          ),
        ),
  _onJSMsgRecv doesnt listen any event  on Android.  When I initialize FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler) in main function,

**Comment by bartukaan** [comment]
any idea?

**Comment by darshankawar** [comment]
@bartukaan 
Can you try couple of things ?

1. flutter_webview_plugin is 3rd party. Can you try Flutter's first party `webview_flutter` and check if it works ?
2. Instead of `_onJSMsgRecv`, can you pass any other method (without firebase) and see if gets called on Android ?

**Comment by bartukaan** [comment]
I solved my problem different way, thank you. 
I closed issue.
