### ISSUE TITLE
firebase_ml_custom using old MLModelInterpreter library

### ISSUE THREAD

**Issue by Mmisiek** [FirebaseExtended/flutterfire#7436]
The MLModelInterpreter library, which provided both a model downloading API and an interface to the TensorFlow Lite interpreter, is deprecated. This page describes how to use the newer MLModelDownloader library along with TensorFlow Lite's native interpreter interface.

**Comment by darshankawar** [comment]
@Mmisiek 
Is there any compile error you get while using this plugin ? If so, can you share the same along with steps to replicate ?

**Comment by MichalOneNav** [comment]
Hello, 
I have replaced this plugin with ml_downloader and managed to make it work for both platforms. 
Thank you

**Comment by Puspharaj** [comment]
downloading ml is ok, But we need a solid interpreter to do the work!. Right now we don't have the clear capability to do the work in android or ios devices. 
We have two plugins that work with ml_custom models but none of them are easily to get things done!, Will some expert will follow and make it work? 

tflite is deprecated, tflite_helpher which is not easy to work with anyway.
