### ISSUE TITLE
[firebase_auth] Getting DisplayName after creating account with email returns 'null'

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#744]
I came across a bug which returns `null` for `displayName` and `photoUrl` after creating a new account with `email` and `password`. This happens until the user signs out and signs back in. Or the app restarts. `Uid`, `email`, and `token` all seem to work fine. I have not yet tested Google Sign in or Facebook Sign in.

The error reproduces even after making sure to wait for `updateProfile()` to finish updating the `displayName` and `photoUrl`.

Right now my workaround is to logout and log back in, right after creating the new account.

**Comment by kroikie** [comment]
@jmen900

The issue at https://github.com/flutter/flutter/issues/19746 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @jmen900
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
