### ISSUE TITLE
Firebase Auth could need more documentation

### ISSUE THREAD

**Issue by sohaibnoman** [FirebaseExtended/flutterfire#7455]
I couldn't find any documentation on flutter fire about firebase auth, mentioning that its required the Podfile to have
`platform :ios, '10.0'` included, when the default for a flutter project still targets ios '9.0'. I received an error trying to run my application which states this, but if its not already included in the documentation maybe it should be.

**Comment by darshankawar** [comment]
This is documented already [here](https://firebase.flutter.dev/docs/installation/ios/#ios-supported-versions) which should answer your question.
Closing.
