### ISSUE TITLE
[📚] Do we need SSL certs for Messaging on IOS?

### ISSUE THREAD

**Issue by fabiancrx** [FirebaseExtended/flutterfire#7458]
The [docs](https://firebase.flutter.dev/docs/messaging/apple-integration#2-registering-an-app-identifier) show how to add the push notification capability to an app, but no 'configure' button is shown. 

So my questions are:
Is it needed a certificate?
Does the docs have information about this somewhere else?

![image](https://user-images.githubusercontent.com/37002358/144483230-b4c9f58a-7ba2-4e8f-8526-821019847d78.png)

I realize in the firebase console it says that it needs "either an APNs authentication key or APNs certificate to connect with APNs" , so is it OK to use it with just the "APNs authentication key"?

![image](https://user-images.githubusercontent.com/37002358/144503353-0eccb3c0-89b4-4855-94c5-ea06c5f54222.png)

**Comment by darshankawar** [comment]
@fabiancrx 
There was a similar issue reported, https://github.com/FirebaseExtended/flutterfire/issues/3404. Please go through it and see if it helps to answer your question.
Closing this as duplicate for now.
