### ISSUE TITLE
 "The getter 'instance' isn't defined for the type 'FirebaseAnalytics'. Is this code example wrong?

### ISSUE THREAD

**Issue by UlyssesAlves** [FirebaseExtended/flutterfire#7463]
When I try to follow the code as shown in the example in line below dart compiler complains with

> "The getter 'instance' isn't defined for the type 'FirebaseAnalytics'.
Try importing the library that defines 'instance', correcting the name to the name of an existing getter, or defining a getter or field named 'instance'."

https://github.com/FirebaseExtended/flutterfire/blob/ad926e50c294494c247c86129459a4af93e286ef/packages/firebase_analytics/firebase_analytics/example/lib/tabs_page.dart#L22

Is this example code wrong? If not, how can I get access to that "instance" member?

**Comment by Sguerra0199** [comment]
Same here

**Comment by gucci-sol** [comment]
I also encountered the same error.The following code worked for me.
```
  final FirebaseAnalytics analytics = FirebaseAnalytics();
```

**Comment by darshankawar** [comment]
@UlyssesAlves 
This seems to be happening using latest plugin version (^8.3.4).

![Screenshot 2021-12-06 at 5 04 42 PM](https://user-images.githubusercontent.com/67046386/144840000-734d3ad9-bd1e-43b7-a343-2fcb7230f3df.png)

**Comment by UlyssesAlves** [comment]
> @UlyssesAlves I also encountered the same error.The following code worked for me.
> 
> ```
>   final FirebaseAnalytics analytics = FirebaseAnalytics();
> ```

Yes. I'm currently using that too, but not in production yet. Would like to know if it's really ok to keep it as it is or if the instance member is actually really necessary.

**Comment by UlyssesAlves** [comment]
I'm trying to use a previous version of firebase_analytics plugin but I can't get rid of the latest version. No matter what I do flutter still downloads and uses the 8.3.4 version.

I've cleaned the cache but after doing so the 8.3.4 version was still there. Is there some way I can force flutter to stop trying to use this latest version and download 8.3.3 for example?

**Comment by russellwheatley** [comment]
The latest version of analytics  (`9.0.0`) uses `instance` to initialise: `final FirebaseAnalytics analytics = FirebaseAnalytics.instance;`. See [Changelog](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/CHANGELOG.md#900).
