### ISSUE TITLE
[firebase_auth] Can not run flutter app on android emulator 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#747]
## Steps to Reproduce

1. 
```
flutter run -d emulator-5554
```
## Logs

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.0s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleDebug'...                           7.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  3.5s
Syncing files to device Android SDK built for x86...         5.1s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:63372/
For a more detailed help message, press "h". To quit, press "q".
```
then the emulator shows

> flutter_app has stopped.

```
[✓] Flutter (Channel master, v0.5.8-pre.79, on Mac OS X 10.14 j3bjh3, locale en-SA)
    • Flutter version 0.5.8-pre.79 at /Users/ddjbc/flutter
    • Framework revision bb338ef2c6 (30 hours ago), 2018-07-19 07:24:06 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/had1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (3 available)
```

**Comment by kroikie** [comment]
@ihadabs

The issue at https://github.com/flutter/flutter/issues/19619 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by kirstywilliams** [comment]
Hey @ihadabs I'm reviewing issues, are you still experiencing this issue with a more recent version of firebase auth? - thanks!

**Comment by ihadabs** [comment]
I was just giving flutter a try.
Didn't use flutter again, so, I'm not sure about if the issue got fixed ^^)

I'd give it another try in the future.

**Comment by dunjil** [comment]
Had the same issue minutes ago. First close the Project from Android Studio, Then Go to the Project's Root Folder and DELETE the  **.idea** folder. Reopen your Project with Android Studio and Everything is fine. This worked for me...give it a try

**Comment by osunkoyadavid** [comment]
> ## Steps to Reproduce
> 
> ```
> flutter run -d emulator-5554
> ```
> 
> ## Logs
> ```
> Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Initializing gradle...                                       1.0s
> Resolving dependencies...                                    1.0s
> Running 'gradlew assembleDebug'...                           7.8s
> Built build/app/outputs/apk/debug/app-debug.apk.
> Installing build/app/outputs/apk/app.apk...                  3.5s
> Syncing files to device Android SDK built for x86...         5.1s
> 
> 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
> An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:63372/
> For a more detailed help message, press "h". To quit, press "q".
> ```
> 
> then the emulator shows
> 
> > flutter_app has stopped.
> 
> ```
> [✓] Flutter (Channel master, v0.5.8-pre.79, on Mac OS X 10.14 j3bjh3, locale en-SA)
>     • Flutter version 0.5.8-pre.79 at /Users/ddjbc/flutter
>     • Framework revision bb338ef2c6 (30 hours ago), 2018-07-19 07:24:06 -0700
>     • Engine revision 5557e3006e
>     • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at /Users/had1/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.4.1, Build version 9F2000
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 24.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
>     • IntelliJ at /Applications/IntelliJ IDEA.app
>     • Flutter plugin version 24.0.1
>     • Dart plugin version 173.4700
> 
> [✓] VS Code (version 1.25.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.16.0
> 
> [✓] Connected devices (3 available)
> ```

still getting the same error

**Comment by osunkoyadavid** [comment]
> Had the same issue minutes ago. First close the Project from Android Studio, Then Go to the Project's Root Folder and DELETE the **.idea** folder. Reopen your Project with Android Studio and Everything is fine. This worked for me...give it a try

I'll try it, hope it works, flutter is to complicated, giving me a lot of errors

**Comment by osunkoyadavid** [comment]
I've finally ran flutter

**Comment by Ehesp** [comment]
This has now been fixed as part of the roadmap https://github.com/FirebaseExtended/flutterfire/issues/2582
