### ISSUE TITLE
🐛 Firestore crashes app while get data on android 4.4 & 5

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [FirebaseExtended/flutterfire#7471]
## Bug report

**Describe the bug**
the app crash just on release on android devices with 4.4 and 5 Android version and no problem occurs with android N and above either on release mode or debugging
the app works like charm on all devices except when i try to get the document from firestore then it crashes on the mentioned devices

multidex is enabled 
no problem with flutter doctor
I am using the latest version of every firebase plugin
this is the stack Trace from crashlytics
![IMG_20211206_111931](https://user-images.githubusercontent.com/20170741/144820205-aba79604-d3b7-4336-8453-3116afb53004.jpg)
![IMG_20211206_111819](https://user-images.githubusercontent.com/20170741/144820209-2896ca72-3217-4963-ac1b-5ad126806db1.jpg)

**Comment by darshankawar** [comment]
@Ahmed-elshorbagy 
Can you provide `flutter doctor -v` and the crash log in text format instead of in screenshots ?
Also is there a way for you to provide a symbolicated version of the crash ? 
Do you know if there are steps to replicate this crash so that we can analyze it better ?

**Comment by darshankawar** [comment]
@Ahmed-elshorbagy 
Can you try setting `minifyEnabled` and `shrinkResources` to `false` and see if it helps ?

**Comment by Ahmed-elshorbagy** [comment]
@darshankawar 
I tried to do so but nothing happened
even tried to use proguard instead of r8 also the same happened
it worked finally 
finally the only solution that helped me was adding this line in the build.gradle

`implementation ("com.google.guava:guava:30.1-android") { setForce(true) }`
I think this should be added to the documentation as 
this class
`com.google.common.base.CharMatcher`
not found by default in older android versions
hope this can help anyone and save them days of debugging

**Comment by Ahmed-elshorbagy** [comment]
the Solution is adding 
`implementation ("com.google.guava:guava:30.1-android") { setForce(true) }`
to your app build.gradle

**Comment by darshankawar** [comment]
@Ahmed-elshorbagy 
Glad to know you found the fix, but adding that line in documentation may not be feasible since it doesn't belong to the original setup, but maybe required for older Android OS (as in your case).
I am going ahead and closing this as resolved.
