### ISSUE TITLE
[firebase_storage] caches images but not URLs

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#749]
If I make a call to get the url of an image (like 'img/thing.png') there is considerable lag. I believe it is because the URL is not cached, even if the image is.

This is for `firebase_storage` package

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/19539 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by dfdgsdfg** [comment]
Any updates? Or workaround?

**Comment by Ehesp** [comment]
Hello

Do you mean once you get the download URL, it takes a long time to load the image via a browser?

**Comment by lukepighetti** [comment]
Honestly I can't remember.
