### ISSUE TITLE
[📚] FirebaseDatabase 9.0.0 Changelog does not mention removal of DatabaseReference.path getter

### ISSUE THREAD

**Issue by Lootwig** [FirebaseExtended/flutterfire#7495]
There is no mention of or migration guide to the removal of the `path` property, i.e. how to migrate calls like

```dart
db.update(<String, dynamic>{
      _reference1!.child('childUuid').path: item.toJson(),
      _reference2!.path: otherItem,
    });
```

**Comment by Salakar** [comment]
PR incoming to add this back in, it shouldn't have been removed, it's still there in the underlying platform interfaces just not exposed on the universal interface
