### ISSUE TITLE
[📚] Incomplete SIGNOUT documentation

### ISSUE THREAD

**Issue by Pingear** [FirebaseExtended/flutterfire#7514]
Hey)
I cannot find in the documentation how to log out. The example in the documentation specifies the only way - https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#:~:text=///%20Example%20code%20for%20sign%20out.

But third-party blogs often use an additional method - await _googleSignIn.signOut ();
At the same time, it is said that the method above cannot be used with a web platform, otherwise it will give an error, and I did it.

Where is the only correct information on how to log out is indicated if the web or non-web is used, google authentication or some other?

the documentation lists one single method - https://firebase.flutter.dev/docs/auth/usage#signing-out
(await FirebaseAuth.instance.signOut ();)

Where did (await _googleSignIn.signOut ();) come from then?

**Comment by Ehesp** [comment]
For signing out of Firebase, the `signOut()` method is all you need.

The `_googleSignIn.signOut()` is probably coming from https://pub.dev/packages/google_sign_in - I assume that the plugin stores the signed in on the device. So calling sign out on Firebase won't sign them out of the `google_sign_in` package. 

If `_googleSignIn.signOut()` is not called, the next time the user "Signs in with Google", they will be instantly signed in to Firebase without having the option to select the Google account.

**Comment by Pingear** [comment]
@Ehesp Thank You)
