### ISSUE TITLE
[📚] [analytics] No replacement information for FirebaseAnalyticsObserver

### ISSUE THREAD

**Issue by igorkurek** [FirebaseExtended/flutterfire#7526]
With release of Firebase Analytics 9, `FirebaseAnalyticsObserver` class previously used to monitor navigation was removed. I failed to find any information what's the correct approach to observe navigation events and send them to Firebase Analytics service. I think it would be good to provide information what should be done to continue tracking screen changes in latest versions of the library

**Comment by EA-YOUHOU** [comment]
Maybe following something like that https://newbedev.com/flutter-how-the-navigatorobserver-class-works... It's weird to remove an API without explicit documentation about the new best way :/

**Comment by russellwheatley** [comment]
Hey guys, after internal discussions, we've decided to add it back in. Apologies for the misunderstanding. PR to follow.

**Comment by deepak786** [comment]
To resolve the issue, I have copied the FirebaseAnalyticsObserver class from the package `firebase_analytics` inside my project.
