### ISSUE TITLE
firebase_storage does not auth?

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#754]
I have anonymous auth working.

```
Flutter: signed in! FirebaseUser({displayName: null, providerId: Firebase, uid: 6vj0tYIQsUSjsdiJfkjid37NhKk2, providerData: [], isEmailVerified: false, email: null, photoUrl: null, isAnonymous: true})
```

<img width="883" alt="screen shot 2018-07-13 at 7 01 44 pm" src="https://user-images.githubusercontent.com/666539/42717470-39085600-86cf-11e8-9e92-3d08322c050a.png">

And my rules are as follows

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

And I keep getting this error

<img width="1126" alt="screen shot 2018-07-13 at 7 02 38 pm" src="https://user-images.githubusercontent.com/666539/42717485-562be58a-86cf-11e8-8c6a-858c9976a773.png">

But if I change my rules to public

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}
```

It works!

<img width="738" alt="screen shot 2018-07-13 at 7 03 56 pm" src="https://user-images.githubusercontent.com/666539/42717507-8145ae4a-86cf-11e8-949d-0b3a5bfc8874.png">

Any ideas what's going on?

```
    this.user = await this.auth.signInAnonymously();
    print("signed in! $user");

    await _getAllSocialImageUrls();
    print("got socialUrls! $socialUrls");
```

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/19361 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey @lukepighetti - is this still an issue for you? Could you provide `flutter doctor` output if so, thanks

**Comment by lukepighetti** [comment]
This issue went unaddressed for so long I can't even remember if it is still an issue or not haha.

**Comment by Salakar** [comment]
> This issue went unaddressed for so long I can't even remember if it is still an issue or not haha.

@lukepighetti understandable 😅 can we close this issue for the time being? We'll be adding e2e tests that should highlight if this is an issue

**Comment by lukepighetti** [comment]
Yeah I would close it if I could but I'm not the OP anymore on this issue. :)

**Comment by Salakar** [comment]
> Yeah I would close it if I could but I'm not the OP anymore on this issue. :)

Cool, will close - thanks
