### ISSUE TITLE
The Crashlytics build ID is missing

### ISSUE THREAD

**Issue by erperejildo** [FirebaseExtended/flutterfire#7543]
Implementation:
```
apply plugin: 'com.google.firebase.crashlytics'
...
implementation 'com.google.firebase:firebase-crashlytics:17.3.0'
...
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
...
runZonedGuarded(() {
    runApp(
      LocalizedApp(
        delegate,
        MyApp(),
      ),
    );
  }, FirebaseCrashlytics.instance.recordError);
```

firebase_crashlytics: ^2.4.3 

doctor:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by Flucadetena** [comment]
Hi!, I'm getting this error also, with a basic new flutter app. What you commented, is it a fix? how to avoid the error? or...

If it is a fix could you elaborate more where to add this...

thanks ;)

**Comment by furkanvatandas** [comment]
Same issue with firebase_analytics: ^9.0.2 for Android
```
Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
```

**Comment by erperejildo** [comment]
> Hi!, I'm getting this error also, with a basic new flutter app. What you commented, is it a fix? how to avoid the error? or...
> 
> If it is a fix could you elaborate more where to add this...
> 
> thanks ;)

I'm getting that error from that implementation

**Comment by darshankawar** [comment]
@erperejildo 
Can you provide us full stacktrace of the error you are getting along with `flutter doctor -v` ?
Can you also try to use latest gradle version (2.7.1) as mentioned in the [documentation](https://firebase.flutter.dev/docs/crashlytics/overview/#2-optional-platform-integration) and see if it helps ?

**Comment by yk-sgr** [comment]
Getting the same error.

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.22000.318], locale en-DE)
    • Flutter version 2.8.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (6 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\yanni\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Users\yanni\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7935034\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\yanni\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7935034
    • Flutter plugin version 63.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Users\yanni\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.5744.223
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.0)
    • VS Code at C:\Users\yanni\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Pixel 4a (mobile) • 0B181JEC203003 • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
```

I'm running the app on Android.

Gradle plugin version is 2.7.1

**Comment by adfdev** [comment]
I have the same error:
`The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.`

**Comment by erperejildo** [comment]
> @erperejildo Can you provide us full stacktrace of the error you are getting along with `flutter doctor -v` ? Can you also try to use latest gradle version (2.7.1) as mentioned in the [documentation](https://firebase.flutter.dev/docs/crashlytics/overview/#2-optional-platform-integration) and see if it helps ?

I added more info but I cannot use the package now, it doesn't find it:
<img width="475" alt="Screenshot 2021-12-14 at 23 25 59" src="https://user-images.githubusercontent.com/5629919/146089249-f5f3926f-2fe5-4916-993b-df08173129c0.png">
<img width="221" alt="Screenshot 2021-12-14 at 23 26 05" src="https://user-images.githubusercontent.com/5629919/146089252-9c7ad344-8441-4104-bac8-c0f2cb1be84a.png">

**Comment by darshankawar** [comment]
@erperejildo 
I tried the steps / configuration you mentioned [here](https://github.com/FirebaseExtended/flutterfire/issues/7543#issue-1076771332) and ran a sample app which compiled and built properly without any issue or the log you mentioned, so I am unable to replicate this behavior. I followed all steps to properly setup per [documentation](https://github.com/FirebaseExtended/flutterfire/issues/7543#issue-1076771332) and ran on Android using latest master. 

Are there any specific steps that leads to this message ?

**Comment by erperejildo** [comment]
> @erperejildo I tried the steps / configuration you mentioned [here](https://github.com/FirebaseExtended/flutterfire/issues/7543#issue-1076771332) and ran a sample app which compiled and built properly without any issue or the log you mentioned, so I am unable to replicate this behavior. I followed all steps to properly setup per [documentation](https://github.com/FirebaseExtended/flutterfire/issues/7543#issue-1076771332) and ran on Android using latest master.
> 
> Are there any specific steps that leads to this message ?

Let me share all the dependencies I have installed, not sure if that would help:
```
line_icons: ^2.0.1
  dapackages: ^1.6.0 # keeps packages updated
  flutter_cupertino_localizations: ^1.0.1
  flutter_google_places: ^0.3.0
  google_mobile_ads: ^1.0.1 # needs Info.plist modification
  native_admob_flutter: ^1.5.0
  maps_launcher: ^2.0.1 # REMOVED, USE OTHER INSTEAD
  uuid: ^3.0.5 # IDs for events
  cloudinary_public: ^0.11.0
  showcaseview: ^1.1.4 # help for new users
  provider: ^6.0.1
  cloud_firestore: ^3.1.4
  firebase_core: ^1.10.5 # needs Runner/GoogleService-Info.plist
  firebase_auth: ^3.3.3 # needs Runner/GoogleService-Info.plist
  firebase_analytics: ^9.0.2 # needs Runner/GoogleService-Info.plist
#  firebase_crashlytics: ^2.4.3 # needs Runner/GoogleService-Info.plist and NSAppTransportSecurity in Info.plist
  http: ^0.13.4
  badges: ^2.0.2
  flutter_translate: ^3.0.1
  flutter_facebook_auth: ^3.5.7
  google_sign_in: ^5.2.1 # needs Info.plist modification
  sign_in_with_apple: ^3.3.0  # needs Xcode modification https://pub.dev/packages/sign_in_with_apple
  shared_preferences: ^2.0.10
  share_plus: ^3.0.4
  intl: ^0.17.0 # locales for table_calendar and datetime manipulation
  jiffy: ^4.1.0 # date manipulation
  permission_handler: ^8.3.0 # needs Info.plist modification
  csv: ^5.0.1
  path_provider: ^2.0.8
  package_info_plus: ^1.3.0
  after_init: ^0.1.2 # NO NULL
  flutter_email_sender: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  #  NEEDS TO BE UPDATED
  file_picker: ^4.2.7 # for multiple images selection
  image_picker: ^0.8.4+4 # for camera
  image: ^3.1.0
  url_launcher: ^6.0.17 # needs Info.plist modification
  transparent_image: ^2.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  flutter_slidable: 1.0.0-dev.9
  flutter_svg: ^1.0.0
  table_calendar: ^3.0.3
  add_2_calendar: ^2.1.2 # Info.plist modification
  #  NEEDS TO BE UPDATED
  contacts_service: ^0.6.3 # get contacts. Info.plist modification
  in_app_purchase: ^1.0.9 # official one.
  device_info_plus: ^3.1.1
  flutter_platform_widgets: ^1.11.1
  flutter_native_splash: ^1.3.2
  intl_phone_number_input: ^0.7.0+2  # NO NULL
  country_pickers: ^2.0.0
  currency_picker: ^2.0.6
  #  country_currency_pickers: ^1.0.1 # NO NULL
  reorderables: ^0.4.2 # NO NULL reorder rent fields
  drag_and_drop_gridview: ^1.0.8 # NO NULL
  pdf: ^3.6.5
  printing: ^5.6.6 # necessary for the above one
  open_file: ^3.2.1 # necessary for the above one
  #  flutter_statusbarcolor_ns: ^0.4.0 # DO NOT CHANGE
  fimber: ^0.6.4

```

**Comment by darshankawar** [comment]
I am unable to replicate this per my earlier [comment](https://github.com/FirebaseExtended/flutterfire/issues/7543#issuecomment-994673616) , so I am going ahead and labeling this based on several reports.

**Comment by eric-taix** [comment]
I have the same issue when using FlutterFire CLI: `google_app_id` is missing with Firebase analytics.

I solved it by using manual installation with google service Gradle plugin.

**Comment by erperejildo** [comment]
> I have the same issue when using FlutterFire CLI: `google_app_id` is missing with Firebase analytics.
> 
> I solved it by using manual installation with google service Gradle plugin.

can you provide more info about that please?

**Comment by dev-ltk** [comment]
> > I have the same issue when using FlutterFire CLI: `google_app_id` is missing with Firebase analytics.
> > I solved it by using manual installation with google service Gradle plugin.
> 
> can you provide more info about that please?

I think he means following the manual installation steps [here](https://firebase.flutter.dev/docs/manual-installation/android), which is working on the native side.

I have encountered this problem today. I ️initialized firebase and Crashlytics following the instruction [here](https://firebase.flutter.dev/docs/overview/) using CLI without touching any native codes. It throws the 'The Crashlytics build ID is missing' error on android but not on ios. It looks like the CLI is not working properly.

After I follow the manual installation steps, it works properly. To make it works, I also need to complete the optional step [here](https://firebase.flutter.dev/docs/crashlytics/overview#2-optional-platform-integration). Otherwise, I got stuck in building the app in any modes.

**Comment by MohamedFBoussaid** [comment]
I found a workaround that solved this issue (but I don't think this should be the way with Dart-only intialization (of course I have used a recent versions for the dependencies) . 

"I had a similar issue just now, but by following the steps in 'Upgrade to the Firebase Crashlytics SDK' managed to fix this.

Basically, you need to add the following to your build.gradle file in the android folder, in the dependencies section:

`classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'`
Then in the app level build.gradle, where you've already added com.google.gms.google-services previously, add:

`apply plugin: 'com.google.firebase.crashlytics'`
Finally, in the dependencies section in the same file, add:

`implementation 'com.google.firebase:firebase-crashlytics:17.3.0'`
This should now work. This is assuming you don't have any of the Fabric repository stuff in there, which you'll need to remove. The details are in that link. "

The original post was here: https://stackoverflow.com/questions/64834965/flutter-run-fail-in-andriod-studio-caused-by-java-lang-illegalstateexception-t

**Comment by erperejildo** [comment]
> irebase-crashlytics-gradle

so the only difference is that I should use firebase-crashlytics-gradle 2.4.1 instead of 2.7.1?
