### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by erperejildo** [FirebaseExtended/flutterfire#7559]
I'm getting this error but not sure why. Locally everything is fine but in Firebase logs I can see it:

![WhatsApp Image 2021-12-11 at 11 43 30 AM](https://user-images.githubusercontent.com/5629919/145673715-dde79614-6e61-4ec6-b223-92fe4ec4afed.jpeg)

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by Salakar** [comment]
The stack trace here doesn't seem to have anything to do with Firebase so not sure this is the right place for this issue?

**Comment by erperejildo** [comment]
> The stack trace here doesn't seem to have anything to do with Firebase so not sure this is the right place for this issue?

No, not sure at all, but I just get this in Firebase and not sure what it complains about. Any idea maybe?

I can close this if it sounds unrelated.

**Comment by darshankawar** [comment]
@erperejildo 
Although it's not super clear from the screenshots, but it seems to be pointing to native backend stack and may have to do with trying to access the db but unable to do so. You might want to search for it a bit more to get more ideas on it.
Since it doesn't look like related to flutterfire plugins, I'll close it. If you get concrete steps leading to any of the flutterfire plugins, write in comments and I'll reopen it.
Thanks.

**Comment by erperejildo** [comment]
> @erperejildo Although it's not super clear from the screenshots, but it seems to be pointing to native backend stack and may have to do with trying to access the db but unable to do so. You might want to search for it a bit more to get more ideas on it. Since it doesn't look like related to flutterfire plugins, I'll close it. If you get concrete steps leading to any of the flutterfire plugins, write in comments and I'll reopen it. Thanks.

I know. I tried to get more logs but that's what I see from Play console app. I'll try to gather more info
