### ISSUE TITLE
flutterfire_ui required old dependency flutter_svg ^0.22.0 instead new one flutter_svg ^1.0.0

### ISSUE THREAD

**Issue by Reriuqni** [FirebaseExtended/flutterfire#7579]
flutter pub add flutterfire_ui
Because every version of flutterfire_ui depends on flutter_svg ^0.22.0 and admin depends on flutter_svg ^1.0.0, flutterfire_ui is forbidden.
So, because admin depends on flutterfire_ui any, version solving failed.
pub finished with exit code 65

![image](https://user-images.githubusercontent.com/7934626/145769488-86598502-e99a-4546-abde-a5f380a0dcbd.png)

**Comment by Salakar** [comment]
Fixed in https://github.com/FirebaseExtended/flutterfire/pull/7549 - releasing later today
