### ISSUE TITLE
[firabase_database] setPersistenceEnabled(true) not working in offline app restarts- firebase realtime database

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#758]
I am using a firebase animated list to show a list of items stored in firebase realtime database.

Now when I start the app(after the app is **killed/terminated**) in the **offline** state, the list does not load.

Persisted to on-device (using setPersistenceEnabled(true)) should survive a terminated app.

I am using latest plugin [firebase_database: "^1.0.1"]

**Comment by kroikie** [comment]
@Apurv2017

The issue at https://github.com/flutter/flutter/issues/19271 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by robindijkhof** [comment]
Probably the same as #885

**Comment by Ehesp** [comment]
Closing in favour of https://github.com/FirebaseExtended/flutterfire/issues/885 which has more details and examples.
