### ISSUE TITLE
🐛 [Flutter_message] The iPhoneX sometimes doesn't get notifications

### ISSUE THREAD

**Issue by paintingStyle** [FirebaseExtended/flutterfire#7583]
## Bug report

**Describe the bug**

On iOS and iPhoneX devices, I find that notifications occasionally don't get received, but sometimes they do. When I tested the Cloud Messaging function, everything worked. How do I check for this problem? 
Looking forward to your reply. 

Thank you

flutter 2.5.3
iOS15.1
The latest plug-in version

**Comment by darshankawar** [comment]
@paintingStyle 
Does all streams such as  [FirebaseMessaging.onMessage, FirebaseMessaging.onBackgroundMessage, FirebaseMessaging.onMessageOpenedApp] trigger properly and everytime ? Can you add trace information to each handler to see which one is invoked everytime and which isn't ? 

Also, you just provided description of the issue without any code or logs, so it's tough to exactly help on what could be the issue. Did you also confirm if your messaging setup for ios is proper as per the [documentation](https://firebase.flutter.dev/docs/messaging/overview/#4-apple-integration) ?
