### ISSUE TITLE
flutterfire demo code outdated

### ISSUE THREAD

**Issue by sheldon-hodo** [FirebaseExtended/flutterfire#7586]
from 
https://firebase.flutter.dev/docs/ui/auth/integrating-your-first-screen

there is a code snippet as following:

```
`import 'package:firebase_auth/firebase_auth.dart';

class AuthGate extends StatelessWidget {
  const AuthGate({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<FirebaseUser?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // ...
      },
    );
  }
}`
```

which had an error prompt in my IDE. After research I found type  FirebaseUser has been renamed to User in firebase_auth 0.18.0.

**Comment by darshankawar** [comment]
The current link from the documentation seem to be using correct version, ie `User`:

<img width="488" alt="Screenshot 2021-12-14 at 5 54 03 PM" src="https://user-images.githubusercontent.com/67046386/145997731-55efcbfe-0ba3-441a-83b6-abb87873cd41.png">

https://firebase.flutter.dev/docs/ui/auth/integrating-your-first-screen/#checking-authentication-state

Closing this as fixed already.
