### ISSUE TITLE
🐛 [google_sign_in] Can't build on M1 mac after upgrading to flutter 2.8

### ISSUE THREAD

**Issue by Alverd04** [FirebaseExtended/flutterfire#7587]
## Bug report

**Describe the bug**
Since updating to flutter 2.8 and trying to upgrade i'm receiveing the following error:
```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/albertfont/my-event-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment
    target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.0.99. (in target 'AppAuth' from project 'Pods')
    /Users/albertfont/my-event-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment
    target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target
    versions is 9.0 to 15.0.99. (in target 'GoogleSignIn' from project 'Pods')
    /Users/albertfont/my-event-app/ios/Runner.xcodeproj: error: The linked framework
    'Pods_Runner.framework' is missing one or more architectures required by this target: x86_64. (in
    target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 13.
```

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by sheldon-hodo** [comment]
having the exactly same issue

**Comment by Alverd04** [comment]
@sheldon-hodo  It's due to google_sign_in dependency, i think it's not yet migrated to flutter 2.8 and it's causing issues in iOS M1 simulator.

**Comment by mrmko** [comment]
Same issue here, found a workaround for now...

https://github.com/flutter/flutter/issues/94914#issuecomment-992898782

**Comment by Alverd04** [comment]
I'll let you know if it worked!

**Comment by darshankawar** [comment]
@Alverd04 
`google_sign_in` plugin issues should be reported in `flutter/flutter repo and I see you've already filed the same there: https://github.com/flutter/flutter/issues/95206
Closing from here, as this plugin isn't maintained / tracked in this repo.
