### ISSUE TITLE
📚 [flutterfire_ui] sign-in example code 

### ISSUE THREAD

**Issue by finsdad** [FirebaseExtended/flutterfire#7588]
The SignInScreen widget doesn't want some of the parameters provided ... like 'actions'

**Comment by lesnitsky** [comment]
@finsdad what version of `flutterfire_ui` are you using? Reproducible example demonstrating the issue would be also nice to have

**Comment by darshankawar** [comment]
@finsdad 
Can you elaborate on what exactly the issue you are facing ? Also provide a code sample per above comment to properly address this issue.
Thanks.
