### ISSUE TITLE
FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by Cedriccool** [FirebaseExtended/flutterfire#7599]
### [REQUIRED] Environment info

**firebase-tools:** 9.23.0

**Platform:** macOS & Windows

### [REQUIRED] Actual behavior

Hi all,

I cant figure out to configure the new firebase in my flutter app.
Everytime i run **"flutterfire configure"** I end up with:
FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.

**I run that command at the root of my project ( same location than a flutter run & cie ) but I've also tried in lib, android, ios... just to be sure**

Firebase CLI has been installed fine, 
**firebase projects:list is working good, I can list all the projects of my account.**

As I work with a remote SSH to a Mac, I've also installed everything on my Windows, and I get the same error.

flutter doctor -v has absolutely no errors.

I've tried also a "flutter create ." to check if I missed some files, but still the same problem!
Except that, my app is working fine! I can run on simulators, real android devices, and compile for Stores!

Thanks in advance

**Comment by Salakar** [comment]
See https://github.com/invertase/flutterfire_cli/issues/12 - this was fixed in a later version of the CLI - please update.
