### ISSUE TITLE
🐛 [flutterfire_ui] Problem using 2 Firebase App instances with new UI widgets

### ISSUE THREAD

**Issue by rkemr** [FirebaseExtended/flutterfire#7615]
## Bug report

**Describe the bug**
When using the **flutterfire_ui** plugin's **SignInScreen** widget with a _secondary_ Firebase App instance to that of the main application (we have 2 Firebase configs - one for the main app and another for authentication purposes), and passing the secondary instance via the widget's `auth` parameter the sign in attempt fails with (Android):

![image](https://user-images.githubusercontent.com/16881620/146236514-516ea7f8-067c-46bd-91ff-3f959ebe378e.png)

The same error happens when targeting Web instead of Android.

### Steps to reproduce

Use the SignInScreen widget as described in documentation but passing a specific FirebaseAuth instance, e.g. 

`SignInScreen(
            auth: context.select((LoginController n) => n.FirebaseAuthInstance),
            providerConfigs: const [
              EmailProviderConfiguration(),
            ],
          ),`

### Expected behavior

The sign in works normally and the user is logged in.

---

## Additional context

In addition if I call the **signInWithEmailAndPassword** method directly on our FirebaseAuth instance it works OK. 

(this method: https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/signInWithEmailAndPassword.html)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.0)
[✓] VS Code (version 1.55.0-insider)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  http: ^0.13.4
  provider: ^6.0.1
  qr_code_scanner: ^0.6.1
  flutterfire_ui: ^0.2.0+2
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. Using the plugin official example and then trying to add a secondary firebase app in `SignInScreen` widget, throws the same error as mentioned above.

Also note that, since this is recently implemented plugin, it must currently be supporting only the default firebase app. Hopefully, support for secondary firebase app will be added soon.
