### ISSUE TITLE
Firebase Crashlytics iOS setup

### ISSUE THREAD

**Issue by alexaung** [FirebaseExtended/flutterfire#7616]
From Xcode, select Runner from the project navigation.
Select the Build Phases tab, then click + > New Run Script Phase.
Add the following to the Type a script... text box underneath the Shell property:

`$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase --validate -ai <googleAppId>
 $PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase -ai <googleAppId>`

If I add these two line in text box, I can't build or run the ios project. If I take out these two line, project is successfully build.

**Comment by darshankawar** [comment]
@alexaung 
What error does xcode throw when you add those lines ?

**Comment by alexaung** [comment]
I got following errors

Showing Recent Messages
/Users/aungmyooo/Library/Developer/Xcode/DerivedData/Runner-ehbtgfrwszowthgqyvfzuynymnrk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-B8558ECE276B549E00A69545.sh: line 2: syntax error near unexpected token `newline'


Showing Recent Messages
/Users/aungmyooo/Library/Developer/Xcode/DerivedData/Runner-ehbtgfrwszowthgqyvfzuynymnrk/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-B8558ECE276B549E00A69545.sh: line 2: `$PODS_ROOT/FirebaseCrashlytics/upload-symbols --build-phase --validate -ai <googleAppId>'

**Comment by alexaung** [comment]
Ok, my mistake. I need to replace <ggogleAppId> including <>
