### ISSUE TITLE
[📚] How do get null or exception when working offline?

### ISSUE THREAD

**Issue by itaishalom** [FirebaseExtended/flutterfire#7619]
Hi all.
I have the following code: 

`  try {

      result = await FirebaseFirestore.instance

          .collection(

              'some_collection')

          .orderBy('createdAt', descending: true)

          .get();

    } on Exception catch (e, s) {

      logger.e('getInitialMessages:: chat error', e, s);

      return [];

    }`

So it happens that result.size is zero when there is no internet connection (I disabled the cache for that matter).
How can I distinct a case where the query was successful and the collection size is indeed zero and the case where there is no internet connection (or any other strange issue) and the query fails?

**Comment by darshankawar** [comment]
@itaishalom 
Check [this](https://firebase.flutter.dev/docs/firestore/usage/#access-data-offline) documentation and see if it helps to answer your question.

**Comment by itaishalom** [comment]
Not sure.
I have set persistenceEnabled: false on my app. In case the internet is down, the query returns with a result size of zero but no I found out that result.metadata.isFromCache is true in that case.
I don't understand why? I have set it to false.
Shouldn't be any exception for that matter?

**Comment by itaishalom** [comment]
I must add - I found the above issue. I get result from the cache after returning from the background.

**Comment by darshankawar** [comment]
@itaishalom 
Check [this](https://stackoverflow.com/a/63415042) SO answer and see if it helps.

**Comment by itaishalom** [comment]
No, this is not a good solution.
The solution is as follows: 
`try {
      
result = await FirebaseFirestore.instance

          .collection('messages')

          .orderBy('createdAt', descending: true)

          .get(GetOptions(source: Source.server));   // <--- This is important

    } on FirebaseException catch (e, s) {

      logger.e('Firebase chat error: ', e, s);

      switch (e.code) {

        case "permission-denied":

          return [];

        default:   //<--- You will get unavailable 

          return null;
      }
    }`

**Comment by bswhite1** [comment]
Out of curiosity, are you wanting to use the cache or expecting to turn it off? Do you have to use the document get or could you use a listen?

**Comment by itaishalom** [comment]
I turned it off, I do not want to use cache, only server.
If the cache is on - I get wrong results - i get most of the time empty list, or the last document.
I use now the Server only option and now I get this exception.
It only happens when app comes back from background to foreground!
I use get just because I want to get all the current documents listed. 
I also use listen for further new documents.
The reason that I think our issues related is because of the strange behaviour that we encounter when app comes back from background. What do you think?

**Comment by darshankawar** [comment]
@itaishalom 
Regarding the `Service is currently unavailable` error you are getting, please follow-up in the discussion to know more about it: https://github.com/FirebaseExtended/flutterfire/discussions/5708
Also, where do we stand on your original issue description ?

**Comment by itaishalom** [comment]
I found out the adding "Server" to the get options will solve the issue.
