### ISSUE TITLE
[firebase_messaging]: IOS notification is removed automatically when the app goes in foreground

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#762]
When an incoming Firebase notification coming to my phone and the app is in background, the notification appears in Notification Center but when the app goes in foreground (I do not tap on notification) the notification is removed automatically from Notification Center as well as badge numbers.

I've used firebase_messaging: "^1.0.3" and I tried on physical device.
This strange behavior only happens on IOS but not on Android.

Someone can help me?

**Comment by kroikie** [comment]
@faspadaro

The issue at https://github.com/flutter/flutter/issues/19138 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by elgammalqa** [comment]
I'm facing same issue , did you get it solved ?

**Comment by edisonpagtakhan** [comment]
Any updates on this? Thanks!

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
