### ISSUE TITLE
How to add an ofl parameter when creating a link

### ISSUE THREAD

**Issue by LazyBaneling** [FirebaseExtended/flutterfire#7631]
I need to create link with ofl parameter described [here](https://firebase.google.com/docs/dynamic-links/create-manually), so that my links open correctly on the desktop.

Previously I used the method [shortenUrl](https://github.com/FirebaseExtended/flutterfire/issues/1978) to add it manually which has now been removed.

**Comment by darshankawar** [comment]
@LazyBaneling 
I think you'll need to ask this in the discussion thread https://github.com/FirebaseExtended/flutterfire/discussions/5587, as this is more of a feature request to be added to the plugin.
Closing from here.
