### ISSUE TITLE
[dynamic_link] Support for ofl parameter

### ISSUE THREAD

**Issue by LazyBaneling** [FirebaseExtended/flutterfire#7643]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/5587

<div type='discussions-op-text'>

<sup>Originally posted by **edisonpagtakhan** February 11, 2020</sup>
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to specify the `ofl` parameter in the dynamic link. This is helpful when the linked content does not have a web equivalent, thus we need to set a different URL for desktop users.

**Describe the solution you'd like**
Add a `desktopLink` for `DynamicLinkParameters`

**Additional context**
For reference: https://firebase.google.com/docs/dynamic-links/create-manually?authuser=0</div>

**Comment by darshankawar** [comment]
Originally logged [issue](https://github.com/FirebaseExtended/flutterfire/issues/1978) was closed and moved to discussion, but there weren't any updates in that thread, so keeping it open and labeling it as enhancement.

/cc @Salakar

**Comment by Chinmay-KB** [comment]
In the previous version of this package, the `shortenUrl()` took an `Uri`. We could just manually append the `ofl` like this 
```
final ShortDynamicLink shortDynamicLink = await DynamicLinkParameters.shortenUrl(Uri.parse(longLink.toString() + "&ofl=https://example.com"));
```
But the current version takes in a `DynamicLinkParameters` object, where there's no option of adding an `ofl`. Currently I am using version `3.0.2` of this package to get it done. I can work on adding this parameter to `DynamicLinkParameters` or any other way, after discussion.

**Comment by LazyBaneling** [comment]
> In the previous version of this package, the `shortenUrl()` took an `Uri`. We could just manually append the `ofl` like this
> 
> ```
> final ShortDynamicLink shortDynamicLink = await DynamicLinkParameters.shortenUrl(Uri.parse(longLink.toString() + "&ofl=https://example.com"));
> ```
> 
> But the current version takes in a `DynamicLinkParameters` object, where there's no option of adding an `ofl`. Currently I am using version `3.0.2` of this package to get it done. I can work on adding this parameter to `DynamicLinkParameters` or any other way, after discussion.

Yes! Exactly! I would be grateful.

**Comment by d3xt3r2909** [comment]
As I see there is already opened [PR](https://github.com/FirebaseExtended/flutterfire/pull/7796) for this one.
