### ISSUE TITLE
[cloud_firestore] Add 'read from cache first'

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#765]
I am currently using Cloud Firestore in an Index Cards app, the main issue with the implementation however is the Cloud Firestore performance under bad network conditions. 
In the case of no network connection Cloud Firestore seems to read data immediately from cache and the user experience remanins uninterrupted. 

In the case of a bad network connection though (read anything slower than 3G), the Cloud Firestore plugin seems to query 'fresh' data from the server first and not return any data until the query is finished, even though this might take more than 5000 ms for one collection that contains less than 10 documents.

This is why I would suggest adding a 'read from cache first' ability to the Cloud Firestore plugin, that allows for the display of cached data first while the server query is running in the background. This would allow for a much better user experience regardless of the network he is in.

**Comment by kroikie** [comment]
@stemuk

The issue at https://github.com/flutter/flutter/issues/19078 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This is now supported by providing a `Source` when fetching documents, you can specify the cache option.

**Comment by totalerex** [comment]
feature is not implemented, but issue closed (#19078 also), seriously?  
read carefully the title 'read from CACHE FIRST' - there is no such option in moment in the ` enum Source`
