### ISSUE TITLE
🐛 [firebase_core][CLI] A clean flutter (2.8) project won't initialise firebase correctly on physical device (iOS) and throws `Could not locate configuration file: 'GoogleService-Info.plist'.`

### ISSUE THREAD

**Issue by hazzo** [FirebaseExtended/flutterfire#7659]
## Bug report

**Describe the bug**
A clean flutter (2.8) project won't initialise firebase correctly on physical device (iOS), but yes on simulator.

### Steps to reproduce

1. `flutter create firebasetest`
2. `flutter pub add firebase_core`
3. `flutterfire configure` (configure firebase with cli)
4. Add following snippet to main file:
```dart
WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
```

### Expected behavior

Firebase should work out of the box in a clean flutter install with new Dart initialization.

---

## Additional context

Error when running project with `flutter run`

<details><summary>Click to see error</summary>

```bash
Running "flutter pub get" in firebase_test...
Launching lib/main.dart on Guido’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 5B7F2K8QVV
Running pod install...
Running Xcode build...
Xcode build done.                                           46.4s
Installing and launching...
(lldb) 2021-12-19 15:27:58.410129+0100 Runner[4500:812084] Warning: Unable to create restoration in progress marker file
8.9.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
Debug service listening on ws://127.0.0.1:55554/7f1RDtjnw_o=/ws
Syncing files to device Guido’s iPhone...
8.9.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
8.9.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
8.9.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'com.example.firebasetest'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```
</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] Connected device (1 available)
    ! Error: Guido’s iPhone is busy: Preparing the watch for development via Guido’s iPhone. Xcode will continue when Guido’s iPhone is finished. (code -10)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.0
Flutter SDK 2.8.0
firebase_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.0.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
```

</details>

---

**Comment by hazzo** [comment]
Thought my apple watch was interfering on build process but even powering it off and not showing flutter doctor device error (! Error: Guido’s iPhone is busy: Preparing the watch for development via Guido’s iPhone. Xcode will continue when Guido’s iPhone is finished. (code -10)) firebase core still does not work in a real device.

**Comment by hazzo** [comment]
There was an error on ios bundle id but even solving that I still get this error:

```bash
Launching lib/main.dart on Guido’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 5B7F2K8QVV
Running pod install...                                           1,582ms
Running Xcode build...                                          
Xcode build done.                                           10.9s
Installing and launching...                                     
(lldb) 2021-12-19 17:45:55.032453+0100 Runner[578:34899] Warning: Unable to create restoration in progress marker file
8.9.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
8.9.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
8.9.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Installing and launching...                                        20.2s
Syncing files to device Guido’s iPhone...                           65ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Guido’s iPhone is available at: http://127.0.0.1:51712/G-hU7maUJHE=/
The Flutter DevTools debugger and profiler on Guido’s iPhone is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51712/G-hU7maUJHE=/
```

**Comment by phamnhuvu-dev** [comment]
> A clean flutter (2.8) project won't initialise firebase correctly on physical device (iOS)

And in release mode

**Comment by hazzo** [comment]
Release mode does not show any logs as the ones before but firebase doesn't seems to work either because I added cloud messaging and no notifications are received. What I mean is, error logs in release mode not showing does not seem to translate to firebase working.

**Comment by kkoken** [comment]
I can confirmed that it still requires Manuel installation with flutter 2.8.1 & latest version of cli

**Comment by hazzo** [comment]
This is kind of annoying when the whole purpose of dart initialization is to avoid copying files for each platform and adding build time scripts for flavor usage.

**Comment by darshankawar** [comment]
I am able to replicate this using the steps mentioned in the issue description using `flutterfire_cli` tool. Using previous method, there isn't any issue.

Get this error upon trying to run on iOS device: `[Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.`

@hazzo Since this issue occurs using the CLI tool, I think you'll also need to report the same in dedicated repo: https://github.com/invertase/flutterfire_cli/issues


/cc @Salakar

**Comment by Salakar** [comment]
Could you show me where it's throwing this error - I only see information logs here which is to be expected since there is no `plist` file, which is fine

**Comment by hazzo** [comment]
Hmmm I added Cloud Messaging and I don't receive any notifications at all and APN error is given. Also this logs don't show on a simulator so I'm not sure if it's really working on a physical device.

**Comment by Salakar** [comment]
> Hmmm I added Cloud Messaging and I don't receive any notifications at all and APN error is given. Also this logs don't show on a simulator so I'm not sure if it's really working on a physical device.

Messaging issue is unrelated, there's a fix for it here #7610 that will be shipped soon.

**Comment by hazzo** [comment]
So maybe you can guide me on a way to test that firebase core is working and guarantee that it's initialised even Info.plist google service file is not found.

**Comment by Salakar** [comment]
> So maybe you can guide me on a way to test that firebase core is working and guarantee that it's initialised even Info.plist google service file is not found.

Your original code didn't throw a Dart exception right? So it has initialised, e.g. can print out the default app after to make sure it's there now.

```dart
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print(Firebase.app());
  print(Firebase.app().name);
  print(Firebase.app().options);
```

**Comment by hazzo** [comment]
This are the logs shown (I replaced sensitive data with ###). This means it's working? So FCM not working it's just another issue?

```
flutter: FirebaseApp([DEFAULT])
flutter: [DEFAULT]
flutter: {apiKey: #####################, appId: ###############, messagingSenderId: ########, projectId: #######, authDomain: null, databaseURL: null, storageBucket: #######.appspot.com, measurementId: null, trackingId: null, deepLinkURLScheme: null, androidClientId: null, iosClientId: ##############.apps.googleusercontent.com, iosBundleId: com.#####.###, appGroupId: null}
```

**Comment by Salakar** [comment]
> This are the logs shown (I replaced sensitive data with ###). This means it's working? So FCM not working it's just another issue?

Yep, correct, it's working and FCM is another issue

**Comment by hazzo** [comment]
Okey thanks for your help. Maybe avoiding to log this kind of messages could avoid to misleading interpretations and future open issues. Also any ideas when FCM fix will be rolled out?

 @darshankawar I'll close this issue since the log given does not reflect the actual state of firebase initialisation.

**Comment by hazzo** [comment]
Dart initialisation is kind of buggy I found another issue: [7752](https://github.com/FirebaseExtended/flutterfire/issues/7752)
