### ISSUE TITLE
[firebase_messaging 📚] Inconsistency between the documentation and the example

### ISSUE THREAD

**Issue by atoka93** [FirebaseExtended/flutterfire#7669]
This step: https://firebase.flutter.dev/docs/messaging/usage/#web-tokens under 2. describes that `firebase-messaging-sw.js` should be created and included into `index.html`.
The example has nothing like that: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/web/index.html

Is it not required anymore with the latest automatic initialization? or is this an oversight?

Should I open a pull request to fix this or that?

**Comment by atoka93** [comment]
Created the issue accidentally before adding the description, should be correct now.

**Comment by atoka93** [comment]
I think
```html
  <!-- ...other html setup. -->
  <script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
        navigator.serviceWorker.register("/firebase-messaging-sw.js");
      });
    }
  </script>
  <!-- ...put the script at the bottom of the enclosing body tags. -->
</body>
```
is not required but the `web/firebase-messaging-sw.js` file is, so the example is correct.

**How I came to this conclusion:**
I added the script tag from above but changed the path and the filename ("/firebase-messaging-sw.js").
This resulted in the following error:
```
Error: [firebase_messaging/failed-service-worker-registration] Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:57181/firebase-cloud-messaging-push-scope') with script ('http://localhost:57181/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). .
    at Object.throw_ [as throw] (http://localhost:57181/dart_sdk.js:5063:11)
    at http://localhost:57181/packages/firebase_core/src/internals.dart.lib.js:81:63
    at _RootZone.runUnary (http://localhost:57181/dart_sdk.js:40062:59)
    at _FutureListener.catchError.handleError (http://localhost:57181/dart_sdk.js:34996:33)
    at handleError (http://localhost:57181/dart_sdk.js:35567:51)
    at Function._propagateToListeners (http://localhost:57181/dart_sdk.js:35593:17)
    at _Future.new.[_completeError] (http://localhost:57181/dart_sdk.js:35443:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57181/dart_sdk.js:35479:31)
    at Object._microtaskLoop (http://localhost:57181/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:57181/dart_sdk.js:40336:13)
    at http://localhost:57181/dart_sdk.js:35811:9
```
The error persisted even after removing the script tag.
The error was solved after moving the file to specified path and using the specified name.

**Comment by darshankawar** [comment]
@atoka93 
Check [this](https://github.com/FirebaseExtended/flutterfire/issues/5515) issue and see if it helps.

**Comment by atoka93** [comment]
@darshankawar everything is working for me, the issue is about documentation.

In the example project neither this
```html
  <!-- ...other html setup. -->
  <script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
        navigator.serviceWorker.register("/firebase-messaging-sw.js");
      });
    }
  </script>
  <!-- ...put the script at the bottom of the enclosing body tags. -->
</body>
```
shown here: https://firebase.flutter.dev/docs/messaging/usage/#web-tokens

nor this
```html
  <!-- ...other html setup. -->
  <script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
        navigator.serviceWorker.register("/firebase-messaging-sw.js");
      });
    }
  </script>
  <!-- ...put the script at the bottom of the enclosing body tags. -->
</body>
```
shown here under the `Web` tab https://firebase.flutter.dev/docs/messaging/usage/#background-messages

is not included.

Neither in my project and both are working correctly for me.

My question is: is that part actually required?
- if yes the example project (and my project) should be updated
- if not the documentation should be updated

Does that make sense?

**Comment by darshankawar** [comment]
Yes, thanks for the update.

**Comment by russellwheatley** [comment]
Hey @atoka93, good catch! I've updated the example 👍
