### ISSUE TITLE
🐛 [Firebase/Messaging] Rich Notification - Notification service extension not called on flutter iOS

### ISSUE THREAD

**Issue by vijay-subramani** [FirebaseExtended/flutterfire#7674]
Issue:- When getting remote notification have to show image using the imageurl in payload. In Android it’s working fine once we changed the payload. In iOS image not showing in push notification.

Issue facing on Notification Service Extension:- I have added the notification extension and added the code for modifying notification content. This configuration is working fine in native iOS app.

Added the same in the flutter iOS project but there it won’t work. While receiving push notification the extension is not getting called. Just receiving normal notification only. I have tried many scenarios to sort out this issue. Still it’s not working.

Steps i’ve followed:

Added code to get notification permission
Added Notification extension to the project
Used automatically manage signing for profile configuration
Added code to modify notification
Added imageURL and mutable-content keys in payload

Added the project and payload screenshots here
<img width="1411" alt="Screenshot 2021-12-21 at 2 04 34 PM" src="https://user-images.githubusercontent.com/32050235/147039805-d9d299f5-334c-4bc6-83c1-b57de0d8dd18.png">

Payload
<img width="1019" alt="Screenshot 2021-12-21 at 2 01 49 PM" src="https://user-images.githubusercontent.com/32050235/147039852-f5bfe418-e33e-4a8a-9898-227b77218eb3.png">

Expected results:

Notification with Image
![IMG_1056](https://user-images.githubusercontent.com/32050235/147039903-67ee15b2-5e77-4e1a-ae1b-5a0ec8a78c84.PNG)

Actual results:
getting normal push notification only
![IMG_1060](https://user-images.githubusercontent.com/32050235/147039977-1575d0ed-a608-493d-8357-a6654e644a93.PNG)

**Comment by darshankawar** [comment]
@vijay-subramani 
Assuming you have already followed the steps properly to set up image notifications per [document](https://firebase.flutter.dev/docs/messaging/apple-integration/#advanced-optional-allowing-notification-images), but can you confirm that once ? 
Also, check [this](https://github.com/FirebaseExtended/flutterfire/issues/4133) open similar issue and underlying comments and see if they help.

**Comment by strmchsr** [comment]
@vijay-subramani  are you able to solve this issue?
