### ISSUE TITLE
[firebase_messaging] Add automatic increment of notification badge on app icon

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#768]
Currently, the server has to send the exact number using the API (nodejs, etc), but allow auto increment so we don't have to keep track of unread notification in the backend. i.e whenever theres a new notification, the number increments by 1.

![image](https://user-images.githubusercontent.com/10779355/42211691-027e4694-7e69-11e8-8c69-b3a1ab385832.png)

**Comment by kroikie** [comment]
@bigboateng

The issue at https://github.com/flutter/flutter/issues/19033 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by rafekun** [comment]
Does this mean that FCM now supports auto increment?

**Comment by kroikie** [comment]
@rafekun it is on our list of things to add.

**Comment by Alexfuse** [comment]
Are there any updates?

**Comment by lyseiha** [comment]
Any update?

**Comment by Ehesp** [comment]
Hey all - unfortunately Apple/iOS don't provide support for incrementing the badge count automatically. They only provide support for getting & setting the value, and leave it down to the developer to handle the badge value.

The Messaging plugin supports setting the badge count via the message payload sent from your server.

I'll leave this open to discuss, however I'm not convinced functionality to set/get the badge should exist in this plugin as it's not really the responsibility of FCM & depends heavily on your own integration. I'd see it being a better fit within the https://pub.dev/packages/flutter_local_notifications plugin

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin. Whilst it doesn't have any badge APIs it is compatible to be used with other local notification plugins that do provide badge APIs.

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin in combination with a local notifications plugin that does have badge APIs.

Thanks everyone.
