### ISSUE TITLE
[📚] [ODM] Some Relative MDX Links are nested incorrectly

### ISSUE THREAD

**Issue by ashtonthomas** [FirebaseExtended/flutterfire#7682]
I'm not familiar with mdx, but I've noticed some links in the docs nest incorrectly and lead to a 404 (but the pages exist and can be accessed browser by correcting the path in url)

Based on the pattern I see elsewhere in these docs, something like these changes seem appropriate
https://github.com/ashtonthomas/flutterfire/commit/c515c695f8c6e8dde40102309bee3e1ba82667f8

Was going to submit as PR but I just don't know enough about MDX or how these docs are generated or contribution guidelines

![2021-12-23_03-41-20 (1)](https://user-images.githubusercontent.com/53977/147215852-160525e0-30cb-49f9-8ce4-1257b78f3bbb.gif)

**Comment by ashtonthomas** [comment]
Ah, seems to have something to do with a trailing slash in URL. Not sure how we end up at different URL, maybe want to close this issue

```
https://firebase.flutter.dev/docs/firestore-odm/overview/
```

vs 

```
https://firebase.flutter.dev/docs/firestore-odm/overview
```

Having the trailing `/` seems to break some of the relative mdx links

**Comment by darshankawar** [comment]
Closing this as not an issue and per above comment.
