### ISSUE TITLE
[flutterfire_ui] AppleProviderConfiguration has no clientId parameter

### ISSUE THREAD

**Issue by maupleke** [FirebaseExtended/flutterfire#7690]
Providers section on documentation (https://firebase.flutter.dev/docs/ui/auth/configuring-providers/#apple) cites a clientId parameter for AppleProviderConfiguration but there isn't one on 0.3.0

sample snippet:
```
RegisterScreen(
  providerConfigs: [
    AppleProviderConfiguration(
      clientId: '...',
    )
  ],
)
```

**Comment by darshankawar** [comment]
> but there isn't one on 0.3.0

@maupleke Which version are you referring here ?
