### ISSUE TITLE
[flutterfire_ui] : multi-query support to deal with Firestore 10 limit when using IN operator

### ISSUE THREAD

**Issue by azazadev** [FirebaseExtended/flutterfire#7698]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/7695

<div type='discussions-op-text'>

<sup>Originally posted by **azazadev** December 24, 2021</sup>
it's possible to support `List<Query>` in `FirestoreListView` to WA Firestore 10 limit when using IN operator ?

**_Feature description_**

Take this example

```
collections :

posts 
	- id
	- message
	- date
	- userId
	- ...
	- ...

users :
	- userId
	- name
	- ...
	- ...

```

**scenario** : user have 100 friends

**Expected** : FirestoreListView with all posts of 100 friends

below code will not work due to Firestore 10 limit when using IN operator

```
final postsQuery = FirebaseFirestore.instance.collection('posts').Where("userId", "in", friends (list of 100 ids ))

FirestoreListView<Map<String, dynamic>>(
  query: postsQuery,
  itemBuilder: (context, snapshot) {
   ...
   ...
  },
);
```

**Possible WA :** 

```
// Split 100 users in list of 10 
final postsQuery1 = FirebaseFirestore.instance.collection('posts').Where("userId", "in", friends (list of 10 ids ))
final postsQuery2 = FirebaseFirestore.instance.collection('posts').Where("userId", "in", friends (list of 10 ids ))
final postsQuery3 = FirebaseFirestore.instance.collection('posts').Where("userId", "in", friends (list of 10 ids ))
...
final postsQuery10 = FirebaseFirestore.instance.collection('posts').Where("userId", "in", friends (list of 10 ids ))

FirestoreListView<Map<String, dynamic>>(
  queries: [postsQuery1,postsQuery2, ... postsQuery10],
  itemBuilder: (context, snapshot) {
   ...
   ...
  },
);
```</div>

**Comment by darshankawar** [comment]
@azazadev 
As mentioned in the document, any new feature request related to this plugin, need to be opened as a discussion. https://firebase.flutter.dev/docs/ui/overview/#roadmap--features
You may also ask this question in the open discussion [thread](https://github.com/FirebaseExtended/flutterfire/discussions/6978) (as linked in the document).
Closing from here, as enhancements and feature requests related to this plugin are tracked in discussion.
