### ISSUE TITLE
A problem occurred configuring project ':firebase_ml_vision'. > compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by JohanaBenabou** [FirebaseExtended/flutterfire#7700]

**Comment by darshankawar** [comment]
firebase_ml_vision is deprecated from flutterfire plugins library. so you should just remove it.
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision
Closing from here.
