### ISSUE TITLE
🐛 [firebase_core_web] _ignoredServiceScripts crashes

### ISSUE THREAD

**Issue by sgehrman** [FirebaseExtended/flutterfire#7701]
context['flutterfire_ignore_scripts'] is null, so this crashes

 List<String> get _ignoredServiceScripts {
    try {
      JsObject ignored =
          JsObject.fromBrowserObject(context['flutterfire_ignore_scripts']);   < -- crash

Should it be JsObject? ignored  = ...

**Comment by darshankawar** [comment]
@sgehrman 
Can you provide us a minimal code sample that shows the crash along with `flutter doctor -v` ?
