### ISSUE TITLE
🐛 [FLUTTER_MESSAGING] Notification icon does not change

### ISSUE THREAD

**Issue by Gercov** [FirebaseExtended/flutterfire#7704]
I am trying to change the notification icon to my custom one by adding meta tags to the manifest.
![image](https://user-images.githubusercontent.com/51914212/147406435-c67a4992-be60-40c4-aa63-6e5572563e4b.png);
But it doesn't work and I get this:
![telegram-cloud-photo-size-2-5350485187672258100-x](https://user-images.githubusercontent.com/51914212/147406453-b1fa9a84-1022-4f47-8fec-638e64d39dd9.jpg);

How can i fix this?
firebase_core: ^1.10.6
firebase_messaging: ^11.2.4

**Comment by darshankawar** [comment]
@Gercov 
Check [this](https://medium.com/nonstopio/change-the-firebase-notification-icon-in-a-flutter-245b7f7dc546) document and see if it helps.
If not, provide `flutter doctor -v` and manifest.xml in text format.

**Comment by Gercov** [comment]
> @Gercov Check [this](https://medium.com/nonstopio/change-the-firebase-notification-icon-in-a-flutter-245b7f7dc546) document and see if it helps. If not, provide `flutter doctor -v` and manifest.xml in text format.

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.mloyalty_app">
   <uses-permission android:name="android.permission.INTERNET"/>
   <application
        android:label="mloyalty"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="false"
        android:fullBackupContent="false">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="com.google.firebase.messaging.default_notification_icon"
              android:resource="@drawable/icon" />
            <meta-data
              android:name="com.google.firebase.messaging.default_notification_color"
              android:resource="@color/colorPrimary" />
            <meta-data android:name="com.google.android.gms.version"
                android:value="@integer/google_play_services_version" />
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <queries>
      
      <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="https" />
      </intent>
      
      <intent>
        <action android:name="android.intent.action.DIAL" />
        <data android:scheme="tel" />
      </intent>
      
      <intent>
        <action android:name="android.intent.action.SENDTO" />
        <data android:scheme="smsto" />
      </intent>
      
      <intent>
        <action android:name="android.intent.action.SEND" />
        <data android:mimeType="*/*" />
      </intent>
    </queries>
</manifest>

[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale ru-RU)
    • Flutter version 2.8.0 at /Users/aleksandr/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aleksandr/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31)
      (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Thanks for the info @Gercov, Your android XML looks fine to me do you have a icon drawable setup?

>  \<meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@drawable/icon" />
               
Additionally, you may try setting the launcher icon to understand if that's an issue with asset or asset path `android:resource="@mipmap/ic_launcher"`

Please see if this helps https://github.com/flutter/flutter/issues/17941#issuecomment-412242466

**Comment by Gercov** [comment]
@maheshmnj
I tried to specify the mipmap path, but it didn't work either

I didn't quite understand about the setup of the icon. It lies in res/drawable

**Comment by Gercov** [comment]
@maheshmnj 
raising to a higher level really helped, thanks a lot

**Comment by maheshmnj** [comment]
> @maheshmnj
raising to a higher level really helped, thanks a lot

Was this resolved? If yes could share what fixed it?

**Comment by Gercov** [comment]
@maheshmnj 
Notification icon meta-tag should be in <application />, not <activity />

**Comment by maheshmnj** [comment]
Thanks for the info Closing as solved
