### ISSUE TITLE
Firebase Dynamic Links not working on Flutter iOS installed app.

### ISSUE THREAD

**Issue by ovidiudvaro** [FirebaseExtended/flutterfire#7730]
The problem is on iOS - If the app is installed - when the dynamic link is clicked the app is not going to open (the App Store will open) and when opening the app via Open button from App Store the FirebaseDynamicLinks.instance.onLink() not received.

In Android everything works as expected.

In iOS if the app is not installed everything works as expected.

Here you can find my implementation.
<img width="636" alt="Screenshot 2021-12-29 at 12 16 49" src="https://user-images.githubusercontent.com/29095440/147651862-acc52624-10f9-4010-9d12-6ea016d9bc26.png">

**Comment by darshankawar** [comment]
@ovidiudvaro 
Check if [this](https://github.com/FirebaseExtended/flutterfire/issues/7546) open issue sounds similar to your case.
