### ISSUE TITLE
🐛 [cloud_firestore] flutter mobile devices (Android and iOS) don't seem to be connecting to firestore emulator when using useFirestoreEmulator

### ISSUE THREAD

**Issue by troyshu** [FirebaseExtended/flutterfire#7732]
## Bug report

**Describe the bug**
Flutter mobile app (Android or iOS) when run on a device (update: looks like this issue is also happening when I run the app via iOS and Android simulators) unable to read from or write to local Firebase Firestore _emulator_ even when Firestore emulator is running.

### Steps to reproduce

0. Create a Flutter app
1. Install Firebase core and Flutterfire according to https://firebase.flutter.dev/docs/overview
2. Follow steps to enable use of Firebase emulator suite [iOS](https://firebase.flutter.dev/docs/manual-installation/ios#enabling-use-of-firebase-emulator-suite) and [Android](https://firebase.flutter.dev/docs/manual-installation/android#building-for-android)
3. Install Firestore and [enable emulator usage in the Flutter app](https://firebase.flutter.dev/docs/firestore/usage#emulator-usage) with `FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);`
4. Ensure Firestore emulator is running locally at default port 8080 e.g. with `firebase emulators:start` 
5. Follow example [here](https://firebase.flutter.dev/docs/firestore/usage#one-time-read) to do a simple read
6. Build and run Flutter mobile app on a device in VSCode

When run on an Android device, the Flutter logs show 
```
(24.0.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
(24.0.0) [WatchStream]: (4c9091f) Stream closed with status: Status{code=UNAVAILABLE, description=Channel shutdownNow invoked, cause=null}.
```

### Expected behavior

I expect the data to be read successfully especially if the collection and document already exist in the local Firestore emulator.

### Sample project

[Toy project to reproduce](https://github.com/troyshu/flutter-firestore-emulator-example)

---

## Additional context

Firebase emulators set up locally with default settings.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0
Flutter SDK 2.5.0
flutter_firestore_example 1.0.0+1

dependencies:
- cloud_firestore 3.1.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.10 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.5 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.0.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by troyshu** [comment]
I closed the issue temporarily because I was fixing the description. Re-opened as I'm still having this issue.

**Comment by darshankawar** [comment]
@troyshu 
The error you are getting:

`[OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.` seem to have to do with the wifi connection.
See this discussion thread for the same topic and error, https://github.com/FirebaseExtended/flutterfire/discussions/5546 which may not be coming from the flutterfire plugins, but from native firebase. 
I suggest you to follow-up in the discussion and underlying comments from it to see if any of them helps.
Closing from here as as duplicate.

**Comment by troyshu** [comment]
Thanks for pointing me in the right direction @darshankawar.

I found a solution to my issue, posted my findings [here](https://github.com/FirebaseExtended/flutterfire/discussions/5546#discussioncomment-1887990)
