### ISSUE TITLE
🐛 [flutterfire_ui] Recover from `AuthFailed` with `AuthAction.link` / "credential-already-in-use"

### ISSUE THREAD

**Issue by jeanmatthieud** [FirebaseExtended/flutterfire#7736]
## Bug report
* Sign-in as anonymous user (`FirebaseAuth.instance.signInAnonymously()`)
* Link with Google Provider, with an previously linked account (`OAuthProviderButton` with action as `link`)
* It fails, with 'credential-already-in-use' as error (you can catch it with a custom action `AuthStateChangeAction<AuthFailed>`)

I want to use the FirebaseAuthException.credentials to switch from the existing anonymous user to the exitsing user.
I can do that with `FirebaseAuth.instance.signInWithCredential(err.credential)`, but how can we resume the OAuthFlow (which should call `AuthStateChangeAction<CredentialLinked>` callback) ?

From AuthFlow:
```dart
Future<void> onCredentialReceived(AuthCredential credential) async {
    late AuthState finalState;
    try {
      switch (action) {
        [...]
        case AuthAction.link:
          value = CredentialReceived(credential);
          await link(credential);
          finalState = CredentialLinked(credential);
          break;
        default:
        [...]
      }

      // value will not be set after an error, even if we recover from it
      if (value is! AuthFailed) {
        value = finalState;
      }
    } on Exception catch (err) {
      value = AuthFailed(err);
    }
  }

  @override
  Future<void> link(AuthCredential credential) async {
    final user = auth.currentUser;

    if (user != null) {
      try {
        await user.linkWithCredential(credential);
      } on Exception catch (err) {
        // I don't see how we can recover from here
        value = AuthFailed(err);
      }
    } else {
      throw Exception(
        "Can't link the credential: no user is currently signed in",
      );
    }
  }
```

**Comment by darshankawar** [comment]
@jeanmatthieud 
I think this question as how to recover from `AuthFailed` should be part of the discussion thread here https://github.com/FirebaseExtended/flutterfire/discussions/6978, so please ask the same there.
Closing from here.
If you disagree, write in comments and I'll reopen it.
Thanks.
