### ISSUE TITLE
📚 Improvement - Count the Size of a Document inside Cloud Firestore

### ISSUE THREAD

**Issue by gOzaru** [FirebaseExtended/flutterfire#7740]
Okay, this issue is bugging me since 7 months ago.
Why is it that Firebase doesn't provide any documentation about how to count the size of a Document inside a Cloud Firestore automatically up until now? Firebase docs said that the limit of a Document is 1 MiB or at least 1,048,576 bytes. They never said any ways to count the size in this documentation link automatically - [Storage Size](https://firebase.google.com/docs/firestore/storage-size)

**What is the purpose of creating that documentation?**

I really wanna file a complaint, actually.
But I know I will lose a lot of time and money in order to set this issue straight. 
How come there are not any documentation about this in Firebase?
You told us how to count it by our own self in that link documentation, but you never provided us any library in order to help our job easier and much faster. 

If I have power, I am gonna sue this company. 
But, never mind.
I have wasted my whole time for 7 months only to found out that Firebase never created any library to help their clients to count the Document's size. I must redesign my entire Firebase for this project. It has a lot of data inside. 
D***, you!

Solution:
I found out a way from Google Search, and found this guy who found a way to count a size of Firestore Document.
Check his library in [Github](https://github.com/alexmamo/FirestoreDocument-Android/tree/master/firestore-document). 
Thanks to his job, I can finally count the size and it will save a lot of budget in the future for multi-million transactions. I am gonna reward him for sure. 

In marketing perspective: 
This is an absolute way to increase the bill of clients. 

In programmer perspective:
This is a waste of time.

**Comment by russellwheatley** [comment]
This library is just a wrapper around the native SDKs, if you have a question/issue you wish to file, you should ask Firebase directly which you can do [here](https://firebase.google.com/support) at Firebase support.
