### ISSUE TITLE
🐛 [firebase_auth] flutterfire_ui:SignInScreen - Twitter authentication not possible (Android)

### ISSUE THREAD

**Issue by sentd94** [FirebaseExtended/flutterfire#7744]
## Bug report

No redirection back to the app after authorizing accesss to the twitter account from the app. 
Instead the redirect URL ([project].firebaseapp.com) in the web browser states:

[project].firebaseapp.com states:

> Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared

### Steps to reproduce

1. Create a twitter app (https://developer.twitter.com/)
2. Setup twitter as a sign-in method in Firebase Auth using the API key and API secret from step 1.
3. Retrieve the firebase callback URL provided from step 2: https://[yourProjectId].firebaseapp.com/__/auth/handler
4. Add this as a child of `activity` to your `AndroidManifest.xml`:

```
             <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https://"
                        android:host="https://[yourProjectId].firebaseapp.com/__/auth/handler" />
            </intent-filter>
```
5. Add the SignInScreen widget to your flutter app:

```
SignInScreen(
                  auth: auth,
                  providerConfigs: const [
                    TwitterProviderConfiguration(
                        apiKey: [twitterAPIKey],
                        apiSecretKey: [twitterAPISecret],
                        redirectUri: "https://[yourProjectId].firebaseapp.com/__/auth/handler"),
                  ],
                )
```

6. Start the app
7. Click on the 'Sign in with Twitter' button of the `SignInScreen` widget. The webbrowser will open https;//api.twitter.com and ask you to authorize the app.
8. You will be redirected to: [project].firebaseapp.com with the following message:

> Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared

### Expected behavior

Be logged in with Firebase Auth und returned to the app.

**Comment by darshankawar** [comment]
@sentd94 
Can you try the steps mentioned in the [document](https://firebase.flutter.dev/docs/auth/social#twitter) and see if you still get the same behavior or not ?

**Comment by sentd94** [comment]
> @sentd94 Can you try the steps mentioned in the [document](https://firebase.flutter.dev/docs/auth/social#twitter) and see if you still get the same behavior or not ?

I used to use the `twitter_login` dependeny as mentioned in the document and it worked. 
But right now I'm trying to use the [SignInScreen widget](https://pub.dev/documentation/flutter_firebase_ui/latest/flutter_firebase_ui/SignInScreen-class.html) instead that has just been released to make this all easier.

**Comment by darshankawar** [comment]
@sentd94 
The Providers documentation for Twitter configuration does mention to use the `twitter_login` plugin: https://firebase.flutter.dev/docs/ui/auth/configuring-providers#twitter
So I think just follow the documentation for Twitter and see if it helps to implement it correctly.

**Comment by sentd94** [comment]
@darshankawar Well you are right. All the videos announcing Flutter 2.8 made it sound like you just had to use the widget and it would do all the work for you.
