### ISSUE TITLE
🐛 [firebase_auth] FirebaseException: An internal error has occurred. [ Chain validation failed ]

### ISSUE THREAD

**Issue by viratshukla** [FirebaseExtended/flutterfire#7749]
## Bug report

**Describe the bug**
When I try to use this line to Anonymously, I am getting this error
"await FirebaseAuth.instance.signInAnonymously();"

Firebase Auth version used => firebase_auth: ^3.3.4

Error logs
----------

W/System  ( 5100): Ignoring header X-Firebase-Locale because its value was null.
E/flutter ( 5100): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ Chain validation failed ]
E/flutter ( 5100): #0      MethodChannelFirebaseAuth.signInAnonymously (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:423:7)
E/flutter ( 5100): <asynchronous suspension>
E/flutter ( 5100): #1      FirebaseAuth.signInAnonymously (package:firebase_auth/src/firebase_auth.dart:447:35)
E/flutter ( 5100): <asynchronous suspension>

**Comment by viratshukla** [comment]
flutter doctor --verbose
[✓] Flutter (Channel master, 2.6.0-12.0.pre.826, on macOS 12.0.1 21A559 darwin-x64, locale en-IN)
    • Flutter version 2.6.0-12.0.pre.826 at /Users/xxx/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c1455a23a (6 weeks ago), 2021-11-23 21:13:05 -0500
    • Engine revision 539239e256
    • Dart version 2.16.0 (build 2.16.0-42.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview copy.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by darshankawar** [comment]
@viratshukla 
You are on older version of master. Can you upgrade to latest master and try again to see if you still get the same error ?
If yes, can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example/lib) and see if using it, you get the same error or not ?

**Comment by viratshukla** [comment]
Well, I tried, now facing this issue [96711](https://github.com/flutter/flutter/issues/96711)

**Comment by darshankawar** [comment]
The issue you pointed has to do with updating package dependency, so if you haven't already tried upgrading the package, try that and see if it resolves.
