### ISSUE TITLE
🐛 [firebase_auth] File not found exception

### ISSUE THREAD

**Issue by viratshukla** [FirebaseExtended/flutterfire#7750]
## Bug report

**Describe the bug**
When tried to implement OTP verification of number using firebase_auth library, getting this error

```
I/art     (11675): Do partial code cache collection, code=30KB, data=27KB
I/art     (11675): After code cache collection, code=28KB, data=27KB
I/art     (11675): Increasing code cache capacity to 128KB
D/InputConnectionAdaptor(11675): The input method toggled cursor monitoring on
W/System  (11675): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth(11675): Notifying id token listeners about a sign-out event.
D/FirebaseAuth(11675): Notifying auth state listeners about a sign-out event.
D/FirebaseAuth(11675): Notifying id token listeners about a sign-out event.
D/FirebaseAuth(11675): Notifying auth state listeners about a sign-out event.
E/zzbf    (11675): SafetyNet Attestation fails basic integrity.
I/Choreographer(11675): Skipped 30 frames!  The application may be doing too much work on its main thread.
I/art     (11675): Do partial code cache collection, code=50KB, data=55KB
I/art     (11675): After code cache collection, code=50KB, data=55KB
I/art     (11675): Increasing code cache capacity to 256KB
I/zzdu    (11675): keyset not found, will generate a new one
I/zzdu    (11675): java.io.FileNotFoundException: can't read keyset; the pref value GenericIdpKeyset does not exist
I/zzdu    (11675): 	at com.google.android.gms.internal.firebase-auth-api.zzdy.zzc(com.google.firebase:firebase-auth@@21.0.1:10)
I/zzdu    (11675): 	at com.google.android.gms.internal.firebase-auth-api.zzdy.zza(com.google.firebase:firebase-auth@@21.0.1:1)
I/zzdu    (11675): 	at com.google.android.gms.internal.firebase-auth-api.zzaw.zzi(com.google.firebase:firebase-auth@@21.0.1:1)
I/zzdu    (11675): 	at com.google.android.gms.internal.firebase-auth-api.zzdt.zzi(com.google.firebase:firebase-auth@@21.0.1:1)
I/zzdu    (11675): 	at com.google.android.gms.internal.firebase-auth-api.zzdt.zzg(com.google.firebase:firebase-auth@@21.0.1:2)
I/zzdu    (11675): 	at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@21.0.1:7)
I/zzdu    (11675): 	at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@21.0.1:3)
I/zzdu    (11675): 	at com.google.firebase.auth.internal.RecaptchaActivity.zzb(com.google.firebase:firebase-auth@@21.0.1:9)
I/zzdu    (11675): 	at com.google.android.gms.internal.firebase-auth-api.zztr.<init>(com.google.firebase:firebase-auth@@21.0.1:13)
I/zzdu    (11675): 	at com.google.firebase.auth.internal.RecaptchaActivity.onResume(com.google.firebase:firebase-auth@@21.0.1:43)
I/zzdu    (11675): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
I/zzdu    (11675): 	at android.app.Activity.performResume(Activity.java:6783)
I/zzdu    (11675): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
I/zzdu    (11675): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
I/zzdu    (11675): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
I/zzdu    (11675): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
I/zzdu    (11675): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
I/zzdu    (11675): 	at android.os.Handler.dispatchMessage(Handler.java:102)
I/zzdu    (11675): 	at android.os.Looper.loop(Looper.java:154)
I/zzdu    (11675): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
I/zzdu    (11675): 	at java.lang.reflect.Method.invoke(Native Method)
I/zzdu    (11675): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
I/zzdu    (11675): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
W/System  (11675): Ignoring header X-Firebase-Locale because its value was null.
D/EGL_emulation(11675): eglMakeCurrent: 0xa8be8360: ver 3 0 (tinfo 0x9557b880)
W/IInputConnectionWrapper(11675): finishComposingText on inactive InputConnection

```

**Comment by viratshukla** [comment]
Firebase Auth version used => firebase_auth: ^3.3.4

**Comment by viratshukla** [comment]
flutter doctor --verbose
[✓] Flutter (Channel master, 2.6.0-12.0.pre.826, on macOS 12.0.1 21A559 darwin-x64, locale en-IN)
• Flutter version 2.6.0-12.0.pre.826 at /Users/xxx/Development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 6c1455a23a (6 weeks ago), 2021-11-23 21:13:05 -0500
• Engine revision 539239e256
• Dart version 2.16.0 (build 2.16.0-42.0.dev)
• DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /Users/xxx/Library/Android/sdk
• Platform android-31, build-tools 30.0.3
• ANDROID_HOME = /Users/xxx/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• CocoaPods version 1.10.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
• Android Studio at /Applications/Android Studio Preview copy.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
✗ Unable to find bundled Java version.
• Try updating or re-installing Android Studio.

[!] Android Studio
• Android Studio at /Applications/Android Studio Preview.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
✗ Unable to find bundled Java version.
• Try updating or re-installing Android Studio.

[✓] Android Studio (version 2020.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
• IntelliJ at /Applications/IntelliJ IDEA CE.app
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
• sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)
• Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by viratshukla** [comment]
Although operation was successful, but this error got generated in logs

**Comment by darshankawar** [comment]
@viratshukla 
Same as https://github.com/FirebaseExtended/flutterfire/issues/7749#issuecomment-1003994539.
Also check this similar issue reported and fixed. https://github.com/FirebaseExtended/flutterfire/issues/4651 and see the solutions mentioned in it.
