### ISSUE TITLE
[📚] Firebase auth, Google Sign in and Dart initialization. GoogleService-Info.plist needed?

### ISSUE THREAD

**Issue by hazzo** [FirebaseExtended/flutterfire#7753]
I was trying to use `firebase_auth` and `google_sign_in` with a firebase app initialised in Dart, but when I try to sign in with google I get the following error:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(missing-config, GoogleService-Info.plist file not found, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:242:5)
<asynchronous suspension>
#3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
<asynchronous suspension>
```

Really I have to put `GoogleService-Info.plist` into my project, even If I'm using Dart initialisation? If so, whats the whole purpose of dart initialisation if some plugins still requiere to have the GoogleServices file? Shouldn't this be stated in the documentation?

I was really exited about Dart initialisation but since I tried it I encountered no other thing than problems. It was supposed to ease firebase configuration not make it more difficult.

**Comment by bhattabhi013** [comment]
I'm willing to update the documentation. Please assign this issue to me.

**Comment by Flucadetena** [comment]
Facing the same problem, out of the bloom. Before it was working fine. I've updated everything and doesn't help.

**Comment by pr-Mais** [comment]
`google_sign_in` doesn't support Dart-only initialization yet, so we still need the manual installation if the app uses Google sign in.

**Comment by hazzo** [comment]
Yet? Sorry to be harsh but it should be stated in same place in the documentation when tips like the following are in the oficial documentation:

![Screenshot 2022-01-03 at 09 07 14](https://user-images.githubusercontent.com/13692810/147909983-72f55293-40a7-4207-a649-a1ed3ae7e706.png)

There is nothing of **safe** and **backwards compatible** on this kind of statements. 

Just to be clear, I loved Flutter, FlutterFire ecosystem and I'm not complaining that `google_sign_in` is not working with Dart initialisation. It's just that the documentation tells the developer that when initialising Firebase with Dart everything will be the same as manual initialisation and it's **not true** (and I'm not mentioning that fcm is not working on iOS with Dart initialisation).

**Comment by pr-Mais** [comment]
Thanks for raising the issue, a PR is in-progress (#7745) to add notes on all unsupported plugins.

**Comment by hazzo** [comment]
Thanks!
