### ISSUE TITLE
[📚] FlutterFire can be initialized without importing 'firebase_options.dart'

### ISSUE THREAD

**Issue by bhattabhi013** [FirebaseExtended/flutterfire#7770]
In the current documentation https://firebase.flutter.dev/docs/overview there's only one way to initialise firebase in flutter app
<img width="535" alt="image" src="https://user-images.githubusercontent.com/47862474/148048506-eff8fe6a-66f7-4140-b885-5c12825b4135.png">
While going through the installation, I wasn't able to generate 'firebase_options.dart' file but I was still able to initalise my app. 
Steps to reproduce:

1) <img width="397" alt="image" src="https://user-images.githubusercontent.com/47862474/148049247-b034258b-aa48-4b84-bc33-090344fb9da7.png">
2) Add google-services.json (generated while configuring the app on firebase) into the android/app.

I think this other way should also be added in the documentation.
Please correct me, if I've done it the wrong way or  I've missed something.

**Comment by Salakar** [comment]
This is correct, the overview shows the recommended approach (generating via CLI), and the approach you took is the manual google services json installation (which is also supported): https://firebase.flutter.dev/docs/manual-installation
