### ISSUE TITLE
[📚] Add what "ODM" stands for

### ISSUE THREAD

**Issue by suryavip** [FirebaseExtended/flutterfire#7780]
Please add what does "ODM" stand for in [here](https://firebase.flutter.dev/docs/firestore-odm/overview). At least mention it once. I got confused the first time seeing this abbreviation on that page. Documentation should be friendly for newbie.

**Comment by Chinmay-KB** [comment]
I could guess what ODM is after some trying, but surely it should be simplified further for newcomers.

**Comment by darshankawar** [comment]
I think it stands for `Object Document Model` or `Object Defining Model` but yes, a long form of it can be documented.

/cc @rrousselGit

**Comment by Chinmay-KB** [comment]
> I think it stands for `Object Document Model` or `Object Defining Model` but yes, a long form of it can be documented.
> 
> /cc @rrousselGit

Object Document Mapping i think
