### ISSUE TITLE
About flutter connection SQL

### ISSUE THREAD

**Issue by notture** [FirebaseExtended/flutterfire#7799]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Socket has been closed
If an await query statement is added, an error will be reported, and the connection can be normal without adding a query statement.
await conn.query(
      'CREATE TABLE users (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, name varchar(255), email varchar(255), age int)');

**Comment by notture** [comment]
![2XRQ`T2DM(AHK6OUVTW~`E3(1).png](https://user-images.githubusercontent.com/77527176/148331745-154ad5b9-f584-443c-ac5c-7a3f6a9009bd.png)

**Comment by darshankawar** [comment]
@notture 
From the code you provided and error, it doesn't seem to be related to flutterfire plugins. You may need to reach out to the sql plugin repo you are using.
Closing from here.
