### ISSUE TITLE
[firebase_dynamic_links] Navigation fires on resume

### ISSUE THREAD

**Issue by ozzy1873** [FirebaseExtended/flutterfire#78]
1) Click on a dynamic link
2) The app opens and navigates to the correct page (1)
3) Manually navigate to a different page (2) in the app
4) Put app in background
5) Resume the app
6) The app navigates back to the dynamic link page

Expected behavior:
On resume, the app should remain on page 2.

This happens on both Android and iOS.

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by jherencia** [comment]
What version of firebase_dynamic_links are you using?

**Comment by ozzy1873** [comment]
I'm using the latest - 0.5.0+1

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by koiralapankajgit** [comment]
I have same issue.

**Comment by jherencia** [comment]
I've checked and everything works as expected, can you show me how you call getInitialLink and onLink in your widget?

I think you are calling getInitialLink more than once.

**Comment by koiralapankajgit** [comment]
Thanks for getting back to me. Issue has been resolved. Due to busy
schedule i couldn't post comment.

**Comment by jherencia** [comment]
@koiralapankajgit 

Great to hear! Can you close the issue?

**Comment by dpedrinha** [comment]
@koiralapankajgit please explain. It might help others like me :D
