### ISSUE TITLE
firebase_analytics  FirebaseAnalyticsObserver brought back as "part of" causing issues

### ISSUE THREAD

**Issue by ScottS2017** [FirebaseExtended/flutterfire#7806]
- 9.0.0 removed FirebaseAnalyticsObserver. Before that time, we used an import for observer.dart
- FirebaseAnalyticsObserver was brought back in 9.0.3 _but it's not imported the same way, and this is causing issues._
- The observer file is now "part of firebase_analytics", which requires a different import than before.

This is still a breaking change, even though the class was brought back. The imports in all code written before 9.0.0 are still going to be broken. Does the file absolutely need to be a part of now? Can it be changed back so the old import will still work?

Old import: 
import 'package:firebase_analytics/observer.dart';

New import needed:
import 'package:firebase_analytics/firebase_analytics.dart';

**Comment by darshankawar** [comment]
Treating this as an enhancement request for proposed change.

/cc @Salakar
