### ISSUE TITLE
🐛 [firebase_messaging] iOS Received an invalid notification content error

### ISSUE THREAD

**Issue by SpeedyG1481** [FirebaseExtended/flutterfire#7817]
Hello;

We have a problem with the firebase_messaging plugin. While it can run smoothly on the Android part with the plugin, it gives meaningless and ridiculous errors on the iOS part. One of them is this;

"Received an invalid notification content":
When the application is open or in the background, when we click on any notification when we click on it (we are redirecting and it works smoothly on the android part) it gives this error... We are investigating the reason, but we could not find it, we tried many things, we added content-avaliable with the apns tag, it did not work, we added mutable content, what is the problem?

`      const message = {
        token: token,
        notification: {
          title: username,
          body: lastMessage,
        },
        data: {
          specificPageRouteId: lastSender.toString(),
          chatId: chatId.toString(),
          notificationType: "chat",
          messageType: messageType,
          click_action: "FLUTTER_NOTIFICATION_CLICK",
        },
      };`

We are currently sending with the message json below. There is no problem in sending, but as I said, we only have a problem with clicking on the iOS part.

We use awesome notifications as a local notification package and it works seamlessly on the android part.

**Comment by darshankawar** [comment]
@SpeedyG1481 
There's similar issue open for the error you are getting: https://github.com/FirebaseExtended/flutterfire/issues/7249 for which see [this](https://github.com/FirebaseExtended/flutterfire/issues/7249#issuecomment-999457883) issue comment from the team member indicating it could be due to an conflict using `awesome_notifications` plugin.
