### ISSUE TITLE
App Check keeps returning same token on all devices (and said token fails)

### ISSUE THREAD

**Issue by Abdelrahman-Sherif** [FirebaseExtended/flutterfire#7824]
I have trouble setting up App-Check on my app(s). The current issue is: On Android, I keep getting the same token "eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==" on all devices (emulator and physical). 
I thought maybe the problem is with the current project, so I setup a new blank project, added appcheck and the same still happens. I receive the same token but then I enforced app-check (as its a test project anyway) and noticed that the calls actually fail, with error message saying that the app check token is invalid.

Summary: Get same token on all Android devices, and said token still fails with Firebase calls.

**Comment by darshankawar** [comment]
@Abdelrahman-Sherif 
Can you provide complete error log that shows `token is invalid` ?
There's similar issue open that you can refer https://github.com/FirebaseExtended/flutterfire/issues/6957

**Comment by Nayane-19** [comment]
I'm having the same problem. Did you manage to solve it?

**Comment by Abdelrahman-Sherif** [comment]
Unfortunately not. Will just wait for it to get more stable..

**Comment by Jai05-techie** [comment]
Any update on this ? After updating firebase_messaging plugin same issue me to facing. FCM Token is returning same token when i do deleteToken and getToken.
