### ISSUE TITLE
iOS: Firestore transaction fails with 'Transaction failed all retries'

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#783]
## Steps to Reproduce

Trying to run a very simple transaction, similar to the example in the cloud_firestore documentation (using v0.7.3):

```dart
    DocumentReference usernameDocRef =
        Firestore.instance.collection(_USERNAMES).document(username);

    await Firestore.instance.runTransaction((transaction) async {
      var snapshot = await transaction.get(usernameDocRef);
      if (!snapshot.exists) {
        await transaction.set(usernameDocRef, {
          _UsernamesKey.userid: _user.id,
        });
      }
    });
```

## Logs

```
[+9301 ms] [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
[        ] PlatformException(9, Transaction failed all retries., null)
[        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
[        ] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
[        ] <asynchronous suspension>
[        ] #2      Firestore.runTransaction (file:///Users/duncan/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.3/lib/src/firestore.dart:115:10)
[        ] <asynchronous suspension>
[        ] #3      FirebaseDataService.updateUsername (package:project/service/firebase_data_service.dart:308:30)
[        ] <asynchronous suspension>
[        ] #4      UsernamePresenter.usernameChosen (package: project/registration/username_presenter.dart:17:39)
[        ] <asynchronous suspension>
[        ] #5      _UsernameSelectionView.build.<anonymous closure> (package: project/registration/username_view.dart:64:43)
[        ] #6      OnePressButtonState._pressed (package: project/shared.dart:171:14)
[        ] #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
[        ] #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
[        ] #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
[        ] #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
[        ] #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
[        ] #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
[        ] #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
[        ] #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
[        ] #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] #20     _invoke1 (dart:ui/hooks.dart:134:13)
[        ] #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

```
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.4 17E202, locale en-GB)
    • Flutter version 0.5.5 at /Users/duncan/git/flutter
    • Framework revision 020e0ef55c (8 days ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/duncan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4668.60

[✓] Connected devices (1 available)
    • duncan_iphone • - • ios • iOS 11.4

• No issues found!
```

**Comment by el-mimoso** [comment]
We are facing a similar exception while running on iOS, in andriod works fine. 
LOG: 
     `Exception has occurred.
PlatformException (PlatformException(9, Transaction failed all retries.: Every document read in a transaction must also be written in that transaction., null))`
Using cloud_firestore: ^0.12.9+2

    DocumentReference docRef = Firestore.instance
          .collection('e')
          .document(escuelas.elementAt(indiceTemporal))
          .collection('o')
          .document(_userID);

    Firestore.instance.runTransaction((Transaction transaction) async { // Exception is thrown 
      DocumentSnapshot docSnapshot = await transaction.get(docRef);
      if (docSnapshot.exists){
        await transaction.update(docRef,{'x': DateTime.now()});//prueba para ios
        documentosPreorden.add(docSnapshot);
      }

**Comment by el-mimoso** [comment]
We are facing a similar exception while running on iOS, in andriod works fine.
LOG:
Exception has occurred. PlatformException (PlatformException(9, Transaction failed all retries.: Every document read in a transaction must also be written in that transaction., null))
Using cloud_firestore: ^0.12.9+2

FLUTTER DOCTOR
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale es-MX)
• Flutter version 1.9.1+hotfix.4 at /Users/danielcastropineda/flutter
• Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
• Android SDK at /Users/danielcastropineda/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.1, Build version 11A1027
• CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 36.0.1
• Dart plugin version 183.6270
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.5.1

[✓] Connected device (1 available)
• iPhone •... • ios • iOS 12.4.2

DocumentReference docRef = Firestore.instance
      .collection('e')
      .document(escuelas.elementAt(indiceTemporal))
      .collection('o')
      .document(_userID);

Firestore.instance.runTransaction((Transaction transaction) async { // Exception is thrown 
  DocumentSnapshot docSnapshot = await transaction.get(docRef);
  if (docSnapshot.exists){
    await transaction.update(docRef,{'x': DateTime.now()});//prueba para ios
    documentosPreorden.add(docSnapshot);
  }

**Comment by guit4eva** [comment]
Still getting this error on iOS as well. It crashes a physical iPhone 4s. Seems to be fine on Android

**Comment by kroikie** [comment]
@el-mimoso @guit4eva If this is still an issue for you please open a new issue with the specific instance where you are seeing this.

Thanks!
