### ISSUE TITLE
[firebase_messaging] push messaging not delivering when app is killed

### ISSUE THREAD

**Issue by Anfet** [FirebaseExtended/flutterfire#7840]
### Description:
firebase_messaging plugin does not deliver FCM messaging to app or system tray when app is killed. 

Using:
```

environment:
  sdk: ">=2.15.0 <3.0.0"

firebase_core: ^1.10.2
firebase_messaging: ^11.2.0

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1415], locale ru-RU)
    • Flutter version 2.8.1 at D:\.Important\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\.Important\AndroidSDK
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = D:\.Important\AndroidSDK
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
```

### initialization code 

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  FirebaseMessaging.onMessage.listen(onFirebaseMessage);
  // FirebaseMessaging.onMessageOpenedApp.listen(_onFirebaseMessage);

  runApp(AssemblerApp());
}
```

While app is in foreground and background, I receive onBackgroundMessage / onMessage.
If I kill the app the messages are no longer being delivered to user while FCM reports success

### Push message data
```{
    "notification": {
        "title": "\u041d\u043e\u0432\u044b\u0439 \u0437\u0430\u043a\u0430\u0437",
        "body": "\u041f\u043e\u0441\u0442\u0443\u043f\u0438\u043b \u043d\u043e\u0432\u044b\u0439 \u0437\u0430\u043a\u0430\u0437 \u2116 [%]. \u041d\u0435\u043c\u0435\u0434\u043b\u0435\u043d\u043d\u043e \u043d\u0430\u0447\u043d\u0438 \u0435\u0433\u043e \u0441\u0431\u043e\u0440\u043a\u0443."
    },
    "data": {
        "type": "ORDER_INFO",
        "title": "\u041d\u043e\u0432\u044b\u0439 \u0437\u0430\u043a\u0430\u0437",
        "body": "\u041f\u043e\u0441\u0442\u0443\u043f\u0438\u043b \u043d\u043e\u0432\u044b\u0439 \u0437\u0430\u043a\u0430\u0437 \u2116 [%]. \u041d\u0435\u043c\u0435\u0434\u043b\u0435\u043d\u043d\u043e \u043d\u0430\u0447\u043d\u0438 \u0435\u0433\u043e \u0441\u0431\u043e\u0440\u043a\u0443.",
        "order_id": "100000853",
        "success": "NEUTRAL",
        "deeplink": "\/order\/100000853"
    },
    "to": "eK5LBortQYWVxQN6pDeYIu:APA91bH7SgA4d1gQFW7emmFeHx2ATSDmXhaokt6FhDDRr-LiAo6svwaNMKdPuhvuiVJoAQK4SVNpT9b6B7HFj8kVCTUz1f46ICRNobFj1vqnBQjY2TRg8Yd7shZrNreM9l5-ajqMxbiP",
    "android": {
        "priority": "high"
    },
    "apns": {
        "payload": {
            "aps": {
                "contentAvailable": "true"
            }
        },
        "headers": {
            "apns-push-type": "background",
            "apns-priority": "5",
            "apns-topic": "io.flutter.plugins.firebase.messaging"
        }
    }
}
{"multicast_id":8906492871425850351,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1641897546671072%d7e81b5ad7e81b5a"}]}```

Message w/o data or notification is not delivering also.
If there is any data I could provide to debug the issue please tell.

**Comment by darshankawar** [comment]
@Anfet 
As mentioned in the documentation https://firebase.flutter.dev/docs/messaging/usage#receiving-messages when the app is killed on Android the notifications can't be received or listened to.
How are you terminating the app ?

**Comment by Anfet** [comment]
By swiping it away.
Why you are stating that notifications can't be received? In documentation we have written 

_Based on your applications current state, incoming payloads require different implementations to handle them:
Terminated: `onBackgroundMessage`_

I've found the solution to my problem by adding  `"priority":"high"` to raw body of the push message. (per this [documentation ](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Notification))
That conflicts with [flutter documentation](https://firebase.flutter.dev/docs/messaging/usage/#receiving-messages) example where 
```
  android: {
    priority: "high",
  },
```
block is added which has no effect.

There is also undesired effect of doubling notifications. As I understand, system is receiving push data containing `notification` block and making a notification itself and forwarding data to app service which makes another notification.

**Comment by darshankawar** [comment]
@Anfet 
Can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if you get the same behavior ?

**Comment by FabianTerhorst** [comment]
I also have the problem that when the android app is killed the background messages aren't received anymore.
I even get the
```FLTFireMsgReceiver: broadcast received for message```
log but the background message handler isn't triggered.
I also tried removing the high priority check to have same behavior for all messages: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundService.java#L39
but even with it always to true no messages are received as soon as the app is killed for longer than a minute.

**Comment by kanekv** [comment]
The problem is that notification isn't delivered to system as well (at least not showing up in notification popup).

**Comment by kanekv** [comment]
@darshankawar this might be related to #6956.

**Comment by Anfet** [comment]
> The problem is that notification isn't delivered to system as well (at least not showing up in notification popup).

I don't understand how to  reliably deliver. 
Even with `"priority":"high"` the messages are being delivered randomly or with unknown delay.

**Comment by darshankawar** [comment]
@Anfet 
Do you mean that the delivery is intermittent, sometimes it delivers and sometimes not or is it consistent that everytime you push, it doesn't deliver ?
Per above comment, can you try on Android 10 and < 10 to confirm ?

**Comment by Anfet** [comment]
> @Anfet Do you mean that the delivery is intermittent, sometimes it delivers and sometimes not or is it consistent that everytime you push, it doesn't deliver ? Per above comment, can you try on Android 10 and < 10 to confirm ?

When I send push and the app is in foreground or background - the push data is delivered and received 100%.
When app is killed (swiped away) - the messages are delivered on unknown schedule. I suppose there is some delay. As from time to time, I see in logcat that app is being started and message processed.

Android 7 have normal behavior. Push messages are delivered reliably.

**Comment by darshankawar** [comment]
@kanekv 
This might be related to native firebase android sdk since per your comment it works well on Android 7 but not on Android 10 or later and not with the firebase_messaging plugin. I would advise you to open this issue in https://github.com/firebase/firebase-android-sdk/issues. 
Flutterfire plugin are just wrappers around native firebase sdks.
