### ISSUE TITLE
[📚] Distributed Counter Help

### ISSUE THREAD

**Issue by rlee1990** [FirebaseExtended/flutterfire#7845]
Hi can we have documentation on how to use Distributed Counter in Flutter? When setting up the extension in Firebase they provide steps for ios android and javascript but not Flutter. The Firebase team states we have to contact you about this.

**Comment by darshankawar** [comment]
If I am not wrong, distributed counter is related to firestore: https://firebase.google.com/docs/firestore/solutions/counters

**Comment by rlee1990** [comment]
> If I am not wrong, distributed counter is related to firestore: https://firebase.google.com/docs/firestore/solutions/counters
> 
> 

This doesn't help as stated above this doesn't reference flutter. When the distributed counter extension is used it gives you code snippets to use but that does not exist in flutter. The firebase team states we need to reach out here for that.

**Comment by darshankawar** [comment]
@rlee1990 
I mentioned that link as a firebase documentation reference.

**Comment by rlee1990** [comment]
> @rlee1990 
> 
> I mentioned that link as a firebase documentation reference.
> 
> 

Yes but it's not helpful as it does not have a reference to flutter or dart at all and that's the issue.

**Comment by rlee1990** [comment]
@darshankawar Are there any documents on this for flutter?

**Comment by rlee1990** [comment]
@darshankawar So when I am referring to the distributed Counters it's for the extension like this one made for android:
[https://github.com/firebase/extensions/blob/next/firestore-counter/clients/android/src/main/java/com/firebase/firestore/counter/FirestoreShardedCounter.java](url)

**Comment by rlee1990** [comment]
@Salakar @darshankawar can someone reopen this

**Comment by pr-Mais** [comment]
Regarding the extension, there's currently a PR open for Dart https://github.com/firebase/extensions/pull/607.
Also, any issues regarding extensions should go in https://github.com/firebase/extensions/issues.

**Comment by rlee1990** [comment]
@pr-Mais thanks so looks like I have to wait.
