### ISSUE TITLE
Hi @Flucadetena this way of Firebase initialization is not working,it gives this error - Firebase has not been correctly initialized.

### ISSUE THREAD

**Issue by MishraVaibhav1999** [FirebaseExtended/flutterfire#7851]
Hi @Flucadetena 

Please try code sample 

<details> 
<summary>code sample</summary> 

```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

`  firebase_core: ^0.5.0`

_Originally posted by @TahaTesser in https://github.com/FirebaseExtended/flutterfire/issues/3384#issuecomment-685688089_

**Comment by Flucadetena** [comment]
Hi @MishraVaibhav1999, first I see you are using `firebase_core:^0.5.0` try by updating to the current version `firebase_core: ^1.11.0`. That might solve the problem.

A part from that, have you just added `firebase_core`? If not, other firebase package might be the problem. 

I've just created a new project, added `firebase_core` initialize firebase with the CLI, as it is explained here: 
[Firebase CLI](https://firebase.flutter.dev/docs/cli/)

And it run perfectly. No errors. But that just with `firebase_core`. If you are using any other firebase service you might need to do a [Manual installation](https://firebase.flutter.dev/docs/manual-installation)

I have multiple projects with both, manual and the new system, connected to more than one firebase project through flavors and always initialize Firebase this way, and have 0 issues.

Do some test and if I can help you with any further thing don't hesitate to write ;)

**Comment by MishraVaibhav1999** [comment]
hello @Flucadetena i am using firebase_core: ^1.11.0
and i tried both technique to initialize the firebase. Through manual technique issue is same but through Firebase CLI it gives export PATH something like that and B.T. W thanks a lot for helping me.

**Comment by Flucadetena** [comment]
Hi @MishraVaibhav1999  without more info I can't help you, if you want DM me on twitter https://twitter.com/F_lucadetena or in insta: https://www.instagram.com/f.lucadetena/
 an we can schedule a call to help you solve the issue. ;)

**Comment by darshankawar** [comment]
@MishraVaibhav1999 
Not sure what exactly your issue is here, try to follow the [documentation](https://firebase.flutter.dev/docs/core/usage) step by step using a new project and see if you are able to compile and run sample app. If not, provide the error log you are getting along with steps to replicate, so that we can address it properly.

**Comment by MishraVaibhav1999** [comment]
I solved the problem and thank you all for helping me
