### ISSUE TITLE
🐛 [firebase_messaging] onMessageOpenedApp does not fire

### ISSUE THREAD

**Issue by mark8044** [FirebaseExtended/flutterfire#7875]
```
environment:
  sdk: ">=2.15.0 <3.0.0"

firebase_core: ^1.11.0
firebase_messaging: ^11.2.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\.Important\AndroidSDK
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = D:\.Important\AndroidSDK
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
```

Messages are being sent as silent notifications:
```
    "data": {
        "title": "Test1",
        "body": "Test2",
        "t": "85674",
        "d": "221345",
        "r": "23353546"
    },
    "to": "...",
    "android": {
        "priority": "high"
    },
    "apns": {
        "payload": {
            "aps": {
                "contentAvailable": "true"
            }
        },
        "headers": {
            "apns-push-type": "background",
            "apns-priority": "5",
        }
    }
```

Using local_notifications the notifications are successfully displayed when the app is opened, background or terminated

- When app is opened and notification comes in `onMessage` fires
- If app is backgrounded and notification comes in `onBackgroundMessage` fires (the push is shown on screen with local notifications
- *** If app is backgrounded and the above notification is clicked on, the app opens but the `onMessageOpenedApp` does not fire

```
void registerNotification(context) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );


  FirebaseMessaging.onBackgroundMessage(onMessageReceivedShowPopup);

  NotificationSettings settings = await FirebaseMessaging.instance.requestPermission(
    alert: true,
    badge: true,
    provisional: false,
    sound: true,
  );

  if (settings.authorizationStatus == AuthorizationStatus.authorized) {
    print('User granted permission');

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {  // These all fire
      print(
          'Message title: ${message.notification?.title}, body: ${message.notification?.body}, data: ${message.data}');

      // Parse the message received
        debugPrint('[FCM] => onMessage');
        onMessageReceivedShowPopup(message);   // These all fire
        handlePushTap(message, context);     // These all fire
    });


    // For handling notification when the app is in background
    // but not terminated and when it is tapped and when we come back into the app
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      debugPrint('[FCM] => onMessageOpenedApp');  // This DOES NOT fire
      handlePushTap(message, context);   // This DOES NOT fire
    });
```

**Comment by darshankawar** [comment]
@mark8044 
Can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if you get same behavior using it too ?

**Comment by mark8044** [comment]
> 

I used the example app to put the piece in the logical same places in my own app and was having the same problem.

However, today I ran it on my device in release mode as opposed to debug and it does seem to be properly triggering.

I'm wondering if this is because the AndroidManifest.xml files contains the high importance channel information as well as FLUTTER_CLICK_NOTIFICATION tag but the debug manifest does not?  

So right now as far as I can tell is that in release mode this is working, but not in debug.  It will make testing this app a bit difficult, but that is something...

**Comment by darshankawar** [comment]
> I'm wondering if this is because the AndroidManifest.xml files contains the high importance channel information as well as FLUTTER_CLICK_NOTIFICATION tag but the debug manifest does not?

Can you try to add the same in debug manifest and check if it helps ?
