### ISSUE TITLE
[firebase_messaging 11.2.5] A Firebase App named "[DEFAULT]" already exists

### ISSUE THREAD

**Issue by loksoon** [FirebaseExtended/flutterfire#7887]
FirebaseException ([core/duplicate-app] A Firebase App named "[DEFAULT]" already exists)
![Screenshot 2022-01-17 at 18 56 42](https://user-images.githubusercontent.com/43371272/149757557-54ec3ac7-72ae-40d5-8c71-171b2e2e0b3e.png)

I setup same with the example code(https://pub.dev/packages/firebase_messaging/example)
![Screenshot 2022-01-17 at 19 00 00](https://user-images.githubusercontent.com/43371272/149757792-62fc4121-5ac4-4a5f-b613-95eeefd53b53.png)

**Comment by Martyhacker** [comment]
Did you try use google-services.json file?

**Comment by loksoon** [comment]
yes has been import inside the project

**Comment by loksoon** [comment]
if i just use 
await Firebase.initializeApp()
is working

**Comment by loksoon** [comment]
if use with the option will came out the error

**Comment by loksoon** [comment]
i am debugging using iphone

**Comment by Martyhacker** [comment]
I have this problem just now, too.
I am also trying to solve this.

**Comment by Martyhacker** [comment]
I am used flutterfire generated <code>flutter_options.dart</code> file. This file worked on iOS very good, but on Android not working. In my code I just paste if statement. If platform is android i use <code>Firebase.initializeApp()</code> else I am using options.
`Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (Platform.isIOS) {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
  } else {
    await Firebase.initializeApp();
  }`

**Comment by Martyhacker** [comment]
Did you solve problem?

**Comment by richard457** [comment]
the initialization should be like this await Firebase.initializeApp(); on mobile and add options only on desktop (still experimental)

**Comment by Martyhacker** [comment]
But we can not use <code>Firebase.initializeApp();</code> on both android and iOS. I got problems when I build on iOS. iOS requires firebase_options.dart file.

**Comment by richard457** [comment]
Then you need to check the platform and use the right initialization.
