### ISSUE TITLE
🐛 [firebase_crashlytics] Automatic deobfuscation in the crashlytics dashboard

### ISSUE THREAD

**Issue by tgpsantos** [FirebaseExtended/flutterfire#7889]
Hello guys,

I've obfuscated my android app and it can become painful to read stack traces onwards. Luckily, there's a way to run debug keys against the obfuscated stack trace and that translates it into readable and actionable stack.

However, it's a bit cumbersome having to:
-  _translate_ every exception from the firebase crashlytics. basically copy and pasting and then having to store the resulted information somewhere, because more often than not we won't solve that exception right away
- it's not always clear which debug key should be used for each exception (arm / arm64 / x86)
- reminding ourselves to store every debug keys for each release, because they might not work for future app versions

Is there a way to automatically deobfuscate the stack? Maybe by bundling the keys into the aab at the moment of release?

Thanks in advance!

**Comment by darshankawar** [comment]
@tgpsantos 
I am not sure if this will be in scope of firebase_crashlytics. You'll probably need to reach out to [firebase-support](https://firebase.google.com/support) as how to do that. See this open issue for your reference: https://github.com/firebase/quickstart-android/issues/897
Closing this from here. If you disagree write in comments and I'll reopen it.

**Comment by zeucxb** [comment]
@tgpsantos any update on it? Do you find a solution?

**Comment by riegersan** [comment]
Have you seen the "[Get readable crash reports in the Crashlytics dashboard](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?authuser=0&platform=android)" section in the Documentation?

**Comment by tgpsantos** [comment]
@zeucxb No I didn't.

@riegersan tried that but it didn't work
