### ISSUE TITLE
Feature Request: FirebaseUI Support

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#789]
I really like FirebaseUI. It is very convenient and helps me focus on my application rather than a tedious authentication flow implementation. Can you make a FirebaseUI plugin for Flutter? Or implement it in dart?

**Comment by kroikie** [comment]
@clarktank

The issue at https://github.com/flutter/flutter/issues/18625 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by CiriousJoker** [comment]
Any news on this?

**Comment by Purus** [comment]
Any official package on this would be much reliable as other packages are incomplete.
