### ISSUE TITLE
[firebase dynamic links] deeplink didn't open app on facebook #7886

### ISSUE THREAD

**Issue by AbanoubWagih94** [FirebaseExtended/flutterfire#7890]
when share link on facebook the link always open store even if app installed on mobile 
this happened on ios

**Comment by darshankawar** [comment]
@AbanoubWagih94 
This seems to be similar to another open issue https://github.com/FirebaseExtended/flutterfire/issues/3861, so please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by AbanoubWagih94** [comment]
@darshankawar  this issue from 2020 and not solved until now
