### ISSUE TITLE
[firebase_messaging] Error while calling method messaging#getToken & Messaging#subscribeToTopic

### ISSUE THREAD

**Issue by FortySL** [FirebaseExtended/flutterfire#7903]
Hello World,

I am new to flutter and writing the function for receiving notification on both iOS and Android platform. I achieved this function and it was working well but these days I got an issue:

```
FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
}
FLTFirebaseMessaging: An error occurred while calling method Messaging#subscribeToTopic, errorOrNil => {
}
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      MethodChannelFirebaseMessaging.subscribeToTopic (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:371:7)
<asynchronous suspension>
```

This **only happened on iOS platform** (Android is working well), I have tried to find the reason so I rollback to previous commit and I can see this happened after I added **Push Notification** and **Background Modes** capabilities to Runner Target, but these two are the main cores for receiving notification on iOS platforms. :3. I also tried to remove these two capabilities, the error still exit, so it is very confusing.
 
Any suggestions would be appreciated!

Here is Flutter Doctor -v
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-arm, locale en-AU)
    • Flutter version 2.8.1 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/bpc/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/bpc/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```
Here is the code
```
    //ios part permission
    FirebaseMessaging.instance.requestPermission().then((value) {
      print(value);});
    FirebaseMessaging.instance.getToken().then((token){
      print(token);});
    FirebaseMessaging.instance.getAPNSToken().then((APNStoken){
      print(APNStoken);});
  }
```

And I am using 
`firebase_messaging: ^11.2.5`

**Comment by darshankawar** [comment]
@FortySL 
Did you use dart-only initialization for firebase or was it manual installation ?
If the latter, can you check if you are using wrong api key of firebase in the GoogleServices-info.plist ?

**Comment by FortySL** [comment]
Thx for your reply. 

I am not so clear about what is dart-only initialization and will do some searches tmr. 

I tried to delete the current Googleservice-info and re download it, this issue was still there. But apart from this, other functions are working well like displaying products from firebase so I think the connection between my app and firebase is fine.

Again, thx for ur reply and suggestion

**Comment by FortySL** [comment]
> 
Thx for your reply.

I am not so clear about what is dart-only initialization and will do some searches tmr.

I tried to delete the current Googleservice-info and re download it, this issue was still there. But apart from this, other functions are working well like displaying products from firebase so I think the connection between my app and firebase is fine.

Again, thx for ur reply and suggestion

**Comment by FortySL** [comment]
@darshankawar 
Thx for your reply.

I am not so clear about what is dart-only initialization and will do some searches tmr.

I tried to delete the current Googleservice-info and re download it, this issue was still there. But apart from this, other functions are working well like displaying products from firebase so I think the connection between my app and firebase is fine.

Again, thx for ur reply and suggestion

**Comment by darshankawar** [comment]
@FortySL 

> I am not so clear about what is dart-only initialization

This is a new CLI tool introduced by flutterfire plugin owner with which you can initialize firebase through this tool. You can read more about it here: https://firebase.flutter.dev/docs/cli/

If you have done it with traditional way, then make sure you have properly setup and configured for iOS, as it may be a bit tricky to set up messaging properly. See this documentation and confirm if you have correct setup : https://firebase.flutter.dev/docs/messaging/overview#4-apple-integration

**Comment by FortySL** [comment]
@darshankawar 
Thx for this, I think the configuration should be correct cuz it was working. This error happened after I merged several branches with different flutter version. I tried to use **flutter clean** and cache clean, but they do not work.

I am thinking is there any way that can help me to clean firebase related setting or configuration inside my iOS folder, so I can redo this part.

I tried to delete the iOS folder inside my project and then use **flutter create .** to generate a new one, and this error has been removed, but in this case, App store regard my app as a new app rather than the continues of the previous one.

FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
}
FLTFirebaseMessaging: An error occurred while calling method Messaging#subscribeToTopic, errorOrNil => {
}
flutter: null
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      MethodChannelFirebaseMessaging.subscribeToTopic (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:371:7)
<asynchronous suspension>

**Comment by darshankawar** [comment]
> This error happened after I merged several branches with different flutter version. I tried to use **flutter clean** and cache clean, but they do not work.

It seems your entire setup / config is messed up. Can you try with a fresh project from scratch with new firebase project and config according to the document and see if you still get same error ?
