### ISSUE TITLE
🐛 [ui] Provider configuration `clientId` vs `appId`

### ISSUE THREAD

**Issue by Ehesp** [FirebaseExtended/flutterfire#7907]
Provider configuration (e.g. `GoogleProviderConfiguration`) requires a `clientId`, even though the documentation states an `appId` is required.

`appId` is preferred since it is the name used on the Firebase Console. 

![image](https://user-images.githubusercontent.com/842078/150305682-6d42ee92-a8f9-4f93-9ef5-628eb0c38559.png)

https://firebase.flutter.dev/docs/ui/auth/configuring-providers

![image](https://user-images.githubusercontent.com/842078/150305741-0ccc51a9-df4d-4a86-b8e6-ee5fa7c440bb.png)

https://firebase.flutter.dev/docs/ui/auth/integrating-your-first-screen#adding-google-sign-in

## Checklist

- [x] Standardise use of `appId` throughout code & docs.
- [x] Provide more detailed documentation where in the Console the `appId` can be found.

**Comment by lesnitsky** [comment]
Naming in code reflects the naming of providers. For example, what Google calls "clientId" is called "App ID" on Twitter developer portal, so this shouldn't be confusing to the developer, since the app should be created on the console in any case. Docs improvements coming.
