### ISSUE TITLE
Slow Firestore query on large collections

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#791]
A simple query like 
```
firestore.collection('small_collection').limit(1).getDocuments()
```
on a relatively small collection is almost "instantaneous". However, the same query on a collection with more than 100k documents takes more than 10-20s.
I think this is a `cloud_firestore` plugin issue because this query running on Python on the same large collection is also "instantaneous".

**Comment by AllNamesRTakn** [comment]
Is there any update on this? This still occurs on IOS

**Comment by kroikie** [comment]
@AllNamesRTakn if you are having this issue still, please file a new issue with information for us to reproduce.
