### ISSUE TITLE
[firebase dynamic links] deeplink didn't open app on facebook on ios

### ISSUE THREAD

**Issue by AbanoubWagih94** [FirebaseExtended/flutterfire#7910]
when share link on facebook the link always open store even if app installed on mobile
this happened on ios.
my last issue closed without solution

**Comment by darshankawar** [comment]
@AbanoubWagih94 
I think you opened same issue earlier which was closed in favor of https://github.com/FirebaseExtended/flutterfire/issues/3861. Please don't open multiple issues for same reason.

I suggest you to follow the dynamic_links documentation and check if you have properly setup the deeplink and also check if it opens as expected on other platforms like WhatsApp and share your findings in the original issue so we can track and revisit it properly.

Closing this as self-duplicate.
