### ISSUE TITLE
🐛 [cloud_firestore] Still not fixed: (#4305 - now closed) Streambuilder very slow to update from Cloud Firestore when Android app resumes after long period of inactivity 

### ISSUE THREAD

**Issue by ratherNotB** [FirebaseExtended/flutterfire#7914]
The issue described in Bug Report #4305 (from Dec 2020) still exists in the following package versions, despite an apparent fix being merged into the Android SDK:

  firebase_core: 1.10.6
  cloud_firestore: 3.1.5

Issue #4305 is now closed so I am opening a new issue. The bug still manifests itself in exactly the same way as described in #4305 and can be reproduced using the exact same steps.

I am not an Android developer so I have not tried to reproduce the issue by directly using the Android SDK as described in:

https://github.com/firebase/firebase-android-sdk/issues/2637

Hoping someone from the Flutterfire or Firebase teams can root cause this and, once a new fix is available for testing, leave this bug report open for comments until the community can validate the fix. Thank you.

**Comment by darshankawar** [comment]
@ratherNotB 
What's the `com.google.firebase:firebase-bom` version you have as dependency in your gradle file ?
The latest Firebase Android SDK version was bumped was https://github.com/FirebaseExtended/flutterfire/pull/6847 which ideally should have the fix as mentioned here https://github.com/FirebaseExtended/flutterfire/issues/4305#issuecomment-873098289

**Comment by ratherNotB** [comment]
Thanks for the reply @darshankawar.

I've actually removed the line that I previously used to specify the firebase-bom version in my app/build.gradle file as I thought it was no longer necessary, according to the following:

https://firebase.flutter.dev/docs/overview

Am I wrong? Should I continue to include the firebase-bom version in my app/build.gradle file?

Thanks

**Comment by darshankawar** [comment]
@ratherNotB 
I am not complete sure, but this document probably indicates it:

https://firebase.flutter.dev/docs/migration#plugin-changes

You may try to use `com.google.firebase:firebase-bom: 29.0.0` and see if it works.

**Comment by ratherNotB** [comment]
Hi @darshankawar,

Unfortunately that didn't solve it for me.

I'm using the following version of firebase_core:

firebase_core: 1.11.0

and I added the following to my app/build.gradle:

implementation platform('com.google.firebase:firebase-bom:29.0.3')

When I lock my phone with my app in the foreground and then unlock it after ~30 mins or so, new data can take 90s or 120s to appear.

Can you please try to reproduce?

Thanks!
