### ISSUE TITLE
🐛 [firebase_auth] register invalid action code in mobile browser

### ISSUE THREAD

**Issue by vendelin8** [FirebaseExtended/flutterfire#7921]
## Bug report

**Describe the bug**
The register process doesn't work in mobile browsers. I tried different android browsers including Chrome, and iOS Chrome.
The same code works on linux desktop browser and Android app. I printed and checked the opened link and the action code, it looks pretty much the same.

### Steps to reproduce

1. I've created a user by `FirebaseAuth.instance.createUserWithEmailAndPassword`
2. I've sent the action code by `.sendEmailVerification(...)`
3. I've clicked on the link in the email
4. I tried to apply the action code by
```
try {
  await FirebaseAuth.instance.checkActionCode(actionCode);
  await FirebaseAuth.instance.applyActionCode(actionCode);
  await FirebaseAuth.instance.currentUser?.reload();
} on FirebaseAuthException catch (e, st) {
  ...
}
```
4. In mobile browsers I've got `[firebase_auth/invalid-action-code] The action code is invalid. This can happen if the code is malformed, expired, or has already been used.`

### Expected behavior

Accept the code as it does in linux desktop browser and android browser.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.
https://github.com/vendelin8/firebase_auth_demo
Hosted for web at
https://firebase-auth-demo.ga/

---

## Additional context
I copied the code from the app I'm developing. Somehow I made a mistake: originally in the mobile web browser opening a dynamic link worked until applying action code failed. In this demo project it even shows an error about `failed to resolve uri domain prefix`. Not sure if it's something because of the code, or some configuration in the firebase project.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.10.0-0.1.pre, on Arch Linux 5.16.2-arch1-1, locale hu_HU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.0-134.1.beta
Flutter SDK 2.10.0-0.1.pre
firebase_auth_demo 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_auth 3.3.5 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 6.1.10 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- vector_math 2.1.1
```

</details>

---

**Comment by vendelin8** [comment]
I think that my other error `originally in the mobile web browser opening a dynamic link worked until applying action code failed. In this demo project it even shows an error about failed to resolve uri domain prefix` has simila reason as https://github.com/FirebaseExtended/flutterfire/issues/7074
I experienced that `dynamicLinkDomain` and `handleCodeInApp` of `ActionCodeSettings` get stuck with values called previously.

**Comment by darshankawar** [comment]
@vendelin8 
Can you check the documentation around sending email verification and then handling it with ActionCodeSettings and see if you have properly implemented it ? https://firebase.flutter.dev/docs/auth/usage#verifying-a-users-email

**Comment by vendelin8** [comment]
@darshankawar I've read it and found no distinction if it's an app, or web. The weirdest thing is that it's working in the Android app and in desktop browser, but not in a mobile browser.

**Comment by darshankawar** [comment]
@vendelin8 
If we go by the error you are getting `[firebase_auth/invalid-action-code] The action code is invalid. This can happen if the code is malformed, expired, or has already been used.`, maybe if the user is already registered ? Can you try to delete the user and register a new one and see if it works ?

If not, can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and see if you still get same behavior ?

**Comment by vendelin8** [comment]
Believe me, I did the very same process for:
- Android app
- Desktop browser
- Android browser
- iOS browser
And it was working for the first 2, and not working for the other 2.
I checked the plugin example, but it doesn't even have anything about sending a sign up verification email. My demo has. Please check out.

**Comment by vendelin8** [comment]
I think that the only thing that's different from the suggested ones is that I use `uni_links` package instead of `firebase_dynamic_links` package, because I want to use dynamic links other than the built in firebase ones. But that shouldn't be a problem, as I get the dynamic link, I can get the oobcode out of it, but it doesn't work.

**Comment by darshankawar** [comment]
@vendelin8 
Thanks for the update. Can you try couple of things ? Can you confirm if `authStateChanges` is triggered when running on mobile browser ? Can you also try by refreshing the browser ?

**Comment by vendelin8** [comment]
@darshankawar I upgraded all dependencies to latest possible, and it works in Android browser. I was also able to fix the `failed to resolve uri domain prefix` error by removing a slash from the end of the dynamic url email template link. I couldn't test it on iOS yet, will give a try soon.

**Comment by vendelin8** [comment]
And I've split the actionCodeSettings based on platform, so I send only the necessary ones. Not sure which made it work though.

**Comment by darshankawar** [comment]
@vendelin8 
Good to know you were able to resolve the issue. Closing based on above comment.
