### ISSUE TITLE
🐛 [cloud_firestore_odm_generator] `orderBy` queries are using hardcode values. 

### ISSUE THREAD

**Issue by dark-chocolate** [FirebaseExtended/flutterfire#7932]
Considering the model used in the [documentation](https://firebase.flutter.dev/docs/firestore-odm/defining-models): 
```
@JsonSerializable()
class User {
  User({
    required this.name,
    required this.age,
    required this.email,
  }) {
    // Apply the validator
    $assertUser(this);
  }

  final String name;
  final String email;

  // Apply the `Min` validator
  @Min(0)
  final int age;
}
```

After running 
```
flutter pub run build_runner build --delete-conflicting-outputs
```

the helper methods it creates for `orderBy` don't make use of the `descending` variable passed to them, for example: 

### Current code:

```dart
UserQuery orderByName({
  bool descending = false,
  // ... other properties
}) {
  var query = reference.orderBy('name', descending: false); // <-- This is the issue. 
  // ... 
}
```

### Expected code:

```dart
UserQuery orderByName({
  bool descending = false,
  // ... other properties
}) {
  var query = reference.orderBy('name', descending: descending); // <-- This is what it should be
  // ... 
}
```

Doing this will now solve the queries returned by: 

```
usersRef.orderByName(descending: true);
```

**Comment by darshankawar** [comment]
@dark-chocolate 
Can you confirm if this is same as https://github.com/FirebaseExtended/flutterfire/issues/7733 ?

**Comment by dark-chocolate** [comment]
@darshankawar  A bit similar because in that thread the OP is only raising issue for snake_case fields but in my issue it's about all the fields.

**Comment by darshankawar** [comment]
Thanks for the update.

/cc @rrousselGit
