### ISSUE TITLE
🐛 [firebase_core] Hot Restart: A Firebase App named "secondary" already exists

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#7938]
## Bug report

When registering a **secondary app** in `main`, **hot restart breaks** for the whole app (i.e. if you await the initialization).

### Steps to reproduce

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await Firebase.initializeApp(
    name: 'secondary',
    options: SecondaryFirebaseOptions.currentPlatform,
  );

  runApp(..);
}
```

### Expected behavior

The Flutter app works as it would without the Firebase dependency.

### Actual behavior

The app can be started, but **hot restart** is not possible. An error is thrown:

> A Firebase App named "secondary" already exists 

### Versions

```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (6 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
firebase_core: 1.11.0
```

**Comment by creativecreatorormaybenot** [comment]
@Salakar are you aware of this issue? It turns out this actually results in a **crash** _on Android_ (as in the app completely stops because there is an exception on the native side).

**Comment by creativecreatorormaybenot** [comment]
@darshankawar Using `flutterfire configure`. I only renamed the class.

**Comment by darshankawar** [comment]
I see, thanks. Yes, using the the default and secondary app config and then trying to hot restart shows `A Firebase App named "secondary" already exists ` error in the console.

`firebase_core: ^1.11.0` and `Channel master, 2.9.0-1.0.pre.504`

**Comment by creativecreatorormaybenot** [comment]
@darshankawar did you also try it out on Android? Because it results in a **crash** for us, which is pretty severe as there is no way to "ignore" a crash on the Dart side.
