### ISSUE TITLE
AbortError: Registration failed - could not retrieve the public key

### ISSUE THREAD

**Issue by leegiseong20030603** [FirebaseExtended/flutterfire#7940]
FirebaseMessaging fcm = FirebaseMessaging.instance;
fcm.getToken().then((token){
print("FCM TOKEN : ${user.fcm_token}");
});

When I run that code, I get the error "AbortError: Registration failed - could not retrieve the public key". how can i solve it??

We proceeded with flutter web, and navigator.serviceWorker.registers were successfully applied normally.

**Comment by darshankawar** [comment]
@leegiseong20030603 
Can you provide your `flutter doctor -v` and on which platform are you getting this error ?

**Comment by pedrammgd** [comment]
i have same problem
