### ISSUE TITLE
🐛 Notification issue when app in background mode for ios devices

### ISSUE THREAD

**Issue by ibrahimnagy** [FirebaseExtended/flutterfire#7944]
Notification display with all remote data but there was not any sound or completed function which had added to onBackgroundMessage Function

**Comment by darshankawar** [comment]
@ibrahimnagy 
Can you elaborate on the issue you are facing by providing `flutter doctor -v`, `pubspec.yaml` and all other requested details as mentioned in the new issue [template](https://github.com/FirebaseExtended/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here).

**Comment by joyincomp** [comment]
Same issue here! On iOS, background handler sometimes works sometimes not:
https://stackoverflow.com/questions/70955587/notification-background-handler-is-not-always-triggered-on-ios
