### ISSUE TITLE
🐛 [firebase_messaging] getToken() returns the same token after deleteToken()

### ISSUE THREAD

**Issue by MickaelHrndz** [FirebaseExtended/flutterfire#7952]
## Bug report

Basically, I'm mimicking the [deleteToken() test case](https://github.com/FirebaseExtended/flutterfire/blob/master/tests/test_driver/firebase_messaging/firebase_messaging_e2e.dart#L146) and it doesn't pass. I try deleting the token with `deleteToken()` but it stays the same.

This issue is similar to #7110. The differences are that this occurs on mobile, and the `onTokenRefresh` get called after `deleteToken()`.

### Steps to reproduce

Here's the test case I wrote :

```
@override
  void initState() {
    super.initState();
    
    () async {
      FirebaseMessaging.instance.onTokenRefresh.listen((event) {
        print('TOKEN REFRESHED : ${event}');
      });
      await Future.delayed(const Duration(seconds: 3));
      print('TOKEN : ${await FirebaseMessaging.instance.getToken()}');
      await Future.delayed(const Duration(seconds: 3));
      print('DELETE TOKEN');
      await FirebaseMessaging.instance.deleteToken();
      await Future.delayed(const Duration(seconds: 3));
      print('TOKEN : ${await FirebaseMessaging.instance.getToken()}');
      // The two TOKEN prints are identical
    }();
  }
```

### Expected behavior

The token should change after `.deleteToken()`, and without the need for `Future.delayed()`.

---

## Additional context

I am constrained to use Flutter 2.2.2 and Dart 2.9 (not null-safe).

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel unknown, 2.2.2, on Microsoft Windows [version 10.0.22000.434], locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
- firebase_core 1.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
```

</details>

**Comment by darshankawar** [comment]
@MickaelHrndz 
Can you provide us a complete test case or a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that replicates this behavior ?

**Comment by MickaelHrndz** [comment]
```
final token1 = await FirebaseMessaging.instance.getToken();
await FirebaseMessaging.instance.deleteToken();
final token2 = await FirebaseMessaging.instance.getToken();
expect(token1, isNot(token2));
```

**Comment by darshankawar** [comment]
@MickaelHrndz. I verified this behavior using below code sample using latest master and latest plugin version that prints different tokens (1 and 2) :

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  FirebaseMessaging.instance.onTokenRefresh.listen((token) {
    print(token);
  });
  final token1 = await FirebaseMessaging.instance.getToken();
  await FirebaseMessaging.instance.deleteToken();
  final token2 = await FirebaseMessaging.instance.getToken();
  print('token1: ${token1}');
  print('token2: ${token2}');

}
```

```
token1: f2b518ewt0Z17tQi8d1u0o:APA91bGJAVuuO3BerhIaRUEwDWKhGFxJUbTXxzi2Gg0nXgXj6hERDbNwdy0GJxKY5bedDXLKYekirrOel-mRhnztp1sscJThzlP_W_6H0yKhEQDYAOLmlAwJW9Rbi73KAYfkZdao4imJ
token2: f2b518ewt0Z17tQi8d1u0o:APA91bGqBK8KDPdCl2PieHbVQwUJw6wb0_ttot8qrPMLIiFWk0l_65apcAeWSKjDhE1BeIvIFiutQ4qm-fXRSiKByM5KNQ7S_fouM22sQKp61KF0134Vf_o_NJbXexVbVyD7ClYGd7Us


```

`firebase_messaging: ^11.2.6`
`Channel master, 2.10.0-1.0.pre.337`

**Comment by MickaelHrndz** [comment]
Not sure if upgrading Flutter to 2.8.1 fixed it or just got confused by the identical beginning, but I can't reproduce it anymore. Thank you for you answer @darshankawar.
