### ISSUE TITLE
🐛 [firebase_core] Cannot install in conjuction with permission_handler

### ISSUE THREAD

**Issue by ryanheitner** [FirebaseExtended/flutterfire#7973]
## Bug report

**Describe the bug**
ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:408:3: error: implicit declaration of function
'pb_release' is invalid in C99 
### Steps to reproduce

Include 
  firebase_core: 1.12.0 in pubspec.yaml
 in the podfile (add from permission_handler library)

post_install do |installer|
    installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            'PERMISSION_CAMERA=1',
            'PERMISSION_MICROPHONE=1',
            'PERMISSION_SPEECH_RECOGNIZER=1',
         ]
    end
  end
end

Try to build the app

### Expected behavior

The app should compile, you can reproduce using the default  counter app
### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.

you can use the default counter app, You just need to change the pubspect.yaml and Podfile
---

## Additional context

---

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-x64, locale
    en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!
➜  ~ 
<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```
ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:408:3: error: implicit declaration of function
'pb_release' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      pb_release(gdt_cct_BatchedLogRequest_fields, &batchedLogRequest);
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:
Changing current working directory to: /Users/ryanheitner/Projects/FirbaseTest
Dart SDK 2.15.1
Flutter SDK 2.8.1
fire_base 1.0.0+1
|-- cupertino_icons 1.0.4
|-- firebase_core 1.12.0
|   |-- firebase_core_platform_interface 4.2.4
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 2.1.2
|   |       '-- meta...
|   |-- firebase_core_web 1.5.4
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- meta...
|   |   |   |-- typed_data...
|   |   |   '-- vector_math...
|   |   |-- js 0.6.3
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- flutter 0.0.0
|   |-- characters 1.2.0
|   |-- collection 1.15.0
|   |-- meta 1.7.0
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0
|   |   '-- collection...
|   '-- vector_math 2.1.1
|-- flutter_application_id 2.0.0-dev
|   |-- args 2.3.0
|   |-- equatable 2.0.3
|   |   |-- collection...
|   |   '-- meta...
|   '-- yaml 3.1.0
|       |-- collection...
|       |-- source_span...
|       '-- string_scanner...
|-- flutter_launcher_icons 0.9.2
|   |-- args...
|   |-- image 3.1.1
|   |   |-- archive 3.1.6
|   |   |   |-- crypto 3.0.1
|   |   |   |   |-- collection...
|   |   |   |   '-- typed_data...
|   |   |   '-- path...
|   |   |-- meta...
|   |   '-- xml 5.3.1
|   |       |-- collection...
|   |       |-- meta...
|   |       '-- petitparser 4.4.0
|   |           '-- meta...
|   |-- path...
|   '-- yaml...
'-- flutter_test 0.0.0
    |-- async 2.8.2
    |   |-- collection...
    |   '-- meta...
    |-- boolean_selector 2.1.0
    |   |-- source_span...
    |   '-- string_scanner...
    |-- characters...
    |-- charcode 1.3.1
    |-- clock 1.1.0
    |-- collection...
    |-- fake_async 1.2.0
    |   |-- clock...
    |   '-- collection...
    |-- flutter...
    |-- matcher 0.12.11
    |   '-- stack_trace...
    |-- meta...
    |-- path 1.8.0
    |-- source_span 1.8.1
    |   |-- collection...
    |   |-- path...
    |   '-- term_glyph...
    |-- stack_trace 1.10.0
    |   '-- path...
    |-- stream_channel 2.1.0
    |   '-- async...
    |-- string_scanner 1.1.0
    |   |-- charcode...
    |   '-- source_span...
    |-- term_glyph 1.2.0
    |-- test_api 0.4.3
    |   |-- async...
    |   |-- boolean_selector...
    |   |-- collection...
    |   |-- matcher...
    |   |-- meta...
    |   |-- source_span...
    |   |-- stack_trace...
    |   |-- stream_channel...
    |   |-- string_scanner...
    |   '-- term_glyph...
    |-- typed_data...
    '-- vector_math...
<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@ryanheitner 
Although I am not getting the same error as you reported, I see below:

`/Users/dhs/Documents/NCFlutter/testdemo/ios/Pods/FirebaseCore/FirebaseCore/Sources/FIRVersion.m:20:2: error: "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"
    #error "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"`

Can you try to use the `permission_handler` plugin [example](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler/example), add `firebase_core` to it and see if you still get same behavior ?

**Comment by ryanheitner** [comment]
Thank you thanks to your help I have resolved the issue 

I was missing  '$(inherited)',


     target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
