### ISSUE TITLE
[firebase_crashlytics] Execution failed for task ':app:uploadCrashlyticsMappingFileProductionRelease'. Host name may not be empty🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by Abdeldjalil-Di-Chougui** [FirebaseExtended/flutterfire#7975]
## Bug report

**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadCrashlyticsMappingFileRelease'.
> Host name may not be empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 17s
Running Gradle task 'bundleRelease'...                            439,7s
Gradle task bundleRelease failed with exit code 1
Process finished with exit code 1

### Steps to reproduce

1. I tried to produce apb file and get this error

## Additional context

FirebaseSDKVersion=29.0.3

android/build.gradle
classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'

app/build.gradle
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

---

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [version 10.0.19042.1466], locale fr-DZ)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

---

### Flutter dependencies

I used
firebase_crashlytics: ^2.4.0

**Comment by darshankawar** [comment]
@Abdeldjalil-Di-Chougui 
First of all, you seem to be on very old version of stable, so I recommend to upgrade to latest stable (2.8.1) and try again.
Also, the error `Host name may not be empty`, indicates some kind of misconfiguration, so it doesn't seem to be related to `firebase_crashlytics` plugin specific. Check [this](https://github.com/firebase/firebase-android-sdk/issues/1647) similar issue and see underlying comments helps to resolve your issue, or you may also ask the same on support channels like StackOverflow.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by Abdeldjalil-Di-Chougui** [comment]
Thanks @darshankawar for answering, I tried the solutions that you mentionned but it does not work for me, I am trying to upgrade to latest stable and try again.
