### ISSUE TITLE
[firebase_auth] Disable default Google Auth Account

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#798]
I am using the `google_sign_in` package and `firebase_auth`. However, I realized whenever I press the raised button for "Sign In With Google" as I want to use google auth. After the first login, it defaults to one account whenever you press Sign In. Any way to disable that?

**Comment by kroikie** [comment]
@YourFavouriteOreo

The issue at https://github.com/flutter/flutter/issues/18355 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @YourFavouriteOreo
I see your own proposed [solution](https://github.com/flutter/flutter/issues/18355#issuecomment-396213283) as well as
@zoechi 's [comment](https://github.com/flutter/flutter/issues/18355#issuecomment-396223995)
tagging @Hixie from original issue

**Comment by omartinma** [comment]
Do we have any update on this feature? It seems that the workaround of login out before it doesnt work on web version.

**Comment by ach4m0** [comment]
I am having the same problem on Flutter Web. Google-sign-in package choose automatically the Google account if you have one logged-in after execute signout method.

**Comment by Ehesp** [comment]
Hi All

Could you show a code sample of how you're using the 2 libraries together? Wondering if this is an issue with the auth plugin or the google_sign_in library.

**Comment by omartinma** [comment]
I finally make it work doing this:

**Comment by Ehesp** [comment]
Closing - this is a google_sign_in thing. If you login with an account, it will continue to use that account by default unless signOut is called.
