### ISSUE TITLE
🐛 [firebase_auth] Firebase Dart initialisation crashes on iOS if push notifications capabilities are set

### ISSUE THREAD

**Issue by anthonyhunter** [FirebaseExtended/flutterfire#7983]
## Bug report

re #7752 not fixed by #7610

Using a clean Flutter 2.8.1 project setup for firebase messaging, app check, auth and firestore.
Run on **real iOS device** (iPhone 12 15.2.1)

With **Push Messaging** capability **enabled** I get the follow crash on real device:

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FirebaseApp instance must be configured before the default Authinstance can be initialized. One way to ensure this is to call `FirebaseApp.configure()` in the App Delegate's `application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI).'

With **Push Messaging** capability **disabled** the app launches as expected on real device.

Would appear the fix for `firebase_messaging` #7610 should also be applied to `firebase_auth` as both packages require APNS token at launch.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.3 20G415 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
userapp 1.0.0+1

dependencies:
- cloud_firestore 3.1.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_app_check 0.0.6+5 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.2.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.12 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.7 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_app_check_platform_interface 0.0.3+5 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.5+5 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.1.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for filing separate issue for this behavior. I verified this on latest master and see the same error as reported:

`
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FirebaseApp instance must be configured before the default Authinstance can be initialized. One way to ensure this is to call FirebaseApp.configure() in the App Delegate's application(_:didFinishLaunchingWithOptions:) (or the @main struct's initializer in SwiftUI).'`

It seems the fix made for `firebase_messaging`, need to be applied to `firebase_auth` as well.

`firebase_auth: ^3.3.6`

`Channel master, 2.10.0-1.0.pre.350`

/cc @russellwheatley

**Comment by Shlaayl** [comment]
I'm sorry, but Will this problem be fixed soon? I have two projects that depend on this plugin. 😢

**Comment by cvanvlack** [comment]
@Shlaayl See [this comment](https://github.com/FirebaseExtended/flutterfire/issues/7752#issuecomment-1014874996) on #7752 for a workaround. Doesn't help with flavors, but you can use it with one flavor for the time being and the utilize the previous flavor methods if nothing comes out in time for you.

**Comment by cvanvlack** [comment]
In case someone needs a flavor workaround, simply doing "Step 4: Adding build flavors to iOS" in [Build flavors in Flutter (Android and iOS) with different Firebase projects per flavor](https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b) worked for me.

**Comment by rlee1990** [comment]
I also am having this issue.
Hoping this will soon be fixed.

**Comment by anthonyhunter** [comment]
A temporary fix is to update `didRegisterForRemoteNotificationsWithDeviceToken` in `packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m`

```diff
(void)application:(UIApplication *)application
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
-  [[FIRAuth auth] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeUnknown];
+  [[FIRMessaging messaging] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeUnknown];
}
```

see pubic repo [here](https://github.com/anthonyhunter/flutterfire/commit/e8611a8dec629534434658eaea4dfe936749ac5f#diff-926b26fe3f9119fb3548066f1b05028306ff8766f9a04abba0fefdb5dac5c0b2)

**Comment by JagandeepBrar** [comment]
Any update on this issue?

Relatively big and breaking as using `firebase_auth` and `firebase_messaging` together is definitely very common.

**Comment by marcusrohden** [comment]
Any updates on this?

I also tested the change bellow from @anthonyhunter, and it fixes the issue.
Thank you


> A temporary fix is to update `didRegisterForRemoteNotificationsWithDeviceToken` in `packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m`
> 
> ```diff
> (void)application:(UIApplication *)application
>     didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
> -  [[FIRAuth auth] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeUnknown];
> +  [[FIRMessaging messaging] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeUnknown];
> }
> ```
> 
> see pubic repo [here](https://github.com/anthonyhunter/flutterfire/commit/e8611a8dec629534434658eaea4dfe936749ac5f#diff-926b26fe3f9119fb3548066f1b05028306ff8766f9a04abba0fefdb5dac5c0b2)
