### ISSUE TITLE
🐛 [cloud_firestore: ^3.1.6]  app is crashing in release mode but working fine in debug mode 

### ISSUE THREAD

**Issue by pranavo72bex** [FirebaseExtended/flutterfire#8004]
## Bug report

**Describe the bug**
when I applied proguard rules in production mode it start crashing

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
    }

Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Debian GNU/Linux 11
    (bullseye) 5.10.0-11-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

  android_path_provider: ^0.3.0
  bottomnav:
    path: ./bottomnav
  cached_network_image: ^3.1.0
  camera: ^0.9.4+6
  chewie: ^1.2.2
  cloud_firestore: ^3.1.6
  connectivity_plus: ^2.0.3
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  file_picker: ^4.2.4
  firebase_auth: ^3.1.0
  firebase_auth_oauth: ^1.0.3
  firebase_core: ^1.10.6
  firebase_database: ^9.0.5
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.4

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
@pranavo72bex 
Can you provide the complete crash log along with a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) ?

**Comment by pranavo72bex** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/7988 
- my issue is the same sorry for opening a new issue but please fix this issue with minifyEnabled true

**Comment by darshankawar** [comment]
Closing this as duplicate. Please follow-up in original issue which is in pipeline to be fixed and released.

**Comment by pranavo72bex** [comment]
please keep this issue in high priority. I have no problem using proguard with other packages except this one. keep this in high priority because it is a very old issue :pray:
