### ISSUE TITLE
FirebaseAuthPlugin: Error codes are not forwarded to Dart

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#802]
Hi,

I just found out that if an error happens on the FirebaseAuth side like "email already used" I will only get an 

```Dart
      throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
```
with errorCode = "exception" and an error message that isn't localized which isn't really helpful.

Looking at the Java side of the plugin made it obvious

```Java
 private class SignInCompleteListener implements OnCompleteListener<AuthResult> {
    private final Result result;

    SignInCompleteListener(Result result) {
      this.result = result;
    }

    @Override
    public void onComplete(@NonNull Task<AuthResult> task) {
      if (!task.isSuccessful()) {
        Exception e = task.getException();
        result.error(ERROR_REASON_EXCEPTION, e.getMessage(), null);
      } else {
        FirebaseUser user = task.getResult().getUser();
        ImmutableMap<String, Object> userMap = mapFromUser(user);
        result.success(userMap);
      }
    }
  }

This should actually be a [FirebaseAuthException](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthException)

which has a `GetErrorCode` method. Please change that so that Apps can react on error conditions with their own texts.

**Comment by VisheshAtWork** [comment]
The error does get caught even when  the user isn't registered. I tried to to resetPassword using firebaseAuth and tried to catch the Platform Exception when the user isnt found. The catch block doesn't get executed. I request to reopen this. The code I used is below and the exception too.  

` RaisedButton(
                  color: Colors.black,
                  onPressed: () async {
                    if (email != null) {
                      try {
                        await _authService.resetPassword(email);
                      } on PlatformException{
                          _sk.currentState.showSnackBar(SnackBar(
                          content: Text('This Email is Not Registered'),
                          backgroundColor: Colors.red,
                        ));
                      } catch (e) {
                        print('catch $e');
                        _sk.currentState.showSnackBar(SnackBar(
                          content: Text(e.toString()),
                          backgroundColor: Colors.red,
                        ));
                      } 
                        _sk.currentState.showSnackBar(SnackBar(
                          content: Text(
                              'Link to reset Sent successfully,Please check your inbox'),
                          backgroundColor: Colors.amber,
                        ));
                    } else {
                      _sk.currentState.showSnackBar(SnackBar(
                        content: Text('Enter a Valid Email'),
                        backgroundColor: Colors.red,
                      ));
                    }
                  },
                  child: Text(
                    'Reset Password',
                    style: TextStyle(color: Colors.white),
                  ),
                )`

I/flutter (24601): PlatformException(ERROR_USER_NOT_FOUND, There is no user record corresponding to this identifier. The user may have been deleted., null)
 
But the catch block doesn't execute.
