### ISSUE TITLE
Problem with footerbuilder authAction provider

### ISSUE THREAD

**Issue by mohayo** [FirebaseExtended/flutterfire#8033]
Good day Flutter fire team, i think there is an issue with the footerBuilder function of this package.

it takes in a context and an AuthAction but when ever the state of the page changes from sign in to register, the AuthAction doesn't change. This works properly in the subtitleBuilder method.

To buttress, this does not work

```
   footerBuilder: (context, action) {
                      //  print(action);
                        return Center(
                          child: Padding(
                            padding: const EdgeInsets.only(top: 16),
                            child: Center(
                                child: action == AuthAction.signIn
                                    ? const Icon(
                                        Icons.fingerprint,
                                        size: 55.0,
                                        color: Colors.blue,
                                      )
                                    : null),

But this works fine
subtitleBuilder: (context, action) =>
                          action == AuthAction.signIn
                              ? const Text('Sign In page')
                              : const Text('Sign Up page'),
```

I have also used the commented print statement to view the AuthAction and it doesn't change from signIn to signUp.

**Comment by darshankawar** [comment]
@mohayo 
Are you referring to `flutterfire_ui` plugin ?
If so, can you provide your `flutter doctor -v`, `pubspec.yaml` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) including actual vs expected behavior ?

Thanks.
