### ISSUE TITLE
[📚] Documentation improvement for crashlytics when initialization directly from Dart

### ISSUE THREAD

**Issue by fionues** [FirebaseExtended/flutterfire#8040]
When reading the documentation for FlutterFire initialization it is stated that things like google-services.json needed for the manual installation can safely be removed.
<img width="924" alt="Bildschirmfoto 2022-02-08 um 09 00 09" src="https://user-images.githubusercontent.com/53770528/152943578-bc668ae5-6187-4982-8e7d-eae0a1d5656e.png">

But when reading the Crashlytics installation guide it says to add this to android/app/build.gradle `apply plugin: 'com.google.firebase.crashlytics'` which seems to need `apply plugin: 'com.google.gms.google-services'` which than again seems to need a google-services.json. So how is the correct setup?

**Error logs:**

I get this error log if only `apply plugin: 'com.google.firebase.crashlytics'` is added:
```* What went wrong:
A problem was found with the configuration of task ':app:uploadCrashlyticsMappingFileRelease' (type 'UploadMappingFileTask').
  - In plugin 'com.google.firebase.crashlytics' type 'com.google.firebase.crashlytics.buildtools.gradle.tasks.UploadMappingFileTask' property 'googleServicesResourceRoot' doesn't have a configured value.

    Reason: This property isn't marked as optional and no value has been configured.

    Possible solutions:
      1. Assign a value to 'googleServicesResourceRoot'.
      2. Mark property 'googleServicesResourceRoot' as optional.

    Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#value_not_set for more details about this problem.
```

And this if `apply plugin: 'com.google.gms.google-services'` and `apply plugin: 'com.google.firebase.crashlytics'` is added but not google-services.json exists:
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  [/Users/fionanueesch/Desktop/DUDA/02_projects/07_ecoo/ecoo-app/android/app/src/debug/google-services.json]()
  [/Users/fionanueesch/Desktop/DUDA/02_projects/07_ecoo/ecoo-app/android/app/src/google-services.json]()
  [/Users/fionanueesch/Desktop/DUDA/02_projects/07_ecoo/ecoo-app/android/app/src/Debug/google-services.json]()
  [/Users/fionanueesch/Desktop/DUDA/02_projects/07_ecoo/ecoo-app/android/app/google-services.json]()```

**Comment by darshankawar** [comment]
@fionues 
Check [this](https://firebase.flutter.dev/docs/cli/#usage) document and see if it helps.

Also, the crashytics installation guide [here](https://firebase.flutter.dev/docs/crashlytics/overview#2-optional-platform-integration) mentions, the platform-integration is optional, so can you try to not add those integrations and see if it helps ?

If you are migrating from manual to dart initialization, check [this](https://firebase.flutter.dev/docs/manual-installation#migrating-to-dart-only-initialization) document and see if it helps.

**Comment by fionues** [comment]
> @fionues Check [this](https://firebase.flutter.dev/docs/cli/#usage) document and see if it helps.

Ah thank you! Yes this helps.
