### ISSUE TITLE
🐛 [firebase_messaging] iOS 15 devices not receiving push notification in foreground app, when "content-available" is 1 or true

### ISSUE THREAD

**Issue by GKPK** [FirebaseExtended/flutterfire#8042]
## Bug report

**Describe the bug**

on iOS 15 devices,  when the app is in foreground and receives a push notification with "content-available" is "1" or "true" then "didReceiveRemoteNotification" handler is not fired and dart "onMessage" is not called in Flutter app.

In FLTFirebaseMessagingPlugin.m

<img width="768" alt="image" src="https://user-images.githubusercontent.com/23374135/152987952-a1db917a-257a-4776-a9c4-d5aa5f790daf.png">

### Steps to reproduce

1. Go to device settings and turn off the WiFi
2. Enable 4G network on the phone 
3. Launch the app.
4. “Shut Down” the iPhone and wait for 2-3 seconds
5. Turn on the iPhone 
6. Launch the app, and check for receiving push notification, when "content-available" is "1" or "true"

### Expected behavior

"onMessage" should be called when the app is in foreground either when "content-available" is "1/0" or "true/false"

## Additional context

This works fine on iOS < 15 devices both when app is in foreground or background.
This works fine on iOS 15 devices when app is in background.

---

### Flutter doctor

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.2 21D49 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

```

</details>

### Flutter dependencies

firebase_messaging: ^11.2.6

</details>

**Comment by GKPK** [comment]
I found the same problem and here is the solution for same.

https://blog.kulman.sk/workaround-for-didreceiveremotenotification-not-called-in-ios11/

Basically, we need to remove the below condition "if (!notificationDict[@"contentAvailable"])", 

```
    // Don't send an event if contentAvailable is true - application:didReceiveRemoteNotification
    // will send the event for us, we don't want to duplicate them.
    if (!notificationDict[@"contentAvailable"]) {
      [_channel invokeMethod:@"Messaging#onMessage" arguments:notificationDict];
    }
```

**Comment by darshankawar** [comment]
I tried this use case on iOS 14.4.1 on which I am getting push notifications properly, but since I don't have iOS 15 device / OS version to verify this, I'll leave it open and label for further insights from the team.

`firebase_messaging: ^11.2.6`
`Channel stable, 2.10.0`

/cc @russellwheatley

**Comment by b3nni97** [comment]
Have the same problem. Many users have complained that they no longer receive notifications while the app is open. 

Is there a workaround? This is a very critical bug for us...

**Comment by SebAubin** [comment]
Same here. Very critical for us too..

**Comment by GKPK** [comment]
Any further update on this, as this is a very critical issue?

**Comment by juandiago** [comment]
Same issue here on iOS 15 with `content-available` set to `True`

**Comment by GKPK** [comment]
It works mostly for iOS < 15 devices, but for iOS 15 it fails for most of the time for this condition(when the app is in foreground and receives a push notification with "content-available" is "1" or "true" then "didReceiveRemoteNotification" handler is not fired and dart "onMessage" is not called in Flutter app.)

**Comment by SebAubin** [comment]
@GKPK Did rebooting your device or uninstalling/installing the app fix your problem?

**Comment by GKPK** [comment]
Yes, but again the issue is back after some other attempts.

**Comment by SebAubin** [comment]
Same for us. We're considering going back directly to APNs for our iOS platforms..

**Comment by GKPK** [comment]
@russellwheatley Please review the comment on your PR and let me know if that works.

**Comment by SebAubin** [comment]
I just don't understand why it' not working and suddenly uninstalling the app fix the problem temporarily.

**Comment by GKPK** [comment]
Any update on this PR, when this will be approved and released with a next version, as this fix is important.

**Comment by russellwheatley** [comment]
Hey @GKPK, there is a question regarding your PR feedback [here](https://github.com/FirebaseExtended/flutterfire/pull/8202) 😄
