### ISSUE TITLE
[firebase_message] plugin Future never rejects if app is tested on simulator

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#805]
## Steps to Reproduce
I have integrated the firebase message plugin inside my login call but the problem is that the future value never rejects ,it works fine for device since push works fine for ios device but in simulator my code never goes inside the catch block

```dart
login().then((token){
                print("token is recieved with a value");
                return _firebaseMessaging.getToken();
              }).then((firebaseToken){
                print("got a value from firebaes token");
              })
              .catchError((e){
                print("could not get the firebase token value");
                print("stack trace value is unknown");
              });
```

**Comment by kroikie** [comment]
@ajaybeniwal

The issue at https://github.com/flutter/flutter/issues/18259 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by helenaford** [comment]
Closing as stale. @ajaybeniwal please try using the latest version.
