### ISSUE TITLE
🐛 [firebase_performance] No implementation found for method Trace#stop on channel plugins.flutter.io/firebase_performance

### ISSUE THREAD

**Issue by dsgriffin** [FirebaseExtended/flutterfire#8057]
## Bug report

**Describe the bug**

I receive a `MissingPluginException` on `firebase_performance` versions `8.0.0` & above:

```
No implementation found for method Trace#stop on channel plugins.flutter.io/firebase_performance
```

The bug is not present on `7.0.1`

### Steps to reproduce

Set up a project that uses `firebase_performance v8.0.0` and above, when navigating across pages that utilize `newTrace`, `start` & `stop` I am running into this exception every time.

Reverting `firebase_performance` to versions before `8.0.0` resolves the issue.

**Comment by darshankawar** [comment]
@dsgriffin 
Can you provide `flutter doctor -v` ?
Also, I tried the plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance/firebase_performance/example) using [latest](https://pub.dev/packages/firebase_performance/install) plugin version, ran it on iOS, although it doesn't have stop trace, but running other traces worked well properly without any issues.
Can you try the same and see if you still get same behavior as you reported ?
