### ISSUE TITLE
🐛 [firebase_database] orderByChild method not working on 9.X.X in android

### ISSUE THREAD

**Issue by Deep-Focus-lab** [FirebaseExtended/flutterfire#8081]
## Bug report

**Describe the bug**
[ orderByChild ] method is not working in android devices after updating 9.0.6. I tried to run in other 9.X.X versions but on luck.
It is working fine in 8.X.X versions. 

### Steps to reproduce

Without specifying any query constraints, reading data will return all data within the node. If you wish to query your node for a subset of data, the package provides utilities to do so. For example, we could choose to order our data by an "age" property, and limit the returns returned:

DatabaseReference ref = FirebaseDatabase.instance.ref("users");

Query query = ref.orderByChild("age").limitToFirst(10);

DataSnapshot event = await query.get();

Dont forget to Index Your Data inside firebase console!!
https://firebase.google.com/docs/database/security/indexing-data

**Comment by darshankawar** [comment]
@Deep-Focus-lab 
Can you provide `flutter doctor -v`, database plugin version you are using along with a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior you are reporting ?

Thanks.
