### ISSUE TITLE
🐛 [firebase_messaging] Notifications arent being received on iOS 15+

### ISSUE THREAD

**Issue by Letalus** [FirebaseExtended/flutterfire#8094]
## Bug report

Hey guys, so I found this bug by accident. The notifications within the app were working without a problem until I upgraded one of my iOS mobile phones to the latest version 15.3.0.
Then suddenly I stopped receiving notifications and I wondered. I tested it on my other iOS mobile phones which were not yet upgraded and the notifications were still working.

I haven't yet checked out the sample app to make a reproducible example because it seems like this bug has been introduced with the latest iOS Update and I first wanted to check out if multiple people have the same issue until I create a reproducible example.

Btw. on android everything is working perfectly fine.

Edit 1:
I tested all of the above code on real android and iOS devices

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.1)
[✓] VS Code (version 1.63.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

Dart SDK 2.16.0
Flutter SDK 2.10.0
dayblizz 0.1.29+29

dependencies:
- app_settings 4.1.1 [flutter]
- async 2.8.2 [collection meta]
- auto_size_text 3.0.0 [flutter]
- auto_size_text_background 3.0.0-nullsafety.0 [flutter]
- better_player 0.0.81 [flutter cupertino_icons wakelock meta flutter_widget_from_html_core visibility_detector path_provider collection xml]
- bubble 1.2.1 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.0.0 [flutter]
- clipboard 0.1.3 [flutter]
- connectivity_plus 2.2.0 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- date_format 2.0.5
- detectable_text_field 2.0.3 [flutter]
- device_info 2.0.3 [flutter device_info_platform_interface]
- extended_image 6.0.1 [extended_image_library flutter meta]
- file_picker 4.3.3 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_analytics 9.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.5.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.0.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.2.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.2.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flare_flutter 3.0.2 [collection flutter meta]
- flare_loading 3.0.0 [flare_flutter flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_ffmpeg 0.4.2 [flutter]
- flutter_group_sliver 0.0.2 [flutter]
- flutter_keyboard_visibility 5.1.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.2.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_mailer 2.0.1 [flutter]
- flutter_native_image 0.0.6+1 [flutter]
- flutter_share_me 1.2.0 [flutter lint]
- flutter_sticky_header 0.6.0 [flutter value_layout_builder]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- get_it 7.2.0 [async collection]
- giphy_picker 2.0.0 [flutter http]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- image 3.1.1 [archive meta xml]
- image_cropper 1.4.1 [flutter]
- image_editor 1.0.2 [flutter]
- image_gallery_saver 1.7.1 [flutter]
- image_picker 0.8.4+6 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- image_size_getter 1.0.0 [collection hashcodes]
- infinite_listview 1.1.0 [flutter]
- iso_countries 2.1.0 [flutter]
- move_to_background 1.0.2 [flutter]
- package_info 2.0.2 [flutter]
- path_provider 2.0.8 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- percent_indicator 4.0.0 [flutter]
- permission_handler 9.0.1 [flutter meta permission_handler_platform_interface]
- photo_manager 1.3.10 [flutter]
- photofilters 2.0.1 [flutter image meta path_provider]
- pinch_zoom 1.0.0 [flutter]
- preload_page_view 0.1.6 [flutter]
- provider 6.0.2 [collection flutter nested]
- receive_sharing_intent 1.4.5 [flutter]
- rxdart 0.27.3
- screenshot 1.2.3 [flutter]
- scrollable_positioned_list 0.2.3 [flutter collection]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sliver_tools 0.2.5 [flutter]
- social_share 2.1.1 [flutter path_provider]
- url_launcher 6.0.18 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.2.18 [flutter video_player_android video_player_avfoundation video_player_platform_interface video_player_web html]
- video_trimmer 0.2.4 [flutter video_player video_thumbnail path_provider intl path flutter_ffmpeg]
- visibility_detector 0.2.2 [flutter]

transitive dependencies:
- archive 3.1.11 [crypto path]
- args 2.3.0
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- connectivity_plus_linux 1.2.0 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.0 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- cupertino_icons 1.0.4
- dbus 0.6.8 [args ffi meta xml]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- extended_image_library 3.1.2 [crypto flutter http_client_helper path path_provider]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+6 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.13 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.0+5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.1.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.13 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.7 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_linux 0.4.1+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- flutter_widget_from_html_core 0.8.5+1 [csslib flutter fwfh_text_style html]
- fwfh_text_style 2.7.3+1 [flutter]
- hashcodes 2.0.0
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_client_helper 2.0.2 [http]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.5 [flutter flutter_web_plugins image_picker_platform_interface pedantic]
- image_picker_platform_interface 2.4.3 [flutter http plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- js 0.6.3
- linkify 4.1.0
- lint 1.8.2
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- nm 0.4.3 [dbus]
- octo_image 1.0.1 [flutter flutter_blurhash]
- path 1.8.1
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.11 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.10 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.0.9 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.0.4 [file flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.0.4 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_linux 2.0.3 [flutter]
- url_launcher_macos 2.0.3 [flutter]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.8 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.5 [crypto]
- value_layout_builder 0.3.1 [flutter]
- vector_math 2.1.1
- video_player_android 2.2.17 [flutter video_player_platform_interface]
- video_player_avfoundation 2.2.18 [flutter video_player_platform_interface]
- video_player_platform_interface 5.0.1 [flutter plugin_platform_interface]
- video_player_web 2.0.6 [flutter flutter_web_plugins pedantic video_player_platform_interface]
- video_thumbnail 0.4.3 [flutter]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.3.10 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]

</details>

---

**Comment by darshankawar** [comment]
@Letalus 
Does it work when app is in background ? or not at all under any state (i.e forground, background or terminated) ?
Are you passing `content-available` flag / value when you don't receive the notification ?
Can you try with and without that flag too ?

**Comment by Letalus** [comment]
@darshankawar thanks alot for your quick response! :)

Sadly, it doesnt work in any state on my iOS 15 device.

I'm sorry to ask, but where do I have to pass the content-available flag directly (maybe within the notification itself?)
Once I know the answer for this, I'll try it directly

**Comment by darshankawar** [comment]
@Letalus 
So, `content-available` on iOS is equivalent of `high-priority` in Android. You can read more about it [here](https://firebase.flutter.dev/docs/messaging/usage/#message-types) and also try to check if you receive message when app is in foreground with this setting:  https://firebase.flutter.dev/docs/messaging/usage/#foreground-messages

The reason I am asking you to verify using `content-available` is because there's similar issue reported for iOS 15 but only using that flag: https://github.com/FirebaseExtended/flutterfire/issues/8042

**Comment by Letalus** [comment]
okay perfect thanks @darshankawar will check it right away and update you about my findings

**Comment by Letalus** [comment]
Okay, so we removed the content-available property, deployed the new api version and tested it. The result: The notifications were still not working. Once we switched it back again, it also wasnt working.

If you have any further ideas, I'm happy to try them out :)

**Comment by eli-me** [comment]
I am having the same issue here, notifications are not working on iOS 15 and I am stuck in what to do.

**Comment by nathanogunleye** [comment]
Same here, very frustrating. Works on Android fine but the same code doesn't work on iOS 15. I've been testing with a real device too

**Comment by Letalus** [comment]
I understand the frustation of everyone, who experienced this bug.  To get this issue faster fixed, please only add a comment, if you have some more relevant information and PLEASE upvote the main issue.

**Comment by darshankawar** [comment]
@Letalus 
Can you check if `didReceiveRemoteNotification` method is getting called at all ? Do you get any error log after push notification is sent and when app doesn't respond ?

I would also suggest to check and confirm the APNS settings per the [document](https://firebase.flutter.dev/docs/messaging/apple-integration/) is correct just to make sure this isn't a setting / config issue.

**Comment by SebAubin** [comment]
We have the same issue. Android works perfectly but iOS nothing.

**Comment by jan-koz** [comment]
Same problem here, works good on android and lower versions of iOS (less than 15)

**Comment by Letalus** [comment]
Alright so @darshankawar sorry for my late response, I had quite a busy week until now but managed to test both of your suggestions.

This is now some kind of magic, I dont really understand.
I tested today the notifications again and voila they where working again.

I did not change anything within the iOS or flutter side regarding the notifications except one thing.

I upgraded to the latest flutter version 2.10.2. Now it is working.
So everyone, who has the same issue like I do. Try upgrading your flutter project and also xcode as well as cocoapods. Maybe this will also fix it for you :)

**Comment by SebAubin** [comment]
After updating to Flutter 2.10.2 we still have the issue. It seems very intermittent.. 

We have the JSON response:
```
{
	"multicast_id": <id>,
	"success": 1,
	"failure": 0,
	"canonical_ids": 0,
	"results": [
		{
			"message_id": "<id>"
		}
	]
}
```

But our app is not receiving the push on iOS. The only way to fix it is to restart our device (iPhone XR).

**Comment by Letalus** [comment]
Edit: True I also deinstalled the app and installed it again. Plus the upgrade (explained in my above comment) and it started working
