### ISSUE TITLE
Firebase storage, trying to upload image when file is null

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#811]
```dart
class StorageFileUploadTask extends StorageUploadTask {
  final File _file;
  StorageFileUploadTask._(this._file, FirebaseStorage firebaseStorage,
      String path, StorageMetadata metadata)
      : super._(firebaseStorage, path, metadata);

  @override
  Future<void> _start() async {
    final String downloadUrl = await FirebaseStorage.channel.invokeMethod(
      'StorageReference#putFile',
      <String, dynamic>{
        'app': _firebaseStorage.app?.name,
        'bucket': _firebaseStorage.storageBucket,
        'filename': _file.absolute.path,
        'path': _path,
        'metadata':
            _metadata == null ? null : _buildMetadataUploadMap(_metadata),
      },
    );
    _completer
        .complete(new UploadTaskSnapshot(downloadUrl: Uri.parse(downloadUrl)));
  }

```

Shouldn't the plugin check here if file exists?

I go `E/flutter (27353): NoSuchMethodError: The getter 'absolute' was called on null.` since I was trying to pick an image from my Drive folder, and I didn't check If the image file was there.

Just wanted to put it out there.

**Comment by kroikie** [comment]
@matejthetree

The issue at https://github.com/flutter/flutter/issues/18153 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age of this issue and that Storage has had a major rework since; I'm going to close this issue in favour of trying the latest release.
