### ISSUE TITLE
🐛 [firebase_messaging_platform_interface  v: 3.1.6]  the argument type 'map<string, int>?' can't be assigned to the parameter type 'map<string, int>' because 'map<string, int>?' is nullable and 'map<string, int>' isn't

### ISSUE THREAD

**Issue by Mobigic-Vaibhav** [FirebaseExtended/flutterfire#8117]
## Bug report

**Describe the bug**
This is unhandled  null safety issue,where  the fcm methods like onmessage,background message throwing exception of the above title i posted

### Steps to reproduce

Steps to reproduce the behavior: i got into this issue when i update my old APK into the new stable dart,flutter versions aslo i change my compiledTimeSdk to 31 also  i migrated my apk with new versions of all packages

```
................................................................. I also found the solution for it...........................
solution:.1) Go to your method_channel_messeging.dart file which is prebuild by the package 
2) they forget to add  null check(!) two overrides namely   requestPermission() and  getNotificationSettings()
3) in thoes overrides in catch block  
from this 
return convertToNotificationSettings(response);
to this
return convertToNotificationSettings(response!);
```

**Comment by darshankawar** [comment]
@Mobigic-Vaibhav 
Can you provide a minimal reproducible code sample along with `flutter doctor -v` and `pubspec.yaml` that replicates the error you reported ?

Also, can you try the plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) and see if you still get same error using it ?
