### ISSUE TITLE
🐛 [firebase_analytics] Firebase Dashboard Users In Last 30 Minutes showing always zero after plugin update

### ISSUE THREAD

**Issue by Jai05-techie** [FirebaseExtended/flutterfire#8131]
Hi,

After upgrading Flutter SDK to 2.8.1 and Firebase Plugins. Realtime active users count showing zero always in Firebase console Dashboard -> Users in last 30 minute.

We have more than 5k app users before upgrading SDK it was working fine showing 2k plus users last 30 minute, but after upgrading the flutter SDK and plugins it came down to zero. Help me out to fix this issue. Thanks in advance!

[Attached Screenshot](https://i.stack.imgur.com/aUfQj.png)

Flutter Plugin,

```
firebase_analytics: ^9.1.0
firebase_core: ^1.10.0
```

Android Dependencies,

```
implementation 'com.google.firebase:firebase-analytics:20.1.0'
```

Flutter Doctor,

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-IN)
    • Flutter version 2.8.1 at
      /Users/maclap/Documents/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/maclap/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • Nokia 4 2 (mobile) • DT89571GA1962616726 • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome              • web-javascript • Google Chrome 98.0.4758.102

• No issues found!
```

**Comment by darshankawar** [comment]
@Jai05-techie 
I suggest you to raise this issue in firebase [support](https://firebase.google.com/support) as I am not sure if this would be related to `firebase_analytics` plugin, because the plugin is a wrapper around native firebase sdks and the plugin usually doesn't do anything while sending the log events and analytics to the google.

**Comment by Jai05-techie** [comment]
@darshankawar thanks for the suggest. Still i've not solved and not got where i missed. I've seen in firebase community slack some developers facing same issue. So i raised a ticket to _Firebase Support Team._

**Comment by russellwheatley** [comment]
@Jai05-techie, please let us know what they say. Thanks!

**Comment by Jai05-techie** [comment]
Hi all,

@darshankawar thanks for the replying and suggestion. As you said there is no problem with `firebase_analytics`  plugin. My production application issue is resolved there is no code change i did. I think Firebase team have done some update hence it caused issue with my production application realtime count and delay in update. After 4th day of issue it got resolved. Here by below i attached screenshot of reply mail from firebase support team. @russellwheatley 

<img width="1067" alt="Screenshot 2022-02-28 at 11 39 51 AM" src="https://user-images.githubusercontent.com/62050139/155934354-dc759f3e-c56e-4e17-b4e6-8340d25064c7.png">

**Comment by russellwheatley** [comment]
Thanks for providing an update @Jai05-techie, very much appreciated 🙏
