### ISSUE TITLE
🐛 Firebase Cloud Messaging - iOS notification do not arrive, while Android and Web do.

### ISSUE THREAD

**Issue by safield** [FirebaseExtended/flutterfire#8133]
I am using FCM in flutter with version...

    firebase_core : ^1.7.0
    firebase_messaging: ^10.0.8

I am testing on iOS 15.3.1.

FCM notifcations work on Android devices and web, but do not arrive on my development iOS (physical device).

I have gone through [this guide](https://firebase.flutter.dev/docs/messaging/overview), and specifically gone through [this guide ](https://firebase.flutter.dev/docs/messaging/apple-integration)multiple times to ensure setup is correct.

To be explicit...

-in my xcode project I have added push notification capability + Backmodes (Remote notification and background fetch).
-I have created an APN key and uploaded it to my firebase project 
-I have requested ios permissions in my app and confirmed they have been authorized
-the guide mentions to create a provision profile, but m code is set to 'Xcode managed provision profile' so I skipped this step.
-went into iOS settings and confirmed that notification permissions are granted.

When testing, device targetted notifications sent from my backend (using a specific fcm registration token) arrive on both iOS and android in foreground and background. On iOS the arrive in neither foreground or background. More specifically, the onMessage callback is not triggered, and when the app is terminated, no system tray notification arrives.

When sending from the firebase console, notifications arrive for both android and web, but do not arrive on ios at all.

Since I have exhaustively confirmed that all steps defined in the setup guide have been carried out, I am left to submit this issue.

```
Flutter Doctor
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-CA)
    • Flutter version 2.8.1 at /Users/scott/.flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102

! Doctor found issues in 2 categories.

```

**Comment by darshankawar** [comment]
@safield 
Are you using iOS 15 ? Can you provide `flutter doctor -v` ?

When you say notifications don't arrive, do any of these streams get trigger or not ? `onMessage, `onBackgroundMessage` ?
What kind of message are you sending ? Is it a data-only or notification message ?

**Comment by safield** [comment]
@darshankawar 

I have updated the initial post with the info.

Specifically, onMessage is not trigger when the app is in the foreground.

I am sending messages with a notification added. In addition I am sending messages from the FCM console with a title and body, which I assume is a message with an attache notification.

**Comment by darshankawar** [comment]
Thanks for the updates. Considering you are on iOS 15.3.1, there are few similar issues reported specific to iOS > 15 on which notifications aren't received. See this similar issue for your reference: https://github.com/FirebaseExtended/flutterfire/issues/8094. and this in which the notifications don't arrive in foreground if `content-available` is 1 or true. https://github.com/FirebaseExtended/flutterfire/issues/8042
I suggest you to follow-up in both issues for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
