### ISSUE TITLE
flutterfire config Bad state: expecting only on entry for depdency

### ISSUE THREAD

**Issue by gumdum** [FirebaseExtended/flutterfire#8137]
On MacOS using most recent npm of flutterfire

-> % flutterfire config
Unhandled exception:
Bad state: expecting only one entry for dependency
#0      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:19:9)
#1      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:103:68)
#2      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113:45)
#3      MapMixin.forEach (dart:collection/maps.dart:123:13)
#4      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112:7)
#5      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:103:15)
#6      PubSpec.loadFile (package:pubspec/src/pubspec.dart:121:15)
<asynchronous suspension>
#7      Package.load (package:flutterfire_cli/src/common/package.dart:54:21)
<asynchronous suspension>
#8      FlutterApp.load (package:flutterfire_cli/src/flutter_app.dart:39:21)
<asynchronous suspension>
#9      main (file:///Users/calvinellis/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:33:24)
<asynchronous suspension>

-> % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.64.2)
[✓] VS Code (version 1.58.1)
[✓] VS Code (version 1.58.1)
[✓] Connected device (3 available)
    ! Error: Gumdum is busy: Fetching debug symbols for Gumdum. Xcode will continue when Gumdum is finished. (code -10)
[✓] HTTP Host Availability

• No issues found!

-> % flutter doctor --verbose
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
    • Flutter version 2.10.1 at /Users/calvinellis/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision db747aa133 (12 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/calvinellis/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Users/calvinellis/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/calvinellis/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/calvinellis/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Users/calvinellis/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Users/calvinellis/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5284.40/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Users/calvinellis/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.92/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.58.1)
    • VS Code at /Users/calvinellis/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.58.1)
    • VS Code at /Users/calvinellis/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Gumdum (mobile) • 00008101-001924982E85001E • ios            • iOS 15.2.1 19C63
    • macOS (desktop) • macos                     • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 98.0.4758.102
    ! Error: Gumdum is busy: Fetching debug symbols for Gumdum. Xcode will continue when Gumdum is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
@gumdum 
According to [this](https://firebase.flutter.dev/docs/cli/#reporting-an-issue) CLI document, all issues related to this tool need to be reported in dedicated repo: https://github.com/invertase/flutterfire_cli/issues, so please open this in linked repo.
Closing from here.
