### ISSUE TITLE
🐛 [flutterfire CLI] wrong google user

### ISSUE THREAD

**Issue by subzero911** [FirebaseExtended/flutterfire#8145]
I run `flutterfire configure`
It automatically chooses the user

![image](https://user-images.githubusercontent.com/12999702/155084305-83f350e7-cc03-4940-8061-59254b6c405d.png)

But this user doesn't have access to the Firebase project. So this config utility fails.
I actually need s.molchanovskiy@notamedia.ru as a user. How can I choose the custom user?
I tried to login in Chrome as s.molchanovskiy@notamedia.ru into Firebase, but configuration utility still uses sergeymolchanovsky@gmail.com address.

**Comment by darshankawar** [comment]
@subzero911 
According to [this](https://firebase.flutter.dev/docs/cli/#reporting-an-issue) CLI document, all issues related to this tool need to be reported in dedicated repo: https://github.com/invertase/flutterfire_cli/issues, so please open this in linked repo.
Closing from here.
