### ISSUE TITLE
🐛 [firebase_messaging] cannot handle event when "notifications" object was null

### ISSUE THREAD

**Issue by billbull21** [FirebaseExtended/flutterfire#8146]
## Bug report

i can't handle message event when i tried to set notifications object to null via REST API. 
I purposely made the object null, so i can replace default notifications from the plugin to **flutter local notification** plugin.
it works when it comes from backgrounds, but when i currently opening my app, i can't get my print inside the onMessage listener.

### Steps to reproduce

1. setup fcm correctly like the documentation says.
2. tried to send object like the code json below. there is no object for notifications. because i do it purposely.
`{
	"data": {
    "id": 34463,
    "title": "INTERNAL ORDER",
    "body": "satu transaksi internal order butuh approval segera!",
    "name": "INTERNAL ORDER"
  },
  "registration_ids": [
"_my user token here_"
  ]
}`

### Expected behavior

i could see my print inside onMessage listener.

**Comment by darshankawar** [comment]
@billbull21 
Based on the use case you described, ie, not sending notification object, in real time scenario, this may not occur, so I am not sure if you are verifying a valid scenario. I suggest you to ask this question on support channels like StackOverflow. Closing from here. If you disagree or think this is a bug in the plugin, write in comments and I'll reopen it.

**Comment by GRyabkin** [comment]
@darshankawar this is actually real time scenario, I am using chat 3rd party [messaging service](connectycube.com) which sends push notifications with null notification object and flutterfire can't handle it, `onMessageOpenedApp` is not called
