### ISSUE TITLE
FirebaseAuthPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#815]
## Steps to Reproduce
1. Include Firebase_auth version 0.5.10 (latest)
2. Run `flutter run`

Error is thrown right after that.

`Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.5.10\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.`

## Flutter version
`Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (2 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58`

**Comment by mojason-81** [comment]
Is there some fix I can apply for this that's not shown here or in #17976?  I'm getting this error on a fresh flutter app.

firebase_auth 0.15.3+1
flutter 1.13.6
dart 2.8.0
openjdk 11.0.5 (could this be the issue?)
zorin OS 15 (Ubuntu 18.04)
