### ISSUE TITLE
[firebase_auth] Because firebase_auth depends on firebase_auth, version solving failed. pub finished with exit code 65

### ISSUE THREAD

**Issue by raphache** [FirebaseExtended/flutterfire#8152]
```
Because firebase_auth depends on firebase_auth, version solving failed.
pub finished with exit code 65
```

**Comment by raphache** [comment]
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0

**Comment by darshankawar** [comment]
@raphache 
Can you provide `pubspec.yaml` and the complete console error you get ?
It seems you'll need to update plugins to latest versions to resolve this conflict. So go through the plugins you are using and make sure they are all on latest versions.

**Comment by eyoeldefare** [comment]
I just started a new flutter project and I get this error.

**Comment by eyoeldefare** [comment]
Apparently, this issue is caused by naming your flutter project the same name as this package.
