### ISSUE TITLE
Firebase Authentication currentUser() returns null

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#817]
This is about Flutter Firebase Authentication plugin.<br> I am trying to send a verification email after creating a new user, but sendEmailVerification() internally uses currentUser(). The error is the same on Android and IOS.<br>

First two lines successfully return FirebaseUser. The third returns null. Forth, if third is commented throws a null reference error. 

Thanks,
Boris

    user = await _auth.createUserWithEmailAndPassword(email: email, password: password); 
    // result is FirebaseUser
    user = await _auth.signInWithEmailAndPassword(email: email, password: password);
    // result is FirebaseUser    
    user = await _auth.currentUser();
    // result is null    
    await user.sendEmailVerification();
    //null reference, because it internally uses .currentUser()

This has posted as StackOverflow question: https://stackoverflow.com/questions/50439051

**Comment by ISimplifyComplexity** [comment]
@kroikie Why is this closed?! There's no resolution!
