### ISSUE TITLE
firebase_core FirebaseConfiguration support

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#818]
Right now `FirebaseConfiguration` isn't implemented in firebase_core

Plugin works fine, but this should blocking 1.0 release

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/17763 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release. I believe also that this is already supported.
