### ISSUE TITLE
[firebase_analytics] events logged when launched from xcode but not flutter command line

### ISSUE THREAD

**Issue by xni06** [FirebaseExtended/flutterfire#82]
When I launch the app...

- from within xcode, events are logged in Firebase
- from the flutter command line onto an *Android* emulator, events are logged in Firebase
- from the flutter command line onto an iOS emulator or device, no events are logged in Firebase. In fact, the device doesn't even appear in the Firebase console

This is very confusing. What am I missing that makes it work with xcode but not the flutter command line?

**Comment by Salakar** [comment]
Hey @xni06 - not sure if you still remember this issue but could you provide some more context;

 - what build type were you doing in Xcode vs Flutter CLI, were they release or debug
 - on Firebase Console were you using the StreamView or DebugView to view these events - they don't show in realtime unless you use either of these views

If this is no longer an issue / relevant to you please could you close the issue - or let me know and I'll close it.

Thanks

**Comment by xni06** [comment]
> * What build flavor were you doing in Xcode vs Flutter CLI, were they release or debug builds, and the same build flavor on both Xcode & CLI?

Both Xcode and CLI used the same debug flavor

> * On the Firebase Console were you using the StreamView or DebugView to view these events? 

DebugView

As an aside, Android was fine using CLI

I will investigate again ASAP - thanks.
