### ISSUE TITLE
Only test ad showing in release apk but its showing normal ads in debug apk

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#820]
Implemented firebase admob. Replaced the appId and adUnitId with the my ids. Its showing only test default test ad of admob in the release apk but i'm able to see normal ads on debug apk.

**Comment by kroikie** [comment]
@Ajit121

The issue at https://github.com/flutter/flutter/issues/17714 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by ShabanGomaa** [comment]
any solutions?

**Comment by blasten** [comment]
@Ajit121 Have you tried the latest version of the plugin? This might be fixed already.

**Comment by AnanthanAn** [comment]
Hi , I am also facing same issue. Test ad showing up in debug but not in release , Can anyone help.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
