### ISSUE TITLE
Where is the analogue to FirebaseAuthUI ?

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#821]
Where can I find code that performs the function that FirebaseAuthUI does for Java on Android?

**Comment by kroikie** [comment]
@ErstwhileIII

The issue at https://github.com/flutter/flutter/issues/17706 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by ErstwhileIII** [comment]
Great ... Now after over a year, has anyone been assigned this case? I hope we don't just move things around.

**Comment by Ehesp** [comment]
Firebase UI is out of scope currently. Closing however this may be picked up in the future.
