### ISSUE TITLE
[dynamic_link] what do i need to do to make the deeplink example on ios actually respond to a deeplink?

### ISSUE THREAD

**Issue by rosenstrauch** [FirebaseExtended/flutterfire#8230]
given i launch the example in release mode on ios
and i send it to background
when i click http://demo.demo/demo
then i want to see the app open

what am i missing? seems there is a step i dont have. lets say i have an a pp registered on firebase, and i have entered my custom domain to info.plist and i also have the accompanying googleServices-info.plist in place, what else do i need

**Comment by darshankawar** [comment]
> when i click http://demo.demo/demo

What happens after you click on the link ? Does it throw any error or direct you to website or anything else ?



> given i launch the example in release mode on ios

Can you confirm if `Associated Domains` in xcode is set up for `Release` mode too apart from `debug` ? 
Also provide what iOS version are you using.

**Comment by rosenstrauch** [comment]
ios 15

thanks! after rechecking associated domains the app opens as expected!
