### ISSUE TITLE
Build fails with: Execution failed for task ':app:mapDebugSourceSetPaths'.

### ISSUE THREAD

**Issue by TobiasLenzEconix** [FirebaseExtended/flutterfire#8238]
## Bug report

* What went wrong:

>Execution failed for task ':app:mapDebugSourceSetPaths'.
> Error while evaluating property 'extraGeneratedResDir' of task ':app:mapDebugSourceSetPaths'
   > Failed to calculate the value of task ':app:mapDebugSourceSetPaths' property 'extraGeneratedResDir'.
       Querying the mapped value of provider(interface java.util.Set) before task ':app:processDebugGoogleServices' has completed is not supported

flutter build appbundle

### Steps to reproduce

android/app/build.gradle:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId ".."
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
}

// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
```

android/build.gradle:

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3+'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
         // Add the google services classpath
        classpath 'com.google.gms:google-services:+'

    }

}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

### Expected behavior

The build fails with the above error message.

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
[✓] VS Code (version 1.65.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `Dart SDK 2.16.1
Flutter SDK 2.10.3
AppName 1.0.5+36

dependencies:
- digi_app 1.1.10+17 [flutter connectivity firebase_messaging shared_preferences dartz flutter_html meta provider flutter_bloc get_version cached_network_image webview_flutter easy_localization easy_localization_loader flutter_local_notifications rocket_chat_connector_flutter fluttertoast uuid cupertino_icons web_socket_channel flutter_chat_ui http geocoding adaptive_action_sheet flutter_native_timezone hive dio auto_size_text flutter_secure_storage material_design_icons_flutter image_picker mailer location permission_handler intl flutter_cached_pdfview scroll_to_index maps_launcher platform_maps_flutter webfeed url_launcher flutter_launcher_icons lottie quiver json_annotation enough_mail flutter_app_badger clippy_flutter qr_flutter flutter_widget_from_html flutter_screen_wake file_picker open_file]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- material_design_icons_flutter 5.0.6595 [flutter]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- test 1.19.5 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- adaptive_action_sheet 2.0.1 [flutter universal_io]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- apple_maps_flutter 1.1.0 [flutter]
- archive 3.1.6 [crypto path]
- args 2.3.0
- asn1lib 1.1.0
- async 2.8.2 [collection meta]
- audio_session 0.1.6+1 [flutter flutter_web_plugins rxdart meta]
- auto_size_text 3.0.0 [flutter]
- basic_utils 3.9.4 [http logging json_annotation pointycastle]
- bloc 8.0.3 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- chewie 1.3.0 [cupertino_icons flutter provider video_player wakelock very_good_analysis]
- chewie_audio 1.3.0 [cupertino_icons flutter video_player]
- cli_util 0.3.5 [meta path]
- clippy_flutter 2.0.0-nullsafety.1 [flutter]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity 3.0.6 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- connectivity_for_web 0.4.0+1 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.1+2 [flutter connectivity_platform_interface]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- csv 5.0.1
- cupertino_icons 1.0.4
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- dartz 0.10.1
- dbus 0.7.1 [args ffi meta xml]
- diffutil_dart 3.0.0
- dio 4.0.4 [http_parser path]
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- easy_localization_loader 1.0.0 [http csv yaml xml flutter]
- easy_logger 0.0.2 [flutter]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- enough_convert 1.4.0
- enough_mail 1.3.6 [pedantic event_bus crypto encrypt pointycastle basic_utils xml intl enough_serialization enough_convert collection]
- enough_serialization 1.4.0
- equatable 2.0.3 [collection meta]
- event_bus 2.0.0
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- file_picker 4.5.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging 11.2.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_messaging_platform_interface 3.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.9 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_app_badger 1.3.0 [flutter]
- flutter_bloc 8.0.1 [flutter bloc provider]
- flutter_blurhash 0.6.4 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_cached_pdfview 0.4.1 [flutter flutter_pdfview flutter_cache_manager path_provider path]
- flutter_chat_types 3.3.1 [equatable json_annotation meta]
- flutter_chat_ui 1.5.5 [flutter diffutil_dart equatable flutter_chat_types flutter_link_previewer intl meta photo_view]
- flutter_html 2.2.1 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_layout_grid 1.0.3 [flutter collection meta quiver]
- flutter_link_previewer 2.6.3 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.3.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_math_fork 0.5.0 [flutter flutter_svg provider meta collection tuple]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_pdfview 1.2.2 [flutter]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_screen_wake 1.0.1 [flutter]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- flutter_widget_from_html 0.8.5 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_just_audio fwfh_selectable_text fwfh_svg fwfh_url_launcher fwfh_webview html]
- flutter_widget_from_html_core 0.8.5+1 [csslib flutter fwfh_text_style html]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- frontend_server_client 2.1.2 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- fwfh_cached_network_image 0.7.0+2 [cached_network_image flutter flutter_cache_manager flutter_widget_from_html_core]
- fwfh_chewie 0.7.0+1 [chewie flutter flutter_widget_from_html_core video_player]
- fwfh_just_audio 0.6.2+2 [flutter flutter_widget_from_html_core just_audio]
- fwfh_selectable_text 0.8.3+1 [flutter flutter_widget_from_html_core]
- fwfh_svg 0.7.2 [flutter flutter_svg flutter_widget_from_html_core]
- fwfh_text_style 2.7.3+1 [flutter]
- fwfh_url_launcher 0.6.1+3 [flutter flutter_widget_from_html_core url_launcher]
- fwfh_webview 0.6.2+2 [flutter flutter_widget_from_html_core webview_flutter]
- geocoding 2.0.2 [flutter geocoding_platform_interface]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- get_version 0.2.2 [flutter package_info]
- glob 2.0.2 [async collection file path string_scanner]
- google_maps_flutter 2.1.2 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_flutter_platform_interface 2.1.5 [collection flutter plugin_platform_interface stream_transform]
- graphs 2.1.0 [collection]
- hive 2.0.6 [meta crypto]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- image_picker 0.8.4+10 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- image_picker_for_web 2.1.6 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_platform_interface 2.4.4 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- just_audio 0.9.20 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_audio_platform_interface 4.1.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.4 [just_audio_platform_interface flutter flutter_web_plugins]
- linkify 4.1.0
- location 4.3.0 [flutter location_platform_interface location_web]
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 1.0.2
- lottie 1.2.2 [archive flutter path vector_math]
- mailer 5.1.0 [async logging intl mime path pedantic meta]
- maps_launcher 2.0.1 [flutter flutter_web_plugins url_launcher]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- node_preamble 2.0.1
- numerus 1.1.1
- octo_image 1.0.1 [flutter flutter_blurhash]
- open_file 3.2.1 [flutter ffi]
- package_config 2.0.2 [path]
- package_info 2.0.2 [flutter]
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- photo_view 0.13.0 [flutter]
- platform 3.1.0
- platform_maps_flutter 1.0.2 [flutter google_maps_flutter google_maps_flutter_platform_interface apple_maps_flutter]
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.5.1 [collection convert js]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 2.1.0 [meta]
- qr_flutter 4.0.0 [flutter qr]
- quiver 3.0.1+1 [matcher]
- rocket_chat_connector_flutter 0.1.0 [flutter collection http web_socket_channel]
- rxdart 0.27.3
- scroll_to_index 2.1.1 [flutter]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.9 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- very_good_analysis 2.4.0
- video_player 2.2.19 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.0 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.0 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.7 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 7.5.0
- wakelock 0.6.1+1 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webfeed 0.7.0 [xml intl]
- webkit_inspection_protocol 1.0.0 [logging]
- webview_flutter 2.8.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 2.8.3 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.1 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment]
Looking at the error, it doesn't seem to be related to flutterfire, so closing from here. 
Also as a note, when you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with.

If you think the issue you are getting is due to flutterfire plugin, write in comments, fill out template and we'll address it.

**Comment by TobiasLenzEconix** [comment]
What do you mean?

I used the template and files ind all the flutter doctor command output.
If I uncomment the last line:

// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'

the build succeeds

**Comment by muhammadyusuf-kurbonov** [comment]
Have anyone solved this problem? It seems google-services is using deprecated (and removed) feature of gradle

**Comment by TobiasLenzEconix** [comment]
@muhammadyusuf-kurbonov 
I somehow fixed it. But I am not sure what did the trick.
I think in firebase changed the instructions for android.

e.g. no you need no use
implementation platform('com.google.firebase:firebase-bom:29.2.1') 

instead of:

implementation 'com.google.firebase:firebase-messaging:21.0.1'

but see the whole Firebase Android instruction for details.

Its a shame that no one tells you about the api changes...

**Comment by muhammadyusuf-kurbonov** [comment]
Thank you. I will check 👍👍👍

**Comment by freindlytech** [comment]
I am also facing this issue anybody know  how to fix it ?

**Comment by freindlytech** [comment]
> @muhammadyusuf-kurbonov I somehow fixed it. But I am not sure what did the trick. I think in firebase changed the instructions for android.
> 
> e.g. no you need no use implementation platform('com.google.firebase:firebase-bom:29.2.1')
> 
> instead of:
> 
> implementation 'com.google.firebase:firebase-messaging:21.0.1'
> 
> but see the whole Firebase Android instruction for details.
> 
> Its a shame that no one tells you about the api changes...

It didn't work for me

**Comment by JensLeirens** [comment]
I also had this kind of error with my project. after some reverting back changes i noticed the error only came when using the 
`'com.google.gms:google-services:4.3.10'` dependency. 
after changing back the google service version to 4.3.5 the error was resolved.

I hope this helps

**Comment by muhammadyusuf-kurbonov** [comment]
> I also had this kind of error with my project. after some reverting back changes i noticed the error only came when using the `'com.google.gms:google-services:4.3.10'` dependency. after changing back the google service version to 4.3.5 the error was resolved.
> 
> I hope this helps

THANK YOU! It works!
