### ISSUE TITLE
flutterfire configure command not working

### ISSUE THREAD

**Issue by bouncydragon** [FirebaseExtended/flutterfire#8244]
### Discussed in https://github.com/FirebaseExtended/flutterfire/discussions/8243

<div type='discussions-op-text'>

<sup>Originally posted by **bouncydragon** March  9, 2022</sup>
I have an error after reexecuting `flutterfire configure` I'm planning to change my firebase project to another project. When I executed `flutterfire configure` it throws an error of `FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.` Even thou the project is created fom flutter itself.

here is my `pubspec.yaml`

```version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cached_network_image: ^3.1.0+1
  camera: ^0.9.4+11
  colour: ^1.0.5
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.1.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  http: ^0.13.4
  image_picker: ^0.8.4+8
  intl: ^0.17.0
  meta: ^1.7.0
  path: ^1.8.0
  path_provider: ^2.0.9
  rxdart: ^0.27.3

dev_dependencies:
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  scrollable_positioned_list: ^0.2.3
  shared_preferences: ^2.0.9

flutter:
  uses-material-design: true```

**need your help badly.**</div>

**Comment by darshankawar** [comment]
flutterfire_cli related issues need to be reported in dedicated repo: https://firebase.flutter.dev/docs/cli/#reporting-an-issue
https://github.com/invertase/flutterfire_cli/issues
Closing from here.
