### ISSUE TITLE
Firebase Auth emails with '.al' suffix dont work

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#826]
On iOS if you try this method (im not sure for other create methods)

`FirebaseAuth.instance.linkWithEmailAndPassword()`
with an email something like
`test@test.al` 
it doesn't work on iOS. it seems that the suffix '.al' cant be seems valid. it works fine on android.

**Comment by kroikie** [comment]
@kondasoft

The issue at https://github.com/flutter/flutter/issues/17569 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
Closing as the issue is stale
