### ISSUE TITLE
Dynamic links in Facebook mobile app is not deep linked to app

### ISSUE THREAD

**Issue by Nasrallahelfarra** [FirebaseExtended/flutterfire#8266]
Dynamic links in Facebook mobile app is not deep linked to app
after click link from facebook not open app

**Comment by darshankawar** [comment]
@Nasrallahelfarra 
See [this](https://github.com/FirebaseExtended/flutterfire/issues/2828#issuecomment-1000373978) issue comment for your reference.
Closing from here as this isn't actionable from our end.

**Comment by grubesa** [comment]
I had the same issue. I was able to open the links from different apps except from the Facebook app. 
Finally, I succeeded in handling links from Facebook with help of this [library](https://pub.dev/packages/receive_intent).
@darshankawar don't understand the logic behind it but why you can't do the same as the lib mentioned?
