### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#827]
Just wondering if the Google Analytics data integrated with flutter should be opt in instead of opt out, in line with GDPR..

**Comment by kroikie** [comment]
@absalomedia

The issue at https://github.com/flutter/flutter/issues/17542 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
@anaisbetts this can be done already via some small changes in your iOS/Android projects; https://firebase.google.com/docs/analytics/configure-data-collection?platform=android and then subsequently using `setAnalyticsCollectionEnabled` in Dart to pragmatically toggle data collection on when the user consents to data collection.

We'll get this documented

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release.
