### ISSUE TITLE
Problem with dynamic links

### ISSUE THREAD

**Issue by iriealex** [FirebaseExtended/flutterfire#8282]
I get the following error with dynamic links :

Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, String>'

on the following line :       `utmParameters: linkData['utmParameters'],`

Do not know why because everything is well configured and worked with the last version of dynamic_links

**Comment by LempereurBenjamin** [comment]
Seems to be fixed in this commit : https://github.com/FirebaseExtended/flutterfire/commit/22bbd807d2b3c3f9d9cc8ba817ccb4da931ae887

**Comment by LempereurBenjamin** [comment]
I think that the fix is not released yet.
Maybe @russellwheatley can provide more informations about it.

**Comment by russellwheatley** [comment]
Hey folks, a fix has been [merged](https://github.com/FirebaseExtended/flutterfire/pull/8280) and a new release is imminent. Sorry for the problem 🙏
