### ISSUE TITLE
iOS app failing after Xcode build done.

### ISSUE THREAD

**Issue by mishrhm** [FirebaseExtended/flutterfire#8285]
When Im trying to run my Flutter application on iOS, the Xcode build is getting completed but after getting installed in the simulator the app is getting launched & crashes abruptly. I am not getting any error whatsoever in the Console. 

It was a fully working application in the lower version of Flutter & now I spend some time to migrate it to the latest Flutter SDK version, the android counterpart is running perfectly fine, but I am having issues with the iOS version.

I added GoogleService-info.plist via Xcode multiple times. Pretty sure that is not the issue.

Flutter doctor output
![Screenshot 2022-03-15 at 11 53 01 PM](https://user-images.githubusercontent.com/36451871/158445946-ed127374-65b4-447e-a4bc-7445be616ab3.png)

**Comment by darshankawar** [comment]
@mishrhm 
Based on the description I am not sure if this is related to flutterfire. Is it failing after you added any flutterfire plugin or without it too ?
Can you run `flutter run -v` and see if it gives you any logs that shows errors in it ?

For now, I am going ahead and closing this as this doesn't seem to be related to flutterfire. If so, write in comments with details and I'll reopen it.
If it is not related to flutterfire, you can open the issue in flutter/flutter repo.

**Comment by mishrhm** [comment]
My guess is it is related to FlutterFire because, sometimes it is getting stuck in the white screen for sometime when it says
"Configuring Firebase App..." in the console.

I suspect firebase_core plugin. Some of the forums I went mentioned to add GoogleService-info.plist using Xcode to the Runner folder, I tried that multiple times it still did not help.

**Comment by mishrhm** [comment]
@darshankawar 

When I ran the app with "flutter run -v" After Xcode build done. It is getting stuck at a certain line which Im attaching below.



**[  +73 ms] executing: xcrun simctl launch 5B56073A-A31F-4F73-8909-73C514468855 Com.CmtyHelp.CmtyHelp --enable-dart-profiling
--enable-checked-mode --verify-entry-points --observatory-port=0
[ +764 ms] Com.CmtyHelp.CmtyHelp: 91822
[        ] Waiting for observatory port to be available...**

It's not proceeding after this. The app gets installed in the simulator & launches with a white screen for a second & crashes without any error in the console.
