### ISSUE TITLE
🐛 [FlutterFire CLI] CLI doesn't find Firebase CLI

### ISSUE THREAD

**Issue by AdrKacz** [FirebaseExtended/flutterfire#8299]
## Bug report

> macOS Monterey - version 12.3 

*FlutterFire CLI* ask me to install *Firebase CLI* even if it is already installed and logged in my account.

### Steps to reproduce

```
>>> firebase --version
10.4.0
>>> firebase login
Already logged in as <my email address>
>>> flutterfire configure
i Found 0 Firebase projects.
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase --version 
ERROR: The FlutterFire CLI currently requires the official Firebase CLI to also be installed, see https://firebase.google.com/docs/cli#install_the_firebase_cli for how to install it.
```

### Expected behavior

I would expect `flutterfire configure` to find *Firebase CLI* and run. 

---

## Additional context

```
# ~/.zshrc
export PATH="$PATH:$HOME/development/flutter/bin"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$PATH":"$HOME/.pub-cache/bin"

alias firebase="`npm config get prefix`/bin/firebase"
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
>>> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

**Comment by darshankawar** [comment]
Please report CLI related issues in dedicated repo: https://github.com/invertase/flutterfire_cli/issues

https://firebase.flutter.dev/docs/cli/#reporting-an-issue
