### ISSUE TITLE
Failed to retrieve data from cache in offline mode - Flutter 2.8v

### ISSUE THREAD

**Issue by swarupa-v** [FirebaseExtended/flutterfire#8312]
In my application, when application is offline I insert data which I  assume it goes in cache. As soon as it is inserted I do  a fetch call to retrieve data but latest data inserted is not retrieved. This happens only in Android. Any help or suggestion would be appreciated.

**Comment by darshankawar** [comment]
@swarupa-v 
Its not clear which flutterfire plugin are you using for the use case you mentioned. Please provide the plugin version, `flutter doctor -v` and any error log you are seeing while carrying out the scenario.

**Comment by swarupa-v** [comment]
Following packages used: cloud_firestore: ^3.1.9
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_performance: ^0.8.0+7
Flutter vesrion:
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

The issue is when there is no internet connectivity and I insert data in cache and  after few seconds I try to retrieve that same inserted data from cache i dont get any values.

**Comment by darshankawar** [comment]
> The issue is when there is no internet connectivity and I insert data in cache and after few seconds I try to retrieve that same inserted data from cache i dont get any values.

Any use case related to internet or network is not an issue with flutterfire plugins, as they are wrappers around native firebase sdks and send / receive data through dart.
I suggest you to open this issue in respective native firebase sdk for further steps on resolution.
Closing from here.
