### ISSUE TITLE
[firebase_auth] Unlink user account

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#834]
After lookng at all the current open issues and since this is not implemented I am raising this issue for the firebase_auth plugin: https://github.com/flutter/plugins/tree/master/packages/firebase_auth

The functionality exists as part of firebase:
https://firebase.google.com/docs/auth/android/account-linking#unlink-an-auth-provider-from-a-user-account

Raised against the plugin: firebase_auth up to 0.5.8

**Comment by kroikie** [comment]
@aqwert

The issue at https://github.com/flutter/flutter/issues/17344 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @aqwert
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
