### ISSUE TITLE
[cloud_firestore] Use the FirebaseAnimatedList with query stream

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#836]
I'd like to suggest also using the FirebaseAnimatedList with the cloud firestore stream. 

It would be nice to share the UI components across both realtime database and cloud firestore. 

Then again, it might be better to make new ui widgets for the firestore plugin.

**Comment by kroikie** [comment]
@branflake2267

The issue at https://github.com/flutter/flutter/issues/17332 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @branflake2267
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
