### ISSUE TITLE
[firebase_core] 'await existingApp.options == options': is not true

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#838]
I have a base app and I added `firebase_core` and `firebase_database`.

I'm setting up some basic config

```dart
Future<void> main() async {
  final FirebaseApp app = await FirebaseApp.configure(
    name: 'test-0909...',
    options: Platform.isIOS
        ? const FirebaseOptions(
            googleAppID: '1:248...',
            gcmSenderID: '248...',
            databaseURL: 'https://est-0909...firebaseio.com',
          )
        : const FirebaseOptions(
            googleAppID: '1:248...',
            apiKey: 'AIza...',
            databaseURL: 'https://est-0909...firebaseio.com',
          ),
  );

  runApp(new MyApp(app: app));
}
```

error:

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'file:///Users/cristi/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.3/lib/src/firebase_app.dart': Failed assertion: line 70 pos 14: 'await existingApp.options == options': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      FirebaseApp.configure (file:///Users/cristi/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.3/lib/src/firebase_app.dart)
<asynchronous suspension>
#3      main (file:///Users/cristi/Work/delete_me/hello_world/lib/main.dart:10:45)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

If I try to debug the firebase_code file and print
```dart
    print(await existingApp.options);
    print(options);
```
I get

```
flutter: {APIKey: null, bundleID: com.test.test, clientID: null, trackingID: null, GCMSenderID: 248..., projectID: null, androidClientID: null, googleAppID: 1:248..., databaseURL: null, deepLinkURLScheme: null, storageBucket: null}

flutter: {APIKey: null, bundleID: null, clientID: null, trackingID: null, GCMSenderID: 248..., projectID: null, androidClientID: null, googleAppID: 1:248..., databaseURL: https://est-0909...firebaseio.com, deepLinkURLScheme: null, storageBucket: null}
```

Notice that they are no the same. The second one is my configuration. The first one is from.. i don't know where.

I could pass the `bundleID` to my params, but for some reason the `await existingApp.options` doesn't have the `databaseURL`.

Is there a super simple fix for this?

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)
```

**Comment by kroikie** [comment]
@patrioticcow

The issue at https://github.com/flutter/flutter/issues/17207 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @patrioticcow
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
