### ISSUE TITLE
[firebase_auth] on ios not using getTokenId refresh bool

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#847]
Refresh bool is hard coded to YES for ios. Android uses the bool as expected.

https://github.com/flutter/plugins/blob/master/packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
```swift
  } else if ([@"getIdToken" isEqualToString:call.method]) {
    [[FIRAuth auth].currentUser
        getIDTokenForcingRefresh:YES
                      completion:^(NSString *_Nullable token, NSError *_Nullable error) {
                        result(error != nil ? error.flutterError : token);
                      }];
```

**Comment by kroikie** [comment]
@bjon

The issue at https://github.com/flutter/flutter/issues/16807 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @bjon
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by AlexZaiats** [comment]
I'm facing the same issue:
`getIdToken(refresh: false` will not refresh token on Android, but will refresh for iOS.
Here is a simple fix for the issue:
https://github.com/FirebaseExtended/flutterfire/pull/1334

**Comment by iapicca** [comment]
Thank you for your contribution @AlexZaiats 
I see that your PR has been merged,
may I close this issue?

**Comment by AZaiats** [comment]
@iapicca sure, thanks
