### ISSUE TITLE
[firebase_auth] Feature request:  Link-To 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#850]
Right now, Firebase Auth allows linking accounts of two types:

- Username/Password:     `_auth.linkWithEmailAndPassword()`
- Google ID: `_auth.linkWithGoogleCredential()`

Account linking is used in a useful stories:

Story 1:
A user initialises the app, after initialisation the app gathers data from the user. This is not analytics data, but user-oriented data. Such as user preferences or data for a sign-up wizard. This can be stored in local preferences or in an anonymous login firebase session. Such a session may require linking to a real (not-anonymous) account later.

 Story 2:
A user uses Facebook sign-in but decides to abandon facebook, user wants to convert to another account type for sign-in, for example Twitter.

As Firebase can by default use to a multitude of auth methods (including Twitter/FaceBook/GitHub/Phone etc, see https://firebase.google.com/docs/auth/) it would be nice if all of these were supported.

Thanks!

**Comment by kroikie** [comment]
@Arno-Z

The issue at https://github.com/flutter/flutter/issues/16610 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This functionality is now available via the `linkWithCredential` method in the latest version of the plugin.
