### ISSUE TITLE
[cloud_firestore] Support for FirestoreSettings in cloud_firestore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#855]
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/FirestoreSettings?hl=da

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/16436 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
This has been implemented in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days.
