### ISSUE TITLE
[cloud_firestore] Support QueryListenOptions in cloud_firestore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#856]
https://firebase.google.com/docs/reference/js/firebase.firestore.QueryListenOptions

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/16434 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This is supported (API is now https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotListenOptions).
