### ISSUE TITLE
[cloud_firestore] Support QueryDocumentSnapshot in cloud_firestore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#857]
https://firebase.google.com/docs/reference/js/firebase.firestore.QueryDocumentSnapshot

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/16433 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, support for this has been added in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
