### ISSUE TITLE
[cloud_firestore] Support snapshot metadata in cloud_firestore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#858]
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/SnapshotMetadata

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/16432 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Closing - support was added in 0.12.9
