### ISSUE TITLE
[cloud_firestore] Support serverTimestampBehavior in cloud_firestore

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#859]
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Enums/ServerTimestampBehavior?authuser=1&hl=zh-cn

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/16431 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
This is now supported: https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/FieldValue/serverTimestamp.html
