### ISSUE TITLE
[📚] Cloud Firestore documentation

### ISSUE THREAD

**Issue by eduardoflorence** [FirebaseExtended/flutterfire#8620]
Does the link https://firebase.flutter.dev/docs/firestore/overview not redirect to a documentation that explains how to use Cloud Firestore in Flutter? It is redirecting to https://firebase.google.com/docs/firestore/quickstart
What happened to the old official documentation?

**Comment by kevinthecheung** [comment]
Hi! The Firestore docs are now integrated with the main/official docs. E.g., https://firebase.google.com/docs/firestore/manage-data/add-data#dart has examples for Dart/Flutter.

**Comment by eduardoflorence** [comment]
> Hi! The Firestore docs are now integrated with the main/official docs. E.g., https://firebase.google.com/docs/firestore/manage-data/add-data#dart has examples for Dart/Flutter.

Hi @kevinthecheung, I did a test now in this link, but there is no example for Dart, only for other languages.

**Comment by kevinthecheung** [comment]
Oh, hmm... this is what I see:

![image](https://user-images.githubusercontent.com/11839002/167677384-5697efc3-820e-47ad-b634-1c3b9d5f8445.png)

Are you maybe using one of the translations? Those can lag behind a little.

**Comment by eduardoflorence** [comment]
Sorry @kevinthecheung, I was reading the documentation in Portuguese and it is not yet available in this language, only in English.

![image](https://user-images.githubusercontent.com/9120528/167690213-9f39cab9-400f-499c-94a4-b6fac6b0f0aa.png)
