### ISSUE TITLE
FlutterFire/firebase-dart abstraction

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#869]
It would be great if FlutterFire could collaborate with firebase-dart to agree upon common interfaces, in which both packages implement.

I'm working on a project where I am building a web app and a flutter app, and I am trying to abstract the common business logic into another library for both apps to consume. As it stands right now I have to implement a lot of things twice, once for web and once for flutter, and the logic is almost the exact same each time.

See the companion issue at [firebase-dart](https://github.com/firebase/firebase-dart/issues/170)

**Comment by kroikie** [comment]
@davidmarne

The issue at https://github.com/flutter/flutter/issues/16186 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by collinjackson** [comment]
This has been addressed by FlutterFire being the common interface and using the firebase-dart for the web implementation.
