### ISSUE TITLE
Delete Firebase Auth User

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#875]
With the latest version of Firebase Auth (0.5.2), it is impossible to delete a user.

Other Firebase Auth libraries (such as the one for Web) have a `user.delete()` instance method, which is missing from the Flutter implementation.

I would like to do a PR, although I do not have a iOS dev enviroment setup. I'll see if I can set one up shortly, but I think this could be a pretty trivial PR for anyone else to do!

**Comment by Abhishek-kumar09** [comment]
FireBase Authenticated user can be deleted : [StackOverFlow](https://stackoverflow.com/a/58780768/11966205),this just only deletes the user from FireBase Authentication List.

**Comment by collinjackson** [comment]
@Abhishek-kumar09 I'm not sure I understand, can you clarify what you're trying to do that isn't covered by the existing delete method?

https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseUser/delete.html

If you want to open a PR for the Android side I can take a look

**Comment by Abhishek-kumar09** [comment]
hey! @collinjackson I was trying to do login authentication after the user has signed up and returned to the app once again. After the user uninstalled the app and tries to install again It is giving platform exception that 

>  PlatformException(FirebaseException, User has already been linked to the given provider., null)
thus failing to signIn again.How can I overcome this problem. any help is admired.

**Comment by kroikie** [comment]
@Abhishek-kumar09 uninstalling the app does not delete the account; so if you are trying to recreate the account when the app is reinstalled then the error makes sense.

If you just uninstall the app then on reinstall the user should just be signed in without recreating or relinking the user with the provider.

**Comment by bean5** [comment]
I've run into strange cases related to this, but I might have done something wrong. In my case, the user was anonymous, then not verified, but soon after logged out, deciding not to complete the process. I called delete, but it didn't clean up things like signOut does.

So when they tried to create a user with that same email address, it all went awry.

**Comment by Ehesp** [comment]
Closing the issue, the `delete` method is implemented & looks to be working as expected.
