### ISSUE TITLE
[firebase_storage] Add notes on installing firebase to every firebase package

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#879]
I was trying to install firebase via the firebase_storage package and had difficulties, later i found following the instructions at https://pub.dartlang.org/packages/firebase_auth in order to properly install it.

Apologies if this issue isn't made at the right repo, but I'd like to suggest we add notes to each firebase package that people need to go through this process for installing and setting up firebase for the 1st time.

**Comment by kroikie** [comment]
@acidjazz

The issue at https://github.com/flutter/flutter/issues/15805 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the Auth, Core & Firestore plugins as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. 

As part of this we introduced a [new documentation site](https://firebase.flutter.dev) which should has a lot of new documentation that should cover this issue & others in general. If you spot any issues on the documentation or anything missing then please raise a new GitHub issue, or better yet suggest a change via a Pull Request (there's a 'Edit this page' button at the bottom of every page on the docs).

Additionally, for help migrating to these new plugins I'd recommend checking out the migration guide: https://firebase.flutter.dev/docs/migration
