### ISSUE TITLE
[firebase_database] await operations not working when offline. (even when using local persistence enabled)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#885]
## Steps to Reproduce

1) using firebase_database plugin version 0.4.0
2) using code
```dart
// Opening database and setting local persistence (keep sync)
_database = FirebaseDatabase.instance;
_database.setPersistenceEnabled(true);
_database.setPersistenceCacheSizeBytes(10000000);
_myReference = _database.reference().child('users/${user.uid}');
_myReference.keepSynced(true);
```
**When online (Wifi connectivity)**
```dart
var snapshot = await _myReference.once();
print(snapshot.value);
```

await works. Once() returns and print statement is called.

**When offline (NO Wifi connectivity)**
**IMPORTANT: When there is no connectivity before launching the mobile app**
If the database was initialized prior to losing connectivity, then the await calls work as expected.
```dart
var snapshot = await _myReference.once();
print(snapshot.value); <=== NEVER CALLED
```
await does not work. Once() never returns and print statement is never called.

## Expected Behavior

Offline support in firebase_database should work when user has no connectivity prior to opening the mobile app.

## Logs

Not applicable. There are no logs that I can see which would help debugging here.
No exceptions, no stack trace from Flutter or anything else.

## Flutter Doctor
```
[√] Flutter (Channel dev, v0.1.7, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 0.1.7 at C:\Workspace_Flutter\flutter
    • Framework revision 3b84503403 (3 weeks ago), 2018-02-26 20:11:11 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\stephanebi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • H1621 • W7TDU16827002676 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```
**IT's OK, not using VS Code with Flutter.**

**Comment by kroikie** [comment]
@StephaneBischoff

The issue at https://github.com/flutter/flutter/issues/15653 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by robindijkhof** [comment]
> @StephaneBischoff
> 
> The issue at [flutter/flutter#15653](https://github.com/flutter/flutter/issues/15653) has been closed and moved here. Future collaboration on this issue will be done here.

Are you sure? It is conflicting with this comment: https://github.com/flutter/flutter/issues/15653#issuecomment-541448894

**Comment by robindijkhof** [comment]
@kroikie any update on this?

**Comment by roopa1712** [comment]
hello, can you please let us know what is the status, as this is open since a year?
Any resolution over this issue?

**Comment by yemyatthu1990** [comment]
It's still not working as a true offline cache. I ended up making a local db for this case.

**Comment by Salakar** [comment]
I'm not sure what else to suggest here. FlutterFire is just a wrapper to the official Android/iOS/Web Firebase SDKs, any network related operations and issues aren't likely to be an issue with FlutterFire. I'd suggest if this is an issue for anyone then raising an issue on the official Firebase SDK repository for the underlying platform you're seeing this issue on, e.g. the Firebase iOS SDK GitHub repository.
