### ISSUE TITLE
[firebase_messaging] Does getToken return invalid value for iOS?

### ISSUE THREAD

**Issue by bambinoua** [FirebaseExtended/flutterfire#89]
We use our iPhone as debug device. There is a listener for onTokenRefresh stream to see what token is used. As we see it looks like token is invalid for iOS. As they know the iOS push token contains 64 hedecimal symbols. But in our case we see "a-la android" string with length about 152 symbols.

The source code is simple as it can be:
final _messaging = FirebaseMessaging();
_messaging.onTokenRefresh.listen((token) { print(token); });
final token = await _messaging.getToken();

Did we do something wrong?

**Comment by kroikie** [comment]
@bambinoua please use the template when submitting bugs.

What error are you seeing when you call `getToken()`? Please add a stack trace.
