### ISSUE TITLE
[firebase_database] FirebaseAnimatedList should have a 'emptyListChild'

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#892]
## Current behavior

When using the firebaseAnimatedList for user generated content, the first time the user loads the application and there's no content, is just not optimal to load an empty container.

## Expected behavior

The ability to show a custom widget when the list is empty

**Comment by kroikie** [comment]
@Panthro

The issue at https://github.com/flutter/flutter/issues/15480 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by devroldy** [comment]
Any progress on this? There needs to be a custom widget for when FirebaseAnimatedList has no value in the list
