### ISSUE TITLE
Please add support for Crashlytics

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#903]
In #9592 there's a request for adding Crashlytics, but it was blocked by an absence of crash reporting support in Flutter. Now that there are ways to intercept errors, it should be possible to add Crashlytics / Firebase error reporting.

**Comment by daohoangson** [comment]
Did you close this issue by mistake @kroikie?

**Comment by kroikie** [comment]
@daohoangson @MisterJimson 

There is support for Crashlytics on Flutter, which is why this issue has been marked as closed.

Fatal error submission is not yet available, we are using https://github.com/FirebaseExtended/flutterfire/issues/398 to track that particular feature.
