### ISSUE TITLE
[cloud_firestore] Cloud Firestore Plugin missing documentation

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#906]
I am having trouble to find the necessary documentation for the use of document references in the Cloud Firestore plugin for Flutter. 
For the problem in question I am trying to pass a Cloud Firesore document reference from the Home widget to a VideoView widget in order to query the necessary data from Cloud Firestore  in the VideoView widget.

Is this possible with the Cloud Firestore plugin right now and if so, is any documentation available to follow along?

**Comment by kroikie** [comment]
@stemuk

The issue at https://github.com/flutter/flutter/issues/14324 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) (we have a new documentation hub with extensive docs 🎉) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
