### ISSUE TITLE
Implement FlutterFire Invites plugin 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#912]
Our application has a need for the Invites module from Firebase (https://firebase.google.com/docs/invites/).  It looks to have a dependency on firebase dynamic links which does not appear to be implemented either.  Any chance to get this work prioritized.  Seems like most people using firebase would need the invites since a primary use of a realtime database is collaborative use.  

Thank you so much for the flutter framework.  It's exactly what I've been hoping for.

**Comment by kroikie** [comment]
@tobytraylor

The issue at https://github.com/flutter/flutter/issues/14044 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by erluxman** [comment]
Any progress on this plugin?

**Comment by kroikie** [comment]
Firebase invites has been [deprecated](https://firebase.google.com/docs/invites) so we will not be implementing a plugin for it. Dynamic links should provide the necessary functionality.
