### ISSUE TITLE
RouteObserver calls didPop too early

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#916]
`RouteObserver` should call `_listeners[route]?.didPop()` in `unsubscribe` instead of `didPop`. This likely affects the accuracy of the Firebase Analytics plugin; it could report that routes have been popped when they are still visible.

More context: https://github.com/flutter/flutter/pull/11236/files/40240cf80e55970246b77f651666c4f33e936b43#r159754696

/cc @weisong0 @Hixie

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/13919 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release.
