### ISSUE TITLE
google_sign_in 1.0.1 and firebase_auth 0.3.2: DexException

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#925]
Using the latest version of `google_sign_in` (`1.0.1`) in `pubspec.yaml`, together with `classpath 'com.google.gms:google-services:3.1.0'` in the root level gradle file and `apply plugin: 'com.google.gms.google-services'` on the last level of the app gradle file, results in:

```
Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzdld;

```

 

Version 0.3.1 does not have this issue.

**Comment by kroikie** [comment]
@jmnyv

The issue at https://github.com/flutter/flutter/issues/13609 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
@jmnyv is the issue still relevant?

**Comment by iapicca** [comment]
Hi @jmnyv
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/215)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
