### ISSUE TITLE
[cloud_firestore] does not like underscore in iOS bundle id

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#928]
Following instructions in:
[Flutter Firebase codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase/#4)

I named my project `friendly_chat`.

The problem is that Dart packages need to use the `snake_case` naming convention. When the iOS bundle name is generated, it uses the project name unchanged. Copying and pasting that into the Firebase console won't work because Firebase does not accept the underscore.

**Comment by kroikie** [comment]
@stevemessick

The issue at https://github.com/flutter/flutter/issues/13518 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi 
does this proposed [solution ](https://github.com/flutter/flutter/issues/13518#issuecomment-351910058) work for you?

**Comment by stevemessick** [comment]
> does this proposed solution work for you?

Hard to say because I'm not sure what the proposal is. Some detail about what is changing might help.

**Comment by stevemessick** [comment]
> does this proposed solution work for you?

Hard to say because I don't know what the proposal is. Some detail about what changes are being made might help.

**Comment by kroikie** [comment]
@stevemessick as identified in the [original issue](https://github.com/flutter/flutter/issues/13518#issuecomment-351910058), `_` are not allowed in bundle IDs. Replacing them with dashes should resolve your issue.
