### ISSUE TITLE
[Firebase Analytics] Flutter Gradle error after installing firebase_analytics: ^5.0.1

### ISSUE THREAD

**Issue by lintoncaldecott** [FirebaseExtended/flutterfire#93]
After installation of  firebase_analytics: ^5.0.1 I get 

```
FAILURE: Build failed with an exception.
Build file '/Users/<user>/Desktop/odbc/android/app/build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'
```
add to pubspec.yaml
`dependencies:
  firebase_analytics: ^5.0.1`

add to android/build.gradle
`    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:3.2.1'  // Google Services plugin
    }`
`apply plugin: 'com.google.gms.google-services'  `

add to android/app/build.gradle
`apply plugin: 'com.google.gms.google-services'  `

On trying to debug the application on a virtual pixel 3 I get the error listed above.

**Comment by pablomdd** [comment]
I have the same issue. Have you tried to disable Analytics? Or, stepping down the version of cloud firestore?

**Comment by lintoncaldecott** [comment]
> I have the same issue. Have you tried to disable Analytics? Or, stepping down the version of cloud firestore?

If you mean this version `firebase_analytics: ` then I have tried 5.0.1 and 4.0.0

**Comment by Salakar** [comment]
Given the age of this issue and that Analytics has had many releases since; I'm going to close this issue in favour of trying the latest release.
