### ISSUE TITLE
[plugin] firebase version update

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#934]
Appcompat version update required:

The latest version:
```
    compile 'com.google.firebase:firebase-core:11.6.0'
    compile 'com.google.firebase:firebase-messaging:11.6.0'
    compile 'com.google.firebase:firebase-crash:11.6.0'
```

Current (not functional): https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/build.gradle#L32
```
        compile 'com.google.firebase:firebase-core:11.4.+'
        compile 'com.google.firebase:firebase-messaging:11.4.+'
```

**Comment by kroikie** [comment]
@JFixby

The issue at https://github.com/flutter/flutter/issues/13184 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
The issue seems far outdated, closing it.
