### ISSUE TITLE
[firebase_auth] signInWithCredentials exceptions reported as uncaught in VSCode

### ISSUE THREAD

**Issue by nstosic-toptal** [FirebaseExtended/flutterfire#94]
Hi everyone,

I'm running `flutter channel stable` (1.7.8+hotfix.4) and VSCode Version: 1.38.0. When running my app (which depends on `firebase_auth` and other `flutterfire` packages) in debug mode, VSCode debugger pauses execution on `.signInWithCredential` call if an exception occurs even though the exception is handled. When unpausing the execution the app behaves as expected and correct error handling logic is triggered.

I'm not sure if this should be addressed by VSCode debugger team or by flutterfire, just thought I'd post it here.

Also, here's a screenshot from the debugging session as reference.

<img width="1135" alt="Screen Shot 2019-09-05 at 8 02 23 PM" src="https://user-images.githubusercontent.com/50679594/64367700-fb92b880-d018-11e9-9bde-513850276d2f.png">

**Comment by jayvasantjv** [comment]
AuthResult authResult = (await _auth.signInWithCredential(credential)).user

**Comment by jayvasantjv** [comment]
@BondarenkoStas This issue can be closed now.
