### ISSUE TITLE
Troubleshoot Firestore deletion behavior and add more tests

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#941]
@pulyaevskiy had some additional plans for the Firestore plugin on flutter/plugins#258

> I've been trying to nail down this weird behavior with deleting items and it seems to be that this is an issue with underlying platform SDKs... but I'm not sure.
> 
> In short: deleting a document (while subscribed to a Query matching this document) results in following sequence of snapshot events with DocumentChanges:
> 
> 1. DocumentChangeType.removed with `hasPendingWrites: false` and `isFromCache: false` - OK
> 2. DocumentChangeType.added with `hasPendingWrites: false` and `isFromCache: true` - ???
> 3. DocumentChangeType.removed with `hasPendingWrites: false` and `isFromCache: false` - ???
> 
> Tested with `AnimatedList` and `Dismissible` items: deleted item appears in the list for a second and disappears again.
> 
> Wondering if anyone knows what am I doing wrong here?
> 
> I will be pushing some more changes this week in regards to SnapshotMetadata and adding some more tests.

**Comment by kroikie** [comment]
@collinjackson

The issue at https://github.com/flutter/flutter/issues/13028 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/flutter/issues/13028#issuecomment-544594576

**Comment by xnio94** [comment]
repost "I'm not sure if this is the problem I'm running into but I would really appreciate some guidance. I have a FirebaseAnimatedList whose children are wrapped in Dismissible. Everything works great but I get the 'A dismissed Dismissible widget is still part of the tree.' error and I haven't found any way to force an item off FirebaseAnimatedList. (This is for firebase_database)"
