### ISSUE TITLE
Firebase database exception on permission denied

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#942]
## Steps to Reproduce

In Firebase when I access a path where I don't have sufficient permissions,
I get

```
[  +43 ms] W/RepoOperation(10726): setValue at /test_db/joinRequestCreate/hFWyZYmtgocsWs69TnpHXuEbBRv1/-Kyz7h7zFCbqxZKNrdOD failed: DatabaseError: Permission denied
```
as log output, but that's easy to miss. 

I think there should be a way to get an exception on the client side for permission denied

firebase_database plugin version 0.0.14

**Comment by kroikie** [comment]
@zoechi

The issue at https://github.com/flutter/flutter/issues/13027 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by syonip** [comment]
I'm also facing this, any progress?

**Comment by Salakar** [comment]
Given the age and inactivity of this issue I'm going to close this issue in favour of trying the latest release. If this is still a problem then raising a new GitHub issue with up to date information and example/reproducible code snippets is the way forward. Thanks
