### ISSUE TITLE
[firebase_auth] Is there any way to implement forgot password and send verification mail  firebase

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#957]
Hi everyone,
Is there any way to implement forgot password and sending verification mail through firebase in flutter.

**Comment by kroikie** [comment]
@vuppalasivakumar

The issue at https://github.com/flutter/flutter/issues/12459 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by fxsalazar** [comment]
Isn't done this way:
```dart
final FirebaseAuth _firebaseAuth;
_firebaseAuth.sendPasswordResetEmail(email: '[email]');
(await _firebaseAuth.currentUser()).sendEmailVerification();
```

**Comment by kirstywilliams** [comment]
Closing as not a bug.
