### ISSUE TITLE
Firebase Auth implementation for signInWithCustomToken.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#964]
I currently only see the following implemented sign in functions for Firebase Auth:

- signInAnonymously
- signInFacebook
- signInGoogle
- signInWithEmailAndPassword

Firebase is a retro fit for our legacy app and so we are using the custom token SDK on our Python backend.

How hard would it be to implement `signInWithCustomToken()`?

**Comment by HeidernBuffalo** [comment]
@kroikie why is this closed?  Any way we can do signInWithCustomToken()?

**Comment by SEGVeenstra** [comment]
> @kroikie why is this closed? Any way we can do signInWithCustomToken()?

I would think so since the signInwithCustomToken() method exists on an auth instance

**Comment by 5hanth** [comment]
@SEGVeenstra the method exists on auth instance because of this
 ```.dart
Future<PlatformAuthResult> signInWithCustomToken(String app, String token) {
    throw UnimplementedError('signInWithCustomToken() is not implemented');
  }
```

**Comment by JurgenJocubeit** [comment]
Still wondering why this issue is closed? Is there another way to achieve this? My flutter app needs a way to sign in without using any of the existing providers.
