### ISSUE TITLE
[firebase_admob] Users would like to display Native Ads in their Flutter UI

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#968]
Both Firebase (AdMob) and Facebook support a "Native Ads" format:

* https://developers.google.com/admob/android/native
* https://developers.facebook.com/docs/audience-network/native-ads/

Native ads are rendered inline with the app's content, with rendering and formatting (colors, fonts) controlled by the app itself.

**Comment by kroikie** [comment]
@sethladd

The issue at https://github.com/flutter/flutter/issues/12114 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by serendipity1004** [comment]
Can we get an idea of what the priority is for this issue? It might be a critical factor to decide whether to use Flutter or not for some people.

**Comment by hundeva** [comment]
Any updates for this?

**Comment by letiagoalves** [comment]
Is this being tackled?

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
