### ISSUE TITLE
[firebase_admob] IOS banner is on the top

### ISSUE THREAD

**Issue by sunjianan9900** [FirebaseExtended/flutterfire#97]
firebase_admob 0.9.0+7

Normally on android , banner is on the bottom
But it is showing on the top of APP IN IOS

**Expected behavior**

**Additional context**

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/pull/45

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/21634

**Comment by talent-apps** [comment]
The PR https://github.com/FirebaseExtended/flutterfire/pull/45 seems to fix this issue, but it is not merged for over 4 months (!!) despite being a one liner.
Does this plugin has any owners on the flutter team who can review  and merge it please?

**Comment by iapicca** [comment]
@bparrishMines

**Comment by danieeelfc** [comment]
> The PR #45 seems to fix this issue, but it is not merged for over 4 months (!!) despite being a one liner.
> Does this plugin has any owners on the flutter team who can review and merge it please?

+1 for this

**Comment by blasten** [comment]
If you can still repro this issue with the latest version, could you please provide a code snippet that reproduces this issue?
