### ISSUE TITLE
firebase_auth fails silently if SHA Fingerprint is not added

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#979]
## Steps to Reproduce

1. Attempt to use firebase_auth without first adding the android key to the firebase fingerprints list.
2. Notice that is silently fails with no indicative warning.

I only consider this an issue since it's not mentioned in the setup docs and it took me quite a bit to figure out.

**Comment by kroikie** [comment]
@pauldemarco

The issue at https://github.com/flutter/flutter/issues/11277 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Consolidating this under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format - which should help with this no longer failing silently.
