### ISSUE TITLE
Firebase Auth uses or overrides a deprecated API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#984]
When compiling an app with the Firebase Auth plugin, I get the following warning:

```
Note: C:\Users\goderbauer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.1.1\android\src\main\java\io\flutter\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
```

We should probably move to a non-deprecated API.

/cc @collinjackson

**Comment by mojason-81** [comment]
Is there some fix I can apply for this that's not shown here or in #17976 or #815 ?  I'm getting this error on a fresh flutter app.

firebase_auth 0.15.3+1
flutter 1.13.6
dart 2.8.0
openjdk 11.0.5 (could this be the issue?)
zorin OS 15 (Ubuntu 18.04)
