### ISSUE TITLE
GeoFire Support (Firebase)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#985]
Manually geosorting with Firebase is a pain. GeoFire would be a convenient tool to have. Perhaps we can add this plugin to FlutterFire!

**Comment by kroikie** [comment]
@bramvbilsen

The issue at https://github.com/flutter/flutter/issues/11121 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Closing this issue. 

This functionality would be better be placed within a 3rd party library, outside of the scope of FlutterFire.
