### ISSUE TITLE
Implement Transactions for Firebase Database

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#987]
## Steps to Reproduce

`database.ref('someRef').transaction` isn't currently implemented.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Dilmagcs** [comment]
???

**Comment by Dilmagcs** [comment]
final databaseReference = FirebaseDatabase.instance.reference();
    FirebaseUser user;
    String title;
    String Description;
    String mountainKey;
    String info;
    String usersAdd;
    String cont;
    String _kTestKey = 'Hello';
    String _kTestValue = 'world!';

    DatabaseReference _counterRef;
    EjecutarVotarPageState({Key key, @required this.title, @required this.Description, @required this.mountainKey, @required this.info});

    Future<void> _increment() async {
      // Increment counter in transaction.
      final TransactionResult transactionResult =
      await _counterRef.runTransaction((MutableData mutableData) async {
        mutableData.value = (mutableData.value ?? 0) + 1;
        return mutableData;
      });

      if (transactionResult.committed) {

      } else {
        print('Transaction not committed.');
        if (transactionResult.error != null) {
          print(transactionResult.error.message);
        }
      }
    }
     void initState(){
      super.initState();
      setUpTodosPage();
      _counterRef =FirebaseDatabase.instance
          .reference().child('ckItjKegbYOCsPN10qSYizE3k7D3').child('Votaciones').child(mountainKey).child("Si");
      _counterRef.keepSynced(true);
    }

    void setUpTodosPage() async {
      FirebaseUser user = await FirebaseAuth.instance.currentUser();
      setState(() {
        usersAdd = user.uid;

      });
    }


I/flutter (13994): Transaction not committed.
I/flutter (13994): User code called from the Firebase Database runloop threw an exception:
I/flutter (13994): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: FirebaseDatabaseWorker
I/flutter (13994): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
I/flutter (13994): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:683)
I/flutter (13994): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:77)
I/flutter (13994): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:379)
I/flutter (13994): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:190)
I/flutter (13994): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
I/flutter (13994): 	at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin$1.doTransaction(FirebaseDatabasePlugin.java:345)
I/flutter (13994): 	at com.google.android.gms.internal.firebase_database.zzck.zza(Unknown Source)
I/flutter (13994): 	at com.google.firebase.database.zzf.run(Unknown Source)
I/flutter (13994): 	at java.util.concurrent.Executors$RunnableAdapter.ca
